// Kategorie 1 – Škádlení a předehra (dávka c)
// Témata: svlékání, polibky s pravidly, škádlení přes oblečení, hudba a tanec, telefon.
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 1,

  male: [
    "Kus za minutu: Svlékej ji tempem jeden kus za minutu a mezi kusy ji polib na místo, které jsi právě odhalil. Cíl: tři kusy, tři polibky.|180|svlekani",
    "Zastavit nad prsy: Pomalu jí vyhrň tričko až nad prsa a tam přestaň. Cíl: dál se nedostaneš, dokud tě o to sama nepoprosí.|90|svlekani",
    "Zuby a nic víc: Svlékni jí jeden kus oblečení jen zuby, bez pomoci rukou. Cíl: sundat to, ať to trvá jakkoli.|180|svlekani",
    "Knoflík a polibek: Rozepínej jí knoflíky jeden po druhém a po každém ji polib na odhalené místo. Cíl: rozepnout všechny a u žádného nespěchat.|120|svlekani",
    "Bez jediného doteku: Sundej jí kalhotky tak, aby se tě ani jednou nedotkla. Když po tobě sáhne, začínáš znovu. Cíl: zvládnout to napoprvé.|90|svlekani",
    "Ty jen koukáš: Postav ji před sebe a nech ji, ať se svlékne sama. Ty sedíš a nesmíš mluvit. Cíl: tři minuty ticha, ani jedno slovo.|180|tanec",
    "Celá písnička na krku: Pusť jednu písničku a po celou dobu ji líbej na krk. Cíl: přestat přesně v okamžiku, kdy dozní poslední tón.|180|stoje_zezadu",
    "Slyší jen hudbu: Dej jí do uší sluchátka se svou oblíbenou písničkou a celou dobu ji svlékej. Cíl: stihnout to do konce písničky a nepromluvit.|180|svlekani",
    "Tanec o dvou pravidlech: Tancujte spolu pomalu, ty ji smíš držet jen za boky a nesmíš ji políbit. Cíl: vydržet celou písničku.|180|objeti",
    "Deset míst: Polib ji na deset různých míst a ani jedno nesmí být na ústech. Ona počítá nahlas. Cíl: dojít k desítce bez jediného opakování.|120",
    "Jen spodní ret: Líbej ji tak, že se dotkneš vždycky jen jejího spodního rtu. Jazyk je zakázaný. Cíl: celá minuta a ani jednou nesklouznout jinam.|60|objeti",
    "Polibek na tři doby: Nejdřív jen rty, pak s jazykem, pak jí kousni do rtu. Mezi tím vždycky počkej pět vteřin. Cíl: ať si o další řekne sama.|90|objeti",
    "Ruce na zdi: Přitiskni ji ke zdi a líbej ji, ruce máš opřené o zeď, ne na ní. Cíl: nepřestat, dokud se jí nepodlomí kolena.|120|zed",
    "Jen přes látku: Líbej ji všude tam, kde má oblečení, a nikdy na holou kůži. Cíl: dvě minuty a ani jeden polibek na kůži.|120",
    "Tři minuty jen ústa: Posaď si ji obkročmo na klín a jenom se líbejte. Nic jiného. Cíl: tři minuty, při kterých se ani jeden nepokusí o víc.|180|klin_celem",
    "Kalhotky zůstávají: Dráždi ji prsty přes kalhotky, sundat je nesmíš. Cíl: tři minuty – a jestli si je stáhne sama, vyhrála.|180",
    "Jen přes látku: Hlaď ji a dráždi přes spodní prádlo tak dlouho, až ho bude chtít sundat. Cíl: ať si ho sundá sama.|180",
    "Hranice nad pasem: Vsuň jí ruku pod tričko a zastav se hned nad pasem. Cíl: nedostat se výš, dokud ti to sama nedovolí.|90",
    "Po paži nahoru: Polib ji do dlaně, pak do zápěstí a pokračuj vzhůru po vnitřní straně paže až k rameni. Cíl: deset polibků na každé ruce.|90",
    "Ruce nehrají: Lehni si k ní a celou minutu ji líbej jenom na krk a za ucho. Cíl: nechat ruce ležet a nepohnout jimi ani jednou.|60|vedle_ona_lezi",
    "Kolena a stehna: Nech ji sednout na kraj postele, klekni si před ni a líbej jí kolena a stehna. Cíl: dvě minuty a ani jednou výš.|120|oral_vsede",
    "Výměna kusu: Sundej jí jeden kus oblečení a ten samý si obleč sám. Cíl: zůstat tak až do konce úkolu a tvářit se úplně normálně.|60|svlekani",
    "Fotka na přání: Vyfoť ji telefonem tak, jak se jí to bude líbit, a ukaž jí to. Pak fotku hned smažte. Cíl: ať se líbí ona sama sobě.|180",
    "Zpráva přes pokoj: Napiš jí z druhého konce pokoje zprávu, co jí uděláš. Nahlas neřekneš nic. Cíl: tři zprávy a ani jedno slovo.|90",
    "Hlasovka do sluchátek: Nahraj jí hlasovku, co s ní chceš dělat, a nech ji, ať si ji poslechne ve sluchátkách. Cíl: dívat se jí u toho do očí.|120",
    "Obkreslování poslepu: Pusť jí do sluchátek písničku a prstem jí obkresluj obrysy těla. Cíl: obkreslit ji celou, než písnička dohraje, a nepromluvit.|180|vedle_ona_lezi",
    "Odpočet od deseti: Odpočítávej nahlas od deseti a při každém čísle jí sundej nebo posuň jeden kus oblečení. Cíl: dojít k nule a nezrychlit.|90|svlekani",
    "Poslední kus určuje ona: Svlékni se až na jeden kus a postav se před ni. Cíl: nechat na ní, kdy padne i ten, a do té doby se nehnout.|60|tanec",
    "Rozehřátí zezadu: Obejmi ji zezadu, líbej ji na šíji a rukama jí zvolna zajeď pod tričko. Cíl: ať se o tebe sama opře.|120|stoje_zezadu",
    "Rozepnout napoprvé: Líbej ji a u toho jí rozepínej podprsenku. Cíl: zvládnout to na první pokus – pak si můžeš říct o odměnu.|90|svlekani",
    "Až k lemu prádla: Táhni jí špičkou prstu od krku dolů a zastav se přesně tam, kde začíná prádlo. Cíl: pět cest a ani jednou přes lem.|60|vedle_ona_lezi",
    "Zakázaná místa: Dotýkej se jí kdekoli, jen ne na prsou a mezi nohama. Tři minuty. Cíl: ať ti ruku sama posune tam, kam chce.|180|vedle_ona_lezi",
    "Punčochy a kotníky: Klekni si před ni a pomalu jí stahuj punčochy nebo ponožky. Cíl: u každého kotníku se zastavit a políbit ho.|90",
    "Zátylek pod vlasy: Zezadu jí zvedni vlasy a líbej ji na odhalený zátylek. Cíl: nepřestat, dokud se nezachvěje.|60|stoje_zezadu",
    "Jen jedno ramínko: Líbej ji na rameno a pomalu jí shrnuj ramínko. Druhé nech být. Cíl: celá minuta jen na jedné straně.|60|svlekani",
    "Nikdy až nahoru: Posaď si ji na klín zády k sobě a hlaď ji po stehnech nahoru a dolů. Cíl: tři minuty a ani jednou nedojet až nahoru.|180|klin_zady",
    "Tanec jednou rukou: Tancujte spolu, ale ty ji smíš držet jen jednou rukou, druhou máš za zády. Cíl: dvě minuty a ruku zezadu nevyndat.|120|objeti",
    "Šeptem a rukama: Pusť hudbu, staň si za ni a veď ji v pohybu rukama na jejích bocích. Nesmíš promluvit. Cíl: ať se o tebe opře sama.|180|stoje_zezadu",
    "Polibek za kus: Polib ji na ústa a při každém dalším polibku jí sundej jeden kus oblečení. Cíl: dostat se k prádlu do pěti polibků.|120|svlekani",
    "Všude, jen ne na ústa: Přejeď jí rty po celém obličeji, ale ústům se vyhni. Cíl: celá minuta a ani jednou nepolíbit ústa.|60|objeti",
    "Ruce mimo hru: Lehni si na záda, posaď si ji na sebe a nech ji líbat tě, jak chce. Cíl: tři minuty a ty nesmíš hnout rukama.|180|ona_nahore",
    "Co tě vzrušuje: Ukaž jí na telefonu fotku nebo scénu, která tě vzrušuje, a popiš jí, co přesně na tom je. Cíl: tři konkrétní detaily.|120",
    "Ruce nad hlavou u zdi: Vezmi jí ruce, přitiskni je nad hlavu ke zdi a líbej ji. Cíl: nepustit ji, dokud se nezačne kroutit.|90|zed",
    "Doteky podle hudby: Nech ji vybrat písničku a dotýkej se jí přesně v tempu, které zrovna hraje. Cíl: dojet to až do konce a tempo nesplést.|180",
    "Pomalá cesta: Začni polibkem na čelo a postupně se propolibkuj až k pasu. Nesmíš přeskakovat. Cíl: nezrychlit ani jednou.|180|vedle_ona_lezi",
    "Podprsenka bez doteku: Sundej jí podprsenku a nedotkni se jí přitom prsou. Ani omylem. Cíl: zvládnout to napoprvé a hned ruce pryč.|60|svlekani",
    "Vyhrň jí sukni nebo stáhni kalhoty jen tak nízko, aby to bylo ještě víc dráždivé než úplně.|60",
    "Oblíkni ji do svého trička a pak jí ho zase pomalu sundávej.|120|svlekani",
    "Líbej ji na bříško a u pupíku se zastav. Pak se vrať nahoru a začni znovu.|90|vedle_ona_lezi",
    "Lehni si za ni na lžičku a celou dobu ji líbej na rameno. Ruce nech na jejích bocích.|120|lzicka",
    "Tři minuty bez rukou: Dotýkej se jí jen rty, nosem a dechem. Ruce máš celou dobu za zády. Cíl: nepoužít ruce ani jednou.|180",
    "Sedni si naproti ní a nech ji, ať se svléká přesně tak pomalu, jak jí řekneš.|180|tanec",
    "Přitáhni si ji k sobě za pásek nebo lem kalhot a chvíli ji tak drž. Nic víc.|45|objeti",
    "Polib ji do ohbí loktů a do podkolení. Na dvou nečekaných místech.|60",
    "Napiš jí prstem na břicho slovo a nech ji hádat. Když uhodne, dostane polibek, kam si řekne.|90|vedle_ona_lezi",
    "Seber jí telefon a napiš si sám sobě zprávu, co ti dneska udělá. Pak jí ji ukaž.|90",
    "Tři pokusy: Ona si smí zkusit sundat tvoje oblečení, ale jen tři kusy. Zbytek si necháš. Cíl: ať dobře vybere.|90|svlekani",
    "Polož ji na záda, klekni si nad ni a líbej ji shora dolů. Nikam nespěchej.|180|misionar",
    "Stáhni jí kalhotky zuby a pak je nech ležet přesně tam, kam spadly.|90|svlekani",
    "Vezmi jí ruku a nech ji, ať si sama ukáže, kde chce být políbená. A polib to.|60",
    "Zvedni ji do náruče, drž ji a líbej ji, dokud neřekneš dost.|90|zvednuta",
    "Sedni si za ni, rozepni jí podprsenku jednou rukou a pak ruce sundej. Ať si ji svlékne sama.|60|masaz_vsede",
    "Škádlení očima: Svlékej se sám, ale dívej se jí přitom do očí. Nesmíš se usmát. Cíl: ať se ona usměje první.|120|tanec",
    "Líbej jí vnitřní stranu stehen přes látku kalhotek. Jenom přes látku.|120|oral_klek",
    "Táhni jí prstem podél lemu prádla dokola, a to je všechno.|90",
    "Postav ji před zrcadlo, staň si za ni a svlékej ji, ať se dívá.|180|stoje_zezadu",
    "Polib ji tak, jako byste to dělali poprvé. Nesměle a pomalu.|60|objeti",
    "Pusť jí hudbu a hlaď ji do rytmu – rychlé pasáže rychle, pomalé pomalu.|180|vedle_ona_lezi",
    "Sedni si k ní a jen jí odhrnuj vlasy z obličeje a dívej se na ni. Nic jiného.|60",
    "Dvacet polibků: Dej jí dvacet krátkých polibků po celém těle, žádný na stejné místo. Ona počítá. Cíl: dojít do dvaceti bez opakování.|180",
    "Svlékni jí všechno až na jeden kus a ten nech na ní až do konce této úrovně.|90|svlekani",
    "Obkreslení obličeje: Lehni si vedle ní a prstem jí obkresluj oči, rty a bradu. Cíl: tři pomalá kola a ona má celou dobu zavřené oči.|60|vedle_ona_lezi",
    "Kousni ji zlehka do ušního lalůčku a pak dlouho nic nedělej.|30|objeti",
    "Popros ji, ať zůstane oblečená, a dráždi ji jen přes látku, dokud si prádlo sama nestáhne.|180",
    "Hlas do ucha: Pusť jí do jednoho ucha sluchátko s hudbou a do druhého jí šeptej. Cíl: ať poslouchá tebe, ne hudbu.|120",
    "Líbej jí záda odshora dolů podél páteře. Každý polibek o kousek níž.|120|masaz_zada",
    "Nech ji, ať si sama vybere kus tvého oblečení, který jí necháš na sobě.|60",
    "Sedni si proti ní a svlékejte se střídavě po jednom kuse. Kdo se první rozesměje, prohrál.|180|sed_celem",
    "Přitiskni si ji zády k sobě a rukama jí pomalu projeď od ramen po boky a zpátky.|120|stoje_zezadu",
    "Polib ji na místo, kde má nejcitlivější kůži, a tam zůstaň celou minutu.|60",
    "Beze slov: Celý úkol probíhá bez jediného slova. Svlékni ji a polib ji tam, kam ti sama ukáže. Cíl: dorozumět se jen pohledy.|180|svlekani",
    "Dej jí ruce za záda a drž jí je jednou svojí. Druhou ji svlékej.|120|klek_ruce_za_zady",
    "Ukaž jí, jak by ses chtěl, aby se tě dneska dotýkala – na sobě, ne na ní.|90",
    "Lehni si k ní, dej jí ruku pod tričko na záda a jen tak ji hlaď, dokud se neuvolní.|180|lzicka",
    "Táhni jí lemem kalhotek do strany a zase zpět, ale nikdy je nesundej.|90",
    "Polib ji naposledy a pak ustup o dva kroky. Nech ji přijít za tebou.|45|objeti",
  ],

  female: [
    "Minuta na kus: Svlékej ho tempem jeden kus za minutu a mezi kusy ho polib na místo, které jsi právě odhalila. Cíl: tři kusy, tři polibky.|180|svlekani!",
    "Stop na hrudníku: Pomalu mu vyhrň tričko až na hrudník a tam přestaň. Cíl: dál se nedostaneš, dokud tě o to sám nepoprosí.|90|svlekani",
    "Zuby a nic víc: Svlékni mu jeden kus oblečení jen zuby, bez pomoci rukou. Cíl: sundat to, ať to trvá jakkoli.|180|svlekani!",
    "Knoflík za polibek: Rozepínej mu knoflíky jeden po druhém a po každém ho polib na odhalené místo. Cíl: rozepnout všechny a u žádného nespěchat.|120|svlekani!",
    "Ruce pryč: Sundej mu trenýrky tak, aby se tě ani jednou nedotkl. Když po tobě sáhne, začínáš znovu. Cíl: zvládnout to napoprvé.|90|svlekani",
    "On jen kouká: Postav se před něj a svlékni se sama. On sedí a nesmí promluvit. Cíl: tři minuty ticha, ani jedno slovo z jeho strany.|180|tanec",
    "Písnička na krku: Pusť jednu písničku a po celou dobu ho líbej na krk. Cíl: přestat přesně v okamžiku, kdy dozní poslední tón.|180|objeti",
    "Slyší jen písničku: Dej mu do uší sluchátka se svou oblíbenou písničkou a celou dobu ho svlékej. Cíl: stihnout to do konce písničky a nepromluvit.|180|svlekani",
    "Tanec o dvou pravidlech: Tancujte spolu pomalu, ty ho smíš držet jen kolem krku a nesmíš ho políbit. Cíl: vydržet celou písničku.|180|objeti",
    "Deset míst na něm: Polib ho na deset různých míst a ani jedno nesmí být na ústech. On počítá nahlas. Cíl: dojít k desítce bez opakování.|120",
    "Jen horní ret: Líbej ho tak, že se dotkneš vždycky jen jeho horního rtu. Jazyk je zakázaný. Cíl: celá minuta a ani jednou nesklouznout jinam.|60|objeti",
    "Polibek na tři doby: Nejdřív jen rty, pak s jazykem, pak mu kousni do rtu. Mezi tím vždycky počkej pět vteřin. Cíl: ať si o další řekne sám.|90|objeti",
    "Obě ruce na zdi: Přitiskni ho ke zdi a líbej ho, ruce máš opřené o zeď, ne na něm. Cíl: nepřestat, dokud po tobě sám nesáhne.|120|zed",
    "Nikdy na kůži: Líbej ho všude tam, kde má oblečení, a nikdy na holou kůži. Cíl: dvě minuty a ani jeden polibek na kůži.|120",
    "Tři minuty polibků: Sedni si mu obkročmo na klín a jenom se líbejte. Nic jiného. Cíl: tři minuty, při kterých se ani jeden nepokusí o víc.|180|klin_celem",
    "Trenýrky zůstávají: Dráždi ho rukou přes trenýrky, sundat mu je nesmíš. Cíl: tři minuty – a jestli si je stáhne sám, vyhrál.|180",
    "Jen přes látku: Hlaď ho a dráždi přes spodní prádlo tak dlouho, až si ho bude chtít sundat. Cíl: ať si ho sundá sám.|180",
    "Hranice u pasu: Vsuň mu ruku pod tričko a zastav se hned nad pasem. Cíl: nedostat se níž, dokud ti to sám nedovolí.|90",
    "Paže odspodu nahoru: Polib ho do dlaně, pak do zápěstí a pokračuj po vnitřní straně paže až k rameni. Cíl: deset polibků na každé ruce.|90",
    "Ruce zůstanou ležet: Lehni si k němu a celou minutu ho líbej jenom na krk a za ucho. Cíl: nepohnout rukama ani jednou.|60|vedle_on_lezi",
    "Kolena a stehna jemu: Nech ho sednout na kraj postele, klekni si před něj a líbej mu kolena a stehna. Cíl: dvě minuty a ani jednou výš.|120|oral_on_vsede",
    "Vyměněný kus: Sundej mu jeden kus oblečení a ten samý si obleč sama. Cíl: zůstat tak až do konce úkolu a tvářit se úplně normálně.|60|svlekani",
    "Fotka na přání: Nech se od něj vyfotit tak, jak se ti to bude líbit, a pak fotku hned smažte. Cíl: ať se líbíš sama sobě.|180",
    "Zpráva na dálku: Napiš mu z druhého konce pokoje zprávu, co mu uděláš. Nahlas neřekneš nic. Cíl: tři zprávy a ani jedno slovo.|90",
    "Hlasovka pro něj: Nahraj mu hlasovku, co s ním chceš dělat, a nech ho, ať si ji poslechne ve sluchátkách. Cíl: dívat se mu u toho do očí.|120",
    "Obrysy při hudbě: Pusť mu do sluchátek písničku a prstem mu obkresluj obrysy těla. Cíl: obkreslit ho celého, než písnička dohraje, a mlčet.|180|vedle_on_lezi",
    "Odpočet na sobě: Odpočítávej nahlas od deseti a při každém čísle si sundej nebo posuň jeden kus oblečení. Cíl: dojít k nule a nezrychlit.|90|tanec",
    "Rozhoduje on: Svlékni se až na jeden kus a postav se před něj. Cíl: nechat na něm, kdy padne i ten, a do té doby se nehnout.|60|tanec",
    "Rozehřátí zezadu: Obejmi ho zezadu, líbej ho na šíji a rukama mu zvolna zajeď pod tričko. Cíl: ať se o tebe sám opře.|120|stoje_zezadu!",
    "Až spadne, zastav: Líbej ho a u toho si pomalu rozepínej podprsenku. Cíl: v okamžiku, kdy spadne, přestat a nechat ho jen koukat.|90|svlekani!",
    "Stop u lemu: Táhni mu špičkou prstu od krku dolů a zastav se přesně tam, kde začíná prádlo. Cíl: pět cest a ani jednou přes lem.|60|vedle_on_lezi",
    "Zakázaná místa: Dotýkej se ho kdekoli, jen ne na hrudníku a mezi nohama. Tři minuty. Cíl: ať ti ruku sám posune tam, kam chce.|180|vedle_on_lezi",
    "Ponožky a kotníky: Klekni si před něj a pomalu mu stahuj ponožky. Cíl: u každého kotníku se zastavit a políbit ho.|90",
    "Vlasy a zátylek: Zezadu mu prsty prohrábni vlasy a líbej ho na zátylek. Cíl: nepřestat, dokud se nezachvěje.|60|stoje_zezadu!",
    "Jedno rameno stačí: Líbej ho na rameno a pomalu mu přitom shrnuj tričko. Druhé nech být. Cíl: celá minuta jen na jedné straně.|60|svlekani!",
    "Vodíš jeho ruce: Sedni si mu na klín zády k němu a jeho dlaně si sama vodíš po stehnech. Cíl: tři minuty, při kterých se nesmí pohnout sám.|180|klin_zady",
    "Jedna ruka za zády: Tancujte spolu, ale ty ho smíš držet jen jednou rukou. Cíl: dvě minuty a druhou ruku zezadu nevyndat.|120|objeti",
    "Šeptem a rukama: Pusť hudbu, staň si před něj a veď jeho ruce po svém těle. Nesmíš promluvit. Cíl: ať tě chytne sám.|180|objeti",
    "Za každý polibek kus: Polib ho na ústa a při každém dalším polibku mu sundej jeden kus oblečení. Cíl: dostat se k prádlu do pěti polibků.|120|svlekani!",
    "Ústa zakázaná: Přejeď mu rty po celém obličeji, ale ústům se vyhni. Cíl: celá minuta a ani jednou nepolíbit ústa.|60|objeti",
    "Jeho ruce nehrají: Sedni si na něj obkročmo a líbej ho, jak chceš. Cíl: tři minuty, při kterých on nesmí hnout rukama.|180|ona_nahore",
    "Co vzrušuje tebe: Ukaž mu na telefonu fotku nebo scénu, která tě vzrušuje, a popiš mu, co přesně na tom je. Cíl: tři konkrétní detaily.|120",
    "Jeho ruce nad hlavou: Vezmi mu ruce, přitiskni je nad hlavu ke zdi a líbej ho. Cíl: nepustit ho, dokud se nezačne kroutit.|90|zed",
    "Nech ho vybrat písničku a po celou dobu se ho smíš dotýkat jen tak, jak se hýbe hudba.|180",
    "Cesta dolů: Začni polibkem na jeho čele a propolibkuj se centimetr po centimetru až k pasu. Nesmíš nic přeskočit. Cíl: nezrychlit ani jednou.|180|vedle_on_lezi",
    "Svlékni se do pasu, ale nedovol mu, aby se tě dotkl. Ani omylem.|60|tanec",
    "Stáhni mu kalhoty jen tak nízko, aby to bylo ještě víc dráždivé než úplně.|60",
    "Oblékni si jeho tričko a pak si ho před ním zase pomalu sundávej.|120|tanec",
    "Líbej ho na bříško a u pupíku se zastav. Pak se vrať nahoru a začni znovu.|90|vedle_on_lezi",
    "Lehni si za něj na lžičku a celou dobu ho líbej na rameno. Ruce nech na jeho bocích.|120|lzicka",
    "Tři minuty bez rukou: Dotýkej se ho jen rty, nosem a dechem. Ruce máš celou dobu za zády. Cíl: nepoužít ruce ani jednou.|180",
    "Sedni si naproti němu a svlékej se přesně tak pomalu, jak ti řekne.|180|tanec",
    "Přitáhni si ho k sobě za pásek a chvíli ho tak drž. Nic víc.|45|objeti",
    "Polib ho do ohbí loktů a do podkolení. Na dvou nečekaných místech.|60",
    "Napiš mu prstem na hrudník slovo a nech ho hádat. Když uhodne, dostane polibek, kam si řekne.|90|vedle_on_lezi",
    "Seber mu telefon a napiš si sama sobě zprávu, co ti dneska udělá. Pak mu ji ukaž.|90",
    "Tři pokusy: On si smí zkusit sundat tvoje oblečení, ale jen tři kusy. Zbytek si necháš. Cíl: ať dobře vybere.|90|svlekani",
    "Polož ho na záda, klekni si nad něj a líbej ho shora dolů. Nikam nespěchej.|180|oral_ona_vleze",
    "Stáhni mu trenýrky zuby a pak je nech ležet přesně tam, kam spadly.|90|svlekani!",
    "Vezmi jeho ruku a nech ho, ať si sám ukáže, kde chce být políbený. A polib to.|60",
    "Nech se od něj zvednout do náruče a líbej ho, dokud tě nepustí.|90|zvednuta",
    "Sedni si před něj a nech ho, ať ti rozepne podprsenku jednou rukou. Pak mu ruce sundej.|60|masaz_vsede",
    "Škádlení očima: Svlékej se, ale dívej se mu přitom do očí. Nesmíš se usmát. Cíl: ať se on usměje první.|120|tanec",
    "Líbej mu vnitřní stranu stehen přes látku trenýrek. Jenom přes látku.|120|oral_on_vleze",
    "Táhni mu prstem podél lemu prádla dokola, a to je všechno.|90",
    "Postav se před zrcadlo, ať si tě prohlíží, a svlékej se pomalu.|180|tanec",
    "Polib ho tak, jako byste to dělali poprvé. Nesměle a pomalu.|60|objeti",
    "Pusť si hudbu a hlaď ho do rytmu – rychlé pasáže rychle, pomalé pomalu.|180|vedle_on_lezi",
    "Sedni si k němu a jen mu prohrábni vlasy a dívej se na něj. Nic jiného.|60",
    "Dvacet polibků: Dej mu dvacet krátkých polibků po celém těle, žádný na stejné místo. On počítá. Cíl: dojít do dvaceti bez opakování.|180",
    "Svlékni ho všeho až na jeden kus a ten mu nech až do konce této úrovně.|90|svlekani!",
    "Obkreslený obličej: Lehni si vedle něj a prstem mu obkresluj oči, rty a bradu. Cíl: tři pomalá kola a on má celou dobu zavřené oči.|60|vedle_on_lezi",
    "Kousni ho zlehka do ušního lalůčku a pak dlouho nic nedělej.|30|objeti",
    "Zůstaň oblečená a nech ho dráždit jen přes látku, dokud si prádlo sama nestáhneš.|180",
    "Hlas do ucha: Pusť mu do jednoho ucha sluchátko s hudbou a do druhého mu šeptej. Cíl: ať poslouchá tebe, ne hudbu.|120",
    "Líbej mu záda odshora dolů podél páteře. Každý polibek o kousek níž.|120|masaz_zada!",
    "Nech ho, ať si sám vybere kus tvého oblečení, který ti nechá na sobě.|60",
    "Sedni si proti němu a svlékejte se střídavě po jednom kuse. Kdo se první rozesměje, prohrál.|180|sed_celem",
    "Přitiskni se k němu zády a veď mu ruce od svých ramen po boky a zpátky.|120|stoje_zezadu",
    "Polib ho na místo, kde má nejcitlivější kůži, a tam zůstaň celou minutu.|60",
    "Beze slov: Celý úkol probíhá bez jediného slova. Svlékni ho a polib ho tam, kam ti sám ukáže. Cíl: dorozumět se jen pohledy.|180|svlekani!",
    "Dej mu ruce za záda a drž mu je jednou svojí. Druhou ho svlékej.|120|klek_ruce_za_zady!",
    "Ukaž mu, jak by ses chtěla, aby se tě dneska dotýkal – na sobě, ne na něm.|90",
    "Lehni si k němu, dej mu ruku pod tričko na záda a jen tak ho hlaď, dokud se neuvolní.|180|lzicka",
    "Táhni mu lemem trenýrek do strany a zase zpět, ale nikdy je nesundej.|90",
    "Polib ho naposledy a pak ustup o dva kroky. Nech ho přijít za tebou.|45|objeti",
  ],
});
