// Kategorie 1 – Škádlení a předehra (dávka d)
// Témata: pírko, štětec, žínka, led, zavázané oči, masáže a smyslové hry.
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 1,

  male: [
    "Hádaná cesta pírkem: Zavaž jí oči a přejížděj jí pírkem od krku až po kotníky. Cíl: deset zastávek a ona musí uhodnout aspoň pět z nich.|180|vedle_ona_lezi",
    "Kruhy štětcem: Maluj jí štětcem po zádech pomalé kruhy, ona leží na břiše. Cíl: tři minuty, při kterých se ani jednou nepohne.|180|masaz_zada",
    "Hádej čím: Zavaž jí oči a dotýkej se jí střídavě pírkem, štětcem a žínkou. Ona hádá. Za každý omyl si sundá kus oblečení. Cíl: tři omyly.|180|vedle_ona_lezi",
    "Led a horké rty: Táhni jí kostku ledu po klíční kosti a roztátou vodu hned slíbej. Cíl: tři cesty ledem a po každé jedna cesta rty.|90|vedle_ona_lezi",
    "Horko a zima: Jednou ji líbej horkými rty, podruhé jí přilož kostku ledu. Cíl: deset střídání a ona nesmí vědět, co přijde.|180|vedle_ona_lezi",
    "Studená ústa: Dej si do pusy kostku ledu a líbej ji tak na krk a na ramena. Cíl: nepřestat, dokud led v puse úplně neroztaje.|120|vedle_ona_lezi",
    "Lázeň žínkou: Namoč žínku v teplé vodě a omyj jí záda, ruce a nohy. Cíl: tři minuty a nevynechat ani centimetr kůže.|180|masaz_zada",
    "Ochutnávka poslepu: Zavaž jí oči a dej jí ochutnat tři různé věci z kuchyně. Cíl: za každou uhodnutou dostaneš polibek, kam si řekneš.|180",
    "Slepá cesta: Zavaž jí oči a veď ji po bytě za ruku. Kde se zastavíš, tam ji políbíš. Cíl: pět zastávek.|180",
    "Uzly v ramenou: Rozmasíruj jí olejem ramena a šíji palci v kroužcích. Cíl: čtyři minuty a nepřestat, dokud jí neklesnou ramena.|240|masaz_vsede",
    "Masáž hlavy do ospalosti: Prsty jí projížděj vlasy a masíruj pokožku hlavy. Cíl: nepřestat, dokud se jí nezačnou klížit oči.|180",
    "Ploska od paty: Vezmi si její chodidlo do klína a palcem jí masíruj plosku od paty ke špičkám. Cíl: půldruhé minuty na každé noze.|180|masaz_chodidla",
    "Masáž zad odshora dolů: Začni u krku a skonči u kříže, každý pruh dvakrát. Ruce máš celou dobu naolejované. Cíl: nevynechat ani centimetr.|300|masaz_zada",
    "Ruka po kouskách: Masíruj jí dlaň, potom každý prst zvlášť, pak zápěstí a předloktí. Cíl: obě ruce a u žádného prstu nespěchat.|180",
    "Čím se tě dotýkám: Zavaž jí oči a dotýkej se jí nosem, loktem, rty nebo kolenem. Cíl: deset doteků a ona musí uhodnout aspoň šest.|180|vedle_ona_lezi",
    "Pírko po stehnech: Veď jí pírko po vnitřní straně stehen nahoru a zase dolů. Cíl: deset cest a ani jednou nedojet až úplně nahoru.|180|vedle_ona_lezi",
    "Štětec a pauza: Přejeď jí štětcem přes bradavky tak lehce, jak to jen jde, a pak nedělej nic. Cíl: pět takových kol s pauzou vždy deset vteřin.|120|vedle_ona_lezi",
    "Ledová stopa: Táhni jí kostku ledu od krku dolů mezi prsy až k pupíku a stopu slíbej. Cíl: dojet celou cestu, než led roztaje.|120|vedle_ona_lezi",
    "Jeden tah přes celá záda: Zahřej si olej v dlani a rozetři jí ho po zádech jediným nepřerušeným tahem. Cíl: pět tahů, ani jeden přerušený.|120|masaz_zada",
    "Jen zadeček a stehna: Masíruj jí zadeček a stehna a ničeho jiného se nedotkni. Cíl: tři minuty a ani jednou nesjet mezi nohy.|180|masaz_zada",
    "Studená žínka: Namoč žínku ve studené vodě, přejeď jí ji po zátylku a pak to místo polib. Cíl: třikrát studená žínka, třikrát horké rty.|60|masaz_vsede",
    "Slovo po písmenech: Kresli jí prstem po zádech písmena a ona z nich skládá slovo. Cíl: tři slova, žádné kratší než pět písmen.|180|masaz_zada",
    "Bez očí a bez uší: Zavaž jí oči, dej jí do uší sluchátka a jen se jí dotýkej. Cíl: pět minut a ani jednou nezopakovat stejný dotek.|300|vedle_ona_lezi",
    "Lýtka a podkolení: Masíruj jí lýtka a pak jemně i místo pod koleny. Cíl: minuta na každé noze a zeptat se, co je lepší.|120|masaz_chodidla",
    "Deset vteřin na místo: Vyber si jedno místo na jejím těle a deset vteřin se věnuj jenom jemu. Pak další. Cíl: šest míst, žádné dvakrát.|120|vedle_ona_lezi",
    "Obrys pírkem: Pírkem jí obkresli obrys celého těla od ramen po kotníky. Cíl: dokončit obrys, aniž by jednou hlesla.|180|vedle_ona_lezi",
    "Olíznout a foukat: Olízni jí místo na kůži a hned na něj foukej. Cíl: pět různých míst a u každého počkat, až jí naskočí husí kůže.|90|vedle_ona_lezi",
    "Nehty a pak dlaně: Nehty jí lehce přejeď po zádech shora dolů a pak to samé dlaněmi, ale pomaleji. Cíl: pět kol a zeptat se, co je lepší.|120|masaz_zada",
    "Uši mezi prsty: Masíruj jí lalůčky mezi prsty a projdi celý okraj boltce. Cíl: minuta na každém uchu a na závěr polibek.|90|masaz_vsede",
    "Tři doteky: Zavaž jí oči a dotkni se jí jen třikrát, pokaždé jinde. Cíl: ať uhodne všechna tři místa – jinak začínáš znovu.|90|vedle_ona_lezi",
    "Ledová zkouška: Polož jí kostku ledu na břicho a ona ji tam musí udržet, dokud neroztaje. Ty ji mezitím líbáš. Cíl: nenechat led spadnout.|180|vedle_ona_lezi",
    "Bez zastavení: Naolejuj si ruce a klouzej jí dlaněmi po bocích nahoru a dolů. Cíl: dvě minuty jednoho plynulého pohybu bez jediné pauzy.|120|masaz_zada",
    "Prst po prstu: Masíruj jí prsty u nohou jeden po druhém a u každého se zeptej, jestli to stačí. Cíl: všech deset prstů.|120|masaz_chodidla",
    "Obtažené rty: Štětcem jí obkresli obrys rtů a teprve pak je polib. Cíl: tři obtažení a mezi nimi vždy deset vteřin čekání.|60",
    "Teplý ručník: Přilož jí na záda teplý ručník a nech ho vychladnout. Cíl: teprve potom začít masírovat, a to celé tři minuty.|180|masaz_zada",
    "Tři doteky na výběr: Zavaž jí oči a nabídni jí tři různé doteky. Cíl: ten, který si vybere, jí dej ještě desetkrát.|120|vedle_ona_lezi",
    "Pírko a nic víc: Pět minut se jí smíš dotýkat jen pírkem. Žádné ruce, žádné rty. Cíl: ať tě sama poprosí o víc.|300|vedle_ona_lezi",
    "Kroužky na kříži: Masíruj jí kříž palci v kroužcích směrem od páteře ven. Cíl: tři minuty a postupně přidávat tlak, dokud neřekne dost.|180|masaz_zada",
    "Studené rty: Přejeď jí kostkou ledu po rtech a hned je polib, dokud jsou studené. Cíl: třikrát po sobě, pokaždé rychleji.|45|objeti",
    "Olej mezi lopatkami: Nalij jí trochu oleje mezi lopatky a rozetři ho celými dlaněmi. Cíl: rozetřít ho až ke kříži a zpátky, a to pětkrát.|120|masaz_zada",
    "Až povolí: Hlaď ji po vlasech a šíji pomalými tahy shora dolů. Cíl: nepřestat, dokud se ti celá neuvolní v rukou.|180|masaz_vsede",
    "Pořadí polibků: Zavaž jí oči a polib ji na pět různých míst. Cíl: ať zpaměti zopakuje přesné pořadí – jinak jdeš znovu.|120",
    "Žínka a olej: Nejdřív ji celou omyj teplou žínkou, pak ji naolejuj. Nespěchej ani u jednoho. Cíl: dvě různé teploty na kůži.|300|masaz_zada",
    "Dlaň v kruzích: Masíruj jí dlaň palcem v pomalých kruzích od zápěstí ke kořenům prstů. Cíl: minuta na každé ruce.|90",
    "Jen nečekaná místa: Dotýkej se jí jen konečky prstů a jen tam, kde by to nečekala. Cíl: deset míst a ani jedno z nich nesmí být to obvyklé.|180|vedle_ona_lezi",
    "Dech a jazyk v uchu: Foukej jí zlehka do ucha a pak jazykem přejeď okraj boltce. Cíl: pět střídání a mezi nimi vždy tři vteřiny nic.|60",
    "Polož ji na břicho a masíruj jí nohy od kotníků ke stehnům. Pomalu nahoru.|240|masaz_zada",
    "Vezmi štětec a přejeď jí ho po celém obličeji. Oči, nos, rty.|90",
    "Ledová a horká: Dej si do jedné ruky led a druhou zahřej. Střídej je na jejích prsou. Cíl: ať nikdy neví, co přijde.|180|vedle_ona_lezi",
    "Masíruj jí ramena a při tom ji líbej na šíji.|180|masaz_vsede",
    "Zavaž jí oči a šeptej jí, čeho se jí právě dotkneš. A pak to udělej jinak.|180|vedle_ona_lezi",
    "Pírkem jí přejeď po chodidlech. Jestli se bude smát, začínáš znovu.|90|masaz_chodidla",
    "Vezmi ji za ruku a masíruj jí zápěstí. Pak tam přitiskni rty a chvíli počkej.|60",
    "Naolejuj jí celá záda a pak na ně polož vlastní hrudník a klouzej po nich.|180|masaz_zada",
    "Slepé instrukce: Zavaž jí oči a ona ti musí říkat, kam se má tvoje ruka posunout. Ty posloucháš. Cíl: nechat ji řídit celou dobu.|180|vedle_ona_lezi",
    "Přejížděj jí žínkou po břiše v kruzích, jednou teplou, podruhé studenou.|120|vedle_ona_lezi",
    "Masíruj jí čelisti a spánky. Uvolní se jí celý obličej.|120",
    "Polib jí každý obratel na páteři odshora dolů. Ona počítá nahlas.|180|masaz_zada",
    "Vezmi kostku ledu do pusy a olízni jí bradavku. Pak na ni foukni.|90|vedle_ona_lezi",
    "Masáž ve dvou tempech: Nejdřív ji masíruj hodně pomalu, pak najednou rychle a silně. Střídej. Cíl: třikrát změnit tempo.|240|masaz_zada",
    "Zavaž jí oči a nech ji poznat po hmatu tři různé látky na svém těle.|120",
    "Hlaď ji po vnitřní straně paží. Je to jedno z nejcitlivějších míst.|90|vedle_ona_lezi",
    "Masíruj jí boky a podbřišek dlaněmi v kruzích. Níž nesmíš.|180|vedle_ona_lezi",
    "Nakresli jí olejem na záda srdce a pak ho rozetři.|90|masaz_zada",
    "Zavaž jí oči a políbej ji na celém těle, ale vždycky jinam, než se čeká.|240|vedle_ona_lezi",
    "Přiložení: Polož jí obě dlaně na tělo a nehýbej jimi celou minutu. Jen teplo a nic víc. Cíl: vydržet bez pohybu.|60|vedle_ona_lezi",
    "Masíruj jí paty a nárty. Pak jí polib kotník.|120|masaz_chodidla",
    "Přejeď jí pírkem podél lemu prádla dokola. Dvakrát.|90|vedle_ona_lezi",
    "Nech ji ležet na břiše a hraj jí prsty po zádech jako na klavír.|120|masaz_zada",
    "Vezmi si ji do klína a masíruj jí zátylek jednou rukou, druhou ji drž.|180|klin_podlaha",
    "Foukej jí na kůži tam, kde jsi ji před chvílí olízl. Pomalu a dlouho.|90|vedle_ona_lezi",
    "Osm doteků: Dotkni se jí osmkrát a pokaždé jinou částí těla. Ona hádá čím. Cíl: aspoň čtyři uhodnuté.|180|vedle_ona_lezi",
    "Masíruj jí kolena a podkolenní jamky. Nikdo to nedělá a je to překvapivě příjemné.|120|masaz_chodidla",
    "Přiložte si na chvíli dlaň na dlaň a jen si vychutnejte, jak jsou různě teplé.|60|sed_celem",
    "Přejeď jí kostkou ledu po zádech, dokud ji neroztaje kůže.|120|masaz_zada",
    "Zavaž jí oči a nech ji, ať hádá, kterým prstem se jí dotýkáš.|120|vedle_ona_lezi",
    "Masíruj jí bříško jemnými kruhy po směru hodinových ručiček.|120|vedle_ona_lezi",
    "Naber si olej a naolejuj jí prsa lehkými tahy, aniž by ses dotkl bradavek.|180|vedle_ona_lezi",
    "Pírkem přejeď mezi prsy a dolů k pupíku. Pak se vrať zpátky.|90|vedle_ona_lezi",
    "Beze slov a poslepu: Ona má zavázané oči a ty se jí dotýkáš jen rukama a rty. Cíl: pět minut, při kterých neřekneš ani slovo.|300|vedle_ona_lezi",
    "Masíruj jí prsty rukou od kořene ke špičce a každý zakonči jemným tahem.|120",
    "Přiklop jí dlaně na uši, ať nic neslyší, a líbej ji na obličej.|90",
    "Vezmi teplou a studenou žínku a nech ji hádat, která je která, aniž by se dívala.|120|vedle_ona_lezi",
    "Masíruj jí ramena zezadu, zatímco sedí na kraji postele, a pomalu klesej níž.|180|masaz_vsede",
    "Naposledy jí přejeď pírkem po tváři a odlož ho. Pak ji polib.|45",
  ],

  female: [
    "Kde právě jsem: Zavaž mu oči a přejížděj mu pírkem od krku až po kotníky. Cíl: deset zastávek a on musí uhodnout aspoň pět z nich.|180|vedle_on_lezi",
    "Štětec po zádech: Maluj mu štětcem po zádech pomalé kruhy, on leží na břiše. Cíl: tři minuty, při kterých se ani jednou nepohne.|180|masaz_zada!",
    "Hádej čím: Zavaž mu oči a dotýkej se ho střídavě pírkem, štětcem a žínkou. On hádá. Za každý omyl si sundá kus oblečení. Cíl: tři omyly.|180|vedle_on_lezi",
    "Ledová stopa: Táhni mu kostku ledu po klíční kosti a roztátou vodu hned slíbej. Cíl: tři cesty ledem a po každé jedna cesta jazykem.|90|vedle_on_lezi",
    "Střídání teplot: Jednou ho líbej horkými rty, podruhé mu přilož kostku ledu. Cíl: deset střídání a on nesmí vědět, co přijde.|180|vedle_on_lezi",
    "Led v puse: Dej si do pusy kostku ledu a líbej ho tak na krk a na ramena. Cíl: nepřestat, dokud led v puse úplně neroztaje.|120|vedle_on_lezi",
    "Teplá lázeň: Namoč žínku v teplé vodě a omyj mu záda, ruce a nohy. Cíl: tři minuty a nevynechat ani centimetr kůže.|180|masaz_zada!",
    "Tři chutě poslepu: Zavaž mu oči a dej mu ochutnat tři různé věci z kuchyně. Cíl: za každou uhodnutou dostaneš polibek, kam si řekneš.|180",
    "Slepá cesta: Zavaž mu oči a veď ho po bytě za ruku. Kde se zastavíš, tam ho políbíš. Cíl: pět zastávek.|180",
    "Tuhá ramena: Rozmasíruj mu olejem ramena a šíji palci v kroužcích. Cíl: čtyři minuty a nepřestat, dokud mu neklesnou ramena.|240|masaz_vsede!",
    "Hlava do ospalosti: Prsty mu projížděj vlasy a masíruj pokožku hlavy. Cíl: nepřestat, dokud se mu nezačnou klížit oči.|180",
    "Chodidlo v klíně: Vezmi si jeho chodidlo do klína a palcem mu masíruj plosku od paty ke špičkám. Cíl: půldruhé minuty na každé noze.|180|masaz_chodidla!",
    "Záda pruh po pruhu: Naolejuj si ruce a jeď od jeho krku až ke kříži, každý pruh projeď dvakrát. Cíl: nevynechat ani centimetr.|300|masaz_zada!",
    "Ruka kousek po kousku: Masíruj mu dlaň, pak každý prst zvlášť, potom zápěstí a předloktí. Cíl: obě ruce a u žádného prstu nespěchat.|180",
    "Čím se ho dotýkáš: Zavaž mu oči a dotýkej se ho nosem, loktem, rty nebo kolenem. Cíl: deset doteků a on musí uhodnout aspoň šest.|180|vedle_on_lezi",
    "Pírko a hranice: Veď mu pírko po vnitřní straně stehen nahoru a zase dolů. Cíl: deset cest a ani jednou nedojet až úplně nahoru.|180|vedle_on_lezi",
    "Štětec a ticho: Přejeď mu štětcem přes bradavky tak lehce, jak to jen jde, a pak nedělej nic. Cíl: pět kol s pauzou vždy deset vteřin.|120|vedle_on_lezi",
    "Ledová stopa: Táhni mu kostku ledu od krku přes hrudník až k pupíku a stopu slíbej. Cíl: dojet celou cestu, než led roztaje.|120|vedle_on_lezi",
    "Jediný tah: Zahřej si olej v dlani a rozetři mu ho po zádech jediným nepřerušeným tahem. Cíl: pět tahů, ani jeden přerušený.|120|masaz_zada!",
    "Zadek a stehna: Masíruj mu zadek a stehna a ničeho jiného se nedotkni. Cíl: tři minuty a ani jednou nesjet mezi nohy.|180|masaz_zada!",
    "Chlad na zátylku: Namoč žínku ve studené vodě, přejeď mu ji po zátylku a pak to místo polib. Cíl: třikrát chlad, třikrát horké rty.|60|masaz_vsede!",
    "Písmena na záda: Kresli mu prstem po zádech písmena a on z nich skládá slovo. Cíl: tři slova, žádné kratší než pět písmen.|180|masaz_zada!",
    "Nevidí a neslyší: Zavaž mu oči, dej mu do uší sluchátka a jen se ho dotýkej. Cíl: pět minut a ani jednou nezopakovat stejný dotek.|300|vedle_on_lezi",
    "Citlivá podkolení: Masíruj mu lýtka a pak jemně i místo pod koleny. Cíl: minuta na každé noze a zeptat se, co je lepší.|120|masaz_chodidla!",
    "Deset vteřin na místo: Vyber si jedno místo na jeho těle a deset vteřin se věnuj jenom jemu. Pak další. Cíl: šest míst, žádné dvakrát.|120|vedle_on_lezi",
    "Obtažený pírkem: Pírkem mu obkresli obrys celého těla od ramen po kotníky. Cíl: dokončit obrys, aniž by jednou hlesl.|180|vedle_on_lezi",
    "Olíznout a foukat na něj: Olízni mu místo na kůži a hned na něj foukej. Cíl: pět míst a u každého počkat na husí kůži.|90|vedle_on_lezi",
    "Nehty, pak dlaně: Nehty mu lehce přejeď po zádech shora dolů a pak to samé dlaněmi, ale pomaleji. Cíl: pět kol a zeptat se, co je lepší.|120|masaz_zada!",
    "Jeho uši: Masíruj mu lalůčky mezi prsty a projdi celý okraj boltce. Cíl: minuta na každém uchu a na závěr polibek.|90|masaz_vsede!",
    "Jen tři doteky: Zavaž mu oči a dotkni se ho jen třikrát, pokaždé jinde. Cíl: ať uhodne všechna tři místa – jinak začínáš znovu.|90|vedle_on_lezi",
    "Ledová zkouška: Polož mu kostku ledu na břicho a on ji tam musí udržet, dokud neroztaje. Ty ho mezitím líbáš. Cíl: nenechat led spadnout.|180|vedle_on_lezi",
    "Plynule a bez pauzy: Naolejuj si ruce a klouzej mu dlaněmi po bocích nahoru a dolů. Cíl: dvě minuty jednoho plynulého pohybu bez zastavení.|120|masaz_zada!",
    "Deset prstů: Masíruj mu prsty u nohou jeden po druhém a u každého se zeptej, jestli to stačí. Cíl: projít všech deset.|120|masaz_chodidla!",
    "Obtažené rty jeho: Štětcem mu obkresli obrys rtů a teprve pak je polib. Cíl: tři obtažení a mezi nimi vždy deset vteřin čekání.|60",
    "Ručník na zádech: Přilož mu na záda teplý ručník a nech ho vychladnout. Cíl: teprve potom začít masírovat, a to celé tři minuty.|180|masaz_zada!",
    "Vyber si dotek: Zavaž mu oči a nabídni mu tři různé doteky. Cíl: ten, který si vybere, mu dej ještě desetkrát.|120|vedle_on_lezi",
    "Pírko a nic víc: Pět minut se ho smíš dotýkat jen pírkem. Žádné ruce, žádné rty. Cíl: ať tě sám poprosí o víc.|300|vedle_on_lezi",
    "Kříž od páteře ven: Masíruj mu kříž palci v kroužcích směrem od páteře ven. Cíl: tři minuty a postupně přidávat tlak, dokud neřekne dost.|180|masaz_zada!",
    "Jeho studené rty: Přejeď mu kostkou ledu po rtech a hned je polib, dokud jsou studené. Cíl: třikrát po sobě, pokaždé rychleji.|45|objeti",
    "Olej na lopatkách: Nalij mu trochu oleje mezi lopatky a rozetři ho celými dlaněmi. Cíl: rozetřít ho až ke kříži a zpátky, a to pětkrát.|120|masaz_zada!",
    "Dokud nepovolí: Hlaď ho po vlasech a šíji pomalými tahy shora dolů. Cíl: nepřestat, dokud se ti celý neuvolní v rukou.|180|masaz_vsede!",
    "Pět míst a pořadí: Zavaž mu oči a polib ho na pět různých míst. Cíl: ať zpaměti zopakuje přesné pořadí – jinak jdeš znovu.|120",
    "Žínka a olej: Nejdřív ho celého omyj teplou žínkou, pak ho naolejuj. Nespěchej ani u jednoho. Cíl: dvě různé teploty na kůži.|300|masaz_zada!",
    "Masíruj mu dlaň palcem v kruzích. Je to malá věc, ale funguje.|90",
    "Dotýkej se ho jen konečky prstů a jen tam, kde by to nečekal.|180|vedle_on_lezi",
    "Foukání do ucha: Foukej mu zlehka do ucha a pak jazykem přejeď okraj boltce. Cíl: pět střídání a mezi nimi vždy tři vteřiny nic.|60",
    "Polož ho na břicho a masíruj mu nohy od kotníků ke stehnům. Pomalu nahoru.|240|masaz_zada!",
    "Vezmi štětec a přejeď mu ho po celém obličeji. Oči, nos, rty.|90",
    "Ledová a horká: Dej si do jedné ruky led a druhou zahřej. Střídej je na jeho hrudníku. Cíl: ať nikdy neví, co přijde.|180|vedle_on_lezi",
    "Masíruj mu ramena a při tom ho líbej na šíji.|180|masaz_vsede!",
    "Zavaž mu oči a šeptej mu, čeho se ho právě dotkneš. A pak to udělej jinak.|180|vedle_on_lezi",
    "Pírkem mu přejeď po chodidlech. Jestli se bude smát, začínáš znovu.|90|masaz_chodidla!",
    "Vezmi ho za ruku a masíruj mu zápěstí. Pak tam přitiskni rty a chvíli počkej.|60",
    "Naolejuj mu celá záda a pak na ně polož vlastní hrudník a klouzej po nich.|180|masaz_zada!",
    "Slepé instrukce: Zavaž mu oči a on ti musí říkat, kam se má tvoje ruka posunout. Ty posloucháš. Cíl: nechat ho řídit celou dobu.|180|vedle_on_lezi",
    "Přejížděj mu žínkou po břiše v kruzích, jednou teplou, podruhé studenou.|120|vedle_on_lezi",
    "Masíruj mu čelisti a spánky. Uvolní se mu celý obličej.|120",
    "Polib mu každý obratel na páteři odshora dolů. On počítá nahlas.|180|masaz_zada!",
    "Vezmi kostku ledu do pusy a olízni mu bradavku. Pak na ni foukni.|90|vedle_on_lezi",
    "Masáž ve dvou tempech: Nejdřív ho masíruj hodně pomalu, pak najednou rychle a silně. Střídej. Cíl: třikrát změnit tempo.|240|masaz_zada!",
    "Zavaž mu oči a nech ho poznat po hmatu tři různé látky na svém těle.|120",
    "Hlaď ho po vnitřní straně paží. Je to jedno z nejcitlivějších míst.|90|vedle_on_lezi",
    "Masíruj mu boky a podbřišek dlaněmi v kruzích. Níž nesmíš.|180|vedle_on_lezi",
    "Nakresli mu olejem na záda srdce a pak ho rozetři.|90|masaz_zada!",
    "Zavaž mu oči a polibkuj ho na celém těle, ale vždycky jinam, než se čeká.|240|vedle_on_lezi",
    "Přiložení: Polož mu obě dlaně na tělo a nehýbej jimi celou minutu. Jen teplo a nic víc. Cíl: vydržet bez pohybu.|60|vedle_on_lezi",
    "Masíruj mu paty a nárty. Pak mu polib kotník.|120|masaz_chodidla!",
    "Přejeď mu pírkem podél lemu prádla dokola. Dvakrát.|90|vedle_on_lezi",
    "Nech ho ležet na břiše a hraj mu prsty po zádech jako na klavír.|120|masaz_zada!",
    "Opři si ho zády o sebe a masíruj mu zátylek jednou rukou, druhou ho drž.|180|klin_podlaha!",
    "Foukej mu na kůži tam, kde jsi ho před chvílí olízla. Pomalu a dlouho.|90|vedle_on_lezi",
    "Osm doteků: Dotkni se ho osmkrát a pokaždé jinou částí těla. On hádá čím. Cíl: aspoň čtyři uhodnuté.|180|vedle_on_lezi",
    "Masíruj mu kolena a podkolenní jamky. Nikdo to nedělá a je to překvapivě příjemné.|120|masaz_chodidla!",
    "Přilož mu svoji dlaň na jeho a chvíli vnímej, o kolik je teplejší než tvoje.|60|sed_zady",
    "Přejeď mu kostkou ledu po zádech, dokud ji neroztaje kůže.|120|masaz_zada!",
    "Zavaž mu oči a nech ho, ať hádá, kterým prstem se ho dotýkáš.|120|vedle_on_lezi",
    "Masíruj mu bříško jemnými kruhy po směru hodinových ručiček.|120|vedle_on_lezi",
    "Naber si olej a naolejuj mu hrudník lehkými tahy, aniž by ses dotkla bradavek.|180|vedle_on_lezi",
    "Pírkem přejeď po jeho hrudníku dolů k pupíku. Pak se vrať zpátky.|90|vedle_on_lezi",
    "Poslepu a beze slov: On má zavázané oči a ty se ho dotýkáš jen rukama a rty. Cíl: pět minut, při kterých neřekneš ani slovo.|300|vedle_on_lezi",
    "Masíruj mu prsty rukou od kořene ke špičce a každý zakonči jemným tahem.|120",
    "Přiklop mu dlaně na uši, ať nic neslyší, a líbej ho na obličej.|90",
    "Vezmi teplou a studenou žínku a nech ho hádat, která je která, aniž by se díval.|120|vedle_on_lezi",
    "Masíruj mu ramena zezadu, zatímco sedí na kraji postele, a pomalu klesej níž.|180|masaz_vsede!",
    "Naposledy mu přejeď pírkem po tváři a odlož ho. Pak ho polib.|45",
  ],
});
