// Kategorie 1 – Škádlení a předehra
// Formát karty: "text" nebo "text|sekundy" (časovač)
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 1,
  name: "Škádlení a předehra",
  description: "Polibky, doteky, šeptání a pomalé svlékání. Pomalu, ať to jiskří.",

  // Úkoly pro muže – pro potěšení ženy
  male: [
    "Posaď ji na kuchyňskou linku, postav se mezi její kolena a pomalu ji líbej – nejdřív rty, pak krk.|90",
    "Přejížděj pírkem po jejím krku, klíčních kostech a vnitřní straně paží. Ona má po celou dobu zavřené oči.|60",
    "Zašeptej jí do ucha tři věci, které na jejím těle miluješ nejvíc – a každou z nich pak polib.",
    "Na gauči jí dej masáž ramen a šíje. Až povolí, polib ji za ucho.|120",
    "Opři ji zády o zeď v chodbě, chyť ji jemně za zápěstí nad hlavou a líbej ji na krk.|60",
    "Rozepni jí podprsenku jen jednou rukou. Když se ti to nepovede napoprvé, vynahraď jí to minutou líbání ramen.",
    "Klekni si před ni a polibky vystoupej od kotníku až k lemu jejího oblečení na stehně – ale ne výš.",
    "Sundej jí triko co nejpomaleji a každý odhalený kousek kůže polib.",
    "Hlaď ji po vnitřní straně stehen přes oblečení a dívej se jí přitom do očí. Nikam dál.|60",
    "Sedni si na židli, posaď si ji obkročmo na klín a líbejte se. Ruce smíš mít jen na jejích bocích.|120",
    "Zavaž jí oči šátkem a polib ji na pět míst podle sebe. Ať pokaždé hádá, kam přijde další polibek.",
    "Jemně ji kousni do ušního lalůčku a pošeptej jí, co s ní dnes chceš dělat.",
    "Stoupni si za ni před zrcadlo, hlaď ji po břiše a bocích a líbej na krk, zatímco se na vás dívá.|90",
    "Na gauči jí namasíruj chodidla a pak polib každý kotník.|120",
    "Obejmi ji zezadu u kuchyňské linky, přitiskni se k ní a pomalu jí přejížděj dlaněmi po stehnech.|60",
    "Líbej ji jen na rty – ale nesmíš se jí dotknout rukama.|60",
    "Pírkem opisuj pomalé kroužky kolem jejího pupíku a po bocích. Když se zasměje, začni znovu.|60",
    "Rozepni jí kalhoty nebo sukni a nech je spadnout na zem – a pak se věnuj už jen jejímu krku.",
    "Polib ji na zátylek a pak jí jazykem pomalu přejeď po páteři tak daleko, kam ti dovolí oblečení.",
    "Lehni si s ní na postel a konečky prstů ji hlaď po celém těle přes oblečení. Prsa a klín jsou zakázané.|120",
    "Pošeptej jí svou nejtajnější fantazii, ve které hraje hlavní roli ona.",
    "Pusť pomalou písničku a tancuj s ní v obýváku. Během tance ji hlaď po zadečku.|120",
    "Zuj ji a pomalu jí líbej nárty a kotníky.",
    "Masíruj jí hlavu – prsty ve vlasech, pomalu, ona má zavřené oči.|90",
    "Posaď ji na jídelní stůl, rozevři jí kolena a líbej ji, zatímco ji hladíš po stehnech.|60",
    "Odhrň jí vlasy z krku a jen na něj pomalu dýchej, bez polibků. Na konci jeden dlouhý polibek.",
    "Přejeď jí pírkem po rtech a pak ji dlouze polib.",
    "Líbej ji a mezitím jí rozepínej knoflíky halenky nebo svetru – jeden po druhém.",
    "Klekni si za ni na gauči a masíruj jí záda pod tričkem.|120",
    "Chyť ji oběma rukama za zadeček a přitáhni si ji k sobě na dlouhý polibek.",
    "Ať si lehne na břicho. Polib každý její obratel – od krku až dolů.",
    "Přejeď jí jazykem po krku od klíční kosti až k uchu. Hodně pomalu.",
    "Vezmi její ruku, polib každý prst a jemně jí políbej dlaň.",
    "Napusť jí vanu nebo pusť sprchu a pomoz jí se svléknout. Sám zůstaň oblečený a jen se dívej.",
    "Podrž jí ruce za zády a líbej ji do výstřihu.|60",
    "Lehni si na ni na posteli, propleť s ní prsty nad její hlavou a líbej ji.|60",
    "Řekni jí, co by sis s ní přál dělat v kuchyni – a s jednou věcí hned začni.",
    "Vyber 7 míst na jejím těle, která jsou podle tebe nejvíc sexy. U každého řekni proč a polib ho.",
    "Namaž jí nohy tělovým olejem nebo krémem – od kotníků ke kolenům, pomalými tahy.|120",
    "Napiš jí prstem na záda slovo. Když ho uhodne, dostane polibek, kam si řekne (nad pasem).",
    "Postav ji k oknu se zataženými závěsy, stoupni si za ni, líbej ji na ramena a hlaď po břiše.|60",
    "Přitáhni si ji k sobě za pásek nebo lem kalhot a polib ji.",
    "Střídej jemné kousání a polibky na jejím krku a ramenou.|60",
    "Sedni si na podlahu, ona si sedne mezi tvé nohy zády k tobě. Hlaď ji po pažích a líbej na ramena.|90",
    "Na gauči si jí polož hlavu do klína, hlaď ji ve vlasech a polib ji vzhůru nohama jako Spider-Man.",
    "Svlékni jí jednu věc podle svého výběru a místo, které se odhalí, líbej.|20",
    "Dej si mezi rty kousek čokolády nebo ovoce a nech ji, ať si ho vezme polibkem.",
    "Dotýkej se jí jen dechem – foukej jí jemně na krk, výstřih, břicho a stehna.|60",
    "Pomalu jí stáhni ramínko podprsenky nebo topu a polib ji na odhalené rameno.",
    "Objímej ji zezadu a líbej na krk, dokud se o tebe sama nezačne otírat zadečkem.",
    "Vezmi ji za ruku, doveď ji do ložnice a cestou ji zastav a polib na třech různých místech bytu.",
    "Líbej ji na břicho těsně nad lemem kalhot nebo kalhotek a zuby ho stáhni o kousek níž.",
    "Posaď ji do křesla, klekni si před ni a masíruj jí lýtka a kolena.|120",
    "Vyjeď rukou po jejím stehně pod sukní nebo nohavicí co nejvýš – a těsně před cílem se zastav.",
    "Polib ji na vnitřní stranu zápěstí, loket a rameno – po jedné ruce nahoru, po druhé dolů.",
    "Stoupni si za ni, polož jí dlaně na prsa přes oblečení a jen je drž, zatímco ji líbáš na krk.|45",
    "Pošeptej jí do ucha, co tě na ní dnes vzrušilo úplně poprvé.",
    "Přejeď jí pírkem pod bradou, po víčkách a po rtech. Pak ji polib.",
    "Rozepni jí zip na zádech, nebo jí vytáhni triko z kalhot zuby.",
    "Nech ji stát uprostřed pokoje a obcházej ji dokola. Dotýkej se jí jen konečky prstů.|60",
    "Opři ji o lednici a líbej ji – záda jí chladí, tak ji zepředu hřej rukama.|60",
    "V koupelně jí pročeš vlasy kartáčem a pak ji polib na šíji.",
    "Zavaž jí oči. Ona řekne místo nad pasem a ty ho políbíš. Tři kola.",
    "Posaď ji na pračku a líbej ji, s rukama na jejích stehnech.|60",
    "Sundej jí ponožky nebo punčochy zuby.",
    "Lehni si vedle ní a hraj si s jejími vlasy, zatímco jí šeptáš, jak je krásná.|60",
    "Stáhni jí kalhoty, ale nech ji v kalhotkách. Polib ji zezadu na obě stehna těsně pod zadečkem.",
    "Pomalu ji olízni od ramene po ucho a jemně ji chytni za vlasy u kořínků.",
    "Posaď ji na gauč a lehni si hlavou na její stehna. Líbej je přes oblečení.|60",
    "Oblečenou ji přitiskni na posteli a pomalu se o ni otírej celým tělem, jako byste už byli nazí.|60",
    "Svlékni se do spodního prádla a nech se od ní prohlédnout. Otoč se, jak si řekne.",
    "Namaž jí záda olejem a masíruj je dlouhými tahy od beder k ramenům.|180",
    "Rozepni jí podprsenku, ale nesundávej ji. Jen líbej ramena a nech ramínka sklouznout samotná.",
    "Pírkem přejížděj po vnitřní straně jejích stehen, jen přes kalhotky – nahoru a zase dolů.|45",
    "Nabídni jí sklenku něčeho dobrého a zatímco pije, líbej ji na krk.",
    "Posaď se ke kuchyňskému stolu a nech ji stát mezi svými koleny. Líbej jí břicho přes oblečení.|60",
    "Přetáhni jí triko přes hlavu, ale nech jí ho chvíli omotané kolem zápěstí. Pak ji líbej na klíční kosti.",
    "Rukama jí přejížděj po těle a pojmenovávej, co zrovna hladíš – a proč to miluješ.|90",
    "Opři se s ní o dveře ložnice a líbejte se tak, jako byste se neviděli měsíc.|60",
    "Polož jí ruku na krk (bez tlaku), palcem jí přejeď po rtech a polib ji.",
    "Na gauči jí polož nohy do klína a hlaď ji od chodidel až ke kolenům.|90",
    "Stoupni si za ni a pomalu jí rozepni kalhoty. Ruku jí jen polož na podbřišek a nech ji tam.|30",
    "Zavaž jí oči a přejížděj po jejím těle střídavě pírkem a konečky prstů. Ať hádá, co to je.|60",
    "Polib ji na čelo, na víčka, na nos, na tváře – a na rty až úplně nakonec.",
    "Zatímco se ona dívá do zrcadla, sundej jí podprsenku zezadu.",
    "Lehni si na ni zezadu, když leží na břiše, a líbej ji na krk a lopatky.|60",
    "Opři ji o kuchyňskou linku a pomalu jí vyhrň sukni nebo stáhni kalhoty, zatímco ji líbáš.",
    "Přejeď jí kostkou ledu po krku a pak to místo zahřej rty.",
    "Pomalu jí přejížděj prsty po rtech, ona ti je může olíznout. Pak ji polib.",
    "Masíruj jí bedra a boky, ona leží na posteli na břiše.|120",
    "Vyzvi ji k pomalému tanci a přitom ji celou dobu svlékej.|180",
    "Polib ji zezadu na krk, zatímco jí přejíždíš rukama po prsou přes podprsenku.|45",
    "Dej jí pusu na každý prst na noze. Když se bude smát, začni znova.",
    "Zatímco sedí na gauči, klekni si před ni a hlaď jí stehna od kolen nahoru – přes oblečení, pomalu.|60",
    "Sundávej jí kalhotky jen pomalu a jen o kousek – a zase je vrať zpátky. Dvakrát.",
    "Přejeď pírkem po jejích prsou přes podprsenku, kolem dokola.|45",
    "Pošeptej jí, jak voní, a nasaj její vůni za uchem a na krku.",
    "Nech ji sedět na židli. Obejdi ji zezadu, rozpusť jí vlasy a masíruj jí spánky.|90",
    "Zvedni ji na kuchyňský stůl, obejmi ji jejími nohama kolem sebe a líbej ji.|60",
    "Na posteli jí pomalu líbej podkolenní jamky.",
    "Jazykem jí jemně olízni rty, ale nenech ji tě políbit. Škádli ji tak ještě chvíli.|30",
    "Posaď se na zem opřený o gauč a nech ji, ať si sedne na tebe. Hlaď ji po zádech pod oblečením.|90",
    "Zavaž jí oči a pomalu ji svleč do spodního prádla. Každou věc jí vezmi až po polibku.",
    "Líbej jí záda od lopatek až k bedrům a na každém konci jemně kousni.",
    "Pusť jí vodu do sprchy, svlékni ji a omyj jí záda mýdlem nebo sprchovým gelem.|120",
    "Přitiskni se k ní zezadu v kuchyni, když něco dělá, a nenápadně jí přejeď rukou po prsou.",
    "Olízni jí vnitřní stranu zápěstí a foukni na to místo.",
    "Na chodbě ji zastav, chyť jemně za bradu a dlouze ji polib.",
    "Na posteli ji pomalu hlaď po břiše kolem pupíku, s každým kolečkem trochu níž – ale ne pod lem kalhotek.|60",
    "Ať si lehne na záda. Přejížděj jí pírkem přes chodidla, lýtka a kolena.|60",
    "Pověz jí, co by sis dnes přál, aby ti udělala – a slib, že jí to vrátíš dvojnásob.",
    "Opři ji o skříň a líbej ji na výstřih, zatímco jí přejíždíš palci po bocích.|45",
    "Klekni si a svlékni jí kalhoty zespodu – nejdřív jednu nohavici, pak druhou, s polibkem na každé stehno.",
    "Namasíruj jí dlaně a prsty – každý zvlášť, pomalu.|90",
    "Hlaď jí vlasy a lehce za ně zatáhni, aby se jí zaklonila hlava. Pak ji polib na odhalený krk.",
    "Nech ji ležet na gauči a lehni si vedle ní. Palcem kresli malá kolečka na jejím boku pod tričkem.|60",
  ],

  // Úkoly pro ženu – pro potěšení muže
  female: [
    "Posaď se mu obkročmo na klín na gauči a pomalu ho líbej, zatímco mu prsty hladíš vlasy.|90",
    "Přejížděj mu pírkem po krku, hrudi a břiše. On má celou dobu zavřené oči.|60",
    "Pošeptej mu do ucha, co tě na něm nejvíc vzrušuje – a pak ho kousni do ušního lalůčku.",
    "Sundej mu triko co nejpomaleji a každý odhalený kousek kůže polib.",
    "Opři ho o zeď v chodbě, přitiskni se k němu a líbej ho na krk.|60",
    "Udělej mu masáž ramen a šíje, zatímco sedí na židli v kuchyni.|120",
    "Rozepni mu košili nebo mikinu zuby – nebo aspoň první knoflík.",
    "Svlékni se před ním do spodního prádla. Pomalu. On se jen dívá a nesmí se hnout.|90",
    "Hlaď ho po vnitřní straně stehen přes kalhoty a dívej se mu přitom do očí. Nikam dál.|60",
    "Zavaž mu oči šátkem a polib ho na pět míst podle sebe. Ať hádá, kam přijde další polibek.",
    "Líbej ho jen na rty – ale nesmíš se ho dotknout rukama.|60",
    "Posaď ho do křesla a tancuj před ním na jednu písničku. Dotýkat se tě nesmí.|180",
    "Klekni si za něj na posteli a masíruj mu záda.|120",
    "Stáhni mu kalhoty a polib ho na obě stehna – přes boxerky se ani nedotkni.",
    "Přejeď mu jazykem po krku od klíční kosti k uchu. Hodně pomalu.",
    "Posaď se na kuchyňskou linku, přitáhni si ho mezi kolena a obejmi ho nohama.|60",
    "Přitiskni se k němu zezadu a hlaď ho po hrudi a břiše pod tričkem.|60",
    "Vezmi jeho ruku a polož si ji tam, kde se chceš nechat hladit – nad pasem.",
    "Masíruj mu hlavu – prsty ve vlasech, pomalu, on má zavřené oči.|90",
    "Stáhni mu ponožky a polib ho na nárt. Pak ho hlaď po lýtkách.",
    "Obkroč ho, když leží na zádech, a líbej mu hrudník. Vlasy ať ho šimrají na kůži.|60",
    "Pomalu mu rozepni pásek a kalhoty – a pak se věnuj jen jeho krku.",
    "Pošeptej mu svou nejtajnější fantazii, ve které hraje hlavní roli on.",
    "Pírkem mu opisuj kolečka kolem bradavek a pupíku.|45",
    "Posaď ho na gauč, lehni si mu hlavou do klína a hlaď ho po stehnech.|60",
    "Polib ho na zátylek a jemně ho chytni za vlasy.",
    "Kousej ho jemně do krku a ramen – střídej to s polibky.|60",
    "Nech ho sedět na židli a sedni si mu na klín zády k němu. Pomalu se o něj otírej.|45",
    "Přejeď mu nehty lehce po zádech – shora dolů, pomalu.|30",
    "Polib ho na každý prst na ruce a jemně mu olízni dlaň.",
    "Postav se před zrcadlo a nech ho, ať se dívá, jak si svlékáš podprsenku.",
    "Dej si kousek čokolády nebo ovoce mezi rty a nech ho, ať si ho vezme polibkem.",
    "Dotýkej se ho jen dechem – foukej mu na krk, hruď, břicho a stehna.|60",
    "Lehni si na něj na posteli, propleť s ním prsty nad jeho hlavou a líbej ho.|60",
    "Svlékni mu jednu věc podle svého výběru a místo, které se odhalí, líbej.|20",
    "Pusť pomalou písničku a tancuj s ním v obýváku přitisknutá co nejvíc to jde.|120",
    "Zašeptej mu, co s ním chceš dělat v ložnici – a jednu věc hned předveď.",
    "Namaž mu záda olejem a masíruj je dlouhými tahy.|180",
    "Opři se o kuchyňskou linku, chyť ho za tričko a přitáhni si ho k polibku.",
    "Napiš mu prstem na záda slovo. Když ho uhodne, dostane polibek, kam si řekne (nad pasem).",
    "Rozepni si pomalu halenku nebo sundej triko, zatímco sedí na gauči a jen se dívá.|60",
    "Klekni si před něj, když sedí, a hlaď ho po stehnech od kolen nahoru – jen přes kalhoty.|60",
    "Obejmi ho zezadu v kuchyni a zajeď mu rukama do kapes kalhot.",
    "Polib ho na čelo, víčka, nos, tváře – a rty až úplně nakonec.",
    "Líbej ho na břicho těsně nad pasem a zuby mu stáhni boxerky o kousek níž.",
    "Zavaž mu oči a přejížděj po jeho těle střídavě pírkem a konečky prstů. Ať hádá, co to je.|60",
    "Oblečená si na něj lehni na posteli a pomalu se o něj otírej celým tělem.|60",
    "Nech ho ležet na břiše. Polib každý jeho obratel od krku dolů.",
    "Sedni si na pračku, přitáhni si ho mezi nohy a líbej ho.|60",
    "Stáhni mu triko přes hlavu, ale nech mu ho chvíli omotané kolem zápěstí. Pak ho líbej na hrudník.",
    "Posaď se na podlahu opřená o gauč a nech ho, ať si lehne hlavou do tvého klína. Hlaď ho ve vlasech a po hrudi.|90",
    "Přejeď mu kostkou ledu po krku a pak to místo zahřej rty.",
    "Nech ho sedět na posteli a svlékni se před ním do spodního prádla – každou věc hoď po něm.",
    "Namasíruj mu chodidla na gauči.|120",
    "Nech ho stát uprostřed pokoje a obcházej ho dokola. Dotýkej se ho jen konečky prstů.|60",
    "Pošeptej mu, co tě na něm dnes vzrušilo úplně poprvé.",
    "Vytáhni mu triko z kalhot zuby a polib ho na podbřišek.",
    "Přejeď mu palcem po rtech a nech ho, ať ti ho olízne. Pak ho polib.",
    "Opři ho o lednici a líbej ho – záda mu chladí, tak ho zepředu hřej svým tělem.|60",
    "Sedni si na kuchyňský stůl, obtoč mu nohy kolem pasu a přitáhni si ho k dlouhému polibku.|60",
    "Vezmi ho za ruku, doveď ho do ložnice a cestou ho zastav a polib na třech různých místech bytu.",
    "Přejížděj mu prsty po stehně přes kalhoty čím dál výš – a těsně před cílem se zastav.",
    "Zatímco sedí na židli, stoupni si za něj, obejmi ho a rukama mu přejížděj po hrudi.|45",
    "Rozepni si podprsenku, ale nesundávej ji. Nech ho, ať ti pomalu stáhne ramínka.",
    "Polib ho na vnitřní stranu zápěstí, loket a rameno – po jedné ruce nahoru, po druhé dolů.",
    "Pusť mu vodu do sprchy, svlékni ho a umyj mu záda.|120",
    "Posaď se mu na klín čelem k němu a pomalu mu rozepínej košili nebo mikinu.",
    "Nech ho sedět na gauči. Lehni si vedle něj a palcem mu kresli kolečka na boku pod tričkem.|60",
    "Nakloň se k němu, jako bys ho chtěla políbit, ale na poslední chvíli uhni. Škádli ho tak třikrát a pak ho polib.",
    "Zavaž mu oči a pomalu ho svleč do spodního prádla. Každou věc mu vezmi až po polibku.",
    "Líbej mu záda od lopatek až k bedrům a na konci ho jemně kousni.",
    "Namaž mu nohy olejem od kotníků až ke kolenům.|120",
    "Stáhni mu kalhoty, ale nech ho v boxerkách. Polib ho na podbřišek těsně nad jejich lemem.",
    "Jazykem mu jemně olízni rty, ale nenech ho, ať tě políbí. Škádli ho tak ještě chvíli.|30",
    "Pírkem mu přejížděj po vnitřní straně stehen přes boxerky – nahoru a zase dolů.|45",
    "Sedni si na gauč a polož mu nohy do klína. Pomalu jimi hlaď jeho stehna.|45",
    "Zatímco se dívá, přejeď si rukama po celém těle přes oblečení.|45",
    "Obejmi ho kolem krku a nech se od něj odnést do ložnice. Pokud to nejde, doveď ho tam ty a cestou ho líbej.",
    "Dej mu pusu na každý prst u nohy. Když se bude smát, začni znova.",
    "Chyť ho za zadek a přitáhni si ho k sobě na dlouhý polibek.",
    "Posaď ho na židli, stoupni si mu mezi kolena a nech ho líbat tvoje břicho – ruce musí mít za opěradlem.|60",
    "Přejeď mu rukou po hrudi pod tričkem a zastav se na bradavce. Jemně ji stiskni.",
    "Olízni mu vnitřní stranu zápěstí a foukni na to místo.",
    "Na chodbě ho zastav, chyť ho jemně za bradu a dlouze ho polib.",
    "Zatímco leží, hlaď ho po břiše kolem pupíku, s každým kolečkem trochu níž – ale ne pod lem boxerek.|60",
    "Pověz mu, co by sis dnes přála, aby ti udělal – a slib, že mu to vrátíš dvojnásob.",
    "Opři ho o skříň, přitiskni se k němu stehnem mezi jeho nohy a líbej ho na krk.|45",
    "Nech ho sedět v křesle. Postav se za něj, rozcuchej mu vlasy a masíruj mu spánky.|90",
    "Lehni si na břicho do postele jen ve spodním prádle a nech ho, ať se dívá. Po minutě ho zavolej k sobě.",
    "Přetáhni si přes hlavu jeho triko, obleč si ho na holé tělo a nech ho, ať ti ho zase sundá.",
    "Na gauči mu polož ruce na hruď, pomalu je sjeď až na pásek a zase zpátky.|30",
    "Hlaď ho po zátylku a lehce mu zatáhni za vlasy, aby zaklonil hlavu. Polib ho na odhalený krk.",
    "Posaď se mu na klín na židli a pomalu mu šeptej, jak moc tě vzrušuje.|45",
    "Klekni si za něj na posteli a hlaď ho po hrudi, zatímco ho líbáš na šíji.|60",
    "Svlékni mu ponožky zuby.",
    "Lehni si vedle něj a pomalu mu přejížděj nehtem po stehně přes kalhoty – nahoru a dolů.|45",
    "Postav se k oknu se zataženými závěsy, přitáhni si ho za sebe a veď jeho ruce po svém těle.|60",
    "Nabídni mu sklenku něčeho dobrého a zatímco pije, líbej ho na krk.",
    "Vyber 7 míst na jeho těle, která jsou podle tebe nejvíc sexy. U každého řekni proč a polib ho.",
    "Namasíruj mu dlaně a prsty – každý zvlášť, pomalu.|90",
    "Zul se a bosou nohou ho pod stolem pomalu hlaď po lýtku až ke kolenu.|30",
    "Opři se zády o něj, když stojí, a pomalu se o něj otírej zadečkem.|30",
    "Zatímco sedí, klekni si na gauč vedle něj a líbej ho na ucho a krk. Ruku mu polož na stehno.|60",
    "Vezmi jeho dlaně a pomalu je veď po svých bocích a stehnech přes oblečení.|45",
    "Lehni si na něj, když leží na břiše, a líbej ho na krk a lopatky.|60",
    "V koupelně mu pomalu namaž tvář krémem po holení – zblízka, s pohledem do očí a polibkem na konci.",
    "Posaď se na zem mezi jeho nohy, když sedí na gauči, a hlaď ho po lýtkách a stehnech.|60",
    "Přitiskni se k němu v kuchyni zezadu, když něco dělá, a nenápadně mu sjeď rukou po zadku.",
    "Svlékni ho do boxerek, ale sama zůstaň oblečená. Pomalu ho obejdi a prohlédni si ho.",
    "Přejeď mu pírkem pod bradou, po víčkách a po rtech. Pak ho polib.",
    "Na posteli se k němu přitul a jemně mu kousej a líbej ucho, dokud se neotočí.",
    "Namaž mu hrudník olejem a pomalu ho roztírej.|90",
    "Sedni si mu obkročmo na stehna, když leží, a jen pomalu přejížděj rukama po jeho těle.|60",
  ],
});
