// Kategorie 1 – Škádlení a předehra (dávka e)
// Témata: pravidla a hry, počítané výzvy, roleplay, špinavé řeči, čekání a odpírání.
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 1,

  male: [
    "Ruce za zády: Celou dobu máš ruce za zády. Smíš používat jen rty, jazyk a dech. Cíl: dostat ji do bodu, kdy sáhne po tobě.|180",
    "Kostka určí čas: Hoď kostkou a tolik minut se věnuj jen jednomu místu, které si vybere ona. Cíl: neodejít odtamtud ani o vteřinu dřív.|180",
    "Sto doteků: Dotkni se jí stokrát. Ona počítá nahlas. Když ztratí počet, začínáte znovu. Cíl: dojít do sta.|300|vedle_ona_lezi",
    "Nehýbat se: Hlaď ji a líbej, ale ona se nesmí pohnout. Za každý pohyb přestáváš na deset vteřin. Cíl: tři minuty a nejvýš dvě pauzy.|180|vedle_ona_lezi",
    "Jako bychom se neznali: Zahrajte si, že se vidíte poprvé. Buď zdvořilý a pomalý. Cíl: čtyři minuty v roli a ani jednou z ní nevypadnout.|240",
    "Placený masér: Zahraj jí maséra, kterého si zaplatila. Mluv jako cizí člověk a dělej přesně to, co si objedná. Cíl: pět minut v roli.|300|masaz_zada",
    "Deset sprostých vět: Řekni jí deset sprostých vět za sebou. Cíl: za každou, u které se někdo z vás zasměje, si sundáš kus oblečení.|180",
    "Špinavé řeči: Popisuj jí nahlas, co s ní děláš, přímo když to děláš. Ani na chvíli neztichni. Cíl: nepřestat mluvit.|180|vedle_ona_lezi",
    "Až řekne prosím: Líbej ji kamkoli chceš, jen ne na ústa. Cíl: nepolíbit ji na ústa, dokud sama neřekne prosím.|180",
    "Tři otázky, tři kusy: Zeptej se jí na tři věci a za každou odpověď jí sundej jeden kus oblečení. Cíl: ptát se tak, aby odpověděla na všechny.|120",
    "Tři možnosti: Dej jí tři možnosti, co jí uděláš, a nech ji vybrat. Cíl: udělat to tak pomalu, že tě bude muset popohnat.|180",
    "Dvě minuty čekání: Řekni jí, co jí uděláš, a pak dvě minuty nedělej vůbec nic. Jen se na ni dívej. Cíl: vydržet celé dvě minuty.|120",
    "Ruce v kravatě: Svaž jí ruce kravatou na uzel, co povolí jedním tahem, a svlékej ji. Cíl: tři minuty a ona se nebrání.|180|klek_ruce_za_zady",
    "Souboj o přání: Vyzvi ji na souboj pohledů, kdo dřív uhne. Cíl: poražený splní jedno přání vítěze, ještě než skončí tahle úroveň.|120|sed_celem",
    "Teplo a zima: Pokládej jí ruce na tělo a ona říká jen teplo, nebo zima. Cíl: najít to místo nejvýš na deset pokusů.|180|vedle_ona_lezi",
    "Ani hlásku: Dej jí jedno pravidlo – nesmí vydat ani hlásku. Pak dělej všechno pro to, aby ho porušila. Cíl: rozmluvit ji do tří minut.|180|vedle_ona_lezi",
    "Pět minut jen na krk: Celých pět minut se věnuj výhradně jejímu krku a uším. Nikam jinam. Cíl: nesjet níž ani jednou.|300|stoje_zezadu",
    "Zakázané slovo: Zeptej se jí, jaké slovo dneska nesmíš říct, a pak mluv tak, abys mu byl pořád blízko. Cíl: neříct ho celou úroveň.|120",
    "Šéf a asistentka: Zadávej jí drobné úkoly a nahlas hodnoť, jak je plní. Cíl: pět úkolů a u každého jedna známka od jedné do deseti.|240",
    "Dvě minuty bez rukou: Dej jí dvě minuty na to, aby tě vzrušila, ale rukama se tě nesmí dotknout. Cíl: vydržet a nesáhnout po ní první.|120",
    "Pomalé odpočítávání: Řekni jí, že za šedesát vteřin ji políbíš, a nahlas počítej. Do té doby se jí nedotkneš. Cíl: dodržet to na vteřinu.|60",
    "Zakázané místo: Vyber jedno místo na jejím těle, kterého se dneska nesmí dotknout nikdo z vás. Cíl: dodržet to až do konce úrovně.|60",
    "Tři za tři: Nech ji vyjmenovat tři věci, které nesnáší, a ty jí místo nich uděláš tři, které má ráda. Cíl: všechny tři ještě dneska.|180",
    "Jedna ruka drží, druhá hladí: Drž jí obě zápěstí nad hlavou jednou rukou a druhou ji hlaď. Cíl: tři minuty a ani jednou ji nepustit.|180|vedle_ona_lezi",
    "Sbalit ji znovu: Hraj, že jsi ji právě potkal na baru, a sbal ji, jako by o tobě nic nevěděla. Cíl: dotáhnout to až k prvnímu polibku.|240|sed_celem",
    "Slova bez doteku: Šeptej jí sprosťárny do ucha a vůbec se jí u toho nedotýkej. Cíl: dvě minuty a nechat ji, ať po tobě sáhne první.|120",
    "Střídavá hra: Dvacet vteřin ji dráždíš, dvacet vteřin nic. A tak dokola pět kol. Cíl: vydržet všech pět kol.|240|vedle_ona_lezi",
    "Hodný, nebo drzý: Nech ji vybrat, jestli máš být hodný, nebo drzý. Cíl: držet se její volby celé tři minuty, ať tě zkouší, jak chce.|180",
    "Klekni a čekej: Poruč jí, ať si klekne a počká, zatímco ty jen stojíš a díváš se. Cíl: půldruhé minuty a nedotknout se jí dřív.|90|klek_ruce_za_zady",
    "Tři příkazy: Dej jí tři jednoduché příkazy za sebou a sleduj, jak rychle je splní. Cíl: každý musí být splněný do deseti vteřin.|120",
    "Cizinec s otázkami: Hraj cizince, který se v ní snaží vyznat, a ptej se na všechno, co má ráda. Cíl: deset otázek a u každé počkat na odpověď.|240|sed_celem",
    "Souboj o tempo: Ona určuje, jak rychle se hýbeš, jediným slovem – rychleji nebo pomaleji. Ty musíš poslechnout. Cíl: ani jednou neudělat něco po svém.|180|vedle_ona_lezi",
    "Dostane to druhé: Nech ji vybrat mezi polibkem a masáží a pak jí dej přesně to, co si nevybrala. Cíl: udělat to tak dobře, že si nestěžuje.|120",
    "Řekne kde: Oznam jí, že se jí nesmíš dotknout, dokud sama neřekne kde a jak. Pak čekej. Cíl: vydržet a nesáhnout po ní první.|120",
    "Jméno za polibek: Kdykoli během úkolu řekne tvoje jméno, dostane polibek. Cíl: dělat všechno pro to, aby ho řekla aspoň pětkrát.|180",
    "Led v dlani: Dej jí do ruky kostku ledu a líbejte se. Cíl: nepřestat, dokud jí led v dlani úplně neroztaje.|120|objeti",
    "Poslední tři slova: Smíš dneska říct už jen tři slova. Vyber je dobře a zbytek ukaž rukama. Cíl: vystačit si se třemi slovy.|180",
    "Rty, nebo prst: Střídej doteky rty a prstem, ona má zavřené oči a pokaždé hádá. Cíl: deset doteků a splést ji aspoň třikrát.|120|vedle_ona_lezi",
    "Nakresli jí prstem na stehno čáru a řekni, že přes ni dneska nesmíš. Zatím.|60",
    "Hraj, že jsi její soused, kterého si pozvala na skleničku. Zůstaň v roli až do konce.|300",
    "Dej jí seznam pěti věcí a ona vyškrtne dvě, které dneska nechce. Zbytek jí uděláš.|180",
    "Pomalu, ale bez pauzy: Dotýkej se jí tři minuty naprosto plynule, aniž bys ruku jednou zvedl z kůže. Cíl: ani jedno přerušení.|180|vedle_ona_lezi",
    "Nech ji, ať ti řekne jednu drzou větu. Ty jí na ni odpovíš činem.|90",
    "Řekni jí, že dneska rozhoduješ ty. Pak jí dej první rozkaz – hodně mírný.|60",
    "Poruč jí, ať si sama sundá jeden kus oblečení, a pak jí poděkuj polibkem.|60|tanec",
    "Dvě kostky: Hoď kostkou dvakrát – první číslo určí místo od hlavy dolů, druhé počet minut. Cíl: vydržet u toho místa přesně tak dlouho.|180",
    "Dej jí tři vteřiny na odpověď: co chce právě teď? Když zaváhá, rozhodneš ty.|60",
    "Jenom dech: Celou minutu ji dráždi jen tím, že jí dýcháš na kůži. Žádný dotek. Cíl: ať se jí zježí chlupy na rukou.|60|vedle_ona_lezi",
    "Nech ji klečet před tebou a jen ji hlaď po vlasech. Nic víc dneska nebude.|120|oral_ona_klek",
    "Řekni jí větu, kterou by od tebe nikdy nečekala, a pak ji polib, než stihne zareagovat.|60",
    "Dnes se rozhoduje hlasováním: navrhni tři věci a ona jednu odmítne. Zbylé dvě uděláte.|120",
    "Vyzvi ji, ať tě vzruší jen slovy. Nesmí se hnout z místa.|120|sed_celem",
    "Hra na žárlivost: Popiš jí, co by udělal někdo jiný, a pak jí ukaž, jak to děláš ty. Cíl: ať uzná, že ty líp.|180",
    "Zakaž jí mluvit a nech ji, ať ti rukou ukáže, co chce.|180|vedle_ona_lezi",
    "Nech ji vybrat si mezi tím, že budeš pomalý, nebo že budeš neodbytný.|60",
    "Za každý úsměv během tohoto úkolu jí dáš polibek. Snaž se ji rozesmát.|120",
    "Dej jí dvě minuty, aby ti řekla všechno, co chce dneska zkusit. Ty jen posloucháš.|120|sed_celem",
    "Stopka: Hlaď ji a líbej, ale kdykoli řekne stop, přestaneš a počkáš pět vteřin. Cíl: tři minuty a ani jednou pravidlo neporušit.|180|vedle_ona_lezi",
    "Pošeptej jí do ucha jednu věc, kterou uděláš, až tahle úroveň skončí. A drž slovo.|45",
    "Poruč jí, ať se na tebe celou minutu jen dívá a nesmí se dotknout.|60|sed_celem",
    "Nech ji hádat, na co myslíš. Za každý špatný tip jí sundáš kus oblečení.|180",
    "Vyber jí jedno slovo, které dneska bude znamenat víc. Řekni jí ho a pak ho použij.|60",
    "Tři a dost: Smíš se jí dotknout jen třikrát, ale každý dotek může trvat, jak dlouho chceš. Cíl: vybrat ta správná tři místa.|240|vedle_ona_lezi",
    "Zahrajte si na fotografa a modelku. Ty ji aranžuješ, ona poslouchá.|240",
    "Dej jí přesně minutu, ať si sama rozhodne, co ti dovolí. Pak se ptát nebudeš.|60",
    "Řekni jí nahlas, co se ti honilo hlavou dneska, když jsi na ni myslel v práci.|90",
    "Dej jí do ruky svoje zápěstí a nech ji, ať tě vede tam, kam chce.|120|vedle_ona_lezi",
    "Nech ji vybrat kus oblečení, který ti dneska zůstane. A ten na tobě opravdu zůstane.|60",
    "Pět otázek: Zeptej se jí na pět věcí a za každé ano si sundáš jeden kus oblečení. Cíl: skončit nahý.|180|sed_celem",
    "Hraj, že máte jen pět minut, než někdo přijde. Chovej se podle toho.|300",
    "Šeptej jí do ucha a mezi větami ji vždycky krátce políbíš na krk.|120|stoje_zezadu",
    "Řekni jí, co se ti na ní dneska líbilo nejvíc, a polib to místo třikrát.|60",
    "Nech ji, ať ti zaváže oči, a pak se nech od ní vodit. Ty nesmíš mluvit.|180",
    "Zakážeš jí zavřít oči. Musí se dívat na všechno, co jí děláš.|180|vedle_ona_lezi",
    "Deset a deset: Deset vteřin ji líbáš, deset vteřin se na ni jen díváš. Šest kol. Cíl: vydržet pauzy.|120|objeti",
    "Postav ji před sebe a nech ji hádat, kam ji políbíš. Když uhodne, polibek dostane jinam.|120",
    "Vyzvi ji, ať ti popíše svoji nejlepší vzpomínku s tebou v posteli. Do detailu.|180|sed_celem",
    "Kdo dneska velí: Dej jí na výběr, jestli bude poslouchat, nebo rozhodovat. Cíl: držet se její volby až do konce úrovně.|60",
    "Slib na konec večera: Slib jí jednu konkrétní věc na konec večera a pak jí ji připomínej. Cíl: připomenout jí ji aspoň pětkrát.|90",
    "Řekni jí, že jediné, co dneska chceš, je dívat se, jak se jí to líbí.|60",
    "Oči v očích: Dotýkej se jí, ale ani na vteřinu nesmíš uhnout pohledem z jejích očí. Cíl: vydržet celý úkol.|180|sed_celem",
    "Zeptej se jí, co by chtěla, abys jí zakázal. A zakaž jí to.|90",
    "Nech ji sedět na tvém klíně zády a nedělej vůbec nic. Jen ji drž.|120|klin_zady",
    "Pět vteřin na výběr: Dej jí pět vteřin, ať si vybere místo, které dneska dostane nejvíc pozornosti. Cíl: minutu se věnovat jen jemu.|60",
    "Řekni jí, ať tě požádá o to, co chce, celou větou a nahlas. Teprve pak jí to dáš.|90",
  ],

  female: [
    "Ruce za zády: Celou dobu máš ruce za zády. Smíš používat jen rty, jazyk a dech. Cíl: dostat ho do bodu, kdy sáhne po tobě.|180",
    "Kolik padne: Hoď kostkou a tolik minut se věnuj jen jednomu místu, které si vybere on. Cíl: neodejít odtamtud ani o vteřinu dřív.|180",
    "Sto doteků: Dotkni se ho stokrát. On počítá nahlas. Když ztratí počet, začínáte znovu. Cíl: dojít do sta.|300|vedle_on_lezi",
    "Ani se nehni: Hlaď ho a líbej, ale on se nesmí pohnout. Za každý pohyb přestáváš na deset vteřin. Cíl: tři minuty a nejvýš dvě pauzy.|180|vedle_on_lezi",
    "Jako cizí lidé: Zahrajte si, že se vidíte poprvé. Buď odměřená a nech ho, ať si tě musí získat. Cíl: čtyři minuty v roli a nevypadnout z ní.|240",
    "Placená masérka: Zahraj mu masérku, kterou si zaplatil. Mluv jako cizí člověk a dělej přesně to, co si objedná. Cíl: pět minut v roli.|300|masaz_zada!",
    "Deset vět bez smíchu: Řekni mu deset sprostých vět za sebou. Cíl: za každou, u které se někdo z vás zasměje, si sundáš kus oblečení.|180",
    "Špinavé řeči: Popisuj mu nahlas, co s ním děláš, přímo když to děláš. Ani na chvíli neztichni. Cíl: nepřestat mluvit.|180|vedle_on_lezi",
    "Dokud neřekne prosím: Líbej ho kamkoli chceš, jen ne na ústa. Cíl: nepolíbit ho na ústa, dokud sám neřekne prosím.|180",
    "Odpověď za kus: Zeptej se ho na tři věci a za každou odpověď mu sundej jeden kus oblečení. Cíl: ptát se tak, aby odpověděl na všechny.|120",
    "Tři na výběr: Dej mu tři možnosti, co mu uděláš, a nech ho vybrat. Cíl: udělat to tak pomalu, že tě bude muset popohnat.|180",
    "Dvě minuty čekání: Řekni mu, co mu uděláš, a pak dvě minuty nedělej vůbec nic. Jen se na něj dívej. Cíl: vydržet celé dvě minuty.|120",
    "Kravata na jeho rukou: Svaž mu ruce kravatou na uzel, co povolí jedním tahem, a svlékej ho. Cíl: tři minuty bez obrany.|180|klek_ruce_za_zady!",
    "Souboj o splněné přání: Vyzvi ho na souboj pohledů, kdo dřív uhne. Cíl: poražený splní jedno přání vítěze ještě dneska.|120|sed_celem",
    "Přihořívá: Pokládej mu ruce na tělo a on říká jen teplo, nebo zima. Cíl: najít to místo nejvýš na deset pokusů.|180|vedle_on_lezi",
    "Ticho po celou dobu: Dej mu jedno pravidlo – nesmí vydat ani hlásku. Pak dělej všechno pro to, aby ho porušil. Cíl: rozmluvit ho do tří minut.|180|vedle_on_lezi",
    "Pět minut jen na krk: Celých pět minut se věnuj výhradně jeho krku a uším. Nikam jinam. Cíl: nesjet níž ani jednou.|300|objeti",
    "Slovo, co nesmí padnout: Zeptej se ho, jaké slovo dneska nesmíš říct, a pak mluv tak, abys mu byla pořád blízko. Cíl: neříct ho celou úroveň.|120",
    "Šéfová a asistent: Zadávej mu drobné úkoly a nahlas hodnoť, jak je plní. Cíl: pět úkolů a u každého jedna známka od jedné do deseti.|240",
    "Dvě minuty a ruce pryč: Dej mu dvě minuty na to, aby tě vzrušil, ale rukama se tě nesmí dotknout. Cíl: vydržet a nesáhnout po něm první.|120",
    "Pomalé odpočítávání: Řekni mu, že za šedesát vteřin ho políbíš, a nahlas počítej. Do té doby se ho nedotkneš. Cíl: dodržet to na vteřinu.|60",
    "Místo mimo hru: Vyber jedno místo na jeho těle, kterého se dneska nesmí dotknout nikdo z vás. Cíl: dodržet to až do konce úrovně.|60",
    "Tři místo tří: Nech ho vyjmenovat tři věci, které nesnáší, a ty mu místo nich uděláš tři, které má rád. Cíl: všechny tři ještě dneska.|180",
    "Držet a hladit: Drž mu obě zápěstí nad hlavou jednou rukou a druhou ho hlaď. Cíl: tři minuty a ani jednou ho nepustit.|180|vedle_on_lezi",
    "Nech se sbalit: Hraj, že tě právě potkal na baru, a nech se sbalit, jako bys o něm nic nevěděla. Cíl: dotáhnout to až k prvnímu polibku.|240|sed_celem",
    "Jen slova: Šeptej mu sprosťárny do ucha a vůbec se ho u toho nedotýkej. Cíl: dvě minuty a nechat ho, ať po tobě sáhne první.|120",
    "Střídavá hra: Dvacet vteřin ho dráždíš, dvacet vteřin nic. A tak dokola pět kol. Cíl: vydržet všech pět kol.|240|vedle_on_lezi",
    "Hodná, nebo drzá: Nech ho vybrat, jestli máš být hodná, nebo drzá. Cíl: držet se jeho volby celé tři minuty, ať tě zkouší, jak chce.|180",
    "Na kolenou a čekat: Poruč mu, ať si klekne a počká, zatímco ty jen stojíš a díváš se. Cíl: půldruhé minuty a nedotknout se ho dřív.|90|klek_ruce_za_zady",
    "Tři rozkazy: Dej mu tři jednoduché příkazy za sebou a sleduj, jak rychle je splní. Cíl: každý musí být splněný do deseti vteřin.|120",
    "Cizinka s otázkami: Hraj cizinku, která se v něm snaží vyznat, a ptej se na všechno, co má rád. Cíl: deset otázek a u každé počkat na odpověď.|240|sed_celem",
    "Souboj o tempo: On určuje, jak rychle se hýbeš, jediným slovem – rychleji nebo pomaleji. Ty musíš poslechnout. Cíl: ani jednou neudělat něco po svém.|180|vedle_on_lezi",
    "Dostane to nevybrané: Nech ho vybrat mezi polibkem a masáží a pak mu dej přesně to, co si nevybral. Cíl: udělat to tak dobře, že si nestěžuje.|120",
    "Musí říct kde: Oznam mu, že se ho nesmíš dotknout, dokud sám neřekne kde a jak. Pak čekej. Cíl: vydržet a nesáhnout po něm první.|120",
    "Za jméno polibek: Pokaždé, když během úkolu vysloví tvoje jméno, dostane polibek. Cíl: dělat všechno pro to, aby ho řekl aspoň pětkrát.|180",
    "Led v jeho dlani: Dej mu do ruky kostku ledu a líbejte se. Cíl: nepřestat, dokud mu led v dlani úplně neroztaje.|120|objeti",
    "Tři slova a dost: Do konce úkolu smíš vyslovit jen tři slova, všechno ostatní ukaž rukama. Cíl: vystačit si s nimi.|180",
    "Rty, nebo prsty: Střídej doteky rty a prstem, on má zavřené oči a pokaždé hádá. Cíl: deset doteků a splést ho aspoň třikrát.|120|vedle_on_lezi",
    "Čára na stehně: Nakresli mu prstem na stehno čáru a oznam, že přes ni dneska nesmíš. Cíl: dojet k ní pětkrát a ani jednou ji nepřekročit.|60",
    "Sousedka na skleničku: Hraj, že jsi jeho sousedka, kterou si pozval na skleničku. Cíl: pět minut v roli a ani jednou z ní nevypadnout.|300",
    "Pět minus dvě: Dej mu seznam pěti věcí a nech ho vyškrtnout dvě, které dneska nechce. Cíl: zbylé tři mu opravdu udělat.|180",
    "Pomalu, ale bez pauzy: Dotýkej se ho tři minuty naprosto plynule, aniž bys ruku jednou zvedla z kůže. Cíl: ani jedno přerušení.|180|vedle_on_lezi",
    "Odpověď činem: Nech ho říct jednu drzou větu a odpověz mu na ni činem, ne slovy. Cíl: tři věty a tři odpovědi bez jediného slova.|90",
    "Dneska velíš ty: Oznam mu, že dneska rozhoduješ ty, a dej mu první rozkaz – hodně mírný. Cíl: tři rozkazy, každý o kousek odvážnější.|60",
    "Kus za polibek: Poruč mu, ať si sám sundá jeden kus oblečení, a pak mu poděkuj polibkem. Cíl: tři kusy, tři poděkování.|60|tanec",
    "Hoď si kostkou dvakrát – první hod určí místo odshora dolů, druhý počet minut, které mu tam věnuješ.|180",
    "Dej mu tři vteřiny na odpověď: co chce právě teď? Když zaváhá, rozhodneš ty.|60",
    "Jenom dech: Celou minutu ho dráždi jen tím, že mu dýcháš na kůži. Žádný dotek. Cíl: ať se mu zježí chlupy na rukou.|60|vedle_on_lezi",
    "Nech ho klečet před tebou a jen mu prohrábni vlasy. Nic víc dneska nebude.|120|oral_ona_klek",
    "Řekni mu větu, kterou by od tebe nikdy nečekal, a pak ho polib, než stihne zareagovat.|60",
    "Dnes se rozhoduje hlasováním: navrhni tři věci a on jednu odmítne. Zbylé dvě uděláte.|120",
    "Vyzvi ho, ať tě vzruší jen slovy. Nesmí se hnout z místa.|120|sed_celem",
    "Hra na žárlivost: Popiš mu, co by udělal někdo jiný, a pak mu ukaž, jak to chceš ty. Cíl: ať uzná, že to víš líp.|180",
    "Zakaž mu mluvit a nech ho, ať ti rukou ukáže, co chce.|180|vedle_on_lezi",
    "Nech ho vybrat si mezi tím, že budeš pomalá, nebo že budeš neodbytná.|60",
    "Za každý úsměv během tohoto úkolu mu dáš polibek. Snaž se ho rozesmát.|120",
    "Dej mu dvě minuty, aby ti řekl všechno, co chce dneska zkusit. Ty jen posloucháš.|120|sed_celem",
    "Stopka: Kdykoli řekne stop, přestaneš a počkáš pět vteřin. On to může říct, kolikrát chce. Cíl: ani jednou neporušit pravidlo.|180|vedle_on_lezi",
    "Pošeptej mu do ucha jednu věc, kterou uděláš, až tahle úroveň skončí. A drž slovo.|45",
    "Poruč mu, ať se na tebe celou minutu jen dívá a nesmí se dotknout.|60|sed_celem",
    "Nech ho hádat, na co myslíš. Za každý špatný tip mu sundáš kus oblečení.|180",
    "Vyber mu jedno slovo, které dneska bude znamenat víc. Řekni mu ho a pak ho použij.|60",
    "Tři a dost: Smíš se ho dotknout jen třikrát, ale každý dotek může trvat, jak dlouho chceš. Cíl: vybrat ta správná tři místa.|240|vedle_on_lezi",
    "Zahrajte si na fotografku a modela. Ty ho aranžuješ, on poslouchá.|240",
    "Dej mu přesně minutu, ať si sám rozhodne, co ti dovolí. Pak se ptát nebudeš.|60",
    "Řekni mu nahlas, co se ti honilo hlavou dneska, když jsi na něj myslela přes den.|90",
    "Dej mu do ruky svoje zápěstí a nech ho, ať tě vede tam, kam chce.|120|vedle_on_lezi",
    "Nech ho vybrat kus oblečení, který ti dneska zůstane. A ten na tobě opravdu zůstane.|60",
    "Pět otázek: Zeptej se ho na pět věcí a za každé ano si sundáš jeden kus oblečení. Cíl: skončit nahá.|180|sed_celem",
    "Dělej, jako byste měli jen pět minut, než se někdo vrátí domů. Podle toho se chovej.|300",
    "Šeptej mu do ucha a mezi větami ho vždycky krátce políbíš na krk.|120|objeti",
    "Řekni mu, co se ti na něm dneska líbilo nejvíc, a polib to místo třikrát.|60",
    "Nech ho, ať ti zaváže oči, a pak se nech od něj vodit. Ty nesmíš mluvit.|180",
    "Zakážeš mu zavřít oči. Musí se dívat na všechno, co mu děláš.|180|vedle_on_lezi",
    "Deset a deset: Deset vteřin ho líbáš, deset vteřin se na něj jen díváš. Šest kol. Cíl: vydržet pauzy.|120|objeti",
    "Postav se před něj a nech ho hádat, kam ho políbíš. Když uhodne, polibek dostane jinam.|120",
    "Vyzvi ho, ať ti popíše svoji nejlepší vzpomínku s tebou v posteli. Do detailu.|180|sed_celem",
    "Dej mu na výběr: buď tě bude poslouchat, nebo bude rozhodovat on. Až do konce úrovně.|60",
    "Slib mu něco na konec večera a celou úroveň mu to připomínej.|90",
    "Řekni mu, že jediné, co dneska chceš, je dívat se, jak se mu to líbí.|60",
    "Oči v očích: Dotýkej se ho, ale ani na vteřinu nesmíš uhnout pohledem z jeho očí. Cíl: vydržet celý úkol.|180|sed_celem",
    "Zeptej se ho, co by chtěl, abys mu zakázala. A zakaž mu to.|90",
    "Sedni si mu na klín zády a nedělej vůbec nic. Jen se o něj opři.|120|klin_zady",
    "Dej mu pět vteřin na to, aby si vybral místo, které dneska dostane nejvíc pozornosti.|60",
    "Řekni mu, ať tě požádá o to, co chce, celou větou a nahlas. Teprve pak mu to dáš.|90",
  ],
});
