// Kategorie 1 – Škádlení a předehra (dávka d)
// Témata: pírko, štětec, žínka, led, zavázané oči, masáže a smyslové hry.
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 1,

  male: [
    "Zavaž jí oči a přejeď jí pírkem od krku po kotníky. Ona hádá, kde přesně jsi.|180|vedle_ona_lezi",
    "Vezmi štětec a maluj jí po zádech pomalé kruhy. Ona leží na břiše a nesmí se hnout.|180|masaz_zada",
    "Hádej čím: Zavaž jí oči a dotýkej se jí střídavě pírkem, štětcem a žínkou. Ona hádá. Za každý omyl si sundá kus oblečení. Cíl: tři omyly.|180|vedle_ona_lezi",
    "Vezmi kostku ledu a táhni jí ji po klíční kosti. Roztátou vodu slíbej.|90|vedle_ona_lezi",
    "Střídej horko a zimu: jednu chvíli ji líbej horkými rty, druhou přiložíš led.|180|vedle_ona_lezi",
    "Dej si do pusy kostku ledu a líbej ji tak na krk a na ramena.|120|vedle_ona_lezi",
    "Namoč žínku v teplé vodě a omyj jí záda, ruce a nohy jako v lázni.|180|masaz_zada",
    "Zavaž jí oči a dej jí ochutnat tři různé věci z kuchyně. Za každou uhodnutou dostaneš polibek.|180",
    "Slepá cesta: Zavaž jí oči a veď ji po bytě za ruku. Kde se zastavíš, tam ji políbíš. Cíl: pět zastávek.|180",
    "Rozmasíruj jí olejem ramena a šíji tak, aby jí povolily všechny uzly.|240|masaz_vsede",
    "Masíruj jí hlavu a vlasy tak dlouho, až se jí začnou klížit oči.|180",
    "Vezmi si její chodidlo do klína a palcem jí masíruj plosku od paty ke špičkám.|180|masaz_chodidla",
    "Masáž zad odshora dolů: Začni u krku a skonči u kříže, každý pruh dvakrát. Ruce máš celou dobu naolejované. Cíl: nevynechat ani centimetr.|300|masaz_zada",
    "Masíruj jí ruce – dlaň, každý prst zvlášť, pak zápěstí a předloktí.|180",
    "Zavaž jí oči a nech ji hádat, kterou částí těla se jí dotýkáš. Nos, loket, rty, koleno.|180|vedle_ona_lezi",
    "Pírko po vnitřní straně stehen nahoru a dolů. Nikdy nedojedeš až úplně nahoru.|180|vedle_ona_lezi",
    "Přejeď jí štětcem přes bradavky tak lehce, jak to jen jde. Pak přestaň a chvíli nic.|120|vedle_ona_lezi",
    "Ledová stopa: Táhni jí kostku ledu od krku dolů mezi prsy až k pupíku a stopu slíbej. Cíl: dojet celou cestu, než led roztaje.|120|vedle_ona_lezi",
    "Nasyp si do dlaně olej, zahřej ho a rozetři jí ho po celých zádech jedním tahem.|120|masaz_zada",
    "Masíruj jí zadeček a stehna, ale ničeho jiného se nedotkni.|180|masaz_zada",
    "Vezmi žínku, namoč ji ve studené vodě a přejeď jí ji po zátylku. Pak ji tam polib.|60|masaz_vsede",
    "Kresli jí prstem po zádech písmena a ona musí složit slovo, které jí posíláš.|180|masaz_zada",
    "Zavaž jí oči, dej jí do uší sluchátka a pět minut se jí jen tak dotýkej. Nic víc.|300|vedle_ona_lezi",
    "Masíruj jí lýtka a podkolení. Překvapí ji, jak je to citlivé.|120|masaz_chodidla",
    "Deset vteřin na místo: Vyber si jedno místo na jejím těle a deset vteřin se věnuj jenom jemu. Pak další. Cíl: šest míst, žádné dvakrát.|120|vedle_ona_lezi",
    "Pírkem jí obkresli obrysy celého těla. Ona nesmí ani hlesnout.|180|vedle_ona_lezi",
    "Foukej jí na mokrá místa, která jsi právě olízal. Sleduj, jak reaguje.|90|vedle_ona_lezi",
    "Nehty jí lehce přejeď po zádech shora dolů. Pak dlaněmi to samé, ale pomaleji.|120|masaz_zada",
    "Masíruj jí uši – lalůčky mezi prsty, celý okraj, pak je polib.|90|masaz_vsede",
    "Zavaž jí oči a dotkni se jí jen třikrát. Nech ji hádat, kde to bylo.|90|vedle_ona_lezi",
    "Ledová zkouška: Polož jí kostku ledu na břicho a ona ji tam musí udržet, dokud neroztaje. Ty ji mezitím líbáš. Cíl: nenechat led spadnout.|180|vedle_ona_lezi",
    "Naolejuj si ruce a klouzej jí dlaněmi po bocích nahoru a dolů. Nikde se nezastavuj.|120|masaz_zada",
    "Masíruj jí prsty u nohou jeden po druhém a u každého se zeptej, jestli to stačí.|120|masaz_chodidla",
    "Štětcem jí obkresli obrys rtů a pak je polib.|60",
    "Vezmi teplý ručník a přilož jí ho na záda. Až vychladne, začni masírovat.|180|masaz_zada",
    "Zavaž jí oči a nabídni jí tři různé doteky. Ať si vybere, který chce znovu.|120|vedle_ona_lezi",
    "Pírko a nic víc: Pět minut se jí smíš dotýkat jen pírkem. Žádné ruce, žádné rty. Cíl: ať tě sama poprosí o víc.|300|vedle_ona_lezi",
    "Masíruj jí kříž palci v kroužcích, směrem od páteře ven.|180|masaz_zada",
    "Přejeď jí kostkou ledu po rtech a hned je polib, dokud jsou studené.|45|objeti",
    "Nalij jí trochu oleje mezi lopatky a rozetři ho celými dlaněmi.|120|masaz_zada",
    "Hlaď ji po vlasech a šíji tak dlouho, dokud se ti úplně neuvolní v rukou.|180|masaz_vsede",
    "Zavaž jí oči a polib ji na pět míst. Pak ji nech hádat pořadí.|120",
    "Žínka a olej: Nejdřív ji celou omyj teplou žínkou, pak ji naolejuj. Nespěchej ani u jednoho. Cíl: dvě různé teploty na kůži.|300|masaz_zada",
    "Masíruj jí dlaň palcem v kruzích. Je to malá věc, ale funguje.|90",
    "Dotýkej se jí jen konečky prstů a jen tam, kde by to nečekala.|180|vedle_ona_lezi",
    "Foukej jí zlehka do ucha a pak jazykem přejeď okraj boltce.|60",
    "Polož ji na břicho a masíruj jí nohy od kotníků ke stehnům. Pomalu nahoru.|240|masaz_zada",
    "Vezmi štětec a přejeď jí ho po celém obličeji. Oči, nos, rty.|90",
    "Ledová a horká: Dej si do jedné ruky led a druhou zahřej. Střídej je na jejích prsou. Cíl: ať nikdy neví, co přijde.|180|vedle_ona_lezi",
    "Masíruj jí ramena a při tom ji líbej na šíji.|180|masaz_vsede",
    "Zavaž jí oči a šeptej jí, čeho se jí právě dotkneš. A pak to udělej jinak.|180|vedle_ona_lezi",
    "Pírkem jí přejeď po chodidlech. Jestli se bude smát, začínáš znovu.|90|masaz_chodidla",
    "Vezmi ji za ruku a masíruj jí zápěstí. Pak tam přitiskni rty a chvíli počkej.|60",
    "Naolejuj jí celá záda a pak na ně polož vlastní hrudník a klouzej po nich.|180|masaz_zada",
    "Slepé instrukce: Zavaž jí oči a ona ti musí říkat, kam se má tvoje ruka posunout. Ty posloucháš. Cíl: nechat ji řídit celou dobu.|180|vedle_ona_lezi",
    "Přejížděj jí žínkou po břiše v kruzích, jednou teplou, podruhé studenou.|120|vedle_ona_lezi",
    "Masíruj jí čelisti a spánky. Uvolní se jí celý obličej.|120",
    "Polib jí každý obratel na páteři odshora dolů. Ona počítá nahlas.|180|masaz_zada",
    "Vezmi kostku ledu do pusy a olízni jí bradavku. Pak na ni foukni.|90|vedle_ona_lezi",
    "Masáž ve dvou tempech: Nejdřív ji masíruj hodně pomalu, pak najednou rychle a silně. Střídej. Cíl: třikrát změnit tempo.|240|masaz_zada",
    "Zavaž jí oči a nech ji poznat po hmatu tři různé látky na svém těle.|120",
    "Hlaď ji po vnitřní straně paží. Je to jedno z nejcitlivějších míst.|90|vedle_ona_lezi",
    "Masíruj jí boky a podbřišek dlaněmi v kruzích. Níž nesmíš.|180|vedle_ona_lezi",
    "Nakresli jí olejem na záda srdce a pak ho rozetři.|90|masaz_zada",
    "Zavaž jí oči a políbej ji na celém těle, ale vždycky jinam, než se čeká.|240|vedle_ona_lezi",
    "Přiložení: Polož jí obě dlaně na tělo a nehýbej jimi celou minutu. Jen teplo a nic víc. Cíl: vydržet bez pohybu.|60|vedle_ona_lezi",
    "Masíruj jí paty a nárty. Pak jí polib kotník.|120|masaz_chodidla",
    "Přejeď jí pírkem podél lemu prádla dokola. Dvakrát.|90|vedle_ona_lezi",
    "Nech ji ležet na břiše a hraj jí prsty po zádech jako na klavír.|120|masaz_zada",
    "Vezmi si ji do klína a masíruj jí zátylek jednou rukou, druhou ji drž.|180|klin_podlaha",
    "Foukej jí na kůži tam, kde jsi ji před chvílí olízl. Pomalu a dlouho.|90|vedle_ona_lezi",
    "Osm doteků: Dotkni se jí osmkrát a pokaždé jinou částí těla. Ona hádá čím. Cíl: aspoň čtyři uhodnuté.|180|vedle_ona_lezi",
    "Masíruj jí kolena a podkolenní jamky. Nikdo to nedělá a je to překvapivě příjemné.|120|masaz_chodidla",
    "Přiložte si na chvíli dlaň na dlaň a jen si vychutnejte, jak jsou různě teplé.|60|sed_celem",
    "Přejeď jí kostkou ledu po zádech, dokud ji neroztaje kůže.|120|masaz_zada",
    "Zavaž jí oči a nech ji, ať hádá, kterým prstem se jí dotýkáš.|120|vedle_ona_lezi",
    "Masíruj jí bříško jemnými kruhy po směru hodinových ručiček.|120|vedle_ona_lezi",
    "Naber si olej a naolejuj jí prsa lehkými tahy, aniž by ses dotkl bradavek.|180|vedle_ona_lezi",
    "Pírkem přejeď mezi prsy a dolů k pupíku. Pak se vrať zpátky.|90|vedle_ona_lezi",
    "Beze slov a poslepu: Ona má zavázané oči a ty musíš celý úkol mlčet. Jen ruce a rty. Cíl: pět minut ticha.|300|vedle_ona_lezi",
    "Masíruj jí prsty rukou od kořene ke špičce a každý zakonči jemným tahem.|120",
    "Přiklop jí dlaně na uši, ať nic neslyší, a líbej ji na obličej.|90",
    "Vezmi teplou a studenou žínku a nech ji hádat, která je která, aniž by se dívala.|120|vedle_ona_lezi",
    "Masíruj jí ramena zezadu, zatímco sedí na kraji postele, a pomalu klesej níž.|180|masaz_vsede",
    "Naposledy jí přejeď pírkem po tváři a odlož ho. Pak ji polib.|45",
  ],

  female: [
    "Zavaž mu oči a přejeď mu pírkem od krku po kotníky. On hádá, kde přesně jsi.|180|vedle_on_lezi",
    "Vezmi štětec a maluj mu po zádech pomalé kruhy. On leží na břiše a nesmí se hnout.|180|masaz_zada!",
    "Hádej čím: Zavaž mu oči a dotýkej se ho střídavě pírkem, štětcem a žínkou. On hádá. Za každý omyl si sundá kus oblečení. Cíl: tři omyly.|180|vedle_on_lezi",
    "Vezmi kostku ledu a táhni mu ji po klíční kosti. Roztátou vodu slíbej.|90|vedle_on_lezi",
    "Střídej horko a zimu: jednu chvíli ho líbej horkými rty, druhou přiložíš led.|180|vedle_on_lezi",
    "Dej si do pusy kostku ledu a líbej ho tak na krk a na ramena.|120|vedle_on_lezi",
    "Namoč žínku v teplé vodě a omyj mu záda, ruce a nohy jako v lázni.|180|masaz_zada!",
    "Zavaž mu oči a dej mu ochutnat tři různé věci z kuchyně. Za každou uhodnutou dostaneš polibek.|180",
    "Slepá cesta: Zavaž mu oči a veď ho po bytě za ruku. Kde se zastavíš, tam ho políbíš. Cíl: pět zastávek.|180",
    "Rozmasíruj mu olejem ramena a šíji tak, aby mu povolily všechny uzly.|240|masaz_vsede!",
    "Masíruj mu hlavu a vlasy tak dlouho, až se mu začnou klížit oči.|180",
    "Vezmi si jeho chodidlo do klína a palcem mu masíruj plosku od paty ke špičkám.|180|masaz_chodidla!",
    "Záda pruh po pruhu: Naolejuj si ruce a jeď od jeho krku až ke kříži, každý pruh projeď dvakrát. Cíl: nevynechat ani centimetr.|300|masaz_zada!",
    "Masíruj mu ruce – dlaň, každý prst zvlášť, pak zápěstí a předloktí.|180",
    "Zavaž mu oči a nech ho hádat, kterou částí těla se ho dotýkáš. Nos, loket, rty, koleno.|180|vedle_on_lezi",
    "Veď mu pírko po vnitřní straně stehen nahoru a zase dolů. Až úplně nahoru nikdy nedojedeš.|180|vedle_on_lezi",
    "Přejeď mu štětcem přes bradavky tak lehce, jak to jen jde. Pak přestaň a chvíli nic.|120|vedle_on_lezi",
    "Ledová stopa: Táhni mu kostku ledu od krku přes hrudník až k pupíku a stopu slíbej. Cíl: dojet celou cestu, než led roztaje.|120|vedle_on_lezi",
    "Nasyp si do dlaně olej, zahřej ho a rozetři mu ho po celých zádech jedním tahem.|120|masaz_zada!",
    "Masíruj mu zadek a stehna, ale ničeho jiného se nedotkni.|180|masaz_zada!",
    "Vezmi žínku, namoč ji ve studené vodě a přejeď mu ji po zátylku. Pak ho tam polib.|60|masaz_vsede!",
    "Kresli mu prstem po zádech písmena a on musí složit slovo, které mu posíláš.|180|masaz_zada!",
    "Zavaž mu oči, dej mu do uší sluchátka a pět minut se ho jen tak dotýkej. Nic víc.|300|vedle_on_lezi",
    "Masíruj mu lýtka a podkolení. Překvapí ho, jak je to citlivé.|120|masaz_chodidla!",
    "Deset vteřin na místo: Vyber si jedno místo na jeho těle a deset vteřin se věnuj jenom jemu. Pak další. Cíl: šest míst, žádné dvakrát.|120|vedle_on_lezi",
    "Pírkem mu obkresli obrysy celého těla. On nesmí ani hlesnout.|180|vedle_on_lezi",
    "Foukej mu na mokrá místa, která jsi právě olízala. Sleduj, jak reaguje.|90|vedle_on_lezi",
    "Nehty mu lehce přejeď po zádech shora dolů. Pak dlaněmi to samé, ale pomaleji.|120|masaz_zada!",
    "Masíruj mu uši – lalůčky mezi prsty, celý okraj, pak je polib.|90|masaz_vsede!",
    "Zavaž mu oči a dotkni se ho jen třikrát. Nech ho hádat, kde to bylo.|90|vedle_on_lezi",
    "Ledová zkouška: Polož mu kostku ledu na břicho a on ji tam musí udržet, dokud neroztaje. Ty ho mezitím líbáš. Cíl: nenechat led spadnout.|180|vedle_on_lezi",
    "Naolejuj si ruce a klouzej mu dlaněmi po bocích nahoru a dolů. Nikde se nezastavuj.|120|masaz_zada!",
    "Masíruj mu prsty u nohou jeden po druhém a u každého se zeptej, jestli to stačí.|120|masaz_chodidla!",
    "Štětcem mu obkresli obrys rtů a pak je polib.|60",
    "Vezmi teplý ručník a přilož mu ho na záda. Až vychladne, začni masírovat.|180|masaz_zada!",
    "Zavaž mu oči a nabídni mu tři různé doteky. Ať si vybere, který chce znovu.|120|vedle_on_lezi",
    "Pírko a nic víc: Pět minut se ho smíš dotýkat jen pírkem. Žádné ruce, žádné rty. Cíl: ať tě sám poprosí o víc.|300|vedle_on_lezi",
    "Masíruj mu kříž palci v kroužcích, směrem od páteře ven.|180|masaz_zada!",
    "Přejeď mu kostkou ledu po rtech a hned je polib, dokud jsou studené.|45|objeti",
    "Nalij mu trochu oleje mezi lopatky a rozetři ho celými dlaněmi.|120|masaz_zada!",
    "Hlaď ho po vlasech a šíji tak dlouho, dokud se ti úplně neuvolní v rukou.|180|masaz_vsede!",
    "Zavaž mu oči a polib ho na pět míst. Pak ho nech hádat pořadí.|120",
    "Žínka a olej: Nejdřív ho celého omyj teplou žínkou, pak ho naolejuj. Nespěchej ani u jednoho. Cíl: dvě různé teploty na kůži.|300|masaz_zada!",
    "Masíruj mu dlaň palcem v kruzích. Je to malá věc, ale funguje.|90",
    "Dotýkej se ho jen konečky prstů a jen tam, kde by to nečekal.|180|vedle_on_lezi",
    "Foukej mu zlehka do ucha a pak jazykem přejeď okraj boltce.|60",
    "Polož ho na břicho a masíruj mu nohy od kotníků ke stehnům. Pomalu nahoru.|240|masaz_zada!",
    "Vezmi štětec a přejeď mu ho po celém obličeji. Oči, nos, rty.|90",
    "Ledová a horká: Dej si do jedné ruky led a druhou zahřej. Střídej je na jeho hrudníku. Cíl: ať nikdy neví, co přijde.|180|vedle_on_lezi",
    "Masíruj mu ramena a při tom ho líbej na šíji.|180|masaz_vsede!",
    "Zavaž mu oči a šeptej mu, čeho se ho právě dotkneš. A pak to udělej jinak.|180|vedle_on_lezi",
    "Pírkem mu přejeď po chodidlech. Jestli se bude smát, začínáš znovu.|90|masaz_chodidla!",
    "Vezmi ho za ruku a masíruj mu zápěstí. Pak tam přitiskni rty a chvíli počkej.|60",
    "Naolejuj mu celá záda a pak na ně polož vlastní hrudník a klouzej po nich.|180|masaz_zada!",
    "Slepé instrukce: Zavaž mu oči a on ti musí říkat, kam se má tvoje ruka posunout. Ty posloucháš. Cíl: nechat ho řídit celou dobu.|180|vedle_on_lezi",
    "Přejížděj mu žínkou po břiše v kruzích, jednou teplou, podruhé studenou.|120|vedle_on_lezi",
    "Masíruj mu čelisti a spánky. Uvolní se mu celý obličej.|120",
    "Polib mu každý obratel na páteři odshora dolů. On počítá nahlas.|180|masaz_zada!",
    "Vezmi kostku ledu do pusy a olízni mu bradavku. Pak na ni foukni.|90|vedle_on_lezi",
    "Masáž ve dvou tempech: Nejdřív ho masíruj hodně pomalu, pak najednou rychle a silně. Střídej. Cíl: třikrát změnit tempo.|240|masaz_zada!",
    "Zavaž mu oči a nech ho poznat po hmatu tři různé látky na svém těle.|120",
    "Hlaď ho po vnitřní straně paží. Je to jedno z nejcitlivějších míst.|90|vedle_on_lezi",
    "Masíruj mu boky a podbřišek dlaněmi v kruzích. Níž nesmíš.|180|vedle_on_lezi",
    "Nakresli mu olejem na záda srdce a pak ho rozetři.|90|masaz_zada!",
    "Zavaž mu oči a polibkuj ho na celém těle, ale vždycky jinam, než se čeká.|240|vedle_on_lezi",
    "Přiložení: Polož mu obě dlaně na tělo a nehýbej jimi celou minutu. Jen teplo a nic víc. Cíl: vydržet bez pohybu.|60|vedle_on_lezi",
    "Masíruj mu paty a nárty. Pak mu polib kotník.|120|masaz_chodidla!",
    "Přejeď mu pírkem podél lemu prádla dokola. Dvakrát.|90|vedle_on_lezi",
    "Nech ho ležet na břiše a hraj mu prsty po zádech jako na klavír.|120|masaz_zada!",
    "Opři si ho zády o sebe a masíruj mu zátylek jednou rukou, druhou ho drž.|180|klin_podlaha!",
    "Foukej mu na kůži tam, kde jsi ho před chvílí olízla. Pomalu a dlouho.|90|vedle_on_lezi",
    "Osm doteků: Dotkni se ho osmkrát a pokaždé jinou částí těla. On hádá čím. Cíl: aspoň čtyři uhodnuté.|180|vedle_on_lezi",
    "Masíruj mu kolena a podkolenní jamky. Nikdo to nedělá a je to překvapivě příjemné.|120|masaz_chodidla!",
    "Přilož mu svoji dlaň na jeho a chvíli vnímej, o kolik je teplejší než tvoje.|60|sed_zady",
    "Přejeď mu kostkou ledu po zádech, dokud ji neroztaje kůže.|120|masaz_zada!",
    "Zavaž mu oči a nech ho, ať hádá, kterým prstem se ho dotýkáš.|120|vedle_on_lezi",
    "Masíruj mu bříško jemnými kruhy po směru hodinových ručiček.|120|vedle_on_lezi",
    "Naber si olej a naolejuj mu hrudník lehkými tahy, aniž by ses dotkla bradavek.|180|vedle_on_lezi",
    "Pírkem přejeď po jeho hrudníku dolů k pupíku. Pak se vrať zpátky.|90|vedle_on_lezi",
    "Beze slov a poslepu: On má zavázané oči a ty musíš celý úkol mlčet. Jen ruce a rty. Cíl: pět minut ticha.|300|vedle_on_lezi",
    "Masíruj mu prsty rukou od kořene ke špičce a každý zakonči jemným tahem.|120",
    "Přiklop mu dlaně na uši, ať nic neslyší, a líbej ho na obličej.|90",
    "Vezmi teplou a studenou žínku a nech ho hádat, která je která, aniž by se díval.|120|vedle_on_lezi",
    "Masíruj mu ramena zezadu, zatímco sedí na kraji postele, a pomalu klesej níž.|180|masaz_vsede!",
    "Naposledy mu přejeď pírkem po tváři a odlož ho. Pak ho polib.|45",
  ],
});
