// Kategorie 1 – Škádlení a předehra (dávka e)
// Témata: pravidla a hry, počítané výzvy, roleplay, špinavé řeči, čekání a odpírání.
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 1,

  male: [
    "Ruce za zády: Celou dobu máš ruce za zády. Smíš používat jen rty, jazyk a dech. Cíl: dostat ji do bodu, kdy sáhne po tobě.|180",
    "Hoď kostkou. Kolik padne, tolik minut se jí musíš věnovat jen na jednom místě, které si vybere ona.|180",
    "Sto doteků: Dotkni se jí stokrát. Ona počítá nahlas. Když ztratí počet, začínáte znovu. Cíl: dojít do sta.|300|vedle_ona_lezi",
    "Ona se nesmí hýbat. Ani jednou. Pokaždé, když se pohne, přestaneš na deset vteřin.|180|vedle_ona_lezi",
    "Zahrajte si, že se dneska vidíte poprvé. Buď zdvořilý a pomalý – jako by sis ji musel teprve získat.|240",
    "Zahraj jí maséra, kterého si zaplatila. Mluv na ni jako cizí člověk a dělej přesně to, co si objedná.|300|masaz_zada",
    "Řekni jí deset sprostých vět za sebou. Za každou, u které se zasmějete, si sundáš kus oblečení.|180",
    "Špinavé řeči: Popisuj jí nahlas, co s ní děláš, přímo když to děláš. Ani na chvíli neztichni. Cíl: nepřestat mluvit.|180|vedle_ona_lezi",
    "Nesmíš ji políbit na ústa, dokud ona neřekne prosím.|180",
    "Zeptej se jí na tři věci a za každou odpověď jí sundáš jeden kus oblečení.|120",
    "Dej jí tři možnosti, co jí uděláš, a nech ji vybrat. Pak to udělej tak pomalu, jak jen dokážeš.|180",
    "Dvě minuty čekání: Řekni jí, co jí uděláš, a pak dvě minuty nedělej vůbec nic. Jen se na ni dívej. Cíl: vydržet celé dvě minuty.|120",
    "Ona má ruce svázané kravatou před tělem. Ty ji svlékáš a líbáš, ona se nesmí bránit.|180|klek_ruce_za_zady",
    "Vyzvi ji na souboj pohledů. Kdo uhne, plní přání toho druhého.|120|sed_celem",
    "Pokládej jí ruce na tělo a ona říká jen teplo nebo zima podle toho, jak blízko jsi tomu, co chce.|180|vedle_ona_lezi",
    "Dej jí jedno pravidlo: nesmí vydat ani hlásku. Pak dělej všechno pro to, aby ho porušila.|180|vedle_ona_lezi",
    "Pět minut jen na krk: Celých pět minut se věnuj výhradně jejímu krku a uším. Nikam jinam. Cíl: nesjet níž ani jednou.|300|stoje_zezadu",
    "Zeptej se jí, jaké slovo dneska nesmíš říct. A pak mluv tak, abys mu byl pořád blízko.|120",
    "Hraj šéfa a ona je tvoje asistentka. Zadávej jí drobné úkoly a hodnoť, jak je plní.|240",
    "Dej jí dvě minuty, aby tě vzrušila, ale nesmí se tě dotknout rukama.|120",
    "Pomalé odpočítávání: Řekni jí, že za šedesát vteřin ji políbíš, a nahlas počítej. Do té doby se jí nedotkneš. Cíl: dodržet to na vteřinu.|60",
    "Vyber jí jedno místo na těle, kterého se dneska nesmí dotknout ani ona, ani ty. Až do konce úrovně.|60",
    "Ona ti řekne tři věci, které nesnáší. Ty jí místo nich uděláš tři věci, které má ráda.|180",
    "Dej jí ruce nad hlavu a drž jí je jednou rukou. Druhou ji hlaď, kde chceš.|180|vedle_ona_lezi",
    "Hraj, že jsi ji právě potkal na baru. Sbal ji znovu, jako by o tobě nic nevěděla.|240|sed_celem",
    "Šeptej jí sprosťárny do ucha, ale u toho se jí vůbec nedotýkej.|120",
    "Střídavá hra: Dvacet vteřin ji dráždíš, dvacet vteřin nic. A tak dokola pět kol. Cíl: vydržet všech pět kol.|240|vedle_ona_lezi",
    "Ať si sama vybere, jestli chce, abys byl hodný, nebo drzý. A pak to dodrž.|180",
    "Poruč jí, ať si klekne a počká. Ty mezitím jen stojíš a díváš se.|90|klek_ruce_za_zady",
    "Dej jí tři jednoduché příkazy za sebou a sleduj, jak rychle je splní.|120",
    "Hraj cizince, který se v ní snaží vyznat. Ptej se na všechno, co má ráda.|240|sed_celem",
    "Souboj o tempo: Ona určuje, jak rychle se hýbeš, jediným slovem – rychleji nebo pomaleji. Ty musíš poslechnout. Cíl: ani jednou neudělat něco po svém.|180|vedle_ona_lezi",
    "Nech ji vybrat mezi polibkem a masáží. Dej jí to, co si nevybrala.|120",
    "Řekni jí, že se jí nesmíš dotknout, dokud sama neřekne kde. A čekej.|120",
    "Kdykoli během tohoto úkolu řekne tvoje jméno, dostane polibek. Ať si to zaslouží.|180",
    "Dej jí do ruky kostku ledu a řekni jí, že ji musí udržet, dokud tě líbá.|120|objeti",
    "Poslední tři slova: Smíš dneska říct už jen tři slova. Vyber je dobře a zbytek ukaž rukama. Cíl: vystačit si se třemi slovy.|180",
    "Ona má zavřené oči a musí hádat, jestli ji líbáš rty, nebo se jí dotýkáš prstem.|120|vedle_ona_lezi",
    "Nakresli jí prstem na stehno čáru a řekni, že přes ni dneska nesmíš. Zatím.|60",
    "Hraj, že jsi její soused, kterého si pozvala na skleničku. Zůstaň v roli až do konce.|300",
    "Dej jí seznam pěti věcí a ona vyškrtne dvě, které dneska nechce. Zbytek jí uděláš.|180",
    "Pomalu, ale bez pauzy: Dotýkej se jí tři minuty naprosto plynule, aniž bys ruku jednou zvedl z kůže. Cíl: ani jedno přerušení.|180|vedle_ona_lezi",
    "Nech ji, ať ti řekne jednu drzou větu. Ty jí na ni odpovíš činem.|90",
    "Řekni jí, že dneska rozhoduješ ty. Pak jí dej první rozkaz – hodně mírný.|60",
    "Poruč jí, ať si sama sundá jeden kus oblečení, a pak jí poděkuj polibkem.|60|tanec",
    "Hoď kostkou dvakrát: první číslo je místo od hlavy dolů, druhé je počet minut.|180",
    "Dej jí tři vteřiny na odpověď: co chce právě teď? Když zaváhá, rozhodneš ty.|60",
    "Jenom dech: Celou minutu ji dráždi jen tím, že jí dýcháš na kůži. Žádný dotek. Cíl: ať se jí zježí chlupy na rukou.|60|vedle_ona_lezi",
    "Nech ji klečet před tebou a jen ji hlaď po vlasech. Nic víc dneska nebude.|120|oral_ona_klek",
    "Řekni jí větu, kterou by od tebe nikdy nečekala, a pak ji polib, než stihne zareagovat.|60",
    "Dnes se rozhoduje hlasováním: navrhni tři věci a ona jednu odmítne. Zbylé dvě uděláte.|120",
    "Vyzvi ji, ať tě vzruší jen slovy. Nesmí se hnout z místa.|120|sed_celem",
    "Hra na žárlivost: Popiš jí, co by udělal někdo jiný, a pak jí ukaž, jak to děláš ty. Cíl: ať uzná, že ty líp.|180",
    "Zakaž jí mluvit a nech ji, ať ti rukou ukáže, co chce.|180|vedle_ona_lezi",
    "Nech ji vybrat si mezi tím, že budeš pomalý, nebo že budeš neodbytný.|60",
    "Za každý úsměv během tohoto úkolu jí dáš polibek. Snaž se ji rozesmát.|120",
    "Dej jí dvě minuty, aby ti řekla všechno, co chce dneska zkusit. Ty jen posloucháš.|120|sed_celem",
    "Stopka: Kdykoli řekne stop, přestaneš a počkáš pět vteřin. Ona to může říct, kolikrát chce. Cíl: ani jednou neporušit pravidlo.|180|vedle_ona_lezi",
    "Pošeptej jí do ucha jednu věc, kterou uděláš, až tahle úroveň skončí. A drž slovo.|45",
    "Poruč jí, ať se na tebe celou minutu jen dívá a nesmí se dotknout.|60|sed_celem",
    "Nech ji hádat, na co myslíš. Za každý špatný tip jí sundáš kus oblečení.|180",
    "Vyber jí jedno slovo, které dneska bude znamenat víc. Řekni jí ho a pak ho použij.|60",
    "Tři a dost: Smíš se jí dotknout jen třikrát, ale každý dotek může trvat, jak dlouho chceš. Cíl: vybrat ta správná tři místa.|240|vedle_ona_lezi",
    "Zahrajte si na fotografa a modelku. Ty ji aranžuješ, ona poslouchá.|240",
    "Dej jí přesně minutu, ať si sama rozhodne, co ti dovolí. Pak se ptát nebudeš.|60",
    "Řekni jí nahlas, co se ti honilo hlavou dneska, když jsi na ni myslel v práci.|90",
    "Dej jí do ruky svoje zápěstí a nech ji, ať tě vede tam, kam chce.|120|vedle_ona_lezi",
    "Nech ji vybrat kus oblečení, který ti dneska zůstane. A ten na tobě opravdu zůstane.|60",
    "Pět otázek: Zeptej se jí na pět věcí a za každé ano si sundáš jeden kus oblečení. Cíl: skončit nahý.|180|sed_celem",
    "Hraj, že máte jen pět minut, než někdo přijde. Chovej se podle toho.|300",
    "Šeptej jí do ucha a mezi větami ji vždycky krátce políbíš na krk.|120|stoje_zezadu",
    "Řekni jí, co se ti na ní dneska líbilo nejvíc, a polib to místo třikrát.|60",
    "Nech ji, ať ti zaváže oči, a pak se nech od ní vodit. Ty nesmíš mluvit.|180",
    "Zakážeš jí zavřít oči. Musí se dívat na všechno, co jí děláš.|180|vedle_ona_lezi",
    "Deset a deset: Deset vteřin ji líbáš, deset vteřin se na ni jen díváš. Šest kol. Cíl: vydržet pauzy.|120|objeti",
    "Postav ji před sebe a nech ji hádat, kam ji políbíš. Když uhodne, polibek dostane jinam.|120",
    "Vyzvi ji, ať ti popíše svoji nejlepší vzpomínku s tebou v posteli. Do detailu.|180|sed_celem",
    "Dej jí na výběr: buď tě bude poslouchat, nebo bude rozhodovat ona. Až do konce úrovně.|60",
    "Slib jí něco na konec večera a celou úroveň jí to připomínej.|90",
    "Řekni jí, že jediné, co dneska chceš, je dívat se, jak se jí to líbí.|60",
    "Oči v očích: Dotýkej se jí, ale ani na vteřinu nesmíš uhnout pohledem z jejích očí. Cíl: vydržet celý úkol.|180|sed_celem",
    "Zeptej se jí, co by chtěla, abys jí zakázal. A zakaž jí to.|90",
    "Nech ji sedět na tvém klíně zády a nedělej vůbec nic. Jen ji drž.|120|klin_zady",
    "Dej jí pět vteřin na to, aby si vybrala místo, které dneska dostane nejvíc pozornosti.|60",
    "Řekni jí, ať tě požádá o to, co chce, celou větou a nahlas. Teprve pak jí to dáš.|90",
  ],

  female: [
    "Ruce za zády: Celou dobu máš ruce za zády. Smíš používat jen rty, jazyk a dech. Cíl: dostat ho do bodu, kdy sáhne po tobě.|180",
    "Hoď kostkou. Kolik padne, tolik minut se mu musíš věnovat jen na jednom místě, které si vybere on.|180",
    "Sto doteků: Dotkni se ho stokrát. On počítá nahlas. Když ztratí počet, začínáte znovu. Cíl: dojít do sta.|300|vedle_on_lezi",
    "On se nesmí hýbat. Ani jednou. Pokaždé, když se pohne, přestaneš na deset vteřin.|180|vedle_on_lezi",
    "Zahrajte si, že se dneska vidíte poprvé. Buď odměřená a nech ho, ať si tě musí získat.|240",
    "Zahraj mu masérku, kterou si zaplatil. Mluv na něj jako cizí člověk a dělej přesně to, co si objedná.|300|masaz_zada",
    "Řekni mu deset sprostých vět za sebou. Za každou, u které se zasmějete, si sundáš kus oblečení.|180",
    "Špinavé řeči: Popisuj mu nahlas, co s ním děláš, přímo když to děláš. Ani na chvíli neztichni. Cíl: nepřestat mluvit.|180|vedle_on_lezi",
    "Nesmíš ho políbit na ústa, dokud on neřekne prosím.|180",
    "Zeptej se ho na tři věci a za každou odpověď mu sundáš jeden kus oblečení.|120",
    "Dej mu tři možnosti, co mu uděláš, a nech ho vybrat. Pak to udělej tak pomalu, jak jen dokážeš.|180",
    "Dvě minuty čekání: Řekni mu, co mu uděláš, a pak dvě minuty nedělej vůbec nic. Jen se na něj dívej. Cíl: vydržet celé dvě minuty.|120",
    "On má ruce svázané kravatou před tělem. Ty ho svlékáš a líbáš, on se nesmí bránit.|180|klek_ruce_za_zady",
    "Vyzvi ho na souboj pohledů. Kdo uhne, plní přání toho druhého.|120|sed_celem",
    "Pokládej mu ruce na tělo a on říká jen teplo nebo zima podle toho, jak blízko jsi tomu, co chce.|180|vedle_on_lezi",
    "Dej mu jedno pravidlo: nesmí vydat ani hlásku. Pak dělej všechno pro to, aby ho porušil.|180|vedle_on_lezi",
    "Pět minut jen na krk: Celých pět minut se věnuj výhradně jeho krku a uším. Nikam jinam. Cíl: nesjet níž ani jednou.|300|objeti",
    "Zeptej se ho, jaké slovo dneska nesmíš říct. A pak mluv tak, abys mu byla pořád blízko.|120",
    "Hraj šéfovou a on je tvůj asistent. Zadávej mu drobné úkoly a hodnoť, jak je plní.|240",
    "Dej mu dvě minuty, aby tě vzrušil, ale nesmí se tě dotknout rukama.|120",
    "Pomalé odpočítávání: Řekni mu, že za šedesát vteřin ho políbíš, a nahlas počítej. Do té doby se ho nedotkneš. Cíl: dodržet to na vteřinu.|60",
    "Vyber mu jedno místo na těle, kterého se dneska nesmí dotknout ani on, ani ty. Až do konce úrovně.|60",
    "On ti řekne tři věci, které nesnáší. Ty mu místo nich uděláš tři věci, které má rád.|180",
    "Dej mu ruce nad hlavu a drž mu je jednou rukou. Druhou ho hlaď, kde chceš.|180|vedle_on_lezi",
    "Hraj, že tě právě potkal na baru. Nech se sbalit znovu, jako bys o něm nic nevěděla.|240|sed_celem",
    "Šeptej mu sprosťárny do ucha, ale u toho se ho vůbec nedotýkej.|120",
    "Střídavá hra: Dvacet vteřin ho dráždíš, dvacet vteřin nic. A tak dokola pět kol. Cíl: vydržet všech pět kol.|240|vedle_on_lezi",
    "Ať si sám vybere, jestli chce, abys byla hodná, nebo drzá. A pak to dodrž.|180",
    "Poruč mu, ať si klekne a počká. Ty mezitím jen stojíš a díváš se.|90|klek_ruce_za_zady",
    "Dej mu tři jednoduché příkazy za sebou a sleduj, jak rychle je splní.|120",
    "Hraj cizinku, která se v něm snaží vyznat. Ptej se na všechno, co má rád.|240|sed_celem",
    "Souboj o tempo: On určuje, jak rychle se hýbeš, jediným slovem – rychleji nebo pomaleji. Ty musíš poslechnout. Cíl: ani jednou neudělat něco po svém.|180|vedle_on_lezi",
    "Nech ho vybrat mezi polibkem a masáží. Dej mu to, co si nevybral.|120",
    "Řekni mu, že se ho nesmíš dotknout, dokud sám neřekne kde. A čekej.|120",
    "Pokaždé, když během úkolu vysloví tvoje jméno, dostane polibek. Ať si ho zaslouží.|180",
    "Dej mu do ruky kostku ledu a řekni mu, že ji musí udržet, dokud tě líbá.|120|objeti",
    "Tři slova a dost: Do konce úkolu smíš vyslovit jen tři slova, všechno ostatní ukaž rukama. Cíl: vystačit si s nimi.|180",
    "On má zavřené oči a musí hádat, jestli ho líbáš rty, nebo se ho dotýkáš prstem.|120|vedle_on_lezi",
    "Nakresli mu prstem na stehno čáru a řekni, že přes ni dneska nesmíš. Zatím.|60",
    "Hraj, že jsi jeho sousedka, kterou si pozval na skleničku. Zůstaň v roli až do konce.|300",
    "Dej mu seznam pěti věcí a on vyškrtne dvě, které dneska nechce. Zbytek mu uděláš.|180",
    "Pomalu, ale bez pauzy: Dotýkej se ho tři minuty naprosto plynule, aniž bys ruku jednou zvedla z kůže. Cíl: ani jedno přerušení.|180|vedle_on_lezi",
    "Nech ho, ať ti řekne jednu drzou větu. Ty mu na ni odpovíš činem.|90",
    "Řekni mu, že dneska rozhoduješ ty. Pak mu dej první rozkaz – hodně mírný.|60",
    "Poruč mu, ať si sám sundá jeden kus oblečení, a pak mu poděkuj polibkem.|60|tanec",
    "Hoď si kostkou dvakrát – první hod určí místo odshora dolů, druhý počet minut, které mu tam věnuješ.|180",
    "Dej mu tři vteřiny na odpověď: co chce právě teď? Když zaváhá, rozhodneš ty.|60",
    "Jenom dech: Celou minutu ho dráždi jen tím, že mu dýcháš na kůži. Žádný dotek. Cíl: ať se mu zježí chlupy na rukou.|60|vedle_on_lezi",
    "Nech ho klečet před tebou a jen mu prohrábni vlasy. Nic víc dneska nebude.|120|oral_ona_klek",
    "Řekni mu větu, kterou by od tebe nikdy nečekal, a pak ho polib, než stihne zareagovat.|60",
    "Dnes se rozhoduje hlasováním: navrhni tři věci a on jednu odmítne. Zbylé dvě uděláte.|120",
    "Vyzvi ho, ať tě vzruší jen slovy. Nesmí se hnout z místa.|120|sed_celem",
    "Hra na žárlivost: Popiš mu, co by udělal někdo jiný, a pak mu ukaž, jak to chceš ty. Cíl: ať uzná, že to víš líp.|180",
    "Zakaž mu mluvit a nech ho, ať ti rukou ukáže, co chce.|180|vedle_on_lezi",
    "Nech ho vybrat si mezi tím, že budeš pomalá, nebo že budeš neodbytná.|60",
    "Za každý úsměv během tohoto úkolu mu dáš polibek. Snaž se ho rozesmát.|120",
    "Dej mu dvě minuty, aby ti řekl všechno, co chce dneska zkusit. Ty jen posloucháš.|120|sed_celem",
    "Stopka: Kdykoli řekne stop, přestaneš a počkáš pět vteřin. On to může říct, kolikrát chce. Cíl: ani jednou neporušit pravidlo.|180|vedle_on_lezi",
    "Pošeptej mu do ucha jednu věc, kterou uděláš, až tahle úroveň skončí. A drž slovo.|45",
    "Poruč mu, ať se na tebe celou minutu jen dívá a nesmí se dotknout.|60|sed_celem",
    "Nech ho hádat, na co myslíš. Za každý špatný tip mu sundáš kus oblečení.|180",
    "Vyber mu jedno slovo, které dneska bude znamenat víc. Řekni mu ho a pak ho použij.|60",
    "Tři a dost: Smíš se ho dotknout jen třikrát, ale každý dotek může trvat, jak dlouho chceš. Cíl: vybrat ta správná tři místa.|240|vedle_on_lezi",
    "Zahrajte si na fotografku a modela. Ty ho aranžuješ, on poslouchá.|240",
    "Dej mu přesně minutu, ať si sám rozhodne, co ti dovolí. Pak se ptát nebudeš.|60",
    "Řekni mu nahlas, co se ti honilo hlavou dneska, když jsi na něj myslela přes den.|90",
    "Dej mu do ruky svoje zápěstí a nech ho, ať tě vede tam, kam chce.|120|vedle_on_lezi",
    "Nech ho vybrat kus oblečení, který ti dneska zůstane. A ten na tobě opravdu zůstane.|60",
    "Pět otázek: Zeptej se ho na pět věcí a za každé ano si sundáš jeden kus oblečení. Cíl: skončit nahá.|180|sed_celem",
    "Dělej, jako byste měli jen pět minut, než se někdo vrátí domů. Podle toho se chovej.|300",
    "Šeptej mu do ucha a mezi větami ho vždycky krátce políbíš na krk.|120|objeti",
    "Řekni mu, co se ti na něm dneska líbilo nejvíc, a polib to místo třikrát.|60",
    "Nech ho, ať ti zaváže oči, a pak se nech od něj vodit. Ty nesmíš mluvit.|180",
    "Zakážeš mu zavřít oči. Musí se dívat na všechno, co mu děláš.|180|vedle_on_lezi",
    "Deset a deset: Deset vteřin ho líbáš, deset vteřin se na něj jen díváš. Šest kol. Cíl: vydržet pauzy.|120|objeti",
    "Postav se před něj a nech ho hádat, kam ho políbíš. Když uhodne, polibek dostane jinam.|120",
    "Vyzvi ho, ať ti popíše svoji nejlepší vzpomínku s tebou v posteli. Do detailu.|180|sed_celem",
    "Dej mu na výběr: buď tě bude poslouchat, nebo bude rozhodovat on. Až do konce úrovně.|60",
    "Slib mu něco na konec večera a celou úroveň mu to připomínej.|90",
    "Řekni mu, že jediné, co dneska chceš, je dívat se, jak se mu to líbí.|60",
    "Oči v očích: Dotýkej se ho, ale ani na vteřinu nesmíš uhnout pohledem z jeho očí. Cíl: vydržet celý úkol.|180|sed_celem",
    "Zeptej se ho, co by chtěl, abys mu zakázala. A zakaž mu to.|90",
    "Sedni si mu na klín zády a nedělej vůbec nic. Jen se o něj opři.|120|klin_zady",
    "Dej mu pět vteřin na to, aby si vybral místo, které dneska dostane nejvíc pozornosti.|60",
    "Řekni mu, ať tě požádá o to, co chce, celou větou a nahlas. Teprve pak mu to dáš.|90",
  ],
});
