// Kategorie 1 – Škádlení a předehra (dávka c)
// Témata: svlékání, polibky s pravidly, škádlení přes oblečení, hudba a tanec, telefon.
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 1,

  male: [
    "Svlékej ji jedním kusem za minutu. Mezi každým kusem ji musíš políbit na místo, které jsi právě odhalil.|180|svlekani",
    "Pomalu jí vyhrň tričko až nad prsa a tam přestaň. Dál se nedostaneš, dokud tě o to nepoprosí.|90|svlekani",
    "Zuby a nic víc: Svlékni jí jeden kus oblečení jen zuby, bez pomoci rukou. Cíl: sundat to, ať to trvá jakkoli.|180|svlekani",
    "Rozepínej jí knoflíky jeden po druhém a po každém ji polib na odhalené místo. Nespěchej.|120|svlekani",
    "Sundej jí kalhotky tak, aby se tě ani jednou nedotkla. Když sáhne po tobě, začínáš znovu.|90|svlekani",
    "Postav ji před sebe a nech ji, ať se svlékne sama. Ty sedíš, koukáš a nesmíš mluvit.|180|tanec",
    "Pusť jí jednu písničku a po celou dobu ji líbej na krk. Až skončí, přestaneš.|180|stoje_zezadu",
    "Dej jí do uší sluchátka s tvojí oblíbenou písničkou a celou tu dobu ji svlékej. Ona tě neslyší, jen cítí.|180|svlekani",
    "Tanec o dvou pravidlech: Tancujte spolu pomalu, ty ji smíš držet jen za boky a nesmíš ji políbit. Cíl: vydržet celou písničku.|180|objeti",
    "Polib ji na deset různých míst a ani jedno nesmí být na ústech. Ona počítá nahlas.|120",
    "Líbej ji, ale jen spodní ret. Jazyk zakázaný.|60|objeti",
    "Polibek na tři doby: Nejdřív jen rty, pak s jazykem, pak jí kousni do rtu. Mezi tím vždycky počkej pět vteřin. Cíl: ať si o další řekne sama.|90|objeti",
    "Přitiskni ji ke zdi a líbej ji tak dlouho, dokud se jí nepodlomí kolena. Ruce měj opřené o zeď, ne na ní.|120|zed",
    "Líbej ji všude tam, kde má oblečení. Přes látku, nikdy na holou kůži.|120",
    "Sedni si, posaď si ji obkročmo na klín a tři minuty se jenom líbejte. Nic jiného.|180|klin_celem",
    "Dráždi ji přes kalhotky. Nesmíš je sundat, dokud neuplyne čas.|180",
    "Jen přes látku: Hlaď ji a dráždi přes spodní prádlo tak dlouho, až ho bude chtít sundat. Cíl: ať si ho sundá sama.|180",
    "Vsuň jí ruku pod tričko, ale zastav se hned nad pasem. Nikam výš, dokud ti to nedovolí.|90",
    "Polib ji do dlaně, pak do zápěstí a pokračuj vzhůru po vnitřní straně paže až k rameni.|90",
    "Lehni si k ní a celou minutu ji líbej jenom na krk a za ucho. Ruce nech ležet.|60|vedle_ona_lezi",
    "Nech ji sednout si na kraj postele, klekni si před ni a líbej jí kolena a stehna. Výš ne.|120|oral_vsede",
    "Sundej jí jeden kus oblečení a ten samý si obleč sám. Zůstaňte tak až do konce úkolu.|60|svlekani",
    "Fotka na přání: Vyfoť ji telefonem tak, jak se jí to bude líbit, a ukaž jí to. Pak fotku hned smažte. Cíl: ať se líbí ona sama sobě.|180",
    "Napiš jí z druhého konce pokoje zprávu, co jí uděláš. Neříkej to nahlas, jen pošli.|90",
    "Nahraj jí na telefon hlasovku, co s ní chceš dělat, a nech ji, ať si ji poslechne se sluchátky.|120",
    "Pusť jí do sluchátek písničku a mezitím jí prstem obkresluj obrysy těla. Nesmíš mluvit.|180|vedle_ona_lezi",
    "Odpočítávej nahlas od deseti a při každém čísle jí sundej nebo posuň jeden kus oblečení.|90|svlekani",
    "Svlékni si sám všechno kromě jednoho kusu a postav se před ni. Ona rozhodne, kdy padne i ten.|60|tanec",
    "Rozehřátí zezadu: Obejmi ji zezadu, líbej ji na šíji a rukama jí zvolna zajeď pod tričko. Cíl: ať se o tebe sama opře.|120|stoje_zezadu",
    "Líbej ji a u toho jí pomalu rozepínej podprsenku. Když ji rozepneš na první pokus, dostaneš od ní odměnu.|90|svlekani",
    "Táhni jí špičkou prstu od krku dolů až k pasu a zastav se přesně tam, kde začíná prádlo.|60|vedle_ona_lezi",
    "Zakázaná místa: Dotýkej se jí kdekoli, jen ne na prsou a mezi nohama. Tři minuty. Cíl: ať ti ruku sama posune tam, kam chce.|180|vedle_ona_lezi",
    "Klekni si před ni a pomalu jí stahuj punčochy nebo ponožky. U každého kotníku se zastav a polib ho.|90",
    "Zezadu jí zvedni vlasy a líbej ji na zátylek tak dlouho, až se zachvěje.|60|stoje_zezadu",
    "Líbej ji na rameno a pomalu jí přitom shrnuj ramínko. Druhé nech být.|60|svlekani",
    "Posaď si ji na klín zády k sobě a hlaď ji po stehnech nahoru a dolů. Nikdy nedojedeš až nahoru.|180|klin_zady",
    "Tancujte v obýváku, ale ty ji smíš držet jen jednou rukou. Druhou máš za zády.|120|objeti",
    "Šeptem a rukama: Pusť hudbu, staň si za ni a veď ji v pohybu rukama na jejích bocích. Nesmíš promluvit. Cíl: ať se o tebe opře sama.|180|stoje_zezadu",
    "Polib ji na ústa a při každém dalším polibku jí sundej jeden kus oblečení.|120|svlekani",
    "Přejeď jí rty po celém obličeji, ale nepolib ji na ústa. Ani jednou.|60|objeti",
    "Lehni si na záda, posaď si ji na sebe a nech ji, ať tě líbá, jak chce. Ty nesmíš hnout rukama.|180|ona_nahore",
    "Ukaž jí na telefonu fotku nebo scénu, která tě vzrušuje, a popiš jí, co přesně na tom je.|120",
    "Vezmi jí ruce a přitiskni jí je nad hlavu ke zdi. Pak ji líbej, dokud se nezačne kroutit.|90|zed",
    "Nech ji vybrat písničku a po celou dobu se jí smíš dotýkat jen tak, jak se hýbe hudba.|180",
    "Pomalá cesta: Začni polibkem na čelo a postupně se propolibkuj až k pasu. Nesmíš přeskakovat. Cíl: nezrychlit ani jednou.|180|vedle_ona_lezi",
    "Sundej jí podprsenku, ale nedotkni se jí přitom prsou. Ani omylem.|60|svlekani",
    "Vyhrň jí sukni nebo stáhni kalhoty jen tak nízko, aby to bylo ještě víc dráždivé než úplně.|60",
    "Oblíkni ji do svého trička a pak jí ho zase pomalu sundávej.|120|svlekani",
    "Líbej ji na bříško a u pupíku se zastav. Pak se vrať nahoru a začni znovu.|90|vedle_ona_lezi",
    "Lehni si za ni na lžičku a celou dobu ji líbej na rameno. Ruce nech na jejích bocích.|120|lzicka",
    "Tři minuty bez rukou: Dotýkej se jí jen rty, nosem a dechem. Ruce máš celou dobu za zády. Cíl: nepoužít ruce ani jednou.|180",
    "Sedni si naproti ní a nech ji, ať se svléká přesně tak pomalu, jak jí řekneš.|180|tanec",
    "Přitáhni si ji k sobě za pásek nebo lem kalhot a chvíli ji tak drž. Nic víc.|45|objeti",
    "Polib ji do ohbí loktů a do podkolení. Na dvou nečekaných místech.|60",
    "Napiš jí prstem na břicho slovo a nech ji hádat. Když uhodne, dostane polibek, kam si řekne.|90|vedle_ona_lezi",
    "Seber jí telefon a napiš si sám sobě zprávu, co ti dneska udělá. Pak jí ji ukaž.|90",
    "Tři pokusy: Ona si smí zkusit sundat tvoje oblečení, ale jen tři kusy. Zbytek si necháš. Cíl: ať dobře vybere.|90|svlekani",
    "Polož ji na záda, klekni si nad ni a líbej ji shora dolů. Nikam nespěchej.|180|misionar",
    "Stáhni jí kalhotky zuby a pak je nech ležet přesně tam, kam spadly.|90|svlekani",
    "Vezmi jí ruku a nech ji, ať si sama ukáže, kde chce být políbená. A polib to.|60",
    "Zvedni ji do náruče, drž ji a líbej ji, dokud neřekneš dost.|90|zvednuta",
    "Sedni si za ni, rozepni jí podprsenku jednou rukou a pak ruce sundej. Ať si ji svlékne sama.|60|masaz_vsede",
    "Škádlení očima: Svlékej se sám, ale dívej se jí přitom do očí. Nesmíš se usmát. Cíl: ať se ona usměje první.|120|tanec",
    "Líbej jí vnitřní stranu stehen přes látku kalhotek. Jenom přes látku.|120|oral_klek",
    "Táhni jí prstem podél lemu prádla dokola, a to je všechno.|90",
    "Postav ji před zrcadlo, staň si za ni a svlékej ji, ať se dívá.|180|stoje_zezadu",
    "Polib ji tak, jako byste to dělali poprvé. Nesměle a pomalu.|60|objeti",
    "Pusť jí hudbu a hlaď ji do rytmu – rychlé pasáže rychle, pomalé pomalu.|180|vedle_ona_lezi",
    "Sedni si k ní a jen jí odhrnuj vlasy z obličeje a dívej se na ni. Nic jiného.|60",
    "Dvacet polibků: Dej jí dvacet krátkých polibků po celém těle, žádný na stejné místo. Ona počítá. Cíl: dojít do dvaceti bez opakování.|180",
    "Svlékni jí všechno až na jeden kus a ten nech na ní až do konce této úrovně.|90|svlekani",
    "Lehni si vedle ní a jen jí prstem obkresluj obličej. Oči, rty, bradu.|60|vedle_ona_lezi",
    "Kousni ji zlehka do ušního lalůčku a pak dlouho nic nedělej.|30|objeti",
    "Popros ji, ať zůstane oblečená, a dráždi ji jen přes látku, dokud si prádlo sama nestáhne.|180",
    "Hlas do ucha: Pusť jí do jednoho ucha sluchátko s hudbou a do druhého jí šeptej. Cíl: ať poslouchá tebe, ne hudbu.|120",
    "Líbej jí záda odshora dolů podél páteře. Každý polibek o kousek níž.|120|masaz_zada",
    "Nech ji, ať si sama vybere kus tvého oblečení, který jí necháš na sobě.|60",
    "Sedni si proti ní a svlékejte se střídavě po jednom kuse. Kdo se první rozesměje, prohrál.|180|sed_celem",
    "Přitiskni si ji zády k sobě a rukama jí pomalu projeď od ramen po boky a zpátky.|120|stoje_zezadu",
    "Polib ji na místo, kde má nejcitlivější kůži, a tam zůstaň celou minutu.|60",
    "Beze slov: Celý úkol probíhá bez jediného slova. Svlékni ji a polib ji tam, kam ti sama ukáže. Cíl: dorozumět se jen pohledy.|180|svlekani",
    "Dej jí ruce za záda a drž jí je jednou svojí. Druhou ji svlékej.|120|klek_ruce_za_zady",
    "Ukaž jí, jak by ses chtěl, aby se tě dneska dotýkala – na sobě, ne na ní.|90",
    "Lehni si k ní, dej jí ruku pod tričko na záda a jen tak ji hlaď, dokud se neuvolní.|180|lzicka",
    "Táhni jí lemem kalhotek do strany a zase zpět, ale nikdy je nesundej.|90",
    "Polib ji naposledy a pak ustup o dva kroky. Nech ji přijít za tebou.|45|objeti",
  ],

  female: [
    "Svlékej ho jedním kusem za minutu. Mezi každým kusem ho musíš políbit na místo, které jsi právě odhalila.|180|svlekani!",
    "Pomalu mu vyhrň tričko až na hrudník a tam přestaň. Dál se nedostaneš, dokud tě o to nepoprosí.|90|svlekani",
    "Zuby a nic víc: Svlékni mu jeden kus oblečení jen zuby, bez pomoci rukou. Cíl: sundat to, ať to trvá jakkoli.|180|svlekani!",
    "Rozepínej mu knoflíky jeden po druhém a po každém ho polib na odhalené místo. Nespěchej.|120|svlekani!",
    "Sundej mu trenýrky tak, aby se tě ani jednou nedotkl. Když po tobě sáhne, začínáš znovu.|90|svlekani",
    "Postav se před něj a svlékni se sama. On sedí, kouká a nesmí mluvit.|180|tanec",
    "Pusť si jednu písničku a po celou dobu ho líbej na krk. Až skončí, přestaneš.|180|objeti",
    "Dej mu do uší sluchátka s tvojí oblíbenou písničkou a celou tu dobu ho svlékej. On tě neslyší, jen cítí.|180|svlekani",
    "Tanec o dvou pravidlech: Tancujte spolu pomalu, ty ho smíš držet jen kolem krku a nesmíš ho políbit. Cíl: vydržet celou písničku.|180|objeti",
    "Polib ho na deset různých míst a ani jedno nesmí být na ústech. On počítá nahlas.|120",
    "Líbej ho, ale jen horní ret. Jazyk zakázaný.|60|objeti",
    "Polibek na tři doby: Nejdřív jen rty, pak s jazykem, pak mu kousni do rtu. Mezi tím vždycky počkej pět vteřin. Cíl: ať si o další řekne sám.|90|objeti",
    "Přitiskni ho ke zdi a líbej ho tak dlouho, dokud po tobě nesáhne. Ruce měj opřené o zeď, ne na něm.|120|zed",
    "Líbej ho všude tam, kde má oblečení. Přes látku, nikdy na holou kůži.|120",
    "Sedni si mu obkročmo na klín a tři minuty se jenom líbejte. Nic jiného.|180|klin_celem",
    "Dráždi ho přes trenýrky. Nesmíš mu je sundat, dokud neuplyne čas.|180",
    "Jen přes látku: Hlaď ho a dráždi přes spodní prádlo tak dlouho, až si ho bude chtít sundat. Cíl: ať si ho sundá sám.|180",
    "Vsuň mu ruku pod tričko, ale zastav se hned nad pasem. Nikam níž, dokud ti to nedovolí.|90",
    "Polib ho do dlaně, pak do zápěstí a pokračuj vzhůru po vnitřní straně paže až k rameni.|90",
    "Lehni si k němu a celou minutu ho líbej jenom na krk a za ucho. Ruce nech ležet.|60|vedle_on_lezi",
    "Nech ho sednout si na kraj postele, klekni si před něj a líbej mu kolena a stehna. Výš ne.|120|oral_on_vsede",
    "Sundej mu jeden kus oblečení a ten samý si obleč sama. Zůstaňte tak až do konce úkolu.|60|svlekani",
    "Fotka na přání: Nech se od něj vyfotit tak, jak se ti to bude líbit, a pak fotku hned smažte. Cíl: ať se líbíš sama sobě.|180",
    "Napiš mu z druhého konce pokoje zprávu, co mu uděláš. Neříkej to nahlas, jen pošli.|90",
    "Nahraj mu na telefon hlasovku, co s ním chceš dělat, a nech ho, ať si ji poslechne se sluchátky.|120",
    "Pusť mu do sluchátek písničku a mezitím mu prstem obkresluj obrysy těla. Nesmíš mluvit.|180|vedle_on_lezi",
    "Odpočítávej nahlas od deseti a při každém čísle si sundej nebo posuň jeden kus oblečení.|90|tanec",
    "Svlékni se až na jeden kus a postav se před něj. On rozhodne, kdy padne i ten.|60|tanec",
    "Rozehřátí zezadu: Obejmi ho zezadu, líbej ho na šíji a rukama mu zvolna zajeď pod tričko. Cíl: ať se o tebe sám opře.|120|stoje_zezadu!",
    "Líbej ho a u toho si pomalu rozepínej vlastní podprsenku. Až spadne, zastav se a nech ho koukat.|90|svlekani!",
    "Táhni mu špičkou prstu od krku dolů až k pasu a zastav se přesně tam, kde začíná prádlo.|60|vedle_on_lezi",
    "Zakázaná místa: Dotýkej se ho kdekoli, jen ne na hrudníku a mezi nohama. Tři minuty. Cíl: ať ti ruku sám posune tam, kam chce.|180|vedle_on_lezi",
    "Klekni si před něj a pomalu mu stahuj ponožky. U každého kotníku se zastav a polib ho.|90",
    "Zezadu mu prsty prohrábni vlasy a líbej ho na zátylek tak dlouho, až se zachvěje.|60|stoje_zezadu!",
    "Líbej ho na rameno a pomalu mu přitom shrnuj tričko. Druhé rameno nech být.|60|svlekani!",
    "Sedni si mu na klín zády k němu a nech ho, ať tě hladí po stehnech. Ruce mu vodíš ty.|180|klin_zady",
    "Tancujte v obýváku, ale ty ho smíš držet jen jednou rukou. Druhou máš za zády.|120|objeti",
    "Šeptem a rukama: Pusť hudbu, staň si před něj a veď jeho ruce po svém těle. Nesmíš promluvit. Cíl: ať tě chytne sám.|180|objeti",
    "Polib ho na ústa a při každém dalším polibku mu sundej jeden kus oblečení.|120|svlekani!",
    "Přejeď mu rty po celém obličeji, ale nepolib ho na ústa. Ani jednou.|60|objeti",
    "Sedni si na něj obkročmo a líbej ho, jak chceš. On nesmí hnout rukama.|180|ona_nahore",
    "Ukaž mu na telefonu fotku nebo scénu, která tě vzrušuje, a popiš mu, co přesně na tom je.|120",
    "Vezmi mu ruce a přitiskni mu je nad hlavu ke zdi. Pak ho líbej, dokud se nezačne kroutit.|90|zed",
    "Nech ho vybrat písničku a po celou dobu se ho smíš dotýkat jen tak, jak se hýbe hudba.|180",
    "Cesta dolů: Začni polibkem na jeho čele a propolibkuj se centimetr po centimetru až k pasu. Nesmíš nic přeskočit. Cíl: nezrychlit ani jednou.|180|vedle_on_lezi",
    "Svlékni se do pasu, ale nedovol mu, aby se tě dotkl. Ani omylem.|60|tanec",
    "Stáhni mu kalhoty jen tak nízko, aby to bylo ještě víc dráždivé než úplně.|60",
    "Oblékni si jeho tričko a pak si ho před ním zase pomalu sundávej.|120|tanec",
    "Líbej ho na bříško a u pupíku se zastav. Pak se vrať nahoru a začni znovu.|90|vedle_on_lezi",
    "Lehni si za něj na lžičku a celou dobu ho líbej na rameno. Ruce nech na jeho bocích.|120|lzicka",
    "Tři minuty bez rukou: Dotýkej se ho jen rty, nosem a dechem. Ruce máš celou dobu za zády. Cíl: nepoužít ruce ani jednou.|180",
    "Sedni si naproti němu a svlékej se přesně tak pomalu, jak ti řekne.|180|tanec",
    "Přitáhni si ho k sobě za pásek a chvíli ho tak drž. Nic víc.|45|objeti",
    "Polib ho do ohbí loktů a do podkolení. Na dvou nečekaných místech.|60",
    "Napiš mu prstem na hrudník slovo a nech ho hádat. Když uhodne, dostane polibek, kam si řekne.|90|vedle_on_lezi",
    "Seber mu telefon a napiš si sama sobě zprávu, co ti dneska udělá. Pak mu ji ukaž.|90",
    "Tři pokusy: On si smí zkusit sundat tvoje oblečení, ale jen tři kusy. Zbytek si necháš. Cíl: ať dobře vybere.|90|svlekani",
    "Polož ho na záda, klekni si nad něj a líbej ho shora dolů. Nikam nespěchej.|180|oral_ona_vleze",
    "Stáhni mu trenýrky zuby a pak je nech ležet přesně tam, kam spadly.|90|svlekani!",
    "Vezmi jeho ruku a nech ho, ať si sám ukáže, kde chce být políbený. A polib to.|60",
    "Nech se od něj zvednout do náruče a líbej ho, dokud tě nepustí.|90|zvednuta",
    "Sedni si před něj a nech ho, ať ti rozepne podprsenku jednou rukou. Pak mu ruce sundej.|60|masaz_vsede",
    "Škádlení očima: Svlékej se, ale dívej se mu přitom do očí. Nesmíš se usmát. Cíl: ať se on usměje první.|120|tanec",
    "Líbej mu vnitřní stranu stehen přes látku trenýrek. Jenom přes látku.|120|oral_on_vleze",
    "Táhni mu prstem podél lemu prádla dokola, a to je všechno.|90",
    "Postav se před zrcadlo, ať si tě prohlíží, a svlékej se pomalu.|180|tanec",
    "Polib ho tak, jako byste to dělali poprvé. Nesměle a pomalu.|60|objeti",
    "Pusť si hudbu a hlaď ho do rytmu – rychlé pasáže rychle, pomalé pomalu.|180|vedle_on_lezi",
    "Sedni si k němu a jen mu prohrábni vlasy a dívej se na něj. Nic jiného.|60",
    "Dvacet polibků: Dej mu dvacet krátkých polibků po celém těle, žádný na stejné místo. On počítá. Cíl: dojít do dvaceti bez opakování.|180",
    "Svlékni ho všeho až na jeden kus a ten mu nech až do konce této úrovně.|90|svlekani!",
    "Lehni si vedle něj a jen mu prstem obkresluj obličej. Oči, rty, bradu.|60|vedle_on_lezi",
    "Kousni ho zlehka do ušního lalůčku a pak dlouho nic nedělej.|30|objeti",
    "Zůstaň oblečená a nech ho dráždit jen přes látku, dokud si prádlo sama nestáhneš.|180",
    "Hlas do ucha: Pusť mu do jednoho ucha sluchátko s hudbou a do druhého mu šeptej. Cíl: ať poslouchá tebe, ne hudbu.|120",
    "Líbej mu záda odshora dolů podél páteře. Každý polibek o kousek níž.|120|masaz_zada!",
    "Nech ho, ať si sám vybere kus tvého oblečení, který ti nechá na sobě.|60",
    "Sedni si proti němu a svlékejte se střídavě po jednom kuse. Kdo se první rozesměje, prohrál.|180|sed_celem",
    "Přitiskni se k němu zády a veď mu ruce od svých ramen po boky a zpátky.|120|stoje_zezadu",
    "Polib ho na místo, kde má nejcitlivější kůži, a tam zůstaň celou minutu.|60",
    "Beze slov: Celý úkol probíhá bez jediného slova. Svlékni ho a polib ho tam, kam ti sám ukáže. Cíl: dorozumět se jen pohledy.|180|svlekani!",
    "Dej mu ruce za záda a drž mu je jednou svojí. Druhou ho svlékej.|120|klek_ruce_za_zady!",
    "Ukaž mu, jak by ses chtěla, aby se tě dneska dotýkal – na sobě, ne na něm.|90",
    "Lehni si k němu, dej mu ruku pod tričko na záda a jen tak ho hlaď, dokud se neuvolní.|180|lzicka",
    "Táhni mu lemem trenýrek do strany a zase zpět, ale nikdy je nesundej.|90",
    "Polib ho naposledy a pak ustup o dva kroky. Nech ho přijít za tebou.|45|objeti",
  ],
});
