// Kategorie 1 – Škádlení a předehra
// Formát karty: "text" nebo "text|sekundy" (časovač)
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 1,
  name: "Škádlení a předehra",
  description: "Polibky, doteky, šeptání a pomalé svlékání. Pomalu, ať to jiskří.",

  // Úkoly pro muže – pro potěšení ženy
  male: [
    "Mezi jejími koleny: Posaď ji na linku, postav se mezi její kolena a líbej ji – nejdřív rty, pak krk. Cíl: minuta na rtech a teprve pak sjet níž.|90",
    "Pírko poslepu: Přejížděj pírkem po jejím krku, klíčních kostech a vnitřní straně paží. Oči má zavřené. Cíl: tři pomalá kola, pokaždé jinou cestou.|60",
    "Tři věci a tři polibky: Zašeptej jí do ucha tři věci, které na jejím těle miluješ nejvíc, a každou z nich pak polib. Cíl: u každé se zdržet aspoň deset vteřin.|90",
    "Ramena a šíje: Na gauči jí palci masíruj ramena a šíji, dokud jí neklesnou ramena. Cíl: teprve potom jeden polibek za ucho.|120",
    "Ruce nad hlavou: Opři ji zády o zeď, chyť jí zápěstí nad hlavou a líbej ji na krk. Cíl: minuta, při které nesmí ruce sundat.|60|zed",
    "Jednou rukou: Rozepni jí podprsenku jen jednou rukou. Za každý neúspěšný pokus jí dlužíš minutu líbání ramen. Cíl: povést se to napoprvé.|120",
    "Cesta po noze: Klekni si před ni a pokládej polibky od kotníku nahoru až k lemu sukně nebo kraťasů. Výš nesmíš. Cíl: deset polibků na každé noze.|120",
    "Kousek po kousku: Sundávej jí triko co nejpomaleji a každý odhalený kousek kůže polib. Cíl: aby svlékání trvalo celou minutu a nevynechal jsi ani centimetr.|60",
    "Stehna a oči: Hlaď ji po vnitřní straně stehen přes oblečení a celou dobu se jí dívej do očí. Cíl: minuta, při které ani jeden neuhne pohledem.|60",
    "Ruce jen na bocích: Posaď si ji obkročmo na klín a líbejte se. Ruce smíš mít jen na jejích bocích. Cíl: dvě minuty a ani jednou výš nebo níž.|120|klin_celem",
    "Hádej, kam přijde: Zavaž jí oči šátkem a polib ji na pět míst podle svého výběru. Před každým polibkem ať hádá. Cíl: aspoň třikrát ji zmást.|120",
    "Kousnutí a slib: Jemně ji kousni do ušního lalůčku a pošeptej jí, co s ní dnes chceš dělat. Cíl: tři věty, každou po dalším kousnutí.|60",
    "Oba v zrcadle: Stoupni si za ni před zrcadlo, hlaď ji po břiše a bocích a líbej ji na krk. Cíl: nespustit v zrcadle oči z jejích, dokud neuhne.|90",
    "Chodidla a kotníky: Na gauči jí palci namasíruj chodidlo od paty ke špičce a pak polib kotník. Cíl: dvě minuty na každé noze.|240",
    "Objetí zezadu: Obejmi ji zezadu, přitiskni se k ní a pomalu jí přejížděj dlaněmi po stehnech. Cíl: nepřestat, dokud se k tobě sama neotočí.|60",
    "Polibek bez rukou: Líbej ji jen na rty a ruce drž celou dobu za zády. Cíl: minuta, při které se jí nedotkneš ničím jiným než ústy.|60",
    "Pírko a smích: Pírkem opisuj pomalé kroužky kolem jejího pupíku a po bocích. Když se zasměje, začínáš znovu. Cíl: tři kola bez jediného smíchu.|60",
    "Spadlá sukně: Rozepni jí kalhoty nebo sukni a nech je spadnout na zem. Pak se věnuj už jen jejímu krku. Cíl: dvě minuty na krku, dolů se ani nepodívej.|120",
    "Po páteři dolů: Polib ji na zátylek a jazykem pomalu sjeď po páteři tak daleko, jak ti dovolí oblečení. Cíl: tři cesty dolů, pokaždé o kousek níž.|90",
    "Zakázaná místa: Lehni si k ní a konečky prstů ji hlaď po celém těle přes oblečení. Prsa a klín jsou zakázané. Cíl: dvě minuty bez jediného přešlapu.|120",
    "Tajná fantazie: Pošeptej jí svou nejtajnější fantazii, ve které hraje hlavní roli ona. Cíl: dovyprávět ji celou, i když se budeš stydět.|120",
    "Tanec na jednu písničku: Pusť pomalou písničku a tancuj s ní. Během tance ji hlaď po zadečku. Cíl: dotancovat až do konce a nepustit ji.|120",
    "Od kotníků nahoru: Zuj ji, vezmi si jednu nohu do klína a pomalu jí líbej nárt a kotník. Cíl: pět polibků na každé noze, každý delší než předchozí.|90",
    "Masáž hlavy: Prsty jí projížděj vlasy a masíruj pokožku hlavy pomalými kroužky. Oči má zavřené. Cíl: půldruhé minuty a ani slovo.|90",
    "Posaď ji na jídelní stůl, rozevři jí kolena a líbej ji, zatímco ji hladíš po stehnech.|60",
    "Jen dech: Odhrň jí vlasy z krku a pomalu na něj dýchej. Žádné polibky, žádné doteky. Cíl: vydržet celou minutu a teprve pak jeden dlouhý polibek.|60",
    "Pírko na rtech: Přejížděj jí pírkem po rtech tak dlouho, dokud je nepootevře. Cíl: teprve pak ji polib – a nepouštěj, dokud tě sama nepřitáhne.|60",
    "Knoflík po knoflíku: Líbej ji a mezitím jí rozepínej halenku nebo svetr. Cíl: rozepnout všechny knoflíky, aniž bys jednou přerušil polibek.|90",
    "Klekni si za ni na gauči a masíruj jí záda pod tričkem.|120",
    "Přitažení k sobě: Chyť ji oběma rukama za zadeček a přitáhni si ji na polibek. Cíl: nepustit ji celou minutu, ať se snaží odtáhnout, jak chce.|60",
    "Ať si lehne na břicho. Polib každý její obratel – od krku až dolů.",
    "Pomalá cesta ke krku: Přejeď jí jazykem od klíční kosti až k uchu. Jedna cesta trvá aspoň deset vteřin. Cíl: pět cest, ani jedna rychlejší.|90",
    "Vezmi její ruku, polib každý prst a pak jí jemně polib dlaň.",
    "Obsluha ve vaně: Napusť jí vanu, pomoz jí se svléknout a sám zůstaň oblečený. Cíl: vydržet jen u dívání, dokud tě nepozve k sobě.|180",
    "Podrž jí ruce za zády a líbej ji do výstřihu.|60",
    "Lehni si na ni na posteli, propleť s ní prsty nad její hlavou a líbej ji.|60",
    "Řekni jí, co by sis s ní přál dělat v kuchyni – a s jednou věcí hned začni.",
    "Vyber 7 míst na jejím těle, která jsou podle tebe nejvíc sexy. U každého řekni proč a polib ho.",
    "Namaž jí nohy tělovým olejem nebo krémem – od kotníků ke kolenům, pomalými tahy.|120",
    "Slovo na zádech: Napiš jí prstem na záda slovo. Když ho uhodne, dostane polibek, kam si řekne (nad pasem). Cíl: pět slov, pět polibků.|120",
    "Postav ji k oknu se zataženými závěsy, stoupni si za ni, líbej ji na ramena a hlaď po břiše.|60",
    "Za pásek: Přitáhni si ji k sobě za pásek nebo lem kalhot, polib ji a zase ji kousek odstrč. Cíl: třikrát, počtvrté už ji nepouštěj.|90",
    "Střídej jemné kousání a polibky na jejím krku a ramenou.|60",
    "Sedni si na podlahu, ona si sedne mezi tvé nohy zády k tobě. Hlaď ji po pažích a líbej na ramena.|90",
    "Hlava v klíně: Nech ji položit si hlavu do tvého klína, hlaď ji ve vlasech a líbej vzhůru nohama jako Spider-Man. Cíl: tři polibky, mezi nimi minuta hlazení.|180",
    "Svlékni jí jednu věc podle svého výběru a místo, které se odhalí, líbej.|20",
    "Sousto z úst: Dej si mezi rty kousek čokolády nebo ovoce a nech ji, ať si ho vezme polibkem. Cíl: tři sousta, pokaždé pomaleji než předtím.|90",
    "Dotýkej se jí jen dechem – foukej jí jemně na krk, výstřih, břicho a stehna.|60",
    "Odhalené rameno: Pomalu jí stáhni ramínko podprsenky nebo topu a polib odhalené místo. Cíl: obě ramena a mezi nimi deset polibků po klíčních kostech.|90",
    "Objímej ji zezadu a líbej ji na krk, dokud se o tebe sama nezačne otírat zadečkem.",
    "Vezmi ji za ruku a veď ji do ložnice. Cestou se třikrát zastav na různých místech bytu a polib ji.",
    "Lem o kousek níž: Líbej ji na břicho těsně nad lemem kalhotek a zuby ho stáhni níž. Cíl: třikrát posunout lem a po každém deset polibků pod ním.|120",
    "Posaď ji do křesla, klekni si před ni a masíruj jí lýtka a kolena.|120",
    "Těsně před cílem: Vyjeď rukou po jejím stehně co nejvýš a těsně před cílem se zastav. Cíl: pětkrát vyjet a couvnout, dokud tě sama nechytí za ruku.|120",
    "Obě ruce: Polib ji na vnitřní stranu zápěstí, loket a rameno – po jedné ruce nahoru, po druhé dolů. Cíl: šest polibků, každý aspoň tři vteřiny.|90",
    "Stoupni si za ni, polož jí dlaně na prsa přes oblečení a jen je drž, zatímco ji líbáš na krk.|45",
    "Co bylo první: Pošeptej jí do ucha, co tě na ní dnes vzrušilo jako první, a to místo polib. Cíl: tři věci a tři polibky na různých místech.|90",
    "Pírko na obličeji: Přejeď jí pírkem pod bradou, po víčkách a po rtech. Oči má celou dobu zavřené. Cíl: tři kola a teprve po třetím polibek.|90",
    "Zip zuby: Rozepni jí zip na zádech nebo jí vytáhni triko z kalhot – a použij jen zuby. Cíl: zvládnout to bez rukou, ať to trvá jakkoli dlouho.|120",
    "Nech ji stát uprostřed pokoje a obcházej ji dokola. Dotýkej se jí jen konečky prstů.|60",
    "Opři ji o lednici a líbej ji – lednice jí chladí záda, tak ji zepředu zahřívej rukama.|60",
    "Kartáč a šíje: Pročesávej jí vlasy kartáčem pomalu od konečků nahoru. Cíl: padesát tahů a po každém desátém polibek na šíji.|180",
    "Zavaž jí oči. Ona řekne místo nad pasem a ty ho políbíš. Tři kola.",
    "Posaď ji na pračku a líbej ji, ruce měj na jejích stehnech.|60",
    "Punčochy zuby: Sundej jí ponožky nebo punčochy jen zuby, ruce drž celou dobu za zády. Cíl: obě nohy a ani jednou si nepomoct rukama.|120",
    "Lehni si vedle ní a hraj si s jejími vlasy, zatímco jí šeptáš, jak je krásná.|60",
    "Těsně pod zadečkem: Stáhni jí kalhoty, ale nech ji v kalhotkách, a líbej ji zezadu na obě stehna. Cíl: deset polibků, žádný výš než lem kalhotek.|90",
    "Rameno a vlasy: Pomalu ji olízni od ramene až k uchu a přitom ji jemně chytni za vlasy u kořínků. Cíl: tři cesty a po každé jedno lehké zatažení.|90",
    "Posaď ji na gauč a lehni si hlavou na její stehna. Líbej je přes oblečení.|60",
    "Lehni si na ni na posteli – oba ještě oblečení – a pomalu se o ni otírej celým tělem, jako byste už byli nazí.|60",
    "Prohlídka na povel: Svlékni se do spodního prádla a otáčej se přesně tak, jak si řekne. Cíl: plnit její pokyny celou minutu a sám nepromluvit.|60",
    "Namaž jí záda olejem a masíruj je dlouhými tahy od beder k ramenům.|180",
    "Ať spadne sama: Rozepni jí podprsenku, ale nesundávej ji. Jen jí líbej ramena. Cíl: vydržet, dokud ramínka nesklouznou úplně sama.|120",
    "Pírkem přejížděj po vnitřní straně jejích stehen, jen přes kalhotky – nahoru a zase dolů.|45",
    "Doušek a polibek: Nabídni jí sklenku něčeho dobrého a pokaždé, když si lokne, polib ji na krk. Cíl: celá sklenka a ani jeden doušek bez polibku.|180",
    "Sedni si na židli u kuchyňského stolu, ona stojí mezi tvými koleny. Líbej ji na břicho přes oblečení.|60",
    "Triko jako pouto: Přetáhni jí triko přes hlavu, ale nech ho omotané kolem zápěstí. Cíl: minuta polibků na klíční kosti, než jí ruce uvolníš.|60",
    "Rukama jí přejížděj po těle a pojmenovávej, co zrovna hladíš – a proč to miluješ.|90",
    "Opři se s ní o dveře ložnice a líbejte se tak, jako byste se neviděli měsíc.|60",
    "Ruka na krku: Polož jí ruku na krk úplně bez tlaku, palcem jí přejeď po rtech a pak ji polib. Cíl: třikrát po sobě, pokaždé s delším polibkem.|60",
    "Na gauči jí polož nohy do klína a hlaď ji od chodidel až ke kolenům.|90",
    "Stoupni si za ni a pomalu jí rozepni kalhoty. Ruku jí jen polož na podbřišek a nech ji tam.|30",
    "Zavaž jí oči a přejížděj po jejím těle střídavě pírkem a konečky prstů. Ať hádá, co to je.|60",
    "Polib ji na čelo, na víčka, na nos, na tváře – a na rty až úplně nakonec.",
    "Před zrcadlem: Postav se za ni k zrcadlu a sundej jí podprsenku zezadu. Cíl: udržet s ní oční kontakt v zrcadle od prvního doteku až do konce.|90",
    "Lehni si na ni zezadu, když leží na břiše, a líbej ji na krk a lopatky.|60",
    "Bez přerušení polibku: Opři ji o linku a pomalu jí vyhrň sukni nebo stáhni kalhoty, zatímco ji líbáš. Cíl: zvládnout to, aniž bys polibek přerušil.|90",
    "Přejeď jí kostkou ledu po krku a pak to místo zahřej rty.",
    "Prsty na rtech: Pomalu jí přejížděj prsty po rtech a ona ti je smí olíznout. Cíl: deset přejetí a teprve po desátém polibek.|60",
    "Masíruj jí bedra a boky, ona leží na posteli na břiše.|120",
    "Vyzvi ji k pomalému tanci a během něj ji postupně svlékej.|180",
    "Polib ji zezadu na krk, zatímco jí přejíždíš rukama po prsou přes podprsenku.|45",
    "Dej jí pusu na každý prst na noze. Když se zasměje, začni znovu.",
    "Zatímco sedí na gauči, klekni si před ni a hlaď jí stehna od kolen nahoru – přes oblečení, pomalu.|60",
    "Stáhni jí kalhotky pomalu jen o kousek a zase je vytáhni zpátky. Zopakuj to dvakrát.",
    "Přejeď pírkem po jejích prsou přes podprsenku, kolem dokola.|45",
    "Jak voní: Přivoň si k ní za uchem, na krku a na zápěstí a po každém nádechu jí pošeptej, co ti to připomíná. Cíl: tři místa, tři věty.|90",
    "Nech ji sedět na židli. Stoupni si za ni, rozpusť jí vlasy a masíruj jí spánky.|90",
    "Posaď ji na kuchyňský stůl, ať tě obejme nohama kolem pasu, a líbej ji.|60",
    "Podkolenní jamky: Na posteli jí pomalu líbej místo pod koleny, které se skoro nikdy nelíbá. Cíl: minuta na každé noze a ani jednou výš.|120",
    "Jazykem jí jemně olízni rty, ale nenech ji, aby tě políbila. Škádli ji tak ještě chvíli.|30",
    "Sedni si na zem, opři se o gauč a nech ji, ať si ti sedne na klín. Hlaď ji po zádech pod oblečením.|90",
    "Zavaž jí oči a pomalu ji svleč do spodního prádla. Každou věc jí sundej až po polibku.",
    "Líbej ji na záda od lopatek až k bedrům a na konci ji jemně kousni.",
    "Pusť jí vodu do sprchy, svlékni ji a omyj jí záda mýdlem nebo sprchovým gelem.|120",
    "Vyrušení při práci: Přitiskni se k ní zezadu, když něco dělá, a přejeď jí rukou po prsou. Cíl: nepřestat, dokud nenechá práce a neotočí se k tobě.|120",
    "Olízni jí vnitřní stranu zápěstí a foukni na to místo.",
    "Zastavení v chodbě: Zastav ji, chyť ji jemně za bradu a dlouze ji polib. Pak ji pusť a jdi pryč. Cíl: nechat ji stát a nic nevysvětlovat.|60",
    "Na posteli ji pomalu hlaď po břiše kolem pupíku, s každým kolečkem trochu níž – ale ne pod lem kalhotek.|60",
    "Ať si lehne na záda. Přejížděj jí pírkem přes chodidla, lýtka a kolena.|60",
    "Přání a slib: Pověz jí, co by sis dnes přál, aby ti udělala, a slib, že jí to vrátíš dvojnásob. Cíl: říct to nahlas a konkrétně, žádné náznaky.|90",
    "Opři ji o skříň a líbej ji do výstřihu, zatímco jí přejíždíš palci po bocích.|45",
    "Klekni si a stáhni jí kalhoty – nejdřív z jedné nohy, pak z druhé, s polibkem na každé stehno.",
    "Namasíruj jí dlaně a prsty – každý prst zvlášť, pomalu.|90",
    "Zaklonit hlavu: Hlaď ji ve vlasech a lehce za ně zatáhni, aby zaklonila hlavu. Cíl: pět zatažení a po každém jeden dlouhý polibek na odhalený krk.|90",
    "Nech ji ležet na gauči a lehni si vedle ní. Palcem kresli malá kolečka na jejím boku pod tričkem.|60",

    // Karty s cílem
    "Mapa těla: Zavaž jí oči a polib ji postupně na 10 různých míst. Po každém polibku řekne „víc“, nebo „dál“. Cíl: najít tři místa, kde chce víc, a u nich zůstat nejdéle.",
    "Socha: Ona stojí uprostřed obýváku a nesmí se pohnout. Ty ji pomalu svlékáš do spodního prádla a líbáš. Když se pohne nebo zasměje, jednu věc jí zase oblékneš. Cíl: dostat ji do spodního prádla.|180",
    "Horko-studeno: Přejížděj jí kostkou ledu po krku, klíčních kostech a břiše a každé studené místo hned zahřej jazykem. Cíl: aby jí naskočila husí kůže.|90",
    "Šeptaná scéna: Pošeptej jí do ucha co nejpodrobněji jednu erotickou scénu, kterou s ní chceš dnes zažít – kde, jak a co jí uděláš. Cíl: aby ti sama řekla „tak to udělej“.",
    "Tanec s vedením: Pusť pomalou písničku, stoupni si za ni a veď její boky rukama do rytmu. Cíl: do konce písničky jí přetáhnout triko přes hlavu, aniž byste přestali tančit.|180",
    "Krmení na lince: Posaď ji na kuchyňskou linku a krm ji jahodami, čokoládou nebo něčím sladkým. Po každém soustu ji polib a ochutnej sladkost z jejích rtů. Cíl: pět soust, pět polibků.",
    "Knoflíková hra: Rozepínej jí oblečení a za každý knoflík, zip nebo háček jí dej polibek na jiné místo. Cíl: aby zůstala jen ve spodním prádle.",
    "Pírkový test: Ona leží na břiše na posteli. Přejížděj jí pírkem po zádech, stehnech, podkolenních jamkách a chodidlech. Cíl: najít místo, kde se nejvíc zachvěje, a to pak dlouze políbit.|90",
    "Masáž s pravidlem: Masíruj jí záda na posteli. Tvoje ruce smí sjet o kousek níž jen tehdy, když ona tiše vzdychne. Cíl: dostat se masáží až na zadeček.|180",
    "Zrcadlo: Postav ji před zrcadlo a stoupni si za ni. Nahlas popisuj, co na ní vidíš a co na ní miluješ, a každé to místo pohlaď. Cíl: aby se na sebe celou dobu dívala.|120",
    "Nejpomalejší polibek: Přibližuj se k jejím rtům tak pomalu, aby to trvalo 30 vteřin, a pak ji líbej celou minutu. Cíl: aby tě k sobě přitáhla dřív, než se dotknete.|90",
    "Bez rukou: Dej ruce za záda. Jen pusou jí vyhrň triko a polibky se dostaň až k podprsence. Cíl: zvládnout to bez jediného dotyku rukou.|120",
    "U dveří ložnice: Opři ji zády o dveře, jednu ruku dej na dveře vedle její hlavy a líbej ji pomalu od čela přes rty až ke krku. Cíl: aby ti sama zajela rukama pod triko.|60",
    "Kalhoty po centimetrech: Klekni si před ni, rozepni jí kalhoty a stahuj je po kouscích. Za každý kousek odhalené kůže dej polibek. Cíl: kalhoty na zemi a ona celá rozechvělá.",
    "Vůně: Ať zavře oči. Přičichni k jejímu krku, zápěstí, vlasům a podbřišku přes oblečení a u každého místa jí řekni, jak voní. Cíl: aby se jí zrychlil dech.",
    "Tři doteky: Na jejím krku vyzkoušej konečky prstů, dech a rty. Ona vybere, co chce zopakovat. Cíl: tím vybraným dotekem projdi celý její krk a ramena.|60",
    "Kdo uhne pohledem: Sedněte si naproti sobě na podlahu, dívejte se do očí a ty ji přitom hladíš po kolenou a stehnech. Kdo první uhne, svlékne jednu věc. Cíl: vydržet dvě minuty.|120",
    "Židle a zákaz: Posaď ji na židli, ruce jí polož za opěradlo. Obcházej ji a líbej ji zezadu na šíji, zepředu na rty, zboku na ucho. Nesmí se tě dotknout. Cíl: vydržet dvě minuty, pak tě smí obejmout.|120",
    "Ramínka zuby: Stoupni si za ni a stáhni jí zuby ramínka podprsenky – nejdřív jedno, pak druhé. Cíl: nepoužít ruce ani jednou.",
    "Schody z polibků: Ona leží na zádech. Polib ji na kotník, koleno, stehno, bok, žebra, rameno, krk a ucho – každý polibek o chvilku delší. Cíl: poslední polibek na rty trvá aspoň 30 vteřin.",
    "Horké dlaně: Promni si dlaně, aby byly horké, a přilož jí je pod tričkem na podbřišek a bedra. Drž je tam a líbej ji na krk. Cíl: aby se o tebe opřela celou vahou.|60",
    "Pod dekou: Přikryjte se dekou na gauči. Pod dekou ji hlaď po stehnech a bocích, nad dekou se tvař nevinně a mluv o úplně obyčejných věcech. Cíl: aby první přestala mluvit ona.|120",
    "Tři otočky: Na chodbě ji chyť za ruku, roztoč ji jako při tanci a zachyť ji zády k sobě. Obejmi ji a polib na krk. Cíl: tři otočky, každá skončí delším polibkem.",
    "Rozepnutá podprsenka: Sedni si na zem opřený o gauč, ona si sedne mezi tvé nohy. Rozepni jí podprsenku pod tričkem, ale nesundávej ji, a hlaď ji po bocích. Cíl: aby si ji sundala sama.|90",
    "Stíny na zdi: Zhasni a nech svítit jen lampu, ať vrhá stíny. Svlékej ji pomalu tak, abyste oba sledovali svoje stíny na zdi. Cíl: svléknout ji do spodního prádla.|120",
    "Kreslení na záda: Nakresli jí prstem na záda tvar – srdce, hvězdu nebo písmeno. Když uhodne, polib ji. Když ne, sundáš jí jednu věc. Cíl: pět kol.",
    "Po paži nahoru: Polib jí konečky prstů, dlaň, zápěstí, loket, rameno, klíční kost a krk. Na každé zastávce 5 vteřin. Cíl: než dojdeš ke krku, musí mít zavřené oči.",
    "Studená plechovka: Vytáhni z lednice něco studeného a přejeď jí s tím po krku a zátylku. Každé místo hned zahřej rty. Cíl: pět míst, pět zahřátí.",
    "Aranžér: Ona sedí na gauči a ty ji „aranžuješ“ – posuneš jí nohu, odhrneš vlasy, stáhneš ramínko. Každou změnu zakonči polibkem. Cíl: pět změn, poslední už ve spodním prádle.",
    "Polibky po částech: Líbej jí jen horní ret, pak jen dolní, pak jen koutky. Cíl: aby tě chytila za tvář a přitáhla si tě na pořádný polibek.",
    "Přemluv ji: Chceš jí sundat triko, ale ona říká „ne“, dokud ji nepřesvědčíš třemi polibky na místa, která sama určí. Cíl: triko na zemi.",
    "Čtyři způsoby: Hlaď ji přes triko, pak pod ním, pak jen nehty a nakonec jen dechem – každý způsob 30 vteřin. Cíl: zjistit, který má nejradši, a ten zopakovat.|120",
    "Opěradlo: Ona klečí na gauči a opírá se o opěradlo. Stoupni si za ni, rozcuchej jí vlasy, líbej ji po šíji a rukama hlaď boky. Cíl: aby se o tebe zadečkem opřela.|90",
    "Lžička pod peřinou: Lehněte si na bok, ty za ní, a pod peřinou ji pomalu hlaď po břiše a stehnech. Cíl: aby se k tobě sama otočila čelem.|120",
    "Zpomalený film: Svlékni jí triko tak pomalu, aby to trvalo celou minutu. Cíl: ani jednou se nezastavit a nezrychlit.|60",
    "Hlas: Zavaž jí oči a šeptej jí do ucha, co s ní uděláš v další úrovni, zatímco ji hladíš jen po pažích. Cíl: aby tě poprosila, ať přestaneš mluvit a začneš.|90",
    "Stůl a stehna: Ona sedí na jídelním stole, ty stojíš mezi jejími koleny. Hlaď ji po vnějších stranách stehen, s každým tahem o kousek výš. Cíl: dojít až k bokům a pevně si ji přitáhnout.|60",
    "Zapnout, rozepnout: Rozepni jí podprsenku a zase ji zapni. Mezitím ji polib na záda. Cíl: potřetí už ji nezapínej a pomalu ji sundej.",
    "Počítání polibků: Ona počítá nahlas do dvaceti a ty ji za každé číslo políbíš na jiné místo na krku a výstřihu. Když se splete, začíná znovu. Cíl: dojít do dvaceti.",
    "Led na rtech: Drž kostku ledu mezi rty a přejížděj jí s ní po klíčních kostech a výstřihu. Cíl: kostka se musí rozpustit na její kůži.|90",
    "Loďka: Lehni si na záda a nech ji ležet na sobě. Hlaď ji pod oblečením a stahuj jí kalhoty jen rukama a nohama. Cíl: kalhoty pryč, aniž by z tebe slezla.",
    "Z kolen: Klekni si před ni, když sedí na kraji postele. Líbej jí kolena a pomalu je rozevírej, ale s polibky nechoď výš než do poloviny stehen. Cíl: aby tě chytila za vlasy.",
    "Šampon: Ve sprše jí umyj vlasy, pomalu jí masíruj hlavu a pak ji polib na krk. Cíl: aby se o tebe zády opřela a zavřela oči.|120",
    "Společný dech: Lehněte si čelem k sobě, čela u sebe. Dýchejte ve stejném rytmu a přejížděj jí rukou po páteři. Cíl: minuta bez polibku – pak ho dostane.|60",
    "Kdo sáhne výš: Sedněte si vedle sebe na gauč a hlaďte se jen po stehnech přes oblečení. Kdo první sáhne výš, prohrává a svléká si triko. Cíl: vydržet déle než ona.|90",
    "Poslepu na židli: Sedni si na židli, ona si sedne obkročmo na tvůj klín. Rozepni jí podprsenku a líbej ji, ale nesmíš otevřít oči. Cíl: zvládnout to poslepu.",
    "Spirály: Ona leží na břiše jen v kalhotkách. Kresli jí prsty po zádech spirály, které se pomalu blíží k lemu kalhotek. Cíl: zastavit se vždy těsně před ním – pětkrát.|90",
    "Vítej doma: Zahraj si, že přicházíš domů. Opři ji o zeď v chodbě, polib ji, jako byste se týden neviděli, a začni ji svlékat hned tam. Cíl: dojít do ložnice a nechat po cestě tři kusy jejího oblečení.",
    "Uši: Věnuj se jen jejím uším – líbej, olizuj, jemně kousej a šeptej. Cíl: aby jí naskočila husí kůže na pažích.|60",
    "Kompliment za kus: Za každou věc, kterou jí sundáš, jí řekni upřímný kompliment o jejím těle. Cíl: dojít ke spodnímu prádlu s pěti komplimenty.",
    "Vana pro ni: Napusť jí vanu s pěnou, pomoz jí dovnitř a namydli jí ramena a záda. Sám zůstaň venku. Cíl: aby tě pozvala k sobě.|300",
    "Kravata: Dej jí do ruky svou kravatu, pásek nebo lem trika a nech se od ní vést bytem. Cestou ji dvakrát zastav a polib ji. Cíl: v ložnici ji posadit na postel a klečet před ní.",
    "Víno na kůži: Namoč prst ve víně nebo šlehačce, přejeď jí s ním po rtech a olízni je. Pak jí kápni kapku na krk a olízni i tam. Cíl: tři místa, každé o kousek níž.",
    "Obrácený polibek: Stoupni si za ni, když sedí na gauči, zakloň jí jemně hlavu a polib ji vzhůru nohama. Rukama ji přitom hlaď po krku a výstřihu. Cíl: aby se k tobě natáhla pro další.|60",
    "Zákaz rtů: Líbej ji všude na obličeji a na krku, jen ne na rty. Cíl: vydržet, dokud tě o polibek na rty sama nepoprosí.|90",
    "Hra na fotografa: Ona pózuje na posteli, ty jí říkáš, jak se má natočit, a „fotíš“ ji jen očima. Po každé póze ji odměníš polibkem. Cíl: pět póz, v každé má na sobě o kus méně.",
  ],

  // Úkoly pro ženu – pro potěšení muže
  female: [
    "Posaď se mu obkročmo na klín na gauči a pomalu ho líbej, zatímco mu prsty hladíš vlasy.|90",
    "Přejížděj mu pírkem po krku, hrudi a břiše. On má celou dobu zavřené oči.|60",
    "Šepot a kousnutí: Pošeptej mu do ucha, co tě na něm nejvíc vzrušuje, a pak ho kousni do ušního lalůčku. Cíl: tři věci, tři kousnutí.|60",
    "Sundej mu triko co nejpomaleji a každý odhalený kousek kůže polib.",
    "Opři ho o zeď v chodbě, přitiskni se k němu a líbej ho na krk.|60",
    "Udělej mu masáž ramen a šíje, zatímco sedí na židli v kuchyni.|120",
    "První knoflík zuby: Rozepínej mu košili nebo mikinu jen zuby, ruce máš za zády. Cíl: aspoň tři knoflíky, ať to trvá, jak chce.|120",
    "Svlékni se před ním do spodního prádla. Pomalu. On se jen dívá a nesmí se hnout.|90",
    "Hlaď ho po vnitřní straně stehen přes kalhoty a dívej se mu přitom do očí. Nikam dál.|60",
    "Zavaž mu oči šátkem a polib ho na pět míst podle sebe. Ať hádá, kam přijde další polibek.",
    "Líbej ho jen na rty – ale nesmíš se ho dotknout rukama.|60",
    "Posaď ho do křesla a tancuj před ním na jednu písničku. Dotýkat se tě nesmí.|180",
    "Klekni si za něj na posteli a masíruj mu záda.|120",
    "Stehna a nic víc: Stáhni mu kalhoty a líbej ho na obě stehna. Boxerek se ani nedotkni. Cíl: deset polibků na každém stehně, pokaždé o kousek výš.|120",
    "Pomalu ke krku: Přejeď mu jazykem od klíční kosti až k uchu. Jedna cesta trvá aspoň deset vteřin. Cíl: pět cest, ani jedna rychlejší.|90",
    "Posaď se na kuchyňskou linku, přitáhni si ho mezi kolena a obejmi ho nohama.|60",
    "Přitiskni se k němu zezadu a hlaď ho po hrudi a břiše pod tričkem.|60",
    "Veď jeho ruku: Vezmi jeho ruku a polož si ji tam, kde se chceš nechat hladit. Nad pasem. Cíl: tři místa a u každého ho nech hladit celou minutu.|180",
    "Masíruj mu hlavu – prsty ve vlasech, pomalu, on má zavřené oči.|90",
    "Od chodidel nahoru: Stáhni mu ponožky, polib ho na nárt a pak ho hlaď po lýtkách. Cíl: dvě minuty na každé noze a ani jednou nad koleno.|240",
    "Obkroč ho, když leží na zádech, a líbej mu hrudník. Ať ho tvoje vlasy šimrají na kůži.|60",
    "Rozepnout a jít nahoru: Pomalu mu rozepni pásek a kalhoty a pak se věnuj už jen jeho krku. Cíl: dvě minuty na krku, dolů se ani nepodívej.|120",
    "Tvoje tajná fantazie: Pošeptej mu svou nejtajnější fantazii, ve které hraje hlavní roli on. Cíl: dovyprávět ji celou, i když se budeš stydět.|120",
    "Pírkem mu opisuj kolečka kolem bradavek a pupíku.|45",
    "Posaď ho na gauč, lehni si mu hlavou do klína a hlaď ho po stehnech.|60",
    "Zátylek a vlasy: Polib ho na zátylek a přitom ho jemně chytni za vlasy u kořínků. Cíl: pět polibků a po každém jedno lehké zatažení.|60",
    "Kousej ho jemně do krku a ramen – střídej to s polibky.|60",
    "Nech ho sedět na židli a sedni si mu na klín zády k němu. Pomalu se o něj otírej.|45",
    "Přejeď mu nehty lehce po zádech – shora dolů, pomalu.|30",
    "Polib ho na každý prst na ruce a jemně mu olízni dlaň.",
    "Zrcadlo a podprsenka: Postav se před zrcadlo a nech ho dívat se, jak si svlékáš podprsenku. Cíl: nespěchat celou minutu a nespustit z něj v zrcadle oči.|60",
    "Čokoláda mezi rty: Dej si kousek čokolády nebo ovoce mezi rty a nech ho, ať si ho vezme polibkem. Cíl: tři sousta a pokaždé si ho musí vzít pomaleji.|90",
    "Dotýkej se ho jen dechem – foukej mu na krk, hruď, břicho a stehna.|60",
    "Lehni si na něj na posteli, propleť s ním prsty nad jeho hlavou a líbej ho.|60",
    "Svlékni mu jednu věc podle svého výběru a místo, které se odhalí, líbej.|20",
    "Pusť pomalou písničku a tancuj s ním v obýváku přitisknutá k němu, co nejvíc to jde.|120",
    "Řekni a předveď: Zašeptej mu, co s ním chceš dělat v ložnici, a jednu věc hned předveď. Cíl: tři věty a z každé aspoň malá ukázka.|90",
    "Namaž mu záda olejem a masíruj je dlouhými tahy.|180",
    "Za tričko k sobě: Opři se o linku, chyť ho za tričko a přitáhni si ho k polibku. Cíl: nepustit ho, dokud tě sám nezvedne nahoru.|90",
    "Psaní na záda: Napiš mu prstem na záda slovo. Když ho uhodne, dostane polibek, kam si řekne (nad pasem). Cíl: pět slov, pět polibků.|120",
    "Rozepni si pomalu halenku nebo sundej triko, zatímco sedí na gauči a jen se dívá.|60",
    "Klekni si před něj, když sedí, a hlaď ho po stehnech od kolen nahoru – jen přes kalhoty.|60",
    "Ruce v kapsách: Obejmi ho zezadu, zajeď mu rukama do kapes kalhot a nech je tam. Cíl: minuta, při které se hýbou jen tvoje prsty.|60",
    "Polib ho na čelo, víčka, nos a tváře – a na rty až úplně nakonec.",
    "Boxerky o kousek níž: Líbej ho na břicho těsně nad pasem a zuby mu stáhni boxerky níž. Cíl: třikrát posunout lem a po každém deset polibků pod ním.|120",
    "Zavaž mu oči a přejížděj po jeho těle střídavě pírkem a konečky prstů. Ať hádá, co to je.|60",
    "Oblečená si na něj lehni na posteli a pomalu se o něj otírej celým tělem.|60",
    "Nech ho ležet na břiše. Polib každý jeho obratel od krku dolů.",
    "Sedni si na pračku, přitáhni si ho mezi nohy a líbej ho.|60",
    "Triko na zápěstích: Stáhni mu triko přes hlavu, ale nech ho omotané kolem zápěstí. Cíl: minuta polibků na hrudníku, než mu ruce uvolníš.|60",
    "Posaď se na podlahu opřená o gauč a nech ho, ať si lehne hlavou do tvého klína. Hlaď ho ve vlasech a po hrudi.|90",
    "Přejeď mu kostkou ledu po krku a pak to místo zahřej rty.",
    "Nech ho sedět na posteli a svlékni se před ním do spodního prádla – každou věc hoď po něm.",
    "Chodidla na gauči: Namasíruj mu chodidlo palci od paty ke špičkám a pak každý prst zvlášť. Cíl: dvě minuty na každé noze.|240",
    "Nech ho stát uprostřed pokoje a obcházej ho dokola. Dotýkej se ho jen konečky prstů.|60",
    "Co bylo dnes první: Pošeptej mu, co tě na něm dnes vzrušilo jako první, a to místo pak polib. Cíl: tři věci a tři polibky na různých místech.|90",
    "Triko zuby: Vytáhni mu triko z kalhot jen zuby a pak ho polib na podbřišek. Cíl: obejít se úplně bez rukou, ať to trvá jakkoli dlouho.|120",
    "Palec na rtech: Přejeď mu palcem po rtech a nech ho, ať ti ho olízne. Cíl: deset přejetí a teprve po desátém polibek.|60",
    "Opři ho o lednici a líbej ho – lednice mu chladí záda, tak ho zepředu zahřívej svým tělem.|60",
    "Sedni si na kuchyňský stůl, obtoč mu nohy kolem pasu a přitáhni si ho k dlouhému polibku.|60",
    "Vezmi ho za ruku a veď ho do ložnice. Cestou se třikrát zastav na různých místech bytu a polib ho.",
    "Zastavit před cílem: Přejížděj mu prsty po stehně přes kalhoty čím dál výš a těsně před cílem se zastav. Cíl: pětkrát vyjet a pětkrát couvnout.|120",
    "Zatímco sedí na židli, stoupni si za něj, obejmi ho a rukama mu přejížděj po hrudi.|45",
    "Ramínka nech jemu: Rozepni si podprsenku, ale nesundávej ji, a nech ho, ať ti pomalu stáhne ramínka. Cíl: nepomoct mu ani jedním prstem.|90",
    "Nahoru a zase dolů: Polib ho na vnitřní stranu zápěstí, loket a rameno – po jedné ruce nahoru, po druhé dolů. Cíl: šest polibků, každý aspoň tři vteřiny.|90",
    "Pusť mu vodu do sprchy, svlékni ho a umyj mu záda.|120",
    "Na klíně čelem: Posaď se mu na klín čelem k němu a pomalu mu rozepínej košili. Cíl: rozepnout ji celou a ani jednou se přitom nezvednout z klína.|120|klin_celem",
    "Nech ho sedět na gauči. Lehni si vedle něj a palcem mu kresli kolečka na boku pod tričkem.|60",
    "Nakloň se k němu, jako bys ho chtěla políbit, ale na poslední chvíli uhni. Škádli ho tak třikrát a pak ho polib.",
    "Zavaž mu oči a pomalu ho svleč do spodního prádla. Každou věc mu sundej až po polibku.",
    "Líbej mu záda od lopatek až k bedrům a na konci ho jemně kousni.",
    "Namaž mu nohy olejem od kotníků až ke kolenům.|120",
    "Nad lemem boxerek: Stáhni mu kalhoty, ale nech ho v boxerkách, a líbej ho na podbřišek nad jejich lemem. Cíl: deset polibků a ani jeden níž.|90",
    "Jazykem mu jemně olízni rty, ale nenech ho, ať tě políbí. Škádli ho tak ještě chvíli.|30",
    "Pírkem mu přejížděj po vnitřní straně stehen přes boxerky – nahoru a zase dolů.|45",
    "Sedni si vedle něj na gauč, dej mu nohy do klína a chodidly ho pomalu hlaď po stehnech.|45",
    "Zatímco se dívá, přejeď si rukama po celém těle přes oblečení.|45",
    "Cesta do ložnice: Obejmi ho kolem krku a nech se odnést do ložnice. Když to nejde, doveď ho tam ty. Cíl: celou cestu se od něj neodtrhnout.|60",
    "Dej mu pusu na každý prst u nohy. Když se zasměje, začni znovu.",
    "Přitáhnout a odstrčit: Chyť ho za zadek, přitáhni si ho na polibek a pak ho zase kousek odstrč. Cíl: třikrát, počtvrté už ho nepouštěj.|90",
    "Posaď ho na židli, stoupni si mu mezi kolena a nech ho líbat tvoje břicho – ruce musí mít za opěradlem.|60",
    "Ruka pod tričkem: Přejeď mu rukou po hrudi pod tričkem, zastav se na bradavce a jemně ji stiskni. Cíl: pět stisknutí a mezi nimi vždy deset vteřin hlazení.|120",
    "Olízni mu vnitřní stranu zápěstí a foukni na to místo.",
    "Zastavit ho v chodbě: Zastav ho, chyť ho jemně za bradu a dlouze ho polib. Pak ho nech stát a odejdi. Cíl: nic nevysvětlovat.|60",
    "Zatímco leží, hlaď ho po břiše kolem pupíku, s každým kolečkem trochu níž – ale ne pod lem boxerek.|60",
    "Přání a odměna: Pověz mu, co by sis dnes přála, aby ti udělal, a slib, že mu to vrátíš dvojnásob. Cíl: říct to nahlas a konkrétně.|90",
    "Opři ho o skříň, přitiskni se k němu stehnem mezi jeho nohy a líbej ho na krk.|45",
    "Nech ho sedět v křesle. Postav se za něj, rozcuchej mu vlasy a masíruj mu spánky.|90",
    "Minuta na dívání: Lehni si na břicho jen ve spodním prádle a nech ho dívat se. Po minutě ho zavolej k sobě. Cíl: celou minutu se neotočit.|60",
    "Jeho triko na tobě: Obleč si na holé tělo jeho triko a nech ho, ať ti ho zase sundá. Cíl: nedovolit mu k tomu použít ruce – jen zuby.|120",
    "Na gauči mu polož ruce na hruď, pomalu s nimi sjeď až k pásku a zase zpátky.|30",
    "Záklon hlavy: Hlaď ho po zátylku a lehce mu zatáhni za vlasy, aby zaklonil hlavu. Cíl: pět zatažení a po každém dlouhý polibek na krk.|90",
    "Posaď se mu na klín na židli a pomalu mu šeptej, jak moc tě vzrušuje.|45",
    "Klekni si za něj na posteli a hlaď ho po hrudi, zatímco ho líbáš na šíji.|60",
    "Ponožky zuby: Sundej mu ponožky jen zuby, ruce máš za zády. Za každé pomoct si rukou si přidáš minutu navíc. Cíl: zvládnout obě nohy bez pomoci.|120",
    "Lehni si vedle něj a pomalu mu přejížděj nehtem po stehně přes kalhoty – nahoru a dolů.|45",
    "Postav se k oknu se zataženými závěsy, přitáhni si ho za sebe a veď jeho ruce po svém těle.|60",
    "Sklenka a krk: Nabídni mu sklenku něčeho dobrého a pokaždé, když si lokne, polib ho na krk. Cíl: celá sklenka, ani jeden doušek bez polibku.|180",
    "Vyber 7 míst na jeho těle, která jsou podle tebe nejvíc sexy. U každého řekni proč a polib ho.",
    "Namasíruj mu dlaně a prsty – každý zvlášť, pomalu.|90",
    "Zuj se a bosou nohou ho pod stolem pomalu hlaď po lýtku až ke kolenu.|30",
    "Opři se zády o něj, když stojí, a pomalu se o něj otírej zadečkem.|30",
    "Zatímco sedí, klekni si na gauč vedle něj a líbej ho na ucho a krk. Ruku mu polož na stehno.|60",
    "Vezmi jeho dlaně a pomalu je veď po svých bocích a stehnech přes oblečení.|45",
    "Lehni si na něj, když leží na břiše, a líbej ho na krk a lopatky.|60",
    "V koupelně mu pomalu namaž tvář krémem po holení – zblízka, s pohledem do očí a polibkem na konci.",
    "Posaď se na zem mezi jeho nohy, když sedí na gauči, a hlaď ho po lýtkách a stehnech.|60",
    "Vyrušení uprostřed práce: Přitiskni se k němu zezadu, když něco dělá, a sjeď mu rukou po zadku. Cíl: nepřestat, dokud nenechá práce a neotočí se.|120",
    "Prohlídka dokola: Svlékni ho do boxerek, sama zůstaň oblečená a pomalu ho obejdi. Cíl: tři kola a u každého nahlas řekni, co se ti líbí.|120",
    "Pírko na tváři: Přejeď mu pírkem pod bradou, po víčkách a po rtech. Oči má zavřené. Cíl: tři kola a teprve po třetím polibek.|90",
    "Na posteli se k němu přitul, jemně ho kousej do ucha a líbej ho, dokud se k tobě neotočí.",
    "Nalij mu na hrudník trochu oleje a pomalu ho rozetři.|90",
    "Sedni si mu obkročmo na stehna, když leží, a jen pomalu přejížděj rukama po jeho těle.|60",

    // Karty s cílem
    "Průzkum poslepu: Zavaž mu oči a polibky prozkoumej jeho hruď, krk a břicho. Po každém polibku buď spokojeně zabručí, nebo mlčí. Cíl: najít tři místa, kde zabručí nejvíc, a vrátit se k nim.",
    "Nehybný: On stojí v obýváku a nesmí se hnout. Ty ho pomalu svlékáš do boxerek a líbáš. Když se pohne, jednu věc mu obleč zpátky. Cíl: dostat ho do boxerek.|180",
    "Striptýz na písničku: Pusť písničku, on sedí v křesle. Každých 20 vteřin sundej jednu věc a tancuj. Cíl: na konci písničky být ve spodním prádle a sednout si mu na klín.|180",
    "Led a teplo: Přejeď mu kostkou ledu po hrudi a bradavkách a každé studené místo hned zahřej pusou. Cíl: aby mu naskočila husí kůže.|90",
    "Scéna do ucha: Pošeptej mu do ucha scénu, kterou s ním dnes chceš zažít – kde, jak a co budeš mít na sobě. Cíl: aby ti řekl „tak pojď“.",
    "Krmení na klíně: Posaď ho na židli v kuchyni, sedni si mu na klín a krm ho ovocem nebo čokoládou ze svých rtů. Cíl: pět soust, každé zakončené polibkem.",
    "Za každý knoflík: Rozepínej mu košili, mikinu nebo kalhoty a za každý knoflík či zip mu dej polibek jinam. Cíl: aby zůstal jen v boxerkách.",
    "Pírkový průzkum: On leží na břiše. Přejížděj mu pírkem po zádech, bocích, stehnech a chodidlech. Cíl: najít místo, kde se zachvěje nejvíc, a dlouze ho políbit.|90",
    "Masáž za zabručení: Masíruj mu záda. Ruce smí sjet o kousek níž, jen když spokojeně zabručí. Cíl: dostat se masáží až na jeho zadek.|180",
    "Tanec na klíně: Posaď ho na židli bez opěrek a ruce mu dej za záda. Oblečená se na jeho klíně pomalu vlň do rytmu hudby. Nesmí tě chytit. Cíl: vydržet celou písničku.|180",
    "Pomalé přiblížení: Přibližuj se k jeho rtům 30 vteřin a pak ho líbej celou minutu. Cíl: aby tě chytil dřív, než se dotknete.|90",
    "Zuby a triko: Dej ruce za záda. Zuby mu vytáhni triko z kalhot a polibky stoupej po břiše k hrudi. Cíl: zvládnout to bez rukou.|120",
    "Přišpendlený: Přitiskni ho zády ke dveřím ložnice, podrž mu ruce nad hlavou a líbej ho od ucha po klíční kost. Cíl: aby se ti vysmekl a pevně tě objal.|60",
    "Pásek: Rozepni mu pásek a vytáhni ho z kalhot jedním pomalým tahem. Pak ho hoď na zem. Cíl: celou dobu se mu dívat do očí.",
    "Jeho vůně: Přičichni k jeho krku, hrudi, zápěstí a podbřišku přes oblečení a u každého místa mu řekni, co ti jeho vůně dělá. Cíl: aby si tě přitáhl.",
    "Tři dotyky: Na jeho krku vyzkoušej konečky prstů, nehty a rty. On vybere, co chce znovu. Cíl: tím vybraným projdi celou jeho hruď.|60",
    "Souboj pohledů: Sedněte si na zem naproti sobě a dívejte se do očí, ty mu přitom hladíš stehna. Kdo první uhne, svlékne jednu věc. Cíl: vydržet dvě minuty.|120",
    "Obcházení židle: Posaď ho na židli a obcházej ho – líbej ho zezadu na krk, zepředu na rty, zboku na ucho. Nesmí se tě dotknout. Cíl: dvě minuty, pak tě smí chytit.|120",
    "Stupně polibků: On leží na zádech. Polib ho na kotník, koleno, stehno, bok, žebra, bradavku, krk a nakonec na rty – každý polibek delší. Cíl: poslední polibek trvá aspoň 30 vteřin.",
    "Horké ruce: Promni si dlaně do horka a přilož mu je pod triko na podbřišek a bedra. Líbej ho na krk. Cíl: aby se mu zrychlil dech.|60",
    "Pod dekou pro něj: Na gauči pod dekou ho hlaď po stehnech, pořád výš, zatímco nahoře vedeš úplně normální rozhovor. Cíl: aby první přestal mluvit on.|120",
    "Jeho trůn: Posaď ho na zem opřeného o gauč a sedni si mu obkročmo na klín čelem k němu. Líbej ho a pomalu mu sundej triko. Cíl: aby tě chytil za zadek.|90",
    "Hlava v klíně: Nech ho položit si hlavu do tvého klína na gauči. Masíruj mu spánky, čelo a vlasy a pak ho polib vzhůru nohama. Cíl: aby zavřel oči a vzdychl.|120",
    "Stínohra: Zhasni a nech svítit jen lampu. Svlékej se pomalu tak, aby tvůj stín tančil na zdi, a on se dívá. Cíl: skončit ve spodním prádle a sednout si mu na klín.|120",
    "Hádej tvar: Nakresli mu prstem na záda tvar nebo písmeno. Když uhodne, dostane polibek, když ne, sundá si jednu věc. Cíl: pět kol.",
    "Cestou po paži: Polib mu konečky prstů, dlaň, zápěstí, loket, rameno a krk. Na každé zastávce 5 vteřin. Cíl: u krku už musí mít zavřené oči.",
    "Studený dotek: Vezmi z lednice něco studeného, přejeď mu s tím po zátylku a břiše a místo hned zahřej rty. Cíl: pět míst.",
    "Aranžérka: On sedí na gauči a ty ho „aranžuješ“ – rozepneš mu košili, vyhrneš triko, rozepneš knoflík u kalhot. Každou změnu zakonči polibkem. Cíl: pět změn, na konci bez trika.",
    "Rty po částech: Líbej mu jen horní ret, pak dolní, pak koutky. Cíl: aby tě chytil za tvář a políbil tě naplno.",
    "Přesvědč mě: Chceš mu sundat triko, ale on se brání, dokud ho nepřesvědčíš třemi polibky na místa, která určí. Cíl: triko na zemi.",
    "Čtyři doteky: Hlaď ho přes triko, pak pod ním, pak jen nehty a nakonec jen dechem – každé 30 vteřin. Cíl: zjistit, co ho nejvíc bere, a to zopakovat.|120",
    "Kočka: Lez k němu po gauči po čtyřech, pomalu a s pohledem do očí, a zastav se těsně před jeho rty. Cíl: dotknout se ho až ve chvíli, kdy se pro polibek natáhne sám.",
    "Obrácená lžička: Lehni si za něj, oba na boku, ty za jeho zády. Hlaď ho po hrudi a břiše. Cíl: aby se k tobě otočil čelem.|120",
    "Minutové triko: Sundej mu triko tak pomalu, aby to trvalo celou minutu. Cíl: nezastavit se.|60",
    "Hlas ve tmě: Zavaž mu oči a šeptej mu, co s ním budeš dělat v další úrovni, zatímco ho hladíš jen po pažích. Cíl: aby tě poprosil, ať přestaneš mluvit a začneš.|90",
    "Na stole: Sedni si na jídelní stůl a přitáhni si ho mezi kolena. Obejmi ho nohama kolem pasu a rukama mu přejížděj po zádech pod tričkem. Cíl: aby se o tebe opřel celou vahou.|60",
    "Dvacet polibků: On počítá nahlas do dvaceti a ty ho za každé číslo polibíš jinam. Když se splete, začíná znovu. Cíl: dojít do dvaceti.",
    "Rozpuštěný led: Drž kostku ledu mezi rty a přejížděj mu s ní po krku a hrudi. Cíl: kostka se musí rozpustit na jeho kůži.|90",
    "Nahoře: Lehni si na něj, když leží na zádech, a jen rukama a nohama mu stáhni kalhoty. Cíl: kalhoty pryč, aniž bys z něj slezla.",
    "U postele: Klekni si před něj, když sedí na posteli, a líbej mu kolena a stehna přes kalhoty, pořád výš. Cíl: zastavit se těsně před klínem a podívat se mu do očí.",
    "Mytí hlavy: Ve sprše mu umyj vlasy a pomalu mu masíruj hlavu, přitisknutá k jeho zádům. Cíl: aby se o tebe opřel a zavřel oči.|120",
    "Dech na dech: Lehněte si čelem k sobě, čela u sebe, a dýchejte stejně. Hlaď ho po páteři. Cíl: minuta bez polibku – pak ho dostane.|60",
    "Rozepínání poslepu: Posaď ho na židli a sedni si mu obkročmo na klín. Se zavřenýma očima mu rozepni košili nebo sundej triko. Cíl: zvládnout to poslepu.",
    "Spirály k boxerkám: On leží na břiše jen v boxerkách. Kresli mu prsty po zádech spirály, které se blíží k lemu boxerek. Cíl: vždy se zastavit těsně před ním – pětkrát.|90",
    "Návrat domů: Zahrajte si, že přichází domů. Přitiskni ho ke zdi v chodbě, polib ho, jako byste se týden neviděli, a začni ho svlékat. Cíl: dojít do ložnice a nechat po cestě tři kusy jeho oblečení.",
    "Jeho uši: Věnuj se jen jeho uším – líbej, olizuj, jemně kousej a šeptej. Cíl: aby mu naskočila husí kůže.|60",
    "Kompliment za každý kus: Za každou věc, kterou mu sundáš, mu řekni upřímný kompliment o jeho těle. Cíl: dojít k boxerkám s pěti komplimenty.",
    "Vana pro něj: Napusť mu vanu, pomoz mu dovnitř a namydli mu ramena a hruď. Sama zůstaň venku. Cíl: aby tě pozval k sobě.|300",
    "Jeho košile: Obleč si jeho košili nebo triko na holé tělo a přijď za ním. Za každý polibek, který ti dá, smí rozepnout jeden knoflík. Cíl: košile úplně rozepnutá.",
    "Za triko do ložnice: Chyť ho za lem trika, kravatu nebo pásek a veď ho bytem do ložnice. Cestou se dvakrát zastav a polib ho. Cíl: posadit ho na postel.",
    "Nehty po zádech: Sedni si za něj na posteli a přejížděj mu nehty po zádech – nejdřív lehce, pak pevněji. Cíl: najít sílu, při které zasténá.|60",
    "Ochutnávka: Namoč prst ve víně, šlehačce nebo medu a nech ho olíznout. Pak si kapku dej na krk a nech ho olíznout i tam. Cíl: tři místa, každé níž.",
    "Polibek vzhůru nohama: Stoupni si za něj, když sedí na gauči, zakloň mu hlavu a polib ho vzhůru nohama. Rukama ho hlaď po hrudi pod tričkem. Cíl: aby se po tobě natáhl.|60",
    "Pohled přes rameno: Stoupni si k oknu se zataženými závěsy zády k němu, pomalu si sundej triko a podívej se na něj přes rameno. Cíl: počkat, až přijde sám a obejme tě.",
    "Bez rtů: Líbej ho všude na obličeji a krku, jen ne na rty. Cíl: vydržet, dokud tě o polibek nepoprosí.|90",
    "Podprsenková výzva: Sedni si zády k němu a nech ho rozepnout ti podprsenku jen jednou rukou. Cíl: pokud to nezvládne do 30 vteřin, dluží ti masáž nohou; když to zvládne, smí ti ji sundat zuby.|30",
  ],
});
