// Kategorie 1 – Škádlení a předehra (dávka b)
// Témata: oční kontakt, dech, blízkost, šeptání, komplimenty, přiznání a fantazie.
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 1,

  male: [
    "Sedněte si čelem k sobě, kolena o kolena, a tři minuty se jen dívejte do očí. Kdo první uhne pohledem, svlékne si jeden kus oblečení.|180|sed_celem",
    "Dýchej s ní: seď proti ní, dlaň jí polož na hrudník a snaž se nadechovat přesně s ní. Nic víc, jen dech.|120|sed_celem",
    "Blízkost na doraz: Přibliž obličej k jejímu tak, aby se vaše rty skoro dotýkaly, a vydrž tak. Nesmíš ji políbit, dokud ona neudělá první krok. Cíl: ať tě políbí jako první.|90|objeti",
    "Šeptej jí do ucha, co sis o ní myslel, když jste se poprvé viděli. Konkrétně a pomalu.|60|objeti",
    "Posaď si ji na klín, obejmi ji kolem pasu a vyjmenuj pět věcí, které na ní máš rád a které nemají nic společného s jejím tělem.|90|klin_celem",
    "Řekni jí nahlas svou nejtajnější fantazii. Celou, i tu část, za kterou se trochu stydíš.|90|sed_celem",
    "Sedni si za ni, opři si ji o hrudník a šeptej jí do ucha, co všechno s ní dneska chceš udělat. Ruce drž na jejích bocích.|120|klin_podlaha",
    "Tři komplimenty: Řekni jí jeden o jejích očích, jeden o jejím hlasu a jeden o tom, jak se směje. Mezi každým ji polib na čelo. Cíl: ať se začervená.",
    "Zeptej se jí, co ji dneska nejvíc vzrušuje, a bez ptaní a bez komentáře to prostě udělej.|120",
    "Dívej se jí do očí a řekni jí přesně, co bys s ní dělal, kdybyste měli celý den jen pro sebe.|90|sed_celem",
    "Tichá hra: mluvit smíš jen ty. Ona nesmí říct ani slovo, jen reagovat tělem. Vyprávěj jí, co s ní budeš dělat.|120",
    "Polož jí čelo na čelo, zavři oči a jen tak zůstaňte. Žádné ruce, žádná slova.|60|sed_celem",
    "Vezmi její ruku, polib každý prst zvlášť a u každého řekni jednu věc, kterou by ti s ní chtěl udělat.|90",
    "Pošeptej jí tři slova, která bys jí nikdy neřekl před nikým jiným.|45",
    "Zpověď: Řekni jí jednu věc, kterou jsi na ní kdy tajně obdivoval a nikdy jí to neřekl. Pak ji polib na místo, o kterém mluvíš. Cíl: nic si nenech pro sebe.|60",
    "Seďte zády k sobě, opřete se o sebe a vyprávěj jí, jak si představuješ ideální večer s ní. Nesmíš se otočit.|120|sed_zady",
    "Zavaž jí oči a celou minutu jí jen šeptej do ucha. Nedotkneš se jí ani jednou.|60",
    "Polož jí ruku na srdce a řekni jí, jak ti tluče srdce, když se svlékne.|45|objeti",
    "Popiš jí nahlas a pomalu, co přesně na ní teď vidíš a co to s tebou dělá. Ani se jí nedotkni.|90",
    "Zeptej se jí na tři věci, které nikdy nezkusila a ráda by. Jednu z nich jí slib na dnešek.|90|sed_celem",
    "Dvacet vteřin: Drž ji v objetí přesně dvacet vteřin a nic neříkej. Pak jí řekni jednu větu, která ji dostane. Cíl: jedna věta, žádné řeči navíc.|30|objeti",
    "Šeptej jí jméno, jak ho říkáš jenom ty, a u toho ji lehce líbej na krk.|60|stoje_zezadu",
    "Vyprávěj jí, co se ti na ní líbí nejvíc, když spí vedle tebe. Šeptem, u ucha.|60|lzicka",
    "Popros ji, ať zavře oči, a pak jí popiš, co bys s ní právě teď udělal, kdyby nebyla žádná pravidla.|90",
    "Sedni si naproti ní, drž ji za obě ruce a vyjmenuj pět momentů s ní, na které nikdy nezapomeneš.|120|sed_celem",
    "Přiznej se jí k jedné fantazii, o které sis myslel, že ti ji nikdy neschválí.|60",
    "Dvě pravdy a jedno přání: Řekni jí dvě věci, které se ti na ní líbí, a jedno, co bys chtěl zkusit. Cíl: ať sama vybere, co uděláte.|90",
    "Řekni jí pomalu do ucha jednu sprostou větu. Jenom jednu, a pak dlouho mlč.|30",
    "Sedni si za ni, drž ji kolem pasu a nech ji, ať ti vypráví svoji fantazii. Ty jen posloucháš a hladíš ji po břiše.|180|klin_podlaha",
    "Polož jí obě dlaně na tváře, dívej se jí do očí a řekni jí, co s tebou dělá, když se na tebe takhle podívá.|45|sed_celem",
    "Nedotýkej se: Postav se těsně před ni a popisuj jí, co jí právě chceš udělat. Ruce musíš mít za zády celou dobu. Cíl: ať ona sáhne po tobě jako první.|120|objeti",
    "Vedle sebe vleže jí do ucha přečti nebo pošeptej scénu, kterou byste spolu mohli zahrát.|120|vedle_ona_lezi",
    "Řekni jí, jak vypadá, když se udělá. Pomalu, slovo po slovu, do ucha.|60|vedle_ona_lezi",
    "Zeptej se jí, jaké slovo ji vzrušuje nejvíc. Pak jí ho celou minutu opakuj do ucha.|60",
    "Sedni si k ní, drž ji za zápěstí a řekni jí přesně, co se ti na ní líbilo dneska přes den.|60|sed_celem",
    "Šeptané ano: Pokládej jí otázky, na které může odpovědět jen ano nebo ne. Vyzvídej, co dneska chce. Cíl: zjistit tři jasná ano.|120|sed_celem",
    "Obejmi ji zezadu, dej jí bradu na rameno a řekni jí, co s tebou dělá, když se před tebou svléká.|60|stoje_zezadu",
    "Přiznej se jí, na co myslíš, když jsi sám. Žádné vytáčky.|60",
    "Drž jí ruku na svém hrudníku, ať cítí tvůj tep, a povídej jí, jak moc ji chceš.|60|sed_celem",
    "Popiš jí, co uděláš jako první, až ji svlékneš. A pak ještě chvíli počkej.|60",
    "Nakloň se k ní, dýchej jí na krk a nic neříkej. Vydrž, dokud tě sama nepolíbí.|60|objeti",
    "Pomalá otázka: Zeptej se jí, kde přesně chce, abys ji políbil. Pak to udělej, ale až za třicet vteřin. Cíl: ať se nemůže dočkat.|60",
    "Seďte proti sobě a střídavě si říkejte, co jste si o tom druhém mysleli první měsíc. Bez cenzury.|180|sed_celem",
    "Šeptej jí do ucha, jak si představuješ, že se tě dneska bude dotýkat ona.|60|lzicka",
    "Polož jí hlavu do klína a nech ji, ať ti hraje s vlasy, zatímco jí vyprávíš svou fantazii.|120",
    "Řekni jí tři věci, které bys s ní chtěl zkusit, ale nikdy sis netroufl navrhnout.|90",
    "Zavaž si oči ty a nech ji, ať ti šeptá do ucha. Ty jen posloucháš a nesmíš se hnout.|120",
    "Vyznání z ticha: Napiš jí prstem na záda tři slova a nech ji hádat, co jsi napsal. Když uhodne, splníš jí přání. Cíl: ať uhodne.|90|masaz_vsede",
    "Sedni si k ní blízko a vyprávěj jí, jak sis ji představoval, než jste spolu poprvé byli.|90|sed_celem",
    "Šeptej jí, co se ti na ní líbí, a u každé věci se jí toho místa lehce dotkni špičkou prstu.|120|vedle_ona_lezi",
    "Zeptej se jí: rychle a bez přemýšlení, co teď chce nejvíc. A dej jí to.|45",
    "Vezmi ji za ruku, polož si ji na tvář a jen tak zůstaňte. Dívejte se na sebe a nemluvte.|60|sed_celem",
    "Přiznej jí jednu věc, kterou jsi jí nikdy neřekl, protože ses bál, co si o tobě pomyslí.|60",
    "Deset vteřin na odpověď: Ptej se jí na choulostivé věci a ona má vždycky deset vteřin na odpověď. Pět otázek. Cíl: ať aspoň jednou zaváhá.|120|sed_celem",
    "Šeptej jí do ucha, co všechno na ní dneska cítíš a jak ti to voní.|45|objeti",
    "Popiš jí, jak přesně bys ji chtěl mít na sobě, a pak počkej, jestli to udělá.|60",
    "Polož si ji na klín, obejmi ji a mlčte spolu celou minutu. Jen dýchejte.|60|klin_podlaha",
    "Vyprávěj jí, co bys s ní dělal, kdyby vás nikdo nesměl vyrušit celý víkend.|120|vedle_ona_lezi",
    "Řekni jí do ucha jednu větu, kterou by od tebe nečekala. Klidně drzou.|30",
    "Ptej se jí na to, co si nikdy netroufla vyslovit, a slib, že se nebudeš divit.|120|sed_celem",
    "Hra na sochu: Ona se nesmí hnout, ty jí chodíš kolem a nahlas popisuješ, co se ti na ní líbí. Když se pohne, začínáš znovu. Cíl: projít celé tělo.|120",
    "Obejmi ji tak dlouho, dokud se ti nezklidní dech. Pak ji polib a pusť.|60|objeti",
    "Šeptej jí, co uděláš, až skončí tahle hra. A buď hodně konkrétní.|60",
    "Polož jí hlavu na břicho, poslouchej ji a vyprávěj jí, co ti to připomíná.|90|vedle_ona_lezi",
    "Řekni jí tři věci, po kterých ti dneska bylo těžko od ní odejít.|60",
    "Vezmi ji za bradu, otoč jí obličej k sobě a chvíli se jen dívej. Pak ji polib.|45|objeti",
    "Popiš jí, jak ji chceš svlékat – kus po kusu, v jakém pořadí a proč.|90|svlekani",
    "Šeptané instrukce: Šeptej jí, co si má se sebou dělat, a ona to poslouchá. Ty se jí nedotkneš. Cíl: tři pokyny, žádný dotek.|180",
    "Zeptej se jí, jaký dotek má nejraději, a pak jí ho dej. Ale jen jednou.|60",
    "Řekni jí, co na ní obdivuješ, když je oblečená, a co, když není.|60",
    "Polož jí ruce na ramena zezadu a šeptej jí, co se ti honí hlavou.|60|masaz_vsede",
    "Vyprávěj jí, jaká byla poprvé, a co si z toho večera pamatuješ nejlíp.|120|vedle_ona_lezi",
    "Zeptej se jí, jestli má nějaké tajemství, které ti ještě neřekla. Nenaléhej, jen se ptej.|90|sed_celem",
    "Povídej jí do ucha o tom, jak ji vidíš ty – a použij slova, která před ní běžně nepoužíváš.|60",
    "Pravidlo jednoho slova: Ona smí odpovídat jen jedním slovem. Vyptávej se, co chce dneska zkusit. Cíl: složit z jejích slov plán večera.|120|sed_celem",
    "Drž ji za obě ruce a řekni jí, co pro tebe znamená, když se ti úplně odevzdá.|60|sed_celem",
    "Šeptej jí do ucha její jméno a mezi tím vždycky jednu věc, co s ní chceš udělat.|90|stoje_zezadu",
    "Řekni jí, které místo na jejím těle ti nejvíc chybí, když nejste spolu. A polib ho.|60",
    "Pokládej jí hlavu do dlaní, dívej se jí do očí a mlčky počkej, až sama promluví.|60|sed_celem",
    "Vyprávěj jí něco sprostého, ale úplně klidným hlasem, jako bys hlásil počasí.|90",
    "Zeptej se jí, jak moc tě dneska chce, na stupnici od jedné do deseti. A pak udělej všechno pro to, aby to byla desítka.|120",
    "Popiš jí přesně, jak vypadá, když se na tebe dívá zezdola.|45",
    "Poslední slovo: Řekni jí jednu větu a pak už do konce úkolu nesmíš promluvit, jen se jí dívat do očí. Cíl: ať promluví ona.|90|sed_celem",
    "Obejmi ji zezadu, položte si ruce na břicho a dýchejte spolu, dokud se nesladíte.|90|stoje_zezadu",
    "Řekni jí, co bys jí dneska nejradši udělal, a nech ji rozhodnout, jestli to dovolí.|60",
  ],

  female: [
    "Posaď se proti němu, kolena o kolena, a tři minuty mu koukej do očí. Kdo první uhne pohledem, svlékne si jeden kus oblečení.|180|sed_celem",
    "Dýchej s ním: seď proti němu, dlaň mu polož na hrudník a nadechuj se přesně s ním. Nic víc, jen dech.|120|sed_celem",
    "Skoro polibek: Přibliž rty k jeho tak, aby se skoro dotýkaly, a vydrž. Nesmíš ho políbit, dokud on neudělá první krok. Cíl: ať tě políbí jako první.|90|objeti",
    "Šeptej mu do ucha, co sis o něm myslela, když jste se poprvé viděli. Konkrétně a pomalu.|60|objeti",
    "Sedni si mu na klín, obejmi ho kolem krku a vyjmenuj pět věcí, které na něm máš ráda a které nemají nic společného s jeho tělem.|90|klin_celem",
    "Řekni mu nahlas svou nejtajnější fantazii. Celou, i tu část, za kterou se trochu stydíš.|90|sed_celem",
    "Sedni si mu mezi nohy, opři se mu o hrudník a povídej mu, co všechno s ním dneska chceš udělat.|120|klin_podlaha",
    "Tři komplimenty: Řekni mu jeden o jeho rukou, jeden o jeho hlasu a jeden o tom, jak se na tebe dívá. Mezi každým ho polib. Cíl: ať nemá co odpovědět.",
    "Zeptej se ho, co ho dneska nejvíc vzrušuje, a bez ptaní a bez komentáře to prostě udělej.|120",
    "Dívej se mu do očí a řekni mu přesně, co bys s ním dělala, kdybyste měli celý den jen pro sebe.|90|sed_celem",
    "Tichá hra: mluvit smíš jen ty. On nesmí říct ani slovo, jen reagovat tělem. Vyprávěj mu, co s ním budeš dělat.|120",
    "Polož mu čelo na čelo, zavři oči a jen tak zůstaňte. Žádné ruce, žádná slova.|60|sed_celem",
    "Vezmi jeho ruku, polib každý prst zvlášť a u každého řekni jednu věc, kterou bys s ním chtěla zkusit.|90",
    "Pošeptej mu tři slova, která bys nikdy neřekla před nikým jiným.|45",
    "Zpověď: Řekni mu jednu věc, kterou jsi na něm tajně obdivovala a nikdy jsi mu to neřekla. Pak ho polib na místo, o kterém mluvíš. Cíl: nic si nenech pro sebe.|60",
    "Seďte zády k sobě, opřete se o sebe a vyprávěj mu, jak si představuješ ideální večer s ním. Nesmíš se otočit.|120|sed_zady",
    "Zavaž mu oči a celou minutu mu jen šeptej do ucha. Nedotkneš se ho ani jednou.|60",
    "Polož mu ruku na srdce a řekni mu, jak ti tluče srdce, když se před tebou svlékne.|45|objeti",
    "Popiš mu nahlas a pomalu, co přesně na něm teď vidíš a co to s tebou dělá. Ani se ho nedotkni.|90",
    "Zeptej se ho na tři věci, které nikdy nezkusil a rád by. Jednu z nich mu slib na dnešek.|90|sed_celem",
    "Dvacet vteřin: Drž ho v objetí přesně dvacet vteřin a nic neříkej. Pak mu řekni jednu větu, která ho dostane. Cíl: jedna věta, žádné řeči navíc.|30|objeti",
    "Šeptej mu jméno, jak ho říkáš jenom ty, a u toho ho lehce líbej na krk.|60|objeti",
    "Vyprávěj mu, co se ti na něm líbí nejvíc, když spí vedle tebe. Šeptem, u ucha.|60|lzicka",
    "Popros ho, ať zavře oči, a pak mu popiš, co bys s ním právě teď udělala, kdyby nebyla žádná pravidla.|90",
    "Sedni si naproti němu, drž ho za obě ruce a vyjmenuj pět momentů s ním, na které nikdy nezapomeneš.|120|sed_celem",
    "Přiznej se mu k jedné fantazii, o které sis myslela, že ti ji nikdy neschválí.|60",
    "Dvě pravdy a jedno přání: Řekni mu dvě věci, které se ti na něm líbí, a jedno, co bys chtěla zkusit. Cíl: ať sám vybere, co uděláte.|90",
    "Řekni mu pomalu do ucha jednu sprostou větu. Jenom jednu, a pak dlouho mlč.|30",
    "Sedni si mu za záda, obejmi ho a nech ho, ať ti vypráví svoji fantazii. Ty jen posloucháš a hladíš ho po hrudníku.|180|klin_podlaha",
    "Polož mu obě dlaně na tváře, dívej se mu do očí a řekni mu, co s tebou dělá, když se na tebe takhle podívá.|45|sed_celem",
    "Nedotýkej se: Postav se těsně před něj a popisuj mu, co mu právě chceš udělat. Ruce musíš mít za zády celou dobu. Cíl: ať on sáhne po tobě jako první.|120|objeti",
    "Vedle sebe vleže mu do ucha pošeptej scénu, kterou byste spolu mohli zahrát.|120|vedle_on_lezi",
    "Řekni mu, jak vypadá, když se udělá. Pomalu, slovo po slovu, do ucha.|60|vedle_on_lezi",
    "Zeptej se ho, jaké slovo ho vzrušuje nejvíc. Pak mu ho celou minutu opakuj do ucha.|60",
    "Sedni si k němu, drž ho za zápěstí a řekni mu přesně, co se ti na něm líbilo dneska přes den.|60|sed_celem",
    "Šeptané ano: Pokládej mu otázky, na které může odpovědět jen ano nebo ne. Vyzvídej, co dneska chce. Cíl: zjistit tři jasná ano.|120|sed_celem",
    "Obejmi ho zezadu, dej mu bradu na rameno a řekni mu, co s tebou dělá, když se před tebou svlékne.|60|stoje_zezadu!",
    "Přiznej se mu, na co myslíš, když jsi sama. Žádné vytáčky.|60",
    "Drž mu ruku na svém hrudníku, ať cítí tvůj tep, a povídej mu, jak moc ho chceš.|60|sed_celem",
    "Popiš mu, co uděláš jako první, až ho svlékneš. A pak ještě chvíli počkej.|60",
    "Nakloň se k němu, dýchej mu na krk a nic neříkej. Vydrž, dokud tě sám nepolíbí.|60|objeti",
    "Pomalá otázka: Zeptej se ho, kde přesně chce, abys ho políbila. Pak to udělej, ale až za třicet vteřin. Cíl: ať se nemůže dočkat.|60",
    "Posaďte se proti sobě a vyprávěj mu, co sis o něm myslela první měsíc. Bez cenzury, i to nehezké.|180|sed_celem",
    "Šeptej mu do ucha, jak si představuješ, že se tě dneska bude dotýkat on.|60|lzicka",
    "Polož si jeho hlavu do klína a hraj si mu s vlasy, zatímco mu vyprávíš svou fantazii.|120",
    "Řekni mu tři věci, které bys s ním chtěla zkusit, ale nikdy sis netroufla navrhnout.|90",
    "Zavaž si oči ty a nech ho, ať ti šeptá do ucha. Ty jen posloucháš a nesmíš se hnout.|120",
    "Vyznání z ticha: Napiš mu prstem na záda tři slova a nech ho hádat, co jsi napsala. Když uhodne, splníš mu přání. Cíl: ať uhodne.|90|masaz_vsede!",
    "Sedni si k němu blízko a vyprávěj mu, jak sis ho představovala, než jste spolu poprvé byli.|90|sed_celem",
    "Šeptej mu, co se ti na něm líbí, a u každé věci se toho místa lehce dotkni špičkou prstu.|120|vedle_on_lezi",
    "Zeptej se ho: rychle a bez přemýšlení, co teď chce nejvíc. A dej mu to.|45",
    "Vezmi jeho ruku, polož si ji na tvář a jen tak zůstaňte. Dívejte se na sebe a nemluvte.|60|sed_celem",
    "Přiznej mu jednu věc, kterou jsi mu nikdy neřekla, protože ses bála, co si o tobě pomyslí.|60",
    "Deset vteřin na odpověď: Ptej se ho na choulostivé věci a on má vždycky deset vteřin na odpověď. Pět otázek. Cíl: ať aspoň jednou zaváhá.|120|sed_celem",
    "Šeptej mu do ucha, co všechno na něm dneska cítíš a jak ti to voní.|45|objeti",
    "Popiš mu, jak přesně bys ho chtěla mít na sobě, a pak počkej, jestli to udělá.|60",
    "Posaď se mu na klín, obejmi ho a mlčte spolu celou minutu. Jen dýchejte.|60|klin_podlaha",
    "Vyprávěj mu, co bys s ním dělala, kdyby vás nikdo nesměl vyrušit celý víkend.|120|vedle_on_lezi",
    "Řekni mu do ucha jednu větu, kterou by od tebe nečekal. Klidně drzou.|30",
    "Ptej se ho na to, co si nikdy netroufl vyslovit, a slib, že se nebudeš divit.|120|sed_celem",
    "Hra na sochu: On se nesmí hnout, ty kolem něj chodíš a nahlas popisuješ, co se ti na něm líbí. Když se pohne, začínáš znovu. Cíl: projít celé tělo.|120",
    "Obejmi ho tak dlouho, dokud se ti nezklidní dech. Pak ho polib a pusť.|60|objeti",
    "Šeptej mu, co uděláš, až skončí tahle hra. A buď hodně konkrétní.|60",
    "Polož mu hlavu na břicho, poslouchej ho a vyprávěj mu, co ti to připomíná.|90|vedle_on_lezi",
    "Řekni mu tři věci, po kterých ti dneska bylo těžko od něj odejít.|60",
    "Vezmi ho za bradu, otoč mu obličej k sobě a chvíli se jen dívej. Pak ho polib.|45|objeti",
    "Popiš mu, jak ho chceš svlékat – kus po kusu, v jakém pořadí a proč.|90|svlekani!",
    "Šeptané instrukce: Šeptej mu, co si má se sebou dělat, a on to poslouchá. Ty se ho nedotkneš. Cíl: tři pokyny, žádný dotek.|180",
    "Zeptej se ho, jaký dotek má nejraději, a pak mu ho dej. Ale jen jednou.|60",
    "Řekni mu, co na něm obdivuješ, když je oblečený, a co, když není.|60",
    "Polož mu ruce na ramena zezadu a šeptej mu, co se ti honí hlavou.|60|masaz_vsede!",
    "Vyprávěj mu, jaké to bylo poprvé, a co si z toho večera pamatuješ nejlíp.|120|vedle_on_lezi",
    "Zeptej se ho, jestli má nějaké tajemství, které ti ještě neřekl. Nenaléhej, jen se ptej.|90|sed_celem",
    "Povídej mu do ucha o tom, jak ho vidíš ty – a použij slova, která před ním běžně nepoužíváš.|60",
    "Pravidlo jednoho slova: On smí odpovídat jen jedním slovem. Vyptávej se, co chce dneska zkusit. Cíl: složit z jeho slov plán večera.|120|sed_celem",
    "Drž ho za obě ruce a řekni mu, co pro tebe znamená, když se ti úplně odevzdá.|60|sed_celem",
    "Šeptej mu do ucha jeho jméno a mezi tím vždycky jednu věc, co s ním chceš udělat.|90|objeti",
    "Řekni mu, které místo na jeho těle ti nejvíc chybí, když nejste spolu. A polib ho.|60",
    "Vezmi mu hlavu do dlaní, dívej se mu do očí a mlčky počkej, až sám promluví.|60|sed_celem",
    "Vyprávěj mu něco sprostého, ale úplně klidným hlasem, jako bys hlásila počasí.|90",
    "Zeptej se ho, jak moc tě dneska chce, na stupnici od jedné do deseti. A pak udělej všechno pro to, aby to byla desítka.|120",
    "Popiš mu přesně, jak vypadá, když se na tebe dívá shora.|45",
    "Poslední slovo: Řekni mu jednu větu a pak už do konce úkolu nesmíš promluvit, jen se mu dívat do očí. Cíl: ať promluví on.|90|sed_celem",
    "Obejmi ho zezadu, položte si ruce na břicho a dýchejte spolu, dokud se nesladíte.|90|stoje_zezadu!",
    "Řekni mu, co by sis dneska nejradši nechala udělat, a nech ho rozhodnout, jestli to splní.|60",
  ],
});
