// Kategorie 1 – Škádlení a předehra
// Formát karty: "text" nebo "text|sekundy" (časovač)
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 1,
  name: "Škádlení a předehra",
  description: "Polibky, doteky, šeptání a pomalé svlékání. Pomalu, ať to jiskří.",

  // Úkoly pro muže – pro potěšení ženy
  male: [
    "Posaď ji na kuchyňskou linku, postav se mezi její kolena a pomalu ji líbej – nejdřív rty, pak krk.|90",
    "Přejížděj pírkem po jejím krku, klíčních kostech a vnitřní straně paží. Ona má po celou dobu zavřené oči.|60",
    "Zašeptej jí do ucha tři věci, které na jejím těle miluješ nejvíc – a každou z nich pak polib.",
    "Na gauči jí dej masáž ramen a šíje. Až povolí, polib ji za ucho.|120",
    "Opři ji zády o zeď v chodbě, chyť ji jemně za zápěstí nad hlavou a líbej ji na krk.|60",
    "Rozepni jí podprsenku jen jednou rukou. Když se ti to nepovede napoprvé, vynahraď jí to minutou líbání ramen.",
    "Klekni si před ni a polibky vystoupej od kotníku až k lemu jejího oblečení na stehně – ale ne výš.",
    "Sundej jí triko co nejpomaleji a každý odhalený kousek kůže polib.",
    "Hlaď ji po vnitřní straně stehen přes oblečení a dívej se jí přitom do očí. Nikam dál.|60",
    "Sedni si na židli, posaď si ji obkročmo na klín a líbejte se. Ruce smíš mít jen na jejích bocích.|120",
    "Zavaž jí oči šátkem a polib ji na pět míst podle sebe. Ať pokaždé hádá, kam přijde další polibek.",
    "Jemně ji kousni do ušního lalůčku a pošeptej jí, co s ní dnes chceš dělat.",
    "Stoupni si za ni před zrcadlo, hlaď ji po břiše a bocích a líbej na krk, zatímco se na vás dívá.|90",
    "Na gauči jí namasíruj chodidla a pak polib každý kotník.|120",
    "Obejmi ji zezadu u kuchyňské linky, přitiskni se k ní a pomalu jí přejížděj dlaněmi po stehnech.|60",
    "Líbej ji jen na rty – ale nesmíš se jí dotknout rukama.|60",
    "Pírkem opisuj pomalé kroužky kolem jejího pupíku a po bocích. Když se zasměje, začni znovu.|60",
    "Rozepni jí kalhoty nebo sukni a nech je spadnout na zem – a pak se věnuj už jen jejímu krku.",
    "Polib ji na zátylek a pak jí jazykem pomalu přejeď po páteři tak daleko, kam ti dovolí oblečení.",
    "Lehni si s ní na postel a konečky prstů ji hlaď po celém těle přes oblečení. Prsa a klín jsou zakázané.|120",
    "Pošeptej jí svou nejtajnější fantazii, ve které hraje hlavní roli ona.",
    "Pusť pomalou písničku a tancuj s ní v obýváku. Během tance ji hlaď po zadečku.|120",
    "Zuj ji a pomalu jí líbej nárty a kotníky.",
    "Masíruj jí hlavu – prsty ve vlasech, pomalu, ona má zavřené oči.|90",
    "Posaď ji na jídelní stůl, rozevři jí kolena a líbej ji, zatímco ji hladíš po stehnech.|60",
    "Odhrň jí vlasy z krku a jen na něj pomalu dýchej, bez polibků. Na konci jeden dlouhý polibek.",
    "Přejeď jí pírkem po rtech a pak ji dlouze polib.",
    "Líbej ji a mezitím jí rozepínej knoflíky halenky nebo svetru – jeden po druhém.",
    "Klekni si za ni na gauči a masíruj jí záda pod tričkem.|120",
    "Chyť ji oběma rukama za zadeček a přitáhni si ji k sobě na dlouhý polibek.",
    "Ať si lehne na břicho. Polib každý její obratel – od krku až dolů.",
    "Přejeď jí jazykem po krku od klíční kosti až k uchu. Hodně pomalu.",
    "Vezmi její ruku, polib každý prst a jemně jí políbej dlaň.",
    "Napusť jí vanu nebo pusť sprchu a pomoz jí se svléknout. Sám zůstaň oblečený a jen se dívej.",
    "Podrž jí ruce za zády a líbej ji do výstřihu.|60",
    "Lehni si na ni na posteli, propleť s ní prsty nad její hlavou a líbej ji.|60",
    "Řekni jí, co by sis s ní přál dělat v kuchyni – a s jednou věcí hned začni.",
    "Vyber 7 míst na jejím těle, která jsou podle tebe nejvíc sexy. U každého řekni proč a polib ho.",
    "Namaž jí nohy tělovým olejem nebo krémem – od kotníků ke kolenům, pomalými tahy.|120",
    "Napiš jí prstem na záda slovo. Když ho uhodne, dostane polibek, kam si řekne (nad pasem).",
    "Postav ji k oknu se zataženými závěsy, stoupni si za ni, líbej ji na ramena a hlaď po břiše.|60",
    "Přitáhni si ji k sobě za pásek nebo lem kalhot a polib ji.",
    "Střídej jemné kousání a polibky na jejím krku a ramenou.|60",
    "Sedni si na podlahu, ona si sedne mezi tvé nohy zády k tobě. Hlaď ji po pažích a líbej na ramena.|90",
    "Na gauči si jí polož hlavu do klína, hlaď ji ve vlasech a polib ji vzhůru nohama jako Spider-Man.",
    "Svlékni jí jednu věc podle svého výběru a místo, které se odhalí, líbej.|20",
    "Dej si mezi rty kousek čokolády nebo ovoce a nech ji, ať si ho vezme polibkem.",
    "Dotýkej se jí jen dechem – foukej jí jemně na krk, výstřih, břicho a stehna.|60",
    "Pomalu jí stáhni ramínko podprsenky nebo topu a polib ji na odhalené rameno.",
    "Objímej ji zezadu a líbej na krk, dokud se o tebe sama nezačne otírat zadečkem.",
    "Vezmi ji za ruku, doveď ji do ložnice a cestou ji zastav a polib na třech různých místech bytu.",
    "Líbej ji na břicho těsně nad lemem kalhot nebo kalhotek a zuby ho stáhni o kousek níž.",
    "Posaď ji do křesla, klekni si před ni a masíruj jí lýtka a kolena.|120",
    "Vyjeď rukou po jejím stehně pod sukní nebo nohavicí co nejvýš – a těsně před cílem se zastav.",
    "Polib ji na vnitřní stranu zápěstí, loket a rameno – po jedné ruce nahoru, po druhé dolů.",
    "Stoupni si za ni, polož jí dlaně na prsa přes oblečení a jen je drž, zatímco ji líbáš na krk.|45",
    "Pošeptej jí do ucha, co tě na ní dnes vzrušilo úplně poprvé.",
    "Přejeď jí pírkem pod bradou, po víčkách a po rtech. Pak ji polib.",
    "Rozepni jí zip na zádech, nebo jí vytáhni triko z kalhot zuby.",
    "Nech ji stát uprostřed pokoje a obcházej ji dokola. Dotýkej se jí jen konečky prstů.|60",
    "Opři ji o lednici a líbej ji – záda jí chladí, tak ji zepředu hřej rukama.|60",
    "V koupelně jí pročeš vlasy kartáčem a pak ji polib na šíji.",
    "Zavaž jí oči. Ona řekne místo nad pasem a ty ho políbíš. Tři kola.",
    "Posaď ji na pračku a líbej ji, s rukama na jejích stehnech.|60",
    "Sundej jí ponožky nebo punčochy zuby.",
    "Lehni si vedle ní a hraj si s jejími vlasy, zatímco jí šeptáš, jak je krásná.|60",
    "Stáhni jí kalhoty, ale nech ji v kalhotkách. Polib ji zezadu na obě stehna těsně pod zadečkem.",
    "Pomalu ji olízni od ramene po ucho a jemně ji chytni za vlasy u kořínků.",
    "Posaď ji na gauč a lehni si hlavou na její stehna. Líbej je přes oblečení.|60",
    "Oblečenou ji přitiskni na posteli a pomalu se o ni otírej celým tělem, jako byste už byli nazí.|60",
    "Svlékni se do spodního prádla a nech se od ní prohlédnout. Otoč se, jak si řekne.",
    "Namaž jí záda olejem a masíruj je dlouhými tahy od beder k ramenům.|180",
    "Rozepni jí podprsenku, ale nesundávej ji. Jen líbej ramena a nech ramínka sklouznout samotná.",
    "Pírkem přejížděj po vnitřní straně jejích stehen, jen přes kalhotky – nahoru a zase dolů.|45",
    "Nabídni jí sklenku něčeho dobrého a zatímco pije, líbej ji na krk.",
    "Posaď se ke kuchyňskému stolu a nech ji stát mezi svými koleny. Líbej jí břicho přes oblečení.|60",
    "Přetáhni jí triko přes hlavu, ale nech jí ho chvíli omotané kolem zápěstí. Pak ji líbej na klíční kosti.",
    "Rukama jí přejížděj po těle a pojmenovávej, co zrovna hladíš – a proč to miluješ.|90",
    "Opři se s ní o dveře ložnice a líbejte se tak, jako byste se neviděli měsíc.|60",
    "Polož jí ruku na krk (bez tlaku), palcem jí přejeď po rtech a polib ji.",
    "Na gauči jí polož nohy do klína a hlaď ji od chodidel až ke kolenům.|90",
    "Stoupni si za ni a pomalu jí rozepni kalhoty. Ruku jí jen polož na podbřišek a nech ji tam.|30",
    "Zavaž jí oči a přejížděj po jejím těle střídavě pírkem a konečky prstů. Ať hádá, co to je.|60",
    "Polib ji na čelo, na víčka, na nos, na tváře – a na rty až úplně nakonec.",
    "Zatímco se ona dívá do zrcadla, sundej jí podprsenku zezadu.",
    "Lehni si na ni zezadu, když leží na břiše, a líbej ji na krk a lopatky.|60",
    "Opři ji o kuchyňskou linku a pomalu jí vyhrň sukni nebo stáhni kalhoty, zatímco ji líbáš.",
    "Přejeď jí kostkou ledu po krku a pak to místo zahřej rty.",
    "Pomalu jí přejížděj prsty po rtech, ona ti je může olíznout. Pak ji polib.",
    "Masíruj jí bedra a boky, ona leží na posteli na břiše.|120",
    "Vyzvi ji k pomalému tanci a přitom ji celou dobu svlékej.|180",
    "Polib ji zezadu na krk, zatímco jí přejíždíš rukama po prsou přes podprsenku.|45",
    "Dej jí pusu na každý prst na noze. Když se bude smát, začni znova.",
    "Zatímco sedí na gauči, klekni si před ni a hlaď jí stehna od kolen nahoru – přes oblečení, pomalu.|60",
    "Sundávej jí kalhotky jen pomalu a jen o kousek – a zase je vrať zpátky. Dvakrát.",
    "Přejeď pírkem po jejích prsou přes podprsenku, kolem dokola.|45",
    "Pošeptej jí, jak voní, a nasaj její vůni za uchem a na krku.",
    "Nech ji sedět na židli. Obejdi ji zezadu, rozpusť jí vlasy a masíruj jí spánky.|90",
    "Zvedni ji na kuchyňský stůl, obejmi ji jejími nohama kolem sebe a líbej ji.|60",
    "Na posteli jí pomalu líbej podkolenní jamky.",
    "Jazykem jí jemně olízni rty, ale nenech ji tě políbit. Škádli ji tak ještě chvíli.|30",
    "Posaď se na zem opřený o gauč a nech ji, ať si sedne na tebe. Hlaď ji po zádech pod oblečením.|90",
    "Zavaž jí oči a pomalu ji svleč do spodního prádla. Každou věc jí vezmi až po polibku.",
    "Líbej jí záda od lopatek až k bedrům a na každém konci jemně kousni.",
    "Pusť jí vodu do sprchy, svlékni ji a omyj jí záda mýdlem nebo sprchovým gelem.|120",
    "Přitiskni se k ní zezadu v kuchyni, když něco dělá, a nenápadně jí přejeď rukou po prsou.",
    "Olízni jí vnitřní stranu zápěstí a foukni na to místo.",
    "Na chodbě ji zastav, chyť jemně za bradu a dlouze ji polib.",
    "Na posteli ji pomalu hlaď po břiše kolem pupíku, s každým kolečkem trochu níž – ale ne pod lem kalhotek.|60",
    "Ať si lehne na záda. Přejížděj jí pírkem přes chodidla, lýtka a kolena.|60",
    "Pověz jí, co by sis dnes přál, aby ti udělala – a slib, že jí to vrátíš dvojnásob.",
    "Opři ji o skříň a líbej ji na výstřih, zatímco jí přejíždíš palci po bocích.|45",
    "Klekni si a svlékni jí kalhoty zespodu – nejdřív jednu nohavici, pak druhou, s polibkem na každé stehno.",
    "Namasíruj jí dlaně a prsty – každý zvlášť, pomalu.|90",
    "Hlaď jí vlasy a lehce za ně zatáhni, aby se jí zaklonila hlava. Pak ji polib na odhalený krk.",
    "Nech ji ležet na gauči a lehni si vedle ní. Palcem kresli malá kolečka na jejím boku pod tričkem.|60",

    // Karty s cílem
    "Mapa těla: Zavaž jí oči a polib ji postupně na 10 různých míst. Po každém polibku řekne „víc“, nebo „dál“. Cíl: najít tři místa, kde chce víc, a u nich zůstat nejdéle.",
    "Socha: Ona stojí uprostřed obýváku a nesmí se pohnout. Ty ji pomalu svlékáš do spodního prádla a líbáš. Když se pohne nebo zasměje, jednu věc jí zase oblékneš. Cíl: dostat ji do spodního prádla.|180",
    "Horko-studeno: Přejížděj jí kostkou ledu po krku, klíčních kostech a břiše a každé studené místo hned zahřej jazykem. Cíl: aby jí naskočila husí kůže.|90",
    "Šeptaná scéna: Pošeptej jí do ucha co nejpodrobněji jednu erotickou scénu, kterou s ní chceš dnes zažít – kde, jak a co jí uděláš. Cíl: aby ti sama řekla „tak to udělej“.",
    "Tanec s vedením: Pusť pomalou písničku, stoupni si za ni a veď její boky rukama do rytmu. Cíl: do konce písničky jí přetáhnout triko přes hlavu, aniž byste přestali tančit.|180",
    "Krmení na lince: Posaď ji na kuchyňskou linku a krm ji jahodou, čokoládou nebo něčím sladkým. Každé sousto si z jejích rtů vezmi zpátky polibkem. Cíl: pět soust, pět polibků.",
    "Knoflíková hra: Rozepínej jí oblečení a za každý knoflík, zip nebo háček jí dej polibek na jiné místo. Cíl: aby zůstala jen ve spodním prádle.",
    "Pírkový test: Ona leží na břiše na posteli. Přejížděj jí pírkem po zádech, stehnech, podkolenních jamkách a chodidlech. Cíl: najít místo, kde se nejvíc zachvěje, a to pak dlouze políbit.|90",
    "Masáž s pravidlem: Masíruj jí záda na posteli. Tvoje ruce smí sjet o kousek níž jen tehdy, když ona tiše vzdychne. Cíl: dostat se masáží až na zadeček.|180",
    "Zrcadlo: Postav ji před zrcadlo a stoupni si za ni. Nahlas popisuj, co na ní vidíš a co na ní miluješ, a každé to místo pohlaď. Cíl: aby se na sebe celou dobu dívala.|120",
    "Nejpomalejší polibek: Přibližuj se k jejím rtům tak pomalu, aby to trvalo 30 vteřin, a pak ji líbej celou minutu. Cíl: aby tě k sobě přitáhla dřív, než se dotknete.|90",
    "Bez rukou: Dej ruce za záda. Jen pusou jí vyhrň triko a polibky se dostaň až k podprsence. Cíl: zvládnout to bez jediného dotyku rukou.|120",
    "U dveří ložnice: Opři ji zády o dveře, jednu ruku dej na dveře vedle její hlavy a líbej ji pomalu od čela přes rty až ke krku. Cíl: aby ti sama zajela rukama pod triko.|60",
    "Kalhoty po centimetrech: Klekni si před ni, rozepni jí kalhoty a stahuj je po kouscích. Za každý kousek odhalené kůže dej polibek. Cíl: kalhoty na zemi a ona celá rozechvělá.",
    "Vůně: Ať zavře oči. Přičichni k jejímu krku, zápěstí, vlasům a podbřišku přes oblečení a u každého místa jí řekni, jak voní. Cíl: aby se jí zrychlil dech.",
    "Tři doteky: Na jejím krku vyzkoušej konečky prstů, dech a rty. Ona vybere, co chce zopakovat. Cíl: tím vybraným dotekem projdi celý její krk a ramena.|60",
    "Kdo uhne pohledem: Sedněte si naproti sobě na podlahu, dívejte se do očí a ty ji přitom hladíš po kolenou a stehnech. Kdo první uhne, svlékne jednu věc. Cíl: vydržet dvě minuty.|120",
    "Židle a zákaz: Posaď ji na židli, ruce jí polož za opěradlo. Obcházej ji a líbej ji zezadu na šíji, zepředu na rty, zboku na ucho. Nesmí se tě dotknout. Cíl: vydržet dvě minuty, pak tě smí obejmout.|120",
    "Ramínka zuby: Stoupni si za ni a stáhni jí zuby ramínka podprsenky – nejdřív jedno, pak druhé. Cíl: nepoužít ruce ani jednou.",
    "Schody z polibků: Ona leží na zádech. Polib ji na kotník, koleno, stehno, bok, žebra, rameno, krk a ucho – každý polibek o chvilku delší. Cíl: poslední polibek na rty trvá aspoň 30 vteřin.",
    "Horké dlaně: Promni si dlaně, aby byly horké, a přilož jí je pod tričkem na podbřišek a bedra. Drž je tam a líbej ji na krk. Cíl: aby se o tebe opřela celou vahou.|60",
    "Pod dekou: Přikryjte se dekou na gauči. Pod dekou ji hlaď po stehnech a bocích, nad dekou se tvař nevinně a mluv o úplně obyčejných věcech. Cíl: aby první přestala mluvit ona.|120",
    "Tři otočky: Na chodbě ji chyť za ruku, roztoč ji jako při tanci a zachyť ji zády k sobě. Obejmi ji a polib na krk. Cíl: tři otočky, každá skončí delším polibkem.",
    "Rozepnutá a nechaná: Sedni si na zem opřený o gauč, ona si sedne mezi tvé nohy. Rozepni jí podprsenku pod tričkem, ale nesundávej ji, a hlaď ji po bocích. Cíl: aby si ji sundala sama.|90",
    "Stíny na zdi: Zhasni a nech svítit jen lampu, ať vrhá stíny. Svlékej ji pomalu tak, abyste oba sledovali vaše stíny na zdi. Cíl: svléknout ji do spodního prádla.|120",
    "Kreslení na záda: Nakresli jí prstem na záda tvar – srdce, hvězdu nebo písmeno. Když uhodne, polib ji. Když ne, sundáš jí jednu věc. Cíl: pět kol.",
    "Po paži nahoru: Polib jí konečky prstů, dlaň, zápěstí, loket, rameno, klíční kost a krk. Na každé zastávce 5 vteřin. Cíl: než dojdeš ke krku, musí mít zavřené oči.",
    "Studená plechovka: Vytáhni z lednice něco studeného a přejeď jí s tím po krku a zátylku. Každé místo hned zahřej rty. Cíl: pět míst, pět zahřátí.",
    "Aranžér: Ona sedí na gauči a ty ji „aranžuješ“ – posuneš jí nohu, odhrneš vlasy, stáhneš ramínko. Každou změnu zakonči polibkem. Cíl: pět změn, poslední už ve spodním prádle.",
    "Kousek po kousku rtů: Líbej jí jen horní ret, pak jen dolní, pak jen koutky. Cíl: aby tě chytila za tvář a přitáhla si tě na pořádný polibek.",
    "Přemluv ji: Chceš jí sundat triko, ale ona říká „ne“, dokud ji nepřesvědčíš třemi polibky na místa, která sama určí. Cíl: triko na zemi.",
    "Čtyři způsoby: Hlaď ji přes triko, pak pod ním, pak jen nehty a nakonec jen dechem – každý způsob 30 vteřin. Cíl: zjistit, který má nejradši, a ten zopakovat.|120",
    "Opěradlo: Ona klečí na gauči a opírá se o opěradlo. Stoupni si za ni, rozcuchej jí vlasy, líbej ji po šíji a rukama hlaď boky. Cíl: aby se o tebe zadečkem opřela.|90",
    "Lžička pod peřinou: Lehněte si na bok, ty za ní, a pod peřinou ji pomalu hlaď po břiše a stehnech. Cíl: aby se k tobě sama otočila čelem.|120",
    "Zpomalený film: Svlékni jí triko tak pomalu, aby to trvalo celou minutu. Cíl: ani jednou se nezastavit a nezrychlit.|60",
    "Hlas: Zavaž jí oči a šeptej jí do ucha, co s ní uděláš v další úrovni, zatímco ji hladíš jen po pažích. Cíl: aby tě poprosila, ať přestaneš mluvit a začneš.|90",
    "Stůl a stehna: Ona sedí na jídelním stole, ty stojíš mezi jejími koleny. Hlaď ji po vnějších stranách stehen, s každým tahem o kousek výš. Cíl: dojít až k bokům a pevně si ji přitáhnout.|60",
    "Zapnout, rozepnout: Rozepni jí podprsenku a zase ji zapni. Mezi tím jí polib záda. Cíl: potřetí už ji nezapínej a pomalu ji sundej.",
    "Počítání polibků: Ona počítá nahlas do dvaceti a ty ji za každé číslo polibíš na jiné místo na krku a výstřihu. Když se splete, začíná znovu. Cíl: dojít do dvaceti.",
    "Led na rtech: Drž kostku ledu mezi rty a přejížděj jí s ní po klíčních kostech a výstřihu. Cíl: kostka se musí rozpustit na její kůži.|90",
    "Loďka: Lehni si na záda a nech ji ležet na sobě. Hlaď ji pod oblečením a stahuj jí kalhoty jen rukama a nohama. Cíl: kalhoty pryč, aniž by z tebe slezla.",
    "Z kolen: Klekni si před ni, když sedí na kraji postele. Líbej jí kolena a pomalu je rozevírej, ale polibky nechoď výš než do poloviny stehen. Cíl: aby tě chytila za vlasy.",
    "Šampon: Ve sprše jí umyj vlasy, pomalu jí masíruj hlavu a pak ji polib na krk. Cíl: aby se o tebe zády opřela a zavřela oči.|120",
    "Společný dech: Lehněte si čelem k sobě, čela u sebe. Dýchejte ve stejném rytmu a přejížděj jí rukou po páteři. Cíl: minuta bez polibku – pak ho dostane.|60",
    "Kdo sáhne výš: Sedněte si vedle sebe na gauč a hlaďte se jen po stehnech přes oblečení. Kdo první sáhne výš, prohrál a svléká triko. Cíl: vydržet déle než ona.|90",
    "Poslepu na židli: Sedni si na židli, ona si sedne obkročmo na tvůj klín. Rozepni jí podprsenku a líbej ji, ale nesmíš otevřít oči. Cíl: zvládnout to poslepu.",
    "Spirály: Ona leží na břiše jen v kalhotkách. Kresli jí prsty po zádech spirály, které se pomalu blíží k lemu kalhotek. Cíl: zastavit se vždy těsně před ním – pětkrát.|90",
    "Vítej doma: Hraj, že přicházíš domů. Opři ji o zeď v chodbě, polib ji, jako byste se týden neviděli, a začni ji svlékat hned tam. Cíl: dojít do ložnice a nechat po cestě tři kusy jejího oblečení.",
    "Uši: Věnuj se jen jejím uším – líbej, olizuj, jemně kousej a šeptej. Cíl: aby jí naskočila husí kůže na pažích.|60",
    "Kompliment za kus: Za každou věc, kterou jí sundáš, jí řekni upřímný kompliment o jejím těle. Cíl: dojít ke spodnímu prádlu s pěti komplimenty.",
    "Vana pro ni: Napusť jí vanu s pěnou, pomoz jí dovnitř a namydli jí ramena a záda. Sám zůstaň venku. Cíl: aby tě pozvala k sobě.|300",
    "Kravata: Dej jí do ruky svou kravatu, pásek nebo lem trika a nech se od ní vést bytem. Cestou ji dvakrát zastav a polib. Cíl: v ložnici ji posadit na postel a klečet před ní.",
    "Víno na kůži: Namoč prst ve víně nebo šlehačce, přejeď jí s ním po rtech a olízni to. Pak kapku na krk a olízni i tam. Cíl: tři místa, každé o kousek níž.",
    "Obrácený polibek: Stoupni si za ni, když sedí na gauči, zakloň jí jemně hlavu a polib ji vzhůru nohama. Rukama ji přitom hlaď po krku a výstřihu. Cíl: aby se k tobě natáhla pro další.|60",
    "Zákaz rtů: Líbej ji všude na obličeji a na krku, jen ne na rty. Cíl: vydržet, dokud tě o polibek na rty sama nepoprosí.|90",
    "Hra na fotografa: Ona pózuje na posteli, ty jí říkáš, jak se má natočit, a „fotíš“ ji jen očima (bez telefonu). Po každé póze přijdeš a polibkem ji odměníš. Cíl: pět póz, v každé má na sobě o kus méně.",
  ],

  // Úkoly pro ženu – pro potěšení muže
  female: [
    "Posaď se mu obkročmo na klín na gauči a pomalu ho líbej, zatímco mu prsty hladíš vlasy.|90",
    "Přejížděj mu pírkem po krku, hrudi a břiše. On má celou dobu zavřené oči.|60",
    "Pošeptej mu do ucha, co tě na něm nejvíc vzrušuje – a pak ho kousni do ušního lalůčku.",
    "Sundej mu triko co nejpomaleji a každý odhalený kousek kůže polib.",
    "Opři ho o zeď v chodbě, přitiskni se k němu a líbej ho na krk.|60",
    "Udělej mu masáž ramen a šíje, zatímco sedí na židli v kuchyni.|120",
    "Rozepni mu košili nebo mikinu zuby – nebo aspoň první knoflík.",
    "Svlékni se před ním do spodního prádla. Pomalu. On se jen dívá a nesmí se hnout.|90",
    "Hlaď ho po vnitřní straně stehen přes kalhoty a dívej se mu přitom do očí. Nikam dál.|60",
    "Zavaž mu oči šátkem a polib ho na pět míst podle sebe. Ať hádá, kam přijde další polibek.",
    "Líbej ho jen na rty – ale nesmíš se ho dotknout rukama.|60",
    "Posaď ho do křesla a tancuj před ním na jednu písničku. Dotýkat se tě nesmí.|180",
    "Klekni si za něj na posteli a masíruj mu záda.|120",
    "Stáhni mu kalhoty a polib ho na obě stehna – přes boxerky se ani nedotkni.",
    "Přejeď mu jazykem po krku od klíční kosti k uchu. Hodně pomalu.",
    "Posaď se na kuchyňskou linku, přitáhni si ho mezi kolena a obejmi ho nohama.|60",
    "Přitiskni se k němu zezadu a hlaď ho po hrudi a břiše pod tričkem.|60",
    "Vezmi jeho ruku a polož si ji tam, kde se chceš nechat hladit – nad pasem.",
    "Masíruj mu hlavu – prsty ve vlasech, pomalu, on má zavřené oči.|90",
    "Stáhni mu ponožky a polib ho na nárt. Pak ho hlaď po lýtkách.",
    "Obkroč ho, když leží na zádech, a líbej mu hrudník. Vlasy ať ho šimrají na kůži.|60",
    "Pomalu mu rozepni pásek a kalhoty – a pak se věnuj jen jeho krku.",
    "Pošeptej mu svou nejtajnější fantazii, ve které hraje hlavní roli on.",
    "Pírkem mu opisuj kolečka kolem bradavek a pupíku.|45",
    "Posaď ho na gauč, lehni si mu hlavou do klína a hlaď ho po stehnech.|60",
    "Polib ho na zátylek a jemně ho chytni za vlasy.",
    "Kousej ho jemně do krku a ramen – střídej to s polibky.|60",
    "Nech ho sedět na židli a sedni si mu na klín zády k němu. Pomalu se o něj otírej.|45",
    "Přejeď mu nehty lehce po zádech – shora dolů, pomalu.|30",
    "Polib ho na každý prst na ruce a jemně mu olízni dlaň.",
    "Postav se před zrcadlo a nech ho, ať se dívá, jak si svlékáš podprsenku.",
    "Dej si kousek čokolády nebo ovoce mezi rty a nech ho, ať si ho vezme polibkem.",
    "Dotýkej se ho jen dechem – foukej mu na krk, hruď, břicho a stehna.|60",
    "Lehni si na něj na posteli, propleť s ním prsty nad jeho hlavou a líbej ho.|60",
    "Svlékni mu jednu věc podle svého výběru a místo, které se odhalí, líbej.|20",
    "Pusť pomalou písničku a tancuj s ním v obýváku přitisknutá co nejvíc to jde.|120",
    "Zašeptej mu, co s ním chceš dělat v ložnici – a jednu věc hned předveď.",
    "Namaž mu záda olejem a masíruj je dlouhými tahy.|180",
    "Opři se o kuchyňskou linku, chyť ho za tričko a přitáhni si ho k polibku.",
    "Napiš mu prstem na záda slovo. Když ho uhodne, dostane polibek, kam si řekne (nad pasem).",
    "Rozepni si pomalu halenku nebo sundej triko, zatímco sedí na gauči a jen se dívá.|60",
    "Klekni si před něj, když sedí, a hlaď ho po stehnech od kolen nahoru – jen přes kalhoty.|60",
    "Obejmi ho zezadu v kuchyni a zajeď mu rukama do kapes kalhot.",
    "Polib ho na čelo, víčka, nos, tváře – a rty až úplně nakonec.",
    "Líbej ho na břicho těsně nad pasem a zuby mu stáhni boxerky o kousek níž.",
    "Zavaž mu oči a přejížděj po jeho těle střídavě pírkem a konečky prstů. Ať hádá, co to je.|60",
    "Oblečená si na něj lehni na posteli a pomalu se o něj otírej celým tělem.|60",
    "Nech ho ležet na břiše. Polib každý jeho obratel od krku dolů.",
    "Sedni si na pračku, přitáhni si ho mezi nohy a líbej ho.|60",
    "Stáhni mu triko přes hlavu, ale nech mu ho chvíli omotané kolem zápěstí. Pak ho líbej na hrudník.",
    "Posaď se na podlahu opřená o gauč a nech ho, ať si lehne hlavou do tvého klína. Hlaď ho ve vlasech a po hrudi.|90",
    "Přejeď mu kostkou ledu po krku a pak to místo zahřej rty.",
    "Nech ho sedět na posteli a svlékni se před ním do spodního prádla – každou věc hoď po něm.",
    "Namasíruj mu chodidla na gauči.|120",
    "Nech ho stát uprostřed pokoje a obcházej ho dokola. Dotýkej se ho jen konečky prstů.|60",
    "Pošeptej mu, co tě na něm dnes vzrušilo úplně poprvé.",
    "Vytáhni mu triko z kalhot zuby a polib ho na podbřišek.",
    "Přejeď mu palcem po rtech a nech ho, ať ti ho olízne. Pak ho polib.",
    "Opři ho o lednici a líbej ho – záda mu chladí, tak ho zepředu hřej svým tělem.|60",
    "Sedni si na kuchyňský stůl, obtoč mu nohy kolem pasu a přitáhni si ho k dlouhému polibku.|60",
    "Vezmi ho za ruku, doveď ho do ložnice a cestou ho zastav a polib na třech různých místech bytu.",
    "Přejížděj mu prsty po stehně přes kalhoty čím dál výš – a těsně před cílem se zastav.",
    "Zatímco sedí na židli, stoupni si za něj, obejmi ho a rukama mu přejížděj po hrudi.|45",
    "Rozepni si podprsenku, ale nesundávej ji. Nech ho, ať ti pomalu stáhne ramínka.",
    "Polib ho na vnitřní stranu zápěstí, loket a rameno – po jedné ruce nahoru, po druhé dolů.",
    "Pusť mu vodu do sprchy, svlékni ho a umyj mu záda.|120",
    "Posaď se mu na klín čelem k němu a pomalu mu rozepínej košili nebo mikinu.",
    "Nech ho sedět na gauči. Lehni si vedle něj a palcem mu kresli kolečka na boku pod tričkem.|60",
    "Nakloň se k němu, jako bys ho chtěla políbit, ale na poslední chvíli uhni. Škádli ho tak třikrát a pak ho polib.",
    "Zavaž mu oči a pomalu ho svleč do spodního prádla. Každou věc mu vezmi až po polibku.",
    "Líbej mu záda od lopatek až k bedrům a na konci ho jemně kousni.",
    "Namaž mu nohy olejem od kotníků až ke kolenům.|120",
    "Stáhni mu kalhoty, ale nech ho v boxerkách. Polib ho na podbřišek těsně nad jejich lemem.",
    "Jazykem mu jemně olízni rty, ale nenech ho, ať tě políbí. Škádli ho tak ještě chvíli.|30",
    "Pírkem mu přejížděj po vnitřní straně stehen přes boxerky – nahoru a zase dolů.|45",
    "Sedni si na gauč a polož mu nohy do klína. Pomalu jimi hlaď jeho stehna.|45",
    "Zatímco se dívá, přejeď si rukama po celém těle přes oblečení.|45",
    "Obejmi ho kolem krku a nech se od něj odnést do ložnice. Pokud to nejde, doveď ho tam ty a cestou ho líbej.",
    "Dej mu pusu na každý prst u nohy. Když se bude smát, začni znova.",
    "Chyť ho za zadek a přitáhni si ho k sobě na dlouhý polibek.",
    "Posaď ho na židli, stoupni si mu mezi kolena a nech ho líbat tvoje břicho – ruce musí mít za opěradlem.|60",
    "Přejeď mu rukou po hrudi pod tričkem a zastav se na bradavce. Jemně ji stiskni.",
    "Olízni mu vnitřní stranu zápěstí a foukni na to místo.",
    "Na chodbě ho zastav, chyť ho jemně za bradu a dlouze ho polib.",
    "Zatímco leží, hlaď ho po břiše kolem pupíku, s každým kolečkem trochu níž – ale ne pod lem boxerek.|60",
    "Pověz mu, co by sis dnes přála, aby ti udělal – a slib, že mu to vrátíš dvojnásob.",
    "Opři ho o skříň, přitiskni se k němu stehnem mezi jeho nohy a líbej ho na krk.|45",
    "Nech ho sedět v křesle. Postav se za něj, rozcuchej mu vlasy a masíruj mu spánky.|90",
    "Lehni si na břicho do postele jen ve spodním prádle a nech ho, ať se dívá. Po minutě ho zavolej k sobě.",
    "Přetáhni si přes hlavu jeho triko, obleč si ho na holé tělo a nech ho, ať ti ho zase sundá.",
    "Na gauči mu polož ruce na hruď, pomalu je sjeď až na pásek a zase zpátky.|30",
    "Hlaď ho po zátylku a lehce mu zatáhni za vlasy, aby zaklonil hlavu. Polib ho na odhalený krk.",
    "Posaď se mu na klín na židli a pomalu mu šeptej, jak moc tě vzrušuje.|45",
    "Klekni si za něj na posteli a hlaď ho po hrudi, zatímco ho líbáš na šíji.|60",
    "Svlékni mu ponožky zuby.",
    "Lehni si vedle něj a pomalu mu přejížděj nehtem po stehně přes kalhoty – nahoru a dolů.|45",
    "Postav se k oknu se zataženými závěsy, přitáhni si ho za sebe a veď jeho ruce po svém těle.|60",
    "Nabídni mu sklenku něčeho dobrého a zatímco pije, líbej ho na krk.",
    "Vyber 7 míst na jeho těle, která jsou podle tebe nejvíc sexy. U každého řekni proč a polib ho.",
    "Namasíruj mu dlaně a prsty – každý zvlášť, pomalu.|90",
    "Zul se a bosou nohou ho pod stolem pomalu hlaď po lýtku až ke kolenu.|30",
    "Opři se zády o něj, když stojí, a pomalu se o něj otírej zadečkem.|30",
    "Zatímco sedí, klekni si na gauč vedle něj a líbej ho na ucho a krk. Ruku mu polož na stehno.|60",
    "Vezmi jeho dlaně a pomalu je veď po svých bocích a stehnech přes oblečení.|45",
    "Lehni si na něj, když leží na břiše, a líbej ho na krk a lopatky.|60",
    "V koupelně mu pomalu namaž tvář krémem po holení – zblízka, s pohledem do očí a polibkem na konci.",
    "Posaď se na zem mezi jeho nohy, když sedí na gauči, a hlaď ho po lýtkách a stehnech.|60",
    "Přitiskni se k němu v kuchyni zezadu, když něco dělá, a nenápadně mu sjeď rukou po zadku.",
    "Svlékni ho do boxerek, ale sama zůstaň oblečená. Pomalu ho obejdi a prohlédni si ho.",
    "Přejeď mu pírkem pod bradou, po víčkách a po rtech. Pak ho polib.",
    "Na posteli se k němu přitul a jemně mu kousej a líbej ucho, dokud se neotočí.",
    "Namaž mu hrudník olejem a pomalu ho roztírej.|90",
    "Sedni si mu obkročmo na stehna, když leží, a jen pomalu přejížděj rukama po jeho těle.|60",

    // Karty s cílem
    "Průzkum poslepu: Zavaž mu oči a polibky prozkoumej jeho hruď, krk a břicho. Po každém polibku buď spokojeně zabručí, nebo mlčí. Cíl: najít tři místa, kde zabručí nejvíc, a vrátit se k nim.",
    "Nehybný: On stojí v obýváku a nesmí se hnout. Ty ho pomalu svlékáš do boxerek a líbáš. Když se pohne, jednu věc mu obleč zpátky. Cíl: dostat ho do boxerek.|180",
    "Striptýz na písničku: Pusť písničku, on sedí v křesle. Každých 20 vteřin sundej jednu věc a tancuj. Cíl: na konci písničky být ve spodním prádle a sednout si mu na klín.|180",
    "Led a teplo: Přejeď mu kostkou ledu po hrudi a bradavkách a každé studené místo hned zahřej pusou. Cíl: aby mu naskočila husí kůže.|90",
    "Scéna do ucha: Pošeptej mu do ucha scénu, kterou s ním dnes chceš zažít – kde, jak a co budeš mít na sobě. Cíl: aby ti řekl „tak pojď“.",
    "Krmení na klíně: Posaď ho na židli v kuchyni, sedni si mu na klín a krm ho ovocem nebo čokoládou ze svých rtů. Cíl: pět soust, každé zakončené polibkem.",
    "Za každý knoflík: Rozepínej mu košili, mikinu nebo kalhoty a za každý knoflík či zip mu dej polibek jinam. Cíl: aby zůstal jen v boxerkách.",
    "Pírkový průzkum: On leží na břiše. Přejížděj mu pírkem po zádech, bocích, stehnech a chodidlech. Cíl: najít místo, kde se zachvěje nejvíc, a dlouze ho políbit.|90",
    "Masáž za zabručení: Masíruj mu záda. Ruce smí sjet o kousek níž, jen když spokojeně zabručí. Cíl: dostat se masáží až na jeho zadek.|180",
    "Klín na židli: Posaď ho na židli bez opěrek a ruce mu dej za záda. Oblečená se na jeho klíně pomalu vlň do rytmu hudby. Nesmí tě chytit. Cíl: vydržet celou písničku.|180",
    "Pomalé přiblížení: Přibližuj se k jeho rtům 30 vteřin a pak ho líbej celou minutu. Cíl: aby tě chytil dřív, než se dotknete.|90",
    "Zuby a triko: Dej ruce za záda. Zuby mu vytáhni triko z kalhot a polibky stoupej po břiše k hrudi. Cíl: zvládnout to bez rukou.|120",
    "Přišpendlený: Přitiskni ho zády ke dveřím ložnice, podrž mu ruce nad hlavou a líbej ho od ucha po klíční kost. Cíl: aby se ti vysmekl a pevně tě objal.|60",
    "Pásek: Rozepni mu pásek a vytáhni ho z kalhot jedním pomalým tahem. Pak ho hoď na zem. Cíl: celou dobu se mu dívat do očí.",
    "Jeho vůně: Přičichni k jeho krku, hrudi, zápěstí a podbřišku přes oblečení a u každého místa mu řekni, co ti jeho vůně dělá. Cíl: aby si tě přitáhl.",
    "Tři dotyky: Na jeho krku vyzkoušej konečky prstů, nehty a rty. On vybere, co chce znovu. Cíl: tím vybraným projdi celou jeho hruď.|60",
    "Souboj pohledů: Sedněte si na zem naproti sobě a dívejte se do očí, ty mu přitom hladíš stehna. Kdo první uhne, svlékne jednu věc. Cíl: vydržet dvě minuty.|120",
    "Obcházení židle: Posaď ho na židli a obcházej ho – líbej ho zezadu na krk, zepředu na rty, zboku na ucho. Nesmí se tě dotknout. Cíl: dvě minuty, pak tě smí chytit.|120",
    "Stupně polibků: On leží na zádech. Polib ho na kotník, koleno, stehno, bok, žebra, bradavku, krk a nakonec na rty – každý polibek delší. Cíl: poslední polibek trvá aspoň 30 vteřin.",
    "Horké ruce: Promni si dlaně do horka a přilož mu je pod triko na podbřišek a bedra. Líbej ho na krk. Cíl: aby se mu zrychlil dech.|60",
    "Pod dekou pro něj: Na gauči pod dekou ho hlaď po stehnech, pořád výš, zatímco nahoře vedeš úplně normální rozhovor. Cíl: aby první přestal mluvit on.|120",
    "Tvůj trůn: Posaď ho na zem opřeného o gauč a sedni si mu obkročmo na klín čelem k němu. Líbej ho a pomalu mu sundej triko. Cíl: aby tě chytil za zadek.|90",
    "Hlava v klíně: Nech ho položit si hlavu do tvého klína na gauči. Masíruj mu spánky, čelo a vlasy a pak ho polib vzhůru nohama. Cíl: aby zavřel oči a vzdychl.|120",
    "Stínohra: Zhasni a nech svítit jen lampu. Svlékej se pomalu tak, aby tvůj stín tančil na zdi, a on se dívá. Cíl: skončit ve spodním prádle a sednout si mu na klín.|120",
    "Hádej tvar: Nakresli mu prstem na záda tvar nebo písmeno. Když uhodne, dostane polibek, když ne, sundá si jednu věc. Cíl: pět kol.",
    "Cestou po paži: Polib mu konečky prstů, dlaň, zápěstí, loket, rameno a krk. Na každé zastávce 5 vteřin. Cíl: u krku už musí mít zavřené oči.",
    "Studený dotek: Vezmi z lednice něco studeného, přejeď mu s tím po zátylku a břiše a místo hned zahřej rty. Cíl: pět míst.",
    "Aranžérka: On sedí na gauči a ty ho „aranžuješ“ – rozepneš mu košili, vyhrneš triko, rozepneš knoflík u kalhot. Každou změnu zakonči polibkem. Cíl: pět změn, na konci bez trika.",
    "Rty po částech: Líbej mu jen horní ret, pak dolní, pak koutky. Cíl: aby tě chytil za tvář a políbil tě naplno.",
    "Přesvědč mě: Chceš mu sundat triko, ale on se brání, dokud ho nepřesvědčíš třemi polibky na místa, která určí. Cíl: triko na zemi.",
    "Čtyři doteky: Hlaď ho přes triko, pak pod ním, pak jen nehty a nakonec jen dechem – každé 30 vteřin. Cíl: zjistit, co ho nejvíc bere, a to zopakovat.|120",
    "Kočka: Lez k němu po gauči po čtyřech, pomalu a s pohledem do očí, a zastav se těsně před jeho rty. Cíl: dotknout se ho až ve chvíli, kdy se pro polibek natáhne sám.",
    "Obrácená lžička: Lehni si za něj, oba na boku, ty za jeho zády. Hlaď ho po hrudi a břiše. Cíl: aby se k tobě otočil čelem.|120",
    "Minutové triko: Sundej mu triko tak pomalu, aby to trvalo celou minutu. Cíl: nezastavit se.|60",
    "Hlas ve tmě: Zavaž mu oči a šeptej mu, co s ním budeš dělat v další úrovni, zatímco ho hladíš jen po pažích. Cíl: aby tě poprosil, ať přestaneš mluvit a začneš.|90",
    "Na stole: Sedni si na jídelní stůl a přitáhni si ho mezi kolena. Obejmi ho nohama kolem pasu a rukama mu přejížděj po zádech pod tričkem. Cíl: aby se o tebe opřel celou vahou.|60",
    "Dvacet polibků: On počítá nahlas do dvaceti a ty ho za každé číslo polibíš jinam. Když se splete, začíná znovu. Cíl: dojít do dvaceti.",
    "Rozpuštěný led: Drž kostku ledu mezi rty a přejížděj mu s ní po krku a hrudi. Cíl: kostka se musí rozpustit na jeho kůži.|90",
    "Nahoře: Lehni si na něj, když leží na zádech, a jen rukama a nohama mu stáhni kalhoty. Cíl: kalhoty pryč, aniž bys z něj slezla.",
    "U postele: Klekni si před něj, když sedí na posteli, a líbej mu kolena a stehna přes kalhoty, pořád výš. Cíl: zastavit se těsně před klínem a podívat se mu do očí.",
    "Mytí hlavy: Ve sprše mu umyj vlasy a pomalu mu masíruj hlavu, přitisknutá k jeho zádům. Cíl: aby se o tebe opřel a zavřel oči.|120",
    "Dech na dech: Lehněte si čelem k sobě, čela u sebe, a dýchejte stejně. Hlaď ho po páteři. Cíl: minuta bez polibku – pak ho dostane.|60",
    "Rozepínání poslepu: Posaď ho na židli a sedni si mu obkročmo na klín. Se zavřenýma očima mu rozepni košili nebo sundej triko. Cíl: zvládnout to poslepu.",
    "Spirály k boxerkám: Leží na břiše jen v boxerkách. Kresli mu prsty po zádech spirály, které se blíží k lemu boxerek. Cíl: vždy se zastavit těsně před ním – pětkrát.|90",
    "Návrat domů: Hraj, že přichází domů. Přitiskni ho ke zdi v chodbě, polib ho, jako byste se týden neviděli, a začni ho svlékat. Cíl: dojít do ložnice a nechat po cestě tři kusy jeho oblečení.",
    "Jeho uši: Věnuj se jen jeho uším – líbej, olizuj, jemně kousej a šeptej. Cíl: aby mu naskočila husí kůže.|60",
    "Kompliment za každý kus: Za každou věc, kterou mu sundáš, mu řekni upřímný kompliment o jeho těle. Cíl: dojít k boxerkám s pěti komplimenty.",
    "Vana pro něj: Napusť mu vanu, pomoz mu dovnitř a namydli mu ramena a hruď. Sama zůstaň venku. Cíl: aby tě pozval k sobě.|300",
    "Jeho košile: Obleč si jeho košili nebo triko na holé tělo a přijď za ním. Za každý polibek, který ti dá, smí rozepnout jeden knoflík. Cíl: košile úplně rozepnutá.",
    "Za triko do ložnice: Chyť ho za lem trika, kravatu nebo pásek a veď ho bytem do ložnice. Cestou se dvakrát zastav a polib ho. Cíl: posadit ho na postel.",
    "Nehty po zádech: Sedni si za něj na posteli a přejížděj mu nehty po zádech – nejdřív lehce, pak pevněji. Cíl: najít sílu, při které zasténá.|60",
    "Ochutnávka: Namoč prst ve víně, šlehačce nebo medu a nech ho olíznout. Pak si kapku dej na krk a nech ho olíznout i tam. Cíl: tři místa, každé níž.",
    "Polibek vzhůru nohama: Stoupni si za něj, když sedí na gauči, zakloň mu hlavu a polib ho vzhůru nohama. Rukama ho hlaď po hrudi pod tričkem. Cíl: aby se po tobě natáhl.|60",
    "Pohled přes rameno: Stoupni si k oknu se zataženými závěsy zády k němu, pomalu si sundej triko a podívej se na něj přes rameno. Cíl: počkat, až přijde sám a obejme tě.",
    "Bez rtů: Líbej ho všude na obličeji a krku, jen ne na rty. Cíl: vydržet, dokud tě o polibek nepoprosí.|90",
    "Podprsenková výzva: Sedni si zády k němu a nech ho rozepnout ti podprsenku jen jednou rukou. Cíl: pokud to nezvládne do 30 vteřin, dluží ti masáž nohou, když ano, smí ti ji sundat zuby.|30",
  ],
});
