// Kategorie 2 – Smyslné doteky (dávka c)
// Témata: dráždění přes prádlo, vzájemná masturbace, vedená ruka, edging rukou.
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 2,

  male: [
    "Až látka zvlhne: Dráždi ji přes kalhotky jedním prstem. Cíl: nesundat jí je, dokud látka úplně nezvlhne.|180|vedle_ona_lezi",
    "Nehybná dlaň: Polož jí dlaň mezi nohy přes prádlo a nech ji tam ležet. Cíl: nepohnout se, dokud se o ni sama neotře.|120|vedle_ona_lezi",
    "Vedená ruka: Vezmi její ruku a nech ji ukázat, jak přesně si chce hladit klitoris. Pak to samé děláš ty. Cíl: napodobit její tempo i tlak.|180|vedle_ona_lezi",
    "Třicet pohybů: Dráždi ji prsty tak pomalu, jak jen dokážeš. Cíl: za tři minuty udělat nejvýš třicet pohybů – počítej je.|180|vedle_ona_lezi",
    "Jen jí drž ruku: Nech ji, ať si sáhne sama, a ty jí u toho jen drž zápěstí a díváš se. Cíl: tři minuty a nepřevzít to za ni.|180|lzicka",
    "Prsty zvenku: Dráždi ji jen po okrajích, nikdy přímo na klitorisu. Cíl: ať si tvoji ruku sama posune.|180|vedle_ona_lezi",
    "Ruka a hlas: Lehni si za ni na lžičku, dráždi ji rukou zepředu a do ucha jí u toho šeptej. Cíl: čtyři minuty a nepřestat mluvit.|240|lzicka",
    "Kolem, nikdy na něm: Namaž si prsty lubrikantem a krouži jí kolem klitorisu. Cíl: tři minuty a ani jednou se ho nedotknout přímo.|180|vedle_ona_lezi",
    "Ona vede, ty plníš: Nech ji, ať ti vede ruku, ale prst uvnitř máš ty. Cíl: tři minuty, při kterých se sám od sebe nepohneš.|180|vedle_ona_lezi",
    "Tři na hraně: Dráždi ji prsty až těsně k vrcholu a vždycky přestaň. Třikrát. Počtvrté už ji nech. Cíl: vydržet všechna tři zastavení.|300|vedle_ona_lezi",
    "Prst bez pohybu: Vsuň do ní jeden prst, nech ho úplně nehybně a líbej ji. Cíl: dvě minuty a prstem ani nezakroutit.|120|vedle_ona_lezi",
    "Uvnitř i zvenku: Dráždi ji dvěma prsty uvnitř a palcem zvenku zároveň. Cíl: čtyři minuty a obojí ve stejném rytmu.|240|vedle_ona_lezi",
    "Nejvýš dva prsty: Přiveď ji rukou k vrcholu, ale nesmíš použít víc než dva prsty. Cíl: dovést ji tam do pěti minut.|300|vedle_ona_lezi",
    "Držet a dráždit: Nech ji ležet na zádech, jednou rukou jí drž zápěstí a druhou ji dráždi. Cíl: čtyři minuty a ruku jí ani jednou nepustit.|240|vedle_ona_lezi",
    "Souboj rukou: Dotýkejte se navzájem rukama zároveň. Kdo první vydá zvuk, prohrál. Cíl: vydržet déle než ona.|240|lzicka",
    "Kdo je sundá: Dráždi ji rukou přes kalhotky a jen sleduj. Cíl: nesahat na ně – vydržet, dokud si je nezačne stahovat sama.|180|vedle_ona_lezi",
    "Celá dlaň: Použij hodně lubrikantu a hlaď ji celou dlaní, ne prsty. Cíl: tři minuty a ani jednou nepoužít špičky prstů.|180|vedle_ona_lezi",
    "Oba naráz: Ukaž jí, jak se dotýkáš sám sebe, a nech ji dělat to samé. Cíl: tři minuty a celou dobu se na sebe dívat.|180|sed_celem",
    "Obě ruce zepředu: Sedni si za ni, roztáhni jí kolena a dráždi ji oběma rukama. Cíl: čtyři minuty a nedovolit jí kolena zavřít.|240|klin_podlaha",
    "Pomalé střídání: Deset vteřin uvnitř prsty, deset vteřin venku dlaní. Pořád dokola. Cíl: nikdy nezrychlit.|240|vedle_ona_lezi",
    "Hřbetem ruky: Hlaď ji mezi nohama hřbetem ruky místo dlaní. Cíl: dvě minuty a pak se zeptat, co je lepší.|120|vedle_ona_lezi",
    "Poslouchej na slovo: Nech ji říct, kolik prstů a jak rychle, a plň to úplně přesně. Cíl: čtyři minuty a ani jednou si nedělat po svém.|240|vedle_ona_lezi",
    "Zvuk stojí pět vteřin: Dráždi ji, ale pokaždé, když vydá zvuk, na pět vteřin přestaneš. Cíl: čtyři minuty a pravidlo dodržet do jedné.|240|vedle_ona_lezi",
    "Ruce nahoře, ruka dole: Drž jí obě zápěstí nad hlavou jednou rukou a druhou ji dráždi. Cíl: čtyři minuty a ani jednou ji nepustit.|240|vedle_ona_lezi",
    "Jen dvě minuty: Máš přesně dvě minuty, abys ji prsty dostal co nejblíž k orgasmu. Cíl: přestat přesně na čase, ať je kdekoli.|120|vedle_ona_lezi",
    "Oči otevřené: Klekni si vedle ní a dráždi ji, ale celou dobu se na sebe musíte dívat. Cíl: kdykoli zavře oči, na pět vteřin přestaň.|240|vedle_ona_lezi",
    "Jeden prst, jedno tempo: Dráždi ji jediným prstem a v jediném tempu, žádné změny. Cíl: tři minuty a ani jednou nezrychlit.|180|vedle_ona_lezi",
    "Krk a ruce: Nech ji sedět mezi tvýma nohama zády k tobě a dráždi ji, zatímco jí líbáš krk. Cíl: pět minut a nepřestat ani u jednoho.|300|klin_podlaha",
    "Tlak podle ní: Polož si její ruku na svou a nech ji přitlačit přesně tak, jak jí to vyhovuje. Cíl: tři minuty a tlak nezměnit sám od sebe.|180|vedle_ona_lezi",
    "Stupnice: Ptej se jí během dráždění, kde je na stupnici od jedné do desíti. Zastavíš se na osmičce. Cíl: udržet ji na osmi celou minutu.|240|vedle_ona_lezi",
    "Zezadu na břiše: Nech ji ležet na břiše s pokrčenou nohou a dráždi ji zezadu rukou. Cíl: čtyři minuty a nenechat ji se otočit.|240|masaz_zada",
    "Prsty a jazyk: Střídej dva prsty uvnitř a jazyk na bradavce. Cíl: deset střídání a nikdy obojí naráz.|240|vedle_ona_lezi",
    "Ruka jako nástroj: Nech ji vést si tvoji ruku po celém svém těle. Cíl: čtyři minuty, při kterých se sám od sebe nepohneš ani o kousek.|240|vedle_ona_lezi",
    "Jen koneček prstu: Dráždi ji jen konečkem prstu a nikdy netlač víc než na sotva znatelný dotek. Cíl: tři minuty a nepřitlačit.|180|vedle_ona_lezi",
    "Podržená ruka: Drž jí obě ruce a dráždi ji tak dlouho, dokud se ti nezačne vzpírat. Cíl: nepustit ji ani jednou.|300|vedle_ona_lezi",
    "Nejdřív ukázka: Polož si její ruku na svou a nech ji na klitorisu ukázat rytmus. Cíl: čtyři minuty ho pak držet sám a ani jednou ho nesplést.|240|vedle_ona_lezi",
    "Kruhy dlaní: Použij lubrikant a hlaď ji celou dlaní v pomalých kruzích. Cíl: tři minuty a ani jeden prst dovnitř.|180|vedle_ona_lezi",
    "Dívat se a nesahat ústy: Klekni si mezi její kolena a dráždi ji rukou, zatímco se na ni jen díváš. Cíl: čtyři minuty a nepoužít ústa.|240|oral_klek",
    "Hledání tempa: Nech ji položit si ruku na tvoji a společně hledejte správné tempo. Cíl: vyzkoušet tři a u toho nejlepšího zůstat celou minutu.|180|vedle_ona_lezi",
    "Ruce ve dvou: Ona se dotýká sama a ty jí k tomu přidáš druhou ruku. Nikdy nepřebírej vedení. Cíl: nechat ji řídit.|300|vedle_ona_lezi",
    "Vpředu a vzadu: Dráždi ji jednou rukou zepředu a druhou jí hlaď záda. Cíl: čtyři minuty a obě ruce ve stejném rytmu.|240|lzicka",
    "Vezmi její prsty a olízni je, než je zase přiložíš tam, kde byly.|120|vedle_ona_lezi",
    "Dráždi ji a přitom jí říkej nahlas, co přesně děláš.|240|vedle_ona_lezi",
    "Nech ji ležet na boku a dráždi ji rukou seshora. Druhou jí drž koleno.|240|lzicka",
    "Dvě rychlosti: Střídej pomalé kroužení a rychlé krátké pohyby po deseti vteřinách. Cíl: ať sama řekne, které chce.|240|vedle_ona_lezi",
    "Použij dva prsty a pohyb směrem k břichu. Hledej to místo uvnitř.|300|vedle_ona_lezi",
    "Drž ji za bok a dráždi ji tak, aby se ti mohla opřít.|240|lzicka",
    "Dráždi ji jen tak dlouho, dokud nezvedne boky. Pak přestaň a čekej.|180|vedle_ona_lezi",
    "Sama si je stáhne: Nech ji, ať si sama stáhne kalhotky, a teprve pak jí zajeď prsty mezi nohy. Cíl: do té doby se jí nedotknout.|120|vedle_ona_lezi",
    "Sto pohybů: Uděláš jí přesně sto pohybů prsty. Ona počítá nahlas. Cíl: dojít do sta bez ztráty rytmu.|300|vedle_ona_lezi",
    "Dráždi ji jednou rukou a druhou jí zakryj ústa. Ať se snaží být potichu.|240|vedle_ona_lezi",
    "Nech ji vybrat mezi prsty a dlaní. Pak použij to druhé.|180|vedle_ona_lezi",
    "Lehni si k ní na bok a dráždi ji tak, abyste se přitom dívali do očí.|240|lzicka",
    "Použij tolik lubrikantu, aby ruka klouzala úplně bez odporu.|240|vedle_ona_lezi",
    "Do konce: Dráždi ji rukou až do vrcholu a nepřestaň hned potom. Pokračuj ještě chvíli jemně. Cíl: dotáhnout to a zůstat.|300|vedle_ona_lezi",
    "Jedna ruka, nebo dvě: Střídej jeden prst na klitorisu a dva prsty v ní. Ona říká, kdy co. Cíl: čtyři minuty a poslechnout na slovo.|240|vedle_ona_lezi",
    "Na klíně zády: Posaď si ji na klín zády k sobě, roztáhni jí kolena a dráždi ji rukou zepředu. Cíl: čtyři minuty a ani jednou ji nepustit z klína.|240|klin_zady",
    "Přiklop jí dlaň na její vlastní ruku a veď ji, jak chceš ty.|180|vedle_ona_lezi",
    "Nech ji, ať se dotýká sama, a ty jí mezitím olizuj bradavky.|240|vedle_ona_lezi",
    "Pět minut bez cíle: Dráždi ji pět minut, ale ani jednou se nesmíš pokusit ji dostat přes hranu. Cíl: nespěchat.|300|vedle_ona_lezi",
    "Dej jí prst do pusy a pak ho použij tam, kde má být.|120|vedle_ona_lezi",
    "Dráždi ji a přitom jí drž nohu zvednutou. Změní to úplně všechno.|240|vedle_ona_lezi",
    "Nech ji položit tvoji ruku tam, kde ji chce mít, a nehýbej s ní.|120|vedle_ona_lezi",
    "Dráždi ji celou dlaní přes kalhotky dokola, nikdy nahoru a dolů.|180|vedle_ona_lezi",
    "Přestávka na povel: Ona řekne stop a ty okamžitě necháš ruku ležet bez pohybu. Pak zase start. Cíl: pět zastavení.|300|vedle_ona_lezi",
    "Použij prsty obou rukou zároveň – jeden uvnitř, druhý venku.|240|vedle_ona_lezi",
    "Dráždi ji vleže za ní a druhou rukou jí hlaď prsa.|240|lzicka",
    "Oči otevřené: Prsti ji a ona se ti přitom musí dívat do očí. Cíl: čtyři minuty – jakmile oči zavře, na deset vteřin přestaneš.|240|vedle_ona_lezi",
    "Dráždi ji tak jemně, že bude muset sama přitlačit.|180|vedle_ona_lezi",
    "Ruka a kolena: Roztáhni jí kolena rukama a dráždi ji jen jazykem prstu u ruky, kterou ji držíš. Cíl: nepustit kolena.|240|oral_klek",
    "Namaž jí lubrikantem celé prsty a nech ji, ať si je sama olízne.|120|vedle_ona_lezi",
    "Dráždi ji do chvíle, kdy ti sama řekne, ať zrychlíš. Do té doby se nepohneš rychleji.|300|vedle_ona_lezi",
    "Sedni si jí za záda a dráždi ji tak, aby ti hlavu opřela o rameno.|240|klin_podlaha",
    "Dej jí ruku mezi nohy a druhou jí drž bradu, ať se ti dívá do očí.|240|vedle_ona_lezi",
    "Beze slov: Celé dráždění probíhá bez jediného slova, jen podle toho, jak reaguje. Cíl: poznat to bez ptaní.|300|vedle_ona_lezi",
    "Dráždi ji jen v přestávkách mezi polibky. Nikdy obojí najednou.|240|vedle_ona_lezi",
    "Nech ji držet tvoje zápěstí a řídit, jak hluboko a jak rychle.|240|vedle_ona_lezi",
    "Dráždi ji zezadu, když klečí na všech čtyřech.|240|zezadu",
    "Dva prsty a dost: Dráždi ji jen malíčkem a ukazováčkem, ostatní prsty nepoužiješ. Cíl: tři minuty a ani jednou si nepomoct palcem.|180|vedle_ona_lezi",
    "Opačné tempo: Prsti ji a čím blíž je k orgasmu, tím pomaleji se hýbeš. Cíl: dovést ji tam tím nejpomalejším možným tempem.|300|vedle_ona_lezi",
    "Dráždi ji a druhou rukou si veď její ruku po svém těle.|240|lzicka",
    "Nech ji, ať si lehne na tebe zády, a dráždi ji oběma rukama.|300|propletene",
    "Dej jí ruku mezi nohy až ve chvíli, kdy tě o to sama poprosí.|180|vedle_ona_lezi",
    "Ruka po konci: Když dojde, nech dlaň ležet na jejím klíně a jen ji drž. Cíl: nehnout se, dokud se jí nezklidní dech.|120|lzicka",
  ],

  female: [
    "Až budou těsné: Dráždi ho přes trenýrky jedním prstem. Cíl: nesundat mu je, dokud v nich nebude úplně těsno.|180|vedle_on_lezi",
    "Dlaň bez pohybu: Polož mu dlaň mezi nohy přes prádlo a nech ji tam ležet. Cíl: nepohnout se, dokud se o ni sám neotře.|120|vedle_on_lezi",
    "Vedená ruka: Vezmi jeho ruku a nech ho ukázat, jak přesně si honí. Pak to samé děláš ty. Cíl: napodobit jeho tempo i stisk.|180|vedle_on_lezi",
    "Třicet tahů: Hlaď ho rukou tak pomalu, jak jen dokážeš. Cíl: za tři minuty udělat nejvýš třicet tahů – počítej je.|180|vedle_on_lezi",
    "Drž mu zápěstí: Nech ho, ať si sáhne sám, a ty mu u toho jen drž zápěstí a díváš se. Cíl: tři minuty a nepřevzít to za něj.|180|lzicka",
    "Jen kolem: Dráždi ho jen po stranách a na hrázi, nikdy přímo. Cíl: ať si tvoji ruku sám posune.|180|vedle_on_lezi",
    "Šepot za jeho zády: Lehni si za něj na lžičku, dráždi ho rukou zepředu a do ucha mu u toho šeptej. Cíl: čtyři minuty a nepřestat mluvit.|240|lzicka",
    "Dlouhé tahy: Namaž si dlaň lubrikantem a hlaď ho pomalými tahy po celé délce. Cíl: padesát tahů a ani jeden kratší.|180|vedle_on_lezi",
    "On vede, ty držíš: Nech ho, ať si vede tvoji ruku, ale dlaň zůstává tvoje. Cíl: tři minuty, při kterých se sama od sebe nepohneš.|180|vedle_on_lezi",
    "Tři na hraně: Hlaď ho rukou až těsně k vrcholu a vždycky přestaň. Třikrát. Počtvrté už ho nech. Cíl: vydržet všechna tři zastavení.|300|vedle_on_lezi",
    "Jen ho drž: Obejmi ho rukou, nehýbej se a jen ho tak drž a líbej. Cíl: dvě minuty bez jediného pohybu dlaně.|120|vedle_on_lezi",
    "Dvě místa naráz: Dráždi ho jednou rukou a druhou mu masíruj hráz mezi varlaty a konečníkem. Cíl: čtyři minuty a obojí ve stejném rytmu.|240|vedle_on_lezi",
    "Dva prsty a nic víc: Přiveď ho rukou k vrcholu, ale nesmíš použít víc než dva prsty. Cíl: dovést ho tam do pěti minut.|300|vedle_on_lezi",
    "Jedna drží, druhá dráždí: Nech ho ležet na zádech, jednou rukou mu drž zápěstí a druhou ho dráždi. Cíl: čtyři minuty a ruku mu nepustit.|240|vedle_on_lezi",
    "Souboj rukou: Dotýkejte se navzájem rukama zároveň. Kdo první vydá zvuk, prohrál. Cíl: vydržet déle než on.|240|lzicka",
    "Kdo je stáhne: Dráždi ho rukou přes trenýrky a jen sleduj. Cíl: nesahat na ně – vydržet, dokud si je nezačne stahovat sám.|180|vedle_on_lezi",
    "Pevně a sotva: Použij hodně lubrikantu a střídej pevný a úplně lehký stisk. Cíl: dvacet střídání a on nesmí uhodnout, co přijde.|180|vedle_on_lezi",
    "Každý sám za sebe: Ukaž mu, jak se dotýkáš sama sebe, a nech ho dělat to samé. Cíl: tři minuty a celou dobu se na sebe dívat.|180|sed_celem",
    "Opřený o tebe: Sedni si za něj, opři si ho o hrudník a dráždi ho oběma rukama. Cíl: čtyři minuty a nenechat ho se předklonit.|240|klin_podlaha",
    "Pomalé střídání: Deset vteřin pevně, deset vteřin jen konečky prstů. Pořád dokola. Cíl: nikdy nezrychlit.|240|vedle_on_lezi",
    "Hřbet místo dlaně: Hlaď ho hřbetem ruky místo dlaní. Cíl: dvě minuty a pak se zeptat, co je lepší.|120|vedle_on_lezi",
    "Podle jeho slov: Honi mu a nech ho říkat, jak pevně a jak rychle. Cíl: čtyři minuty a ani jednou si nedělat po svém.|240|vedle_on_lezi",
    "Zvuk za pět vteřin: Dráždi ho, ale pokaždé, když vydá zvuk, na pět vteřin přestaneš. Cíl: čtyři minuty a pravidlo dodržet do jedné.|240|vedle_on_lezi",
    "Jeho zápěstí nahoře: Drž mu obě zápěstí nad hlavou jednou rukou a druhou ho dráždi. Cíl: čtyři minuty a ani jednou ho nepustit.|240|vedle_on_lezi",
    "Dvě minuty na hranu: Máš přesně dvě minuty, abys ho rukou dostala co nejblíž. Cíl: přestat přesně na čase, ať je kdekoli.|120|vedle_on_lezi",
    "Nezavírat oči: Klekni si vedle něj a dráždi ho, ale celou dobu se na sebe musíte dívat. Cíl: kdykoli zavře oči, na pět vteřin přestaň.|240|vedle_on_lezi",
    "Dva prsty, jedno tempo: Dráždi ho jen dvěma prsty a v jediném tempu, žádné změny. Cíl: tři minuty a ani jednou nezrychlit.|180|vedle_on_lezi",
    "Zády k němu: Sedni si mu mezi nohy zády k němu a dráždi ho, zatímco tě líbá na krk. Cíl: pět minut a nepřestat ani u jednoho.|300|klin_podlaha",
    "Tlak podle něj: Polož si jeho ruku na svou a nech ho přitlačit přesně tak, jak mu to vyhovuje. Cíl: tři minuty a tlak nezměnit sama od sebe.|180|vedle_on_lezi",
    "Stupnice: Ptej se ho během dráždění, kde je na stupnici od jedné do desíti. Zastavíš se na osmičce. Cíl: udržet ho na osmi celou minutu.|240|vedle_on_lezi",
    "Na břiše zezadu: Nech ho ležet na břiše, vsuň mu ruku pod boky a dráždi ho zezadu. Cíl: čtyři minuty a nenechat ho se otočit.|240|masaz_zada!",
    "Ruka, nebo jazyk: Střídej ruku a jazyk na jeho bradavce, nikdy obojí najednou. Cíl: deset střídání a ani jednou pravidlo neporušit.|240|vedle_on_lezi",
    "Tvoje ruka, jeho vedení: Nech ho vést si tvoji ruku po těle až na penis a řídit i stisk. Cíl: čtyři minuty a sama od sebe se nepohnout.|240|vedle_on_lezi",
    "Sotva se dotýkat: Dráždi ho jen konečkem prstu a nikdy netlač víc než na sotva znatelný dotek. Cíl: tři minuty a nepřitlačit.|180|vedle_on_lezi",
    "Podržená ruka: Drž mu obě ruce a dráždi ho tak dlouho, dokud se ti nezačne vzpírat. Cíl: nepustit ho ani jednou.|300|vedle_on_lezi",
    "Ukázka a pak sama: Polož si jeho ruku na svou a nech ho na penisu ukázat rytmus. Cíl: čtyři minuty ho pak držet sama a nesplést ho.|240|vedle_on_lezi",
    "Dokola místo nahoru: Použij lubrikant a otáčej dlaní kolem dokola místo nahoru a dolů. Cíl: tři minuty a ani jednou nesklouznout do obvyklého pohybu.|180|vedle_on_lezi",
    "Ruka, ne ústa: Klekni si mezi jeho kolena a dráždi ho rukou, zatímco se na něj jen díváš. Cíl: čtyři minuty a nepoužít ústa.|240|oral_on_vleze",
    "Společné tempo: Nech ho položit si ruku na tvoji a společně hledejte správné tempo. Cíl: vyzkoušet tři a u toho nejlepšího zůstat celou minutu.|180|vedle_on_lezi",
    "Ruce ve dvou: On se dotýká sám a ty mu k tomu přidáš druhou ruku. Nikdy nepřebírej vedení. Cíl: nechat ho řídit.|300|vedle_on_lezi",
    "Zepředu a po zádech: Dráždi ho jednou rukou zepředu a druhou mu hlaď záda. Cíl: čtyři minuty a obě ruce ve stejném rytmu.|240|lzicka",
    "Olíznuté prsty: Vezmi jeho prsty, olízni je a teprve pak je zase přilož tam, kde byly. Cíl: pětkrát a pokaždé o něco pomaleji.|120|vedle_on_lezi",
    "Dráždi ho a přitom mu říkej nahlas, co přesně děláš.|240|vedle_on_lezi",
    "Nech ho ležet na boku a dráždi ho rukou seshora. Druhou mu drž koleno.|240|lzicka",
    "Dvě rychlosti: Střídej pomalé dlouhé tahy a rychlé krátké po deseti vteřinách. Cíl: ať sám řekne, které chce.|240|vedle_on_lezi",
    "Použij obě ruce nad sebou a pohybuj jimi proti sobě.|300|vedle_on_lezi",
    "Drž ho za bok a dráždi ho tak, aby se o tebe mohl opřít.|240|lzicka",
    "Dráždi ho jen tak dlouho, dokud nezvedne boky. Pak přestaň a čekej.|180|vedle_on_lezi",
    "Sám si je stáhne: Nech ho, ať si sám stáhne trenýrky, a teprve pak ho vezmi do ruky. Cíl: do té doby se ho nedotknout.|120|vedle_on_lezi",
    "Sto pohybů: Uděláš mu přesně sto pohybů rukou. On počítá nahlas. Cíl: dojít do sta bez ztráty rytmu.|300|vedle_on_lezi",
    "Dráždi ho jednou rukou a druhou mu zakryj ústa. Ať se snaží být potichu.|240|vedle_on_lezi",
    "Nech ho vybrat mezi rukou a prsty. Pak použij to druhé.|180|vedle_on_lezi",
    "Lehni si k němu na bok a dráždi ho tak, abyste se přitom dívali do očí.|240|lzicka",
    "Nalij si do dlaně tolik lubrikantu, že ruka bude klouzat úplně sama.|240|vedle_on_lezi",
    "Do konce: Dráždi ho rukou až do konce a nepřestaň hned potom. Pokračuj ještě chvíli jemně. Cíl: dotáhnout to a zůstat.|300|vedle_on_lezi",
    "Jedna ruka, nebo obě: Střídej jednu ruku na penisu a obě nad sebou. On říká, kdy co. Cíl: čtyři minuty a poslechnout na slovo.|240|vedle_on_lezi",
    "Dráždi ho vsedě, když mu sedíš na klíně zády.|240|klin_zady",
    "Přiklop mu dlaň na jeho vlastní ruku a veď ji, jak chceš ty.|180|vedle_on_lezi",
    "Nech ho, ať se dotýká sám, a ty mu mezitím olizuj bradavky.|240|vedle_on_lezi",
    "Pět minut bez cíle: Dráždi ho pět minut, ale ani jednou se nesmíš pokusit ho dostat přes hranu. Cíl: nespěchat.|300|vedle_on_lezi",
    "Dej mu prst do pusy a pak ho použij tam, kde má být.|120|vedle_on_lezi",
    "Dráždi ho a přitom mu drž nohu zvednutou. Změní to úplně všechno.|240|vedle_on_lezi",
    "Nech ho položit tvoji ruku tam, kde ji chce mít, a nehýbej s ní.|120|vedle_on_lezi",
    "Dráždi ho celou dlaní přes trenýrky dokola, nikdy nahoru a dolů.|180|vedle_on_lezi",
    "Přestávka na povel: On řekne stop a ty okamžitě necháš ruku ležet bez pohybu. Pak zase start. Cíl: pět zastavení.|300|vedle_on_lezi",
    "Použij obě ruce zároveň – jedna nahoře, druhá na varlatech.|240|vedle_on_lezi",
    "Dráždi ho vleže za ním a druhou rukou mu hlaď hrudník.|240|lzicka",
    "Nesmí zavřít oči: Honi mu a on se ti přitom musí dívat do očí. Cíl: čtyři minuty – jakmile oči zavře, na deset vteřin přestaneš.|240|vedle_on_lezi",
    "Dráždi ho tak jemně, že bude muset sám přitlačit.|180|vedle_on_lezi",
    "Ruka a kolena: Roztáhni mu kolena rukama a dráždi ho jen jednou rukou, kterou ho držíš. Cíl: nepustit kolena.|240|oral_on_vleze",
    "Namaž si lubrikantem celé prsty a nech ho, ať si je sám olízne.|120|vedle_on_lezi",
    "Dráždi ho do chvíle, kdy ti sám řekne, ať zrychlíš. Do té doby se nepohneš rychleji.|300|vedle_on_lezi",
    "Sedni si mu za záda a dráždi ho tak, aby ti hlavu opřel o rameno.|240|klin_podlaha",
    "Dej mu ruku mezi nohy a druhou mu drž bradu, ať se ti dívá do očí.|240|vedle_on_lezi",
    "Mlčky: Honi mu celých pět minut bez jediného slova a tempo měň jen podle toho, jak reaguje. Cíl: poznat to bez ptaní.|300|vedle_on_lezi",
    "Dráždi ho jen v přestávkách mezi polibky. Nikdy obojí najednou.|240|vedle_on_lezi",
    "Nech ho držet tvoje zápěstí a řídit, jak pevně a jak rychle.|240|vedle_on_lezi",
    "Dráždi ho zezadu, když klečí na všech čtyřech.|240|zezadu!",
    "Použij jen palec a ukazovák v kroužku. Nic víc.|180|vedle_on_lezi",
    "Obrácené tempo: Honi mu a čím blíž je ke konci, tím pomaleji se hýbeš. Cíl: dovést ho tam tím nejpomalejším možným tempem.|300|vedle_on_lezi",
    "Dráždi ho a druhou rukou si veď jeho ruku po svém těle.|240|lzicka",
    "Nech ho, ať si lehne na tebe zády, a dráždi ho oběma rukama.|300|propletene",
    "Dej mu ruku mezi nohy až ve chvíli, kdy tě o to sám poprosí.|180|vedle_on_lezi",
    "Ruka po jeho konci: Když se udělá, nech dlaň ležet na jeho penisu a jen ho drž. Cíl: nehnout se, dokud se mu nezklidní dech.|120|lzicka",
  ],
});
