// Kategorie 2 – Smyslné doteky
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 2,
  name: "Smyslné doteky",
  description: "Nahá kůže, šikovné ruce, první vibrace. Dráždit, ale ještě nepouštět.",

  // Úkoly pro muže – pro potěšení ženy
  male: [
    "Celé tělo olejem: Svlékni ji donaha a namasíruj jí olejem celé tělo. Cíl: pět minut, při kterých se prsou a klína dotkneš až úplně nakonec.|300",
    "Přes látku: Přikládej jí vibrátor přes kalhotky na klitoris a střídej lehký dotek s pevnějším přitlačením. Cíl: deset střídání a kalhotky nesundat.|90",
    "Ruce za hlavou: Přejížděj jí pírkem po bradavkách a pak po vnitřní straně stehen. Cíl: půldruhé minuty a ona nesmí ruce sundat zpod hlavy.|90",
    "Jen dlaň: Zajeď jí rukou do kalhotek a hlaď ji pomalu celou dlaní. Cíl: celá minuta a ani jeden prst dovnitř.|60",
    "Jen zvenku: Posaď ji na linku, sundej jí kalhotky a prsty ji hlaď po stydkých pyscích. Cíl: půldruhé minuty a klitorisu se ani nedotknout.|90",
    "Obě ruce naráz: Lehni si za ni na lžičku a jednou rukou jí hlaď prsa, druhou klín. Cíl: dvě minuty a obě ruce ve stejném rytmu.|120|lzicka",
    "Mydlinky ve sprše: Namydli jí prsa a klín a pomalu ji dlaněmi hlaď a omývej – hlavně tam, kde to má nejradši. Cíl: dvě minuty a nikam nespěchat.|120",
    "Kolem dokola: Olízni si prsty a pomalu kroužkuj kolem jejího klitorisu. Cíl: dvacet koleček a ani jednou přímo na něj.|60",
    "Ke klínu jen na chvilku: Roztáhni jí nohy a vibrátorem přejížděj po vnitřní straně stehen. Cíl: ke klínu zajet jen třikrát, pokaždé na dvě vteřiny.|60",
    "Bradavky mezi prsty: Jemně jí sevři bradavky mezi prsty a pomalu je mnuj. Cíl: minuta a postupně přidávat tlak, dokud neřekne dost.|60",
    "Tři různé doteky: Zavaž jí oči a střídej na jejím těle pírko, prsty a vibrátor. Cíl: deset střídání a ať u každého uhodne, co to bylo.|120",
    "Prst, který se nehýbe: Vsuň do ní pomalu jeden prst a nech ho tam úplně nehybně, zatímco ji líbáš. Cíl: nepohnout jím, dokud se sama nezavrtí.|45",
    "Dívá se na sebe: Stoupni si za ni k zrcadlu, dej jí obě ruce mezi nohy a nech ji dívat se. Cíl: nepřestat, dokud nezavře oči – a pak ji donutit je otevřít.|90",
    "Olej na prsou: Namaž jí prsa olejem a masíruj je dokola, palci přejížděj přes bradavky. Cíl: dvacet kroužků na každém prsu.|90",
    "Třes zespodu: Posaď ji nahou na odstřeďující pračku a prsty ji hlaď po klíně. Cíl: nechat ji tam, dokud se sama nezačne otírat o víko.|60",
    "Až budou vlhké: Hlaď ji dvěma prsty po klitorisu přes kalhotky. Cíl: nesundat jí je, dokud nebudou úplně vlhké.|120",
    "Nohy přes opěrky: Posaď ji do křesla, přehoď jí nohy přes opěrky a prsty ji pomalu hlaď. Cíl: půldruhé minuty a ani jednou neuhnout pohledem.|90",
    "Centimetr po centimetru: Zapni vibrátor na nejnižší stupeň, polož jí ho na podbřišek a posouvej ho níž. Cíl: dostat se ke klínu nejdřív po minutě.|60",
    "Jazyk a dech: Přejeď jí jazykem po bradavce a hned na ni foukni. Pak to samé na druhé. Cíl: pět kol na každé straně.|60",
    "Kroužky kolem bradavek: Nech ji ležet na zádech a vibrátorem jí kroužkuj kolem bradavek. Cíl: deset kroužků na každé a přímo na ně nesahat.|60",
    "Hledání bodu G: Vsuň do ní dva prsty a proti přední stěně dělej pohyb „pojď sem“. Cíl: najít místo, u kterého se jí změní dech, a zůstat na něm.|90",
    "Vedeš její ruku: Vezmi její ruku a veď ji po jejím vlastním těle až mezi nohy. Cíl: minuta, při které tempo určuješ jen ty.|60",
    "Zezadu na břiše: Nech ji ležet na břiše, roztáhni jí nohy a zezadu ji hlaď po klínu. Cíl: půldruhé minuty a nenechat ji otočit se.|90",
    "Proud ze sprchy: Posaď ji na okraj vany a proudem ze sprchy jí jemně masíruj klín. Cíl: vyzkoušet tři vzdálenosti a u té nejlepší zůstat.|60",
    "Tři vteřiny a dost: Pusť vibrátor naplno, ale přikládej ho jen na vnitřní stranu stehen. Cíl: na klitoris ho dát jen jednou, a to na tři vteřiny.|60",
    "Opřená mezi tvýma nohama: Nech ji sednout si mezi tvé nohy zády k tobě a hlaď ji po prsou a klínu. Cíl: dvě minuty a ani jednou ji nepustit.|120|klin_podlaha",
    "Kalhotky u kolen: Stáhni jí kalhotky jen ke kolenům a pomalu jí přejížděj prsty mezi nohama. Cíl: celá minuta a dál je nestahovat.|60",
    "Pírko dole: Šimrej ji pírkem na stydkých pyscích a klitorisu, hodně zlehka. Cíl: vydržet u toho tři čtvrtě minuty a nepřitlačit.|45",
    "Nahoře i dole: Hlaď jí prsa a zároveň jí vibrátorem dráždi klitoris přes kalhotky. Cíl: půldruhé minuty a obě ruce ve stejném rytmu.|90",
    "Ruce nahoře: Dej jí ruce nad hlavu s tím, že je nesmí sundat, a hlaď ji po celém těle. Cíl: zdržet se všude, kde vzdychne, aspoň deset vteřin.|120",
    "Ústa a prsty naráz: Líbej ji na rty a přitom ji prsty pomalu dráždi mezi nohama. Cíl: nepřerušit polibek, ani když zrychlíš.|90",
    "Opřená o stůl: Nech ji opřít se rukama o stůl a zezadu jí zajeď rukou mezi nohy. Cíl: celá minuta a ona se nesmí narovnat.|60",
    "Dlaň v kruzích: Masíruj jí stydký pahorek celou dlaní v pomalých kruzích. Cíl: třicet kruhů a ani jednou nezrychlit.|60",
    "Pět věcí nahlas: Svlékni ji donaha, prohlížej si ji a řekni jí nahlas pět věcí, které na jejím nahém těle miluješ. Cíl: u každé se toho místa dotknout.|120",
    "Jakoby náhodou: Namaž si ruce olejem a masíruj jí vnitřní stranu stehen. Cíl: desetkrát se hřbetem ruky otřít o její klín, pokaždé jakoby náhodou.|90",
    "Polibek přes kalhotky: Opři ji o zeď, klekni si a polib ji přes kalhotky přímo na klín. Cíl: deset polibků a kalhotky jí nesundat.|90|zed",
    "Dva rytmy v jednom: Dráždi jí klitoris jedním prstem a druhou rukou jí hlaď bradavku. Cíl: půldruhé minuty a rytmus obou rukou ani jednou nerozejít.|90",
    "Cesta odshora dolů: Přejížděj jí vibrátorem od krku přes prsa a břicho až ke klínu. Cíl: pět cest a každá musí trvat aspoň patnáct vteřin.|90",
    "Prst a palec: Vsuň do ní prst a pomalu s ním kroužkuj, zatímco palcem hladíš klitoris. Cíl: dvacet kroužků, aniž bys palec přerušil.|60",
    "Voda a obě ruce: Přitiskni se k ní ve sprše zezadu a hlaď jí prsa i klín pod tekoucí vodou. Cíl: dvě minuty a ani jednou se neopřít o stěnu.|120",
    "Kalhotky zuby: Pomalu z ní stáhni kalhotky jen zuby, ruce máš za zády. Cíl: dostat je až ke kotníkům bez jediného doteku rukou.|120",
    "Ústa nahoře, ruka dole: Klekni si před ni, olizuj jí bradavky a rukou ji přitom hlaď mezi nohama. Cíl: půldruhé minuty a nepřerušit ani jedno.|90",
    "Dva naráz: Vezmi oba vibrátory a přilož jí je na obě bradavky zároveň. Cíl: tři čtvrtě minuty a postupně přidávat stupeň.|45",
    "Až začne sama: Hlaď ji mezi nohama pomalu a stejným tempem. Cíl: nezrychlit, dokud sama nezačne přirážet boky proti tvé ruce.|120",
    "Ruka a šepot: Stoupni si za ni, zajeď jí rukou do kalhot a dráždi ji prsty, zatímco jí šeptáš do ucha. Cíl: mluvit celou minutu bez pauzy.|60",
    "Nech ji lehnout na gauč s polštářem pod zadečkem a hlaď ji dlaní přes celý klín.|90",
    "Led a horká ústa: Přejeď jí kostkou ledu po bradavkách a hned je zahřej ústy. Cíl: pět střídání a pokaždé počkat, až se bradavka postaví.|90",
    "Zavaž jí oči a dotýkej se jí jen vibrátorem. Ať hádá, kam ho přiložíš příště.|90",
    "Rozetři jí lubrikant po klíně a pomalu ji hlaď celou dlaní.|60",
    "Prsty jí jemně rozevři stydké pysky a pomalu jí přejížděj konečkem prstu nahoru a dolů.|45",
    "Nech ji sedět na kuchyňské lince s roztaženýma nohama a přikládej jí vibrátor na klitoris. Líbej ji přitom.|90",
    "Lehni si vedle ní a pozoruj ji, jak se sama hladí. Ty ji smíš hladit jen po prsou.|120",
    "Hlaď ji mezi nohama a zpomal pokaždé, když začne zrychlovat dech.|120",
    "Masíruj jí zadeček olejem, pomalu a pevně. Občas nech prsty sklouznout mezi její nohy.|90",
    "Stáhni jí podprsenku a jazykem kresli kolečka kolem dvorců.|60",
    "Opři ji o okenní parapet se zataženými závěsy a zezadu ji hlaď rukou mezi nohama.|60",
    "Posaď si ji na klín čelem k sobě, oba nazí, a jen ji hlaď po zádech a zadečku, zatímco se o tebe otírá.|90",
    "Vsuň do ní dva prsty a nech je v klidu. Ona se na nich musí hýbat sama.|60",
    "Klekni si mezi její nohy a pomalu ji hlaď, přitom jí líbej vnitřní stranu stehen.|90",
    "Přitlač vibrátor na její podbřišek těsně nad stydkou kostí a druhou rukou ji hlaď po klitorisu.|60",
    "Pírkem jí přejížděj po zadečku a mezi hýžděmi, zlehka.|45",
    "Na posteli ji nech ležet na břiše a přikládej jí vibrátor zespodu mezi nohy, ať se o něj může otírat.|90",
    "Nech ji stát nahou v kuchyni a obcházej ji dokola. Pokaždé, když jsi za ní, přejeď jí rukou po klíně.|60",
    "Masíruj jí prsa oběma rukama a palci jí hlaď bradavky, dokud neztvrdnou.",
    "Olízni jí bradavku a hned na ni přilož vibrátor.|45",
    "Rychle a lehce jí ťukej prsty na klitoris, pak přejdi na pomalé dlouhé tahy. Opakuj.|90",
    "Nech ji ležet na zádech, klekni si nad ni a jen ji konečky prstů hlaď od kolen až k prsům, pořád dokola.|90",
    "Ve vaně nebo ve sprše vezmi sprchovou hlavici a pusť jí proud vody na klín.|90",
    "Dívej se a popisuj: Nech ji lehnout si a roztáhnout nohy. Dívej se na ni a nahlas popisuj, co vidíš a co s ní chceš dělat. Cíl: minuta bez jediného doteku.|60",
    "Hlaď ji přes kalhotky, pak pod nimi, pak zase přes ně. Střídej to.|90",
    "Zavaž jí oči, svlékni ji a hlaď ji všude – kromě klína. Až tě poprosí, dotkni se jí i tam.",
    "Vsuň do ní prst a pomalu ho vytahuj a zasouvej, přitom ji líbej na krk.|60",
    "Palcem jí masíruj klitoris v kolečkách, ukazováčkem ji hlaď u vstupu.|90",
    "Stoupni si s ní před zrcadlo. Ona si drží prsa, ty jí přikládáš vibrátor mezi nohy.|90",
    "Postav ji na chodbě zády ke zdi, klekni si a hlaď ji prsty po klíně, zatímco se dívá dolů na tebe.|60",
    "Vlhký prst: Pomalu jí přejížděj vlhkým prstem po rtech a pak po bradavkách. Cíl: deset cest a ani jednou nesjet níž.|60",
    "Nech ji ležet na zádech. Jedním vibrátorem jí dráždi bradavku, druhým vnitřní stranu stehna.|60",
    "Rozetři jí olej po prsou a břiše a pak si na ni lehni, ať kloužete tělem o tělo.|60",
    "Hlaď ji prsty, dokud se nezačne chvět – pak přestaň, polib ji a začni znovu.",
    "Posaď ji obkročmo na své stehno a nech ji, ať se o něj pomalu otírá. Ty jí hlaď prsa.|90",
    "Na posteli jí dej ruce za hlavu a jemně jí je přidrž jednou rukou. Druhou ji hlaď mezi nohama.|90",
    "Přejížděj jí jazykem po břiše od prsou až k lemu kalhotek – a zase zpátky.|60",
    "Nech ji ležet na boku a zezadu jí vsuň prsty mezi nohy, zatímco ji líbáš na krk.|90",
    "Vibrátorem přes kalhotky jí dělej pomalé osmičky kolem klitorisu.|60",
    "Masíruj jí chodidla olejem a pomalu stoupej výš až ke klínu. Zastav se těsně před ním.|120",
    "Vsuň do ní dva prsty, palec polož na klitoris a pomalu, rytmicky tiskni, jako bys ji masíroval.|90",
    "Posaď ji na jídelní stůl, polož ji na záda a hlaď ji po celém těle od krku až po kolena.|90",
    "Obejmi ji nahou zezadu, vezmi ji za ruku a veď její prsty po jejím klitorisu.|60",
    "Pírkem jí přejížděj po klitorisu a hned potom jí na něj foukni.|30",
    "Nech ji klečet na gauči opřenou o opěradlo a zezadu ji prsty dráždi.|90",
    "Kostkou ledu jí hlaď bradavky a teplou dlaní zároveň klín.|45",
    "Přilož si vibrátor k prstům a teprve těmi vibrujícími prsty ji hlaď.|60",
    "Lehni si vedle ní, dej jí ruku mezi nohy a ať ti sama říká, jak chce – pomaleji, rychleji, silněji.|120",
    "Líbej ji po krku a prsou a zároveň ji pomalu hlaď po stehnech – pokaždé o kousek blíž ke klínu.|90",
    "Rozetři jí lubrikant mezi nohama a pomalu ji hlaď od klitorisu až ke vstupu.|60",
    "Nech ji na posteli ležet na zádech s rukama podél těla. Dotknout se tě nesmí – ty ji hladíš všude, kde chceš.|120",
    "Stoupni si za ni ve sprše a jednou rukou jí drž prsa, druhou ji hlaď mezi nohama.|90",
    "Polož jí vibrátor na klitoris přes kalhotky a nech ho tam ležet. Ty ji zatím líbej na rty.|60",
    "Hlaď ji pomalu po zadečku, stehnech a klínu tak, jako by byla to nejvzácnější na světě.|90",
    "Posaď ji na postel, klekni si před ni a pomalu jí stáhni kalhotky. Pak ji polib na klín – jen jednou.",
    "Přitlač svůj nahý hrudník na její prsa a pomalu se o ni otírej, zatímco ji prsty hladíš mezi nohama.|60",
    "Odhrň jí kalhotky stranou a hlaď ji prsty přímo na klíně.|60",
    "V kuchyni ji opři o linku, klekni si za ni a hlaď jí stehna zezadu až ke klínu.|60",
    "Přitiskni jí teplou dlaň na klín a jen ji tam drž, zatímco jí olizuješ bradavku.|45",
    "Obkroč ji, když leží na zádech, a přejížděj jí vibrátorem po celém těle. Kde vzdychne, tam se zdrž.|90",
    "Namaž si prsty olejem a pomalu jimi přejížděj mezi jejími prsy a dolů po břiše.|45",
    "Klekni si nad ni, drž jí ruce nad hlavou a pomalu se o ni otírej celým tělem, ale do ní nevnikej.|60",
    "Posaď si ji na stehno a hlaď ji tak pomalu, jak jen umíš. Ona nesmí zrychlit.|90",
    "Hlaď jí klitoris jen konečkem vlhkého prstu, sotva znatelně.|60",
    "Posaď ji na gauč a roztáhni jí nohy. Jedním vibrátorem jí dráždi klitoris, druhým ji hlaď po bradavkách.|60",
    "Vsuň do ní prst a jemně tlač nahoru, zatímco druhou rukou tlačíš zvenku na podbřišek.|60",
    "Stáhni ji k okraji postele, klekni si na zem a pomalu ji hlaď prsty mezi nohama.|90",
    "Namaž jí olejem zadeček a stehna a masíruj je tak, aby se tvoje prsty pořád vracely ke klínu.|90",
    "Zakaž jí hýbat se. Hlaď ji prsty, a kdyby se pohnula, začni znovu od kolen.|90",

    // Karty s cílem
    "Tři rychlosti: Hlaď jí prstem klitoris pomalu, středně a rychle, každou rychlost 20 vteřin. Ona řekne, která je nejlepší. Cíl: v té pokračovat, dokud nezačne sténat.|90",
    "Vibrátorová mapa: Přikládej jí vibrátor na bradavky, podbřišek, třísla a vnitřní stehna, každé místo 10 vteřin. Cíl: klitoris až nakonec a nechat ho tam, dokud tě nechytí za ruku.|90",
    "Lekce od ní: Ona ti prsty ukáže, jak přesně se ráda hladí – kde, jak rychle a jak silně. Pak její ruku vystřídáš ty. Cíl: aby řekla, že to umíš stejně dobře.|180",
    "Stupnice vzrušení: Hlaď ji mezi nohama a ona každých 15 vteřin řekne číslo od 1 do 10, jak moc je vzrušená. Cíl: dostat ji na devítku – pak přestaň a polib ji.|180",
    "Prohlídka: Posaď ji, roztáhni jí nohy a prsty jí jemně rozevři stydké pysky. Jen se dívej a popisuj. Cíl: dotknout se jediným prstem, až sama zvedne boky.|60",
    "Proud vody: Ve sprše ji zezadu obejmi kolem pasu a sprchovou hlavicí jí pomalu přejížděj přes bradavky a pak mezi nohy. Cíl: najít úhel proudu, při kterém se jí podlomí kolena.|120",
    "Hledání klíče: Vsuň do ní jeden prst a pomalu s ním zkoušej různé směry. Ona tě navádí slovy „výš“, „níž“, „tam“. Cíl: najít místo, kde řekne „tam“, a zůstat u něj.|90",
    "Pírko a vibrátor: V jedné ruce pírko, ve druhé vibrátor. Pírkem jezdíš po jejích prsou, vibrátorem po stehnech. Po minutě je prohoď. Cíl: aby tě poprosila o vibrátor na klitoris – a pak ho dostane.|120",
    "Olejové tahy: Namaž jí celé tělo olejem a masíruj ji jen dlouhými tahy od kotníků přes klín až k prsům, bez zastavení. Cíl: dvacet tahů, každý o trochu pomalejší.|180",
    "Ruce nad hlavou: Ona leží na zádech s rukama nad hlavou a ty jí prsty dráždíš klitoris. Když ruce sundá, na 10 vteřin přestaneš. Cíl: aby vydržela celé dvě minuty.|120",
    "Mokrá skvrna: Hlaď ji přes kalhotky, dokud na nich neuvidíš vlhkou skvrnu. Pak jí je stáhni zuby. Cíl: kalhotky dole bez použití rukou.",
    "Předkloněná u linky: Ona se předkloní přes kuchyňskou linku. Zezadu ji hlaď prsty po stydkých pyscích a druhou rukou ji drž za bok. Cíl: aby sama začala přirážet proti tvé ruce.|90",
    "Dva rytmy: Vsuň do ní dva prsty a palcem jí kruž po klitorisu. Prsty se hýbou pomalu, palec rychle. Cíl: udržet tenhle rozdílný rytmus dvě minuty.|120",
    "Bradavkový test: Věnuj se jen jejím bradavkám – prsty, jazykem, vibrátorem a lehkým štípnutím, každé po 20 vteřinách. Cíl: zjistit, co ji vzruší nejvíc, a u toho skončit.|120",
    "Dráždivé pauzy: Hlaď jí klitoris 30 vteřin, pak 10 vteřin nic – jen se jí dívej do očí. Opakuj. Cíl: aby tě při pauze sama chytila za ruku a vrátila ji zpátky.|180",
    "Zrcadlo v ložnici: Posaď se před zrcadlo, ona si sedne mezi tvé nohy zády k tobě a roztáhne nohy. Hlaď ji a ona se dívá do zrcadla. Cíl: nesmí zavřít oči ani uhnout pohledem.|120",
    "Nejpomalejší prst: Zasouvej do ní prst tak pomalu, aby to trvalo 20 vteřin, a stejně pomalu ho vytahuj. Cíl: pět opakování a ona nesmí tlačit boky proti tobě.|120",
    "Vibrující dlaň: Polož dlaň na její klín a na hřbet ruky přitiskni vibrátor, aby vibrace procházely tvou rukou. Cíl: nechat ji o dlaň otírat, dokud nebude chtít víc.|90",
    "Tajné signály: Domluvte se: jedno stisknutí tvé ruky znamená pomaleji, dvě rychleji, tři silněji. Hlaď ji prsty a řiď se jen jejím mačkáním. Cíl: dvě minuty beze slov.|120",
    "Stehno jako sedlo: Nech ji sednout si obkročmo na tvoje napnuté stehno a otírat se o něj klínem, zatímco jí saješ bradavky. Cíl: aby zrychlila bez pobízení.|90",
    "Led a dlaň: Přejeď jí kostkou ledu po vnitřní straně stehen a krátce přes stydké pysky, pak přilož celou teplou dlaň. Cíl: třikrát vystřídat studenou a teplou, dokud se nezachvěje.",
    "Obě ruce zaměstnané: Jednou rukou ji prsty hladíš na klitorisu, druhou jí vibrátorem pomalu jezdíš po bradavkách. Cíl: dvě minuty nepřestat ani s jednou rukou.|120",
    "Zakázaná zóna: Hlaď ji dvě minuty po celém nahém těle, jen klitoris je zakázaný. Pak mu věnuj jediný pomalý, dlouhý dotek. Cíl: aby se u něj prohnula.|120",
    "Dva polštáře: Podlož jí boky dvěma polštáři, klekni si mezi její nohy a hlaď ji oběma rukama – jednou nahoře na klitorisu, druhou u vstupu. Cíl: najít rytmus, při kterém začne dýchat nahlas.|120",
    "Masáž bodu G: Vsuň do ní dva prsty dlaní nahoru a pohybem „pojď sem“ tlač na přední stěnu. Druhou dlaní jí jemně tlač na podbřišek. Cíl: vydržet v pravidelném rytmu, dokud nedojde nebo neřekne dost.|180",
    "Dirigent: Sedni si do křesla naproti posteli. Ona si lehne a hladí se vibrátorem, ty jí říkáš, kam ho má dát a jak rychle. Cíl: dirigovat ji dvě minuty, pak přijít a převzít vibrátor.|180",
    "Pračka při odstřeďování: Posaď ji nahou na pračku při odstřeďování a hlaď ji prsty, zatímco ji vibrace rozechvívají zespodu. Cíl: dojít k vrcholu dřív, než pračka dotočí.|180",
    "Kluzká těla: Namažte se oba olejem. Lehni si na ni a pomalu po ní klouzej nahoru a dolů, stehno přitisknuté k jejímu klínu. Cíl: dvě minuty klouzání, bez vniknutí.|120",
    "Vibrátor mezi stehny: Ona stojí a sevře mezi stehny vibrátor přitisknutý ke klínu. Ty ji zezadu objímáš, hladíš jí prsa a držíš jí nohy u sebe. Cíl: aby se jí roztřásla kolena.|90",
    "Jeden prst, jedna minuta: Máš k dispozici jen ukazováček a jednu minutu. Cíl: dostat ji co nejblíž k orgasmu jen tímhle prstem.|60",
    "Pírko na klitoris: Ať roztáhne nohy. Přejížděj jí pírkem jen po klitorisu a stydkých pyscích, lehounce. Cíl: aby tě poprosila o skutečný dotek – a pak ho dostane od tvého prstu.|60",
    "Pod stolem: Sedněte si vedle sebe k jídelnímu stolu. Ona je bez kalhotek, ty ji pod stolem hladíš mezi nohama a oba se tváříte, že večeříte. Cíl: udržet kamennou tvář jednu minutu.|60",
    "Dvojitá dlaň: Přilož obě dlaně na její klín, jednu přes druhou, a pomalu s nimi kruž a tlač. Cíl: aby zvedla boky proti tvým dlaním.|60",
    "Neměnné tempo: Hlaď jí klitoris pořád stejným tempem – nezrychluj, nezpomaluj, ať se děje cokoli. Cíl: dovést ji k orgasmu bez jediné změny rytmu.",
    "Plácnutí a pohlazení: Jemně ji plácni dlaní přímo na klín, nech tam ruku ležet a hlaď ji. Opakuj pomalu. Cíl: zjistit, jestli chce silněji, nebo jemněji, a podle toho pokračovat.|60",
    "U zdi v chodbě: Ona stojí nahá zády ke zdi s nohama od sebe. Klekni si bokem k ní a prsty ji hlaď zespodu. Cíl: aby se musela opřít o tvé rameno.|90",
    "Kroužky k bradavkám: Namaž jí prsa olejem a masíruj je kroužky zvenku dovnitř až k bradavkám, které na konci jemně stiskni. Cíl: deset kroužků, stisk – a znovu.|120",
    "Ruka v kalhotách: Když stojí oblečená u linky, přistup zezadu a zajeď jí rukou do kalhot. Prsty ji hlaď, druhou rukou jí drž bradu a líbej ji na krk. Cíl: aby se musela opřít rukama o linku.|90",
    "Palec v puse: Ona ti saje palec a ty jí dvěma prsty druhé ruky hladíš klitoris. Čím víc saje, tím rychleji hladíš. Cíl: tempo určuje jen ona.|90",
    "Spolupráce: Ona si hladí klitoris sama, ty jí hladíš prsa a zasuneš do ní prst. Cíl: sladit se tak, aby dosáhla vrcholu.",
    "Vibrace na hrázi: Přilož jí vibrátor na hráz mezi vagínou a konečníkem a prsty jí hlaď klitoris. Cíl: zjistit, jestli jí vibrace dole zesilují pocity nahoře.|90",
    "Tři minuty něhy: Zatemni pokoj, nech svítit jen lampičku. Pod dekou ji hlaď rukama po celém těle, mezi nohama zatím jen letmo. Cíl: tři minuty něhy – pak do ní zasuň prsty.|180",
    "Počítání vzdechů: Hlaď ji prsty a nahlas počítej její vzdechy. Cíl: dvacet vzdechů – u dvacátého zrychli.",
    "Sevřená stehna: Ona leží na boku s koleny u sebe. Zezadu jí vsuň ruku mezi stehna ke klínu. Cíl: hladit ji, zatímco ona tiskne stehna k sobě.|90",
    "Po směru a proti směru: Hlaď jí klitoris ve směru hodinových ručiček dvacet kroužků, pak proti směru dvacet. Ona vybere, co je lepší. Cíl: tím směrem pokračovat minutu.|120",
    "Vibrátor ve sprše: Pod tekoucí vodou jí přikládej na klitoris vodotěsný vibrátor (když není vodotěsný, použij prsty). Cíl: aby se o tebe musela opřít.|90",
    "Přes ramena: Ona sedí na židli a ty stojíš za ní. Spusť obě ruce přes její ramena dolů – jednu na prsa, druhou mezi nohy. Cíl: aby zaklonila hlavu na tvé břicho.|90",
    "Rychlý start: Máš 30 vteřin na to, abys ji svlékl, a pak 60 vteřin na to, abys ji prsty pořádně rozehřál. Cíl: stihnout obojí.|90",
    "Kalhotky stranou: Ona sedí na gauči v kalhotkách. Odhrň jí je prstem stranou a hlaď ji pod nimi, ale nesundávej je. Cíl: pokračovat, dokud si je nestáhne sama.",
    "Mokré prsty: Hlaď ji mezi nohama, pak jí vlhké prsty přilož ke rtům a nech ji olíznout. Pak pokračuj. Cíl: tři kola.",
    "Přes opěradlo: Ona se přehne přes opěradlo gauče. Zezadu jí zajeď rukou mezi nohy a druhou ji hlaď po zádech. Cíl: aby se sama natlačila na tvou ruku.|120",
    "Dálkové ovládání: Ona si drží vibrátor na klitorisu a ty jí říkáš jen „přitlač“, „povol“, „výš“ a „níž“. Dotknout se jí nesmíš. Cíl: dvě minuty – pak smíš přidat ruku.|120",
    "Prst a dech: Hlaď ji prstem na klitorisu a zároveň na něj střídavě foukej teplý a studený dech. Cíl: dokud nezačne kroutit boky.|60",
    "Zmenšující se trojúhelník: Hlaď ji prsty v trojúhelníku – klitoris, levý stydký pysk, pravý stydký pysk – a zpět. Cíl: trojúhelník postupně zmenšovat, až skončíš jen na klitorisu.|90",
    "Plná výbava: Použij všechno najednou – prsty, oba vibrátory a pírko – na dvě minuty. Cíl: aby tě na konci chytila za zápěstí a řekla „nepřestávej“.|120",
    "Poslední kapka: Když se blíží vrchol, přestaň a přikryj jí klín celou dlaní. Počkej 10 vteřin a pokračuj. Cíl: dvakrát zastavit, potřetí ji nech dojít.",
  ],

  // Úkoly pro ženu – pro potěšení muže
  female: [
    "Olej na celém těle: Svlékni ho donaha a namasíruj mu olejem celé tělo. Cíl: pět minut, při kterých se penisu dotkneš až úplně nakonec.|300",
    "Vibrace přes látku: Přikládej mu vibrátor přes boxerky a jezdi po celé délce nahoru a dolů. Cíl: dvacet cest a boxerky mu nesundat.|90",
    "Jeho ruce za hlavou: Přejížděj mu pírkem po bradavkách, podbřišku a vnitřní straně stehen. Cíl: půldruhé minuty a on nesmí ruce sundat.|90",
    "Celou dlaní: Zajeď mu rukou do boxerek a hlaď ho pomalu jen celou dlaní. Cíl: celá minuta bez jediného sevření prstů.|60",
    "Obě ruce na něm: Posaď ho, stáhni mu boxerky a hlaď ho pomalu oběma rukama naráz. Cíl: každá ruka jiným tempem, a to půldruhé minuty.|90",
    "Zezadu na boku: Lehni si za něj na lžičku a jednou rukou ho hlaď po hrudi, druhou po penisu. Cíl: dvě minuty a obě ruce ve stejném rytmu.|120|lzicka",
    "Mydlinky na něm: Namydli ho a pomalu ho dlaněmi hlaď a omývej – hlavně penis a varlata. Cíl: dvě minuty a nikam nespěchat.|120",
    "Ruka za rukou: Namaž si ruce olejem a přejížděj mu po penisu střídavě jednou a druhou rukou. Cíl: dvacet tahů bez jediné mezery mezi nimi.|90",
    "Mezi jeho koleny: Nech ho sedět na židli, klekni si mezi jeho nohy a hlaď ho po stehnech a varlatech. Cíl: minuta a penisu se ani nedotknout.|60",
    "Nahoře jazyk, dole ruka: Olizuj mu bradavky a přitom ho rukou pomalu hlaď přes boxerky. Cíl: celá minuta a obě věci ve stejném tempu.|60",
    "Tři doteky poslepu: Zavaž mu oči a střídej na jeho těle pírko, prsty a vibrátor. Cíl: deset střídání a ať u každého uhodne, co to bylo.|120",
    "Dívá se v zrcadle: Stoupni si za něj k zrcadlu, obejmi ho a obě ruce mu dej na penis. Cíl: nepřestat, dokud neuhne pohledem.|90",
    "Noha po jeho stehně: Sedni si nahá na linku a hlaď ho nohou po stehně, zatímco se dívá. Cíl: celá minuta a nedovolit mu se dotknout.|60",
    "Varlata a krk: Masíruj mu varlata dlaní jemně a pomalu, zatímco ho líbáš na krk. Cíl: celá minuta a ani jednou nepřitlačit.|60",
    "Prsa po jeho hrudi: Lehni si na něj nahá a pomalu se o něj otírej prsy. Cíl: dvacet pomalých pohybů a rukama se nikde neopřít.|60",
    "Vibrace na hrázi: Přikládej mu vibrátor na hráz mezi varlaty a konečníkem. Cíl: vyzkoušet tři stupně a u toho nejlepšího zůstat.|60",
    "Jen přes kalhoty: Hlaď ho přes kalhoty pomalu celou dlaní. Cíl: nerozepnout mu je, dokud mu úplně neztvrdne.|120",
    "Mezi prsy: Posaď ho do křesla, klekni si před něj a sevři jeho penis mezi prsy. Cíl: dvacet pomalých pohybů a ruce si nechat na jeho stehnech.|60",
    "Od kořene ke špičce: Nech ho ležet na zádech a vibrátorem mu jezdi po penisu od kořene až ke špičce. Cíl: dvacet cest a ani jedna rychlejší.|60",
    "Stisknout a olíznout: Jemně mu stiskni bradavky mezi prsty a pak je hned olízni. Cíl: pět kol a pokaždé stisknout o kousek pevněji.|45",
    "Kroutivý pohyb: Rozetři si lubrikant na dlaně a hlaď ho pomalu kroutivým pohybem. Cíl: půldruhé minuty jednoho tempa bez jediného zrychlení.|90",
    "Zezadu na kolenou: Nech ho klečet na posteli, stoupni si za něj a hlaď ho zezadu po penisu a varlatech. Cíl: půldruhé minuty a on se nesmí otočit.|90",
    "Pod tekoucí vodou: Stoupni si za něj ve sprše, přitiskni se k němu a hlaď ho po penisu. Cíl: dvě minuty a ani jednou nepustit.|120",
    "Ledem a pak ústy: Přejeď mu kostkou ledu po bradavkách a hned je zahřej ústy. Cíl: pět střídání a mezi nimi vždy tři vteřiny nic.|90",
    "Na klíně zády: Posaď se mu na klín nahá zády k němu a pomalu se o něj otírej. Cíl: dvacet pohybů a do sebe ho nepustit.|60|klin_zady",
    "Jeho ruce nahoře: Dej mu ruce nad hlavu s tím, že je nesmí sundat, a hlaď ho po celém těle. Cíl: zdržet se všude, kde vzdychne, aspoň deset vteřin.|120",
    "Polibek a ruka: Líbej ho na rty a zároveň mu pomalu hlaď penis. Cíl: nepřerušit polibek, ani když zrychlíš.|90",
    "Opřený o stůl: Nech ho opřít se rukama o stůl a zezadu mu zajeď rukou mezi nohy. Cíl: celá minuta a on se nesmí narovnat.|60",
    "Pírko na něm: Šimrej ho pírkem po penisu a varlatech, hodně zlehka. Cíl: vydržet u toho tři čtvrtě minuty a nepřitlačit.|45",
    "Dva vibrátory: Vezmi oba vibrátory a přilož mu je z obou stran na penis. Cíl: tři čtvrtě minuty a postupně přidávat stupeň.|45",
    "Dívá se a nesmí: Svlékni se donaha, lehni si a hlaď se, zatímco se na tebe dívá. Cíl: dvě minuty a on se tě nesmí dotknout.|120",
    "Boxerky zuby: Stáhni mu boxerky jen zuby, ruce máš celou dobu za zády. Cíl: dostat je až ke kotníkům bez jediného doteku rukou.|120",
    "Jen hřbetem ruky: Namaž mu olejem vnitřní stranu stehen a hřbetem ruky se občas otři o jeho varlata. Cíl: desetkrát a pokaždé jakoby náhodou.|90",
    "Polibek přes boxerky: Opři ho o zeď, klekni si a polib ho přes boxerky. Cíl: deset polibků a boxerky mu nesundat.|90|zed",
    "Stejný rytmus: Hlaď ho jednou rukou po penisu a druhou po bradavce přesně ve stejném rytmu. Cíl: půldruhé minuty a rytmus ani jednou nesplést.|90",
    "Jen špička: Hlaď ho rukou jen po špičce, pomalu dokola a s lubrikantem. Cíl: celá minuta a níž nesjet ani jednou.|60",
    "Až k sobě, ale ne dovnitř: Posaď se nahá na stůl, přitáhni si ho mezi nohy a hlaď ho. Cíl: půldruhé minuty a do sebe ho nepustit.|90",
    "Olejová záda: Namaž si prsa olejem a otírej se jimi o jeho záda, když leží na břiše. Cíl: projet ho takhle třikrát od ramen ke kříži.|90",
    "Když zrychlí, zpomal ty: Nech ho ležet na zádech a hlaď ho pomalu. Cíl: jakmile se začne hýbat proti tvé ruce, zpomalit – a tak třikrát po sobě.|120",
    "Chyť jeho penis a pomalu si ho přejížděj po bradavkách.|45",
    "Zavaž mu oči a dotýkej se ho jen vibrátorem. Ať hádá, kam ho přiložíš příště.|90",
    "Nech ho sedět v křesle a sedni si mu nahá obkročmo na stehno. Pomalu se o něj otírej.|90",
    "Masíruj mu zadek olejem, pomalu a pevně. Prsty občas sklouzni mezi nohy k varlatům.|90",
    "Stoupni si za něj ve sprše a jednou rukou mu hlaď hruď, druhou penis.|90",
    "Lehni si vedle něj a hlaď ho, ale nech ho, ať si sám řekne tempo – pomaleji, rychleji, silněji.|120",
    "Nech ho ležet na zádech. Klekni si nad něj a jen konečky prstů ho hlaď od kolen až ke krku, pořád dokola.|90",
    "Stáhni mu boxerky jen ke kolenům a pomalu ho hlaď po celé délce.|60",
    "Hlaď ho rukou přes boxerky, pak pod nimi, pak zase přes ně. Střídej to.|90",
    "Nahá se přitiskni k jeho zádům, obejmi ho a veď jeho ruku po jeho vlastním penisu.|60",
    "Hlaď ho jednou rukou po penisu a druhou mu jemně masíruj varlata.|90",
    "Vlna v bocích: Lehni si nahá na břicho, nech ho dívat se a pomalu se vlň boky. Cíl: deset vln a teprve pak ho zavolat k sobě.|120",
    "Na chodbě ho opři zády o zeď, klekni si a hlaď ho rukou, zatímco se ti dívá do očí.|60",
    "Nech ho sedět na gauči. Posaď se mezi jeho nohy zády k němu a zajeď rukama za sebe na jeho penis.|60",
    "Přitlač vibrátor na jeho podbřišek těsně nad penisem a druhou rukou ho hlaď.|60",
    "Pírkem mu přejížděj po zadku a mezi hýžděmi, zlehka.|45",
    "Svlékni se před ním donaha a řekni mu, ať si vybere jedno místo na tvém těle, kterého se smí dotknout.|60",
    "Přejeď mu jazykem po břiše od hrudníku až k lemu boxerek – a zase zpátky.|60",
    "Nech ho ležet na zádech. Klekni si mu mezi nohy a otírej se prsy o jeho penis.|60",
    "Rozetři mu olej po hrudi a břiše a lehni si na něj, ať kloužete tělem o tělo.|60",
    "Hlaď ho rukou, dokud nezačne těžce dýchat – pak přestaň, polib ho a začni znovu.",
    "Obkroč ho, když leží, a pomalu se o něj otírej klínem přes kalhotky.|90",
    "Dej mu ruce za hlavu a jednou rukou mu je podrž. Druhou ho hlaď po penisu.|90",
    "Nech ho ležet na boku a zezadu mu vsuň ruku mezi nohy k varlatům a penisu.|90",
    "Vibrátorem přes boxerky mu kresli pomalé osmičky kolem špičky.|60",
    "Masíruj mu chodidla olejem a pomalu stoupej výš až k jeho klínu. Zastav se těsně před ním.|120",
    "Stiskni mu penis u kořene a pomalu ho hlaď druhou rukou ke špičce.|60",
    "Nech ho klečet na gauči opřeného o opěradlo a zezadu ho hlaď rukou.|90",
    "Přilož si vibrátor k prstům a teprve těmi vibrujícími prsty ho hlaď.|60",
    "Nahá se před ním protáhni na koberci v obýváku – pomalu, jako kočka. Dotknout se tě nesmí.|60",
    "Líbej ho po krku a hrudi a zároveň ho hlaď po stehnech – pokaždé o kousek blíž.|90",
    "Na posteli ho nech ležet na zádech s rukama podél těla. Dotknout se tě nesmí – ty ho hladíš, kde chceš.|120",
    "Polož mu vibrátor přes boxerky na penis a nech ho tam ležet. Ty ho zatím líbej na rty.|60",
    "Klekni si na postel, ať máš zadeček u jeho obličeje, a nech ho, ať se dívá. Mezitím ho hlaď rukou.|60",
    "Stáhni ho k okraji postele, klekni si na zem a pomalu ho hlaď oběma rukama.|90",
    "Jemně mu přejížděj nehty po vnitřní straně stehen a přes varlata.|45",
    "V kuchyni ho opři o linku a zezadu mu rukou zajeď do kalhot.|60",
    "Obkroč ho, když leží, a přejížděj mu vibrátorem po celém těle. Kde zasténá, tam se zdrž.|90",
    "Namaž si prsa olejem, stiskni je k sobě a nech ho, ať mezi nimi klouže penisem.|90",
    "Hlaď ho, jak nejpomaleji umíš. On nesmí přirážet.|90",
    "Hlaď ho jen konečky prstů pod špičkou, sotva znatelně.|60",
    "Posaď ho na gauč. Jedním vibrátorem mu dráždi varlata, druhým bradavky.|60",
    "Pomalu ke kotníkům: Otoč se k němu zády jen v kalhotkách, předkloň se a stahuj si je až ke kotníkům. Cíl: ať to trvá celou minutu.|60",
    "Zavaž mu oči, svlékni ho a hlaď ho všude – kromě penisu. Až tě poprosí, dotkni se ho.",
    "Masíruj mu hráz prsty v pomalých kolečkách, zatímco ho druhou rukou hladíš po penisu.|90",
    "Nech ho stát nahého v obýváku a obcházej ho. Pokaždé, když jsi za ním, přejeď mu rukou mezi nohy.|60",
    "Stoupni si s ním před zrcadlo. Ty ho hladíš, on se dívá na tebe i na sebe.|90",
    "Posaď se na postel, nohy dej kolem jeho pasu a hlaď ho pomalu rukama mezi svými stehny.|90",
    "Ve vaně nebo sprše mu pusť proud teplé vody na varlata a penis.|60",
    "Vezmi jeho ruku, polož si ji na prsa a ty ho zatím hlaď po penisu – oba stejným tempem.|90",
    "Namaž mu penis lubrikantem a jen ho pomalu mačkej a povoluj v dlani, bez pohybu.|60",
    "Lehni si nahá na něj a otírej se o něj, dokud nezačne sám tlačit boky proti tobě. Pak slez.",
    "Obejmi mu penis oběma rukama nad sebou a pomalu jimi otáčej proti sobě.|60",
    "Pozvání prstem: Stoupni si nahá do dveří, pozvi ho prstem a jakmile přijde, zajeď mu rukou do kalhot. Cíl: nepromluvit ani slovo.|60",
    "Hlaď ho rukou a zároveň mu jazykem kresli kolečka kolem bradavky.|90",
    "Nech ho ležet na zádech a posaď se nahá vedle jeho hlavy. Hlaď ho po penisu a nech ho, ať tě hladí po stehně.|90",
    "Namaž mu olejem zadek a stehna a masíruj je tak, aby se tvoje prsty pořád vracely k varlatům.|90",
    "Vedený do ložnice: Vezmi ho za penis a pomalu ho veď za sebou do ložnice. Cíl: nepustit ho celou cestu a ani jednou se neotočit.|60",
    "Zakaž mu hýbat se. Hlaď ho, a kdyby se pohnul, začni znovu od kolen.|90",
    "Obleč si jen jeho košili nebo triko, sedni si mu na klín a hlaď ho rukou pod sebou.|60",
    "Otírej se nahými prsy o jeho obličej a hlaď ho přitom po penisu.|45",
    "Klekni si za něj na posteli, přitiskni prsa k jeho zádům a obě ruce mu dej mezi nohy.|90",
    "Hlaď ho kolem penisu – břicho, třísla, stehna, varlata – ale penisu samotného se nedotkni.|60",
    "Nech ho sedět na židli v kuchyni. Stoupni si nahá před něj a nech ho, ať si tě prohlíží zblízka – dotknout se nesmí.|45",
    "Pírkem ho šimrej na špičce penisu a hned na ni foukni.|30",
    "Přitáhnout si ho: Pomalu mu stiskni zadek oběma rukama a přitáhni si jeho klín ke svému. Cíl: pět přitažení a pokaždé pevněji.|60",
    "Rozetři si lubrikant mezi stehny a nech ho, ať mezi nimi klouže – bez průniku.|90",
    "Hlaď ho rukou a přitom mu do ucha šeptej, jak je tvrdý a jak se ti to líbí.|60",
    "Posaď se na pračku, přitáhni si ho mezi nohy a hlaď ho, zatímco tě líbá.|60",
    "Přilož mu k varlatům vibrátor na nejnižší stupeň a rukou ho hlaď po penisu.|60",
    "Lehni si vedle něj a hlaď ho tak dlouho, dokud neřekne „prosím“. Pak ještě chvíli.",
    "Namaž mu olejem hruď a pomalu ji masíruj, dokud se mu nezačnou chvět boky.|90",
    "Sedni si mu jen v kalhotkách na pár vteřin na obličej, pak slez a pokračuj rukou na jeho penisu.|60",
    "Klekni si na gauč a otírej se zadečkem o jeho klín, zatímco sedí.|60",

    // Karty s cílem
    "Tři tempa: Hlaď mu penis rukou třemi rychlostmi – pomalu, středně a rychle, každou 20 vteřin. Ať řekne, která je nejlepší. Cíl: v ní pokračovat, dokud nezačne sténat.|90",
    "Vibrace po těle: Přikládej mu vibrátor na bradavky, podbřišek, třísla, vnitřní strany stehen a varlata – každé místo 10 vteřin. Cíl: uzdičku pod špičkou nech až úplně nakonec.|90",
    "Lekce od něj: Ať ti na sobě ukáže, jak se rád hladí – sevření, rychlost, místo. Pak jeho ruku vystřídáš ty. Cíl: aby řekl, že to děláš lépe než on.|180",
    "Teploměr: Hlaď ho rukou a on každých 15 vteřin řekne číslo od 1 do 10, jak blízko je vrcholu. Cíl: dostat ho na devítku – pak přestaň a polib ho.|180",
    "Detailní prohlídka: Posaď ho na gauč, roztáhni mu nohy a zblízka si prohlížej jeho penis. Popisuj, co vidíš a co s ním chceš dělat. Pak se ho dotkni jedním prstem. Cíl: aby mu ztvrdl jen z tvých slov.|60",
    "Proud na varlata: Ve sprše ho zezadu obejmi a jemným proudem mu přejížděj po varlatech a penisu. Cíl: najít úhel, při kterém se nahlas nadechne.|90",
    "Kroužek z prstů: Udělej z palce a ukazováčku kroužek, nasaď ho u kořene a pomalu s ním jezdi po celé délce. Na špičce kroužek vždy trochu utáhni. Cíl: dvacet tahů.|90",
    "Pírko proti vibrátoru: V jedné ruce pírko, ve druhé vibrátor. Pírkem po hrudi, vibrátorem po stehnech. Po minutě je prohoď. Cíl: aby tě poprosil o vibrátor na penis.|120",
    "Olejová masáž celého těla: Namaž ho olejem a masíruj dlouhými tahy od kotníků přes penis až k hrudi. Cíl: dvacet tahů, každý pomalejší než předchozí.|180",
    "Ruce nahoře: On leží s rukama nad hlavou a ty mu hladíš penis. Když ruce sundá, 10 vteřin nic nedostane. Cíl: aby vydržel dvě minuty.|120",
    "Mokré boxerky: Hlaď ho přes boxerky, dokud na nich neuvidíš vlhkou skvrnu. Pak mu je stáhni zuby. Cíl: boxerky dole bez rukou.",
    "Zezadu u linky: On se opře o kuchyňskou linku. Přitiskni se k jeho zádům a zezadu mu jednou rukou hlaď penis, druhou varlata. Cíl: aby se musel opřít rukama o linku.|90",
    "Dva rytmy: Jednou rukou mu pomalu hlaď penis, druhou rychle a jemně varlata. Cíl: udržet rozdílný rytmus dvě minuty.|120",
    "Jeho bradavky: Věnuj se jen jeho bradavkám – prsty, jazykem, vibrátorem a lehkým štípnutím. Cíl: zjistit, co ho vzruší nejvíc, a u toho zůstat.|120",
    "Pauzy s pohledem: Hlaď mu penis 30 vteřin, pak 10 vteřin nic – jen se mu dívej do očí. Opakuj. Cíl: aby tě při pauze chytil za ruku a vrátil ji zpátky.|180",
    "Před zrcadlem: Posaď ho před zrcadlo, klekni si za něj, obejmi ho a oběma rukama ho hlaď. Cíl: nesmí zavřít oči ani uhnout pohledem.|120",
    "Desetivteřinový tah: Jeden tah rukou od kořene ke špičce trvá 10 vteřin. Cíl: deset takových tahů a on nesmí přirážet.|120",
    "Vibrující dlaň: Obejmi mu penis dlaní a na hřbet ruky přitiskni vibrátor. Cíl: držet, dokud nezačne sám přirážet do tvé ruky.|90",
    "Signály rukou: Domluvte se: jedno stisknutí znamená pomaleji, dvě rychleji, tři silněji. Hlaď ho a řiď se jen jeho mačkáním. Cíl: dvě minuty beze slov.|120",
    "Na jeho stehně: Sedni si nahá obkročmo na jeho stehno a otírej se o něj klínem, zatímco mu rukou hladíš penis. Cíl: udržet stejný rytmus klínem i rukou.|90",
    "Studená a teplá: Přejeď mu kostkou ledu po vnitřní straně stehen a krátce po varlatech, pak přilož teplou dlaň. Cíl: třikrát vystřídat, dokud se nezachvěje.",
    "Ruka a vibrátor: Jednou rukou mu hlaď penis, druhou mu vibrátorem přejížděj po bradavkách. Cíl: dvě minuty nepřestat ani s jedním.|120",
    "Zakázaný penis: Hlaď ho dvě minuty po celém nahém těle, jen penis je zakázaný. Pak mu dej jediný dlouhý tah. Cíl: aby se u něj prohnul.|120",
    "Polštář pod boky: Podlož mu boky polštářem, klekni si mezi jeho nohy a hlaď ho oběma rukama – jednou penis, druhou mu masíruj hráz. Cíl: najít rytmus, při kterém začne nahlas dýchat.|120",
    "Hráz pod palci: Přitlač dva prsty na jeho hráz a jemně kruž, zatímco ho druhou rukou pomalu hladíš po penisu. Cíl: zjistit, jaký tlak mu dělá nejlíp.|120",
    "Dirigentka: Sedni si do křesla naproti posteli. On se hladí sám a ty mu říkáš, jak rychle a kde. Cíl: dirigovat ho dvě minuty, pak přijít a převzít to.|180",
    "Pračka pro něj: Posaď ho na pračku při odstřeďování, stoupni si mezi jeho kolena a hlaď ho rukou. Cíl: aby se udělal dřív, než pračka dotočí.",
    "Klouzání: Namažte se oba olejem a lehni si na něj. Klouzej po něm nahoru a dolů, jeho penis ti klouže po břiše. Cíl: dvě minuty, bez vniknutí.|120",
    "Mezi stehny: Stoupni si k němu zády, namaž si vnitřní strany stehen olejem a sevři mezi nimi jeho penis. Pohybuj boky. Cíl: bez vniknutí ho dostat co nejblíž k vrcholu.|90",
    "Jedna ruka, jedna minuta: Máš jednu ruku a jednu minutu. Cíl: dostat ho co nejblíž k orgasmu.|60",
    "Pírko na špičku: Přejížděj mu pírkem jen po špičce a uzdičce. Cíl: aby tě poprosil o skutečný dotek.|60",
    "Večeře s překvapením: Sedněte si vedle sebe k jídelnímu stolu. Rozepni mu pod stolem kalhoty a hlaď ho, zatímco se oba tváříte, že večeříte. Cíl: aby jako první nevydržel s vážnou tváří on.|60",
    "Pumpa: Obejmi jeho penis dlaní a jen ho rytmicky stiskni a povol, bez pohybu nahoru a dolů. Cíl: aby začal přirážet sám.|60",
    "Stálé tempo: Hlaď ho pořád stejným tempem a nezrychluj, ať se děje cokoli. Cíl: dovést ho k orgasmu bez jediné změny rytmu.",
    "Varlata v dlani: Vezmi mu varlata do dlaně, jemně je potěžkej a masíruj prsty, zatímco ho líbáš na krk. Cíl: zjistit, jak silný dotek má rád.|60",
    "Opřený o zeď: Postav ho nahého zády ke zdi v chodbě. Klekni si bokem k němu a hlaď ho oběma rukama. Cíl: aby se musel opřít hlavou o zeď.|90",
    "Otvírání sklenice: S lubrikantem mu otáčej dlaní kolem špičky, jako bys otevírala sklenici. Cíl: deset otoček, pak jeden dlouhý tah dolů – a znovu.|90",
    "Ruka v kalhotách: Když stojí oblečený u linky, přistup zezadu, zajeď mu rukou do kalhot a hlaď ho. Druhou rukou mu drž bradu a líbej ho na krk. Cíl: aby se musel opřít o linku.|90",
    "Sání palce: Nech ho sát tvůj palec, zatímco mu druhou rukou hladíš penis. Čím víc saje, tím rychleji hladíš. Cíl: tempo si určuje on.|90",
    "Týmová práce: On se hladí sám a ty mu hladíš varlata a bradavky. Cíl: sladit se, dokud se neudělá.",
    "Vibrace na hrázi: On leží na zádech s pokrčenými koleny. Přilož mu vibrátor na hráz a rukou ho hlaď po penisu. Cíl: zjistit, jestli mu vibrace dole zesilují pocity.|90",
    "Něha pod dekou: Zatemni pokoj, nech jen lampičku. Pod dekou ho hlaď rukama po celém těle, penis zatím jen letmo. Cíl: tři minuty něhy – pak ho pevně chyť.|180",
    "Dvacet vzdechů: Hlaď ho a nahlas počítej jeho vzdechy. Cíl: dvacet vzdechů – u dvacátého zrychli.",
    "Mezi prsy: Namaž si prsa olejem, klekni si mezi jeho nohy a sevři mezi nimi jeho penis. Pohybuj se nahoru a dolů. Cíl: dvě minuty bez použití pusy.|120",
    "Směr hodin: Kruž mu dlaní kolem špičky dvacetkrát po směru hodin, pak dvacetkrát proti. Ať vybere. Cíl: tím směrem pokračuj minutu.|120",
    "Mýdlové ruce: Ve sprše si napěň ruce a hlaď ho pomalu po penisu a varlatech, zatímco na něj teče voda. Cíl: aby se o tebe musel opřít.|90",
    "Za židlí: On sedí na židli, ty stojíš za ním. Spusť mu ruce přes ramena dolů – jednu na hruď, druhou na penis. Cíl: aby zaklonil hlavu na tvé břicho.|90",
    "Rychlá rozcvička: Máš 30 vteřin na to, abys ho svlékla, a 60 vteřin, abys ho rukou dovedla do plné erekce. Cíl: stihnout obojí.|90",
    "Boxerky zůstávají: On sedí na gauči v boxerkách. Vytáhni mu penis rozparkem nebo nohavicí a hlaď ho, ale boxerky mu nesundávej. Cíl: pokračovat, dokud si je nesundá sám.",
    "Olíznutá ruka: Hlaď ho, pak si před ním pomalu olízni dlaň a pokračuj vlhkou rukou. Cíl: tři kola, pokaždé s pohledem do očí.",
    "Přes opěradlo pro něj: Ať klekne na gauč a opře se o opěradlo. Zezadu mu zajeď rukou mezi nohy k penisu a druhou ho hlaď po zádech. Cíl: aby začal přirážet do tvé ruky.|120",
    "Dálkové ovládání: On se hladí sám a ty mu říkáš jen „rychleji“, „pomaleji“, „stiskni“ a „povol“. Dotknout se ho nesmíš. Cíl: dvě minuty, pak přidáš svou ruku.|120",
    "Dech na špičku: Hlaď ho rukou a na špičku mu střídavě foukej teplý a studený dech. Cíl: dokud nezačne kroutit boky.|60",
    "Šplhání po laně: Obejmi mu penis oběma rukama nad sebou a posouvej je střídavě, jako bys šplhala po laně. Cíl: 30 vteřin bez přerušení, pak zpomal.|60",
    "Všechno najednou: Použij ruce, oba vibrátory i pírko na dvě minuty. Cíl: aby tě na konci chytil za zápěstí a řekl „nepřestávej“.|120",
    "Stisk u kořene: Když se blíží vrchol, pevně ho stiskni u kořene a zastav se. Počkej 10 vteřin a pokračuj. Cíl: dvakrát zastavit, potřetí ho nech dojít.",
  ],
});
