// Kategorie 2 – Smyslné doteky (dávka b)
// Témata: celotělová olejová masáž, bradavky a hrudník, klouzání tělo na tělo.
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 2,

  male: [
    "Naolejuj si dlaně a jeď jí od kotníků až k zátylku jedním nepřerušeným tahem. Třikrát.|180|masaz_zada",
    "Masíruj jí prsa celými dlaněmi v kruzích a bradavek se dotkni až úplně nakonec.|180|vedle_ona_lezi",
    "Jen bradavky: Tři minuty se věnuj výhradně jejím bradavkám – prsty, jazykem, dechem. Nikam jinam. Cíl: ať se prohne v zádech.|180|vedle_ona_lezi",
    "Vezmi její bradavku mezi rty a jemně saj. Druhou zatím dráždi palcem.|120|vedle_ona_lezi",
    "Naolejuj si celý hrudník a klouzej po ní tělem odshora dolů.|180|propletene",
    "Polož ji na břicho, sedni si jí na stehna a rozmasíruj jí celá záda dlaněmi i předloktím.|300|masaz_zada",
    "Masíruj jí boky a zadeček tak, jako bys ji chtěl uvolnit, ne vzrušit. Vydrž u toho.|240|masaz_zada",
    "Zezadu jí obejmi hrudník a jen ho zlehka svírej a pouštěj do rytmu jejího dechu.|120|stoje_zezadu",
    "Kroužky kolem: Krouži kolem její bradavky prstem a postupně se zmenšuj. Do středu se dostaneš až po minutě. Cíl: co nejpomalejší spirála.|120|vedle_ona_lezi",
    "Lehni si na ni celým tělem a jenom se pomalu pohybuj. Ruce mají volno.|180|propletene",
    "Masíruj jí vnitřní stranu stehen dlaněmi nahoru a dolů a pokaždé se zastav kousek před cílem.|180|vedle_ona_lezi",
    "Naolejuj jí záda a pak po nich klouzej vlastním hrudníkem tam a zpátky.|180|masaz_zada",
    "Vezmi jí obě prsa do dlaní a drž je. Nic nedělej, jen je drž.|60|stoje_zezadu",
    "Olizuj jí bradavky střídavě a mezi tím na ně foukej.|180|vedle_ona_lezi",
    "Naolejuj jí nohy od kotníků nahoru a nech ruce doputovat až ke slabinám.|240|vedle_ona_lezi",
    "Ruce a nic víc: Dvě minuty se jí smíš dotýkat jen dlaněmi, nikdy prsty. Cíl: velké, pomalé tahy.|120|masaz_zada",
    "Masíruj jí ramena a při každém tahu sjeď o kousek níž, až se dostaneš k prsům.|240|masaz_vsede",
    "Klouzej po ní naolejovaným tělem, ale nikdy nepoužij ruce.|180|propletene",
    "Polož jí hlavu na hrudník a poslouchej, jak se jí zrychluje tep, zatímco ji hladíš.|120|vedle_ona_lezi",
    "Jemně jí přejížděj nehty po prsou a břiše. Tak lehce, ať to spíš tuší, než cítí.|120|vedle_ona_lezi",
    "Naolejovaná záda: Nalij jí olej mezi lopatky a nech ho stéct. Pak ho rozetři až ke kříži. Cíl: nepoužít víc než dvě dlaně oleje.|180|masaz_zada",
    "Masíruj jí podbřišek dlaní v kruzích a druhou rukou jí drž ruku.|180|vedle_ona_lezi",
    "Hlaď ji po celém těle, ale změň tlak pokaždé, když vydechne.|180|vedle_ona_lezi",
    "Sedni si za ni, obejmi ji a dlaněmi jí pomalu přejížděj od klíčních kostí k pasu.|180|klin_podlaha",
    "Prsa a jazyk: Střídej dlaň a jazyk na jejích prsou tak, aby nikdy nevěděla, co přijde. Cíl: vydržet celou dobu jen u prsou.|240|vedle_ona_lezi",
    "Masíruj jí stehna zezadu, tam, kde přecházejí v zadeček. Silně a pomalu.|180|masaz_zada",
    "Vezmi si olej a masíruj jí celé tělo tak, aby se ti nakonec pod rukama úplně poddala.|300|masaz_zada",
    "Dlaněmi jí projeď od kolen po ramena a zpátky. Jeden tah, jeden nádech.|120|vedle_ona_lezi",
    "Zezadu jí zajeď rukama pod tričko a hlaď jí břicho a žebra.|120|stoje_zezadu",
    "Pomalu, pak rychle: Minutu ji hlaď co nejpomaleji, minutu naopak rychle a pevně. Cíl: ať sama řekne, co chce.|120|masaz_zada",
    "Lehni si na ni a nech se od ní obejmout nohama. Jen se na sebe tiskněte.|120|propletene",
    "Masíruj jí prsa zespoda nahoru, jako bys je nadzvedával. Bradavky nechej být.|180|vedle_ona_lezi",
    "Naolejuj si předloktí a jeď jí jimi po zádech. Je to úplně jiný pocit než dlaně.|180|masaz_zada",
    "Kousni ji zlehka do ramene a pak to místo dlouho olizuj.|90|stoje_zezadu",
    "Hlaď ji jednou rukou po hrudníku a druhou po zádech současně.|120|vedle_ona_lezi",
    "Dva prsty: Celý úkol se jí smíš dotýkat jen dvěma prsty. Vyber si, kterými. Cíl: dokázat, že stačí.|180|vedle_ona_lezi",
    "Masíruj jí krk a hrudní kost směrem dolů, jako bys jí uvolňoval dech.|180|vedle_ona_lezi",
    "Naolejuj jí zadeček a hněť ho oběma rukama, dokud nezvedne boky.|180|masaz_zada",
    "Polož jí dlaň na hrudník a druhou na podbřišek a jen tak vydrž.|90|vedle_ona_lezi",
    "Vezmi ji do náruče zezadu a hlaď jí prsa přes tričko tak dlouho, až si ho sundá.|180|stoje_zezadu",
    "Olej a dech: Naolejuj jí břicho a sleduj, jak se pod tvou dlaní zvedá a klesá. Přizpůsob se jejímu dechu. Cíl: nedělat nic jiného.|120|vedle_ona_lezi",
    "Masíruj jí ruce až po ramena a pak sjeď na klíční kosti.|180|masaz_vsede",
    "Sáhni jí zezadu pod podprsenku a hlaď jí prsa, aniž bys ji sundal.|120|stoje_zezadu",
    "Přejeď jí jazykem od pupíku nahoru mezi prsy až ke krku.|90|vedle_ona_lezi",
    "Masíruj jí kříž oběma palci, zatímco leží na břiše a ty sedíš vedle.|180|masaz_zada",
    "Tři tempa: Hlaď ji nejdřív konečky prstů, pak celou dlaní, pak hřbetem ruky. Každé dvě minuty. Cíl: zeptat se, které bylo nejlepší.|300|vedle_ona_lezi",
    "Lehni si k ní na bok a jednou rukou jí zkoumej celé tělo, jako bys ho neznal.|240|lzicka",
    "Naolejuj jí prsa a klouzej po nich dlaněmi ze stran ke středu.|180|vedle_ona_lezi",
    "Hlaď jí vnitřní stranu paží a podpaží. Je to citlivější, než čeká.|120|vedle_ona_lezi",
    "Masíruj jí šíji jednou rukou a druhou jí drž čelo. Ať se opře.|120|masaz_vsede",
    "Bez konce: Hlaď ji po celém těle tak, aby ruka nikdy neopustila kůži. Pět minut. Cíl: ani jedno přerušení.|300|masaz_zada",
    "Jazykem jí obkresli obě bradavky a pak na ně foukej, dokud neztvrdnou.|120|vedle_ona_lezi",
    "Klouzej po jejích naolejovaných zádech pánví. Pomalu a beze spěchu.|180|na_brise",
    "Masíruj jí boky palci v kruzích a postupuj směrem k tříslům.|180|vedle_ona_lezi",
    "Dej jí ruce na prsa a nech je tam ležet, zatímco ji líbáš na ústa.|90|misionar",
    "Hlaď ji po zádech tak dlouho, dokud jí nezpomalí dech.|240|masaz_zada",
    "Mapa citlivosti: Projdi jí celé tělo a hledej tři nejcitlivější místa. Ona je ohodnotí od jedné do desíti. Cíl: najít aspoň jednu desítku.|300|vedle_ona_lezi",
    "Naolejuj si ruce a hlaď jí zároveň prsa i podbřišek. Mezi tím nikam.|180|vedle_ona_lezi",
    "Lehni si za ni a přes rameno jí hlaď hrudník. Do ucha jí u toho dýchej.|180|lzicka",
    "Masíruj jí lopatky a mezižeberní prostory. Málokdo tam sahá.|180|masaz_zada",
    "Sedni si jí obkročmo na stehna a hněť jí zadeček oběma rukama.|180|masaz_zada",
    "Pomalu jí sjížděj rukou od krku k pupíku a pokaždé se zastav o kousek níž.|180|vedle_ona_lezi",
    "Jedna ruka: Celý úkol máš k dispozici jen jednu ruku. Druhou drž za zády. Cíl: ať jí to stačí.|240|vedle_ona_lezi",
    "Naolejuj jí chodidla a masíruj je tak dlouho, až úplně změkne.|180|masaz_chodidla",
    "Olizuj jí kůži pod prsy a po stranách hrudníku. Bradavek se nedotkni.|180|vedle_ona_lezi",
    "Hlaď ji dlaní po zadečku a stehnech v jednom velkém kruhu dokola.|180|masaz_zada",
    "Masíruj jí ramena zezadu, zatímco sedí, a pomalu jí sundávej ramínka.|180|masaz_vsede",
    "Přitiskni si ji zády k hrudníku a hlaď jí celé tělo shora dolů.|180|stoje_zezadu",
    "Tři minuty na prsa: Celé tři minuty se věnuj jen jejím prsům. Nic pod pasem. Cíl: ať si stáhne tvoji ruku níž sama.|180|vedle_ona_lezi",
    "Masíruj jí bříško nad kalhotkami a lem občas jen tak přejeď.|180|vedle_ona_lezi",
    "Klouzej jí naolejovanými dlaněmi po bocích, jako bys jí kreslil přesýpací hodiny.|120|stoje_zezadu",
    "Lehni si na záda a nech ji, ať si lehne na tebe. Hlaď ji po celém těle.|240|propletene",
    "Vezmi jí prsa zespoda do dlaní a jazykem přejížděj od jednoho ke druhému.|180|vedle_ona_lezi",
    "Masíruj jí krční svaly palci a zbytkem dlaně jí drž hlavu.|120|masaz_vsede",
    "Bez rukou: Klouzej po ní jen naolejovaným tělem – hrudníkem, stehny, břichem. Ruce máš za zády. Cíl: neopřít se ani jednou.|180|propletene",
    "Hlaď jí kůži za koleny a na vnitřní straně stehen. Postupně výš.|180|vedle_ona_lezi",
    "Masíruj jí celou přední stranu těla dlaněmi, od ramen po kotníky.|300|vedle_ona_lezi",
    "Nech ji ležet na boku a hlaď jí bok od podpaží po stehno. Jeden dlouhý tah.|120|lzicka",
    "Naolejuj si břicho a přitiskni se k jejím zádům. Pak se pomalu pohybuj.|180|lzicka",
    "Kousni ji zlehka do zadečku a pak to místo pohlaď dlaní.|60|masaz_zada",
    "Deset kruhů: Uděláš jí na zádech deset velkých kruhů dlaněmi. Ona počítá. Cíl: každý kruh pomalejší než předchozí.|180|masaz_zada",
    "Masíruj jí tříselné rýhy palci. Blízko, ale ne přímo.|180|vedle_ona_lezi",
    "Polož jí ruce na prsa a mezitím ji líbej na krk tak dlouho, až se začne kroutit.|180|stoje_zezadu",
    "Hlaď ji po celém těle a pokaždé, když vydechne, přitlač.|180|vedle_ona_lezi",
    "Naolejuj jí ruce a nechte se navzájem klouzat po pažích a zádech.|180|sed_celem",
    "Nakonec ji jen obejmi a nech ruce ležet tam, kde skončily.|60|lzicka",
  ],

  female: [
    "Naolejuj si dlaně a jeď mu od kotníků až k zátylku jedním nepřerušeným tahem. Třikrát.|180|masaz_zada!",
    "Masíruj mu hrudník celými dlaněmi v kruzích a bradavek se dotkni až úplně nakonec.|180|vedle_on_lezi",
    "Jen bradavky: Tři minuty se věnuj výhradně jeho bradavkám – prsty, jazykem, dechem. Nikam jinam. Cíl: ať se prohne v zádech.|180|vedle_on_lezi",
    "Vezmi jeho bradavku mezi rty a jemně saj. Druhou zatím dráždi palcem.|120|vedle_on_lezi",
    "Naolejuj si celá prsa a klouzej po něm tělem odshora dolů.|180|propletene",
    "Polož ho na břicho, sedni si mu na stehna a rozmasíruj mu celá záda dlaněmi i předloktím.|300|masaz_zada!",
    "Masíruj mu boky a zadek tak, jako bys ho chtěla uvolnit, ne vzrušit. Vydrž u toho.|240|masaz_zada!",
    "Zezadu mu obejmi hrudník a jen ho zlehka svírej a pouštěj do rytmu jeho dechu.|120|stoje_zezadu!",
    "Kroužky kolem: Krouži kolem jeho bradavky prstem a postupně se zmenšuj. Do středu se dostaneš až po minutě. Cíl: co nejpomalejší spirála.|120|vedle_on_lezi",
    "Lehni si na něj celým tělem a jenom se pomalu pohybuj. Ruce mají volno.|180|propletene",
    "Masíruj mu vnitřní stranu stehen dlaněmi nahoru a dolů a pokaždé se zastav kousek před cílem.|180|vedle_on_lezi",
    "Naolejuj mu záda a pak po nich klouzej vlastními prsy tam a zpátky.|180|masaz_zada!",
    "Polož mu obě dlaně na hrudník a jen je tam drž. Nic nedělej.|60|vedle_on_lezi",
    "Olizuj mu bradavky střídavě a mezi tím na ně foukej.|180|vedle_on_lezi",
    "Naolejuj mu nohy od kotníků nahoru a nech ruce doputovat až ke slabinám.|240|vedle_on_lezi",
    "Ruce a nic víc: Dvě minuty se ho smíš dotýkat jen dlaněmi, nikdy prsty. Cíl: velké, pomalé tahy.|120|masaz_zada!",
    "Masíruj mu ramena a při každém tahu sjeď o kousek níž, až se dostaneš na hrudník.|240|masaz_vsede!",
    "Klouzej po něm naolejovaným tělem, ale nikdy nepoužij ruce.|180|propletene",
    "Polož mu hlavu na hrudník a poslouchej, jak se mu zrychluje tep, zatímco ho hladíš.|120|vedle_on_lezi",
    "Jemně mu přejížděj nehty po hrudníku a břiše. Tak lehce, ať to spíš tuší, než cítí.|120|vedle_on_lezi",
    "Naolejovaná záda: Nalij mu olej mezi lopatky a nech ho stéct. Pak ho rozetři až ke kříži. Cíl: nepoužít víc než dvě dlaně oleje.|180|masaz_zada!",
    "Masíruj mu podbřišek dlaní v kruzích a druhou rukou mu drž ruku.|180|vedle_on_lezi",
    "Hlaď ho po celém těle, ale změň tlak pokaždé, když vydechne.|180|vedle_on_lezi",
    "Sedni si za něj, obejmi ho a dlaněmi mu pomalu přejížděj od klíčních kostí k pasu.|180|klin_podlaha",
    "Hruď a jazyk: Střídej dlaň a jazyk na jeho hrudníku tak, aby nikdy nevěděl, co přijde. Cíl: vydržet celou dobu nad pasem.|240|vedle_on_lezi",
    "Masíruj mu stehna zezadu, tam, kde přecházejí v zadek. Silně a pomalu.|180|masaz_zada!",
    "Vezmi si olej a masíruj mu celé tělo tak, aby se ti nakonec pod rukama úplně poddal.|300|masaz_zada!",
    "Dlaněmi mu projeď od kolen po ramena a zpátky. Jeden tah, jeden nádech.|120|vedle_on_lezi",
    "Zezadu mu zajeď rukama pod tričko a hlaď mu břicho a žebra.|120|stoje_zezadu!",
    "Pomalu, pak rychle: Minutu ho hlaď co nejpomaleji, minutu naopak rychle a pevně. Cíl: ať sám řekne, co chce.|120|masaz_zada!",
    "Lehni si na něj a obejmi ho nohama. Jen se na sebe tiskněte.|120|propletene",
    "Masíruj mu hrudní svaly zespoda nahoru. Bradavky nechej být.|180|vedle_on_lezi",
    "Naolejuj si předloktí a jeď mu jimi po zádech. Je to úplně jiný pocit než dlaně.|180|masaz_zada!",
    "Kousni ho zlehka do ramene a pak to místo dlouho olizuj.|90|stoje_zezadu!",
    "Hlaď ho jednou rukou po hrudníku a druhou po zádech současně.|120|vedle_on_lezi",
    "Dva prsty: Celý úkol se ho smíš dotýkat jen dvěma prsty. Vyber si, kterými. Cíl: dokázat, že stačí.|180|vedle_on_lezi",
    "Masíruj mu krk a hrudní kost směrem dolů, jako bys mu uvolňovala dech.|180|vedle_on_lezi",
    "Naolejuj mu zadek a hněť ho oběma rukama, dokud nezvedne boky.|180|masaz_zada!",
    "Polož mu dlaň na hrudník a druhou na podbřišek a jen tak vydrž.|90|vedle_on_lezi",
    "Obejmi ho zezadu a hlaď mu hrudník přes tričko tak dlouho, až si ho sundá.|180|stoje_zezadu!",
    "Olej a dech: Naolejuj mu břicho a sleduj, jak se pod tvou dlaní zvedá a klesá. Přizpůsob se jeho dechu. Cíl: nedělat nic jiného.|120|vedle_on_lezi",
    "Masíruj mu ruce až po ramena a pak sjeď na klíční kosti.|180|masaz_vsede!",
    "Sáhni mu zezadu pod tričko a hlaď mu hrudník, aniž bys ho svlékla.|120|stoje_zezadu!",
    "Přejeď mu jazykem od pupíku nahoru přes hrudník až ke krku.|90|vedle_on_lezi",
    "Masíruj mu kříž oběma palci, zatímco leží na břiše a ty sedíš vedle.|180|masaz_zada!",
    "Tři tempa: Hlaď ho nejdřív konečky prstů, pak celou dlaní, pak hřbetem ruky. Každé dvě minuty. Cíl: zeptat se, které bylo nejlepší.|300|vedle_on_lezi",
    "Lehni si k němu na bok a jednou rukou mu zkoumej celé tělo, jako bys ho neznala.|240|lzicka",
    "Naolejuj mu hrudník a klouzej po něm dlaněmi ze stran ke středu.|180|vedle_on_lezi",
    "Hlaď mu vnitřní stranu paží a podpaží. Je to citlivější, než čeká.|120|vedle_on_lezi",
    "Masíruj mu šíji jednou rukou a druhou mu drž čelo. Ať se opře.|120|masaz_vsede!",
    "Bez konce: Hlaď ho po celém těle tak, aby ruka nikdy neopustila kůži. Pět minut. Cíl: ani jedno přerušení.|300|masaz_zada!",
    "Jazykem mu obkresli obě bradavky a pak na ně foukej, dokud neztvrdnou.|120|vedle_on_lezi",
    "Klouzej po jeho naolejovaných zádech pánví. Pomalu a beze spěchu.|180|na_brise!",
    "Masíruj mu boky palci v kruzích a postupuj směrem k tříslům.|180|vedle_on_lezi",
    "Dej mu ruce na hrudník a nech je tam ležet, zatímco ho líbáš na ústa.|90|ona_nahore",
    "Hlaď ho po zádech tak dlouho, dokud mu nezpomalí dech.|240|masaz_zada!",
    "Mapa citlivosti: Projdi mu celé tělo a hledej tři nejcitlivější místa. On je ohodnotí od jedné do desíti. Cíl: najít aspoň jednu desítku.|300|vedle_on_lezi",
    "Naolejuj si ruce a hlaď mu zároveň hrudník i podbřišek. Mezi tím nikam.|180|vedle_on_lezi",
    "Lehni si za něj a přes rameno mu hlaď hrudník. Do ucha mu u toho dýchej.|180|lzicka",
    "Masíruj mu lopatky a mezižeberní prostory. Málokdo tam sahá.|180|masaz_zada!",
    "Sedni si mu obkročmo na stehna a hněť mu zadek oběma rukama.|180|masaz_zada",
    "Pomalu mu sjížděj rukou od krku k pupíku a pokaždé se zastav o kousek níž.|180|vedle_on_lezi",
    "Jedna ruka: Celý úkol máš k dispozici jen jednu ruku. Druhou drž za zády. Cíl: ať mu to stačí.|240|vedle_on_lezi",
    "Naolejuj mu chodidla a masíruj je tak dlouho, až úplně změkne.|180|masaz_chodidla!",
    "Olizuj mu kůži na žebrech a po stranách hrudníku. Bradavek se nedotkni.|180|vedle_on_lezi",
    "Hlaď ho dlaní po zadku a stehnech v jednom velkém kruhu dokola.|180|masaz_zada!",
    "Masíruj mu ramena zezadu, zatímco sedí, a pomalu mu stahuj tričko.|180|masaz_vsede!",
    "Přitiskni se k němu zády a veď mu ruce po svém těle shora dolů.|180|stoje_zezadu",
    "Tři minuty nad pasem: Celé tři minuty se věnuj jen jeho hrudníku a břichu. Nic níž. Cíl: ať si stáhne tvoji ruku níž sám.|180|vedle_on_lezi",
    "Masíruj mu bříško nad trenýrkami a lem občas jen tak přejeď.|180|vedle_on_lezi",
    "Klouzej mu naolejovanými dlaněmi po bocích a žebrech shora dolů.|120|stoje_zezadu!",
    "Lehni si na záda a nech ho, ať si lehne na tebe. Hlaď ho po celém těle.|240|propletene",
    "Přejížděj mu dlaněmi po hrudníku a jazykem od jedné bradavky ke druhé.|180|vedle_on_lezi",
    "Masíruj mu krční svaly palci a zbytkem dlaně mu drž hlavu.|120|masaz_vsede!",
    "Bez rukou: Klouzej po něm jen naolejovaným tělem – prsy, stehny, břichem. Ruce máš za zády. Cíl: neopřít se ani jednou.|180|propletene",
    "Hlaď mu kůži za koleny a na vnitřní straně stehen. Postupně výš.|180|vedle_on_lezi",
    "Masíruj mu celou přední stranu těla dlaněmi, od ramen po kotníky.|300|vedle_on_lezi",
    "Nech ho ležet na boku a hlaď mu bok od podpaží po stehno. Jeden dlouhý tah.|120|lzicka",
    "Naolejuj si břicho a přitiskni se k jeho zádům. Pak se pomalu pohybuj.|180|lzicka",
    "Kousni ho zlehka do zadku a pak to místo pohlaď dlaní.|60|masaz_zada!",
    "Deset kruhů: Uděláš mu na zádech deset velkých kruhů dlaněmi. On počítá. Cíl: každý kruh pomalejší než předchozí.|180|masaz_zada!",
    "Masíruj mu tříselné rýhy palci. Blízko, ale ne přímo.|180|vedle_on_lezi",
    "Polož mu ruce na hrudník a mezitím ho líbej na krk tak dlouho, až se začne kroutit.|180|ona_nahore",
    "Hlaď ho po celém těle a pokaždé, když vydechne, přitlač.|180|vedle_on_lezi",
    "Naolejujte si navzájem ruce a klouzejte si po pažích a zádech.|180|sed_celem",
    "Nakonec ho jen obejmi a nech ruce ležet tam, kde skončily.|60|lzicka",
  ],
});
