// Kategorie 2 – Smyslné doteky (dávka b)
// Témata: celotělová olejová masáž, bradavky a hrudník, klouzání tělo na tělo.
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 2,

  male: [
    "Od kotníků k zátylku: Naolejuj si dlaně a projeď ji jedním nepřerušeným tahem od kotníků až k zátylku. Cíl: tři takové tahy, ani jeden přerušený.|180|masaz_zada",
    "Bradavky až nakonec: Masíruj jí prsa celými dlaněmi v pomalých kruzích. Cíl: tři minuty a bradavek se dotknout až v posledních deseti vteřinách.|180|vedle_ona_lezi",
    "Jen bradavky: Tři minuty se věnuj výhradně jejím bradavkám – prsty, jazykem, dechem. Nikam jinam. Cíl: ať se prohne v zádech.|180|vedle_ona_lezi",
    "Ústa a palec: Vezmi její bradavku mezi rty a jemně saj, druhou zatím dráždi palcem. Cíl: minuta na každé straně a pak výměna.|120|vedle_ona_lezi",
    "Tělo po těle: Naolejuj si celý hrudník a klouzej po ní shora dolů. Cíl: deset cest a ani jednou si nepomoct rukama.|180|propletene",
    "Záda dlaněmi i lokty: Polož ji na břicho, sedni si jí na stehna a rozmasíruj jí celá záda dlaněmi a pak předloktím. Cíl: pět minut a projít každý sval.|300|masaz_zada",
    "Uvolnit, ne vzrušit: Masíruj jí boky a zadeček, jako bys ji chtěl jen uvolnit. Cíl: čtyři minuty vydržet v tomhle tempu, ať se vrtí, jak chce.|240|masaz_zada",
    "Sevřít s nádechem: Obejmi jí zezadu hrudník a svírej a pouštěj ho přesně do rytmu jejího dechu. Cíl: dvacet nádechů a ani jeden nesplést.|120|stoje_zezadu",
    "Kroužky kolem: Krouži kolem její bradavky prstem a postupně se zmenšuj. Do středu se dostaneš až po minutě. Cíl: co nejpomalejší spirála.|120|vedle_ona_lezi",
    "Celou vahou: Lehni si na ni celým tělem a jen se pomalu pohybuj, ruce nepoužívej. Cíl: tři minuty a ptát se, jestli to není moc.|180|propletene",
    "Kousek před cílem: Masíruj jí vnitřní stranu stehen dlaněmi nahoru a dolů. Cíl: patnáct cest a ani jednou nedojet až úplně nahoru.|180|vedle_ona_lezi",
    "Hrudník po zádech: Naolejuj jí záda a pak po nich klouzej vlastním hrudníkem tam a zpátky. Cíl: deset cest a ruce si nechat opřené vedle ní.|180|masaz_zada",
    "Jen držet: Vezmi jí obě prsa do dlaní a jen je drž. Nic jiného. Cíl: celá minuta bez jediného pohybu prstů.|60|stoje_zezadu",
    "Olíznout a foukat: Olizuj jí bradavky střídavě a mezi tím na ně pokaždé foukej. Cíl: deset střídání na každé straně.|180|vedle_ona_lezi",
    "Od kotníků ke slabinám: Naolejuj jí nohy od kotníků nahoru a nech ruce doputovat až ke slabinám. Cíl: dvě minuty na každé noze.|240|vedle_ona_lezi",
    "Ruce a nic víc: Hlaď ji jen otevřenými dlaněmi, nikdy prsty. Velké, pomalé tahy přes celá záda. Cíl: dvě minuty a ani jednou nepoužít prsty.|120|masaz_zada",
    "O kousek níž: Masíruj jí ramena a při každém tahu sjeď o kousek níž. Cíl: dostat se k prsům nejdřív po třech minutách.|240|masaz_vsede",
    "Bez rukou: Klouzej po ní naolejovaným tělem, ale ruce nepoužiješ ani jednou. Cíl: tři minuty a ruce nechat celou dobu nad hlavou.|180|propletene",
    "Poslouchej jí tep: Polož jí hlavu na hrudník a hlaď ji, zatímco posloucháš, jak se jí zrychluje tep. Cíl: nepřestat, dokud tep nezrychlí dvakrát.|120|vedle_ona_lezi",
    "Sotva znatelně: Přejížděj jí nehty po prsou a břiše tak lehce, ať to spíš tuší, než cítí. Cíl: dvě minuty a nepřitlačit ani jednou.|120|vedle_ona_lezi",
    "Naolejovaná záda: Nalij jí olej mezi lopatky a nech ho stéct. Pak ho rozetři až ke kříži. Cíl: nepoužít víc než dvě dlaně oleje.|180|masaz_zada",
    "Kruhy na podbřišku: Masíruj jí podbřišek dlaní v pomalých kruzích a druhou rukou jí drž ruku. Cíl: padesát kruhů a ruku ani jednou nepustit.|180|vedle_ona_lezi",
    "Tlak podle dechu: Hlaď ji po celém těle a pokaždé, když vydechne, změň tlak. Cíl: tři minuty a ani jeden výdech nepropásnout.|180|vedle_ona_lezi",
    "Od klíčků k pasu: Sedni si za ni, obejmi ji a dlaněmi jí pomalu přejížděj od klíčních kostí až k pasu. Cíl: dvacet cest a žádná rychlejší.|180|klin_podlaha",
    "Prsa a jazyk: Střídej dlaň a jazyk na jejích prsou tak, aby nikdy nevěděla, co přijde. Cíl: vydržet celou dobu jen u prsou.|240|vedle_ona_lezi",
    "Kde stehno končí: Masíruj jí stehna zezadu tam, kde přecházejí v zadeček. Silně a pomalu. Cíl: půldruhé minuty na každé noze.|180|masaz_zada",
    "Dokud se nepoddá: Vezmi si olej a masíruj jí celé tělo shora dolů. Cíl: nepřestat, dokud se ti pod rukama úplně neuvolní.|300|masaz_zada",
    "Tah na jeden nádech: Projeď jí dlaněmi od kolen až po ramena a zpátky. Jeden tah trvá přesně jeden nádech. Cíl: dvacet tahů, žádný rychlejší.|120|vedle_ona_lezi",
    "Ruce pod tričkem: Zezadu jí zajeď rukama pod tričko a hlaď jí břicho a žebra. Cíl: dvě minuty a výš než k žebrům nesahat.|120|stoje_zezadu",
    "Pomalu, pak rychle: Minutu ji hlaď co nejpomaleji, minutu naopak rychle a pevně. Cíl: ať sama řekne, co chce.|120|masaz_zada",
    "Jen se tisknout: Lehni si na ni, nech se obejmout nohama a jen se o sebe tiskněte celým tělem. Cíl: dvě minuty a ani jeden se nepohne.|120|propletene",
    "Zespoda nahoru: Masíruj jí prsa zespoda nahoru, jako bys je nadzvedával. Cíl: tři minuty a bradavek se ani jednou nedotknout.|180|vedle_ona_lezi",
    "Předloktí místo dlaní: Naolejuj si předloktí a jeď jí jimi po zádech. Cíl: deset tahů a pak se zeptat, co je lepší.|180|masaz_zada",
    "Kousnutí a jazyk: Kousni ji zlehka do ramene a pak to místo dlouho olizuj. Cíl: pět kousnutí, každé na jiném místě ramene.|90|stoje_zezadu",
    "Zepředu i zezadu: Hlaď ji jednou rukou po hrudníku a druhou po zádech současně. Cíl: dvě minuty a obě ruce ve stejném rytmu.|120|vedle_ona_lezi",
    "Dva prsty: Celý úkol se jí smíš dotýkat jen dvěma prsty. Vyber si, kterými. Cíl: dokázat, že stačí.|180|vedle_ona_lezi",
    "Uvolnit jí dech: Masíruj jí krk a hrudní kost směrem dolů, jako bys jí chtěl otevřít dech. Cíl: nepřestat, dokud se jí nezpomalí dýchání.|180|vedle_ona_lezi",
    "Dokud nezvedne boky: Naolejuj jí zadeček a hněť ho oběma rukama. Cíl: nepřestat, dokud sama nezvedne boky proti tvým rukám.|180|masaz_zada",
    "Dvě dlaně a ticho: Polož jí jednu dlaň na hrudník, druhou na podbřišek a nech je tam. Cíl: půldruhé minuty úplného klidu a ani slovo.|90|vedle_ona_lezi",
    "Přes tričko: Vezmi ji do náruče zezadu a hlaď jí prsa přes tričko. Cíl: nesundat jí ho – vydržet, dokud si ho nesundá sama.|180|stoje_zezadu",
    "Olej a dech: Naolejuj jí břicho a sleduj, jak se pod tvou dlaní zvedá a klesá. Přizpůsob se jejímu dechu. Cíl: nedělat nic jiného.|120|vedle_ona_lezi",
    "Ruce a klíčky: Masíruj jí ruce od dlaní až po ramena a teprve pak sjeď na klíční kosti. Cíl: půldruhé minuty na každé ruce.|180|masaz_vsede",
    "Pod podprsenkou: Sáhni jí zezadu pod podprsenku a hlaď jí prsa, ale nesundávej ji. Cíl: dvě minuty a nechat ji zapnutou až do konce.|120|stoje_zezadu",
    "Jedna čára jazykem: Přejeď jí jazykem od pupíku nahoru mezi prsy až ke krku. Cíl: pět cest a každá musí trvat aspoň deset vteřin.|90|vedle_ona_lezi",
    "Palce na kříži: Masíruj jí kříž oběma palci, zatímco leží na břiše. Cíl: tři minuty a postupně přidávat tlak, dokud neřekne dost.|180|masaz_zada",
    "Tři tempa: Hlaď ji nejdřív konečky prstů, pak celou dlaní, pak hřbetem ruky. Každé dvě minuty. Cíl: zeptat se, které bylo nejlepší.|300|vedle_ona_lezi",
    "Jako bys ji neznal: Lehni si k ní na bok a jednou rukou jí pomalu ohmatávej celé tělo, jako bys ho viděl poprvé. Cíl: čtyři minuty a nikde nespěchat.|240|lzicka",
    "Ze stran ke středu: Naolejuj jí prsa a klouzej po nich dlaněmi ze stran ke středu. Cíl: padesát tahů a bradavek se dotknout až nakonec.|180|vedle_ona_lezi",
    "Hlaď jí vnitřní stranu paží a podpaží. Je to citlivější, než čeká.|120|vedle_ona_lezi",
    "Masíruj jí šíji jednou rukou a druhou jí drž čelo. Ať se opře.|120|masaz_vsede",
    "Bez konce: Hlaď ji po celém těle tak, aby ruka nikdy neopustila kůži. Pět minut. Cíl: ani jedno přerušení.|300|masaz_zada",
    "Jazykem jí obkresli obě bradavky a pak na ně foukej, dokud neztvrdnou.|120|vedle_ona_lezi",
    "Klouzej po jejích naolejovaných zádech pánví. Pomalu a beze spěchu.|180|na_brise",
    "Masíruj jí boky palci v kruzích a postupuj směrem k tříslům.|180|vedle_ona_lezi",
    "Dej jí ruce na prsa a nech je tam ležet, zatímco ji líbáš na ústa.|90|misionar",
    "Hlaď ji po zádech tak dlouho, dokud jí nezpomalí dech.|240|masaz_zada",
    "Mapa citlivosti: Projdi jí celé tělo a hledej tři nejcitlivější místa. Ona je ohodnotí od jedné do desíti. Cíl: najít aspoň jednu desítku.|300|vedle_ona_lezi",
    "Naolejuj si ruce a hlaď jí zároveň prsa i podbřišek. Mezi tím nikam.|180|vedle_ona_lezi",
    "Lehni si za ni a přes rameno jí hlaď hrudník. Do ucha jí u toho dýchej.|180|lzicka",
    "Masíruj jí lopatky a mezižeberní prostory. Málokdo tam sahá.|180|masaz_zada",
    "Sedni si jí obkročmo na stehna a hněť jí zadeček oběma rukama.|180|masaz_zada",
    "Pomalu jí sjížděj rukou od krku k pupíku a pokaždé se zastav o kousek níž.|180|vedle_ona_lezi",
    "Jedna ruka: Hlaď ji a dráždi jen jednou rukou, druhou drž celou dobu za zády. Cíl: čtyři minuty a ani jednou ji nevytáhnout.|240|vedle_ona_lezi",
    "Naolejuj jí chodidla a masíruj je tak dlouho, až úplně změkne.|180|masaz_chodidla",
    "Olizuj jí kůži pod prsy a po stranách hrudníku. Bradavek se nedotkni.|180|vedle_ona_lezi",
    "Hlaď ji dlaní po zadečku a stehnech v jednom velkém kruhu dokola.|180|masaz_zada",
    "Masíruj jí ramena zezadu, zatímco sedí, a pomalu jí sundávej ramínka.|180|masaz_vsede",
    "Přitiskni si ji zády k hrudníku a hlaď jí celé tělo shora dolů.|180|stoje_zezadu",
    "Tři minuty na prsa: Celé tři minuty se věnuj jen jejím prsům. Nic pod pasem. Cíl: ať si stáhne tvoji ruku níž sama.|180|vedle_ona_lezi",
    "Masíruj jí bříško nad kalhotkami a lem občas jen tak přejeď.|180|vedle_ona_lezi",
    "Klouzej jí naolejovanými dlaněmi po bocích, jako bys jí kreslil přesýpací hodiny.|120|stoje_zezadu",
    "Lehni si na záda a nech ji, ať si lehne na tebe. Hlaď ji po celém těle.|240|propletene",
    "Vezmi jí prsa zespoda do dlaní a jazykem přejížděj od jednoho ke druhému.|180|vedle_ona_lezi",
    "Masíruj jí krční svaly palci a zbytkem dlaně jí drž hlavu.|120|masaz_vsede",
    "Bez rukou: Klouzej po ní jen naolejovaným tělem – hrudníkem, stehny, břichem. Ruce máš za zády. Cíl: neopřít se ani jednou.|180|propletene",
    "Hlaď jí kůži za koleny a na vnitřní straně stehen. Postupně výš.|180|vedle_ona_lezi",
    "Masíruj jí celou přední stranu těla dlaněmi, od ramen po kotníky.|300|vedle_ona_lezi",
    "Nech ji ležet na boku a hlaď jí bok od podpaží po stehno. Jeden dlouhý tah.|120|lzicka",
    "Naolejuj si břicho a přitiskni se k jejím zádům. Pak se pomalu pohybuj.|180|lzicka",
    "Kousni ji zlehka do zadečku a pak to místo pohlaď dlaní.|60|masaz_zada",
    "Deset kruhů: Uděláš jí na zádech deset velkých kruhů dlaněmi. Ona počítá. Cíl: každý kruh pomalejší než předchozí.|180|masaz_zada",
    "Masíruj jí tříselné rýhy palci. Blízko, ale ne přímo.|180|vedle_ona_lezi",
    "Polož jí ruce na prsa a mezitím ji líbej na krk tak dlouho, až se začne kroutit.|180|stoje_zezadu",
    "Hlaď ji po celém těle a pokaždé, když vydechne, přitlač.|180|vedle_ona_lezi",
    "Naolejuj jí ruce a nechte se navzájem klouzat po pažích a zádech.|180|sed_celem",
    "Nakonec ji jen obejmi a nech ruce ležet tam, kde skončily.|60|lzicka",
  ],

  female: [
    "Kotníky až zátylek: Naolejuj si dlaně a projeď ho jedním nepřerušeným tahem od kotníků až k zátylku. Cíl: tři takové tahy, ani jeden přerušený.|180|masaz_zada!",
    "Bradavky nakonec: Masíruj mu hrudník celými dlaněmi v pomalých kruzích. Cíl: tři minuty a bradavek se dotknout až v posledních deseti vteřinách.|180|vedle_on_lezi",
    "Jen bradavky: Tři minuty se věnuj výhradně jeho bradavkám – prsty, jazykem, dechem. Nikam jinam. Cíl: ať se prohne v zádech.|180|vedle_on_lezi",
    "Rty a palec: Vezmi jeho bradavku mezi rty a jemně saj, druhou zatím dráždi palcem. Cíl: minuta na každé straně a pak výměna.|120|vedle_on_lezi",
    "Prsa po jeho těle: Naolejuj si celá prsa a klouzej po něm shora dolů. Cíl: deset cest a ani jednou si nepomoct rukama.|180|propletene",
    "Jeho záda naplno: Polož ho na břicho, sedni si mu na stehna a rozmasíruj mu celá záda dlaněmi a pak předloktím. Cíl: pět minut a projít každý sval.|300|masaz_zada!",
    "Jen uvolnit: Masíruj mu boky a zadek, jako bys ho chtěla jen uvolnit. Cíl: čtyři minuty vydržet v tomhle tempu, ať se vrtí, jak chce.|240|masaz_zada!",
    "Dech pod tvýma rukama: Obejmi mu zezadu hrudník a svírej a pouštěj ho přesně do rytmu jeho dechu. Cíl: dvacet nádechů a ani jeden nesplést.|120|stoje_zezadu!",
    "Kroužky kolem: Krouži kolem jeho bradavky prstem a postupně se zmenšuj. Do středu se dostaneš až po minutě. Cíl: co nejpomalejší spirála.|120|vedle_on_lezi",
    "Celou vahou na něm: Lehni si na něj celým tělem a jen se pomalu pohybuj, ruce nepoužívej. Cíl: tři minuty a ptát se, jestli to není moc.|180|propletene",
    "Vždycky kousek pod: Masíruj mu vnitřní stranu stehen dlaněmi nahoru a dolů. Cíl: patnáct cest a ani jednou nedojet až úplně nahoru.|180|vedle_on_lezi",
    "Prsa po jeho zádech: Naolejuj mu záda a pak po nich klouzej vlastními prsy tam a zpátky. Cíl: deset cest a ruce si nechat opřené vedle něj.|180|masaz_zada!",
    "Ruce bez pohybu: Polož mu obě dlaně na hrudník a jen je tam drž. Nic jiného. Cíl: celá minuta bez jediného pohybu prstů.|60|vedle_on_lezi",
    "Jazyk a foukání: Olizuj mu bradavky střídavě a mezi tím na ně pokaždé foukej. Cíl: deset střídání na každé straně.|180|vedle_on_lezi",
    "Nohy až ke slabinám: Naolejuj mu nohy od kotníků nahoru a nech ruce doputovat až ke slabinám. Cíl: dvě minuty na každé noze.|240|vedle_on_lezi",
    "Dlaně místo prstů: Hlaď ho jen otevřenými dlaněmi, nikdy prsty. Velké, pomalé tahy přes celá záda. Cíl: dvě minuty a ani jednou nepoužít prsty.|120|masaz_zada!",
    "Tah po tahu níž: Masíruj mu ramena a při každém tahu sjeď o kousek níž. Cíl: dostat se na hrudník nejdřív po třech minutách.|240|masaz_vsede!",
    "Ruce nad hlavou: Klouzej po něm naolejovaným tělem, ale ruce nepoužiješ ani jednou. Cíl: tři minuty a ruce nechat celou dobu nad hlavou.|180|propletene",
    "Jeho tep pod uchem: Polož mu hlavu na hrudník a hlaď ho, zatímco posloucháš, jak se mu zrychluje tep. Cíl: nepřestat, dokud tep nezrychlí dvakrát.|120|vedle_on_lezi",
    "Spíš tušit než cítit: Přejížděj mu nehty po hrudníku a břiše tak lehce, ať to spíš tuší, než cítí. Cíl: dvě minuty a nepřitlačit ani jednou.|120|vedle_on_lezi",
    "Naolejovaná záda: Nalij mu olej mezi lopatky a nech ho stéct. Pak ho rozetři až ke kříži. Cíl: nepoužít víc než dvě dlaně oleje.|180|masaz_zada!",
    "Podbřišek v kruzích: Masíruj mu podbřišek dlaní v pomalých kruzích a druhou rukou mu drž ruku. Cíl: padesát kruhů a ruku ani jednou nepustit.|180|vedle_on_lezi",
    "Výdech mění tlak: Hlaď ho po celém těle a pokaždé, když vydechne, změň tlak. Cíl: tři minuty a ani jeden výdech nepropásnout.|180|vedle_on_lezi",
    "Klíčky až pas: Sedni si za něj, obejmi ho a dlaněmi mu pomalu přejížděj od klíčních kostí až k pasu. Cíl: dvacet cest a žádná rychlejší.|180|klin_podlaha",
    "Hruď a jazyk: Střídej dlaň a jazyk na jeho hrudníku tak, aby nikdy nevěděl, co přijde. Cíl: vydržet celou dobu nad pasem.|240|vedle_on_lezi",
    "Pod zadkem: Masíruj mu stehna zezadu tam, kde přecházejí v zadek. Silně a pomalu. Cíl: půldruhé minuty na každé noze.|180|masaz_zada!",
    "Dokud se nepoddá on: Vezmi si olej a masíruj mu celé tělo shora dolů. Cíl: nepřestat, dokud se ti pod rukama úplně neuvolní.|300|masaz_zada!",
    "Nádech na jeden tah: Projeď mu dlaněmi od kolen až po ramena a zpátky. Jeden tah trvá přesně jeden nádech. Cíl: dvacet tahů, žádný rychlejší.|120|vedle_on_lezi",
    "Pod jeho tričkem: Zezadu mu zajeď rukama pod tričko a hlaď mu břicho a žebra. Cíl: dvě minuty a níž než k pasu nesahat.|120|stoje_zezadu!",
    "Pomalu, pak rychle: Minutu ho hlaď co nejpomaleji, minutu naopak rychle a pevně. Cíl: ať sám řekne, co chce.|120|masaz_zada!",
    "Propletení a ticho: Lehni si na něj a obejmi ho nohama. Cíl: dvě minuty, při kterých se ani jeden z vás nepohne.|120|propletene",
    "Hrudník zespoda: Masíruj mu hrudní svaly zespoda nahoru pevnými tahy. Cíl: tři minuty a bradavek se ani jednou nedotknout.|180|vedle_on_lezi",
    "Lokty po zádech: Naolejuj si předloktí a jeď mu jimi po zádech. Cíl: deset tahů a pak se zeptat, co je lepší.|180|masaz_zada!",
    "Kousnout a olízat: Kousni ho zlehka do ramene a pak to místo dlouho olizuj. Cíl: pět kousnutí, každé na jiném místě ramene.|90|stoje_zezadu!",
    "Z obou stran: Hlaď ho jednou rukou po hrudníku a druhou po zádech současně. Cíl: dvě minuty a obě ruce ve stejném rytmu.|120|vedle_on_lezi",
    "Dva prsty: Celý úkol se ho smíš dotýkat jen dvěma prsty. Vyber si, kterými. Cíl: dokázat, že stačí.|180|vedle_on_lezi",
    "Otevřít mu dech: Masíruj mu krk a hrudní kost směrem dolů, jako bys mu chtěla otevřít dech. Cíl: nepřestat, dokud se mu nezpomalí dýchání.|180|vedle_on_lezi",
    "Až zvedne boky: Naolejuj mu zadek a hněť ho oběma rukama. Cíl: nepřestat, dokud sám nezvedne boky proti tvým rukám.|180|masaz_zada!",
    "Dvě dlaně v klidu: Polož mu jednu dlaň na hrudník, druhou na podbřišek a nech je tam. Cíl: půldruhé minuty úplného klidu a ani slovo.|90|vedle_on_lezi",
    "Přes jeho tričko: Obejmi ho zezadu a hlaď mu hrudník přes tričko. Cíl: nesundat mu ho – vydržet, dokud si ho nesundá sám.|180|stoje_zezadu!",
    "Olej a dech: Naolejuj mu břicho a sleduj, jak se pod tvou dlaní zvedá a klesá. Přizpůsob se jeho dechu. Cíl: nedělat nic jiného.|120|vedle_on_lezi",
    "Od dlaní po klíčky: Masíruj mu ruce od dlaní až po ramena a teprve pak sjeď na klíční kosti. Cíl: půldruhé minuty na každé ruce.|180|masaz_vsede!",
    "Sáhni mu zezadu pod tričko a hlaď mu hrudník, aniž bys ho svlékla.|120|stoje_zezadu!",
    "Přejeď mu jazykem od pupíku nahoru přes hrudník až ke krku.|90|vedle_on_lezi",
    "Masíruj mu kříž oběma palci, zatímco leží na břiše a ty sedíš vedle.|180|masaz_zada!",
    "Tři tempa: Hlaď ho nejdřív konečky prstů, pak celou dlaní, pak hřbetem ruky. Každé dvě minuty. Cíl: zeptat se, které bylo nejlepší.|300|vedle_on_lezi",
    "Jako bys ho neznala: Lehni si k němu na bok a jednou rukou mu pomalu ohmatávej celé tělo, jako bys ho viděla poprvé. Cíl: čtyři minuty a nikde nespěchat.|240|lzicka",
    "Naolejuj mu hrudník a klouzej po něm dlaněmi ze stran ke středu.|180|vedle_on_lezi",
    "Hlaď mu vnitřní stranu paží a podpaží. Je to citlivější, než čeká.|120|vedle_on_lezi",
    "Masíruj mu šíji jednou rukou a druhou mu drž čelo. Ať se opře.|120|masaz_vsede!",
    "Bez konce: Hlaď ho po celém těle tak, aby ruka nikdy neopustila kůži. Pět minut. Cíl: ani jedno přerušení.|300|masaz_zada!",
    "Jazykem mu obkresli obě bradavky a pak na ně foukej, dokud neztvrdnou.|120|vedle_on_lezi",
    "Klouzej po jeho naolejovaných zádech pánví. Pomalu a beze spěchu.|180|na_brise!",
    "Masíruj mu boky palci v kruzích a postupuj směrem k tříslům.|180|vedle_on_lezi",
    "Dej mu ruce na hrudník a nech je tam ležet, zatímco ho líbáš na ústa.|90|ona_nahore",
    "Hlaď ho po zádech tak dlouho, dokud mu nezpomalí dech.|240|masaz_zada!",
    "Mapa citlivosti: Projdi mu celé tělo a hledej tři nejcitlivější místa. On je ohodnotí od jedné do desíti. Cíl: najít aspoň jednu desítku.|300|vedle_on_lezi",
    "Naolejuj si ruce a hlaď mu zároveň hrudník i podbřišek. Mezi tím nikam.|180|vedle_on_lezi",
    "Lehni si za něj a přes rameno mu hlaď hrudník. Do ucha mu u toho dýchej.|180|lzicka",
    "Masíruj mu lopatky a mezižeberní prostory. Málokdo tam sahá.|180|masaz_zada!",
    "Sedni si mu obkročmo na stehna a hněť mu zadek oběma rukama.|180|masaz_zada",
    "Pomalu mu sjížděj rukou od krku k pupíku a pokaždé se zastav o kousek níž.|180|vedle_on_lezi",
    "Druhá ruka za zády: Hlaď ho a dráždi jen jednou rukou, druhou drž celou dobu za zády. Cíl: čtyři minuty a ani jednou ji nevytáhnout.|240|vedle_on_lezi",
    "Naolejuj mu chodidla a masíruj je tak dlouho, až úplně změkne.|180|masaz_chodidla!",
    "Olizuj mu kůži na žebrech a po stranách hrudníku. Bradavek se nedotkni.|180|vedle_on_lezi",
    "Hlaď ho dlaní po zadku a stehnech v jednom velkém kruhu dokola.|180|masaz_zada!",
    "Masíruj mu ramena zezadu, zatímco sedí, a pomalu mu stahuj tričko.|180|masaz_vsede!",
    "Přitiskni se k němu zády a veď mu ruce po svém těle shora dolů.|180|stoje_zezadu",
    "Tři minuty nad pasem: Celé tři minuty se věnuj jen jeho hrudníku a břichu. Nic níž. Cíl: ať si stáhne tvoji ruku níž sám.|180|vedle_on_lezi",
    "Masíruj mu bříško nad trenýrkami a lem občas jen tak přejeď.|180|vedle_on_lezi",
    "Klouzej mu naolejovanými dlaněmi po bocích a žebrech shora dolů.|120|stoje_zezadu!",
    "Lehni si na záda a nech ho, ať si lehne na tebe. Hlaď ho po celém těle.|240|propletene",
    "Přejížděj mu dlaněmi po hrudníku a jazykem od jedné bradavky ke druhé.|180|vedle_on_lezi",
    "Masíruj mu krční svaly palci a zbytkem dlaně mu drž hlavu.|120|masaz_vsede!",
    "Bez rukou: Klouzej po něm jen naolejovaným tělem – prsy, stehny, břichem. Ruce máš za zády. Cíl: neopřít se ani jednou.|180|propletene",
    "Hlaď mu kůži za koleny a na vnitřní straně stehen. Postupně výš.|180|vedle_on_lezi",
    "Masíruj mu celou přední stranu těla dlaněmi, od ramen po kotníky.|300|vedle_on_lezi",
    "Nech ho ležet na boku a hlaď mu bok od podpaží po stehno. Jeden dlouhý tah.|120|lzicka",
    "Naolejuj si břicho a přitiskni se k jeho zádům. Pak se pomalu pohybuj.|180|lzicka",
    "Kousni ho zlehka do zadku a pak to místo pohlaď dlaní.|60|masaz_zada!",
    "Deset kruhů: Uděláš mu na zádech deset velkých kruhů dlaněmi. On počítá. Cíl: každý kruh pomalejší než předchozí.|180|masaz_zada!",
    "Masíruj mu tříselné rýhy palci. Blízko, ale ne přímo.|180|vedle_on_lezi",
    "Polož mu ruce na hrudník a mezitím ho líbej na krk tak dlouho, až se začne kroutit.|180|ona_nahore",
    "Hlaď ho po celém těle a pokaždé, když vydechne, přitlač.|180|vedle_on_lezi",
    "Naolejujte si navzájem ruce a klouzejte si po pažích a zádech.|180|sed_celem",
    "Nakonec ho jen obejmi a nech ruce ležet tam, kde skončily.|60|lzicka",
  ],
});
