// Kategorie 2 – Smyslné doteky (dávka d)
// Témata: smyslová deprivace, pozorování, instrukce na dálku, počítané výzvy.
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 2,

  male: [
    "Zavaž jí oči i uši sluchátky a pět minut se jí dotýkej úplně nepředvídatelně.|300|vedle_ona_lezi",
    "Nasaď jí sluchátka s hudbou, ať tě neslyší, a dotýkej se jí jen v pauzách mezi slokami.|300|vedle_ona_lezi",
    "Slepá mapa: Zavaž jí oči a dotýkej se jí na deseti místech. Na konci musí říct všechna v pořadí. Cíl: aspoň sedm správně.|300|vedle_ona_lezi",
    "Zavaž jí oči a nech ji hádat, jestli se jí dotýkáš prstem, jazykem, nebo pírkem.|240|vedle_ona_lezi",
    "Sedni si na kraj postele a jen se dívej, jak se dotýká sama. Nesmíš se přiblížit.|300",
    "Posaďte se proti sobě a dotýkejte se každý sám sebe. Kdo první sáhne po druhém, prohrál.|300|sed_celem",
    "Instrukce na dálku: Sedni si dva metry od ní a říkej jí, co si má dělat. Nesmíš se jí dotknout. Cíl: dovést ji k tomu jen hlasem.|300",
    "Řekni jí, ať zavře oči a nehýbe se. Pak jí dej přesně pět doteků. Ani o jeden víc.|180|vedle_ona_lezi",
    "Zavaž jí oči a polož jí ruku někam na tělo. Ona musí uhodnout, která ruka to je.|180|vedle_ona_lezi",
    "Dotýkej se jí tak, aby nikdy nevěděla, kde budeš za tři vteřiny.|240|vedle_ona_lezi",
    "Padesát doteků: Dej jí padesát krátkých doteků po celém těle. Ona počítá potichu a na konci řekne číslo. Cíl: shodnout se.|300|vedle_ona_lezi",
    "Zavaž jí oči a nech ji, ať ti rukou najde tvář. Pak jí líbej dlaň.|120",
    "Dej jí zákaz otevřít oči. Pokaždé, když je otevře, přestaneš na deset vteřin.|240|vedle_ona_lezi",
    "Nech ji ležet nahou a jen ji pozoruj. Nedotkni se jí ani jednou.|120|vedle_ona_lezi",
    "Popisuj jí nahlas, co s ní právě děláš, ale dělej přitom něco jiného.|240|vedle_ona_lezi",
    "Pravidlo tří: Řekni jí tři pravidla na tenhle úkol a striktně je dodržuj. Cíl: ani jedno neporušit.|240|vedle_ona_lezi",
    "Zavaž jí oči a přikládej jí na kůži střídavě teplou a studenou dlaň.|180|vedle_ona_lezi",
    "Dotýkej se jí jen v tom rytmu, v jakém dýchá. Nikdy rychleji.|240|vedle_ona_lezi",
    "Nech ji, ať se dotýká sama, a ty jí u toho jen šeptej, co má dělat dál.|300|vedle_ona_lezi",
    "Zavaž jí oči a nech ji vybrat mezi třemi doteky jen podle pocitu.|180|vedle_ona_lezi",
    "Zrcadlo: Dělej přesně to, co dělá ona sama sobě, ale na svém těle. Cíl: neuhnout ani na chvíli.|240|sed_celem",
    "Dej jí ruce nad hlavu a řekni jí, že je tam musí nechat. Pak ji celou prozkoumej.|300|vedle_ona_lezi",
    "Nech ji ležet se zavázanýma očima a dlouho nedělej vůbec nic. Ať čeká.|120|vedle_ona_lezi",
    "Střídej dotek a pauzu přesně po pěti vteřinách. Počítej nahlas.|240|vedle_ona_lezi",
    "Dvacet vteřin na místo: Ona ti řekne jedno místo a ty se mu věnuješ přesně dvacet vteřin. Pak další. Cíl: šest míst.|180|vedle_ona_lezi",
    "Zavaž jí oči a olizuj ji na náhodných místech. Ať nikdy neví, kde přistaneš.|240|vedle_ona_lezi",
    "Nech ji sedět naproti tobě a dotýkat se sama sebe, zatímco se na ni jen díváš.|300|sed_celem",
    "Dotýkej se jí jen jednou rukou a druhou jí drž ruku pevně v dlani.|240|lzicka",
    "Řekni jí, ať ti popisuje, co cítí. Když ztichne, přestaneš.|240|vedle_ona_lezi",
    "Odpočítávání: Řekni jí, že za tři minuty přestaneš, a nahlas počítej poslední minutu. Cíl: přestat přesně na nule.|180|vedle_ona_lezi",
    "Nech ji, ať si zaváže oči sama, a ty pak dělej, co chceš.|300|vedle_ona_lezi",
    "Dotýkej se jí přes tenkou látku a ptej se, jestli pozná, čím.|180|vedle_ona_lezi",
    "Dej jí sluchátka a dotýkej se jí tak, aby to sedělo do hudby, kterou slyší jen ona.|300|vedle_ona_lezi",
    "Nech ji hádat, kolik prstů má na jejím těle.|180|vedle_ona_lezi",
    "Beze slov a bez očí: Ona má zavázané oči a ty musíš mlčet. Pět minut jen ruce. Cíl: neříct ani slovo.|300|vedle_ona_lezi",
    "Dotýkej se jí co nejlehčeji a ptej se, jestli to vůbec cítí.|180|vedle_ona_lezi",
    "Nech ji ležet a jen jí zlehka přejeď po těle dlaní pokaždé, když se nadechne.|240|vedle_ona_lezi",
    "Řekni jí, že ji necháš čekat. A nech ji čekat celou minutu, než začneš.|60|vedle_ona_lezi",
    "Dotýkej se jí jen tam, kde ti to sama dovolí, a musí to říct nahlas.|300|vedle_ona_lezi",
    "Tři pokusy: Zkus najít místo, které ji rozhodí, na tři pokusy. Ona jen kývne. Cíl: trefit se napoprvé.|180|vedle_ona_lezi",
    "Zavaž jí oči a přejeď jí po těle něčím, co si sám vybereš. Ať hádá.|180|vedle_ona_lezi",
    "Dělej přesně to, co ti řekne, ale o vteřinu později.|240|vedle_ona_lezi",
    "Nech ji, ať drží ruce na tvých ramenou a nesmí je sundat.|240|sed_celem",
    "Dotýkej se jí jedním prstem a celou minutu nezměň tempo.|60|vedle_ona_lezi",
    "Dva hlasy: Střídej šeptání a normální hlas a dotýkej se jí podle toho jemně nebo silně. Cíl: ať pozná systém.|240|vedle_ona_lezi",
    "Dej jí ruce za záda a dotýkej se jí celou dobu jen zepředu.|240|klek_ruce_za_zady",
    "Nech ji sedět na kraji postele a dotýkej se jí, zatímco klečíš před ní.|300|oral_vsede",
    "Zavaž jí oči a nech ji hádat, kde bude další polibek. Když uhodne, dostane ho jinam.|240|vedle_ona_lezi",
    "Dotýkej se jí, ale zastav se pokaždé, když otevře pusu.|240|vedle_ona_lezi",
    "Pět zastavení: Během pěti minut se musíš pětkrát úplně zastavit a nehýbat se. Ona nesmí vědět kdy. Cíl: překvapit ji pokaždé.|300|vedle_ona_lezi",
    "Nech ji, ať ti popíše, co by si přála, a pak jí dej přesně to.|240|vedle_ona_lezi",
    "Dej jí ruku na své a nech ji vést tvoje prsty po svém těle.|240|vedle_ona_lezi",
    "Dotýkej se jí zezadu, když nevidí, co děláš.|240|stoje_zezadu",
    "Řekni jí, ať si klekne a čeká se zavřenýma očima, dokud nezačneš.|120|klek_ruce_za_zady",
    "Sto vteřin: Dotýkej se jí přesně sto vteřin a pak přestaň, ať je kdekoli. Cíl: nepřetáhnout.|120|vedle_ona_lezi",
    "Nech ji ležet na boku a dotýkej se jí jen na zádech a bocích.|240|lzicka",
    "Zavaž jí oči a dej jí do ruky pírko. Ať se dotýká sama a ty se díváš.|240",
    "Dotýkej se jí a vždycky, když řekne víc, o kousek zpomalíš.|240|vedle_ona_lezi",
    "Nech ji, ať si vybere jedno místo, kterému se budeš věnovat celou dobu.|300|vedle_ona_lezi",
    "Souhra dechu: Dotýkej se jí jen při jejím výdechu, při nádechu přestaň. Cíl: udržet to celou dobu.|240|vedle_ona_lezi",
    "Dej jí ruce na oči a nech je tam. Pak se dotýkej, kde chceš.|240|vedle_ona_lezi",
    "Nech ji stát a dotýkej se jí, zatímco se drží zdi.|240|zed",
    "Řekni jí jedno slovo, po kterém vždycky přestaneš. A ať ho použije.|300|vedle_ona_lezi",
    "Dotýkej se jí přes prostěradlo. Nikdy pod ním.|180|vedle_ona_lezi",
    "Tři doteky za minutu: Máš povoleno jen tři doteky za každou minutu. Vyber je dobře. Cíl: vydržet pět minut.|300|vedle_ona_lezi",
    "Nech ji ležet na břiše a dotýkej se jí jen na zadní straně těla.|300|masaz_zada",
    "Zavaž jí oči a nech ji poznat po hmatu, jakou částí těla ji hladíš.|240|vedle_ona_lezi",
    "Dotýkej se jí a pokaždé, když se zasměje, začínáš od hlavy.|240|vedle_ona_lezi",
    "Řekni jí, ať si sedne na tvůj klín zády a nehýbe se.|240|klin_zady",
    "Jeden prst a hodně času: Celý úkol se jí smíš dotýkat jen jedním prstem. Cíl: dokázat, že to stačí.|300|vedle_ona_lezi",
    "Nech ji, ať drží kostku ledu, dokud ji celou nerozpustí. Mezitím ji hlaď.|240|vedle_ona_lezi",
    "Dotýkej se jí a mezi doteky se vždy na chvíli úplně vzdal.|240|vedle_ona_lezi",
    "Nech ji vybrat, jestli chce vidět, nebo cítit. Když si vybere vidět, zavážeš jí oči.|240|vedle_ona_lezi",
    "Dotýkej se jí, ale nikdy oběma rukama najednou.|240|vedle_ona_lezi",
    "Deset a pauza: Deset vteřin se jí věnuješ, deset vteřin nic. A tak dokola. Cíl: nikdy pauzu nevynechat.|300|vedle_ona_lezi",
    "Nech ji klečet a dotýkej se jí shora. Ona nesmí zvednout ruce.|240|klek_ruce_hlava",
    "Dotýkej se jí a ptej se jí po každém doteku, jestli chce znovu.|240|vedle_ona_lezi",
    "Zavaž jí oči a nech ji hledat tvoje rty jen podle dechu.|180|objeti",
    "Dotýkej se jí přesně tak, jak ti to předvedla na sobě.|240|vedle_ona_lezi",
    "Vlastní tempo: Ona počítá nahlas do dvaceti a ty se musíš stihnout dotknout každého čísla jinde. Cíl: dvacet různých míst.|180|vedle_ona_lezi",
    "Dotýkej se jí, dokud neřekne stop. Pak počkej, dokud neřekne pokračuj.|300|vedle_ona_lezi",
    "Nech ji ležet mezi tvýma nohama a hlaď ji odshora.|300|klin_podlaha",
    "Dotýkej se jí jen přes jednu vrstvu oblečení, kterou si sama vybere.|240|vedle_ona_lezi",
    "Nakonec jí sundej šátek a nech ji, ať se na tebe podívá. Nic neříkej.|60|vedle_ona_lezi",
  ],

  female: [
    "Zavaž mu oči i uši sluchátky a pět minut se ho dotýkej úplně nepředvídatelně.|300|vedle_on_lezi",
    "Nasaď mu sluchátka s hudbou, ať tě neslyší, a dotýkej se ho jen v pauzách mezi slokami.|300|vedle_on_lezi",
    "Slepá mapa: Zavaž mu oči a dotýkej se ho na deseti místech. Na konci musí říct všechna v pořadí. Cíl: aspoň sedm správně.|300|vedle_on_lezi",
    "Zavaž mu oči a nech ho hádat, jestli se ho dotýkáš prstem, jazykem, nebo pírkem.|240|vedle_on_lezi",
    "Sedni si na kraj postele a jen se dívej, jak se dotýká sám. Nesmíš se přiblížit.|300",
    "Sedni si proti němu a dotýkejte se každý sám sebe. Kdo první nevydrží a sáhne po druhém, prohrál.|300|sed_celem",
    "Instrukce na dálku: Sedni si dva metry od něj a říkej mu, co si má dělat. Nesmíš se ho dotknout. Cíl: dovést ho k tomu jen hlasem.|300",
    "Řekni mu, ať zavře oči a nehýbe se. Pak mu dej přesně pět doteků. Ani o jeden víc.|180|vedle_on_lezi",
    "Zavaž mu oči a polož mu ruku někam na tělo. On musí uhodnout, která ruka to je.|180|vedle_on_lezi",
    "Dotýkej se ho tak, aby nikdy nevěděl, kde budeš za tři vteřiny.|240|vedle_on_lezi",
    "Padesát doteků: Dej mu padesát krátkých doteků po celém těle. On počítá potichu a na konci řekne číslo. Cíl: shodnout se.|300|vedle_on_lezi",
    "Zavaž mu oči a nech ho, ať ti rukou najde tvář. Pak mu líbej dlaň.|120",
    "Dej mu zákaz otevřít oči. Pokaždé, když je otevře, přestaneš na deset vteřin.|240|vedle_on_lezi",
    "Nech ho ležet nahého a jen ho pozoruj. Nedotkni se ho ani jednou.|120|vedle_on_lezi",
    "Popisuj mu nahlas, co s ním právě děláš, ale dělej přitom něco jiného.|240|vedle_on_lezi",
    "Pravidlo tří: Řekni mu tři pravidla na tenhle úkol a striktně je dodržuj. Cíl: ani jedno neporušit.|240|vedle_on_lezi",
    "Zavaž mu oči a přikládej mu na kůži střídavě teplou a studenou dlaň.|180|vedle_on_lezi",
    "Dotýkej se ho jen v tom rytmu, v jakém dýchá. Nikdy rychleji.|240|vedle_on_lezi",
    "Nech ho, ať se dotýká sám, a ty mu u toho jen šeptej, co má dělat dál.|300|vedle_on_lezi",
    "Zavaž mu oči a nech ho vybrat mezi třemi doteky jen podle pocitu.|180|vedle_on_lezi",
    "Zrcadlo: Dělej přesně to, co dělá on sám sobě, ale na svém těle. Cíl: neuhnout ani na chvíli.|240|sed_celem",
    "Dej mu ruce nad hlavu a řekni mu, že je tam musí nechat. Pak ho celého prozkoumej.|300|vedle_on_lezi",
    "Nech ho ležet se zavázanýma očima a dlouho nedělej vůbec nic. Ať čeká.|120|vedle_on_lezi",
    "Pět vteřin dotek, pět vteřin nic – a počítej to nahlas.|240|vedle_on_lezi",
    "Dvacet vteřin na místo: On ti řekne jedno místo a ty se mu věnuješ přesně dvacet vteřin. Pak další. Cíl: šest míst.|180|vedle_on_lezi",
    "Zavaž mu oči a olizuj ho na náhodných místech. Ať nikdy neví, kde přistaneš.|240|vedle_on_lezi",
    "Nech ho sedět naproti tobě a dotýkej se sama sebe, zatímco se on jen dívá.|300|sed_celem",
    "Dotýkej se ho jen jednou rukou a druhou mu drž ruku pevně v dlani.|240|lzicka",
    "Řekni mu, ať ti popisuje, co cítí. Když ztichne, přestaneš.|240|vedle_on_lezi",
    "Odpočítávání: Řekni mu, že za tři minuty přestaneš, a nahlas počítej poslední minutu. Cíl: přestat přesně na nule.|180|vedle_on_lezi",
    "Nech ho, ať si zaváže oči sám, a ty pak dělej, co chceš.|300|vedle_on_lezi",
    "Dotýkej se ho přes tenkou látku a ptej se, jestli pozná, čím.|180|vedle_on_lezi",
    "Dej mu sluchátka a dotýkej se ho tak, aby to sedělo do hudby, kterou slyší jen on.|300|vedle_on_lezi",
    "Nech ho hádat, kolik prstů máš na jeho těle.|180|vedle_on_lezi",
    "Beze slov a bez očí: On má zavázané oči a ty musíš mlčet. Pět minut jen ruce. Cíl: neříct ani slovo.|300|vedle_on_lezi",
    "Dotýkej se ho co nejlehčeji a ptej se, jestli to vůbec cítí.|180|vedle_on_lezi",
    "Nech ho ležet a jen mu zlehka přejeď po těle dlaní pokaždé, když se nadechne.|240|vedle_on_lezi",
    "Řekni mu, že ho necháš čekat. A nech ho čekat celou minutu, než začneš.|60|vedle_on_lezi",
    "Dotýkej se ho jen tam, kde ti to sám dovolí, a musí to říct nahlas.|300|vedle_on_lezi",
    "Tři pokusy: Zkus najít místo, které ho rozhodí, na tři pokusy. On jen kývne. Cíl: trefit se napoprvé.|180|vedle_on_lezi",
    "Zavaž mu oči a přejeď mu po těle něčím, co si sama vybereš. Ať hádá.|180|vedle_on_lezi",
    "Plň jeho pokyny přesně, ale vždycky až o vteřinu později.|240|vedle_on_lezi",
    "Nech ho, ať drží ruce na tvých ramenou a nesmí je sundat.|240|sed_celem",
    "Dotýkej se ho jedním prstem a celou minutu nezměň tempo.|60|vedle_on_lezi",
    "Dva hlasy: Střídej šeptání a normální hlas a dotýkej se ho podle toho jemně nebo silně. Cíl: ať pozná systém.|240|vedle_on_lezi",
    "Dej mu ruce za záda a dotýkej se ho celou dobu jen zepředu.|240|klek_ruce_za_zady!",
    "Nech ho sedět na kraji postele a dotýkej se ho, zatímco klečíš před ním.|300|oral_on_vsede",
    "Zavaž mu oči a nech ho hádat, kde bude další polibek. Když uhodne, dostane ho jinam.|240|vedle_on_lezi",
    "Dotýkej se ho, ale zastav se pokaždé, když otevře pusu.|240|vedle_on_lezi",
    "Pět zastavení: Během pěti minut se musíš pětkrát úplně zastavit a nehýbat se. On nesmí vědět kdy. Cíl: překvapit ho pokaždé.|300|vedle_on_lezi",
    "Nech ho, ať ti popíše, co by si přál, a pak mu dej přesně to.|240|vedle_on_lezi",
    "Dej mu ruku na svou a nech ho vést tvoje prsty po jeho těle.|240|vedle_on_lezi",
    "Dotýkej se ho zezadu, když nevidí, co děláš.|240|stoje_zezadu!",
    "Řekni mu, ať si klekne a čeká se zavřenýma očima, dokud nezačneš.|120|klek_ruce_za_zady!",
    "Sto vteřin: Dotýkej se ho přesně sto vteřin a pak přestaň, ať je kdekoli. Cíl: nepřetáhnout.|120|vedle_on_lezi",
    "Nech ho ležet na boku a dotýkej se ho jen na zádech a bocích.|240|lzicka",
    "Zavaž mu oči a dej mu do ruky pírko. Ať se dotýká sám a ty se díváš.|240",
    "Dotýkej se ho a vždycky, když řekne víc, o kousek zpomalíš.|240|vedle_on_lezi",
    "Nech ho, ať si vybere jedno místo, kterému se budeš věnovat celou dobu.|300|vedle_on_lezi",
    "Souhra dechu: Dotýkej se ho jen při jeho výdechu, při nádechu přestaň. Cíl: udržet to celou dobu.|240|vedle_on_lezi",
    "Dej mu ruce na oči a nech je tam. Pak se dotýkej, kde chceš.|240|vedle_on_lezi",
    "Nech ho stát a dotýkej se ho, zatímco se drží zdi.|240|zed",
    "Řekni mu jedno slovo, po kterém vždycky přestaneš. A ať ho použije.|300|vedle_on_lezi",
    "Dotýkej se ho přes prostěradlo. Nikdy pod ním.|180|vedle_on_lezi",
    "Tři za minutu: Na každou minutu máš povolené jen tři doteky, vyber je dobře. Cíl: vydržet pět minut.|300|vedle_on_lezi",
    "Nech ho ležet na břiše a dotýkej se ho jen na zadní straně těla.|300|masaz_zada!",
    "Zavaž mu oči a nech ho poznat po hmatu, jakou částí těla ho hladíš.|240|vedle_on_lezi",
    "Dotýkej se ho a pokaždé, když se zasměje, začínáš od hlavy.|240|vedle_on_lezi",
    "Sedni si mu na klín zády a nehýbej se, dokud nezačne prosit.|240|klin_zady",
    "Jeden prst a hodně času: Celý úkol se ho smíš dotýkat jen jedním prstem. Cíl: dokázat, že to stačí.|300|vedle_on_lezi",
    "Nech ho, ať drží kostku ledu, dokud ji celou nerozpustí. Mezitím ho hlaď.|240|vedle_on_lezi",
    "Dotýkej se ho a mezi doteky se vždy na chvíli úplně vzdal.|240|vedle_on_lezi",
    "Nech ho vybrat, jestli chce vidět, nebo cítit. Když si vybere vidět, zavážeš mu oči.|240|vedle_on_lezi",
    "Dotýkej se ho, ale nikdy oběma rukama najednou.|240|vedle_on_lezi",
    "Deset a pauza: Deset vteřin se mu věnuješ, deset vteřin nic. A tak dokola. Cíl: nikdy pauzu nevynechat.|300|vedle_on_lezi",
    "Nech ho klečet a dotýkej se ho shora. On nesmí zvednout ruce.|240|klek_ruce_hlava!",
    "Dotýkej se ho a ptej se ho po každém doteku, jestli chce znovu.|240|vedle_on_lezi",
    "Zavaž mu oči a nech ho hledat tvoje rty jen podle dechu.|180|objeti",
    "Dotýkej se ho přesně tak, jak ti to předvedl na sobě.|240|vedle_on_lezi",
    "Vlastní tempo: On počítá nahlas do dvaceti a ty se musíš stihnout dotknout každého čísla jinde. Cíl: dvacet různých míst.|180|vedle_on_lezi",
    "Dotýkej se ho, dokud neřekne stop. Pak počkej, dokud neřekne pokračuj.|300|vedle_on_lezi",
    "Nech ho ležet mezi tvýma nohama a hlaď ho odshora.|300|klin_podlaha!",
    "Dotýkej se ho jen přes jednu vrstvu oblečení, kterou si sám vybere.|240|vedle_on_lezi",
    "Nakonec mu sundej šátek a nech ho, ať se na tebe podívá. Nic neříkej.|60|vedle_on_lezi",
  ],
});
