// Kategorie 2 – Smyslné doteky (dávka e)
// Témata: polohy pro doteky, svázané ruce, jemný vibrátor, rytmus a společné tempo.
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 2,

  male: [
    "Shora dolů oběma rukama: Posaď si ji před sebe zády, roztáhni jí kolena a hlaď ji oběma rukama shora dolů. Cíl: dvacet cest a žádná rychlejší.|300|klin_podlaha",
    "Stejné tempo oba: Sedněte si proti sobě, propleťte si nohy a dotýkejte se navzájem zároveň. Cíl: pět minut a tempo ani jednou nerozejít.|300|sed_celem",
    "Zády k sobě: Sedněte si zády k sobě a dotýkejte se každý sám sebe. Smíte se opírat, nic víc. Cíl: vydržet celou dobu zády k sobě.|240|sed_zady",
    "Od kolen k ramenům: Lehni si na záda, nech ji sednout si na tebe a hlaď ji od kolen až po ramena. Cíl: dvacet cest a ani jednou ji nepustit.|300|ona_nahore",
    "Lžička a dvě role rukou: Lehni si za ni na bok, jednou rukou ji dráždi zepředu a druhou jí drž hlavu. Cíl: pět minut a ani jednou polohu nezměnit.|300|lzicka",
    "Kravata nad hlavou: Sváž jí ruce kravatou nad hlavou tak, aby uzel šel rozvázat jedním tahem, a dotýkej se jí. Cíl: nepřestat, dokud se nezačne vzpírat.|300|pouta_postel",
    "Objetí ve svázaných rukou: Sváž jí zápěstí kravatou před tělem, uzel volně, a nech ji, ať tě takhle objímá. Cíl: čtyři minuty a nepustit ji.|240|objeti",
    "Ruce v klidu: Ona má ruce svázané a nesmí se hýbat. Ty ji prozkoumáš od hlavy k patě. Cíl: nevynechat nic.|300|pouta_postel",
    "Jen bradavky: Přilož jí vibrátor na bradavky na nejnižší stupeň. Cíl: tři minuty a nesjet s ním nikam jinam, ať prosí, jak chce.|180|vedle_ona_lezi",
    "Všude kromě: Přejeď jí vibrátorem po celém těle, ale mezi nohy s ním nesmíš. Cíl: čtyři minuty a ani jednou porušit zákaz.|240|vedle_ona_lezi",
    "Nehybný vibrátor: Přilož jí vibrátor přes kalhotky a drž ho tam úplně bez pohybu. Cíl: tři minuty a nepohnout s ním ani o milimetr.|180|vedle_ona_lezi",
    "Nejnižší stupeň: Použij vibrátor na nejslabší nastavení a nikdy ho nezesiluj. Cíl: dovést ji tam jen tímhle.|300|vedle_ona_lezi",
    "Vede si ho sama: Dej jí vibrátor do ruky a nech ji, ať si ho vede sama. Ty ji jen hladíš. Cíl: pět minut a nesáhnout na vibrátor ani jednou.|300|lzicka",
    "Půl minuty a výměna: Střídej vibrátor a vlastní ruku přesně po půl minutě. Cíl: deset střídání a ani jednou nepřetáhnout čas.|300|vedle_ona_lezi",
    "Na všech čtyřech a jen hladit: Ona klečí na všech čtyřech a ty jí hladíš záda, boky a stehna. Cíl: čtyři minuty a mezi nohy nesáhnout.|240|zezadu",
    "Od ramen ke kolenům: Nech ji opřít se o zeď a hlaď ji zezadu od ramen až ke kolenům. Cíl: dvacet cest a ani jednou se nezastavit.|240|zed",
    "Dokud ji udržíš: Zvedni ji do náruče a líbej ji. Cíl: udržet ji aspoň minutu a půl a nepoložit ji, dokud neřekne.|90|zvednuta",
    "Stehna zevnitř: Posaď ji na kraj postele, klekni si před ni a hlaď jí stehna zevnitř. Cíl: pět minut a výš než k tříslům nesahat.|300|oral_vsede",
    "Do rytmu: Najděte společný rytmus dechu a dotýkej se jí přesně v něm. Cíl: udržet stejné tempo celou dobu.|300|propletene",
    "Váha místo rukou: Lehni si na ni celým tělem a pohybuj se jen pomalu, bez rukou. Cíl: čtyři minuty a ruce mít celou dobu nad hlavou.|240|propletene",
    "Propletené prsty: Lehni si na ni, když leží na břiše, hlaď jí ruce a proplétej si s ní prsty. Cíl: čtyři minuty a ani jednou prsty nerozpojit.|240|na_brise",
    "Sleduje si to v zrcadle: Sedni si jí za záda a hlaď jí prsa, zatímco se dívá do zrcadla. Cíl: nepřestat, dokud sama nezavře oči.|240|klin_podlaha",
    "Jen se opírat: Nech ji sedět obkročmo na tvém klíně a jen se o sebe opírejte. Cíl: tři minuty, při kterých se ani jeden nepohne.|180|klin_celem",
    "Nová poloha každou minutu: Hlaď ji po celém těle a po každé minutě změňte polohu. Cíl: pět poloh a hlazení ani jednou nepřerušit.|300|vedle_ona_lezi",
    "Tři polohy: Během úkolu vystřídáte tři různé polohy a v každé ji hladíš jinak. Cíl: plynulý přechod bez přerušení.|300|lzicka",
    "Svázaná na židli: Sváž jí ruce kravatou, uzel nech volný, posaď ji na židli a věnuj se jí. Cíl: pět minut a ani jednou ji neodvázat.|300|zidle_celem",
    "Jen vlasy a tváře: Ona klečí, ty stojíš a hladíš ji po vlasech a tvářích. Nic víc. Cíl: tři minuty a nezkusit nic dalšího.|180|oral_ona_klek",
    "Přes tvoje nohy: Nech ji lehnout si břichem přes tvoje nohy a hlaď jí záda a zadeček. Cíl: čtyři minuty a ani jednou ji nenechat sklouznout.|240|masaz_zada",
    "Kolena o kolena: Lehněte si proti sobě na bok tak, abyste se dotýkali koleny, a hlaďte se navzájem. Cíl: pět minut a kolena neoddělit.|300|lzicka",
    "Dvě ruce, dvě místa: Jednou rukou ji hlaď nahoře, druhou dole, a nikdy je neprohoď. Cíl: udržet obě v pohybu.|300|vedle_ona_lezi",
    "Jedna dlouhá trasa: Přitiskni se k ní zezadu a hlaď ji jednou nepřerušenou trasou přes celé tělo. Cíl: deset takových tras bez jediné pauzy.|240|lzicka",
    "Nohy přes tvoje stehna: Nech ji ležet na zádech s nohama přes tvoje stehna a hlaď ji mezi nimi. Cíl: pět minut a nenechat ji nohy stáhnout.|300|vedle_ona_lezi",
    "Ona drží, ty líbáš: Dej jí vibrátor do ruky, ať si ho drží kde chce, a ty ji celou dobu líbej. Cíl: pět minut a polibek ani jednou nepřerušit.|300|vedle_ona_lezi",
    "Nahoře i dole naráz: Ona sedí na tobě zády a ty jí hladíš prsa i podbřišek zároveň. Cíl: pět minut a obě ruce ve stejném rytmu.|300|ona_nahore_zady",
    "Centimetr po centimetru výš: Přilož jí vibrátor na vnitřní stranu stehna a postupuj s ním výš. Cíl: dostat se ke klínu nejdřív po třech minutách.|240|vedle_ona_lezi",
    "Pomalu nahoru: Začni vibrátorem u kotníků a dostaň se s ním až nahoru za celé tři minuty. Cíl: nepřeskočit ani kus.|180|vedle_ona_lezi",
    "Ruce u stehen: Sváž jí ruce kravatou volně ke stehnům a jemně ji dráždi. Cíl: pět minut a kdykoli řekne stop, hned ji rozvázat.|300|vedle_ona_lezi",
    "Drží se opěradla: Nech ji stát a držet se opěradla a hlaď ji zezadu od ramen po stehna. Cíl: čtyři minuty a ona se nesmí narovnat.|240|predklon",
    "Jen chodidla: Lehněte si tak, abyste se dotýkali jen chodidly, a hlaďte si navzájem nohy. Cíl: tři minuty a nesáhnout na sebe rukama.|180|sed_celem",
    "Jedna nahoře, druhá všude: Hlaď ji jednou rukou po celém těle a druhou jí drž ruku nad hlavou. Cíl: pět minut a ani jednou ji nepustit.|300|vedle_ona_lezi",
    "Rytmus dvou: Ona říká rychleji nebo pomaleji a ty se okamžitě přizpůsobíš. Cíl: nikdy nezaváhat.|300|vedle_ona_lezi",
    "Zezadu a po zádech: Přilož jí vibrátor zezadu, když leží na břiše, a druhou rukou jí hlaď záda. Cíl: čtyři minuty a nenechat ji se otočit.|240|na_brise",
    "Klečí a čeká: Nech ji klečet mezi tvýma nohama a jen ji hlaď po ramenou. Cíl: tři minuty a nedovolit jí začít cokoli dalšího.|180|oral_ona_klek",
    "Záda odshora dolů: Ona sedí na tobě čelem a ty jí hladíš záda od šíje až ke kříži. Cíl: dvacet cest a každá aspoň deset vteřin.|240|klin_celem",
    "Přejeď jí vibrátorem po zádech podél páteře. Je to jiný pocit, než čeká.|180|masaz_zada",
    "Dvě minuty vibrací: Přilož jí vibrátor a drž ho přesně dvě minuty na jednom místě. Cíl: nepohnout s ním.|120|vedle_ona_lezi",
    "Sváž jí ruce kravatou za zády a posaď si ji na klín.|300|klin_zady",
    "Nech ji ležet napříč postelí a hlaď ji ze strany, jak ti to sedne.|240|vedle_ona_lezi",
    "Ona stojí u zdi a ty ji hladíš zepředu, ale nesmíš se opřít.|240|zed",
    "Hlaď ji tak, aby se celou dobu musela držet čela postele.|300|pouta_postel",
    "Beze změny: Vyber jedno tempo a jedno místo a nezměň to celých pět minut. Cíl: vydržet stereotyp.|300|vedle_ona_lezi",
    "Lehni si na záda a nech ji, ať se o tebe opře zády. Hlaď ji odspodu.|300|propletene",
    "Přilož jí vibrátor na bradavku a rukou ji dráždi mezi nohama.|300|vedle_ona_lezi",
    "Nech ji, ať drží vibrátor u sebe, a ty jí u toho olizuj bradavky.|300|vedle_ona_lezi",
    "Sváž jí ruce a nech ji stát. Pak ji celou prozkoumej ve stoje.|300|klek_ruce_za_zady",
    "Klekni si za ni na posteli a hlaď ji přes celá záda a boky.|240|zezadu_vzpr",
    "Hlaď ji v poloze, kterou si sama vybere. Ale jen v té jedné.|300|vedle_ona_lezi",
    "Střídání poloh: Po každé minutě změňte polohu, ale ty hlaď dál, jako by se nic nestalo. Cíl: pět poloh za sebou bez jediného přerušení.|300|lzicka",
    "Nech ji sedět na tobě a jen ji drž. Pohyb dělá jen ona.|240|ona_nahore",
    "Přilož jí vibrátor pod prostěradlo, ať nevidí, kam míří.|240|vedle_ona_lezi",
    "Hlaď ji po zádech, zatímco leží na tobě celou vahou.|240|propletene",
    "Sváž jí kravatou jednu ruku k posteli. Druhou má volnou.|300|pouta_postel",
    "Lehni si k ní a hlaďte se navzájem, ale každý jen jednou rukou.|300|lzicka",
    "Dvojí tempo: Jednou rukou se hýbej pomalu, druhou rychle. Nezaměň je. Cíl: vydržet obojí zároveň.|240|vedle_ona_lezi",
    "Ona leží na kraji postele a ty stojíš. Hlaď ji odshora.|240|kraj_postele",
    "Přilož jí vibrátor a druhou rukou jí drž ruce nad hlavou.|300|vedle_ona_lezi",
    "Nech ji ležet mezi tvýma nohama a hlaď jí prsa a krk.|300|klin_podlaha",
    "Hlaď ji jen tam, kde má opálenou kůži. Nikde jinde.|180|vedle_ona_lezi",
    "Sedni si za ni na posteli a hlaď ji dlouhými tahy od krku ke stehnům.|300|klin_podlaha",
    "Cesta tam a zpět: Projeď jí rukou od kotníků až k šíji a zase zpátky dolů. Cíl: pět cest a každá musí trvat stejně dlouho.|300|masaz_zada",
    "Ona klečí na posteli a ty za ní. Hlaď jí prsa a břicho zezadu.|240|zezadu_vzpr",
    "Přilož jí vibrátor na hráz a nech ho tam bez pohybu.|180|vedle_ona_lezi",
    "Hlaď ji tak, aby se nemohla opřít o nic jiného než o tebe.|240|objeti",
    "Nech ji ležet a hlaď ji jen rukama, které si předtím zahřeješ.|240|vedle_ona_lezi",
    "Do vrcholu rukou: Dostaň ji přes hranu jen rukou a v poloze, kterou si vybere ona. Cíl: nechat ji vybrat.|300|vedle_ona_lezi",
    "Sedni si jí na stehna a hlaď ji odshora dolů celou vahou dlaní.|240|masaz_zada",
    "Nech ji ležet na boku a přilož jí vibrátor zezadu.|300|lzicka",
    "Hlaď ji jednou rukou a druhou si veď její ruku po svém těle.|300|lzicka",
    "Sváž jí ruce a nech ji ležet na břiše. Hlaď jí záda a zadeček.|300|na_brise",
    "Přiklop se na ni a hlaď ji, dokud se ti neodevzdá úplně.|300|propletene",
    "Poslední poloha: Vyberte spolu polohu, ve které chcete skončit, a v ní ji hlaď až do konce. Cíl: dohodnout se beze slov.|300|lzicka",
    "Nech ji sedět na tobě obkročmo a hlaď jí záda i zadeček najednou.|300|klin_celem",
    "Hlaď ji tak dlouho, dokud se sama nepohne k tobě.|240|lzicka",
    "Nakonec si ji jen přitáhni k sobě a nech ruce ležet.|60|lzicka",
  ],

  female: [
    "Jeho ruce shora dolů: Sedni si mu mezi nohy zády a nech si od něj hladit celé tělo shora dolů. Cíl: pět minut a ani jednou mu neříct, kde.|300|klin_podlaha",
    "Ve stejném tempu: Sedněte si proti sobě, propleťte si nohy a dotýkejte se navzájem zároveň. Cíl: pět minut a tempo ani jednou nerozejít.|300|sed_celem",
    "Opřeni o sebe: Opři se o jeho záda a dotýkej se sama sebe. Víc než opřít se nesmíte. Cíl: vydržet celou dobu zády k němu.|240|sed_zady",
    "Hrudník a ramena: Sedni si na něj a hlaď mu hrudník a ramena, zatímco leží. Cíl: pět minut a pod pas nesjet ani jednou.|300|ona_nahore",
    "Za jeho zády na boku: Lehni si za něj na bok, jednou rukou ho dráždi zepředu a druhou mu drž hlavu. Cíl: pět minut a ani jednou polohu nezměnit.|300|lzicka",
    "Kravata nad jeho hlavou: Sváž mu ruce kravatou nad hlavou tak, aby uzel šel rozvázat jedním tahem, a dotýkej se ho. Cíl: nepřestat, dokud se nezačne vzpírat.|300|pouta_postel!",
    "Svázané objetí: Sváž mu zápěstí kravatou před tělem, uzel volně, a nech ho, ať tě takhle objímá. Cíl: čtyři minuty a nepustit ho.|240|objeti",
    "Ruce v klidu: On má ruce svázané a nesmí se hýbat. Ty ho prozkoumáš od hlavy k patě. Cíl: nevynechat nic.|300|pouta_postel!",
    "Nikam jinam: Přilož mu vibrátor na bradavky na nejnižší stupeň. Cíl: tři minuty a nesjet s ním nikam jinam, ať prosí, jak chce.|180|vedle_on_lezi",
    "Zakázaná zóna: Přejeď mu vibrátorem po celém těle, ale mezi nohy s ním nesmíš. Cíl: čtyři minuty a ani jednou porušit zákaz.|240|vedle_on_lezi",
    "Bez jediného pohybu: Přilož mu vibrátor přes trenýrky a drž ho tam úplně bez pohybu. Cíl: tři minuty a nepohnout s ním ani o milimetr.|180|vedle_on_lezi",
    "Nejnižší stupeň: Použij vibrátor na nejslabší nastavení a nikdy ho nezesiluj. Cíl: dovést ho tam jen tímhle.|300|vedle_on_lezi",
    "Vede si ho sám: Dej mu vibrátor do ruky a nech ho, ať si ho vede sám. Ty ho jen hladíš. Cíl: pět minut a nesáhnout na vibrátor ani jednou.|300|lzicka",
    "Výměna po půl minutě: Střídej vibrátor a vlastní ruku přesně po půl minutě. Cíl: deset střídání a ani jednou nepřetáhnout čas.|300|vedle_on_lezi",
    "Na čtyřech a jen hladit: On klečí na všech čtyřech a ty mu hladíš záda, boky a stehna. Cíl: čtyři minuty a mezi nohy nesáhnout.|240|zezadu!",
    "Ramena až kolena: Nech ho opřít se o zeď a hlaď ho zezadu od ramen až ke kolenům. Cíl: dvacet cest a ani jednou se nezastavit.|240|zed",
    "Dokud tě udrží: Nech se od něj zvednout, drž se ho a líbej ho. Cíl: vydržet nahoře aspoň minutu a půl.|90|zvednuta",
    "Jeho stehna zevnitř: Posaď ho na kraj postele, klekni si před něj a hlaď mu stehna zevnitř. Cíl: pět minut a výš než k tříslům nesahat.|300|oral_on_vsede",
    "Do rytmu: Najděte společný rytmus dechu a dotýkej se ho přesně v něm. Cíl: udržet stejné tempo celou dobu.|300|propletene",
    "Bez jediné ruky: Lehni si na něj celým tělem a pohybuj se jen pomalu, bez rukou. Cíl: čtyři minuty a ruce mít celou dobu nad hlavou.|240|propletene",
    "Prsty v jeho prstech: Lehni si na něj, když leží na břiše, hlaď mu ruce a proplétej si s ním prsty. Cíl: čtyři minuty a prsty ani jednou nerozpojit.|240|na_brise!",
    "Vidí to v zrcadle: Sedni si mu za záda a hlaď mu hrudník, zatímco se dívá do zrcadla. Cíl: nepřestat, dokud sám nezavře oči.|240|klin_podlaha",
    "Opřít se a nic víc: Sedni si mu obkročmo na klín a jen se o sebe opírejte. Cíl: tři minuty, při kterých se ani jeden nepohne.|180|klin_celem",
    "Poloha za polohou: Hlaď ho po celém těle a po každé minutě změňte polohu. Cíl: pět poloh a hlazení ani jednou nepřerušit.|300|vedle_on_lezi",
    "Tři polohy: Během úkolu vystřídáte tři různé polohy a v každé ho hladíš jinak. Cíl: plynulý přechod bez přerušení.|300|lzicka",
    "Svázaný na židli: Sváž mu ruce kravatou, uzel nech volný, posaď ho na židli a věnuj se mu. Cíl: pět minut a ani jednou ho neodvázat.|300|zidle_celem",
    "Vlasy a tváře: On klečí, ty stojíš a hladíš ho po vlasech a tvářích. Nic víc. Cíl: tři minuty a nezkusit nic dalšího.|180|oral_ona_klek",
    "Přes tvůj klín: Nech ho lehnout si břichem přes tvoje nohy a hlaď mu záda a zadek. Cíl: čtyři minuty a ani jednou ho nenechat sklouznout.|240|masaz_zada",
    "Kolena se dotýkají: Lehněte si proti sobě na bok tak, abyste se dotýkali koleny, a hlaďte se navzájem. Cíl: pět minut a kolena neoddělit.|300|lzicka",
    "Dvě ruce, dvě místa: Jednou rukou ho hlaď nahoře, druhou dole, a nikdy je neprohoď. Cíl: udržet obě v pohybu.|300|vedle_on_lezi",
    "Dlouhá trasa: Přitiskni se k němu zezadu a hlaď ho jednou nepřerušenou trasou přes celé tělo. Cíl: deset takových tras bez jediné pauzy.|240|lzicka",
    "Jeho nohy přes tvoje: Nech ho ležet na zádech s nohama přes tvoje stehna a hlaď ho mezi nimi. Cíl: pět minut a nenechat ho nohy stáhnout.|300|vedle_on_lezi",
    "On drží, ty líbáš: Dej mu vibrátor do ruky, ať si ho drží kde chce, a ty ho celou dobu líbej. Cíl: pět minut a polibek ani jednou nepřerušit.|300|vedle_on_lezi",
    "Jeho ruce na tobě: Sedni si na něj zády a polož si jeho ruce na prsa a podbřišek. Cíl: pět minut a nenechat ho je posunout jinam.|300|ona_nahore_zady",
    "Pomalu výš: Přilož mu vibrátor na vnitřní stranu stehna a postupuj s ním výš. Cíl: dostat se k rozkroku nejdřív po třech minutách.|240|vedle_on_lezi",
    "Zdola nahoru: Přilož mu vibrátor ke kotníkům a nech mu tři minuty, než dojedeš nahoru. Cíl: nepřeskočit ani kus.|180|vedle_on_lezi",
    "Ruce u jeho stehen: Sváž mu ruce kravatou volně ke stehnům a jemně ho dráždi. Cíl: pět minut a kdykoli řekne stop, hned ho rozvázat.|300|vedle_on_lezi",
    "Drží se opěradla on: Nech ho stát a držet se opěradla a hlaď ho zezadu od ramen po stehna. Cíl: čtyři minuty a on se nesmí narovnat.|240|predklon!",
    "Chodidlo o chodidlo: Opřete se o sebe chodidly a hlaďte si navzájem lýtka a nárty. Cíl: tři minuty a nesáhnout na sebe jinde.|180|sed_celem",
    "Jedna drží, druhá putuje: Hlaď ho jednou rukou po celém těle a druhou mu drž ruku nad hlavou. Cíl: pět minut a ani jednou ho nepustit.|300|vedle_on_lezi",
    "Rytmus dvou: On říká rychleji nebo pomaleji a ty se okamžitě přizpůsobíš. Cíl: nikdy nezaváhat.|300|vedle_on_lezi",
    "Přilož mu vibrátor zezadu, když leží na břiše, a druhou rukou mu hlaď záda.|240|na_brise!",
    "Klekni si mu mezi nohy a jen mu hlaď stehna a břicho.|180|oral_on_vleze",
    "Sedni si na něj čelem a hlaď ho po hrudníku odshora dolů.|240|klin_celem",
    "Přejeď mu vibrátorem po zádech podél páteře. Je to jiný pocit, než čeká.|180|masaz_zada!",
    "Dvě minuty vibrací: Přilož mu vibrátor a drž ho přesně dvě minuty na jednom místě. Cíl: nepohnout s ním.|120|vedle_on_lezi",
    "Sváž mu ruce kravatou za zády a sedni si mu na klín.|300|klin_zady",
    "Nech ho ležet napříč postelí a hlaď ho ze strany, jak ti to sedne.|240|vedle_on_lezi",
    "On stojí u zdi a ty ho hladíš zepředu, ale nesmíš se opřít.|240|zed",
    "Hlaď ho tak, aby se celou dobu musel držet čela postele.|300|pouta_postel!",
    "Pořád stejně: Zvol jedno místo a jedno tempo a pět minut se toho drž. Cíl: vydržet stereotyp.|300|vedle_on_lezi",
    "Lehni si na něj zády a nech se od něj hladit odspodu.|300|propletene",
    "Přilož mu vibrátor na bradavku a rukou ho dráždi mezi nohama.|300|vedle_on_lezi",
    "Nech ho, ať si drží vibrátor sám, a ty mu u toho olizuj bradavky.|300|vedle_on_lezi",
    "Sváž mu ruce a nech ho stát. Pak ho celého prozkoumej ve stoje.|300|klek_ruce_za_zady!",
    "Klekni si za něj na posteli a hlaď ho přes celá záda a boky.|240|zezadu_vzpr",
    "Hlaď ho v poloze, kterou si sám vybere. Ale jen v té jedné.|300|vedle_on_lezi",
    "Minuta a dál: Každou minutu změňte polohu a ty pokračuj, jako by se nic nedělo. Cíl: pět poloh za sebou.|300|lzicka",
    "Pohyb dělá on: Sedni si na něj, opři se o jeho hrudník a nehýbej se. Cíl: čtyři minuty, při kterých se hýbe jen on.|240|ona_nahore",
    "Přilož mu vibrátor pod prostěradlo, ať nevidí, kam míří.|240|vedle_on_lezi",
    "Hlaď mu záda, zatímco na něm ležíš celou vahou.|240|propletene",
    "Sváž mu kravatou jednu ruku k posteli. Druhou má volnou.|300|pouta_postel!",
    "Lehni si k němu a hlaďte se navzájem, ale každý jen jednou rukou.|300|lzicka",
    "Každá jinak: Pravá ruka pomalu, levá rychle – a ani jednou je neprohodíš. Cíl: vydržet obojí zároveň.|240|vedle_on_lezi",
    "On leží na kraji postele a ty stojíš. Hlaď ho odshora.|240|kraj_postele",
    "Přilož mu vibrátor a druhou rukou mu drž ruce nad hlavou.|300|vedle_on_lezi",
    "Nech ho ležet mezi tvýma nohama a hlaď mu hrudník a krk.|300|klin_podlaha!",
    "Hlaď ho jen tam, kde má opálenou kůži. Nikde jinde.|180|vedle_on_lezi",
    "Sedni si za něj na posteli a hlaď ho dlouhými tahy od krku ke stehnům.|300|klin_podlaha",
    "Tam a zase zpátky: Projeď mu rukou od kotníků až k šíji a zase zpátky dolů. Cíl: pět cest a každá musí trvat stejně dlouho.|300|masaz_zada!",
    "On klečí na posteli a ty za ním. Hlaď mu hrudník a břicho zezadu.|240|zezadu_vzpr!",
    "Přilož mu vibrátor na hráz a nech ho tam bez pohybu.|180|vedle_on_lezi",
    "Hlaď ho tak, aby se nemohl opřít o nic jiného než o tebe.|240|objeti",
    "Nech ho ležet a hlaď ho jen rukama, které si předtím zahřeješ.|240|vedle_on_lezi",
    "Do konce rukou: Dostaň ho přes hranu jen rukou a v poloze, kterou si vybere on. Cíl: nechat ho vybrat.|300|vedle_on_lezi",
    "Sedni si mu na stehna a hlaď ho odshora dolů celou vahou dlaní.|240|masaz_zada",
    "Nech ho ležet na boku a přilož mu vibrátor zezadu.|300|lzicka",
    "Hlaď ho jednou rukou a druhou si veď jeho ruku po svém těle.|300|lzicka",
    "Sváž mu ruce a nech ho ležet na břiše. Hlaď mu záda a zadek.|300|na_brise!",
    "Lehni si na něj a hlaď ho, dokud se ti neodevzdá úplně.|300|propletene",
    "Poslední poloha: Vyberte spolu polohu, ve které chcete skončit, a v ní ho hlaď až do konce. Cíl: dohodnout se beze slov.|300|lzicka",
    "Sedni si na něj obkročmo a hlaď mu záda i zadek najednou.|300|klin_celem",
    "Hlaď ho tak dlouho, dokud se sám nepohne k tobě.|240|lzicka",
    "Nakonec si ho jen přitáhni k sobě a nech ruce ležet.|60|lzicka",
  ],
});
