// Kategorie 2 – Smyslné doteky (dávka e)
// Témata: polohy pro doteky, svázané ruce, jemný vibrátor, rytmus a společné tempo.
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 2,

  male: [
    "Posaď si ji před sebe zády, roztáhni jí kolena a hlaď ji oběma rukama shora dolů.|300|klin_podlaha",
    "Sedni si proti ní a propleťte si nohy. Dotýkejte se navzájem zároveň a stejným tempem.|300|sed_celem",
    "Zády k sobě: Sedněte si zády k sobě a dotýkejte se každý sám sebe. Smíte se opírat, nic víc. Cíl: vydržet celou dobu zády k sobě.|240|sed_zady",
    "Lehni si na záda a nech ji sednout si na tebe. Hlaď ji od kolen po ramena.|300|ona_nahore",
    "Ona leží na boku, ty za ní. Jedna ruka vpředu, druhá pod hlavou.|300|lzicka",
    "Sváž jí ruce kravatou nad hlavou a dotýkej se jí, dokud se nezačne vzpírat.|300|pouta_postel",
    "Sváž jí zápěstí kravatou před tělem a nech ji, ať tě takhle svázaná objímá.|240|objeti",
    "Ruce v klidu: Ona má ruce svázané a nesmí se hýbat. Ty ji prozkoumáš od hlavy k patě. Cíl: nevynechat nic.|300|pouta_postel",
    "Přilož jí vibrátor na bradavky na nejnižší stupeň a nikam jinam.|180|vedle_ona_lezi",
    "Přejeď jí vibrátorem po celém těle, ale mezi nohy s ním nesmíš.|240|vedle_ona_lezi",
    "Přilož jí vibrátor přes kalhotky a drž ho tam bez pohybu.|180|vedle_ona_lezi",
    "Nejnižší stupeň: Použij vibrátor na nejslabší nastavení a nikdy ho nezesiluj. Cíl: dovést ji tam jen tímhle.|300|vedle_ona_lezi",
    "Dej jí vibrátor do ruky a nech ji, ať si ho vede sama. Ty ji jen hladíš.|300|lzicka",
    "Střídej vibrátor a vlastní ruku po půl minutě.|300|vedle_ona_lezi",
    "Ona klečí na všech čtyřech a ty jí hladíš záda, boky a stehna. Nic víc.|240|zezadu",
    "Ať se opře o zeď a ty ji hlaď zezadu od ramen až ke kolenům.|240|zed",
    "Zvedni ji a drž ji, dokud ti to jde. Mezitím ji líbej.|90|zvednuta",
    "Posaď ji na kraj postele, klekni si před ni a hlaď jí stehna zevnitř.|300|oral_vsede",
    "Do rytmu: Najděte společný rytmus dechu a dotýkej se jí přesně v něm. Cíl: udržet stejné tempo celou dobu.|300|propletene",
    "Lehni si na ni celým tělem a jen se pomalu pohybuj. Bez rukou.|240|propletene",
    "Ona leží na břiše, ty na ní. Hlaď jí ruce a proplétej si s ní prsty.|240|na_brise",
    "Sedni si jí za záda a hlaď jí prsa, zatímco se dívá do zrcadla.|240|klin_podlaha",
    "Nech ji sedět obkročmo na tvém klíně a jen se o sebe opírejte.|180|klin_celem",
    "Hlaď ji po celém těle a pokaždé změň polohu, ve které ležíte.|300|vedle_ona_lezi",
    "Tři polohy: Během úkolu vystřídáte tři různé polohy a v každé ji hladíš jinak. Cíl: plynulý přechod bez přerušení.|300|lzicka",
    "Sváž jí ruce a posaď ji na židli. Pak se jí věnuj tak dlouho, jak vydržíš.|300|zidle_celem",
    "Ona klečí, ty stojíš. Hlaď ji po vlasech a tvářích, nic víc.|180|oral_ona_klek",
    "Ať si lehne přes tvoje nohy a ty jí hlaď záda a zadeček.|240|masaz_zada",
    "Lehni si na bok proti ní tak, abyste se dotýkali koleny, a hlaďte se navzájem.|300|lzicka",
    "Dvě ruce, dvě místa: Jednou rukou ji hlaď nahoře, druhou dole, a nikdy je neprohoď. Cíl: udržet obě v pohybu.|300|vedle_ona_lezi",
    "Přiklop se k ní zezadu a hlaď ji přes celé tělo jednou dlouhou trasou.|240|lzicka",
    "Nech ji ležet na zádech s nohama přes tvoje stehna a hlaď ji mezi nimi.|300|vedle_ona_lezi",
    "Dej jí vibrátor do ruky a řekni jí, ať si ho drží, kde chce. Ty ji líbáš.|300|vedle_ona_lezi",
    "Ona sedí na tobě zády a ty jí hladíš prsa i podbřišek zároveň.|300|ona_nahore_zady",
    "Přilož jí vibrátor na vnitřní stranu stehna a pomalu s ním postupuj výš.|240|vedle_ona_lezi",
    "Pomalu nahoru: Začni vibrátorem u kotníků a dostaň se s ním až nahoru za celé tři minuty. Cíl: nepřeskočit ani kus.|180|vedle_ona_lezi",
    "Sváž jí ruce ke stehnům, ať se nemůže bránit, a dráždi ji jemně.|300|vedle_ona_lezi",
    "Nech ji stát a hlaď ji zezadu, zatímco se drží opěradla.|240|predklon",
    "Lehni si tak, abyste se dotýkali jen chodidly, a hlaďte si navzájem nohy.|180|sed_celem",
    "Ona leží a ty jí hladíš celé tělo jednou rukou a druhou jí držíš ruku nad hlavou.|300|vedle_ona_lezi",
    "Rytmus dvou: Ona říká rychleji nebo pomaleji a ty se okamžitě přizpůsobíš. Cíl: nikdy nezaváhat.|300|vedle_ona_lezi",
    "Přilož jí vibrátor zezadu, když leží na břiše, a druhou rukou jí hlaď záda.|240|na_brise",
    "Nech ji klečet mezi tvýma nohama a jen ji hlaď po ramenou.|180|oral_ona_klek",
    "Ona sedí na tobě čelem a ty ji hladíš po zádech odshora dolů.|240|klin_celem",
    "Přejeď jí vibrátorem po zádech podél páteře. Je to jiný pocit, než čeká.|180|masaz_zada",
    "Dvě minuty vibrací: Přilož jí vibrátor a drž ho přesně dvě minuty na jednom místě. Cíl: nepohnout s ním.|120|vedle_ona_lezi",
    "Sváž jí ruce kravatou za zády a posaď si ji na klín.|300|klin_zady",
    "Nech ji ležet napříč postelí a hlaď ji ze strany, jak ti to sedne.|240|vedle_ona_lezi",
    "Ona stojí u zdi a ty ji hladíš zepředu, ale nesmíš se opřít.|240|zed",
    "Hlaď ji tak, aby se celou dobu musela držet čela postele.|300|pouta_postel",
    "Beze změny: Vyber jedno tempo a jedno místo a nezměň to celých pět minut. Cíl: vydržet stereotyp.|300|vedle_ona_lezi",
    "Lehni si na záda a nech ji, ať se o tebe opře zády. Hlaď ji odspodu.|300|propletene",
    "Přilož jí vibrátor na bradavku a rukou ji dráždi mezi nohama.|300|vedle_ona_lezi",
    "Nech ji, ať drží vibrátor u sebe, a ty jí u toho olizuj bradavky.|300|vedle_ona_lezi",
    "Sváž jí ruce a nech ji stát. Pak ji celou prozkoumej ve stoje.|300|klek_ruce_za_zady",
    "Klekni si za ni na posteli a hlaď ji přes celá záda a boky.|240|zezadu_vzpr",
    "Hlaď ji v poloze, kterou si sama vybere. Ale jen v té jedné.|300|vedle_ona_lezi",
    "Střídání poloh: Po každé minutě změňte polohu. Ty musíš pokračovat, jako by se nic nestalo. Cíl: pět poloh za sebou.|300|lzicka",
    "Nech ji sedět na tobě a jen ji drž. Pohyb dělá jen ona.|240|ona_nahore",
    "Přilož jí vibrátor pod prostěradlo, ať nevidí, kam míří.|240|vedle_ona_lezi",
    "Hlaď ji po zádech, zatímco leží na tobě celou vahou.|240|propletene",
    "Sváž jí kravatou jednu ruku k posteli. Druhou má volnou.|300|pouta_postel",
    "Lehni si k ní a hlaďte se navzájem, ale každý jen jednou rukou.|300|lzicka",
    "Dvojí tempo: Jednou rukou se hýbej pomalu, druhou rychle. Nezaměň je. Cíl: vydržet obojí zároveň.|240|vedle_ona_lezi",
    "Ona leží na kraji postele a ty stojíš. Hlaď ji odshora.|240|kraj_postele",
    "Přilož jí vibrátor a druhou rukou jí drž ruce nad hlavou.|300|vedle_ona_lezi",
    "Nech ji ležet mezi tvýma nohama a hlaď jí prsa a krk.|300|klin_podlaha",
    "Hlaď ji jen tam, kde má opálenou kůži. Nikde jinde.|180|vedle_ona_lezi",
    "Sedni si za ni na posteli a hlaď ji dlouhými tahy od krku ke stehnům.|300|klin_podlaha",
    "Cesta tam a zpět: Projeď jí rukou od kotníků k šíji a zase zpět. Pětkrát. Cíl: pokaždé stejně dlouho.|300|masaz_zada",
    "Ona klečí na posteli a ty za ní. Hlaď jí prsa a břicho zezadu.|240|zezadu_vzpr",
    "Přilož jí vibrátor na hráz a nech ho tam bez pohybu.|180|vedle_ona_lezi",
    "Hlaď ji tak, aby se nemohla opřít o nic jiného než o tebe.|240|objeti",
    "Nech ji ležet a hlaď ji jen rukama, které si předtím zahřeješ.|240|vedle_ona_lezi",
    "Do vrcholu rukou: Dostaň ji přes hranu jen rukou a v poloze, kterou si vybere ona. Cíl: nechat ji vybrat.|300|vedle_ona_lezi",
    "Sedni si jí na stehna a hlaď ji odshora dolů celou vahou dlaní.|240|masaz_zada",
    "Nech ji ležet na boku a přilož jí vibrátor zezadu.|300|lzicka",
    "Hlaď ji jednou rukou a druhou si veď její ruku po svém těle.|300|lzicka",
    "Sváž jí ruce a nech ji ležet na břiše. Hlaď jí záda a zadeček.|300|na_brise",
    "Přiklop se na ni a hlaď ji, dokud se ti neodevzdá úplně.|300|propletene",
    "Poslední poloha: Vyberte spolu polohu, ve které chcete skončit, a v ní ji hlaď až do konce. Cíl: dohodnout se beze slov.|300|lzicka",
    "Nech ji sedět na tobě obkročmo a hlaď jí záda i zadeček najednou.|300|klin_celem",
    "Hlaď ji tak dlouho, dokud se sama nepohne k tobě.|240|lzicka",
    "Nakonec si ji jen přitáhni k sobě a nech ruce ležet.|60|lzicka",
  ],

  female: [
    "Sedni si mu mezi nohy zády a nech si od něj hladit celé tělo shora dolů.|300|klin_podlaha",
    "Sedni si proti němu a propleťte si nohy. Dotýkejte se navzájem zároveň a stejným tempem.|300|sed_celem",
    "Opřeni o sebe: Opři se o jeho záda a dotýkej se sama sebe. Víc než opřít se nesmíte. Cíl: vydržet celou dobu zády k němu.|240|sed_zady",
    "Sedni si na něj a hlaď mu hrudník a ramena, zatímco leží.|300|ona_nahore",
    "On leží na boku, ty za ním. Jedna ruka vpředu, druhá pod jeho hlavou.|300|lzicka",
    "Sváž mu ruce kravatou nad hlavou a dotýkej se ho, dokud se nezačne vzpírat.|300|pouta_postel",
    "Sváž mu zápěstí kravatou před tělem a nech ho, ať tě takhle svázaný objímá.|240|objeti",
    "Ruce v klidu: On má ruce svázané a nesmí se hýbat. Ty ho prozkoumáš od hlavy k patě. Cíl: nevynechat nic.|300|pouta_postel",
    "Přilož mu vibrátor na bradavky na nejnižší stupeň a nikam jinam.|180|vedle_on_lezi",
    "Přejeď mu vibrátorem po celém těle, ale mezi nohy s ním nesmíš.|240|vedle_on_lezi",
    "Přilož mu vibrátor přes trenýrky a drž ho tam bez pohybu.|180|vedle_on_lezi",
    "Nejnižší stupeň: Použij vibrátor na nejslabší nastavení a nikdy ho nezesiluj. Cíl: dovést ho tam jen tímhle.|300|vedle_on_lezi",
    "Dej mu vibrátor do ruky a nech ho, ať si ho vede sám. Ty ho jen hladíš.|300|lzicka",
    "Po půl minutě se vždycky vyměň – jednou vibrátor, podruhé tvoje ruka.|300|vedle_on_lezi",
    "On klečí na všech čtyřech a ty mu hladíš záda, boky a stehna. Nic víc.|240|zezadu",
    "Ať se opře o zeď a ty ho hlaď zezadu od ramen až ke kolenům.|240|zed",
    "Nech se od něj zvednout a drž se ho, dokud to jde. Mezitím ho líbej.|90|zvednuta",
    "Posaď ho na kraj postele, klekni si před něj a hlaď mu stehna zevnitř.|300|oral_on_vsede",
    "Do rytmu: Najděte společný rytmus dechu a dotýkej se ho přesně v něm. Cíl: udržet stejné tempo celou dobu.|300|propletene",
    "Lehni si na něj celým tělem a jen se pomalu pohybuj. Bez rukou.|240|propletene",
    "On leží na břiše, ty na něm. Hlaď mu ruce a proplétej si s ním prsty.|240|na_brise",
    "Sedni si mu za záda a hlaď mu hrudník, zatímco se dívá do zrcadla.|240|klin_podlaha",
    "Sedni si mu obkročmo na klín a jen se o sebe opírejte.|180|klin_celem",
    "Hlaď ho po celém těle a pokaždé změň polohu, ve které ležíte.|300|vedle_on_lezi",
    "Tři polohy: Během úkolu vystřídáte tři různé polohy a v každé ho hladíš jinak. Cíl: plynulý přechod bez přerušení.|300|lzicka",
    "Sváž mu ruce a posaď ho na židli. Pak se mu věnuj tak dlouho, jak vydržíš.|300|zidle_celem",
    "On klečí, ty stojíš. Hlaď ho po vlasech a tvářích, nic víc.|180|oral_ona_klek",
    "Ať si lehne přes tvoje nohy a ty mu hlaď záda a zadek.|240|masaz_zada",
    "Lehni si na bok proti němu tak, abyste se dotýkali koleny, a hlaďte se navzájem.|300|lzicka",
    "Dvě ruce, dvě místa: Jednou rukou ho hlaď nahoře, druhou dole, a nikdy je neprohoď. Cíl: udržet obě v pohybu.|300|vedle_on_lezi",
    "Přiklop se k němu zezadu a hlaď ho přes celé tělo jednou dlouhou trasou.|240|lzicka",
    "Nech ho ležet na zádech s nohama přes tvoje stehna a hlaď ho mezi nimi.|300|vedle_on_lezi",
    "Dej mu vibrátor do ruky a řekni mu, ať ho drží, kde chce. Ty ho líbáš.|300|vedle_on_lezi",
    "Sedni si na něj zády a nech si jeho ruce položit na prsa i podbřišek.|300|ona_nahore_zady",
    "Přilož mu vibrátor na vnitřní stranu stehna a pomalu s ním postupuj výš.|240|vedle_on_lezi",
    "Zdola nahoru: Přilož mu vibrátor ke kotníkům a nech mu tři minuty, než dojedeš nahoru. Cíl: nepřeskočit ani kus.|180|vedle_on_lezi",
    "Sváž mu ruce ke stehnům, ať se nemůže bránit, a dráždi ho jemně.|300|vedle_on_lezi",
    "Nech ho stát a hlaď ho zezadu, zatímco se drží opěradla.|240|predklon",
    "Opřete se o sebe chodidly a hlaďte si navzájem lýtka a nárty.|180|sed_celem",
    "On leží a ty mu hladíš celé tělo jednou rukou a druhou mu držíš ruku nad hlavou.|300|vedle_on_lezi",
    "Rytmus dvou: On říká rychleji nebo pomaleji a ty se okamžitě přizpůsobíš. Cíl: nikdy nezaváhat.|300|vedle_on_lezi",
    "Přilož mu vibrátor zezadu, když leží na břiše, a druhou rukou mu hlaď záda.|240|na_brise",
    "Klekni si mu mezi nohy a jen mu hlaď stehna a břicho.|180|oral_on_vleze",
    "Sedni si na něj čelem a hlaď ho po hrudníku odshora dolů.|240|klin_celem",
    "Přejeď mu vibrátorem po zádech podél páteře. Je to jiný pocit, než čeká.|180|masaz_zada",
    "Dvě minuty vibrací: Přilož mu vibrátor a drž ho přesně dvě minuty na jednom místě. Cíl: nepohnout s ním.|120|vedle_on_lezi",
    "Sváž mu ruce kravatou za zády a sedni si mu na klín.|300|klin_zady",
    "Nech ho ležet napříč postelí a hlaď ho ze strany, jak ti to sedne.|240|vedle_on_lezi",
    "On stojí u zdi a ty ho hladíš zepředu, ale nesmíš se opřít.|240|zed",
    "Hlaď ho tak, aby se celou dobu musel držet čela postele.|300|pouta_postel",
    "Pořád stejně: Zvol jedno místo a jedno tempo a pět minut se toho drž. Cíl: vydržet stereotyp.|300|vedle_on_lezi",
    "Lehni si na něj zády a nech se od něj hladit odspodu.|300|propletene",
    "Přilož mu vibrátor na bradavku a rukou ho dráždi mezi nohama.|300|vedle_on_lezi",
    "Nech ho, ať si drží vibrátor sám, a ty mu u toho olizuj bradavky.|300|vedle_on_lezi",
    "Sváž mu ruce a nech ho stát. Pak ho celého prozkoumej ve stoje.|300|klek_ruce_za_zady",
    "Klekni si za něj na posteli a hlaď ho přes celá záda a boky.|240|zezadu_vzpr",
    "Hlaď ho v poloze, kterou si sám vybere. Ale jen v té jedné.|300|vedle_on_lezi",
    "Minuta a dál: Každou minutu změňte polohu a ty pokračuj, jako by se nic nedělo. Cíl: pět poloh za sebou.|300|lzicka",
    "Sedni si na něj a jen se o něj opři. Pohyb dělá jen on.|240|ona_nahore",
    "Přilož mu vibrátor pod prostěradlo, ať nevidí, kam míří.|240|vedle_on_lezi",
    "Hlaď mu záda, zatímco na něm ležíš celou vahou.|240|propletene",
    "Sváž mu kravatou jednu ruku k posteli. Druhou má volnou.|300|pouta_postel",
    "Lehni si k němu a hlaďte se navzájem, ale každý jen jednou rukou.|300|lzicka",
    "Každá jinak: Pravá ruka pomalu, levá rychle – a ani jednou je neprohodíš. Cíl: vydržet obojí zároveň.|240|vedle_on_lezi",
    "On leží na kraji postele a ty stojíš. Hlaď ho odshora.|240|kraj_postele",
    "Přilož mu vibrátor a druhou rukou mu drž ruce nad hlavou.|300|vedle_on_lezi",
    "Nech ho ležet mezi tvýma nohama a hlaď mu hrudník a krk.|300|klin_podlaha",
    "Hlaď ho jen tam, kde má opálenou kůži. Nikde jinde.|180|vedle_on_lezi",
    "Sedni si za něj na posteli a hlaď ho dlouhými tahy od krku ke stehnům.|300|klin_podlaha",
    "Cesta tam a zpět: Projeď mu rukou od kotníků k šíji a zase zpět. Pětkrát. Cíl: pokaždé stejně dlouho.|300|masaz_zada",
    "On klečí na posteli a ty za ním. Hlaď mu hrudník a břicho zezadu.|240|zezadu_vzpr",
    "Přilož mu vibrátor na hráz a nech ho tam bez pohybu.|180|vedle_on_lezi",
    "Hlaď ho tak, aby se nemohl opřít o nic jiného než o tebe.|240|objeti",
    "Nech ho ležet a hlaď ho jen rukama, které si předtím zahřeješ.|240|vedle_on_lezi",
    "Do konce rukou: Dostaň ho přes hranu jen rukou a v poloze, kterou si vybere on. Cíl: nechat ho vybrat.|300|vedle_on_lezi",
    "Sedni si mu na stehna a hlaď ho odshora dolů celou vahou dlaní.|240|masaz_zada",
    "Nech ho ležet na boku a přilož mu vibrátor zezadu.|300|lzicka",
    "Hlaď ho jednou rukou a druhou si veď jeho ruku po svém těle.|300|lzicka",
    "Sváž mu ruce a nech ho ležet na břiše. Hlaď mu záda a zadek.|300|na_brise",
    "Lehni si na něj a hlaď ho, dokud se ti neodevzdá úplně.|300|propletene",
    "Poslední poloha: Vyberte spolu polohu, ve které chcete skončit, a v ní ho hlaď až do konce. Cíl: dohodnout se beze slov.|300|lzicka",
    "Sedni si na něj obkročmo a hlaď mu záda i zadek najednou.|300|klin_celem",
    "Hlaď ho tak dlouho, dokud se sám nepohne k tobě.|240|lzicka",
    "Nakonec si ho jen přitáhni k sobě a nech ruce ležet.|60|lzicka",
  ],
});
