// Kategorie 2 – Smyslné doteky (dávka c)
// Témata: dráždění přes prádlo, vzájemná masturbace, vedená ruka, edging rukou.
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 2,

  male: [
    "Dráždi ji přes kalhotky jedním prstem, dokud látka nezvlhne. Teprve pak je smíš sundat.|180|vedle_ona_lezi",
    "Polož jí dlaň mezi nohy přes prádlo a jen ji tam nech. Nehýbej se, dokud se o ni sama neotře.|120|vedle_ona_lezi",
    "Vedená ruka: Vezmi její ruku a nech ji, ať ti ukáže přesně, jak se má dotýkat. Ty jen kopíruješ. Cíl: naučit se to přesně.|180|vedle_ona_lezi",
    "Dráždi ji prsty tak pomalu, jak jen dokážeš. Za tři minuty smíš udělat nejvýš třicet pohybů.|180|vedle_ona_lezi",
    "Nech ji, ať si sama sáhne, a ty jí jen drž ruku a díváš se.|180|lzicka",
    "Prsty zvenku: Dráždi ji jen po okrajích, nikdy přímo na klitorisu. Cíl: ať si tvoji ruku sama posune.|180|vedle_ona_lezi",
    "Lehni si za ni na lžičku a dráždi ji rukou zepředu. Do ucha jí u toho šeptej.|240|lzicka",
    "Namaž si prsty lubrikantem a krouži jí kolem klitorisu. Nikdy na něm.|180|vedle_ona_lezi",
    "Dovol jí, aby si ruku vedla sama, ale prst máš tam ty.|180|vedle_ona_lezi",
    "Tři na hraně: Dráždi ji prsty až těsně k vrcholu a vždycky přestaň. Třikrát. Počtvrté už ji nech. Cíl: vydržet všechna tři zastavení.|300|vedle_ona_lezi",
    "Vsuň do ní jeden prst a nehýbej jím. Jen ho tam nech a líbej ji.|120|vedle_ona_lezi",
    "Dráždi ji dvěma prsty uvnitř a palcem zvenku najednou.|240|vedle_ona_lezi",
    "Rukou ji přiveď k vrcholu, ale nesmíš u toho použít víc než dva prsty.|300|vedle_ona_lezi",
    "Nech ji ležet na zádech a drž jí jednu ruku, zatímco ji druhou dráždíš.|240|vedle_ona_lezi",
    "Souboj rukou: Dotýkejte se navzájem rukama zároveň. Kdo první vydá zvuk, prohrál. Cíl: vydržet déle než ona.|240|lzicka",
    "Dráždi ji rukou přes kalhotky a sleduj, kdy si je začne sama stahovat.|180|vedle_ona_lezi",
    "Použij hodně lubrikantu a hlaď ji celou dlaní, ne prsty.|180|vedle_ona_lezi",
    "Ukaž jí, jak se dotýkáš sám sebe, a nech ji, ať dělá to samé.|180|sed_celem",
    "Sedni si za ni, roztáhni jí kolena a dráždi ji oběma rukama.|240|klin_podlaha",
    "Pomalé střídání: Deset vteřin uvnitř prsty, deset vteřin venku dlaní. Pořád dokola. Cíl: nikdy nezrychlit.|240|vedle_ona_lezi",
    "Hlaď ji mezi nohama hřbetem ruky. Je to překvapivě jiný pocit.|120|vedle_ona_lezi",
    "Nech ji, ať ti řekne přesně, kolik prstů a jak rychle. Poslechni na slovo.|240|vedle_ona_lezi",
    "Dráždi ji, ale pokaždé, když vydá zvuk, na pět vteřin přestaneš.|240|vedle_ona_lezi",
    "Drž jí ruce nad hlavou jednou svojí a druhou ji dráždi.|240|vedle_ona_lezi",
    "Jen dvě minuty: Máš přesně dvě minuty, abys ji dostal co nejblíž. Pak musíš přestat, ať je kdekoli. Cíl: přestat včas.|120|vedle_ona_lezi",
    "Klekni si vedle ní a dráždi ji tak, aby se ti přitom dívala do očí.|240|vedle_ona_lezi",
    "Použij jen jeden prst a jediné tempo. Žádné změny.|180|vedle_ona_lezi",
    "Nech ji sedět mezi tvýma nohama zády k tobě a dráždi ji, zatímco jí líbáš krk.|300|klin_podlaha",
    "Dej jí ruku na tvoji a nech ji přitlačit tak, jak jí to vyhovuje.|180|vedle_ona_lezi",
    "Stupnice: Ptej se jí během dráždění, kde je na stupnici od jedné do desíti. Zastavíš se na osmičce. Cíl: udržet ji na osmi celou minutu.|240|vedle_ona_lezi",
    "Dráždi ji zezadu rukou, když leží na břiše s pokrčenou nohou.|240|masaz_zada",
    "Střídej dva prsty uvnitř a jazyk na bradavce.|240|vedle_ona_lezi",
    "Nech ji, ať si vede tvoji ruku po celém svém těle, a ty se nehneš sám od sebe.|240|vedle_ona_lezi",
    "Dráždi ji jen konečkem prstu a nikdy netlač víc než na jemný dotek.|180|vedle_ona_lezi",
    "Podržená ruka: Drž jí obě ruce a dráždi ji tak dlouho, dokud se ti nezačne vzpírat. Cíl: nepustit ji ani jednou.|300|vedle_ona_lezi",
    "Dej si její ruku na svou a nech ji, ať ti ukáže rytmus. Pak pokračuj sám.|240|vedle_ona_lezi",
    "Použij lubrikant a hlaď ji celou dlaní v kruzích. Žádné prsty dovnitř.|180|vedle_ona_lezi",
    "Klekni si mezi její kolena a dráždi ji rukou, zatímco se na ni jen díváš.|240|oral_klek",
    "Nech ji položit si ruku na tvoji a společně najděte správné tempo.|180|vedle_ona_lezi",
    "Ruce ve dvou: Ona se dotýká sama a ty jí k tomu přidáš druhou ruku. Nikdy nepřebírej vedení. Cíl: nechat ji řídit.|300|vedle_ona_lezi",
    "Dráždi ji zepředu i zezadu naráz – jedna ruka vpředu, druhá ji hladí po zádech.|240|lzicka",
    "Vezmi její prsty a olízni je, než je zase přiložíš tam, kde byly.|120|vedle_ona_lezi",
    "Dráždi ji a přitom jí říkej nahlas, co přesně děláš.|240|vedle_ona_lezi",
    "Nech ji ležet na boku a dráždi ji rukou seshora. Druhou jí drž koleno.|240|lzicka",
    "Dvě rychlosti: Střídej pomalé kroužení a rychlé krátké pohyby po deseti vteřinách. Cíl: ať sama řekne, které chce.|240|vedle_ona_lezi",
    "Použij dva prsty a pohyb směrem k břichu. Hledej to místo uvnitř.|300|vedle_ona_lezi",
    "Drž ji za bok a dráždi ji tak, aby se ti mohla opřít.|240|lzicka",
    "Dráždi ji jen tak dlouho, dokud nezvedne boky. Pak přestaň a čekej.|180|vedle_ona_lezi",
    "Nech ji, ať si sama stáhne kalhotky, ale ty se jí do té doby nedotkneš.|120|vedle_ona_lezi",
    "Sto pohybů: Uděláš jí přesně sto pohybů prsty. Ona počítá nahlas. Cíl: dojít do sta bez ztráty rytmu.|300|vedle_ona_lezi",
    "Dráždi ji jednou rukou a druhou jí zakryj ústa. Ať se snaží být potichu.|240|vedle_ona_lezi",
    "Nech ji vybrat mezi prsty a dlaní. Pak použij to druhé.|180|vedle_ona_lezi",
    "Lehni si k ní na bok a dráždi ji tak, abyste se přitom dívali do očí.|240|lzicka",
    "Použij tolik lubrikantu, aby ruka klouzala úplně bez odporu.|240|vedle_ona_lezi",
    "Do konce: Dráždi ji rukou až do vrcholu a nepřestaň hned potom. Pokračuj ještě chvíli jemně. Cíl: dotáhnout to a zůstat.|300|vedle_ona_lezi",
    "Střídej jednu a dvě ruce. Ona říká, kdy má být kolik.|240|vedle_ona_lezi",
    "Dráždi ji vsedě, když ti sedí na klíně zády.|240|klin_zady",
    "Přiklop jí dlaň na její vlastní ruku a veď ji, jak chceš ty.|180|vedle_ona_lezi",
    "Nech ji, ať se dotýká sama, a ty jí mezitím olizuj bradavky.|240|vedle_ona_lezi",
    "Pět minut bez cíle: Dráždi ji pět minut, ale ani jednou se nesmíš pokusit ji dostat přes hranu. Cíl: nespěchat.|300|vedle_ona_lezi",
    "Dej jí prst do pusy a pak ho použij tam, kde má být.|120|vedle_ona_lezi",
    "Dráždi ji a přitom jí drž nohu zvednutou. Změní to úplně všechno.|240|vedle_ona_lezi",
    "Nech ji položit tvoji ruku tam, kde ji chce mít, a nehýbej s ní.|120|vedle_ona_lezi",
    "Dráždi ji celou dlaní přes kalhotky dokola, nikdy nahoru a dolů.|180|vedle_ona_lezi",
    "Přestávka na povel: Ona řekne stop a ty okamžitě necháš ruku ležet bez pohybu. Pak zase start. Cíl: pět zastavení.|300|vedle_ona_lezi",
    "Použij prsty obou rukou zároveň – jeden uvnitř, druhý venku.|240|vedle_ona_lezi",
    "Dráždi ji vleže za ní a druhou rukou jí hlaď prsa.|240|lzicka",
    "Nech ji, ať ti při tom kouká do očí a nesmí je zavřít.|240|vedle_ona_lezi",
    "Dráždi ji tak jemně, že bude muset sama přitlačit.|180|vedle_ona_lezi",
    "Ruka a kolena: Roztáhni jí kolena rukama a dráždi ji jen jazykem prstu u ruky, kterou ji držíš. Cíl: nepustit kolena.|240|oral_klek",
    "Namaž jí lubrikantem celé prsty a nech ji, ať si je sama olízne.|120|vedle_ona_lezi",
    "Dráždi ji do chvíle, kdy ti sama řekne, ať zrychlíš. Do té doby se nepohneš rychleji.|300|vedle_ona_lezi",
    "Sedni si jí za záda a dráždi ji tak, aby ti hlavu opřela o rameno.|240|klin_podlaha",
    "Dej jí ruku mezi nohy a druhou jí drž bradu, ať se ti dívá do očí.|240|vedle_ona_lezi",
    "Beze slov: Celé dráždění probíhá bez jediného slova, jen podle toho, jak reaguje. Cíl: poznat to bez ptaní.|300|vedle_ona_lezi",
    "Dráždi ji jen v přestávkách mezi polibky. Nikdy obojí najednou.|240|vedle_ona_lezi",
    "Nech ji držet tvoje zápěstí a řídit, jak hluboko a jak rychle.|240|vedle_ona_lezi",
    "Dráždi ji zezadu, když klečí na všech čtyřech.|240|zezadu",
    "Použij jen malíček a ukázováček. Nic víc.|180|vedle_ona_lezi",
    "Opačné tempo: Čím víc se blíží, tím pomaleji se hýbeš. Cíl: dovést ji tam nejpomalejším možným tempem.|300|vedle_ona_lezi",
    "Dráždi ji a druhou rukou si veď její ruku po svém těle.|240|lzicka",
    "Nech ji, ať si lehne na tebe zády, a dráždi ji oběma rukama.|300|propletene",
    "Dej jí ruku mezi nohy až ve chvíli, kdy tě o to sama poprosí.|180|vedle_ona_lezi",
    "Na konci nech ruku ležet tam, kde je, a jen ji drž, dokud se nezklidní.|120|lzicka",
  ],

  female: [
    "Dráždi ho přes trenýrky jedním prstem tak dlouho, až budou těsné. Teprve pak mu je smíš sundat.|180|vedle_on_lezi",
    "Polož mu dlaň mezi nohy přes prádlo a jen ji tam nech. Nehýbej se, dokud se o ni sám neotře.|120|vedle_on_lezi",
    "Vedená ruka: Vezmi jeho ruku a nech ho, ať ti ukáže přesně, jak se má dotýkat. Ty jen kopíruješ. Cíl: naučit se to přesně.|180|vedle_on_lezi",
    "Hlaď ho rukou tak pomalu, jak jen dokážeš. Za tři minuty smíš udělat nejvýš třicet pohybů.|180|vedle_on_lezi",
    "Nech ho, ať si sáhne sám, a ty mu jen drž ruku a díváš se.|180|lzicka",
    "Jen kolem: Dráždi ho jen po stranách a na hrázi, nikdy přímo. Cíl: ať si tvoji ruku sám posune.|180|vedle_on_lezi",
    "Lehni si za něj na lžičku a dráždi ho rukou zepředu. Do ucha mu u toho šeptej.|240|lzicka",
    "Namaž si dlaň lubrikantem a hlaď ho pomalými dlouhými tahy.|180|vedle_on_lezi",
    "Dovol mu, aby si ruku vedl sám, ale dlaň má tvoje.|180|vedle_on_lezi",
    "Tři na hraně: Hlaď ho rukou až těsně k vrcholu a vždycky přestaň. Třikrát. Počtvrté už ho nech. Cíl: vydržet všechna tři zastavení.|300|vedle_on_lezi",
    "Obejmi ho rukou a nehýbej se. Jen ho tak drž a líbej ho.|120|vedle_on_lezi",
    "Dráždi ho jednou rukou a druhou mu masíruj hráz.|240|vedle_on_lezi",
    "Rukou ho přiveď k vrcholu, ale nesmíš u toho použít víc než dva prsty.|300|vedle_on_lezi",
    "Nech ho ležet na zádech a drž mu jednu ruku, zatímco ho druhou dráždíš.|240|vedle_on_lezi",
    "Souboj rukou: Dotýkejte se navzájem rukama zároveň. Kdo první vydá zvuk, prohrál. Cíl: vydržet déle než on.|240|lzicka",
    "Dráždi ho rukou přes trenýrky a sleduj, kdy si je začne sám stahovat.|180|vedle_on_lezi",
    "Použij hodně lubrikantu a střídej pevný a úplně lehký stisk.|180|vedle_on_lezi",
    "Ukaž mu, jak se dotýkáš sama sebe, a nech ho, ať dělá to samé.|180|sed_celem",
    "Sedni si za něj, opři si ho o hrudník a dráždi ho oběma rukama.|240|klin_podlaha",
    "Pomalé střídání: Deset vteřin pevně, deset vteřin jen konečky prstů. Pořád dokola. Cíl: nikdy nezrychlit.|240|vedle_on_lezi",
    "Hlaď ho hřbetem ruky. Je to překvapivě jiný pocit.|120|vedle_on_lezi",
    "Nech ho, ať ti řekne přesně, jak pevně a jak rychle. Poslechni na slovo.|240|vedle_on_lezi",
    "Dráždi ho, ale pokaždé, když vydá zvuk, na pět vteřin přestaneš.|240|vedle_on_lezi",
    "Drž mu ruce nad hlavou jednou svojí a druhou ho dráždi.|240|vedle_on_lezi",
    "Jen dvě minuty: Máš přesně dvě minuty, abys ho dostala co nejblíž. Pak musíš přestat, ať je kdekoli. Cíl: přestat včas.|120|vedle_on_lezi",
    "Klekni si vedle něj a dráždi ho tak, aby se ti přitom díval do očí.|240|vedle_on_lezi",
    "Použij jen dva prsty a jediné tempo. Žádné změny.|180|vedle_on_lezi",
    "Sedni si mu mezi nohy zády k němu a dráždi ho, zatímco tě líbá na krk.|300|klin_podlaha",
    "Dej mu ruku na tvoji a nech ho přitlačit tak, jak mu to vyhovuje.|180|vedle_on_lezi",
    "Stupnice: Ptej se ho během dráždění, kde je na stupnici od jedné do desíti. Zastavíš se na osmičce. Cíl: udržet ho na osmi celou minutu.|240|vedle_on_lezi",
    "Dráždi ho zezadu rukou, když leží na břiše.|240|masaz_zada!",
    "Střídej ruku a jazyk na jeho bradavce. Nikdy obojí najednou.|240|vedle_on_lezi",
    "Nech ho, ať si vede tvoji ruku po celém svém těle, a ty se nehneš sama od sebe.|240|vedle_on_lezi",
    "Dráždi ho jen konečkem prstu a nikdy netlač víc než na jemný dotek.|180|vedle_on_lezi",
    "Podržená ruka: Drž mu obě ruce a dráždi ho tak dlouho, dokud se ti nezačne vzpírat. Cíl: nepustit ho ani jednou.|300|vedle_on_lezi",
    "Dej si jeho ruku na svou a nech ho ukázat rytmus. Pak pokračuj sama.|240|vedle_on_lezi",
    "Použij lubrikant a otáčej dlaní kolem dokola místo nahoru a dolů.|180|vedle_on_lezi",
    "Klekni si mezi jeho kolena a dráždi ho rukou, zatímco se na něj jen díváš.|240|oral_on_vleze",
    "Nech ho položit si ruku na tvoji a společně najděte správné tempo.|180|vedle_on_lezi",
    "Ruce ve dvou: On se dotýká sám a ty mu k tomu přidáš druhou ruku. Nikdy nepřebírej vedení. Cíl: nechat ho řídit.|300|vedle_on_lezi",
    "Dráždi ho zepředu a druhou rukou ho hlaď po zádech.|240|lzicka",
    "Vezmi jeho prsty a olízni je, než je zase přiložíš tam, kde byly.|120|vedle_on_lezi",
    "Dráždi ho a přitom mu říkej nahlas, co přesně děláš.|240|vedle_on_lezi",
    "Nech ho ležet na boku a dráždi ho rukou seshora. Druhou mu drž koleno.|240|lzicka",
    "Dvě rychlosti: Střídej pomalé dlouhé tahy a rychlé krátké po deseti vteřinách. Cíl: ať sám řekne, které chce.|240|vedle_on_lezi",
    "Použij obě ruce nad sebou a pohybuj jimi proti sobě.|300|vedle_on_lezi",
    "Drž ho za bok a dráždi ho tak, aby se o tebe mohl opřít.|240|lzicka",
    "Dráždi ho jen tak dlouho, dokud nezvedne boky. Pak přestaň a čekej.|180|vedle_on_lezi",
    "Nech ho, ať si sám stáhne trenýrky, ale ty se ho do té doby nedotkneš.|120|vedle_on_lezi",
    "Sto pohybů: Uděláš mu přesně sto pohybů rukou. On počítá nahlas. Cíl: dojít do sta bez ztráty rytmu.|300|vedle_on_lezi",
    "Dráždi ho jednou rukou a druhou mu zakryj ústa. Ať se snaží být potichu.|240|vedle_on_lezi",
    "Nech ho vybrat mezi rukou a prsty. Pak použij to druhé.|180|vedle_on_lezi",
    "Lehni si k němu na bok a dráždi ho tak, abyste se přitom dívali do očí.|240|lzicka",
    "Nalij si do dlaně tolik lubrikantu, že ruka bude klouzat úplně sama.|240|vedle_on_lezi",
    "Do konce: Dráždi ho rukou až do konce a nepřestaň hned potom. Pokračuj ještě chvíli jemně. Cíl: dotáhnout to a zůstat.|300|vedle_on_lezi",
    "Střídej jednu a dvě ruce. On říká, kdy má být kolik.|240|vedle_on_lezi",
    "Dráždi ho vsedě, když mu sedíš na klíně zády.|240|klin_zady",
    "Přiklop mu dlaň na jeho vlastní ruku a veď ji, jak chceš ty.|180|vedle_on_lezi",
    "Nech ho, ať se dotýká sám, a ty mu mezitím olizuj bradavky.|240|vedle_on_lezi",
    "Pět minut bez cíle: Dráždi ho pět minut, ale ani jednou se nesmíš pokusit ho dostat přes hranu. Cíl: nespěchat.|300|vedle_on_lezi",
    "Dej mu prst do pusy a pak ho použij tam, kde má být.|120|vedle_on_lezi",
    "Dráždi ho a přitom mu drž nohu zvednutou. Změní to úplně všechno.|240|vedle_on_lezi",
    "Nech ho položit tvoji ruku tam, kde ji chce mít, a nehýbej s ní.|120|vedle_on_lezi",
    "Dráždi ho celou dlaní přes trenýrky dokola, nikdy nahoru a dolů.|180|vedle_on_lezi",
    "Přestávka na povel: On řekne stop a ty okamžitě necháš ruku ležet bez pohybu. Pak zase start. Cíl: pět zastavení.|300|vedle_on_lezi",
    "Použij obě ruce zároveň – jedna nahoře, druhá na varlatech.|240|vedle_on_lezi",
    "Dráždi ho vleže za ním a druhou rukou mu hlaď hrudník.|240|lzicka",
    "Nech ho, ať ti při tom kouká do očí a nesmí je zavřít.|240|vedle_on_lezi",
    "Dráždi ho tak jemně, že bude muset sám přitlačit.|180|vedle_on_lezi",
    "Ruka a kolena: Roztáhni mu kolena rukama a dráždi ho jen jednou rukou, kterou ho držíš. Cíl: nepustit kolena.|240|oral_on_vleze",
    "Namaž si lubrikantem celé prsty a nech ho, ať si je sám olízne.|120|vedle_on_lezi",
    "Dráždi ho do chvíle, kdy ti sám řekne, ať zrychlíš. Do té doby se nepohneš rychleji.|300|vedle_on_lezi",
    "Sedni si mu za záda a dráždi ho tak, aby ti hlavu opřel o rameno.|240|klin_podlaha",
    "Dej mu ruku mezi nohy a druhou mu drž bradu, ať se ti dívá do očí.|240|vedle_on_lezi",
    "Mlčky: Celý úkol zvládni bez jediného slova a řiď se jen tím, jak jeho tělo reaguje. Cíl: poznat to bez ptaní.|300|vedle_on_lezi",
    "Dráždi ho jen v přestávkách mezi polibky. Nikdy obojí najednou.|240|vedle_on_lezi",
    "Nech ho držet tvoje zápěstí a řídit, jak pevně a jak rychle.|240|vedle_on_lezi",
    "Dráždi ho zezadu, když klečí na všech čtyřech.|240|zezadu!",
    "Použij jen palec a ukazovák v kroužku. Nic víc.|180|vedle_on_lezi",
    "Opačné tempo: Čím víc se blíží, tím pomaleji se hýbeš. Cíl: dovést ho tam nejpomalejším možným tempem.|300|vedle_on_lezi",
    "Dráždi ho a druhou rukou si veď jeho ruku po svém těle.|240|lzicka",
    "Nech ho, ať si lehne na tebe zády, a dráždi ho oběma rukama.|300|propletene",
    "Dej mu ruku mezi nohy až ve chvíli, kdy tě o to sám poprosí.|180|vedle_on_lezi",
    "Na konci nech ruku ležet tam, kde je, a jen ho drž, dokud se nezklidní.|120|lzicka",
  ],
});
