// Kategorie 2 – Smyslné doteky (dávka d)
// Témata: smyslová deprivace, pozorování, instrukce na dálku, počítané výzvy.
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 2,

  male: [
    "Bez očí a bez uší: Zavaž jí oči, nasaď jí sluchátka a dotýkej se jí úplně nepředvídatelně. Cíl: pět minut a ani jednou nezopakovat stejné místo.|300|vedle_ona_lezi",
    "Jen mezi slokami: Nasaď jí sluchátka a dotýkej se jí výhradně v pauzách mezi slokami. Cíl: pět minut a ani jednou se netrefit vedle.|300|vedle_ona_lezi",
    "Slepá mapa: Zavaž jí oči a dotýkej se jí na deseti místech. Na konci musí říct všechna v pořadí. Cíl: aspoň sedm správně.|300|vedle_ona_lezi",
    "Prst, jazyk, nebo pírko: Zavaž jí oči a střídej tyhle tři doteky. Cíl: deset pokusů a ať uhodne aspoň šest.|240|vedle_ona_lezi",
    "Na dosah a přece ne: Sedni si na kraj postele a jen se dívej, jak se dotýká sama. Cíl: pět minut a nepřiblížit se k ní ani o krok.|300",
    "Kdo sáhne první: Posaďte se proti sobě a dotýkejte se každý sám sebe. Cíl: pět minut – kdo první sáhne po druhém, plní jeho přání.|300|sed_celem",
    "Instrukce na dálku: Sedni si dva metry od ní a říkej jí, co si má dělat. Nesmíš se jí dotknout. Cíl: dovést ji k tomu jen hlasem.|300",
    "Přesně pět doteků: Řekni jí, ať zavře oči a nehýbe se, a dej jí přesně pět doteků. Cíl: ani o jeden víc, ať tě prosí, jak chce.|180|vedle_ona_lezi",
    "Levá, nebo pravá: Zavaž jí oči a pokládej jí dlaň na prsa, břicho a stehna. Ona hádá, která ruka to je. Cíl: deset pokusů a splést ji aspoň čtyřikrát.|180|vedle_ona_lezi",
    "Nikdy nevíš kde: Dotýkej se jí tak, aby nikdy nedokázala odhadnout, kde budeš za tři vteřiny. Cíl: čtyři minuty bez jediného pravidelného vzorce.|240|vedle_ona_lezi",
    "Padesát doteků: Dej jí padesát krátkých doteků po celém těle. Ona počítá potichu a na konci řekne číslo. Cíl: shodnout se.|300|vedle_ona_lezi",
    "Najdi mě poslepu: Zavaž jí oči a nech ji, ať si tě rukou najde. Cíl: nepomoct jí ani hláskem a pak jí políbit dlaň.|120",
    "Zavřené oči: Zakaž jí otevřít oči a hlaď ji po celém těle včetně klína. Za každé otevření přestáváš na deset vteřin. Cíl: nejvýš dvě pauzy.|240|vedle_ona_lezi",
    "Jen se dívat: Nech ji ležet nahou a jen ji pozoruj. Cíl: dvě minuty a nedotknout se jí ani jednou.|120|vedle_ona_lezi",
    "Říkáš něco jiného: Popisuj jí nahlas dotek, ale rukama dělej něco úplně jiného. Cíl: čtyři minuty a ani jednou se netrefit do vlastních slov.|240|vedle_ona_lezi",
    "Pravidlo tří: Řekni jí tři pravidla na tenhle úkol a striktně je dodržuj. Cíl: ani jedno neporušit.|240|vedle_ona_lezi",
    "Teplá a studená dlaň: Zavaž jí oči a přikládej jí na kůži střídavě zahřátou a vychlazenou dlaň. Cíl: deset střídání a ať u každého uhodne, co to bylo.|180|vedle_ona_lezi",
    "Rytmus jejího dechu: Dotýkej se jí přesně v rytmu, ve kterém dýchá. Cíl: čtyři minuty a ani jednou nebýt rychlejší než její nádech.|240|vedle_ona_lezi",
    "Řídíš jen hlasem: Nech ji, ať se dotýká sama, a ty jí jen šeptej, co má dělat dál. Cíl: pět minut a nedotknout se jí ani jednou.|300|vedle_ona_lezi",
    "Vyber si poslepu: Zavaž jí oči, dej jí tři různé doteky a nech ji vybrat jen podle pocitu. Cíl: ten vybraný jí dát ještě desetkrát.|180|vedle_ona_lezi",
    "Zrcadlo: Ona se dotýká sama sebe a ty opakuješ přesně totéž na svém těle. Cíl: čtyři minuty a ani jednou neuhnout pohledem.|240|sed_celem",
    "Ruce zůstanou nahoře: Dej jí ruce nad hlavu s tím, že je tam musí nechat, a pak ji celou prozkoumej. Cíl: pět minut a ruce se nehnou.|300|vedle_ona_lezi",
    "Čekání poslepu: Nech ji ležet se zavázanýma očima a jen ji pozoruj. Cíl: celou minutu se jí nedotknout a pak začít rovnou na bradavkách.|120|vedle_ona_lezi",
    "Pět a pět: Střídej dotek a pauzu přesně po pěti vteřinách a počítej nahlas. Cíl: čtyři minuty a ani jednou se nesplést.|240|vedle_ona_lezi",
    "Dvacet vteřin na místo: Ona ti řekne jedno místo a ty se mu věnuješ přesně dvacet vteřin. Pak další. Cíl: šest míst.|180|vedle_ona_lezi",
    "Kde přistanu: Zavaž jí oči a olizuj ji na náhodných místech. Cíl: dvacet míst a ani jedno dvakrát.|240|vedle_ona_lezi",
    "Dívat se a nesahat: Nech ji sedět naproti tobě a dotýkat se sama sebe, zatímco se na ni jen díváš. Cíl: pět minut a nesáhnout po ní.|300|sed_celem",
    "Druhá ruka v její: Dotýkej se jí jen jednou rukou a druhou jí pevně drž ruku v dlani. Cíl: čtyři minuty a ani jednou ji nepustit.|240|lzicka",
    "Mluv, nebo přestanu: Řekni jí, ať ti nahlas popisuje, co cítí. Jakmile ztichne, přestaneš. Cíl: čtyři minuty a nejvýš tři pauzy.|240|vedle_ona_lezi",
    "Odpočítávání: Řekni jí, že za tři minuty přestaneš, a nahlas počítej poslední minutu. Cíl: přestat přesně na nule.|180|vedle_ona_lezi",
    "Sama si zaváže oči: Nech ji, ať si zaváže oči sama, a pak střídej prsty, rty a pírko po celém těle. Cíl: pět minut a nikdy neprozradit, co přijde.|300|vedle_ona_lezi",
    "Poznáš to přes látku: Dotýkej se jí přes tenkou látku různými věcmi a ptej se, jestli pozná čím. Cíl: deset pokusů a splést ji aspoň třikrát.|180|vedle_ona_lezi",
    "Do rytmu, který neslyšíš: Dej jí sluchátka a dotýkej se jí tak, aby to sedělo do hudby, kterou slyší jen ona. Cíl: nechat se řídit jejím dechem.|300|vedle_ona_lezi",
    "Kolik prstů: Zavaž jí oči a pokládej jí na tělo různý počet prstů. Ona hádá kolik. Cíl: deset pokusů a splést ji aspoň třikrát.|180|vedle_ona_lezi",
    "Beze slov a bez očí: Zavaž jí oči a hlaď ji jen rukama, nikde nespěchej. Cíl: pět minut a neříct ani jedno slovo.|300|vedle_ona_lezi",
    "Na hranici citlivosti: Dotýkej se jí co nejlehčeji a ptej se, jestli to vůbec cítí. Cíl: najít nejslabší dotek, který ještě pozná, a u něj zůstat.|180|vedle_ona_lezi",
    "Tah na nádech: Nech ji ležet a přejeď jí zlehka dlaní po těle pokaždé, když se nadechne. Cíl: čtyřicet nádechů a ani jeden nevynechat.|240|vedle_ona_lezi",
    "Minuta čekání: Oznam jí, že ji necháš čekat, a nech ji čekat celou minutu. Cíl: nedotknout se jí dřív, ať říká cokoli.|60|vedle_ona_lezi",
    "Musí to říct nahlas: Dotýkej se jí jen tam, kde ti to sama dovolí, a musí to pokaždé vyslovit. Cíl: pět minut a ani jednou to porušit.|300|vedle_ona_lezi",
    "Tři pokusy: Zkus najít místo, které ji rozhodí, na tři pokusy. Ona jen kývne. Cíl: trefit se napoprvé.|180|vedle_ona_lezi",
    "Hádej, co to je: Zavaž jí oči a přejeď jí po těle věcmi, které si vybereš. Cíl: pět různých věcí a ať uhodne aspoň tři.|180|vedle_ona_lezi",
    "O vteřinu později: Hlaď a prsti ji přesně podle jejích pokynů, ale vždycky až o vteřinu později. Cíl: čtyři minuty a zpoždění nezkrátit.|240|vedle_ona_lezi",
    "Ruce na tvých ramenou: Posaď si ji proti sobě, ať se drží tvých ramen, a prsti ji. Cíl: čtyři minuty – jakmile ruce sundá, přestáváš.|240|sed_celem",
    "Dotýkej se jí jedním prstem a celou minutu nezměň tempo.|60|vedle_ona_lezi",
    "Dva hlasy: Střídej šeptání a normální hlas a dotýkej se jí podle toho jemně nebo silně. Cíl: ať pozná systém.|240|vedle_ona_lezi",
    "Dej jí ruce za záda a dotýkej se jí celou dobu jen zepředu.|240|klek_ruce_za_zady",
    "Nech ji sedět na kraji postele a dotýkej se jí, zatímco klečíš před ní.|300|oral_vsede",
    "Zavaž jí oči a nech ji hádat, kde bude další polibek. Když uhodne, dostane ho jinam.|240|vedle_ona_lezi",
    "Dotýkej se jí, ale zastav se pokaždé, když otevře pusu.|240|vedle_ona_lezi",
    "Pět zastavení: Prsti ji pět minut a pětkrát se úplně zastav a nech ruku ležet. Ona nesmí vědět kdy. Cíl: překvapit ji pokaždé.|300|vedle_ona_lezi",
    "Popíše a dostane: Nech ji nahlas popsat, jaký dotek by teď chtěla, a pak jí ho dej úplně přesně. Cíl: tři přání a ani jedno nezměnit.|240|vedle_ona_lezi",
    "Dej jí ruku na své a nech ji vést tvoje prsty po svém těle.|240|vedle_ona_lezi",
    "Nevidí na tvoje ruce: Stoupni si za ni a dotýkej se jí tak, aby nikdy neviděla, co chystáš. Cíl: čtyři minuty a nenechat ji se otočit.|240|stoje_zezadu",
    "Klečí a čeká: Poruč jí, ať si klekne se zavřenýma očima, a pak ji zezadu hlaď po prsou a klíně. Cíl: nechat ji čekat celou minutu.|120|klek_ruce_za_zady",
    "Sto vteřin: Dotýkej se jí přesně sto vteřin a pak přestaň, ať je kdekoli. Cíl: nepřetáhnout.|120|vedle_ona_lezi",
    "Nech ji ležet na boku a dotýkej se jí jen na zádech a bocích.|240|lzicka",
    "Zavaž jí oči a dej jí do ruky pírko. Ať se dotýká sama a ty se díváš.|240",
    "Dotýkej se jí a vždycky, když řekne víc, o kousek zpomalíš.|240|vedle_ona_lezi",
    "Jedno jediné místo: Nech ji vybrat jedno místo – prsa, klitoris, krk – a pět minut se věnuj jenom jemu. Cíl: ani jednou nesjet jinam.|300|vedle_ona_lezi",
    "Souhra dechu: Dotýkej se jí jen při jejím výdechu, při nádechu přestaň. Cíl: udržet to celou dobu.|240|vedle_ona_lezi",
    "Dej jí ruce na oči a nech je tam. Pak se dotýkej, kde chceš.|240|vedle_ona_lezi",
    "Nech ji stát a dotýkej se jí, zatímco se drží zdi.|240|zed",
    "Slovo, po kterém přestaneš: Dráždi ji prsty a domluvte slovo, po kterém vždycky okamžitě přestaneš. Cíl: ať ho použije aspoň třikrát.|300|vedle_ona_lezi",
    "Dotýkej se jí přes prostěradlo. Nikdy pod ním.|180|vedle_ona_lezi",
    "Tři doteky za minutu: Máš povoleno jen tři doteky za každou minutu. Vyber je dobře. Cíl: vydržet pět minut.|300|vedle_ona_lezi",
    "Nech ji ležet na břiše a dotýkej se jí jen na zadní straně těla.|300|masaz_zada",
    "Zavaž jí oči a nech ji poznat po hmatu, jakou částí těla ji hladíš.|240|vedle_ona_lezi",
    "Dotýkej se jí a pokaždé, když se zasměje, začínáš od hlavy.|240|vedle_ona_lezi",
    "Řekni jí, ať si sedne na tvůj klín zády a nehýbe se.|240|klin_zady",
    "Jeden prst a hodně času: Celý úkol se jí smíš dotýkat jen jedním prstem. Cíl: dokázat, že to stačí.|300|vedle_ona_lezi",
    "Nech ji, ať drží kostku ledu, dokud ji celou nerozpustí. Mezitím ji hlaď.|240|vedle_ona_lezi",
    "Dotýkej se jí a mezi doteky se vždy na chvíli úplně vzdal.|240|vedle_ona_lezi",
    "Vidět, nebo cítit: Nech ji vybrat, jestli chce vidět, nebo cítit – a pak jí zavaž oči tak jako tak a hlaď ji po celém těle. Cíl: nedat se uprosit.|240|vedle_ona_lezi",
    "Dotýkej se jí, ale nikdy oběma rukama najednou.|240|vedle_ona_lezi",
    "Deset a pauza: Deset vteřin se jí věnuješ, deset vteřin nic. A tak dokola. Cíl: nikdy pauzu nevynechat.|300|vedle_ona_lezi",
    "Nech ji klečet a dotýkej se jí shora. Ona nesmí zvednout ruce.|240|klek_ruce_hlava",
    "Dotýkej se jí a ptej se jí po každém doteku, jestli chce znovu.|240|vedle_ona_lezi",
    "Hledá tvoje rty: Zavaž jí oči a nech ji hledat tvoje rty jen podle dechu. Cíl: pět polibků a pokaždé se přesunout jinam.|180|objeti",
    "Dotýkej se jí přesně tak, jak ti to předvedla na sobě.|240|vedle_ona_lezi",
    "Vlastní tempo: Ona počítá nahlas do dvaceti a ty se musíš stihnout dotknout každého čísla jinde. Cíl: dvacet různých míst.|180|vedle_ona_lezi",
    "Dotýkej se jí, dokud neřekne stop. Pak počkej, dokud neřekne pokračuj.|300|vedle_ona_lezi",
    "Nech ji ležet mezi tvýma nohama a hlaď ji odshora.|300|klin_podlaha",
    "Dotýkej se jí jen přes jednu vrstvu oblečení, kterou si sama vybere.|240|vedle_ona_lezi",
    "Nakonec jí sundej šátek a nech ji, ať se na tebe podívá. Nic neříkej.|60|vedle_ona_lezi",
  ],

  female: [
    "Ani nevidí, ani neslyší: Zavaž mu oči, nasaď mu sluchátka a dotýkej se ho úplně nepředvídatelně. Cíl: pět minut a ani jednou stejné místo.|300|vedle_on_lezi",
    "Pauzy mezi slokami: Nasaď mu sluchátka a dotýkej se ho výhradně v pauzách mezi slokami. Cíl: pět minut a ani jednou se netrefit vedle.|300|vedle_on_lezi",
    "Slepá mapa: Zavaž mu oči a dotýkej se ho na deseti místech. Na konci musí říct všechna v pořadí. Cíl: aspoň sedm správně.|300|vedle_on_lezi",
    "Tři možnosti: Zavaž mu oči a střídej prst, jazyk a pírko. Cíl: deset pokusů a ať uhodne aspoň šest.|240|vedle_on_lezi",
    "Blízko a přece daleko: Sedni si na kraj postele a jen se dívej, jak se dotýká sám. Cíl: pět minut a nepřiblížit se k němu ani o krok.|300",
    "Kdo nevydrží: Sedni si proti němu a dotýkejte se každý sám sebe. Cíl: pět minut – kdo první sáhne po druhém, plní jeho přání.|300|sed_celem",
    "Instrukce na dálku: Sedni si dva metry od něj a říkej mu, co si má dělat. Nesmíš se ho dotknout. Cíl: dovést ho k tomu jen hlasem.|300",
    "Pět a dost: Řekni mu, ať zavře oči a nehýbe se, a dej mu přesně pět doteků. Cíl: ani o jeden víc, ať tě prosí, jak chce.|180|vedle_on_lezi",
    "Která je to ruka: Zavaž mu oči a pokládej mu dlaň na hrudník, břicho a stehna. On hádá, která ruka to je. Cíl: deset pokusů a splést ho čtyřikrát.|180|vedle_on_lezi",
    "Nikdy neuhodne: Dotýkej se ho tak, aby nikdy nedokázal odhadnout, kde budeš za tři vteřiny. Cíl: čtyři minuty bez jediného pravidelného vzorce.|240|vedle_on_lezi",
    "Padesát doteků: Dej mu padesát krátkých doteků po celém těle. On počítá potichu a na konci řekne číslo. Cíl: shodnout se.|300|vedle_on_lezi",
    "Najdi mě poslepu sám: Zavaž mu oči a nech ho, ať si tě rukou najde. Cíl: nepomoct mu ani hláskem a pak mu políbit dlaň.|120",
    "Oči zavřené: Zakaž mu otevřít oči a hlaď ho po celém těle včetně penisu. Za každé otevření přestáváš na deset vteřin. Cíl: nejvýš dvě pauzy.|240|vedle_on_lezi",
    "Jen pozorovat: Nech ho ležet nahého a jen ho pozoruj. Cíl: dvě minuty a nedotknout se ho ani jednou.|120|vedle_on_lezi",
    "Slova proti rukám: Popisuj mu nahlas dotek, ale rukama dělej něco úplně jiného. Cíl: čtyři minuty a ani jednou se netrefit do vlastních slov.|240|vedle_on_lezi",
    "Pravidlo tří: Řekni mu tři pravidla na tenhle úkol a striktně je dodržuj. Cíl: ani jedno neporušit.|240|vedle_on_lezi",
    "Dvě teploty dlaně: Zavaž mu oči a přikládej mu na kůži střídavě zahřátou a vychlazenou dlaň. Cíl: deset střídání a ať u každého uhodne, co to bylo.|180|vedle_on_lezi",
    "Podle jeho dechu: Dotýkej se ho přesně v rytmu, ve kterém dýchá. Cíl: čtyři minuty a ani jednou nebýt rychlejší než jeho nádech.|240|vedle_on_lezi",
    "Vedení hlasem: Nech ho, ať se dotýká sám, a ty mu jen šeptej, co má dělat dál. Cíl: pět minut a nedotknout se ho ani jednou.|300|vedle_on_lezi",
    "Poslepu si vyber: Zavaž mu oči, dej mu tři různé doteky a nech ho vybrat jen podle pocitu. Cíl: ten vybraný mu dát ještě desetkrát.|180|vedle_on_lezi",
    "Zrcadlo naopak: On se dotýká sám sebe a ty opakuješ přesně totéž na svém těle. Cíl: čtyři minuty a ani jednou neuhnout pohledem.|240|sed_celem",
    "Jeho ruce zůstanou: Dej mu ruce nad hlavu s tím, že je tam musí nechat, a pak ho celého prozkoumej. Cíl: pět minut a ruce se nehnou.|300|vedle_on_lezi",
    "Ať si počká: Nech ho ležet se zavázanýma očima a jen ho pozoruj. Cíl: celou minutu se ho nedotknout a pak začít rovnou na bradavkách.|120|vedle_on_lezi",
    "Pět vteřin dotek: Střídej pět vteřin doteku a pět vteřin ničeho a počítej nahlas. Cíl: čtyři minuty a ani jednou se nesplést.|240|vedle_on_lezi",
    "Dvacet vteřin na místo: On ti řekne jedno místo a ty se mu věnuješ přesně dvacet vteřin. Pak další. Cíl: šest míst.|180|vedle_on_lezi",
    "Náhodná místa: Zavaž mu oči a olizuj ho na náhodných místech. Cíl: dvacet míst a ani jedno dvakrát.|240|vedle_on_lezi",
    "On se jen dívá: Sedni si naproti němu a dotýkej se sama sebe, zatímco se on jen dívá. Cíl: pět minut a nedovolit mu se přiblížit.|300|sed_celem",
    "Druhá ruka v jeho: Dotýkej se ho jen jednou rukou a druhou mu pevně drž ruku v dlani. Cíl: čtyři minuty a ani jednou ho nepustit.|240|lzicka",
    "Mluvit, nebo konec: Řekni mu, ať ti nahlas popisuje, co cítí. Jakmile ztichne, přestaneš. Cíl: čtyři minuty a nejvýš tři pauzy.|240|vedle_on_lezi",
    "Odpočítávání: Řekni mu, že za tři minuty přestaneš, a nahlas počítej poslední minutu. Cíl: přestat přesně na nule.|180|vedle_on_lezi",
    "Zaváže si je sám: Nech ho, ať si zaváže oči sám, a pak střídej prsty, rty a pírko po celém těle. Cíl: pět minut a nikdy neprozradit, co přijde.|300|vedle_on_lezi",
    "Přes látku: Dotýkej se ho přes tenkou látku různými věcmi a ptej se, jestli pozná čím. Cíl: deset pokusů a splést ho aspoň třikrát.|180|vedle_on_lezi",
    "Hudba jen pro něj: Dej mu sluchátka a dotýkej se ho tak, aby to sedělo do hudby, kterou slyší jen on. Cíl: nechat se řídit jeho dechem.|300|vedle_on_lezi",
    "Kolik jich cítíš: Zavaž mu oči a pokládej mu na tělo různý počet prstů. On hádá kolik. Cíl: deset pokusů a splést ho aspoň třikrát.|180|vedle_on_lezi",
    "Bez očí a beze slov: Zavaž mu oči a hlaď ho jen rukama, nikde nespěchej. Cíl: pět minut a neříct ani jedno slovo.|300|vedle_on_lezi",
    "Nejslabší dotek: Dotýkej se ho co nejlehčeji a ptej se, jestli to vůbec cítí. Cíl: najít nejslabší dotek, který ještě pozná, a u něj zůstat.|180|vedle_on_lezi",
    "Dlaň na každý nádech: Nech ho ležet a přejeď mu zlehka dlaní po těle pokaždé, když se nadechne. Cíl: čtyřicet nádechů a ani jeden nevynechat.|240|vedle_on_lezi",
    "Minuta čekání: Oznam mu, že ho necháš čekat, a celou minutu se ho nedotkni. Cíl: pak začít rovnou rukou na penisu.|60|vedle_on_lezi",
    "Nahlas a konkrétně: Dotýkej se ho jen tam, kde ti to sám dovolí, a musí to pokaždé vyslovit. Cíl: pět minut a ani jednou to porušit.|300|vedle_on_lezi",
    "Tři pokusy: Zkus najít místo, které ho rozhodí, na tři pokusy. On jen kývne. Cíl: trefit se napoprvé.|180|vedle_on_lezi",
    "Co ti jezdí po kůži: Zavaž mu oči a přejeď mu po těle věcmi, které si vybereš. Cíl: pět různých věcí a ať uhodne aspoň tři.|180|vedle_on_lezi",
    "Vteřina zpoždění: Honi mu přesně podle jeho pokynů, ale vždycky až o vteřinu později. Cíl: čtyři minuty a zpoždění nezkrátit.|240|vedle_on_lezi",
    "Jeho ruce na tvých ramenou: Posaď si ho proti sobě, ať se drží tvých ramen, a honi mu. Cíl: čtyři minuty – jakmile ruce sundá, přestáváš.|240|sed_celem",
    "Dotýkej se ho jedním prstem a celou minutu nezměň tempo.|60|vedle_on_lezi",
    "Dva hlasy: Střídej šeptání a normální hlas a dotýkej se ho podle toho jemně nebo silně. Cíl: ať pozná systém.|240|vedle_on_lezi",
    "Dej mu ruce za záda a dotýkej se ho celou dobu jen zepředu.|240|klek_ruce_za_zady!",
    "Nech ho sedět na kraji postele a dotýkej se ho, zatímco klečíš před ním.|300|oral_on_vsede",
    "Zavaž mu oči a nech ho hádat, kde bude další polibek. Když uhodne, dostane ho jinam.|240|vedle_on_lezi",
    "Dotýkej se ho, ale zastav se pokaždé, když otevře pusu.|240|vedle_on_lezi",
    "Pět zastavení: Honi mu pět minut a pětkrát se úplně zastav a nech ruku ležet. On nesmí vědět kdy. Cíl: překvapit ho pokaždé.|300|vedle_on_lezi",
    "Popíše a dostane: Nech ho nahlas popsat, jaký dotek by teď chtěl, a pak mu ho dej úplně přesně. Cíl: tři přání a ani jedno nezměnit.|240|vedle_on_lezi",
    "Dej mu ruku na svou a nech ho vést tvoje prsty po jeho těle.|240|vedle_on_lezi",
    "Za jeho zády: Stoupni si za něj a dotýkej se ho tak, aby nikdy neviděl, co chystáš. Cíl: čtyři minuty a nenechat ho se otočit.|240|stoje_zezadu!",
    "Klečí se zavřenýma očima: Poruč mu, ať si klekne se zavřenýma očima, a pak ho zezadu hlaď po hrudi a penisu. Cíl: nechat ho čekat celou minutu.|120|klek_ruce_za_zady!",
    "Sto vteřin: Dotýkej se ho přesně sto vteřin a pak přestaň, ať je kdekoli. Cíl: nepřetáhnout.|120|vedle_on_lezi",
    "Nech ho ležet na boku a dotýkej se ho jen na zádech a bocích.|240|lzicka",
    "Zavaž mu oči a dej mu do ruky pírko. Ať se dotýká sám a ty se díváš.|240",
    "Dotýkej se ho a vždycky, když řekne víc, o kousek zpomalíš.|240|vedle_on_lezi",
    "Jediné místo: Nech ho vybrat jedno místo – penis, bradavky, krk – a pět minut se věnuj jenom jemu. Cíl: ani jednou nesjet jinam.|300|vedle_on_lezi",
    "Souhra dechu: Dotýkej se ho jen při jeho výdechu, při nádechu přestaň. Cíl: udržet to celou dobu.|240|vedle_on_lezi",
    "Dej mu ruce na oči a nech je tam. Pak se dotýkej, kde chceš.|240|vedle_on_lezi",
    "Nech ho stát a dotýkej se ho, zatímco se drží zdi.|240|zed",
    "Slovo na zastavení: Honi mu a domluvte slovo, po kterém vždycky okamžitě přestaneš. Cíl: ať ho použije aspoň třikrát.|300|vedle_on_lezi",
    "Dotýkej se ho přes prostěradlo. Nikdy pod ním.|180|vedle_on_lezi",
    "Tři za minutu: Na každou minutu máš povolené jen tři doteky, vyber je dobře. Cíl: vydržet pět minut.|300|vedle_on_lezi",
    "Nech ho ležet na břiše a dotýkej se ho jen na zadní straně těla.|300|masaz_zada!",
    "Zavaž mu oči a nech ho poznat po hmatu, jakou částí těla ho hladíš.|240|vedle_on_lezi",
    "Dotýkej se ho a pokaždé, když se zasměje, začínáš od hlavy.|240|vedle_on_lezi",
    "Sedni si mu na klín zády a nehýbej se, dokud nezačne prosit.|240|klin_zady",
    "Jeden prst a hodně času: Celý úkol se ho smíš dotýkat jen jedním prstem. Cíl: dokázat, že to stačí.|300|vedle_on_lezi",
    "Nech ho, ať drží kostku ledu, dokud ji celou nerozpustí. Mezitím ho hlaď.|240|vedle_on_lezi",
    "Dotýkej se ho a mezi doteky se vždy na chvíli úplně vzdal.|240|vedle_on_lezi",
    "Vidět, nebo jen cítit: Nech ho vybrat, jestli chce vidět, nebo cítit – a pak mu zavaž oči tak jako tak a hlaď ho po celém těle. Cíl: nedat se uprosit.|240|vedle_on_lezi",
    "Dotýkej se ho, ale nikdy oběma rukama najednou.|240|vedle_on_lezi",
    "Deset a pauza: Deset vteřin se mu věnuješ, deset vteřin nic. A tak dokola. Cíl: nikdy pauzu nevynechat.|300|vedle_on_lezi",
    "Nech ho klečet a dotýkej se ho shora. On nesmí zvednout ruce.|240|klek_ruce_hlava!",
    "Dotýkej se ho a ptej se ho po každém doteku, jestli chce znovu.|240|vedle_on_lezi",
    "Hledá tvoje rty poslepu: Zavaž mu oči a nech ho hledat tvoje rty jen podle dechu. Cíl: pět polibků a pokaždé se přesunout jinam.|180|objeti",
    "Dotýkej se ho přesně tak, jak ti to předvedl na sobě.|240|vedle_on_lezi",
    "Vlastní tempo: On počítá nahlas do dvaceti a ty se musíš stihnout dotknout každého čísla jinde. Cíl: dvacet různých míst.|180|vedle_on_lezi",
    "Dotýkej se ho, dokud neřekne stop. Pak počkej, dokud neřekne pokračuj.|300|vedle_on_lezi",
    "Nech ho ležet mezi tvýma nohama a hlaď ho odshora.|300|klin_podlaha!",
    "Dotýkej se ho jen přes jednu vrstvu oblečení, kterou si sám vybere.|240|vedle_on_lezi",
    "Nakonec mu sundej šátek a nech ho, ať se na tebe podívá. Nic neříkej.|60|vedle_on_lezi",
  ],
});
