// Kategorie 2 – Smyslné doteky
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 2,
  name: "Smyslné doteky",
  description: "Nahá kůže, šikovné ruce, první vibrace. Dráždit, ale ještě nepouštět.",

  // Úkoly pro muže – pro potěšení ženy
  male: [
    "Svlékni ji úplně donaha a namasíruj jí celé tělo olejem. Klín a prsa si nech až na úplný konec.|300",
    "Přikládej jí vibrátor přes kalhotky na klitoris – střídej lehký dotek a pevnější přitlačení.|90",
    "Přejížděj jí pírkem po bradavkách a pak po vnitřní straně stehen. Ona má ruce za hlavou.|90",
    "Zajeď jí rukou do kalhotek a jen dlaní ji pomalu hlaď. Prsty dovnitř zatím ne.|60",
    "Posaď ji na kuchyňskou linku, sundej jí kalhotky a prsty ji hlaď po stydkých pyscích.|90",
    "Lehni si za ni, když leží na boku, a jednou rukou jí hlaď prsa, druhou klín.|120",
    "Ve sprše jí namydli prsa a klín a pomalu ji omývej – hlavně tam, kde to má nejradši.|120",
    "Olízni si prsty a pomalu kroužkuj kolem jejího klitorisu.|60",
    "Posaď ji na gauč, roztáhni jí nohy a vibrátorem jí přejížděj po vnitřní straně stehen – ke klínu jen na chvilku.|60",
    "Jemně jí sevři bradavky mezi prsty a pomalu je mnuj. Sleduj, jak na to reaguje.|60",
    "Zavaž jí oči a hlaď ji po celém těle střídavě pírkem, prsty a vibrátorem.|120",
    "Vsuň do ní pomalu jeden prst a jen ho tam nech, zatímco ji líbáš.|45",
    "Stoupni si za ni před zrcadlo, obě ruce jí dej mezi nohy a nech ji, ať se dívá, co s ní děláš.|90",
    "Namaž jí prsa olejem a masíruj je – pomalu, dokola, s palci přes bradavky.|90",
    "Posaď ji nahou na pračku, ideálně když odstřeďuje, a prsty ji hlaď po klíně, zatímco se pod ní všechno třese.|60",
    "Hlaď ji dvěma prsty po klitorisu přes kalhotky, dokud nejsou vlhké.",
    "Posaď ji do křesla, přehoď jí nohy přes opěrky a prsty ji pomalu hlaď. Dívej se jí do očí.|90",
    "Polož vibrátor na nejnižší stupeň na její podbřišek a pomalu ho posouvej níž.|60",
    "Přejeď jí jazykem po bradavkách, střídavě po jedné a druhé, a foukni na ně.|60",
    "Nech ji ležet na zádech a vibrátorem jí kroužkuj kolem bradavek.|60",
    "Vsuň do ní dva prsty a hledej bod G – pohyb „pojď sem“ proti přední stěně.|90",
    "Vezmi její ruku a veď ji po jejím vlastním těle mezi nohy. Ty jen řídíš tempo.|60",
    "Na posteli ji nech ležet na břiše, roztáhni jí nohy a zezadu ji hlaď po klínu.|90",
    "V koupelně ji posaď na okraj vany a sprchou jí jemně masíruj klín.|60",
    "Pusť vibrátor na nejvyšší stupeň, ale přikládej ho jen na vnitřní stranu stehen. Ke klitorisu pouze na tři vteřiny.|60",
    "Posaď se na gauč, ona si sedne před tebe zády k tobě mezi tvé nohy. Hlaď ji rukama po prsou a klínu.|120",
    "Stáhni jí kalhotky jen ke kolenům a pomalu jí přejížděj prsty mezi nohama.|60",
    "Pírkem ji šimrej na stydkých pyscích a klitorisu. Hodně zlehka.|45",
    "Hlaď jí prsa a zároveň jí vibrátorem dráždi klitoris přes kalhotky.|90",
    "Dej jí ruce nad hlavu a řekni, že je nesmí sundat. Pak jí hlaď celé tělo, zastav se všude, kde vzdychne.|120",
    "Líbej ji na rty a přitom ji prsty pomalu dráždi mezi nohama.|90",
    "Nech ji stát opřenou rukama o kuchyňský stůl a zezadu jí zajeď rukou mezi nohy.|60",
    "Masíruj jí stydký pahorek dlaní v pomalých kruzích.|60",
    "Svlékni ji donaha a prohlížej si ji. Řekni jí nahlas pět věcí, které na jejím nahém těle miluješ.",
    "Namaž si ruce olejem a masíruj jí vnitřní stranu stehen. Hřbetem ruky se občas otři o její klín.|90",
    "Opři ji o zeď v chodbě, klekni si a polib ji přes kalhotky přímo na klín.",
    "Dráždi jí klitoris jedním prstem a druhou rukou jí hlaď bradavku ve stejném rytmu.|90",
    "Nech ji ležet na zádech na posteli a pomalu jí přejížděj vibrátorem od krku přes prsa a břicho až ke klínu.|90",
    "Vsuň do ní prst a pomalu s ním kroužkuj, zatímco palcem hladíš klitoris.|60",
    "Ve sprše se k ní přitiskni zezadu a hlaď jí prsa i klín pod tekoucí vodou.|120",
    "Pomalu z ní stáhni kalhotky zuby.",
    "Posaď ji na židli a klekni si před ni. Líbej a olizuj jí bradavky, rukou ji hlaď na klíně.|90",
    "Vezmi oba vibrátory a přilož jí je na obě bradavky zároveň.|45",
    "Hlaď ji mezi nohama tak dlouho, dokud nezačne sama přirážet boky proti tvé ruce.",
    "Stoupni si za ni, zajeď jí rukou do kalhot a pomalu ji prsty dráždi, zatímco jí šeptáš do ucha.|60",
    "Nech ji lehnout na gauč s polštářem pod zadečkem a hlaď ji dlaní přes celý klín.|90",
    "Přejeď jí kostkou ledu po bradavkách a pak je zahřej ústy.",
    "Zavaž jí oči a dotýkej se jí jen vibrátorem. Ať hádá, kam ho přiložíš příště.|90",
    "Rozetři jí lubrikant po klíně a pomalu ji hlaď celou dlaní.|60",
    "Prsty ji roztáhni a pomalu jí přejížděj konečkem prstu nahoru a dolů.|45",
    "Nech ji sedět na kuchyňské lince s roztaženýma nohama a přikládej jí vibrátor na klitoris. Líbej ji přitom.|90",
    "Lehni si vedle ní a pozoruj ji, jak se sama hladí. Smíš jí jen hladit prsa.|120",
    "Hlaď ji mezi nohama a zpomal pokaždé, když začne zrychlovat dech.|120",
    "Masíruj jí zadeček olejem, pomalu a pevně. Prsty občas sklouzni mezi nohy.|90",
    "Stáhni jí podprsenku a jazykem kresli kolečka kolem dvorců.|60",
    "Opři ji o okenní parapet se zataženými závěsy a zezadu ji hlaď rukou mezi nohama.|60",
    "Posaď si ji na klín čelem k sobě, oba nazí, a jen ji hlaď po zádech a zadečku, zatímco se o tebe otírá.|90",
    "Vsuň do ní dva prsty a nech je v klidu. Ona se na nich musí hýbat sama.|60",
    "Klekni si mezi její nohy a pomalu ji hlaď, přitom jí líbej vnitřní stranu stehen.|90",
    "Přitlač vibrátor na její podbřišek těsně nad stydkou kostí a druhou rukou ji hlaď po klitorisu.|60",
    "Pírkem jí přejížděj po zadečku a mezi hýžděmi, zlehka.|45",
    "Na posteli ji nech ležet na břiše a přikládej jí vibrátor zespodu mezi nohy, ať se o něj může otírat.|90",
    "Nech ji stát nahou v kuchyni a obejdi ji. Pokaždé, když jsi za ní, jí přejeď rukou po klíně.|60",
    "Masíruj jí prsa oběma rukama a hlaď palci bradavky, dokud neztvrdnou.",
    "Olízni jí bradavku a hned na ni přilož vibrátor.|45",
    "Rychle a lehce jí prsty ťukej na klitoris, pak zpomal do dlouhých tahů. Opakuj.|90",
    "Nech ji ležet na zádech, klekni si nad ni a jen ji konečky prstů hlaď od kolen až k prsům, pořád dokola.|90",
    "Ve vaně nebo sprše jí vezmi sprchovou hlavici a pusť jí proud vody na klín.|90",
    "Nech ji, ať si lehne na gauč a roztáhne nohy. Dívej se na ni a popisuj, co vidíš a co s tím chceš udělat.",
    "Hlaď ji přes kalhotky, pak pod nimi, pak zase přes ně. Střídej to.|90",
    "Zavaž jí oči, svlékni ji a hlaď ji všude – kromě klína. Až tě poprosí, dotkni se.",
    "Vsuň do ní prst a pomalu ho vytahuj a zasouvej, přitom ji líbej na krk.|60",
    "Palcem jí masíruj klitoris v kolečkách, ukazováčkem ji hlaď u vstupu.|90",
    "Stoupni si s ní před zrcadlo. Ona si drží prsa, ty jí přikládáš vibrátor mezi nohy.|90",
    "Postav ji na chodbě zády ke zdi, klekni si a hlaď ji prsty po klíně, zatímco se dívá dolů na tebe.|60",
    "Pomalu jí přejížděj vlhkým prstem po rtech a pak po bradavkách.",
    "Nech ji ležet na zádech. Jedním vibrátorem jí dráždi bradavku, druhým vnitřní stranu stehna.|60",
    "Rozetři jí olej po prsou a břiše a pak si na ni lehni, ať kloužete tělo na tělo.|60",
    "Hlaď ji prsty, dokud se nezačne chvět – pak přestaň, polib ji a začni znovu.",
    "Posaď ji obkročmo na své stehno a nech ji, ať se o něj pomalu otírá. Ty jí hlaď prsa.|90",
    "Na posteli jí dej ruce za hlavu a jemně jí je přidrž jednou rukou. Druhou ji hlaď mezi nohama.|90",
    "Přejížděj jí jazykem po břiše od prsou až k lemu kalhotek – a zase zpátky.|60",
    "Nech ji ležet na boku a zezadu jí vsuň prsty mezi nohy, zatímco ji líbáš na krk.|90",
    "Vibrátorem přes kalhotky jí dělej pomalé osmičky kolem klitorisu.|60",
    "Masíruj jí chodidla olejem a pomalu stoupej výš až ke klínu. Zastav se těsně před ním.|120",
    "Dva prsty do ní, palec na klitoris a pomalé rytmické stlačování jako při masáži.|90",
    "Posaď ji na jídelní stůl, lehni ji na záda a hlaď jí celé tělo od krku až po kolena.|90",
    "Nahou ji obejmi zezadu a veď jejími vlastními prsty po jejím klitorisu.|60",
    "Pírkem jí přejížděj po klitorisu a hned potom jí na něj foukni.|30",
    "Nech ji klečet na gauči opřenou o opěradlo a zezadu ji prsty dráždi.|90",
    "Hlaď jí bradavky ledovou kostkou a klín teplou dlaní současně.|45",
    "Přilož vibrátor na své prsty a teprve těmi vibrujícími prsty ji hlaď.|60",
    "Lehni si vedle ní, dej jí ruku mezi nohy a nech ji, ať si sama řekne rychlost – pomaleji, rychleji, silněji.|120",
    "Líbej ji po krku a prsou a zároveň ji pomalu hlaď po stehnech – pokaždé o kousek blíž.|90",
    "Rozetři jí lubrikant mezi nohama a pomalu ji hlaď od klitorisu až ke vstupu.|60",
    "Nech ji na posteli ležet na zádech s rukama podél těla. Dotknout se tě nesmí – ty ji hladíš všude, kde chceš.|120",
    "Stoupni si za ni ve sprše a jednou rukou jí drž prsa, druhou ji hlaď mezi nohama.|90",
    "Polož jí vibrátor na klitoris přes kalhotky a nech ho tam ležet. Ty ji zatím líbej na rty.|60",
    "Hlaď ji pomalu po zadečku, stehnech a klínu tak, jako by to byla ta nejvzácnější věc na světě.|90",
    "Posaď ji na postel, klekni si před ni a pomalu jí stáhni kalhotky. Pak ji polib na klín – jen jednou.",
    "Přitlač svůj nahý hrudník na její prsa a pomalu se o ni otírej, zatímco ji prsty hladíš mezi nohama.|60",
    "Vezmi její kalhotky, přetáhni je stranou a hlaď ji prsty pod nimi.|60",
    "V kuchyni ji opři o linku, klekni si za ni a hlaď jí stehna zezadu až ke klínu.|60",
    "Přitlač dlaň na její klín a jen ho drž teplou rukou, zatímco jí olizuješ bradavku.|45",
    "Obkroč ji, když leží na zádech, a přejížděj jí vibrátorem po celém těle. Kde vzdychne, tam se zdrž.|90",
    "Namaž si prsty olejem a pomalu jimi přejížděj mezi jejími prsy a dolů po břiše.|45",
    "Klekni si nad ní, drž jí ruce nad hlavou a pomalu se o ni otírej svým tělem, ale dovnitř nic.|60",
    "Nech ji sedět na tvé noze a hlaď ji, jak nejpomaleji umíš. Ona nesmí zrychlit.|90",
    "Hlaď jí klitoris jen konečkem vlhkého prstu, sotva znatelně.|60",
    "Posaď ji na gauč a roztáhni jí nohy. Jedním vibrátorem jí dráždi klitoris, druhým ji hlaď po bradavkách.|60",
    "Vsuň do ní prst a jemně tlač nahoru, zatímco druhou rukou tlačíš zvenku na podbřišek.|60",
    "Stáhni ji k okraji postele, klekni si na zem a pomalu ji hlaď prsty mezi nohama.|90",
    "Namaž jí olejem zadeček a stehna a masíruj je tak, aby se tvoje prsty pořád vracely ke klínu.|90",
    "Na chvíli jí zakaž se hýbat. Hlaď ji prsty, a kdyby se pohnula, začni znovu od kolen.|90",
  ],

  // Úkoly pro ženu – pro potěšení muže
  female: [
    "Svlékni ho úplně donaha a namasíruj mu celé tělo olejem. Penis si nech až na úplný konec.|300",
    "Přikládej mu vibrátor přes boxerky na penis – pomalu po celé délce nahoru a dolů.|90",
    "Přejížděj mu pírkem po bradavkách, podbřišku a vnitřní straně stehen. On má ruce za hlavou.|90",
    "Zajeď mu rukou do boxerek a jen ho dlaní pomalu hlaď.|60",
    "Posaď ho na gauč, stáhni mu boxerky a pomalu ho hlaď oběma rukama.|90",
    "Lehni si za něj, když leží na boku, a jednou rukou ho hlaď po hrudi, druhou po penisu.|120",
    "Ve sprše ho namydli a pomalu ho omývej – hlavně penis a varlata.|120",
    "Namaž si ruce olejem a pomalu mu přejížděj po penisu, jednou rukou po druhé.|90",
    "Nech ho sedět na židli, klekni si mezi jeho nohy a hlaď ho po stehnech a varlatech.|60",
    "Olízni mu bradavky a přitom ho rukou pomalu hlaď přes boxerky.|60",
    "Zavaž mu oči a hlaď ho po celém těle střídavě pírkem, prsty a vibrátorem.|120",
    "Stoupni si za něj před zrcadlo, obejmi ho a obě ruce mu dej na penis. Ať se dívá.|90",
    "Sedni si na kuchyňskou linku nahá a nech ho, ať se dívá. Mezitím ho nohou hlaď po stehně.|60",
    "Masíruj mu varlata dlaní, jemně a pomalu, zatímco ho líbáš na krk.|60",
    "Nahá si na něj lehni a pomalu se o něj otírej prsy.|60",
    "Vezmi vibrátor a přikládej mu ho na hráz (mezi varlaty a konečníkem).|60",
    "Hlaď ho přes kalhoty tak dlouho, dokud mu úplně neztvrdne.",
    "Posaď ho do křesla, klekni si před něj a sevři jeho penis mezi prsy.|60",
    "Nech ho ležet na zádech a vibrátorem mu přejížděj po penisu od kořene až ke špičce.|60",
    "Jemně mu stiskni bradavky a pak je olízni.|45",
    "Rozetři si lubrikant na dlaně a pomalu ho hlaď kroutivým pohybem.|90",
    "Nech ho klečet na posteli, stoupni si za něj a hlaď ho zezadu po penisu a varlatech.|90",
    "Ve sprše mu stoupni za záda, přitiskni se k němu a pod tekoucí vodou ho hlaď po penisu.|120",
    "Přejeď mu kostkou ledu po bradavkách a hned je zahřej ústy.",
    "Posaď se mu na klín nahá, zády k němu, a pomalu se o něj otírej.|60",
    "Dej mu ruce nad hlavu a řekni, že je nesmí sundat. Pak ho hlaď po celém těle.|120",
    "Líbej ho na rty a zároveň mu pomalu hlaď penis.|90",
    "Nech ho stát opřeného rukama o kuchyňský stůl a zezadu mu zajeď rukou mezi nohy.|60",
    "Pírkem ho šimrej po penisu a varlatech. Hodně zlehka.|45",
    "Vezmi oba vibrátory a přilož mu je z obou stran na penis.|45",
    "Svlékni se donaha a lehni si na gauč. Hlaď se přitom, jak se na tebe dívá. On se nesmí dotknout.|120",
    "Stáhni mu boxerky zuby.",
    "Namaž mu olejem vnitřní stranu stehen a hřbetem ruky se občas otři o jeho varlata.|90",
    "Opři ho o zeď v chodbě, klekni si a polib ho přes boxerky.",
    "Hlaď ho jednou rukou po penisu a druhou po bradavce ve stejném rytmu.|90",
    "Rukou ho hlaď jen po špičce, pomalu dokola, s lubrikantem.|60",
    "Posaď se nahá na jídelní stůl, přitáhni si ho mezi nohy a hlaď ho, ale do sebe ho nepusť.|90",
    "Namaž si prsa olejem a otírej se jimi o jeho záda, když leží na břiše.|90",
    "Nech ho ležet na zádech a hlaď ho pomalu, dokud se nezačne sám hýbat proti tvé ruce. Pak zpomal.",
    "Chyť jeho penis a pomalu si ho přejížděj po bradavkách.|45",
    "Zavaž mu oči a dotýkej se ho jen vibrátorem. Ať hádá, kam ho přiložíš příště.|90",
    "Nech ho sedět v křesle a sedni si mu nahá obkročmo na stehno. Pomalu se o něj otírej.|90",
    "Masíruj mu zadek olejem, pomalu a pevně. Prsty občas sklouzni mezi nohy k varlatům.|90",
    "Stoupni si za něj ve sprše a jednou rukou mu hlaď hruď, druhou penis.|90",
    "Lehni si vedle něj a hlaď ho, ale nech ho, ať si sám řekne tempo – pomaleji, rychleji, silněji.|120",
    "Nech ho ležet na zádech. Klekni si nad něj a jen konečky prstů ho hlaď od kolen až ke krku, pořád dokola.|90",
    "Stáhni mu boxerky jen ke kolenům a pomalu ho hlaď po celé délce.|60",
    "Hlaď ho rukou přes boxerky, pak pod nimi, pak zase přes ně. Střídej to.|90",
    "Nahá se přitiskni k jeho zádům, obejmi ho a veď jeho ruku po jeho vlastním penisu.|60",
    "Hlaď ho jednou rukou po penisu a druhou mu jemně masíruj varlata.|90",
    "Lehni si na postel nahá na břicho a nech ho, ať se dívá. Zavlň se boky a pak ho zavolej, ať si lehne vedle.",
    "Na chodbě ho opři zády o zeď, klekni si a hlaď ho rukou, zatímco se ti dívá do očí.|60",
    "Nech ho sedět na gauči. Posaď se mezi jeho nohy zády k němu a zajeď rukama za sebe na jeho penis.|60",
    "Přitlač vibrátor na jeho podbřišek těsně nad penisem a druhou rukou ho hlaď.|60",
    "Pírkem mu přejížděj po zadku a mezi hýžděmi, zlehka.|45",
    "Svlékni se před ním donaha a řekni mu, ať si vybere jedno místo na tvém těle, kterého se smí dotknout.|60",
    "Přejeď mu jazykem po břiše od hrudníku až k lemu boxerek – a zase zpátky.|60",
    "Nech ho ležet na zádech. Klekni si mu mezi nohy a otírej se prsy o jeho penis.|60",
    "Rozetři mu olej po hrudi a břiše a lehni si na něj, ať kloužete tělo na tělo.|60",
    "Hlaď ho rukou, dokud nezačne těžce dýchat – pak přestaň, polib ho a začni znovu.",
    "Obkroč ho, když leží, a pomalu se o něj otírej klínem přes kalhotky.|90",
    "Dej mu ruce za hlavu a jednou rukou mu je podrž. Druhou ho hlaď po penisu.|90",
    "Nech ho ležet na boku a zezadu mu vsuň ruku mezi nohy k varlatům a penisu.|90",
    "Vibrátorem přes boxerky mu kresli pomalé osmičky kolem špičky.|60",
    "Masíruj mu chodidla olejem a pomalu stoupej výš až k jeho klínu. Zastav se těsně před ním.|120",
    "Stiskni mu penis u kořene a pomalu ho hlaď druhou rukou ke špičce.|60",
    "Nech ho klečet na gauči opřeného o opěradlo a zezadu ho hlaď rukou.|90",
    "Přilož vibrátor na své prsty a teprve těmi vibrujícími prsty ho hlaď.|60",
    "Nahá se před ním protáhni na koberci v obýváku – pomalu, jako kočka. Dotknout se tě nesmí.|60",
    "Líbej ho po krku a hrudi a zároveň ho hlaď po stehnech – pokaždé o kousek blíž.|90",
    "Na posteli ho nech ležet na zádech s rukama podél těla. Dotknout se tě nesmí – ty ho hladíš, kde chceš.|120",
    "Polož mu vibrátor přes boxerky na penis a nech ho tam ležet. Ty ho zatím líbej na rty.|60",
    "Klekni si na postel, ať máš zadeček u jeho obličeje, a nech ho, ať se dívá. Mezitím ho hlaď rukou.|60",
    "Stáhni ho k okraji postele, klekni si na zem a pomalu ho hlaď oběma rukama.|90",
    "Jemně mu přejížděj nehty po vnitřní straně stehen a přes varlata.|45",
    "V kuchyni ho opři o linku a zezadu mu rukou zajeď do kalhot.|60",
    "Obkroč ho, když leží, a přejížděj mu vibrátorem po celém těle. Kde zasténá, tam se zdrž.|90",
    "Namaž si prsa olejem a nech ho, ať se ti otírá penisem mezi nimi, zatímco je držíš u sebe.|90",
    "Hlaď ho, jak nejpomaleji umíš. On nesmí přirážet.|90",
    "Hlaď ho jen konečky prstů pod špičkou, sotva znatelně.|60",
    "Posaď ho na gauč. Jedním vibrátorem mu dráždi varlata, druhým bradavky.|60",
    "Nahá se k němu otoč zády, předkloň se a pomalu si stáhni kalhotky až ke kotníkům.",
    "Zavaž mu oči, svlékni ho a hlaď ho všude – kromě penisu. Až tě poprosí, dotkni se ho.",
    "Masíruj mu hráz prsty v pomalých kolečkách, zatímco ho druhou rukou hladíš po penisu.|90",
    "Nech ho stát nahého v obýváku a obcházej ho. Pokaždé, když jsi za ním, přejeď mu rukou mezi nohy.|60",
    "Stoupni si s ním před zrcadlo. Ty ho hladíš, on se dívá na tebe i na sebe.|90",
    "Posaď se na postel, nohy dej kolem jeho pasu a hlaď ho pomalu rukama mezi svými stehny.|90",
    "Ve vaně nebo sprše mu pusť proud teplé vody na varlata a penis.|60",
    "Vezmi jeho ruku, polož si ji na prsa a ty ho zatím hlaď po penisu – oba stejným tempem.|90",
    "Namaž mu penis lubrikantem a jen ho pomalu mačkej a povoluj v dlani, bez pohybu.|60",
    "Lehni si nahá na něj a otírej se o něj, dokud nezačne sám tlačit boky proti tobě. Pak slez.",
    "Obě ruce mu dej na penis nad sebe a pomalu je otáčej proti sobě.|60",
    "Stoupni si nahá do dveří ložnice a pozvi ho prstem. Když přijde, hned mu zajeď rukou do kalhot.",
    "Hlaď ho rukou a zároveň mu jazykem kresli kolečka kolem bradavky.|90",
    "Nech ho ležet na zádech a posaď se nahá vedle jeho hlavy. Hlaď ho po penisu a nech ho, ať tě hladí po stehně.|90",
    "Namaž mu olejem zadek a stehna a masíruj je tak, aby se tvoje prsty pořád vracely k varlatům.|90",
    "Vezmi ho za penis a pomalu ho veď za sebou do ložnice.",
    "Na chvíli mu zakaž se hýbat. Hlaď ho, a kdyby se pohnul, začni znovu od kolen.|90",
    "Obleč si jen jeho košili nebo triko, sedni si mu na klín a hlaď ho rukou pod sebou.|60",
    "Otírej se nahými prsy o jeho obličej a hlaď ho přitom po penisu.|45",
    "Klekni si za něj na posteli, přitiskni prsa k jeho zádům a obě ruce mu dej mezi nohy.|90",
    "Hlaď ho kolem penisu – břicho, třísla, stehna, varlata – ale penisu samotného se nedotkni.|60",
    "Nech ho sedět na židli v kuchyni. Stoupni si nahá před něj a nech ho, ať si tě prohlíží zblízka – dotknout se nesmí.|45",
    "Pírkem ho šimrej na špičce penisu a hned na ni foukni.|30",
    "Pomalu mu stiskni zadek oběma rukama a přitáhni si jeho klín k sobě.",
    "Rozetři si lubrikant mezi stehny a nech ho, ať mezi nimi klouže – bez průniku.|90",
    "Hlaď ho rukou a přitom mu do ucha šeptej, jak je tvrdý a jak se ti to líbí.|60",
    "Posaď se na pračku, přitáhni si ho mezi nohy a hlaď ho, zatímco tě líbá.|60",
    "Vibrátor na nejnižší stupeň přiložený k varlatům, tvoje ruka na penisu.|60",
    "Lehni si vedle něj a hlaď ho tak dlouho, dokud neřekne „prosím“. Pak ještě chvíli.",
    "Namaž mu olejem hruď a pomalu ji masíruj, dokud se mu nezačnou chvět boky.|90",
    "Posaď se mu na obličej jen v kalhotkách na pár vteřin, pak slez a pokračuj rukou na jeho penisu.|60",
    "Klekni si na gauč a otírej se zadečkem o jeho klín, zatímco sedí.|60",
  ],
});
