// Kategorie 3 – Orální hrátky (dávka d)
// Témata: škádlení a odpírání, edging ústy, kombinace s pomůckami, počítané výzvy.
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 3,

  male: [
    "Na hranu a zpátky: Doveď ji ústy těsně k vrcholu, přestaň a počkej půl minuty. Cíl: třikrát na hranu a teprve počtvrté ji nechat dojít.|300|oral_klek",
    "Škádlení kolem: Celé tři minuty ji lízej všude kolem klitorisu, jen ne přímo na něm. Cíl: ať tě sama nasměruje rukou.|180|oral_klek",
    "Musí poprosit: Lízej ji jen tehdy, když tě o to nahlas poprosí. Jinak jen čekáš. Cíl: pět minut a nezačít ani jednou sám od sebe.|300|oral_klek",
    "Zákaz dojít: Lízej ji a zakaž jí vyvrcholit. Cíl: nepřestat, dokud tě nahlas neodprosí o svolení.|300|oral_klek",
    "Pětkrát na hranu: Doveď ji ústy pětkrát na hranu a pokaždé přestaň. Napošesté ji nech. Cíl: vydržet všech pět.|300|oral_klek",
    "Jazyk a vibrace na bradavce: Lízej ji a zároveň jí drž vibrátor na bradavce. Cíl: pět minut a ani jednou ho nesundat.|300|oral_klek",
    "Vibrátor uvnitř, jazyk venku: Vsuň do ní vibrátor a jazykem jí dráždi klitoris. Cíl: pět minut a obojí ve stejném rytmu.|300|oral_klek",
    "Zezadu jen zvenku: Lízej ji a prstem s lubrikantem jí zezadu krouži kolem, dovnitř nikdy. Cíl: pět minut a tempo řídí ona.|300|oral_klek",
    "Vibrátor si drží sama: Nech ji, ať si vibrátor drží sama, a ty ji lížeš odspodu. Cíl: pět minut a nesáhnout na vibrátor ani jednou.|300|oral_klek",
    "Nikdy neví co: Střídej vibrátor a jazyk po půl minutě. Cíl: deset střídání a pokaždé ji překvapit.|300|oral_klek",
    "Nejdřív ledová: Vezmi si do pusy kostku ledu, olízni ji a pak hned pokračuj horkým jazykem. Cíl: co největší rozdíl.|240|oral_klek",
    "Mokré prsty po břiše: Lízej ji a mezi tím jí mokrými prsty kresli po břiše písmena. Cíl: napsat celé slovo a ať ho uhodne.|240|oral_klek",
    "Bez jediného tření: Dej si na rty trochu lubrikantu a lízej ji tak, aby ses jí vlastně jen klouzal po kůži. Cíl: pět minut a nepřitlačit.|300|oral_klek",
    "Palec na hrázi: Lízej ji a druhou rukou jí palcem dráždi hráz. Cíl: pět minut a obojí ve stejném tempu.|300|oral_klek",
    "Počítá hrany: Lízej ji a nech ji nahlas počítat, kolikrát se dostane na hranu. Cíl: dojít aspoň ke čtyřem, než ji necháš dojít.|300|oral_klek",
    "Deset minut bez konce: Lízej ji střídavě rychle a pomalu, ale nesmíš ji nechat dojít, dokud čas neuběhne. Cíl: udržet ji na hraně.|300|oral_klek",
    "Prosím stojí deset vteřin: Lízej ji, ale pokaždé, když řekne prosím, na deset vteřin přestaneš. Cíl: pět minut a pravidlo dodržet do jedné.|300|oral_klek",
    "Popis místo prosby: Lízej ji a oznam jí, že smí dojít, jen když ti přesně popíše, co cítí. Cíl: nepolevit, dokud to neřekne celou větou.|300|oral_klek",
    "Známkování: Lízej ji a nech ji průběžně známkovat od jedné do desíti. Cíl: pět minut a ani jednou neklesnout pod osmičku.|300|oral_klek",
    "Ona diriguje: Nech ji, ať ti nahlas říká, co má dělat tvůj jazyk, a ty jen plníš. Cíl: pět minut a ani jednou si nedělat po svém.|300|oral_klek",
    "Hlas na povel: Lízej ji, ale musí nahlas říkat, co cítí. Kdykoli ztichne, přestaneš a čekáš. Cíl: pět minut a nejvýš tři pauzy.|300|oral_klek",
    "Nesmí si pomoct: Lízej ji a druhou rukou jí drž obě ruce, aby si nemohla pomoct sama. Cíl: pět minut a nepustit ji.|300|oral_klek",
    "Prsty ven v pravou chvíli: Vsuň jí dva prsty a lízej ji, ale kdykoli se blíží, ruku vytáhneš. Cíl: třikrát ji takhle zastavit.|300|oral_klek",
    "Minuta s roztaženýma nohama: Nech ji ležet s roztaženýma nohama a jen se dívej. Cíl: začít ji lízat až po celé minutě – a pak nepřestat.|120|oral_klek",
    "Až tě přitáhne: Lízej ji pomalu a stejným tempem. Cíl: nezrychlit, dokud ti sama netlačí hlavu k sobě.|300|oral_klek",
    "Tři minuty ticha: Lízej ji tři minuty a ani jeden z vás nesmí vydat hlásku. Cíl: úplné ticho.|180|oral_klek",
    "Až budou promočené: Lízej ji přes tenké kalhotky. Cíl: nesundat jí je, dokud nebudou úplně mokré.|240|oral_klek",
    "Dostane to druhé: Nech ji vybrat mezi jazykem a prsty a pak jí dej přesně to, co si nevybrala. Cíl: čtyři minuty a nepolevit.|240|oral_klek",
    "Vibrace na stehně: Lízej ji a zároveň jí přikládej vibrátor na vnitřní stranu stehna. Cíl: pět minut a ani jednou s ním nesjet výš.|300|oral_klek",
    "Každý jinam: Dej jí vibrátor, ať si ho přiloží kam chce, a ty lížeš vždycky někde jinde. Cíl: pět minut a nikdy se netrefit na stejné místo.|300|oral_klek",
    "Dvě pomůcky: Vibrátor na bradavce, druhý na klitorisu a ty lížeš dovnitř. Cíl: udržet obě na místě.|300|oral_klek",
    "Pohyb znamená zpomalit: Lízej ji a pokaždé, když pohne boky, zpomalíš. Cíl: pět minut a pravidlo dodržet do jedné.|300|oral_klek",
    "Ruce za hlavou: Lízej ji, zatímco leží s rukama za hlavou. Jakmile je sundá, přestáváš. Cíl: pět minut a nejvýš jedno přerušení.|300|oral_klek",
    "Ještě chvíli počkat: Lízej ji tak dlouho, dokud nezačne prosit. Cíl: po první prosbě vydržet ještě celou minutu.|300|oral_klek",
    "Až na tvoje slovo: Lízej ji a oznam jí, že smí dojít až na tvoje svolení. Dej jí ho co nejpozději. Cíl: vydržet aspoň pět minut.|300|oral_klek",
    "Pomalé odpočítávání: Lízej ji, oznam jí, že za tři minuty skončíš, a nahlas počítej poslední minutu. Cíl: dotáhnout to přesně na nulu.|180|oral_klek",
    "Vibrátor u hráze: Lízej ji a druhou rukou jí drž vibrátor zezadu u hráze. Cíl: pět minut a ani jednou ho neodložit.|300|oral_klek",
    "Neví, kdy konec: Zavaž jí oči a lízej ji v nepravidelných intervalech. Cíl: pět minut, při kterých nikdy neodhadne, kdy přestaneš.|300|oral_klek",
    "Od klína k prstům: Lízej ji a mezi tím jí vždycky olízni prsty u nohou. Cíl: deset střídání a nohu pokaždé vyměnit.|300|oral_klek",
    "Přitlačí, když chce: Lízej ji, polož si její ruku do vlasů a nech ji přitlačit, kdykoli chce víc. Cíl: reagovat na každé přitlačení.|300|oral_klek",
    "Tři pokusy: Lízej ji co nejpomaleji a ona má tři pokusy uhodnout slovo, kterým tě zrychlí. Cíl: jinak zůstáváš pomalý až do konce.|300|oral_klek",
    "Otevře oči, přestáváš: Lízej ji a pokaždé, když otevře oči, přestaneš. Cíl: pět minut a nejvýš dvě přerušení.|300|oral_klek",
    "Led jako časomíra: Dej jí do ruky kostku ledu a lízej ji. Cíl: smí dojít, až led v dlani úplně roztaje – dřív ne.|300|oral_klek",
    "Odpočítává si to sama: Lízej ji a nech ji nahlas říkat, kolik vteřin ještě vydrží. Cíl: pokaždé, když řekne číslo, o pět vteřin ho přidat.|300|oral_klek",
    "Ruce pryč z tvé hlavy: Lízej ji a ona se přitom nesmí ani jednou dotknout tvojí hlavy. Cíl: pět minut – za každý dotek přestáváš na deset vteřin.|300|oral_klek",
    "Zadržený dech: Ona se zhluboka nadechne a ty lížeš, dokud nevydechne. Pak pauza. Pět kol. Cíl: vydržet všech pět.|300|oral_klek",
    "Lízej ji a zároveň jí prsty dráždi bradavky. Obojí naráz.|300|oral_klek",
    "Nohy zkřížené za tvou hlavou: Lízej ji, zatímco má nohy zkřížené za tvou hlavou. Cíl: pět minut a nesmí tě ani jednou pustit.|300|nohy_ramena",
    "Lízej ji a mezi tím jí pomalu strkej vibrátor dovnitř.|300|oral_klek",
    "Dej jí lubrikant na prsty a nech ji, ať si sama pomáhá, zatímco ji lížeš.|300|oral_klek",
    "Kdo dřív: Ty ji lížeš a ona se snaží vydržet co nejdéle bez zvuku. Cíl: ať to nevydrží do dvou minut.|120|oral_klek",
    "Lízej ji a druhou rukou jí drž kolena od sebe.|300|oral_klek",
    "Nech ji vybrat, jak dlouho ji budeš lízat. Pak přidej minutu navíc.|300|oral_klek",
    "Lízej ji a mezi tím jí kousej do vnitřní strany stehen.|300|oral_klek",
    "Počítá tvoje tahy: Lízej ji dlouhými tahy a ona je nahlas počítá. Když se splete, začínáte od nuly. Cíl: dojít ke stovce.|300|oral_klek",
    "Jazyk a led: Střídej horký jazyk a kostku ledu po dvaceti vteřinách. Cíl: pět střídání za sebou.|240|oral_klek",
    "Lízej ji a pokaždé, když se nadechne zhluboka, přestaneš.|300|oral_klek",
    "Roztáhne si je sama: Nech ji, ať si sama roztáhne nohy přesně tak, jak to chce, a teprve pak ji začni lízat. Cíl: nic jí neupravovat.|300|oral_klek",
    "Lízej ji a mezi tím jí přejížděj pírkem po břiše.|300|oral_klek",
    "Dej si vibrátor pod bradu a lízej ji zároveň s ním.|300|oral_klek",
    "Dvojí zdroj: Vibrátor uvnitř a tvůj jazyk venku. Nikdy neuber ani jedno. Cíl: dovést ji tam oběma naráz.|300|oral_klek",
    "Lízej ji a nech ji, ať se drží čela postele. Nesmí pustit.|300|pouta_postel",
    "Přestaneš, kdy chceš ty: Lízej ji a oznam jí, že přestaneš, kdykoli se ti zachce. Cíl: pět takových pauz a ani jednu neohlásit dopředu.|300|oral_klek",
    "Lízej ji tak, aby se musela úplně odevzdat a nic neřídila.|300|oral_klek",
    "Za pohyb minuta navíc: Lízej ji a ona nesmí pohnout boky. Za každý pohyb si připíše minutu navíc. Cíl: dostat se přes pět minut.|300|oral_klek",
    "Lízej ji a pak najednou přestaň a chvíli se na ni jen dívej.|240|oral_klek",
    "Čtyři fáze: Lízej ji postupně škádlivě, pomalu, rychle a nakonec až do konce. Každá fáze minutu a čtvrt. Cíl: dodržet pořadí.|300|oral_klek",
    "Lízej ji s vibrátorem přiloženým zvenku na jejím podbřišku.|300|oral_klek",
    "Určí si konec: Nech ji říct, v kolikáté minutě má dojít, a lízej ji tak, abys to trefil. Cíl: strefit se na půl minuty přesně.|300|oral_klek",
    "Lízej ji a druhou rukou jí drž hlavu, aby se musela dívat.|300|oral_klek",
    "Ne dřív než za tři minuty: Lízej ji a oznam jí, že když dojde dřív než za tři minuty, dneska už nic dalšího nebude. Cíl: ať to vydrží.|180|oral_klek",
    "Vzestup po minutách: Lízej ji první minutu velmi jemně, druhou silněji a třetí naplno. Cíl: nikdy se nevrátit k slabšímu tlaku.|180|oral_klek",
    "Lízej ji a přitom si její nohy obtoč kolem svého krku.|300|nohy_ramena",
    "Rychle, nebo škádlit: Nech ji vybrat, jestli ji máš lízáním dovést rychle do konce, nebo ji dlouho škádlit. Cíl: dodržet její volbu.|300|oral_klek",
    "Lízej ji a mezi tím jí přejeď žínkou po stehnech.|300|oral_klek",
    "Vibrátor až na tvoje slovo: Lízej ji a vibrátor jí dej do ruky s tím, že ho smí použít až na tvoje slovo. Cíl: dát jí svolení co nejpozději.|300|oral_klek",
    "Lízej ji tak dlouho, dokud ti nezačne škubat stehny.|300|oral_klek",
    "Poslední slovo: Lízej ji a dovolení dojít dostane, až řekne jednu celou souvislou větu. Cíl: ať ji vůbec dokáže složit.|300|oral_klek",
    "Lízej ji a mezi tím jí lehce plácni na vnitřní stranu stehna.|300|oral_klek",
    "Nech ji držet si kolena a ty používej obě ruce i ústa.|300|nohy_ramena",
    "Lízej ji a pokaždé, když řekne tvoje jméno, zrychlíš.|300|oral_klek",
    "Konec až s orgasmem: Lízej ji a oznam jí, že tahle karta skončí až v okamžiku, kdy se udělá. Cíl: nepřestat, ať to trvá jakkoli dlouho.|300|oral_klek",
    "Dvě za sebou: Lízej ji až do orgasmu a pak pokračuj, dokud nedojde podruhé. Cíl: dvě za sebou bez jediné přestávky.|300|oral_klek",
    "Lízej ji pomalu i po vrcholu, dokud tě sama neodstrčí.|300|oral_klek",
    "Hlava na jejím stehně: Až dolížeš, polož jí hlavu na stehno a nech ji vydechnout. Cíl: celou minutu ji jen držet a nic nechtít.|60|oral_klek",
  ],

  female: [
    "Na hranu a zase zpět: Doveď ho ústy těsně k vrcholu, přestaň a počkej půl minuty. Cíl: třikrát na hranu a teprve počtvrté ho nechat dojít.|300|oral_on_vleze",
    "Škádlení kolem: Celé tři minuty olizuj všude kolem, jen ne tam, kde to chce. Cíl: ať tě sám nasměruje.|180|oral_on_vleze",
    "Musí si říct: Kouři mu jen tehdy, když tě o to nahlas poprosí. Jinak jen čekáš. Cíl: pět minut a nezačít ani jednou sama od sebe.|300|oral_on_vleze",
    "Zákaz se udělat: Kouři mu a zakaž mu se udělat. Cíl: nepřestat, dokud tě nahlas neodprosí o svolení.|300|oral_on_vleze",
    "Pětkrát na hranu: Doveď ho ústy pětkrát na hranu a pokaždé přestaň. Napošesté ho nech. Cíl: vydržet všech pět.|300|oral_on_vleze",
    "Vibrace na jeho bradavce: Kouři mu a zároveň mu drž vibrátor na bradavce. Cíl: pět minut a ani jednou ho nesundat.|300|oral_on_vleze",
    "Vibrace dole, jazyk nahoře: Přilož mu vibrátor na varlata a jazykem dráždi špičku. Cíl: pět minut a ani jednou se neprohodit.|300|oral_on_vleze",
    "Hráz jen zvenku: Kouři mu a prstem s lubrikantem mu krouži po hrázi, dovnitř nikdy. Cíl: pět minut a tempo řídí on.|300|oral_on_vleze",
    "Vibrátor si drží sám: Nech ho, ať si vibrátor drží sám, a ty mu kouříš. Cíl: pět minut a nesáhnout na vibrátor ani jednou.|300|oral_on_vleze",
    "Nikdy neuhodne: Střídej vibrátor a jazyk po půl minutě. Cíl: deset střídání a pokaždé ho překvapit.|300|oral_on_vleze",
    "Nejdřív ledová: Vezmi si do pusy kostku ledu, olízni ho a pak hned pokračuj horkým jazykem. Cíl: co největší rozdíl.|240|oral_on_vleze",
    "Písmena na jeho břiše: Kouři mu a mezi tím mu mokrými prsty kresli po břiše písmena. Cíl: napsat celé slovo a ať ho uhodne.|240|oral_on_vleze",
    "Bez tření: Dej si na rty trochu lubrikantu a kuř mu tak, aby ses mu jen klouzala. Cíl: pět minut a nepřitlačit.|300|oral_on_vleze",
    "Palec na jeho hrázi: Kouři mu a druhou rukou mu palcem dráždi hráz. Cíl: pět minut a obojí ve stejném tempu.|300|oral_on_vleze",
    "Počítá si hrany: Kouři mu a nech ho nahlas počítat, kolikrát se dostane na hranu. Cíl: dojít aspoň ke čtyřem, než ho necháš dojít.|300|oral_on_vleze",
    "Deset minut bez konce: Kouři mu střídavě rychle a pomalu, ale nesmíš ho nechat dojít, dokud čas neuběhne. Cíl: udržet ho na hraně.|300|oral_on_vleze",
    "Prosím tě stojí deset vteřin: Kouři mu, ale pokaždé, když řekne prosím, na deset vteřin přestaneš. Cíl: pět minut a pravidlo dodržet.|300|oral_on_vleze",
    "Popsat, ne prosit: Kuř mu a oznam mu, že smí dojít, jen když ti přesně popíše, co cítí. Cíl: nepolevit, dokud to neřekne celou větou.|300|oral_on_vleze",
    "Známky od něj: Kouři mu a nech ho průběžně známkovat od jedné do desíti. Cíl: pět minut a ani jednou neklesnout pod osmičku.|300|oral_on_vleze",
    "On diriguje: Nech ho, ať ti nahlas říká, co má dělat tvůj jazyk, a ty jen plníš. Cíl: pět minut a ani jednou si nedělat po svém.|300|oral_on_vleze",
    "Hlas na povel jemu: Kouři mu, ale musí nahlas říkat, co cítí. Kdykoli ztichne, přestaneš a čekáš. Cíl: pět minut a nejvýš tři pauzy.|300|oral_on_vleze",
    "Nesmí si pomoct sám: Kouři mu a druhou rukou mu drž obě ruce, aby si nemohl pomoct. Cíl: pět minut a nepustit ho.|300|oral_on_vleze",
    "Ruka pryč v pravou chvíli: Kouři mu s rukou u kořene, ale kdykoli se blíží, ruku sundáš. Cíl: třikrát ho takhle zastavit.|300|oral_on_vleze",
    "Minuta čekání pro něj: Nech ho ležet s roztaženýma nohama a jen se dívej. Cíl: vzít ho do pusy až po celé minutě – a pak nepřestat.|120|oral_on_vleze",
    "Až tě přitáhne on: Kouři mu pomalu a stejným tempem. Cíl: nezrychlit, dokud ti sám netlačí hlavu k sobě.|300|oral_on_vleze",
    "Tři minuty ticha: Kouři mu tři minuty a ani jeden z vás nesmí vydat hlásku. Cíl: úplné ticho.|180|oral_on_vleze",
    "Promočené trenýrky: Olizuj ho přes tenké trenýrky. Cíl: nesundat mu je, dokud nebudou úplně mokré.|240|oral_on_vleze",
    "Dostane to nevybrané: Nech ho vybrat mezi ústy a rukou a pak mu dej přesně to druhé. Cíl: čtyři minuty a nepolevit.|240|oral_on_vleze",
    "Vibrace na jeho stehně: Kouři mu a zároveň mu přikládej vibrátor na vnitřní stranu stehna. Cíl: pět minut a ani jednou s ním nesjet výš.|300|oral_on_vleze",
    "Každý jinde: Dej mu vibrátor, ať si ho přiloží kam chce, a ty ho ústy olizuj vždycky někde jinde. Cíl: nikdy se netrefit na stejné místo.|300|oral_on_vleze",
    "Dvě pomůcky: Vibrátor na bradavce, druhý na hrázi a ty ústy nahoře. Cíl: udržet obě na místě.|300|oral_on_vleze",
    "Pohne se, zpomalíš: Kouři mu a pokaždé, když pohne boky, zpomalíš. Cíl: pět minut a pravidlo dodržet do jedné.|300|oral_on_vleze",
    "Jeho ruce za hlavou: Kuř mu, zatímco leží s rukama za hlavou. Jakmile je sundá, přestáváš. Cíl: pět minut a nejvýš jedno přerušení.|300|oral_on_vleze",
    "Po první prosbě ještě minuta: Kouři mu tak dlouho, dokud nezačne prosit. Cíl: po první prosbě vydržet ještě celou minutu.|300|oral_on_vleze",
    "Až na tvoje svolení: Kuř mu a oznam mu, že se smí udělat až na tvoje svolení. Dej mu ho co nejpozději. Cíl: vydržet aspoň pět minut.|300|oral_on_vleze",
    "Odpočítávání pro něj: Kuř mu, oznam mu, že za tři minuty skončíš, a nahlas počítej poslední minutu. Cíl: dotáhnout to přesně na nulu.|180|oral_on_vleze",
    "Vibrátor u jeho hráze: Kouři mu a druhou rukou mu drž vibrátor zezadu u hráze. Cíl: pět minut a ani jednou ho neodložit.|300|oral_on_vleze",
    "Neví, kdy přestaneš: Zavaž mu oči a kuř mu v nepravidelných intervalech. Cíl: pět minut, při kterých nikdy neodhadne, kdy přestaneš.|300|oral_on_vleze",
    "Od klína k jeho prstům: Kouři mu a mezi tím mu vždycky olízni prsty u nohou. Cíl: deset střídání a nohu pokaždé vyměnit.|300|oral_on_vleze",
    "Jeho ruka ve tvých vlasech: Kuř mu, polož si jeho ruku do vlasů a nech ho přitlačit, kdykoli chce víc. Cíl: reagovat na každé přitlačení.|300|oral_on_vleze",
    "Tři pokusy pro něj: Kuř mu co nejpomaleji a on má tři pokusy uhodnout slovo, kterým tě zrychlí. Cíl: jinak zůstáváš pomalá až do konce.|300|oral_on_vleze",
    "Oči otevřel, konec: Kouři mu a pokaždé, když otevře oči, přestaneš. Cíl: pět minut a nejvýš dvě přerušení.|300|oral_on_vleze",
    "Led v jeho dlani: Dej mu do ruky kostku ledu a kuř mu. Cíl: smí se udělat, až led v dlani úplně roztaje – dřív ne.|300|oral_on_vleze",
    "Kouři mu a nech ho říkat, kolik vteřin ještě vydrží.|300|oral_on_vleze",
    "Jeho ruce pryč: Kuř mu a on se přitom nesmí ani jednou dotknout tvojí hlavy. Cíl: pět minut – za každý dotek přestáváš na deset vteřin.|300|oral_on_vleze",
    "Zadržený dech: On se zhluboka nadechne a ty kouříš, dokud nevydechne. Pak pauza. Pět kol. Cíl: vydržet všech pět.|300|oral_on_vleze",
    "Kouři mu a zároveň mu prsty dráždi bradavky. Obojí naráz.|300|oral_on_vleze",
    "Nohy zkřížené za tebou: Kuř mu, zatímco má nohy zkřížené za tvými zády. Cíl: pět minut a nesmí tě ani jednou pustit.|300|oral_on_vleze",
    "Kouři mu a mezi tím mu pomalu přikládej vibrátor k varlatům.|300|oral_on_vleze",
    "Dej mu lubrikant na dlaň a nech ho, ať si sám pomáhá, zatímco mu kouříš.|300|oral_on_vleze",
    "Kdo dřív: Ty mu kouříš a on se snaží vydržet co nejdéle bez zvuku. Cíl: ať to nevydrží do dvou minut.|120|oral_on_vleze",
    "Kouři mu a druhou rukou mu drž kolena od sebe.|300|oral_on_vleze",
    "Nech ho vybrat, jak dlouho mu budeš kouřit. Pak přidej minutu navíc.|300|oral_on_vleze",
    "Kouři mu a mezi tím mu kousej do vnitřní strany stehen.|300|oral_on_vleze",
    "Počítá tvoje tahy: Kuř mu dlouhými tahy a on je nahlas počítá. Když se splete, začínáte od nuly. Cíl: dojít ke stovce.|300|oral_on_vleze",
    "Horko a mráz: Kouři mu a po dvaceti vteřinách vždycky vyměň horký jazyk za kostku ledu. Cíl: pět střídání za sebou bez pauzy.|240|oral_on_vleze",
    "Kouři mu a pokaždé, když se nadechne zhluboka, přestaneš.|300|oral_on_vleze",
    "Roztáhne si je sám: Nech ho, ať si sám roztáhne nohy přesně tak, jak to chce, a teprve pak mu začni kouřit. Cíl: nic mu neupravovat.|300|oral_on_vleze",
    "Kouři mu a mezi tím mu přejížděj pírkem po břiše.|300|oral_on_vleze",
    "Dej si vibrátor do volné ruky a používej ho zároveň s ústy.|300|oral_on_vleze",
    "Dvojí zdroj: Vibrátor na varlatech a tvoje ústa nahoře. Nikdy neuber ani jedno. Cíl: dovést ho tam oběma naráz.|300|oral_on_vleze",
    "Kouři mu a nech ho, ať se drží čela postele. Nesmí pustit.|300|pouta_postel!",
    "Přestaneš, kdy chceš ty: Kuř mu a oznam mu, že přestaneš, kdykoli se ti zachce. Cíl: pět takových pauz a ani jednu neohlásit dopředu.|300|oral_on_vleze",
    "Kouři mu tak, aby se musel úplně odevzdat a nic neřídil.|300|oral_on_vleze",
    "Za pohyb minuta navíc: Kuř mu a on nesmí pohnout boky. Za každý pohyb si připíše minutu navíc. Cíl: dostat se přes pět minut.|300|oral_on_vleze",
    "Kouři mu a pak najednou přestaň a chvíli se na něj jen dívej.|240|oral_on_vleze",
    "Čtyři díly: Kuř mu postupně škádlivě, pomalu, rychle a nakonec až do konce. Každý díl minutu a čtvrt. Cíl: dodržet pořadí.|300|oral_on_vleze",
    "Kouři mu s vibrátorem přiloženým zvenku na jeho podbřišku.|300|oral_on_vleze",
    "Určí si konec: Nech ho říct, v kolikáté minutě se má udělat, a kuř mu tak, abys to trefila. Cíl: strefit se na půl minuty přesně.|300|oral_on_vleze",
    "Kouři mu a druhou rukou mu drž hlavu, aby se musel dívat.|300|oral_on_vleze",
    "Ne dřív než za tři minuty: Kuř mu a oznam mu, že když se udělá dřív než za tři minuty, dneska už nic dalšího nebude. Cíl: ať to vydrží.|180|oral_on_vleze",
    "Po minutách nahoru: Kouři mu první minutu úplně jemně, druhou silněji a třetí naplno. Cíl: nikdy se nevrátit k slabšímu tempu.|180|oral_on_vleze",
    "Kouři mu a přitom si jeho nohu opři o rameno.|300|oral_on_vleze",
    "Rychle, nebo škádlit jeho: Nech ho vybrat, jestli ho máš ústy dovést rychle do konce, nebo ho dlouho škádlit. Cíl: dodržet jeho volbu.|300|oral_on_vleze",
    "Kouři mu a mezi tím mu přejeď žínkou po stehnech.|300|oral_on_vleze",
    "Vibrátor na tvoje slovo: Kuř mu a vibrátor mu dej do ruky s tím, že ho smí použít až na tvoje slovo. Cíl: dát mu svolení co nejpozději.|300|oral_on_vleze",
    "Kouři mu tak dlouho, dokud mu nezačnou škubat stehna.|300|oral_on_vleze",
    "Poslední slovo: Kuř mu a dovolení se udělat dostane, až řekne jednu celou souvislou větu. Cíl: ať ji vůbec dokáže složit.|300|oral_on_vleze",
    "Kouři mu a mezi tím mu lehce plácni na vnitřní stranu stehna.|300|oral_on_vleze",
    "Nech ho držet si kolena a ty používej obě ruce i ústa.|300|oral_on_vleze",
    "Kouři mu a pokaždé, když řekne tvoje jméno, zrychlíš.|300|oral_on_vleze",
    "Konec až s jeho orgasmem: Kuř mu a oznam mu, že karta skončí až v okamžiku, kdy se udělá. Cíl: nepřestat, ať to trvá jakkoli dlouho.|300|oral_on_vleze",
    "Hned podruhé: Kuř mu až do konce a pak pokračuj jemně dál, dokud to snese. Cíl: vydržet u něj aspoň půl minuty po orgasmu.|300|oral_on_vleze",
    "Kouři mu pomalu i po vrcholu, dokud tě sám neodstrčí.|300|oral_on_vleze",
    "Hlava na jeho stehně: Až dokouříš, polož mu hlavu na stehno a nech ho vydechnout. Cíl: celou minutu ho jen držet a nic nechtít.|60|oral_on_vleze",
  ],
});
