// Kategorie 3 – Orální hrátky
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 3,
  name: "Orální hrátky",
  description: "Rty, jazyk a pořádná dávka trpělivosti. Tady se nikdo nikam nespěchá.",

  // Úkoly pro muže – pro potěšení ženy
  male: [
    "Dlouhé tahy zdola: Posaď ji na linku, klekni si před ni a lízej ji pomalými dlouhými tahy zdola nahoru. Cíl: třicet tahů, žádný rychlejší.|120|oral_vsede",
    "Tempo určuje ona: Lehni si na záda a nech ji sednout si ti na obličej. Cíl: tři minuty, při kterých se sám od sebe ani nepohneš.|180|oral_ona_nad_nim",
    "Abeceda jazykem: Dej si její nohy přes ramena a jazykem jí kresli na klitoris písmena abecedy. Cíl: dojít aspoň k písmenu M.|120|oral_vsede",
    "Jazyk dole, vibrace nahoře: Lízej ji a zároveň jí vibrátorem hlaď bradavky. Cíl: dvě minuty a ani jedno nepřerušit.|120|oral_klek",
    "Vzdech mění rytmus: Zavaž jí oči a lízej ji. Pokaždé, když vzdychne, změň rytmus. Cíl: deset změn a ani jednu nezmeškat.|120|oral_klek",
    "Rty a jazyk naráz: Jemně jí saj klitoris rty a přitom jazykem rychle kmitej. Cíl: celá minuta bez jediného přerušení.|60|oral_klek",
    "Jazyk a dva prsty: Lízej ji a vsuň do ní dva prsty, kterými děláš pohyb „pojď sem“ proti přední stěně. Cíl: dvě minuty a obojí ve stejném rytmu.|120|oral_klek",
    "Noha přes rameno u zdi: Opři ji zády o zeď, klekni si, dej si její nohu přes rameno a lízej ji. Cíl: půldruhé minuty a nenechat ji sklouznout.|90|zed",
    "Polštář pod boky: Nech ji ležet s polštářem pod zadečkem a lízej ji. Cíl: nepřestat, dokud sama neřekne dost.|180|oral_klek",
    "Nejdřív přes látku: Lízej ji přes kalhotky tak dlouho, dokud nebudou mokré. Cíl: teprve pak je odhrnout stranou a pokračovat.|120|oral_klek",
    "Vibrace nahoře, jazyk níž: Přikládej jí vibrátor na klitoris a jazykem ji lízej o kousek níž. Cíl: půldruhé minuty a ani jednou se neprohodit.|90|oral_klek",
    "69 na boku: Ležte oba na boku hlavou k nohám toho druhého a ližte se navzájem. Cíl: tři minuty a soustředit se hlavně na ni.|180|p69_bok",
    "Drží se opěradla: Posaď ji na židli, klekni si před ni a lízej ji, zatímco se drží opěradla. Cíl: dvě minuty a nesmí se pustit.|120|oral_vsede",
    "Až napotřetí: Líbej ji po vnitřní straně stehen až ke klínu, pak zpátky a znovu. Cíl: teprve při třetí cestě ji olíznout i mezi nohama.|120|oral_klek",
    "Zezadu vkleče: Nech ji klečet opřenou o opěradlo a lízej ji zezadu. Cíl: dvě minuty a držet ji přitom oběma rukama za boky.|120|zezadu",
    "Bradavky a prsty: Saj a olizuj jí bradavky střídavě, zatímco ji prsty hladíš mezi nohama. Cíl: deset střídání bez přerušení ruky.|90|vedle_ona_lezi",
    "Pod tekoucí vodou: Klekni si ve sprše, dej si její nohu na rameno a lízej ji. Cíl: půldruhé minuty a nenechat ji uklouznout.|90",
    "Čím víc pobízí, tím pomaleji: Lízej ji tak pomalu, jak jen dokážeš. Cíl: pokaždé, když tě chce popohnat, zpomalit ještě víc.|120|oral_klek",
    "Nehybný jazyk: Polož jí jazyk pevně na klitoris a vůbec s ním nehýbej. Cíl: celá minuta, při které se musí hýbat jen ona.|60|oral_klek",
    "Olízat dočista: Kápni jí šlehačku, med nebo čokoládu na bradavky a podbřišek. Cíl: olízat ji úplně dočista a nepoužít k tomu ruce.|120",
    "Nemůže uhnout: Lízej ji a přitom jí pevně drž boky oběma rukama. Cíl: dvě minuty a ani jednou ji nepustit.|120|oral_klek",
    "Na pračce: Posaď ji na zapnutou pračku, roztáhni jí nohy a lízej ji. Cíl: dvě minuty a nechat vibrace pracovat za tebe.|120|oral_vsede",
    "Obráceně nad tebou: Nech ji sednout si ti na obličej čelem k tvým nohám a lízej ji, zatímco se předkloní a hladí tě. Cíl: dvě minuty bez přerušení.|120|oral_ona_nad_nim",
    "Deset a deset: Střídej deset vteřin rychlého kmitání jazykem a deset vteřin pomalých polibků stydkých pysků. Cíl: šest kol a čas nesplést.|120|oral_klek",
    "Jako polibek na ústa: Líbej jí klín přesně tak, jako bys ji líbal na ústa – pomalu, s jazykem. Cíl: půldruhé minuty a nezrychlit.|90|oral_klek",
    "Jazyk a obě ruce: Lízej ji a oběma rukama jí přitom mačkej prsa. Cíl: dvě minuty a nepustit je ani jednou.|120|oral_klek",
    "Nech ji ležet na posteli, klekni si nad ni obráceně a lízej ji, zatímco ona hladí rukou tebe.|120",
    "Vibrace uvnitř: Zasuň do ní kousek vibrátor na nejnižším stupni a přitom ji lízej. Cíl: dvě minuty a stupeň nezvyšovat.|120|oral_klek",
    "Až si řekne: Olizuj jí jen okolí klitorisu. Cíl: nedotknout se ho, dokud si o to sama nahlas neřekne.|180|oral_klek",
    "Sedni si na podlahu u gauče, ona si stoupne nad tebe a jednu nohu opře o gauč. Lízej ji zespodu.|90",
    "Třikrát na hraně: Lízej ji a pokaždé, když se blíží vrchol, přestaň a polib ji na stehno. Cíl: třikrát ji zastavit a počtvrté ji nechat dojít.|240|oral_klek",
    "Foukat a olíznout: Foukni jí jemně na klitoris, olízni ho a znovu foukni. Cíl: deset takových trojic a ani jednu nezrychlit.|60|oral_klek",
    "Sleduje to v zrcadle: Klekni si mezi její nohy a lízej ji, zatímco se dívá do zrcadla. Cíl: nepřestat, dokud sama nezavře oči.|120|oral_vsede",
    "Až do konce: Lízej ji tak dlouho, dokud nedojde. Cíl: po orgasmu ji ještě jednou úplně jemně olíznout.|300|oral_klek",
    "Jazyk hluboko: Pronikni do ní jazykem tak hluboko, jak to jde, a pomalu s ním pohybuj. Cíl: dvacet pohybů a ani jednou nevyjet.|60|oral_klek",
    "Nech ji ležet na kuchyňském stole na zádech a lízej ji.|120",
    "Vezmi pírko a střídej ho s jazykem – pírko, jazyk, pírko, jazyk.|90",
    "Nech ji stát předkloněnou u linky a zezadu ji lízej, rukama jí roztahuj hýždě.|90",
    "Od prstů ke klínu: Olizuj jí prsty na nohou a pomalu stoupej jazykem po celé noze nahoru. Cíl: cesta musí trvat aspoň dvě minuty.|180",
    "Lízej ji a přitom jí vibrátorem masíruj hráz.|90",
    "Nech ji, ať tě drží za vlasy a sama si tě navádí, kam potřebuje.|120",
    "Pomalu jí saj stydké pysky, každý zvlášť, a pak klitoris.|90",
    "Lízej ji naplocho položeným jazykem a širokými tahy, jako bys lízal zmrzlinu.|90",
    "Zavaž jí oči a ruce jí dej za hlavu. Lízej ji a ona se nesmí pohnout.|120",
    "Lehni si na záda na koberec v obýváku a nech ji, ať si klekne nad tvůj obličej.|120",
    "Kalhotky zuby dolů: Líbej ji na klín přes kalhotky a přitom jí je pomalu stahuj zuby. Cíl: dostat je ke kotníkům bez použití rukou.|120|oral_klek",
    "69 s ní nahoře: Lehni si na záda a nech ji nad sebe hlavou k tvým nohám. Ližte se navzájem. Cíl: kdo dřív přestane, plní ještě jeden úkol navíc.|180|p69",
    "Kresli jí jazykem na klitoris kolečka po směru hodinových ručiček, pak proti. Zeptej se, co je lepší, a u toho zůstaň.|90",
    "Nech ji sedět na okraji vany a lízej ji, zatímco jí stéká teplá voda po zádech.|90",
    "Lízej jí bradavky tak dlouho, dokud nebudou tvrdé, pak sjeď jazykem po břiše až dolů.",
    "Lízej ji a zároveň jí prstem jemně hlaď kolem zadečku (s lubrikantem, bez vnikání).|90",
    "Posaď ji do křesla s nohama přes opěrky a lízej ji v klidu jako na hostině.|180",
    "Jemně sevři její klitoris rty a pomalu ho nasávej, jako bys cucal bonbon.|60",
    "Nech ji ležet na boku, zvedni jí horní nohu a lízej ji zezadu.|90",
    "Lízej ji a nech ji, ať ti přitom říká, co přesně máš dělat.|120",
    "Přilož jí vibrátor na klitoris a jazykem ji lízej u vstupu.|90",
    "Přitiskni ústa na její klín a hlasitě bzuč – hlasivky budou vibrovat.|30",
    "Líbej ji po celém těle a každé kolo zakonči mezi jejíma nohama. Pětkrát.",
    "Lízej ji, zatímco ona leží na gauči s hlavou na polštáři a sleduje tě.|120",
    "Přejížděj jí jazykem od klitorisu až dozadu a zase zpátky.|60",
    "Nech ji klečet na posteli s hlavou v polštáři a lízej ji zezadu, zatímco ji hladíš po zádech.|120",
    "Lízej ji a přitom jí jemně stiskni bradavku pokaždé, když olízneš klitoris.|90",
    "Posaď se na zem opřený o gauč, ona si sedne na opěradlo gauče nad tebou a ty ji lízej.|90",
    "Lízej jí klitoris a dvěma prsty v ní dělej malá kolečka.|120",
    "Studený jazyk: Podrž si kostku ledu v puse, vyplivni ji a hned ji studeným jazykem olízni. Cíl: třikrát po sobě a pokaždé počkat, až se zahřeješ.|120|oral_klek",
    "Nech ji, ať si sama roztáhne stydké pysky prsty, a ty ji lízej přesně tam, kde ukáže.|90",
    "Lízej ji ve stoje: ona stojí opřená o dveře ložnice, ty klečíš.|90",
    "Lízej ji a mezitím jí druhým vibrátorem hlaď bradavky.|120",
    "Lízej ji tak, jak by sis přál, aby lízala ona tebe – vášnivě a bez spěchu.|120",
    "Líbej ji na rty a pak hned na klín. Střídej to, ať cítí svou chuť.|90",
    "Nech ji ležet na zádech na posteli, zvedni jí nohy nahoru a lízej ji.|120",
    "Lehni si na gauč s hlavou na sedáku a nech ji, ať si nad tebou klekne a opře se rukama o opěradlo.|120",
    "Lízej ji a přitom se jí dívej do očí, i když ona zavře svoje.|90",
    "Lízej ji a pomalu do ní přitom vsouvej a vytahuj vibrátor.|120",
    "Zastavit a foukat: Olizuj jí vnitřní stranu stehen zdola nahoru a těsně u klína se pokaždé zastav a foukni. Cíl: deset cest, ani jedna dál.|120|oral_klek",
    "Lízej ji a vždy po 20 vteřinách jí polib bradavku. Opakuj.|120",
    "Nech ji, ať si lehne na jídelní stůl, a sedni si na židli mezi její nohy jako k večeři.|180",
    "Lízej ji a nech ji, ať ti za vlasy přitahuje hlavu blíž, kdykoli chce.|120",
    "Kmitej jí jazykem rychle nahoru a dolů přímo po klitorisu.|60",
    "Nech ji stát ve sprše s jednou nohou na okraji vany a lízej ji.|90",
    "69 vleže na gauči. Ty dole, ona nahoře. Obě ruce jí dej na zadeček.|180",
    "Lízej ji a zároveň jí vibrátorem hlaď podbřišek těsně nad klitorisem.|90",
    "Rty jí sevři klitoris a pomalu, rytmicky saj – jako tep.|60",
    "Ruce za zády: Lízej ji a ruce drž celou dobu za zády. Cíl: dvě minuty a ani jednou si nepomoct rukama.|120|oral_klek",
    "Nech ji ležet s roztaženýma nohama a lízej ji jen samotnou špičkou jazyka.|90",
    "Kousnout a olíznout: Kousni ji jemně do vnitřní strany stehna a hned ji olízni přímo na klitorisu. Cíl: pět takových dvojic po sobě.|120|oral_klek",
    "Lízej ji a mluv na ni – mezi olíznutími jí říkej, jak skvěle chutná.|90",
    "Lehni si na postel a nech ji, ať si ti sedne na obličej a drží se čela postele.|180",
    "Lízej ji a dvěma prsty jí jemně roztahuj stydké pysky, ať máš přístup ke všemu.|90",
    "Kapka s příchutí: Kápni jí na klitoris lubrikant s příchutí a olízni ji dočista. Cíl: nepřestat, dokud po ní nezbude ani stopa.|120|oral_klek",
    "Klekni si mezi její nohy na podlaze v obýváku, ona leží na gauči. Lízej ji, dokud nebude křičet.",
    "Lízej ji, zatímco ona sama drží vibrátor na svých bradavkách.|120",
    "Lízej ji ve vaně nebo pod sprchou, zatímco jí proud vody stéká po břiše.|90",
    "Nech ji ležet na zádech, ať si dá ruce na prsa, a lízej ji. Tvoje ruce drží její nohy roztažené.|120",
    "Líbej ji, lízej ji, saj ji – každou minutu změň techniku.|180",
    "Zeptej se jí, jak se jí to líbí nejvíc, a přesně tak ji lízej.|120",
    "Lízej ji zezadu, zatímco klečí na gauči a hladí se sama po prsou.|90",
    "Lízej ji, a jakmile její orgasmus odezní, pokračuj velmi jemně, dokud tě neodstrčí.",
    "Pomalu jí přejížděj jazykem po bradavkách a sjížděj níž – s každým dalším kolečkem o kousek.|90",
    "Vibrátorem jí dráždi klitoris a jazykem vstup – pak to prohoď: jazyk nahoře, vibrátor dole.|120",
    "Vsuň do ní palec a jazykem jí lízej klitoris.|90",
    "Nech ji sedět na kuchyňském stole, polib ji na klín a pak se dlouho věnuj jen bradavkám. Pak zpátky dolů.|120",
    "Lízej ji a přitom ji jemně plácej po stehně do rytmu olíznutí.|60",
    "Nech ji ležet na posteli a lízej ji, zatímco ona drží tvůj obličej oběma rukama.|120",
    "Lehni si na postel a nech ji, ať si na tvůj obličej sedne zády k tvým nohám a opře se rukama o tvůj hrudník.|120",
    "Lízej jí stydké pysky, ale klitorisu se vyhni, dokud tě o to dvakrát nepoprosí.",
    "Olízni ji jednou pořádně zespodu až nahoru a hned ji polib na rty.",
    "Líbej a saj jí bradavky, zatímco ji palcem pomalu hladíš po klitorisu.|90",
    "Lízej ji a přitom se jí prsty druhé ruky dotýkej rtů – ať je olizuje.|90",
    "Postav ji k oknu se zataženými závěsy, ať se opírá o parapet, klekni si a lízej ji.|90",
    "Lízej ji a zpívej jí do klína – jakoukoli písničku, hlavně ať to vibruje.|30",
    "Lízej ji tak dlouho, dokud nebude mít orgasmus. Bez časového limitu, bez přestávky.",
    "Nech ji ležet na břiše s polštářem pod boky a lízej ji zezadu.|120",

    // Karty s cílem
    "Abeceda jazykem: Lízej jí klitoris a jazykem piš písmena od A do Z. Ona řekne „stop“ u písmene, které je nejlepší. Cíl: to písmeno opakovat, dokud nedojde.",
    "Trůn: Lehni si na záda na postel. Ona si klekne nad tvůj obličej a chytí se čela postele, ty ji držíš za boky a lížeš. Cíl: ona řídí tlak tím, jak nízko si sedne – ty jen posloucháš její tělo.|180",
    "Na hraně gauče: Ona leží na zádech na gauči se zadečkem na samém kraji a nohama na tvých ramenou. Klekni si na zem a lízej ji. Cíl: tři minuty bez přestávky delší než pět vteřin.|180",
    "Tři zóny: Lízej ji střídavě na třech místech – klitoris, stydké pysky, vstup – každé 20 vteřin. Cíl: po třech kolech zůstat na zóně, kde nejvíc vzdychala.|180",
    "Pravidlo ticha: Ona nesmí vydat ani hlásku, zatímco ji lížeš. Za každý vzdech jí přidáš 10 vteřin. Cíl: aby to nevydržela.|120",
    "Jazyk jako vibrátor: Přitiskni jazyk naplocho na klitoris a rychle s ním kmitej ze strany na stranu, pak přejdi na široké pomalé tahy. Cíl: střídat po 15 vteřinách, dokud ti nepřitiskne hlavu.|120",
    "Večeře na stole: Ona leží na zádech na kuchyňském stole s nohama od sebe. Ty sedíš na židli mezi jejíma nohama a pomalu ji lížeš. Cíl: nevstat, dokud nedojde.",
    "Nasát a pustit: Jemně nasaj klitoris rty, drž 3 vteřiny a pusť. Mezi jednotlivými nasátími ji olízni. Cíl: patnáct opakování, pak zrychli rytmus.|90",
    "Jazyk a bod G: Jazykem lízej klitoris a dva prsty v ní ohni k přední stěně. Cíl: každé olíznutí sladit s jedním zatlačením prstů.|180",
    "Vibrátor dole, jazyk nahoře: Zasuň do ní vibrátor na střední stupeň a jazykem se věnuj jen klitorisu. Cíl: dovést ji k orgasmu do pěti minut.|300",
    "Ve sprše na kolenou: Ona stojí ve sprše s jednou nohou na okraji vany a opírá se o stěnu. Klekni si na ručník, ruce jí dej na zadeček a lízej ji. Cíl: podržet ji, až se jí podlomí kolena.|120",
    "69 na boku: Oba ležíte na boku hlavou k nohám toho druhého, její horní noha je opřená o tvé rameno. Lízej ji. Cíl: být tak dobrý, že ona musí přestat.|180",
    "Křeslo s opěrkami: Ona sedí v křesle s nohama přes opěrky. Klekni si, lízej ji a rukama jí přitom hlaď prsa. Cíl: aby tě chytila za vlasy.|180",
    "Tři minuty trpělivosti: První minutu smíš lízat jen třísla a vnitřní strany stehen, druhou stydké pysky, třetí klitoris. Cíl: dodržet pořadí, i když bude prosit.|180",
    "Hodnocení: Lízej ji a po každé změně techniky tě ohodnotí od 1 do 10. Cíl: najít desítku a zůstat u ní.|180",
    "Zezadu na gauči: Ona klečí na gauči opřená o opěradlo a prohne se. Klekni si za ni na zem a lízej ji zezadu dlouhými tahy. Cíl: aby se ti zadečkem natlačila na obličej.|120",
    "Pět technik poslepu: Zavaž jí oči a každých 20 vteřin změň: jazyk, rty, prst, dech, vibrátor. Cíl: aby nedokázala uhádnout, co přijde.|120",
    "Jen pusa: Ruce máš za zády a ona si sama drží nohy roztažené. Cíl: dovést ji k orgasmu jen pusou.",
    "Druhá vlna: Po jejím orgasmu ji 20 vteřin jen líbej na stehna. Pak ji začni velmi jemně lízat znovu. Cíl: druhý orgasmus.",
    "Šlehačková stezka: Nakresli jí šlehačkou čáru od bradavky přes břicho až k podbřišku. Olízni ji celou a na konci pokračuj jazykem níž. Cíl: nezvednout jazyk z její kůže.",
    "Na koberci: Ona leží na koberci s polštářem pod boky. Lehni si na břicho mezi její nohy, drž jí stehna od sebe a lízej ji. Cíl: pět minut bez přestávky.|300",
    "Obrácený trůn: Lehni si na záda, ona si na tvůj obličej sedne čelem k tvým nohám a předkloní se. Cíl: lízat ji tak, aby se musela opřít rukama o tvá stehna.|180",
    "U zdi s nohou na rameni: Ona stojí u zdi, ty klečíš a její nohu máš přes rameno. Lízej ji a prsty jí přitom jemně rozevírej stydké pysky. Cíl: aby se o zeď opírala čím dál víc.|120",
    "Bzučák: Přitiskni rty na klitoris a bzuč nízkým tónem, pak zase lízej. Cíl: najít tón, při kterém sebou cukne.|60",
    "Teplý a studený jazyk: Lízej ji a jednou za 30 vteřin si dej na 2 vteřiny do pusy kostku ledu. Cíl: střídat teplý a studený jazyk, dokud nezačne sténat nahlas.|150",
    "Na pračce: Ona sedí na pračce s roztaženýma nohama a opírá se o zeď. Ty stojíš předkloněný a lížeš ji. Cíl: nechat ji dojít přímo na pračce.",
    "Pírko jako předkrm: Nejdřív ji minutu šimrej pírkem po klitorisu, pak plynule přejdi na jazyk. Cíl: aby nepoznala, kdy pírko skončilo a začal jazyk.|120",
    "Do rytmu písničky: Pusť písničku a lízej ji přesně do rytmu. Cíl: v refrénu zrychlit.|180",
    "Pět a polibek: Po každých pěti olíznutích ji vášnivě polib na rty. Cíl: deset kol.",
    "Trojitá stimulace: Jeden vibrátor na jejích bradavkách, druhý v ní, tvůj jazyk na klitorisu. Ona drží vibrátor na bradavkách, ty zbytek. Cíl: dokud nedojde.",
    "Bradavky a klín: Střídej: 30 vteřin saj jednu bradavku, 30 vteřin lízej klitoris, 30 vteřin druhou bradavku. Cíl: tři kola, pak zůstaň dole.|270",
    "Jazykem dozadu: Ona klečí na posteli. Olizuj jí stydké pysky, pak jazykem jemně přejeď výš až k zadečku a zpátky. Cíl: zjistit, jestli se jí to líbí – a pokud ano, zůstat tam déle.|90",
    "Kraj židle: Ona sedí na kraji židle s nohama na tvých ramenou, ty klečíš. Cíl: lízat ji tak dlouho, až sklouzne ze židle přímo k tobě.",
    "Přes kalhotky a pak bez: Lízej ji minutu přes kalhotky, pak je odhrň a minutu napřímo. Cíl: zeptat se, co chce dál, a udělat to.|120",
    "Zvednuté boky: Ona leží na zádech, ty klečíš. Chyť ji pod zadečkem a zvedni jí boky ke svým ústům, její nohy máš přes ramena. Cíl: udržet ji takhle, dokud nevzdychne tvoje jméno.|120",
    "Pětivteřinová olíznutí: Každé olíznutí od vstupu ke klitorisu trvá 5 vteřin. Cíl: dvacet olíznutí, žádné rychlejší.|120",
    "Deset druhů polibků: Polib její klín deseti různými způsoby – krátce, dlouze, s jazykem, se sáním, jemně, pevně… Cíl: nechat ji vybrat nejlepší a ten opakovat.",
    "Jazyk dovnitř, palec nahoru: Ztvrď jazyk a pronikej jím do ní, zatímco jí palcem hladíš klitoris. Cíl: jazyk i palec ve stejném rytmu.|90",
    "Sevření hlavy: Ona leží na zádech a sevře ti hlavu stehny. Lízej ji dál. Cíl: čím víc svírá, tím pomaleji jdeš – ať se naučí povolit a užít si to.|120",
    "Přesná práce: Ať si sama prsty roztáhne stydké pysky. Ty lízej klitoris jen špičkou jazyka. Cíl: dvě minuty přesné práce.|120",
    "Na okraji vany: Ona sedí na okraji vany, ty klečíš na ručníku a sprcha jí teče po prsou. Cíl: lízat ji, dokud se nebude muset chytit tvých ramen.|120",
    "Výměna: 30 vteřin jí palcem hladíš klitoris a jazykem pronikáš dovnitř, pak prohoď – jazyk nahoře, palec uvnitř. Cíl: čtyři výměny.|120",
    "Hlasové ovládání: Lízej ji a ona smí říkat jen „víc“, „míň“, „nahoru“ a „dolů“. Cíl: řídit se jen jejími slovy, dokud nedojde.",
    "Svázané ruce: Nech ji, ať ti šátkem sváže ruce za zády. Pak ji lízej. Cíl: dovést ji k orgasmu bez rukou.",
    "Škádlivé přiblížení: Přibliž pusu k jejímu klínu a jen dýchej. Počkej, až sama zvedne boky – pak jedno olíznutí a zase se odtáhni. Cíl: pět kol.|90",
    "Ze tří stran: Lízej ji zepředu, pak zboku, když leží na boku, a nakonec zezadu, když leží na břiše. Cíl: minutu z každé strany.|180",
    "Broskev: Polož jí na podbřišek těsně nad klín plátek broskve nebo jahodu, sněz ho a pak pokračuj jazykem až dolů. Cíl: nenechat ani kapku.",
    "Líbání dole: Líbej její stydké pysky, jako bys ji líbal na ústa – s jazykem a nasáváním. Cíl: minuta vášnivého líbání.|60",
    "Stehno na závěr: Po lízání se přesuň nahoru, polib ji a přitiskni jí stehno na mokrý klín. Cíl: nechat ji o něj dojít, zatímco jí saješ bradavky.",
    "Žabka: Ona leží na zádech a drží si kolena přitažená k prsům. Lízej ji dlouhými tahy od hráze až ke klitorisu. Cíl: aby pustila kolena, protože se nedokáže soustředit.|120",
    "Pod peřinou: Vklouzni pod peřinu, zatímco ona leží, a začni ji lízat bez varování. Cíl: aby se odkryla sama, protože jí bude horko.",
    "Tři pokusy: Lízej ji těsně k orgasmu, pak přestaň a polib ji na břicho. Pak znovu. Cíl: napotřetí ji nech dojít.",
    "Opřená o stůl: Ona se zadečkem opírá o kraj jídelního stolu a jednu nohu má na židli. Klekni si a lízej ji. Cíl: aby si na stůl musela sednout.|120",
    "Vibrátor na bradě: Přitiskni si vibrátor k bradě a lízej ji – vibrace půjdou přes tvou pusu. Cíl: najít tlak, který ji rozechvěje.|90",
    "Slova do klína: Mezi olíznutími jí šeptej, jak chutná a co s ní budeš dělat v další úrovni. Cíl: aby tě poprosila, ať mlčíš a lížeš.|120",
    "Maraton: Lízej ji sedm minut bez přestávky a techniky střídej jen podle jejích reakcí. Cíl: nejméně jeden orgasmus.|420",
  ],

  // Úkoly pro ženu – pro potěšení muže
  female: [
    "Od kořene ke špičce: Klekni si před něj, stáhni mu kalhoty a pomalu ho olizuj od kořene až ke špičce. Cíl: dvacet cest a žádná rychlejší.|120|oral_on_vsede",
    "Jen hladit vlasy: Klekni si mu mezi nohy a kouři mu. On tě smí jen hladit po vlasech, nic víc. Cíl: tři minuty a ruce mu neposunout níž.|180|oral_on_vsede",
    "Jazyk dole, ruka nahoře: Olizuj mu varlata a přitom ho rukou hlaď po penisu. Cíl: půldruhé minuty a ani jednou se neprohodit.|90|oral_on_vleze",
    "Ústa a vibrace: Kouři mu a zároveň mu vibrátorem masíruj hráz mezi varlaty a konečníkem. Cíl: dvě minuty a obojí ve stejném rytmu.|120|oral_on_vleze",
    "Sten mění rytmus: Zavaž mu oči a kouři mu. Pokaždé, když zasténá, změň rytmus. Cíl: deset změn a ani jednu nezmeškat.|120|oral_on_vleze",
    "Jen špička: Vezmi do pusy jen špičku a jazykem kolem ní kresli kolečka. Cíl: třicet koleček a hlouběji nezajet.|60|oral_on_vleze",
    "Opřený o zeď: Nech ho opřít se o zeď, klekni si před něj a kouři mu. Cíl: dvě minuty a nenechat ho sklouznout dolů.|120|oral_ona_klek",
    "Čím víc pobízí, tím pomaleji jemu: Kouři mu tak pomalu, jak jen dokážeš. Cíl: pokaždé, když tě chce popohnat, zpomalit ještě víc.|120|oral_on_vleze",
    "Nejdřív přes boxerky: Olizuj ho přes boxerky tak dlouho, dokud nebudou mokré. Cíl: teprve pak mu je stáhnout a pokračovat.|90|oral_on_vleze",
    "69 na boku pro něj: Ležte oba na boku hlavou k nohám toho druhého a ližte se navzájem. Cíl: tři minuty a soustředit se hlavně na něj.|180|p69_bok",
    "Drží se sedáku: Posaď ho na židli, klekni si mu mezi nohy a kouři mu, zatímco se drží sedáku. Cíl: dvě minuty a nesmí se pustit.|120|oral_on_vsede",
    "Napotřetí do pusy: Líbej ho po vnitřní straně stehen až k varlatům, pak zpátky a znovu. Cíl: teprve při třetí cestě ho vzít do pusy.|120|oral_on_vleze",
    "Sprcha na vás: Klekni si před něj ve sprše a kouři mu pod tekoucí vodou. Cíl: půldruhé minuty a nepřerušit to kvůli vodě.|90|oral_ona_klek",
    "Jen jazyk, žádné rty: Nech ho ležet na zádech a olizuj ho výhradně jazykem, rty nepoužiješ. Cíl: půldruhé minuty a do pusy ho nevzít.|90|oral_on_vleze",
    "Dočista jazykem: Kápni mu na penis šlehačku, med nebo čokoládu. Cíl: olízat ho úplně dočista a nepoužít k tomu ruce.|120|oral_on_vleze",
    "Ústa a obě ruce: Kouři mu a oběma rukama mu přitom hlaď bradavky. Cíl: dvě minuty a ruce ani jednou nesundat.|120|oral_on_vleze",
    "Oči do očí: Posaď ho na okraj postele, klekni si a kouři mu, zatímco se na sebe díváte. Cíl: dvě minuty a neuhnout pohledem.|120|oral_on_vsede",
    "Hýbe se jen on: Vezmi ho do pusy a vůbec se nehýbej. Cíl: celá minuta, při které všechnu práci dělá on – pomalu a opatrně.|60|oral_on_vleze",
    "Ruka rychle, pusa pomalu: Střídej deset vteřin rychlé ruky a deset vteřin pomalých úst. Cíl: šest kol a čas ani jednou nesplést.|120|oral_on_vleze",
    "Hlava přes okraj: Lehni si na záda s hlavou přes okraj postele, on stojí. Tempo řídíš rukama na jeho bocích. Cíl: dvě minuty a nepustit je.|120|oral_okraj",
    "Ústa a dlaň: Kouři mu a přitom mu druhou rukou jemně masíruj varlata. Cíl: dvě minuty a ani jedno nepřerušit.|120|oral_on_vleze",
    "Opřený o pračku: Nech ho opřít se o zapnutou pračku, klekni si a kouři mu. Cíl: půldruhé minuty a nechat vibrace pracovat za tebe.|90|oral_on_vsede",
    "Jen uzdička: Lízej mu jen uzdičku pod špičkou rychlými krátkými tahy. Cíl: celá minuta a nikam jinam nesjet.|60|oral_on_vleze",
    "Jedno a pak druhé: Vezmi jedno varle do pusy a jemně ho saj, pak to samé s druhým. Cíl: půl minuty na každé straně.|60|oral_on_vleze",
    "Oba naráz: Kouři mu a mezitím si sama přikládej vibrátor mezi nohy. Cíl: dvě minuty a nepřestat ani u jednoho.|120|oral_on_vleze",
    "Hluboko a zpátky: Vezmi ho do pusy tak hluboko, jak je ti příjemné, a pomalu vyjeď až ke špičce. Cíl: patnáct cest a žádná rychlejší.|90|oral_on_vleze",
    "Jako zmrzlinu: Lehni si mu mezi nohy a olizuj ho dlouhými tahy, jako bys lízala zmrzlinu. Cíl: třicet tahů a do pusy ho nevzít.|90|oral_on_vleze",
    "Třikrát ho zastavit: Kouři mu a pokaždé, když se blíží vrchol, přestaň a polib ho na stehno. Cíl: třikrát ho zastavit a počtvrté ho nechat dojít.|240|oral_on_vleze",
    "Foukat a olíznout jemu: Foukni mu jemně na špičku, olízni ji a znovu foukni. Cíl: deset takových trojic a ani jednu nezrychlit.|60|oral_on_vleze",
    "Dva pohledy naráz: Klekni si před něj u zrcadla a kouři mu tak, aby se mohl dívat přímo i do odrazu. Cíl: nepřestat, dokud sám nezavře oči.|120|oral_ona_klek",
    "Až do konce jemu: Domluvte se předem, kam se udělá, a pak mu kuř. Cíl: nepřestat, dokud se neudělá.|300|oral_on_vleze",
    "69 s tebou nahoře: Klekni si nad něj hlavou k jeho nohám a ližte se navzájem. Cíl: kdo dřív přestane, plní ještě jeden úkol navíc.|180|p69",
    "Pírko a jazyk: Přejeď mu pírkem po penisu a hned po stejné dráze jazykem. Cíl: deset takových dvojic a dráhu ani jednou nezměnit.|90|oral_on_vleze",
    "Hráz jazykem: Olizuj mu hráz mezi varlaty a konečníkem a přitom ho rukou hlaď po penisu. Cíl: půldruhé minuty a ruku nezastavit.|90|oral_on_vleze",
    "Vibrace na varlatech: Kouři mu a přitom mu drž vibrátor přiložený na varlatech. Cíl: dvě minuty a stupeň postupně zvyšovat.|120|oral_on_vleze",
    "Vede tě za vlasy: Nech ho, ať ti drží vlasy v culíku a jemně určuje tempo. Cíl: dvě minuty a ani jednou si neurčit tempo sama.|120|oral_on_vleze",
    "Ze všech stran: Pomalu mu olizuj celou délku nahoře, dole i po obou bocích. Cíl: pět kol dokola a žádnou stranu nevynechat.|90|oral_on_vleze",
    "Ruce za hlavou: Zavaž mu oči, dej mu ruce za hlavu a kuř mu. Cíl: dvě minuty a on se nesmí ani pohnout.|120|oral_on_vleze",
    "Klečí nad tebou: Lehni si na záda a nech ho kleknout si nad tebe. Tempo vedeš rukama na jeho bocích. Cíl: dvě minuty a nepustit je.|120|oral_ona_vleze",
    "Boxerky zuby dolů: Líbej ho přes boxerky a přitom mu je pomalu stahuj zuby. Cíl: dostat je ke kotníkům bez použití rukou.|120|oral_on_vleze",
    "Po směru a proti: Kresli mu jazykem kolečka kolem špičky po směru hodin, pak proti. Cíl: zeptat se, co je lepší, a u toho zůstat celou minutu.|90|oral_on_vleze",
    "Na okraji vany: Nech ho sedět na okraji vany a kuř mu, zatímco na vás teče sprcha. Cíl: půldruhé minuty a nenechat ho sklouznout.|90|oral_on_vsede",
    "Dokud tě neposune: Olizuj mu bradavky tak dlouho, dokud sám nezačne tlačit tvou hlavu níž. Cíl: teprve pak sjet jazykem až dolů.|120|oral_on_vleze",
    "Kouři mu a přitom mu prstem s lubrikantem jemně hlaď kolem zadku (bez vnikání).|90",
    "Posaď ho do křesla s nohama od sebe a kouři mu v klidu, jako byste měli neomezeně času.|180",
    "Kouři mu a přitom mu rukou zakruť kolem kořene při každém pohybu dolů.|90",
    "Lízej ho a nech ho, ať ti přitom říká, co přesně chce.|120",
    "Přilož mu vibrátor na špičku penisu a jazykem mu olizuj varlata.|90",
    "Vezmi ho do pusy a bzuč – hlasivky budou vibrovat.|30",
    "Líbej ho po celém těle a každé kolo zakonči na jeho penisu. Pětkrát.",
    "Kouři mu, zatímco on leží na gauči s hlavou na polštáři a sleduje tě.|120",
    "Nech ho klečet na posteli, lehni si pod něj na záda hlavou mezi jeho nohy a olizuj mu varlata.|90",
    "Kouři mu a přitom mu jemně stiskni bradavku pokaždé, když vyjedeš až ke špičce.|90",
    "Nech ho stát u linky, klekni si a pomalu mu olizuj penis, zatímco se drží linky oběma rukama.|120",
    "Studená pusa: Podrž si kostku ledu v puse, vyplivni ji a hned ho vezmi do studených úst. Cíl: třikrát po sobě a pokaždé počkat, až se zahřeješ.|120|oral_on_vleze",
    "Nech ho, ať si sám drží penis a vede ho po tvých rtech a jazyku.|60",
    "Klekni si před něj, když stojí u dveří ložnice, a kouři mu.|90",
    "Kouři mu a přitom mu druhým vibrátorem masíruj bradavky.|120",
    "Kouři mu tak, jak by sis přála, aby lízal on tebe – vášnivě a bez spěchu.|120",
    "Olízni ho a hned ho polib na rty. Střídej to.|90",
    "Nech ho ležet na zádech se zvednutými koleny a olizuj mu varlata a hráz.|90",
    "Nespustit z něj oči: Kouři mu a celou dobu se mu dívej do očí. Cíl: půldruhé minuty a ani jednou neuhnout pohledem.|90|oral_on_vleze",
    "Zastavit u varlat: Olizuj mu vnitřní stranu stehen zdola nahoru a těsně u varlat se pokaždé zastav a foukni. Cíl: deset cest, ani jedna dál.|120|oral_on_vleze",
    "Kouři mu a vždy po 20 vteřinách ho polib na podbřišek. Opakuj.|120",
    "Jako k večeři: Posaď ho na stůl, sedni si před něj na židli mezi jeho nohy a nespěchej. Cíl: tři minuty a ani jednou se nezvednout.|180|oral_on_vsede",
    "Jazykem mu rychle přejížděj po špičce, pak ho pomalu vezmi celého do pusy.|60",
    "Nech ho stát ve sprše a klekni si před něj. Pod vodou mu pomalu olizuj varlata a penis.|90",
    "69 vleže na gauči. On dole, ty nahoře. Pomalu mu kouři a on tě hladí po zadečku.|180",
    "Ruce mimo hru: Kouři mu a ruce drž celou dobu za zády. Cíl: dvě minuty a ani jednou si nepomoct rukama.|120|oral_on_vleze",
    "Olizuj ho jen samotnou špičkou jazyka, sotva znatelně.|90",
    "Kousnutí a pusa: Kousni ho jemně do vnitřní strany stehna a hned ho vezmi do pusy. Cíl: pět takových dvojic po sobě.|120|oral_on_vleze",
    "Kouři mu a mezi pohyby mu říkej, jak moc se ti líbí.|90",
    "Lehni si na postel a nech ho, ať si klekne obkročmo nad tvou hrudí. Kouři mu, zatímco ti hladí vlasy.|120",
    "Kouři mu a rukou mu jemně stahuj kůži u kořene dolů, ať je citlivější.|90",
    "Kapka na špičce: Kápni mu na špičku lubrikant s příchutí nebo med a olízni ho dočista. Cíl: nepřestat, dokud po něm nezbude ani stopa.|120|oral_on_vleze",
    "Klekni si na podlahu v obýváku, on sedí na gauči. Kouři mu, dokud nebude sténat nahlas.",
    "Kouři mu, zatímco si on sám drží vibrátor na varlatech.|120",
    "Nech ho sedět na posteli opřeného o čelo a kouři mu. Jeho ruce si polož do vlasů.|120",
    "Líbej ho, olizuj, saj – každou minutu změň techniku.|180",
    "Zeptej se ho, jak se mu to líbí nejvíc, a přesně tak mu kouři.|120",
    "Nech ho klečet na gauči opřeného o opěradlo, vklouzni pod něj a olizuj ho zespodu.|90",
    "Kouři mu a jakmile se udělá, pokračuj velmi jemně, dokud tě neodtáhne.",
    "Olizuj mu bradavky a sjížděj níž – s každým kolečkem o kousek.|90",
    "Rukou ho hlaď u kořene a pusou saj jen špičku. Pak to prohoď: pusou níž, rukou nahoře.|120",
    "Kouři mu a přitom si prsty hlaď bradavky, ať se může dívat.|90",
    "Nech ho sedět na kuchyňské židli, polib ho na špičku a pak se dlouho věnuj jen varlatům. Pak zpátky nahoru.|120",
    "Kouři mu a přitom ho jemně plácej po stehně do rytmu.|60",
    "Nech ho, ať ti drží tvář oběma rukama, zatímco mu kouříš.|120",
    "Olizuj mu varlata, ale penisu se vyhni, dokud tě o to dvakrát nepoprosí.",
    "Olízni ho jednou pořádně od kořene až po špičku a hned ho polib na rty.",
    "Saj mu bradavky a přitom ho palcem hlaď po uzdičce.|90",
    "Kouři mu a prsty druhé ruky se mu dotýkej rtů – ať je olizuje.|90",
    "Opři ho o parapet okna se zataženými závěsy, klekni si a kouři mu.|90",
    "Vezmi ho do pusy a zpívej – jakoukoli písničku, hlavně ať to vibruje.|30",
    "Kouři mu tak dlouho, dokud se neudělá. Bez časového limitu.",
    "Nech ho ležet na břiše s polštářem pod boky, roztáhni mu nohy a olizuj mu varlata zezadu.|90",
    "Klekni si mezi jeho nohy, prsy mu sevři penis a špičku olizuj.|90",
    "Kouři mu na posteli, zatímco on leží a ty klečíš bokem – ať vidí tvůj zadeček a může tě hladit.|120",
    "Nech ho stát, klekni si a kouři mu bez pomoci rukou – ruce mu dej na zadek a přitahuj si ho.|90",
    "Kouři mu rychle a hluboko, pak úplně pomalu jen špičku. Střídej po 15 vteřinách.|120",
    "Klekni si nad něj do polohy 69 a olizuj ho, zatímco ti on hladí zadeček prsty. Lízat tě zatím nesmí.|120",
    "Vezmi oba vibrátory, jeden mu dej na varlata, druhý na hráz, a olizuj mu špičku.|90",
    "Nech ho stát nahého ve sprše a pomalu ho olizuj od kolen nahoru přes stehna až k penisu.|90",
    "Kouři mu a jeho ruku si přitom přitiskni mezi nohy.|120",
    "Líbej a olizuj mu třísla a podbřišek, ale penis jen hlaď rukou.|60",
    "Posaď se na zem v kuchyni zády ke skříňce, on stojí před tebou. Kouři mu, tempo určuješ rukama na jeho bocích.|120",
    "Kouři mu a vždy, když zasténá, na vteřinu přestaň a usměj se na něj.|90",
    "Vezmi mu varlata do dlaně a pomalu je masíruj, zatímco saješ špičku.|90",
    "Lehni si na posteli bokem k němu, hlavu si polož na jeho stehno a olizuj ho.|120",
    "Kouři mu v kombinaci s rukou namazanou lubrikantem – ruka i pusa se pohybují spolu.|120",
    "Olizuj ho a mezitím mu šeptej, co s ním budeš dělat v další úrovni.|60",
    "Klekni si nahá před gauč, na kterém sedí. Kouři mu a on se ti celou dobu musí dívat do očí.|120",

    // Karty s cílem
    "Abeceda na uzdičce: Olizuj mu uzdičku pod špičkou a jazykem piš písmena od A do Z. Ať řekne „stop“ u nejlepšího. Cíl: to písmeno opakovat, dokud nezasténá.",
    "Na polštáři u postele: On sedí na kraji postele, ty klečíš na polštáři mezi jeho nohama. Kouři mu a rukama mu drž stehna. Cíl: tři minuty, tempo se smí jen zvyšovat.|180",
    "Z boku: On leží na zádech, ty klečíš na posteli bokem k němu, kouříš mu a jednou rukou hladíš varlata. Cíl: sledovat jeho obličej a zrychlit, když zavře oči.|120",
    "Tři zóny pro něj: Střídej po 20 vteřinách – špička, celá délka, varlata. Cíl: po třech kolech zůstat u zóny, kde nejvíc sténal.|180",
    "Ticho: Nesmí vydat ani hlásku, zatímco mu kouříš. Za každý vzdech přidáš 10 vteřin pomalého tempa. Cíl: aby to nevydržel.|120",
    "Vír: Vezmi ho do pusy a jazykem mu kruž kolem špičky, zatímco rty jezdíš nahoru a dolů. Cíl: udržet krouživý jazyk minutu bez přerušení.|60",
    "Kuchyňská židle: On sedí na židli, ty klečíš. Kouři mu pomalu a rukama mu přitom rozepínej košili. Cíl: aby byl nahoře bez dřív, než přestaneš.",
    "Nasát a pustit: Nasaj mu špičku, drž 3 vteřiny a pusť. Mezitím mu olízni celou délku. Cíl: patnáct opakování, pak zrychli.|90",
    "Pusa a ruka jako jedno: Pusou saj špičku a rukou s lubrikantem jezdi po zbytku ve stejném rytmu. Cíl: aby to působilo jako jeden plynulý pohyb.|180",
    "Vibrující varlata: Přilož mu vibrátor na varlata a kouři mu. Cíl: dovést ho k orgasmu do pěti minut.|300",
    "Sprcha na kolenou: On stojí ve sprše opřený o stěnu. Klekni si na složený ručník, ruce mu dej na zadek a kouři mu. Cíl: aby se musel chytit stěny.|120",
    "69 na boku pro něj: Oba ležíte na boku hlavou k nohám toho druhého. Kouři mu. Cíl: být tak dobrá, že on musí přestat.|180",
    "Křeslo: On sedí v křesle s nohama od sebe, ty klečíš. Kouři mu a rukama mu hlaď hruď. Cíl: aby tě chytil za vlasy.|180",
    "Pomalá rozcvička: První minutu olizuj jen třísla a stehna, druhou varlata, třetí penis. Cíl: dodržet pořadí, i když bude prosit.|180",
    "Známkování: Po každé změně techniky ať tě ohodnotí od 1 do 10. Cíl: najít desítku a zůstat u ní.|180",
    "Zespodu: On klečí na gauči opřený o opěradlo. Lehni si na záda na sedák pod něj, hlavou mezi jeho koleny, a olizuj mu varlata a penis zespodu. Cíl: rukama na jeho bocích určovat, jak hluboko smí.|120",
    "Poslepu pět technik: Zavaž mu oči a každých 20 vteřin změň: jazyk, rty, ruka, dech, vibrátor. Cíl: aby nedokázal uhádnout, co přijde.|120",
    "Jen pusou: Ruce máš za zády. Cíl: dovést ho k orgasmu jen pusou.",
    "Dozvuk: Po jeho orgasmu ho jemně drž v puse a 20 vteřin se nehýbej. Pak ho pomalu pusť. Cíl: aby se celý roztřásl.",
    "Šlehačka až dolů: Nakresli mu šlehačkou čáru od bradavky přes břicho až ke špičce penisu. Olízni ji celou. Cíl: nezvednout jazyk z jeho kůže.",
    "Koberec: On leží na koberci s polštářem pod hlavou, ty ležíš na břiše mezi jeho nohama a kouříš mu. Cíl: pět minut s pohledem do očí, tempo se pomalu zvyšuje.|300",
    "Obráceně nad ním: Klekni si nad něj obráceně, kolena u jeho hlavy, a kouři mu. On tě smí hladit po zadečku, ale lízat ne. Cíl: aby tě prosil, že tě chce lízat.|180",
    "Chodba: On stojí opřený o zeď v chodbě, ty klečíš. Jednou rukou mu drž penis, druhou masíruj varlata a pusou saj špičku. Cíl: aby se mu roztřásla kolena.|120",
    "Bzučení: Vezmi mu špičku do pusy a bzuč nízkým tónem. Střídej to s pohyby. Cíl: najít tón, při kterém cukne.|60",
    "Led v puse: Kouři mu a jednou za 30 vteřin si na 2 vteřiny vezmi do pusy kostku ledu. Cíl: střídat teplou a studenou pusu, dokud nezačne nahlas sténat.|150",
    "Pračka: On sedí na pračce, stoupni si mezi jeho kolena a skloň se k němu. Cíl: aby se udělal dřív, než pračka dotočí.",
    "Pírko a pak pusa: Minutu ho šimrej pírkem po penisu a varlatech, pak ho plynule vezmi do pusy. Cíl: aby nepoznal, kdy pírko skončilo.|120",
    "Do rytmu hudby: Pusť písničku a kouři mu přesně do rytmu. Cíl: v refrénu zrychlit.|180",
    "Pět a polibek pro něj: Po každých pěti pohybech pusou ho vášnivě polib na rty. Cíl: deset kol.",
    "Tři místa najednou: Jeden vibrátor na varlatech, druhý na hrázi, tvoje pusa na špičce. On drží jeden vibrátor, ty zbytek. Cíl: dokud se neudělá.",
    "Bradavky a penis: 30 vteřin saj jeho bradavku, 30 vteřin kouři, 30 vteřin druhou bradavku. Cíl: tři kola, pak zůstaň dole.|270",
    "Jazykem až dozadu: On leží na zádech s pokrčenými koleny. Olizuj mu varlata, hráz a jazykem jemně až k zadku a zpátky. Cíl: zjistit, jestli se mu to líbí – a pokud ano, zůstat tam déle.|90",
    "Na kraji židle: On sedí na kraji židle, ty klečíš. Kouři mu tak, aby se musel pořád víc naklánět dopředu. Cíl: aby tě nakonec zvedl a posadil si tě na klín.",
    "Přes boxerky a pak bez: Minutu ho olizuj a saj přes boxerky, pak mu ho vytáhni a minutu napřímo. Cíl: zeptat se, co chce dál, a udělat to.|120",
    "Hluboko a zůstat: Vezmi ho do pusy tak hluboko, jak je ti příjemné, a zůstaň 3 vteřiny. Pak pomalu vyjeď. Cíl: deset opakování s pohledem do očí.|120",
    "Pětivteřinové pohyby: Kouři mu tak, že každý pohyb od kořene ke špičce trvá přesně pět vteřin. Cíl: dvacet pohybů a žádný rychlejší.|120|oral_on_vleze",
    "Deset polibků na penis: Polib mu penis deseti různými způsoby – krátce, dlouze, s jazykem, se sáním, jemně, pevně… Cíl: ať vybere nejlepší a ten opakuj.",
    "Dva rytmy: Špičkou jazyka rychle kmitej na uzdičce a rukou pomalu jezdi u kořene. Cíl: rozdílný rytmus 90 vteřin.|90",
    "Pohodlná vytrvalost: Lehni si na bok tak, abys měla hlavu na jeho stehně a penis u pusy. Cíl: kouřit mu pět minut v klidu a vytrvale.|300",
    "Nabízený: Ať si drží penis u kořene a nabízí ti ho. Ty olizuj jen špičku. Cíl: dvě minuty přesné práce.|120",
    "Ve vaně: On sedí na okraji vany, ty klečíš ve vaně na ručníku a sprcha mu teče po hrudi. Cíl: kouřit mu, dokud se neudělá.|120",
    "Výměna pusy a ruky: 30 vteřin pusa na špičce a ruka na varlatech, pak ruka na penisu a pusa na varlatech. Cíl: čtyři výměny.|120",
    "Jeho povely: Kouři mu a on smí říkat jen „víc“, „míň“, „hlouběji“ a „pomaleji“. Cíl: řídit se jen jeho slovy, dokud se neudělá.",
    "Svázané ruce pro něj: Nech ho, ať ti šátkem sváže ruce za zády. Pak mu kouři. Cíl: dovést ho k orgasmu bez rukou.",
    "Dech bez dotyku: Přibliž pusu k jeho penisu a jen dýchej. Počkej, až se k tobě sám natáhne – pak jedno olíznutí a zase pryč. Cíl: pět kol.|90",
    "Obchůzka: Kouři mu postupně ze tří poloh – mezi jeho nohama, z boku a obráceně nad ním. Cíl: minutu z každé strany.|180",
    "Čokoládová špička: Potři mu špičku vlažnou rozpuštěnou čokoládou nebo medem a olízni ho dočista. Cíl: nenechat ani kapku.",
    "Líbání dole: Líbej mu špičku jako rty – s jazykem a nasáváním. Cíl: minuta vášnivého líbání.|60",
    "Konec mezi prsy: Když se blíží vrchol, vyndej ho z pusy, sevři ho mezi prsy a dokonči to tam. Cíl: předem se domluvit, kde se udělá.",
    "Kolena k hrudi: On leží na zádech s koleny přitaženými k hrudi. Olizuj mu varlata a hráz dlouhými tahy a rukou ho hlaď. Cíl: aby pustil kolena, protože se nedokáže soustředit.|120",
    "Pod peřinou pro něj: Vklouzni pod peřinu, zatímco leží, a začni mu kouřit bez varování. Cíl: aby se odkryl sám, protože mu bude horko.",
    "Napotřetí: Kouři mu těsně k orgasmu, pak přestaň a polib ho na břicho. Znovu. Cíl: napotřetí ho nech dojít.",
    "Ruce na stole: On se opírá zadkem o kraj jídelního stolu a ruce má na stole. Klekni si a kouři mu. Cíl: nesmí ruce zvednout.|120",
    "Vibrátor u tváře: Přilož si vibrátor na tvář u pusy a kouři mu – vibrace půjdou do tvé pusy. Cíl: najít polohu, kdy to cítí nejvíc.|90",
    "Šepot mezi tahy: Mezi pohyby mu šeptej, jak chutná a co s ním budeš dělat v další úrovni. Cíl: aby tě poprosil, ať mlčíš a pokračuješ.|120",
    "Maraton pro něj: Kouři mu sedm minut a techniky střídej podle jeho reakcí. Cíl: aby se udělal.|420",
  ],
});
