// Kategorie 3 – Orální hrátky (dávka e)
// Témata: souboje a hry, špinavé řeči, hodnocení, lehké lízání mezi půlkami, finále.
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 3,

  male: [
    "Souboj o vydržení: Střídejte se po minutě. Kdo první řekne dost, plní další přání. Cíl: vydržet déle.|300|p69",
    "Hoď kostkou. Kolik padne, tolik minut ji lížeš bez přerušení.|300|oral_klek",
    "Ona řekne číslo od jedné do desíti a ty přesně tolik minut zůstaneš dole.|300|oral_klek",
    "Za každé slovo, které při tom řekne, jí přidáš deset vteřin navíc.|300|oral_klek",
    "Nech ji hodnotit každý tvůj tah od jedné do pěti. Pod trojku se nesmíš dostat.|300|oral_klek",
    "Hodnocení nahlas: Ona po každé půlminutě řekne známku jako ve škole. Cíl: dostat jedničku třikrát za sebou.|300|oral_klek",
    "Mluv sprostě, zatímco ji lížeš. Když ztichneš, přestaneš.|300|oral_klek",
    "Popisuj jí nahlas, jak chutná a jak vypadá.|300|oral_klek",
    "Řekni jí do stehna jednu sprostou větu a pak pokračuj.|240|oral_klek",
    "Lízej ji a mezi tím jí říkej, co s ní uděláš, až skončíš.|300|oral_klek",
    "Nech ji mluvit sprostě a ty jí odpovídej jen jazykem.|300|oral_klek",
    "Rozkaz shora: Ona ti dává rozkazy a ty je plníš do vteřiny. Cíl: nezaváhat ani jednou.|300|oral_klek",
    "Lízej ji a mezi tím jí lehce olizuj i mezi půlkami. Jen jazykem a jen zvenku.|300|na_brise",
    "Ona leží na břiše. Lízej ji odzadu přes celou tu oblast, ale jemně.|300|na_brise",
    "Ať si klekne a opře se. Ty ji lížeš zezadu odshora dolů.|300|zezadu",
    "Lízej ji a druhou rukou jí namaž zadeček lubrikantem. Nic víc.|300|zezadu",
    "Vsuň jí palec zezadu, zatímco ji lížeš. Hloubku řídí ona.|300|oral_klek",
    "Zezadu a jemně: Lízej ji zezadu, když klečí, a druhou rukou ji dráždi vpředu. Cíl: dělat obojí zároveň.|300|zezadu",
    "Nasaď si erekční kroužek a nech ji, ať ti kouří. Pak ji lížeš ty.|300|p69",
    "Nech ji, ať ti nasadí kroužek, a pak ji lížej tak dlouho, dokud nedojde.|300|oral_klek",
    "Vezmi vibrátor a přilož jí ho zezadu, zatímco ji lížeš zepředu.|300|oral_klek",
    "Lízej ji a mezi tím jí do pusy strkej svoje prsty.|300|oral_klek",
    "Nech ji držet si rty prsty od sebe, ať máš snadnější přístup.|300|oral_klek",
    "Zrcadlová hra: Dělej jí jazykem přesně to, co ona předtím dělala tobě. Cíl: zopakovat to přesně.|300|oral_klek",
    "Nejdřív ji lížeš ty a hned potom ona kouří tobě. Bez přestávky.|300|p69",
    "Střídejte se po třiceti vteřinách. Kdo je na řadě, ten mluví.|300|p69",
    "Lížete se navzájem, ale kdo se první udělá, ten prohrál.|300|p69",
    "Na střídačku: Vy oba se střídáte po minutě a nikdo nesmí dvakrát po sobě. Cíl: pět kol.|300|p69",
    "Nech ji, ať ti při tom sedí na obličeji, a ty jí držíš boky.|300|oral_ona_nad_nim",
    "Lízej ji a nech ji, ať si k tomu hraje s bradavkami sama.|300|oral_klek",
    "Ať ti klečí nad hlavou a sama se pohybuje. Ty jen otevřeš pusu.|300|oral_ona_nad_nim",
    "Lízej ji a druhou ruku jí dej na krk. Jen položit, netlačit.|300|oral_klek",
    "Tahej ji přitom lehce za vlasy a sleduj, jestli se jí to líbí.|300|oral_klek",
    "Ruce a vlasy: Ona ti drží hlavu za vlasy a ty děláš přesně to, kam tě dotlačí. Cíl: nechat se vést.|300|oral_klek",
    "Lízej ji a mezi tím si dej její nohu na rameno.|300|nohy_ramena",
    "Lízej ji s hlavou mezi jejími stehny a rukama na jejích prsou.|300|oral_klek",
    "Nech ji vybrat si tři místa a každému věnuj minutu.|300|oral_klek",
    "Doveď ji ústy až do konce a ani na chvíli nezměň tempo.|300|oral_klek",
    "Až úplně: Doveď ji ústy až za hranu a pokračuj ještě půl minuty potom. Cíl: vydržet i po vrcholu.|300|oral_klek",
    "Lízej ji a mezi tím na ni koukej zdola. Ať to vidí.|300|oral_klek",
    "Nech ji ležet a ty lížeš ze strany. Druhou rukou ji přidržuješ.|300|oral_klek",
    "Ať si sedne na kraj postele a dá ti nohy na ramena.|300|oral_vsede",
    "Lízej ji a mezi tím jí přejeď ledem po břiše.|300|oral_klek",
    "Dej si její kalhotky na hlavu jako vtip a pak pokračuj.|240|oral_klek",
    "Dvacet a dvacet: Dvacet vteřin jazykem, dvacet vteřin prsty. Osm kol. Cíl: nikdy nespojit obojí.|300|oral_klek",
    "Lízej ji a nech ji říkat čísla od desíti dolů. Na nule přestaneš.|300|oral_klek",
    "Nech ji, ať ti sama ukáže, kde přesně to chce, a pak tam zůstaň.|300|oral_klek",
    "Lízej ji a druhou rukou jí drž nohy roztažené za kotníky.|300|nohy_ramena",
    "Ať se dívá dolů na tebe a nesmí zavřít oči ani na vteřinu.|300|oral_klek",
    "Řekni jí, že když vydrží pět minut bez pohybu, dostane, co chce.|300|oral_klek",
    "Nehybná: Ona nesmí pohnout boky. Pokaždé, když to udělá, začínáš od nuly. Cíl: dojet to bez restartu.|300|oral_klek",
    "Lízej ji a mezi tím jí šeptej do stehna, jak ji chceš.|300|oral_klek",
    "Nech ji ležet s polštářem pod boky, ať je výš.|300|misionar_polstar",
    "Ať si lehne na tebe obráceně a ty ji lížeš, zatímco ona nic nedělá.|300|p69",
    "Lízej ji a nech ji, ať ti stiskne hlavu stehny.|300|nohy_ramena",
    "Kdo víc: Počítejte, kolikrát se jí podlomí dech. Pod pět to nesmí klesnout. Cíl: aspoň pět.|300|oral_klek",
    "Lízej ji a druhou rukou si drž její zápěstí.|300|oral_klek",
    "Nech ji sedět na židli a dej si její nohy přes opěradlo.|300|oral_zidle",
    "Lízej ji a přitom si sám hraj s sebou. Ale nesmíš dojít.|300|oral_klek",
    "Řekni jí, že tuhle kartu splníš jen tehdy, když bude nahlas prosit.|300|oral_klek",
    "Prosba nahlas: Ona musí třikrát nahlas říct, co přesně chce. Teprve pak to dostane. Cíl: tři jasné věty.|300|oral_klek",
    "Lízej ji a mezi tím jí kousej do zadečku.|300|na_brise",
    "Ať si klekne nad tebe a pomalu klesá, dokud tě nedosáhne.|300|oral_ona_nad_nim",
    "Lízej ji tak dlouho, dokud ti nezačne kroutit hlavou mezi stehny.|300|oral_klek",
    "Nech ji vybrat, čím skončíte – jazykem, prsty, nebo obojím.|300|oral_klek",
    "Lízej ji a mezi tím jí drž vibrátor na klitorisu, když se nadechne.|300|oral_klek",
    "Až se udělá dvakrát: Nesmíš přestat, dokud nedojde dvakrát. Mezi tím jen zpomal. Cíl: dvě vlny.|300|oral_klek",
    "Lízej ji a pokaždé, když se pokusí utéct, ji přitáhni zpátky.|300|oral_klek",
    "Nech ji ležet na boku a lízej ji zezadu s rukou vpředu.|300|p69_bok",
    "Lízej ji a mezi tím jí olizuj i tříselné rýhy.|300|oral_klek",
    "Ať si drží nohy sama a ty používej jazyk i obě ruce.|300|nohy_ramena",
    "Lízej ji a mezitím jí dej druhou ruku pod zadeček a zvedni ji.|300|nohy_ramena",
    "Bez pomoci: Ona nesmí použít ruce vůbec k ničemu. Ani k držení, ani k tlačení. Cíl: ať to vydrží.|300|oral_klek",
    "Lízej ji a mezi tím jí olizuj i břicho a boky. Nikdy dvakrát za sebou stejně.|300|oral_klek",
    "Nech ji hádat, jestli teď použiješ jazyk, rty, nebo prst.|300|oral_klek",
    "Lízej ji a přitom se snaž nevydat ani hlásku.|300|oral_klek",
    "Ať si sedne na tebe a opře se rukama za sebe.|300|oral_ona_nad_nim",
    "Lízej ji a mezi tím jí stiskni bradavky mezi prsty.|300|oral_klek",
    "Tempo podle dechu: Lížeš přesně tak rychle, jak rychle dýchá. Když zrychlí, zrychlíš i ty. Cíl: kopírovat ji.|300|oral_klek",
    "Doveď ji ústy až na hranu a pak ji nech dojít prsty.|300|oral_klek",
    "Nech ji, ať ti při tom sedí na obličeji a drží se čela postele.|300|oral_ona_nad_nim",
    "Lízej ji a potom ji hned polib na ústa, ať se ochutná.|240|oral_klek",
    "Ať ti kouří a ty ji mezitím lížeš. Kdo přestane první, prohrál.|300|p69",
    "Poslední minuta: Poslední minutu už nesmíš nic měnit – jedno tempo, jedno místo. Cíl: dotáhnout to tak, jak je.|60|oral_klek",
    "Lízej ji a mezi tím jí přejeď štětcem po vnitřní straně stehen.|300|oral_klek",
    "Na konci jí polož hlavu na břicho a poslouchej, jak dýchá.|60|oral_klek",
  ],

  female: [
    "Souboj o vydržení: Střídejte se po minutě. Kdo první řekne dost, plní další přání. Cíl: vydržet déle než on.|300|p69",
    "Hoď kostkou. Kolik padne, tolik minut mu kouříš bez přerušení.|300|oral_on_vleze",
    "On řekne číslo od jedné do desíti a ty přesně tolik minut zůstaneš dole.|300|oral_on_vleze",
    "Za každé slovo, které při tom řekne, mu přidáš deset vteřin navíc.|300|oral_on_vleze",
    "Nech ho hodnotit každý tvůj tah od jedné do pěti. Pod trojku se nesmíš dostat.|300|oral_on_vleze",
    "Známkování: On po každé půlminutě řekne známku jako ve škole. Cíl: dostat jedničku třikrát za sebou.|300|oral_on_vleze",
    "Mluv sprostě, zatímco mu kouříš. Když ztichneš, přestaneš.|300|oral_on_vleze",
    "Popisuj mu nahlas, jak chutná a jak vypadá.|300|oral_on_vleze",
    "Řekni mu do stehna jednu sprostou větu a pak pokračuj.|240|oral_on_vleze",
    "Kouři mu a mezi tím mu říkej, co s ním uděláš, až skončíš.|300|oral_on_vleze",
    "Nech ho mluvit sprostě a ty mu odpovídej jen jazykem.|300|oral_on_vleze",
    "Rozkaz shora: On ti dává rozkazy a ty je plníš do vteřiny. Cíl: nezaváhat ani jednou.|300|oral_on_vleze",
    "Kouři mu a mezi tím mu jazykem přejeď i po hrázi. Jen jemně.|300|oral_on_vleze",
    "On leží na břiše. Olizuj mu zadek a hráz zezadu, ale jemně.|300|na_brise!",
    "Ať si klekne a opře se. Ty ho olizuješ zezadu odshora dolů.|300|zezadu!",
    "Kouři mu a druhou rukou mu namaž hráz lubrikantem. Nic víc.|300|oral_on_vleze",
    "Vsuň mu palec zezadu, zatímco mu kouříš. Hloubku řídí on.|300|oral_on_vleze",
    "Zezadu a jemně: Olizuj ho zezadu, když klečí, a druhou rukou ho dráždi vpředu. Cíl: dělat obojí zároveň.|300|zezadu!",
    "Nasaď mu erekční kroužek a pak mu kouři, dokud to vydrží.|300|oral_on_vleze",
    "Nech ho, ať si nasadí kroužek, a kouři mu tak dlouho, dokud se neudělá.|300|oral_on_vleze",
    "Vezmi vibrátor a přilož mu ho na hráz, zatímco mu kouříš.|300|oral_on_vleze",
    "Kouři mu a mezi tím mu do pusy strkej svoje prsty.|300|oral_on_vleze",
    "Nech ho držet si ho sám u kořene, ať máš snadnější práci.|300|oral_on_vleze",
    "Zrcadlová hra: Dělej mu jazykem přesně to, co on předtím dělal tobě. Cíl: zopakovat to přesně.|300|oral_on_vleze",
    "Nejdřív mu kouříš ty a hned potom on lížeš tobě. Bez přestávky.|300|p69",
    "Po třiceti vteřinách se vždycky vystřídejte a mluvit smí jen ten, kdo je zrovna na řadě.|300|p69",
    "Užívejte si navzájem, ale kdo se první udělá, ten prohrál.|300|p69",
    "Minutu ty, minutu on: Střídáte se po minutě a nikdo nesmí přijít na řadu dvakrát za sebou. Cíl: pět kol.|300|p69",
    "Sedni si mu na obličej a nech se od něj držet za boky.|300|oral_ona_nad_nim",
    "Kouři mu a nech ho, ať si k tomu hraje s tvými prsy.|300|oral_on_vleze",
    "Klekni si mu nad hlavu a sama se pohybuj. On jen otevře pusu.|300|oral_ona_nad_nim",
    "Kouři mu a druhou ruku mu dej na krk. Jen položit, netlačit.|300|oral_on_vleze",
    "Nech ho tahat tě přitom lehce za vlasy a řekni, jestli se ti to líbí.|300|oral_on_vleze",
    "Ruce a vlasy: On ti drží hlavu za vlasy a ty děláš přesně to, kam tě dotlačí. Cíl: nechat se vést.|300|oral_on_vleze",
    "Kouři mu a mezi tím si dej jeho nohu na rameno.|300|oral_on_vleze",
    "Kouři mu s hlavou mezi jeho stehny a rukama na jeho hrudníku.|300|oral_on_vleze",
    "Nech ho vybrat si tři místa a každému věnuj minutu.|300|oral_on_vleze",
    "Doveď ho ústy až do konce a ani na chvíli nezměň tempo.|300|oral_on_vleze",
    "Až úplně: Doveď ho ústy až za hranu a pokračuj ještě půl minuty potom. Cíl: vydržet i po konci.|300|oral_on_vleze",
    "Kouři mu a mezi tím na něj koukej zdola. Ať to vidí.|300|oral_on_vleze",
    "Nech ho ležet a kouři mu ze strany. Druhou rukou ho přidržuješ.|300|oral_on_vleze",
    "Ať si sedne na kraj postele a ty si klekneš mezi jeho kolena.|300|oral_on_vsede",
    "Kouři mu a mezi tím mu přejeď ledem po břiše.|300|oral_on_vleze",
    "Dej si jeho tričko přes hlavu jako vtip a pak pokračuj.|240|oral_on_vleze",
    "Dvacet a dvacet: Dvacet vteřin jazykem, dvacet vteřin rukou. Osm kol. Cíl: nikdy nespojit obojí.|300|oral_on_vleze",
    "Kouři mu a nech ho říkat čísla od desíti dolů. Na nule přestaneš.|300|oral_on_vleze",
    "Nech ho, ať ti sám ukáže, jak přesně to chce, a pak to tak dělej.|300|oral_on_vleze",
    "Kouři mu a druhou rukou mu drž nohy roztažené za kotníky.|300|oral_on_vleze",
    "Ať tě celou dobu sleduje shora a nezavře oči ani na vteřinu.|300|oral_on_vleze",
    "Řekni mu, že když vydrží pět minut bez pohybu, dostane, co chce.|300|oral_on_vleze",
    "Nehybný: On nesmí pohnout boky. Pokaždé, když to udělá, začínáš od nuly. Cíl: dojet to bez restartu.|300|oral_on_vleze",
    "Kouři mu a mezi tím mu šeptej do stehna, jak ho chceš.|300|oral_on_vleze",
    "Nech ho ležet s polštářem pod boky, ať je výš.|300|misionar_polstar",
    "Lehni si na něj obráceně a nech ho, ať nic nedělá. Pracuješ jen ty.|300|p69",
    "Kouři mu a nech ho, ať ti stiskne hlavu stehny.|300|oral_on_vleze",
    "Kdo víc: Počítejte, kolikrát se mu podlomí dech. Pod pět to nesmí klesnout. Cíl: aspoň pět.|300|oral_on_vleze",
    "Kouři mu a druhou rukou si drž jeho zápěstí.|300|oral_on_vleze",
    "Nech ho sedět na židli a dej si jeho nohy přes opěradlo.|300|oral_zidle",
    "Kouři mu a přitom si sama hraj se sebou. Ale nesmíš dojít.|300|oral_on_vleze",
    "Řekni mu, že tuhle kartu splníš jen tehdy, když bude nahlas prosit.|300|oral_on_vleze",
    "Prosba nahlas: On musí třikrát nahlas říct, co přesně chce. Teprve pak to dostane. Cíl: tři jasné věty.|300|oral_on_vleze",
    "Kouři mu a mezi tím ho kousej do zadku.|300|na_brise!",
    "Klekni si nad něj a pomalu klesej, dokud ho nedosáhneš.|300|oral_ona_nad_nim",
    "Kouři mu tak dlouho, dokud tě nezačne tlačit hlouběji.|300|oral_on_vleze",
    "Nech ho vybrat, čím skončíte – ústy, rukou, nebo obojím.|300|oral_on_vleze",
    "Kouři mu a mezi tím mu drž vibrátor na varlatech, když se nadechne.|300|oral_on_vleze",
    "Až na konec a dál: Nesmíš přestat, dokud se neudělá, a pak ještě chvíli jemně pokračuj. Cíl: vydržet i potom.|300|oral_on_vleze",
    "Kouři mu a pokaždé, když se pokusí utéct, ho přitáhni zpátky.|300|oral_on_vleze",
    "Nech ho ležet na boku a olizuj ho zezadu s rukou vpředu.|300|p69_bok",
    "Kouři mu a mezi tím mu olizuj i tříselné rýhy.|300|oral_on_vleze",
    "Ať si drží nohy sám a ty používej jazyk i obě ruce.|300|oral_on_vleze",
    "Kouři mu a mezitím mu dej druhou ruku pod zadek a zvedni ho.|300|oral_on_vleze",
    "Bez pomoci: On nesmí použít ruce vůbec k ničemu. Ani k držení, ani k tlačení. Cíl: ať to vydrží.|300|oral_on_vleze",
    "Kouři mu a mezi tím mu olizuj i břicho a boky. Nikdy dvakrát za sebou stejně.|300|oral_on_vleze",
    "Nech ho hádat, jestli teď použiješ jazyk, rty, nebo ruku.|300|oral_on_vleze",
    "Kouři mu a přitom se snaž nevydat ani hlásku.|300|oral_on_vleze",
    "Sedni si na něj a opři se rukama za sebe.|300|oral_ona_nad_nim",
    "Kouři mu a mezi tím mu stiskni bradavky mezi prsty.|300|oral_on_vleze",
    "Tempo podle dechu: Kouříš přesně tak rychle, jak rychle dýchá. Když zrychlí, zrychlíš i ty. Cíl: kopírovat ho.|300|oral_on_vleze",
    "Doveď ho ústy až na hranu a pak ho nech dojít rukou.|300|oral_on_vleze",
    "Sedni si mu na obličej a drž se čela postele.|300|oral_ona_nad_nim",
    "Kouři mu a potom ho hned polib na ústa.|240|oral_on_vleze",
    "Ať tě líže a ty mu mezitím kouříš. Kdo přestane první, prohrál.|300|p69",
    "Závěr bez změn: V poslední minutě zůstaň u jednoho tempa a jednoho místa. Cíl: dotáhnout to tak, jak je.|60|oral_on_vleze",
    "Kouři mu a mezi tím mu přejeď štětcem po vnitřní straně stehen.|300|oral_on_vleze",
    "Na konci mu polož hlavu na břicho a poslouchej, jak dýchá.|60|oral_on_vleze",
  ],
});
