// Kategorie 3 – Orální hrátky (dávka b)
// Témata: technika, tempo, tlak, jazyk versus rty, kombinace ruky a úst.
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 3,

  male: [
    "Lízej ji jen špičkou jazyka a nikdy nezrychli. Tři minuty stejné tempo.|180|oral_klek",
    "Střídej plochý jazyk a špičku po deseti vteřinách. Ona počítá nahlas.|240|oral_klek",
    "Jazyk a nic víc: Celou dobu používej jen jazyk, ruce drž na jejích stehnech bez pohybu. Cíl: ani jednou nepomoct prsty.|300|oral_klek",
    "Kroužky jazykem kolem klitorisu, nikdy přímo na něm. Až na konci.|240|oral_klek",
    "Sáhni jí dvěma prsty dovnitř a zároveň ji lízej. Pohyb prsty směrem k břichu.|300|oral_klek",
    "Saj jí klitoris rty tak jemně, jako bys ji líbal na ústa.|180|oral_klek",
    "Lízej ji dlouhými tahy odspodu nahoru. Dvacet tahů, pak přestaň.|180|oral_klek",
    "Osmičky: Kresli jí jazykem osmičky a nikdy nezměň směr. Cíl: vydržet celou dobu stejný obrazec.|240|oral_klek",
    "Nejdřív ji lízej přes kalhotky a teprve po minutě je sundej.|240|oral_klek",
    "Dej si její nohy na ramena a lízej ji zespodu.|300|nohy_ramena",
    "Lízej ji a mezi tím na ni foukej studeným dechem.|240|oral_klek",
    "Rychle a pomalu: Půl minuty rychle, půl minuty co nejpomaleji. Pořád dokola. Cíl: nikdy tempo nesplést.|300|oral_klek",
    "Polož jí dlaň na břicho a lehce přitlač, zatímco ji lízáš.|240|oral_klek",
    "Lízej ji tak dlouho, dokud ti sama neřekne, ať přestaneš.|300|oral_klek",
    "Vezmi si do pusy kostku ledu a pak ji lízej. Až roztaje, pokračuj.|240|oral_klek",
    "Dej si do pusy něco mentolového a pak ji lízej. Ať to zebe a hřeje zároveň.|240|oral_klek",
    "Lízej ji a druhou rukou jí dráždi bradavku. Obojí stejným tempem.|300|oral_klek",
    "Trojí kombinace: Jazyk na klitorisu, dva prsty uvnitř a druhá ruka na bradavce. Všechno naráz. Cíl: udržet všechny tři celou dobu.|300|oral_klek",
    "Lízej ji a přitom se jí dívej do očí. Ani jednou neuhni.|240|oral_klek",
    "Nech ji ležet na kraji postele a lízej ji vkleče na podlaze.|300|oral_vsede",
    "Lízej ji zezadu, když klečí na všech čtyřech.|240|zezadu",
    "Ona leží na břiše s polštářem pod boky. Lízej ji zezadu.|300|na_brise",
    "Nech ji sednout si ti na obličej a nehýbej se. Tempo řídí ona.|300|oral_ona_nad_nim",
    "Deset a deset: Deset vteřin lízej, deset vteřin jen dýchej. Pět kol. Cíl: nikdy pauzu nezkrátit.|300|oral_klek",
    "Lízej ji a rukama jí drž stehna od sebe. Nesmí je zavřít.|300|oral_klek",
    "Jazykem obkresluj celý tvar a nikde se nezastavuj.|240|oral_klek",
    "Lízej ji tak, aby se musela držet čela postele.|300|pouta_postel",
    "Střídej lízání a polibky na vnitřní strany stehen.|300|oral_klek",
    "Nejdřív minutu jen dýchej: Celou první minutu na ni jen dýchej a nedotkni se jí. Pak teprve začni. Cíl: vydržet tu minutu.|300|oral_klek",
    "Lízej ji a přitom jí jednou rukou drž ruce nad hlavou.|300|oral_klek",
    "Vsuň do ní jeden prst a lízej ji, dokud se nezačne stahovat.|300|oral_klek",
    "Lízej ji shora dolů, pak zdola nahoru. Pokaždé jinak silně.|240|oral_klek",
    "Pomalu jí strkej prsty dovnitř přesně v tempu jazyka.|300|oral_klek",
    "Ať si sedne na kraj postele a opře se dozadu. Ty klečíš.|300|oral_vsede",
    "Bez rukou: Celý úkol máš ruce za zády. Jen ústa. Cíl: dokázat, že to stačí.|300|oral_klek",
    "Lízej ji a mezitím jí strkej palec do pusy, ať ho saje.|240|oral_klek",
    "Zrychluj postupně tak, že za pět minut dojdeš z nejpomalejšího na nejrychlejší.|300|oral_klek",
    "Lízej ji přesně tak, jak ti to řekne. Poslouchej každé slovo.|300|oral_klek",
    "Nech ji, ať si sama drží nohy, a ty používej obě ruce.|300|nohy_ramena",
    "Sto tahů: Uděláš jí jazykem přesně sto tahů. Ona počítá. Cíl: dojít do sta bez zrychlení.|300|oral_klek",
    "Lízej ji a sleduj, co dělá rukama. Podle toho zrychli nebo zpomal.|300|oral_klek",
    "Vsuň jí prst dovnitř a nehýbej jím. Všechnu práci dělá jazyk.|300|oral_klek",
    "Lízej ji tak jemně, že bude muset sama přitlačit.|240|oral_klek",
    "Nech ji stát a lízej ji vkleče před ní.|240|oral_ona_klek",
    "Lízej ji a pokaždé, když se pohne, na pět vteřin přestaň.|300|oral_klek",
    "Tři místa: Střídej klitoris, vchod a vnitřní stranu stehna. Nikdy dvakrát za sebou stejné. Cíl: devět střídání.|300|oral_klek",
    "Lízej ji přes tenkou látku a teprve na konci ji odhrň.|240|oral_klek",
    "Nech ji ležet s nohama přes tvoje ramena a drž ji za boky.|300|nohy_ramena",
    "Lízej ji a druhou rukou jí masíruj podbřišek.|300|oral_klek",
    "Dej si ji do postele napříč a lízej ji zboku.|300|oral_klek",
    "Až na konec: Lízej ji pět minut, ale nesmíš ji nechat dojít. Cíl: zastavit se včas.|300|oral_klek",
    "Lízej ji tak dlouho, dokud nezvedne boky. Pak se odtáhni a čekej.|240|oral_klek",
    "Vsuň do ní dva prsty a lízej ji zároveň, ale každý jiným tempem.|300|oral_klek",
    "Lízej ji s rukama položenýma na jejích prsou.|300|oral_klek",
    "Nech ji, ať ti drží hlavu a určuje, kam máš jít.|300|oral_klek",
    "Ona počítá: Ona nahlas počítá do dvaceti a ty musíš do posledního čísla vydržet stejné tempo. Cíl: dvacet bez změny.|180|oral_klek",
    "Lízej ji a jednu ruku jí dej do vlasů.|300|oral_klek",
    "Střídej saní a lízání po patnácti vteřinách.|300|oral_klek",
    "Lízej ji a mezi tím jí olizuj vnitřní stranu stehen. Vždycky po půl minutě.|300|oral_klek",
    "Ať si klekne nad tebe a ty ji lízáš zespodu.|300|oral_ona_nad_nim",
    "Jedním prstem: Lízej ji a používej jen jeden prst uvnitř. Ani o jeden víc. Cíl: vystačit si s jedním.|300|oral_klek",
    "Lízej ji a pokaždé, když vydechne, přitlač jazykem.|300|oral_klek",
    "Zavaž jí oči a lízej ji, aniž bys řekl jediné slovo.|300|oral_klek",
    "Lízej ji a druhou rukou si veď její ruku na svoje vlasy.|300|oral_klek",
    "Nech ji, ať si lehne na bok, a lízej ji zezadu.|300|p69_bok",
    "Souboj vůle: Lízej ji tak dlouho, dokud neřekne dost. Ona se snaží vydržet co nejdéle. Cíl: ať se vzdá jako první.|300|oral_klek",
    "Lízej ji rychle, ale jen velmi lehce. Bez tlaku.|240|oral_klek",
    "Nech ji sedět na židli a klekni si před ni.|300|oral_zidle",
    "Lízej ji a druhou rukou jí hlaď záda a zadeček.|300|oral_klek",
    "Vsuň jí prsty dovnitř a jazykem dráždi jen okraje.|300|oral_klek",
    "Lízej ji přesně tak, jak by sis přál, aby ona lízala tebe.|300|oral_klek",
    "Slepá zkouška: Zavaž si oči a lízej ji jen podle toho, jak reaguje. Cíl: trefit se bez očí.|300|oral_klek",
    "Lízej ji a přitom jí zakryj ústa dlaní.|300|oral_klek",
    "Nech ji ležet a lízej ji shora tak, že máš hlavu obráceně.|300|p69",
    "Lízej ji a nech ji mluvit sprostě. Když ztichne, přestaneš.|300|oral_klek",
    "Dej si její koleno přes rameno a lízej ji z jedné strany.|300|oral_klek",
    "Až se udělá: Lízej ji tak dlouho, dokud nedojde, a pak ještě chvíli jemně pokračuj. Cíl: nepřestat příliš brzy.|300|oral_klek",
    "Lízej ji a druhou rukou jí drž nohu zvednutou ke stropu.|300|nohy_ramena",
    "Střídej jazyk a prsty tak, aby nikdy nevěděla, co přijde.|300|oral_klek",
    "Lízej ji tak dlouho, jak ti vydrží dech, pak se nadechni a pokračuj.|240|oral_klek",
    "Nech ji vybrat, jestli chce rychle, nebo dlouho. A dodrž to.|300|oral_klek",
    "Dvě kola: Doveď ji na hranu, přestaň na půl minuty, pak znovu. Podruhé už ji nech dojít. Cíl: vydržet tu pauzu.|300|oral_klek",
    "Lízej ji a druhou rukou jí drž ruku, ať se má čeho držet.|300|oral_klek",
    "Na konec ji jen polib mezi nohy a vstaň.|60|oral_klek",
  ],

  female: [
    "Olizuj mu ho jen špičkou jazyka a nikdy nezrychli. Tři minuty stejné tempo.|180|oral_on_vleze",
    "Střídej plochý jazyk a špičku po deseti vteřinách. On počítá nahlas.|240|oral_on_vleze",
    "Jazyk a nic víc: Celou dobu používej jen jazyk, ruce drž na jeho stehnech bez pohybu. Cíl: ani jednou nepomoct rukou.|300|oral_on_vleze",
    "Krouži jazykem kolem žaludu, nikdy přímo přes něj. Až na konci.|240|oral_on_vleze",
    "Vezmi ho do pusy a zároveň mu rukou masíruj varlata.|300|oral_on_vleze",
    "Saj ho rty tak jemně, jako bys ho líbala na ústa.|180|oral_on_vleze",
    "Olizuj ho dlouhými tahy odspodu nahoru. Dvacet tahů, pak přestaň.|180|oral_on_vleze",
    "Osmičky: Kresli mu jazykem osmičky a nikdy nezměň směr. Cíl: vydržet celou dobu stejný obrazec.|240|oral_on_vleze",
    "Nejdřív ho olizuj přes trenýrky a teprve po minutě mu je sundej.|240|oral_on_vleze",
    "Nech ho ležet a klekni si nad něj tak, abys ho mohla brát shora.|300|oral_on_vleze",
    "Kouři mu a mezi tím na něj foukej studeným dechem.|240|oral_on_vleze",
    "Dvě rychlosti: Třicet vteřin rychle, třicet co nejpomaleji, a tak pořád dokola. Cíl: nikdy tempo nesplést.|300|oral_on_vleze",
    "Polož mu dlaň na břicho a lehce přitlač, zatímco mu kouříš.|240|oral_on_vleze",
    "Kouři mu tak dlouho, dokud ti sám neřekne, ať přestaneš.|300|oral_on_vleze",
    "Vezmi si do pusy kostku ledu a pak ho olizuj. Až roztaje, pokračuj.|240|oral_on_vleze",
    "Dej si do pusy něco mentolového a pak mu kouři. Ať to zebe a hřeje zároveň.|240|oral_on_vleze",
    "Kouři mu a druhou rukou mu dráždi bradavku. Obojí stejným tempem.|300|oral_on_vleze",
    "Trojí kombinace: Ústa nahoře, jedna ruka na kmeni a druhá na varlatech. Všechno naráz. Cíl: udržet všechny tři celou dobu.|300|oral_on_vleze",
    "Kouři mu a přitom se mu dívej do očí. Ani jednou neuhni.|240|oral_on_vleze",
    "Nech ho sedět na kraji postele a kouři mu vkleče na podlaze.|300|oral_on_vsede",
    "Olizuj ho zezadu, když klečí na všech čtyřech.|240|zezadu",
    "On leží na břiše. Olizuj mu záda, zadek a hráz zezadu.|300|na_brise",
    "Klekni si nad něj a nech ho, ať ti pomáhá rukama. Tempo řídíš ty.|300|oral_on_vleze",
    "Deset a deset: Deset vteřin kouříš, deset vteřin jen dýcháš. Pět kol. Cíl: nikdy pauzu nezkrátit.|300|oral_on_vleze",
    "Kouři mu a rukama mu drž stehna od sebe. Nesmí je zavřít.|300|oral_on_vleze",
    "Objeď mu jazykem celý tvar dokola a ani na chvíli se nezastav.|240|oral_on_vleze",
    "Kouři mu tak, aby se musel držet čela postele.|300|pouta_postel",
    "Střídej kouření a polibky na vnitřní strany stehen.|300|oral_on_vleze",
    "Nejdřív minutu jen dýchej: Celou první minutu na něj jen dýchej a nedotkni se ho. Pak teprve začni. Cíl: vydržet tu minutu.|300|oral_on_vleze",
    "Kouři mu a přitom mu jednou rukou drž ruce nad hlavou.|300|oral_on_vleze",
    "Vezmi ho hluboko a pak zase jen špičku. Střídej to.|300|oral_on_vleze",
    "Olizuj ho shora dolů, pak zdola nahoru. Pokaždé jinak silně.|240|oral_on_vleze",
    "Pohybuj rukou přesně v tempu úst. Ani o kousek jinak.|300|oral_on_vleze",
    "Posaď ho na kraj postele, ať se opře dozadu, a ty si klekni mezi jeho kolena.|300|oral_on_vsede",
    "Ruce pryč: Po celý úkol máš ruce složené za zády a pracuješ jen ústy. Cíl: dokázat, že to stačí.|300|oral_on_vleze",
    "Kouři mu a mezitím mu strkej palec do pusy, ať ho saje.|240|oral_on_vleze",
    "Přidávej postupně, ať jsi za pět minut z nejpomalejšího tempa na nejrychlejším.|300|oral_on_vleze",
    "Kouři mu přesně tak, jak ti řekne. Poslouchej každé slovo.|300|oral_on_vleze",
    "Nech ho, ať si sám drží nohy, a ty používej obě ruce.|300|oral_on_vleze",
    "Sto tahů: Uděláš mu jazykem přesně sto tahů. On počítá. Cíl: dojít do sta bez zrychlení.|300|oral_on_vleze",
    "Kouři mu a sleduj, co dělá rukama. Podle toho zrychli nebo zpomal.|300|oral_on_vleze",
    "Vezmi ho do pusy a nehýbej se. Všechnu práci dělá jazyk.|300|oral_on_vleze",
    "Olizuj ho tak jemně, že bude muset sám přitlačit.|240|oral_on_vleze",
    "Nech ho stát a kouři mu vkleče před ním.|240|oral_ona_klek",
    "Kouři mu a pokaždé, když se pohne, na pět vteřin přestaň.|300|oral_on_vleze",
    "Tři místa: Střídej žalud, kmen a varlata. Nikdy dvakrát za sebou stejné. Cíl: devět střídání.|300|oral_on_vleze",
    "Olizuj ho přes tenkou látku a teprve na konci ji odhrň.|240|oral_on_vleze",
    "Nech ho ležet a klekni si vedle jeho hlavy tak, aby na tebe viděl.|300|oral_on_vleze",
    "Kouři mu a druhou rukou mu masíruj podbřišek.|300|oral_on_vleze",
    "Polož si ho napříč postelí a kouři mu zboku.|300|oral_on_vleze",
    "Až na konec: Kouři mu pět minut, ale nesmíš ho nechat dojít. Cíl: zastavit se včas.|300|oral_on_vleze",
    "Kouři mu tak dlouho, dokud nezvedne boky. Pak se odtáhni a čekej.|240|oral_on_vleze",
    "Rukou i ústy zároveň, ale každým jiným tempem.|300|oral_on_vleze",
    "Kouři mu s rukama položenýma na jeho hrudníku.|300|oral_on_vleze",
    "Nech ho, ať ti drží hlavu a určuje tempo.|300|oral_on_vleze",
    "On počítá: On nahlas počítá do dvaceti a ty musíš do posledního čísla vydržet stejné tempo. Cíl: dvacet bez změny.|180|oral_on_vleze",
    "Kouři mu a jednu jeho ruku si dej do vlasů.|300|oral_on_vleze",
    "Střídej saní a olizování po patnácti vteřinách.|300|oral_on_vleze",
    "Kouři mu a mezi tím mu olizuj vnitřní stranu stehen. Vždycky po půl minutě.|300|oral_on_vleze",
    "Klekni si nad něj a kouři mu shora, zatímco tě drží za boky.|300|oral_on_vleze",
    "Jednou rukou: Kouři mu a používej jen jednu ruku. Druhou drž za zády. Cíl: vystačit si s jednou.|300|oral_on_vleze",
    "Kouři mu a pokaždé, když vydechne, přitlač jazykem.|300|oral_on_vleze",
    "Zavaž mu oči a kouři mu, aniž bys řekla jediné slovo.|300|oral_on_vleze",
    "Kouři mu a druhou rukou si veď jeho ruku na svoje vlasy.|300|oral_on_vleze",
    "Nech ho, ať si lehne na bok, a olizuj ho zezadu.|300|p69_bok",
    "Souboj vůle: Kouři mu tak dlouho, dokud neřekne dost. On se snaží vydržet co nejdéle. Cíl: ať se vzdá jako první.|300|oral_on_vleze",
    "Olizuj ho rychle, ale jen velmi lehce. Bez tlaku.|240|oral_on_vleze",
    "Nech ho sedět na židli a klekni si před něj.|300|oral_zidle",
    "Kouři mu a druhou rukou mu hlaď záda a zadek.|300|oral_on_vleze",
    "Vezmi ho do pusy a jazykem dráždi jen okraj žaludu.|300|oral_on_vleze",
    "Kouři mu přesně tak, jak by sis přála, aby on lízal tebe.|300|oral_on_vleze",
    "Slepá zkouška: Zavaž si oči a kouři mu jen podle toho, jak reaguje. Cíl: trefit se bez očí.|300|oral_on_vleze",
    "Kouři mu a přitom mu zakryj ústa dlaní.|300|oral_on_vleze",
    "Nech ho ležet a kouři mu shora tak, že máš hlavu obráceně.|300|p69",
    "Kouři mu a nech ho mluvit sprostě. Když ztichne, přestaneš.|300|oral_on_vleze",
    "Dej si jeho koleno přes rameno a olizuj ho z jedné strany.|300|oral_on_vleze",
    "Až se udělá: Kouři mu tak dlouho, dokud se neudělá, a pak ještě chvíli jemně pokračuj. Cíl: nepřestat příliš brzy.|300|oral_on_vleze",
    "Kouři mu a druhou rukou mu drž nohu zvednutou.|300|oral_on_vleze",
    "Střídej ústa a ruku tak, aby nikdy nevěděl, co přijde.|300|oral_on_vleze",
    "Kouři mu tak dlouho, jak ti vydrží dech, pak se nadechni a pokračuj.|240|oral_on_vleze",
    "Nech ho vybrat, jestli chce rychle, nebo dlouho. A dodrž to.|300|oral_on_vleze",
    "Dvě kola: Doveď ho na hranu, přestaň na půl minuty, pak znovu. Podruhé už ho nech dojít. Cíl: vydržet tu pauzu.|300|oral_on_vleze",
    "Kouři mu a druhou rukou mu drž ruku, ať se má čeho držet.|300|oral_on_vleze",
    "Na konec ho jen polib mezi nohy a vstaň.|60|oral_on_vleze",
  ],
});
