// Kategorie 3 – Orální hrátky (dávka c)
// Témata: polohy, 69, klečení, kraj postele, ve stoje, svázané ruce, oční kontakt.
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 3,

  male: [
    "Lehněte si na bok proti sobě a užívejte si navzájem ústy ve stejnou chvíli.|300|p69_bok",
    "Lehni si na záda a nech ji, ať si na tebe lehne obráceně. Ty jsi dole.|300|p69",
    "Devětašedesát shora: Lehni si na záda, nech ji nad sebou a drž ji za boky. Ona řídí hloubku. Cíl: nechat vedení na ní.|300|p69",
    "Ona leží na zádech přes kraj postele s hlavou dolů. Ty stojíš u ní.|240|oral_okraj",
    "Nech ji klečet na posteli a ty jí lížeš zezadu mezi nohama.|300|zezadu",
    "Posaď ji na židli, roztáhni jí kolena a klekni si.|300|oral_zidle",
    "Ať se opře zády o zeď a ty ji lížeš vkleče.|240|zed",
    "Nech ji sednout si na kraj postele a opřít se dozadu o ruce.|300|oral_vsede",
    "Poloha na hlavu: Ona leží a ty si klekneš nad ni obráceně. Ústa na ústa, ale dole. Cíl: neztratit rytmus.|300|p69",
    "Ať si klekne nad tvůj obličej a opře se o čelo postele.|300|oral_ona_nad_nim",
    "Lež na zádech a nech ji, ať si sedne a pomalu se pohybuje. Ty jen držíš.|300|oral_ona_nad_nim",
    "Dej si ji na břicho a lízej ji zezadu, zatímco jí zvedáš boky.|300|na_brise",
    "Ona leží a ty jí dáš obě nohy na svoje ramena.|300|nohy_ramena",
    "Lízej ji ve stoje, když se drží tvých ramen.|240|oral_ona_klek",
    "Klek a čekání: Nech ji stát a klekni si před ni. Nezačneš, dokud tě sama nepřitáhne. Cíl: vydržet čekat.|240|oral_ona_klek",
    "Sváž jí ruce kravatou nad hlavou a pak ji lízej.|300|pouta_postel",
    "Sváž jí ruce ke kotníkům, ať se nemůže hýbat, a pomalu ji lízej.|300|nohy_ramena",
    "Ona má ruce svázané za zády a klečí. Ty ji lížeš zezadu.|300|zezadu",
    "Lízej ji a ona se ti nesmí ani jednou podívat do očí.|300|oral_klek",
    "Pravidlo pohledu: Ona se ti musí celou dobu dívat do očí. Když uhne, přestaneš. Cíl: nepřestat ani jednou.|300|oral_klek",
    "Nech ji opřít se o opěradlo gauče a lízej ji zezadu.|300|predklon",
    "Ona sedí na tobě a ty jí lížeš prsa. Až pak sjedeš níž.|300|klin_celem",
    "Nech ji ležet napříč postelí s hlavou přes okraj a lízej ji shora.|300|oral_okraj",
    "Ať si lehne na bok a zvedne horní nohu. Lízej ji z boku.|300|p69_bok",
    "Ona klečí na židli čelem k opěradlu a ty jí lížeš zezadu.|300|zidle_celem",
    "Šedesát devět vestoje: Nemožné, tak zkuste kompromis – ona klečí, ty stojíš a nakloníš se k ní. Cíl: najít polohu, co vám sedne.|240|oral_ona_klek",
    "Nech ji ležet s polštářem pod boky a lízej ji seshora.|300|misionar_polstar",
    "Ona leží na zádech a ty jí rukama roztahuješ kolena. Nesmí je zavřít.|300|oral_klek",
    "Lízej ji, zatímco stojí a jednu nohu má opřenou o postel.|240|oral_ona_klek",
    "Nech ji, ať si sama vybere polohu, a ty se přizpůsobíš.|300|oral_klek",
    "Tři polohy: Během úkolu vystřídáte tři různé polohy a ani na chvíli nepřestaneš. Cíl: plynulé přechody.|300|oral_klek",
    "Ať si klekne na všechny čtyři a opře se o lokty. Ty za ní.|300|zezadu",
    "Ona leží a ty ležíš mezi jejíma nohama na břiše. Ruce máš pod jejím zadečkem.|300|oral_klek",
    "Nech ji sedět na tobě obráceně a lízej ji, zatímco ti kouří.|300|p69",
    "Nech ji ležet a ty si klekni vedle její hlavy. Střídavě ji líbáš a lížeš.|300|oral_klek",
    "Vzájemně a naráz: Oba zároveň, ale kdo první zrychlí, ten prohrál. Cíl: udržet stejné tempo.|300|p69",
    "Ona stojí předkloněná přes postel a ty klečíš za ní.|240|predklon",
    "Lízej ji, zatímco jí držíš ruce za zády.|300|zezadu",
    "Nech ji ležet s nohama pokrčenýma a lízej ji shora dolů.|300|misionar",
    "Sedni si na podlahu a nech ji sednout si na tebe. Lízej ji zdola.|300|oral_ona_nad_nim",
    "Ona leží na tobě obráceně a ty ji držíš za stehna.|300|p69",
    "Sváž jí kravatou jednu nohu k posteli. Druhá zůstane volná.|300|nohy_ramena",
    "Nech ji klečet nad tvým obličejem a drž ji za boky, ať neuteče.|300|oral_ona_nad_nim",
    "Přes okraj: Ať si lehne tak, aby jí hlava visela přes okraj postele, a lízej ji odshora. Cíl: vydržet tu polohu.|240|oral_okraj",
    "Ona sedí na kraji postele a ty klečíš. Drž jí ruce v dlaních.|300|oral_vsede",
    "Lízej ji a jednou rukou si drž její kotník.|300|nohy_ramena",
    "Nech ji ležet na zádech a klekni si nad ni obráceně, ale ty jen lížeš.|300|p69",
    "Ať se opře o kraj postele a ty ji lížeš zezadu vkleče.|300|zezadu",
    "Lízej ji na boku, když má nohy propletené s tvýma.|300|p69_bok",
    "Ona klečí a drží se opěradla. Ty klečíš pod ní.|300|oral_ona_nad_nim",
    "Nahoru a dolů: Vystřídáš tři výšky – ona vleže, vsedě a ve stoje. V každé aspoň minutu. Cíl: projít všechny tři.|300|oral_vsede",
    "Sváž jí ruce a posaď ji na kraj postele. Pak si klekni.|300|oral_vsede",
    "Nech ji ležet a zvedni jí boky rukama nahoru. Lízej ji zespodu.|300|nohy_ramena",
    "Ona leží na břiše přes polštář a ty jí lížeš zezadu.|300|na_brise",
    "Klekni si mezi její kolena tak, aby na tebe viděla.|300|oral_klek",
    "Nech ji, ať si sedne na židli a přehodí ti nohy přes ramena.|300|oral_zidle",
    "Dívej se a lízej: Ona se dívá na všechno, co děláš, a nahlas to komentuje. Cíl: ať nepřestane mluvit.|300|oral_klek",
    "Ona stojí a ty klečíš. Drží se tvé hlavy a určuje směr.|240|oral_ona_klek",
    "Lízej ji na boku, když leží před tebou zády.|300|p69_bok",
    "Nech ji ležet a lízej ji s hlavou opřenou o její stehno.|300|oral_klek",
    "Ať se opře o zeď a zvedne jednu nohu na tvoje rameno.|240|zed",
    "Ona sedí na tobě a ty ji lížeš, zatímco leží na zádech.|300|oral_klek",
    "Dvojice zároveň: Vy oba ústy, ale ty musíš být vždycky o vteřinu napřed. Cíl: udržet náskok.|300|p69",
    "Nech ji položit si nohy na čelo postele a lízej ji seshora.|300|nohy_ramena",
    "Ona klečí vedle tebe a ty ležíš. Lízej ji zboku.|300|p69_bok",
    "Sváž jí ruce nad hlavou a nech ji ležet nehnutě, zatímco ji lížeš.|300|pouta_postel",
    "Lízej ji tak, aby musela ležet úplně rovně a nesměla se ohnout.|300|oral_klek",
    "Nech ji sedět na tvém obličeji a řídit všechno sama.|300|oral_ona_nad_nim",
    "Poloha bez rukou: Vyber polohu, ve které nemáš volné ruce, a vydrž v ní celou dobu. Cíl: nepomoct si.|300|oral_ona_nad_nim",
    "Ona leží na kraji postele a ty klečíš na podlaze mezi jejími koleny.|300|oral_vsede",
    "Lízej ji, když stojí předkloněná a opírá se o kolena.|240|predklon_stoje",
    "Ať si klekne a ty si lehneš pod ni. Pak už jen drž.|300|oral_ona_nad_nim",
    "Nech ji ležet a ty lížeš zespoda s rukama na jejích prsou.|300|oral_klek",
    "Ona má ruce svázané za zády a stojí. Ty klečíš.|240|oral_ona_klek",
    "Vzájemně na boku: Oba na boku, ale ty přestaneš vždycky, když ona zrychlí. Cíl: naučit ji pomalost.|300|p69_bok",
    "Lízej ji přes opěradlo, zatímco se drží gauče.|300|predklon",
    "Nech ji sedět na židli a lízej ji s rukama za zády.|300|oral_zidle",
    "Ona leží a ty jí dáš jednu nohu na rameno a druhou necháš dole.|300|nohy_ramena",
    "Lízej ji, zatímco ti sedí na klíně zády.|300|klin_zady",
    "Nech ji ležet a ty ležíš vedle. Lížeš ji ze strany a rukou hladíš.|300|oral_klek",
    "Poslední poloha: Nech ji vybrat, ve které poloze má skončit, a v ní ji doveď až na konec. Cíl: skončit tam, kde chce ona.|300|oral_klek",
    "Lízej ji tak, aby se musela držet tvých vlasů.|300|oral_klek",
    "Nech ji sedět na tobě a jen se dívej, jak se hýbe.|300|oral_ona_nad_nim",
    "Na konec ji polož a polib ji na břicho. Pak vstaň.|60|oral_klek",
  ],

  female: [
    "Lehni si na bok proti němu a užívejte si navzájem ústy ve stejnou chvíli.|300|p69_bok",
    "Lehni si na něj obráceně a nech ho, ať tě drží. Ty jsi nahoře.|300|p69",
    "Devětašedesát shora: Klekni si nad něj obráceně a hloubku si řiď sama. On tě jen drží za boky. Cíl: mít to celé pod kontrolou.|300|p69",
    "Nech ho ležet přes kraj postele s hlavou dolů a stoupni si k němu.|240|oral_okraj!",
    "Nech ho klečet na posteli a ty ho olizuješ zezadu mezi nohama.|300|zezadu!",
    "Posaď ho na židli, roztáhni mu kolena a klekni si.|300|oral_zidle",
    "Ať se opře zády o zeď a ty mu kouříš vkleče.|240|zed",
    "Nech ho sednout si na kraj postele a opřít se dozadu o ruce.|300|oral_on_vsede",
    "Poloha na hlavu: Klekni si nad něj obráceně, ústa na ústa, ale dole. Cíl: neztratit rytmus.|300|p69",
    "Klekni si nad jeho obličej a opři se o čelo postele.|300|oral_ona_nad_nim",
    "Sedni si na něj a pomalu se pohybuj. On tě jen drží.|300|oral_ona_nad_nim",
    "Polož ho na břicho a olizuj ho zezadu, zatímco mu zvedáš boky.|300|na_brise!",
    "Nech ho ležet a dej si jeho kolena přes svoje ramena.|300|oral_on_vleze",
    "Kouři mu ve stoje, když se drží tvých ramen.|240|oral_ona_klek",
    "Klek a čekání: Nech ho stát a klekni si před něj. Nezačneš, dokud tě sám nepřitáhne. Cíl: vydržet čekat.|240|oral_ona_klek",
    "Sváž mu ruce kravatou nad hlavou a pak mu kouři.|300|pouta_postel!",
    "Sváž mu ruce ke kotníkům, ať se nemůže hýbat, a pomalu mu kouři.|300|oral_on_vleze",
    "On má ruce svázané za zády a klečí. Ty ho olizuješ zezadu.|300|zezadu!",
    "Kouři mu a on se ti nesmí ani jednou podívat do očí.|300|oral_on_vleze",
    "Pravidlo pohledu: On se ti musí celou dobu dívat do očí. Když uhne, přestaneš. Cíl: nepřestat ani jednou.|300|oral_on_vleze",
    "Nech ho opřít se o opěradlo gauče a olizuj ho zezadu.|300|predklon!",
    "Sedni si na něj a olizuj mu hrudník. Až pak sjedeš níž.|300|klin_celem",
    "Nech ho ležet napříč postelí s hlavou přes okraj a kouři mu shora.|300|oral_okraj!",
    "Ať si lehne na bok a zvedne horní nohu. Olizuj ho z boku.|300|p69_bok",
    "On klečí na židli čelem k opěradlu a ty ho olizuješ zezadu.|300|zidle_celem",
    "Devětašedesát vestoje: Nejde to, tak zkuste kompromis – ty klečíš, on stojí a nakloní se k tobě. Cíl: najít polohu, co vám sedne.|240|oral_ona_klek",
    "Nech ho ležet s polštářem pod boky a kouři mu seshora.|300|misionar_polstar",
    "On leží na zádech a ty mu rukama roztahuješ kolena. Nesmí je zavřít.|300|oral_on_vleze",
    "Kouři mu, zatímco stojí a jednu nohu má opřenou o postel.|240|oral_ona_klek",
    "Nech ho, ať si sám vybere polohu, a ty se přizpůsobíš.|300|oral_on_vleze",
    "Trojí poloha: Vystřídejte během úkolu tři polohy a ty u toho ani na vteřinu nepřestaneš. Cíl: plynulé přechody.|300|oral_on_vleze",
    "Ať si klekne na všechny čtyři a opře se o lokty. Ty za ním.|300|zezadu!",
    "On leží a ty ležíš mezi jeho nohama na břiše. Ruce máš pod jeho zadkem.|300|oral_on_vleze",
    "Sedni si na něj obráceně a kouři mu, zatímco tě on líže.|300|p69",
    "Nech ho ležet a klekni si vedle jeho hlavy. Střídavě ho líbáš a olizuješ.|300|oral_on_vleze",
    "Oba naráz: Užívejte si navzájem ve stejnou chvíli a kdo první zrychlí, prohrál. Cíl: udržet stejné tempo.|300|p69",
    "On stojí předkloněný přes postel a ty klečíš za ním.|240|predklon",
    "Kouři mu, zatímco mu držíš ruce za zády.|300|zezadu!",
    "Nech ho ležet s nohama pokrčenýma a kouři mu shora dolů.|300|oral_on_vleze",
    "Sedni si na podlahu a nech ho stoupnout si před tebe.|300|oral_ona_klek",
    "On leží pod tebou obráceně a ty ho držíš za stehna.|300|p69",
    "Sváž mu kravatou jednu nohu k posteli. Druhá zůstane volná.|300|oral_on_vleze",
    "Klekni si nad jeho obličej a drž se čela postele.|300|oral_ona_nad_nim",
    "Přes okraj: Ať si lehne tak, aby mu hlava visela přes okraj postele, a kouři mu odshora. Cíl: vydržet tu polohu.|240|oral_okraj!",
    "On sedí na kraji postele a ty klečíš. Drž mu ruce v dlaních.|300|oral_on_vsede",
    "Kouři mu a jednou rukou si drž jeho kotník.|300|oral_on_vleze",
    "Nech ho ležet a klekni si nad něj obráceně, ale ty jen kouříš.|300|p69",
    "Ať se opře o kraj postele a ty ho olizuješ zezadu vkleče.|300|zezadu!",
    "Olizuj ho na boku, když má nohy propletené s tvýma.|300|p69_bok",
    "On klečí a drží se opěradla. Ty klečíš pod ním.|300|oral_on_vleze",
    "Nahoru a dolů: Vystřídáš tři výšky – on vleže, vsedě a ve stoje. V každé aspoň minutu. Cíl: projít všechny tři.|300|oral_on_vsede",
    "Sváž mu ruce a posaď ho na kraj postele. Pak si klekni.|300|oral_on_vsede",
    "Nech ho ležet a zvedni mu boky rukama nahoru. Olizuj ho zespodu.|300|oral_on_vleze",
    "On leží na břiše přes polštář a ty ho olizuješ zezadu.|300|na_brise!",
    "Klekni si mezi jeho kolena tak, aby na tebe viděl.|300|oral_on_vleze",
    "Nech ho sednout si na židli a přehoď si jeho nohu přes rameno.|300|oral_zidle",
    "Dívej se a kouři: On se dívá na všechno, co děláš, a nahlas to komentuje. Cíl: ať nepřestane mluvit.|300|oral_on_vleze",
    "On stojí a ty klečíš. Drží tvoji hlavu a určuje tempo.|240|oral_ona_klek",
    "Olizuj ho na boku, když leží před tebou zády.|300|p69_bok",
    "Nech ho ležet a kouři mu s hlavou opřenou o jeho stehno.|300|oral_on_vleze",
    "Ať se opře o zeď a ty klečíš před ním s rukama na jeho bocích.|240|zed",
    "Sedni si na něj a kouři mu, zatímco leží na zádech.|300|oral_on_vleze",
    "O vteřinu napřed: Oba ústy naráz, ale ty musíš být pořád o vteřinu před ním. Cíl: udržet náskok.|300|p69",
    "Nech ho opřít si nohy o čelo postele a kouři mu seshora.|300|oral_on_vleze",
    "On klečí vedle tebe a ty ležíš. Olizuj ho zboku.|300|p69_bok",
    "Sváž mu ruce nad hlavou a nech ho ležet nehnutě, zatímco mu kouříš.|300|pouta_postel!",
    "Kouři mu tak, aby musel ležet úplně rovně a nesměl se ohnout.|300|oral_on_vleze",
    "Sedni si mu na obličej a řiď všechno sama.|300|oral_ona_nad_nim",
    "Ruce mimo hru: Zvol si polohu, ve které se rukama nedostaneš nikam, a vydrž v ní. Cíl: nepomoct si.|300|oral_ona_nad_nim",
    "On leží na kraji postele a ty klečíš na podlaze mezi jeho koleny.|300|oral_on_vsede",
    "Kouři mu, když stojí předkloněný a opírá se o kolena.|240|predklon_stoje!",
    "Ať si klekne a ty si lehneš pod něj. Pak už jen drž.|300|oral_on_vleze",
    "Nech ho ležet a kouři mu zespoda s rukama na jeho hrudníku.|300|oral_on_vleze",
    "On má ruce svázané za zády a stojí. Ty klečíš.|240|oral_ona_klek",
    "Vzájemně na boku: Oba na boku, ale ty přestaneš vždycky, když on zrychlí. Cíl: naučit ho pomalost.|300|p69_bok",
    "Olizuj ho přes opěradlo, zatímco se drží gauče.|300|predklon!",
    "Nech ho sedět na židli a kouři mu s rukama za zády.|300|oral_zidle",
    "On leží a ty mu dáš jednu nohu na rameno a druhou necháš dole.|300|oral_on_vleze",
    "Kouři mu, zatímco ti sedí za zády a drží tě.|300|klin_zady",
    "Nech ho ležet a ty ležíš vedle. Olizuješ ho ze strany a rukou hladíš.|300|oral_on_vleze",
    "Poslední poloha: Nech ho vybrat, ve které poloze má skončit, a v ní ho doveď až na konec. Cíl: skončit tam, kde chce on.|300|oral_on_vleze",
    "Kouři mu tak, aby se musel držet tvých vlasů.|300|oral_on_vleze",
    "Sedni si na něj a jen se dívej, jak se snaží vydržet.|300|oral_ona_nad_nim",
    "Na konec ho polož a polib ho na břicho. Pak vstaň.|60|oral_on_vleze",
  ],
});
