// Kategorie 3 – Orální hrátky
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 3,
  name: "Orální hrátky",
  description: "Rty, jazyk a pořádná dávka trpělivosti. Tady se nikdo nikam nespěchá.",

  // Úkoly pro muže – pro potěšení ženy
  male: [
    "Posaď ji na kuchyňskou linku, klekni si před ni a lízej ji pomalými dlouhými tahy zdola nahoru.|120",
    "Lehni si na záda a nech ji, ať si ti sedne na obličej. Ona určuje tempo i tlak.|180",
    "Posaď ji na gauč s nohama přes tvá ramena a jazykem kresli abecedu na jejím klitorisu.|120",
    "Lízej ji a zároveň jí vibrátorem hlaď bradavky.|120",
    "Zavaž jí oči a lízej ji. Pokaždé, když vzdychne, změň rytmus.|120",
    "Jemně jí saj klitoris rty a přitom jazykem kmitej.|60",
    "Lízej ji a vsuň do ní dva prsty – pohyb „pojď sem“ proti přední stěně.|120",
    "Postav ji zády ke zdi v chodbě, jednu nohu jí dej na své rameno a lízej ji vestoje.|90",
    "Nech ji ležet na posteli s polštářem pod zadečkem a lízej ji tak dlouho, dokud neřekne dost.",
    "Lízej ji přes kalhotky, dokud nejsou mokré. Pak je odhrň stranou a pokračuj.|120",
    "Přikládej vibrátor na její klitoris a jazykem ji lízej o kousek níž.|90",
    "69 na boku – oba ležíte na posteli a lížete se navzájem. Ty se soustřeď hlavně na ni.|180",
    "Posaď ji na jídelní židli, klekni si před ni a lízej ji, zatímco se drží opěradla.|120",
    "Líbej ji po vnitřní straně stehen až ke klínu, pak zpátky a znovu. Až na třetí pokus ji olízni.",
    "Nech ji klečet na gauči opřenou o opěradlo a lízej ji zezadu.|120",
    "Saj a olizuj jí bradavky střídavě, zatímco ji prsty hladíš mezi nohama.|90",
    "Ve sprše si klekni, dej si její nohu na rameno a lízej ji pod tekoucí vodou.|90",
    "Lízej ji tak pomalu, jak jen dokážeš. Kdyby tě chtěla popohnat, zpomal ještě víc.|120",
    "Jazyk nech pevně na jejím klitorisu a nehýbej s ním. Ona se musí hýbat sama.|60",
    "Dej si na jazyk kapku šlehačky, medu nebo čokolády a olízni ji z jejích bradavek a podbřišku.",
    "Lízej ji a zároveň jí pevně drž boky, ať nemůže uhnout.|120",
    "Posaď ji na pračku, roztáhni jí nohy a lízej ji.|120",
    "Nech ji, ať se ti posadí na obličej čelem k tvým nohám, a ty ji lízej, zatímco se předkloní a dívá se na tebe.|120",
    "Střídej: 10 vteřin rychle jazykem po klitorisu, 10 vteřin pomalé líbání stydkých pysků.|120",
    "Líbej jí klín jako ústa – pomalu, s jazykem, vášnivě.|90",
    "Lízej ji a oběma rukama jí přitom mačkej prsa.|120",
    "Nech ji ležet na posteli, klekni si nad ni obráceně a lízej ji, zatímco ona hladí rukou tebe.|120",
    "Lízej ji s vibrátorem vloženým jen kousek do ní na nejnižším stupni.|120",
    "Jazykem jí olizuj jen okolí klitorisu, ale přímo na něj nesahej, dokud o to nepožádá.",
    "Posaď se na podlahu, ona se postaví nad tebe s jednou nohou na gauči. Lízej ji zespodu.|90",
    "Lízej ji a vždy, když se blíží vrchol, přestaň a polib ji na stehno. Třikrát, pak ji nech dojít.",
    "Foukni jí jemně na klitoris, olízni ho a znovu foukni. Opakuj pomalu.|60",
    "Posaď ji na gauč naproti zrcadlu, klekni si mezi její nohy a lízej ji, zatímco se dívá do zrcadla.|120",
    "Lízej ji, dokud nebude mít orgasmus. Pak ji jemně olízni ještě jednou.",
    "Jazykem ji pronikni tak hluboko, jak to jde, a pomalu s ním pohybuj.|60",
    "Nech ji ležet na kuchyňském stole na zádech a lízej ji.|120",
    "Vezmi pírko a střídej ho s jazykem – pírko, jazyk, pírko, jazyk.|90",
    "Nech ji stát předkloněnou u linky a zezadu ji lízej, rukama jí roztahuj hýždě.|90",
    "Olizuj jí prsty na nohou a pomalu stoupej jazykem po celé noze až ke klínu.",
    "Lízej ji a přitom jí vibrátorem masíruj hráz.|90",
    "Nech ji, ať ti drží hlavu ve vlasech a sama si tě navádí, kam potřebuje.|120",
    "Pomalu jí saj stydké pysky, každý zvlášť, a pak klitoris.|90",
    "Lízej ji s jazykem naplocho a širokými tahy, jako bys lízal zmrzlinu.|90",
    "Zavaž jí oči a ruce jí dej za hlavu. Lízej ji a ona se nesmí pohnout.|120",
    "Lehni si na záda na koberec v obýváku a nech ji, ať si klekne nad tvůj obličej.|120",
    "Líbej ji na klín přes kalhotky a přitom jí je pomalu stahuj zuby.",
    "69 – ona nahoře. Kdo dřív přestane, plní ještě jeden úkol navíc.|180",
    "Kresli jí jazykem kolečka po směru hodin, pak proti. Zeptej se, co je lepší, a u toho zůstaň.|90",
    "Nech ji sedět na okraji vany a lízej ji, zatímco jí stéká teplá voda po zádech.|90",
    "Lízej jí bradavky tak dlouho, dokud nebudou tvrdé, pak sjeď jazykem po břiše až dolů.",
    "Lízej ji a zároveň jí prstem jemně hlaď kolem zadečku (s lubrikantem, bez vnikání).|90",
    "Posaď ji do křesla s nohama přes opěrky a lízej ji v klidu jako na hostině.|180",
    "Rty jemně sevři její klitoris a pomalu ho vytahuj, jako bys sál bonbon.|60",
    "Nech ji ležet na boku, zvedni jí horní nohu a lízej ji zezadu.|90",
    "Lízej ji a nech ji, ať ti přitom říká, co přesně má dělat.|120",
    "Jeden vibrátor na klitoris, tvůj jazyk u vstupu.|90",
    "Přitiskni ústa na její klín a hlasitě bzuč – hlasivky budou vibrovat.|30",
    "Líbej ji po celém těle a končí to vždy mezi nohama. Pětkrát.",
    "Lízej ji, zatímco ona leží na gauči s hlavou na polštáři a sleduje tě.|120",
    "Přejížděj jí jazykem od klitorisu až dozadu a zase zpátky.|60",
    "Nech ji klečet na posteli s hlavou v polštáři a lízej ji zezadu, zatímco ji hladíš po zádech.|120",
    "Lízej ji a přitom jí jemně stiskni bradavku pokaždé, když olízneš klitoris.|90",
    "Posaď se na zem opřený o gauč, ona si sedne na opěradlo gauče nad tebou a ty ji lízej.|90",
    "Lízej jí klitoris a dvěma prsty v ní dělej malá kolečka.|120",
    "Dej si kostku ledu do pusy na pár vteřin, vyplivni ji a hned ji studeným jazykem olízni.",
    "Nech ji, ať si sama roztáhne stydké pysky prsty, a ty ji lízej přesně tam, kde ukáže.|90",
    "Lízej ji ve stoje: ona stojí opřená o dveře ložnice, ty klečíš.|90",
    "Lízej ji a mezitím jí druhým vibrátorem hlaď bradavky.|120",
    "Lízej ji tak, jak by sis přál, aby lízala ona tebe – vášnivě a bez spěchu.|120",
    "Líbej ji na rty a pak hned na klín. Střídej to, ať cítí svou chuť.|90",
    "Nech ji ležet na zádech na posteli, zvedni jí nohy nahoru a lízej ji.|120",
    "Lehni si na gauč s hlavou na sedáku a nech ji, ať si nad tebou klekne a opře se rukama o opěradlo.|120",
    "Lízej ji a přitom se jí dívej do očí, i když ona zavře svoje.|90",
    "Lízej ji a pomalu do ní přitom vsouvej a vytahuj vibrátor.|120",
    "Olízni jí vnitřní stranu stehen zezdola nahoru – a u klína se zastav a foukni.",
    "Lízej ji a vždy po 20 vteřinách jí polib bradavku. Opakuj.|120",
    "Nech ji, ať si lehne na jídelní stůl, a sedni si na židli mezi její nohy jako k večeři.|180",
    "Lízej ji a nech ji, ať ti za vlasy přitahuje hlavu blíž, kdykoli chce.|120",
    "Jazykem jí dělej rychlé kmitání nahoru a dolů přímo na klitorisu.|60",
    "Nech ji stát ve sprše s jednou nohou na okraji vany a lízej ji.|90",
    "69 vleže na gauči. Ty dole, ona nahoře. Obě ruce jí dej na zadeček.|180",
    "Lízej ji a zároveň jí vibrátorem hlaď podbřišek těsně nad klitorisem.|90",
    "Rty jí sevři klitoris a pomalu, rytmicky saj – jako tep.|60",
    "Lízej ji a nesmíš použít ruce. Ruce drž za zády.|120",
    "Nech ji ležet s roztaženýma nohama a lízej ji jen samotnou špičkou jazyka.|90",
    "Kousni ji jemně do vnitřní strany stehna a pak ji hned olízni přímo na klitorisu.",
    "Lízej ji a mluv na ni – mezi každým olíznutím jí řekni, jak skvěle chutná.|90",
    "Nech ji, ať se ti posadí na obličej na posteli a drží se čela postele.|180",
    "Lízej ji a dvěma prsty jí jemně roztahuj stydké pysky, ať máš přístup ke všemu.|90",
    "Dej jí na klitoris kapku lubrikantu s příchutí a olízni ji do čista.",
    "Klekni si mezi její nohy na podlaze v obýváku, ona leží na gauči. Lízej ji, dokud nebude křičet.",
    "Lízej ji, zatímco ona sama drží vibrátor na svých bradavkách.|120",
    "Lízej ji ve vaně nebo pod sprchou, zatímco jí proud vody stéká po břiše.|90",
    "Nech ji ležet na zádech, ruce jí polož na prsa a lízej ji. Tvoje ruce drží její nohy roztažené.|120",
    "Líbej ji, lízej ji, saj ji – každou minutu změň techniku.|180",
    "Zeptej se jí, jak se jí to líbí nejvíc, a přesně tak ji lízej.|120",
    "Lízej ji zezadu, zatímco klečí na gauči a hladí se sama po prsou.|90",
    "Lízej ji a jakmile ji přejde orgasmus, pokračuj velmi jemně, dokud tě neodstrčí.",
    "Pomalu jí přejížděj jazykem po bradavkách a sjížděj níž – s každým dalším kolečkem o kousek.|90",
    "Lízej ji s vibrátorem na klitorisu a jazykem ve vstupu – pak si to prohoďte.|120",
    "Vsuň jí palec dovnitř a jazykem ji lízej nahoře.|90",
    "Nech ji sedět na kuchyňském stole, polib ji na klín a pak se dlouho věnuj jen bradavkám. Pak zpátky dolů.|120",
    "Lízej ji a přitom ji jemně pleskej po stehně v rytmu olíznutí.|60",
    "Nech ji ležet na posteli a lízej ji, zatímco ona drží tvůj obličej oběma rukama.|120",
    "Lehni si na postel a nech ji, ať si na tvůj obličej sedne zády k tvým nohám a opře se rukama o tvůj hrudník.|120",
    "Lízej jí stydké pysky, ale klitorisu se vyhni, dokud tě o to dvakrát nepoprosí.",
    "Olízni ji jednou pořádně od spodu až nahoru a hned ji polib na rty.",
    "Líbej a saj jí bradavky, zatímco ji palcem pomalu hladíš po klitorisu.|90",
    "Lízej ji a přitom se jí prsty druhé ruky dotýkej rtů – ať je olizuje.|90",
    "Postav se s ní u okna se zataženými závěsy, klekni si a lízej ji, zatímco se opírá o parapet.|90",
    "Lízej ji a zpívej jí do klína – jakoukoli písničku, hlavně ať to vibruje.|30",
    "Lízej ji tak dlouho, dokud nebude mít orgasmus. Bez časového limitu, bez přestávky.",
    "Nech ji ležet na břiše s polštářem pod boky a lízej ji zezadu.|120",
  ],

  // Úkoly pro ženu – pro potěšení muže
  female: [
    "Klekni si před něj v kuchyni, stáhni mu kalhoty a pomalu ho olizuj od kořene až ke špičce.|120",
    "Nech ho sedět na gauči, klekni si mezi jeho nohy a kouři mu. On ti smí jen hladit vlasy.|180",
    "Olizuj mu varlata a přitom ho rukou hlaď po penisu.|90",
    "Kouři mu a zároveň mu vibrátorem masíruj hráz.|120",
    "Zavaž mu oči a kouři mu. Pokaždé, když zasténá, změň rytmus.|120",
    "Vezmi do pusy jen špičku a jazykem kolem ní kresli kolečka.|60",
    "Nech ho stát opřeného o zeď v chodbě a klekni si před něj.|120",
    "Kouři mu tak pomalu, jak jen dokážeš. Kdyby tě chtěl popohnat, zpomal ještě víc.|120",
    "Olízni ho přes boxerky, dokud nejsou mokré. Pak je stáhni a pokračuj.|90",
    "69 na boku – oba ležíte na posteli a lížete se navzájem. Ty se soustřeď hlavně na něj.|180",
    "Posaď ho na jídelní židli, klekni si mezi jeho nohy a kouři mu, zatímco se drží sedáku.|120",
    "Líbej ho po vnitřní straně stehen až k varlatům, pak zpátky a znovu. Až na třetí pokus ho vezmi do pusy.",
    "Ve sprše si klekni před něj a kouři mu pod tekoucí vodou.|90",
    "Nech ho ležet na zádech a olizuj ho jen jazykem, bez rtů. Pomalými tahy.|90",
    "Dej si na jazyk kapku šlehačky, medu nebo čokolády a olízni ji z jeho penisu.",
    "Kouři mu a oběma rukama mu přitom hlaď bradavky.|120",
    "Posaď ho na okraj postele, klekni si na zem a kouři mu, zatímco se ti dívá do očí.|120",
    "Vezmi ho do pusy a nehýbej se. Ať se hýbe on – pomalu a opatrně.|60",
    "Střídej: 10 vteřin rychle rukou, 10 vteřin pomalu pusou.|120",
    "Lehni si na záda na posteli s hlavou přes okraj. On stojí u postele a ty mu kouříš – tempo řídíš rukama na jeho bocích.|120",
    "Kouři mu a přitom mu jemně masíruj varlata.|120",
    "Nech ho sedět na pračce nebo o ni opřeného, klekni si a kouři mu.|90",
    "Lízej mu jen uzdičku pod špičkou – rychlými krátkými tahy.|60",
    "Vezmi jedno varle do pusy a jemně ho saj. Pak druhé.|60",
    "Kouři mu a mezitím si sama přikládej vibrátor mezi nohy.|120",
    "Pusou ho vezmi co nejhlouběji, jak ti je příjemné, a pomalu vyjeď až ke špičce.|90",
    "Nech ho ležet na gauči a lehni si mu mezi nohy. Olizuj ho, jako by to byla zmrzlina.|90",
    "Kouři mu a vždy, když se blíží vrchol, přestaň a polib ho na stehno. Třikrát, pak ho nech dojít.",
    "Foukni mu jemně na špičku, olízni ji a znovu foukni.|60",
    "Klekni si před něj v koupelně před zrcadlem, ať se může dívat ze dvou stran.|120",
    "Kouři mu, dokud se neudělá. Kam, to si domluvte předem.",
    "69 – ty nahoře. Kdo dřív přestane, plní ještě jeden úkol navíc.|180",
    "Přejeď mu pírkem po penisu a hned po stejné dráze jazykem. Pírko, jazyk, pírko, jazyk.|90",
    "Olizuj mu hráz a přitom ho rukou hlaď po penisu.|90",
    "Kouři mu s vibrátorem přiloženým na jeho varlatech.|120",
    "Nech ho, ať ti drží vlasy v culíku a jemně určuje tempo.|120",
    "Pomalu mu olizuj celou délku ze všech stran – nahoře, dole, po bocích.|90",
    "Zavaž mu oči, ruce mu dej za hlavu. Kouři mu a on se nesmí pohnout.|120",
    "Lehni si na záda na koberec v obýváku a nech ho, ať si nad tebou klekne. Ty ho vedeš rukama.|120",
    "Líbej ho přes boxerky a přitom mu je pomalu stahuj zuby.",
    "Kresli mu jazykem kolečka kolem špičky po směru hodin, pak proti. Zeptej se, co je lepší, a u toho zůstaň.|90",
    "Nech ho sedět na okraji vany a kouři mu, zatímco na vás teče sprcha.|90",
    "Olizuj mu bradavky tak dlouho, dokud nezačne tlačit tvou hlavu níž. Pak sjeď jazykem až dolů.",
    "Kouři mu a přitom mu prstem s lubrikantem jemně hlaď kolem zadečku (bez vnikání).|90",
    "Posaď ho do křesla s nohama od sebe a kouři mu v klidu, jako by byl čas neomezený.|180",
    "Kouři mu a přitom mu rukou zakruť kolem kořene při každém pohybu dolů.|90",
    "Lízej ho a nech ho, ať ti přitom říká, co přesně chce.|120",
    "Vibrátor na špičku penisu, tvůj jazyk na varlatech.|90",
    "Vezmi ho do pusy a bzuč – hlasivky budou vibrovat.|30",
    "Líbej ho po celém těle a vždy to skonči na penisu. Pětkrát.",
    "Kouři mu, zatímco on leží na gauči s hlavou na polštáři a sleduje tě.|120",
    "Nech ho klečet na posteli, lehni si pod něj na záda hlavou mezi jeho nohy a olizuj mu varlata.|90",
    "Kouři mu a přitom mu jemně stiskni bradavku pokaždé, když vyjedeš až ke špičce.|90",
    "Nech ho stát u linky, klekni si a pomalu mu olizuj penis, zatímco se drží linky oběma rukama.|120",
    "Dej si kostku ledu do pusy na pár vteřin, vyplivni ji a hned ho vezmi studenými ústy.",
    "Nech ho, ať si sám drží penis a vede ho po tvých rtech a jazyku.|60",
    "Klekni si před něj, když stojí u dveří ložnice, a kouři mu.|90",
    "Kouři mu a přitom mu druhým vibrátorem masíruj bradavky.|120",
    "Kouři mu tak, jak by sis přála, aby lízal on tebe – vášnivě a bez spěchu.|120",
    "Olízni ho a hned ho polib na rty. Střídej to.|90",
    "Nech ho ležet na zádech se zvednutými koleny a olizuj mu varlata a hráz.|90",
    "Kouři mu a dívej se mu přitom do očí.|90",
    "Olízni mu vnitřní stranu stehen zdola nahoru – a u varlat se zastav a foukni.",
    "Kouři mu a vždy po 20 vteřinách ho polib na podbřišek. Opakuj.|120",
    "Posaď ho na jídelní stůl a sedni si na židli mezi jeho nohy jako k večeři.|180",
    "Rychle ho jazykem pleskej po špičce, pak ho pomalu vezmi celého do pusy.|60",
    "Nech ho stát ve sprše a klekni si před něj. Pod vodou mu pomalu olizuj varlata a penis.|90",
    "69 vleže na gauči. On dole, ty nahoře. Pomalu ho kouři a on tě hladí po zadečku.|180",
    "Kouři mu a nesmíš použít ruce. Ruce drž za zády.|120",
    "Olizuj ho jen samotnou špičkou jazyka, sotva znatelně.|90",
    "Kousni ho jemně do vnitřní strany stehna a pak ho hned vezmi do pusy.",
    "Kouři mu a mezi každým pohybem mu řekni, jak se ti líbí.|90",
    "Lehni si na postel a nech ho, ať si klekne obkročmo nad tvou hrudí. Kouři mu, zatímco ti hladí vlasy.|120",
    "Kouři mu a rukou mu jemně stahuj kůži u kořene dolů, ať je citlivější.|90",
    "Dej mu na špičku kapku lubrikantu s příchutí nebo medu a olízni ho do čista.",
    "Klekni si na podlahu v obýváku, on sedí na gauči. Kouři mu, dokud nebude sténat nahlas.",
    "Kouři mu, zatímco si on sám drží vibrátor na varlatech.|120",
    "Nech ho sedět na posteli opřeného o čelo a kouři mu. Ruce mu polož na své vlasy.|120",
    "Líbej ho, olizuj, saj – každou minutu změň techniku.|180",
    "Zeptej se ho, jak se mu to líbí nejvíc, a přesně tak mu kouři.|120",
    "Nech ho klečet na gauči opřeného o opěradlo, vklouzni pod něj a olizuj ho zespodu.|90",
    "Kouři mu a jakmile se udělá, pokračuj velmi jemně, dokud tě neodtáhne.",
    "Olizuj mu bradavky a sjížděj níž – s každým kolečkem o kousek.|90",
    "Rukou ho hlaď a pusou saj jen špičku. Pak si to prohoďte: pusa dole, ruka nahoře.|120",
    "Kouři mu a přitom si prsty hlaď bradavky, ať se může dívat.|90",
    "Nech ho sedět na kuchyňské židli, polib ho na špičku a pak se dlouho věnuj jen varlatům. Pak zpátky nahoru.|120",
    "Kouři mu a přitom ho jemně pleskej po stehně v rytmu.|60",
    "Nech ho, ať ti drží tvář oběma rukama, zatímco mu kouříš.|120",
    "Olizuj mu varlata, ale penisu se vyhni, dokud tě o to dvakrát nepoprosí.",
    "Olízni ho jednou pořádně od kořene až po špičku a hned ho polib na rty.",
    "Saj mu bradavky a přitom ho palcem hlaď po uzdičce.|90",
    "Kouři mu a prsty druhé ruky se mu dotýkej rtů – ať je olizuje.|90",
    "Opři ho o parapet okna se zataženými závěsy, klekni si a kouři mu.|90",
    "Vezmi ho do pusy a zpívej – jakoukoli písničku, hlavně ať to vibruje.|30",
    "Kouři mu tak dlouho, dokud se neudělá. Bez časového limitu.",
    "Nech ho ležet na břiše s polštářem pod boky, roztáhni mu nohy a olizuj mu varlata zezadu.|90",
    "Klekni si mezi jeho nohy, prsy mu sevři penis a špičku olizuj.|90",
    "Kouři mu na posteli, zatímco on leží a ty klečíš bokem – ať vidí tvůj zadeček a může tě hladit.|120",
    "Nech ho stát, klekni si a olizuj ho bez rukou. Ruce mu dej na zadek a přitahuj si ho.|90",
    "Kouři mu rychle a hluboko, pak úplně pomalu jen špičku. Střídej po 15 vteřinách.|120",
    "Obkroč ho do 69 a olizuj ho, zatímco ti on hladí zadeček prsty. Lízat tě zatím nesmí.|120",
    "Vezmi oba vibrátory, jeden mu dej na varlata, druhý na hráz, a olizuj mu špičku.|90",
    "Nech ho stát nahého ve sprše a pomalu ho olizuj od kolen nahoru přes stehna až k penisu.|90",
    "Kouři mu a přitom si mezi nohy sama přikládej jeho ruku.|120",
    "Líbej a olizuj mu třísla a podbřišek, ale penis jen hlaď rukou.|60",
    "Posaď se na zem v kuchyni zády ke skříňce, on stojí před tebou. Kouři mu, tempo určuješ rukama na jeho bocích.|120",
    "Kouři mu a vždy, když zasténá, na vteřinu přestaň a usměj se na něj.|90",
    "Vezmi mu varlata do dlaně a pomalu je masíruj, zatímco saješ špičku.|90",
    "Nech ho ležet na posteli a olizuj ho zboku, hlavu mu polož na své stehno.|120",
    "Kouři mu v kombinaci s rukou namazanou lubrikantem – ruka i pusa jedou spolu.|120",
    "Olizuj ho a mezitím mu šeptej, co s ním budeš dělat v další úrovni.|60",
    "Klekni si nahá před gauč, on sedí. Kouři mu a on smí sledovat jen tvoje oči.|120",
  ],
});
