// Kategorie 3 – Orální hrátky (dávka d)
// Témata: škádlení a odpírání, edging ústy, kombinace s pomůckami, počítané výzvy.
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 3,

  male: [
    "Na hranu a zpátky: Doveď ji ústy těsně k vrcholu, přestaň a počkej půl minuty. Cíl: třikrát na hranu a teprve počtvrté ji nechat dojít.|300|oral_klek",
    "Škádlení kolem: Celé tři minuty lížej všude kolem, jen ne tam, kde to chce. Cíl: ať tě sama nasměruje.|180|oral_klek",
    "Musí poprosit: Lízej ji jen tehdy, když tě o to nahlas poprosí. Jinak jen čekáš. Cíl: pět minut a nezačít ani jednou sám od sebe.|300|oral_klek",
    "Zákaz dojít: Lízej ji a zakaž jí vyvrcholit. Cíl: nepřestat, dokud tě nahlas neodprosí o svolení.|300|oral_klek",
    "Pětkrát na hranu: Doveď ji ústy pětkrát na hranu a pokaždé přestaň. Napošesté ji nech. Cíl: vydržet všech pět.|300|oral_klek",
    "Jazyk a vibrace na bradavce: Lízej ji a zároveň jí drž vibrátor na bradavce. Cíl: pět minut a ani jednou ho nesundat.|300|oral_klek",
    "Vibrátor uvnitř, jazyk venku: Vsuň do ní vibrátor a jazykem jí dráždi klitoris. Cíl: pět minut a obojí ve stejném rytmu.|300|oral_klek",
    "Zezadu jen zvenku: Lízej ji a prstem s lubrikantem jí zezadu krouži kolem, dovnitř nikdy. Cíl: pět minut a tempo řídí ona.|300|oral_klek",
    "Vibrátor si drží sama: Nech ji, ať si vibrátor drží sama, a ty ji lížeš odspodu. Cíl: pět minut a nesáhnout na vibrátor ani jednou.|300|oral_klek",
    "Nikdy neví co: Střídej vibrátor a jazyk po půl minutě. Cíl: deset střídání a pokaždé ji překvapit.|300|oral_klek",
    "Nejdřív ledová: Vezmi si do pusy kostku ledu, olízni ji a pak hned pokračuj horkým jazykem. Cíl: co největší rozdíl.|240|oral_klek",
    "Mokré prsty po břiše: Lízej ji a mezi tím jí mokrými prsty kresli po břiše písmena. Cíl: napsat celé slovo a ať ho uhodne.|240|oral_klek",
    "Bez jediného tření: Dej si na rty trochu lubrikantu a lízej ji tak, aby ses jí vlastně jen klouzal po kůži. Cíl: pět minut a nepřitlačit.|300|oral_klek",
    "Palec na hrázi: Lízej ji a druhou rukou jí palcem dráždi hráz. Cíl: pět minut a obojí ve stejném tempu.|300|oral_klek",
    "Počítá hrany: Lízej ji a nech ji nahlas počítat, kolikrát se dostane na hranu. Cíl: dojít aspoň ke čtyřem, než ji necháš dojít.|300|oral_klek",
    "Deset minut bez konce: Lízej ji střídavě rychle a pomalu, ale nesmíš ji nechat dojít, dokud čas neuběhne. Cíl: udržet ji na hraně.|300|oral_klek",
    "Prosím stojí deset vteřin: Lízej ji, ale pokaždé, když řekne prosím, na deset vteřin přestaneš. Cíl: pět minut a pravidlo dodržet do jedné.|300|oral_klek",
    "Popis místo prosby: Oznam jí, že smí dojít, jen když ti přesně popíše, co cítí. Cíl: nepolevit, dokud to neřekne celou větou.|300|oral_klek",
    "Známkování: Lízej ji a nech ji průběžně známkovat od jedné do desíti. Cíl: pět minut a ani jednou neklesnout pod osmičku.|300|oral_klek",
    "Ona diriguje: Nech ji, ať ti nahlas říká, co má dělat tvůj jazyk, a ty jen plníš. Cíl: pět minut a ani jednou si nedělat po svém.|300|oral_klek",
    "Hlas na povel: Lízej ji, ale musí nahlas říkat, co cítí. Kdykoli ztichne, přestaneš a čekáš. Cíl: pět minut a nejvýš tři pauzy.|300|oral_klek",
    "Nesmí si pomoct: Lízej ji a druhou rukou jí drž obě ruce, aby si nemohla pomoct sama. Cíl: pět minut a nepustit ji.|300|oral_klek",
    "Prsty ven v pravou chvíli: Vsuň jí dva prsty a lízej ji, ale kdykoli se blíží, ruku vytáhneš. Cíl: třikrát ji takhle zastavit.|300|oral_klek",
    "Minuta s roztaženýma nohama: Nech ji ležet s roztaženýma nohama a jen se dívej. Cíl: nedotknout se jí dřív než po celé minutě.|120|oral_klek",
    "Až tě přitáhne: Lízej ji pomalu a stejným tempem. Cíl: nezrychlit, dokud ti sama netlačí hlavu k sobě.|300|oral_klek",
    "Tři minuty ticha: Lízej ji tři minuty a ani jeden z vás nesmí vydat hlásku. Cíl: úplné ticho.|180|oral_klek",
    "Až budou promočené: Lízej ji přes tenké kalhotky. Cíl: nesundat jí je, dokud nebudou úplně mokré.|240|oral_klek",
    "Dostane to druhé: Nech ji vybrat mezi jazykem a prsty a pak jí dej přesně to, co si nevybrala. Cíl: čtyři minuty a nepolevit.|240|oral_klek",
    "Vibrace na stehně: Lízej ji a zároveň jí přikládej vibrátor na vnitřní stranu stehna. Cíl: pět minut a ani jednou s ním nesjet výš.|300|oral_klek",
    "Každý jinam: Dej jí vibrátor, ať si ho přiloží kam chce, a ty lížeš vždycky někde jinde. Cíl: pět minut a nikdy se netrefit na stejné místo.|300|oral_klek",
    "Dvě pomůcky: Vibrátor na bradavce, druhý na klitorisu a ty lížeš dovnitř. Cíl: udržet obě na místě.|300|oral_klek",
    "Pohyb znamená zpomalit: Lízej ji a pokaždé, když pohne boky, zpomalíš. Cíl: pět minut a pravidlo dodržet do jedné.|300|oral_klek",
    "Ruce za hlavou: Nech ji ležet s rukama za hlavou. Jakmile je sundá, přestáváš. Cíl: pět minut a nejvýš jedno přerušení.|300|oral_klek",
    "Ještě chvíli počkat: Lízej ji tak dlouho, dokud nezačne prosit. Cíl: po první prosbě vydržet ještě celou minutu.|300|oral_klek",
    "Až na tvoje slovo: Oznam jí, že smí dojít až na tvoje svolení, a dej jí ho co nejpozději. Cíl: vydržet aspoň pět minut.|300|oral_klek",
    "Pomalé odpočítávání: Řekni jí, že za tři minuty skončíš, a nahlas počítej poslední minutu. Cíl: dotáhnout to přesně na nulu.|180|oral_klek",
    "Vibrátor u hráze: Lízej ji a druhou rukou jí drž vibrátor zezadu u hráze. Cíl: pět minut a ani jednou ho neodložit.|300|oral_klek",
    "Neví, kdy konec: Zavaž jí oči a lízej ji v nepravidelných intervalech. Cíl: pět minut, při kterých nikdy neodhadne, kdy přestaneš.|300|oral_klek",
    "Od klína k prstům: Lízej ji a mezi tím jí vždycky olízni prsty u nohou. Cíl: deset střídání a nohu pokaždé vyměnit.|300|oral_klek",
    "Přitlačí, když chce: Polož si její ruku do vlasů a nech ji přitlačit, kdykoli chce víc. Cíl: pět minut a reagovat na každé přitlačení.|300|oral_klek",
    "Tři pokusy: Ona má tři pokusy říct správné slovo, kterým tě zrychlí. Jinak zůstáváš pomalý. Cíl: ať to uhodne.|300|oral_klek",
    "Otevře oči, přestáváš: Lízej ji a pokaždé, když otevře oči, přestaneš. Cíl: pět minut a nejvýš dvě přerušení.|300|oral_klek",
    "Led jako časomíra: Dej jí do ruky kostku ledu a lízej ji. Cíl: smí dojít, až led v dlani úplně roztaje – dřív ne.|300|oral_klek",
    "Odpočítává si to sama: Lízej ji a nech ji nahlas říkat, kolik vteřin ještě vydrží. Cíl: pokaždé, když řekne číslo, o pět vteřin ho přidat.|300|oral_klek",
    "Řekni jí, ať se nesmí ani jednou dotknout tvojí hlavy.|300|oral_klek",
    "Zadržený dech: Ona se zhluboka nadechne a ty lížeš, dokud nevydechne. Pak pauza. Pět kol. Cíl: vydržet všech pět.|300|oral_klek",
    "Lízej ji a zároveň jí prsty dráždi bradavky. Obojí naráz.|300|oral_klek",
    "Nech ji mít nohy zkřížené za tvojí hlavou a nepustit tě.|300|nohy_ramena",
    "Lízej ji a mezi tím jí pomalu strkej vibrátor dovnitř.|300|oral_klek",
    "Dej jí lubrikant na prsty a nech ji, ať si sama pomáhá, zatímco ji lížeš.|300|oral_klek",
    "Kdo dřív: Ty ji lížeš a ona se snaží vydržet co nejdéle bez zvuku. Cíl: ať to nevydrží do dvou minut.|120|oral_klek",
    "Lízej ji a druhou rukou jí drž kolena od sebe.|300|oral_klek",
    "Nech ji vybrat, jak dlouho ji budeš lízat. Pak přidej minutu navíc.|300|oral_klek",
    "Lízej ji a mezi tím jí kousej do vnitřní strany stehen.|300|oral_klek",
    "Řekni jí, ať počítá tvoje tahy nahlas. Když se splete, začínáš od nuly.|300|oral_klek",
    "Jazyk a led: Střídej horký jazyk a kostku ledu po dvaceti vteřinách. Cíl: pět střídání za sebou.|240|oral_klek",
    "Lízej ji a pokaždé, když se nadechne zhluboka, přestaneš.|300|oral_klek",
    "Nech ji, ať si sama roztáhne nohy tak, jak to chce.|300|oral_klek",
    "Lízej ji a mezi tím jí přejížděj pírkem po břiše.|300|oral_klek",
    "Dej si vibrátor pod bradu a lízej ji zároveň s ním.|300|oral_klek",
    "Dvojí zdroj: Vibrátor uvnitř a tvůj jazyk venku. Nikdy neuber ani jedno. Cíl: dovést ji tam oběma naráz.|300|oral_klek",
    "Lízej ji a nech ji, ať se drží čela postele. Nesmí pustit.|300|pouta_postel",
    "Řekni jí, že přestaneš, kdykoli se ti bude chtít. A několikrát to udělej.|300|oral_klek",
    "Lízej ji tak, aby se musela úplně odevzdat a nic neřídila.|300|oral_klek",
    "Nech ji ležet nehnutě. Za každý pohyb si připíše minutu navíc.|300|oral_klek",
    "Lízej ji a pak najednou přestaň a chvíli se na ni jen dívej.|240|oral_klek",
    "Čtyři fáze: Škádlení, pomalu, rychle, dokonči. Každá fáze přesně minutu a čtvrt. Cíl: dodržet pořadí.|300|oral_klek",
    "Lízej ji s vibrátorem přiloženým zvenku na jejím podbřišku.|300|oral_klek",
    "Nech ji, ať ti řekne, kdy má přijít konec. A ten okamžik dodrž.|300|oral_klek",
    "Lízej ji a druhou rukou jí drž hlavu, aby se musela dívat.|300|oral_klek",
    "Řekni jí, že když se udělá dřív než za tři minuty, nebude nic dalšího.|180|oral_klek",
    "Vzestup po minutách: Lízej ji první minutu velmi jemně, druhou silněji a třetí naplno. Cíl: nikdy se nevrátit k slabšímu tlaku.|180|oral_klek",
    "Lízej ji a přitom si její nohy obtoč kolem svého krku.|300|nohy_ramena",
    "Nech ji vybrat mezi tím, jestli ji necháš dojít rychle, nebo dlouho škádlit.|300|oral_klek",
    "Lízej ji a mezi tím jí přejeď žínkou po stehnech.|300|oral_klek",
    "Dej jí vibrátor do ruky a řekni, že ho může použít až na tvoje slovo.|300|oral_klek",
    "Lízej ji tak dlouho, dokud ti nezačne škubat stehny.|300|oral_klek",
    "Poslední slovo: Ona musí říct jednu celou větu, aby dostala dovolení. Cíl: ať ji vůbec dokáže složit.|300|oral_klek",
    "Lízej ji a mezi tím jí lehce plácni na vnitřní stranu stehna.|300|oral_klek",
    "Nech ji držet si kolena a ty používej obě ruce i ústa.|300|nohy_ramena",
    "Lízej ji a pokaždé, když řekne tvoje jméno, zrychlíš.|300|oral_klek",
    "Řekni jí, že tahle karta skončí až v okamžiku, kdy se udělá. Bez výjimek.|300|oral_klek",
    "Dvě za sebou: Nech ji dojít a pak pokračuj, dokud nedojde podruhé. Cíl: dvě za sebou bez přestávky.|300|oral_klek",
    "Lízej ji pomalu i po vrcholu, dokud tě sama neodstrčí.|300|oral_klek",
    "Na konec jí polož hlavu na stehno a nech ji vydechnout.|60|oral_klek",
  ],

  female: [
    "Na hranu a zase zpět: Doveď ho ústy těsně k vrcholu, přestaň a počkej půl minuty. Cíl: třikrát na hranu a teprve počtvrté ho nechat dojít.|300|oral_on_vleze",
    "Škádlení kolem: Celé tři minuty olizuj všude kolem, jen ne tam, kde to chce. Cíl: ať tě sám nasměruje.|180|oral_on_vleze",
    "Musí si říct: Kouři mu jen tehdy, když tě o to nahlas poprosí. Jinak jen čekáš. Cíl: pět minut a nezačít ani jednou sama od sebe.|300|oral_on_vleze",
    "Zákaz se udělat: Kouři mu a zakaž mu se udělat. Cíl: nepřestat, dokud tě nahlas neodprosí o svolení.|300|oral_on_vleze",
    "Pětkrát na hranu: Doveď ho ústy pětkrát na hranu a pokaždé přestaň. Napošesté ho nech. Cíl: vydržet všech pět.|300|oral_on_vleze",
    "Vibrace na jeho bradavce: Kouři mu a zároveň mu drž vibrátor na bradavce. Cíl: pět minut a ani jednou ho nesundat.|300|oral_on_vleze",
    "Vibrace dole, jazyk nahoře: Přilož mu vibrátor na varlata a jazykem dráždi špičku. Cíl: pět minut a ani jednou se neprohodit.|300|oral_on_vleze",
    "Hráz jen zvenku: Kouři mu a prstem s lubrikantem mu krouži po hrázi, dovnitř nikdy. Cíl: pět minut a tempo řídí on.|300|oral_on_vleze",
    "Vibrátor si drží sám: Nech ho, ať si vibrátor drží sám, a ty mu kouříš. Cíl: pět minut a nesáhnout na vibrátor ani jednou.|300|oral_on_vleze",
    "Nikdy neuhodne: Střídej vibrátor a jazyk po půl minutě. Cíl: deset střídání a pokaždé ho překvapit.|300|oral_on_vleze",
    "Nejdřív ledová: Vezmi si do pusy kostku ledu, olízni ho a pak hned pokračuj horkým jazykem. Cíl: co největší rozdíl.|240|oral_on_vleze",
    "Písmena na jeho břiše: Kouři mu a mezi tím mu mokrými prsty kresli po břiše písmena. Cíl: napsat celé slovo a ať ho uhodne.|240|oral_on_vleze",
    "Bez tření: Dej si na rty trochu lubrikantu a kuř mu tak, aby ses mu jen klouzala. Cíl: pět minut a nepřitlačit.|300|oral_on_vleze",
    "Palec na jeho hrázi: Kouři mu a druhou rukou mu palcem dráždi hráz. Cíl: pět minut a obojí ve stejném tempu.|300|oral_on_vleze",
    "Počítá si hrany: Kouři mu a nech ho nahlas počítat, kolikrát se dostane na hranu. Cíl: dojít aspoň ke čtyřem, než ho necháš dojít.|300|oral_on_vleze",
    "Deset minut bez konce: Kouři mu střídavě rychle a pomalu, ale nesmíš ho nechat dojít, dokud čas neuběhne. Cíl: udržet ho na hraně.|300|oral_on_vleze",
    "Prosím tě stojí deset vteřin: Kouři mu, ale pokaždé, když řekne prosím, na deset vteřin přestaneš. Cíl: pět minut a pravidlo dodržet.|300|oral_on_vleze",
    "Popsat, ne prosit: Oznam mu, že smí dojít, jen když ti přesně popíše, co cítí. Cíl: nepolevit, dokud to neřekne celou větou.|300|oral_on_vleze",
    "Známky od něj: Kouři mu a nech ho průběžně známkovat od jedné do desíti. Cíl: pět minut a ani jednou neklesnout pod osmičku.|300|oral_on_vleze",
    "On diriguje: Nech ho, ať ti nahlas říká, co má dělat tvůj jazyk, a ty jen plníš. Cíl: pět minut a ani jednou si nedělat po svém.|300|oral_on_vleze",
    "Hlas na povel jemu: Kouři mu, ale musí nahlas říkat, co cítí. Kdykoli ztichne, přestaneš a čekáš. Cíl: pět minut a nejvýš tři pauzy.|300|oral_on_vleze",
    "Nesmí si pomoct sám: Kouři mu a druhou rukou mu drž obě ruce, aby si nemohl pomoct. Cíl: pět minut a nepustit ho.|300|oral_on_vleze",
    "Ruka pryč v pravou chvíli: Kouři mu s rukou u kořene, ale kdykoli se blíží, ruku sundáš. Cíl: třikrát ho takhle zastavit.|300|oral_on_vleze",
    "Minuta čekání pro něj: Nech ho ležet s roztaženýma nohama a jen se dívej. Cíl: nedotknout se ho dřív než po celé minutě.|120|oral_on_vleze",
    "Až tě přitáhne on: Kouři mu pomalu a stejným tempem. Cíl: nezrychlit, dokud ti sám netlačí hlavu k sobě.|300|oral_on_vleze",
    "Tři minuty ticha: Kouři mu tři minuty a ani jeden z vás nesmí vydat hlásku. Cíl: úplné ticho.|180|oral_on_vleze",
    "Promočené trenýrky: Olizuj ho přes tenké trenýrky. Cíl: nesundat mu je, dokud nebudou úplně mokré.|240|oral_on_vleze",
    "Dostane to nevybrané: Nech ho vybrat mezi ústy a rukou a pak mu dej přesně to druhé. Cíl: čtyři minuty a nepolevit.|240|oral_on_vleze",
    "Vibrace na jeho stehně: Kouři mu a zároveň mu přikládej vibrátor na vnitřní stranu stehna. Cíl: pět minut a ani jednou s ním nesjet výš.|300|oral_on_vleze",
    "Každý jinde: Dej mu vibrátor, ať si ho přiloží kam chce, a ty pracuješ vždycky někde jinde. Cíl: pět minut a nikdy se netrefit na stejné místo.|300|oral_on_vleze",
    "Dvě pomůcky: Vibrátor na bradavce, druhý na hrázi a ty ústy nahoře. Cíl: udržet obě na místě.|300|oral_on_vleze",
    "Pohne se, zpomalíš: Kouři mu a pokaždé, když pohne boky, zpomalíš. Cíl: pět minut a pravidlo dodržet do jedné.|300|oral_on_vleze",
    "Jeho ruce za hlavou: Nech ho ležet s rukama za hlavou. Jakmile je sundá, přestáváš. Cíl: pět minut a nejvýš jedno přerušení.|300|oral_on_vleze",
    "Po první prosbě ještě minuta: Kouři mu tak dlouho, dokud nezačne prosit. Cíl: po první prosbě vydržet ještě celou minutu.|300|oral_on_vleze",
    "Až na tvoje svolení: Oznam mu, že se smí udělat až na tvoje svolení, a dej mu ho co nejpozději. Cíl: vydržet aspoň pět minut.|300|oral_on_vleze",
    "Pomalé odpočítávání: Řekni mu, že za tři minuty skončíš, a nahlas počítej poslední minutu. Cíl: dotáhnout to přesně na nulu.|180|oral_on_vleze",
    "Vibrátor u jeho hráze: Kouři mu a druhou rukou mu drž vibrátor zezadu u hráze. Cíl: pět minut a ani jednou ho neodložit.|300|oral_on_vleze",
    "Neví, kdy přestaneš: Zavaž mu oči a kuř mu v nepravidelných intervalech. Cíl: pět minut, při kterých nikdy neodhadne, kdy přestaneš.|300|oral_on_vleze",
    "Od klína k jeho prstům: Kouři mu a mezi tím mu vždycky olízni prsty u nohou. Cíl: deset střídání a nohu pokaždé vyměnit.|300|oral_on_vleze",
    "Dej si jeho ruku do vlasů a nech ho, ať přitlačí, když chce víc.|300|oral_on_vleze",
    "Tři pokusy: On má tři pokusy říct správné slovo, kterým tě zrychlí. Jinak zůstáváš pomalá. Cíl: ať to uhodne.|300|oral_on_vleze",
    "Oči otevřel, konec: Kouři mu a pokaždé, když otevře oči, přestaneš. Cíl: pět minut a nejvýš dvě přerušení.|300|oral_on_vleze",
    "Led v jeho dlani: Dej mu do ruky kostku ledu a kuř mu. Cíl: smí se udělat, až led v dlani úplně roztaje – dřív ne.|300|oral_on_vleze",
    "Kouři mu a nech ho říkat, kolik vteřin ještě vydrží.|300|oral_on_vleze",
    "Řekni mu, ať se nesmí ani jednou dotknout tvojí hlavy.|300|oral_on_vleze",
    "Zadržený dech: On se zhluboka nadechne a ty kouříš, dokud nevydechne. Pak pauza. Pět kol. Cíl: vydržet všech pět.|300|oral_on_vleze",
    "Kouři mu a zároveň mu prsty dráždi bradavky. Obojí naráz.|300|oral_on_vleze",
    "Nech ho mít nohy zkřížené za tvými zády a nepustit tě.|300|oral_on_vleze",
    "Kouři mu a mezi tím mu pomalu přikládej vibrátor k varlatům.|300|oral_on_vleze",
    "Dej mu lubrikant na dlaň a nech ho, ať si sám pomáhá, zatímco mu kouříš.|300|oral_on_vleze",
    "Kdo dřív: Ty mu kouříš a on se snaží vydržet co nejdéle bez zvuku. Cíl: ať to nevydrží do dvou minut.|120|oral_on_vleze",
    "Kouři mu a druhou rukou mu drž kolena od sebe.|300|oral_on_vleze",
    "Nech ho vybrat, jak dlouho mu budeš kouřit. Pak přidej minutu navíc.|300|oral_on_vleze",
    "Kouři mu a mezi tím mu kousej do vnitřní strany stehen.|300|oral_on_vleze",
    "Řekni mu, ať počítá tvoje tahy nahlas. Když se splete, začínáš od nuly.|300|oral_on_vleze",
    "Horko a mráz: Kouři mu a po dvaceti vteřinách vždycky vyměň horký jazyk za kostku ledu. Cíl: pět střídání za sebou bez pauzy.|240|oral_on_vleze",
    "Kouři mu a pokaždé, když se nadechne zhluboka, přestaneš.|300|oral_on_vleze",
    "Nech ho, ať si sám roztáhne nohy tak, jak to chce.|300|oral_on_vleze",
    "Kouři mu a mezi tím mu přejížděj pírkem po břiše.|300|oral_on_vleze",
    "Dej si vibrátor do volné ruky a používej ho zároveň s ústy.|300|oral_on_vleze",
    "Dvojí zdroj: Vibrátor na varlatech a tvoje ústa nahoře. Nikdy neuber ani jedno. Cíl: dovést ho tam oběma naráz.|300|oral_on_vleze",
    "Kouři mu a nech ho, ať se drží čela postele. Nesmí pustit.|300|pouta_postel!",
    "Řekni mu, že přestaneš, kdykoli se ti bude chtít. A několikrát to udělej.|300|oral_on_vleze",
    "Kouři mu tak, aby se musel úplně odevzdat a nic neřídil.|300|oral_on_vleze",
    "Nech ho ležet nehnutě. Za každý pohyb si připíše minutu navíc.|300|oral_on_vleze",
    "Kouři mu a pak najednou přestaň a chvíli se na něj jen dívej.|240|oral_on_vleze",
    "Čtyři díly: Nejdřív škádlení, pak pomalu, pak rychle a nakonec konec. Každý díl minutu a čtvrt. Cíl: dodržet pořadí.|300|oral_on_vleze",
    "Kouři mu s vibrátorem přiloženým zvenku na jeho podbřišku.|300|oral_on_vleze",
    "Nech ho, ať ti řekne, kdy má přijít konec. A ten okamžik dodrž.|300|oral_on_vleze",
    "Kouři mu a druhou rukou mu drž hlavu, aby se musel dívat.|300|oral_on_vleze",
    "Řekni mu, že když se udělá dřív než za tři minuty, nebude nic dalšího.|180|oral_on_vleze",
    "Po minutách nahoru: Kouři mu první minutu úplně jemně, druhou silněji a třetí naplno. Cíl: nikdy se nevrátit k slabšímu tempu.|180|oral_on_vleze",
    "Kouři mu a přitom si jeho nohu opři o rameno.|300|oral_on_vleze",
    "Nech ho vybrat mezi tím, jestli ho necháš dojít rychle, nebo ho budeš dlouho škádlit.|300|oral_on_vleze",
    "Kouři mu a mezi tím mu přejeď žínkou po stehnech.|300|oral_on_vleze",
    "Dej mu vibrátor do ruky a řekni, že ho může použít až na tvoje slovo.|300|oral_on_vleze",
    "Kouři mu tak dlouho, dokud mu nezačnou škubat stehna.|300|oral_on_vleze",
    "Poslední slovo: On musí říct jednu celou větu, aby dostal dovolení. Cíl: ať ji vůbec dokáže složit.|300|oral_on_vleze",
    "Kouři mu a mezi tím mu lehce plácni na vnitřní stranu stehna.|300|oral_on_vleze",
    "Nech ho držet si kolena a ty používej obě ruce i ústa.|300|oral_on_vleze",
    "Kouři mu a pokaždé, když řekne tvoje jméno, zrychlíš.|300|oral_on_vleze",
    "Řekni mu, že tahle karta skončí až v okamžiku, kdy se udělá. Bez výjimek.|300|oral_on_vleze",
    "Hned podruhé: Nech ho dojít a pak pokračuj jemně dál, dokud to snese. Cíl: vydržet u něj i po konci.|300|oral_on_vleze",
    "Kouři mu pomalu i po vrcholu, dokud tě sám neodstrčí.|300|oral_on_vleze",
    "Na konec mu polož hlavu na stehno a nech ho vydechnout.|60|oral_on_vleze",
  ],
});
