// Kategorie 3 – Orální hrátky (dávka e)
// Témata: souboje a hry, špinavé řeči, hodnocení, lehké lízání mezi půlkami, finále.
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 3,

  male: [
    "Souboj o vydržení: Střídejte se po minutě. Kdo první řekne dost, plní další přání. Cíl: vydržet déle.|300|p69",
    "Kostka určí minuty: Hoď kostkou a tolik minut ji lížeš úplně bez přerušení. Cíl: nezastavit se ani na vteřinu.|300|oral_klek",
    "Číslo od ní: Nech ji říct číslo od jedné do desíti a přesně tolik minut zůstaň dole. Cíl: neodejít ani o vteřinu dřív.|300|oral_klek",
    "Každé slovo stojí deset vteřin: Lízej ji a za každé slovo, které řekne, přidáš deset vteřin navíc. Cíl: rozmluvit ji aspoň na minutu navíc.|300|oral_klek",
    "Známka za každý tah: Lízej ji a nech ji každý tah ohodnotit od jedné do pěti. Cíl: pět minut a ani jednou neklesnout pod trojku.|300|oral_klek",
    "Hodnocení nahlas: Ona po každé půlminutě řekne známku jako ve škole. Cíl: dostat jedničku třikrát za sebou.|300|oral_klek",
    "Mluv, nebo končíš: Mluv sprostě, zatímco ji lížeš. Jakmile ztichneš, musíš přestat. Cíl: pět minut a nejvýš dvě pauzy.|300|oral_klek",
    "Popisuj ji nahlas: Lízej ji a mezi tím jí nahlas popisuj, jak chutná a jak vypadá. Cíl: pět různých vět a ani jedna se nesmí opakovat.|300|oral_klek",
    "Věta do stehna: Řekni jí přímo do stehna jednu sprostou větu a hned pokračuj v lízání. Cíl: pět vět a mezi nimi vždy půl minuty.|240|oral_klek",
    "Co bude potom: Lízej ji a mezi tím jí popisuj, co s ní uděláš, až skončíš. Cíl: popsat tři věci, a pak je opravdu udělat.|300|oral_klek",
    "Odpovědi jazykem: Nech ji mluvit sprostě a odpovídej jí výhradně jazykem. Cíl: pět minut a neříct ani jedno slovo.|300|oral_klek",
    "Rozkaz shora: Ona ti shora dává rozkazy a ty je plníš do vteřiny. Cíl: pět minut a nezaváhat ani jednou.|300|oral_klek",
    "Jen zvenku a jazykem: Lízej ji a mezi tím jí lehce olizuj i mezi půlkami – jen zvenku. Cíl: pět minut a tempo řídí ona.|300|na_brise",
    "Celá oblast zezadu: Nech ji ležet na břiše a lízej ji odzadu přes celou tu oblast, hodně jemně. Cíl: pět minut a nepřitlačit ani jednou.|300|na_brise",
    "Zezadu odshora dolů: Nech ji kleknout a opřít se a lízej ji zezadu od kříže až dolů. Cíl: dvacet cest a žádná kratší.|300|zezadu",
    "Jen namazat a nic víc: Lízej ji a druhou rukou jí namaž zadeček lubrikantem. Dovnitř nikdy. Cíl: pět minut a zůstat jen u hlazení.|300|zezadu",
    "Hloubku určuje ona: Vsuň jí namazaný palec zezadu, zatímco ji lížeš. Cíl: pět minut a hloubku ani jednou nezvolit sám.|300|oral_klek",
    "Zezadu a jemně: Lízej ji zezadu, když klečí, a druhou rukou ji dráždi vpředu. Cíl: dělat obojí zároveň.|300|zezadu",
    "Kroužek a výměna: Nasaď si erekční kroužek a nech ji, ať ti kouří. Cíl: po dvou minutách se vyměnit a lízat ji stejně dlouho.|300|p69",
    "Ona ti ho nasadí: Nech ji nasadit ti erekční kroužek a pak ji lízej. Cíl: nepřestat, dokud nedojde.|300|oral_klek",
    "Zepředu i zezadu: Přilož jí vibrátor zezadu, zatímco ji lížeš zepředu. Cíl: pět minut a ani jednou ho neodložit.|300|oral_klek",
    "Prsty do její pusy: Lízej ji a mezi tím jí do pusy strkej svoje prsty, ať je saje. Cíl: pět minut a prsty mít mokré pokaždé, když se vrátí dolů.|300|oral_klek",
    "Drží si to sama: Nech ji, ať si prsty drží stydké pysky od sebe. Cíl: pět minut a nesmí se ani jednou pustit.|300|oral_klek",
    "Zrcadlová hra: Dělej jí jazykem přesně to, co ona předtím dělala tobě. Cíl: zopakovat celé pořadí, aniž bys něco vynechal.|300|oral_klek",
    "Hned po sobě: Nejdřív ji lížeš ty a hned potom kouří ona tobě. Cíl: mezi tím nesmí být ani vteřina pauzy.|300|p69",
    "Kdo je na řadě, mluví: Střídejte se po třiceti vteřinách a kdo zrovna pracuje, musí nahlas mluvit. Cíl: deset kol bez jediného ticha.|300|p69",
    "Kdo první prohrál: Ližte se navzájem naplno. Cíl: kdo se první udělá, plní ještě jeden úkol navíc.|300|p69",
    "Na střídačku: Střídejte se po minutě a nikdo nesmí přijít na řadu dvakrát za sebou. Cíl: pět kol bez jediného přešlapu.|300|p69",
    "Držíš jí boky: Nech ji sedět ti na obličeji a celou dobu jí drž boky oběma rukama. Cíl: pět minut a ani jednou je nepustit.|300|oral_ona_nad_nim",
    "Bradavky si obstará sama: Lízej ji a nech ji, ať si k tomu sama hraje s bradavkami. Cíl: pět minut a nepomáhat jí ani jednou rukou.|300|oral_klek",
    "Ty jen otevřeš pusu: Nech ji klečet nad tvou hlavou a hýbat se samu. Cíl: pět minut, při kterých se ty vůbec nepohneš.|300|oral_ona_nad_nim",
    "Ruka jen položená: Lízej ji a druhou ruku jí polož na krk – jen položit, nikdy netlačit. Cíl: pět minut a kdykoli řekne stop, hned ji sundat.|300|oral_klek",
    "Lehce za vlasy: Lízej ji a mezi tím ji lehce zatahej za vlasy. Cíl: pět zatažení a po každém se zeptat, jestli chce víc.|300|oral_klek",
    "Ruce a vlasy: Ona ti drží hlavu za vlasy a ty děláš přesně to, kam tě dotlačí. Cíl: nechat se vést.|300|oral_klek",
    "Noha nahoru a dolů: Lízej ji a po každé minutě jí přehoď jinou nohu přes rameno. Cíl: pět minut a nohu vystřídat aspoň čtyřikrát.|300|nohy_ramena",
    "Lízej ji s hlavou mezi jejími stehny a rukama na jejích prsou.|300|oral_klek",
    "Nech ji vybrat si tři místa a každému věnuj minutu.|300|oral_klek",
    "Doveď ji ústy až do konce a ani na chvíli nezměň tempo.|300|oral_klek",
    "Až úplně: Doveď ji ústy až za hranu a pokračuj ještě půl minuty potom. Cíl: vydržet i po vrcholu.|300|oral_klek",
    "Lízej ji a mezi tím na ni koukej zdola. Ať to vidí.|300|oral_klek",
    "Nech ji ležet a ty lížeš ze strany. Druhou rukou ji přidržuješ.|300|oral_klek",
    "Nohy na tvých ramenou: Nech ji sednout na kraj postele, dej si její nohy na ramena a lízej ji. Cíl: pět minut a nohy nespustit.|300|oral_vsede",
    "Lízej ji a mezi tím jí přejeď ledem po břiše.|300|oral_klek",
    "Dej si její kalhotky na hlavu jako vtip a pak pokračuj.|240|oral_klek",
    "Dvacet a dvacet: Dvacet vteřin ji lížeš jazykem, dvacet vteřin dráždíš prsty. Cíl: osm kol a nikdy obojí naráz.|300|oral_klek",
    "Lízej ji a nech ji říkat čísla od desíti dolů. Na nule přestaneš.|300|oral_klek",
    "Nech ji, ať ti sama ukáže, kde přesně to chce, a pak tam zůstaň.|300|oral_klek",
    "Lízej ji a druhou rukou jí drž nohy roztažené za kotníky.|300|nohy_ramena",
    "Musí se dívat: Lízej ji a ona se na tebe musí celou dobu dívat dolů. Cíl: pět minut – jakmile zavře oči, přestáváš.|300|oral_klek",
    "Řekni jí, že když vydrží pět minut bez pohybu, dostane, co chce.|300|oral_klek",
    "Nehybná: Ona nesmí pohnout boky. Pokaždé, když to udělá, začínáš od nuly. Cíl: dojet to bez restartu.|300|oral_klek",
    "Lízej ji a mezi tím jí šeptej do stehna, jak ji chceš.|300|oral_klek",
    "Nech ji ležet s polštářem pod boky, ať je výš.|300|misionar_polstar",
    "Ona nedělá nic: Nech ji lehnout si na tebe obráceně a lízej ji, zatímco ona vůbec nic nedělá. Cíl: pět minut a nenechat ji zasáhnout.|300|p69",
    "Lízej ji a nech ji, ať ti stiskne hlavu stehny.|300|nohy_ramena",
    "Kdo víc: Počítejte, kolikrát se jí podlomí dech. Pod pět to nesmí klesnout. Cíl: aspoň pět.|300|oral_klek",
    "Zápěstí v dlani: Lízej ji a druhou rukou jí drž zápěstí přitisknuté k posteli. Cíl: pět minut a ani jednou ho nepustit.|300|oral_klek",
    "Nech ji sedět na židli a dej si její nohy přes opěradlo.|300|oral_zidle",
    "Lízej ji a přitom si sám hraj s sebou. Ale nesmíš dojít.|300|oral_klek",
    "Řekni jí, že tuhle kartu splníš jen tehdy, když bude nahlas prosit.|300|oral_klek",
    "Prosba nahlas: Ona musí třikrát nahlas říct, co přesně chce. Teprve pak to dostane. Cíl: tři jasné věty.|300|oral_klek",
    "Kousnutí mezi tím: Lízej ji zezadu a mezi tím ji vždycky lehce kousni do zadečku. Cíl: deset kousnutí a pokaždé jinam.|300|na_brise",
    "Pomalu klesá: Nech ji kleknout si nad tebe a klesat tak pomalu, jak jen dokáže. Cíl: sestup musí trvat aspoň minutu.|300|oral_ona_nad_nim",
    "Lízej ji tak dlouho, dokud ti nezačne kroutit hlavou mezi stehny.|300|oral_klek",
    "Nech ji vybrat, čím skončíte – jazykem, prsty, nebo obojím.|300|oral_klek",
    "Lízej ji a mezi tím jí drž vibrátor na klitorisu, když se nadechne.|300|oral_klek",
    "Až se udělá dvakrát: Nesmíš přestat, dokud nedojde dvakrát. Mezi tím jen zpomal. Cíl: dvě vlny.|300|oral_klek",
    "Lízej ji a pokaždé, když se pokusí utéct, ji přitáhni zpátky.|300|oral_klek",
    "Nech ji ležet na boku a lízej ji zezadu s rukou vpředu.|300|p69_bok",
    "Lízej ji a mezi tím jí olizuj i tříselné rýhy.|300|oral_klek",
    "Drží si nohy sama: Nech ji, ať si drží nohy sama, a ty používej jazyk i obě ruce. Cíl: pět minut a nesmí je pustit.|300|nohy_ramena",
    "Lízej ji a mezitím jí dej druhou ruku pod zadeček a zvedni ji.|300|nohy_ramena",
    "Bez pomoci: Ona nesmí použít ruce vůbec k ničemu. Ani k držení, ani k tlačení. Cíl: ať to vydrží.|300|oral_klek",
    "Lízej ji a mezi tím jí olizuj i břicho a boky. Nikdy dvakrát za sebou stejně.|300|oral_klek",
    "Nech ji hádat, jestli teď použiješ jazyk, rty, nebo prst.|300|oral_klek",
    "Lízej ji a přitom se snaž nevydat ani hlásku.|300|oral_klek",
    "Opřená rukama za sebou: Nech ji sednout si na tebe a opřít se rukama za sebe, a lízej ji zespodu. Cíl: pět minut a nesmí se předklonit.|300|oral_ona_nad_nim",
    "Lízej ji a mezi tím jí stiskni bradavky mezi prsty.|300|oral_klek",
    "Tempo podle dechu: Lížeš přesně tak rychle, jak rychle dýchá. Když zrychlí, zrychlíš i ty. Cíl: kopírovat ji.|300|oral_klek",
    "Doveď ji ústy až na hranu a pak ji nech dojít prsty.|300|oral_klek",
    "Nech ji, ať ti při tom sedí na obličeji a drží se čela postele.|300|oral_ona_nad_nim",
    "Lízej ji a potom ji hned polib na ústa, ať se ochutná.|240|oral_klek",
    "Kdo první přestane: Ona ti kouří a ty ji mezitím lížeš. Cíl: pět minut – kdo první přestane, plní ještě jeden úkol navíc.|300|p69",
    "Poslední minuta: Poslední minutu už nesmíš nic měnit – jedno tempo, jedno místo. Cíl: dotáhnout to tak, jak je.|60|oral_klek",
    "Lízej ji a mezi tím jí přejeď štětcem po vnitřní straně stehen.|300|oral_klek",
    "Na konci jí polož hlavu na břicho a poslouchej, jak dýchá.|60|oral_klek",
  ],

  female: [
    "Souboj o vydržení: Střídejte se po minutě. Kdo první řekne dost, plní další přání. Cíl: vydržet déle než on.|300|p69",
    "Kostka a minuty: Hoď kostkou a tolik minut mu kouříš úplně bez přerušení. Cíl: nezastavit se ani na vteřinu.|300|oral_on_vleze",
    "Číslo od něj: Nech ho říct číslo od jedné do desíti a přesně tolik minut zůstaň dole. Cíl: neodejít ani o vteřinu dřív.|300|oral_on_vleze",
    "Slovo za deset vteřin: Kouři mu a za každé slovo, které řekne, přidáš deset vteřin navíc. Cíl: rozmluvit ho aspoň na minutu navíc.|300|oral_on_vleze",
    "Známkuje každý tah: Kouři mu a nech ho každý tah ohodnotit od jedné do pěti. Cíl: pět minut a ani jednou neklesnout pod trojku.|300|oral_on_vleze",
    "Známkování: On po každé půlminutě řekne známku jako ve škole. Cíl: dostat jedničku třikrát za sebou.|300|oral_on_vleze",
    "Ticho znamená stop: Mluv sprostě, zatímco mu kouříš. Jakmile ztichneš, musíš přestat. Cíl: pět minut a nejvýš dvě pauzy.|300|oral_on_vleze",
    "Popisuj ho nahlas: Kouři mu a mezi tím mu nahlas popisuj, jak chutná a jak vypadá. Cíl: pět různých vět a ani jedna se nesmí opakovat.|300|oral_on_vleze",
    "Sprostá věta do stehna: Řekni mu přímo do stehna jednu sprostou větu a hned pokračuj. Cíl: pět vět a mezi nimi vždy půl minuty.|240|oral_on_vleze",
    "Plán na potom: Kouři mu a mezi tím mu popisuj, co s ním uděláš, až skončíš. Cíl: popsat tři věci, a pak je opravdu udělat.|300|oral_on_vleze",
    "Odpověď jen jazykem: Nech ho mluvit sprostě a odpovídej mu výhradně jazykem. Cíl: pět minut a neříct ani jedno slovo.|300|oral_on_vleze",
    "Jeho rozkazy: On ti dává rozkazy a ty je plníš do vteřiny. Cíl: pět minut a nezaváhat ani jednou.|300|oral_on_vleze",
    "Hráz mezi tím: Kouři mu a mezi tím mu jazykem přejeď i po hrázi, hodně jemně. Cíl: deset střídání a nikdy dvě stejná za sebou.|300|oral_on_vleze",
    "Zezadu a jemně: Nech ho ležet na břiše a olizuj mu zadek a hráz zezadu, hodně jemně. Cíl: pět minut a nepřitlačit ani jednou.|300|na_brise!",
    "Odshora dolů zezadu: Nech ho kleknout a opřít se a olizuj ho zezadu od kříže až dolů. Cíl: dvacet cest a žádná kratší.|300|zezadu!",
    "Namazat a zůstat: Kouři mu a druhou rukou mu namaž hráz lubrikantem. Dovnitř nikdy. Cíl: pět minut a zůstat jen u hlazení.|300|oral_on_vleze",
    "Hloubku určuje on: Vsuň mu namazaný palec zezadu, zatímco mu kouříš. Cíl: pět minut a hloubku ani jednou nezvolit sama.|300|oral_on_vleze",
    "Zezadu a jemně: Olizuj ho zezadu, když klečí, a druhou rukou ho dráždi vpředu. Cíl: dělat obojí zároveň.|300|zezadu!",
    "Kroužek a výdrž: Nasaď mu erekční kroužek a kuř mu. Cíl: nepřestat, dokud tě sám nezastaví.|300|oral_on_vleze",
    "Nasadí si ho sám: Nech ho, ať si nasadí erekční kroužek, a kuř mu. Cíl: nepřestat, dokud se neudělá.|300|oral_on_vleze",
    "Vibrace zespodu: Přilož mu vibrátor na hráz, zatímco mu kouříš. Cíl: pět minut a ani jednou ho neodložit.|300|oral_on_vleze",
    "Prsty do jeho pusy: Kouři mu a mezi tím mu do pusy strkej svoje prsty, ať je saje. Cíl: pět minut a prsty mít mokré pokaždé, když se vrátí dolů.|300|oral_on_vleze",
    "Drží si ho sám: Nech ho, ať si ho sám drží u kořene. Cíl: pět minut a nesmí se ani jednou pustit.|300|oral_on_vleze",
    "Zrcadlo z minula: Dělej mu jazykem přesně to, co on předtím dělal tobě. Cíl: zopakovat celé pořadí, aniž bys něco vynechala.|300|oral_on_vleze",
    "Jeden po druhém: Nejdřív mu kouříš ty a hned potom on lížeš tobě. Cíl: mezi tím nesmí být ani vteřina pauzy.|300|p69",
    "Mluví jen ten na řadě: Střídejte se po třiceti vteřinách a kdo zrovna pracuje, musí nahlas mluvit. Cíl: deset kol bez jediného ticha.|300|p69",
    "Kdo to nevydrží: Užívejte si navzájem naplno. Cíl: kdo se první udělá, plní ještě jeden úkol navíc.|300|p69",
    "Minutu ty, minutu on: Střídáte se po minutě a nikdo nesmí přijít na řadu dvakrát za sebou. Cíl: pět kol bez jediného přešlapu.|300|p69",
    "Drží tě za boky: Sedni si mu na obličej a nech se od něj celou dobu držet za boky. Cíl: pět minut a ani jednou tě nesmí pustit.|300|oral_ona_nad_nim",
    "Jeho ruce na tvých prsou: Kouři mu a nech ho, ať si k tomu hraje s tvými prsy. Cíl: pět minut a ani jednou mu ruce neodstrčit.|300|oral_on_vleze",
    "On jen otevře pusu: Klekni si mu nad hlavu a hýbej se sama. Cíl: pět minut, při kterých se on vůbec nepohne.|300|oral_ona_nad_nim",
    "Dlaň na jeho krku: Kouři mu a druhou ruku mu polož na krk – jen položit, nikdy netlačit. Cíl: pět minut a na stop ji hned sundat.|300|oral_on_vleze",
    "Nech ho tahat tě přitom lehce za vlasy a řekni, jestli se ti to líbí.|300|oral_on_vleze",
    "Ruce a vlasy: On ti drží hlavu za vlasy a ty děláš přesně to, kam tě dotlačí. Cíl: nechat se vést.|300|oral_on_vleze",
    "Kouři mu a mezi tím si dej jeho nohu na rameno.|300|oral_on_vleze",
    "Kouři mu s hlavou mezi jeho stehny a rukama na jeho hrudníku.|300|oral_on_vleze",
    "Nech ho vybrat si tři místa a každému věnuj minutu.|300|oral_on_vleze",
    "Doveď ho ústy až do konce a ani na chvíli nezměň tempo.|300|oral_on_vleze",
    "Až úplně: Doveď ho ústy až za hranu a pokračuj ještě půl minuty potom. Cíl: vydržet i po konci.|300|oral_on_vleze",
    "Kouři mu a mezi tím na něj koukej zdola. Ať to vidí.|300|oral_on_vleze",
    "Nech ho ležet a kouři mu ze strany. Druhou rukou ho přidržuješ.|300|oral_on_vleze",
    "Mezi jeho koleny: Nech ho sednout na kraj postele, klekni si mu mezi kolena a kuř mu. Cíl: pět minut a ani jednou se nezvednout.|300|oral_on_vsede",
    "Kouři mu a mezi tím mu přejeď ledem po břiše.|300|oral_on_vleze",
    "Dej si jeho tričko přes hlavu jako vtip a pak pokračuj.|240|oral_on_vleze",
    "Jazyk a ruka po dvaceti: Dvacet vteřin jazykem, dvacet vteřin rukou. Cíl: osm kol a nikdy obojí naráz.|300|oral_on_vleze",
    "Kouři mu a nech ho říkat čísla od desíti dolů. Na nule přestaneš.|300|oral_on_vleze",
    "Nech ho, ať ti sám ukáže, jak přesně to chce, a pak to tak dělej.|300|oral_on_vleze",
    "Kouři mu a druhou rukou mu drž nohy roztažené za kotníky.|300|oral_on_vleze",
    "Ať tě celou dobu sleduje shora a nezavře oči ani na vteřinu.|300|oral_on_vleze",
    "Řekni mu, že když vydrží pět minut bez pohybu, dostane, co chce.|300|oral_on_vleze",
    "Nehybný: On nesmí pohnout boky. Pokaždé, když to udělá, začínáš od nuly. Cíl: dojet to bez restartu.|300|oral_on_vleze",
    "Kouři mu a mezi tím mu šeptej do stehna, jak ho chceš.|300|oral_on_vleze",
    "Nech ho ležet s polštářem pod boky, ať je výš.|300|misionar_polstar",
    "Lehni si na něj obráceně a nech ho, ať nic nedělá. Pracuješ jen ty.|300|p69",
    "Kouři mu a nech ho, ať ti stiskne hlavu stehny.|300|oral_on_vleze",
    "Kdo víc: Počítejte, kolikrát se mu podlomí dech. Pod pět to nesmí klesnout. Cíl: aspoň pět.|300|oral_on_vleze",
    "Jeho zápěstí v dlani: Kouři mu a druhou rukou mu drž zápěstí přitisknuté k posteli. Cíl: pět minut a ani jednou ho nepustit.|300|oral_on_vleze",
    "Nech ho sedět na židli a dej si jeho nohy přes opěradlo.|300|oral_zidle",
    "Kouři mu a přitom si sama hraj se sebou. Ale nesmíš dojít.|300|oral_on_vleze",
    "Řekni mu, že tuhle kartu splníš jen tehdy, když bude nahlas prosit.|300|oral_on_vleze",
    "Prosba nahlas: On musí třikrát nahlas říct, co přesně chce. Teprve pak to dostane. Cíl: tři jasné věty.|300|oral_on_vleze",
    "Kousni ho mezi tím: Olizuj ho zezadu a mezi tím ho vždycky lehce kousni do zadku. Cíl: deset kousnutí a pokaždé jinam.|300|na_brise!",
    "Klesáš pomalu: Klekni si nad něj a klesej tak pomalu, jak jen dokážeš. Cíl: sestup musí trvat aspoň minutu.|300|oral_ona_nad_nim",
    "Kouři mu tak dlouho, dokud tě nezačne tlačit hlouběji.|300|oral_on_vleze",
    "Nech ho vybrat, čím skončíte – ústy, rukou, nebo obojím.|300|oral_on_vleze",
    "Kouři mu a mezi tím mu drž vibrátor na varlatech, když se nadechne.|300|oral_on_vleze",
    "Až na konec a dál: Nesmíš přestat, dokud se neudělá, a pak ještě chvíli jemně pokračuj. Cíl: vydržet i potom.|300|oral_on_vleze",
    "Kouři mu a pokaždé, když se pokusí utéct, ho přitáhni zpátky.|300|oral_on_vleze",
    "Nech ho ležet na boku a olizuj ho zezadu s rukou vpředu.|300|p69_bok",
    "Kouři mu a mezi tím mu olizuj i tříselné rýhy.|300|oral_on_vleze",
    "Drží si nohy sám: Nech ho, ať si drží nohy sám, a ty používej jazyk i obě ruce. Cíl: pět minut a nesmí je pustit.|300|oral_on_vleze",
    "Kouři mu a mezitím mu dej druhou ruku pod zadek a zvedni ho.|300|oral_on_vleze",
    "Bez pomoci: On nesmí použít ruce vůbec k ničemu. Ani k držení, ani k tlačení. Cíl: ať to vydrží.|300|oral_on_vleze",
    "Kouři mu a mezi tím mu olizuj i břicho a boky. Nikdy dvakrát za sebou stejně.|300|oral_on_vleze",
    "Nech ho hádat, jestli teď použiješ jazyk, rty, nebo ruku.|300|oral_on_vleze",
    "Kouři mu a přitom se snaž nevydat ani hlásku.|300|oral_on_vleze",
    "Opřená za sebou: Sedni si mu na obličej a opři se rukama za sebe. Cíl: pět minut a ani jednou se nepředklonit.|300|oral_ona_nad_nim",
    "Kouři mu a mezi tím mu stiskni bradavky mezi prsty.|300|oral_on_vleze",
    "Tempo podle dechu: Kouříš přesně tak rychle, jak rychle dýchá. Když zrychlí, zrychlíš i ty. Cíl: kopírovat ho.|300|oral_on_vleze",
    "Doveď ho ústy až na hranu a pak ho nech dojít rukou.|300|oral_on_vleze",
    "Čelo postele v rukou: Sedni si mu na obličej a drž se přitom čela postele. Cíl: pět minut a ani jednou se nepustit.|300|oral_ona_nad_nim",
    "Kouření a polibek: Kouři mu a pak ho hned polib na ústa, bez jediné pauzy. Cíl: pět takových střídání za sebou.|240|oral_on_vleze",
    "Kdo z vás dřív: On tě líže a ty mu mezitím kouříš. Cíl: pět minut – kdo první přestane, plní ještě jeden úkol navíc.|300|p69",
    "Závěr bez změn: V poslední minutě zůstaň u jednoho tempa a jednoho místa. Cíl: dotáhnout to tak, jak je.|60|oral_on_vleze",
    "Kouři mu a mezi tím mu přejeď štětcem po vnitřní straně stehen.|300|oral_on_vleze",
    "Na konci mu polož hlavu na břicho a poslouchej, jak dýchá.|60|oral_on_vleze",
  ],
});
