// Kategorie 3 – Orální hrátky (dávka d)
// Témata: škádlení a odpírání, edging ústy, kombinace s pomůckami, počítané výzvy.
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 3,

  male: [
    "Doveď ji ústy až těsně k vrcholu a přestaň. Počkej půl minuty. Pak znovu.|300|oral_klek",
    "Škádlení kolem: Celé tři minuty lížej všude kolem, jen ne tam, kde to chce. Cíl: ať tě sama nasměruje.|180|oral_klek",
    "Lízej ji jen tehdy, když tě o to nahlas poprosí. Jinak čekáš.|300|oral_klek",
    "Zakaž jí dojít. Lízej ji tak dlouho, dokud to nebude muset říct nahlas.|300|oral_klek",
    "Pětkrát na hranu: Doveď ji ústy pětkrát na hranu a pokaždé přestaň. Napošesté ji nech. Cíl: vydržet všech pět.|300|oral_klek",
    "Lízej ji a zároveň jí drž vibrátor na bradavce.|300|oral_klek",
    "Vsuň do ní vibrátor a jazykem dráždi klitoris.|300|oral_klek",
    "Lízej ji a přitom jí prsty dráždi zezadu. Jen zvenku a s lubrikantem.|300|oral_klek",
    "Nech ji držet si vibrátor sama a ty ji lížeš odspodu.|300|oral_klek",
    "Střídej vibrátor a jazyk po půl minutě. Ona nesmí vědět, co přijde.|300|oral_klek",
    "Nejdřív ledová: Vezmi si do pusy kostku ledu, olízni ji a pak hned pokračuj horkým jazykem. Cíl: co největší rozdíl.|240|oral_klek",
    "Lízej ji a mezi tím jí mokrými prsty kresli po břiše.|240|oral_klek",
    "Dej si na rty trochu lubrikantu a lízej ji úplně bez tření.|300|oral_klek",
    "Lízej ji a druhou rukou jí dráždi hráz palcem.|300|oral_klek",
    "Nech ji počítat, kolikrát se dostane na hranu. Ty rozhoduješ, kdy ji necháš.|300|oral_klek",
    "Deset minut bez konce: Lízej ji střídavě rychle a pomalu, ale nesmíš ji nechat dojít, dokud čas neuběhne. Cíl: udržet ji na hraně.|300|oral_klek",
    "Lízej ji a pokaždé, když řekne prosím, na deset vteřin přestaneš.|300|oral_klek",
    "Řekni jí, že ji necháš dojít jen tehdy, když ti přesně popíše, co cítí.|300|oral_klek",
    "Lízej ji a nech ji hodnotit od jedné do desíti. Pod osmičku nesmíš klesnout.|300|oral_klek",
    "Nech ji, ať ti nahlas říká, co má dělat tvůj jazyk. Ty jen plníš.|300|oral_klek",
    "Hlas na povel: Ona musí nahlas říkat, co cítí. Kdykoli ztichne, přestaneš a čekáš. Cíl: ať nezmlkne ani na chvíli.|300|oral_klek",
    "Lízej ji a druhou rukou jí drž ruce, ať si nemůže pomoct sama.|300|oral_klek",
    "Vsuň jí dva prsty a lízej ji, ale pokaždé, když se blíží, ruku vytáhneš.|300|oral_klek",
    "Nech ji čekat celou minutu s roztaženýma nohama, než se jí vůbec dotkneš.|120|oral_klek",
    "Lízej ji pomalu tak dlouho, až tě začne sama tlačit k sobě.|300|oral_klek",
    "Tři minuty ticha: Lízej ji tři minuty a ani jeden z vás nesmí vydat hlásku. Cíl: úplné ticho.|180|oral_klek",
    "Lízej ji přes tenké kalhotky, dokud nebudou úplně mokré.|240|oral_klek",
    "Nech ji vybrat mezi jazykem a prsty. Pak jí dej to druhé.|240|oral_klek",
    "Lízej ji a zároveň jí přikládej vibrátor na vnitřní stranu stehna.|300|oral_klek",
    "Dej jí do ruky vibrátor a řekni, ať si ho přiloží, kam chce. Ty lížeš jinam.|300|oral_klek",
    "Dvě pomůcky: Vibrátor na bradavce, druhý na klitorisu a ty lížeš dovnitř. Cíl: udržet obě na místě.|300|oral_klek",
    "Lízej ji a pokaždé, když se pohne boky, zpomalíš.|300|oral_klek",
    "Nech ji ležet s rukama za hlavou. Když je sundá, přestaneš.|300|oral_klek",
    "Lízej ji tak dlouho, dokud nebude prosit. Pak ještě chvíli počkej.|300|oral_klek",
    "Řekni jí, že dojít smí až na tvoje svolení. A dej jí ho co nejpozději.|300|oral_klek",
    "Pomalé odpočítávání: Řekni jí, že za tři minuty skončíš, a nahlas počítej poslední minutu. Cíl: dotáhnout to přesně na nulu.|180|oral_klek",
    "Lízej ji a druhou rukou jí drž vibrátor zezadu u hráze.|300|oral_klek",
    "Nech ji mít zavázané oči a nevědět, kdy přestaneš.|300|oral_klek",
    "Lízej ji a mezi tím jí olizuj prsty u nohou.|300|oral_klek",
    "Dej si její ruku do vlasů a nech ji, ať přitlačí, když chce víc.|300|oral_klek",
    "Tři pokusy: Ona má tři pokusy říct správné slovo, kterým tě zrychlí. Jinak zůstáváš pomalý. Cíl: ať to uhodne.|300|oral_klek",
    "Lízej ji a pokaždé, když otevře oči, přestaneš.|300|oral_klek",
    "Nech ji držet kostku ledu v ruce. Až roztaje, smí dojít.|300|oral_klek",
    "Lízej ji a nech ji říkat, kolik vteřin ještě vydrží.|300|oral_klek",
    "Řekni jí, ať se nesmí ani jednou dotknout tvojí hlavy.|300|oral_klek",
    "Zadržený dech: Ona se zhluboka nadechne a ty lížeš, dokud nevydechne. Pak pauza. Pět kol. Cíl: vydržet všech pět.|300|oral_klek",
    "Lízej ji a zároveň jí prsty dráždi bradavky. Obojí naráz.|300|oral_klek",
    "Nech ji mít nohy zkřížené za tvojí hlavou a nepustit tě.|300|nohy_ramena",
    "Lízej ji a mezi tím jí pomalu strkej vibrátor dovnitř.|300|oral_klek",
    "Dej jí lubrikant na prsty a nech ji, ať si sama pomáhá, zatímco ji lížeš.|300|oral_klek",
    "Kdo dřív: Ty ji lížeš a ona se snaží vydržet co nejdéle bez zvuku. Cíl: ať to nevydrží do dvou minut.|120|oral_klek",
    "Lízej ji a druhou rukou jí drž kolena od sebe.|300|oral_klek",
    "Nech ji vybrat, jak dlouho ji budeš lízat. Pak přidej minutu navíc.|300|oral_klek",
    "Lízej ji a mezi tím jí kousej do vnitřní strany stehen.|300|oral_klek",
    "Řekni jí, ať počítá tvoje tahy nahlas. Když se splete, začínáš od nuly.|300|oral_klek",
    "Jazyk a led: Střídej horký jazyk a kostku ledu po dvaceti vteřinách. Cíl: pět střídání za sebou.|240|oral_klek",
    "Lízej ji a pokaždé, když se nadechne zhluboka, přestaneš.|300|oral_klek",
    "Nech ji, ať si sama roztáhne nohy tak, jak to chce.|300|oral_klek",
    "Lízej ji a mezi tím jí přejížděj pírkem po břiše.|300|oral_klek",
    "Dej si vibrátor pod bradu a lízej ji zároveň s ním.|300|oral_klek",
    "Dvojí zdroj: Vibrátor uvnitř a tvůj jazyk venku. Nikdy neuber ani jedno. Cíl: dovést ji tam oběma naráz.|300|oral_klek",
    "Lízej ji a nech ji, ať se drží čela postele. Nesmí pustit.|300|pouta_postel",
    "Řekni jí, že přestaneš, kdykoli se ti bude chtít. A několikrát to udělej.|300|oral_klek",
    "Lízej ji tak, aby se musela úplně odevzdat a nic neřídila.|300|oral_klek",
    "Nech ji ležet nehnutě. Za každý pohyb si připíše minutu navíc.|300|oral_klek",
    "Lízej ji a pak najednou přestaň a chvíli se na ni jen dívej.|240|oral_klek",
    "Čtyři fáze: Škádlení, pomalu, rychle, dokonči. Každá fáze přesně minutu a čtvrt. Cíl: dodržet pořadí.|300|oral_klek",
    "Lízej ji s vibrátorem přiloženým zvenku na jejím podbřišku.|300|oral_klek",
    "Nech ji, ať ti řekne, kdy má přijít konec. A ten okamžik dodrž.|300|oral_klek",
    "Lízej ji a druhou rukou jí drž hlavu, aby se musela dívat.|300|oral_klek",
    "Řekni jí, že když se udělá dřív než za tři minuty, nebude nic dalšího.|180|oral_klek",
    "Vzestup po minutách: První minutu velmi jemně, druhou silněji, třetí naplno. Cíl: nikdy se nevrátit zpět.|180|oral_klek",
    "Lízej ji a přitom si její nohy obtoč kolem svého krku.|300|nohy_ramena",
    "Nech ji vybrat mezi tím, jestli ji necháš dojít rychle, nebo dlouho škádlit.|300|oral_klek",
    "Lízej ji a mezi tím jí přejeď žínkou po stehnech.|300|oral_klek",
    "Dej jí vibrátor do ruky a řekni, že ho může použít až na tvoje slovo.|300|oral_klek",
    "Lízej ji tak dlouho, dokud ti nezačne škubat stehny.|300|oral_klek",
    "Poslední slovo: Ona musí říct jednu celou větu, aby dostala dovolení. Cíl: ať ji vůbec dokáže složit.|300|oral_klek",
    "Lízej ji a mezi tím jí lehce plácni na vnitřní stranu stehna.|300|oral_klek",
    "Nech ji držet si kolena a ty používej obě ruce i ústa.|300|nohy_ramena",
    "Lízej ji a pokaždé, když řekne tvoje jméno, zrychlíš.|300|oral_klek",
    "Řekni jí, že tahle karta skončí až v okamžiku, kdy se udělá. Bez výjimek.|300|oral_klek",
    "Dvě za sebou: Nech ji dojít a pak pokračuj, dokud nedojde podruhé. Cíl: dvě za sebou bez přestávky.|300|oral_klek",
    "Lízej ji pomalu i po vrcholu, dokud tě sama neodstrčí.|300|oral_klek",
    "Na konec jí polož hlavu na stehno a nech ji vydechnout.|60|oral_klek",
  ],

  female: [
    "Doveď ho ústy až těsně k vrcholu a přestaň. Počkej půl minuty. Pak znovu.|300|oral_on_vleze",
    "Škádlení kolem: Celé tři minuty olizuj všude kolem, jen ne tam, kde to chce. Cíl: ať tě sám nasměruje.|180|oral_on_vleze",
    "Kouři mu jen tehdy, když tě o to nahlas poprosí. Jinak čekáš.|300|oral_on_vleze",
    "Zakaž mu se udělat. Kouři mu tak dlouho, dokud to nebude muset říct nahlas.|300|oral_on_vleze",
    "Pětkrát na hranu: Doveď ho ústy pětkrát na hranu a pokaždé přestaň. Napošesté ho nech. Cíl: vydržet všech pět.|300|oral_on_vleze",
    "Kouři mu a zároveň mu drž vibrátor na bradavce.|300|oral_on_vleze",
    "Přilož mu vibrátor na varlata a jazykem dráždi špičku.|300|oral_on_vleze",
    "Kouři mu a přitom mu prsty dráždi hráz. Jen zvenku a s lubrikantem.|300|oral_on_vleze",
    "Nech ho držet si vibrátor sám a ty mu kouříš.|300|oral_on_vleze",
    "Střídej vibrátor a jazyk po půl minutě. On nesmí vědět, co přijde.|300|oral_on_vleze",
    "Nejdřív ledová: Vezmi si do pusy kostku ledu, olízni ho a pak hned pokračuj horkým jazykem. Cíl: co největší rozdíl.|240|oral_on_vleze",
    "Kouři mu a mezi tím mu mokrými prsty kresli po břiše.|240|oral_on_vleze",
    "Dej si na rty trochu lubrikantu a kouři mu úplně bez tření.|300|oral_on_vleze",
    "Kouři mu a druhou rukou mu dráždi hráz palcem.|300|oral_on_vleze",
    "Nech ho počítat, kolikrát se dostane na hranu. Ty rozhoduješ, kdy ho necháš.|300|oral_on_vleze",
    "Deset minut bez konce: Kouři mu střídavě rychle a pomalu, ale nesmíš ho nechat dojít, dokud čas neuběhne. Cíl: udržet ho na hraně.|300|oral_on_vleze",
    "Kouři mu a pokaždé, když řekne prosím, na deset vteřin přestaneš.|300|oral_on_vleze",
    "Řekni mu, že ho necháš dojít jen tehdy, když ti přesně popíše, co cítí.|300|oral_on_vleze",
    "Kouři mu a nech ho hodnotit od jedné do desíti. Pod osmičku nesmíš klesnout.|300|oral_on_vleze",
    "Nech ho, ať ti nahlas říká, co má dělat tvůj jazyk. Ty jen plníš.|300|oral_on_vleze",
    "Hlas na povel: On musí nahlas říkat, co cítí. Kdykoli ztichne, přestaneš a čekáš. Cíl: ať nezmlkne ani na chvíli.|300|oral_on_vleze",
    "Kouři mu a druhou rukou mu drž ruce, ať si nemůže pomoct sám.|300|oral_on_vleze",
    "Obejmi ho rukou a kouři mu, ale pokaždé, když se blíží, ruku sundáš.|300|oral_on_vleze",
    "Nech ho čekat celou minutu s roztaženýma nohama, než se ho vůbec dotkneš.|120|oral_on_vleze",
    "Kouři mu pomalu tak dlouho, až tě začne sám tlačit k sobě.|300|oral_on_vleze",
    "Tři minuty ticha: Kouři mu tři minuty a ani jeden z vás nesmí vydat hlásku. Cíl: úplné ticho.|180|oral_on_vleze",
    "Olizuj ho přes tenké trenýrky, dokud nebudou úplně mokré.|240|oral_on_vleze",
    "Nech ho vybrat mezi ústy a rukou. Pak mu dej to druhé.|240|oral_on_vleze",
    "Kouři mu a zároveň mu přikládej vibrátor na vnitřní stranu stehna.|300|oral_on_vleze",
    "Dej mu do ruky vibrátor a řekni, ať si ho přiloží, kam chce. Ty pracuješ jinde.|300|oral_on_vleze",
    "Dvě pomůcky: Vibrátor na bradavce, druhý na hrázi a ty ústy nahoře. Cíl: udržet obě na místě.|300|oral_on_vleze",
    "Kouři mu a pokaždé, když se pohne boky, zpomalíš.|300|oral_on_vleze",
    "Nech ho ležet s rukama za hlavou. Když je sundá, přestaneš.|300|oral_on_vleze",
    "Kouři mu tak dlouho, dokud nebude prosit. Pak ještě chvíli počkej.|300|oral_on_vleze",
    "Řekni mu, že se udělat smí až na tvoje svolení. A dej mu ho co nejpozději.|300|oral_on_vleze",
    "Pomalé odpočítávání: Řekni mu, že za tři minuty skončíš, a nahlas počítej poslední minutu. Cíl: dotáhnout to přesně na nulu.|180|oral_on_vleze",
    "Kouři mu a druhou rukou mu drž vibrátor zezadu u hráze.|300|oral_on_vleze",
    "Nech ho mít zavázané oči a nevědět, kdy přestaneš.|300|oral_on_vleze",
    "Kouři mu a mezi tím mu olizuj prsty u nohou.|300|oral_on_vleze",
    "Dej si jeho ruku do vlasů a nech ho, ať přitlačí, když chce víc.|300|oral_on_vleze",
    "Tři pokusy: On má tři pokusy říct správné slovo, kterým tě zrychlí. Jinak zůstáváš pomalá. Cíl: ať to uhodne.|300|oral_on_vleze",
    "Kouři mu a pokaždé, když otevře oči, přestaneš.|300|oral_on_vleze",
    "Nech ho držet kostku ledu v ruce. Až roztaje, smí se udělat.|300|oral_on_vleze",
    "Kouři mu a nech ho říkat, kolik vteřin ještě vydrží.|300|oral_on_vleze",
    "Řekni mu, ať se nesmí ani jednou dotknout tvojí hlavy.|300|oral_on_vleze",
    "Zadržený dech: On se zhluboka nadechne a ty kouříš, dokud nevydechne. Pak pauza. Pět kol. Cíl: vydržet všech pět.|300|oral_on_vleze",
    "Kouři mu a zároveň mu prsty dráždi bradavky. Obojí naráz.|300|oral_on_vleze",
    "Nech ho mít nohy zkřížené za tvými zády a nepustit tě.|300|oral_on_vleze",
    "Kouři mu a mezi tím mu pomalu přikládej vibrátor k varlatům.|300|oral_on_vleze",
    "Dej mu lubrikant na dlaň a nech ho, ať si sám pomáhá, zatímco mu kouříš.|300|oral_on_vleze",
    "Kdo dřív: Ty mu kouříš a on se snaží vydržet co nejdéle bez zvuku. Cíl: ať to nevydrží do dvou minut.|120|oral_on_vleze",
    "Kouři mu a druhou rukou mu drž kolena od sebe.|300|oral_on_vleze",
    "Nech ho vybrat, jak dlouho mu budeš kouřit. Pak přidej minutu navíc.|300|oral_on_vleze",
    "Kouři mu a mezi tím mu kousej do vnitřní strany stehen.|300|oral_on_vleze",
    "Řekni mu, ať počítá tvoje tahy nahlas. Když se splete, začínáš od nuly.|300|oral_on_vleze",
    "Horko a mráz: Po dvaceti vteřinách vždycky vyměň horký jazyk za kostku ledu. Cíl: pět střídání za sebou.|240|oral_on_vleze",
    "Kouři mu a pokaždé, když se nadechne zhluboka, přestaneš.|300|oral_on_vleze",
    "Nech ho, ať si sám roztáhne nohy tak, jak to chce.|300|oral_on_vleze",
    "Kouři mu a mezi tím mu přejížděj pírkem po břiše.|300|oral_on_vleze",
    "Dej si vibrátor do volné ruky a používej ho zároveň s ústy.|300|oral_on_vleze",
    "Dvojí zdroj: Vibrátor na varlatech a tvoje ústa nahoře. Nikdy neuber ani jedno. Cíl: dovést ho tam oběma naráz.|300|oral_on_vleze",
    "Kouři mu a nech ho, ať se drží čela postele. Nesmí pustit.|300|pouta_postel",
    "Řekni mu, že přestaneš, kdykoli se ti bude chtít. A několikrát to udělej.|300|oral_on_vleze",
    "Kouři mu tak, aby se musel úplně odevzdat a nic neřídil.|300|oral_on_vleze",
    "Nech ho ležet nehnutě. Za každý pohyb si připíše minutu navíc.|300|oral_on_vleze",
    "Kouři mu a pak najednou přestaň a chvíli se na něj jen dívej.|240|oral_on_vleze",
    "Čtyři díly: Nejdřív škádlení, pak pomalu, pak rychle a nakonec konec. Každý díl minutu a čtvrt. Cíl: dodržet pořadí.|300|oral_on_vleze",
    "Kouři mu s vibrátorem přiloženým zvenku na jeho podbřišku.|300|oral_on_vleze",
    "Nech ho, ať ti řekne, kdy má přijít konec. A ten okamžik dodrž.|300|oral_on_vleze",
    "Kouři mu a druhou rukou mu drž hlavu, aby se musel dívat.|300|oral_on_vleze",
    "Řekni mu, že když se udělá dřív než za tři minuty, nebude nic dalšího.|180|oral_on_vleze",
    "Po minutách nahoru: Minutu úplně jemně, minutu silněji, třetí minutu naplno. Cíl: nikdy se nevrátit zpět.|180|oral_on_vleze",
    "Kouři mu a přitom si jeho nohu opři o rameno.|300|oral_on_vleze",
    "Nech ho vybrat mezi tím, jestli ho necháš dojít rychle, nebo ho budeš dlouho škádlit.|300|oral_on_vleze",
    "Kouři mu a mezi tím mu přejeď žínkou po stehnech.|300|oral_on_vleze",
    "Dej mu vibrátor do ruky a řekni, že ho může použít až na tvoje slovo.|300|oral_on_vleze",
    "Kouři mu tak dlouho, dokud mu nezačnou škubat stehna.|300|oral_on_vleze",
    "Poslední slovo: On musí říct jednu celou větu, aby dostal dovolení. Cíl: ať ji vůbec dokáže složit.|300|oral_on_vleze",
    "Kouři mu a mezi tím mu lehce plácni na vnitřní stranu stehna.|300|oral_on_vleze",
    "Nech ho držet si kolena a ty používej obě ruce i ústa.|300|oral_on_vleze",
    "Kouři mu a pokaždé, když řekne tvoje jméno, zrychlíš.|300|oral_on_vleze",
    "Řekni mu, že tahle karta skončí až v okamžiku, kdy se udělá. Bez výjimek.|300|oral_on_vleze",
    "Hned podruhé: Nech ho dojít a pak pokračuj jemně dál, dokud to snese. Cíl: vydržet u něj i po konci.|300|oral_on_vleze",
    "Kouři mu pomalu i po vrcholu, dokud tě sám neodstrčí.|300|oral_on_vleze",
    "Na konec mu polož hlavu na stehno a nech ho vydechnout.|60|oral_on_vleze",
  ],
});
