// Kategorie 3 – Orální hrátky (dávka b)
// Témata: technika, tempo, tlak, jazyk versus rty, kombinace ruky a úst.
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 3,

  male: [
    "Jen špička jazyka: Lízej ji výhradně špičkou jazyka a drž jedno tempo. Cíl: tři minuty a ani jednou nezrychlit.|180|oral_klek",
    "Plochý a špičatý: Střídej plochý jazyk a jeho špičku po deseti vteřinách, ona počítá nahlas. Cíl: čtyři minuty a ani jednou se nesplést.|240|oral_klek",
    "Jazyk a nic víc: Celou dobu používej jen jazyk, ruce drž na jejích stehnech bez pohybu. Cíl: ani jednou nepomoct prsty.|300|oral_klek",
    "Kroužky kolem: Dělej jazykem kroužky kolem klitorisu, nikdy přímo na něm. Cíl: čtyři minuty a přímý dotek si nechat až na posledních deset vteřin.|240|oral_klek",
    "Prsty k břichu: Vsuň jí dva prsty dovnitř a pohybuj jimi směrem k břichu, zatímco ji lížeš. Cíl: pět minut a obojí ve stejném rytmu.|300|oral_klek",
    "Jako polibek na rty: Saj jí klitoris rty přesně tak jemně, jako bys ji líbal na ústa. Cíl: tři minuty a ani jednou nepřitlačit.|180|oral_klek",
    "Dvacet tahů: Lízej ji dlouhými tahy odspodu nahoru. Cíl: přesně dvacet tahů a pak přestat, ať prosí, jak chce.|180|oral_klek",
    "Osmičky: Kresli jí jazykem osmičky a nikdy nezměň směr. Cíl: vydržet celou dobu stejný obrazec.|240|oral_klek",
    "Minuta přes látku: Lízej ji nejdřív přes kalhotky. Cíl: sundat jí je nejdřív po celé minutě.|240|oral_klek",
    "Nohy na ramenou: Dej si její nohy na ramena a lízej ji zespodu, rukama jí drž boky. Cíl: pět minut a nenechat ji nohy stáhnout.|300|nohy_ramena",
    "Teplo a chlad z úst: Lízej ji a mezi tím na ni foukej studeným dechem. Cíl: deset střídání a nikdy neudělat dvě stejná za sebou.|240|oral_klek",
    "Rychle a pomalu: Půl minuty rychle, půl minuty co nejpomaleji. Pořád dokola. Cíl: nikdy tempo nesplést.|300|oral_klek",
    "Dlaň na břiše: Polož jí dlaň na břicho a lehce přitlač, zatímco ji lížeš. Cíl: čtyři minuty a tlak držet pořád stejný.|240|oral_klek",
    "Ona řekne dost: Lízej ji stejným tempem. Cíl: nepřestat, dokud ti sama neřekne, ať přestaneš.|300|oral_klek",
    "Led a pak teplo: Vezmi si do pusy kostku ledu a lízej ji. Cíl: nepřestat, dokud led neroztaje – a pak pokračovat teplým jazykem.|240|oral_klek",
    "Mentol v puse: Dej si do pusy něco mentolového a pak ji lízej. Cíl: čtyři minuty a zeptat se, jestli je to lepší, nebo horší.|240|oral_klek",
    "Jazyk a bradavka: Lízej ji a druhou rukou jí dráždi bradavku. Cíl: pět minut a obojí přesně ve stejném tempu.|300|oral_klek",
    "Trojí kombinace: Jazyk na klitorisu, dva prsty uvnitř a druhá ruka na bradavce. Všechno naráz. Cíl: udržet všechny tři celou dobu.|300|oral_klek",
    "Oči nahoru: Lízej ji a celou dobu se jí dívej do očí. Cíl: čtyři minuty a ani jednou neuhnout pohledem.|240|oral_klek",
    "Kraj postele a klek: Nech ji ležet na kraji postele a lízej ji vkleče na podlaze. Cíl: pět minut a ani jednou se nezvednout z kolen.|300|oral_vsede",
    "Zezadu na čtyřech: Nech ji kleknout si na všechny čtyři a lízej ji zezadu. Cíl: čtyři minuty a držet ji přitom oběma rukama za boky.|240|zezadu",
    "Polštář pod boky: Nech ji ležet na břiše s polštářem pod boky a lízej ji zezadu. Cíl: pět minut a nenechat ji se otočit.|300|na_brise",
    "Ty se nehýbeš: Nech ji sednout si ti na obličej a sám se vůbec nehýbej. Cíl: pět minut, při kterých tempo řídí jen ona.|300|oral_ona_nad_nim",
    "Deset a deset: Deset vteřin lízej, deset vteřin jen dýchej. Pět kol. Cíl: nikdy pauzu nezkrátit.|300|oral_klek",
    "Stehna od sebe: Lízej ji a rukama jí drž stehna od sebe. Cíl: pět minut a nenechat ji je zavřít ani jednou.|300|oral_klek",
    "Jedno nepřerušené kolo: Jazykem obkresluj celý tvar a nikde se nezastavuj. Cíl: dvacet kol a ani jedno přerušené.|240|oral_klek",
    "Musí se chytit: Lízej ji tak naléhavě, aby se musela něčeho chytit. Cíl: nepřestat, dokud se nechytí čela postele.|300|pouta_postel",
    "Stehna mezi tím: Střídej lízání a polibky na vnitřní strany stehen. Cíl: deset střídání a ani jednou dvě stejné věci za sebou.|300|oral_klek",
    "Nejdřív minutu jen dýchej: Celou první minutu na ni jen dýchej a nedotkni se jí. Pak teprve začni. Cíl: vydržet tu minutu.|300|oral_klek",
    "Ruce nad hlavou při lízání: Lízej ji a jednou rukou jí drž obě zápěstí nad hlavou. Cíl: pět minut a ani jednou ji nepustit.|300|oral_klek",
    "Až se začne stahovat: Vsuň do ní jeden prst a lízej ji. Cíl: nepřestat, dokud kolem prstu neucítíš stahy.|300|oral_klek",
    "Pokaždé jinak silně: Lízej ji shora dolů a pak zdola nahoru, pokaždé jiným tlakem. Cíl: deset cest a ať ti řekne, která byla nejlepší.|240|oral_klek",
    "Prsty v tempu jazyka: Zasouvej jí prsty přesně v tempu, ve kterém se hýbe tvůj jazyk. Cíl: pět minut a tempo ani jednou nerozejít.|300|oral_klek",
    "Opřená dozadu: Nech ji sednout na kraj postele a opřít se dozadu o ruce, ty klečíš a lížeš ji. Cíl: pět minut a nesmí se předklonit.|300|oral_vsede",
    "Bez rukou: Celý úkol máš ruce za zády. Jen ústa. Cíl: dokázat, že to stačí.|300|oral_klek",
    "Lízej ji a mezitím jí strkej palec do pusy, ať ho saje.|240|oral_klek",
    "Zrychluj postupně tak, že za pět minut dojdeš z nejpomalejšího na nejrychlejší.|300|oral_klek",
    "Lízej ji přesně tak, jak ti to řekne. Poslouchej každé slovo.|300|oral_klek",
    "Nech ji, ať si sama drží nohy, a ty používej obě ruce.|300|nohy_ramena",
    "Sto tahů: Uděláš jí jazykem přesně sto tahů. Ona počítá. Cíl: dojít do sta bez zrychlení.|300|oral_klek",
    "Lízej ji a sleduj, co dělá rukama. Podle toho zrychli nebo zpomal.|300|oral_klek",
    "Vsuň jí prst dovnitř a nehýbej jím. Všechnu práci dělá jazyk.|300|oral_klek",
    "Lízej ji tak jemně, že bude muset sama přitlačit.|240|oral_klek",
    "Vkleče před stojící: Nech ji stát, klekni si před ni a lízej ji. Jednu nohu si dej přes rameno. Cíl: čtyři minuty a udržet ji na nohou.|240|oral_ona_klek",
    "Lízej ji a pokaždé, když se pohne, na pět vteřin přestaň.|300|oral_klek",
    "Tři místa: Střídej klitoris, vchod a vnitřní stranu stehna. Nikdy dvakrát za sebou stejné. Cíl: devět střídání.|300|oral_klek",
    "Lízej ji přes tenkou látku a teprve na konci ji odhrň.|240|oral_klek",
    "Nech ji ležet s nohama přes tvoje ramena a drž ji za boky.|300|nohy_ramena",
    "Lízej ji a druhou rukou jí masíruj podbřišek.|300|oral_klek",
    "Dej si ji do postele napříč a lízej ji zboku.|300|oral_klek",
    "Až na konec: Lízej ji pět minut, ale nesmíš ji nechat dojít. Cíl: zastavit se včas.|300|oral_klek",
    "Lízej ji tak dlouho, dokud nezvedne boky. Pak se odtáhni a čekej.|240|oral_klek",
    "Vsuň do ní dva prsty a lízej ji zároveň, ale každý jiným tempem.|300|oral_klek",
    "Lízej ji s rukama položenýma na jejích prsou.|300|oral_klek",
    "Nech ji, ať ti drží hlavu a určuje, kam máš jít.|300|oral_klek",
    "Ona počítá: Ona nahlas počítá do dvaceti a ty musíš do posledního čísla vydržet stejné tempo. Cíl: dvacet bez změny.|180|oral_klek",
    "Ruka v jejích vlasech: Lízej ji a jednu ruku jí měj celou dobu zapletenou ve vlasech. Cíl: pět minut a ruku ani jednou nevyndat.|300|oral_klek",
    "Patnáct a patnáct: Střídej sání a lízání přesně po patnácti vteřinách. Cíl: pět minut a ani jednou čas nepřetáhnout.|300|oral_klek",
    "Lízej ji a mezi tím jí olizuj vnitřní stranu stehen. Vždycky po půl minutě.|300|oral_klek",
    "Zespodu nahoru: Nech ji kleknout si nad tebe a lízej ji zespodu, rukama jí drž boky. Cíl: pět minut a ani jednou ji nepustit.|300|oral_ona_nad_nim",
    "Jedním prstem: Lízej ji a používej jen jeden prst uvnitř. Ani o jeden víc. Cíl: vystačit si s jedním.|300|oral_klek",
    "Lízej ji a pokaždé, když vydechne, přitlač jazykem.|300|oral_klek",
    "Zavaž jí oči a lízej ji, aniž bys řekl jediné slovo.|300|oral_klek",
    "Lízej ji a druhou rukou si veď její ruku na svoje vlasy.|300|oral_klek",
    "Nech ji, ať si lehne na bok, a lízej ji zezadu.|300|p69_bok",
    "Souboj vůle: Lízej ji tak dlouho, dokud neřekne dost. Ona se snaží vydržet co nejdéle. Cíl: ať se vzdá jako první.|300|oral_klek",
    "Lízej ji rychle, ale jen velmi lehce. Bez tlaku.|240|oral_klek",
    "Na židli a vkleče: Nech ji sedět na židli s nohama přes tvoje ramena a klekni si před ni. Cíl: pět minut a nesmí dát nohy dolů.|300|oral_zidle",
    "Lízej ji a druhou rukou jí hlaď záda a zadeček.|300|oral_klek",
    "Vsuň jí prsty dovnitř a jazykem dráždi jen okraje.|300|oral_klek",
    "Lízej ji přesně tak, jak by sis přál, aby ona lízala tebe.|300|oral_klek",
    "Slepá zkouška: Zavaž si oči a lízej ji jen podle toho, jak reaguje. Cíl: trefit se bez očí.|300|oral_klek",
    "Dlaň na jejích ústech: Lízej ji a druhou rukou jí zakryj ústa. Cíl: pět minut a nepustit ji, ať je hlasitá, jak chce.|300|oral_klek",
    "Nech ji ležet a lízej ji shora tak, že máš hlavu obráceně.|300|p69",
    "Lízej ji a nech ji mluvit sprostě. Když ztichne, přestaneš.|300|oral_klek",
    "Dej si její koleno přes rameno a lízej ji z jedné strany.|300|oral_klek",
    "Až se udělá: Lízej ji tak dlouho, dokud nedojde, a pak ještě chvíli jemně pokračuj. Cíl: nepřestat příliš brzy.|300|oral_klek",
    "Lízej ji a druhou rukou jí drž nohu zvednutou ke stropu.|300|nohy_ramena",
    "Střídej jazyk a prsty tak, aby nikdy nevěděla, co přijde.|300|oral_klek",
    "Lízej ji tak dlouho, jak ti vydrží dech, pak se nadechni a pokračuj.|240|oral_klek",
    "Nech ji vybrat, jestli chce rychle, nebo dlouho. A dodrž to.|300|oral_klek",
    "Dvě kola: Doveď ji na hranu, přestaň na půl minuty, pak znovu. Podruhé už ji nech dojít. Cíl: vydržet tu pauzu.|300|oral_klek",
    "Lízej ji a druhou rukou jí drž ruku, ať se má čeho držet.|300|oral_klek",
    "Polibek a odchod: Polib ji jednou mezi nohy, vstaň a odejdi. Nic víc. Cíl: nevrátit se, ať prosí, jak chce.|60|oral_klek",
  ],

  female: [
    "Špičkou jazyka: Olizuj ho výhradně špičkou jazyka a drž jedno tempo. Cíl: tři minuty a ani jednou nezrychlit.|180|oral_on_vleze",
    "Plocha a špička: Střídej plochý jazyk a jeho špičku po deseti vteřinách, on počítá nahlas. Cíl: čtyři minuty a ani jednou se nesplést.|240|oral_on_vleze",
    "Jazyk a nic víc: Celou dobu používej jen jazyk, ruce drž na jeho stehnech bez pohybu. Cíl: ani jednou nepomoct rukou.|300|oral_on_vleze",
    "Kolem žaludu: Krouži jazykem kolem žaludu, nikdy přímo přes něj. Cíl: čtyři minuty a přímý dotek si nechat až na posledních deset vteřin.|240|oral_on_vleze",
    "Pusa a varlata: Vezmi ho do pusy a zároveň mu rukou masíruj varlata. Cíl: pět minut a obojí ve stejném rytmu.|300|oral_on_vleze",
    "Jemně jako na ústa: Saj ho rty přesně tak jemně, jako bys ho líbala na ústa. Cíl: tři minuty a ani jednou nepřitlačit.|180|oral_on_vleze",
    "Dvacet a konec: Olizuj ho dlouhými tahy odspodu nahoru. Cíl: přesně dvacet tahů a pak přestat, ať prosí, jak chce.|180|oral_on_vleze",
    "Osmičky: Kresli mu jazykem osmičky a nikdy nezměň směr. Cíl: vydržet celou dobu stejný obrazec.|240|oral_on_vleze",
    "Minuta přes trenýrky: Olizuj ho nejdřív přes trenýrky. Cíl: sundat mu je nejdřív po celé minutě.|240|oral_on_vleze",
    "Shora nad ním: Nech ho ležet a klekni si nad něj tak, abys ho brala shora. Cíl: pět minut a ani jednou polohu nezměnit.|300|oral_on_vleze",
    "Chlad mezi tím: Kouři mu a mezi tím na něj foukej studeným dechem. Cíl: deset střídání a nikdy dvě stejná za sebou.|240|oral_on_vleze",
    "Dvě rychlosti: Třicet vteřin rychle, třicet co nejpomaleji, a tak pořád dokola. Cíl: nikdy tempo nesplést.|300|oral_on_vleze",
    "Dlaň na jeho břiše: Polož mu dlaň na břicho a lehce přitlač, zatímco mu kouříš. Cíl: čtyři minuty a tlak držet pořád stejný.|240|oral_on_vleze",
    "On řekne dost: Kouři mu stejným tempem. Cíl: nepřestat, dokud ti sám neřekne, ať přestaneš.|300|oral_on_vleze",
    "Led a pak horko: Vezmi si do pusy kostku ledu a olizuj ho. Cíl: nepřestat, dokud led neroztaje – a pak pokračovat teplým jazykem.|240|oral_on_vleze",
    "Mentol na jazyku: Dej si do pusy něco mentolového a pak mu kuř. Cíl: čtyři minuty a zeptat se, jestli je to lepší, nebo horší.|240|oral_on_vleze",
    "Ústa a jeho bradavka: Kouři mu a druhou rukou mu dráždi bradavku. Cíl: pět minut a obojí přesně ve stejném tempu.|300|oral_on_vleze",
    "Trojí kombinace: Ústa nahoře, jedna ruka na kmeni a druhá na varlatech. Všechno naráz. Cíl: udržet všechny tři celou dobu.|300|oral_on_vleze",
    "Pohled vzhůru: Kouři mu a celou dobu se mu dívej do očí. Cíl: čtyři minuty a ani jednou neuhnout pohledem.|240|oral_on_vleze",
    "Kraj postele a kolena: Nech ho sedět na kraji postele a kuř mu vkleče na podlaze. Cíl: pět minut a ani jednou se nezvednout z kolen.|300|oral_on_vsede",
    "Zezadu vkleče: Nech ho kleknout si na všechny čtyři a olizuj ho zezadu. Cíl: čtyři minuty a držet ho přitom oběma rukama za boky.|240|zezadu!",
    "Záda až hráz: Nech ho ležet na břiše a olizuj mu záda, zadek a hráz. Cíl: pět minut a nenechat ho se otočit.|300|na_brise!",
    "Tempo řídíš ty: Klekni si nad něj a nech ho, ať ti pomáhá rukama, ale tempo určuješ ty. Cíl: pět minut a nenechat si ho vzít.|300|oral_on_vleze",
    "Deset a deset: Deset vteřin kouříš, deset vteřin jen dýcháš. Pět kol. Cíl: nikdy pauzu nezkrátit.|300|oral_on_vleze",
    "Jeho stehna od sebe: Kouři mu a rukama mu drž stehna od sebe. Cíl: pět minut a nenechat ho je zavřít ani jednou.|300|oral_on_vleze",
    "Celý tvar dokola: Objeď mu jazykem celý tvar dokola a ani na chvíli se nezastav. Cíl: dvacet kol a ani jedno přerušené.|240|oral_on_vleze",
    "Ať se musí chytit: Kouři mu tak naléhavě, aby se musel něčeho chytit. Cíl: nepřestat, dokud se nechytí čela postele.|300|pouta_postel!",
    "Jeho stehna mezi tím: Střídej kouření a polibky na vnitřní strany stehen. Cíl: deset střídání a ani jednou dvě stejné věci za sebou.|300|oral_on_vleze",
    "Nejdřív minutu jen dýchej: Celou první minutu na něj jen dýchej a nedotkni se ho. Pak teprve začni. Cíl: vydržet tu minutu.|300|oral_on_vleze",
    "Jeho ruce nad hlavou: Kouři mu a jednou rukou mu drž obě zápěstí nad hlavou. Cíl: pět minut a ani jednou ho nepustit.|300|oral_on_vleze",
    "Hluboko a jen špička: Vezmi ho hluboko a pak zase jen špičku a takhle to střídej. Cíl: dvacet střídání a ani jedno nezrychlit.|300|oral_on_vleze",
    "Olizuj ho shora dolů, pak zdola nahoru. Pokaždé jinak silně.|240|oral_on_vleze",
    "Pohybuj rukou přesně v tempu úst. Ani o kousek jinak.|300|oral_on_vleze",
    "Opřený dozadu: Posaď ho na kraj postele, ať se opře dozadu o ruce, a klekni si mu mezi kolena. Cíl: pět minut a nesmí se předklonit.|300|oral_on_vsede",
    "Ruce pryč: Po celý úkol máš ruce složené za zády a pracuješ jen ústy. Cíl: dokázat, že to stačí.|300|oral_on_vleze",
    "Kouři mu a mezitím mu strkej palec do pusy, ať ho saje.|240|oral_on_vleze",
    "Přidávej postupně, ať jsi za pět minut z nejpomalejšího tempa na nejrychlejším.|300|oral_on_vleze",
    "Kouři mu přesně tak, jak ti řekne. Poslouchej každé slovo.|300|oral_on_vleze",
    "Nech ho, ať si sám drží nohy, a ty používej obě ruce.|300|oral_on_vleze",
    "Sto tahů: Uděláš mu jazykem přesně sto tahů. On počítá. Cíl: dojít do sta bez zrychlení.|300|oral_on_vleze",
    "Kouři mu a sleduj, co dělá rukama. Podle toho zrychli nebo zpomal.|300|oral_on_vleze",
    "Vezmi ho do pusy a nehýbej se. Všechnu práci dělá jazyk.|300|oral_on_vleze",
    "Olizuj ho tak jemně, že bude muset sám přitlačit.|240|oral_on_vleze",
    "Vkleče před stojícím: Nech ho stát, klekni si před něj a kuř mu. Ruce máš na jeho bocích. Cíl: čtyři minuty a udržet ho na nohou.|240|oral_ona_klek",
    "Kouři mu a pokaždé, když se pohne, na pět vteřin přestaň.|300|oral_on_vleze",
    "Tři místa: Střídej žalud, kmen a varlata. Nikdy dvakrát za sebou stejné. Cíl: devět střídání.|300|oral_on_vleze",
    "Olizuj ho přes tenkou látku a teprve na konci ji odhrň.|240|oral_on_vleze",
    "Nech ho ležet a klekni si vedle jeho hlavy tak, aby na tebe viděl.|300|oral_on_vleze",
    "Kouři mu a druhou rukou mu masíruj podbřišek.|300|oral_on_vleze",
    "Napříč postelí: Polož si ho napříč postelí a kuř mu zboku, ať tě celou vidí. Cíl: pět minut a ani jednou nezměnit stranu.|300|oral_on_vleze",
    "Až na konec: Kouři mu pět minut, ale nesmíš ho nechat dojít. Cíl: zastavit se včas.|300|oral_on_vleze",
    "Kouři mu tak dlouho, dokud nezvedne boky. Pak se odtáhni a čekej.|240|oral_on_vleze",
    "Dvě různá tempa: Pracuj rukou i ústy zároveň, ale každým jiným tempem. Cíl: pět minut a ani jednou je nesladit.|300|oral_on_vleze",
    "Kouři mu s rukama položenýma na jeho hrudníku.|300|oral_on_vleze",
    "Určuje tempo on: Nech ho, ať ti drží hlavu a sám určuje tempo. Cíl: pět minut a ani jednou si neurčit tempo sama.|300|oral_on_vleze",
    "On počítá: On nahlas počítá do dvaceti a ty musíš do posledního čísla vydržet stejné tempo. Cíl: dvacet bez změny.|180|oral_on_vleze",
    "Jeho ruka ve vlasech: Kouři mu a jednu jeho ruku si polož do vlasů. Cíl: pět minut a nenechat ho ji sundat.|300|oral_on_vleze",
    "Střídej saní a olizování po patnácti vteřinách.|300|oral_on_vleze",
    "Kouři mu a mezi tím mu olizuj vnitřní stranu stehen. Vždycky po půl minutě.|300|oral_on_vleze",
    "Klekni si nad něj a kouři mu shora, zatímco tě drží za boky.|300|oral_on_vleze",
    "Jednou rukou: Kouři mu a používej jen jednu ruku. Druhou drž za zády. Cíl: vystačit si s jednou.|300|oral_on_vleze",
    "Kouři mu a pokaždé, když vydechne, přitlač jazykem.|300|oral_on_vleze",
    "Zavaž mu oči a kouři mu, aniž bys řekla jediné slovo.|300|oral_on_vleze",
    "Kouři mu a druhou rukou si veď jeho ruku na svoje vlasy.|300|oral_on_vleze",
    "Nech ho, ať si lehne na bok, a olizuj ho zezadu.|300|p69_bok",
    "Souboj vůle: Kouři mu tak dlouho, dokud neřekne dost. On se snaží vydržet co nejdéle. Cíl: ať se vzdá jako první.|300|oral_on_vleze",
    "Olizuj ho rychle, ale jen velmi lehce. Bez tlaku.|240|oral_on_vleze",
    "Židle a kolena: Nech ho sedět na židli a klekni si před něj mezi jeho nohy. Cíl: pět minut a ani jednou se nezvednout.|300|oral_zidle",
    "Kouři mu a druhou rukou mu hlaď záda a zadek.|300|oral_on_vleze",
    "Vezmi ho do pusy a jazykem dráždi jen okraj žaludu.|300|oral_on_vleze",
    "Kouři mu přesně tak, jak by sis přála, aby on lízal tebe.|300|oral_on_vleze",
    "Slepá zkouška: Zavaž si oči a kouři mu jen podle toho, jak reaguje. Cíl: trefit se bez očí.|300|oral_on_vleze",
    "Dlaň na jeho ústech: Kouři mu a druhou rukou mu zakryj ústa. Cíl: pět minut a nepustit ho, ať je hlasitý, jak chce.|300|oral_on_vleze",
    "Nech ho ležet a kouři mu shora tak, že máš hlavu obráceně.|300|p69",
    "Kouři mu a nech ho mluvit sprostě. Když ztichne, přestaneš.|300|oral_on_vleze",
    "Dej si jeho koleno přes rameno a olizuj ho z jedné strany.|300|oral_on_vleze",
    "Až se udělá: Kouři mu tak dlouho, dokud se neudělá, a pak ještě chvíli jemně pokračuj. Cíl: nepřestat příliš brzy.|300|oral_on_vleze",
    "Kouři mu a druhou rukou mu drž nohu zvednutou.|300|oral_on_vleze",
    "Střídej ústa a ruku tak, aby nikdy nevěděl, co přijde.|300|oral_on_vleze",
    "Kouři mu tak dlouho, jak ti vydrží dech, pak se nadechni a pokračuj.|240|oral_on_vleze",
    "Nech ho vybrat, jestli chce rychle, nebo dlouho. A dodrž to.|300|oral_on_vleze",
    "Dvě kola: Doveď ho na hranu, přestaň na půl minuty, pak znovu. Podruhé už ho nech dojít. Cíl: vydržet tu pauzu.|300|oral_on_vleze",
    "Kouři mu a druhou rukou mu drž ruku, ať se má čeho držet.|300|oral_on_vleze",
    "Jeden polibek a konec: Polib ho jednou mezi nohy, vstaň a odejdi. Nic víc. Cíl: nevrátit se, ať prosí, jak chce.|60|oral_on_vleze",
  ],
});
