// Kategorie 3 – Orální hrátky (dávka c)
// Témata: polohy, 69, klečení, kraj postele, ve stoje, svázané ruce, oční kontakt.
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 3,

  male: [
    "Oba naráz na boku: Lehněte si na bok hlavou k nohám toho druhého a ližte se navzájem. Cíl: pět minut a ani jeden nesmí přestat dřív.|300|p69_bok",
    "Ty vespod v 69: Lehni si na záda a nech ji lehnout si na tebe obráceně. Cíl: pět minut a ani jednou nepřestat dřív než ona.|300|p69",
    "Devětašedesát shora: Lehni si na záda, nech ji nad sebou a drž ji za boky. Ona řídí hloubku. Cíl: nechat vedení na ní.|300|p69",
    "Hlavou přes okraj: Nech ji ležet na zádech s hlavou přes okraj postele, ty stojíš u ní a lížeš ji shora. Cíl: čtyři minuty a držet ji za stehna.|240|oral_okraj",
    "Zezadu mezi nohama: Nech ji klečet na posteli a lízej ji zezadu mezi nohama. Cíl: pět minut a držet ji za boky, ať se nevykroutí.|300|zezadu",
    "Kolena přes opěrky: Posaď ji na židli, přehoď jí kolena přes opěrky a klekni si před ni. Cíl: pět minut a nesmí je stáhnout.|300|oral_zidle",
    "U zdi vkleče: Nech ji opřít se zády o zeď, klekni si před ni a lízej ji. Cíl: čtyři minuty a udržet ji na nohou.|240|zed",
    "Opřená o ruce: Nech ji sednout na kraj postele a opřít se dozadu o ruce, a lízej ji. Cíl: pět minut a nesmí se předklonit.|300|oral_vsede",
    "Poloha na hlavu: Ona leží a ty si klekneš nad ni obráceně. Ústa na ústa, ale dole. Cíl: neztratit rytmus.|300|p69",
    "Drží se čela postele: Nech ji kleknout si nad tvůj obličej a opřít se o čelo postele, a lízej ji zespodu. Cíl: pět minut a nepustit jí boky.|300|oral_ona_nad_nim",
    "Jen držíš a čekáš: Lež na zádech a nech ji, ať si sedne a pomalu se pohybuje. Cíl: pět minut, při kterých ty jen držíš její boky.|300|oral_ona_nad_nim",
    "Zvednuté boky: Nech ji ležet na břiše, zvedni jí boky rukama a lízej ji zezadu. Cíl: pět minut a boky ani jednou nespustit.|300|na_brise",
    "Obě nohy na ramenou: Dej si její nohy na ramena a lízej ji, rukama jí drž boky. Cíl: pět minut a nenechat ji nohy stáhnout.|300|nohy_ramena",
    "Stojí a drží se tě: Lízej ji vkleče, zatímco stojí a drží se tvých ramen. Cíl: čtyři minuty a nenechat ji sesunout se na zem.|240|oral_ona_klek",
    "Klek a čekání: Nech ji stát a klekni si před ni. Nezačneš, dokud tě sama nepřitáhne. Cíl: vydržet čekat.|240|oral_ona_klek",
    "Kravata a jazyk: Sváž jí ruce kravatou nad hlavou tak, aby uzel šel rozvázat jedním tahem, a lízej ji. Cíl: pět minut a na stop ji rozvázat.|300|pouta_postel",
    "Ruce u kotníků: Sváž jí ruce volně ke kotníkům a pomalu ji lízej. Cíl: pět minut a kdykoli řekne stop, hned ji uvolnit.|300|nohy_ramena",
    "Svázané ruce vkleče: Sváž jí ruce kravatou za zády, uzel volně, nech ji kleknout a lízej ji zezadu. Cíl: pět minut a na stop ji hned rozvázat.|300|zezadu",
    "Nesmí se podívat: Lízej ji a ona se ti přitom nesmí ani jednou podívat do očí. Cíl: pět minut – za každý pohled přestáváš na deset vteřin.|300|oral_klek",
    "Pravidlo pohledu: Ona se ti musí celou dobu dívat do očí. Když uhne, přestaneš. Cíl: nepřestat ani jednou.|300|oral_klek",
    "Přes opěradlo: Nech ji opřít se o opěradlo gauče a lízej ji zezadu. Cíl: pět minut a nesmí se narovnat.|300|predklon",
    "Nejdřív prsa: Nech ji sedět na tobě a olizuj jí prsa. Cíl: sjet níž nejdřív po dvou minutách.|300|klin_celem",
    "Napříč postelí: Nech ji ležet napříč postelí s hlavou přes okraj a lízej ji shora. Cíl: pět minut a držet ji za stehna.|300|oral_okraj",
    "Zvednutá horní noha: Nech ji lehnout si na bok a zvednout horní nohu, a lízej ji z boku. Cíl: pět minut a nohu jí držet celou dobu.|300|p69_bok",
    "Čelem k opěradlu: Nech ji kleknout na židli čelem k opěradlu a lízej ji zezadu. Cíl: pět minut a nesmí se pustit opěradla.|300|zidle_celem",
    "Šedesát devět vestoje: Nemožné, tak zkuste kompromis – ona klečí, ty stojíš a nakloníš se k ní. Cíl: najít polohu, co vám sedne.|240|oral_ona_klek",
    "Polštář a úhel: Nech ji ležet s polštářem pod boky a lízej ji seshora. Cíl: pět minut a nenechat polštář vyklouznout.|300|misionar_polstar",
    "Kolena nesmí zavřít: Nech ji ležet na zádech a rukama jí roztahuj kolena, zatímco ji lížeš. Cíl: pět minut a ani jednou je nesmí zavřít.|300|oral_klek",
    "Noha na posteli: Lízej ji vkleče, zatímco stojí a jednu nohu má opřenou o postel. Cíl: čtyři minuty a nohu nesmí sundat.|240|oral_ona_klek",
    "Polohu vybírá ona: Nech ji, ať si sama vybere polohu, a ty se jí beze slova přizpůsobíš. Cíl: pět minut a ani jednou ji neopravit.|300|oral_klek",
    "Tři polohy: Během úkolu vystřídáte tři různé polohy a ani na chvíli nepřestaneš. Cíl: plynulé přechody.|300|oral_klek",
    "Na loktech a kolenou: Nech ji kleknout si na všechny čtyři, opřít se o lokty a lízej ji zezadu. Cíl: pět minut a nesmí se zvednout.|300|zezadu",
    "Ruce pod ní: Lehni si na břicho mezi její nohy a obě ruce si dej pod její zadeček. Lízej ji. Cíl: pět minut a ruce nevyndat.|300|oral_klek",
    "Oba zároveň: Nech ji sedět na tobě obráceně a lízej ji, zatímco ti kouří. Cíl: pět minut a kdo přestane dřív, plní úkol navíc.|300|p69",
    "Ústa nahoře i dole: Klekni si vedle její hlavy a střídavě ji líbej na ústa a lízej mezi nohama. Cíl: deset střídání po třiceti vteřinách.|300|oral_klek",
    "Vzájemně a naráz: Oba zároveň, ale kdo první zrychlí, ten prohrál. Cíl: udržet stejné tempo.|300|p69",
    "Předkloněná přes postel: Nech ji předklonit se přes postel a lízej ji vkleče zezadu. Cíl: čtyři minuty a držet ji oběma rukama za boky.|240|predklon",
    "Ruce za zády při lízání: Lízej ji a jednou rukou jí přitom drž obě zápěstí za zády. Cíl: pět minut a ani jednou ji nepustit.|300|zezadu",
    "Pokrčená kolena: Nech ji ležet s pokrčenými koleny a lízej ji shora dolů. Cíl: dvacet dlouhých tahů a žádný rychlejší.|300|misionar",
    "Na podlaze pod ní: Sedni si na podlahu, nech ji sednout si na tebe a lízej ji zdola. Cíl: pět minut a ani jednou nepolevit v tempu.|300|oral_ona_nad_nim",
    "Držíš ji za stehna: Nech ji ležet na tobě obráceně a drž ji oběma rukama za stehna, zatímco ji lížeš. Cíl: pět minut a nepustit je.|300|p69",
    "Jedna noha uvázaná: Sváž jí kravatou jednu nohu k posteli, druhou nech volnou, a lízej ji. Cíl: pět minut a na stop ji hned rozvázat.|300|nohy_ramena",
    "Ať neuteče: Nech ji klečet nad tvým obličejem a drž ji pevně za boky. Cíl: pět minut a ani jednou jí nedovolit se odtáhnout.|300|oral_ona_nad_nim",
    "Přes okraj: Ať si lehne tak, aby jí hlava visela přes okraj postele, a lízej ji odshora. Cíl: vydržet tu polohu.|240|oral_okraj",
    "Ruce v dlaních: Nech ji sedět na kraji postele, klekni si před ni a drž jí obě ruce v dlaních, zatímco ji lížeš. Cíl: pět minut a nepustit je.|300|oral_vsede",
    "Kotník v dlani: Lízej ji a jednou rukou jí přitom drž kotník zvednuté nohy. Cíl: pět minut a nohu ani jednou nespustit.|300|nohy_ramena",
    "Jednostranné 69: Klekni si nad ni obráceně, ale ona se tě nesmí dotknout – pracuješ jen ty. Cíl: pět minut a nenechat ji zasáhnout.|300|p69",
    "Opřená o kraj postele: Nech ji opřít se o kraj postele a lízej ji vkleče zezadu. Cíl: pět minut a nenechat ji se narovnat.|300|zezadu",
    "Propletené nohy na boku: Lízej ji na boku, když máte nohy propletené. Cíl: pět minut a nohy ani jednou nerozplést.|300|p69_bok",
    "Klečí nad tebou: Nech ji kleknout si nad tebe a držet se opěradla, ty klečíš pod ní a lížeš ji. Cíl: pět minut a nesmí se pustit.|300|oral_ona_nad_nim",
    "Nahoru a dolů: Vystřídáš tři výšky – ona vleže, vsedě a ve stoje. V každé aspoň minutu. Cíl: projít všechny tři.|300|oral_vsede",
    "Svázaná na kraji postele: Sváž jí ruce kravatou, uzel volně, posaď ji na kraj postele a klekni si před ni. Cíl: pět minut a na stop ji rozvázat.|300|oral_vsede",
    "Nech ji ležet a zvedni jí boky rukama nahoru. Lízej ji zespodu.|300|nohy_ramena",
    "Přes polštář na břiše: Nech ji ležet na břiše přes polštář a lízej ji zezadu. Cíl: pět minut a nenechat ji se otočit.|300|na_brise",
    "Ať na tebe vidí: Klekni si mezi její kolena tak, aby ti celou dobu viděla do obličeje. Cíl: pět minut a ani jednou neuhnout pohledem.|300|oral_klek",
    "Nech ji, ať si sedne na židli a přehodí ti nohy přes ramena.|300|oral_zidle",
    "Dívej se a lízej: Ona se dívá na všechno, co děláš, a nahlas to komentuje. Cíl: ať nepřestane mluvit.|300|oral_klek",
    "Vede tě za hlavu: Ona stojí, ty klečíš a ona ti drží hlavu a určuje směr. Cíl: čtyři minuty a ani jednou si nezvolit směr sám.|240|oral_ona_klek",
    "Zezadu na boku: Lehni si za ni, když leží na boku zády k tobě, a lízej ji zezadu. Cíl: pět minut a nenechat ji se otočit.|300|p69_bok",
    "Nech ji ležet a lízej ji s hlavou opřenou o její stehno.|300|oral_klek",
    "Noha na tvém rameni: Nech ji opřít se o zeď, zvedni jí jednu nohu na rameno a lízej ji. Cíl: čtyři minuty a nohu ani jednou nespustit.|240|zed",
    "Ty vespod: Lehni si na záda a lízej ji, zatímco sedí nad tebou. Cíl: pět minut a ruce mít celou dobu na jejích stehnech.|300|oral_klek",
    "Dvojice zároveň: Vy oba ústy, ale ty musíš být vždycky o vteřinu napřed. Cíl: udržet náskok.|300|p69",
    "Nech ji položit si nohy na čelo postele a lízej ji seshora.|300|nohy_ramena",
    "Ona klečí vedle tebe a ty ležíš. Lízej ji zboku.|300|p69_bok",
    "Sváž jí ruce nad hlavou a nech ji ležet nehnutě, zatímco ji lížeš.|300|pouta_postel",
    "Lízej ji tak, aby musela ležet úplně rovně a nesměla se ohnout.|300|oral_klek",
    "Nech ji sedět na tvém obličeji a řídit všechno sama.|300|oral_ona_nad_nim",
    "Poloha bez rukou: Vyber polohu, ve které nemáš volné ruce, a vydrž v ní celou dobu. Cíl: nepomoct si.|300|oral_ona_nad_nim",
    "Klečíš na podlaze: Nech ji ležet na kraji postele a klekni si na podlahu mezi její kolena. Cíl: pět minut a ani jednou se nezvednout.|300|oral_vsede",
    "Lízej ji, když stojí předkloněná a opírá se o kolena.|240|predklon_stoje",
    "Pak už jen drž: Nech ji kleknout si nad tebe, lehni si pod ni a dál se nehýbej. Cíl: pět minut, při kterých pracuje jen ona.|300|oral_ona_nad_nim",
    "Nech ji ležet a ty lížeš zespoda s rukama na jejích prsou.|300|oral_klek",
    "Svázaná a ve stoje: Sváž jí ruce kravatou za zády, uzel volně, a lízej ji vkleče, zatímco stojí. Cíl: čtyři minuty a na stop ji hned rozvázat.|240|oral_ona_klek",
    "Vzájemně na boku: Oba na boku, ale ty přestaneš vždycky, když ona zrychlí. Cíl: naučit ji pomalost.|300|p69_bok",
    "Lízej ji přes opěradlo, zatímco se drží gauče.|300|predklon",
    "Nech ji sedět na židli a lízej ji s rukama za zády.|300|oral_zidle",
    "Ona leží a ty jí dáš jednu nohu na rameno a druhou necháš dole.|300|nohy_ramena",
    "Na klíně zády: Posaď si ji na klín zády k sobě a lízej ji odspodu, rukama jí drž stehna. Cíl: pět minut a ani jednou ji nepustit.|300|klin_zady",
    "Nech ji ležet a ty ležíš vedle. Lížeš ji ze strany a rukou hladíš.|300|oral_klek",
    "Poslední poloha: Nech ji vybrat, ve které poloze má skončit, a v ní ji doveď až na konec. Cíl: skončit tam, kde chce ona.|300|oral_klek",
    "Lízej ji tak, aby se musela držet tvých vlasů.|300|oral_klek",
    "Nech ji sedět na tobě a jen se dívej, jak se hýbe.|300|oral_ona_nad_nim",
    "Na konec ji polož a polib ji na břicho. Pak vstaň.|60|oral_klek",
  ],

  female: [
    "Na boku oba zároveň: Lehněte si na bok hlavou k nohám toho druhého a ližte se navzájem. Cíl: pět minut a ani jeden nesmí přestat dřív.|300|p69_bok",
    "Lehni si na něj obráceně a nech ho, ať tě drží. Ty jsi nahoře.|300|p69",
    "Devětašedesát shora: Klekni si nad něj obráceně a hloubku si řiď sama. On tě jen drží za boky. Cíl: mít to celé pod kontrolou.|300|p69",
    "Nech ho ležet přes kraj postele s hlavou dolů a stoupni si k němu.|240|oral_okraj!",
    "Nech ho klečet na posteli a ty ho olizuješ zezadu mezi nohama.|300|zezadu!",
    "Posaď ho na židli, roztáhni mu kolena a klekni si.|300|oral_zidle",
    "Zády o zeď: Nech ho opřít se zády o zeď, klekni si před něj a kuř mu. Cíl: čtyři minuty a udržet ho na nohou.|240|zed",
    "Nech ho sednout si na kraj postele a opřít se dozadu o ruce.|300|oral_on_vsede",
    "Poloha na hlavu: Klekni si nad něj obráceně, ústa na ústa, ale dole. Cíl: neztratit rytmus.|300|p69",
    "Opřená o čelo postele: Klekni si nad jeho obličej a opři se rukama o čelo postele. Cíl: pět minut a ani jednou se nepustit.|300|oral_ona_nad_nim",
    "Sedni si na něj a pomalu se pohybuj. On tě jen drží.|300|oral_ona_nad_nim",
    "Polož ho na břicho a olizuj ho zezadu, zatímco mu zvedáš boky.|300|na_brise!",
    "Nech ho ležet a dej si jeho kolena přes svoje ramena.|300|oral_on_vleze",
    "Drží se tvých ramen: Kouři mu vkleče, zatímco stojí a drží se tvých ramen. Cíl: čtyři minuty a nenechat ho sesunout se na zem.|240|oral_ona_klek",
    "Klek a čekání: Nech ho stát a klekni si před něj. Nezačneš, dokud tě sám nepřitáhne. Cíl: vydržet čekat.|240|oral_ona_klek",
    "Sváž mu ruce kravatou nad hlavou a pak mu kouři.|300|pouta_postel!",
    "Sváž mu ruce ke kotníkům, ať se nemůže hýbat, a pomalu mu kouři.|300|oral_on_vleze",
    "On má ruce svázané za zády a klečí. Ty ho olizuješ zezadu.|300|zezadu!",
    "Kouři mu a on se ti nesmí ani jednou podívat do očí.|300|oral_on_vleze",
    "Pravidlo pohledu: On se ti musí celou dobu dívat do očí. Když uhne, přestaneš. Cíl: nepřestat ani jednou.|300|oral_on_vleze",
    "Nech ho opřít se o opěradlo gauče a olizuj ho zezadu.|300|predklon!",
    "Sedni si na něj a olizuj mu hrudník. Až pak sjedeš níž.|300|klin_celem",
    "Nech ho ležet napříč postelí s hlavou přes okraj a kouři mu shora.|300|oral_okraj!",
    "Ať si lehne na bok a zvedne horní nohu. Olizuj ho z boku.|300|p69_bok",
    "On klečí na židli čelem k opěradlu a ty ho olizuješ zezadu.|300|zidle_celem",
    "Devětašedesát vestoje: Nejde to, tak zkuste kompromis – ty klečíš, on stojí a nakloní se k tobě. Cíl: najít polohu, co vám sedne.|240|oral_ona_klek",
    "Nech ho ležet s polštářem pod boky a kouři mu seshora.|300|misionar_polstar",
    "Jeho kolena od sebe: Nech ho ležet na zádech a rukama mu roztahuj kolena, zatímco mu kouříš. Cíl: pět minut a ani jednou je nesmí zavřít.|300|oral_on_vleze",
    "Kouři mu, zatímco stojí a jednu nohu má opřenou o postel.|240|oral_ona_klek",
    "Nech ho, ať si sám vybere polohu, a ty se přizpůsobíš.|300|oral_on_vleze",
    "Trojí poloha: Vystřídejte během úkolu tři polohy a ty u toho ani na vteřinu nepřestaneš. Cíl: plynulé přechody.|300|oral_on_vleze",
    "Na loktech a kolenou on: Nech ho kleknout si na všechny čtyři, opřít se o lokty a olizuj ho zezadu. Cíl: pět minut a nesmí se zvednout.|300|zezadu!",
    "Ruce pod ním: Lehni si na břicho mezi jeho nohy a obě ruce si dej pod jeho zadek. Kouři mu. Cíl: pět minut a ruce nevyndat.|300|oral_on_vleze",
    "Sedni si na něj obráceně a kouři mu, zatímco tě on líže.|300|p69",
    "Nech ho ležet a klekni si vedle jeho hlavy. Střídavě ho líbáš a olizuješ.|300|oral_on_vleze",
    "Oba naráz: Užívejte si navzájem ve stejnou chvíli a kdo první zrychlí, prohrál. Cíl: udržet stejné tempo.|300|p69",
    "Předkloněný přes postel: Nech ho předklonit se přes postel a olizuj ho vkleče zezadu. Cíl: čtyři minuty a držet ho oběma rukama za boky.|240|predklon",
    "Jeho ruce za zády: Kouři mu a jednou rukou mu přitom drž obě zápěstí za zády. Cíl: pět minut a ani jednou ho nepustit.|300|zezadu!",
    "Nech ho ležet s nohama pokrčenýma a kouři mu shora dolů.|300|oral_on_vleze",
    "Sedni si na podlahu a nech ho stoupnout si před tebe.|300|oral_ona_klek",
    "On leží pod tebou obráceně a ty ho držíš za stehna.|300|p69",
    "Sváž mu kravatou jednu nohu k posteli. Druhá zůstane volná.|300|oral_on_vleze",
    "Nad jeho obličejem: Klekni si nad jeho obličej, drž se čela postele a řiď tempo sama. Cíl: pět minut a nenechat ho se pohnout.|300|oral_ona_nad_nim",
    "Přes okraj: Ať si lehne tak, aby mu hlava visela přes okraj postele, a kouři mu odshora. Cíl: vydržet tu polohu.|240|oral_okraj!",
    "Jeho ruce v tvých: Nech ho sedět na kraji postele, klekni si před něj a drž mu obě ruce v dlaních. Cíl: pět minut a nepustit je.|300|oral_on_vsede",
    "Jeho kotník v dlani: Kouři mu a jednou rukou mu přitom drž kotník zvednuté nohy. Cíl: pět minut a nohu ani jednou nespustit.|300|oral_on_vleze",
    "Nech ho ležet a klekni si nad něj obráceně, ale ty jen kouříš.|300|p69",
    "Ať se opře o kraj postele a ty ho olizuješ zezadu vkleče.|300|zezadu!",
    "Olizuj ho na boku, když má nohy propletené s tvýma.|300|p69_bok",
    "Klečí nad tebou on: Nech ho kleknout si nad tebe a držet se opěradla, ty klečíš pod ním. Cíl: pět minut a nesmí se pustit.|300|oral_on_vleze",
    "Nahoru a dolů: Vystřídáš tři výšky – on vleže, vsedě a ve stoje. V každé aspoň minutu. Cíl: projít všechny tři.|300|oral_on_vsede",
    "Sváž mu ruce a posaď ho na kraj postele. Pak si klekni.|300|oral_on_vsede",
    "Nech ho ležet a zvedni mu boky rukama nahoru. Olizuj ho zespodu.|300|oral_on_vleze",
    "On leží na břiše přes polštář a ty ho olizuješ zezadu.|300|na_brise!",
    "Ať na tebe vidí: Klekni si mezi jeho kolena tak, aby ti celou dobu viděl do obličeje. Cíl: pět minut a ani jednou neuhnout pohledem.|300|oral_on_vleze",
    "Nech ho sednout si na židli a přehoď si jeho nohu přes rameno.|300|oral_zidle",
    "Dívej se a kouři: On se dívá na všechno, co děláš, a nahlas to komentuje. Cíl: ať nepřestane mluvit.|300|oral_on_vleze",
    "On stojí a ty klečíš. Drží tvoji hlavu a určuje tempo.|240|oral_ona_klek",
    "Olizuj ho na boku, když leží před tebou zády.|300|p69_bok",
    "Nech ho ležet a kouři mu s hlavou opřenou o jeho stehno.|300|oral_on_vleze",
    "Ruce na jeho bocích: Nech ho opřít se o zeď a klekni si před něj s rukama na jeho bocích. Cíl: čtyři minuty a ruce ani jednou nesundat.|240|zed",
    "Sedni si na něj a kouři mu, zatímco leží na zádech.|300|oral_on_vleze",
    "O vteřinu napřed: Oba ústy naráz, ale ty musíš být pořád o vteřinu před ním. Cíl: udržet náskok.|300|p69",
    "Nech ho opřít si nohy o čelo postele a kouři mu seshora.|300|oral_on_vleze",
    "On klečí vedle tebe a ty ležíš. Olizuj ho zboku.|300|p69_bok",
    "Sváž mu ruce nad hlavou a nech ho ležet nehnutě, zatímco mu kouříš.|300|pouta_postel!",
    "Kouři mu tak, aby musel ležet úplně rovně a nesměl se ohnout.|300|oral_on_vleze",
    "Všechno řídíš sama: Sedni si mu na obličej a řiď tempo i tlak úplně sama. Cíl: pět minut, při kterých se on nesmí pohnout.|300|oral_ona_nad_nim",
    "Ruce mimo hru: Zvol si polohu, ve které se rukama nedostaneš nikam, a vydrž v ní. Cíl: nepomoct si.|300|oral_ona_nad_nim",
    "Na podlaze mezi koleny: Nech ho ležet na kraji postele a klekni si na podlahu mezi jeho kolena. Cíl: pět minut a ani jednou se nezvednout.|300|oral_on_vsede",
    "Kouři mu, když stojí předkloněný a opírá se o kolena.|240|predklon_stoje!",
    "Jen držíš: Nech ho kleknout si nad tebe, lehni si pod něj a dál se nehýbej. Cíl: pět minut, při kterých pracuje jen on.|300|oral_on_vleze",
    "Nech ho ležet a kouři mu zespoda s rukama na jeho hrudníku.|300|oral_on_vleze",
    "Svázaný ve stoje: Sváž mu ruce kravatou za zády, uzel volně, a kuř mu vkleče, zatímco stojí. Cíl: čtyři minuty a na stop ho hned rozvázat.|240|oral_ona_klek",
    "Vzájemně na boku: Oba na boku, ale ty přestaneš vždycky, když on zrychlí. Cíl: naučit ho pomalost.|300|p69_bok",
    "Olizuj ho přes opěradlo, zatímco se drží gauče.|300|predklon!",
    "Nech ho sedět na židli a kouři mu s rukama za zády.|300|oral_zidle",
    "On leží a ty mu dáš jednu nohu na rameno a druhou necháš dole.|300|oral_on_vleze",
    "Drží tě zezadu: Kouři mu, zatímco ti sedí za zády a drží tě kolem pasu. Cíl: pět minut a ani jednou tě nesmí pustit.|300|klin_zady",
    "Nech ho ležet a ty ležíš vedle. Olizuješ ho ze strany a rukou hladíš.|300|oral_on_vleze",
    "Poslední poloha: Nech ho vybrat, ve které poloze má skončit, a v ní ho doveď až na konec. Cíl: skončit tam, kde chce on.|300|oral_on_vleze",
    "Kouři mu tak, aby se musel držet tvých vlasů.|300|oral_on_vleze",
    "Sedni si na něj a jen se dívej, jak se snaží vydržet.|300|oral_ona_nad_nim",
    "Na konec ho polož a polib ho na břicho. Pak vstaň.|60|oral_on_vleze",
  ],
});
