// Kategorie 4 – Sex a polohy (dávka d)
// Témata: v sedě, ve stoje, na kraji postele, zvednutá, přechody mezi polohami.
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 4,

  male: [
    "Pohyb dělá ona: Posaď si ji obkročmo na klín, zaveď se do ní a sám se vůbec nehýbej. Cíl: čtyři minuty, při kterých všechnu práci dělá ona.|240|zidle_celem",
    "Na židli čelem: Sedí ti obkročmo na klíně, jezdí na tobě a drží se opěradla. Cíl: pět minut a tempo přírazů nechat celé na ní.|300|zidle_celem",
    "Objatá přes prsa: Nech ji nasadit se na tebe zády a drž ji celou dobu přes prsa. Cíl: čtyři minuty jízdy a ani jednou ji nepustit.|240|klin_zady",
    "Na židli zády: Posaď si ji na klín zády, zaveď se do ní a rukou jí zepředu dráždi klitoris. Cíl: pět minut a ruku ani jednou nesundat.|300|klin_zady",
    "Objetí bez pohybu: Posaď si ji na klín a jen se objímejte, zatímco v ní jsi. Cíl: dvě minuty úplného klidu, teprve pak se začni hýbat.|240|klin_celem",
    "Lotos na podlaze: Sedněte si na podlahu proti sobě, zaveď se do ní a propleťte nohy. Cíl: čtyři minuty a hýbat se jen boky.|240|lotos",
    "Lotos vsedě: Sedíte proti sobě, nohy propletené, jsi v ní. Hýbat se dá jen boky. Cíl: pět minut a ani jednou nevyklouznout.|300|lotos",
    "Kraj postele a ty ve stoje: Posaď ji na kraj postele, postav se před ni, vnikni do ní a přitáhni si ji za boky. Cíl: čtyři minuty přírazů vestoje.|240|kraj_postele",
    "Stehna v dlaních: Leží na kraji postele, zvedni jí nohy, drž ji za stehna a přirážej. Cíl: čtyři minuty a ani jednou ji nepustit.|240|kraj_postele",
    "Kraj postele: Leží na kraji, ty stojíš a přirážíš do ní vestoje. Cíl: čtyři minuty a najít výšku, kde to sedne oběma.|240|kraj_postele",
    "Přitáhne si tě nohama: Posaď ji na kraj postele, vnikni do ní a nech si ji přitahovat nohama. Cíl: čtyři minuty, při kterých tempo určuje jen ona.|240|kraj_postele",
    "Nohy na ramenou na kraji: Polož si její nohy na ramena a vnikni do ní co nejhlouběji. Cíl: čtyři minuty a každou minutu se zeptat, jestli to není moc.|240|kraj_postele",
    "Jedna noha u zdi: Postav ji ke zdi, zvedni jí jednu nohu a miluj se s ní vestoje. Cíl: čtyři minuty a nohu ani jednou nespustit.|240|zed",
    "Zápěstí na zdi: Přitiskni ji ke zdi, vnikni do ní zezadu a drž jí obě zápěstí nad hlavou. Cíl: čtyři minuty a na stop ji hned pustit.|240|zed",
    "U zdi a pomalu: Je opřená o zeď a ty do ní vestoje přirážíš tak pomalu, jak umíš. Cíl: čtyři minuty a ani jednou nezrychlit.|240|zed",
    "Čelem ke zdi: Postav ji čelem ke zdi, ať se opře dlaněmi, a vnikni do ní zezadu. Cíl: čtyři minuty a nesmí ruce sundat.|240|zed",
    "Obě dlaně na zdi: Nech ji opřít se oběma dlaněmi o zeď a miluj ji zezadu. Cíl: čtyři minuty a nesmí ruce ze zdi sundat.|240|zed",
    "Přes opěradlo gauče: Předkloň ji přes opěradlo gauče a vnikni do ní zezadu. Cíl: čtyři minuty a držet ji celou dobu za boky.|240|predklon",
    "Ruce za zády přes opěradlo: Předkloň ji přes opěradlo, vnikni do ní zezadu a drž jí obě ruce za zády. Cíl: čtyři minuty a na stop ji hned pustit.|240|predklon",
    "Přes opěradlo: Drží se opěradla a ty do ní zezadu přirážíš naplno. Cíl: čtyři minuty a najít společný rytmus.|240|predklon",
    "Ruce na kolenou: Nech ji předklonit se a opřít si ruce o kolena a miluj ji zezadu. Cíl: čtyři minuty a nesmí se narovnat.|240|predklon_stoje",
    "Předkloněná ve stoje: Ona stojí předkloněná, ty ji držíš za boky a přirážíš. Cíl: čtyři minuty a udržet oba na nohou.|240|predklon_stoje",
    "V náručí: Zvedni ji do náruče, vnikni do ní a nech ji držet se tě nohama kolem pasu. Cíl: udržet ji aspoň tři minuty.|180|zvednuta",
    "Donést ji ke zdi: Přirážej do ní v náručí tak dlouho, jak zvládneš, a pak ji opři o zeď. Cíl: dojít až ke zdi bez vyjití.|180|zvednuta",
    "Opora o zeď: Zvedni ji, opři ji zády o zeď a přirážej do ní vestoje. Cíl: čtyři minuty a ani jednou ji nepoložit na zem.|240|zed",
    "Na kraji linky: Posaď si ji na kraj stolu nebo linky, vnikni do ní a přitáhni si ji za boky. Cíl: čtyři minuty přírazů a najít správnou výšku.|240|kraj_postele",
    "Na kraji postele čelem: Sedni si na kraj postele a nech ji nasadit se na tebe čelem. Cíl: čtyři minuty jízdy a držet se navzájem za ramena.|240|klin_celem",
    "Zvedáš ji pod zadečkem: Vsedě na kraji postele ji drž pod zadečkem a přirážej do ní sám. Cíl: čtyři minuty, při kterých se ona nenamáhá.|240|klin_celem",
    "Opřený o čelo postele: Sedni si opřený o čelo postele a nech ji nasadit se na tebe. Cíl: čtyři minuty a přiráží jen ona.|240|ona_nahore",
    "Vsedě opřený: Sedíš opřený a ona na tobě jezdí čelem k tobě. Cíl: pět minut a polibek ani jednou nepřerušit.|300|klin_celem",
    "Nejdřív se svlékne: Sedni si na židli, nech ji svléknout se před tebou a pak nasadit se na tebe. Cíl: nesáhnout na ni, dokud nebude úplně nahá.|300|zidle_celem",
    "Ruce za zády na židli: Jezdí ti obkročmo na klíně na židli a ty jí držíš ruce za zády. Cíl: čtyři minuty a na stop ji hned pustit.|240|zidle_celem",
    "Nohy mezi tvýma: Nech ji nasadit se na tebe zády s nohama mezi tvýma. Cíl: čtyři minuty jízdy a držet ji celou dobu za boky.|240|klin_zady",
    "Tempo určuješ ty: Sedí ti na židli zády, ty ji držíš za boky a přirážíš svým tempem. Cíl: čtyři minuty a ani jednou jí tempo nepřenechat.|240|klin_zady",
    "Klečí na židli: Nech ji kleknout na židli čelem k opěradlu a miluj ji zezadu. Cíl: čtyři minuty a nesmí se pustit opěradla.|240|zidle_celem",
    "Opřený o postel: Sedni si na podlahu opřený o postel a nech ji nasadit se na tebe. Cíl: čtyři minuty a hýbat se jen boky.|240|lotos",
    "Na podlaze: Sedíte na koberci, jsi v ní a oba jste opření dozadu o ruce. Cíl: čtyři minuty a udržet rovnováhu.|240|lotos",
    "Pověšená na krku: Ať se ti pověsí na krk a obtočí tě nohama, a přirážej do ní vestoje. Cíl: udržet ji aspoň tři minuty.|180|zvednuta",
    "Přesun bez vyjití: Zvedni si ji do náruče a posaď si ji na kraj postele, aniž bys z ní vyklouzl. Cíl: čtyři minuty a ani jedno přerušení.|240|kraj_postele",
    "Klečíš před ní: Posaď ji na kraj postele, klekni si před ni a vnikni do ní. Cíl: čtyři minuty přírazů a ani jednou se nezvednout.|240|kraj_postele",
    "Nohy kolem tvého pasu: Vnikni do ní na kraji postele a dej si její nohy kolem pasu. Cíl: čtyři minuty přírazů a nohy jí nespustit.|240|kraj_postele",
    "Kotníky v tvých dlaních: Ať leží na kraji, drž ji za kotníky roztažené a přirážej. Cíl: čtyři minuty a kotníky ani jednou nepustit.|240|kraj_postele",
    "Tři výšky: Milujte se dvě minuty vleže, dvě vsedě a dvě ve stoje. Cíl: projít všechny tři bez jediného vyjití.|300|kraj_postele",
    "Od zdi na židli: Začni do ní přirážet vestoje u zdi a skonči vsedě na židli. Cíl: přejít bez jediného přerušení.|300|zed",
    "Ze židle do náruče: Začni na židli a pak se s ní v náručí postav a přirážej vestoje. Cíl: přechod bez jediného vyjití.|300|zvednuta",
    "Přechod bez vyklouznutí: Začněte na lžičku a přejděte do misionáře, aniž bys z ní vyšel. Cíl: tři takové přechody za pět minut.|300|lzicka",
    "Přechod bez vyjití: Vystřídejte při sexu tři polohy a ani jednou z ní nevyjdeš. Cíl: tři plynulé přechody za pět minut.|300|zezadu",
    "Opřená o kraj postele: Nech ji stát opřenou o kraj postele a miluj ji zezadu. Cíl: čtyři minuty a nesmí se narovnat.|240|predklon",
    "Postav ji před zrcadlo a vnikni do ní zezadu, ať se dívá.|240|zed",
    "Bok a noha: Přirážej do ní u zdi, jednou rukou ji drž za bok a druhou jí drž nohu nahoře. Cíl: čtyři minuty a ani jednu ruku nesundat.|240|zed",
    "Drží se zárubně: Nech ji držet se zárubně dveří a miluj ji zezadu. Cíl: čtyři minuty a nesmí se pustit ani jednou.|240|predklon_stoje",
    "Ve stoje a potichu: Miluj se s ní vestoje u zdi a ani jeden z vás nesmí vydat hlásku. Cíl: čtyři minuty úplného ticha.|240|zed",
    "Klín na podlaze: Posaď si ji na klín na podlaze, zaveď se do ní a obejmi ji oběma rukama. Cíl: čtyři minuty a objetí nerozpojit.|240|klin_podlaha",
    "Mezi tvýma nohama: Sedni si za ni, posaď si ji zády mezi svoje nohy a zaveď se do ní. Cíl: čtyři minuty a hýbat se jen boky.|240|klin_podlaha",
    "Na klíně zády: Jezdí ti na klíně zády a ty jí sáhneš zepředu na klitoris. Cíl: pět minut a nepřestat ji dráždit ani na chvíli.|300|klin_zady",
    "Ústy a pak na klín: Nech ji stát mezi tvýma nohama a vzít si tě do pusy, pak si ji posaď na klín a miluj se s ní. Cíl: minuta ústy a dvě na klíně.|180|oral_vsede",
    "Dokud udržíš: Zvedni si ji na sebe a přirážej do ní v náručí, dokud ji udržíš. Cíl: aspoň dvě minuty, než si sednete.|180|zvednuta",
    "Nohy kolem opěradla: Nech ji nasadit se na tebe na židli a dát si nohy kolem opěradla. Cíl: čtyři minuty jízdy a nohy ani jednou nespustit.|240|zidle_celem",
    "Sedni si a nech ji, ať se na tobě houpe jen dopředu a dozadu.|240|klin_celem",
    "Oči v očích na klíně: Nech ji jezdit na tobě čelem tak pomalu, ať se celou dobu díváte do očí. Cíl: pět minut a ani jednou neuhnout.|300|klin_celem",
    "Oči v očích vsedě: Sedíte čelem k sobě, jezdí na tobě a ani jeden neuhne pohledem. Cíl: pět minut a kdo uhne, plní úkol navíc.|300|klin_celem",
    "Předkloněná přes postel: Nech ji předklonit se přes postel a miluj ji zezadu ve stoje. Cíl: čtyři minuty a držet ji za boky.|240|predklon",
    "Lopatky pod dlaní: Předkloň ji přes postel, vnikni do ní zezadu a polož jí ruku mezi lopatky. Cíl: čtyři minuty a tlak nezvyšovat.|240|predklon",
    "Zápěstí vzadu ve stoje: Ať stojí předkloněná, vnikni do ní zezadu a drž jí obě zápěstí vzadu. Cíl: čtyři minuty a na stop ji hned pustit.|240|predklon_stoje",
    "Rameno u zdi: Postav ji ke zdi zády, vnikni do ní zezadu a drž jí jednou rukou rameno. Cíl: čtyři minuty a ani jednou ji nepustit.|240|zed",
    "Noha na posteli: Ona stojí, ty jí zvedneš nohu na kraj postele a miluješ se s ní. Cíl: čtyři minuty a nohu nespustit.|240|zed",
    "Jedna noha nahoře: Stojí s jednou nohou opřenou vysoko, ty jí držíš koleno a přirážíš. Cíl: vydržet tak dvě minuty.|240|zed",
    "Opřená dozadu na židli: Nech ji nasadit se na tebe na židli zády a opřít se ti dozadu o hrudník. Cíl: čtyři minuty a hýbat se jen boky.|240|klin_zady",
    "Otočka na tobě: Nech ji nasadit se na tebe a pomalu se na tobě otáčet dokola, aniž bys vyklouzl. Cíl: dvě celé otočky za pět minut.|300|ona_nahore",
    "Hýbeš se jen ty: Posaď si ji na klín, zaveď se do ní a všechny přírazy dělej sám. Cíl: čtyři minuty, při kterých se ona vůbec nepohne.|240|klin_celem",
    "Zvedáš ji ty: Sedí ti na klíně, drží se tvých ramen a ty ji zvedáš a přirážíš do ní. Cíl: čtyři minuty a ani jednou ji nepoložit.|240|klin_celem",
    "Po centimetrech: Sedni si a nech ji nasadit se na tebe úplně pomalu, po centimetrech. Cíl: sestup musí trvat aspoň minutu.|180|klin_celem",
    "Pomalé usednutí: Nasazuje se na tebe celou minutu, ani o vteřinu dřív. Cíl: vydržet celou minutu bez jediného přírazu.|60|klin_celem",
    "V náručí ve stoje: Drž ji kolem pasu, ať se drží tvého krku, a přirážej do ní vestoje. Cíl: udržet ji aspoň tři minuty a nepoložit.|180|zvednuta",
    "Ona výš než ty: Postav ji na kraj postele, aby byla výš než ty, a miluj se s ní. Cíl: čtyři minuty a držet ji, ať neztratí rovnováhu.|240|kraj_postele",
    "Za ruce k sobě: Posaď ji na okraj postele, vnikni do ní a přitahuj si ji za obě ruce. Cíl: čtyři minuty a ruce jí nepustit.|240|kraj_postele",
    "Za kolena k sobě: Na kraji postele si ji přitáhni za kolena úplně k sobě a přirážej. Cíl: čtyři minuty a kolena si nepustit.|240|kraj_postele",
    "Napříč postelí: Nech ji ležet napříč postelí, postav se z boku a vnikni do ní. Cíl: čtyři minuty a najít úhel, který sedne oběma.|240|kraj_postele",
    "Ze stoje do lehu: Začni do ní přirážet vestoje a postupně skončete vleže bez vyjití. Cíl: plynulý přechod za pět minut.|300|zed",
    "Rozhodne ona: Sedni si a nech ji nasadit se na tebe tak, jak chce – čelem, nebo zády. Cíl: čtyři minuty a po dvou minutách se otočí.|240|klin_celem",
    "Na židli a ty stojíš: Nech ji kleknout na židli, opřít se o opěradlo a vnikni do ní zezadu. Cíl: čtyři minuty a nesmí se pustit.|240|zidle_celem",
    "Konec na klíně: Posaď si ji nakonec na klín, zůstaň v ní a jen ji drž bez pohybu. Cíl: dvě minuty klidu a ani slovo.|120|klin_celem",
  ],

  female: [
    "Pohyb děláš ty: Sedni si mu obkročmo na klín na židli, zaveď si ho do sebe a hýbej se jen ty. Cíl: čtyři minuty a on se nepohne.|240|zidle_celem",
    "Na židli čelem: Jezdi na něm obkročmo na židli a drž se opěradla. Cíl: pět minut a tempo přírazů určovat celou dobu sama.|300|zidle_celem",
    "Objatá přes prsa: Nasaď se mu na klín zády a nech se celou dobu držet přes prsa. Cíl: čtyři minuty jízdy a nesmí tě pustit.|240|klin_zady",
    "Na židli zády: Nasaď se mu na klín zády a nech si zepředu dráždit klitoris. Cíl: pět minut a ruku mu nedovolit sundat.|300|klin_zady",
    "Sedni si mu na klín a jen se objímejte, zatímco je v tobě.|240|klin_celem",
    "Lotos na podlaze: Nech ho sednout si na podlahu, nasaď se na něj a propleťte nohy. Cíl: čtyři minuty a hýbat se jen boky.|240|lotos",
    "Lotos vsedě: Sedíte proti sobě, nohy propletené, je v tobě. Hýbat se dá jen boky. Cíl: pět minut a ani jednou nevyklouznout.|300|lotos",
    "Na kraji a on ve stoje: Sedni si na kraj postele, nech ho stát před tebou a vniknout do tebe. Cíl: čtyři minuty přírazů vestoje.|240|kraj_postele!",
    "Stehna v jeho dlaních: Lež na kraji postele, nech si zvednout nohy, držet za stehna a přirážet. Cíl: čtyři minuty a nesmí tě pustit.|240|kraj_postele!",
    "Kraj postele: Ležíš na kraji, on stojí a přiráží do tebe vestoje. Cíl: čtyři minuty a najít výšku, kde to sedne oběma.|240|kraj_postele",
    "Přitáhni si ho nohama: Sedni si na kraj postele, nech ho vniknout a přitahuj si ho nohama. Cíl: čtyři minuty, při kterých tempo určuješ ty.|240|kraj_postele",
    "Nohy na jeho ramenou: Na kraji postele si polož nohy na jeho ramena a nech ho hluboko vniknout. Cíl: čtyři minuty a každou minutu říct, jestli to není moc.|240|kraj_postele!",
    "Noha kolem jeho boku: Opři se o zeď, zvedni nohu a obtoč mu ji kolem pasu, ať do tebe může vniknout vestoje. Cíl: čtyři minuty a nohu nespustit.|240|zed",
    "Zápěstí nad hlavou u zdi: Nech se přitisknout ke zdi, vniknout zezadu a držet za obě zápěstí nad hlavou. Cíl: čtyři minuty a na stop tě musí pustit.|240|zed",
    "U zdi a pomalu: Jsi opřená o zeď a on do tebe vestoje přiráží co nejpomaleji. Cíl: čtyři minuty a ani jednou nezrychlit.|240|zed",
    "Postav se čelem ke zdi a nech ho vniknout zezadu.|240|zed",
    "Dlaně na zdi: Opři se oběma dlaněmi o zeď a nech se milovat zezadu. Cíl: čtyři minuty a ruce ze zdi nesundat.|240|zed",
    "Přes opěradlo gauče: Předkloň se přes opěradlo a nech ho vniknout do tebe zezadu. Cíl: čtyři minuty přírazů a nepustit se opěradla.|240|predklon",
    "Ruce za zády přes opěradlo: Předkloň se přes opěradlo, nech ho vniknout zezadu a držet ti ruce za zády. Cíl: čtyři minuty a na stop tě musí pustit.|240|predklon!",
    "Přes opěradlo: Držíš se opěradla a on do tebe zezadu přiráží naplno. Cíl: čtyři minuty a najít společný rytmus.|240|predklon!",
    "Ruce o kolena: Předkloň se, opři si ruce o kolena a nech se milovat zezadu. Cíl: čtyři minuty a ani jednou se nenarovnat.|240|predklon_stoje",
    "Předkloněná ve stoje: Stůj předkloněná, nech ho vniknout zezadu a držet tě za boky. Cíl: čtyři minuty přírazů a nepodklesnout v kolenou.|240|predklon_stoje",
    "V náručí: Nech se zvednout do náruče, obtoč ho nohama a nech ho přirážet vestoje. Cíl: vydržet nahoře aspoň tři minuty.|180|zvednuta",
    "Donést tě ke zdi: Ať do tebe přiráží v náručí tak dlouho, jak zvládne, a pak tě opře o zeď. Cíl: dojít až ke zdi bez vyjití.|180|zvednuta",
    "Opora o zeď: Nech se zvednout, opřít zády o zeď a přirážet do tebe vestoje. Cíl: čtyři minuty a ani jednou tě nesmí položit.|240|zed",
    "Na kraji linky: Sedni si na kraj stolu nebo linky, nech ho vniknout a přitáhnout si tě za boky. Cíl: čtyři minuty přírazů a najít správnou výšku.|240|kraj_postele",
    "Na kraji postele čelem: Nech ho sednout si na kraj postele a nasaď se na něj čelem. Cíl: čtyři minuty jízdy a držet se navzájem za ramena.|240|klin_celem",
    "Zvedá tě pod zadečkem: Nasaď se mu na klín na kraji postele a nech se držet pod zadečkem a zvedat. Cíl: čtyři minuty, při kterých se nenamáháš.|240|klin_celem",
    "Opřený o čelo postele: Nech ho opřít se o čelo postele a nasaď se na něj. Cíl: čtyři minuty a přirážíš jen ty.|240|ona_nahore",
    "Vsedě opřený: Sedí opřený a ty na něm jezdíš čelem k němu. Cíl: pět minut a polibek ani jednou nepřerušit.|300|klin_celem",
    "Nejdřív se svlékni: Nech ho sednout si na židli, pomalu se před ním svlékni a pak se na něj nasaď. Cíl: nesmí na tebe sáhnout, dokud nejsi nahá.|300|zidle_celem",
    "Ruce za zády na židli: Jezdi na něm obkročmo na židli a nech si držet ruce za zády. Cíl: čtyři minuty a na stop tě musí hned pustit.|240|zidle_celem",
    "Nohy mezi jeho: Nasaď se mu na klín zády a dej si nohy mezi jeho. Cíl: čtyři minuty a tempo přírazů určuješ jen ty.|240|klin_zady",
    "Tempo určuje on: Nasaď se mu na klín zády a nech ho držet tě za boky a určovat tempo přírazů. Cíl: čtyři minuty a do tempa mu nemluvit.|240|klin_zady",
    "Čelem k opěradlu: Klekni si na židli čelem k opěradlu a nech ho vniknout do tebe zezadu. Cíl: čtyři minuty a opěradla se nepustit.|240|zidle_celem",
    "Opřený o postel: Nech ho sednout si na podlahu opřeného o postel a nasaď se na něj. Cíl: čtyři minuty a hýbat se jen boky.|240|lotos",
    "Na podlaze: Sedíte na koberci, je v tobě a oba jste opření dozadu o ruce. Cíl: čtyři minuty a udržet rovnováhu.|240|lotos",
    "Pověšená na krku: Pověs se mu na krk, obtoč ho nohama a nech ho přirážet vestoje. Cíl: vydržet nahoře aspoň tři minuty.|180|zvednuta",
    "Přesun bez vyjití: Nech se zvednout do náruče a posadit na kraj postele, aniž by z tebe vyšel. Cíl: čtyři minuty a ani jedno přerušení.|240|kraj_postele",
    "Klečí před tebou: Sedni si na kraj postele, nech ho kleknout si před tebe a vniknout do tebe. Cíl: čtyři minuty a ani jednou se nezvednout.|240|kraj_postele",
    "Nohy kolem jeho pasu: Nech ho vniknout na kraji postele a dej si nohy kolem jeho pasu. Cíl: čtyři minuty přírazů a nohy nespustit.|240|kraj_postele!",
    "Roztažené kotníky: Lež na kraji postele, nech si držet kotníky roztažené a přirážet. Cíl: čtyři minuty a kotníky ti nesmí pustit.|240|kraj_postele",
    "Od podlahy nahoru: Milujte se dvě minuty vleže, dvě vsedě a dvě ve stoje. Cíl: projít všechny tři výšky bez vyjití.|300|kraj_postele!",
    "Od zdi na židli: Nech ho začít přirážet vestoje u zdi a skončete vsedě na židli. Cíl: přejít bez jediného přerušení.|300|zed",
    "Ze židle do náruče: Začněte na židli a pak tě zvedne a bude přirážet vestoje. Cíl: přechod bez jediného vyjití.|300|zvednuta",
    "Přechod bez přerušení: Nech ho vniknout na lžičku a přejděte do misionáře, aniž by z tebe vyšel. Cíl: tři takové přechody za pět minut.|300|lzicka",
    "Přechod bez vyjití: Vystřídejte při sexu tři polohy a ani jednou z tebe nevyjde. Cíl: tři plynulé přechody za pět minut.|300|zezadu",
    "Opřená o kraj: Postav se opřená o kraj postele a nech se milovat zezadu. Cíl: čtyři minuty a ani jednou se nenarovnat.|240|predklon",
    "Postav se před zrcadlo a nech ho vniknout zezadu, ať se díváš.|240|zed",
    "Bok a noha v jeho rukou: Nech ho přirážet u zdi a držet ti jednou rukou bok a druhou zvednutou nohu. Cíl: čtyři minuty a nohu nespustit.|240|zed",
    "Zárubeň v rukou: Chyť se zárubně dveří a nech ho milovat tě zezadu. Cíl: čtyři minuty a ani jednou se nepustit.|240|predklon_stoje!",
    "Tiše ve stoje: Miluj se s ním vestoje u zdi a ani jeden z vás nesmí vydat hlásku. Cíl: čtyři minuty úplného ticha.|240|zed",
    "Klín na podlaze: Nasaď se mu na klín na podlaze a nech se obejmout oběma rukama. Cíl: čtyři minuty a objetí nerozpojit.|240|klin_podlaha",
    "Opřená mezi jeho nohama: Sedni si mu mezi nohy zády, opři se mu o hrudník a pomalu se na něm houpej. Cíl: čtyři minuty a ani jednou se nenarovnat.|240|klin_podlaha",
    "Na klíně zády: Jezdíš mu na klíně zády a on ti sahá zepředu na klitoris. Cíl: pět minut a ať tě nepřestane dráždit ani na chvíli.|300|klin_zady",
    "Ústy a pak na klín: Postav se mu mezi nohy a vezmi si ho do pusy, pak si mu sedni na klín a miluj se s ním. Cíl: minuta ústy a dvě na klíně.|180|oral_on_vsede",
    "Dokud tě udrží: Nech se zvednout na něj a přirážet v náručí, dokud tě udrží. Cíl: aspoň dvě minuty, než si sednete.|180|zvednuta",
    "Nohy kolem opěradla: Nasaď se na něj na židli a nohy si dej kolem opěradla. Cíl: čtyři minuty jízdy a nohy ani jednou nespustit.|240|zidle_celem",
    "Sedni si na něj a houpej se jen dopředu a dozadu.|240|klin_celem",
    "Oči v očích na klíně: Jezdi na něm čelem tak pomalu, ať si můžete celou dobu koukat do očí. Cíl: pět minut a ani jednou neuhnout.|300|klin_celem",
    "Pohled vsedě: Jezdíš na něm čelem k sobě a ani jeden neuhne očima. Cíl: pět minut a kdo uhne, plní úkol navíc.|300|klin_celem",
    "Předkloněná přes postel: Předkloň se přes postel a nech ho vniknout do tebe zezadu vestoje. Cíl: čtyři minuty přírazů a nezvednout se.|240|predklon!",
    "Lopatky pod dlaní: Předkloněná přes postel nech ho vniknout zezadu a položit ti ruku mezi lopatky. Cíl: čtyři minuty a tlak nezvyšovat.|240|predklon!",
    "Zápěstí vzadu ve stoje: Stůj předkloněná, nech ho vniknout zezadu a držet ti obě zápěstí vzadu. Cíl: čtyři minuty a na stop tě musí pustit.|240|predklon_stoje",
    "Rameno u zdi: Postav se ke zdi zády, nech ho vniknout zezadu a držet ti jednou rukou rameno. Cíl: čtyři minuty a nesmí tě pustit.|240|zed",
    "Noha na kraji postele: Postav se, zvedni si nohu na kraj postele a nech ho vniknout zezadu. Cíl: čtyři minuty vestoje a nohu nespustit.|240|zed",
    "Jedna noha nahoře: Stojíš s nohou opřenou vysoko, on ti drží koleno a přiráží. Cíl: vydržet tak dvě minuty.|240|zed",
    "Na židli zády a opřená: Nasaď se mu na klín zády a opři se mu dozadu o hrudník. Cíl: čtyři minuty a hýbat se jen boky.|240|klin_zady",
    "Otáčení na něm: Nasaď se na něj a pomalu se otáčej dokola, aniž by z tebe vyšel. Cíl: dvě celé otočky za pět minut.|300|ona_nahore",
    "Hýbe se jen on: Nasaď se mu na klín a nech všechny přírazy na něm. Cíl: čtyři minuty, při kterých se vůbec nepohneš.|240|klin_celem",
    "Zvedá tě on: Nasaď se mu na klín, drž se jeho ramen a nech ho, ať tě zvedá a přiráží. Cíl: čtyři minuty a sama se nenamáhat.|240|klin_celem",
    "Centimetr po centimetru: Sedej si na něj úplně pomalu, po centimetrech. Cíl: sestup musí trvat aspoň minutu.|180|klin_celem",
    "Pomalé usednutí: Nasazuješ se na něj celou minutu, ani o vteřinu dřív. Cíl: vydržet celou minutu bez jediného přírazu.|60|klin_celem",
    "V náručí ve stoje: Nech se držet kolem pasu, drž se jeho krku a nech ho přirážet vestoje. Cíl: vydržet nahoře aspoň tři minuty.|180|zvednuta",
    "Výš než on: Postav se na kraj postele, ať jsi výš, a nech ho vniknout do tebe zezadu. Cíl: čtyři minuty přírazů a udržet rovnováhu.|240|kraj_postele",
    "Za ruce k sobě: Sedni si na okraj postele, nech ho vniknout a přitahovat si tě za obě ruce. Cíl: čtyři minuty a ruce mu nepustit.|240|kraj_postele",
    "Za kolena k sobě: Na kraji postele si ho přitáhni koleny úplně k sobě a nech ho přirážet. Cíl: čtyři minuty a kolena nepovolit.|240|kraj_postele!",
    "Napříč postelí: Lehni si napříč postelí, nech ho stát z boku a vniknout do tebe. Cíl: čtyři minuty a najít úhel, který sedne oběma.|240|kraj_postele!",
    "Ze stoje do lehu: Nech ho přirážet vestoje a postupně skončete vleže bez vyjití. Cíl: plynulý přechod za pět minut.|300|zed",
    "Rozhoduješ ty: Nasaď se mu na klín tak, jak chceš – čelem, nebo zády. Cíl: čtyři minuty a po dvou minutách se otočit.|240|klin_celem",
    "Klečíš na židli: Klekni si na židli, opři se o opěradlo a nech ho přirážet zezadu vestoje. Cíl: čtyři minuty a nesmíš se pustit.|240|zidle_celem",
    "Konec na klíně: Nasaď se mu nakonec na klín, zůstaňte bez pohybu a jen se drž. Cíl: dvě minuty klidu a ani slovo.|120|klin_celem",
  ],
});
