// Kategorie 4 – Sex a polohy
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 4,
  name: "Sex a polohy",
  description: "Polohy po celém bytě, vibrace, první pouta a lehké plácnutí. Konečně naplno.",

  // Úkoly pro muže – pro potěšení ženy
  male: [
    "Na kraji linky: Posaď ji na linku, přitáhni si ji za boky k okraji a pomalu do ní vnikni. Cíl: tři minuty a polibek ani jednou nepřerušit.|180|kraj_postele",
    "Polštář a oční kontakt: Miluj ji v misionáři s polštářem pod zadečkem, pomalu a hluboko. Cíl: tři minuty a ani jednou neuhnout pohledem.|180|misionar_polstar",
    "Tempo určuje ona zezadu: Ona klečí opřená o opěradlo, ty jsi zezadu a nehýbeš se. Cíl: tři minuty, při kterých přiráží jen ona.|180|zezadu",
    "Vibrátor mezi vámi: Miluj ji v misionáři a celou dobu jí drž vibrátor na klitorisu. Cíl: tři minuty a ani jednou ho nesundat.|180|misionar",
    "Lžička a obě ruce: Vnikni do ní na lžičku zezadu, jednou rukou jí hlaď klitoris, druhou prsa. Cíl: čtyři minuty a obě ruce ve stejném rytmu.|240|lzicka",
    "Noha nahoře u zdi: Opři ji o zeď, zvedni jí jednu nohu a miluj se s ní vestoje. Cíl: dvě minuty a ani jednou nohu nespustit.|120|zed",
    "Pouta nad hlavou: Nasaď jí pouta s rukama před tělem, přidrž jí je nad hlavou a miluj ji v misionáři. Cíl: tři minuty a na stop ji hned uvolnit.|180|misionar",
    "Ruce na jejích bocích: Posaď si ji obkročmo na klín a rukama na bocích jí pomáhej s pohybem. Cíl: tři minuty a ani jednou ruce nesundat.|180|zidle_celem",
    "Desetkrát špičkou: Vnikni do ní jen špičkou a zase vyjdi, a to desetkrát. Cíl: až po desátém jednou pomalu celý a hluboko.|180|misionar",
    "Nohy na ramenou ve stoje: Ona leží na kraji postele, ty stojíš a její nohy máš na ramenou. Cíl: tři minuty a držet ji celou dobu za stehna.|180|nohy_ramena",
    "Předkloněná o stůl: Nech ji předklonit se a opřít o stůl a miluj ji zezadu s rukama na jejích bocích. Cíl: tři minuty a nesmí se narovnat.|180|predklon",
    "Tři rány a pak pomalu: Plácni ji bičíkem lehce přes zadeček třikrát a pak do ní zezadu pomalu vnikni. Cíl: mezi ranami vždy deset vteřin čekání.|180|zezadu",
    "Stop před vrcholem: Miluj se s ní a pokaždé, když se blíží vrchol, úplně se zastav. Cíl: třikrát ji zastavit a počtvrté ji nechat dojít.|240|misionar",
    "Opřená o stěnu sprchy: Nech ji opřít se rukama o stěnu a vnikni do ní zezadu. Cíl: dvě minuty a držet ji pevně za boky, ať neuklouzne.|120|zezadu_vzpr",
    "Kroužit místo přirážet: V misionáři se skoro nehýbej – jen pomalu krouž boky a tlač pánví na její klitoris. Cíl: dvě minuty a ani jeden příraz.|120|misionar",
    "Ona nahoře a vibrátor: Lehni si na záda, nech ji na sobě jezdit a přikládej jí vibrátor na klitoris. Cíl: tři minuty a ani jednou ho neodložit.|180|ona_nahore",
    "Poslepu a se změnou tempa: Zavaž jí oči a miluj se s ní. Každou minutu změň tempo. Cíl: čtyři různá tempa a ať ani jedno neuhodne dopředu.|240|misionar",
    "Pračka jako výška: Posaď ji na zapnutou pračku, roztáhni jí nohy a miluj se s ní vestoje. Cíl: dvě minuty a nechat vibrace pracovat za vás.|120|kraj_postele",
    "Zápěstí v jedné ruce: Miluj ji zezadu a jednou rukou jí drž obě zápěstí za zády. Cíl: dvě minuty a na stop ji hned pustit.|120|zezadu",
    "Kolena u prsou: Ona leží na zádech s koleny u prsou, ty klečíš a přirážíš hluboko. Cíl: dvacet přírazů a u každého pátého se zeptat, jestli to není moc.|120|nohy_ramena",
    "Horní noha na rameni: Ona leží na boku, ty klečíš, její horní nohu si opřeš o rameno a vnikneš do ní. Cíl: tři minuty a nohu ani jednou nespustit.|180|dvojita_bok",
    "Nová poloha každých 30 vteřin: Každou půlminutu vyberiš novou polohu a bez vytažení do ní přejdete. Cíl: šest poloh a nejvýš jedno vyklouznutí.|180",
    "Sleduje vás v zrcadle: Miluj se s ní před zrcadlem tak, aby na vás celou dobu viděla. Cíl: nepřestat, dokud sama nezavře oči.|180|zezadu_vzpr",
    "Zůstat a zakroutit: Dělej jen hluboké pomalé přírazy a po každém zůstaň hluboko v ní a zakruť boky. Cíl: dvacet přírazů a ani jeden mělký.|120|misionar",
    "Na břiše přes polštář: Nech ji ležet na břiše s polštářem pod boky, lehni si na ni a pomalu přirážej zezadu. Cíl: tři minuty a nezrychlit.|180|na_brise",
    "Slova a bradavky: Miluj se s ní, jemně jí stiskni bradavky a řekni jí, jak se v ní cítíš. Cíl: tři různé věty a u každé jedno stisknutí.|120|misionar",
    "Pouta a břicho: Nasaď jí pouta s rukama za zády, polož ji na břicho a miluj ji zezadu. Cíl: tři minuty a na stop ji hned odemknout.|180|na_brise",
    "Nohy k hrudi na stole: Polož ji zády na stůl, zvedni si její nohy k hrudi a miluj se s ní vestoje. Cíl: tři minuty a nohy ani jednou nespustit.|180|nohy_ramena",
    "Ruka zepředu, ona nahoře: Nech ji sednout si na tebe zády a hlaď jí klitoris, zatímco na tobě jezdí. Cíl: tři minuty a ruku ani jednou nesundat.|180|ona_nahore_zady",
    "Až na tvoje slovo: Miluj se s ní a ona smí dojít jen tehdy, až jí to dovolíš. Cíl: nechat ji čekat aspoň čtyři minuty, pak to dovolit.|300|misionar",
    "Třicet a třicet: Třicet vteřin rychle a intenzivně, pak třicet vteřin co nejpomaleji. Cíl: šest kol a čas ani jednou nesplést.|180|misionar",
    "Nohy kolem pasu: Miluj ji v misionáři a nech ji omotat si nohy kolem tvého pasu. Cíl: tři minuty a nepřestat ji líbat na krk.|180|misionar",
    "Vlasy v culíku: Miluj ji zezadu a vlasy jí přitom jemně drž v culíku. Cíl: dvě minuty a po každých třiceti vteřinách se zeptat, jestli je to dobré.|120|zezadu",
    "Každý určuje půlku: Ty vybereš polohu, ona tempo, a oba to plníte úplně přesně. Cíl: tři kola a ani jednou si nedělat po svém.|180|misionar",
    "Čekat na pobídku: Pomalu do ní vnikni a pak se vůbec nehýbej. Cíl: nezačít, dokud tě sama nepopožene boky nebo slovem.|180|misionar",
    "Oči v zrcadle: Nech ji opřít se o umyvadlo a vnikni do ní zezadu. Cíl: dvě minuty a nespustit z ní v zrcadle oči.|120|zezadu_vzpr",
    "Pomalu a hluboko: Miluj ji v misionáři jen pomalými hlubokými přírazy. Cíl: tři minuty a ani jeden rychlý příraz.|180|misionar",
    "Vibrátor si drží sama: Miluj ji zezadu a dej jí do ruky vibrátor, ať si ho drží sama. Cíl: tři minuty a nesáhnout na něj ani jednou.|180|zezadu",
    "Plácnutí do rytmu: Miluj ji zezadu a plácej ji dlaní po zadečku přesně do rytmu přírazů. Cíl: dvacet plácnutí a síla pokaždé stejná.|90|zezadu",
    "Přitáhnout si ji za boky: Ona leží na kraji gauče, ty klečíš na zemi a přitahuješ si ji za boky. Cíl: tři minuty a ani jednou ji nepustit.|180|kraj_postele",
    "Čelem na boku: Miluj se s ní na boku čelem k sobě s propletenýma nohama. Cíl: tři minuty a nepřerušit polibek ani jednou.|180|propletene",
    "Chyť ji jemně za zápěstí a přidrž jí je nad hlavou na posteli. Pak ji pomalu miluj.|180",
    "Miluj ji vestoje zezadu u okna se zataženými závěsy, ona se drží parapetu.|120",
    "Poloha „kovadlina“: ona leží na zádech a přitáhne si nohy k hlavě (jen pokud je to pro ni pohodlné), ty přirážíš shora.|90",
    "Obtočená nohama: Sedni si na kraj postele, posaď si ji na klín čelem k sobě a nech ji obtočit se nohama. Cíl: tři minuty a pohyb dělá jen ona.|180|kraj_postele",
    "Spoutej jí ruce pouty nad hlavou (třeba k čelu postele) a pomalu se s ní miluj v misionáři.|180",
    "Nezkoušená poloha: Vyber polohu, kterou jste spolu ještě nikdy nedělali, a zkuste ji. Cíl: vydržet v ní tři minuty a pak říct, jestli stojí za zopakování.|180",
    "Miluj se s ní a po každém třetím přírazu jí polib bradavku.|120",
    "Ona se opře lokty o kuchyňskou linku a ty do ní vnikneš zezadu. Hlaď ji přitom po zádech.|180",
    "Opřená o tvá kolena: Posaď si ji na sebe zády a nech ji opřít se rukama o tvá kolena. Cíl: tři minuty a tempo určuje jen ona.|180|ona_nahore_zady",
    "Při sexu jí šeptej do ucha přesně, co s ní děláš a jak se ti to líbí.|120",
    "Při sexu použij oba vibrátory: jeden jí přilož na klitoris, druhý ke kořeni svého penisu, ať vibrace cítíte oba.|180",
    "Rozkaž jí, ať se otočí a předkloní. Pak ji odměň pomalými přírazy zezadu.|120",
    "Nohy u sebe: Nech ji ležet na zádech s nohama u sebe a její nohy měj mezi svými. Bude to těsnější. Cíl: dvacet pomalých přírazů a nezrychlit.|120|misionar",
    "Miluj se s ní na jídelní židli: ty sedíš, ona na tobě sedí obkročmo a opírá se o stůl za sebou.|180",
    "Při sexu z ní vyjdi, olízni ji a pak do ní zase vnikni. Třikrát dokola.",
    "Lehni si na ni zezadu, když leží na břiše, a propleť s ní prsty nad hlavou.|180",
    "Miluj ji zezadu na gauči, zatímco si ona hladí klitoris vibrátorem. Tempo řídíš ty.|180",
    "Plácnutí a příraz: Plácni ji bičíkem lehce po vnitřní straně stehen a hned do ní pomalu vnikni. Cíl: pět takových dvojic, síla vždy stejná.|180|misionar",
    "Zvedni ji do náruče, ať tě obejme nohama, a udělej pár přírazů vestoje. Pak ji polož na postel (jen pokud to bezpečně zvládnete).|60",
    "Miluj se s ní v misionáři a po každých 10 přírazech ji polib a řekni jí, co na ní miluješ.|180",
    "Ona leží na posteli na boku, ty klečíš za ní, držíš její horní nohu nahoře a vnikneš do ní.|180",
    "Devět a jedna: Devět mělkých přírazů a jeden hluboký, pak osm a dva, a tak dál. Cíl: dojít až k jednomu mělkému a devíti hlubokým bez chyby.|300|misionar",
    "Nasaď jí pouta, sedni si na gauč a posaď si ji na klín zády k sobě. Hlaď ji, zatímco se na tobě pohybuje.|180",
    "Ona si sedne na okraj vany, ty klečíš ve vaně před ní a miluješ se s ní.|120",
    "Otoč ji zády k sobě u dveří ložnice, přitiskni ji ke dveřím a vnikni do ní zezadu.|120",
    "Poruč jí, že nesmí vydat ani hlásku. Pak ji miluj tak dobře, aby to nevydržela.|120",
    "Ona je nahoře, ale ty ji držíš za boky a určuješ tempo zespodu.|180",
    "Miluj se s ní a po každé minutě se zastav a zeptej se: rychleji, pomaleji, nebo silněji?|240",
    "Ona leží na zádech s nohama opřenýma o tvůj hrudník, ty klečíš a miluješ se s ní. Hlaď jí přitom chodidla.|120",
    "Miluj ji zezadu vestoje, ona si přitom opře jednu nohu o židli nebo okraj vany.|120",
    "Lehni si na záda a nech ji nahoře. Mezi vašimi těly jí drž vibrátor přitisknutý na klitoris.|180",
    "Jemně jí polož ruku na krk (bez tlaku na hrdlo), dívej se jí do očí a pomalu přirážej.|120",
    "Ona leží na zádech na kraji jídelního stolu, ty stojíš a miluješ se s ní. Jednou rukou jí hlaď klitoris.|180",
    "Pět ran při sexu: Miluj ji zezadu a dej jí pět plácnutí bičíkem na zadeček. Ona je počítá nahlas. Cíl: síla pokaždé stejná, ani jedna tvrdší.|180|zezadu",
    "Lehněte si pod deku na gauč do lžičky a miluj ji zezadu pomalu a líně, s polibky na krk.|240",
    "Miluj se s ní v poloze, kterou si vybere – a dej do toho všechno.|240",
    "Poslepu a čekat: Zavaž jí oči, ať si lehne a roztáhne nohy, a nech ji čekat. Cíl: vniknout do ní nejdřív po celé minutě ticha.|180|misionar",
    "V misionáři se posuň trochu výš a přirážej pánví tak, aby ses třel o její klitoris.|120",
    "Ona klečí na zemi u gauče a hrudníkem se opírá o sedák, ty do ní vnikneš zezadu.|180",
    "Obrácená jezdkyně: ležíš na zádech a ona na tobě sedí zády k tobě. Hlaď ji po zadečku a zádech.|180",
    "Při sexu jí jemně chytni vlasy u kořínků a zakloň jí hlavu, pak ji polib na krk.|90",
    "Ona stojí u kuchyňské linky a ty ji miluješ zezadu, oběma rukama jí přitom hladíš prsa.|120",
    "Miluj se s ní co nejpomaleji – každý příraz ať trvá aspoň 5 vteřin.|180",
    "Spoutej jí ruce pouty za zády a nech ji, ať si na tebe sedne. Ty ji držíš za boky, ať nespadne.|180",
    "V misionáři se přestaň hýbat a jen ji líbej. Hýbat se smí jen ona pod tebou.|120",
    "Vyzkoušejte polohu „nůžky“: ležíte na boku, nohy máte propletené do tvaru X a ty do ní vnikneš.|180",
    "Ona leží na břiše, vsuň jí pod klín vibrátor přitisknutý na klitoris a miluj ji zezadu.|180",
    "Při každém hlubokém přírazu jí řekni, že je tvoje. Při každém mělkém, že je krásná.|120",
    "Rozkaž jí, ať si sedne na kraj stolu a roztáhne nohy. Dívej se na ni 10 vteřin a pak ji miluj.|180",
    "Ona leží na zádech se zvednutýma a roztaženýma nohama, ty ji držíš za kotníky a miluješ se s ní.|120",
    "V chodbě se ona opře rukama o zeď a ty ji miluješ vestoje zezadu, jednou rukou ji přitom hladíš mezi nohama.|120",
    "Miluj se s ní a popros ji, ať ti řekne, až bude blízko. Pak zrychli.",
    "Sedni si na gauč, ona si nad tebe klekne obkročmo a pomalu si na tebe sedá.|180",
    "Při sexu v misionáři jí vezmi zápěstí a přidrž je u polštáře. Pak zpomal.|120",
    "Plácni ji dvakrát dlaní po zadečku, pak ho pohlaď a polib. A pak do ní vnikni zezadu.",
    "Miluj se s ní na pračce – ona sedí, ty stojíš.|120",
    "Poloha lotos: sedíš na posteli se zkříženýma nohama a ona ti sedí obkročmo na klíně. Pomalu se spolu houpejte.|180",
    "Ona klečí na posteli, ty ji miluješ zezadu a vibrátorem jí zespodu hladíš klitoris.|180",
    "Při sexu vystřídejte tři polohy, ale při přechodu z ní nevyklouzni.",
    "Miluj se s ní v misionáři hluboko a každých 20 vteřin jí olízni bradavku.|180",
    "Připoutej jí ruce pouty k čelu postele, zavaž jí oči a miluj se s ní. Ona neví, kdy přijde další příraz.|180",
    "Ona se předkloní přes opěradlo gauče a ty ji miluješ vestoje zezadu.|120",
    "Rozkaž jí, ať tě prosí o každý příraz. Když poprosí, splň to.|120",
    "Ona leží na zádech na gauči s jednou nohou na opěradle, ty jsi mezi jejíma nohama a miluješ se s ní.|180",
    "Ať si lehne na posteli na břicho s nohama u sebe. Lehni si na ni obkročmo a vnikni do ní zezadu.|180",
    "Při sexu jí palcem kruž po klitorisu. Nepřestávej, dokud nedojde.",
    "Ve sprše stojí ona zády k tobě s nohou na okraji vany a ty do ní vnikneš zezadu. Voda teče na vás oba.|120",
    "Postav ji před zrcadlo, ať se opře rukama o komodu, a vnikni do ní zezadu. Dívej se jí v zrcadle do očí.|120",
    "Zatímco ji miluješ v misionáři, přikaž jí, ať si sama hladí prsa a nepřestává.|180",
    "Když na tobě jezdí, lehce ji plácni bičíkem přes stehno pokaždé, když zpomalí.|120",
    "Ona leží na břiše, ty na boku těsně vedle ní a vnikneš do ní zezadu.|180",
    "Nech ji ležet na kraji postele s nohama na zemi, zvedni jí boky a miluj se s ní vkleče.|180",
    "Zakaž jí dotýkat se tebe rukama. Když tě chytí, zpomal na minimum.|180",
    "Nech ji, ať si vybere místo v bytě, kde jste to ještě nedělali. Tam se s ní miluj.",
    "Ona první: Dopřej jí orgasmus jakkoli chceš. Cíl: musí dojít dřív než ty – jinak úkol nepočítá.|300|misionar",

    // Karty s cílem
    "Jezdkyně: Lehni si na záda, ona si na tebe sedne obkročmo a zavede si tě do sebe. Ty se nesmíš hýbat, jen jí palcem hladíš klitoris. Cíl: aby dosáhla vrcholu jen svými pohyby.|240",
    "Lžička s vibrátorem: Oba ležíte na boku, ty za ní, a vnikneš do ní zezadu. Ona si drží vibrátor na klitorisu. Cíl: přirážet pomalu a hluboko, dokud nedojde.|240",
    "Obrácená jezdkyně na gauči: Ty sedíš na gauči, ona si na tebe sedne zády k tobě a opře se rukama o tvá kolena. Cíl: držet ji za boky a pomáhat jí s rytmem tři minuty bez zastavení.|180",
    "Pět poloh za pět minut: Každou minutu změňte polohu – misionář, ona nahoře, zezadu, lžička, kraj postele. Cíl: nevyklouznout víc než dvakrát.|300|misionar",
    "Kraj stolu: Ona leží zády na stole se zadečkem na kraji, ty stojíš a její kotníky máš na ramenou. Cíl: třicet pomalých přírazů, pak třicet rychlých.|180|nohy_ramena",
    "Na loktech: Ona klečí na posteli opřená o lokty se zadečkem nahoře, ty zezadu. Jednou rukou ji hladíš po zádech. Cíl: po každém desátém přírazu zůstat hluboko 3 vteřiny.|180",
    "Spoutané ruce vpředu: Nasaď jí pouta s rukama před tělem. Ona leží na zádech s rukama nad hlavou, ty jí je přidržuješ a miluješ se s ní v misionáři. Cíl: celou dobu se jí dívat do očí.|180",
    "Noha nahoru: Ona stojí zády ke zdi, jednu nohu jí zvedneš a podepřeš v podkolení. Vnikni do ní vestoje. Cíl: najít úhel, při kterém se tvoje pánev tře o její klitoris.|120",
    "Houpačka: Sedni si na pevnou židli bez opěrek, ona si sedne obkročmo čelem k tobě. Opřete se čely a houpejte se místo přirážení. Cíl: tři minuty něžného tempa s polibky.|180",
    "Její číslo: Ona zvolí číslo od 20 do 50. Uděláš přesně tolik přírazů, každý pomalejší a hlubší. Cíl: na konci se zeptat, jestli chce ještě jednou tolik.",
    "Kolébka: Ona leží na zádech s koleny u prsou a chodidly na tvém hrudníku, ty klečíš. Cíl: tlačit pomalu, aby cítila každý centimetr – dvě minuty.|120",
    "Oči v zrcadle: Ona stojí předkloněná, rukama opřená o komodu před zrcadlem, ty zezadu. Cíl: dívat se jí do očí v zrcadle – kdo první uhne, zrychluje.|180",
    "Bičík po deseti: Ona je na všech čtyřech na posteli, ty zezadu. Po každých deseti přírazech jí dej lehké plácnutí bičíkem na zadeček. Cíl: ona určuje, jestli silněji, nebo jemněji.|180",
    "Těsný misionář: Ona leží na zádech s nataženýma nohama u sebe, ty klečíš obkročmo nad jejími stehny. Cíl: pomalé přírazy v těsném sevření, dokud nezasténá.|180",
    "Linka zezadu s rukou: Ona se opře předloktími o kuchyňskou linku a vystrčí zadeček, ty jsi zezadu a jednu ruku máš na jejím klitorisu. Cíl: ruka ve stejném rytmu jako přírazy.|180",
    "Jízda na povel: Ona je nahoře a ty říkáš jen „rychleji“, „pomaleji“, „hlouběji“ a „zastav“. Cíl: řídit ji hlasem až k jejímu orgasmu.|240",
    "Ona první: Miluj se s ní pět minut a nesmíš dojít. Když se blížíš, zastav a hlaď ji rukou. Cíl: ona musí dojít jako první.|300",
    "Okraj vany: Ona sedí na kraji vany na ručníku, ty klečíš na podložce a vnikneš do ní. Cíl: pomalé přírazy, zatímco na vás teče sprcha.|120",
    "Zápěstí za zády: Ona se přehne přes opěradlo gauče a ty jí zezadu držíš obě zápěstí za zády. Cíl: při každém přírazu si ji jemně přitáhnout za zápěstí.|120",
    "Nůžky čelem: Ona leží na boku, ty na boku čelem k ní, její horní noha je přes tvůj bok. Cíl: pomalé přírazy a líbání bez přestávky.|180",
    "Polštář pod klínem: Ona leží na břiše se dvěma polštáři pod boky, ty ležíš na ní zezadu. Cíl: přirážet tak, aby se klitorisem třela o polštář.|180",
    "Tep: Ona ti položí ruku na srdce. Přirážej v rytmu svého tepu. Cíl: jak se ti zrychluje tep, zrychluje i tempo.|180",
    "Klika u dveří: Přitiskni ji čelem ke dveřím ložnice, ona se opírá dlaněmi, ty zezadu vestoje s rukama na jejích prsou. Cíl: aby se musela chytit kliky.|120",
    "Čtyři styly jízdy: Ona je nahoře a každou minutu změní styl – nahoru a dolů, krouživě, dopředu a dozadu, rychle. Cíl: najít její oblíbený a v něm ji nechat dojít.|240",
    "Bičík na stehno: Misionář s jejíma nohama od sebe. Při každém hlubokém přírazu jí lehce přetáhni bičíkem vnější stranu stehna. Cíl: deset plácnutí, sílu určuje ona.|120",
    "Poloviční start: Vnikni do ní jen do poloviny a 30 vteřin se hýbej jen nepatrně. Pak pomalu celý. Cíl: aby si tě sama stáhla hlouběji.|90",
    "Líný gauč: Lehněte si na gauč do lžičky pod deku a miluj ji líně, skoro bez pohybu, s rukou na jejím klínu. Cíl: udržet to pět minut.|300",
    "Linka a paty: Posaď ji na kraj kuchyňské linky a vnikni do ní vestoje. Ona tě obejme nohama. Cíl: tři minuty, tempo řídí ona patami na tvém zadku.|180",
    "Poslepu aranžovaná: Zavaž jí oči a rukama ji aranžuj do polohy – otoč ji, zvedni jí nohu, předkloň ji – a pak do ní vnikni. Cíl: tři různé polohy, každou pozná až tělem.|240",
    "Motýl: Ona leží na zádech na kraji postele, boky má na polštáři a nohy na tvých ramenou. Ty stojíš a držíš ji za boky. Cíl: přirážet pod úhlem nahoru, na bod G.|180",
    "Spoutaná jezdkyně: Nasaď jí pouta za zády a pomoz jí posadit se na tebe. Držíš ji za boky, aby nespadla. Cíl: ona se hýbe jen boky, ty ji jen držíš.|180",
    "Bez rukou oba: Ani jeden z vás nesmí použít ruce. Najděte polohu a milujte se. Cíl: tři minuty bez rukou.|180",
    "Mělké a hluboké: Tři mělké přírazy a jeden hluboký, pak dva a dva, pak jeden mělký a tři hluboké. Opakuj. Cíl: nesplést se v počítání.|180",
    "Přes područku: Nech ji lehnout si břichem přes područku gauče a miluj ji zezadu. Cíl: přirážet tak, až se musí chytit polštářů.|180|predklon",
    "Dvě otočky: Začni v misionáři, pak ji bez vytažení přetoč na bok a nakonec na břicho. Cíl: zvládnout obě otočky, aniž bys z ní vyklouzl.",
    "Kousavé polibky: V misionáři jí při každém hlubokém přírazu dej kousavý polibek na krk nebo rameno. Cíl: najít místo, kde se prohne nejvíc.|120",
    "Vibrátor mezi břichy: Misionář s vibrátorem mezi vašimi podbřišky na jejím klitorisu. Pohybuj se krouživě, ne dovnitř a ven. Cíl: aby vibrátor nevypadl a ona došla.|180",
    "Řízení nohama: Misionář, ona tě obejme nohama kolem pasu. Hýbeš se jen tehdy, když si tě patami přitáhne. Cíl: nechat se řídit dvě minuty.|120",
    "Rytmus pračky: Ona se opře o zapnutou pračku a předkloní se, ty zezadu. Cíl: přirážet v rytmu otáček.|120",
    "Lotos: Ty sedíš na posteli se zkříženýma nohama, ona ti sedí na klíně čelem k tobě a obejme tě nohama. Cíl: tři minuty houpání bez přirážení, s pohledem do očí.|180",
    "Povel otoč se: Kdykoli řekneš „otoč se“, změní polohu podle tebe. Cíl: čtyři povely za čtyři minuty – poslední poloha je její oblíbená.|240",
    "Stojící lžička u okna: Oba stojíte, ona zády k tobě u okna se zataženými závěsy. Pokrč kolena a vnikni do ní zezadu. Cíl: jednou rukou jí hladit klitoris, druhou ji držet kolem pasu.|120",
    "Každý čtvrtý: Zezadu na posteli ji plácni dlaní po zadečku při každém čtvrtém přírazu. Cíl: ona nahlas počítá do dvaceti.|180",
    "Teplo, přihořívá, hoří: Pomalými přírazy hledej úhel a ona říká „teplo“, „přihořívá“ nebo „hoří“. Cíl: najít „hoří“ a zůstat tam.|180",
    "Sedátko: Sedni si na kraj postele, ona si na tebe sedne zády k tobě s nohama přes tvá stehna a opře se o tvůj hrudník. Cíl: rukama jí hladit prsa a klitoris, dokud nedojde.|180",
    "Noha na opěradle: Ona leží na zádech na gauči, jednu nohu opřenou o opěradlo, druhou na zemi, ty klečíš mezi nimi. Cíl: každý její vzdech odměnit polibkem.|180",
    "Dovolení: Nasaď jí pouta a miluj ji. Dojít smí až na tvé „teď“. Cíl: říct „teď“ přesně ve chvíli, kdy je na hraně.",
    "Nehybný: Zůstaň v misionáři nehybně v ní a ona se musí hýbat pod tebou. Cíl: aby tě prosila, ať se pohneš.|90",
    "Ruce na zdi: Opři ji zády o zeď, zvedni jí ruce nad hlavu a drž je jednou rukou. Vnikni do ní vestoje – ať si stoupne na špičky nebo na nízkou stoličku. Cíl: dvě minuty pomalu.|120",
    "Kdo zrychlí: Miluj se s ní tak pomalu, jak to jen jde. Cíl: tři minuty – kdo první zrychlí, plní úkol navíc.|180",
    "Tři minuty, tři pravidla: První minutu úplně potichu, druhou smíte sténat, třetí musíte říkat, co cítíte. Cíl: dodržet všechna pravidla.|180",
    "Kolena k ramenům: Ona leží s koleny u tvých ramen, ty nad ní. Cíl: dvacet pomalých hlubokých přírazů a u každého pátého se zeptat, jestli to není moc.|120|nohy_ramena",
    "Stisk při zrychlení: Ona na tobě jezdí a ty jí hladíš a mačkáš prsa. Cíl: kdykoli zrychlí, jemně jí stiskni bradavky.|180",
    "Vibrátor u kořene: Přilož vibrátor ke kořeni svého penisu, zatímco jsi v ní, ať vibrace přecházejí do ní. Cíl: najít polohu, kde to cítí nejvíc.|180",
    "Sázka: Milujte se v libovolné poloze. Když dojdeš dřív než ona, dlužíš jí pusu až do jejího orgasmu. Cíl: ona musí dojít tak či tak.",
    "Poloha snů: Zeptej se jí, jakou polohu si nejvíc přeje, a udělej ji co nejlépe. Cíl: po skončení ti dá známku od 1 do 10.|240",
  ],

  // Úkoly pro ženu – pro potěšení muže
  female: [
    "Nohama si ho přitáhnout: Posaď se na linku, přitáhni si ho nohama k sobě a nech ho do sebe vniknout. Cíl: tři minuty a polibek nepřerušit.|180|kraj_postele",
    "Pomalu a do očí: Sedni si na něj a jezdi na něm pomalu a hluboko. Cíl: tři minuty a ani jednou neuhnout pohledem.|180|ona_nahore",
    "Přirážíš zezadu ty: Klekni si, opři se o opěradlo a přirážej zadečkem proti němu. Cíl: tři minuty, při kterých se on vůbec nepohne.|180|zezadu",
    "Vibrátor na varlatech: Jezdi na něm a celou dobu mu drž vibrátor na varlatech. Cíl: tři minuty a ani jednou ho nesundat.|180|ona_nahore",
    "Lžička a jeho ruka: Lehněte si na lžičku, přirážej proti němu zadečkem a jeho ruku si polož na prsa. Cíl: čtyři minuty a ruku mu nedovolit sundat.|240|lzicka",
    "Noha kolem jeho boku: Opři se o zeď, zvedni nohu a obejmi ho s ní kolem boku. Cíl: dvě minuty vestoje a nohu ani jednou nespustit.|120|zed",
    "Spoutaný pod tebou: Nasaď mu pouta s rukama nad hlavou a jezdi na něm. Cíl: tři minuty a nesmí se tě dotknout – na stop ho hned odemkni.|180|ona_nahore",
    "Židle bez opěrek: Posaď ho na židli, sedni si na něj čelem a drž se jeho ramen. Cíl: tři minuty a nesmí ti pomáhat rukama.|180|zidle_celem",
    "Desetkrát jen špička: Pusť do sebe jen špičku a zase se nadzvedni, a to desetkrát. Cíl: až po desátém se na něj posadit celá.|180|ona_nahore",
    "Přitahuj si ho za zadek: Lehni si na kraj postele, dej mu nohy na ramena a rukama na jeho zadku si ho přitahuj. Cíl: tři minuty a tempo určuješ ty.|180|nohy_ramena",
    "Řekni mu, ať zrychlí: Předkloň se o stůl a nech se milovat zezadu. Cíl: třikrát se otočit přes rameno a nahlas mu říct, ať zrychlí.|180|predklon",
    "Plácni ho bičíkem lehce přes zadek třikrát a pak se na něj posaď.",
    "Zastavit ho před vrcholem: Jezdi na něm a pokaždé, když se blíží vrchol, se úplně zastav. Cíl: třikrát ho zastavit a počtvrté ho nechat dojít.|240|ona_nahore",
    "Opřená o stěnu: Opři se rukama o stěnu sprchy a vystrč na něj zadeček. Cíl: dvě minuty a nechat ho, ať tě pevně drží za boky.|120|zezadu_vzpr",
    "Kroužení místo skákání: Sedni si na něj a místo pohybu nahoru a dolů jen pomalu krouž boky. Cíl: padesát kroužků a ani jednou se nezvednout.|120|ona_nahore",
    "Jízda a vibrace: Jezdi na něm a přitom mu vibrátorem hlaď bradavky. Cíl: tři minuty a obojí ve stejném tempu.|180|ona_nahore",
    "Poslepu a se změnami: Zavaž mu oči a miluj se s ním. Každou minutu změň tempo. Cíl: čtyři různá tempa a ať ani jedno neuhodne dopředu.|240|ona_nahore",
    "Pračka jako sedátko: Sedni si na zapnutou pračku, roztáhni nohy a přitáhni si ho k sobě. Cíl: dvě minuty a nechat vibrace pracovat za vás.|120|kraj_postele",
    "Spoutaný na gauči: Nasaď mu pouta s rukama za zády, posaď ho na gauč a sedni si na něj. Cíl: tři minuty a na stop ho hned odemknout.|180|zidle_celem",
    "Kolena k prsům: Lehni si na záda, přitáhni si kolena k prsům a nech ho přirážet hluboko. Cíl: dvacet přírazů a u každého pátého říct, jestli to stačí.|120|nohy_ramena",
    "Noha na jeho rameni: Lehni si na bok, horní nohu mu dej na rameno a nech ho do sebe vniknout. Cíl: tři minuty a nohu ani jednou nespustit.|180|dvojita_bok",
    "Polohový maraton: Každých třicet vteřin mu řekni novou polohu a on ji musí hned zaujmout. Cíl: šest poloh a nejvýš jedno vyklouznutí.|180|ona_nahore",
    "Dívá se v zrcadle: Miluj se s ním před zrcadlem tak, aby na vás celou dobu viděl. Cíl: nepřestat, dokud sám nezavře oči.|180|zezadu_vzpr",
    "Stáhnout a zůstat: Jezdi na něm hluboce a pomalu a dole vždycky chvíli zůstaň a stáhni svaly. Cíl: dvacet pohybů a u každého jedno stažení.|120|ona_nahore",
    "Na břiše a proti němu: Lehni si na břicho s polštářem pod boky a přirážej proti němu zadečkem. Cíl: tři minuty, při kterých se on skoro nehýbe.|180|na_brise",
    "Slova a jeho bradavky: Miluj se s ním, jemně mu stiskni bradavky a řekni mu, jak se v tobě cítí. Cíl: tři různé věty a u každé jedno stisknutí.|120|ona_nahore",
    "Jeho zápěstí nad hlavou: Chyť ho za zápěstí, přidrž mu je nad hlavou a jezdi na něm. Cíl: tři minuty a ani jednou ho nepustit.|180|ona_nahore",
    "Na stole a on stojí: Lehni si zády na stůl, nohy mu dej na ramena a nech ho milovat se s tebou vestoje. Cíl: tři minuty a nohy nespustit.|180|nohy_ramena",
    "Jeho ruce na tvých prsou: Posaď ho do křesla, sedni si na něj zády a jeho ruce si polož na prsa. Cíl: tři minuty a nenechat ho je posunout jinam.|180|klin_zady",
    "Dovolíš mu to ty: Jezdi na něm a on smí dojít, až mu to dovolíš. Cíl: nechat ho čekat aspoň čtyři minuty, pak to dovolit.|300|ona_nahore",
    "Naplno a skoro nic: Půl minuty na něm jezdi jako o život, pak půl minuty skoro bez pohybu. Cíl: šest kol a čas ani jednou nesplést.|180|ona_nahore",
    "Paty na jeho zádech: V misionáři si ho obtoč nohama kolem pasu a patami si ho přitahuj k sobě. Cíl: tři minuty, při kterých tempo určuješ jen ty.|180|misionar",
    "Pohled přes rameno: Klekni si na všechny čtyři a nech se milovat zezadu. Cíl: dvě minuty a celou dobu se na něj dívat přes rameno.|120|zezadu",
    "Půlka pro každého: Ty vybereš polohu, on tempo, a oba to plníte úplně přesně. Cíl: tři kola a ani jednou si nedělat po svém.|180|ona_nahore",
    "Nehýbej se: Posaď se na něj celá a vůbec se nehýbej. Cíl: nezačít, dokud tě sám nezačne prosit.|180|ona_nahore",
    "V koupelně se opři o umyvadlo, on zezadu, a dívej se na něj do zrcadla.|120",
    "Na koberci: Nech ho lehnout si na koberec a jezdi na něm s rukama opřenýma o jeho hrudník. Cíl: tři minuty a ani jednou se nezastavit.|180|ona_nahore",
    "Vibrace pro oba: Nech se milovat zezadu a sama si přikládej vibrátor na klitoris. Cíl: tři minuty a ani jednou ho neodložit.|180|zezadu",
    "Rytmus dlaní: Když je nad tebou, plácej ho dlaní po zadku přesně v tempu, jakým chceš, aby přirážel. Cíl: dvacet plácnutí a ať se do nich trefí.|90|misionar",
    "Posaď ho na kraj gauče a klekni si nad něj. Pomalu si na něj sedej.|180",
    "Miluj se s ním na boku čelem k sobě, nohy propletené, pusy u sebe.|180",
    "Obkroč ho, drž mu ruce u polštáře a pomalu na něm jezdi.|180",
    "U okna se zataženými závěsy se opři o parapet a nech ho, ať tě miluje zezadu.|120",
    "Lehni si na záda a zvedni nohy vysoko – nech ho, ať ti je drží za kotníky.|90",
    "Sedni si mu na klín na kraji postele čelem k němu a obejmi ho nohama.|180",
    "Spoutej mu ruce pouty (třeba k čelu postele nebo za zády) a pomalu na něm jezdi. Líbat tě smí, ale jen když se nakloníš ty.|180",
    "Vymysli polohu, kterou jste spolu ještě nezkusili, a naveď ho do ní.|180",
    "Jezdi na něm a po každém třetím pohybu se k němu nakloň, ať ti může políbit prsa.|120",
    "Opři se lokty o kuchyňskou linku, vystrč na něj zadeček a nech ho, ať tě miluje zezadu a hladí po zádech.|180",
    "Opřená o jeho kolena: Sedni si na něj zády a opři se rukama o jeho kolena. Cíl: tři minuty a nenechat ho, aby ti pomáhal.|180|ona_nahore_zady",
    "Při sexu mu šeptej do ucha přesně, co ti dělá a jak se ti to líbí.|120",
    "Při sexu použij oba vibrátory: jeden mu přilož na varlata, druhý sobě na klitoris.|180",
    "Rozkaž mu, ať si lehne na záda a nehýbe se. Pak ho odměň pomalou jízdou.|120",
    "Lehni si na záda, dej nohy k sobě a nech ho do sebe vniknout – bude to pro něj těsnější.|120",
    "Posaď ho na jídelní židli a sedni si na něj obkročmo, opřená o stůl za sebou.|180",
    "Při jízdě z něj slez, olízni ho a pak si na něj zase sedni. Třikrát dokola.",
    "Lehni si na břicho a nech ho, ať si na tebe lehne a propletete prsty nad hlavou.|180",
    "Klekni si na gauč a nech ho, ať tě miluje zezadu. Mezitím mu sáhni rukou mezi nohy a hlaď mu varlata.|180",
    "Rána a hned dolů: Plácni ho bičíkem lehce po stehnech a hned si na něj sedni. Cíl: pět takových dvojic, síla vždy stejná.|180|ona_nahore",
    "Obejmi ho nohama kolem pasu, když stojí, a nech ho, ať tě chvíli drží (jen pokud to zvládnete bezpečně). Pak si lehni na postel a stáhni ho na sebe.|60",
    "Jezdi na něm a vždy po 10 pohybech ho polib a řekni mu, co na něm miluješ.|180",
    "Lehni si na posteli na bok a nech ho klečet za tebou. Horní nohu mu dej do ruky a nech ho do sebe vniknout.|180",
    "Devět mělkých a jeden: Devět mělkých pohybů a jeden hluboký, pak osm a dva, a tak dál. Cíl: dojít až k jednomu mělkému a devíti hlubokým bez chyby.|300|ona_nahore",
    "Nasaď mu pouta, posaď ho na gauč a sedni si na něj zády k němu. Pohybuj se, jak chceš ty.|180",
    "Okraj vany: Posaď ho na okraj vany a sedni si na něj čelem k němu. Cíl: dvě minuty a držet se jeho ramen, ať nikdo neuklouzne.|120|zidle_celem",
    "Opři se o dveře ložnice, vystrč na něj zadeček a nech ho, ať tě miluje zezadu.|120",
    "Poruč mu, že nesmí vydat ani hlásku. Pak na něm jezdi tak dobře, aby to nevydržel.|120",
    "Jsi nahoře, ale nech ho, ať tě drží za boky a určuje tempo zespodu.|180",
    "Miluj se s ním a po každé minutě se zastav a zeptej se: rychleji, pomaleji, nebo silněji?|240",
    "Lehni si na záda a nohy mu dej na hruď. Chodidly ho hlaď po bradavkách.|120",
    "Postav se zády k němu, opři si jednu nohu o židli nebo okraj vany a přitáhni si ho, ať tě miluje zezadu.|120",
    "Jezdi na něm a sama si přitom přikládej vibrátor na klitoris. Ať se dívá.|180",
    "Když na něm jezdíš, polož mu ruce kolem krku (bez tlaku), dívej se mu do očí a pomalu se pohybuj.|120",
    "Lehni si na záda na kraj jídelního stolu a nech ho, ať se s tebou miluje vestoje. Jednou rukou mu hlaď varlata.|180",
    "Pět ran zezadu: Když je v tobě zezadu, dej mu do ruky bičík a nech ho dát ti pět lehkých plácnutí. Cíl: počítat nahlas a sílu určuješ ty.|180|zezadu",
    "Lehněte si pod deku na gauč do lžičky a pomalu, líně proti němu přirážej zadečkem.|240",
    "Miluj se s ním v poloze, kterou si vybere – a dej do toho všechno.|240",
    "Zavaž mu oči a přikaž mu, ať si lehne na záda. Nech ho chvíli čekat, a pak si na něj pomalu sedni.",
    "Jezdi na něm a otírej se klitorisem o jeho pánev – pomalými krouživými pohyby.|120",
    "Klekni si na zem u gauče a hrudníkem se opři o sedák. Nech ho, ať tě miluje zezadu.|180",
    "Nakloněná dopředu: Sedni si na něj zády a nakloň se dopředu, ať na všechno vidí. Cíl: tři minuty a ani jednou se nenarovnat.|180|ona_nahore_zady",
    "Při sexu ho chytni za vlasy a přitáhni si jeho pusu ke krku.|90",
    "Stoupni si k lince, vystrč zadeček, nech ho, ať tě miluje zezadu, a jeho ruce si dej na prsa.|120",
    "Miluj se s ním co nejpomaleji – každý pohyb ať trvá aspoň 5 vteřin.|180",
    "Spoutej mu ruce pouty za zády, posaď ho na kraj postele a sedni si na něj.|180",
    "V misionáři se pod ním nehýbej a jen ho líbej. Hýbat se smí jen on.|120",
    "Lehni si na bok, propleť s ním nohy do „nůžek“ a přirážej proti němu.|180",
    "Lehni si na břicho a vibrátor si dej pod sebe ke klitorisu. Nech ho, ať tě miluje zezadu – vibrace ucítí i on.|180",
    "Při každém hlubokém pohybu mu řekni, že je tvůj. Při každém mělkém, že je úžasný.|120",
    "Rozkaž mu, ať si sedne na židli a nehne se. Tanči před ním 10 vteřin a pak si na něj sedni.|180",
    "Lehni si na záda, zvedni nohy a roztáhni je. Nech ho, ať tě drží za kotníky.|120",
    "Opři se rukama o zeď v chodbě a nech ho, ať tě miluje zezadu. Jeho ruku si dej mezi nohy.|120",
    "Jezdi na něm a popros ho, ať ti řekne, až bude blízko. Pak zpomal – a pak zrychli.",
    "Posaď ho na gauč, klekni si obkročmo nad něj a pomalu si na něj sedej.|180",
    "Chyť ho při misionáři za zadek a přitahuj si ho do sebe tak, jak to chceš ty.|120",
    "Plácni ho dvakrát po zadku dlaní, pak ho pohlaď a polib. A pak se mu nastav zezadu.",
    "Sedni si na pračku a přitáhni si ho mezi nohy, ať se s tebou miluje vestoje.|120",
    "Poloha lotos: on sedí se zkříženýma nohama a ty mu sedíš obkročmo na klíně. Pomalu se spolu houpejte.|180",
    "Klekni si na posteli a nech ho, ať tě miluje zezadu. Jednou rukou mu zespodu mezi svýma nohama hlaď varlata.|180",
    "Při sexu vystřídejte tři polohy, ale nenech ho z tebe vyklouznout.",
    "Jezdi na něm pomalu a hluboko a každých 20 vteřin mu olízni bradavku.|180",
    "Nasaď mu pouta, zavaž mu oči a jezdi na něm. Nebude vědět, kdy přijde další pohyb.|180",
    "Předkloň se přes opěradlo gauče a nech ho, ať tě miluje vestoje zezadu.|120",
    "Rozkaž mu, ať tě prosí o každý pohyb. Když poprosí, splň to.|120",
    "Lehni si na gauč na záda, jednu nohu dej na opěradlo a přitáhni si ho mezi nohy.|180",
    "Lehni si na posteli na břicho, dej nohy k sobě a nech ho, ať si na tebe lehne obkročmo a vnikne do tebe zezadu.|180",
    "Při sexu mu prsty masíruj hráz a nepřestávej.|180",
    "Ve sprše: stoupni si zády k němu, nohu dej na okraj vany a přitáhni si ho.|120",
    "Opři se rukama o komodu před zrcadlem a nech ho, ať tě miluje zezadu. Dívej se mu v zrcadle do očí.|120",
    "Zatímco na něm jezdíš, přikaž mu, ať ti hladí prsa a nepřestává.|180",
    "Když tě miluje, plácni ho lehce bičíkem přes stehno pokaždé, když zpomalí.|120",
    "Lehni si na břicho a nech ho, ať si lehne na bok těsně vedle tebe a vnikne do tebe zezadu.|180",
    "Na kraji postele čelem: Posaď ho na kraj postele a sedni si mu na klín čelem k němu. Cíl: tři minuty a pohyb dělá jen ty.|180|kraj_postele",
    "Zakaž mu dotýkat se tě rukama. Když tě chytí, zpomal na minimum.|180",
    "Vyber místo v bytě, kde jste to ještě nedělali. Tam se s ním miluj.",
    "Konec podle tebe: Doveď ho až do konce a způsob si vybereš úplně sama. Cíl: nenechat ho, aby ti do toho mluvil.|300|ona_nahore",

    // Karty s cílem
    "Jezdkyně: Posaď se na něj obkročmo, když leží na zádech, a zaveď si ho do sebe. On se nesmí hýbat. Cíl: dovést ho k vrcholu jen svými boky – nejdřív pomalu, pak rychle.|240",
    "Lžička s vibracemi: Lehni si na bok zády k němu a nech ho vniknout zezadu. Sáhni si mezi nohy a přikládej mu vibrátor na varlata. Cíl: aby sám zrychlil.|240",
    "Obrácená kovbojka: On leží na zádech, ty si na něj sedneš zády k němu, předkloníš se a opřeš se o jeho stehna. Cíl: ať vidí všechno – tři minuty podle tvého rytmu.|180",
    "Pět poloh podle tebe: Ty určuješ každou minutu novou polohu – ty nahoře, zezadu, lžička, misionář, kraj postele. Cíl: nenechat ho vyklouznout víc než dvakrát.|300",
    "Kotníky na ramenou: Lehni si zády na jídelní stůl se zadečkem na kraji a kotníky mu dej na ramena. Cíl: rukama na jeho zadku si ho tahat do sebe – třicet pomalých, třicet rychlých.|180",
    "Prohnutá kočka: Klekni si na posteli na lokty, prohni záda a vystrč zadeček, ať tě miluje zezadu. Cíl: po každém desátém přírazu se proti němu zatlačit a zůstat 3 vteřiny.|180",
    "Pouta nahoru: Nasaď mu pouta s rukama nad hlavou, sedni si na něj a miluj se s ním. Cíl: dívat se mu do očí a nedovolit mu je zavřít.|180",
    "Noha na jeho boku: Opři se zády o zeď a zvedni jednu nohu na jeho bok. Nech ho vniknout vestoje. Cíl: pohybovat pánví proti němu tak, aby to bylo nejlepší pro oba.|120",
    "Čelo na čelo: On sedí na pevné židli, ty obkročmo čelem k němu. Opřete se čely a houpejte se. Cíl: tři minuty pomalu s polibky.|180",
    "Tvoje číslo: Řekni mu číslo od 20 do 50 a udělej na něm přesně tolik pohybů – každý pomalejší a hlubší. Cíl: na konci se zeptat, jestli chce ještě jednou tolik.",
    "Chodidla na hrudi: Lehni si na záda, přitáhni kolena k prsům a chodidla mu opři o hrudník. Cíl: chodidly řídit, jak hluboko smí – dvě minuty.|120",
    "Zrcadlová výzva: Opři se o komodu před zrcadlem a nech ho, ať tě miluje zezadu. Cíl: dívat se mu do očí v zrcadle – kdo první uhne, zrychluje.|180",
    "Bičík pro něj po deseti: Jsi nahoře a po každých deseti pohybech mu dej lehké plácnutí bičíkem na stehno. Cíl: on řekne, jestli silněji, nebo jemněji.|180",
    "Svírání: Lehni si na břicho s nohama u sebe a nech ho lehnout si na tebe zezadu. Cíl: stisknout svaly pánevního dna při každém jeho přírazu.|180",
    "Zadeček proti němu: Opři se předloktími o kuchyňskou linku, vystrč zadeček a nech ho, ať tě miluje zezadu. Cíl: přirážet proti němu a určovat tempo sama.|180",
    "Plnění povelů: Jsi nahoře a on ti smí říkat jen „rychleji“, „pomaleji“, „hlouběji“ a „zastav“. Cíl: splnit každý povel, dokud se neudělá.|240",
    "Dojde na tvůj povel: Miluj se s ním pět minut a on nesmí dojít. Když se blíží, zpomal a stiskni ho svaly. Cíl: nechat ho dojít až na tvé „teď“.|300",
    "Na okraji vany: Posaď ho na kraj vany na ručník a sedni si na něj obkročmo. Cíl: pomalé houpání, zatímco na vás teče sprcha.|120",
    "Přišpendlené ruce: Jsi nahoře a držíš mu zápěstí přitisknutá k posteli nad hlavou. Cíl: nepustit ho, dokud neřekne „prosím“.|120",
    "Nůžky pro něj: Lehni si na bok, přehoď mu horní nohu přes bok a nech ho vniknout. Cíl: líbat se po celou dobu bez přestávky.|180",
    "Polštář pod tebou: Lehni si na břicho s polštářem pod boky a nech ho ležet na tobě. Cíl: tlačit zadeček nahoru proti němu, aby se ti klitoris třel o polštář.|180",
    "Tempo podle jeho srdce: Polož ruku na jeho srdce a pohybuj se na něm v rytmu jeho tepu. Cíl: jak se mu zrychluje tep, zrychluj i ty.|180",
    "Čelem ke dveřím: Opři se dlaněmi o zavřené dveře ložnice a nech ho, ať tě miluje vestoje zezadu. Jeho ruce si dej na prsa. Cíl: aby tě musel držet, protože se ti podlamují kolena.|120",
    "Styly jízdy: Jsi nahoře a každou minutu změníš styl – nahoru a dolů, krouživě, dopředu a dozadu, rychle. Cíl: ať si vybere oblíbený a v tom to dotáhni do konce.|240",
    "Plácnutí při každém pohybu: Jsi nahoře zády k němu. Ať tě při každém tvém pohybu dolů lehce plácne dlaní po zadečku. Cíl: dvacet plácnutí, sílu určuješ ty.|120",
    "Jen špička: Sedni si na něj a vpusť do sebe jen špičku. 30 vteřin se hýbej nepatrně, pak se na něj pomalu posaď celá. Cíl: aby tě sám stáhl dolů.|90",
    "Líná lžička: Lehněte si pod deku do lžičky, on za tebou, a líně pohybuj zadečkem proti němu. Cíl: udržet to pět minut.|300",
    "Paty na jeho zadku: Sedni si na kuchyňskou linku, přitáhni si ho a obejmi ho nohama. Patami mu řiď tempo. Cíl: tři minuty – bez tvých pat nesmí zrychlit.|180",
    "Vedený poslepu: Zavaž mu oči a veď ho rukama do polohy – polož ho, otoč ho, sedni si na něj. Cíl: tři různé polohy, pozná je až tělem.|240",
    "Úhel nahoru: Lehni si na záda na kraj postele, nohy mu dej na ramena a boky podlož polštářem. Cíl: rukama na jeho bocích ho nasměrovat, aby přirážel pod úhlem nahoru.|180",
    "Spoutaný na kraji postele: Nasaď mu pouta za zády, posaď ho na kraj postele a sedni si na něj. Cíl: pohybovat se, jak chceš ty – on ti smí jen líbat prsa.|180",
    "Ruce za zády oba: Oba držíte ruce za zády. Ty vymysli, jak se na něj dostat a milovat se s ním. Cíl: tři minuty bez jediného dotyku rukou.|180",
    "Mělce a hluboko nahoře: Jsi nahoře – tři mělké pohyby a jeden hluboký, pak dva a dva, pak jeden a tři. Opakuj. Cíl: nesplést se.|180",
    "Přes područku pro něj: Lehni si břichem přes područku gauče a nech ho zezadu. Cíl: rukou na jeho stehně si ho přitahovat k sobě.|180",
    "Přetáčení: Začněte v misionáři, pak se bez vytažení přetoč nahoru na něj a nakonec zády k němu. Cíl: zvládnout obě otočky, aniž by vyklouzl.",
    "Kousnutí dolů: Jsi nahoře a při každém pohybu dolů ho kousni do ramene nebo krku. Cíl: najít místo, kde zasténá nejvíc.|120",
    "Vibrátor mezi vámi: Jsi nahoře a mezi vašimi těly držíš vibrátor na klitorisu. Cíl: krouživými pohyby ho udržet na místě, ať ho cítí i on.|180",
    "Ruce na jeho zadku: Misionář – obejmi ho a rukama na jeho zadku mu řiď každý příraz. Cíl: dvě minuty přesně podle tebe.|120",
    "Pračka zezadu: Opři se o zapnutou pračku, předkloň se a nech ho zezadu. Cíl: přirážet proti němu v rytmu otáček.|120",
    "Lotos pro něj: On sedí se zkříženýma nohama, ty mu sedíš na klíně čelem k němu s nohama za jeho zády. Cíl: tři minuty houpání s pohledem do očí.|180",
    "Otoč se, říkáš ty: Kdykoli řekneš „otoč se“, on změní polohu podle tebe. Cíl: čtyři povely za čtyři minuty – poslední je jeho oblíbená.|240",
    "Parapet: Stoupni si k oknu se zataženými závěsy zády k němu a opři se o parapet. Nech ho zezadu a jeho ruku veď na svůj klitoris. Cíl: aby hladil stejným tempem, jakým přiráží.|120",
    "Počítej plácnutí: Klečíš na posteli a on tě miluje zezadu. Při každém čtvrtém přírazu tě plácne po zadečku a ty počítáš nahlas. Cíl: do dvaceti.|180",
    "Navigace: Nech ho přirážet pomalu a naviguj ho slovy „výš“, „níž“, „hlouběji“, „přesně tak“. Cíl: dostat ho na „přesně tak“ a držet ho tam.|180",
    "Na jeho klíně zády: On sedí na kraji postele, ty mu sedíš na klíně zády k němu. Cíl: opřít se o něj a vést jeho ruce na prsa a klín.|180|klin_zady",
    "Noha na opěradle pro něj: Lehni si na gauč, jednu nohu dej na opěradlo, druhou na zem, a přitáhni si ho. Cíl: pokaždé, když zasténá, dostane polibek.|180",
    "Teď: Nasaď mu pouta a jezdi na něm. Dojít smí až na tvé „teď“. Cíl: říct to přesně ve chvíli, kdy je na hraně.",
    "Úplný klid: Jsi nahoře a úplně se zastav. On se musí hýbat pod tebou. Cíl: aby tě prosil, ať se pohneš.|90",
    "Na stoličce: Stoupni si zády k němu na nízkou stoličku, ať jste ve stejné výšce, a opři se o zeď. Cíl: dvě minuty vestoje bez ztráty rovnováhy.|120|zezadu_vzpr",
    "Šnečí tempo: Jsi nahoře a každý pohyb nahoru a dolů trvá 5 vteřin. Cíl: tři minuty – kdyby přirazil, začínáš znovu.|180",
    "Postupně nahlas: První minutu oba potichu, druhou smíte sténat, třetí mu musíš popisovat, co právě cítíš. Cíl: dodržet všechna pravidla.|180",
    "Ruka na jeho břiše: Lehni si na koberec a kolena přitáhni k ramenům, on nad tebou. Cíl: rukou na jeho břiše mu dávat vědět, jak hluboko smí.|120",
    "Prsa k ústům: Jsi nahoře a nakloň se, ať má tvé bradavky u pusy. Cíl: kdykoli ti je saje, zrychli.|180",
    "Vibrace pro oba: Jsi nahoře a přitiskni vibrátor ke svému klitorisu tak, aby se dotýkal i jeho kořene. Cíl: najít polohu, kde vibrace cítíte oba.|180",
    "Sázka pro něj: Milujte se v libovolné poloze. Když dojdeš dřív ty, dlužíš mu ruku nebo pusu až do konce. Cíl: on musí dojít tak či tak.",
    "Jeho poloha snů: Zeptej se ho, jakou polohu chce nejvíc, a udělej ji co nejlépe. Cíl: na konci ti dá známku od 1 do 10.|240",
  ],
});
