// Kategorie 4 – Sex a polohy (dávka b)
// Témata: vleže čelem k sobě, misionář a jeho varianty, nohy nahoru, na boku a lžička.
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 4,

  male: [
    "Misionář naplno: Lehni si na ni, opři se o lokty a přirážej pomalu a hluboko. Obličej máte u sebe. Cíl: ani jednou nezrychlit.|240|misionar",
    "Propletené prsty nad hlavou: Dej jí ruce nad hlavu a propleť si s ní prsty, zatímco přirážíš. Cíl: čtyři minuty a prsty ani jednou nerozpojit.|240|misionar",
    "Pohled bez uhnutí: Miluj ji v misionáři a celou dobu se jí dívej do očí. Cíl: čtyři minuty – kdo první uhne, plní úkol navíc.|240|misionar",
    "Jiný úhel: Polož jí pod boky polštář a vnikej do ní shora. Cíl: čtyři minuty a zeptat se, jestli je ten úhel lepší.|240|misionar_polstar",
    "Krátce a rychle: S polštářem pod jejími boky přirážej jen krátce a rychle. Cíl: tři minuty a ani jeden hluboký příraz.|180|misionar_polstar",
    "Nohy nahoře, tempo dole: Dej si její nohy na ramena a přirážej pomalu a hluboko. Cíl: čtyřicet přírazů a žádný rychlý.|240|nohy_ramena",
    "Tempo určuješ ty: Dej si její nohy na ramena, ruce na její boky a veď celé tempo sám. Cíl: čtyři minuty, při kterých se ona vůbec nehýbe.|240|nohy_ramena",
    "Hluboko a pomalu: Nohy má na tvých ramenou. Uděláš deset úplně pomalých pohybů a pak minutu nic. Cíl: tři taková kola.|300|nohy_ramena",
    "Jedna nahoře, druhá dole: Dej si jednu její nohu na rameno a druhou nech dole. Cíl: po dvou minutách nohy prohodit a zeptat se, co je lepší.|240|nohy_ramena",
    "Kolena u hrudníku: Miluj se s ní tak, že má kolena přitažená k hrudníku. Cíl: čtyři minuty a u každé minuty se zeptat, jestli to není moc.|240|nohy_ramena",
    "Minuta bez pohybu: Zůstaň v ní úplně bez pohybu a jen ji líbej. Cíl: celá minuta a ani jeden příraz.|60|misionar",
    "Co nejblíž: Propleť si s ní nohy tak, abyste byli co nejblíž, a hýbej se jen boky. Cíl: čtyři minuty a ani jednou se od sebe neodtrhnout.|240|propletene",
    "Celý na ní: Lehni si na ni celou vahou a pohybuj se jen pánví. Žádné velké přírazy. Cíl: dojít bez jediného velkého pohybu.|300|propletene",
    "Shora na ni: Opři se o natažené paže a dívej se na ni shora, zatímco přirážíš. Cíl: čtyři minuty a paže ani jednou nepokrčit.|240|misionar",
    "Jen do poloviny: Vnikej do ní jen napůl a pokaždé se zase stáhni. Cíl: třicet přírazů a ani jeden hlubší.|180|misionar",
    "Deset a deset: Dělej deset pomalých a deset rychlých přírazů, ona je počítá nahlas. Cíl: šest kol a ani jednou se nesplést.|240|misionar",
    "Stehno v dlani: Miluj se s ní na boku čelem k sobě a drž ji přitom za stehno. Cíl: čtyři minuty a ani jednou ho nepustit.|240|lzicka",
    "Zvednutá horní noha: Lehni si za ni na lžičku, zvedni jí horní nohu a vnikni do ní zezadu. Cíl: čtyři minuty a nohu nespustit.|240|lzicka",
    "Lžička naplno: Na lžičku a rukou jí zepředu dráždi klitoris. Nesmíš zrychlit. Cíl: dovést ji tam pomalu.|300|lzicka",
    "Lžička a polibky na krk: Miluj ji na lžičku a celou dobu ji líbej na rameno a krk. Cíl: čtyři minuty a nepřestat líbat ani na chvíli.|240|lzicka",
    "Propletené nohy na boku: Propleť si s ní nohy na boku a hýbej se jen minimálně. Cíl: čtyři minuty a ani jeden velký pohyb.|240|lzicka",
    "Objetí a šepot: Drž ji na boku kolem pasu a celou dobu jí šeptej do ucha. Cíl: čtyři minuty a nepřestat mluvit.|240|lzicka",
    "Ruka nad hlavou na boku: Miluj se s ní na boku a jednou rukou jí drž ruku nad hlavou. Cíl: čtyři minuty a ani jednou ji nepustit.|240|lzicka",
    "Lžička a ruka na prsou: Miluj ji na lžičku pomalu a mezi tím jí hlaď prsa. Cíl: pět minut a ruku ani jednou nesundat.|300|lzicka",
    "Dva na boku: Na boku vydržte pět minut a ani jeden nesmí změnit polohu. Cíl: pět minut bez pohnutí jinam.|300|lzicka",
    "Obtočený nohama: Lehni si na ni a nech ji, ať tě obejme nohama kolem pasu. Cíl: čtyři minuty a nedovolit jí nohy rozpojit.|240|propletene",
    "Zvednuté boky: V misionáři jí podlož boky rukama a zvedni ji k sobě. Cíl: čtyři minuty a ruce ani jednou nevytáhnout.|240|misionar",
    "Příraz a polibek: Vnikej do ní a mezi tím jí pokaždé polib krk. Cíl: dvacet přírazů a dvacet polibků.|240|misionar",
    "Nohy stisknuté k sobě: Miluj se s ní tak, aby měla nohy natažené a pevně stisknuté. Cíl: čtyři minuty a nedovolit jí je rozevřít.|240|propletene",
    "Nohy k sobě: Ona má nohy úplně u sebe a ty jsi nad nimi. Bude to těsnější. Cíl: vydržet tak celou dobu.|240|propletene",
    "Deset vteřin pauzy: Pokaždé, když se blíží vrchol, se zastav a pokračuj až za deset vteřin. Cíl: čtyři takové pauzy, než ji necháš dojít.|300|misionar",
    "Ruce u těla: Miluj se s ní a celou dobu jí drž obě ruce přitisknuté k tělu. Cíl: čtyři minuty a ani jednou ji nepustit.|240|misionar",
    "Ruka mezi vámi: S polštářem pod jejími boky jí dráždi rukou klitoris, zatímco v ní jsi. Cíl: pět minut a ruku ani jednou nesundat.|300|misionar_polstar",
    "Ať se pohne ona: Vnikni do ní a hned se úplně zastav. Cíl: tři minuty, při kterých se hýbe výhradně ona.|180|misionar",
    "Kolena pod jejími stehny: Dej si kolena pod její stehna a zvedej ji k sobě. Cíl: čtyři minuty a nenechat ji sklouznout dolů.|240|nohy_ramena",
    "Kotníky na ramenou: Opři si její kotníky o ramena, drž ji za boky a přirážej hluboko. Cíl: čtyři minuty a nohy jí ani jednou nespustit.|240|nohy_ramena",
    "Do kříže: Ona leží na zádech, ty na boku napříč přes její nohy. Netradiční, ale funguje. Cíl: najít správný úhel.|240|propletene",
    "Polibek po desátém: Miluj ji v misionáři a pokaždé po deseti přírazech ji polib. Cíl: čtyři minuty a ani jeden polibek nevynechat.|240|misionar",
    "Kotník v ruce: V misionáři jí zvedni jednu nohu a drž ji za kotník. Cíl: čtyři minuty a po dvou minutách nohu vyměnit.|240|nohy_ramena",
    "Podle jejího dechu: Vnikej do ní velmi pomalu a poslouchej, jak dýchá. Cíl: pět minut a zrychlit jen tehdy, když zrychlí její dech.|300|misionar",
    "Lehni si na ni a nehýbej se. Všechnu práci dělá ona boky.|240|propletene",
    "Miluj se s ní na boku a druhou rukou jí drž bradu, ať se dívá.|240|lzicka",
    "Na lžičku a mezi tím jí přiložíš vibrátor zepředu.|300|lzicka",
    "Tři rychlosti: Minutu pomalu, minutu středně, minutu naplno. Bez přerušení. Cíl: nikdy se nevrátit zpět.|180|misionar",
    "V misionáři jí dej ruce pod záda a přitáhni si ji.|240|misionar",
    "Miluj se s ní tak, že má obě nohy položené na tvé hrudi.|240|nohy_ramena",
    "Kousnutí do ramene: Vnikej do ní a mezi tím ji vždycky lehce kousni do ramene. Cíl: deset kousnutí a pokaždé o kousek jinam.|240|propletene",
    "V misionáři se pohybuj do kruhu, ne dopředu a dozadu.|240|misionar",
    "Kroužení: Místo přírazů se pohybuj pánví do kruhu. Tlak bude pořád na stejném místě. Cíl: vydržet u kroužení celou dobu.|300|misionar",
    "Miluj se s ní s polštářem pod boky a rukama pod jejím zadečkem.|240|misionar_polstar",
    "Dej jí nohy na svoje ramena a nakloň se dopředu, až se skoro složí.|240|nohy_ramena",
    "V misionáři se zastav a nech ji, ať řekne, kdy má pokračovat.|300|misionar",
    "Miluj se s ní na boku tak, že ji držíš za rameno a přitahuješ k sobě.|240|lzicka",
    "Lžička a putující ruka: Miluj ji na lžičku a rukou jí přitom přejížděj po břiše a stehnech. Cíl: pět minut a ruku nezastavit.|300|lzicka",
    "Nech ji ležet na boku a zvedni jí horní nohu ke stropu.|240|lzicka",
    "Nůžky vleže: Ona na boku, ty klečíš mezi jejíma nohama. Hloubka i úhel jsou jiné. Cíl: najít, co jí sedne.|240|lzicka",
    "V misionáři jí zakryj ústa dlaní a sleduj, jak reaguje.|240|misionar",
    "Miluj se s ní a nech ji, ať ti nehty zarývá do zad.|240|misionar",
    "V misionáři jí podlož obě kolena rukama a rozevři je co nejvíc.|240|misionar",
    "Nech ji ležet s rukama nad hlavou. Nesmí je sundat.|240|misionar",
    "Sto pohybů: Uděláš přesně sto pohybů a pak se zastavíš, ať jste kdekoli. Cíl: dojít do sta bez ztráty rytmu.|300|misionar",
    "V misionáři ji drž za zápěstí a vnikej pomalu.|240|misionar",
    "Miluj se s ní tak, že jí jednu nohu položíš přes svoje rameno a druhou kolem pasu.|240|nohy_ramena",
    "S polštářem pod boky přirážej shora dolů. Úhel je pro ni jiný.|240|misionar_polstar",
    "Nech ji, ať si sama nastaví nohy tak, jak jí to nejvíc vyhovuje.|240|misionar",
    "Přírazy a jazyk: Miluj se s ní a mezi tím jí střídavě olizuj bradavky. Cíl: čtyři minuty a každou bradavku aspoň pětkrát.|240|misionar",
    "Pomalá pětka: Pět minut se smíš hýbat jen tak pomalu, abyste stihli mluvit. Cíl: vydržet mluvit celou dobu.|300|misionar",
    "V misionáři jí drž nohu za lýtko a tlač ji k jejímu rameni.|240|nohy_ramena",
    "Miluj se s ní na boku a druhou rukou si drž její zadeček.|240|lzicka",
    "Lžička a lubrikant: Použij hodně lubrikantu a miluj ji na lžičku co nejpomaleji. Cíl: pět minut a ani jednou nezrychlit.|300|lzicka",
    "Nech ji ležet na zádech a ty klečíš mezi jejíma nohama vzpřímeně.|240|misionar",
    "Vzpřímeně nad ní: Klečíš mezi jejíma nohama, držíš ji za boky a zvedáš ji k sobě. Cíl: nést její váhu celou dobu.|240|nohy_ramena",
    "Miluj se s ní tak, že se drží tvých ramen a přitahuje si tě.|240|misionar",
    "V misionáři střídej hluboké a mělké pohyby po pěti.|240|misionar",
    "Nech ji, ať ti nehty jede po zádech pokaždé, když zpomalíš.|240|misionar",
    "Miluj se s ní a mezi tím jí drž obě kolena u jejích ramen.|240|nohy_ramena",
    "Ruce pod ní: Dej jí obě ruce pod zadeček a celou dobu ji drž nahoře. Cíl: nepustit ji.|240|misionar_polstar",
    "Lehni si na ni a nech ji, ať ti šeptá do ucha, co má být dál.|300|propletene",
    "V misionáři vydrž bez pohybu pokaždé, když vydechne.|240|misionar",
    "Miluj se s ní na boku a nech ji, ať si sama drží nohu.|240|lzicka",
    "Nech ji ležet a ty jsi nad ní. Ale hýbat se smí jen ona.|240|misionar",
    "Dvě polohy: Začni v misionáři a po dvou minutách přejdi na lžičku, aniž bys z ní vyšel. Cíl: přechod bez přerušení.|300|lzicka",
    "V misionáři jí sundej polštář zpod hlavy a dej jí ho pod boky.|240|misionar_polstar",
    "Nakonec zůstaň v ní a jen se líbejte, dokud se nezklidníte.|120|propletene",
  ],

  female: [
    "Misionář naplno: Nech ho na sebe lehnout, obejmi ho nohama a tempo mu urči rukama na bocích. Cíl: ani jednou nezrychlit.|240|misionar",
    "Propletené prsty: Dej si ruce nad hlavu a nech si od něj proplést prsty. Cíl: čtyři minuty a prsty ani jednou nerozpojit.|240|misionar",
    "Neuhnout pohledem: Nech ho být nahoře a celou dobu se mu dívej do očí. Cíl: čtyři minuty – kdo první uhne, plní úkol navíc.|240|misionar",
    "Polštář změní úhel: Podlož si pod boky polštář a nech ho vniknout shora. Cíl: čtyři minuty a pak mu říct, jestli je to lepší.|240|misionar_polstar",
    "Krátce a rychle na přání: S polštářem pod boky ho popros o krátké a rychlé přírazy. Cíl: tři minuty a ani jeden hluboký.|180|misionar_polstar",
    "Pomalu a hluboko s nohama nahoře: Dej si nohy na jeho ramena a nech ho jít pomalu a hluboko. Cíl: čtyřicet přírazů a žádný rychlý.|240|nohy_ramena",
    "Tempo určuje on: Dej si nohy na jeho ramena, jeho ruce patří na tvoje boky a tempo vede celé on. Cíl: čtyři minuty a ty se vůbec nehýbeš.|240|nohy_ramena",
    "Hluboko a pomalu: Máš nohy na jeho ramenou. Deset úplně pomalých pohybů a pak minutu nic. Cíl: tři taková kola.|300|nohy_ramena",
    "Nahoře a dole: Dej si jednu nohu na jeho rameno a druhou nech dole. Cíl: po dvou minutách nohy prohodit a říct, co je lepší.|240|nohy_ramena",
    "Kolena k hrudníku: Přitáhni si kolena k hrudníku a nech ho opřít se do tebe. Cíl: čtyři minuty a každou minutu říct, jestli to není moc.|240|nohy_ramena",
    "Minuta jen polibků: Ať v tobě zůstane úplně bez pohybu a jen tě líbá. Cíl: celá minuta a ani jeden příraz.|60|misionar",
    "Nejblíž, jak to jde: Propleť si s ním nohy tak, abyste byli co nejblíž, a hýbej se jen boky. Cíl: čtyři minuty a neodtrhnout se od sebe.|240|propletene",
    "Celý na tobě: Nech ho lehnout si na tebe celou vahou a hýbat se jen pánví. Cíl: dojít bez jediného velkého pohybu.|300|propletene",
    "Dívá se na tebe shora: Nech ho opřít se o natažené paže, ať se na tebe celou dobu dívá. Cíl: čtyři minuty a paže nesmí pokrčit.|240|misionar",
    "Jen do poloviny jemu: Nech ho vnikat jen napůl a pokaždé se zase stáhnout. Cíl: třicet přírazů a ani jeden hlubší.|180|misionar",
    "Deset a deset s počítáním: Řekni mu, ať udělá deset pomalých a deset rychlých přírazů, a počítej nahlas. Cíl: šest kol bez chyby.|240|misionar",
    "Rameno v dlani: Miluj se s ním na boku čelem k sobě a celou dobu se ho drž za rameno. Cíl: čtyři minuty a ani jednou ho nepustit.|240|lzicka",
    "Horní noha nahoru: Lehni si na lžičku, zvedni horní nohu a nech ho vniknout zezadu. Cíl: čtyři minuty a nohu nespustit.|240|lzicka",
    "Lžička naplno: Na lžičku a jeho ruku si dej zepředu na klitoris. Nesmí zrychlit. Cíl: nechat se dovést pomalu.|300|lzicka",
    "Polibky na krk zezadu: Miluj se s ním na lžičku a nech se celou dobu líbat na rameno a krk. Cíl: čtyři minuty a nedovolit mu přestat.|240|lzicka",
    "Propleteni na boku: Propleť si na boku nohy s jeho a hýbejte se jen minimálně. Cíl: čtyři minuty a ani jeden velký pohyb.|240|lzicka",
    "Šepot za zády: Opři se o něj na boku zády a nech si celou dobu šeptat do ucha. Cíl: čtyři minuty a nesmí ztichnout.|240|lzicka",
    "Ruka nad hlavou na boku: Miluj se s ním na boku a nech si od něj držet ruku nad hlavou. Cíl: čtyři minuty a nesmí ji pustit.|240|lzicka",
    "Ruka na prsou zezadu: Miluj se s ním na lžičku pomalu a jeho ruku si nech na prsou. Cíl: pět minut a ruku mu nedovolit sundat.|300|lzicka",
    "Pět minut na boku: Zůstaňte na boku celých pět minut a ani jeden se nepřesune jinam. Cíl: nezměnit polohu.|300|lzicka",
    "Obtoč ho nohama: Nech ho lehnout si na tebe a obejmi ho nohama kolem pasu. Cíl: čtyři minuty a nohy ani jednou nerozpojit.|240|propletene",
    "Zvedne ti boky: Nech si od něj podložit boky rukama a zvednout k sobě. Cíl: čtyři minuty a ruce ti nesmí vytáhnout.|240|misionar",
    "Říkej si o polibky: Nech ho vnikat a mezi tím si nahlas říkej o polibky na krk. Cíl: dvacet polibků a ani jeden bez vyžádání.|240|misionar",
    "Nohy pevně u sebe: Natáhni nohy a pevně je stiskni k sobě, zatímco je v tobě. Cíl: čtyři minuty a ani jednou je nerozevřít.|240|propletene",
    "Nohy k sobě: Nohy měj úplně u sebe a on je nad nimi. Bude to těsnější. Cíl: vydržet tak celou dobu.|240|propletene",
    "Pauza na deset vteřin: Nech ho zastavit se pokaždé, když se blížíš, a pokračovat až za deset vteřin. Cíl: čtyři pauzy, než tě nechá dojít.|300|misionar",
    "Ruce přitisknuté k tělu: Nech si od něj držet obě ruce u těla, ať se nemůžeš hýbat. Cíl: čtyři minuty a nesmí tě pustit.|240|misionar",
    "Sama si pomáháš: S polštářem pod boky si sama dráždi klitoris, zatímco je v tobě. Cíl: pět minut a nenechat ho zasáhnout.|300|misionar_polstar",
    "Pohyb děláš ty: Nech ho vniknout a hned se úplně zastavit. Cíl: tři minuty, při kterých se hýbeš výhradně ty.|180|misionar",
    "Nech ho kleknout si pod tvoje stehna a zvednout tě.|240|nohy_ramena",
    "Opři si kotníky o jeho ramena a nech se držet za boky.|240|nohy_ramena",
    "Do kříže: Ty ležíš na zádech, on na boku napříč přes tvoje nohy. Netradiční, ale funguje. Cíl: najít správný úhel.|240|propletene",
    "V misionáři ho po každých deseti pohybech polib.|240|misionar",
    "Zvedni jednu nohu a nech si ji od něj podržet za kotník.|240|nohy_ramena",
    "Nech ho vnikat velmi pomalu a poslouchej, jak dýchá.|300|misionar",
    "Nech ho lehnout si na tebe bez pohybu. Všechnu práci děláš ty boky.|240|propletene",
    "Miluj se s ním na boku a nech si držet bradu, ať se musíš dívat.|240|lzicka",
    "Vibrátor si držíš sama: Miluj se s ním na lžičku a sama si zepředu přikládej vibrátor. Cíl: pět minut a nenechat ho na něj sáhnout.|300|lzicka",
    "Tři stupně: Nejdřív minutu pomalu, pak minutu středně a nakonec minutu naplno. Cíl: nikdy se nevrátit zpět.|180|misionar",
    "Dej si ruce pod záda a nech ho, ať si tě přitáhne.|240|misionar",
    "Polož si obě nohy na jeho hrudník a odtlačuj se.|240|nohy_ramena",
    "Kousej ho do ramene: Nech ho vnikat a mezi tím ho vždycky lehce kousni do ramene. Cíl: deset kousnutí a pokaždé o kousek jinam.|240|propletene",
    "Řekni mu, ať se místo přírazů pohybuje do kruhu.|240|misionar",
    "Kroužení: Ať se pohybuje pánví do kruhu, ne dopředu a dozadu. Tlak zůstane na jednom místě. Cíl: vydržet u kroužení.|300|misionar",
    "S polštářem pod boky si dej jeho ruce pod zadeček.|240|misionar_polstar",
    "Dej si nohy na jeho ramena a nech ho naklonit se dopředu, až se skoro složíš.|240|nohy_ramena",
    "Zastav ho a nech ho čekat, dokud sama neřekneš pokračuj.|300|misionar",
    "Miluj se s ním na boku a nech se přitahovat za rameno.|240|lzicka",
    "Jeho ruka putuje: Miluj se s ním na lžičku a nech mu ruku přejíždět po břiše a stehnech. Cíl: pět minut a ruku nesmí zastavit.|300|lzicka",
    "Lehni si na bok a zvedni horní nohu ke stropu.|240|lzicka",
    "Nůžky vleže: Ty na boku, on klečí mezi tvýma nohama. Hloubka i úhel jsou jiné. Cíl: najít, co ti sedne.|240|lzicka",
    "Nech si od něj zakrýt ústa dlaní a zkus být potichu.|240|misionar",
    "Zarývej mu nehty do zad pokaždé, když zrychlí.|240|misionar",
    "Nech si podložit obě kolena a rozevřít je co nejvíc.|240|misionar",
    "Ruce nahoře: Dej si ruce nad hlavu a nech ho vniknout. Cíl: čtyři minuty a ani jednou ruce nesundat.|240|misionar",
    "Sto pohybů: Napočítáte přesně sto pohybů a pak se zastavíte, ať jste kdekoli. Cíl: dojít do sta bez ztráty rytmu.|300|misionar",
    "Nech si držet zápěstí a užívej si, že nemáš kontrolu.|240|misionar",
    "Dej si jednu nohu přes jeho rameno a druhou kolem jeho pasu.|240|nohy_ramena",
    "S polštářem pod boky ho nech přirážet shora dolů. Úhel je jiný.|240|misionar_polstar",
    "Nastav si nohy přesně tak, jak ti to nejvíc vyhovuje, a řekni mu to.|240|misionar",
    "Nech se milovat a mezi tím si říkej o olizování bradavek.|240|misionar",
    "Pomalá pětka: Pět minut se smíte hýbat jen tak pomalu, abyste stihli mluvit. Cíl: vydržet mluvit celou dobu.|300|misionar",
    "Nech si od něj přitlačit nohu za lýtko k rameni.|240|nohy_ramena",
    "Miluj se s ním na boku a nech si držet zadeček.|240|lzicka",
    "Na lžičku a hodně pomalu, s dostatkem lubrikantu.|300|lzicka",
    "Nech ho kleknout si mezi tvoje nohy vzpřímeně a opři se o lokty.|240|misionar",
    "Vzpřímeně nad tebou: Klečí mezi tvýma nohama, drží tě za boky a zvedá k sobě. Cíl: nechat ho nést tvoji váhu.|240|nohy_ramena",
    "Přitahuj si ho: Chytni se jeho ramen a přitahuj si ho k sobě při každém přírazu. Cíl: čtyři minuty, při kterých tempo určuješ jen ty.|240|misionar",
    "Řekni mu, ať střídá pět hlubokých a pět mělkých pohybů.|240|misionar",
    "Jeď mu nehty po zádech pokaždé, když zpomalí.|240|misionar",
    "Nech si od něj přitlačit obě kolena k ramenům.|240|nohy_ramena",
    "Ruce pod tebou: Ať ti dá obě ruce pod zadeček a celou dobu tě drží nahoře. Cíl: čtyři minuty a ani jednou tě nesmí položit.|240|misionar_polstar",
    "Nech ho lehnout si na tebe a šeptej mu do ucha, co má být dál.|300|propletene",
    "Řekni mu, ať se zastaví pokaždé, když vydechneš.|240|misionar",
    "Nohu si držíš sama: Miluj se s ním na boku a horní nohu si celou dobu drž sama. Cíl: čtyři minuty a ani jednou ji nespustit.|240|lzicka",
    "Nech ho být nad tebou, ale hýbat se smíš jen ty.|240|misionar",
    "Dvě polohy: Začněte v misionáři a po dvou minutách přejděte na lžičku, aniž by z tebe vyšel. Cíl: přechod bez přerušení.|300|lzicka",
    "Vyndej si polštář zpod hlavy a dej si ho pod boky.|240|misionar_polstar",
    "Nakonec ho v sobě nech a jen se líbejte, dokud se nezklidníte.|120|propletene",
  ],
});
