// Kategorie 4 – Sex a polohy (dávka b)
// Témata: vleže čelem k sobě, misionář a jeho varianty, nohy nahoru, na boku a lžička.
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 4,

  male: [
    "Misionář naplno: Lehni si na ni, opři se o lokty a přirážej pomalu a hluboko. Obličej máte u sebe. Cíl: ani jednou nezrychlit.|240|misionar",
    "Propletené prsty nad hlavou: Dej jí ruce nad hlavu a propleť si s ní prsty, zatímco přirážíš. Cíl: čtyři minuty a prsty ani jednou nerozpojit.|240|misionar",
    "Pohled bez uhnutí: Miluj ji v misionáři a celou dobu se jí dívej do očí. Cíl: čtyři minuty – kdo první uhne, plní úkol navíc.|240|misionar",
    "Jiný úhel: Polož jí pod boky polštář a vnikej do ní shora. Cíl: čtyři minuty a zeptat se, jestli je ten úhel lepší.|240|misionar_polstar",
    "Krátce a rychle: S polštářem pod jejími boky přirážej jen krátce a rychle. Cíl: tři minuty a ani jeden hluboký příraz.|180|misionar_polstar",
    "Nohy nahoře, tempo dole: Dej si její nohy na ramena a přirážej pomalu a hluboko. Cíl: čtyřicet přírazů a žádný rychlý.|240|nohy_ramena",
    "Tempo určuješ ty: Dej si její nohy na ramena, vnikni do ní a tempo přírazů veď celé sám. Cíl: čtyři minuty, při kterých se ona vůbec nehýbe.|240|nohy_ramena",
    "Hluboko a pomalu: Nohy má na tvých ramenou. Uděláš deset úplně pomalých hlubokých přírazů a pak minutu zůstaneš v ní bez pohybu. Cíl: tři taková kola.|300|nohy_ramena",
    "Jedna nahoře, druhá dole: Vnikni do ní s jednou nohou na rameni a druhou dole. Cíl: po dvou minutách nohy prohodit a zeptat se, který úhel je lepší.|240|nohy_ramena",
    "Kolena u hrudníku: Miluj se s ní tak, že má kolena přitažená k hrudníku. Cíl: čtyři minuty a u každé minuty se zeptat, jestli to není moc.|240|nohy_ramena",
    "Minuta bez pohybu: Zůstaň v ní úplně bez pohybu a jen ji líbej. Cíl: celá minuta a ani jeden příraz.|60|misionar",
    "Co nejblíž: Miluj se s ní s propletenýma nohama tak, abyste byli co nejblíž, a hýbej se jen boky. Cíl: čtyři minuty a neodtrhnout se od sebe.|240|propletene",
    "Celý na ní: Lehni si na ni celou vahou a pohybuj se jen pánví. Žádné velké přírazy. Cíl: dojít bez jediného velkého pohybu.|300|propletene",
    "Shora na ni: Opři se o natažené paže a dívej se na ni shora, zatímco přirážíš. Cíl: čtyři minuty a paže ani jednou nepokrčit.|240|misionar",
    "Jen do poloviny: Vnikej do ní jen napůl a pokaždé se zase stáhni. Cíl: třicet přírazů a ani jeden hlubší.|180|misionar",
    "Deset a deset: Dělej deset pomalých a deset rychlých přírazů, ona je počítá nahlas. Cíl: šest kol a ani jednou se nesplést.|240|misionar",
    "Stehno v dlani: Miluj se s ní na boku čelem k sobě a drž ji přitom za stehno. Cíl: čtyři minuty a ani jednou ho nepustit.|240|lzicka",
    "Zvednutá horní noha: Lehni si za ni na lžičku, zvedni jí horní nohu a vnikni do ní zezadu. Cíl: čtyři minuty a nohu nespustit.|240|lzicka",
    "Lžička naplno: Vnikni do ní zezadu na lžičku a rukou jí zepředu dráždi klitoris. Nesmíš zrychlit. Cíl: dovést ji tam pomalu.|300|lzicka",
    "Lžička a polibky na krk: Miluj ji na lžičku a celou dobu ji líbej na rameno a krk. Cíl: čtyři minuty a nepřestat líbat ani na chvíli.|240|lzicka",
    "Propletené nohy na boku: Vnikni do ní na boku s propletenýma nohama a hýbej se jen minimálně. Cíl: čtyři minuty a ani jeden velký příraz.|240|lzicka",
    "Objetí a šepot: Miluj ji na lžičku, drž ji kolem pasu a celou dobu jí šeptej do ucha. Cíl: čtyři minuty a nepřestat mluvit.|240|lzicka",
    "Ruka nad hlavou na boku: Miluj se s ní na boku a jednou rukou jí drž ruku nad hlavou. Cíl: čtyři minuty a ani jednou ji nepustit.|240|lzicka",
    "Lžička a ruka na prsou: Miluj ji na lžičku pomalu a mezi tím jí hlaď prsa. Cíl: pět minut a ruku ani jednou nesundat.|300|lzicka",
    "Dva na boku: Miluj se s ní na boku a ani jeden z vás nesmí změnit polohu. Cíl: pět minut přírazů a nepřesunout se jinam.|300|lzicka",
    "Obtočený nohama: Vnikni do ní vleže a nech ji, ať tě obejme nohama kolem pasu. Cíl: čtyři minuty a nedovolit jí nohy rozpojit.|240|propletene",
    "Zvednuté boky: Miluj ji v misionáři, podlož jí boky rukama a zvedni ji k sobě. Cíl: čtyři minuty a ruce ani jednou nevytáhnout.|240|misionar",
    "Příraz a polibek: Vnikej do ní a mezi tím jí pokaždé polib krk. Cíl: dvacet přírazů a dvacet polibků.|240|misionar",
    "Nohy stisknuté k sobě: Miluj se s ní tak, aby měla nohy natažené a pevně stisknuté. Cíl: čtyři minuty a nedovolit jí je rozevřít.|240|propletene",
    "Nohy k sobě: Vnikni do ní, když má nohy úplně u sebe, a klekni si nad ně. Bude to těsnější. Cíl: čtyři minuty v tomhle sevření.|240|propletene",
    "Deset vteřin pauzy: Miluj ji a pokaždé, když se blíží vrchol, zůstaň v ní bez pohybu deset vteřin. Cíl: čtyři takové pauzy, než ji necháš dojít.|300|misionar",
    "Ruce u těla: Miluj se s ní a celou dobu jí drž obě ruce přitisknuté k tělu. Cíl: čtyři minuty a ani jednou ji nepustit.|240|misionar",
    "Ruka mezi vámi: S polštářem pod jejími boky jí dráždi rukou klitoris, zatímco v ní jsi. Cíl: pět minut a ruku ani jednou nesundat.|300|misionar_polstar",
    "Ať se pohne ona: Vnikni do ní a hned se úplně zastav. Cíl: tři minuty, při kterých se hýbe výhradně ona.|180|misionar",
    "Kolena pod jejími stehny: Vnikni do ní, dej si kolena pod její stehna a zvedej ji k sobě. Cíl: čtyři minuty a nenechat ji sklouznout dolů.|240|nohy_ramena",
    "Kotníky na ramenou: Opři si její kotníky o ramena, drž ji za boky a přirážej hluboko. Cíl: čtyři minuty a nohy jí ani jednou nespustit.|240|nohy_ramena",
    "Do kříže: Ona leží na zádech, ty na boku napříč přes její nohy a vnikáš do ní z boku. Cíl: čtyři minuty a najít správný úhel.|240|propletene",
    "Polibek po desátém: Miluj ji v misionáři a pokaždé po deseti přírazech ji polib. Cíl: čtyři minuty a ani jeden polibek nevynechat.|240|misionar",
    "Kotník v ruce: Miluj ji v misionáři, zvedni jí jednu nohu a drž ji za kotník. Cíl: čtyři minuty a po dvou minutách nohu vyměnit.|240|nohy_ramena",
    "Podle jejího dechu: Vnikej do ní velmi pomalu a poslouchej, jak dýchá. Cíl: pět minut a zrychlit jen tehdy, když zrychlí její dech.|300|misionar",
    "Práci dělá ona: Vnikni do ní vleže a pak se vůbec nehýbej. Všechny pohyby dělá ona boky. Cíl: čtyři minuty a ani jeden tvůj příraz.|240|propletene",
    "Miluj se s ní na boku a druhou rukou jí drž bradu, ať se dívá.|240|lzicka",
    "Lžička a vibrátor: Miluj ji na lžičku a zepředu jí přitom drž vibrátor na klitorisu. Cíl: pět minut a ani jednou ho neodložit.|300|lzicka",
    "Tři rychlosti: Miluj ji minutu pomalu, minutu středně a minutu naplno, bez přerušení. Cíl: nikdy se nevrátit k pomalejšímu tempu.|180|misionar",
    "Ruce pod jejími zády: Miluj ji v misionáři, dej jí ruce pod záda a přitáhni si ji na sebe. Cíl: čtyři minuty a ani jednou ji nepoložit zpátky.|240|misionar",
    "Miluj se s ní tak, že má obě nohy položené na tvé hrudi.|240|nohy_ramena",
    "Kousnutí do ramene: Vnikej do ní a mezi tím ji vždycky lehce kousni do ramene. Cíl: deset kousnutí a pokaždé o kousek jinam.|240|propletene",
    "Kroužit, ne přirážet: Zůstaň v ní v misionáři a pohybuj se pánví do kruhu, ne dopředu a dozadu. Cíl: čtyři minuty a ani jeden příraz.|240|misionar",
    "Kroužení: Místo přírazů se pohybuj pánví do kruhu. Tlak bude pořád na stejném místě. Cíl: vydržet u kroužení celou dobu.|300|misionar",
    "Miluj se s ní s polštářem pod boky a rukama pod jejím zadečkem.|240|misionar_polstar",
    "Až se skoro složí: Vnikni do ní s nohama na svých ramenou a nakloň se dopředu, až se skoro složí. Cíl: čtyři minuty a ptát se, jestli to není moc.|240|nohy_ramena",
    "Řekne, kdy pokračovat: Miluj ji v misionáři a občas se úplně zastav v ní. Cíl: pokračovat vždycky až na její slovo – aspoň pět takových pauz.|300|misionar",
    "Miluj se s ní na boku tak, že ji držíš za rameno a přitahuješ k sobě.|240|lzicka",
    "Lžička a putující ruka: Miluj ji na lžičku a rukou jí přitom přejížděj po břiše a stehnech. Cíl: pět minut a ruku nezastavit.|300|lzicka",
    "Horní noha ke stropu: Nech ji ležet na boku, zvedni jí horní nohu ke stropu a vnikni do ní z boku. Cíl: čtyři minuty a nohu nespustit.|240|lzicka",
    "Nůžky vleže: Ona leží na boku, ty klečíš mezi jejíma nohama a vnikáš do ní. Hloubka i úhel jsou jiné. Cíl: čtyři minuty a najít, co jí sedne.|240|lzicka",
    "Dlaň na jejích ústech: Miluj ji v misionáři a zakryj jí ústa dlaní. Cíl: čtyři minuty – kdykoli řekne stop, ruku hned sundat.|240|misionar",
    "Miluj se s ní a nech ji, ať ti nehty zarývá do zad.|240|misionar",
    "Kolena co nejvíc od sebe: Miluj ji v misionáři, podlož jí obě kolena rukama a rozevři je co nejvíc. Cíl: čtyři minuty a ani jednou je nepustit.|240|misionar",
    "Ruce nad hlavou při sexu: Miluj ji v misionáři, zatímco leží s rukama nad hlavou. Cíl: čtyři minuty – jakmile je sundá, zastavíš se v ní.|240|misionar",
    "Sto přírazů: Miluj ji a udělej přesně sto přírazů, pak se zastavíš, ať jste kdekoli. Cíl: dojít do sta bez ztráty rytmu.|300|misionar",
    "V misionáři ji drž za zápěstí a vnikej pomalu.|240|misionar",
    "Miluj se s ní tak, že jí jednu nohu položíš přes svoje rameno a druhou kolem pasu.|240|nohy_ramena",
    "S polštářem pod boky přirážej shora dolů. Úhel je pro ni jiný.|240|misionar_polstar",
    "Nohy si nastaví sama: Nech ji, ať si sama nastaví nohy tak, jak jí to nejvíc vyhovuje, a teprve pak do ní vnikni. Cíl: nic jí neupravovat.|240|misionar",
    "Přírazy a jazyk: Miluj se s ní a mezi tím jí střídavě olizuj bradavky. Cíl: čtyři minuty a každou bradavku aspoň pětkrát.|240|misionar",
    "Pomalá pětka: Miluj ji tak pomalu, abyste u toho stihli normálně mluvit. Cíl: pět minut a nepřestat si povídat.|300|misionar",
    "Lýtko k rameni: Miluj ji v misionáři, drž jí nohu za lýtko a tlač ji k jejímu rameni. Cíl: čtyři minuty a ptát se, jestli to není moc.|240|nohy_ramena",
    "Miluj se s ní na boku a druhou rukou si drž její zadeček.|240|lzicka",
    "Lžička a lubrikant: Použij hodně lubrikantu a miluj ji na lžičku co nejpomaleji. Cíl: pět minut a ani jednou nezrychlit.|300|lzicka",
    "Vzpřímeně na kolenou: Nech ji ležet na zádech, klekni si vzpřímeně mezi její nohy a vnikni do ní. Cíl: čtyři minuty a držet ji za boky.|240|misionar",
    "Vzpřímeně nad ní: Klečíš mezi jejíma nohama, vnikáš do ní a držíš ji za boky zvednutou k sobě. Cíl: nést její váhu celé čtyři minuty.|240|nohy_ramena",
    "Miluj se s ní tak, že se drží tvých ramen a přitahuje si tě.|240|misionar",
    "Pět a pět: Miluj ji v misionáři a střídej pět hlubokých a pět mělkých přírazů. Cíl: čtyři minuty a ani jednou se nesplést.|240|misionar",
    "Nehty při zpomalení: Miluj ji a pokaždé, když zpomalíš, ti zaryje nehty do zad. Cíl: deset zpomalení a deset škrábnutí.|240|misionar",
    "Miluj se s ní a mezi tím jí drž obě kolena u jejích ramen.|240|nohy_ramena",
    "Ruce pod ní: Vnikni do ní, dej jí obě ruce pod zadeček a celou dobu ji drž nahoře. Cíl: čtyři minuty a ani jednou ji nepoložit.|240|misionar_polstar",
    "Šeptá ti, co dál: Vnikni do ní vleže a nech ji, ať ti šeptá do ucha, co má přijít dál. Cíl: pět minut a plnit každý její návrh.|300|propletene",
    "Stop na každý výdech: Miluj ji v misionáři a pokaždé, když vydechne, zůstaň v ní bez pohybu. Cíl: čtyři minuty a ani jeden výdech nepropásnout.|240|misionar",
    "Miluj se s ní na boku a nech ji, ať si sama drží nohu.|240|lzicka",
    "Hýbe se jen ona: Vnikni do ní shora a pak se vůbec nehýbej – přirážet smí jen ona zespodu. Cíl: čtyři minuty a ani jeden tvůj pohyb.|240|misionar",
    "Dvě polohy: Miluj ji dvě minuty v misionáři a pak přejdi na lžičku, aniž bys z ní vyšel. Cíl: přechod bez jediného přerušení.|300|lzicka",
    "Polštář z hlavy pod boky: Miluj ji v misionáři, pak jí sundej polštář zpod hlavy a podlož jí ho pod boky. Cíl: čtyři minuty a zeptat se, co je lepší.|240|misionar_polstar",
    "Nakonec zůstaň v ní a jen se líbejte, dokud se nezklidníte.|120|propletene",
  ],

  female: [
    "Misionář naplno: Nech ho na sebe lehnout a vniknout do tebe, obejmi ho nohama a tempo přírazů mu urči rukama na bocích. Cíl: ani jednou nezrychlit.|240|misionar",
    "Propletené prsty: Dej si ruce nad hlavu, nech si od něj proplést prsty a nech ho do tebe vnikat. Cíl: čtyři minuty přírazů a prsty ani jednou nerozpojit.|240|misionar",
    "Neuhnout pohledem: Nech ho nahoře vnikat do tebe a celou dobu se mu dívej do očí. Cíl: čtyři minuty přírazů – kdo první uhne, plní úkol navíc.|240|misionar",
    "Polštář změní úhel: Podlož si pod boky polštář a nech ho vniknout shora. Cíl: čtyři minuty a pak mu říct, jestli je to lepší.|240|misionar_polstar",
    "Krátce a rychle na přání: S polštářem pod boky ho popros o krátké a rychlé přírazy. Cíl: tři minuty a ani jeden hluboký.|180|misionar_polstar",
    "Pomalu a hluboko s nohama nahoře: Dej si nohy na jeho ramena a nech ho jít pomalu a hluboko. Cíl: čtyřicet přírazů a žádný rychlý.|240|nohy_ramena",
    "Tempo určuje on: Dej si nohy na jeho ramena, nech ho vniknout a tempo přírazů vede celé on. Cíl: čtyři minuty a ty se vůbec nehýbeš.|240|nohy_ramena",
    "Hluboko a pomalu: Nohy máš na jeho ramenou a on hluboko v tobě. Deset úplně pomalých přírazů a pak minutu nic. Cíl: tři taková kola.|300|nohy_ramena",
    "Nahoře a dole: Jednu nohu si dej na jeho rameno, druhou nech dole a nech ho do tebe vnikat. Cíl: po dvou minutách nohy prohodit a říct, co je lepší.|240|nohy_ramena",
    "Kolena k hrudníku: Přitáhni si kolena k hrudníku a nech ho vniknout do tebe co nejhlouběji. Cíl: čtyři minuty přírazů a každou minutu říct, jestli to není moc.|240|nohy_ramena",
    "Minuta jen polibků: Ať v tobě zůstane úplně bez pohybu a jen tě líbá. Cíl: celá minuta a ani jeden příraz.|60|misionar",
    "Nejblíž, jak to jde: Propleť si s ním nohy, nech ho v sobě a hýbej se jen boky. Cíl: čtyři minuty přírazů a neodtrhnout se od sebe.|240|propletene",
    "Celý na tobě: Nech ho lehnout si na tebe celou vahou, vniknout a přirážet jen pánví. Cíl: dojít bez jediného velkého pohybu.|300|propletene",
    "Dívá se na tebe shora: Nech ho přirážet opřeného o natažené paže, ať se na tebe celou dobu dívá. Cíl: čtyři minuty a paže nesmí pokrčit.|240|misionar",
    "Jen do poloviny jemu: Nech ho vnikat jen napůl a pokaždé se zase stáhnout. Cíl: třicet přírazů a ani jeden hlubší.|180|misionar",
    "Deset a deset s počítáním: Řekni mu, ať udělá deset pomalých a deset rychlých přírazů, a počítej nahlas. Cíl: šest kol bez chyby.|240|misionar",
    "Rameno v dlani: Miluj se s ním na boku čelem k sobě a celou dobu se ho drž za rameno. Cíl: čtyři minuty a ani jednou ho nepustit.|240|lzicka",
    "Horní noha nahoru: Lehni si na lžičku, zvedni horní nohu a nech ho vniknout zezadu. Cíl: čtyři minuty a nohu nespustit.|240|lzicka",
    "Lžička naplno: Nech ho vniknout zezadu na lžičku a jeho ruku si dej zepředu na klitoris. Nesmí zrychlit. Cíl: nechat se dovést pomalu.|300|lzicka",
    "Polibky na krk zezadu: Miluj se s ním na lžičku a nech se celou dobu líbat na rameno a krk. Cíl: čtyři minuty a nedovolit mu přestat.|240|lzicka",
    "Propleteni na boku: Propleť si na boku nohy s jeho, nech ho v sobě a hýbejte se jen minimálně. Cíl: čtyři minuty a ani jeden velký příraz.|240|lzicka",
    "Šepot za zády: Opři se o něj zády, nech ho vniknout zezadu a celou dobu ti šeptat do ucha. Cíl: čtyři minuty přírazů a nesmí ztichnout.|240|lzicka",
    "Ruka nad hlavou na boku: Miluj se s ním na boku a nech si od něj držet ruku nad hlavou. Cíl: čtyři minuty a nesmí ji pustit.|240|lzicka",
    "Ruka na prsou zezadu: Miluj se s ním na lžičku pomalu a jeho ruku si nech na prsou. Cíl: pět minut a ruku mu nedovolit sundat.|300|lzicka",
    "Pět minut na boku: Nech ho vniknout zezadu na lžičku a zůstaňte tak celých pět minut. Cíl: pět minut přírazů bez jediné změny polohy.|300|lzicka",
    "Obtoč ho nohama: Nech ho lehnout si na tebe, vniknout do tebe a obejmi ho nohama kolem pasu. Cíl: čtyři minuty přírazů a nohy ani jednou nerozpojit.|240|propletene",
    "Zvedne ti boky: Nech si od něj podložit boky rukama, zvednout k sobě a tak do tebe přirážet. Cíl: čtyři minuty a ruce ti nesmí vytáhnout.|240|misionar",
    "Říkej si o polibky: Nech ho vnikat a mezi tím si nahlas říkej o polibky na krk. Cíl: dvacet polibků a ani jeden bez vyžádání.|240|misionar",
    "Nohy pevně u sebe: Natáhni nohy a pevně je stiskni k sobě, zatímco je v tobě. Cíl: čtyři minuty a ani jednou je nerozevřít.|240|propletene",
    "Nohy k sobě: Nohy měj úplně u sebe, on je nad nimi a vniká do tebe. Bude to těsnější. Cíl: čtyři minuty přírazů a nohy nerozevřít.|240|propletene",
    "Pauza na deset vteřin: Nech ho přirážet a zastavit se pokaždé, když se blížíš, a pokračovat až za deset vteřin. Cíl: čtyři pauzy, než tě nechá dojít.|300|misionar",
    "Ruce přitisknuté k tělu: Nech si od něj držet obě ruce u těla a přirážet do tebe, ať se nemůžeš hýbat. Cíl: čtyři minuty a nesmí tě pustit.|240|misionar",
    "Sama si pomáháš: S polštářem pod boky si sama dráždi klitoris, zatímco je v tobě. Cíl: pět minut a nenechat ho zasáhnout.|300|misionar_polstar",
    "Pohyb děláš ty: Nech ho vniknout a hned se úplně zastavit. Cíl: tři minuty, při kterých se hýbeš výhradně ty.|180|misionar",
    "Nech ho kleknout si pod tvoje stehna, zvednout tě k sobě a vniknout do tebe. Cíl: čtyři minuty přírazů a nespustit tě dolů.|240|nohy_ramena",
    "Opři si kotníky o jeho ramena, nech se držet za boky a nech ho hluboko přirážet. Cíl: čtyři minuty a kotníky ani jednou nespustit.|240|nohy_ramena",
    "Do kříže: Ty ležíš na zádech, on na boku napříč přes tvoje nohy a zezadu do tebe vniká. Cíl: čtyři minuty a najít úhel, u kterého to sedne.|240|propletene",
    "Nech ho v misionáři přirážet a po každých deseti přírazech ho polib. Cíl: deset polibků a ani jeden vynechat.|240|misionar",
    "Zvedni jednu nohu, nech si ji od něj podržet za kotník a nech ho tak do tebe vnikat. Cíl: čtyři minuty přírazů a nohu nespustit.|240|nohy_ramena",
    "Nech ho vnikat velmi pomalu a poslouchej, jak dýchá.|300|misionar",
    "Nech ho vniknout, lehnout si na tebe a nehýbat se. Všechnu práci odvedou tvoje boky. Cíl: čtyři minuty a hýbeš se jen ty.|240|propletene",
    "Miluj se s ním na boku a nech si držet bradu, ať se musíš dívat.|240|lzicka",
    "Vibrátor si držíš sama: Miluj se s ním na lžičku a sama si zepředu přikládej vibrátor. Cíl: pět minut a nenechat ho na něj sáhnout.|300|lzicka",
    "Tři stupně: Nech ho přirážet minutu pomalu, minutu středně a minutu naplno. Cíl: tři minuty a ani jednou nezpomalit zpět.|180|misionar",
    "Dej si ruce pod záda, nech ho, ať si tě přitáhne na sebe, a přirážet. Cíl: čtyři minuty a ruce nevytáhnout.|240|misionar",
    "Polož si obě nohy na jeho hrudník a odtlačuj se proti jeho přírazům. Cíl: čtyři minuty a pokaždé se odtlačit.|240|nohy_ramena",
    "Kousej ho do ramene: Nech ho vnikat a mezi tím ho vždycky lehce kousni do ramene. Cíl: deset kousnutí a pokaždé o kousek jinam.|240|propletene",
    "Řekni mu, ať se místo přírazů pohybuje do kruhu.|240|misionar",
    "Kroužení: Nech ho v sobě a ať krouží pánví do kruhu místo přírazů dopředu a dozadu. Cíl: pět minut kroužení a ani jednou nepřirazit.|300|misionar",
    "S polštářem pod boky si dej jeho ruce pod zadeček a nech ho shora přirážet. Cíl: čtyři minuty a boky nepoložit.|240|misionar_polstar",
    "Dej si nohy na jeho ramena a nech ho naklonit se dopředu a vniknout co nejhlouběji. Cíl: čtyři minuty přírazů a nohy neuhnout.|240|nohy_ramena",
    "Nech ho vniknout, pak ho zastav a nech ho v sobě čekat, dokud sama neřekneš pokračuj. Cíl: tři takové pauzy po půl minutě.|300|misionar",
    "Miluj se s ním na boku a nech se přitahovat za rameno.|240|lzicka",
    "Jeho ruka putuje: Miluj se s ním na lžičku a nech mu ruku přejíždět po břiše a stehnech. Cíl: pět minut a ruku nesmí zastavit.|300|lzicka",
    "Lehni si na bok, zvedni horní nohu ke stropu a nech ho tak do tebe vnikat. Cíl: čtyři minuty přírazů a nohu nespustit.|240|lzicka",
    "Nůžky vleže: Ty na boku, on klečí mezi tvýma nohama a přiráží. Hloubka i úhel jsou jiné. Cíl: čtyři minuty a říct mu, který úhel ti sedne.|240|lzicka",
    "Nech ho přirážet, zakrýt ti ústa dlaní a zkus být úplně potichu. Cíl: čtyři minuty a ani jednou nevydat hlásku.|240|misionar",
    "Nech ho přirážet a zarývej mu nehty do zad pokaždé, když zrychlí. Cíl: deset zrychlení a pokaždé nehty.|240|misionar",
    "Nech si podložit obě kolena, rozevřít je co nejvíc a nech ho hluboko vnikat. Cíl: čtyři minuty přírazů a kolena nesevřít.|240|misionar",
    "Ruce nahoře: Dej si ruce nad hlavu a nech ho vniknout. Cíl: čtyři minuty a ani jednou ruce nesundat.|240|misionar",
    "Sto přírazů: Nech ho vniknout a nahlas počítej přírazy, u stovky se oba zastavte. Cíl: dojít do sta bez ztráty rytmu.|300|misionar",
    "Nech si držet zápěstí nad hlavou, nech ho přirážet a užívej si, že nemáš kontrolu. Cíl: čtyři minuty a o pauzu neříct.|240|misionar",
    "Dej si jednu nohu přes jeho rameno, druhou kolem jeho pasu a nech ho vniknout. Cíl: čtyři minuty přírazů a nohy neprohodit.|240|nohy_ramena",
    "S polštářem pod boky ho nech přirážet shora dolů. Úhel je jiný.|240|misionar_polstar",
    "Nastav si nohy tak, ať do tebe vniká přesně jak chceš, a nahlas mu to řekni. Cíl: tři úpravy za čtyři minuty a každou vyslovit.|240|misionar",
    "Nech se milovat a mezi tím si říkej o olizování bradavek.|240|misionar",
    "Pomalá pětka: Nech ho přirážet tak pomalu, abyste u toho stihli mluvit. Cíl: pět minut a ani jednou se neodmlčet.|300|misionar",
    "Nech si od něj přitlačit nohu za lýtko k rameni a tak do tebe vnikat. Cíl: čtyři minuty přírazů a nohu nestáhnout.|240|nohy_ramena",
    "Miluj se s ním na boku a nech si držet zadeček.|240|lzicka",
    "Nech ho na lžičku vniknout hodně pomalu a s dostatkem lubrikantu. Cíl: pět minut pomalých přírazů a ani jednou nezrychlit.|300|lzicka",
    "Nech ho kleknout si mezi tvoje nohy vzpřímeně, vniknout a opři se o lokty. Cíl: čtyři minuty přírazů a z loktů nesjet.|240|misionar",
    "Vzpřímeně nad tebou: Klečí mezi tvýma nohama, drží tě za boky a přiráží do tebe zvednuté. Cíl: čtyři minuty a nechat ho nést tvoji váhu.|240|nohy_ramena",
    "Přitahuj si ho: Chytni se jeho ramen a přitahuj si ho k sobě při každém přírazu. Cíl: čtyři minuty, při kterých tempo určuješ jen ty.|240|misionar",
    "Nech ho vniknout a řekni mu, ať střídá pět hlubokých a pět mělkých přírazů. Cíl: deset takových kol a nesplést se.|240|misionar",
    "Nech ho přirážet a jeď mu nehty po zádech pokaždé, když zpomalí. Cíl: deset zpomalení a pokaždé nehty.|240|misionar",
    "Nech si od něj přitlačit obě kolena k ramenům a hluboko do tebe vnikat. Cíl: čtyři minuty přírazů a kolena nespustit.|240|nohy_ramena",
    "Ruce pod tebou: Ať ti dá obě ruce pod zadeček, drží tě nahoře a celou dobu do tebe přiráží. Cíl: čtyři minuty a ani jednou tě nesmí položit.|240|misionar_polstar",
    "Nech ho lehnout si na tebe, vniknout a šeptej mu do ucha, jak má přirážet. Cíl: pět pokynů za pět minut a všechny splnit.|300|propletene",
    "Nech ho přirážet a ať se zastaví pokaždé, když nahlas vydechneš. Cíl: deset zastavení za čtyři minuty.|240|misionar",
    "Nohu si držíš sama: Miluj se s ním na boku a horní nohu si celou dobu drž sama. Cíl: čtyři minuty a ani jednou ji nespustit.|240|lzicka",
    "Nech ho vniknout a zůstat nad tebou bez hnutí – přirážet smíš jen ty boky. Cíl: čtyři minuty a on se ani jednou nepohne.|240|misionar",
    "Dvě polohy: Nech ho vniknout v misionáři a po dvou minutách přejděte na lžičku, aniž by z tebe vyšel. Cíl: přechod bez jediného přerušení přírazů.|300|lzicka",
    "Vyndej si polštář zpod hlavy, dej si ho pod boky a nech ho tak do tebe vnikat. Cíl: čtyři minuty přírazů a boky držet nahoře.|240|misionar_polstar",
    "Nech ho po posledním přírazu zůstat v sobě a jen se líbejte, dokud se oba nezklidníte. Cíl: dvě minuty bez jediného pohybu boků.|120|propletene",
  ],
});
