// Kategorie 4 – Sex a polohy (dávka e)
// Témata: tempo jako hra, pravidla a zákazy, pomůcky při sexu, orgasmus jako výzva.
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 4,

  male: [
    "Deset a deset: Deset pomalých přírazů, deset rychlých, pořád dokola. Ona počítá nahlas. Cíl: pět celých kol bez jediné chyby.|300|misionar",
    "Podle nádechu: Pohybuj se jen tehdy, když se ona nadechne, a při výdechu stůj. Cíl: padesát nádechů a ani jeden nepropásnout.|300|misionar",
    "Jméno znamená stop: Miluj se s ní a pokaždé, když řekne tvoje jméno, se úplně zastav. Cíl: pět minut a ani jednou to nepropásnout.|300|ona_nahore",
    "Tempo tleskáním: Ona ti tleskáním určuje tempo a ty musíš držet krok. Cíl: pět minut a ani jednou se netrefit vedle.|300|ona_nahore",
    "Stop a start: Ona říká stop a start, kdy se jí zachce, a ty se řídíš na vteřinu přesně. Cíl: pět minut bez jediného zpoždění.|300|zezadu",
    "Dokud nepoprosí: Přirážej co nejpomaleji, jak jen dokážeš. Cíl: nezrychlit, dokud tě sama nahlas nepoprosí.|300|misionar",
    "Pět a jeden: Pět pomalých přírazů a po nich vždycky jeden úplně rychlý. Cíl: dvacet kol a ani jednou pořadí nesplést.|300|zezadu",
    "Stupeň za minutu: Začni úplně pomalu a každou minutu zrychli o jeden stupeň. Cíl: pět stupňů a ani jednou se nevrátit zpět.|300|misionar",
    "Jen mělce: Pohybuj se výhradně v posledních pár centimetrech a nikdy nejdi hluboko. Cíl: pět minut a ani jeden hluboký příraz.|300|zezadu",
    "Naopak: Jdi vždycky jen hodně hluboko a nikdy mělce. Cíl: udržet hloubku celou dobu.|300|misionar",
    "Ruce jen na posteli: Miluj se s ní, ale rukama se smíš dotýkat jen postele. Cíl: čtyři minuty a ani jednou na ni nesáhnout.|240|misionar",
    "Bez rukou: Ruce máš celou dobu opřené vedle ní a nesmíš se jí dotknout. Cíl: dokázat to.|240|misionar",
    "Oči otevřené: Miluj se s ní vsedě a ani jeden z vás nesmí zavřít oči. Cíl: pět minut – kdo je zavře první, plní přání toho druhého.|300|klin_celem",
    "Rozmluv ji: Ona nesmí vydat ani hlásku a ty děláš všechno pro to, aby to nevydržela. Cíl: rozmluvit ji do pěti minut.|300|zezadu",
    "Ticho a tma: Zhasněte a nikdo z vás nesmí promluvit. Jen dech. Cíl: dorozumět se beze slov.|300|misionar",
    "Musí si říkat: Ona musí nahlas říkat, co chce. Jakmile ztichne, přestáváš. Cíl: pět minut a nejvýš tři pauzy.|300|ona_nahore",
    "Komentuješ celou dobu: Miluj ji zezadu a celou dobu nahlas popisuj, co právě děláš. Cíl: pět minut a ani jednou neztichnout.|300|zezadu",
    "Její ruce mimo hru: Miluj se s ní a ona nesmí použít ruce k ničemu, ani se držet. Cíl: pět minut a ani jednou pravidlo neporušit.|300|misionar",
    "Pravidlo pohledu: Nesmíte se přestat dívat do očí. Když jeden uhne, měníte polohu. Cíl: vydržet v jedné.|300|klin_celem",
    "Nasadí ti ho ona: Nech ji, ať ti sama nasadí erekční kroužek, a pak se s ní miluj. Cíl: pět minut a ani jednou nezrychlit.|300|misionar",
    "S kroužkem a pomalu: Nasaď si erekční kroužek a nech ji na sobě jezdit hodně pomalu. Cíl: pět minut a ani jednou nezrychlit.|300|ona_nahore",
    "Vibrátor mezi vámi: Drž jí vibrátor na klitorisu, zatímco jsi v ní. Cíl: pět minut a ani jednou ho nesundat.|300|misionar",
    "Vibrátor při sexu: Ona si drží vibrátor sama a ty se jen hýbeš. Cíl: nechat to na ní.|300|ona_nahore",
    "Zepředu a zezadu: Přilož jí vibrátor zezadu, zatímco do ní vnikáš zepředu. Cíl: pět minut a obojí ve stejném rytmu.|300|misionar",
    "Kravata nad hlavou: Sváž jí ruce kravatou nad hlavou tak, aby uzel šel rozvázat jedním tahem. Cíl: pět minut a na stop ji rozvázat.|300|pouta_postel",
    "Svázané ruce zezadu: Sváž jí ruce kravatou za zády, uzel volně, a miluj ji zezadu. Cíl: pět minut a na stop ji hned rozvázat.|300|zezadu",
    "S kravatou: Zavaž jí oči kravatou a miluj se s ní. Ona nesmí vědět, co přijde. Cíl: překvapit ji třikrát.|300|misionar",
    "Změna poloh beze slov: Zavaž jí oči a měň polohy, aniž bys řekl jediné slovo. Cíl: čtyři polohy a veď ji jen rukama.|300|zezadu",
    "Rána po patnáctém: Miluj ji zezadu a po každých patnácti přírazech ji plácni po zadečku. Cíl: pět ran a síla pokaždé stejná.|300|zezadu",
    "Jemně za vlasy: Miluj ji zezadu a jemně ji tahej za vlasy. Cíl: deset zatažení a po každém se zeptat, jestli chce víc.|300|zezadu",
    "Dlaň na krku: Miluj se s ní a polož jí ruku na krk – jen položit, žádný tlak. Cíl: kdykoli řekne stop, ruku hned sundat.|300|misionar",
    "Kousnutí v pravou chvíli: Miluj ji na lžičku a kousni ji do ramene přesně ve chvíli, kdy je nejblíž vrcholu. Cíl: trefit se aspoň dvakrát.|300|lzicka",
    "Deset plácnutí: Během úkolu ji desetkrát plácneš, pokaždé jinak silně. Ona počítá. Cíl: dojít do deseti.|300|zezadu",
    "Ona vždycky první: Miluj se s ní a hlídej si vlastní vzrušení. Cíl: nechat ji dojít první a teprve pak myslet na sebe.|300|ona_nahore",
    "Oba naráz: Miluj se s ní a hlídejte si tempo tak, abyste došli ve stejnou chvíli. Cíl: trefit se do pěti vteřin.|300|misionar",
    "Společně: Snažte se dojít naráz. Když se to nepovede, zkusíte to znovu. Cíl: trefit to na první pokus.|300|klin_celem",
    "Dvakrát ona, pak ty: Miluj se s ní a hlídej si vlastní vzrušení. Cíl: nechat ji dojít dvakrát dřív, než se uděláš ty.|300|ona_nahore",
    "Třikrát na hranu: Doveď ji až na hranu a pak pokaždé zpomal. Cíl: třikrát ji zastavit a počtvrté ji nechat dojít.|300|misionar",
    "Edging při sexu: Kdykoli je blízko, úplně se zastavíš. Pětkrát. Cíl: vydržet všech pět.|300|zezadu",
    "Počítej do sta: Zakaž jí dojít, dokud nahlas nedopočítá do sta. Cíl: nenechat ji přeskočit ani jedno číslo.|300|ona_nahore",
    "Musí to vyslovit: Ona nesmí dojít, dokud nahlas neřekne, co přesně chce. Cíl: nepolevit, dokud to neřekne celou větou.|300|misionar",
    "Obě zápěstí v jedné ruce: Miluj se s ní a jednou rukou jí drž obě zápěstí nad hlavou. Cíl: pět minut a ani jednou ji nepustit.|300|misionar",
    "Vybírá všechno ona: Nech ji vybrat polohu, tempo i délku a ty jen plníš. Cíl: pět minut a ani jednou si nedělat po svém.|300|ona_nahore",
    "Její hra: Celou dobu rozhoduje ona o poloze i tempu a ty neřekneš ani slovo. Cíl: pět minut a nepřevzít vedení.|300|ona_nahore",
    "Rozhoduješ ty: Ty určuješ polohu, tempo i pauzy a ona jen poslouchá. Cíl: pět minut a nenechat se přemluvit ke změně.|300|zezadu",
    "Výměna velení: Po každé minutě si prohodíte, kdo z vás rozhoduje o tempu. Cíl: pět výměn a ani jednou se nepřerušit.|300|klin_celem",
    "Led po zádech: Miluj ji zezadu a mezi tím jí přejížděj kostkou ledu po zádech. Cíl: pět cest ledem a ani jednou nezpomalit.|300|zezadu",
    "Led při sexu: Kostka ledu na jejích zádech, zatímco jsi v ní. Cíl: nenechat ji spadnout.|300|na_brise",
    "Pírko při sexu: Miluj se s ní a mezi tím jí přejížděj pírkem po prsou. Cíl: deset cest pírkem a ani jednou nepřerušit tempo.|300|misionar",
    "Neslyší tě: Dej jí sluchátka s hudbou, ať tě neslyší, a miluj ji zezadu. Cíl: pět minut a domluvit se jen doteky.|300|zezadu",
    "Oba v zrcadle: Miluj se s ní před zrcadlem tak, ať se oba vidíte. Cíl: pět minut a nespustit z ní v zrcadle oči.|300|zezadu",
    "Jen zvuk: Nahraj si na telefon zvuk celého úkolu a pak si ho spolu poslechněte. Cíl: nahrávku dotáhnout do konce a nezastavit ji.|300|misionar",
    "Fantazie do ucha: Miluj ji na lžičku a do ucha jí popisuj svoji fantazii. Cíl: pět minut a ani jednou neztichnout.|300|lzicka",
    "Scénka: Vyberte si roli a celou dobu v ní zůstaňte, i když to bude k smíchu. Cíl: nevypadnout z role.|300|zezadu",
    "Aspoň jednou se zasmát: Miluj se s ní vsedě a najdi způsob, jak se oba rozesmát. Cíl: aspoň jeden společný smích za čtyři minuty.|240|klin_celem",
    "Beze změny: Miluj se s ní a nezměň ani polohu, ani tempo. Cíl: vydržet celých pět minut úplně stejně.|300|misionar",
    "Budík velí: Nastav si budík na každou minutu a při každém zazvonění změňte polohu. Cíl: pět poloh a nejvýš jedno vyklouznutí.|300|zezadu",
    "Pět minut, pět poloh: Každou minutu jiná poloha a žádná se nesmí opakovat. Cíl: pět různých poloh bez přerušení.|300|zezadu",
    "Nehty jako signál: Miluj se s ní a nech ji, ať ti zaryje nehty do zad, když je blízko. Cíl: podle toho pokaždé zrychlit.|300|misionar",
    "Dokud neřekne dost: Miluj ji zezadu stejným tempem. Cíl: nepřestat, dokud sama neřekne dost.|300|zezadu",
    "Krk a rameno: Miluj ji na lžičku a mezi tím jí olizuj krk a rameno. Cíl: pět minut a nepřestat ani u jednoho.|300|lzicka",
    "Konec podle ní: Nech ji vybrat, čím to skončí – tebou, rukou, nebo vibrátorem. Cíl: dotáhnout její volbu až do konce.|300|ona_nahore",
    "Před koncem: Poslední minutu už nesmíš nic měnit. Žádná nová poloha, žádné nové tempo. Cíl: dojet to, jak to je.|60|misionar",
    "Miluj se s ní a nech ji říkat čísla od desíti dolů. Na nule končíte.|300|ona_nahore",
    "Dej jí do ruky vibrátor a řekni, že ho může použít, kdy chce.|300|misionar",
    "Nasaď si kroužek a nech ji rozhodnout, jak dlouho to bude trvat.|300|ona_nahore",
    "Miluj se s ní a mezi tím jí drž obě ruce za zády.|300|zezadu",
    "Sváž jí kravatou jednu ruku k posteli a druhou nech volnou.|300|pouta_postel",
    "Poslušnost: Dáš jí tři příkazy během úkolu a ona je musí splnit hned. Cíl: ani jedno zaváhání.|300|zezadu",
    "Miluj se s ní a mezi tím jí jemně kousni do zadečku.|300|na_brise",
    "Nech ji, ať si sedne na tebe a řekne ti, kdy smíš dojít.|300|ona_nahore",
    "Miluj se s ní a nech ji říkat po každé minutě, co má být jinak.|300|misionar",
    "Zkus to celé bez jediného polibku. Uvidíš, jak bude chybět.|300|zezadu",
    "Polibek bez konce: Miluj se s ní vsedě a celou dobu se líbejte. Cíl: pět minut a polibek ani jednou nepřerušit.|300|klin_celem",
    "Nepřerušený polibek: Celý úkol se musíte líbat. Když polibek přerušíte, začínáte znovu. Cíl: vydržet.|300|klin_celem",
    "Miluj se s ní a mezi tím jí hlaď prsa oběma rukama.|300|zezadu_vzpr",
    "Nech ji na sobě sedět a jen ji držet. Ať se hýbe sama.|300|ona_nahore",
    "Miluj se s ní tak, aby to bylo co nejtišší. Ani postel nesmí vrzat.|300|misionar",
    "Naopak buďte co nejhlasitější. Ať to není k vydržení.|300|zezadu",
    "Souboj o kontrolu: Oba se snažíte určovat tempo. Kdo se první podvolí, splní přání. Cíl: nevzdat to.|300|klin_celem",
    "Miluj se s ní a mezi tím jí šeptej, jak blízko jsi.|300|lzicka",
    "Nech ji, ať ti řekne, kdy má být konec, a ty to dodrž na vteřinu.|300|ona_nahore",
    "Na konci v ní zůstaň a jen ji drž, dokud se oba nezklidníte.|120|propletene",
  ],

  female: [
    "Deset pomalu, deset rychle: Deset pomalých pohybů, deset rychlých, pořád dokola. On počítá. Cíl: pět celých kol bez chyby.|300|ona_nahore",
    "Hýbej se jen tehdy, když se on nadechne. Při výdechu stůj.|300|ona_nahore",
    "Jakmile vysloví tvoje jméno, okamžitě se zastav a počkej.|300|ona_nahore",
    "Tempo si určuje on tleskáním. Ty musíš držet krok.|300|ona_nahore",
    "Na jeho povel: On říká stop a start, kdy se mu zachce, a ty se řídíš na vteřinu přesně. Cíl: pět minut bez jediného zpoždění.|300|ona_nahore",
    "Jeď co nejpomaleji, dokud tě sám nepoprosí o rychleji.|300|ona_nahore",
    "Pět a jeden na něm: Pět pomalých pohybů a po nich vždycky jeden úplně rychlý. Cíl: dvacet kol a ani jednou pořadí nesplést.|300|ona_nahore",
    "Začni na nejpomalejším tempu a po každé minutě přidej jeden stupeň.|300|ona_nahore",
    "Zůstávej nahoře a sedej si jen o pár centimetrů. Nikdy až dolů.|300|ona_nahore",
    "Naopak: Sedej si vždycky úplně dolů a nikdy jen mělce. Cíl: udržet hloubku celou dobu.|300|ona_nahore",
    "Miluj se s ním, ale nesmíš se dotknout rukama ničeho kromě postele.|240|ona_nahore",
    "Bez rukou: Ruce máš celou dobu opřené vedle něj a nesmíš se ho dotknout. Cíl: dokázat to.|240|ona_nahore",
    "Kdo zavře oči: Miluj se s ním vsedě a ani jeden z vás nesmí zavřít oči. Cíl: pět minut – kdo je zavře první, plní přání toho druhého.|300|klin_celem",
    "On nesmí vydat ani hlásku. Ty děláš všechno pro to, aby to nevydržel.|300|ona_nahore",
    "Potmě a beze slov: Zhasněte a celou dobu mlčte, zbude vám jen dech a doteky. Cíl: dorozumět se bez mluvení.|300|misionar",
    "Musí si říct: On musí nahlas říkat, co chce. Jakmile ztichne, přestáváš. Cíl: pět minut a nejvýš tři pauzy.|300|ona_nahore",
    "Nahlas popisuj každý svůj pohyb a ani na chvíli se neodmlč.|300|ona_nahore",
    "Jeho ruce mimo hru: Jezdi na něm a on nesmí použít ruce k ničemu, ani se držet. Cíl: pět minut a ani jednou pravidlo neporušit.|300|ona_nahore",
    "Z očí do očí: Dokud se díváte, zůstáváte v poloze. Jakmile jeden uhne, měníte ji. Cíl: pět minut a nezměnit ji ani jednou.|300|klin_celem",
    "Nasaď mu erekční kroužek a pak si na něj sedni.|300|ona_nahore",
    "Kroužek a dlouhé tempo: Nasaď mu erekční kroužek a jezdi na něm hodně pomalu. Cíl: pět minut a ani jednou nezrychlit.|300|ona_nahore",
    "Vezmi vibrátor a drž si ho na klitorisu, zatímco je v tobě.|300|ona_nahore",
    "Vibrátor při sexu: Držíš si vibrátor sama a on se jen hýbe. Cíl: mít to ve svých rukou.|300|misionar",
    "Nech si přiložit vibrátor zezadu, zatímco do tebe vniká zepředu.|300|misionar",
    "Sváž mu ruce kravatou nad hlavou a pak si na něj sedni.|300|pouta_postel!",
    "Sváž mu ruce za zády a nech ho klečet za tebou.|300|zezadu!",
    "S kravatou: Zavaž mu oči kravatou a miluj se s ním. Nesmí vědět, co přijde. Cíl: překvapit ho třikrát.|300|ona_nahore",
    "Zavaž si oči a nech ho změnit polohu beze slova.|300|zezadu!",
    "Řekni mu, ať tě plácne po zadečku vždycky po patnácti pohybech.|300|zezadu",
    "Nech se jemně tahat za vlasy a řekni mu, jestli se ti to líbí.|300|zezadu",
    "Dej si jeho ruku na krk. Jen položit, žádný tlak.|300|misionar",
    "Kousni ho do ramene ve chvíli, kdy je nejblíž.|300|klin_celem",
    "Deset plácnutí: Během úkolu tě desetkrát plácne, pokaždé jinak silně. Ty počítáš. Cíl: dojít do deseti.|300|zezadu",
    "Nech ho dojít první a teprve pak se postarej o sebe.|300|ona_nahore",
    "Zkuste to načasovat tak, abyste se udělali ve stejnou vteřinu.|300|misionar",
    "Naráz: Cílem je dojít oba zároveň, a když to nevyjde, zkusíte to ještě jednou. Cíl: trefit se napoprvé.|300|klin_celem",
    "Třikrát ho zastavit: Doveď ho až na hranu a pak pokaždé zpomal. Cíl: třikrát ho zastavit a počtvrté ho nechat dojít.|300|ona_nahore",
    "Ty první: Jezdi na něm a hlídej mu tempo. Cíl: dojít dřív než on – teprve potom ho nechat.|300|ona_nahore",
    "Pět zastavení: Pokaždé, když je těsně před koncem, se úplně zastav. Cíl: zvládnout všech pět.|300|ona_nahore",
    "Zakaž mu se udělat, dokud nedopočítáš do sta.|300|ona_nahore",
    "On se nesmí udělat, dokud neřekne nahlas, co přesně chce.|300|ona_nahore",
    "Sedni si na něj a nech si držet ruce nad hlavou jednou rukou.|300|misionar",
    "Nech ho vybrat polohu, tempo a jak dlouho. Ty jen plníš.|300|zezadu!",
    "Jeho hra: Celou dobu rozhoduje on o poloze i tempu a ty neřekneš ani slovo. Cíl: pět minut a nepřevzít vedení.|300|zezadu!",
    "Velíš ty: Ty určuješ polohu, tempo i pauzy a on jen poslouchá. Cíl: pět minut a nenechat se přemluvit ke změně.|300|ona_nahore",
    "Velení po minutě: Po každé minutě si vyměňte, kdo z vás velí. Cíl: pět výměn a ani jednou se nepřerušit.|300|klin_celem",
    "Miluj se s ním a mezi tím mu přejížděj ledem po zádech.|300|propletene",
    "Led při sexu: Kostka ledu na jeho zádech, zatímco je v tobě. Cíl: nenechat ji spadnout.|300|propletene",
    "Miluj se s ním a mezi tím mu přejeď pírkem po hrudníku.|300|ona_nahore",
    "Dej mu sluchátka s hudbou, ať tě neslyší, a sedni si na něj.|300|ona_nahore",
    "Miluj se s ním před zrcadlem, ať se oba vidíte.|300|zezadu!",
    "Nahrávka jen se zvukem: Nahrajte si na telefon zvuk celého úkolu a pak si ho spolu poslechněte. Cíl: nahrávku nezastavit dřív než na konci.|300|ona_nahore",
    "Miluj se s ním a přitom mu do ucha popisuj svoji fantazii.|300|lzicka",
    "Role: Každý si vybere postavu a zůstane v ní až do konce, i kdyby to bylo k popukání. Cíl: nevypadnout z ní.|300|zezadu!",
    "Miluj se s ním a mezi tím se oba musíte zasmát. Aspoň jednou.|240|klin_celem",
    "Vydržte pět minut, aniž byste změnili polohu i tempo.|300|ona_nahore",
    "Budík na minutu: Nastavte si budík na každou minutu a při každém zazvonění změňte polohu. Cíl: pět poloh a nejvýš jedno vyklouznutí.|300|zezadu!",
    "Minuta na polohu: Po každé minutě měníte polohu a žádná se nesmí opakovat. Cíl: pět různých poloh bez přerušení.|300|zezadu!",
    "Nehty do zad: Miluj se s ním a pokaždé, když jsi blízko, mu zaryj nehty do zad. Cíl: ať z toho pozná, kdy zrychlit.|300|misionar",
    "Miluj se s ním tak dlouho, dokud neřekne dost.|300|ona_nahore",
    "Miluj se s ním a mezi tím mu olizuj krk a rameno.|300|klin_celem",
    "Nech ho, ať si vybere, čím to skončí – tebou, rukou, nebo ústy.|300|ona_nahore",
    "Před koncem: Poslední minutu už nesmíte nic měnit. Žádná nová poloha, žádné nové tempo. Cíl: dojet to, jak to je.|60|ona_nahore",
    "Miluj se s ním a nech ho říkat čísla od desíti dolů. Na nule končíte.|300|ona_nahore",
    "Vezmi si vibrátor a řekni mu, že ho použiješ, kdy budeš chtít.|300|ona_nahore",
    "Nasaď mu kroužek a rozhodni sama, jak dlouho to bude trvat.|300|ona_nahore",
    "Dej mu ruce za záda a drž mu je, zatímco na něm sedíš.|300|ona_nahore",
    "Sváž mu kravatou jednu ruku k posteli a druhou nech volnou.|300|pouta_postel!",
    "Poslušnost: Dáš mu tři příkazy během úkolu a on je musí splnit hned. Cíl: ani jedno zaváhání.|300|ona_nahore",
    "Miluj se s ním a mezi tím ho jemně kousni do zadku.|300|propletene",
    "Sedni si na něj a řekni mu, kdy se smí udělat.|300|ona_nahore",
    "Miluj se s ním a po každé minutě mu řekni, co má být jinak.|300|misionar",
    "Zkuste to celé bez jediného polibku. Uvidíš, jak bude chybět.|300|zezadu!",
    "Tentokrát naopak: pusa na puse celou dobu, bez jediného přerušení.|300|klin_celem",
    "Jeden dlouhý polibek: Nesmíte se od sebe odtrhnout, jinak začínáte znovu od začátku. Cíl: vydržet do konce.|300|klin_celem",
    "Obě ruce na prsou: Nech se milovat zezadu vkleče a jeho ruce si nech na prsou. Cíl: pět minut a nedovolit mu je sundat.|300|zezadu_vzpr",
    "Sedni si na něj a nech ho jen držet. Hýbáš se jen ty.|300|ona_nahore",
    "Miluj se s ním tak, aby to bylo co nejtišší. Ani postel nesmí vrzat.|300|ona_nahore",
    "Co nejhlasitěji: Tentokrát buďte oba tak hlasití, jak jen dokážete. Cíl: pět minut a ani jednou se neztišit.|300|zezadu!",
    "Přetahovaná: Každý si tahá tempo na svou stranu a kdo první povolí, plní přání toho druhého. Cíl: nevzdat to.|300|klin_celem",
    "Miluj se s ním a mezi tím mu šeptej, jak blízko jsi.|300|lzicka",
    "Nech ho, ať ti řekne, kdy má být konec, a ty to dodrž na vteřinu.|300|ona_nahore",
    "Na konci na něm zůstaň a jen ho drž, dokud se oba nezklidníte.|120|propletene",
  ],
});
