// Kategorie 4 – Sex a polohy
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 4,
  name: "Sex a polohy",
  description: "Polohy po celém bytě, vibrace, první pouta a lehké plácnutí. Konečně naplno.",

  // Úkoly pro muže – pro potěšení ženy
  male: [
    "Posaď ji na kuchyňskou linku, přitáhni si ji za boky k okraji a pomalu do ní vnikni. Líbejte se přitom.|180",
    "Misionář na posteli s polštářem pod jejím zadečkem. Hluboce a pomalu, dívej se jí do očí.|180",
    "Zezadu na gauči – ona klečí na sedáku opřená o opěradlo. Tempo určuje ona tím, jak k tobě přiráží.|180",
    "Při sexu v misionáři jí drž vibrátor na klitorisu.|180",
    "Lžička na boku v posteli. Pomalé přírazy, jednou rukou jí hlaď klitoris, druhou prsa.|240",
    "Opři ji o zeď v chodbě, zvedni jí jednu nohu a miluj se s ní vestoje.|120",
    "Nasaď jí pouta s rukama před tělem a miluj se s ní v misionáři. Ruce jí přidrž nad hlavou.|180",
    "Posaď se na židli bez opěrek, ona si sedne na tebe čelem k tobě. Ty jí pomáháš rukama na bocích.|180",
    "Pomalu do ní vnikni jen špičkou a zase vyjdi. Desetkrát. Pak jednou celý a hluboko.",
    "Ona leží na kraji postele, ty stojíš. Její nohy dej na svá ramena.|180",
    "Zezadu u kuchyňského stolu – ona se o něj opírá předkloněná, ty ji držíš za boky.|180",
    "Plácni ji bičíkem lehce přes zadeček třikrát a pak do ní zezadu pomalu vnikni.",
    "Miluj se s ní a zastav se úplně vždy, když se blíží vrchol. Nech ji chvilku čekat.|240",
    "Ve sprše: ona se opírá rukama o stěnu, ty zezadu. Pozor, ať neuklouznete.|120",
    "Misionář, ale ty se skoro nehýbeš – jen pomalu krouživě boky tlačíš proti jejímu klitorisu.|120",
    "Lehni si na záda a nech ji jezdit na tobě. Ty jí přitom přikládáš vibrátor na klitoris.|180",
    "Zavaž jí oči a miluj se s ní v jakékoli poloze. Každou minutu změň tempo.|240",
    "Posaď ji na pračku, roztáhni jí nohy a miluj se s ní vestoje.|120",
    "Dej jí ruce za záda a drž jí zápěstí jednou rukou, zatímco ji zezadu na posteli miluješ.|120",
    "Poloha „na žabku“: ona leží na zádech s koleny u prsou, ty klečíš a přirážíš hluboko.|120",
    "Na gauči: ona leží na boku, ty klečíš a její horní nohu máš opřenou o rameno.|180",
    "Každých 30 vteřin změňte polohu. Ty vybíráš.|180",
    "Miluj se s ní před zrcadlem tak, aby se na vás mohla dívat.|180",
    "Jen hluboké, pomalé přírazy – a na konci každého chvíli zůstaň v ní a zakruť boky.|120",
    "Ona leží na břiše s polštářem pod boky, ty ležíš na ní a pomalu přirážíš zezadu.|180",
    "Při sexu jí jemně stiskni bradavky a řekni jí, jak úžasně se v ní cítíš.|120",
    "Nasaď jí pouta s rukama za zády, polož ji na postel na břicho a miluj se s ní zezadu.|180",
    "Opři ji o jídelní stůl na zádech, zvedni jí nohy k sobě a miluj se s ní vestoje.|180",
    "Sedni si do křesla, ona si sedne na tebe zády k tobě. Hlaď jí klitoris, zatímco na tobě jezdí.|180",
    "Miluj se s ní a ona smí dojít jen tehdy, až jí to dovolíš. Pak jí to dovol.",
    "Rychle a intenzivně 30 vteřin, pak pomalu 30 vteřin. Opakuj.|180",
    "Misionář s jejíma nohama omotanýma kolem tvého pasu. Líbej ji přitom na krk.|180",
    "Zezadu na posteli – ona klečí, ty jí držíš vlasy jemně v culíku.|120",
    "Poručte si navzájem: ty jí řekneš polohu, ona tempo. Plňte to přesně.|180",
    "Pomalu do ní vnikni a nehýbej se, dokud tě sama nepopožene.",
    "Ve stoje v koupelně před zrcadlem: ona se opírá o umyvadlo, ty zezadu, díváte se na sebe.|120",
    "Na podlaze v obýváku na dece nebo koberci – misionář, pomalu a hluboko.|180",
    "Při sexu zezadu jí dej do ruky vibrátor, ať si ho sama drží na klitorisu.|180",
    "Plácej ji dlaní přes zadeček v rytmu přírazů – ne moc silně.|90",
    "Ona leží na zádech na kraji gauče, ty klečíš na zemi. Zvedni jí boky k sobě.|180",
    "Miluj se s ní na boku čelem k sobě, nohy propletené, pusy u sebe.|180",
    "Chyť ji jemně za zápěstí a přidrž jí je nad hlavou na posteli. Pak ji pomalu miluj.|180",
    "Zezadu vestoje u okna se zataženými závěsy – ona se drží parapetu.|120",
    "Pozice „kovadlina“: ona leží na zádech a má nohy u hlavy (jen pokud je to pro ni pohodlné), ty přirážíš shora.|90",
    "Sedni si na kraj postele, ona si sedne na tvůj klín čelem k tobě a obejme tě nohama.|180",
    "Spoutej ji pouty k čelu postele (nebo ruce nad hlavou) a miluj se s ní v misionáři. Pomalu.|180",
    "Vyzkoušejte polohu, kterou jste ještě nikdy nedělali. Ty vybíráš.|180",
    "Miluj se s ní a každé 3 přírazy jí polib bradavku.|120",
    "Zezadu na kuchyňské lince – ona se opírá lokty o linku, ty ji hladíš po zádech.|180",
    "Ona na tobě na gauči, zády k tobě, opřená rukama o tvoje kolena.|180",
    "Při sexu jí šeptej do ucha přesně, co s ní děláš a jak se ti to líbí.|120",
    "Oba vibrátory: jeden na její klitoris, druhý přiložený na tvé tělo u kořene, ať vibrace cítí oba.|180",
    "Rozkaž jí, ať se otočí a předkloní. Pak ji odměň pomalými přírazy zezadu.|120",
    "Misionář, nohy jí dej k sobě a přes ně si obkroč – bude to těsnější.|120",
    "Miluj se s ní na jídelní židli: ty sedíš, ona na tobě obkročmo a opírá se o stůl za sebou.|180",
    "Mezi přírazy z ní vyjdi a olízni ji, pak zase do ní. Třikrát dokola.",
    "Lehni si na ni zezadu, když leží na břiše, a propleť s ní prsty nad hlavou.|180",
    "Zezadu na gauči, ona si mezitím hladí klitoris vibrátorem. Tempo řídíš ty.|180",
    "Plácni ji bičíkem lehce po vnitřní straně stehen a hned do ní pomalu vnikni.",
    "Stoupni si a zvedni ji do náruče, ať tě obejme nohama – pár přírazů vestoje, pak ji polož na postel (jen pokud to zvládnete bezpečně).|60",
    "Misionář, ale vždy po 10 přírazech ji polib a řekni jí, co na ní miluješ.|180",
    "Na posteli: ona leží na boku, ty klečíš za ní a držíš její horní nohu nahoře.|180",
    "Hraj si s rytmem: 9 mělkých přírazů, 1 hluboký. Pak 8 a 2. Až k 1 a 9.",
    "Nasaď jí pouta, sedni si na gauč a posaď si ji na klín zády k sobě. Hlaď ji, zatímco se na tobě pohybuje.|180",
    "Ve vaně nebo sprše: ona si sedne na okraj vany, ty klečíš ve vaně před ní.|120",
    "Otoč ji zády k sobě u dveří ložnice, přitiskni ji ke dveřím a vnikni do ní zezadu.|120",
    "Poručíš jí, ať nesmí vydat ani hlásku. Pak ji miluj tak dobře, aby to nevydržela.|120",
    "Ona je nahoře, ale ty ji držíš za boky a určuješ tempo zespodu.|180",
    "Miluj se s ní a po každé minutě se zastav a zeptej se: rychleji, pomaleji, nebo silněji?|240",
    "Misionář s jejíma nohama na tvém hrudníku. Hlaď jí přitom chodidla.|120",
    "Zezadu ve stoje, ona si opírá jednu nohu o židli nebo okraj vany.|120",
    "Ležíš na zádech, ona je nahoře. Drž jí vibrátor mezi vašimi těly přitisknutý ke klitorisu.|180",
    "Chyť ji jemně za krk ze strany (bez tlaku na hrdlo) a za bradu, dívej se na ni a pomalu přirážej.|120",
    "Na kraji jídelního stolu: ona leží na zádech, ty stojíš. Jednou rukou jí hlaď klitoris.|180",
    "Při sexu zezadu jí dej 5 plácnutí bičíkem na zadeček – ona je počítá nahlas.",
    "Lžička na gauči pod dekou. Pomalu, líně, s polibky na krk.|240",
    "Miluj se s ní v poloze, kterou si vybere – a snaž se jí to udělat co nejlíp.|240",
    "Zavaž jí oči a přikaž jí, ať si lehne na záda a roztáhne nohy. Pak ji nech chvíli čekat a pak do ní pomalu vnikni.",
    "Misionář a ty přirážíš jen pánví nahoru, třeš se o její klitoris.|120",
    "Na zemi u gauče: ona klečí a hrudníkem se opírá o sedák, ty jsi zezadu.|180",
    "Poloha „na koníka“ obráceně: ona na tobě zády k tobě, ty jí hladíš zadeček a záda.|180",
    "Při sexu jí jemně chytni vlasy u kořínků a zakloň jí hlavu, pak ji polib na krk.|90",
    "Ona stojí u kuchyňské linky, ty zezadu. Oběma rukama jí hladíš prsa.|120",
    "Zkus to nejpomalejší milování v historii. Každý příraz trvá aspoň 5 vteřin.|180",
    "Spoutej jí ruce pouty za zády a nech ji, ať si na tebe sedne. Ty ji držíš za boky, ať nespadne.|180",
    "Ležíš na ní v misionáři a nehýbeš se, jen se líbáte. Hýbe se jen ona pod tebou.|120",
    "Vyzkoušejte polohu „na nůžky“ – bokem, nohy propletené.|180",
    "Zezadu na posteli, ona leží na břiše, ty vibrátor vsuneš pod ni ke klitorisu.|180",
    "Při každém hlubokém přírazu jí řekni, že je tvoje. Při každém mělkém, že je krásná.|120",
    "Rozkaž jí, ať si sedne na kraj stolu a roztáhne nohy. Dívej se na ni 10 vteřin a pak ji miluj.|180",
    "Misionář, ale nohy má zvednuté a roztažené, ty je držíš za kotníky.|120",
    "Ve stoje v chodbě: ona se opírá o zeď rukama, ty zezadu, jednou rukou ji hladíš mezi nohama.|120",
    "Miluj se s ní a řekni jí, ať ti řekne, až bude blízko. Pak zrychli.",
    "Posaď se na gauč, ona si klekne na gauč obkročmo nad tebe a pomalu si na tebe sedá.|180",
    "Při sexu v misionáři jí vezmi zápěstí a přidrž je u polštáře. Pak zpomal.|120",
    "Plácni ji dvakrát po zadečku dlaní, pak jí ho pohlaď a polib. A pak do ní zezadu.",
    "Miluj se s ní na pračce – ona sedí, ty stojíš.|120",
    "Vezmi ji na posteli do „lotosu“: ty sedíš s nohama zkříženýma, ona na tobě obkročmo, pomalé houpání.|180",
    "Zezadu na posteli, ona klečí a ty jí zároveň vibrátorem hladíš klitoris zespodu.|180",
    "Při sexu ji otoč do tří různých poloh, ale zůstaň v ní při přechodu.",
    "Misionář, hluboce, a každých 20 vteřin jí olízni bradavku.|180",
    "Nasaď jí pouta k čelu postele, zavaž jí oči a miluj se s ní. Ona neví, kdy přijde další příraz.|180",
    "Opři ji o záda gauče vestoje zezadu. Ona je předkloněná přes opěradlo.|120",
    "Rozkaž jí, ať tě prosí o každý příraz. Když poprosí, splň to.|120",
    "Ona leží na zádech na gauči s jednou nohou na opěradle, ty mezi jejíma nohama.|180",
    "Ať si lehne na posteli na břicho, spoj jí nohy k sobě a lehni si obkročmo na ni zezadu.|180",
    "Při sexu jí dělej malá kolečka palcem na klitorisu. Nepřestávej, dokud nedojde.",
    "Ve sprše: ona stojí zády k tobě a má nohu na okraji vany. Voda teče na vás oba.|120",
    "Postav se s ní před zrcadlo, ať se opírá rukama o komodu, a vnikni do ní zezadu. Dívej se jí do očí v odrazu.|120",
    "Zatímco ji miluješ v misionáři, přikaž jí, ať si sama hladí prsa a nepřestává.|180",
    "Dej jí lehce bičíkem přes stehna, když na tobě jezdí – pokaždé, když zpomalí.|120",
    "Miluj se s ní v poloze „na lžičku“, ale ona leží na břiše a ty na boku za ní.|180",
    "Nech ji ležet na kraji postele s nohama na zemi, zvedni jí boky a miluj se s ní vkleče.|180",
    "Zakaž jí dotýkat se tebe rukama. Když tě chytí, zpomal na minimum.|180",
    "Nech ji, ať si vybere místo v bytě, kde jste to ještě nedělali. Tam ji miluj.",
    "Na konci karty jí dopřej orgasmus – jakkoli, ale ona musí dojít první.",
  ],

  // Úkoly pro ženu – pro potěšení muže
  female: [
    "Posaď se na kuchyňskou linku, přitáhni si ho nohama k sobě a nech ho do sebe vniknout. Líbejte se přitom.|180",
    "Sedni si na něj na posteli a jezdi na něm pomalu a hluboko. Dívej se mu do očí.|180",
    "Klekni si na gauč, opři se o opěradlo a přirážej zadečkem proti němu. Tempo určuješ ty.|180",
    "Při sexu mu drž vibrátor na varlatech.|180",
    "Lžička na boku v posteli. Pomalu proti němu přirážej zadečkem a jeho ruku si dej na prsa.|240",
    "Opři se o zeď v chodbě, zvedni nohu a obejmi ho s ní. Miluj se s ním vestoje.|120",
    "Nasaď mu pouta s rukama nad hlavou a jezdi na něm. Dotknout se tě nesmí.|180",
    "Posaď ho na židli bez opěrek a sedni si na něj čelem k němu.|180",
    "Sedni si na něj a jen špičku do sebe pomalu pusť a zase vyjeď. Desetkrát. Pak se na něj posaď celá.",
    "Lehni si na kraj postele a dej si nohy na jeho ramena. Ruce mu dej na zadek a přitahuj si ho.|180",
    "Opři se předkloněná o kuchyňský stůl a nech ho zezadu. Otoč se a řekni mu, ať zrychlí.|180",
    "Plácni ho bičíkem lehce přes zadek třikrát a pak se na něj posaď.",
    "Jezdi na něm a zastav se úplně vždy, když se blíží vrchol. Nech ho chvilku čekat.|240",
    "Ve sprše: opři se rukama o stěnu a vystrč na něj zadeček. Pozor, ať neuklouznete.|120",
    "Sedni si na něj a nehýbej se nahoru a dolů – jen pomalu kroužkuj boky.|120",
    "Jezdi na něm a přitom mu vibrátorem hlaď bradavky.|180",
    "Zavaž mu oči a miluj se s ním v jakékoli poloze. Každou minutu změň tempo.|240",
    "Sedni si na pračku, roztáhni nohy a přitáhni si ho.|120",
    "Nasaď mu pouta s rukama za zády, posaď ho na gauč a sedni si na něj.|180",
    "Lehni si na záda, kolena si přitáhni k prsům a nech ho přirážet hluboko.|120",
    "Na gauči: lehni si na bok a dej mu horní nohu na rameno.|180",
    "Polohový maraton: každých 30 vteřin mu řekni novou polohu a on ji musí hned zaujmout.|180",
    "Miluj se s ním před zrcadlem tak, aby se na vás mohl dívat.|180",
    "Jezdi na něm s hlubokými pomalými pohyby a dole vždy chvíli zůstaň a stáhni svaly pánevního dna.|120",
    "Lehni si na břicho s polštářem pod boky a nech ho ležet na sobě. Přirážej proti němu zadečkem.|180",
    "Při sexu mu jemně stiskni bradavky a řekni mu, jak skvěle se v tobě cítí.|120",
    "Chyť ho za zápěstí a přidrž mu je nad hlavou, zatímco na něm jezdíš.|180",
    "Lehni si na jídelní stůl na záda, nohy mu dej na ramena a nech ho stát.|180",
    "Posaď ho do křesla a sedni si na něj zády k němu. Jeho ruce si dej na prsa.|180",
    "Jezdi na něm a on smí dojít jen tehdy, až mu to dovolíš. Pak mu to dovol.",
    "Jezdi na něm půl minuty jako o život, pak půl minuty skoro bez pohybu. Opakuj.|180",
    "Misionář – obtoč mu nohy kolem pasu a přitahuj si ho patami k sobě.|180",
    "Klekni si na posteli na všechny čtyři a nech ho zezadu. Otáčej se na něj přes rameno.|120",
    "Poručte si navzájem: ty mu řekneš polohu, on tempo. Plňte to přesně.|180",
    "Posaď se na něj celá a nehýbej se, dokud tě sám nezačne prosit.",
    "V koupelně se opři o umyvadlo, on zezadu, a dívej se na něj do zrcadla.|120",
    "Na podlaze v obýváku na dece nebo koberci – jezdi na něm.|180",
    "Při sexu zezadu si sama přikládej vibrátor na klitoris, ať cítí vibrace i on.|180",
    "Plácej ho dlaní přes zadek v rytmu, jakým chceš, aby přirážel.|90",
    "Posaď ho na kraj gauče a klekni si nad něj. Pomalu si na něj sedej.|180",
    "Miluj se s ním na boku čelem k sobě, nohy propletené, pusy u sebe.|180",
    "Obkroč ho, drž mu ruce u polštáře a pomalu na něm jezdi.|180",
    "Opři se u okna se zataženými závěsy o parapet a nech ho zezadu.|120",
    "Lehni si na záda a zvedni nohy vysoko – nech ho, ať ti je drží za kotníky.|90",
    "Sedni si mu na klín na kraji postele čelem k němu a obejmi ho nohama.|180",
    "Spoutej mu ruce pouty (třeba k čelu postele nebo za zády) a pomalu na něm jezdi. Líbat tě smí, ale jen když se nakloníš ty.|180",
    "Vymysli polohu, kterou jste spolu ještě nezkusili, a naveď ho do ní.|180",
    "Jezdi na něm a každé 3 pohyby mu dej své prsy k ústům.|120",
    "Opři se lokty o kuchyňskou linku a vystrč na něj zadeček. Ať tě hladí po zádech.|180",
    "Sedni si na něj na gauči zády k němu a opři se rukama o jeho kolena.|180",
    "Při sexu mu šeptej do ucha přesně, co ti dělá a jak se ti to líbí.|120",
    "Oba vibrátory: jeden na jeho varlata, druhý na tvůj klitoris.|180",
    "Rozkaž mu, ať si lehne na záda a nehýbe se. Pak ho odměň pomalou jízdou.|120",
    "Lehni si na záda a dej nohy k sobě – bude to pro něj těsnější.|120",
    "Posaď ho na jídelní židli a sedni si na něj obkročmo, opřená o stůl za sebou.|180",
    "Mezi pohyby z něj slez a olízni ho, pak si na něj zase sedni. Třikrát dokola.",
    "Lehni si na břicho a nech ho, ať si na tebe lehne a propletete prsty nad hlavou.|180",
    "Klekni si na gauč, on zezadu, a mezitím mu sahej rukou mezi nohy na varlata.|180",
    "Plácni ho bičíkem lehce po stehnech a hned si na něj sedni.",
    "Obejmi ho nohama kolem pasu, když stojí, a nech ho, ať tě chvíli drží (jen pokud to zvládnete bezpečně). Pak si lehni na postel a stáhni ho na sebe.|60",
    "Jezdi na něm a vždy po 10 pohybech ho polib a řekni mu, co na něm miluješ.|180",
    "Na posteli: lehni si na bok a nech ho klečet za tebou. Horní nohu mu dej do ruky.|180",
    "Hraj si s rytmem: 9 mělkých pohybů, 1 hluboký. Pak 8 a 2. Až k 1 a 9.",
    "Nasaď mu pouta, posaď ho na gauč a sedni si na něj zády k němu. Pohybuj se, jak chceš ty.|180",
    "Ve vaně nebo sprše: posaď ho na okraj vany a sedni si na něj.|120",
    "Opři se o dveře ložnice zády k němu a vystrč zadeček.|120",
    "Poruč mu, že nesmí vydat ani hlásku. Pak na něm jezdi tak dobře, aby to nevydržel.|120",
    "Jsi nahoře, ale nech ho, ať tě drží za boky a určuje tempo zespodu.|180",
    "Miluj se s ním a po každé minutě se zastav a zeptej se: rychleji, pomaleji, nebo silněji?|240",
    "Lehni si na záda a nohy mu dej na hruď. Chodidly ho hlaď po bradavkách.|120",
    "Zezadu ve stoje: opři si jednu nohu o židli nebo okraj vany a přitáhni si ho.|120",
    "Jezdi na něm a sama si přitom přikládej vibrátor na klitoris. Ať se dívá.|180",
    "Při jízdě mu dej ruce kolem krku (bez tlaku), dívej se mu do očí a pomalu se pohybuj.|120",
    "Lehni si na kraj jídelního stolu na záda a nech ho stát. Jednou rukou mu hlaď varlata.|180",
    "Když je v tobě zezadu, dej mu do ruky bičík a nech ho, ať ti dá 5 lehkých plácnutí. Počítej nahlas.",
    "Lžička na gauči pod dekou. Pomalu, líně, zadečkem proti němu.|240",
    "Miluj se s ním v poloze, kterou si vybere – a snaž se mu to udělat co nejlíp.|240",
    "Zavaž mu oči a přikaž mu, ať si lehne na záda. Nech ho chvíli čekat, a pak si na něj pomalu sedni.",
    "Jezdi na něm a otírej se klitorisem o jeho pánev – pomalými krouživými pohyby.|120",
    "Klekni si na zem u gauče a hrudníkem se opři o sedák. Nech ho zezadu.|180",
    "Sedni si na něj zády k němu a nakloň se dopředu, ať vidí všechno.|180",
    "Při sexu ho chytni za vlasy a přitáhni si jeho pusu ke krku.|90",
    "Stoupni si k lince, vystrč zadeček a jeho ruce si dej na prsa.|120",
    "Zkus to nejpomalejší milování v historii. Každý pohyb trvá aspoň 5 vteřin.|180",
    "Spoutej mu ruce pouty za zády, posaď ho na kraj postele a sedni si na něj.|180",
    "Lehni si pod něj a nehýbej se, jen se líbejte. Hýbe se jen on.|120",
    "Lehni si na bok, propleť s ním nohy do „nůžek“ a přirážej proti němu.|180",
    "Lehni si na břicho a vibrátor si dej pod sebe ke klitorisu. On zezadu – ať cítí vibrace.|180",
    "Při každém hlubokém pohybu mu řekni, že je tvůj. Při každém mělkém, že je úžasný.|120",
    "Rozkaž mu, ať si sedne na židli a nehne se. Tanči před ním 10 vteřin a pak si na něj sedni.|180",
    "Lehni si na záda, zvedni nohy a roztáhni je. Nech ho, ať tě drží za kotníky.|120",
    "Opři se rukama o zeď v chodbě a nech ho zezadu. Jeho ruku si dej mezi nohy.|120",
    "Jezdi na něm a řekni mu, ať ti řekne, až bude blízko. Pak zpomal – a pak zrychli.",
    "Posaď ho na gauč, klekni si obkročmo nad něj a pomalu si na něj sedej.|180",
    "Chyť ho při misionáři za zadek a přitahuj si ho do sebe tak, jak to chceš ty.|120",
    "Plácni ho dvakrát po zadku dlaní, pak ho pohlaď a polib. A pak se mu nastav zezadu.",
    "Sedni si na pračku a nech ho stát mezi tvými nohama.|120",
    "Posaď ho do „lotosu“ – sedí s nohama zkříženýma a ty na něm obkročmo. Pomalé houpání.|180",
    "Klekni si na posteli, on zezadu, a jednou rukou mu zespodu mezi nohama hlaď varlata.|180",
    "Při sexu se otoč do tří různých poloh, ale nenech ho z tebe vyklouznout.",
    "Jezdi na něm hluboce a každých 20 vteřin mu olízni bradavku.|180",
    "Nasaď mu pouta, zavaž mu oči a jezdi na něm. Neví, kdy přijde další pohyb.|180",
    "Opři se o opěradlo gauče předkloněná a nech ho vestoje zezadu.|120",
    "Rozkaž mu, ať tě prosí o každý pohyb. Když poprosí, splň to.|120",
    "Lehni si na gauč na záda, jednu nohu dej na opěradlo a přitáhni si ho mezi nohy.|180",
    "Lehni si na posteli na břicho, dej nohy k sobě a nech ho, ať si na tebe lehne obkročmo.|180",
    "Při sexu mu masíruj hráz prsty. Nepřestávej.|180",
    "Ve sprše: stoupni si zády k němu, nohu dej na okraj vany a přitáhni si ho.|120",
    "Opři se rukama o komodu před zrcadlem a nech ho zezadu. Dívej se mu do očí v odrazu.|120",
    "Zatímco na něm jezdíš, přikaž mu, ať ti hladí prsa a nepřestává.|180",
    "Dej mu lehce bičíkem přes stehna pokaždé, když zpomalí.|120",
    "Lehni si na břicho a nech ho ležet na boku za tebou.|180",
    "Posaď ho na kraj postele s nohama na zemi a sedni si na něj čelem k němu.|180",
    "Zakaž mu dotýkat se tě rukama. Když tě chytí, zpomal na minimum.|180",
    "Vyber místo v bytě, kde jste to ještě nedělali. Tam se s ním miluj.",
    "Na konci karty mu dopřej orgasmus – jakkoli chceš, ale ty určuješ jak.",
  ],
});
