// Kategorie 4 – Sex a polohy (dávka d)
// Témata: v sedě, ve stoje, na kraji postele, zvednutá, přechody mezi polohami.
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 4,

  male: [
    "Pohyb dělá ona: Posaď si ji obkročmo na klín a sám se vůbec nehýbej. Cíl: čtyři minuty, při kterých všechnu práci dělá ona.|240|zidle_celem",
    "Na židli čelem: Ona ti sedí obkročmo a drží se opěradla. Ty jí držíš boky. Cíl: nechat ji, ať určí tempo.|300|zidle_celem",
    "Objatá přes prsa: Nech ji sednout si na tebe zády a drž ji celou dobu přes prsa. Cíl: čtyři minuty a ani jednou ji nepustit.|240|klin_zady",
    "Na židli zády: Posaď si ji na klín zády k sobě a rukou jí zepředu dráždi klitoris. Cíl: pět minut a ruku ani jednou nesundat.|300|klin_zady",
    "Objetí bez pohybu: Posaď si ji na klín a jen se objímejte, zatímco v ní jsi. Cíl: dvě minuty úplného klidu, teprve pak se začni hýbat.|240|klin_celem",
    "Lotos na podlaze: Sedněte si na podlahu proti sobě, ona na tobě, nohy propletené. Cíl: čtyři minuty a hýbat se jen boky.|240|lotos",
    "Lotos vsedě: Sedíte proti sobě, nohy propletené, ona na tobě. Hýbat se dá jen boky. Cíl: vydržet pět minut.|300|lotos",
    "Kraj postele a ty ve stoje: Posaď ji na kraj postele, postav se před ni a přitáhni si ji za boky. Cíl: čtyři minuty a najít správnou výšku.|240|kraj_postele",
    "Stehna v dlaních: Ona leží na kraji postele, ty jí zvedneš nohy a držíš ji za stehna. Cíl: čtyři minuty a ani jednou ji nepustit.|240|kraj_postele",
    "Kraj postele: Ona leží na kraji, ty stojíš. Výška je přesně tak akorát. Cíl: najít správnou výšku.|240|kraj_postele",
    "Přitáhne si tě nohama: Nech ji sednout na kraj postele a přitahovat si tě nohama k sobě. Cíl: čtyři minuty, při kterých tempo určuje jen ona.|240|kraj_postele",
    "Nohy na ramenou na kraji: Polož si její nohy na ramena a nakloň se k ní. Cíl: čtyři minuty a u každé minuty se zeptat, jestli to není moc.|240|kraj_postele",
    "Jedna noha u zdi: Postav ji ke zdi, zvedni jí jednu nohu a miluj se s ní vestoje. Cíl: čtyři minuty a nohu ani jednou nespustit.|240|zed",
    "Zápěstí na zdi: Přitiskni ji ke zdi a drž jí obě zápěstí nad hlavou. Cíl: čtyři minuty a na stop ji hned pustit.|240|zed",
    "U zdi a pomalu: Ona je opřená o zeď, ty proti ní. Nesmíš zrychlit ani jednou. Cíl: vydržet pomalé tempo ve stoje.|240|zed",
    "Čelem ke zdi: Postav ji čelem ke zdi, ať se opře dlaněmi, a vnikni do ní zezadu. Cíl: čtyři minuty a nesmí ruce sundat.|240|zed",
    "Obě dlaně na zdi: Nech ji opřít se oběma dlaněmi o zeď a miluj ji zezadu. Cíl: čtyři minuty a nesmí ruce ze zdi sundat.|240|zed",
    "Přes opěradlo gauče: Předkloň ji přes opěradlo gauče a vnikni do ní zezadu. Cíl: čtyři minuty a držet ji celou dobu za boky.|240|predklon",
    "Ruce za zády přes opěradlo: Předkloň ji přes opěradlo a drž jí obě ruce za zády. Cíl: čtyři minuty a na stop ji hned pustit.|240|predklon",
    "Přes opěradlo: Ona se drží opěradla, ty stojíš za ní. Můžeš jít hodně naplno. Cíl: najít společný rytmus.|240|predklon",
    "Ruce na kolenou: Nech ji předklonit se a opřít si ruce o kolena a miluj ji zezadu. Cíl: čtyři minuty a nesmí se narovnat.|240|predklon_stoje",
    "Předkloněná ve stoje: Ona stojí předkloněná, ty ji držíš za boky a přirážíš. Cíl: čtyři minuty a udržet oba na nohou.|240|predklon_stoje",
    "V náručí: Zvedni ji do náruče a nech ji, ať se tě drží nohama kolem pasu. Cíl: udržet ji aspoň tři minuty.|180|zvednuta",
    "V náručí: Drž ji nahoře tak dlouho, jak zvládneš, a pak ji polož ke zdi. Cíl: dojít až ke zdi.|180|zvednuta",
    "Opora o zeď: Zvedni ji a opři ji zády o zeď, ať máš oporu. Cíl: čtyři minuty a ani jednou ji nepoložit na zem.|240|zed",
    "Na kraji linky: Posaď si ji na kraj stolu nebo linky a přitáhni si ji za boky. Cíl: čtyři minuty a najít správnou výšku.|240|kraj_postele",
    "Na kraji postele čelem: Sedni si na kraj postele a nech ji sednout si na tebe čelem. Cíl: čtyři minuty a držet se navzájem za ramena.|240|klin_celem",
    "Zvedáš ji pod zadečkem: Vsedě na kraji postele ji drž pod zadečkem a sám ji zvedej. Cíl: čtyři minuty, při kterých se ona nenamáhá.|240|klin_celem",
    "Opřený o čelo postele: Sedni si opřený o čelo postele a nech ji sednout si na tebe. Cíl: čtyři minuty a hýbe se jen ona.|240|ona_nahore",
    "Vsedě opřený: Sedíš opřený, ona na tobě čelem. Můžete se u toho líbat celou dobu. Cíl: nepřerušit polibek.|300|klin_celem",
    "Nejdřív se svlékne: Sedni si na židli a nech ji, ať se před tebou nejdřív pomalu svlékne. Cíl: nesáhnout na ni, dokud nebude úplně nahá.|300|zidle_celem",
    "Ruce za zády na židli: Ona ti sedí obkročmo na židli a ty jí držíš ruce za zády. Cíl: čtyři minuty a na stop ji hned pustit.|240|zidle_celem",
    "Nohy mezi tvýma: Nech ji sednout si na tebe zády s nohama mezi tvýma. Cíl: čtyři minuty a držet ji celou dobu za boky.|240|klin_zady",
    "Tempo určuješ ty: Ona ti sedí na židli zády, ty ji držíš za boky a určuješ tempo. Cíl: čtyři minuty a ani jednou jí tempo nepřenechat.|240|klin_zady",
    "Klečí na židli: Nech ji kleknout na židli čelem k opěradlu a miluj ji zezadu. Cíl: čtyři minuty a nesmí se pustit opěradla.|240|zidle_celem",
    "Opřený o postel: Sedni si na podlahu opřený zády o postel a nech ji sednout si na tebe. Cíl: čtyři minuty a hýbat se jen boky.|240|lotos",
    "Na podlaze: Sedíte na koberci, ona na tobě, oba opření o ruce. Cíl: udržet rovnováhu.|240|lotos",
    "Pověšená na krku: Postav se a nech ji, ať se ti pověsí na krk a obtočí tě nohama. Cíl: udržet ji aspoň tři minuty.|180|zvednuta",
    "Zvedni ji a posaď si ji na kraj postele, aniž bys z ní vyšel.|240|kraj_postele",
    "Klečíš před ní: Nech ji sednout na kraj postele a klekni si před ni na podlahu. Cíl: čtyři minuty a ani jednou se nezvednout.|240|kraj_postele",
    "Na kraji postele jí dej nohy kolem svého pasu.|240|kraj_postele",
    "Ať leží na kraji a ty ji držíš za kotníky roztažené.|240|kraj_postele",
    "Tři výšky: Vystřídáte polohu vleže, vsedě a ve stoje, každou dvě minuty. Cíl: projít všechny tři.|300|kraj_postele",
    "Začni ve stoje u zdi a skonči vsedě na židli. Bez přerušení.|300|zed",
    "Začni na židli a přejdi do stoje s ní v náručí.|300|zvednuta",
    "Přechod bez vyklouznutí: Začněte na lžičku a přejděte do misionáře, aniž bys z ní vyšel. Cíl: tři takové přechody za pět minut.|300|lzicka",
    "Přechod bez vyjití: Vystřídejte tři polohy a ani jednou z ní nevyjdeš. Cíl: tři plynulé přechody.|300|zezadu",
    "Opřená o kraj postele: Nech ji stát opřenou o kraj postele a miluj ji zezadu. Cíl: čtyři minuty a nesmí se narovnat.|240|predklon",
    "Postav ji před zrcadlo a vnikni do ní zezadu, ať se dívá.|240|zed",
    "Bok a noha: U zdi ji jednou rukou drž za bok a druhou jí drž nohu nahoře. Cíl: čtyři minuty a ani jednu ruku nesundat.|240|zed",
    "Drží se zárubně: Nech ji držet se zárubně dveří a miluj ji zezadu. Cíl: čtyři minuty a nesmí se pustit ani jednou.|240|predklon_stoje",
    "Ve stoje a potichu: Miluj se s ní vestoje u zdi a ani jeden z vás nesmí vydat hlásku. Cíl: čtyři minuty úplného ticha.|240|zed",
    "Posaď si ji na klín na podlaze a obejmi ji oběma rukama.|240|klin_podlaha",
    "Sedni si za ni a nech ji sedět mezi tvýma nohama zády.|240|klin_podlaha",
    "Na klíně zády: Ona ti sedí na klíně zády a ty jí sáhneš dopředu. Cíl: nepřestat ji dráždit ani na chvíli.|300|klin_zady",
    "Sedni si na kraj postele a nech ji stát mezi tvýma nohama.|180|oral_vsede",
    "Zvedni ji a drž ji na sobě, dokud vydržíš. Pak sedni.|180|zvednuta",
    "Nohy kolem opěradla: Nech ji sednout si na tebe na židli a dát si nohy kolem opěradla. Cíl: čtyři minuty a nohy ani jednou nespustit.|240|zidle_celem",
    "Sedni si a nech ji, ať se na tobě houpe jen dopředu a dozadu.|240|klin_celem",
    "Vsedě čelem a pomalu, ať se můžete celou dobu dívat do očí.|300|klin_celem",
    "Oči v očích vsedě: Sedíte čelem k sobě a nesmíte uhnout pohledem. Cíl: vydržet až do konce.|300|klin_celem",
    "Předkloněná přes postel: Nech ji předklonit se přes postel a miluj ji zezadu ve stoje. Cíl: čtyři minuty a držet ji za boky.|240|predklon",
    "Přes postel jí polož ruku mezi lopatky a přitlač.|240|predklon",
    "Ať stojí předkloněná a ty jí držíš obě zápěstí vzadu.|240|predklon_stoje",
    "Rameno u zdi: Postav ji ke zdi zády k sobě a jednou rukou jí drž rameno. Cíl: čtyři minuty a ani jednou ji nepustit.|240|zed",
    "Noha na posteli: Ona stojí, ty jí zvedneš nohu na kraj postele a miluješ se s ní. Cíl: čtyři minuty a nohu nespustit.|240|zed",
    "Jedna noha nahoře: Ona stojí, jednu nohu má opřenou vysoko. Ty držíš její koleno. Cíl: vydržet tak dvě minuty.|240|zed",
    "Sedni si na židli a nech ji, ať si na tebe sedne zády a opře se dozadu.|240|klin_zady",
    "Sedni si a nech ji, ať se pomalu otáčí, zatímco na tobě sedí.|300|ona_nahore",
    "Hýbeš se jen ty: Posaď si ji na klín a všechen pohyb dělej sám. Cíl: čtyři minuty, při kterých se ona vůbec nepohne.|240|klin_celem",
    "Zvedáš ji ty: Ona ti sedí na klíně a drží se tvých ramen, ty ji zvedáš. Cíl: čtyři minuty a ani jednou ji nepoložit.|240|klin_celem",
    "Po centimetrech: Sedni si a nech ji, ať si na tebe sedá úplně pomalu, po centimetrech. Cíl: sestup musí trvat aspoň minutu.|180|klin_celem",
    "Pomalé usednutí: Ona si na tebe sedá celou minutu. Ani o vteřinu dřív. Cíl: vydržet celou minutu.|60|klin_celem",
    "V náručí ve stoje: Drž ji kolem pasu a ať se drží tvého krku. Cíl: udržet ji aspoň tři minuty a nepoložit.|180|zvednuta",
    "Ona výš než ty: Postav ji na kraj postele, aby byla výš než ty, a miluj se s ní. Cíl: čtyři minuty a držet ji, ať neztratí rovnováhu.|240|kraj_postele",
    "Ať si sedne na okraj a ty ji držíš za ruce a přitahuješ.|240|kraj_postele",
    "Na kraji postele si ji přitáhni za kolena úplně k sobě.|240|kraj_postele",
    "Napříč postelí: Nech ji ležet napříč postelí a postav se z boku. Cíl: čtyři minuty a najít úhel, který sedne oběma.|240|kraj_postele",
    "Ze stoje do lehu: Začni ve stoje a postupně skončete vleže, aniž byste přerušili. Cíl: plynulý přechod.|300|zed",
    "Sedni si a nech ji rozhodnout, jestli bude čelem, nebo zády.|240|klin_celem",
    "Na židli a ty stojíš: Nech ji kleknout na židli a opřít se o opěradlo, ty stojíš za ní. Cíl: čtyři minuty a nesmí se pustit.|240|zidle_celem",
    "Konec na klíně: Posaď si ji nakonec na klín a jen ji drž, bez pohybu. Cíl: dvě minuty klidu a ani slovo.|120|klin_celem",
  ],

  female: [
    "Nech ho sednout si na židli a sedni si mu obkročmo na klín. Pohyb děláš ty.|240|zidle_celem",
    "Na židli čelem: Sedíš mu obkročmo a držíš se opěradla. On tě drží za boky. Cíl: určovat tempo sama.|300|zidle_celem",
    "Nech ho sednout si a sedni si mu na klín zády. Ať tě drží přes prsa.|240|klin_zady",
    "Na židli zády k němu a nech si sahat dopředu.|300|klin_zady",
    "Sedni si mu na klín a jen se objímejte, zatímco je v tobě.|240|klin_celem",
    "Nech ho sednout si na podlahu a sedni si na něj. Nohy propleťte.|240|lotos",
    "Lotos vsedě: Sedíte proti sobě, nohy propletené, ty na něm. Hýbat se dá jen boky. Cíl: vydržet pět minut.|300|lotos",
    "Sedni si na kraj postele a nech ho stát před tebou.|240|kraj_postele!",
    "Na kraji postele si nech zvednout nohy a držet za stehna.|240|kraj_postele!",
    "Kraj postele: Ležíš na kraji, on stojí. Výška je přesně tak akorát. Cíl: najít správnou výšku.|240|kraj_postele",
    "Sedni si na kraj postele a přitáhni si ho nohama.|240|kraj_postele",
    "Na kraji postele si polož nohy na jeho ramena a nech ho naklonit se.|240|kraj_postele!",
    "Noha nahoru u zdi: Opři se o zeď, zvedni jednu nohu a obtoč mu ji kolem boku. Cíl: čtyři minuty a nohu ani jednou nespustit.|240|zed",
    "Zápěstí nad hlavou u zdi: Nech se přitisknout ke zdi a držet za obě zápěstí nad hlavou. Cíl: čtyři minuty a na stop tě musí pustit.|240|zed",
    "U zdi a pomalu: Jsi opřená o zeď, on proti tobě. Nesmí zrychlit ani jednou. Cíl: vydržet pomalé tempo ve stoje.|240|zed",
    "Postav se čelem ke zdi a nech ho vniknout zezadu.|240|zed",
    "Dlaně na zdi: Opři se oběma dlaněmi o zeď a nech se milovat zezadu. Cíl: čtyři minuty a ruce ze zdi nesundat.|240|zed",
    "Předkloň se přes opěradlo gauče a nech ho jít zezadu.|240|predklon",
    "Ruce za zády přes opěradlo: Předkloň se přes opěradlo a nech si držet obě ruce za zády. Cíl: čtyři minuty a na stop tě musí pustit.|240|predklon!",
    "Přes opěradlo: Držíš se opěradla, on stojí za tebou. Může jít hodně naplno. Cíl: najít společný rytmus.|240|predklon!",
    "Ruce o kolena: Předkloň se, opři si ruce o kolena a nech se milovat zezadu. Cíl: čtyři minuty a ani jednou se nenarovnat.|240|predklon_stoje",
    "Předkloněná ve stoje a nech se držet za boky.|240|predklon_stoje",
    "Nech se zvednout do náruče a drž se ho nohama.|180|zvednuta",
    "V náručí: Ať tě drží nahoře tak dlouho, jak zvládne, a pak tě opře o zeď. Cíl: dojít až ke zdi.|180|zvednuta",
    "Nech se zvednout a opřít zády o zeď, ať má oporu.|240|zed",
    "Sedni si na kraj stolu nebo linky a nech se přitáhnout za boky.|240|kraj_postele",
    "Nech ho sednout si na kraj postele a sedni si na něj čelem.|240|klin_celem",
    "Vsedě na kraji postele se nech držet pod zadečkem a zvedat.|240|klin_celem",
    "Nech ho opřít se o čelo postele a sedni si na něj.|240|ona_nahore",
    "Vsedě opřený: Sedí opřený, ty na něm čelem. Můžete se u toho líbat celou dobu. Cíl: nepřerušit polibek.|300|klin_celem",
    "Nech ho sednout si na židli a před ním se nejdřív svlékni.|300|zidle_celem",
    "Na židli si nech držet ruce za zády, zatímco na něm sedíš.|240|zidle_celem",
    "Nohy mezi jeho: Sedni si mu zády na klín a dej si nohy mezi jeho. Cíl: čtyři minuty a tempo určuješ jen ty.|240|klin_zady",
    "Na židli zády k němu si nech držet boky a určovat tempo.|240|klin_zady",
    "Klekni si na židli čelem k opěradlu a nech ho jít zezadu.|240|zidle_celem",
    "Nech ho sednout si na podlahu opřeného o postel a sedni si na něj.|240|lotos",
    "Na podlaze: Sedíte na koberci, ty na něm, oba opření o ruce. Cíl: udržet rovnováhu.|240|lotos",
    "Pověšená na krku: Pověs se mu na krk, obtoč ho nohama a nech se zvednout. Cíl: vydržet nahoře aspoň tři minuty.|180|zvednuta",
    "Nech se zvednout a posadit na kraj postele, aniž by z tebe vyšel.|240|kraj_postele",
    "Sedni si na kraj a nech ho kleknout si na podlahu před tebe.|240|kraj_postele",
    "Na kraji postele si dej nohy kolem jeho pasu.|240|kraj_postele!",
    "Lež na kraji a nech si držet kotníky roztažené.|240|kraj_postele",
    "Od podlahy nahoru: Dvě minuty vleže, dvě vsedě a dvě ve stoje. Cíl: projít všechny tři výšky.|300|kraj_postele!",
    "Začněte ve stoje u zdi a skončete vsedě na židli. Bez přerušení.|300|zed",
    "Začněte na židli a přejděte do stoje, ať tě nese v náručí.|300|zvednuta",
    "Přechod bez přerušení: Začněte na lžičku a přejděte do misionáře, aniž by z tebe vyšel. Cíl: tři takové přechody za pět minut.|300|lzicka",
    "Přechod bez vyjití: Vystřídejte tři polohy a ani jednou z tebe nevyjde. Cíl: tři plynulé přechody.|300|zezadu",
    "Opřená o kraj: Postav se opřená o kraj postele a nech se milovat zezadu. Cíl: čtyři minuty a ani jednou se nenarovnat.|240|predklon",
    "Postav se před zrcadlo a nech ho vniknout zezadu, ať se díváš.|240|zed",
    "Bok a noha v jeho rukou: U zdi si nech držet jednou rukou bok a druhou zvednutou nohu. Cíl: čtyři minuty a nohu nespustit.|240|zed",
    "Zárubeň v rukou: Chyť se zárubně dveří a nech ho milovat tě zezadu. Cíl: čtyři minuty a ani jednou se nepustit.|240|predklon_stoje!",
    "Tiše ve stoje: Miluj se s ním vestoje u zdi a ani jeden z vás nesmí vydat hlásku. Cíl: čtyři minuty úplného ticha.|240|zed",
    "Sedni si mu na klín na podlaze a nech se obejmout oběma rukama.|240|klin_podlaha",
    "Opřená mezi jeho nohama: Sedni si mu mezi nohy zády a opři se mu o hrudník. Cíl: čtyři minuty a ani jednou se nenarovnat.|240|klin_podlaha",
    "Na klíně zády: Sedíš mu na klíně zády a on ti sahá dopředu. Cíl: ať tě nepřestane dráždit ani na chvíli.|300|klin_zady",
    "Nech ho sednout si na kraj postele a postav se mezi jeho nohy.|180|oral_on_vsede",
    "Nech se zvednout a držet na něm, dokud vydrží. Pak si sedněte.|180|zvednuta",
    "Sedni si na něj na židli a nohy si dej kolem opěradla.|240|zidle_celem",
    "Sedni si na něj a houpej se jen dopředu a dozadu.|240|klin_celem",
    "Sedni si na něj čelem a jeďte tak pomalu, abyste si mohli celou dobu koukat do očí.|300|klin_celem",
    "Pohled vsedě: Sedíte čelem k sobě a ani jeden neuhne očima. Cíl: vydržet až do konce.|300|klin_celem",
    "Předkloň se přes postel a nech ho stát za tebou.|240|predklon!",
    "Přes postel si nech položit ruku mezi lopatky a přitlačit.|240|predklon!",
    "Stůj předkloněná a nech si držet obě zápěstí vzadu.|240|predklon_stoje",
    "Postav se ke zdi zády k němu a nech si držet rameno.|240|zed",
    "Noha na kraji postele: Postav se a zvedni si nohu na kraj postele. Cíl: čtyři minuty vestoje a nohu nespustit.|240|zed",
    "Jedna noha nahoře: Stojíš a jednu nohu máš opřenou vysoko. On drží tvoje koleno. Cíl: vydržet tak dvě minuty.|240|zed",
    "Na židli zády a opřená: Sedni si mu na židli zády a opři se mu dozadu o hrudník. Cíl: čtyři minuty a hýbat se jen boky.|240|klin_zady",
    "Otáčení na něm: Sedni si na něj a pomalu se otáčej dokola, aniž by z tebe vyšel. Cíl: dvě celé otočky za pět minut.|300|ona_nahore",
    "Sedni si mu na klín a nech hýbat se jen jeho.|240|klin_celem",
    "Zvedá tě on: Sedni si mu na klín, drž se jeho ramen a nech ho, ať tě zvedá. Cíl: čtyři minuty a sama se nenamáhat.|240|klin_celem",
    "Centimetr po centimetru: Sedej si na něj úplně pomalu, po centimetrech. Cíl: sestup musí trvat aspoň minutu.|180|klin_celem",
    "Pomalé usednutí: Sedáš si na něj celou minutu. Ani o vteřinu dřív. Cíl: vydržet celou minutu.|60|klin_celem",
    "Ve stoje se nech držet kolem pasu a drž se jeho krku.|180|zvednuta",
    "Výš než on: Postav se na kraj postele, ať jsi výš než on, a nech se držet za boky. Cíl: čtyři minuty a udržet rovnováhu.|240|kraj_postele",
    "Sedni si na okraj a nech se držet za ruce a přitahovat.|240|kraj_postele",
    "Na kraji postele si ho přitáhni koleny úplně k sobě.|240|kraj_postele!",
    "Lehni si napříč postelí a nech ho stát z boku.|240|kraj_postele!",
    "Ze stoje do lehu: Začněte ve stoje a postupně skončete vleže, aniž byste přerušili. Cíl: plynulý přechod.|300|zed",
    "Rozhoduješ ty: Sedni si mu na klín a sama rozhodni, jestli čelem, nebo zády. Cíl: čtyři minuty a po dvou minutách se otočit.|240|klin_celem",
    "Klečíš na židli: Klekni si na židli, opři se o opěradlo a nech ho stát za tebou. Cíl: čtyři minuty a nesmíš se pustit.|240|zidle_celem",
    "Na konci si mu sedni na klín a nech se držet.|120|klin_celem",
  ],
});
