// Kategorie 4 – Sex a polohy (dávka e)
// Témata: tempo jako hra, pravidla a zákazy, pomůcky při sexu, orgasmus jako výzva.
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 4,

  male: [
    "Deset a deset: Deset pomalých přírazů, deset rychlých, pořád dokola. Ona počítá nahlas. Cíl: pět celých kol bez jediné chyby.|300|misionar",
    "Podle nádechu: Přirážej do ní jen tehdy, když se nadechne, a při výdechu stůj. Cíl: padesát nádechů a ani jeden nepropásnout.|300|misionar",
    "Jméno znamená stop: Miluj se s ní a pokaždé, když řekne tvoje jméno, se úplně zastav. Cíl: pět minut a ani jednou to nepropásnout.|300|ona_nahore",
    "Tempo tleskáním: Ona ti tleskáním určuje tempo přírazů a ty musíš držet krok. Cíl: pět minut a ani jednou se netrefit vedle.|300|ona_nahore",
    "Stop a start: Přirážej do ní zezadu a na její stop a start se zastav nebo pokračuj na vteřinu přesně. Cíl: pět minut bez jediného zpoždění.|300|zezadu",
    "Dokud nepoprosí: Přirážej co nejpomaleji, jak jen dokážeš. Cíl: nezrychlit, dokud tě sama nahlas nepoprosí.|300|misionar",
    "Pět a jeden: Pět pomalých přírazů a po nich vždycky jeden úplně rychlý. Cíl: dvacet kol a ani jednou pořadí nesplést.|300|zezadu",
    "Stupeň za minutu: Začni do ní přirážet úplně pomalu a každou minutu zrychli o stupeň. Cíl: pět stupňů a ani jednou se nevrátit zpět.|300|misionar",
    "Jen mělce: Pohybuj se výhradně v posledních pár centimetrech a nikdy nejdi hluboko. Cíl: pět minut a ani jeden hluboký příraz.|300|zezadu",
    "Naopak: Přirážej vždycky jen úplně hluboko a nikdy mělce. Cíl: pět minut a hloubku ani jednou neztratit.|300|misionar",
    "Ruce jen na posteli: Miluj se s ní, ale rukama se smíš dotýkat jen postele. Cíl: čtyři minuty a ani jednou na ni nesáhnout.|240|misionar",
    "Bez rukou: Přirážej do ní s rukama opřenýma vedle ní a nesmíš se jí dotknout. Cíl: čtyři minuty a ani jeden dotek.|240|misionar",
    "Oči otevřené: Miluj se s ní vsedě a ani jeden z vás nesmí zavřít oči. Cíl: pět minut – kdo je zavře první, plní přání toho druhého.|300|klin_celem",
    "Rozmluv ji: Přirážej do ní zezadu tak, aby nevydržela mlčet ani hlásku. Cíl: rozmluvit ji do pěti minut.|300|zezadu",
    "Ticho a tma: Zhasněte, milujte se a nikdo z vás nesmí promluvit. Zbude jen dech. Cíl: pět minut a dorozumět se beze slov.|300|misionar",
    "Musí si říkat: Nech ji jezdit na tobě a nahlas říkat, co chce. Jakmile ztichne, přestáváš. Cíl: pět minut a nejvýš tři pauzy.|300|ona_nahore",
    "Komentuješ celou dobu: Miluj ji zezadu a celou dobu nahlas popisuj, co právě děláš. Cíl: pět minut a ani jednou neztichnout.|300|zezadu",
    "Její ruce mimo hru: Miluj se s ní a ona nesmí použít ruce k ničemu, ani se držet. Cíl: pět minut a ani jednou pravidlo neporušit.|300|misionar",
    "Pravidlo pohledu: Nech ji jezdit na tobě a nesmíte přestat koukat do očí. Kdo uhne, mění polohu. Cíl: pět minut v jedné.|300|klin_celem",
    "Nasadí ti ho ona: Nech ji, ať ti sama nasadí erekční kroužek, a pak se s ní miluj. Cíl: pět minut a ani jednou nezrychlit.|300|misionar",
    "S kroužkem a pomalu: Nasaď si erekční kroužek a nech ji na sobě jezdit hodně pomalu. Cíl: pět minut a ani jednou nezrychlit.|300|ona_nahore",
    "Vibrátor mezi vámi: Drž jí vibrátor na klitorisu, zatímco jsi v ní. Cíl: pět minut a ani jednou ho nesundat.|300|misionar",
    "Vibrátor při sexu: Ona si drží vibrátor sama a ty se jen hýbeš. Cíl: nechat to na ní.|300|ona_nahore",
    "Zepředu a zezadu: Přilož jí vibrátor zezadu, zatímco do ní vnikáš zepředu. Cíl: pět minut a obojí ve stejném rytmu.|300|misionar",
    "Kravata nad hlavou: Sváž jí ruce kravatou nad hlavou na uzel, co povolí jedním tahem, a miluj se s ní. Cíl: pět minut a na stop ji rozvázat.|300|pouta_postel",
    "Svázané ruce zezadu: Sváž jí ruce kravatou za zády, uzel volně, a miluj ji zezadu. Cíl: pět minut a na stop ji hned rozvázat.|300|zezadu",
    "S kravatou: Zavaž jí oči kravatou a miluj se s ní. Ona nesmí vědět, co přijde. Cíl: překvapit ji třikrát.|300|misionar",
    "Změna poloh beze slov: Zavaž jí oči a při sexu měň polohy, aniž bys řekl jediné slovo. Cíl: čtyři polohy a vést ji jen rukama.|300|zezadu",
    "Rána po patnáctém: Miluj ji zezadu a po každých patnácti přírazech ji plácni po zadečku. Cíl: pět ran a síla pokaždé stejná.|300|zezadu",
    "Jemně za vlasy: Miluj ji zezadu a jemně ji tahej za vlasy. Cíl: deset zatažení a po každém se zeptat, jestli chce víc.|300|zezadu",
    "Dlaň na krku: Miluj se s ní a polož jí ruku na krk – jen položit, žádný tlak. Cíl: kdykoli řekne stop, ruku hned sundat.|300|misionar",
    "Kousnutí v pravou chvíli: Miluj ji na lžičku a kousni ji do ramene přesně ve chvíli, kdy je nejblíž vrcholu. Cíl: trefit se aspoň dvakrát.|300|lzicka",
    "Deset plácnutí: Přirážej do ní zezadu a desetkrát ji plácni po zadečku, pokaždé jinak silně. Cíl: dojít do deseti a ona počítá.|300|zezadu",
    "Ona vždycky první: Miluj se s ní a hlídej si vlastní vzrušení. Cíl: nechat ji dojít první a teprve pak myslet na sebe.|300|ona_nahore",
    "Oba naráz: Miluj se s ní a hlídejte si tempo tak, abyste došli ve stejnou chvíli. Cíl: trefit se do pěti vteřin.|300|misionar",
    "Společně: Miluj se s ní tak, abyste došli naráz, a když to nevyjde, zkuste to znovu. Cíl: trefit to na první pokus.|300|klin_celem",
    "Dvakrát ona, pak ty: Miluj se s ní a hlídej si vlastní vzrušení. Cíl: nechat ji dojít dvakrát dřív, než se uděláš ty.|300|ona_nahore",
    "Třikrát na hranu: Přirážej do ní až na hranu a pak pokaždé zpomal. Cíl: třikrát ji zastavit a počtvrté ji nechat dojít.|300|misionar",
    "Edging při sexu: Kdykoli je blízko, úplně se zastavíš. Pětkrát. Cíl: vydržet všech pět.|300|zezadu",
    "Počítej do sta: Nech ji jezdit na tobě a zakaž jí dojít, dokud nahlas nedopočítá do sta. Cíl: nenechat ji přeskočit ani jedno číslo.|300|ona_nahore",
    "Musí to vyslovit: Miluj se s ní, ale nesmí dojít, dokud nahlas neřekne, co přesně chce. Cíl: nepolevit, dokud to neřekne celou větou.|300|misionar",
    "Obě zápěstí v jedné ruce: Miluj se s ní a jednou rukou jí drž obě zápěstí nad hlavou. Cíl: pět minut a ani jednou ji nepustit.|300|misionar",
    "Vybírá všechno ona: Nech ji nasadit se na tebe a vybrat polohu, tempo i délku. Cíl: pět minut a ani jednou si nedělat po svém.|300|ona_nahore",
    "Její hra: Nech ji jezdit na tobě a rozhodovat o poloze i tempu, ty neřekneš ani slovo. Cíl: pět minut a nepřevzít vedení.|300|ona_nahore",
    "Rozhoduješ ty: Přirážej do ní zezadu a určuj polohu, tempo i pauzy, ona jen poslouchá. Cíl: pět minut a nenechat se přemluvit ke změně.|300|zezadu",
    "Výměna velení: Po každé minutě si prohodíte, kdo z vás řídí tempo přírazů. Cíl: pět výměn a ani jednou se nepřerušit.|300|klin_celem",
    "Led po zádech: Miluj ji zezadu a mezi tím jí přejížděj kostkou ledu po zádech. Cíl: pět cest ledem a ani jednou nezpomalit.|300|zezadu",
    "Led při sexu: Kostka ledu na jejích zádech, zatímco jsi v ní. Cíl: nenechat ji spadnout.|300|na_brise",
    "Pírko při sexu: Miluj se s ní a mezi tím jí přejížděj pírkem po prsou. Cíl: deset cest pírkem a ani jednou nepřerušit tempo.|300|misionar",
    "Neslyší tě: Dej jí sluchátka s hudbou, ať tě neslyší, a miluj ji zezadu. Cíl: pět minut a domluvit se jen doteky.|300|zezadu",
    "Oba v zrcadle: Miluj se s ní před zrcadlem tak, ať se oba vidíte. Cíl: pět minut a nespustit z ní v zrcadle oči.|300|zezadu",
    "Jen zvuk: Nahraj si na telefon zvuk celého sexu a pak si ho spolu poslechněte. Cíl: nahrávku dotáhnout do konce a nezastavit ji.|300|misionar",
    "Fantazie do ucha: Miluj ji na lžičku a do ucha jí popisuj svoji fantazii. Cíl: pět minut a ani jednou neztichnout.|300|lzicka",
    "Scénka: Vyberte si roli a celou dobu v ní zůstaňte, i když to bude k smíchu. Cíl: nevypadnout z role.|300|zezadu",
    "Aspoň jednou se zasmát: Miluj se s ní vsedě a najdi způsob, jak se oba rozesmát. Cíl: aspoň jeden společný smích za čtyři minuty.|240|klin_celem",
    "Beze změny: Miluj se s ní a nezměň ani polohu, ani tempo. Cíl: vydržet celých pět minut úplně stejně.|300|misionar",
    "Budík velí: Nastav si budík na každou minutu a při každém zazvonění změňte polohu. Cíl: pět poloh a nejvýš jedno vyklouznutí.|300|zezadu",
    "Pět minut, pět poloh: Každou minutu do ní přirážej v jiné poloze a ani jednou nevyklouzni. Cíl: pět různých poloh bez přerušení.|300|zezadu",
    "Nehty jako signál: Miluj se s ní a nech ji, ať ti zaryje nehty do zad, když je blízko. Cíl: podle toho pokaždé zrychlit.|300|misionar",
    "Dokud neřekne dost: Miluj ji zezadu stejným tempem. Cíl: nepřestat, dokud sama neřekne dost.|300|zezadu",
    "Krk a rameno: Miluj ji na lžičku a mezi tím jí olizuj krk a rameno. Cíl: pět minut a nepřestat ani u jednoho.|300|lzicka",
    "Konec podle ní: Miluj se s ní a nech ji vybrat, čím to skončí – tebou, rukou, nebo vibrátorem. Cíl: dotáhnout její volbu do konce.|300|ona_nahore",
    "Před koncem: Poslední minutu přirážej pořád stejně – žádná nová poloha, žádné nové tempo. Cíl: dojet to, jak to je.|60|misionar",
    "Miluj se s ní a nech ji říkat čísla od desíti dolů. Na nule končíte.|300|ona_nahore",
    "Vibrátor v její ruce: Dej jí do ruky vibrátor, miluj se s ní a nech ji použít ho, kdy chce. Cíl: pět minut a ani jednou jí do toho nemluvit.|300|misionar",
    "Nasaď si kroužek a nech ji rozhodnout, jak dlouho to bude trvat.|300|ona_nahore",
    "Miluj se s ní a mezi tím jí drž obě ruce za zády.|300|zezadu",
    "Jedna ruka volná: Sváž jí kravatou jednu ruku k posteli, druhou nech volnou a miluj se s ní. Cíl: pět minut a na stop ji hned rozvázat.|300|pouta_postel",
    "Poslušnost: Přirážej do ní zezadu a dej jí tři příkazy, které musí splnit hned. Cíl: pět minut a ani jedno zaváhání.|300|zezadu",
    "Miluj se s ní a mezi tím jí jemně kousni do zadečku.|300|na_brise",
    "Konec určuje ona: Nech ji nasadit se na tebe a říct ti, kdy smíš dojít. Cíl: pět minut a nedojít dřív, než to dovolí.|300|ona_nahore",
    "Miluj se s ní a nech ji říkat po každé minutě, co má být jinak.|300|misionar",
    "Bez jediného polibku: Miluj se s ní zezadu celých pět minut a ani jednou ji nepolib. Cíl: vydržet do konce.|300|zezadu",
    "Polibek bez konce: Miluj se s ní vsedě a celou dobu se líbejte. Cíl: pět minut a polibek ani jednou nepřerušit.|300|klin_celem",
    "Nepřerušený polibek: Nech ji jezdit na tobě a celou dobu se líbejte. Když polibek přerušíte, začínáte znovu. Cíl: pět minut.|300|klin_celem",
    "Miluj se s ní a mezi tím jí hlaď prsa oběma rukama.|300|zezadu_vzpr",
    "Hýbe se jen ona: Nech ji nasadit se na tebe, jen ji drž a ať všechno dělá sama. Cíl: pět minut a ty se nepohneš.|300|ona_nahore",
    "Miluj se s ní tak, aby to bylo co nejtišší. Ani postel nesmí vrzat.|300|misionar",
    "Co nejhlasitěji: Miluj se s ní zezadu a buďte oba tak hlasití, jak dokážete. Cíl: pět minut a ani jednou se neztišit.|300|zezadu",
    "Souboj o kontrolu: Oba se snažíte určovat tempo přírazů a kdo první povolí, plní přání. Cíl: pět minut a nevzdat to.|300|klin_celem",
    "Miluj se s ní a mezi tím jí šeptej, jak blízko jsi.|300|lzicka",
    "Konec na vteřinu: Nech ji jezdit na tobě a určit vteřinu, kdy je konec, a ty to dodrž. Cíl: netrefit se ani o vteřinu vedle.|300|ona_nahore",
    "Na konci v ní zůstaň a jen ji drž, dokud se oba nezklidníte.|120|propletene",
  ],

  female: [
    "Deset pomalu, deset rychle: Jezdi na něm deset pomalých pohybů a deset rychlých, pořád dokola. Cíl: pět celých kol bez chyby.|300|ona_nahore",
    "Podle nádechu: Jezdi na něm jen tehdy, když se nadechne, a při výdechu stůj. Cíl: padesát nádechů a ani jeden nepropásnout.|300|ona_nahore",
    "Tvoje jméno je stopka: Jezdi na něm a jakmile vysloví tvoje jméno, okamžitě se zastav. Cíl: deset zastavení za pět minut.|300|ona_nahore",
    "Tempo tleskáním: Jezdi na něm a tempo ti tleskáním určuje on. Cíl: pět minut a ani jednou se netrefit vedle.|300|ona_nahore",
    "Na jeho povel: Jezdi na něm a na jeho stop a start se zastav nebo pokračuj na vteřinu přesně. Cíl: pět minut bez jediného zpoždění.|300|ona_nahore",
    "Dokud nepoprosí: Jezdi na něm co nejpomaleji, dokud tě sám nepoprosí o rychleji. Cíl: nezrychlit, dokud to neřekne nahlas.|300|ona_nahore",
    "Pět a jeden na něm: Jezdi na něm pět pomalých pohybů a po nich vždycky jeden úplně rychlý. Cíl: dvacet kol a pořadí ani jednou nesplést.|300|ona_nahore",
    "Stupeň za minutu: Nasaď se na něj, začni nejpomaleji a po každé minutě přidej stupeň. Cíl: pět stupňů a ani jednou se nevrátit zpět.|300|ona_nahore",
    "Jen pár centimetrů: Jezdi na něm jen v posledních centimetrech a nikdy až úplně dolů. Cíl: pět minut a ani jednou nesjet dolů.|300|ona_nahore",
    "Naopak: Jezdi na něm vždycky úplně dolů a nikdy jen mělce. Cíl: pět minut a hloubku ani jednou neztratit.|300|ona_nahore",
    "Miluj se s ním, ale nesmíš se dotknout rukama ničeho kromě postele.|240|ona_nahore",
    "Bez rukou: Jezdi na něm s rukama opřenýma vedle něj a nesmíš se ho dotknout. Cíl: čtyři minuty a ani jeden dotek.|240|ona_nahore",
    "Kdo zavře oči: Miluj se s ním vsedě a ani jeden z vás nesmí zavřít oči. Cíl: pět minut – kdo je zavře první, plní přání toho druhého.|300|klin_celem",
    "Rozmluv ho: Jezdi na něm tak, aby nevydržel mlčet ani hlásku. Cíl: rozmluvit ho do pěti minut.|300|ona_nahore",
    "Potmě a beze slov: Zhasněte, milujte se a celou dobu mlčte – zbude jen dech a doteky. Cíl: pět minut a dorozumět se beze slov.|300|misionar",
    "Musí si říct: Jezdi na něm a ať nahlas říká, co chce. Jakmile ztichne, přestáváš. Cíl: pět minut a nejvýš tři pauzy.|300|ona_nahore",
    "Popisuj, co děláš: Jezdi na něm a nahlas popisuj každý svůj pohyb, ani na chvíli se neodmlč. Cíl: pět minut bez jediné pauzy.|300|ona_nahore",
    "Jeho ruce mimo hru: Jezdi na něm a on nesmí použít ruce k ničemu, ani se držet. Cíl: pět minut a ani jednou pravidlo neporušit.|300|ona_nahore",
    "Z očí do očí: Jezdi na něm a dokud se díváte do očí, zůstáváte v poloze. Kdo uhne, mění ji. Cíl: pět minut a nezměnit ji ani jednou.|300|klin_celem",
    "Nasaď mu erekční kroužek a pak si na něj sedni.|300|ona_nahore",
    "Kroužek a dlouhé tempo: Nasaď mu erekční kroužek a jezdi na něm hodně pomalu. Cíl: pět minut a ani jednou nezrychlit.|300|ona_nahore",
    "Vezmi vibrátor a drž si ho na klitorisu, zatímco je v tobě.|300|ona_nahore",
    "Vibrátor při sexu: Držíš si vibrátor sama a on se jen hýbe. Cíl: mít to ve svých rukou.|300|misionar",
    "Nech si přiložit vibrátor zezadu, zatímco do tebe vniká zepředu.|300|misionar",
    "Kravata nad hlavou: Sváž mu ruce kravatou nad hlavou a pak se na něj nasaď. Cíl: pět minut a na stop ho hned rozvázat.|300|pouta_postel!",
    "Ruce za zády vkleče: Sváž mu ruce za zády a nech ho tak do tebe zezadu přirážet. Cíl: pět minut a na stop ho hned rozvázat.|300|zezadu!",
    "S kravatou: Zavaž mu oči kravatou a miluj se s ním. Nesmí vědět, co přijde. Cíl: překvapit ho třikrát.|300|ona_nahore",
    "Poslepu a beze slov: Zavaž si oči a nech ho při sexu měnit polohy, aniž by řekl slovo. Cíl: čtyři polohy a nechat se vést jen rukama.|300|zezadu!",
    "Plácnutí po patnácté: Nech ho přirážet zezadu a ať tě plácne po zadečku po každých patnácti přírazech. Cíl: deset plácnutí.|300|zezadu",
    "Vlasy a zpětná vazba: Nech ho přirážet zezadu, jemně tě tahat za vlasy a pokaždé mu řekni, jak to je. Cíl: pět takových vět.|300|zezadu",
    "Ruka na krku: Nech ho přirážet a polož si jeho ruku na krk – jen položit, žádný tlak. Cíl: pět minut a na stop ruku hned sundat.|300|misionar",
    "Kousnutí do ramene: Jezdi mu na klíně a pokaždé, když je nejblíž, ho kousni do ramene. Cíl: deset kousnutí za pět minut.|300|klin_celem",
    "Deset plácnutí: Nech ho přirážet zezadu a desetkrát tě plácnout, pokaždé jinak silně. Cíl: dojít do deseti a počítat nahlas.|300|zezadu",
    "On první: Jezdi na něm, dokud nedojde, a teprve pak se postarej o sebe. Cíl: nepřestat, dokud nedojde on.|300|ona_nahore",
    "Ve stejnou vteřinu: Milujte se tak, abyste se udělali ve stejnou vteřinu. Cíl: trefit se do stejné vteřiny.|300|misionar",
    "Naráz: Jezdi na něm tak, abyste došli oba zároveň, a když to nevyjde, zkuste to znovu. Cíl: trefit se napoprvé.|300|klin_celem",
    "Třikrát ho zastavit: Jezdi na něm až na hranu a pak pokaždé zpomal. Cíl: třikrát ho zastavit a počtvrté ho nechat dojít.|300|ona_nahore",
    "Ty první: Jezdi na něm a hlídej mu tempo. Cíl: dojít dřív než on – teprve potom ho nechat.|300|ona_nahore",
    "Pět zastavení: Jezdi na něm a pokaždé, když je těsně před koncem, se úplně zastav. Cíl: zvládnout všech pět.|300|ona_nahore",
    "Počítej do sta: Jezdi na něm a zakaž mu udělat se, dokud nahlas nedopočítáš do sta. Cíl: nepřeskočit ani jedno číslo.|300|ona_nahore",
    "Musí to vyslovit: Jezdi na něm, ale nesmí se udělat, dokud nahlas neřekne, co přesně chce. Cíl: nepolevit, dokud to neřekne celou větou.|300|ona_nahore",
    "Ruce nad hlavou: Nasaď se na něj a nech si držet obě ruce nad hlavou jeho jednou rukou. Cíl: pět minut a na stop tě musí pustit.|300|misionar",
    "Vybírá všechno on: Nech ho vniknout do tebe a vybrat polohu, tempo i délku, ty jen plníš. Cíl: pět minut a ani jednou si nedělat po svém.|300|zezadu!",
    "Jeho hra: Nech ho přirážet a rozhodovat o poloze i tempu, ty neřekneš ani slovo. Cíl: pět minut a nepřevzít vedení.|300|zezadu!",
    "Velíš ty: Jezdi na něm a určuj polohu, tempo i pauzy, on jen poslouchá. Cíl: pět minut a nenechat se přemluvit ke změně.|300|ona_nahore",
    "Velení po minutě: Po každé minutě si vyměňte, kdo z vás řídí tempo přírazů. Cíl: pět výměn a ani jednou se nepřerušit.|300|klin_celem",
    "Miluj se s ním a mezi tím mu přejížděj ledem po zádech.|300|propletene",
    "Led při sexu: Kostka ledu na jeho zádech, zatímco je v tobě. Cíl: nenechat ji spadnout.|300|propletene",
    "Miluj se s ním a mezi tím mu přejeď pírkem po hrudníku.|300|ona_nahore",
    "Sluchátka na uších: Dej mu sluchátka s hudbou, ať tě neslyší, a nasaď se na něj. Cíl: pět minut a sluchátka mu nesundat.|300|ona_nahore",
    "Miluj se s ním před zrcadlem, ať se oba vidíte.|300|zezadu!",
    "Nahrávka jen se zvukem: Nahrajte si na telefon zvuk celého sexu a pak si ho spolu poslechněte. Cíl: nahrávku nezastavit dřív než na konci.|300|ona_nahore",
    "Miluj se s ním a přitom mu do ucha popisuj svoji fantazii.|300|lzicka",
    "Role: Každý si vybere postavu, milujte se v ní a nikdo z ní nevypadne. Cíl: pět minut a nevypadnout z role.|300|zezadu!",
    "Miluj se s ním a mezi tím se oba musíte zasmát. Aspoň jednou.|240|klin_celem",
    "Jedna poloha, jedno tempo: Jezdi na něm pět minut a nezměňte ani polohu, ani tempo. Cíl: vydržet celých pět minut.|300|ona_nahore",
    "Budík na minutu: Nastavte si budík na každou minutu a při každém zazvonění změňte polohu. Cíl: pět poloh a nejvýš jedno vyklouznutí.|300|zezadu!",
    "Minuta na polohu: Po každé minutě měníte polohu a ani jednou z tebe nevyklouzne. Cíl: pět různých poloh bez přerušení.|300|zezadu!",
    "Nehty do zad: Miluj se s ním a pokaždé, když jsi blízko, mu zaryj nehty do zad. Cíl: ať z toho pozná, kdy zrychlit.|300|misionar",
    "Miluj se s ním tak dlouho, dokud neřekne dost.|300|ona_nahore",
    "Miluj se s ním a mezi tím mu olizuj krk a rameno.|300|klin_celem",
    "Konec podle něj: Jezdi na něm a nech ho vybrat, čím to skončí – tebou, rukou, nebo ústy. Cíl: dotáhnout jeho volbu do konce.|300|ona_nahore",
    "Před koncem: Poslední minutu jezdi pořád stejně – žádná nová poloha, žádné nové tempo. Cíl: dojet to, jak to je.|60|ona_nahore",
    "Miluj se s ním a nech ho říkat čísla od desíti dolů. Na nule končíte.|300|ona_nahore",
    "Vibrátor v tvé ruce: Nasaď se na něj, vezmi si vibrátor a použij ho, kdy budeš chtít. Cíl: pět minut a nesmí ti do toho mluvit.|300|ona_nahore",
    "Kroužek a tvoje pravidla: Nasaď mu kroužek, nasaď se na něj a sama rozhodni, jak dlouho to potrvá. Cíl: pět minut a konec určíš ty.|300|ona_nahore",
    "Jeho ruce za zády: Jezdi na něm a celou dobu mu drž ruce za zády. Cíl: pět minut a na stop ho hned pustit.|300|ona_nahore",
    "Jedna ruka volná: Sváž mu kravatou jednu ruku k posteli, druhou nech volnou a nasaď se na něj. Cíl: pět minut a na stop ho rozvázat.|300|pouta_postel!",
    "Poslušnost: Jezdi na něm a dej mu tři příkazy, které musí splnit hned. Cíl: pět minut a ani jedno zaváhání.|300|ona_nahore",
    "Miluj se s ním a mezi tím ho jemně kousni do zadku.|300|propletene",
    "Konec určuješ ty: Nasaď se na něj a řekni mu, kdy se smí udělat. Cíl: pět minut a nesmí to udělat dřív.|300|ona_nahore",
    "Miluj se s ním a po každé minutě mu řekni, co má být jinak.|300|misionar",
    "Bez jediného polibku: Nech ho přirážet zezadu celých pět minut a ani jednou se nepolibte. Cíl: vydržet do konce.|300|zezadu!",
    "Pusa na puse: Jezdi mu na klíně a celou dobu se líbejte, bez jediného přerušení. Cíl: pět minut a neodtrhnout se.|300|klin_celem",
    "Jeden dlouhý polibek: Jezdi mu na klíně a nesmíte se od sebe odtrhnout, jinak začínáte znovu. Cíl: vydržet do konce.|300|klin_celem",
    "Obě ruce na prsou: Nech se milovat zezadu vkleče a jeho ruce si nech na prsou. Cíl: pět minut a nedovolit mu je sundat.|300|zezadu_vzpr",
    "Hýbeš se jen ty: Nasaď se na něj, ať tě jen drží, a všechno dělej sama. Cíl: pět minut a on se ani jednou nepohne.|300|ona_nahore",
    "Miluj se s ním tak, aby to bylo co nejtišší. Ani postel nesmí vrzat.|300|ona_nahore",
    "Co nejhlasitěji: Nech ho přirážet zezadu a buďte oba tak hlasití, jak dokážete. Cíl: pět minut a ani jednou se neztišit.|300|zezadu!",
    "Přetahovaná: Každý si tahá tempo přírazů na svou stranu a kdo první povolí, plní přání. Cíl: pět minut a nevzdat to.|300|klin_celem",
    "Miluj se s ním a mezi tím mu šeptej, jak blízko jsi.|300|lzicka",
    "Konec na vteřinu: Jezdi na něm a nech ho určit vteřinu, kdy je konec, a ty to dodrž. Cíl: netrefit se ani o vteřinu vedle.|300|ona_nahore",
    "Konec bez pohybu: Nech ho po posledním přírazu zůstat v tobě a jen se držte, dokud se nezklidníte. Cíl: dvě minuty klidu.|120|propletene",
  ],
});
