// Kategorie 4 – Sex a polohy (dávka d)
// Témata: v sedě, ve stoje, na kraji postele, zvednutá, přechody mezi polohami.
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 4,

  male: [
    "Sedni si na židli a posaď si ji obkročmo na klín. Pohyb dělá ona.|240|zidle_celem",
    "Na židli čelem: Ona ti sedí obkročmo a drží se opěradla. Ty jí držíš boky. Cíl: nechat ji, ať určí tempo.|300|zidle_celem",
    "Sedni si a nech ji sednout si na tebe zády. Drž ji přes prsa.|240|klin_zady",
    "Na židli zády k tobě a ty jí sahej dopředu.|300|klin_zady",
    "Posaď si ji na klín a jen se objímejte, zatímco v ní jsi.|240|klin_celem",
    "Sedni si na podlahu a nech ji sednout si na tebe. Nohy propleťte.|240|lotos",
    "Lotos vsedě: Sedíte proti sobě, nohy propletené, ona na tobě. Hýbat se dá jen boky. Cíl: vydržet pět minut.|300|lotos",
    "Posaď ji na kraj postele a stůj před ní.|240|kraj_postele",
    "Na kraji postele jí zvedni nohy a drž ji za stehna.|240|kraj_postele",
    "Kraj postele: Ona leží na kraji, ty stojíš. Výška je přesně tak akorát. Cíl: najít správnou výšku.|240|kraj_postele",
    "Ať si sedne na kraj postele a přitáhne si tě nohama.|240|kraj_postele",
    "Na kraji postele jí polož nohy na svá ramena a nakloň se.|240|kraj_postele",
    "Postav ji ke zdi a zvedni jí jednu nohu.|240|zed",
    "U zdi ji drž za zápěstí nad hlavou.|240|zed",
    "U zdi a pomalu: Ona je opřená o zeď, ty proti ní. Nesmíš zrychlit ani jednou. Cíl: vydržet pomalé tempo ve stoje.|240|zed",
    "Postav ji čelem ke zdi a vnikni do ní zezadu.|240|zed",
    "U zdi jí dej ruce na zeď a ať se opře.|240|zed",
    "Předkloň ji přes opěradlo gauče a jdi do ní zezadu.|240|predklon",
    "Přes opěradlo jí drž ruce za zády.|240|predklon",
    "Přes opěradlo: Ona se drží opěradla, ty stojíš za ní. Můžeš jít hodně naplno. Cíl: najít společný rytmus.|240|predklon",
    "Ať se předkloní a opře si ruce o kolena. Ty za ní.|240|predklon_stoje",
    "Předkloněná ve stoje a ty ji držíš za boky.|240|predklon_stoje",
    "Zvedni ji do náruče a nech ji, ať se tě drží nohama.|180|zvednuta",
    "V náručí: Drž ji nahoře tak dlouho, jak zvládneš, a pak ji polož ke zdi. Cíl: dojít až ke zdi.|180|zvednuta",
    "Zvedni ji a opři ji zády o zeď, ať máš oporu.|240|zed",
    "Posaď si ji na kraj stolu nebo linky a přitáhni si ji za boky.|240|kraj_postele",
    "Sedni si na kraj postele a nech ji sednout si na tebe čelem.|240|klin_celem",
    "Na kraji postele vsedě ji drž pod zadečkem a zvedej.|240|klin_celem",
    "Sedni si opřený o čelo postele a ona si sedne na tebe.|240|ona_nahore",
    "Vsedě opřený: Sedíš opřený, ona na tobě čelem. Můžete se u toho líbat celou dobu. Cíl: nepřerušit polibek.|300|klin_celem",
    "Sedni si na židli a nech ji, ať se před tebou nejdřív svlékne.|300|zidle_celem",
    "Na židli jí drž ruce za zády, zatímco na tobě sedí.|240|zidle_celem",
    "Sedni si na židli a nech ji sednout si zády s nohama mezi tvýma.|240|klin_zady",
    "Na židli zády k tobě jí drž boky a určuj tempo.|240|klin_zady",
    "Ať si klekne na židli čelem k opěradlu a ty jsi za ní.|240|zidle_celem",
    "Sedni si na podlahu opřený o postel a nech ji sednout si na tebe.|240|lotos",
    "Na podlaze: Sedíte na koberci, ona na tobě, oba opření o ruce. Cíl: udržet rovnováhu.|240|lotos",
    "Postav se a nech ji, ať se ti pověsí na krk.|180|zvednuta",
    "Zvedni ji a posaď si ji na kraj postele, aniž bys z ní vyšel.|240|kraj_postele",
    "Ať si sedne na kraj a ty klečíš na podlaze před ní.|240|kraj_postele",
    "Na kraji postele jí dej nohy kolem svého pasu.|240|kraj_postele",
    "Ať leží na kraji a ty ji držíš za kotníky roztažené.|240|kraj_postele",
    "Tři výšky: Vystřídáte polohu vleže, vsedě a ve stoje, každou dvě minuty. Cíl: projít všechny tři.|300|kraj_postele",
    "Začni ve stoje u zdi a skonči vsedě na židli. Bez přerušení.|300|zed",
    "Začni na židli a přejdi do stoje s ní v náručí.|300|zvednuta",
    "Přejdi z lžičky do misionáře, aniž bys z ní vyšel.|300|lzicka",
    "Přechod bez vyjití: Vystřídejte tři polohy a ani jednou z ní nevyjdeš. Cíl: tři plynulé přechody.|300|zezadu",
    "Ať se opře o kraj postele a stojí. Ty za ní.|240|predklon",
    "Postav ji před zrcadlo a vnikni do ní zezadu, ať se dívá.|240|zed",
    "U zdi ji drž za bok a druhou rukou jí drž nohu nahoře.|240|zed",
    "Ať se drží zárubně dveří a ty jsi za ní.|240|predklon_stoje",
    "Ve stoje a potichu: Celý úkol ve stoje a ani jeden z vás nesmí vydat hlásku. Cíl: úplné ticho.|240|zed",
    "Posaď si ji na klín na podlaze a obejmi ji oběma rukama.|240|klin_podlaha",
    "Sedni si za ni a nech ji sedět mezi tvýma nohama zády.|240|klin_podlaha",
    "Na klíně zády: Ona ti sedí na klíně zády a ty jí sáhneš dopředu. Cíl: nepřestat ji dráždit ani na chvíli.|300|klin_zady",
    "Sedni si na kraj postele a nech ji stát mezi tvýma nohama.|180|oral_vsede",
    "Zvedni ji a drž ji na sobě, dokud vydržíš. Pak sedni.|180|zvednuta",
    "Ať si na tebe sedne na židli a nohy si dá kolem opěradla.|240|zidle_celem",
    "Sedni si a nech ji, ať se na tobě houpe jen dopředu a dozadu.|240|klin_celem",
    "Vsedě čelem a pomalu, ať se můžete celou dobu dívat do očí.|300|klin_celem",
    "Oči v očích vsedě: Sedíte čelem k sobě a nesmíte uhnout pohledem. Cíl: vydržet až do konce.|300|klin_celem",
    "Ať se předkloní přes postel a ty stojíš za ní.|240|predklon",
    "Přes postel jí polož ruku mezi lopatky a přitlač.|240|predklon",
    "Ať stojí předkloněná a ty jí držíš obě zápěstí vzadu.|240|predklon_stoje",
    "Postav ji ke zdi zády k sobě a jednou rukou jí drž rameno.|240|zed",
    "Ve stoje jí zvedni nohu na kraj postele.|240|zed",
    "Jedna noha nahoře: Ona stojí, jednu nohu má opřenou vysoko. Ty držíš její koleno. Cíl: vydržet tak dvě minuty.|240|zed",
    "Sedni si na židli a nech ji, ať si na tebe sedne zády a opře se dozadu.|240|klin_zady",
    "Sedni si a nech ji, ať se pomalu otáčí, zatímco na tobě sedí.|300|ona_nahore",
    "Posaď si ji na klín a hýbej se jen ty.|240|klin_celem",
    "Ať sedí na tobě a drží se tvých ramen. Ty ji zvedáš.|240|klin_celem",
    "Sedni si a ať si na tebe sedne úplně pomalu. Po centimetrech.|180|klin_celem",
    "Pomalé usednutí: Ona si na tebe sedá celou minutu. Ani o vteřinu dřív. Cíl: vydržet celou minutu.|60|klin_celem",
    "Ve stoje ji drž kolem pasu a ať se drží tvého krku.|180|zvednuta",
    "Postav ji na kraj postele, aby byla výš než ty.|240|kraj_postele",
    "Ať si sedne na okraj a ty ji držíš za ruce a přitahuješ.|240|kraj_postele",
    "Na kraji postele si ji přitáhni za kolena úplně k sobě.|240|kraj_postele",
    "Ať leží napříč postelí a ty stojíš z boku.|240|kraj_postele",
    "Ze stoje do lehu: Začni ve stoje a postupně skončete vleže, aniž byste přerušili. Cíl: plynulý přechod.|300|zed",
    "Sedni si a nech ji rozhodnout, jestli bude čelem, nebo zády.|240|klin_celem",
    "Ať si klekne na židli a opře se o opěradlo. Ty stojíš za ní.|240|zidle_celem",
    "Na konci si ji posaď na klín a jen ji drž.|120|klin_celem",
  ],

  female: [
    "Nech ho sednout si na židli a sedni si mu obkročmo na klín. Pohyb děláš ty.|240|zidle_celem",
    "Na židli čelem: Sedíš mu obkročmo a držíš se opěradla. On tě drží za boky. Cíl: určovat tempo sama.|300|zidle_celem",
    "Nech ho sednout si a sedni si mu na klín zády. Ať tě drží přes prsa.|240|klin_zady",
    "Na židli zády k němu a nech si sahat dopředu.|300|klin_zady",
    "Sedni si mu na klín a jen se objímejte, zatímco je v tobě.|240|klin_celem",
    "Nech ho sednout si na podlahu a sedni si na něj. Nohy propleťte.|240|lotos",
    "Lotos vsedě: Sedíte proti sobě, nohy propletené, ty na něm. Hýbat se dá jen boky. Cíl: vydržet pět minut.|300|lotos",
    "Sedni si na kraj postele a nech ho stát před tebou.|240|kraj_postele!",
    "Na kraji postele si nech zvednout nohy a držet za stehna.|240|kraj_postele!",
    "Kraj postele: Ležíš na kraji, on stojí. Výška je přesně tak akorát. Cíl: najít správnou výšku.|240|kraj_postele",
    "Sedni si na kraj postele a přitáhni si ho nohama.|240|kraj_postele",
    "Na kraji postele si polož nohy na jeho ramena a nech ho naklonit se.|240|kraj_postele!",
    "Opři se o zeď a zvedni jednu nohu.|240|zed",
    "U zdi si nech držet zápěstí nad hlavou.|240|zed",
    "U zdi a pomalu: Jsi opřená o zeď, on proti tobě. Nesmí zrychlit ani jednou. Cíl: vydržet pomalé tempo ve stoje.|240|zed",
    "Postav se čelem ke zdi a nech ho vniknout zezadu.|240|zed",
    "U zdi si dej ruce na zeď a opři se.|240|zed",
    "Předkloň se přes opěradlo gauče a nech ho jít zezadu.|240|predklon",
    "Přes opěradlo si nech držet ruce za zády.|240|predklon!",
    "Přes opěradlo: Držíš se opěradla, on stojí za tebou. Může jít hodně naplno. Cíl: najít společný rytmus.|240|predklon!",
    "Předkloň se a opři si ruce o kolena. On je za tebou.|240|predklon_stoje",
    "Předkloněná ve stoje a nech se držet za boky.|240|predklon_stoje",
    "Nech se zvednout do náruče a drž se ho nohama.|180|zvednuta",
    "V náručí: Ať tě drží nahoře tak dlouho, jak zvládne, a pak tě opře o zeď. Cíl: dojít až ke zdi.|180|zvednuta",
    "Nech se zvednout a opřít zády o zeď, ať má oporu.|240|zed",
    "Sedni si na kraj stolu nebo linky a nech se přitáhnout za boky.|240|kraj_postele",
    "Nech ho sednout si na kraj postele a sedni si na něj čelem.|240|klin_celem",
    "Vsedě na kraji postele se nech držet pod zadečkem a zvedat.|240|klin_celem",
    "Nech ho opřít se o čelo postele a sedni si na něj.|240|ona_nahore",
    "Vsedě opřený: Sedí opřený, ty na něm čelem. Můžete se u toho líbat celou dobu. Cíl: nepřerušit polibek.|300|klin_celem",
    "Nech ho sednout si na židli a před ním se nejdřív svlékni.|300|zidle_celem",
    "Na židli si nech držet ruce za zády, zatímco na něm sedíš.|240|zidle_celem",
    "Sedni si mu zády na klín s nohama mezi jeho.|240|klin_zady",
    "Na židli zády k němu si nech držet boky a určovat tempo.|240|klin_zady",
    "Klekni si na židli čelem k opěradlu a nech ho jít zezadu.|240|zidle_celem",
    "Nech ho sednout si na podlahu opřeného o postel a sedni si na něj.|240|lotos",
    "Na podlaze: Sedíte na koberci, ty na něm, oba opření o ruce. Cíl: udržet rovnováhu.|240|lotos",
    "Pověs se mu na krk a nech se zvednout.|180|zvednuta",
    "Nech se zvednout a posadit na kraj postele, aniž by z tebe vyšel.|240|kraj_postele",
    "Sedni si na kraj a nech ho kleknout si na podlahu před tebe.|240|kraj_postele",
    "Na kraji postele si dej nohy kolem jeho pasu.|240|kraj_postele!",
    "Lež na kraji a nech si držet kotníky roztažené.|240|kraj_postele",
    "Od podlahy nahoru: Dvě minuty vleže, dvě vsedě a dvě ve stoje. Cíl: projít všechny tři výšky.|300|kraj_postele!",
    "Začněte ve stoje u zdi a skončete vsedě na židli. Bez přerušení.|300|zed",
    "Začněte na židli a přejděte do stoje, ať tě nese v náručí.|300|zvednuta",
    "Přejděte ze lžičky do misionáře, aniž by z tebe vyšel.|300|lzicka",
    "Přechod bez vyjití: Vystřídejte tři polohy a ani jednou z tebe nevyjde. Cíl: tři plynulé přechody.|300|zezadu",
    "Opři se o kraj postele ve stoje. On je za tebou.|240|predklon",
    "Postav se před zrcadlo a nech ho vniknout zezadu, ať se díváš.|240|zed",
    "U zdi si nech držet bok a nohu nahoře.|240|zed",
    "Chyť se zárubně dveří a nech ho za sebou.|240|predklon_stoje!",
    "Tiše ve stoje: Zvládněte celý úkol ve stoje bez jediného zvuku. Cíl: úplné ticho.|240|zed",
    "Sedni si mu na klín na podlaze a nech se obejmout oběma rukama.|240|klin_podlaha",
    "Sedni si mu mezi nohy zády a opři se o něj.|240|klin_podlaha",
    "Na klíně zády: Sedíš mu na klíně zády a on ti sahá dopředu. Cíl: ať tě nepřestane dráždit ani na chvíli.|300|klin_zady",
    "Nech ho sednout si na kraj postele a postav se mezi jeho nohy.|180|oral_on_vsede",
    "Nech se zvednout a držet na něm, dokud vydrží. Pak si sedněte.|180|zvednuta",
    "Sedni si na něj na židli a nohy si dej kolem opěradla.|240|zidle_celem",
    "Sedni si na něj a houpej se jen dopředu a dozadu.|240|klin_celem",
    "Sedni si na něj čelem a jeďte tak pomalu, abyste si mohli celou dobu koukat do očí.|300|klin_celem",
    "Pohled vsedě: Sedíte čelem k sobě a ani jeden neuhne očima. Cíl: vydržet až do konce.|300|klin_celem",
    "Předkloň se přes postel a nech ho stát za tebou.|240|predklon!",
    "Přes postel si nech položit ruku mezi lopatky a přitlačit.|240|predklon!",
    "Stůj předkloněná a nech si držet obě zápěstí vzadu.|240|predklon_stoje",
    "Postav se ke zdi zády k němu a nech si držet rameno.|240|zed",
    "Ve stoje si zvedni nohu na kraj postele.|240|zed",
    "Jedna noha nahoře: Stojíš a jednu nohu máš opřenou vysoko. On drží tvoje koleno. Cíl: vydržet tak dvě minuty.|240|zed",
    "Sedni si mu na židli zády a opři se dozadu.|240|klin_zady",
    "Sedni si na něj a pomalu se otáčej, zatímco na něm sedíš.|300|ona_nahore",
    "Sedni si mu na klín a nech hýbat se jen jeho.|240|klin_celem",
    "Sedni si na něj a drž se jeho ramen. On tě zvedá.|240|klin_celem",
    "Sedni si na něj úplně pomalu. Po centimetrech.|180|klin_celem",
    "Pomalé usednutí: Sedáš si na něj celou minutu. Ani o vteřinu dřív. Cíl: vydržet celou minutu.|60|klin_celem",
    "Ve stoje se nech držet kolem pasu a drž se jeho krku.|180|zvednuta",
    "Postav se na kraj postele, ať jsi výš než on.|240|kraj_postele",
    "Sedni si na okraj a nech se držet za ruce a přitahovat.|240|kraj_postele",
    "Na kraji postele si ho přitáhni koleny úplně k sobě.|240|kraj_postele!",
    "Lehni si napříč postelí a nech ho stát z boku.|240|kraj_postele!",
    "Ze stoje do lehu: Začněte ve stoje a postupně skončete vleže, aniž byste přerušili. Cíl: plynulý přechod.|300|zed",
    "Sedni si na něj a rozhodni sama, jestli budeš čelem, nebo zády.|240|klin_celem",
    "Klekni si na židli a opři se o opěradlo. On stojí za tebou.|240|zidle_celem",
    "Na konci si mu sedni na klín a nech se držet.|120|klin_celem",
  ],
});
