// Kategorie 4 – Sex a polohy (dávka c)
// Témata: zezadu ve všech variantách a ona nahoře čelem, zády, v dřepu.
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 4,

  male: [
    "Ať si klekne na všechny čtyři a vnikni do ní zezadu. Drž ji za boky.|240|zezadu",
    "Zezadu a pomalu: Ona klečí, ty za ní. Deset pohybů pomalu, pak deset naplno. Cíl: čtyři taková kola.|300|zezadu",
    "Zezadu jí polož ruku mezi lopatky a jemně ji zatlač do podložky.|240|zezadu",
    "Ať se opře o lokty a zvedne zadeček. Ty jí drž boky oběma rukama.|240|zezadu",
    "Zezadu jí zajeď rukou dopředu a dráždi ji, zatímco do ní vnikáš.|300|zezadu",
    "Zezadu ji chyť za ramena a přitahuj si ji k sobě.|240|zezadu",
    "Nech ji ležet na břiše s polštářem pod boky a vnikni do ní shora.|240|na_brise",
    "Na břiše a hluboko: Ona leží na břiše, nohy u sebe. Bude to nejtěsnější poloha, jakou znáte. Cíl: jít hodně pomalu.|300|na_brise",
    "Na břiše jí zvedni jeden bok a vnikej z boku.|240|na_brise",
    "Ať klečí vzpřímeně a ty za ní taky. Drž ji přes prsa.|240|zezadu_vzpr",
    "Vzpřímeně zezadu jí jednou rukou drž rameno a druhou dráždi klitoris.|300|zezadu_vzpr",
    "Vzpřímeně na kolenou: Oba klečíte, ona před tebou. Obejmi ji a pohybuj se jen málo. Cíl: co největší blízkost.|300|zezadu_vzpr",
    "Ať klečí a drží se čela postele. Ty za ní.|240|pouta_postel",
    "Zezadu jí vezmi ruce dozadu a drž ji za zápěstí.|240|zezadu",
    "Zezadu ji lehce tahej za vlasy. Jen tak, aby jí to bylo příjemné.|240|zezadu",
    "Zezadu ji plácni po zadečku vždycky po deseti pohybech.|240|zezadu",
    "Ať si klekne a opře čelo o postel. Ty jsi nad ní a jedeš hluboko.|240|zezadu",
    "Zezadu a stop: Zastav se pokaždé, když se blíží, a čekej deset vteřin. Třikrát. Cíl: vydržet všechna tři zastavení.|300|zezadu",
    "Zezadu jí pod břicho vsuň polštář, ať má jiný úhel.|240|na_brise",
    "Ať klečí na kraji postele a ty stojíš na podlaze za ní.|240|zezadu",
    "Zezadu jí dej ruku na krk. Jen položit, netlačit.|240|zezadu",
    "Nech ji klečet a sám se nehýbej. Přirážet musí ona.|300|zezadu",
    "Zezadu jí dej jednu ruku na rameno a druhou na bok a urči tempo.|240|zezadu",
    "Ona nahoře: Lehni si na záda a nech ji, ať si na tebe sedne a řídí všechno sama. Cíl: nepohnout se ani jednou.|300|ona_nahore",
    "Ať si na tebe sedne čelem a ty jí drž ruce.|240|ona_nahore",
    "Ona nahoře, ty ji držíš za boky a pomáháš jí s tempem.|240|ona_nahore",
    "Nech ji na sobě kroužit místo zvedání. Bude to úplně jinak.|300|ona_nahore",
    "Ať si sedne a opře se rukama dozadu o tvoje stehna.|240|ona_nahore",
    "Ona nahoře a ty jí olizuj bradavky, když se skloní.|240|ona_nahore",
    "Kroužení shora: Ona na tobě nesmí vůbec zvedat boky, jen kroužit. Cíl: dovést ji tam jen kroužením.|300|ona_nahore",
    "Nech ji sednout si na tebe zády a dívej se, jak se hýbe.|240|ona_nahore_zady",
    "Ona zády a ty jí hladíš záda a zadeček.|240|ona_nahore_zady",
    "Ona zády, ty ji držíš za boky a zvedáš ji.|240|ona_nahore_zady",
    "Zády a rukou: Ona sedí zády a ty jí zezadu sáhneš dopředu a dráždíš ji. Cíl: obojí najednou.|300|ona_nahore_zady",
    "Ať si na tebe dřepne a pohybuje se nahoru a dolů.|240|drep",
    "V dřepu nad tebou a ty ji držíš za ruce, ať má oporu.|240|drep",
    "Dřep a pauza: V dřepu udělá deset pohybů a pak na deset vteřin zůstane dole. Pětkrát. Cíl: pět kol.|300|drep",
    "Nech ji na tobě sedět úplně bez pohybu celou minutu.|60|ona_nahore",
    "Ať si sedne a ty jí drž ruce za zády.|240|ona_nahore",
    "Ona nahoře a ty ji držíš pod zadečkem a zvedáš.|240|ona_nahore",
    "Ať si sedne obkročmo a ty se posaď taky. Obejměte se.|240|klin_celem",
    "Vsedě proti sobě: Sedíte oba, ona na tobě, nohy propletené. Hýbat se dá jen málo, o to víc to je. Cíl: vydržet v objetí.|300|klin_celem",
    "Nech ji sedět na tobě a pomalu ji kloň dozadu.|240|ona_nahore",
    "Ona nahoře a ty ji drž za vlasy stažené do ruky.|240|ona_nahore",
    "Ať si sedne a ty jí přiložíš vibrátor zepředu.|300|ona_nahore",
    "Ona nahoře a ty jí zakryješ oči dlaní.|240|ona_nahore",
    "Sto pohybů shora: Ona udělá přesně sto pohybů. Ty jen ležíš a počítáš nahlas. Cíl: dojít do sta.|300|ona_nahore",
    "Nech ji sedět na tobě zády a drž jí kotníky.|240|ona_nahore_zady",
    "Zezadu jí zvedni jednu nohu na postel, ať má jiný úhel.|240|zezadu",
    "Zezadu ji drž za obě ramena a přitahuj si ji na sebe.|240|zezadu",
    "Nech ji klečet a sám zůstaň stát. Rozdíl výšek to změní.|240|zezadu",
    "Zezadu ji obejmi kolem pasu a drž ji těsně u sebe.|240|zezadu_vzpr",
    "Zezadu jí polož ruku na břicho a přitáhni si ji k sobě.|240|zezadu_vzpr",
    "Zezadu a šeptem: Klečíte oba, ty za ní, a celou dobu jí šeptáš do ucha, co s ní děláš. Cíl: nepřestat mluvit.|300|zezadu_vzpr",
    "Nech ji na sobě sedět a pohybovat se, jen když ty vydechneš.|300|ona_nahore",
    "Ať si na tebe sedne a drží se čela postele.|240|ona_nahore",
    "Ona nahoře a ty jí hladíš stehna a boky.|240|ona_nahore",
    "Střídej: minutu ona nahoře, minutu ty zezadu. Bez přerušení.|300|zezadu",
    "Tři polohy za sebou: Zezadu, pak ona nahoře, pak misionář. Přechody bez vyjití. Cíl: všechny tři plynule.|300|zezadu",
    "Zezadu jí polož ruce na lopatky a jemně zatlač dolů.|240|zezadu",
    "Nech ji klečet a ty za ní jen velmi pomalu.|300|zezadu",
    "Zezadu jí dej ruku dopředu na prsa a přitáhni ji.|240|zezadu_vzpr",
    "Ať si klekne bokem k tobě a ty vnikej ze strany.|240|zezadu",
    "Zezadu jí drž oba kotníky a řiď šířku jejích nohou.|240|na_brise",
    "Na břiše ji drž za zápěstí nad hlavou.|240|na_brise",
    "Zadeček nahoru: Ona leží na hrudníku a zvedá zadeček co nejvýš. Ty jsi nad ní. Cíl: vydržet ten úhel.|240|na_brise",
    "Nech ji na tobě sedět čelem a líbejte se u toho.|240|ona_nahore",
    "Ona nahoře a ty jí sevřeš boky mezi dlaněmi.|240|ona_nahore",
    "Ať si sedne a ty jí dáš ruce na krk a na prsa.|240|ona_nahore",
    "Ona nahoře a mezi tím jí lehce plácneš po zadečku.|240|ona_nahore",
    "Dvojí kontrola: Minutu řídí ona, minutu ty, a tak dokola. Cíl: pět výměn bez přerušení.|300|ona_nahore",
    "Nech ji sedět na tobě a při každém sestupu se zhluboka nadechni.|300|ona_nahore",
    "Ať se na tobě nakloní dopředu a opře se ti o hrudník.|240|ona_nahore",
    "Ona nahoře, ale s rukama za zády. Ty ji držíš.|240|ona_nahore",
    "Ať si na tebe sedne zády a nakloní se dopředu k tvým kolenům.|240|ona_nahore_zady",
    "Zády a hluboko: Ona sedí zády a nakloní se dopředu. Úhel je úplně jiný. Cíl: najít, kde to sedí nejlíp.|300|ona_nahore_zady",
    "Zezadu ji chyť pod břichem a zvedni k sobě.|240|zezadu",
    "Nech ji klečet a ty se pohybuj jen v posledních centimetrech.|300|zezadu",
    "Zezadu ji drž za ruku propletenou s tvojí.|240|zezadu",
    "Ať klečí a ty za ní stojíš na kolenou vzpřímeně. Drž ji za boky.|240|zezadu_vzpr",
    "Zezadu a vibrátor: Klečíš za ní a přikládáš jí vibrátor zepředu. Cíl: nepustit ho celou dobu.|300|zezadu",
    "Nech ji na tobě a jen se dívej, jak se snaží.|300|ona_nahore",
    "Na konci ji nech sednout si na tebe a jen se objímejte.|120|klin_celem",
  ],

  female: [
    "Klekni si na všechny čtyři a nech ho vniknout zezadu. Ať tě drží za boky.|240|zezadu",
    "Zezadu a pomalu: Klečíš, on za tebou. Deset pohybů pomalu, pak deset naplno. Cíl: čtyři taková kola.|300|zezadu",
    "Nech si od něj položit ruku mezi lopatky a jemně se zatlačit do podložky.|240|zezadu",
    "Opři se o lokty a zvedni zadeček. Ať tě drží za boky oběma rukama.|240|zezadu",
    "Zezadu si dej jeho ruku dopředu, ať tě dráždí, zatímco do tebe vniká.|300|zezadu",
    "Nech se zezadu chytit za ramena a přitahovat k němu.|240|zezadu",
    "Lehni si na břicho s polštářem pod boky a nech ho vniknout shora.|240|na_brise",
    "Na břiše a hluboko: Lež na břiše s nohama u sebe. Bude to nejtěsnější poloha, jakou znáte. Cíl: jít hodně pomalu.|300|na_brise",
    "Na břiše zvedni jeden bok a nech ho vnikat z boku.|240|na_brise!",
    "Klekni si vzpřímeně a nech ho kleknout si za tebe. Ať tě drží přes prsa.|240|zezadu_vzpr",
    "Vzpřímeně zezadu si dej jeho jednu ruku na rameno a druhou na klitoris.|300|zezadu_vzpr!",
    "Vzpřímeně na kolenou: Oba klečíte, ty před ním. Nech se obejmout a hýbejte se jen málo. Cíl: co největší blízkost.|300|zezadu_vzpr",
    "Klekni si a drž se čela postele. On je za tebou.|240|pouta_postel",
    "Dej ruce dozadu a nech si je od něj držet za zápěstí.|240|zezadu",
    "Nech se zezadu lehce tahat za vlasy. Jen tak, aby to bylo příjemné.|240|zezadu",
    "Řekni mu, ať tě zezadu plácne po zadečku vždycky po deseti pohybech.|240|zezadu",
    "Klekni si a opři si čelo o postel. On je nad tebou a jede hluboko.|240|zezadu",
    "Zezadu a stop: Ať se zastaví pokaždé, když se blížíš, a počká deset vteřin. Třikrát. Cíl: vydržet všechna tři zastavení.|300|zezadu!",
    "Vsuň si pod břicho polštář, ať máš jiný úhel.|240|na_brise",
    "Klekni si na kraj postele a nech ho stát na podlaze za tebou.|240|zezadu!",
    "Nech si od něj položit ruku na krk. Jen položit, netlačit.|240|zezadu",
    "Klečíš a on se nehýbe. Přirážet musíš ty.|300|zezadu",
    "Ať ti dá jednu ruku na rameno a druhou na bok a určí tempo.|240|zezadu!",
    "Ona nahoře: Sedni si na něj a řiď všechno sama. On se nesmí ani jednou pohnout. Cíl: mít to celé v rukou.|300|ona_nahore",
    "Sedni si na něj čelem a nech si od něj držet ruce.|240|ona_nahore",
    "Sedni si na něj a nech se držet za boky, ať ti pomáhá s tempem.|240|ona_nahore",
    "Na něm krouži místo zvedání. Bude to úplně jinak.|300|ona_nahore",
    "Sedni si a opři se rukama dozadu o jeho stehna.|240|ona_nahore",
    "Sedni si na něj a skloň se, ať ti může olizovat bradavky.|240|ona_nahore",
    "Kroužení shora: Na něm nesmíš vůbec zvedat boky, jen kroužit. Cíl: dojít tam jen kroužením.|300|ona_nahore",
    "Sedni si na něj zády a nech ho koukat, jak se hýbeš.|240|ona_nahore_zady",
    "Zády k němu a nech si hladit záda a zadeček.|240|ona_nahore_zady",
    "Zády k němu a nech se držet za boky a zvedat.|240|ona_nahore_zady",
    "Zády a rukou: Sedíš zády a jeho ruka ti sahá zezadu dopředu. Cíl: obojí najednou.|300|ona_nahore_zady",
    "Dřepni si na něj a pohybuj se nahoru a dolů.|240|drep",
    "V dřepu nad ním se drž jeho rukou, ať máš oporu.|240|drep",
    "Dřep a pauza: V dřepu uděláš deset pohybů a pak na deset vteřin zůstaneš dole. Pětkrát. Cíl: pět kol.|300|drep",
    "Sedni si na něj a celou minutu se vůbec nehýbej.|60|ona_nahore",
    "Sedni si na něj a dej si ruce za záda, ať ti je drží.|240|ona_nahore",
    "Sedni si na něj a nech se držet pod zadečkem a zvedat.|240|ona_nahore",
    "Sedni si mu obkročmo na klín a ať se posadí taky. Objímejte se.|240|klin_celem",
    "Vsedě proti sobě: Sedíte oba, ty na něm, nohy propletené. Hýbat se dá jen málo, o to víc to je. Cíl: vydržet v objetí.|300|klin_celem",
    "Sedni si na něj a pomalu se klaň dozadu.|240|ona_nahore",
    "Sedni si na něj a nech se držet za vlasy stažené do jeho ruky.|240|ona_nahore",
    "Sedni si na něj a přilož si vibrátor zepředu.|300|ona_nahore",
    "Sedni si na něj a nech si zakrýt oči jeho dlaní.|240|ona_nahore",
    "Sto pohybů shora: Uděláš přesně sto pohybů. On jen leží a počítá nahlas. Cíl: dojít do sta.|300|ona_nahore",
    "Sedni si na něj zády a nech si držet kotníky.|240|ona_nahore_zady",
    "Zvedni si jednu nohu na postel, ať má zezadu jiný úhel.|240|zezadu",
    "Nech se zezadu držet za obě ramena a přitahovat na něj.|240|zezadu",
    "Klekni si a nech ho zůstat stát. Rozdíl výšek to změní.|240|zezadu",
    "Nech se zezadu obejmout kolem pasu a držet těsně u něj.|240|zezadu_vzpr",
    "Dej si jeho ruku na břicho a přitáhni si ho k sobě.|240|zezadu_vzpr",
    "Zezadu a šeptem: Klečíte oba, on za tebou, a celou dobu ti šeptá do ucha, co dělá. Cíl: ať nepřestane mluvit.|300|zezadu_vzpr!",
    "Sedni si na něj a pohybuj se jen tehdy, když on vydechne.|300|ona_nahore",
    "Sedni si na něj a drž se čela postele.|240|ona_nahore",
    "Sedni si na něj a nech si hladit stehna a boky.|240|ona_nahore",
    "Střídejte se: minutu ty nahoře, minutu on zezadu. Bez přerušení.|300|zezadu",
    "Tři polohy za sebou: Zezadu, pak ty nahoře, pak misionář. Přechody bez vyjití. Cíl: všechny tři plynule.|300|zezadu!",
    "Nech si položit ruce na lopatky a jemně zatlačit dolů.|240|zezadu",
    "Klečíš a on je za tebou úplně pomalu.|300|zezadu",
    "Dej si jeho ruku zepředu na prsa a nech se přitáhnout.|240|zezadu_vzpr",
    "Klekni si k němu bokem a nech ho vnikat ze strany.|240|zezadu",
    "Nech si od něj držet oba kotníky a řídit šířku tvých nohou.|240|na_brise",
    "Na břiše si nech držet zápěstí nad hlavou.|240|na_brise!",
    "Zadeček nahoru: Lež na hrudníku a zvedni zadeček co nejvýš. On je nad tebou. Cíl: vydržet ten úhel.|240|na_brise",
    "Sedni si na něj čelem a líbejte se u toho.|240|ona_nahore",
    "Sedni si na něj a nech si sevřít boky mezi jeho dlaněmi.|240|ona_nahore",
    "Sedni si na něj a dej si jeho ruce na krk a na prsa.|240|ona_nahore",
    "Sedni si na něj a nech se mezi tím lehce plácnout po zadečku.|240|ona_nahore",
    "Dvojí kontrola: Minutu řídíš ty, minutu on, a tak dokola. Cíl: pět výměn bez přerušení.|300|ona_nahore",
    "Sedni si na něj a při každém sestupu se zhluboka nadechni.|300|ona_nahore",
    "Nakloň se na něm dopředu a opři se mu o hrudník.|240|ona_nahore",
    "Sedni si na něj s rukama za zády. On tě drží.|240|ona_nahore",
    "Sedni si na něj zády a nakloň se dopředu k jeho kolenům.|240|ona_nahore_zady",
    "Zády a hluboko: Sedíš zády a nakloníš se dopředu. Úhel je úplně jiný. Cíl: najít, kde to sedí nejlíp.|300|ona_nahore_zady",
    "Nech se zezadu chytit pod břichem a zvednout k němu.|240|zezadu",
    "Klečíš a on se pohybuje jen v posledních centimetrech.|300|zezadu",
    "Dej mu zezadu ruku a nech si ji proplést s jeho.|240|zezadu",
    "Klekni si a nech ho kleknout si vzpřímeně za tebe. Ať tě drží za boky.|240|zezadu_vzpr",
    "Zezadu a vibrátor: Klečí za tebou a přikládá ti vibrátor zepředu. Cíl: nepustit ho celou dobu.|300|zezadu!",
    "Sedni si na něj a nech ho jen se dívat, jak se snažíš.|300|ona_nahore",
    "Na konci si na něj sedni a jen se objímejte.|120|klin_celem",
  ],
});
