// Kategorie 4 – Sex a polohy (dávka b)
// Témata: vleže čelem k sobě, misionář a jeho varianty, nohy nahoru, na boku a lžička.
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 4,

  male: [
    "Misionář naplno: Lehni si na ni, opři se o lokty a přirážej pomalu a hluboko. Obličej máte u sebe. Cíl: ani jednou nezrychlit.|240|misionar",
    "V misionáři jí dej ruce nad hlavu a propleť si s ní prsty.|240|misionar",
    "Miluj se s ní v misionáři, ale nesmíš se od ní odtrhnout pohledem.|240|misionar",
    "Polož jí pod boky polštář a vnikej do ní shora. Úhel se úplně změní.|240|misionar_polstar",
    "S polštářem pod jejími boky přirážej krátce a rychle.|180|misionar_polstar",
    "Dej si její nohy na ramena a jeď pomalu a hluboko.|240|nohy_ramena",
    "Nohy na ramenou, ruce na jejích bocích. Tempo určuješ ty.|240|nohy_ramena",
    "Hluboko a pomalu: Nohy má na tvých ramenou. Uděláš deset úplně pomalých pohybů a pak minutu nic. Cíl: tři taková kola.|300|nohy_ramena",
    "Dej si jednu její nohu na rameno a druhou nech dole. Zkus, jaký je rozdíl.|240|nohy_ramena",
    "Miluj se s ní tak, že má kolena přitažená k hrudníku.|240|nohy_ramena",
    "Zůstaň v ní úplně bez pohybu a jen ji líbej. Minutu.|60|misionar",
    "Propleť si s ní nohy tak, abyste byli co nejblíž, a hýbej se jen boky.|240|propletene",
    "Celý na ní: Lehni si na ni celou vahou a pohybuj se jen pánví. Žádné velké přírazy. Cíl: dojít bez jediného velkého pohybu.|300|propletene",
    "Miluj se s ní tak, že se opíráš o natažené paže a díváš se na ni shora.|240|misionar",
    "Vnikej do ní jen napůl a pokaždé se zase stáhni.|180|misionar",
    "Dělej deset pomalých a deset rychlých pohybů. Ona počítá nahlas.|240|misionar",
    "Miluj se s ní na boku čelem k sobě a drž ji za stehno.|240|lzicka",
    "Lehni si za ni na lžičku, zvedni jí horní nohu a vnikni do ní zezadu.|240|lzicka",
    "Lžička naplno: Na lžičku a rukou jí zepředu dráždi klitoris. Nesmíš zrychlit. Cíl: dovést ji tam pomalu.|300|lzicka",
    "Na lžičku a líbej ji přitom na rameno a krk.|240|lzicka",
    "Na boku jí propleť nohy se svýma a hýbej se jen málo.|240|lzicka",
    "Na boku ji drž kolem pasu a šeptej jí do ucha.|240|lzicka",
    "Miluj se s ní na boku a jednou rukou jí drž ruku nad hlavou.|240|lzicka",
    "Na lžičku pomalu a mezi tím jí hlaď prsa.|300|lzicka",
    "Dva na boku: Na boku vydržte pět minut a ani jeden nesmí změnit polohu. Cíl: pět minut bez pohnutí jinam.|300|lzicka",
    "Lehni si na ni a nech ji, ať tě obejme nohama kolem pasu.|240|propletene",
    "V misionáři jí podlož boky rukama a zvedni ji k sobě.|240|misionar",
    "Vnikej do ní a mezi tím jí líbej krk. Pořád dokola.|240|misionar",
    "Miluj se s ní tak, aby měla nohy natažené a stisknuté k sobě.|240|propletene",
    "Nohy k sobě: Ona má nohy úplně u sebe a ty jsi nad nimi. Bude to těsnější. Cíl: vydržet tak celou dobu.|240|propletene",
    "V misionáři se zastav pokaždé, když se blíží, a pokračuj až za deset vteřin.|300|misionar",
    "Miluj se s ní a mezi tím jí drž ruce u těla.|240|misionar",
    "S polštářem pod boky jí dráždi rukou klitoris, zatímco v ní jsi.|300|misionar_polstar",
    "Vnikni do ní a hned se zastav. Ať se pohne ona.|180|misionar",
    "Miluj se s ní tak, že máš kolena pod jejími stehny a zvedáš ji.|240|nohy_ramena",
    "Opři si její kotníky o svá ramena a drž ji za boky oběma rukama.|240|nohy_ramena",
    "Do kříže: Ona leží na zádech, ty na boku napříč přes její nohy. Netradiční, ale funguje. Cíl: najít správný úhel.|240|propletene",
    "Miluj se s ní v misionáři a pokaždé po deseti pohybech ji polib.|240|misionar",
    "V misionáři jí zvedni jednu nohu a drž ji za kotník.|240|nohy_ramena",
    "Vnikej do ní velmi pomalu a poslouchej, jak dýchá.|300|misionar",
    "Lehni si na ni a nehýbej se. Všechnu práci dělá ona boky.|240|propletene",
    "Miluj se s ní na boku a druhou rukou jí drž bradu, ať se dívá.|240|lzicka",
    "Na lžičku a mezi tím jí přiložíš vibrátor zepředu.|300|lzicka",
    "Tři rychlosti: Minutu pomalu, minutu středně, minutu naplno. Bez přerušení. Cíl: nikdy se nevrátit zpět.|180|misionar",
    "V misionáři jí dej ruce pod záda a přitáhni si ji.|240|misionar",
    "Miluj se s ní tak, že má obě nohy položené na tvé hrudi.|240|nohy_ramena",
    "Vnikej do ní a mezi tím jí kousej do ramene.|240|propletene",
    "V misionáři se pohybuj do kruhu, ne dopředu a dozadu.|240|misionar",
    "Kroužení: Místo přírazů se pohybuj pánví do kruhu. Tlak bude pořád na stejném místě. Cíl: vydržet u kroužení celou dobu.|300|misionar",
    "Miluj se s ní s polštářem pod boky a rukama pod jejím zadečkem.|240|misionar_polstar",
    "Dej jí nohy na svoje ramena a nakloň se dopředu, až se skoro složí.|240|nohy_ramena",
    "V misionáři se zastav a nech ji, ať řekne, kdy má pokračovat.|300|misionar",
    "Miluj se s ní na boku tak, že ji držíš za rameno a přitahuješ k sobě.|240|lzicka",
    "Na lžičku jí přitom hlaď břicho a stehna.|300|lzicka",
    "Nech ji ležet na boku a zvedni jí horní nohu ke stropu.|240|lzicka",
    "Nůžky vleže: Ona na boku, ty klečíš mezi jejíma nohama. Hloubka i úhel jsou jiné. Cíl: najít, co jí sedne.|240|lzicka",
    "V misionáři jí zakryj ústa dlaní a sleduj, jak reaguje.|240|misionar",
    "Miluj se s ní a nech ji, ať ti nehty zarývá do zad.|240|misionar",
    "V misionáři jí podlož obě kolena rukama a rozevři je co nejvíc.|240|misionar",
    "Nech ji ležet s rukama nad hlavou. Nesmí je sundat.|240|misionar",
    "Sto pohybů: Uděláš přesně sto pohybů a pak se zastavíš, ať jste kdekoli. Cíl: dojít do sta bez ztráty rytmu.|300|misionar",
    "V misionáři ji drž za zápěstí a vnikej pomalu.|240|misionar",
    "Miluj se s ní tak, že jí jednu nohu položíš přes svoje rameno a druhou kolem pasu.|240|nohy_ramena",
    "S polštářem pod boky přirážej shora dolů. Úhel je pro ni jiný.|240|misionar_polstar",
    "Nech ji, ať si sama nastaví nohy tak, jak jí to nejvíc vyhovuje.|240|misionar",
    "Miluj se s ní a mezi tím jí olizuj bradavky.|240|misionar",
    "Pomalá pětka: Pět minut se smíš hýbat jen tak pomalu, abyste stihli mluvit. Cíl: vydržet mluvit celou dobu.|300|misionar",
    "V misionáři jí drž nohu za lýtko a tlač ji k jejímu rameni.|240|nohy_ramena",
    "Miluj se s ní na boku a druhou rukou si drž její zadeček.|240|lzicka",
    "Na lžičku pomalu a s hodně lubrikantu.|300|lzicka",
    "Nech ji ležet na zádech a ty klečíš mezi jejíma nohama vzpřímeně.|240|misionar",
    "Vzpřímeně nad ní: Klečíš mezi jejíma nohama, držíš ji za boky a zvedáš ji k sobě. Cíl: nést její váhu celou dobu.|240|nohy_ramena",
    "Miluj se s ní tak, že se drží tvých ramen a přitahuje si tě.|240|misionar",
    "V misionáři střídej hluboké a mělké pohyby po pěti.|240|misionar",
    "Nech ji, ať ti nehty jede po zádech pokaždé, když zpomalíš.|240|misionar",
    "Miluj se s ní a mezi tím jí drž obě kolena u jejích ramen.|240|nohy_ramena",
    "Ruce pod ní: Dej jí obě ruce pod zadeček a celou dobu ji drž nahoře. Cíl: nepustit ji.|240|misionar_polstar",
    "Lehni si na ni a nech ji, ať ti šeptá do ucha, co má být dál.|300|propletene",
    "V misionáři vydrž bez pohybu pokaždé, když vydechne.|240|misionar",
    "Miluj se s ní na boku a nech ji, ať si sama drží nohu.|240|lzicka",
    "Nech ji ležet a ty jsi nad ní. Ale hýbat se smí jen ona.|240|misionar",
    "Dvě polohy: Začni v misionáři a po dvou minutách přejdi na lžičku, aniž bys z ní vyšel. Cíl: přechod bez přerušení.|300|lzicka",
    "V misionáři jí sundej polštář zpod hlavy a dej jí ho pod boky.|240|misionar_polstar",
    "Nakonec zůstaň v ní a jen se líbejte, dokud se nezklidníte.|120|propletene",
  ],

  female: [
    "Misionář naplno: Nech ho na sebe lehnout, obejmi ho nohama a tempo mu urči rukama na bocích. Cíl: ani jednou nezrychlit.|240|misionar",
    "V misionáři si dej ruce nad hlavu a nech si od něj proplést prsty.|240|misionar",
    "Nech ho být nahoře, ale nesmíš se od něj odtrhnout pohledem.|240|misionar",
    "Podlož si pod boky polštář a nech ho vniknout shora. Úhel se úplně změní.|240|misionar_polstar",
    "S polštářem pod boky ho popros o krátké a rychlé přírazy.|180|misionar_polstar",
    "Dej si nohy na jeho ramena a nech ho jít pomalu a hluboko.|240|nohy_ramena",
    "Nohy na jeho ramenou, jeho ruce na tvých bocích. Tempo určuje on.|240|nohy_ramena",
    "Hluboko a pomalu: Máš nohy na jeho ramenou. Deset úplně pomalých pohybů a pak minutu nic. Cíl: tři taková kola.|300|nohy_ramena",
    "Dej si jednu nohu na jeho rameno a druhou nech dole. Zkus, jaký je rozdíl.|240|nohy_ramena",
    "Přitáhni si kolena k hrudníku a nech ho, ať se do tebe opře.|240|nohy_ramena",
    "Ať v tobě zůstane úplně bez pohybu a jen tě líbá. Minutu.|60|misionar",
    "Propleť si s ním nohy tak, abyste byli co nejblíž, a hýbej se jen boky.|240|propletene",
    "Celý na tobě: Nech ho lehnout si na tebe celou vahou a hýbat se jen pánví. Cíl: dojít bez jediného velkého pohybu.|300|propletene",
    "Nech ho opřít se o natažené paže, ať se na tebe dívá shora.|240|misionar",
    "Nech ho vnikat jen napůl a pokaždé se zase stáhnout.|180|misionar",
    "Řekni mu, ať udělá deset pomalých a deset rychlých pohybů. Ty počítáš nahlas.|240|misionar",
    "Miluj se s ním na boku čelem k sobě a drž se ho za rameno.|240|lzicka",
    "Lehni si před něj na lžičku, zvedni horní nohu a nech ho vniknout zezadu.|240|lzicka",
    "Lžička naplno: Na lžičku a jeho ruku si dej zepředu na klitoris. Nesmí zrychlit. Cíl: nechat se dovést pomalu.|300|lzicka",
    "Na lžičku a nech se líbat na rameno a krk.|240|lzicka",
    "Na boku si propleť nohy s jeho a hýbejte se jen málo.|240|lzicka",
    "Na boku se o něj opři zády a nech si šeptat do ucha.|240|lzicka",
    "Miluj se s ním na boku a nech si držet ruku nad hlavou.|240|lzicka",
    "Na lžičku pomalu a nech si hladit prsa.|300|lzicka",
    "Pět minut na boku: Zůstaňte na boku celých pět minut a ani jeden se nepřesune jinam. Cíl: nezměnit polohu.|300|lzicka",
    "Nech ho lehnout si na tebe a obejmi ho nohama kolem pasu.|240|propletene",
    "Nech si od něj podložit boky rukama a zvednout k sobě.|240|misionar",
    "Nech ho vnikat a mezi tím si říkej o polibky na krk.|240|misionar",
    "Natáhni nohy a stiskni je k sobě, zatímco je v tobě.|240|propletene",
    "Nohy k sobě: Nohy měj úplně u sebe a on je nad nimi. Bude to těsnější. Cíl: vydržet tak celou dobu.|240|propletene",
    "Nech ho zastavit se pokaždé, když se blížíš, a pokračovat až za deset vteřin.|300|misionar",
    "Nech si od něj držet ruce u těla, ať se nemůžeš hýbat.|240|misionar",
    "S polštářem pod boky si sama dráždi klitoris, zatímco je v tobě.|300|misionar_polstar",
    "Nech ho vniknout a hned se zastavit. Pohyb uděláš ty.|180|misionar",
    "Nech ho kleknout si pod tvoje stehna a zvednout tě.|240|nohy_ramena",
    "Opři si kotníky o jeho ramena a nech se držet za boky.|240|nohy_ramena",
    "Do kříže: Ty ležíš na zádech, on na boku napříč přes tvoje nohy. Netradiční, ale funguje. Cíl: najít správný úhel.|240|propletene",
    "V misionáři ho po každých deseti pohybech polib.|240|misionar",
    "Zvedni jednu nohu a nech si ji od něj podržet za kotník.|240|nohy_ramena",
    "Nech ho vnikat velmi pomalu a poslouchej, jak dýchá.|300|misionar",
    "Nech ho lehnout si na tebe bez pohybu. Všechnu práci děláš ty boky.|240|propletene",
    "Miluj se s ním na boku a nech si držet bradu, ať se musíš dívat.|240|lzicka",
    "Na lžičku a přilož si vibrátor zepředu sama.|300|lzicka",
    "Tři stupně: Nejdřív minutu pomalu, pak minutu středně a nakonec minutu naplno. Cíl: nikdy se nevrátit zpět.|180|misionar",
    "Dej si ruce pod záda a nech ho, ať si tě přitáhne.|240|misionar",
    "Polož si obě nohy na jeho hrudník a odtlačuj se.|240|nohy_ramena",
    "Nech ho vnikat a kousej ho přitom do ramene.|240|propletene",
    "Řekni mu, ať se místo přírazů pohybuje do kruhu.|240|misionar",
    "Kroužení: Ať se pohybuje pánví do kruhu, ne dopředu a dozadu. Tlak zůstane na jednom místě. Cíl: vydržet u kroužení.|300|misionar",
    "S polštářem pod boky si dej jeho ruce pod zadeček.|240|misionar_polstar",
    "Dej si nohy na jeho ramena a nech ho naklonit se dopředu, až se skoro složíš.|240|nohy_ramena",
    "Zastav ho a nech ho čekat, dokud sama neřekneš pokračuj.|300|misionar",
    "Miluj se s ním na boku a nech se přitahovat za rameno.|240|lzicka",
    "Na lžičku si nech hladit břicho a stehna.|300|lzicka",
    "Lehni si na bok a zvedni horní nohu ke stropu.|240|lzicka",
    "Nůžky vleže: Ty na boku, on klečí mezi tvýma nohama. Hloubka i úhel jsou jiné. Cíl: najít, co ti sedne.|240|lzicka",
    "Nech si od něj zakrýt ústa dlaní a zkus být potichu.|240|misionar",
    "Zarývej mu nehty do zad pokaždé, když zrychlí.|240|misionar",
    "Nech si podložit obě kolena a rozevřít je co nejvíc.|240|misionar",
    "Dej si ruce nad hlavu a nesmíš je sundat.|240|misionar",
    "Sto pohybů: Napočítáte přesně sto pohybů a pak se zastavíte, ať jste kdekoli. Cíl: dojít do sta bez ztráty rytmu.|300|misionar",
    "Nech si držet zápěstí a užívej si, že nemáš kontrolu.|240|misionar",
    "Dej si jednu nohu přes jeho rameno a druhou kolem jeho pasu.|240|nohy_ramena",
    "S polštářem pod boky ho nech přirážet shora dolů. Úhel je jiný.|240|misionar_polstar",
    "Nastav si nohy přesně tak, jak ti to nejvíc vyhovuje, a řekni mu to.|240|misionar",
    "Nech se milovat a mezi tím si říkej o olizování bradavek.|240|misionar",
    "Pomalá pětka: Pět minut se smíte hýbat jen tak pomalu, abyste stihli mluvit. Cíl: vydržet mluvit celou dobu.|300|misionar",
    "Nech si od něj přitlačit nohu za lýtko k rameni.|240|nohy_ramena",
    "Miluj se s ním na boku a nech si držet zadeček.|240|lzicka",
    "Na lžičku a hodně pomalu, s dostatkem lubrikantu.|300|lzicka",
    "Nech ho kleknout si mezi tvoje nohy vzpřímeně a opři se o lokty.|240|misionar",
    "Vzpřímeně nad tebou: Klečí mezi tvýma nohama, drží tě za boky a zvedá k sobě. Cíl: nechat ho nést tvoji váhu.|240|nohy_ramena",
    "Chytni se jeho ramen a přitahuj si ho k sobě.|240|misionar",
    "Řekni mu, ať střídá pět hlubokých a pět mělkých pohybů.|240|misionar",
    "Jeď mu nehty po zádech pokaždé, když zpomalí.|240|misionar",
    "Nech si od něj přitlačit obě kolena k ramenům.|240|nohy_ramena",
    "Ruce pod tebou: Ať ti dá obě ruce pod zadeček a celou dobu tě drží nahoře. Cíl: ať tě nepustí.|240|misionar_polstar",
    "Nech ho lehnout si na tebe a šeptej mu do ucha, co má být dál.|300|propletene",
    "Řekni mu, ať se zastaví pokaždé, když vydechneš.|240|misionar",
    "Miluj se s ním na boku a drž si nohu sama.|240|lzicka",
    "Nech ho být nad tebou, ale hýbat se smíš jen ty.|240|misionar",
    "Dvě polohy: Začněte v misionáři a po dvou minutách přejděte na lžičku, aniž by z tebe vyšel. Cíl: přechod bez přerušení.|300|lzicka",
    "Vyndej si polštář zpod hlavy a dej si ho pod boky.|240|misionar_polstar",
    "Nakonec ho v sobě nech a jen se líbejte, dokud se nezklidníte.|120|propletene",
  ],
});
