// Kategorie 4 – Sex a polohy (dávka e)
// Témata: tempo jako hra, pravidla a zákazy, pomůcky při sexu, orgasmus jako výzva.
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 4,

  male: [
    "Deset a deset: Deset pomalých pohybů, deset rychlých, pořád dokola. Ona počítá. Cíl: pět celých kol.|300|misionar",
    "Pohybuj se jen tehdy, když se ona nadechne. Při výdechu stůj.|300|misionar",
    "Zastav se pokaždé, když řekne tvoje jméno.|300|ona_nahore",
    "Tempo si určuje ona tleskáním. Ty musíš držet krok.|300|ona_nahore",
    "Stop a start: Ona říká stop a start, kdy chce. Ty se řídíš na vteřinu přesně. Cíl: ani jedno zpoždění.|300|zezadu",
    "Jeď co nejpomaleji, dokud tě sama nepoprosí o rychleji.|300|misionar",
    "Pět pomalých a jeden rychlý. Pořád dokola.|300|zezadu",
    "Každou minutu zrychli o stupeň. Začni úplně pomalu.|300|misionar",
    "Hýbej se jen v posledních pár centimetrech. Nikdy hluboko.|300|zezadu",
    "Naopak: Jdi vždycky jen hodně hluboko a nikdy mělce. Cíl: udržet hloubku celou dobu.|300|misionar",
    "Miluj se s ní, ale nesmíš se dotknout rukama ničeho kromě postele.|240|misionar",
    "Bez rukou: Ruce máš celou dobu opřené vedle ní a nesmíš se jí dotknout. Cíl: dokázat to.|240|misionar",
    "Ani jeden z vás nesmí zavřít oči. Kdo zavře, prohrál.|300|klin_celem",
    "Ona nesmí vydat ani hlásku. Ty děláš všechno pro to, aby to nevydržela.|300|zezadu",
    "Ticho a tma: Zhasněte a nikdo z vás nesmí promluvit. Jen dech. Cíl: dorozumět se beze slov.|300|misionar",
    "Ona musí nahlas říkat, co chce. Když ztichne, přestaneš.|300|ona_nahore",
    "Ty musíš celou dobu popisovat, co děláš. Ani na chvíli neztichni.|300|zezadu",
    "Ona nesmí použít ruce k ničemu. Ani se držet.|300|misionar",
    "Pravidlo pohledu: Nesmíte se přestat dívat do očí. Když jeden uhne, měníte polohu. Cíl: vydržet v jedné.|300|klin_celem",
    "Nech ji si nasadit ti erekční kroužek a pak se s ní miluj.|300|misionar",
    "S kroužkem jeď hodně pomalu a dlouho.|300|ona_nahore",
    "Vezmi vibrátor a drž jí ho na klitorisu, zatímco jsi v ní.|300|misionar",
    "Vibrátor při sexu: Ona si drží vibrátor sama a ty se jen hýbeš. Cíl: nechat to na ní.|300|ona_nahore",
    "Přilož jí vibrátor zezadu, zatímco do ní vnikáš zepředu.|300|misionar",
    "Sváž jí ruce kravatou nad hlavou a pak se s ní miluj.|300|pouta_postel",
    "Sváž jí ruce za zády a vezmi ji zezadu.|300|zezadu",
    "S kravatou: Zavaž jí oči kravatou a miluj se s ní. Ona nesmí vědět, co přijde. Cíl: překvapit ji třikrát.|300|misionar",
    "Zavaž jí oči a změň polohu, aniž bys řekl slovo.|300|zezadu",
    "Plácni ji po zadečku vždycky po patnácti pohybech.|300|zezadu",
    "Tahej ji jemně za vlasy a sleduj, jak reaguje.|300|zezadu",
    "Dej jí ruku na krk. Jen položit, žádný tlak.|300|misionar",
    "Kousni ji do ramene ve chvíli, kdy je nejblíž.|300|lzicka",
    "Deset plácnutí: Během úkolu ji desetkrát plácneš, pokaždé jinak silně. Ona počítá. Cíl: dojít do deseti.|300|zezadu",
    "Nech ji dojít první a teprve pak se starej o sebe.|300|ona_nahore",
    "Zkuste se udělat oba ve stejnou chvíli.|300|misionar",
    "Společně: Snažte se dojít naráz. Když se to nepovede, zkusíte to znovu. Cíl: trefit to na první pokus.|300|klin_celem",
    "Nech ji dojít dvakrát, než se uděláš ty.|300|ona_nahore",
    "Doveď ji na hranu a pak zpomal. Třikrát.|300|misionar",
    "Edging při sexu: Kdykoli je blízko, úplně se zastavíš. Pětkrát. Cíl: vydržet všech pět.|300|zezadu",
    "Zakaž jí dojít, dokud nedopočítá do sta.|300|ona_nahore",
    "Ona nesmí dojít, dokud neřekne nahlas, co přesně chce.|300|misionar",
    "Miluj se s ní a mezi tím jí drž ruce nad hlavou jednou rukou.|300|misionar",
    "Nech ji vybrat polohu, tempo a jak dlouho. Ty jen plníš.|300|ona_nahore",
    "Její hra: Celou dobu rozhoduje ona o všem. Ty neřekneš ani slovo. Cíl: nepřevzít vedení.|300|ona_nahore",
    "Rozhodni ty všechno a ona jen poslouchá.|300|zezadu",
    "Po každé minutě se prohodíte v tom, kdo rozhoduje.|300|klin_celem",
    "Miluj se s ní a mezi tím jí přejížděj ledem po zádech.|300|zezadu",
    "Led při sexu: Kostka ledu na jejích zádech, zatímco jsi v ní. Cíl: nenechat ji spadnout.|300|na_brise",
    "Miluj se s ní a mezi tím jí přejeď pírkem po prsou.|300|misionar",
    "Dej jí sluchátka s hudbou, ať tě neslyší, a miluj se s ní.|300|zezadu",
    "Miluj se s ní před zrcadlem, ať se oba vidíte.|300|zezadu",
    "Natoč si na telefon jen zvuk a pak si to spolu poslechněte.|300|misionar",
    "Miluj se s ní a přitom jí do ucha popisuj svoji fantazii.|300|lzicka",
    "Scénka: Vyberte si roli a celou dobu v ní zůstaňte, i když to bude k smíchu. Cíl: nevypadnout z role.|300|zezadu",
    "Miluj se s ní a mezi tím se oba musíte smát. Aspoň jednou.|240|klin_celem",
    "Vydrž pět minut, aniž bys změnil polohu i tempo.|300|misionar",
    "Změň polohu pokaždé, když zazvoní budík na minutu.|300|zezadu",
    "Pět minut, pět poloh: Každou minutu jiná poloha, žádná dvakrát. Cíl: pět různých poloh.|300|zezadu",
    "Miluj se s ní a nech ji, ať ti nehty zarývá do zad, když je blízko.|300|misionar",
    "Miluj se s ní tak dlouho, dokud neřekne dost.|300|zezadu",
    "Miluj se s ní a mezi tím jí olizuj krk a rameno.|300|lzicka",
    "Nech ji, ať si vybere, čím to skončí – tebou, rukou, nebo vibrátorem.|300|ona_nahore",
    "Před koncem: Poslední minutu už nesmíš nic měnit. Žádná nová poloha, žádné nové tempo. Cíl: dojet to, jak to je.|60|misionar",
    "Miluj se s ní a nech ji říkat čísla od desíti dolů. Na nule končíte.|300|ona_nahore",
    "Dej jí do ruky vibrátor a řekni, že ho může použít, kdy chce.|300|misionar",
    "Nasaď si kroužek a nech ji rozhodnout, jak dlouho to bude trvat.|300|ona_nahore",
    "Miluj se s ní a mezi tím jí drž obě ruce za zády.|300|zezadu",
    "Sváž jí kravatou jednu ruku k posteli a druhou nech volnou.|300|pouta_postel",
    "Poslušnost: Dáš jí tři příkazy během úkolu a ona je musí splnit hned. Cíl: ani jedno zaváhání.|300|zezadu",
    "Miluj se s ní a mezi tím jí jemně kousni do zadečku.|300|na_brise",
    "Nech ji, ať si sedne na tebe a řekne ti, kdy smíš dojít.|300|ona_nahore",
    "Miluj se s ní a nech ji říkat po každé minutě, co má být jinak.|300|misionar",
    "Zkus to celé bez jediného polibku. Uvidíš, jak bude chybět.|300|zezadu",
    "Naopak se celou dobu líbejte a nepřestaňte.|300|klin_celem",
    "Nepřerušený polibek: Celý úkol se musíte líbat. Když polibek přerušíte, začínáte znovu. Cíl: vydržet.|300|klin_celem",
    "Miluj se s ní a mezi tím jí hlaď prsa oběma rukama.|300|zezadu_vzpr",
    "Nech ji na sobě sedět a jen ji držet. Ať se hýbe sama.|300|ona_nahore",
    "Miluj se s ní tak, aby to bylo co nejtišší. Ani postel nesmí vrzat.|300|misionar",
    "Naopak buďte co nejhlasitější. Ať to není k vydržení.|300|zezadu",
    "Souboj o kontrolu: Oba se snažíte určovat tempo. Kdo se první podvolí, splní přání. Cíl: nevzdat to.|300|klin_celem",
    "Miluj se s ní a mezi tím jí šeptej, jak blízko jsi.|300|lzicka",
    "Nech ji, ať ti řekne, kdy má být konec, a ty to dodrž na vteřinu.|300|ona_nahore",
    "Na konci v ní zůstaň a jen ji drž, dokud se oba nezklidníte.|120|propletene",
  ],

  female: [
    "Deset a deset: Deset pomalých pohybů, deset rychlých, pořád dokola. On počítá. Cíl: pět celých kol.|300|ona_nahore",
    "Hýbej se jen tehdy, když se on nadechne. Při výdechu stůj.|300|ona_nahore",
    "Jakmile vysloví tvoje jméno, okamžitě se zastav a počkej.|300|ona_nahore",
    "Tempo si určuje on tleskáním. Ty musíš držet krok.|300|ona_nahore",
    "Stop a start: On říká stop a start, kdy chce. Ty se řídíš na vteřinu přesně. Cíl: ani jedno zpoždění.|300|ona_nahore",
    "Jeď co nejpomaleji, dokud tě sám nepoprosí o rychleji.|300|ona_nahore",
    "Pět pomalých pohybů a po nich vždycky jeden úplně rychlý.|300|ona_nahore",
    "Začni na nejpomalejším tempu a po každé minutě přidej jeden stupeň.|300|ona_nahore",
    "Zůstávej nahoře a sedej si jen o pár centimetrů. Nikdy až dolů.|300|ona_nahore",
    "Naopak: Sedej si vždycky úplně dolů a nikdy jen mělce. Cíl: udržet hloubku celou dobu.|300|ona_nahore",
    "Miluj se s ním, ale nesmíš se dotknout rukama ničeho kromě postele.|240|ona_nahore",
    "Bez rukou: Ruce máš celou dobu opřené vedle něj a nesmíš se ho dotknout. Cíl: dokázat to.|240|ona_nahore",
    "Nikdo z vás nesmí zavřít oči – kdo je zavře první, plní přání.|300|klin_celem",
    "On nesmí vydat ani hlásku. Ty děláš všechno pro to, aby to nevydržel.|300|ona_nahore",
    "Potmě a beze slov: Zhasněte a celou dobu mlčte, zbude vám jen dech a doteky. Cíl: dorozumět se bez mluvení.|300|misionar",
    "On musí nahlas říkat, co chce. Když ztichne, přestaneš.|300|ona_nahore",
    "Nahlas popisuj každý svůj pohyb a ani na chvíli se neodmlč.|300|ona_nahore",
    "On nesmí použít ruce k ničemu. Ani se držet.|300|ona_nahore",
    "Z očí do očí: Dokud se díváte, zůstáváte v poloze. Jakmile jeden uhne, měníte ji. Cíl: nezměnit ji ani jednou.|300|klin_celem",
    "Nasaď mu erekční kroužek a pak si na něj sedni.|300|ona_nahore",
    "S kroužkem jeďte hodně pomalu a dlouho.|300|ona_nahore",
    "Vezmi vibrátor a drž si ho na klitorisu, zatímco je v tobě.|300|ona_nahore",
    "Vibrátor při sexu: Držíš si vibrátor sama a on se jen hýbe. Cíl: mít to ve svých rukou.|300|misionar",
    "Nech si přiložit vibrátor zezadu, zatímco do tebe vniká zepředu.|300|misionar",
    "Sváž mu ruce kravatou nad hlavou a pak si na něj sedni.|300|pouta_postel",
    "Sváž mu ruce za zády a nech ho klečet za tebou.|300|zezadu",
    "S kravatou: Zavaž mu oči kravatou a miluj se s ním. Nesmí vědět, co přijde. Cíl: překvapit ho třikrát.|300|ona_nahore",
    "Zavaž si oči a nech ho změnit polohu beze slova.|300|zezadu",
    "Řekni mu, ať tě plácne po zadečku vždycky po patnácti pohybech.|300|zezadu",
    "Nech se jemně tahat za vlasy a řekni mu, jestli se ti to líbí.|300|zezadu",
    "Dej si jeho ruku na krk. Jen položit, žádný tlak.|300|misionar",
    "Kousni ho do ramene ve chvíli, kdy je nejblíž.|300|klin_celem",
    "Deset plácnutí: Během úkolu tě desetkrát plácne, pokaždé jinak silně. Ty počítáš. Cíl: dojít do deseti.|300|zezadu",
    "Nech ho dojít první a teprve pak se postarej o sebe.|300|ona_nahore",
    "Zkuste to načasovat tak, abyste se udělali ve stejnou vteřinu.|300|misionar",
    "Naráz: Cílem je dojít oba zároveň, a když to nevyjde, zkusíte to ještě jednou. Cíl: trefit se napoprvé.|300|klin_celem",
    "Doveď ho na hranu a pak zpomal. Třikrát.|300|ona_nahore",
    "Nech ho dojít až potom, co dojdeš ty.|300|ona_nahore",
    "Pět zastavení: Pokaždé, když je těsně před koncem, se úplně zastav. Cíl: zvládnout všech pět.|300|ona_nahore",
    "Zakaž mu se udělat, dokud nedopočítáš do sta.|300|ona_nahore",
    "On se nesmí udělat, dokud neřekne nahlas, co přesně chce.|300|ona_nahore",
    "Sedni si na něj a nech si držet ruce nad hlavou jednou rukou.|300|misionar",
    "Nech ho vybrat polohu, tempo a jak dlouho. Ty jen plníš.|300|zezadu",
    "Jeho hra: Celou dobu rozhoduje on o všem. Ty neřekneš ani slovo. Cíl: nepřevzít vedení.|300|zezadu",
    "Rozhodni ty všechno a on jen poslouchá.|300|ona_nahore",
    "Každou minutu si vyměňte, kdo z vás dvou velí.|300|klin_celem",
    "Miluj se s ním a mezi tím mu přejížděj ledem po zádech.|300|propletene",
    "Led při sexu: Kostka ledu na jeho zádech, zatímco je v tobě. Cíl: nenechat ji spadnout.|300|propletene",
    "Miluj se s ním a mezi tím mu přejeď pírkem po hrudníku.|300|ona_nahore",
    "Dej mu sluchátka s hudbou, ať tě neslyší, a sedni si na něj.|300|ona_nahore",
    "Miluj se s ním před zrcadlem, ať se oba vidíte.|300|zezadu",
    "Natočte si na telefon jen zvuk a pak si to spolu poslechněte.|300|ona_nahore",
    "Miluj se s ním a přitom mu do ucha popisuj svoji fantazii.|300|lzicka",
    "Role: Každý si vybere postavu a zůstane v ní až do konce, i kdyby to bylo k popukání. Cíl: nevypadnout z ní.|300|zezadu",
    "Miluj se s ním a mezi tím se oba musíte zasmát. Aspoň jednou.|240|klin_celem",
    "Vydržte pět minut, aniž byste změnili polohu i tempo.|300|ona_nahore",
    "Změňte polohu pokaždé, když zazvoní budík na minutu.|300|zezadu",
    "Minuta na polohu: Po každé minutě měníte polohu a žádná se nesmí opakovat. Cíl: pět různých.|300|zezadu",
    "Zarývej mu nehty do zad, když jsi blízko.|300|misionar",
    "Miluj se s ním tak dlouho, dokud neřekne dost.|300|ona_nahore",
    "Miluj se s ním a mezi tím mu olizuj krk a rameno.|300|klin_celem",
    "Nech ho, ať si vybere, čím to skončí – tebou, rukou, nebo ústy.|300|ona_nahore",
    "Před koncem: Poslední minutu už nesmíte nic měnit. Žádná nová poloha, žádné nové tempo. Cíl: dojet to, jak to je.|60|ona_nahore",
    "Miluj se s ním a nech ho říkat čísla od desíti dolů. Na nule končíte.|300|ona_nahore",
    "Vezmi si vibrátor a řekni mu, že ho použiješ, kdy budeš chtít.|300|ona_nahore",
    "Nasaď mu kroužek a rozhodni sama, jak dlouho to bude trvat.|300|ona_nahore",
    "Dej mu ruce za záda a drž mu je, zatímco na něm sedíš.|300|ona_nahore",
    "Sváž mu kravatou jednu ruku k posteli a druhou nech volnou.|300|pouta_postel",
    "Poslušnost: Dáš mu tři příkazy během úkolu a on je musí splnit hned. Cíl: ani jedno zaváhání.|300|ona_nahore",
    "Miluj se s ním a mezi tím ho jemně kousni do zadku.|300|propletene",
    "Sedni si na něj a řekni mu, kdy se smí udělat.|300|ona_nahore",
    "Miluj se s ním a po každé minutě mu řekni, co má být jinak.|300|misionar",
    "Zkuste to celé bez jediného polibku. Uvidíš, jak bude chybět.|300|zezadu",
    "Tentokrát naopak: pusa na puse celou dobu, bez jediného přerušení.|300|klin_celem",
    "Jeden dlouhý polibek: Nesmíte se od sebe odtrhnout, jinak začínáte znovu od začátku. Cíl: vydržet do konce.|300|klin_celem",
    "Nech si zezadu hladit prsa oběma rukama.|300|zezadu_vzpr",
    "Sedni si na něj a nech ho jen držet. Hýbáš se jen ty.|300|ona_nahore",
    "Miluj se s ním tak, aby to bylo co nejtišší. Ani postel nesmí vrzat.|300|ona_nahore",
    "A teď obráceně – buďte tak hlasití, jak jen dokážete.|300|zezadu",
    "Přetahovaná: Každý si tahá tempo na svou stranu a kdo první povolí, plní přání toho druhého. Cíl: nevzdat to.|300|klin_celem",
    "Miluj se s ním a mezi tím mu šeptej, jak blízko jsi.|300|lzicka",
    "Nech ho, ať ti řekne, kdy má být konec, a ty to dodrž na vteřinu.|300|ona_nahore",
    "Na konci na něm zůstaň a jen ho drž, dokud se oba nezklidníte.|120|propletene",
  ],
});
