// Kategorie 4 – Sex a polohy (dávka c)
// Témata: zezadu ve všech variantách a ona nahoře čelem, zády, v dřepu.
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 4,

  male: [
    "Na všech čtyřech: Nech ji kleknout si na všechny čtyři, vnikni do ní zezadu a drž ji za boky. Cíl: čtyři minuty a ani jednou ji nepustit.|240|zezadu",
    "Zezadu a pomalu: Ona klečí, ty jsi za ní. Deset přírazů pomalu, pak deset naplno. Cíl: čtyři taková kola a ani jednou se nesplést.|300|zezadu",
    "Ruka mezi lopatkami: Miluj ji zezadu a polož jí ruku mezi lopatky, jemně ji tlač do podložky. Cíl: čtyři minuty a kdykoli řekne stop, ruku sundat.|240|zezadu",
    "Na loktech se zvednutým zadečkem: Nech ji opřít se o lokty a zvednout zadeček, drž ji za boky a přirážej. Cíl: čtyři minuty a nesmí se sesunout.|240|zezadu",
    "Ruka dopředu: Miluj ji zezadu a jednou rukou jí zepředu dráždi klitoris. Cíl: pět minut a obojí ve stejném rytmu.|300|zezadu",
    "Za ramena: Chyť ji zezadu za ramena a při každém přírazu si ji přitáhni. Cíl: čtyřicet přírazů a u každého jedno přitažení.|240|zezadu",
    "Polštář pod břichem: Nech ji ležet na břiše s polštářem pod boky a vnikni do ní shora. Cíl: čtyři minuty a polštář nenechat vyklouznout.|240|na_brise",
    "Na břiše a hluboko: Ona leží na břiše s nohama u sebe – je to nejtěsnější poloha, jakou znáte. Cíl: pět minut a ani jeden rychlý příraz.|300|na_brise",
    "Zvednutý bok: Nech ji ležet na břiše, zvedni jí jeden bok a vnikej z boku. Cíl: čtyři minuty a po dvou minutách stranu vyměnit.|240|na_brise",
    "Vzpřímeně a přes prsa: Oba klečíte vzpřímeně, ty jsi za ní a držíš ji přes prsa. Cíl: čtyři minuty a ani jednou ji nepustit.|240|zezadu_vzpr",
    "Rameno a klitoris: Vzpřímeně zezadu jí jednou rukou drž rameno a druhou dráždi klitoris. Cíl: pět minut a ani jednu ruku nesundat.|300|zezadu_vzpr",
    "Vzpřímeně na kolenou: Oba klečíte, ona před tebou. Obejmi ji a pohybuj se jen málo. Cíl: co největší blízkost.|300|zezadu_vzpr",
    "Drží se čela postele: Nech ji klečet a držet se čela postele a miluj ji zezadu. Cíl: čtyři minuty a nesmí se pustit ani jednou.|240|pouta_postel",
    "Ruce dozadu: Miluj ji zezadu, vezmi jí ruce dozadu a drž ji za zápěstí. Cíl: čtyři minuty a na stop ji hned pustit.|240|zezadu",
    "Lehce za vlasy: Miluj ji zezadu a lehce ji tahej za vlasy, jen tolik, aby jí to bylo příjemné. Cíl: deset zatažení a po každém se zeptat.|240|zezadu",
    "Rána po desátém: Miluj ji zezadu a po každých deseti přírazech ji plácni po zadečku. Cíl: čtyřicet přírazů, čtyři rány, síla stejná.|240|zezadu",
    "Čelo na posteli: Nech ji kleknout si a opřít čelo o postel a přirážej hluboko. Cíl: čtyřicet hlubokých přírazů a žádný mělký.|240|zezadu",
    "Zezadu a stop: Zastav se pokaždé, když se blíží, a čekej deset vteřin. Třikrát. Cíl: vydržet všechna tři zastavení.|300|zezadu",
    "Polštář změní úhel: Vsuň jí pod břicho polštář a miluj ji zezadu. Cíl: čtyři minuty a pak se zeptat, jestli je ten úhel lepší.|240|na_brise",
    "Ty stojíš, ona klečí: Nech ji klečet na kraji postele a stoupni si za ni na podlahu. Cíl: čtyři minuty a najít výšku, kde to sedne oběma.|240|zezadu",
    "Dlaň na krku zezadu: Miluj ji zezadu a polož jí ruku na krk – jen položit, nikdy netlačit. Cíl: na stop ruku hned sundat.|240|zezadu",
    "Přiráží ona: Nech ji klečet a sám se vůbec nehýbej. Cíl: pět minut, při kterých všechnu práci dělá ona.|300|zezadu",
    "Rameno a bok: Miluj ji zezadu s jednou rukou na rameni a druhou na boku a veď celé tempo sám. Cíl: čtyři minuty bez jediného zaváhání.|240|zezadu",
    "Ona nahoře: Lehni si na záda a nech ji, ať si na tebe sedne a řídí všechno sama. Cíl: nepohnout se ani jednou.|300|ona_nahore",
    "Ruce v tvých: Nech ji sednout si na tebe čelem a celou dobu jí drž obě ruce. Cíl: čtyři minuty a ani jednou ji nepustit.|240|ona_nahore",
    "Pomáháš jí za boky: Ona je nahoře a ty jí rukama na bocích pomáháš s tempem. Cíl: čtyři minuty a ruce ani jednou nesundat.|240|ona_nahore",
    "Kroužit, ne zvedat: Nech ji na tobě kroužit boky místo zvedání. Cíl: pět minut a ani jednou se nezvednout.|300|ona_nahore",
    "Opřená o tvoje stehna: Nech ji sednout si na tebe a opřít se rukama dozadu o tvoje stehna. Cíl: čtyři minuty a nesmí se předklonit.|240|ona_nahore",
    "Když se skloní: Ona je nahoře a pokaždé, když se skloní, jí olízni bradavku. Cíl: dvacet sklonění a ani jedno nevynechat.|240|ona_nahore",
    "Kroužení shora: Ona na tobě nesmí vůbec zvedat boky, jen kroužit. Cíl: dovést ji tam jen kroužením.|300|ona_nahore",
    "Výhled zezadu: Nech ji sednout si na tebe zády a jen se dívej, jak se hýbe. Cíl: čtyři minuty a nesahat na ni rukama.|240|ona_nahore_zady",
    "Záda pod tvýma rukama: Nech ji sedět na tobě zády a hlaď jí záda a zadeček. Cíl: čtyři minuty a ruce ani jednou nesundat.|240|ona_nahore_zady",
    "Zvedáš ji za boky: Ona sedí na tobě zády, ty ji držíš za boky a sám ji zvedáš. Cíl: čtyři minuty, při kterých se ona vůbec nenamáhá.|240|ona_nahore_zady",
    "Zády a rukou: Ona sedí zády a ty jí zezadu sáhneš dopředu a dráždíš ji. Cíl: obojí najednou.|300|ona_nahore_zady",
    "Dřep nad tebou: Nech ji dřepnout si na tebe a pohybovat se nahoru a dolů. Cíl: čtyřicet pohybů a ani jednou si nesednout.|240|drep",
    "Držíš jí ruce: Ona dřepí nad tebou a ty ji držíš za obě ruce, ať má oporu. Cíl: čtyři minuty a ani jednou ji nepustit.|240|drep",
    "Dřep a pauza: V dřepu udělá deset pohybů a pak na deset vteřin zůstane dole. Pětkrát. Cíl: pět kol.|300|drep",
    "Minuta bez hnutí: Nech ji sedět na tobě úplně bez pohybu. Cíl: celá minuta, při které se nepohne ani jeden z vás.|60|ona_nahore",
    "Ruce za zády nahoře: Nech ji sednout si na tebe a drž jí obě ruce za zády. Cíl: čtyři minuty a na stop ji hned pustit.|240|ona_nahore",
    "Neseš ji ty: Ona je nahoře a ty ji držíš pod zadečkem a sám ji zvedáš. Cíl: čtyři minuty, při kterých se ona vůbec nenamáhá.|240|ona_nahore",
    "Vsedě proti sobě: Sedněte si proti sobě, ona obkročmo na tobě, a objímejte se. Cíl: čtyři minuty a hýbat se jen boky.|240|klin_celem",
    "Vsedě proti sobě: Sedíte oba, ona na tobě, nohy propletené. Hýbat se dá jen málo, o to víc to je. Cíl: vydržet v objetí.|300|klin_celem",
    "Kloníš ji dozadu: Nech ji sedět na tobě a pomalu ji zaklánej dozadu, až se opře o ruce. Cíl: pět takových záklonů, každý pomalejší.|240|ona_nahore",
    "Vlasy v hrsti: Ona je nahoře a ty jí držíš vlasy stažené do ruky. Cíl: čtyři minuty a každou minutu se zeptat, jestli to není moc.|240|ona_nahore",
    "Vibrátor zepředu: Nech ji sednout si na tebe a přikládej jí zepředu vibrátor. Cíl: pět minut a ani jednou ho neodložit.|300|ona_nahore",
    "Dlaň přes oči: Ona je nahoře a ty jí dlaní zakryješ oči. Cíl: čtyři minuty poslepu a ruku ani jednou nesundat.|240|ona_nahore",
    "Sto pohybů shora: Ona udělá přesně sto pohybů. Ty jen ležíš a počítáš nahlas. Cíl: dojít do sta.|300|ona_nahore",
    "Kotníky v dlaních: Nech ji sedět na tobě zády a drž jí oba kotníky. Cíl: čtyři minuty a ani jednou je nepustit.|240|ona_nahore_zady",
    "Zezadu jí zvedni jednu nohu na postel, ať má jiný úhel.|240|zezadu",
    "Za ramena k sobě: Drž ji zezadu za obě ramena a při každém přírazu si ji přitáhni. Cíl: čtyřicet přírazů a u každého jedno přitažení.|240|zezadu",
    "Nech ji klečet a sám zůstaň stát. Rozdíl výšek to změní.|240|zezadu",
    "Zezadu ji obejmi kolem pasu a drž ji těsně u sebe.|240|zezadu_vzpr",
    "Zezadu jí polož ruku na břicho a přitáhni si ji k sobě.|240|zezadu_vzpr",
    "Zezadu a šeptem: Klečíte oba, ty za ní, a celou dobu jí šeptáš do ucha, co s ní děláš. Cíl: nepřestat mluvit.|300|zezadu_vzpr",
    "Nech ji na sobě sedět a pohybovat se, jen když ty vydechneš.|300|ona_nahore",
    "Nahoře a drží se čela: Nech ji sednout si na tebe a držet se čela postele. Cíl: čtyři minuty a nesmí se pustit ani jednou.|240|ona_nahore",
    "Stehna a boky: Ona je nahoře a ty jí celou dobu hladíš stehna a boky. Cíl: čtyři minuty a ruce nezastavit.|240|ona_nahore",
    "Střídej: minutu ona nahoře, minutu ty zezadu. Bez přerušení.|300|zezadu",
    "Tři polohy za sebou: Zezadu, pak ona nahoře, pak misionář. Přechody bez vyjití. Cíl: všechny tři plynule.|300|zezadu",
    "Zezadu jí polož ruce na lopatky a jemně zatlač dolů.|240|zezadu",
    "Zezadu co nejpomaleji: Nech ji klečet a přirážej zezadu tak pomalu, jak jen dokážeš. Cíl: pět minut a ani jednou nezrychlit.|300|zezadu",
    "Zezadu jí dej ruku dopředu na prsa a přitáhni ji.|240|zezadu_vzpr",
    "Ať si klekne bokem k tobě a ty vnikej ze strany.|240|zezadu",
    "Zezadu jí drž oba kotníky a řiď šířku jejích nohou.|240|na_brise",
    "Zápěstí nad hlavou na břiše: Ona leží na břiše a ty jí držíš obě zápěstí nad hlavou. Cíl: čtyři minuty a na stop ji hned pustit.|240|na_brise",
    "Zadeček nahoru: Ona leží na hrudníku a zvedá zadeček co nejvýš. Ty jsi nad ní. Cíl: vydržet ten úhel.|240|na_brise",
    "Nech ji na tobě sedět čelem a líbejte se u toho.|240|ona_nahore",
    "Boky mezi dlaněmi: Ona je nahoře a ty jí pevně sevřeš boky mezi dlaněmi. Cíl: čtyři minuty a tempo řídit jen rukama.|240|ona_nahore",
    "Ruce na krku a prsou: Nech ji sednout si na tebe a polož jí jednu ruku na krk a druhou na prsa. Bez tlaku. Cíl: na stop ruce hned sundat.|240|ona_nahore",
    "Ona nahoře a mezi tím jí lehce plácneš po zadečku.|240|ona_nahore",
    "Dvojí kontrola: Minutu řídí tempo ona, minutu ty, a tak dokola. Cíl: pět výměn a ani jednou se nepřerušit.|300|ona_nahore",
    "Nech ji sedět na tobě a při každém sestupu se zhluboka nadechni.|300|ona_nahore",
    "Opřená o tvůj hrudník: Nech ji naklonit se dopředu a opřít se ti rukama o hrudník. Cíl: čtyři minuty a ani jednou se nenarovnat.|240|ona_nahore",
    "Ona nahoře, ale s rukama za zády. Ty ji držíš.|240|ona_nahore",
    "Nakloněná ke kolenům: Nech ji sednout si na tebe zády a naklonit se dopředu k tvým kolenům. Cíl: čtyři minuty a držet ji za boky.|240|ona_nahore_zady",
    "Zády a hluboko: Ona sedí zády a nakloní se dopředu. Úhel je úplně jiný. Cíl: najít, kde to sedí nejlíp.|300|ona_nahore_zady",
    "Chyť ji pod břichem: Chyť ji zezadu pod břichem a zvedni si ji k sobě. Cíl: čtyři minuty a ani jednou ji nepoložit zpátky.|240|zezadu",
    "Nech ji klečet a ty se pohybuj jen v posledních centimetrech.|300|zezadu",
    "Propletená ruka zezadu: Miluj ji zezadu a jednu ruku měj propletenou s její. Cíl: čtyři minuty a prsty ani jednou nerozpojit.|240|zezadu",
    "Oba na kolenou: Ona klečí, ty za ní vzpřímeně na kolenou a držíš ji za boky. Cíl: čtyři minuty a udržet rovnováhu obou.|240|zezadu_vzpr",
    "Zezadu a vibrátor: Klečíš za ní a přikládáš jí vibrátor zepředu. Cíl: nepustit ho celou dobu.|300|zezadu",
    "Nech ji na tobě a jen se dívej, jak se snaží.|300|ona_nahore",
    "Na konci ji nech sednout si na tebe a jen se objímejte.|120|klin_celem",
  ],

  female: [
    "Klekni si na všechny čtyři a nech ho vniknout zezadu. Ať tě drží za boky.|240|zezadu",
    "Pomalu a naplno: Klečíš, on je za tebou. Deset přírazů pomalu, pak deset naplno. Cíl: čtyři taková kola a ani jednou se nesplést.|300|zezadu",
    "Nech si od něj položit ruku mezi lopatky a jemně se zatlačit do podložky.|240|zezadu",
    "Opři se o lokty a zvedni zadeček. Ať tě drží za boky oběma rukama.|240|zezadu",
    "Zezadu si dej jeho ruku dopředu, ať tě dráždí, zatímco do tebe vniká.|300|zezadu",
    "Nech se zezadu chytit za ramena a přitahovat k němu.|240|zezadu",
    "Lehni si na břicho s polštářem pod boky a nech ho vniknout shora.|240|na_brise",
    "Nejtěsnější poloha: Lež na břiše s nohama u sebe – těsnější to už nebude. Cíl: pět minut a ani jeden rychlý příraz.|300|na_brise",
    "Na břiše zvedni jeden bok a nech ho vnikat z boku.|240|na_brise!",
    "Klekni si vzpřímeně a nech ho kleknout si za tebe. Ať tě drží přes prsa.|240|zezadu_vzpr",
    "Vzpřímeně zezadu si dej jeho jednu ruku na rameno a druhou na klitoris.|300|zezadu_vzpr!",
    "Vzpřímeně na kolenou: Oba klečíte, ty před ním. Nech se obejmout a hýbejte se jen málo. Cíl: co největší blízkost.|300|zezadu_vzpr",
    "Čelo postele v rukou: Klekni si a drž se čela postele, on je za tebou. Cíl: čtyři minuty a nesmíš se pustit ani jednou.|240|pouta_postel",
    "Dej ruce dozadu a nech si je od něj držet za zápěstí.|240|zezadu",
    "Nech se zezadu lehce tahat za vlasy. Jen tak, aby to bylo příjemné.|240|zezadu",
    "Řekni mu, ať tě zezadu plácne po zadečku vždycky po deseti pohybech.|240|zezadu",
    "Čelo dolů: Klekni si a opři si čelo o postel, on přiráží hluboko zezadu. Cíl: čtyřicet hlubokých přírazů a žádný mělký.|240|zezadu",
    "Zezadu a stop: Ať se zastaví pokaždé, když se blížíš, a počká deset vteřin. Třikrát. Cíl: vydržet všechna tři zastavení.|300|zezadu!",
    "Vsuň si pod břicho polštář, ať máš jiný úhel.|240|na_brise",
    "Klekni si na kraj postele a nech ho stát na podlaze za tebou.|240|zezadu!",
    "Nech si od něj položit ruku na krk. Jen položit, netlačit.|240|zezadu",
    "Přirážíš ty: Klečíš a on se vůbec nehýbe – všechnu práci děláš ty. Cíl: pět minut a ani jednou ho nepožádat o pomoc.|300|zezadu",
    "Ať ti dá jednu ruku na rameno a druhou na bok a určí tempo.|240|zezadu!",
    "Ona nahoře: Sedni si na něj a řiď všechno sama. On se nesmí ani jednou pohnout. Cíl: mít to celé v rukou.|300|ona_nahore",
    "Sedni si na něj čelem a nech si od něj držet ruce.|240|ona_nahore",
    "Sedni si na něj a nech se držet za boky, ať ti pomáhá s tempem.|240|ona_nahore",
    "Na něm krouži místo zvedání. Bude to úplně jinak.|300|ona_nahore",
    "Opřená o jeho stehna: Sedni si na něj a opři se rukama dozadu o jeho stehna. Cíl: čtyři minuty a ani jednou se nepředklonit.|240|ona_nahore",
    "Bradavky na dosah: Sedni si na něj a skloň se tak, aby ti mohl olizovat bradavky. Cíl: čtyři minuty a ani jednou se nenarovnat.|240|ona_nahore",
    "Kroužení shora: Na něm nesmíš vůbec zvedat boky, jen kroužit. Cíl: dojít tam jen kroužením.|300|ona_nahore",
    "Sedni si na něj zády a nech ho koukat, jak se hýbeš.|240|ona_nahore_zady",
    "Jeho ruce na tvých zádech: Sedni si na něj zády a nech si hladit záda a zadeček. Cíl: čtyři minuty a ruce mu nedovolit sundat.|240|ona_nahore_zady",
    "Zády k němu a nech se držet za boky a zvedat.|240|ona_nahore_zady",
    "Zády a jeho ruka: Sedíš na něm zády a jeho ruka ti sahá zezadu dopředu. Cíl: pět minut a obojí ve stejném rytmu.|300|ona_nahore_zady",
    "Dřep nad ním: Dřepni si na něj a pohybuj se nahoru a dolů celým tělem. Cíl: čtyřicet pohybů a ani jednou si nesednout.|240|drep",
    "Opora v jeho rukou: V dřepu nad ním se drž jeho rukou, ať máš oporu. Cíl: čtyři minuty a ani jednou se nepustit.|240|drep",
    "Dřep a pauza: V dřepu uděláš deset pohybů a pak na deset vteřin zůstaneš dole. Pětkrát. Cíl: pět kol.|300|drep",
    "Sedni si na něj a celou minutu se vůbec nehýbej.|60|ona_nahore",
    "Sedni si na něj a dej si ruce za záda, ať ti je drží.|240|ona_nahore",
    "Sedni si na něj a nech se držet pod zadečkem a zvedat.|240|ona_nahore",
    "Sedni si mu obkročmo na klín a ať se posadí taky. Objímejte se.|240|klin_celem",
    "Vsedě proti sobě: Sedíte oba, ty na něm, nohy propletené. Hýbat se dá jen málo, o to víc to je. Cíl: vydržet v objetí.|300|klin_celem",
    "Záklon dozadu: Sedni si na něj a pomalu se zaklánej dozadu, až se opřeš o ruce. Cíl: pět takových záklonů, každý pomalejší.|240|ona_nahore",
    "Sedni si na něj a nech se držet za vlasy stažené do jeho ruky.|240|ona_nahore",
    "Sedni si na něj a přilož si vibrátor zepředu.|300|ona_nahore",
    "Sedni si na něj a nech si zakrýt oči jeho dlaní.|240|ona_nahore",
    "Sto pohybů shora: Uděláš přesně sto pohybů. On jen leží a počítá nahlas. Cíl: dojít do sta.|300|ona_nahore",
    "Sedni si na něj zády a nech si držet kotníky.|240|ona_nahore_zady",
    "Zvedni si jednu nohu na postel, ať má zezadu jiný úhel.|240|zezadu",
    "Nech se zezadu držet za obě ramena a přitahovat na něj.|240|zezadu",
    "Klekni si a nech ho zůstat stát. Rozdíl výšek to změní.|240|zezadu",
    "Nech se zezadu obejmout kolem pasu a držet těsně u něj.|240|zezadu_vzpr",
    "Dej si jeho ruku na břicho a přitáhni si ho k sobě.|240|zezadu_vzpr",
    "Zezadu a šeptem: Klečíte oba, on za tebou, a celou dobu ti šeptá do ucha, co dělá. Cíl: ať nepřestane mluvit.|300|zezadu_vzpr!",
    "Sedni si na něj a pohybuj se jen tehdy, když on vydechne.|300|ona_nahore",
    "Nahoře u čela postele: Sedni si na něj a drž se přitom čela postele. Cíl: čtyři minuty a nesmíš se pustit ani jednou.|240|ona_nahore",
    "Sedni si na něj a nech si hladit stehna a boky.|240|ona_nahore",
    "Střídejte se: minutu ty nahoře, minutu on zezadu. Bez přerušení.|300|zezadu",
    "Tři polohy za sebou: Zezadu, pak ty nahoře, pak misionář. Přechody bez vyjití. Cíl: všechny tři plynule.|300|zezadu!",
    "Nech si položit ruce na lopatky a jemně zatlačit dolů.|240|zezadu",
    "Zezadu co nejpomaleji: Klečíš a on tě miluje zezadu tak pomalu, jak jen dokáže. Cíl: pět minut a ani jednou mu nedovolit zrychlit.|300|zezadu",
    "Dej si jeho ruku zepředu na prsa a nech se přitáhnout.|240|zezadu_vzpr",
    "Klekni si k němu bokem a nech ho vnikat ze strany.|240|zezadu",
    "Nech si od něj držet oba kotníky a řídit šířku tvých nohou.|240|na_brise",
    "Zápěstí nad hlavou: Lež na břiše a nech si od něj držet obě zápěstí nad hlavou. Cíl: čtyři minuty a na stop tě musí hned pustit.|240|na_brise!",
    "Zadeček nahoru: Lež na hrudníku a zvedni zadeček co nejvýš. On je nad tebou. Cíl: vydržet ten úhel.|240|na_brise",
    "Nahoře a polibek: Sedni si na něj čelem a celou dobu se líbejte. Cíl: čtyři minuty a polibek ani jednou nepřerušit.|240|ona_nahore",
    "Sedni si na něj a nech si sevřít boky mezi jeho dlaněmi.|240|ona_nahore",
    "Sedni si na něj a dej si jeho ruce na krk a na prsa.|240|ona_nahore",
    "Sedni si na něj a nech se mezi tím lehce plácnout po zadečku.|240|ona_nahore",
    "Střídavá kontrola: Minutu řídíš tempo ty, minutu on, a tak dokola. Cíl: pět výměn a ani jednou se nepřerušit.|300|ona_nahore",
    "Nádech při každém sestupu: Sedni si na něj a při každém sestupu se zhluboka nadechni. Cíl: padesát pohybů a ani jeden bez nádechu.|300|ona_nahore",
    "Opřená o jeho hrudník: Nakloň se na něm dopředu a opři se mu rukama o hrudník. Cíl: čtyři minuty a ani jednou se nenarovnat.|240|ona_nahore",
    "Ruce za zády nahoře: Sedni si na něj s rukama za zády a nech se od něj držet. Cíl: čtyři minuty a ani jednou ruce nevyndat.|240|ona_nahore",
    "Nakloněná k jeho kolenům: Sedni si na něj zády a nakloň se dopředu k jeho kolenům. Cíl: čtyři minuty a nechat se držet za boky.|240|ona_nahore_zady",
    "Zády a hluboko: Sedíš zády a nakloníš se dopředu. Úhel je úplně jiný. Cíl: najít, kde to sedí nejlíp.|300|ona_nahore_zady",
    "Nech se zezadu chytit pod břichem a zvednout k němu.|240|zezadu",
    "Klečíš a on se pohybuje jen v posledních centimetrech.|300|zezadu",
    "Dej mu zezadu ruku a nech si ji proplést s jeho.|240|zezadu",
    "Klekni si a nech ho kleknout si vzpřímeně za tebe. Ať tě drží za boky.|240|zezadu_vzpr",
    "Zezadu a vibrátor: Klečí za tebou a přikládá ti vibrátor zepředu. Cíl: nepustit ho celou dobu.|300|zezadu!",
    "Sedni si na něj a nech ho jen se dívat, jak se snažíš.|300|ona_nahore",
    "Konec v objetí: Sedni si mu na klín, zůstaň v klidu a jen se objímejte. Cíl: dvě minuty, při kterých se ani jeden nepohne.|120|klin_celem",
  ],
});
