// Kategorie 4 – Sex a polohy (dávka c)
// Témata: zezadu ve všech variantách a ona nahoře čelem, zády, v dřepu.
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 4,

  male: [
    "Na všech čtyřech: Nech ji kleknout si na všechny čtyři, vnikni do ní zezadu a drž ji za boky. Cíl: čtyři minuty a ani jednou ji nepustit.|240|zezadu",
    "Zezadu a pomalu: Ona klečí, ty jsi za ní. Deset přírazů pomalu, pak deset naplno. Cíl: čtyři taková kola a ani jednou se nesplést.|300|zezadu",
    "Ruka mezi lopatkami: Miluj ji zezadu a polož jí ruku mezi lopatky, jemně ji tlač do podložky. Cíl: čtyři minuty a kdykoli řekne stop, ruku sundat.|240|zezadu",
    "Na loktech se zvednutým zadečkem: Nech ji opřít se o lokty a zvednout zadeček, drž ji za boky a přirážej. Cíl: čtyři minuty a nesmí se sesunout.|240|zezadu",
    "Ruka dopředu: Miluj ji zezadu a jednou rukou jí zepředu dráždi klitoris. Cíl: pět minut a obojí ve stejném rytmu.|300|zezadu",
    "Za ramena: Chyť ji zezadu za ramena a při každém přírazu si ji přitáhni. Cíl: čtyřicet přírazů a u každého jedno přitažení.|240|zezadu",
    "Polštář pod břichem: Nech ji ležet na břiše s polštářem pod boky a vnikni do ní shora. Cíl: čtyři minuty a polštář nenechat vyklouznout.|240|na_brise",
    "Na břiše a hluboko: Ona leží na břiše s nohama u sebe – je to nejtěsnější poloha, jakou znáte. Cíl: pět minut a ani jeden rychlý příraz.|300|na_brise",
    "Zvednutý bok: Nech ji ležet na břiše, zvedni jí jeden bok a vnikej z boku. Cíl: čtyři minuty a po dvou minutách stranu vyměnit.|240|na_brise",
    "Vzpřímeně a přes prsa: Oba klečíte vzpřímeně, vnikni do ní zezadu a drž ji přes prsa. Cíl: čtyři minuty přírazů a ani jednou ji nepustit.|240|zezadu_vzpr",
    "Rameno a klitoris: Vnikni do ní vzpřímeně zezadu, jednou rukou jí drž rameno a druhou dráždi klitoris. Cíl: pět minut a ani jednu ruku nesundat.|300|zezadu_vzpr",
    "Vzpřímeně na kolenou: Oba klečíte, ona před tebou. Vnikni do ní, obejmi ji a přirážej jen minimálně. Cíl: pět minut a nerozpojit objetí.|300|zezadu_vzpr",
    "Drží se čela postele: Nech ji klečet a držet se čela postele a miluj ji zezadu. Cíl: čtyři minuty a nesmí se pustit ani jednou.|240|pouta_postel",
    "Ruce dozadu: Miluj ji zezadu, vezmi jí ruce dozadu a drž ji za zápěstí. Cíl: čtyři minuty a na stop ji hned pustit.|240|zezadu",
    "Lehce za vlasy: Miluj ji zezadu a lehce ji tahej za vlasy, jen tolik, aby jí to bylo příjemné. Cíl: deset zatažení a po každém se zeptat.|240|zezadu",
    "Rána po desátém: Miluj ji zezadu a po každých deseti přírazech ji plácni po zadečku. Cíl: čtyřicet přírazů, čtyři rány, síla stejná.|240|zezadu",
    "Čelo na posteli: Nech ji kleknout si a opřít čelo o postel a přirážej hluboko. Cíl: čtyřicet hlubokých přírazů a žádný mělký.|240|zezadu",
    "Zezadu a stop: Přirážej do ní zezadu a pokaždé, když se blíží, se v ní na deset vteřin zastav. Cíl: vydržet všechna tři zastavení.|300|zezadu",
    "Polštář změní úhel: Vsuň jí pod břicho polštář a miluj ji zezadu. Cíl: čtyři minuty a pak se zeptat, jestli je ten úhel lepší.|240|na_brise",
    "Ty stojíš, ona klečí: Nech ji klečet na kraji postele, stoupni si za ni na podlahu a vnikni do ní. Cíl: čtyři minuty přírazů a najít výšku, kde to sedne oběma.|240|zezadu",
    "Dlaň na krku zezadu: Miluj ji zezadu a polož jí ruku na krk – jen položit, nikdy netlačit. Cíl: na stop ruku hned sundat.|240|zezadu",
    "Přiráží ona: Nech ji klečet a sám se vůbec nehýbej. Cíl: pět minut, při kterých všechnu práci dělá ona.|300|zezadu",
    "Rameno a bok: Miluj ji zezadu s jednou rukou na rameni a druhou na boku a veď celé tempo sám. Cíl: čtyři minuty bez jediného zaváhání.|240|zezadu",
    "Ona nahoře: Lehni si na záda a nech ji, ať si tě sama zavede do sebe a jezdí na tobě, jak chce. Cíl: pět minut a nepohnout se ani jednou.|300|ona_nahore",
    "Ruce v tvých: Nech ji nasadit se na tebe čelem a jezdit, drž jí přitom obě ruce. Cíl: čtyři minuty a ani jednou ji nepustit.|240|ona_nahore",
    "Pomáháš jí za boky: Ona jezdí na tobě a ty jí rukama na bocích pomáháš s tempem. Cíl: čtyři minuty a ruce ani jednou nesundat.|240|ona_nahore",
    "Kroužit, ne zvedat: Nech ji nasadit se na tebe a kroužit boky místo zvedání. Cíl: pět minut a ani jednou se nezvednout.|300|ona_nahore",
    "Opřená o tvoje stehna: Nech ji nasadit se na tebe a opřít se rukama dozadu o tvoje stehna. Cíl: čtyři minuty jízdy a nesmí se předklonit.|240|ona_nahore",
    "Když se skloní: Ona jezdí na tobě a pokaždé, když se skloní, jí olízni bradavku. Cíl: dvacet sklonění a ani jedno nevynechat.|240|ona_nahore",
    "Kroužení shora: Nech ji nasadit se na tebe a jen kroužit boky, zvedat se nesmí vůbec. Cíl: dovést ji tam jen kroužením.|300|ona_nahore",
    "Výhled zezadu: Nech ji nasadit se na tebe zády a jen se dívej, jak na tobě jezdí. Cíl: čtyři minuty a nesahat na ni rukama.|240|ona_nahore_zady",
    "Záda pod tvýma rukama: Nech ji jezdit na tobě zády a hlaď jí u toho záda a zadeček. Cíl: čtyři minuty a ruce ani jednou nesundat.|240|ona_nahore_zady",
    "Zvedáš ji za boky: Sedí na tobě zády, ty ji držíš za boky a přirážíš do ní sám zespodu. Cíl: čtyři minuty, při kterých se ona vůbec nenamáhá.|240|ona_nahore_zady",
    "Zády a rukou: Jezdí na tobě zády a ty jí zezadu sáhneš dopředu na klitoris. Cíl: pět minut a dráždit ji celou dobu.|300|ona_nahore_zady",
    "Dřep nad tebou: Nech ji dřepnout si nad tebe, nasadit se a jezdit nahoru a dolů. Cíl: čtyřicet pohybů a ani jednou si nesednout.|240|drep",
    "Držíš jí ruce: Jezdí na tobě v dřepu a ty ji držíš za obě ruce, ať má oporu. Cíl: čtyři minuty a ani jednou ji nepustit.|240|drep",
    "Dřep a pauza: Nech ji v dřepu jezdit deset pohybů a pak zůstat deset vteřin dole. Cíl: pět takových kol.|300|drep",
    "Minuta bez hnutí: Nech ji nasadit se na tebe a zůstat úplně bez pohybu. Cíl: celá minuta, při které se nepohne ani jeden z vás.|60|ona_nahore",
    "Ruce za zády nahoře: Nech ji jezdit na tobě a drž jí přitom obě ruce za zády. Cíl: čtyři minuty a na stop ji hned pustit.|240|ona_nahore",
    "Neseš ji ty: Je na tobě, ty ji držíš pod zadečkem a přirážíš do ní sám zespodu. Cíl: čtyři minuty, při kterých se ona nemusí vůbec namáhat.|240|ona_nahore",
    "Vsedě proti sobě: Posaď si ji obkročmo na klín, zaveď se do ní a objímejte se. Cíl: čtyři minuty a hýbat se jen boky.|240|klin_celem",
    "Vsedě a propletení: Sedíte oba proti sobě, jsi v ní, nohy propletené. Hýbat se dá jen málo. Cíl: pět minut a ani jednou nevyklouznout.|300|klin_celem",
    "Kloníš ji dozadu: Nech ji jezdit na tobě a pomalu ji zaklánej dozadu, až se opře o ruce. Cíl: pět takových záklonů, každý pomalejší.|240|ona_nahore",
    "Vlasy v hrsti: Jezdí na tobě a ty jí držíš vlasy stažené do ruky. Cíl: čtyři minuty a každou minutu se zeptat, jestli to není moc.|240|ona_nahore",
    "Vibrátor zepředu: Nech ji nasadit se na tebe a přikládej jí zepředu vibrátor na klitoris. Cíl: pět minut a ani jednou ho neodložit.|300|ona_nahore",
    "Dlaň přes oči: Jezdí na tobě a ty jí dlaní zakryješ oči. Cíl: čtyři minuty poslepu a ruku ani jednou nesundat.|240|ona_nahore",
    "Sto pohybů shora: Nech ji jezdit na tobě přesně sto pohybů, ty jen ležíš a počítáš nahlas. Cíl: dojít do sta bez ztráty rytmu.|300|ona_nahore",
    "Kotníky v dlaních: Nech ji jezdit na tobě zády a drž jí u toho oba kotníky. Cíl: čtyři minuty a ani jednou je nepustit.|240|ona_nahore_zady",
    "Noha na posteli: Zezadu jí zvedni jednu nohu na postel a přirážej z toho úhlu. Cíl: čtyři minuty a nohu jí ani jednou nespustit.|240|zezadu",
    "Za ramena k sobě: Drž ji zezadu za obě ramena a při každém přírazu si ji přitáhni. Cíl: čtyřicet přírazů a u každého jedno přitažení.|240|zezadu",
    "Rozdíl výšek: Nech ji klečet, sám zůstaň stát a vnikni do ní zezadu. Cíl: čtyři minuty přírazů z toho rozdílu výšek.|240|zezadu",
    "Obejmutá kolem pasu: Vnikni do ní zezadu, obejmi ji kolem pasu a drž ji těsně u sebe. Cíl: čtyři minuty přírazů a objetí nerozpojit.|240|zezadu_vzpr",
    "Ruka na jejím břiše: Vnikni do ní zezadu, polož jí ruku na břicho a přitáhni si ji k sobě. Cíl: čtyři minuty a ruku z břicha nesundat.|240|zezadu_vzpr",
    "Zezadu a šeptem: Klečíte oba, přirážej do ní zezadu a celou dobu jí šeptej do ucha, co s ní děláš. Cíl: pět minut a ani jednou se neodmlčet.|300|zezadu_vzpr",
    "Pohyb na tvůj výdech: Nech ji nasadit se na tebe a pohnout se vždycky jen tehdy, když ty nahlas vydechneš. Cíl: padesát tvých výdechů.|300|ona_nahore",
    "Nahoře a drží se čela: Nech ji jezdit na tobě a přitom se držet čela postele. Cíl: čtyři minuty a nesmí se pustit ani jednou.|240|ona_nahore",
    "Stehna a boky: Jezdí na tobě a ty jí celou dobu hladíš stehna a boky. Cíl: čtyři minuty a ruce nezastavit.|240|ona_nahore",
    "Střídej: minutu jezdí na tobě ona, minutu přirážíš ty zezadu. Cíl: pět výměn a ani jednou z ní nevyjít.|300|zezadu",
    "Tři polohy za sebou: Přirážej zezadu, pak nech jezdit ji, pak misionář. Cíl: všechny tři plynule a bez jediného vyjití.|300|zezadu",
    "Lopatky pod dlaněmi: Přirážej do ní zezadu, polož jí ruce na lopatky a jemně zatlač dolů. Cíl: čtyři minuty a tlak ani jednou nezvýšit.|240|zezadu",
    "Zezadu co nejpomaleji: Nech ji klečet a přirážej zezadu tak pomalu, jak jen dokážeš. Cíl: pět minut a ani jednou nezrychlit.|300|zezadu",
    "Ruka na jejích prsou: Vnikni do ní zezadu, dej jí ruku dopředu na prsa a přitáhni si ji. Cíl: čtyři minuty přírazů a ruku nesundat.|240|zezadu_vzpr",
    "Ať si klekne bokem k tobě a ty vnikej ze strany.|240|zezadu",
    "Šířka podle tebe: Vnikni do ní zezadu na břiše, drž jí oba kotníky a řiď šířku jejích nohou. Cíl: tři různé šířky a u každé deset přírazů.|240|na_brise",
    "Zápěstí nad hlavou na břiše: Leží na břiše, vnikni do ní zezadu a drž jí obě zápěstí nad hlavou. Cíl: čtyři minuty a na stop ji hned pustit.|240|na_brise",
    "Zadeček nahoru: Leží na hrudníku, zvedne zadeček co nejvýš a ty do ní shora přirážíš. Cíl: čtyři minuty a ten úhel neztratit.|240|na_brise",
    "Jízda a polibek: Nech ji jezdit na tobě čelem a celou dobu se u toho líbejte. Cíl: čtyři minuty a polibek ani jednou nepřerušit.|240|ona_nahore",
    "Boky mezi dlaněmi: Jezdí na tobě a ty jí pevně sevřeš boky mezi dlaněmi. Cíl: čtyři minuty a tempo přírazů řídit jen rukama.|240|ona_nahore",
    "Ruce na krku a prsou: Nech ji jezdit na tobě a polož jí jednu ruku na krk a druhou na prsa. Bez tlaku. Cíl: na stop ruce hned sundat.|240|ona_nahore",
    "Plácnutí shora: Nech ji jezdit na tobě a mezi tím jí vždycky lehce plácni po zadečku. Cíl: deset plácnutí za čtyři minuty.|240|ona_nahore",
    "Dvojí kontrola: Minutu řídí tempo přírazů ona shora, minutu ty zespodu, a tak dokola. Cíl: pět výměn a ani jednou se nepřerušit.|300|ona_nahore",
    "Nádech při sestupu: Nech ji jezdit na tobě a při každém jejím sestupu se zhluboka nadechni. Cíl: padesát sestupů a ani jeden bez nádechu.|300|ona_nahore",
    "Opřená o tvůj hrudník: Nech ji jezdit na tobě nakloněnou dopředu, opřenou rukama o tvůj hrudník. Cíl: čtyři minuty a ani jednou se nenarovnat.|240|ona_nahore",
    "Ruce za zády: Nech ji jezdit na tobě s rukama za zády, které jí celou dobu držíš. Cíl: čtyři minuty a na stop ji hned pustit.|240|ona_nahore",
    "Nakloněná ke kolenům: Nech ji jezdit na tobě zády nakloněnou dopředu k tvým kolenům. Cíl: čtyři minuty a celou dobu ji držet za boky.|240|ona_nahore_zady",
    "Zády a hluboko: Jezdí na tobě zády a nakloní se dopředu, úhel přírazů je úplně jiný. Cíl: pět minut a říct si, kde to sedí nejlíp.|300|ona_nahore_zady",
    "Chyť ji pod břichem: Vnikni do ní zezadu, chyť ji pod břichem a zvedni si ji k sobě. Cíl: čtyři minuty přírazů a ani jednou ji nepoložit zpátky.|240|zezadu",
    "Jen poslední centimetry: Nech ji klečet, vnikni do ní zezadu a přirážej jen v posledních centimetrech. Cíl: pět minut a ani jednou nezajet hlouběji.|300|zezadu",
    "Propletená ruka zezadu: Miluj ji zezadu a jednu ruku měj propletenou s její. Cíl: čtyři minuty a prsty ani jednou nerozpojit.|240|zezadu",
    "Oba na kolenou: Ona klečí, ty za ní vzpřímeně přirážíš a držíš ji za boky. Cíl: čtyři minuty a udržet rovnováhu obou.|240|zezadu_vzpr",
    "Zezadu a vibrátor: Přirážej do ní zezadu a zepředu jí přikládej vibrátor na klitoris. Cíl: pět minut a nepustit ho celou dobu.|300|zezadu",
    "Jen se dívej: Nech ji jezdit na tobě a jen lež a dívej se, jak se snaží. Cíl: pět minut a nepomoct jí ani jedním pohybem.|300|ona_nahore",
    "Objetí na konci: Na konci ji nech nasadit se na tebe a jen se objímejte bez pohybu. Cíl: dvě minuty a ani jeden příraz.|120|klin_celem",
  ],

  female: [
    "Klekni si na všechny čtyři a nech ho vniknout zezadu. Ať tě drží za boky.|240|zezadu",
    "Pomalu a naplno: Klečíš, on je za tebou. Deset přírazů pomalu, pak deset naplno. Cíl: čtyři taková kola a ani jednou se nesplést.|300|zezadu",
    "Ruka mezi lopatkami: Nech ho vniknout zezadu, položit ti ruku mezi lopatky a jemně tě zatlačit do podložky. Cíl: čtyři minuty přírazů a nezvednout se.|240|zezadu",
    "O lokty a zadeček nahoru: Opři se o lokty, zvedni zadeček a nech ho vniknout zezadu a držet tě za boky. Cíl: čtyři minuty přírazů a zadeček nespustit.|240|zezadu",
    "Zezadu si dej jeho ruku dopředu, ať tě dráždí, zatímco do tebe vniká.|300|zezadu",
    "Za ramena k sobě: Nech ho vniknout zezadu, chytit tě za ramena a přitahovat si tě na sebe. Cíl: čtyři minuty a ani jednou neuhnout dopředu.|240|zezadu",
    "Lehni si na břicho s polštářem pod boky a nech ho vniknout shora.|240|na_brise",
    "Nejtěsnější poloha: Lež na břiše s nohama u sebe – těsnější to už nebude. Cíl: pět minut a ani jeden rychlý příraz.|300|na_brise",
    "Na břiše zvedni jeden bok a nech ho vnikat z boku.|240|na_brise!",
    "Oba vzpřímeně: Klekni si vzpřímeně, nech ho kleknout si za tebe, vniknout a držet tě přes prsa. Cíl: čtyři minuty přírazů a nepustit se.|240|zezadu_vzpr",
    "Dvě ruce najednou: Nech ho vzpřímeně vniknout zezadu a dej si jeho jednu ruku na rameno a druhou na klitoris. Cíl: pět minut a ani jednu ruku nepustit.|300|zezadu_vzpr!",
    "Vzpřímeně na kolenou: Oba klečíte, ty před ním. Nech ho vniknout, obejmout tě a přirážet jen minimálně. Cíl: pět minut a nerozpojit objetí.|300|zezadu_vzpr",
    "Čelo postele v rukou: Klekni si, drž se čela postele a nech ho přirážet zezadu. Cíl: čtyři minuty a nesmíš se pustit ani jednou.|240|pouta_postel",
    "Zápěstí v jeho dlani: Dej ruce dozadu, nech si je držet za zápěstí a nech ho přirážet zezadu. Cíl: čtyři minuty a na stop tě musí hned pustit.|240|zezadu",
    "Vlasy v jeho ruce: Nech ho přirážet zezadu a lehce tě u toho tahat za vlasy, jen aby to bylo příjemné. Cíl: čtyři minuty a hned říct, když je to moc.|240|zezadu",
    "Plácnutí po desáté: Nech ho přirážet zezadu a ať tě plácne po zadečku vždycky po deseti přírazech. Cíl: deset plácnutí a ani jedno nevynechat.|240|zezadu",
    "Čelo dolů: Klekni si a opři si čelo o postel, on přiráží hluboko zezadu. Cíl: čtyřicet hlubokých přírazů a žádný mělký.|240|zezadu",
    "Zezadu a stop: Nech ho přirážet a zastavit se v tobě pokaždé, když se blížíš, na deset vteřin. Cíl: vydržet všechna tři zastavení.|300|zezadu!",
    "Polštář pod břichem: Vsuň si pod břicho polštář a nech ho vniknout zezadu – úhel bude úplně jiný. Cíl: čtyři minuty přírazů a polštář nevytáhnout.|240|na_brise",
    "On stojí, ty klečíš: Klekni si na kraj postele, nech ho stát na podlaze za tebou a vniknout do tebe. Cíl: čtyři minuty přírazů a najít společnou výšku.|240|zezadu!",
    "Ruka na krku: Nech ho přirážet zezadu a položit ti ruku na krk – jen položit, netlačit. Cíl: čtyři minuty a na stop ruku hned sundat.|240|zezadu",
    "Přirážíš ty: Klečíš a on se vůbec nehýbe – všechnu práci děláš ty. Cíl: pět minut a ani jednou ho nepožádat o pomoc.|300|zezadu",
    "Tempo v jeho rukou: Nech ho vniknout zezadu, dát ti jednu ruku na rameno a druhou na bok a určit tempo přírazů. Cíl: čtyři minuty a do tempa mu nemluvit.|240|zezadu!",
    "Ona nahoře: Zaveď si ho do sebe a jezdi na něm sama. On se nesmí ani jednou pohnout. Cíl: pět minut a mít to celé v rukou.|300|ona_nahore",
    "Ruce v jeho dlaních: Nasaď se na něj čelem, jezdi na něm a nech si od něj držet obě ruce. Cíl: čtyři minuty a ani jednou se nepustit.|240|ona_nahore",
    "Pomáhá ti za boky: Nasaď se na něj, jezdi a nech se držet za boky, ať ti pomáhá s tempem. Cíl: čtyři minuty a ruce mu nesundat.|240|ona_nahore",
    "Krouži, nezvedej: Nasaď se na něj a krouži na něm boky místo zvedání. Bude to úplně jinak. Cíl: pět minut a ani jednou se nezvednout.|300|ona_nahore",
    "Opřená o jeho stehna: Sedni si na něj, opři se rukama dozadu o jeho stehna a houpej se v bocích. Cíl: čtyři minuty a ani jednou se nepředklonit.|240|ona_nahore",
    "Bradavky na dosah: Jezdi na něm skloněná tak, aby ti mohl olizovat bradavky. Cíl: čtyři minuty a ani jednou se nenarovnat.|240|ona_nahore",
    "Kroužení shora: Nasaď se na něj a jen krouži boky, zvedat se nesmíš vůbec. Cíl: dojít tam jen kroužením.|300|ona_nahore",
    "Jen ať se dívá: Nasaď se na něj zády a nech ho jen koukat, jak na něm jezdíš. Cíl: čtyři minuty a nesmí na tebe sáhnout.|240|ona_nahore_zady",
    "Jeho ruce na tvých zádech: Jezdi na něm zády a nech si u toho hladit záda a zadeček. Cíl: čtyři minuty a ruce mu nedovolit sundat.|240|ona_nahore_zady",
    "Zvedá tě on: Nasaď se na něj zády a nech se držet za boky a zvedat, ať přiráží on. Cíl: čtyři minuty, při kterých se vůbec nenamáháš.|240|ona_nahore_zady",
    "Zády a jeho ruka: Jezdíš na něm zády a jeho ruka ti sahá zezadu dopředu na klitoris. Cíl: pět minut a obojí ve stejném rytmu.|300|ona_nahore_zady",
    "Dřep nad ním: Dřepni si nad něj, nasaď se a jezdi nahoru a dolů celým tělem. Cíl: čtyřicet pohybů a ani jednou si nesednout.|240|drep",
    "Opora v jeho rukou: Jezdi na něm v dřepu a drž se jeho rukou, ať máš oporu. Cíl: čtyři minuty a ani jednou se nepustit.|240|drep",
    "Dřep a pauza: Jezdi na něm v dřepu deset pohybů a pak zůstaň deset vteřin dole. Cíl: pět takových kol.|300|drep",
    "Celá minuta v klidu: Nasaď se na něj a pak se celou minutu vůbec nehýbej. Cíl: minuta, při které se nepohne ani jeden z vás.|60|ona_nahore",
    "Zápěstí za zády: Dej si ruce za záda, nasaď se na něj a nech si zápěstí celou dobu držet. Cíl: čtyři minuty a na stop tě musí hned pustit.|240|ona_nahore",
    "Nese tě on: Nasaď se na něj a nech se držet pod zadečkem a zvedat, ať přiráží on. Cíl: čtyři minuty, při kterých se nemusíš vůbec namáhat.|240|ona_nahore",
    "Obkročmo na klíně: Sedni si mu obkročmo na klín, zaveď si ho do sebe a objímejte se. Cíl: čtyři minuty a hýbat se jen boky.|240|klin_celem",
    "Vsedě a propletení: Sedíte oba proti sobě, je v tobě, nohy propletené. Hýbat se dá jen málo. Cíl: pět minut a ani jednou nevyklouznout.|300|klin_celem",
    "Záklon dozadu: Jezdi na něm a pomalu se zaklánej dozadu, až se opřeš o ruce. Cíl: pět takových záklonů, každý pomalejší.|240|ona_nahore",
    "Vlasy stažené do hrsti: Jezdi na něm a nech se u toho držet za vlasy stažené do jeho ruky. Cíl: čtyři minuty a hned říct, když je to moc.|240|ona_nahore",
    "Vibrátor při jízdě: Nasaď se na něj a zepředu si přilož vibrátor na klitoris. Cíl: pět minut a ani jednou ho neodložit.|300|ona_nahore",
    "Poslepu shora: Jezdi na něm a nech si zakrýt oči jeho dlaní. Cíl: čtyři minuty poslepu a ruku mu nesundat.|240|ona_nahore",
    "Sto pohybů shora: Jezdi na něm přesně sto pohybů, on jen leží a počítá nahlas. Cíl: dojít do sta bez ztráty rytmu.|300|ona_nahore",
    "Kotníky v jeho dlaních: Jezdi na něm zády a nech si od něj držet oba kotníky. Cíl: čtyři minuty a ani jednou je nepustit.|240|ona_nahore_zady",
    "Noha nahoře zezadu: Zvedni si jednu nohu na postel a nech ho vniknout zezadu z toho úhlu. Cíl: čtyři minuty přírazů a nohu nespustit.|240|zezadu",
    "Obě ramena v jeho rukou: Nech ho vniknout zezadu, držet tě za obě ramena a přitahovat si tě na sebe. Cíl: čtyři minuty a nepodklesnout v loktech.|240|zezadu",
    "On stojí nad tebou: Klekni si, nech ho zůstat stát a vniknout do tebe zezadu. Cíl: čtyři minuty přírazů z toho rozdílu výšek.|240|zezadu",
    "Objetí kolem pasu: Nech ho vniknout zezadu, obejmout tě kolem pasu a držet těsně u sebe. Cíl: čtyři minuty přírazů a objetí nerozpojit.|240|zezadu_vzpr",
    "Jeho ruka na břiše: Nech ho vniknout zezadu, dej si jeho ruku na břicho a přitáhni si ho k sobě. Cíl: čtyři minuty a ruku z břicha nepustit.|240|zezadu_vzpr",
    "Zezadu a šeptem: Klečíte oba, on do tebe zezadu přiráží a celou dobu ti šeptá do ucha, co dělá. Cíl: pět minut a ani jednou se neodmlčí.|300|zezadu_vzpr!",
    "Pohyb na jeho výdech: Nasaď se na něj a pohni se vždycky jen tehdy, když on nahlas vydechne. Cíl: padesát jeho výdechů.|300|ona_nahore",
    "Nahoře u čela postele: Jezdi na něm a drž se přitom čela postele. Cíl: čtyři minuty a nesmíš se pustit ani jednou.|240|ona_nahore",
    "Ruce na tvých stehnech: Jezdi na něm a nech si u toho celou dobu hladit stehna a boky. Cíl: čtyři minuty a ruce mu nedovolit zastavit.|240|ona_nahore",
    "Střídejte se: minutu jezdíš na něm ty, minutu přiráží on zezadu. Cíl: pět výměn a ani jednou se nerozpojit.|300|zezadu",
    "Tři polohy za sebou: Nech ho přirážet zezadu, pak jezdi ty, pak misionář. Cíl: všechny tři plynule a bez jediného vyjití.|300|zezadu!",
    "Lopatky k podložce: Nech ho přirážet zezadu, položit ti ruce na lopatky a jemně tě zatlačit dolů. Cíl: čtyři minuty a tlak nezvyšovat.|240|zezadu",
    "Zezadu co nejpomaleji: Klečíš a on tě miluje zezadu tak pomalu, jak jen dokáže. Cíl: pět minut a ani jednou mu nedovolit zrychlit.|300|zezadu",
    "Přitáhne si tě za prsa: Nech ho vniknout zezadu, dej si jeho ruku zepředu na prsa a nech se přitáhnout. Cíl: čtyři minuty přírazů a ruku nepustit.|240|zezadu_vzpr",
    "Klekni si k němu bokem a nech ho vnikat ze strany.|240|zezadu",
    "Šířka podle něj: Lež na břiše, nech ho vniknout zezadu a držet ti oba kotníky a řídit šířku nohou. Cíl: tři různé šířky a u každé deset přírazů.|240|na_brise",
    "Zápěstí nad hlavou: Lež na břiše, nech ho vniknout zezadu a držet ti obě zápěstí nad hlavou. Cíl: čtyři minuty a na stop tě musí hned pustit.|240|na_brise!",
    "Zadeček nahoru: Lež na hrudníku, zvedni zadeček co nejvýš a nech ho shora přirážet. Cíl: čtyři minuty a ten úhel neztratit.|240|na_brise",
    "Nahoře a polibek: Jezdi na něm čelem k sobě a celou dobu se líbejte. Cíl: čtyři minuty a polibek ani jednou nepřerušit.|240|ona_nahore",
    "Boky v jeho dlaních: Nasaď se na něj a nech si pevně sevřít boky mezi jeho dlaněmi. Cíl: čtyři minuty a tempo přírazů ať řídí jen jeho ruce.|240|ona_nahore",
    "Jeho dlaně na tobě: Jezdi na něm a dej si jeho jednu ruku na krk a druhou na prsa. Bez tlaku. Cíl: na stop ruce hned sundat.|240|ona_nahore",
    "Plácnutí při jízdě: Jezdi na něm a nech se mezi tím vždycky lehce plácnout po zadečku. Cíl: deset plácnutí za čtyři minuty.|240|ona_nahore",
    "Střídavá kontrola: Minutu řídíš tempo přírazů ty shora, minutu on zespodu, a tak dokola. Cíl: pět výměn a ani jednou se nepřerušit.|300|ona_nahore",
    "Nádech při každém sestupu: Jezdi na něm a při každém sestupu se zhluboka nadechni. Cíl: padesát pohybů a ani jeden bez nádechu.|300|ona_nahore",
    "Opřená o jeho hrudník: Nakloň se na něm dopředu, opři se mu rukama o hrudník a jezdi na něm. Cíl: čtyři minuty a ani jednou se nenarovnat.|240|ona_nahore",
    "Ruce za zády nahoře: Jezdi na něm s rukama za zády a nech se od něj držet. Cíl: čtyři minuty a ani jednou ruce nevyndat.|240|ona_nahore",
    "Nakloněná k jeho kolenům: Jezdi na něm zády nakloněná dopředu k jeho kolenům. Cíl: čtyři minuty a nechat se celou dobu držet za boky.|240|ona_nahore_zady",
    "Zády a hluboko: Jezdíš na něm zády a nakloníš se dopředu, úhel přírazů je úplně jiný. Cíl: pět minut a říct si, kde to sedí nejlíp.|300|ona_nahore_zady",
    "Zvednutá pod břichem: Nech ho vniknout zezadu, chytit tě pod břichem a zvednout si tě k sobě. Cíl: čtyři minuty přírazů a ani jednou tě nesmí položit.|240|zezadu",
    "Poslední centimetry: Klečíš, on je v tobě a přiráží jen v posledních centimetrech. Cíl: pět minut a ani jednou nezajet hlouběji.|300|zezadu",
    "Ruka dozadu: Nech ho přirážet zezadu, podej mu dozadu ruku a nech si prsty proplést s jeho. Cíl: čtyři minuty a ruku nerozpojit.|240|zezadu",
    "Vzpřímeně za tebou: Klekni si a nech ho vzpřímeně kleknout za tebe, vniknout a držet tě za boky. Cíl: čtyři minuty přírazů a udržet rovnováhu.|240|zezadu_vzpr",
    "Zezadu a vibrátor: Přiráží do tebe zezadu a zepředu ti přikládá vibrátor na klitoris. Cíl: pět minut a nepustit ho celou dobu.|300|zezadu!",
    "Ať se jen dívá: Jezdi na něm a nech ho jen ležet a dívat se, jak se snažíš. Cíl: pět minut a nesmí ti pomoct jediným pohybem.|300|ona_nahore",
    "Konec v objetí: Nasaď se mu na klín, zůstaň v klidu a jen se objímejte. Cíl: dvě minuty, při kterých se ani jeden nepohne.|120|klin_celem",
  ],
});
