// Kategorie 4 – Sex a polohy
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 4,
  name: "Sex a polohy",
  description: "Polohy po celém bytě, vibrace, první pouta a lehké plácnutí. Konečně naplno.",

  // Úkoly pro muže – pro potěšení ženy
  male: [
    "Posaď ji na kuchyňskou linku, přitáhni si ji za boky k okraji a pomalu do ní vnikni. Líbejte se přitom.|180",
    "Miluj se s ní v misionáři s polštářem pod jejím zadečkem – pomalu a hluboko, dívej se jí přitom do očí.|180",
    "Ona klečí na gauči opřená o opěradlo a ty do ní vnikneš zezadu. Tempo určuje ona tím, jak proti tobě přiráží.|180",
    "Při sexu v misionáři jí drž vibrátor na klitorisu.|180",
    "Lehněte si na bok do lžičky, ty za ní, a vnikni do ní zezadu. Přirážej pomalu, jednou rukou jí hlaď klitoris, druhou prsa.|240",
    "Opři ji o zeď v chodbě, zvedni jí jednu nohu a miluj se s ní vestoje.|120",
    "Nasaď jí pouta s rukama před tělem a miluj se s ní v misionáři. Ruce jí přidrž nad hlavou.|180",
    "Sedni si na židli bez opěrek, ona si na tebe sedne obkročmo čelem k tobě. Rukama na jejích bocích jí pomáhej s pohybem.|180",
    "Pomalu do ní vnikni jen špičkou a zase vyjdi. Desetkrát. Pak jednou pomalu celý a hluboko.",
    "Ona leží na zádech na kraji postele, ty stojíš a její nohy si dáš na ramena. Pak se s ní miluj.|180",
    "Ona se předkloní a opře o kuchyňský stůl, ty ji zezadu držíš za boky a miluješ se s ní.|180",
    "Plácni ji bičíkem lehce přes zadeček třikrát a pak do ní zezadu pomalu vnikni.",
    "Miluj se s ní a zastav se úplně vždy, když se blíží vrchol. Nech ji chvilku čekat.|240",
    "Ve sprše se ona opře rukama o stěnu a ty do ní vnikneš zezadu. Pozor, ať neuklouznete.|120",
    "V misionáři se skoro nehýbej – jen pomalu krouž boky a tlač pánví na její klitoris.|120",
    "Lehni si na záda a nech ji na sobě jezdit. Přikládej jí přitom vibrátor na klitoris.|180",
    "Zavaž jí oči a miluj se s ní v jakékoli poloze. Každou minutu změň tempo.|240",
    "Posaď ji na pračku, roztáhni jí nohy a miluj se s ní vestoje.|120",
    "Dej jí ruce za záda a drž jí zápěstí jednou rukou, zatímco ji zezadu na posteli miluješ.|120",
    "Poloha „na žabku“: ona leží na zádech s koleny u prsou, ty klečíš a přirážíš hluboko.|120",
    "Ona leží na gauči na boku, ty klečíš, její horní nohu si opřeš o rameno a vnikneš do ní.|180",
    "Každých 30 vteřin změňte polohu. Ty vybíráš.|180",
    "Miluj se s ní před zrcadlem tak, aby se na vás mohla dívat.|180",
    "Jen hluboké, pomalé přírazy – a po každém chvíli zůstaň hluboko v ní a zakruť boky.|120",
    "Ona leží na břiše s polštářem pod boky, ty si lehneš na ni a pomalu přirážíš zezadu.|180",
    "Při sexu jí jemně stiskni bradavky a řekni jí, jak úžasně se v ní cítíš.|120",
    "Nasaď jí pouta s rukama za zády, polož ji na postel na břicho a miluj se s ní zezadu.|180",
    "Polož ji zády na jídelní stůl, zvedni si její nohy k hrudi a miluj se s ní vestoje.|180",
    "Sedni si do křesla, ona si sedne na tebe zády k tobě. Hlaď jí klitoris, zatímco na tobě jezdí.|180",
    "Miluj se s ní a ona smí dojít jen tehdy, až jí to dovolíš. Pak jí to dovol.",
    "Miluj se s ní 30 vteřin rychle a intenzivně, pak 30 vteřin pomalu. Opakuj.|180",
    "V misionáři ať ti omotá nohy kolem pasu. Líbej ji přitom na krk.|180",
    "Ona klečí na posteli a ty do ní vnikneš zezadu. Vlasy jí přitom jemně drž v culíku.|120",
    "Poručte si navzájem: ty jí řekneš polohu, ona tempo. Plňte to přesně.|180",
    "Pomalu do ní vnikni a nehýbej se, dokud tě sama nepopožene.",
    "V koupelně se ona opře o umyvadlo před zrcadlem a ty do ní vnikneš zezadu. Dívejte se na sebe do zrcadla.|120",
    "Miluj se s ní na dece nebo koberci v obýváku v misionáři – pomalu a hluboko.|180",
    "Při sexu zezadu jí dej do ruky vibrátor, ať si ho sama drží na klitorisu.|180",
    "Při sexu zezadu ji plácej dlaní po zadečku do rytmu přírazů – ne moc silně.|90",
    "Ona leží na zádech na kraji gauče, ty klečíš na zemi. Přitáhni si její boky k sobě a miluj se s ní.|180",
    "Miluj se s ní vleže na boku čelem k sobě – nohy propletené, rty u sebe.|180",
    "Chyť ji jemně za zápěstí a přidrž jí je nad hlavou na posteli. Pak ji pomalu miluj.|180",
    "Miluj ji vestoje zezadu u okna se zataženými závěsy, ona se drží parapetu.|120",
    "Poloha „kovadlina“: ona leží na zádech a přitáhne si nohy k hlavě (jen pokud je to pro ni pohodlné), ty přirážíš shora.|90",
    "Sedni si na kraj postele, ona si sedne na tvůj klín čelem k tobě a obejme tě nohama.|180",
    "Spoutej jí ruce pouty nad hlavou (třeba k čelu postele) a pomalu se s ní miluj v misionáři.|180",
    "Vyzkoušejte polohu, kterou jste ještě nikdy nedělali. Ty vybíráš.|180",
    "Miluj se s ní a po každém třetím přírazu jí polib bradavku.|120",
    "Ona se opře lokty o kuchyňskou linku a ty do ní vnikneš zezadu. Hlaď ji přitom po zádech.|180",
    "Sedni si na gauč, ona si na tebe sedne zády k tobě a opře se rukama o tvá kolena.|180",
    "Při sexu jí šeptej do ucha přesně, co s ní děláš a jak se ti to líbí.|120",
    "Při sexu použij oba vibrátory: jeden jí přilož na klitoris, druhý ke kořeni svého penisu, ať vibrace cítíte oba.|180",
    "Rozkaž jí, ať se otočí a předkloní. Pak ji odměň pomalými přírazy zezadu.|120",
    "Ona leží na zádech s nohama u sebe, ty jsi nad ní a její nohy máš mezi svými – bude to těsnější.|120",
    "Miluj se s ní na jídelní židli: ty sedíš, ona na tobě sedí obkročmo a opírá se o stůl za sebou.|180",
    "Při sexu z ní vyjdi, olízni ji a pak do ní zase vnikni. Třikrát dokola.",
    "Lehni si na ni zezadu, když leží na břiše, a propleť s ní prsty nad hlavou.|180",
    "Miluj ji zezadu na gauči, zatímco si ona hladí klitoris vibrátorem. Tempo řídíš ty.|180",
    "Plácni ji bičíkem lehce po vnitřní straně stehen a hned do ní pomalu vnikni.",
    "Zvedni ji do náruče, ať tě obejme nohama, a udělej pár přírazů vestoje. Pak ji polož na postel (jen pokud to bezpečně zvládnete).|60",
    "Miluj se s ní v misionáři a po každých 10 přírazech ji polib a řekni jí, co na ní miluješ.|180",
    "Ona leží na posteli na boku, ty klečíš za ní, držíš její horní nohu nahoře a vnikneš do ní.|180",
    "Hraj si s rytmem: 9 mělkých přírazů a 1 hluboký, pak 8 mělkých a 2 hluboké – a tak dál až k 1 mělkému a 9 hlubokým.",
    "Nasaď jí pouta, sedni si na gauč a posaď si ji na klín zády k sobě. Hlaď ji, zatímco se na tobě pohybuje.|180",
    "Ona si sedne na okraj vany, ty klečíš ve vaně před ní a miluješ se s ní.|120",
    "Otoč ji zády k sobě u dveří ložnice, přitiskni ji ke dveřím a vnikni do ní zezadu.|120",
    "Poruč jí, že nesmí vydat ani hlásku. Pak ji miluj tak dobře, aby to nevydržela.|120",
    "Ona je nahoře, ale ty ji držíš za boky a určuješ tempo zespodu.|180",
    "Miluj se s ní a po každé minutě se zastav a zeptej se: rychleji, pomaleji, nebo silněji?|240",
    "Ona leží na zádech s nohama opřenýma o tvůj hrudník, ty klečíš a miluješ se s ní. Hlaď jí přitom chodidla.|120",
    "Miluj ji zezadu vestoje, ona si přitom opře jednu nohu o židli nebo okraj vany.|120",
    "Lehni si na záda a nech ji nahoře. Mezi vašimi těly jí drž vibrátor přitisknutý na klitoris.|180",
    "Jemně jí polož ruku na krk (bez tlaku na hrdlo), dívej se jí do očí a pomalu přirážej.|120",
    "Ona leží na zádech na kraji jídelního stolu, ty stojíš a miluješ se s ní. Jednou rukou jí hlaď klitoris.|180",
    "Při sexu zezadu jí dej 5 plácnutí bičíkem na zadeček – ona je počítá nahlas.",
    "Lehněte si pod deku na gauč do lžičky a miluj ji zezadu pomalu a líně, s polibky na krk.|240",
    "Miluj se s ní v poloze, kterou si vybere – a dej do toho všechno.|240",
    "Zavaž jí oči a přikaž jí, ať si lehne na záda a roztáhne nohy. Nech ji chvíli čekat a teprve pak do ní pomalu vnikni.",
    "V misionáři se posuň trochu výš a přirážej pánví tak, aby ses třel o její klitoris.|120",
    "Ona klečí na zemi u gauče a hrudníkem se opírá o sedák, ty do ní vnikneš zezadu.|180",
    "Obrácená jezdkyně: ležíš na zádech a ona na tobě sedí zády k tobě. Hlaď ji po zadečku a zádech.|180",
    "Při sexu jí jemně chytni vlasy u kořínků a zakloň jí hlavu, pak ji polib na krk.|90",
    "Ona stojí u kuchyňské linky a ty ji miluješ zezadu, oběma rukama jí přitom hladíš prsa.|120",
    "Miluj se s ní co nejpomaleji – každý příraz ať trvá aspoň 5 vteřin.|180",
    "Spoutej jí ruce pouty za zády a nech ji, ať si na tebe sedne. Ty ji držíš za boky, ať nespadne.|180",
    "V misionáři se přestaň hýbat a jen ji líbej. Hýbat se smí jen ona pod tebou.|120",
    "Vyzkoušejte polohu „nůžky“: ležíte na boku, nohy máte propletené do tvaru X a ty do ní vnikneš.|180",
    "Ona leží na břiše, vsuň jí pod klín vibrátor přitisknutý na klitoris a miluj ji zezadu.|180",
    "Při každém hlubokém přírazu jí řekni, že je tvoje. Při každém mělkém, že je krásná.|120",
    "Rozkaž jí, ať si sedne na kraj stolu a roztáhne nohy. Dívej se na ni 10 vteřin a pak ji miluj.|180",
    "Ona leží na zádech se zvednutýma a roztaženýma nohama, ty ji držíš za kotníky a miluješ se s ní.|120",
    "V chodbě se ona opře rukama o zeď a ty ji miluješ vestoje zezadu, jednou rukou ji přitom hladíš mezi nohama.|120",
    "Miluj se s ní a popros ji, ať ti řekne, až bude blízko. Pak zrychli.",
    "Sedni si na gauč, ona si nad tebe klekne obkročmo a pomalu si na tebe sedá.|180",
    "Při sexu v misionáři jí vezmi zápěstí a přidrž je u polštáře. Pak zpomal.|120",
    "Plácni ji dvakrát dlaní po zadečku, pak ho pohlaď a polib. A pak do ní vnikni zezadu.",
    "Miluj se s ní na pračce – ona sedí, ty stojíš.|120",
    "Poloha lotos: sedíš na posteli se zkříženýma nohama a ona ti sedí obkročmo na klíně. Pomalu se spolu houpejte.|180",
    "Ona klečí na posteli, ty ji miluješ zezadu a vibrátorem jí zespodu hladíš klitoris.|180",
    "Při sexu vystřídejte tři polohy, ale při přechodu z ní nevyklouzni.",
    "Miluj se s ní v misionáři hluboko a každých 20 vteřin jí olízni bradavku.|180",
    "Připoutej jí ruce pouty k čelu postele, zavaž jí oči a miluj se s ní. Ona neví, kdy přijde další příraz.|180",
    "Ona se předkloní přes opěradlo gauče a ty ji miluješ vestoje zezadu.|120",
    "Rozkaž jí, ať tě prosí o každý příraz. Když poprosí, splň to.|120",
    "Ona leží na zádech na gauči s jednou nohou na opěradle, ty jsi mezi jejíma nohama a miluješ se s ní.|180",
    "Ať si lehne na posteli na břicho s nohama u sebe. Lehni si na ni obkročmo a vnikni do ní zezadu.|180",
    "Při sexu jí palcem kruž po klitorisu. Nepřestávej, dokud nedojde.",
    "Ve sprše stojí ona zády k tobě s nohou na okraji vany a ty do ní vnikneš zezadu. Voda teče na vás oba.|120",
    "Postav ji před zrcadlo, ať se opře rukama o komodu, a vnikni do ní zezadu. Dívej se jí v zrcadle do očí.|120",
    "Zatímco ji miluješ v misionáři, přikaž jí, ať si sama hladí prsa a nepřestává.|180",
    "Když na tobě jezdí, lehce ji plácni bičíkem přes stehno pokaždé, když zpomalí.|120",
    "Ona leží na břiše, ty na boku těsně vedle ní a vnikneš do ní zezadu.|180",
    "Nech ji ležet na kraji postele s nohama na zemi, zvedni jí boky a miluj se s ní vkleče.|180",
    "Zakaž jí dotýkat se tebe rukama. Když tě chytí, zpomal na minimum.|180",
    "Nech ji, ať si vybere místo v bytě, kde jste to ještě nedělali. Tam se s ní miluj.",
    "Dopřej jí orgasmus – jakkoli chceš, ale ona musí dojít první.",

    // Karty s cílem
    "Jezdkyně: Lehni si na záda, ona si na tebe sedne obkročmo a zavede si tě do sebe. Ty se nesmíš hýbat, jen jí palcem hladíš klitoris. Cíl: aby dosáhla vrcholu jen svými pohyby.|240",
    "Lžička s vibrátorem: Oba ležíte na boku, ty za ní, a vnikneš do ní zezadu. Ona si drží vibrátor na klitorisu. Cíl: přirážet pomalu a hluboko, dokud nedojde.|240",
    "Obrácená jezdkyně na gauči: Ty sedíš na gauči, ona si na tebe sedne zády k tobě a opře se rukama o tvá kolena. Cíl: držet ji za boky a pomáhat jí s rytmem tři minuty bez zastavení.|180",
    "Pět poloh za pět minut: Každou minutu změňte polohu: misionář → ona nahoře → zezadu na kolenou → lžička → ona na kraji postele. Cíl: nevyklouznout při přechodu víc než dvakrát.|300",
    "Kraj stolu: Ona leží zády na jídelním stole se zadečkem na kraji, ty stojíš a její kotníky máš na ramenou. Cíl: třicet pomalých hlubokých přírazů, pak třicet rychlých.|180",
    "Na loktech: Ona klečí na posteli opřená o lokty se zadečkem nahoře, ty zezadu. Jednou rukou ji hladíš po zádech. Cíl: po každém desátém přírazu zůstat hluboko 3 vteřiny.|180",
    "Spoutané ruce vpředu: Nasaď jí pouta s rukama před tělem. Ona leží na zádech s rukama nad hlavou, ty jí je přidržuješ a miluješ se s ní v misionáři. Cíl: celou dobu se jí dívat do očí.|180",
    "Noha nahoru: Ona stojí zády ke zdi, jednu nohu jí zvedneš a podepřeš v podkolení. Vnikni do ní vestoje. Cíl: najít úhel, při kterém se tvoje pánev tře o její klitoris.|120",
    "Houpačka: Sedni si na pevnou židli bez opěrek, ona si sedne obkročmo čelem k tobě. Opřete se čely a houpejte se místo přirážení. Cíl: tři minuty něžného tempa s polibky.|180",
    "Její číslo: Ona zvolí číslo od 20 do 50. Uděláš přesně tolik přírazů, každý pomalejší a hlubší. Cíl: na konci se zeptat, jestli chce ještě jednou tolik.",
    "Kolébka: Ona leží na zádech s koleny u prsou a chodidly na tvém hrudníku, ty klečíš. Cíl: tlačit pomalu, aby cítila každý centimetr – dvě minuty.|120",
    "Oči v zrcadle: Ona stojí předkloněná, rukama opřená o komodu před zrcadlem, ty zezadu. Cíl: dívat se jí do očí v zrcadle – kdo první uhne, zrychluje.|180",
    "Bičík po deseti: Ona je na všech čtyřech na posteli, ty zezadu. Po každých deseti přírazech jí dej lehké plácnutí bičíkem na zadeček. Cíl: ona určuje, jestli silněji, nebo jemněji.|180",
    "Těsný misionář: Ona leží na zádech s nataženýma nohama u sebe, ty klečíš obkročmo nad jejími stehny. Cíl: pomalé přírazy v těsném sevření, dokud nezasténá.|180",
    "Linka zezadu s rukou: Ona se opře předloktími o kuchyňskou linku a vystrčí zadeček, ty jsi zezadu a jednu ruku máš na jejím klitorisu. Cíl: ruka ve stejném rytmu jako přírazy.|180",
    "Jízda na povel: Ona je nahoře a ty říkáš jen „rychleji“, „pomaleji“, „hlouběji“ a „zastav“. Cíl: řídit ji hlasem až k jejímu orgasmu.|240",
    "Ona první: Miluj se s ní pět minut a nesmíš dojít. Když se blížíš, zastav a hlaď ji rukou. Cíl: ona musí dojít jako první.|300",
    "Okraj vany: Ona sedí na kraji vany na ručníku, ty klečíš na podložce a vnikneš do ní. Cíl: pomalé přírazy, zatímco na vás teče sprcha.|120",
    "Zápěstí za zády: Ona se přehne přes opěradlo gauče a ty jí zezadu držíš obě zápěstí za zády. Cíl: při každém přírazu si ji jemně přitáhnout za zápěstí.|120",
    "Nůžky čelem: Ona leží na boku, ty na boku čelem k ní, její horní noha je přes tvůj bok. Cíl: pomalé přírazy a líbání bez přestávky.|180",
    "Polštář pod klínem: Ona leží na břiše se dvěma polštáři pod boky, ty ležíš na ní zezadu. Cíl: přirážet tak, aby se klitorisem třela o polštář.|180",
    "Tep: Ona ti položí ruku na srdce. Přirážej v rytmu svého tepu. Cíl: jak se ti zrychluje tep, zrychluje i tempo.|180",
    "Klika u dveří: Přitiskni ji čelem ke dveřím ložnice, ona se opírá dlaněmi, ty zezadu vestoje s rukama na jejích prsou. Cíl: aby se musela chytit kliky.|120",
    "Čtyři styly jízdy: Ona je nahoře a každou minutu změní styl – nahoru a dolů, krouživě, dopředu a dozadu, rychle. Cíl: najít její oblíbený a v něm ji nechat dojít.|240",
    "Bičík na stehno: Misionář s jejíma nohama od sebe. Při každém hlubokém přírazu jí lehce přetáhni bičíkem vnější stranu stehna. Cíl: deset plácnutí, sílu určuje ona.|120",
    "Poloviční start: Vnikni do ní jen do poloviny a 30 vteřin se hýbej jen nepatrně. Pak pomalu celý. Cíl: aby si tě sama stáhla hlouběji.|90",
    "Líný gauč: Lehněte si na gauč do lžičky pod deku a miluj ji líně, skoro bez pohybu, s rukou na jejím klínu. Cíl: udržet to pět minut.|300",
    "Linka a paty: Posaď ji na kraj kuchyňské linky a vnikni do ní vestoje. Ona tě obejme nohama. Cíl: tři minuty, tempo řídí ona patami na tvém zadku.|180",
    "Poslepu aranžovaná: Zavaž jí oči a rukama ji aranžuj do polohy – otoč ji, zvedni jí nohu, předkloň ji – a pak do ní vnikni. Cíl: tři různé polohy, každou pozná až tělem.|240",
    "Motýl: Ona leží na zádech na kraji postele, boky má na polštáři a nohy na tvých ramenou. Ty stojíš a držíš ji za boky. Cíl: přirážet pod úhlem nahoru, na bod G.|180",
    "Spoutaná jezdkyně: Nasaď jí pouta za zády a pomoz jí posadit se na tebe. Držíš ji za boky, aby nespadla. Cíl: ona se hýbe jen boky, ty ji jen držíš.|180",
    "Bez rukou oba: Ani jeden z vás nesmí použít ruce. Najděte polohu a milujte se. Cíl: tři minuty bez rukou.|180",
    "Mělké a hluboké: Tři mělké přírazy a jeden hluboký, pak dva a dva, pak jeden mělký a tři hluboké. Opakuj. Cíl: nesplést se v počítání.|180",
    "Přes područku: Ona leží břichem přes područku gauče s nohama na zemi, ty zezadu. Cíl: aby se musela chytit polštářů.|180",
    "Dvě otočky: Začni v misionáři, pak ji bez vytažení přetoč na bok a nakonec na břicho. Cíl: zvládnout obě otočky, aniž bys z ní vyklouzl.",
    "Kousavé polibky: V misionáři jí při každém hlubokém přírazu dej kousavý polibek na krk nebo rameno. Cíl: najít místo, kde se prohne nejvíc.|120",
    "Vibrátor mezi břichy: Misionář s vibrátorem mezi vašimi podbřišky na jejím klitorisu. Pohybuj se krouživě, ne dovnitř a ven. Cíl: aby vibrátor nevypadl a ona došla.|180",
    "Řízení nohama: Misionář, ona tě obejme nohama kolem pasu. Hýbeš se jen tehdy, když si tě patami přitáhne. Cíl: nechat se řídit dvě minuty.|120",
    "Rytmus pračky: Ona se opře o zapnutou pračku a předkloní se, ty zezadu. Cíl: přirážet v rytmu otáček.|120",
    "Lotos: Ty sedíš na posteli se zkříženýma nohama, ona ti sedí na klíně čelem k tobě a obejme tě nohama. Cíl: tři minuty houpání bez přirážení, s pohledem do očí.|180",
    "Povel otoč se: Kdykoli řekneš „otoč se“, změní polohu podle tebe. Cíl: čtyři povely za čtyři minuty – poslední poloha je její oblíbená.|240",
    "Stojící lžička u okna: Oba stojíte, ona zády k tobě u okna se zataženými závěsy. Pokrč kolena a vnikni do ní zezadu. Cíl: jednou rukou jí hladit klitoris, druhou ji držet kolem pasu.|120",
    "Každý čtvrtý: Zezadu na posteli ji plácni dlaní po zadečku při každém čtvrtém přírazu. Cíl: ona nahlas počítá do dvaceti.|180",
    "Teplo, přihořívá, hoří: Pomalými přírazy hledej úhel a ona říká „teplo“, „přihořívá“ nebo „hoří“. Cíl: najít „hoří“ a zůstat tam.|180",
    "Sedátko: Sedni si na kraj postele, ona si na tebe sedne zády k tobě s nohama přes tvá stehna a opře se o tvůj hrudník. Cíl: rukama jí hladit prsa a klitoris, dokud nedojde.|180",
    "Noha na opěradle: Ona leží na zádech na gauči, jednu nohu opřenou o opěradlo, druhou na zemi, ty klečíš mezi nimi. Cíl: každý její vzdech odměnit polibkem.|180",
    "Dovolení: Nasaď jí pouta a miluj ji. Dojít smí až na tvé „teď“. Cíl: říct „teď“ přesně ve chvíli, kdy je na hraně.",
    "Nehybný: Zůstaň v misionáři nehybně v ní a ona se musí hýbat pod tebou. Cíl: aby tě prosila, ať se pohneš.|90",
    "Ruce na zdi: Opři ji zády o zeď, zvedni jí ruce nad hlavu a drž je jednou rukou. Vnikni do ní vestoje – ať si stoupne na špičky nebo na nízkou stoličku. Cíl: dvě minuty pomalu.|120",
    "Kdo zrychlí: Miluj se s ní tak pomalu, jak to jen jde. Cíl: tři minuty – kdo první zrychlí, plní úkol navíc.|180",
    "Tři minuty, tři pravidla: První minutu úplně potichu, druhou smíte sténat, třetí musíte říkat, co cítíte. Cíl: dodržet všechna pravidla.|180",
    "Kolena k ramenům: Ona leží na koberci s koleny u tvých ramen, ty nad ní. Cíl: pomalé hluboké přírazy – a ptát se jí, jestli to není moc.|120",
    "Stisk při zrychlení: Ona na tobě jezdí a ty jí hladíš a mačkáš prsa. Cíl: kdykoli zrychlí, jemně jí stiskni bradavky.|180",
    "Vibrátor u kořene: Přilož vibrátor ke kořeni svého penisu, zatímco jsi v ní, ať vibrace přecházejí do ní. Cíl: najít polohu, kde to cítí nejvíc.|180",
    "Sázka: Milujte se v libovolné poloze. Když dojdeš dřív než ona, dlužíš jí pusu až do jejího orgasmu. Cíl: ona musí dojít tak či tak.",
    "Poloha snů: Zeptej se jí, jakou polohu si nejvíc přeje, a udělej ji co nejlépe. Cíl: po skončení ti dá známku od 1 do 10.|240",
  ],

  // Úkoly pro ženu – pro potěšení muže
  female: [
    "Posaď se na kuchyňskou linku, přitáhni si ho nohama k sobě a nech ho do sebe vniknout. Líbejte se přitom.|180",
    "Sedni si na něj na posteli a jezdi na něm pomalu a hluboko. Dívej se mu do očí.|180",
    "Klekni si na gauč, opři se o opěradlo a přirážej zadečkem proti němu. Tempo určuješ ty.|180",
    "Při sexu mu drž vibrátor na varlatech.|180",
    "Lehněte si na bok do lžičky, on za tebou. Pomalu proti němu přirážej zadečkem a jeho ruku si dej na prsa.|240",
    "Opři se o zeď v chodbě, zvedni nohu, obejmi ho s ní kolem boku a miluj se s ním vestoje.|120",
    "Nasaď mu pouta s rukama nad hlavou a jezdi na něm. Dotknout se tě nesmí.|180",
    "Posaď ho na židli bez opěrek a sedni si na něj čelem k němu.|180",
    "Sedni si na něj, pomalu do sebe pusť jen špičku a zase se nadzvedni. Desetkrát. Pak se na něj posaď celá.",
    "Lehni si na záda na kraj postele a dej mu nohy na ramena. Ruce mu dej na zadek a přitahuj si ho.|180",
    "Předkloň se, opři se o kuchyňský stůl a nech ho, ať tě miluje zezadu. Otoč se a řekni mu, ať zrychlí.|180",
    "Plácni ho bičíkem lehce přes zadek třikrát a pak se na něj posaď.",
    "Jezdi na něm a zastav se úplně vždy, když se blíží vrchol. Nech ho chvilku čekat.|240",
    "Ve sprše: opři se rukama o stěnu a vystrč na něj zadeček. Pozor, ať neuklouznete.|120",
    "Sedni si na něj a místo pohybu nahoru a dolů jen pomalu krouž boky.|120",
    "Jezdi na něm a přitom mu vibrátorem hlaď bradavky.|180",
    "Zavaž mu oči a miluj se s ním v jakékoli poloze. Každou minutu změň tempo.|240",
    "Sedni si na pračku, roztáhni nohy a přitáhni si ho.|120",
    "Nasaď mu pouta s rukama za zády, posaď ho na gauč a sedni si na něj.|180",
    "Lehni si na záda, kolena si přitáhni k prsům a nech ho přirážet hluboko.|120",
    "Lehni si na gauči na bok, horní nohu mu dej na rameno a nech ho do sebe vniknout.|180",
    "Polohový maraton: každých 30 vteřin mu řekni novou polohu a on ji musí hned zaujmout.|180",
    "Miluj se s ním před zrcadlem tak, aby se na vás mohl dívat.|180",
    "Jezdi na něm s hlubokými pomalými pohyby a dole vždy chvíli zůstaň a stáhni svaly pánevního dna.|120",
    "Lehni si na břicho s polštářem pod boky a nech ho ležet na sobě. Přirážej proti němu zadečkem.|180",
    "Při sexu mu jemně stiskni bradavky a řekni mu, jak skvěle se v tobě cítí.|120",
    "Chyť ho za zápěstí a přidrž mu je nad hlavou, zatímco na něm jezdíš.|180",
    "Lehni si na záda na jídelní stůl, nohy mu dej na ramena a nech ho, ať se s tebou miluje vestoje.|180",
    "Posaď ho do křesla a sedni si na něj zády k němu. Jeho ruce si dej na prsa.|180",
    "Jezdi na něm a on smí dojít jen tehdy, až mu to dovolíš. Pak mu to dovol.",
    "Jezdi na něm půl minuty jako o život, pak půl minuty skoro bez pohybu. Opakuj.|180",
    "Misionář – obtoč mu nohy kolem pasu a přitahuj si ho patami k sobě.|180",
    "Klekni si na posteli na všechny čtyři a nech ho, ať tě miluje zezadu. Dívej se na něj přes rameno.|120",
    "Poručte si navzájem: ty mu řekneš polohu, on tempo. Plňte to přesně.|180",
    "Posaď se na něj celá a nehýbej se, dokud tě sám nezačne prosit.",
    "V koupelně se opři o umyvadlo, on zezadu, a dívej se na něj do zrcadla.|120",
    "Na dece nebo koberci v obýváku na něm jezdi.|180",
    "Při sexu zezadu si sama přikládej vibrátor na klitoris, ať cítí vibrace i on.|180",
    "Když je nad tebou, plácej ho dlaní po zadku do rytmu, jakým chceš, aby přirážel.|90",
    "Posaď ho na kraj gauče a klekni si nad něj. Pomalu si na něj sedej.|180",
    "Miluj se s ním na boku čelem k sobě, nohy propletené, pusy u sebe.|180",
    "Obkroč ho, drž mu ruce u polštáře a pomalu na něm jezdi.|180",
    "U okna se zataženými závěsy se opři o parapet a nech ho, ať tě miluje zezadu.|120",
    "Lehni si na záda a zvedni nohy vysoko – nech ho, ať ti je drží za kotníky.|90",
    "Sedni si mu na klín na kraji postele čelem k němu a obejmi ho nohama.|180",
    "Spoutej mu ruce pouty (třeba k čelu postele nebo za zády) a pomalu na něm jezdi. Líbat tě smí, ale jen když se nakloníš ty.|180",
    "Vymysli polohu, kterou jste spolu ještě nezkusili, a naveď ho do ní.|180",
    "Jezdi na něm a po každém třetím pohybu se k němu nakloň, ať ti může políbit prsa.|120",
    "Opři se lokty o kuchyňskou linku, vystrč na něj zadeček a nech ho, ať tě miluje zezadu a hladí po zádech.|180",
    "Sedni si na něj na gauči zády k němu a opři se rukama o jeho kolena.|180",
    "Při sexu mu šeptej do ucha přesně, co ti dělá a jak se ti to líbí.|120",
    "Při sexu použij oba vibrátory: jeden mu přilož na varlata, druhý sobě na klitoris.|180",
    "Rozkaž mu, ať si lehne na záda a nehýbe se. Pak ho odměň pomalou jízdou.|120",
    "Lehni si na záda, dej nohy k sobě a nech ho do sebe vniknout – bude to pro něj těsnější.|120",
    "Posaď ho na jídelní židli a sedni si na něj obkročmo, opřená o stůl za sebou.|180",
    "Při jízdě z něj slez, olízni ho a pak si na něj zase sedni. Třikrát dokola.",
    "Lehni si na břicho a nech ho, ať si na tebe lehne a propletete prsty nad hlavou.|180",
    "Klekni si na gauč a nech ho, ať tě miluje zezadu. Mezitím mu sáhni rukou mezi nohy a hlaď mu varlata.|180",
    "Plácni ho bičíkem lehce po stehnech a hned si na něj sedni.",
    "Obejmi ho nohama kolem pasu, když stojí, a nech ho, ať tě chvíli drží (jen pokud to zvládnete bezpečně). Pak si lehni na postel a stáhni ho na sebe.|60",
    "Jezdi na něm a vždy po 10 pohybech ho polib a řekni mu, co na něm miluješ.|180",
    "Lehni si na posteli na bok a nech ho klečet za tebou. Horní nohu mu dej do ruky a nech ho do sebe vniknout.|180",
    "Hraj si s rytmem: 9 mělkých pohybů a 1 hluboký, pak 8 mělkých a 2 hluboké – a tak dál až k 1 mělkému a 9 hlubokým.",
    "Nasaď mu pouta, posaď ho na gauč a sedni si na něj zády k němu. Pohybuj se, jak chceš ty.|180",
    "Ve vaně nebo ve sprše ho posaď na okraj vany a sedni si na něj.|120",
    "Opři se o dveře ložnice, vystrč na něj zadeček a nech ho, ať tě miluje zezadu.|120",
    "Poruč mu, že nesmí vydat ani hlásku. Pak na něm jezdi tak dobře, aby to nevydržel.|120",
    "Jsi nahoře, ale nech ho, ať tě drží za boky a určuje tempo zespodu.|180",
    "Miluj se s ním a po každé minutě se zastav a zeptej se: rychleji, pomaleji, nebo silněji?|240",
    "Lehni si na záda a nohy mu dej na hruď. Chodidly ho hlaď po bradavkách.|120",
    "Postav se zády k němu, opři si jednu nohu o židli nebo okraj vany a přitáhni si ho, ať tě miluje zezadu.|120",
    "Jezdi na něm a sama si přitom přikládej vibrátor na klitoris. Ať se dívá.|180",
    "Když na něm jezdíš, polož mu ruce kolem krku (bez tlaku), dívej se mu do očí a pomalu se pohybuj.|120",
    "Lehni si na záda na kraj jídelního stolu a nech ho, ať se s tebou miluje vestoje. Jednou rukou mu hlaď varlata.|180",
    "Když je v tobě zezadu, dej mu do ruky bičík a nech ho, ať ti dá 5 lehkých plácnutí. Počítej nahlas.",
    "Lehněte si pod deku na gauč do lžičky a pomalu, líně proti němu přirážej zadečkem.|240",
    "Miluj se s ním v poloze, kterou si vybere – a dej do toho všechno.|240",
    "Zavaž mu oči a přikaž mu, ať si lehne na záda. Nech ho chvíli čekat, a pak si na něj pomalu sedni.",
    "Jezdi na něm a otírej se klitorisem o jeho pánev – pomalými krouživými pohyby.|120",
    "Klekni si na zem u gauče a hrudníkem se opři o sedák. Nech ho, ať tě miluje zezadu.|180",
    "Když leží na zádech, sedni si na něj zády k němu a nakloň se dopředu, ať vidí všechno.|180",
    "Při sexu ho chytni za vlasy a přitáhni si jeho pusu ke krku.|90",
    "Stoupni si k lince, vystrč zadeček, nech ho, ať tě miluje zezadu, a jeho ruce si dej na prsa.|120",
    "Miluj se s ním co nejpomaleji – každý pohyb ať trvá aspoň 5 vteřin.|180",
    "Spoutej mu ruce pouty za zády, posaď ho na kraj postele a sedni si na něj.|180",
    "V misionáři se pod ním nehýbej a jen ho líbej. Hýbat se smí jen on.|120",
    "Lehni si na bok, propleť s ním nohy do „nůžek“ a přirážej proti němu.|180",
    "Lehni si na břicho a vibrátor si dej pod sebe ke klitorisu. Nech ho, ať tě miluje zezadu – vibrace ucítí i on.|180",
    "Při každém hlubokém pohybu mu řekni, že je tvůj. Při každém mělkém, že je úžasný.|120",
    "Rozkaž mu, ať si sedne na židli a nehne se. Tanči před ním 10 vteřin a pak si na něj sedni.|180",
    "Lehni si na záda, zvedni nohy a roztáhni je. Nech ho, ať tě drží za kotníky.|120",
    "Opři se rukama o zeď v chodbě a nech ho, ať tě miluje zezadu. Jeho ruku si dej mezi nohy.|120",
    "Jezdi na něm a popros ho, ať ti řekne, až bude blízko. Pak zpomal – a pak zrychli.",
    "Posaď ho na gauč, klekni si obkročmo nad něj a pomalu si na něj sedej.|180",
    "Chyť ho při misionáři za zadek a přitahuj si ho do sebe tak, jak to chceš ty.|120",
    "Plácni ho dvakrát po zadku dlaní, pak ho pohlaď a polib. A pak se mu nastav zezadu.",
    "Sedni si na pračku a přitáhni si ho mezi nohy, ať se s tebou miluje vestoje.|120",
    "Poloha lotos: on sedí se zkříženýma nohama a ty mu sedíš obkročmo na klíně. Pomalu se spolu houpejte.|180",
    "Klekni si na posteli a nech ho, ať tě miluje zezadu. Jednou rukou mu zespodu mezi svýma nohama hlaď varlata.|180",
    "Při sexu vystřídejte tři polohy, ale nenech ho z tebe vyklouznout.",
    "Jezdi na něm pomalu a hluboko a každých 20 vteřin mu olízni bradavku.|180",
    "Nasaď mu pouta, zavaž mu oči a jezdi na něm. Nebude vědět, kdy přijde další pohyb.|180",
    "Předkloň se přes opěradlo gauče a nech ho, ať tě miluje vestoje zezadu.|120",
    "Rozkaž mu, ať tě prosí o každý pohyb. Když poprosí, splň to.|120",
    "Lehni si na gauč na záda, jednu nohu dej na opěradlo a přitáhni si ho mezi nohy.|180",
    "Lehni si na posteli na břicho, dej nohy k sobě a nech ho, ať si na tebe lehne obkročmo a vnikne do tebe zezadu.|180",
    "Při sexu mu prsty masíruj hráz a nepřestávej.|180",
    "Ve sprše: stoupni si zády k němu, nohu dej na okraj vany a přitáhni si ho.|120",
    "Opři se rukama o komodu před zrcadlem a nech ho, ať tě miluje zezadu. Dívej se mu v zrcadle do očí.|120",
    "Zatímco na něm jezdíš, přikaž mu, ať ti hladí prsa a nepřestává.|180",
    "Když tě miluje, plácni ho lehce bičíkem přes stehno pokaždé, když zpomalí.|120",
    "Lehni si na břicho a nech ho, ať si lehne na bok těsně vedle tebe a vnikne do tebe zezadu.|180",
    "Posaď ho na kraj postele s nohama na zemi a sedni si na něj čelem k němu.|180",
    "Zakaž mu dotýkat se tě rukama. Když tě chytí, zpomal na minimum.|180",
    "Vyber místo v bytě, kde jste to ještě nedělali. Tam se s ním miluj.",
    "Dopřej mu orgasmus – způsob vybíráš ty.",

    // Karty s cílem
    "Jezdkyně: Posaď se na něj obkročmo, když leží na zádech, a zaveď si ho do sebe. On se nesmí hýbat. Cíl: dovést ho k vrcholu jen svými boky – nejdřív pomalu, pak rychle.|240",
    "Lžička s vibracemi: Lehni si na bok zády k němu a nech ho vniknout zezadu. Sáhni si mezi nohy a přikládej mu vibrátor na varlata. Cíl: aby sám zrychlil.|240",
    "Obrácená kovbojka: On leží na zádech, ty si na něj sedneš zády k němu, předkloníš se a opřeš se o jeho stehna. Cíl: ať vidí všechno – tři minuty podle tvého rytmu.|180",
    "Pět poloh podle tebe: Ty určuješ každou minutu novou polohu – ty nahoře, zezadu, lžička, misionář, kraj postele. Cíl: nenechat ho vyklouznout víc než dvakrát.|300",
    "Kotníky na ramenou: Lehni si zády na jídelní stůl se zadečkem na kraji a kotníky mu dej na ramena. Cíl: rukama na jeho zadku si ho tahat do sebe – třicet pomalých, třicet rychlých.|180",
    "Prohnutá kočka: Klekni si na posteli na lokty, prohni záda a vystrč zadeček, ať tě miluje zezadu. Cíl: po každém desátém přírazu se proti němu zatlačit a zůstat 3 vteřiny.|180",
    "Pouta nahoru: Nasaď mu pouta s rukama nad hlavou, sedni si na něj a miluj se s ním. Cíl: dívat se mu do očí a nedovolit mu je zavřít.|180",
    "Noha na jeho boku: Opři se zády o zeď a zvedni jednu nohu na jeho bok. Nech ho vniknout vestoje. Cíl: pohybovat pánví proti němu tak, aby to bylo nejlepší pro oba.|120",
    "Čelo na čelo: On sedí na pevné židli, ty obkročmo čelem k němu. Opřete se čely a houpejte se. Cíl: tři minuty pomalu s polibky.|180",
    "Tvoje číslo: Řekni mu číslo od 20 do 50 a udělej na něm přesně tolik pohybů – každý pomalejší a hlubší. Cíl: na konci se zeptat, jestli chce ještě jednou tolik.",
    "Chodidla na hrudi: Lehni si na záda, přitáhni kolena k prsům a chodidla mu opři o hrudník. Cíl: chodidly řídit, jak hluboko smí – dvě minuty.|120",
    "Zrcadlová výzva: Opři se o komodu před zrcadlem a nech ho, ať tě miluje zezadu. Cíl: dívat se mu do očí v zrcadle – kdo první uhne, zrychluje.|180",
    "Bičík pro něj po deseti: Jsi nahoře a po každých deseti pohybech mu dej lehké plácnutí bičíkem na stehno. Cíl: on řekne, jestli silněji, nebo jemněji.|180",
    "Svírání: Lehni si na břicho s nohama u sebe a nech ho lehnout si na tebe zezadu. Cíl: stisknout svaly pánevního dna při každém jeho přírazu.|180",
    "Zadeček proti němu: Opři se předloktími o kuchyňskou linku, vystrč zadeček a nech ho, ať tě miluje zezadu. Cíl: přirážet proti němu a určovat tempo sama.|180",
    "Plnění povelů: Jsi nahoře a on ti smí říkat jen „rychleji“, „pomaleji“, „hlouběji“ a „zastav“. Cíl: splnit každý povel, dokud se neudělá.|240",
    "Dojde na tvůj povel: Miluj se s ním pět minut a on nesmí dojít. Když se blíží, zpomal a stiskni ho svaly. Cíl: nechat ho dojít až na tvé „teď“.|300",
    "Na okraji vany: Posaď ho na kraj vany na ručník a sedni si na něj obkročmo. Cíl: pomalé houpání, zatímco na vás teče sprcha.|120",
    "Přišpendlené ruce: Jsi nahoře a držíš mu zápěstí přitisknutá k posteli nad hlavou. Cíl: nepustit ho, dokud neřekne „prosím“.|120",
    "Nůžky pro něj: Lehni si na bok, přehoď mu horní nohu přes bok a nech ho vniknout. Cíl: líbat se po celou dobu bez přestávky.|180",
    "Polštář pod tebou: Lehni si na břicho s polštářem pod boky a nech ho ležet na tobě. Cíl: tlačit zadeček nahoru proti němu, aby se ti klitoris třel o polštář.|180",
    "Tempo podle jeho srdce: Polož ruku na jeho srdce a pohybuj se na něm v rytmu jeho tepu. Cíl: jak se mu zrychluje tep, zrychluj i ty.|180",
    "Čelem ke dveřím: Opři se dlaněmi o zavřené dveře ložnice a nech ho, ať tě miluje vestoje zezadu. Jeho ruce si dej na prsa. Cíl: aby tě musel držet, protože se ti podlamují kolena.|120",
    "Styly jízdy: Jsi nahoře a každou minutu změníš styl – nahoru a dolů, krouživě, dopředu a dozadu, rychle. Cíl: ať si vybere oblíbený a v tom to dotáhni do konce.|240",
    "Plácnutí při každém pohybu: Jsi nahoře zády k němu. Ať tě při každém tvém pohybu dolů lehce plácne dlaní po zadečku. Cíl: dvacet plácnutí, sílu určuješ ty.|120",
    "Jen špička: Sedni si na něj a vpusť do sebe jen špičku. 30 vteřin se hýbej nepatrně, pak se na něj pomalu posaď celá. Cíl: aby tě sám stáhl dolů.|90",
    "Líná lžička: Lehněte si pod deku do lžičky, on za tebou, a líně pohybuj zadečkem proti němu. Cíl: udržet to pět minut.|300",
    "Paty na jeho zadku: Sedni si na kuchyňskou linku, přitáhni si ho a obejmi ho nohama. Patami mu řiď tempo. Cíl: tři minuty – bez tvých pat nesmí zrychlit.|180",
    "Vedený poslepu: Zavaž mu oči a veď ho rukama do polohy – polož ho, otoč ho, sedni si na něj. Cíl: tři různé polohy, pozná je až tělem.|240",
    "Úhel nahoru: Lehni si na záda na kraj postele, nohy mu dej na ramena a boky podlož polštářem. Cíl: rukama na jeho bocích ho nasměrovat, aby přirážel pod úhlem nahoru.|180",
    "Spoutaný na kraji postele: Nasaď mu pouta za zády, posaď ho na kraj postele a sedni si na něj. Cíl: pohybovat se, jak chceš ty – on ti smí jen líbat prsa.|180",
    "Ruce za zády oba: Oba držíte ruce za zády. Ty vymysli, jak se na něj dostat a milovat se s ním. Cíl: tři minuty bez jediného dotyku rukou.|180",
    "Mělce a hluboko nahoře: Jsi nahoře – tři mělké pohyby a jeden hluboký, pak dva a dva, pak jeden a tři. Opakuj. Cíl: nesplést se.|180",
    "Přes područku pro něj: Lehni si břichem přes područku gauče a nech ho zezadu. Cíl: rukou na jeho stehně si ho přitahovat k sobě.|180",
    "Přetáčení: Začněte v misionáři, pak se bez vytažení přetoč nahoru na něj a nakonec zády k němu. Cíl: zvládnout obě otočky, aniž by vyklouzl.",
    "Kousnutí dolů: Jsi nahoře a při každém pohybu dolů ho kousni do ramene nebo krku. Cíl: najít místo, kde zasténá nejvíc.|120",
    "Vibrátor mezi vámi: Jsi nahoře a mezi vašimi těly držíš vibrátor na klitorisu. Cíl: krouživými pohyby ho udržet na místě, ať ho cítí i on.|180",
    "Ruce na jeho zadku: Misionář – obejmi ho a rukama na jeho zadku mu řiď každý příraz. Cíl: dvě minuty přesně podle tebe.|120",
    "Pračka zezadu: Opři se o zapnutou pračku, předkloň se a nech ho zezadu. Cíl: přirážet proti němu v rytmu otáček.|120",
    "Lotos pro něj: On sedí se zkříženýma nohama, ty mu sedíš na klíně čelem k němu s nohama za jeho zády. Cíl: tři minuty houpání s pohledem do očí.|180",
    "Otoč se, říkáš ty: Kdykoli řekneš „otoč se“, on změní polohu podle tebe. Cíl: čtyři povely za čtyři minuty – poslední je jeho oblíbená.|240",
    "Parapet: Stoupni si k oknu se zataženými závěsy zády k němu a opři se o parapet. Nech ho zezadu a jeho ruku veď na svůj klitoris. Cíl: aby hladil stejným tempem, jakým přiráží.|120",
    "Počítej plácnutí: Klečíš na posteli a on tě miluje zezadu. Při každém čtvrtém přírazu tě plácne po zadečku a ty počítáš nahlas. Cíl: do dvaceti.|180",
    "Navigace: Nech ho přirážet pomalu a naviguj ho slovy „výš“, „níž“, „hlouběji“, „přesně tak“. Cíl: dostat ho na „přesně tak“ a držet ho tam.|180",
    "Na jeho klíně zády: On sedí na kraji postele, ty mu sedíš na klíně zády k němu s nohama přes jeho stehna. Cíl: opřít se o něj a vést jeho ruce na prsa a klín.|180",
    "Noha na opěradle pro něj: Lehni si na gauč, jednu nohu dej na opěradlo, druhou na zem, a přitáhni si ho. Cíl: pokaždé, když zasténá, dostane polibek.|180",
    "Teď: Nasaď mu pouta a jezdi na něm. Dojít smí až na tvé „teď“. Cíl: říct to přesně ve chvíli, kdy je na hraně.",
    "Úplný klid: Jsi nahoře a úplně se zastav. On se musí hýbat pod tebou. Cíl: aby tě prosil, ať se pohneš.|90",
    "Na stoličce: Stoupni si zády k němu na nízkou stoličku nebo schod, ať jste ve stejné výšce, a opři se o zeď. Cíl: dvě minuty zezadu vestoje bez ztráty rovnováhy.|120",
    "Šnečí tempo: Jsi nahoře a každý pohyb nahoru a dolů trvá 5 vteřin. Cíl: tři minuty – kdyby přirazil, začínáš znovu.|180",
    "Postupně nahlas: První minutu oba potichu, druhou smíte sténat, třetí mu musíš popisovat, co právě cítíš. Cíl: dodržet všechna pravidla.|180",
    "Ruka na jeho břiše: Lehni si na koberec a kolena přitáhni k ramenům, on nad tebou. Cíl: rukou na jeho břiše mu dávat vědět, jak hluboko smí.|120",
    "Prsa k ústům: Jsi nahoře a nakloň se, ať má tvé bradavky u pusy. Cíl: kdykoli ti je saje, zrychli.|180",
    "Vibrace pro oba: Jsi nahoře a přitiskni vibrátor ke svému klitorisu tak, aby se dotýkal i jeho kořene. Cíl: najít polohu, kde vibrace cítíte oba.|180",
    "Sázka pro něj: Milujte se v libovolné poloze. Když dojdeš dřív ty, dlužíš mu ruku nebo pusu až do konce. Cíl: on musí dojít tak či tak.",
    "Jeho poloha snů: Zeptej se ho, jakou polohu chce nejvíc, a udělej ji co nejlépe. Cíl: na konci ti dá známku od 1 do 10.|240",
  ],
});
