// Kategorie 5 – Hardcore (dávka b)
// Témata: pouta a svázání, úplná deprivace, kontrolní pozice, rozkazy a poslušnost.
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 5,

  male: [
    "Spoutej jí obě ruce k čelu postele a dělej s ní půl hodiny, co chceš. Ona smí říct jen stop slovo.|300|pouta_postel",
    "Sváž jí zápěstí kravatou nad hlavou a pak ji pomalu prozkoumej celou. Uzly nesmí táhnout.|300|pouta_postel",
    "Rozepnutá a svázaná: Spoutej jí ruce k čelu postele, zavaž oči a nasaď sluchátka. Pět minut jen čeká. Cíl: nedotknout se jí dřív.|300|pouta_postel",
    "Spoutej jí ruce za zády a nech ji klečet, dokud jí to nedovolíš.|300|klek_pouta",
    "Sváž jí ruce za zády a vezmi ji zezadu, když klečí.|300|zezadu",
    "Spoutej ji, zavaž jí oči a nech ji hádat, čím se jí dotýkáš.|300|pouta_postel",
    "Přivaž jí každou ruku k jinému rohu postele. Roztažená a bezbranná.|300|pouta_postel",
    "Sváž jí kotníky k sobě a pak jí roztáhni kolena rukama.|300|nohy_ramena",
    "Pouta a příkaz: Spoutej jí ruce a dej jí jediné pravidlo – nesmí prosit. Když poprosí, přestaneš na minutu. Cíl: ať poprosí.|300|pouta_postel",
    "Spoutej ji a nech ji celou minutu jen tak ležet, než začneš.|300|pouta_postel",
    "Sváž jí ruce ke stehnům, ať se nemůže bránit, a dráždi ji vibrátorem.|300|pouta_postel",
    "Zavaž jí oči, nasaď sluchátka a pak ji miluj, aniž bys řekl slovo.|300|deprivace",
    "Úplná tma: Zavázané oči, sluchátka a spoutané ruce. Ona neví nic. Cíl: pět minut úplné nejistoty.|300|deprivace",
    "Zavaž jí oči a přikládej jí střídavě led a vibrátor.|300|deprivace",
    "Zavaž jí oči a nech ji hádat, jestli se jí dotýkáš rukou, nebo pomůckou.|300|deprivace",
    "Zavaž jí oči a nech ji čekat, dokud nezačne prosit.|300|deprivace",
    "Poruč jí, ať si klekne a dá ruce za hlavu. Nesmí je sundat.|300|klek_ruce_hlava",
    "Klek a povel: Klečí s rukama za hlavou a ty ji obcházíš. Když ruce sundá, začíná znovu. Cíl: vydržet bez pohybu.|300|klek_ruce_hlava",
    "Poruč jí, ať klečí na posteli s rukama za hlavou, a vezmi ji zezadu.|300|zezadu_vzpr",
    "Nech ji klečet a čekat, dokud jí neřekneš, že smí vstát.|240|klek_pouta",
    "Poruč jí, ať se předkloní přes opěradlo a nehne se.|300|predklon",
    "Řekni jí, že smí mluvit jen ano, pane, nebo stop slovo.|300|klek_pouta",
    "Tři rozkazy: Dáš jí tři rozkazy za sebou a každý musí splnit do tří vteřin. Cíl: žádné zaváhání.|300|klek_pouta",
    "Poruč jí, ať tě sama poprosí o to, co chce. Celou větou.|300|klek_ruce_hlava",
    "Řekni jí, ať se nehýbe, ať děláš cokoli. Za pohyb je trest.|300|pouta_postel",
    "Poruč jí, ať se na tebe celou dobu dívá a nesmí zavřít oči.|300|kontrola_vsede!",
    "Drž jí ruce nad hlavou a miluj se s ní. Nesmí se vysmeknout.|300|kontrola_vsede!",
    "Sedni si na ni, drž jí zápěstí a určuj všechno sám.|300|kontrola_vsede!",
    "Plná kontrola: Držíš jí ruce nad hlavou a ona nesmí ani jednou převzít vedení. Cíl: vydržet to celou dobu.|300|kontrola_vsede!",
    "Nech ji ležet s rukama nad hlavou a jen jí to připomeň pohledem.|300|pouta_postel",
    "Spoutej ji a mezi jednotlivými doteky dělej dlouhé pauzy.|300|pouta_postel",
    "Sváž jí ruce a pak ji nech klečet mezi tvýma nohama.|300|oral_ona_klek",
    "Spoutej ji, posaď ji na židli a nech ji dívat se, jak se svlékáš.|300|zidle_celem",
    "Sváž jí ruce ke kotníkům a nech ji ležet na boku.|300|dvojita_bok",
    "Klečící a spoutaná: Ruce za zády, klečí na podlaze, ty stojíš. Nic nedělej minutu. Cíl: nechat ji čekat.|300|klek_pouta",
    "Spoutej ji a zeptej se jí, kolik toho ještě vydrží.|300|pouta_postel",
    "Sváž jí ruce a nech ji vybrat, co s ní uděláš. Pak udělej něco jiného.|300|pouta_postel",
    "Poruč jí, ať počítá nahlas každý tvůj pohyb.|300|zezadu",
    "Zakaž jí mluvit úplně. Jen kývne nebo zavrtí hlavou.|300|pouta_postel",
    "Poruč jí, ať si sama zaváže oči a čeká na posteli.|240|deprivace",
    "Rituál: Ona ti musí říct nahlas, co dneska chce, klečíc před tebou. Teprve pak to dostane. Cíl: nechat ji to vyslovit.|300|oral_ona_klek",
    "Spoutej ji a pak jí velmi pomalu svlékej zbytek oblečení.|300|pouta_postel",
    "Sváž jí ruce a nech ji stát uprostřed pokoje, zatímco ji obcházíš.|240|klek_pouta",
    "Spoutej jí ruce za zády a nech ji na kolenou před tebou.|300|oral_ona_klek",
    "Sváž jí ruce a zvedni je nad hlavu ke zdi.|300|zed",
    "Spoutej ji a nasaď jí sluchátka. Ať tě neslyší přicházet.|300|deprivace",
    "Ticho a čekání: Spoutaná se zavázanýma očima čeká tři minuty úplně sama. Cíl: nepromluvit ani jednou.|180|deprivace",
    "Spoutej ji a přitom jí celou dobu něco šeptej do ucha.|300|pouta_postel",
    "Sváž jí ruce kravatou a nech ji, ať si sama vybere polohu.|300|pouta_postel",
    "Spoutej ji a doveď ji k vrcholu jen vibrátorem.|300|pouta_postel",
    "Spoutej ji a nech ji dojít třikrát za sebou.|300|pouta_postel",
    "Sváž jí ruce, zavaž oči a střídej pírko a bičík.|300|pouta_postel",
    "Spoutej ji a pak si na ni sedni a drž ji za boky.|300|kontrola_vsede!",
    "Pouta a pomalost: Je spoutaná a ty se hýbeš tak pomalu, jak to jde. Cíl: nezrychlit ani jednou.|300|pouta_postel",
    "Sváž jí ruce a miluj se s ní na boku.|300|dvojita_bok",
    "Spoutej ji a nech ji prosit o každou další věc zvlášť.|300|pouta_postel",
    "Poruč jí, ať se otočí a nedívá se, co chystáš.|240|zezadu",
    "Řekni jí, ať nesmí dojít bez tvého svolení. A dlouho ho nedávej.|300|pouta_postel",
    "Poruč jí, ať si klekne, a ty jí jen hlaď vlasy. Nic víc.|240|oral_ona_klek",
    "Rozkaz a odměna: Za každý bezchybně splněný rozkaz dostane jednu věc, kterou má ráda. Cíl: tři odměny.|300|klek_pouta",
    "Sváž jí ruce a přitom jí drž bradu, ať se ti dívá do očí.|300|kontrola_vsede!",
    "Spoutej ji a nech ji ležet na břiše. Pak ji vezmi zezadu.|300|na_brise",
    "Sváž jí ruce a nech ji klečet na všech čtyřech s hlavou dole.|300|zezadu",
    "Spoutej ji a nech ji rozhodnout jen o jedné jediné věci.|300|pouta_postel",
    "Poruč jí, ať tě poslouchá na slovo, a pak buď hodně konkrétní.|300|zezadu",
    "Přesně tak: Popiš jí přesně, jak má ležet, a oprav každou odchylku. Cíl: ať to sedí na centimetr.|300|pouta_postel",
    "Spoutej ji a nech ji čekat, zatímco si dáváš na čas.|240|pouta_postel",
    "Sváž jí ruce nad hlavou a olizuj ji tak dlouho, dokud neprosí.|300|pouta_postel",
    "Spoutej ji a pak ji polib, jako by se nic nedělo.|240|pouta_postel",
    "Sváž jí jednu ruku a druhou nech volnou. Ať si vybere, co s ní.|300|pouta_postel",
    "Poruč jí, ať klečí, a řekni jí, že dneska rozhoduješ ty.|300|klek_pouta",
    "Jediné slovo: Domluvte si jedno slovo, po kterém okamžitě přestaneš. Pak jdi až na hranu. Cíl: nikdy to slovo neslyšet.|300|pouta_postel",
    "Spoutej ji a mezi tím jí přejížděj ledem po celém těle.|300|pouta_postel",
    "Sváž jí ruce a nech ji stát u zdi zády k tobě.|240|zed",
    "Spoutej ji a nech ji ležet nahou, zatímco se jen díváš.|240|pouta_postel",
    "Poruč jí, ať ti řekne nahlas tři věci, které dneska udělá.|240|klek_pouta",
    "Sváž jí ruce a doveď ji na hranu pětkrát za sebou.|300|pouta_postel",
    "Spoutej ji a nech ji celou dobu mluvit, co cítí.|300|pouta_postel",
    "Poslední rozkaz: Dej jí jeden poslední rozkaz a nech ji ho splnit beze slov. Cíl: nemuset nic vysvětlovat.|240|klek_pouta",
    "Sváž jí ruce a pak jí sundej pouta, ale ona se pořád nesmí hýbat.|300|pouta_postel",
    "Spoutej ji a pak ji obejmi. Kontrast, který funguje.|180|pouta_postel",
    "Na konec jí rozvaž ruce a promasíruj jí zápěstí.|120|pouta_postel",
  ],

  female: [
    "Spoutej mu obě ruce k čelu postele a dělej s ním, co chceš. On smí říct jen stop slovo.|300|pouta_postel!",
    "Sváž mu zápěstí kravatou nad hlavou a pak ho pomalu prozkoumej celého. Uzly nesmí táhnout.|300|pouta_postel!",
    "Rozepnutý a svázaný: Spoutej mu ruce k čelu postele, zavaž oči a nasaď sluchátka. Pět minut jen čeká. Cíl: nedotknout se ho dřív.|300|pouta_postel!",
    "Spoutej mu ruce za zády a nech ho klečet, dokud mu to nedovolíš.|300|klek_pouta!",
    "Sváž mu ruce za zády a nech ho klečet, zatímco ho olizuješ zezadu.|300|zezadu!",
    "Spoutej ho, zavaž mu oči a nech ho hádat, čím se ho dotýkáš.|300|pouta_postel!",
    "Přivaž mu každou ruku k jinému rohu postele. Roztažený a bezbranný.|300|pouta_postel!",
    "Sváž mu kotníky k sobě a pak mu roztáhni kolena rukama.|300|oral_on_vleze",
    "Pouta a příkaz: Spoutej mu ruce a dej mu jediné pravidlo – nesmí prosit. Když poprosí, přestaneš na minutu. Cíl: ať poprosí.|300|pouta_postel!",
    "Spoutej ho a nech ho celou minutu jen tak ležet, než začneš.|300|pouta_postel!",
    "Sváž mu ruce ke stehnům, ať se nemůže bránit, a dráždi ho vibrátorem.|300|pouta_postel!",
    "Zavaž mu oči, nasaď sluchátka a pak si na něj sedni, aniž bys řekla slovo.|300|deprivace!",
    "Úplná tma: Zavázané oči, sluchátka a spoutané ruce. On neví nic. Cíl: pět minut úplné nejistoty.|300|deprivace!",
    "Zavaž mu oči a přikládej mu střídavě led a vibrátor.|300|deprivace!",
    "Zavaž mu oči a nech ho hádat, jestli se ho dotýkáš rukou, nebo pomůckou.|300|deprivace!",
    "Zavaž mu oči a nech ho čekat, dokud nezačne prosit.|300|deprivace!",
    "Poruč mu, ať si klekne a dá ruce za hlavu. Nesmí je sundat.|300|klek_ruce_hlava!",
    "Klek a povel: Klečí s rukama za hlavou a ty ho obcházíš. Když ruce sundá, začíná znovu. Cíl: vydržet bez pohybu.|300|klek_ruce_hlava!",
    "Poruč mu, ať klečí na posteli s rukama za hlavou, a olizuj ho zezadu.|300|zezadu_vzpr!",
    "Nech ho klečet a čekat, dokud mu neřekneš, že smí vstát.|240|klek_pouta!",
    "Poruč mu, ať se předkloní přes opěradlo a nehne se.|300|predklon!",
    "Řekni mu, že smí mluvit jen ano, paní, nebo stop slovo.|300|klek_pouta!",
    "Tři rozkazy: Dáš mu tři rozkazy za sebou a každý musí splnit do tří vteřin. Cíl: žádné zaváhání.|300|klek_pouta!",
    "Poruč mu, ať tě sám poprosí o to, co chce. Celou větou.|300|klek_ruce_hlava",
    "Řekni mu, ať se nehýbe, ať děláš cokoli. Za pohyb je trest.|300|pouta_postel!",
    "Poruč mu, ať se na tebe celou dobu dívá a nesmí zavřít oči.|300|kontrola_vsede",
    "Drž mu ruce nad hlavou a sedni si na něj. Nesmí se vysmeknout.|300|kontrola_vsede",
    "Sedni si na něj, drž mu zápěstí a určuj všechno sama.|300|kontrola_vsede",
    "Plná kontrola: Držíš mu ruce nad hlavou a on nesmí ani jednou převzít vedení. Cíl: vydržet to celou dobu.|300|kontrola_vsede",
    "Nech ho ležet s rukama nad hlavou a jen mu to připomeň pohledem.|300|pouta_postel!",
    "Spoutej ho a mezi jednotlivými doteky dělej dlouhé pauzy.|300|pouta_postel!",
    "Sváž mu ruce a pak ho nech klečet před sebou.|300|oral_ona_klek",
    "Spoutej ho, posaď ho na židli a nech ho dívat se, jak se svlékáš.|300|zidle_celem",
    "Sváž mu ruce ke kotníkům a nech ho ležet na boku.|300|dvojita_bok!",
    "Klečící a spoutaný: Ruce za zády, klečí na podlaze, ty stojíš. Nic nedělej minutu. Cíl: nechat ho čekat.|300|klek_pouta",
    "Spoutej ho a zeptej se ho, kolik toho ještě vydrží.|300|pouta_postel!",
    "Sváž mu ruce a nech ho vybrat, co s ním uděláš. Pak udělej něco jiného.|300|pouta_postel!",
    "Poruč mu, ať počítá nahlas každý tvůj pohyb.|300|ona_nahore",
    "Zakaž mu mluvit úplně. Jen kývne nebo zavrtí hlavou.|300|pouta_postel!",
    "Poruč mu, ať si sám zaváže oči a čeká na posteli.|240|deprivace!",
    "Rituál: On ti musí říct nahlas, co dneska chce, klečíc před tebou. Teprve pak to dostane. Cíl: nechat ho to vyslovit.|300|oral_ona_klek",
    "Spoutej ho a pak mu velmi pomalu svlékej zbytek oblečení.|300|pouta_postel!",
    "Sváž mu ruce a nech ho stát uprostřed pokoje, zatímco ho obcházíš.|240|klek_pouta!",
    "Spoutej mu ruce za zády a nech ho na kolenou před sebou.|300|oral_ona_klek",
    "Sváž mu ruce a zvedni je nad hlavu ke zdi.|300|zed",
    "Spoutej ho a nasaď mu sluchátka. Ať tě neslyší přicházet.|300|deprivace!",
    "Ticho a čekání: Spoutaný se zavázanýma očima čeká tři minuty úplně sám. Cíl: nepromluvit ani jednou.|180|deprivace!",
    "Spoutej ho a přitom mu celou dobu něco šeptej do ucha.|300|pouta_postel!",
    "Sváž mu ruce kravatou a nech ho, ať si sám vybere polohu.|300|pouta_postel!",
    "Spoutej ho a doveď ho na konec jen rukou.|300|pouta_postel!",
    "Spoutej ho a nech ho dojít, pak pokračuj ještě chvíli.|300|pouta_postel!",
    "Sváž mu ruce, zavaž oči a střídej pírko a bičík.|300|pouta_postel!",
    "Spoutej ho a pak si na něj sedni a drž ho za ramena.|300|kontrola_vsede",
    "Pouta a pomalost: Je spoutaný a ty se hýbeš tak pomalu, jak to jde. Cíl: nezrychlit ani jednou.|300|pouta_postel!",
    "Sváž mu ruce a miluj se s ním na boku.|300|dvojita_bok!",
    "Spoutej ho a nech ho prosit o každou další věc zvlášť.|300|pouta_postel!",
    "Poruč mu, ať se otočí a nedívá se, co chystáš.|240|zezadu!",
    "Řekni mu, že se nesmí udělat bez tvého svolení. A dlouho ho nedávej.|300|pouta_postel!",
    "Poruč mu, ať si klekne, a ty mu jen prohrábni vlasy. Nic víc.|240|oral_ona_klek",
    "Rozkaz a odměna: Za každý bezchybně splněný rozkaz dostane jednu věc, kterou má rád. Cíl: tři odměny.|300|klek_pouta!",
    "Sváž mu ruce a přitom mu drž bradu, ať se ti dívá do očí.|300|kontrola_vsede",
    "Spoutej ho a nech ho ležet na břiše. Pak si sedni na něj.|300|na_brise!",
    "Sváž mu ruce a nech ho klečet na všech čtyřech s hlavou dole.|300|zezadu!",
    "Spoutej ho a nech ho rozhodnout jen o jedné jediné věci.|300|pouta_postel!",
    "Poruč mu, ať tě poslouchá na slovo, a pak buď hodně konkrétní.|300|ona_nahore",
    "Přesně tak: Popiš mu přesně, jak má ležet, a oprav každou odchylku. Cíl: ať to sedí na centimetr.|300|pouta_postel!",
    "Spoutej ho a nech ho čekat, zatímco si dáváš na čas.|240|pouta_postel!",
    "Sváž mu ruce nad hlavou a kouři mu tak dlouho, dokud neprosí.|300|pouta_postel!",
    "Spoutej ho a pak ho polib, jako by se nic nedělo.|240|pouta_postel!",
    "Sváž mu jednu ruku a druhou nech volnou. Ať si vybere, co s ní.|300|pouta_postel!",
    "Poruč mu, ať klečí, a řekni mu, že dneska rozhoduješ ty.|300|klek_pouta!",
    "Jedno slovo a konec: Dohodněte se na slově, po kterém všechno okamžitě skončí, a pak jdi až na hranu. Cíl: nikdy ho neslyšet.|300|pouta_postel!",
    "Spoutej ho a mezi tím mu přejížděj ledem po celém těle.|300|pouta_postel!",
    "Sváž mu ruce a nech ho stát u zdi zády k tobě.|240|zed",
    "Spoutej ho a nech ho ležet nahého, zatímco se jen díváš.|240|pouta_postel!",
    "Poruč mu, ať ti řekne nahlas tři věci, které dneska udělá.|240|klek_pouta!",
    "Sváž mu ruce a doveď ho na hranu pětkrát za sebou.|300|pouta_postel!",
    "Spoutej ho a nech ho celou dobu mluvit, co cítí.|300|pouta_postel!",
    "Poslední rozkaz: Dej mu jeden poslední rozkaz a nech ho splnit beze slov. Cíl: nemuset nic vysvětlovat.|240|klek_pouta!",
    "Sváž mu ruce a pak mu sundej pouta, ale on se pořád nesmí hýbat.|300|pouta_postel!",
    "Spoutej ho a pak ho obejmi. Kontrast, který funguje.|180|pouta_postel!",
    "Na konec mu rozvaž ruce a promasíruj mu zápěstí.|120|pouta_postel!",
  ],
});
