// Kategorie 5 – Hardcore (dávka e)
// Témata: trojkombinace stimulací, postupná anální hra, prostata, dva vibrátory, led.
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 5,

  male: [
    "Trojkombinace: Vibrátor v zadečku, dva prsty uvnitř a jazyk na klitorisu. Všechno naráz, dokud se neudělá. Cíl: nepřerušit ani jedno.|300|oral_klek",
    "Vsuň jí s hodně lubrikantu vibrátor do zadečku, prsty ji prstěj a přitom ji lízej.|300|oral_klek",
    "Jeden vibrátor jí vsuň do zadečku, druhý drž na klitorisu a rukou jí dráždi bradavky.|300|pouta_postel",
    "Tři body naráz: Prst v zadečku, prsty vpředu a rty na klitorisu. Nikdy neuber ani jedno. Cíl: dovést ji tam všemi třemi.|300|oral_klek",
    "Namaž jí zadeček lubrikantem, vsuň palec a zároveň ji lízej.|300|oral_klek",
    "Prstěj ji vpředu, palec měj vzadu a jazykem krouži na klitorisu.|300|oral_klek",
    "Vsuň jí vibrátor dopředu, druhý přilož na klitoris a lízej jí bradavky.|300|vedle_ona_lezi",
    "Miluj se s ní a zároveň jí drž vibrátor na klitorisu a prst v zadečku.|300|misionar",
    "Plná trojka při sexu: Jsi v ní, vibrátor na klitorisu a namazaný prst v zadečku. Cíl: udržet všechno tři minuty.|300|misionar",
    "Vezmi ji zezadu a zároveň jí sahej dopředu oběma rukama.|300|zezadu",
    "Dvojitý průnik: Vibrátor v zadečku a ty v ní, s hodně lubrikantu. Hloubku řídí ona. Cíl: jít tak pomalu, jak řekne.|300|lzicka",
    "Vsuň jí vibrátor do zadečku a miluj se s ní na boku.|300|lzicka",
    "Vsuň jí vibrátor dopředu a sám vnikej do zadečku. Jen pokud to sama chce.|300|lzicka",
    "Anál pomalu: Hodně lubrikantu, začni jen špičkou a čekej, až se uvolní. Hloubku řídí ona. Cíl: nikam nespěchat.|300|zezadu",
    "Namaž jí zadeček a jen krouži prstem kolem. Dovnitř zatím ne.|300|na_brise",
    "Vsuň jí namazaný prst do zadečku a nehýbej jím. Jen ho tam nech.|300|na_brise",
    "Postupně: nejdřív jeden prst, po minutě druhý. Ona řekne kdy.|300|na_brise",
    "Namaž jí kolík lubrikantem a vsuň ho jen kousek. Ona řekne, kdy dál.|300|na_brise",
    "Krok za krokem: Prst, pak menší kolík, pak víc – ale jen když ona sama řekne další. Cíl: nikdy nepředběhnout.|300|na_brise",
    "Vsuň jí vibrátor do zadečku a rukou ji dráždi vpředu.|300|lzicka",
    "Nech ji ležet na břiše a s lubrikantem ji pomalu prstěj v zadečku.|300|na_brise",
    "Anál v lžičce: Na boku, hodně lubrikantu a ona si sama drží vibrátor vpředu. Cíl: nechat ji řídit tempo.|300|lzicka",
    "Nech ji klečet a s lubrikantem ji pomalu ber zezadu. Ona určuje hloubku.|300|zezadu",
    "Ať si sedne na tebe sama a řídí si celý anál od začátku do konce.|300|ona_nahore_zady",
    "Nech ji ležet na boku a dráždi ji zepředu i zezadu naráz.|300|dvojita_bok",
    "Vsuň jí vibrátor do zadečku a lízej ji, dokud nedojde.|300|oral_klek",
    "Vibrátor a jazyk: Vibrátor v zadečku, tvůj jazyk na klitorisu a nic jiného. Cíl: dovést ji tam tímhle.|300|oral_klek",
    "Nech ji držet si vibrátor vpředu a ty se staráš o zbytek.|300|na_brise",
    "Vezmi dva vibrátory: jeden dovnitř, druhý na klitoris.|300|pouta_postel",
    "Dva vibrátory: Jeden na bradavkách, druhý mezi nohama. Střídej, který má vyšší stupeň. Cíl: nikdy oba naplno.|300|pouta_postel",
    "Přilož jí oba vibrátory naráz a nech ji, ať řekne, kdy dost.|300|pouta_postel",
    "Spoutej ji a použij oba vibrátory zároveň.|300|pouta_postel",
    "Jeden vibrátor v ní, druhý si drž ty a přejížděj po celém těle.|300|pouta_postel",
    "Přilož jí vibrátor na klitoris a druhý jí dej do ruky, ať si sama vybere kam.|300|vedle_ona_lezi",
    "Střídavá dvojka: Dva vibrátory, ale vždycky běží jen jeden. Střídej je po deseti vteřinách. Cíl: ať nikdy neví který.|300|deprivace",
    "Spoutej ji, zavaž jí oči a použij led a vibrátor zároveň.|300|pouta_postel",
    "Led a pouta: Je spoutaná a ty jí střídáš kostku ledu a horký dech po celém těle. Cíl: deset střídání.|300|pouta_postel",
    "Přejeď jí ledem po zádech, zatímco jí drží vibrátor vepředu.|300|pouta_postel",
    "Vsuň jí kostku ledu mezi prsa a nech ji, ať ji tam udrží.|300|pouta_postel",
    "Střídej led a vibrátor na klitorisu po deseti vteřinách.|300|vedle_ona_lezi",
    "Spoutej ji a přejížděj jí ledem po vnitřní straně stehen.|300|pouta_postel",
    "Nasaď si erekční kroužek a miluj se s ní tak dlouho, jak to jen půjde.|300|misionar",
    "Kroužek a výdrž: S kroužkem musíš vydržet, dokud nedojde ona. Cíl: nedojít dřív.|300|ona_nahore",
    "S kroužkem ji vezmi zezadu a zároveň jí drž vibrátor vpředu.|300|zezadu",
    "S kroužkem se nech od ní osedlat a nehýbej se vůbec.|300|ona_nahore",
    "Nasaď si kroužek a nech ji rozhodnout, kdy skončíte.|300|ona_nahore",
    "Spoutej ji, nasaď si kroužek a nespěchej vůbec nikam.|300|pouta_postel",
    "Vsuň jí vibrátor do zadečku a miluj se s ní v misionáři.|300|misionar",
    "Dvojí plnost: Vibrátor vzadu a ty vpředu, oba velmi pomalu. Cíl: nikdy nezrychlit.|300|misionar",
    "Vezmi ji zezadu a zároveň jí drž vibrátor na klitorisu.|300|zezadu",
    "Nech ji sedět na tobě a přitom jí dráždi zadeček prstem.|300|ona_nahore",
    "Ať si sedne na tebe zády a ty jí sahej dopředu i dozadu.|300|ona_nahore_zady",
    "Miluj se s ní a zároveň jí drž ruku na krku a druhou na klitorisu.|300|misionar",
    "Vezmi ji zezadu, drž ji za vlasy a zároveň jí sahej dopředu.|300|zezadu",
    "Tři ruce, dvě těla: Jedna ruka na vlasech, druhá vpředu a ty v ní zezadu. Cíl: nepustit ani jedno.|300|zezadu",
    "Nech ji ležet na břiše, vsuň jí vibrátor a plácej ji dlaní.|300|na_brise",
    "Spoutej ji, vsuň jí vibrátor a nech ji dojít bez jediného doteku navíc.|300|pouta_postel",
    "Přilož jí vibrátor a zároveň jí lízej bradavky a prstěj ji.|300|vedle_ona_lezi",
    "Vsuň jí dva prsty, palcem dráždi klitoris a druhou rukou zezadu.|300|vedle_ona_lezi",
    "Všechno najednou: Prsty vpředu, palec vzadu, jazyk na klitorisu a druhá ruka na prsou. Cíl: udržet všechny čtyři.|300|oral_klek",
    "Prstěj ji zepředu a zezadu zároveň, každou rukou jinak.|300|vedle_ona_lezi",
    "Lízej ji a zároveň jí strkej prst do zadečku a druhý dopředu.|300|oral_klek",
    "Nech ji klečet a dráždi ji jazykem zezadu, zatímco ji prstíš vpředu.|300|zezadu",
    "Ať si sedne na tvůj obličej a ty ji prstíš zezadu.|300|oral_ona_nad_nim",
    "Nech ji ležet na boku a dráždi ji zepředu, zezadu a líbej ji na krk.|300|dvojita_bok",
    "Vsuň jí vibrátor zezadu a nech ji, ať si vpředu pomáhá sama.|300|na_brise",
    "Ona řídí všechno: Ona říká, co má být kde, a ty jen plníš. Cíl: neudělat nic sám od sebe.|300|na_brise",
    "Nech ji vybrat, kolik pomůcek dneska použiješ. Maximálně tři.|300|pouta_postel",
    "Vsuň jí kolík a pak se s ní miluj úplně normálně.|300|misionar",
    "S kolíkem v zadečku ji vezmi zezadu, hodně pomalu.|300|zezadu",
    "Nech ji nosit kolík celou dobu této karty a dělej jinak všechno obvyklé.|300|misionar",
    "Kolík a čekání: Vsuň jí kolík a pak se jí pět minut nedotkni. Jen ať si na něj zvykne. Cíl: vydržet těch pět minut.|300|pouta_postel",
    "Vsuň jí kolík a zároveň jí přilož vibrátor na klitoris.|300|pouta_postel",
    "Prstěj ji zezadu jedním prstem, zatímco jí ústy pracuješ vpředu.|300|oral_klek",
    "Nech ji ležet s polštářem pod boky a dráždi ji všemi třemi způsoby.|300|misionar_polstar",
    "Spoutej ji a použij prst, vibrátor i jazyk za sebou.|300|pouta_postel",
    "Postupná stavba: Nejdřív jen jazyk, pak přidej prst, pak vibrátor. Nikdy nic neuber. Cíl: skončit se vším naráz.|300|oral_klek",
    "Doveď ji na hranu trojkombinací a pak úplně přestaň.|300|oral_klek",
    "Trojkombinací ji doveď ke dvěma orgasmům za sebou.|300|oral_klek",
    "Použij všechny pomůcky, co doma máte, ale postupně.|300|pouta_postel",
    "Nech ji rozhodnout, co z toho všeho dneska vynecháte.|300|pouta_postel",
    "Bez pomůcek: Stejná trojkombinace, ale jen rukama a ústy. Žádné hračky. Cíl: dokázat, že to jde.|300|oral_klek",
    "Dráždi ji zezadu jazykem, zatímco jí vpředu drží vibrátor ona sama.|300|na_brise",
    "Vsuň jí vibrátor a při tom ji spoutanou lízej.|300|pouta_postel",
    "Nech ji ležet a udělej všechno, co má ráda, najednou.|300|vedle_ona_lezi",
    "Použij led, vibrátor a jazyk během jedné minuty.|300|oral_klek",
    "Nech ji dojít trojkombinací a pak jí všechno pomalu vyndej.|300|oral_klek",
    "Konec a péče: Všechno opatrně vyndej, umyj si ruce, přines jí vodu a lehni si k ní. Cíl: nevynechat žádný krok.|180|lzicka",
    "Na konec ji jen obejmi a nech ji vydechnout.|120|lzicka",
  ],

  female: [
    "Trojkombinace: Vibrátor v zadku, ruka na kmeni a ústa na špičce. Všechno naráz, dokud se neudělá. Cíl: nepřerušit ani jedno.|300|oral_on_vleze",
    "Vsuň mu s hodně lubrikantu vibrátor do zadku, rukou ho hlaď a přitom mu kouři.|300|oral_on_vleze",
    "Jeden vibrátor mu vsuň do zadku, druhý drž na varlatech a rukou ho dráždi.|300|pouta_postel!",
    "Tři body naráz: Prst v zadku, ruka na kmeni a rty na špičce. Nikdy neuber ani jedno. Cíl: dovést ho tam všemi třemi.|300|oral_on_vleze",
    "Namaž mu zadek lubrikantem, vsuň prst a zároveň mu kouři.|300|oral_on_vleze",
    "Masíruj mu prostatu prstem, rukou ho hlaď a jazykem dráždi varlata.|300|oral_on_vleze",
    "Prostata a ústa: Prst uvnitř pohybem pojď sem a ústa nahoře. Obojí zároveň. Cíl: najít správné místo.|300|oral_on_vleze",
    "Vsuň mu namazaný prst a masíruj prostatu, zatímco ho hladíš rukou.|300|oral_on_vleze",
    "Masíruj mu prostatu, dokud se neudělá jen z toho.|300|oral_on_vleze",
    "Nasaď mu kroužek, masíruj prostatu a zároveň mu kouři.|300|oral_on_vleze",
    "Kroužek a prostata: Kroužek nasazený, prst uvnitř a ústa nahoře. Cíl: udržet všechno tři minuty.|300|oral_on_vleze",
    "Sedni si na něj a zároveň mu prstem dráždi hráz.|300|ona_nahore",
    "Dvojitý průnik: Vibrátor v jeho zadku, zatímco na něm sedíš. Hloubku řídí on. Cíl: jít tak pomalu, jak řekne.|300|ona_nahore",
    "Vsuň mu vibrátor do zadku a miluj se s ním na boku.|300|lzicka",
    "Anál pomalu: Hodně lubrikantu, začni jen špičkou prstu a čekej, až se uvolní. Hloubku řídí on. Cíl: nikam nespěchat.|300|na_brise!",
    "Namaž mu zadek a jen krouži prstem kolem. Dovnitř zatím ne.|300|na_brise!",
    "Vsuň mu namazaný prst a nehýbej jím. Jen ho tam nech.|300|na_brise!",
    "Postupně: nejdřív jeden prst, po minutě druhý. On řekne kdy.|300|na_brise!",
    "Namaž kolík lubrikantem a vsuň mu ho jen kousek. On řekne, kdy dál.|300|na_brise!",
    "Krok za krokem: Prst, pak menší kolík, pak víc – ale jen když on sám řekne další. Cíl: nikdy nepředběhnout.|300|na_brise!",
    "Vsuň mu vibrátor do zadku a rukou ho hlaď vpředu.|300|lzicka",
    "Nech ho ležet na břiše a s lubrikantem ho pomalu prstěj.|300|na_brise!",
    "Anál v lžičce: Na boku, hodně lubrikantu a on si sám drží ruku vpředu. Cíl: nechat ho řídit tempo.|300|lzicka",
    "Nech ho klečet a s lubrikantem mu pomalu vsouvej kolík. On určuje hloubku.|300|zezadu!",
    "Ať si sedne na tebe sám a řídí si celé tempo od začátku do konce.|300|kontrola_vsede",
    "Nech ho ležet na boku a dráždi ho zepředu i zezadu naráz.|300|dvojita_bok!",
    "Vsuň mu vibrátor do zadku a kouři mu, dokud se neudělá.|300|oral_on_vleze",
    "Vibrátor a jazyk: Vibrátor v zadku, tvoje ústa nahoře a nic jiného. Cíl: dovést ho tam tímhle.|300|oral_on_vleze",
    "Nech ho držet si to sám a ty se staráš o zbytek.|300|na_brise!",
    "Vezmi dva vibrátory: jeden na varlata, druhý na hráz.|300|pouta_postel!",
    "Dvojice hraček: Jednu přilož na bradavky, druhou mezi nohy a pořád přehazuj, která jede silněji. Cíl: nikdy obě naplno.|300|pouta_postel!",
    "Přilož mu oba vibrátory naráz a nech ho, ať řekne, kdy dost.|300|pouta_postel!",
    "Spoutej ho a použij oba vibrátory zároveň.|300|pouta_postel!",
    "Jeden vibrátor v něm, druhý si drž ty a přejížděj po celém těle.|300|pouta_postel!",
    "Přilož mu vibrátor na hráz a druhý mu dej do ruky, ať si sám vybere kam.|300|vedle_on_lezi",
    "Jen jeden běží: Máš dvě hračky, ale zapnutá je vždycky jen jedna a po deseti vteřinách je prohodíš. Cíl: ať nepozná která.|300|deprivace!",
    "Spoutej ho, zavaž mu oči a použij led a vibrátor zároveň.|300|pouta_postel!",
    "Led a pouta: Je spoutaný a ty mu střídáš kostku ledu a horký dech po celém těle. Cíl: deset střídání.|300|pouta_postel!",
    "Přejeď mu ledem po zádech, zatímco mu drží vibrátor vepředu.|300|pouta_postel!",
    "Polož mu kostku ledu na hrudník a nech ho, ať ji tam udrží.|300|pouta_postel!",
    "Střídej led a ústa po deseti vteřinách.|300|oral_on_vleze",
    "Spoutej ho a přejížděj mu ledem po vnitřní straně stehen.|300|pouta_postel!",
    "Nasaď mu erekční kroužek a sedni si na něj tak dlouho, jak to jen půjde.|300|ona_nahore",
    "Kroužek a výdrž: S kroužkem musí vydržet, dokud nedojdeš ty. Cíl: ať nedojde dřív.|300|ona_nahore",
    "S kroužkem ho nech kleknout si za tebe a zároveň si drž vibrátor vpředu.|300|zezadu",
    "S kroužkem si na něj sedni a nenech ho hnout se ani jednou.|300|kontrola_vsede",
    "Nasaď mu kroužek a rozhodni sama, kdy skončíte.|300|ona_nahore",
    "Spoutej ho, nasaď mu kroužek a nespěchej vůbec nikam.|300|pouta_postel!",
    "Vsuň mu vibrátor do zadku a sedni si na něj.|300|ona_nahore",
    "Dvojí plnost: Vibrátor vzadu a ty na něm, oba velmi pomalu. Cíl: nikdy nezrychlit.|300|ona_nahore",
    "Nech ho klečet za tebou a zároveň mu sahej dozadu mezi nohy.|300|zezadu!",
    "Sedni si na něj a přitom mu dráždi hráz prstem.|300|ona_nahore",
    "Sedni si na něj zády a sahej mu dozadu.|300|ona_nahore_zady",
    "Sedni si na něj, drž mu ruku na krku a druhou mu dráždi bradavky.|300|kontrola_vsede",
    "Nech ho klečet, drž ho za vlasy a zároveň mu sahej dopředu.|300|zezadu!",
    "Tři ruce, dvě těla: Jedna ruka na vlasech, druhá vpředu a on v tobě zezadu. Cíl: nepustit ani jedno.|300|zezadu!",
    "Nech ho ležet na břiše, vsuň mu vibrátor a plácej ho dlaní.|300|na_brise!",
    "Spoutej ho, vsuň mu vibrátor a nech ho dojít bez jediného doteku navíc.|300|pouta_postel!",
    "Přilož mu vibrátor a zároveň mu olizuj bradavky a hlaď ho.|300|vedle_on_lezi",
    "Drž ho rukou, palcem dráždi špičku a druhou rukou mu sahej dozadu.|300|vedle_on_lezi",
    "Všechno najednou: Ruka na kmeni, prst vzadu, ústa na špičce a druhá ruka na bradavkách. Cíl: udržet všechny čtyři.|300|oral_on_vleze",
    "Prstěj ho zezadu a rukou ho hlaď vpředu, každou jinak.|300|vedle_on_lezi",
    "Kouři mu a zároveň mu strkej prst do zadku a druhou rukou hlaď varlata.|300|oral_on_vleze",
    "Nech ho klečet a dráždi ho jazykem zezadu, zatímco ho držíš rukou vpředu.|300|zezadu!",
    "Sedni si mu na obličej a zároveň mu sahej rukou dozadu.|300|oral_ona_nad_nim",
    "Nech ho ležet na boku a dráždi ho zepředu, zezadu a líbej ho na krk.|300|dvojita_bok!",
    "Vsuň mu vibrátor zezadu a nech ho, ať si vpředu pomáhá sám.|300|na_brise!",
    "On řídí všechno: On říká, co má být kde, a ty jen plníš. Cíl: neudělat nic sama od sebe.|300|na_brise!",
    "Nech ho vybrat, kolik pomůcek dneska použiješ. Maximálně tři.|300|pouta_postel!",
    "Vsuň mu kolík a pak se s ním miluj úplně normálně.|300|ona_nahore",
    "S kolíkem v zadku si na něj sedni, hodně pomalu.|300|ona_nahore",
    "Nech ho nosit kolík celou dobu této karty a dělej jinak všechno obvyklé.|300|ona_nahore",
    "Kolík a čekání: Vsuň mu kolík a pak se ho pět minut nedotkni. Jen ať si na něj zvykne. Cíl: vydržet těch pět minut.|300|pouta_postel!",
    "Vsuň mu kolík a zároveň mu nasaď kroužek.|300|pouta_postel!",
    "Prstěj ho zezadu jedním prstem, zatímco mu ústy pracuješ vpředu.|300|oral_on_vleze",
    "Nech ho ležet s polštářem pod boky a dráždi ho všemi třemi způsoby.|300|misionar_polstar",
    "Spoutej ho a použij prst, vibrátor i jazyk za sebou.|300|pouta_postel!",
    "Postupná stavba: Nejdřív jen jazyk, pak přidej ruku, pak vibrátor. Nikdy nic neuber. Cíl: skončit se vším naráz.|300|oral_on_vleze",
    "Doveď ho na hranu trojkombinací a pak úplně přestaň.|300|oral_on_vleze",
    "Trojkombinací ho doveď až na konec a pak ještě chvíli pokračuj.|300|oral_on_vleze",
    "Projdi postupně všechny pomůcky, které doma máte, jednu po druhé.|300|pouta_postel!",
    "Nech ho rozhodnout, co z toho všeho dneska vynecháte.|300|pouta_postel!",
    "Jen ty: Stejná trojkombinace, ale bez jediné hračky – vystačíš si rukama a ústy. Cíl: dokázat, že to jde.|300|oral_on_vleze",
    "Dráždi ho zezadu jazykem, zatímco si vpředu pomáhá sám.|300|na_brise!",
    "Vsuň mu vibrátor a při tom mu spoutanému kouři.|300|pouta_postel!",
    "Nech ho ležet a udělej všechno, co má rád, najednou.|300|vedle_on_lezi",
    "Během jediné minuty musí přijít na řadu led, vibrátor i tvůj jazyk.|300|oral_on_vleze",
    "Nech ho dojít trojkombinací a pak mu všechno pomalu vyndej.|300|oral_on_vleze",
    "Konec a péče: Všechno opatrně vyndej, umyj si ruce, přines mu vodu a lehni si k němu. Cíl: nevynechat žádný krok.|180|lzicka",
    "Na konec ho jen obejmi a nech ho vydechnout.|120|lzicka",
  ],
});
