// Kategorie 5 – Hardcore
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 5,
  name: "Hardcore",
  description: "Pouta, bičík, anál, dva vibrátory a úplná kontrola. Stop slovo platí vždycky.",

  // Úkoly pro muže – pro potěšení ženy
  male: [
    "Dva vibrátory poslepu: Spoutej jí ruce k čelu postele, zavaž jí oči a přikládej jí jeden vibrátor na klitoris a druhý na bradavky. Cíl: nepřestat, dokud nedojde.|300|pouta_postel",
    "Deset ran se stupňováním: Předkloň ji přes opěradlo a dej jí deset ran bičíkem, každou o kousek silněji. Ona počítá. Cíl: teprve po desáté do ní vniknout.|240|predklon",
    "Prst a jazyk: Vsuň jí pomalu s lubrikantem prst do zadečku a zároveň ji lízej. Cíl: tři minuty a tempo i hloubku určuje jen ona.|180|oral_klek",
    "Anál od špičky: Použij hodně lubrikantu, začni jen špičkou a počkej, až se uvolní. Cíl: hloubku i tempo určuje jen ona, ty jí hladíš klitoris.|240|zezadu",
    "Nepřestat po orgasmu: Miluj ji v misionáři a drž jí vibrátor na klitorisu. Cíl: nepřestat ani po jejím orgasmu, dokud sama neřekne dost.|300|misionar",
    "Držíš ji za pouta: Nasaď jí pouta za zády a miluj ji zezadu, přitom ji drž za pouta. Cíl: tři minuty a na stop ji hned odemknout.|180|zezadu",
    "Dvojitá stimulace: Jeden vibrátor jí vsuň, druhý přilož na klitoris a jazykem jí olizuj bradavky. Cíl: tři minuty a ani jedno nepřerušit.|180|vedle_ona_lezi",
    "Dvě slova: Přikaž jí lehnout si a nehýbat se a mrdej ji na kraji postele. Smí říct jen „ano“, nebo stop slovo. Cíl: čtyři minuty a na to druhé hned přestat.|240|kraj_postele",
    "Odpírání orgasmu: Dráždi ji vibrátorem až těsně k vrcholu a pak pokaždé přestaň. Cíl: třikrát ji zastavit a počtvrté ji nechat dojít.|300|vedle_ona_lezi",
    "Pírko, nebo bičík: Spoutej ji, zavaž jí oči a střídej pírko a bičík po celém těle. Cíl: dvacet doteků a ať ani jednou neuhodne, co přijde.|180|pouta_postel",
    "Za vlasy přes linku: Vezmi ji za vlasy pevně, ale ne bolestivě, předkloň ji přes linku a miluj ji zezadu. Cíl: dvě minuty a na stop ji hned pustit.|120|predklon",
    "Anál s vibrátorem: S hodně lubrikantu do ní pomalu vnikni análně, ona si přitom drží vibrátor na klitorisu. Cíl: tempo určuje výhradně ona.|180|zezadu",
    "Dvojitý průnik: Vsuň do ní vibrátor s rozšířenou základnou a sám do ní pomalu vnikni análně. Cíl: hodně lubrikantu a zrychlit až na její slovo.|180|zezadu",
    "Dva za sebou: Spoutej ji k posteli a dováděj ji vibrátorem. Cíl: dva orgasmy za sebou a mezi nimi žádná pauza delší než půl minuty.|300|pouta_postel",
    "Rána a polibek: Dej jí pět ran bičíkem na vnitřní stranu stehen a po každé to místo olízni. Cíl: síla pokaždé stejná, ani jedna tvrdší.|180|oral_klek",
    "Ruce za hlavou vkleče: Poruč jí, ať klečí s rukama za hlavou, a miluj ji zezadu. Cíl: tři minuty – jakmile ruce sundá, začínáte znovu.|180|klek_ruce_hlava",
    "Tvrdě s nohama na ramenou: Ona leží na zádech s nohama na tvých ramenou a ty přirážíš rychle a silně. Cíl: dvě minuty a každou půlminutu se zeptat, jestli to není moc.|120|nohy_ramena",
    "Vibrátor pod ní: Spoutej ji, polož ji na břicho s polštářem pod boky, vsuň pod ni vibrátor a miluj ji zezadu. Cíl: tři minuty a na stop ji odemknout.|180|na_brise",
    "Dokud nepoprosí: Zakaž jí dojít a pak ji lízej a prsti. Cíl: nepolevit, dokud tě nahlas nepoprosí o svolení – a pak jí ho dát.|300|oral_klek",
    "Palec při sexu: Mrdej ji zezadu a vsuň jí palec s lubrikantem do zadečku. Cíl: dvě minuty a hloubku určuje jen ona.|120|zezadu",
    "Spoutaná na židli: Spoutej ji, zavaž jí oči, posaď ji na židli a střídej jazyk a vibrátor. Cíl: nepřestat, dokud se na židli nezačne kroutit.|180|zidle_celem",
    "Plácnutí při jízdě: Plácej ji dlaní po zadečku, zatímco na tobě jezdí. Cíl: dvacet plácnutí a po každém pátém se zeptat, jestli chce silněji.|90|ona_nahore",
    "Spoutaná u gauče: Nech ji klečet opřenou o gauč s rukama spoutanýma před sebou a miluj ji zezadu. Cíl: tři minuty a na stop ji hned odemknout.|180|zezadu",
    "Rychle proti bodu G: Prsti ji dvěma prsty rychle a intenzivně proti přední stěně a podlož ručník. Cíl: nepřestat, dokud nedojde.|300|vedle_ona_lezi",
    "Tři a tři: Předkloň ji přes kraj postele a střídej tři rány bičíkem a tři přírazy. Cíl: pět takových kol a pořadí ani jednou nesplést.|180|predklon",
    "Anál ve lžičce: Ležíte na boku, ty za ní. S hodně lubrikantu do ní pomalu vnikni. Cíl: tempo i hloubku řídí výhradně ona rukou na tvém boku.|180|lzicka",
    "Spoutaná u zdi: Spoutej jí ruce za zády, nech ji stát opřenou o zeď a lízej ji vkleče. Cíl: dvě minuty a udržet ji na nohou.|120|zed",
    "Vibrace vzadu: Miluj ji v misionáři a vibrátorem jí zvenku dráždi zadeček. Cíl: tři minuty a dovnitř s ním nikdy.|180|misionar",
    "Drží si nohy sama: Přikaž jí, ať si sama drží nohy u prsou, a miluj ji tvrdě. Cíl: dvě minuty – jakmile je pustí, začínáte znovu.|120|nohy_ramena",
    "Přivázaná k posteli: Zavaž jí oči a přivaž jí ruce k nohám postele. Cíl: lízat ji, dokud nedojde dvakrát – a na stop ji hned rozvázat.|300|pouta_postel",
    "Ruka na zátylku: Miluj se s ní na lince tvrdě a rychle a jednou rukou ji drž za zátylek. Cíl: dvě minuty a na stop ruku hned sundat.|120|predklon",
    "Vibrátor vzadu, ty vepředu: Vsuň jí do zadečku vibrátor s rozšířenou základnou a miluj se s ní klasicky. Cíl: hodně lubrikantu a tempo určuje ona.|180|misionar",
    "Rány na její povel: Nasaď jí pouta, polož ji na břicho a dávej jí bičíkem rány přes zadeček a stehna. Cíl: nepřestat, dokud sama neřekne dost.|180|na_brise",
    "Na povel teď: Miluj ji a ona smí dojít jen na tvoje slovo. Odpočítej nahlas od deseti k nule. Cíl: trefit se přesně do nuly.|300|misionar",
    "Jazyk vzadu, vibrace vepředu: Olizuj jí zadeček a zároveň jí vibrátorem dráždi klitoris. Cíl: dvě minuty a ani jedno nepřerušit.|120|na_brise",
    "Nejdřív jemně, pak tvrdě: Spoutej jí ruce nad hlavou a dvě minuty ji jen pomalu líbej po celém těle. Cíl: teprve pak přejít do tvrdého tempa.|240|pouta_postel",
    "Obcházíš ji dokola: Nech ji stát spoutanou se zavázanýma očima a obcházej ji, střídej bičík, ruce a vibrátor. Cíl: ať nikdy neuhodne, odkud přijde další dotek.|180|klek_pouta",
    "Tvrdě ve sprše: Nech ji opřít se o stěnu a miluj ji zezadu tvrdě, s rukama na jejích bocích. Cíl: dvě minuty a držet ji tak, aby neuklouzla.|120|zezadu_vzpr",
    "Dva naplno: Zapni oba vibrátory naplno, jeden jí vsuň a druhý přilož na klitoris. Cíl: dvě minuty a držet jí ruce, ať si je nemůže sundat.|120|pouta_postel",
    "Vybíráš ty: Poruč jí, ať klečí předkloněná a roztáhne si hýždě rukama. Lízej ji. Cíl: pak si vybrat, kam do ní vnikneš – a hodně lubrikantu.|240|zezadu",
    "Přehni ji přes koleno. Plácej ji dlaní po zadečku a mezi ranami ji hlaď mezi nohama.|90",
    "Posaď ji na židli a spoutej jí ruce za opěradlem. Klekni si a lízej ji, dokud nebude prosit o pauzu.",
    "Miluj ji v misionáři a drž jí přitom zápěstí přitisknutá k posteli. Rychle a hluboko.|120",
    "Anál na kraji postele: ona leží na břiše, ty stojíš. Použij hodně lubrikantu, začni pomalu a pak zrychluj podle ní.|180",
    "Oči do konce: Dráždi ji vibrátorem a ona se ti přitom musí dívat do očí. Cíl: nesmí je zavřít, dokud nedojde – jinak začínáte znovu.|300|vedle_ona_lezi",
    "Musí to říct přesně: Spoutej ji a přikaž jí říct, jestli ji máš prstit, lízat, nebo mrdat. Cíl: dokud to neřekne konkrétně, nedostane vůbec nic.|300|klek_pouta",
    "Polož ji na jídelní stůl, spoutej jí ruce nad hlavou a miluj ji vestoje. Jednou rukou jí přitom drž vibrátor na klitorisu.|180",
    "Plácni ji bičíkem přes bradavky jen velmi jemně – a hned je olízni. Pětkrát.",
    "Zkus s ní „vynucený“ orgasmus vibrátorem – drž jí ho na klitorisu, i když se kroutí, dokud nedojde (stop slovo platí).",
    "Miluj ji v jakékoli poloze a každých 20 vteřin jí dej plácnutí na zadeček. Ona počítá.|180",
    "Spoutej jí ruce za zády a posaď si ji na sebe. Drž ji za boky a tvrdě přirážej zespodu.|120",
    "Vsuň do ní vibrátor a nech ho tam. Pak jí lízej klitoris. Nesmí se pohnout.|180",
    "Tvrdý sex zezadu na posteli – jednou rukou ji drž za vlasy, druhou jí hlaď klitoris.|120",
    "Prstem s lubrikantem jí pomalu dráždi zadeček a zároveň do ní zasouvej vibrátor.|180",
    "Rozkaž jí, ať si lehne na podlahu v obýváku s roztaženýma nohama a rukama nad hlavou. Klekni si mezi její nohy a vezmi si ji.|180",
    "Nasaď jí pouta, zavaž jí oči, polož ji na gauč a mrdej ji ve čtyřech různých polohách. Netuší, co přijde.|240",
    "Miluj ji tak tvrdě a rychle, jak to jen jde, a pak se úplně zastav a pomalu ji polib. Opakuj.|180",
    "Nech ji, ať si vybere počet ran bičíkem (1–15). Dej jí je a po poslední ji odměň orálem.",
    "Ona klečí a má v sobě vibrátor, ty do ní zezadu pomalu vnikni análně s hodně lubrikantu. Tempo i hloubku určuje jen ona.|180",
    "Oba vibrátory přilož na klitoris zároveň z obou stran a nepovol, dokud nedojde.",
    "Dívá se na sebe: Postav ji spoutanou před zrcadlo, přitiskni se k ní zezadu a dováděj ji vibrátorem. Cíl: nesmí odvrátit oči od zrcadla.|300|stoje_zezadu",
    "Mluví, jinak zpomalíš: Poruč jí, ať nahlas popisuje, co cítí. Jakmile ztichne, zpomalíš. Cíl: tři minuty a nejvýš dvě zpomalení.|180|zezadu",
    "Proud ze sprchy: Spoutej jí ruce před tělem, posaď ji na okraj vany a proudem ze sprchy jí miř na klitoris. Cíl: nepřestat, dokud nedojde.|300",
    "Bičík při jízdě zády: Ona na tobě jezdí zády k tobě a ty ji plácáš bičíkem po zadečku. Cíl: deset ran a síla pokaždé stejná.|120|ona_nahore_zady",
    "Přestimulace jazykem: Lízej ji dál i po orgasmu, ale úplně jemně. Cíl: nepřestat, dokud nepřijde druhý – nebo dokud neřekne stop.|300|oral_klek",
    "Za ramena přes linku: Přikaž jí předklonit se přes linku a vystrčit zadeček, drž ji za ramena a tvrdě ji mrdej. Cíl: dvě minuty bez zpomalení.|120|predklon",
    "Zápěstí u kotníků: Přivaž jí zápěstí ke kotníkům, ať je rozevřená, a lízej ji. Cíl: tři minuty a kdykoli řekne stop, hned ji rozvázat.|180|nohy_ramena",
    "Vepředu i vzadu: Miluj ji v misionáři a vzadu jí přidej vibrátor s rozšířenou základnou nebo namazaný prst. Cíl: hloubku určuje jen ona.|180|misionar",
    "Žádné doteky a žádný konec: Zakaž jí dotknout se sebe i tebe a pak ji dráždi. Cíl: pět minut, při kterých ji nenecháš dojít.|300|vedle_ona_lezi",
    "Zmizíš na minutu: Spoutej ji, zavaž jí oči a nech jí vibrátor na nízký stupeň. Pak se potichu odtáhni. Cíl: celá minuta ticha, než se vrátíš.|60|pouta_postel",
    "Zpomalení stojí ránu: Poruč jí, ať na tobě jezdí rychle. Za každé zpomalení dostane ránu bičíkem. Cíl: dvě minuty a nejvýš tři rány.|120|ona_nahore",
    "Ruce přitisknuté ke zdi: Ona se opírá o zeď, ty ji miluješ zezadu a držíš jí ruce na zdi. Cíl: dvě minuty a nesmí je sundat.|120|zed",
    "Vezmi si ji na pračce v plném odstřeďování – tvrdě a rychle.|120",
    "Plácni ji po zadečku třikrát bičíkem, třikrát dlaní a nakonec ho třikrát polib.",
    "Nasaď jí pouta s rukama před tělem a nech ji, ať si tě spoutanýma rukama navede tam, kde tě chce. Pak ji tak mrdej.|180",
    "Anál v misionáři: podlož jí boky polštářem, hodně lubrikantu, dívej se jí do očí a hlaď jí klitoris. Tempo i hloubku určuje jen ona.|180",
    "Ona klečí spoutaná na gauči. Vsuň jí vibrátor do kundičky a s hodně lubrikantu ji pomalu mrdej do zadečku. Tempo i hloubku určuje jen ona.|180",
    "Prsti ji a lízej zároveň, dokud nebude mít orgasmus. Pak ji hned miluj tvrdě.",
    "Spoutej jí ruce za zády a nech ji ležet na břiše na posteli. Lehni si na ni celou vahou (opatrně) a miluj ji zezadu pomalu a hluboko.|180",
    "Zakaž jí mluvit, dokud nedojde. Za každé slovo dostane ránu bičíkem.",
    "Přikládej jí vibrátor střídavě na klitoris a na zadeček, zatímco ji miluješ.|180",
    "Zavaž jí oči, spoutej ji a vsuň jí prst do pusy. Ať ho saje, zatímco ji miluješ.|120",
    "Dvacet lehkých: Dej jí dvacet rychlých lehkých plácnutí bičíkem po zadečku a stehnech, ona počítá. Cíl: teprve po dvacátém do ní vniknout.|180|zezadu",
    "Miluj ji na kraji jídelního stolu a přitom jí oběma vibrátory hlaď bradavky.|180",
    "Drž jí zápěstí za zády jako v poutech a tvrdě ji miluj zezadu u okna se zataženými závěsy.|120",
    "Nech ji ležet se spoutanýma rukama na zádech. Olizuj ji, prsti ji, miluj ji – prostě ji rozmazluj, dokud neřekne dost.",
    "Rozkaž jí, ať si sama drží vibrátor na klitorisu, a pokud ho sundá, přestaneš. Pak ji tvrdě miluj.|180",
    "Anál vestoje u kuchyňské linky: hodně lubrikantu a začni úplně pomalu. Tempo i hloubku určuje celou dobu jen ona.|180",
    "Jen pírko a vibrátor: Spoutej ji a doveď ji k orgasmu výhradně pírkem a vibrátorem. Cíl: nepoužít ani jazyk, ani prsty.|300|pouta_postel",
    "Plácni ji bičíkem na zadeček vždy, když zasténá. Pak ji miluj tak, aby sténala pořád.|120",
    "Vsuň jí dva prsty do vagíny a palec s lubrikantem do zadečku a jemně je k sobě přitlač.|90",
    "Miluj ji zezadu na posteli a nech ji, ať si vybere: rány bičíkem, nebo vibrátor na klitoris. Může si vybrat i obojí.|180",
    "Poruč jí, ať si klekne na koberec a prohne záda. Miluj ji zezadu a drž ji za oba boky.|180",
    "Spoutej ji pouty a nech ji, ať ti řekne, jak moc chce, abys jí dal orgasmus. Pak jí dej dva.",
    "Anál na boku s hodně lubrikantu: ona leží na boku, ty za ní a vibrátor jí přikládáš zepředu na klitoris. Tempo i hloubku určuje jen ona.|180",
    "Miluj ji a jednou rukou jí zakrývej pusu, aby tlumila sténání (nos nech volný).|90",
    "Rychle a bez pauzy: Miluj ji v misionáři rychle a hluboko, bez jediné přestávky. Cíl: dvě minuty a ani jednou nezpomalit.|120|misionar",
    "Zavaž jí oči a přikaž jí, ať si klekne na postel na všechny čtyři. Pak ji nech minutu čekat a pak ji dráždi bičíkem a vibrátorem.|60",
    "Nech v ní vibrátor a posaď si ji na sebe tak, abyste vibrace cítili oba.|180",
    "Odpírání: spoutej ji a pokaždé, když se blíží orgasmu, dej jí lehkou ránu bičíkem a přestaň. Až po pátém pokusu ji nech dojít.",
    "Spoutej ji k čelu postele a miluj ji tvrdě v misionáři s jejíma nohama na svých ramenou.|120",
    "Lízej jí zadeček a vagínu střídavě, a vibrátorem jí přitom dráždi klitoris.|120",
    "Poruč jí, ať si tě s hodně lubrikantu sama pomalu zavede do zadečku a určí si tempo i hloubku. Ty jí přitom hlaď klitoris.|180",
    "Na gauči ji ohni přes područku a miluj ji zezadu tvrdě. Pak jí dej ránu bičíkem a zase zpomal.|180",
    "Vezmi ji do sprchy, spoutej jí ruce a miluj ji tam zezadu. Pozor na uklouznutí.|120",
    "Jeden vibrátor jí vsuň, druhý ať si sevře stehny na klitorisu. Jazykem jí olizuj bradavky a rukama jí drž zápěstí.|180",
    "Nejdivočejší přání: Spoutanou ji nech vyslovit tu nejdivočejší věc, kterou by chtěla, a pak ji přesně tak mrdej. Cíl: splnit to ještě dneska.|180|klek_pouta",
    "Tvrdě ji miluj a ona smí dojít, jen když si o to řekne tvým jménem.|180",
    "Spoutej jí ruce, zavaž jí oči a dej jí na výběr: tvrdý sex, nebo 5 minut vibrátoru. Pak udělej to druhé taky.",
    "Stáhni ji za nohy ke kraji postele, roztáhni jí nohy a vezmi si ji tvrdě vestoje.|120",
    "Pomalý anál s hodně lubrikantu: po každém přírazu jí řekni, jak je skvělá. Tempo i hloubku určuje jen ona.|180",
    "Nejdřív rychle, pak pomalu: Doveď ji vibrátorem k orgasmu co nejrychleji. Cíl: ten druhý jí dopřát co nejpomaleji – ať trvá aspoň pět minut.|300|vedle_ona_lezi",
    "Připne tě sama: Dej jí pouta a nech ji rozhodnout, kam ti připne ruce. Cíl: pak ji potěšit jen pusou, dokud nedojde.|300|oral_klek",

    // Karty s cílem
    "Výslech: Spoutej jí ruce za zády a posaď ji na židli. Za upřímnou odpověď minuta vibrátoru, za vytáčku rána bičíkem. Cíl: prozradit aspoň tři fantazie.|300|zidle_celem",
    "Orgasmový žebříček: Spoutej ji k posteli. Cíl: tři orgasmy – první vibrátorem, druhý jazykem, třetí při sexu – a mezi nimi jí nedej víc než minutu pauzy.",
    "Anální rozehřátí: Namasíruj jí zadeček olejem, pak prstem s lubrikantem kruž kolem a nakonec pomalu jeden prst dovnitř. Cíl: hloubku určuje jen ona.|300|na_brise",
    "Královna na deset minut: Ona leží a rozkazuje, ty plníš každý její sexuální příkaz přesně a bez odmlouvání. Cíl: splnit všechno, dokud nedojde.|600",
    "Bičík podle abecedy: Ona je na všech čtyřech. Dej jí 26 lehkých ran bičíkem a u každé řekne další písmeno abecedy. Když se splete, začínáš od A. Cíl: dojít k Z – a pak ji odměnit orálem.",
    "Bez tvých rukou: Spoutej jí ruce nad hlavou. Jeden vibrátor jí vsuň, druhý ať si sevře stehny na klitorisu. Ty ji jen líbáš. Cíl: orgasmus bez jediného dotyku tvých rukou.",
    "Anál v zrcadle: Ležíte na boku čelem k zrcadlu, s hodně lubrikantu do ní pomalu vnikni análně a ona si drží vibrátor na klitorisu. Cíl: tempo i hloubku určuje jen ona.|300",
    "Odpočet: Dráždi ji vibrátorem a ona smí dojít až po odpočítání od 30 do 0 nahlas. Když dojde dřív, dostane pět ran bičíkem. Cíl: aby došla přesně na nule.",
    "Spoutané kotníky: Spoutej jí kotníky pouty a polož ji na břicho. Miluj ji zezadu mezi stisknutými stehny. Cíl: nepřestat, dokud nedojde.|240",
    "Nehybná u zdi: Spoutej jí ruce za zády a postav ji ke zdi. Zatímco ji prstíš a lížeš, nesmí se pohnout – za každý pohyb rána bičíkem. Cíl: aby vydržela dvě minuty.|120",
    "Dvojitý průnik: Vsuň jí vibrátor do kundičky a sám do ní s hodně lubrikantu pomalu vnikni análně. Cíl: čtyři minuty a tempo i hloubku určuje jen ona.|240",
    "Tvrdě přes gauč: Předkloň ji přes opěradlo gauče, chyť ji za boky a přirážej tvrdě a rychle. Každých 30 vteřin jí dej plácnutí. Cíl: tři minuty bez zpomalení.|180",
    "Nepovolit: Po jejím prvním orgasmu vibrátorem nech vibrátor dál na klitorisu na nejnižším stupni a drž jí ruce. Cíl: druhý orgasmus bez pauzy – stop slovo platí.",
    "Na kolenou u postele: Klečí na zemi hrudníkem na posteli, ruce spoutané. Mrdej ji zezadu, drž ji za boky a nezrychli bez jejího slova. Cíl: tři minuty.|180|zezadu",
    "Stupnice bolesti a slasti: Přehni ji přes koleno. Plácej ji bičíkem a ona po každé ráně řekne číslo od 1 do 10. Cíl: držet se mezi 5 a 7 a pak ji prsty dovést k orgasmu, dokud má zadeček ještě horký.",
    "Nikdy neví: Spoutej ji a zavaž jí oči. Každých 20 vteřin něco jiného – rána bičíkem, pírko, vibrátor, jazyk, příraz. Cíl: pět minut, kdy nikdy neví, co přijde.|300",
    "Řekni prosím: Miluj ji a přestaň. Pokračuj jen tehdy, když ti přesně řekne, co chce, a začne slovy „prosím, udělej mi…“. Cíl: aby to řekla aspoň pětkrát.",
    "Anál na stole: Ona leží na kraji stolu s nohama nahoře, ty stojíš. Hodně lubrikantu a pomalý začátek. Cíl: tempo řídí ona rukou na tvém břiše.|240|nohy_ramena",
    "Židle s vibrátorem: Posaď ji na židli s rukama spoutanýma za opěradlem a vibrátorem na sedáku pod jejím klínem. Ty jí saješ bradavky. Cíl: aby se o vibrátor otírala, dokud nedojde.",
    "Tři najednou: Jeden vibrátor jí vsuň, druhý přilož zvenku na zadeček a jazykem jí lízej klitoris. Cíl: udržet všechny tři najednou, dokud nedojde.",
    "Pevný stisk: Chyť ji zezadu za vlasy u kořínků – pevně, ne bolestivě – a druhou rukou za bok. Miluj ji tvrdě na kolenou na posteli. Cíl: zaklonit jí hlavu a šeptat jí do ucha, jak je dokonalá.|180",
    "Rány a přírazy: Ona je předkloněná přes linku. Tři rány bičíkem, tři hluboké přírazy, znovu tři rány. Cíl: deset kol a pak pokračovat bez počítání, dokud nedojde.",
    "Rozevřená: Spoutej jí zápěstí ke kotníkům – levou ruku k levému, pravou k pravému – ať leží na zádech rozevřená. Cíl: vylízat ji k orgasmu, zatímco se nemůže bránit.",
    "Prst při přírazech: Při sexu v misionáři jí vsuň prst s lubrikantem do zadečku a nech ho tam. Cíl: hloubku prstu určuje jen ona.|180",
    "Pět přerušení: Dráždi ji k orgasmu a pokaždé, když řekne „už budu“, přestaň. Když vydrží pět přerušení bez prošení, dostane orgasmus, jaký si sama řekne. Cíl: dotáhnout hru do konce.",
    "Ruce za hlavou: Ať si klekne nahá na koberec s rukama za hlavou a nohama od sebe. Obcházej ji s bičíkem a dotýkej se jí jím. Cíl: pak si klekni za ni a vezmi si ji, aniž by sundala ruce.|240",
    "Plná: Jeden vibrátor jí vsuň do vagíny, druhý – bezpečný, s rozšířenou základnou – do zadečku (jinak použij prst). K tomu jí lízej klitoris. Cíl: orgasmus, jaký ještě nezažila.",
    "Tvrdě a polibek: Udělej dvacet tvrdých rychlých přírazů, pak se na 10 vteřin úplně zastav a polib ji. Cíl: deset kol – v posledním nepřestávej.|300",
    "Spoutané ruce mezi nohama: Nasaď jí pouta tak, aby měla ruce před tělem mezi nohama, a přikaž jí, ať se hladí, zatímco ji miluješ zezadu. Cíl: musí se k orgasmu dovést sama, ty jen přirážíš.|240",
    "Pouta ve sprše: Ve sprše jí spoutej ruce před tělem, zvedni jí je nad hlavu a drž je. Miluj ji zezadu. Cíl: pomalé tvrdé přírazy dvě minuty – a pozor na uklouznutí.|120",
    "Krok za krokem: Spoutej ji, zavaž jí oči a polož ji na břicho. Nejdřív ji lízej, pak prsti, pak pomalu anál s hodně lubrikantu. Cíl: tempo i hloubku určuje jen ona.",
    "Povel s trestem: Dráždi ji vibrátorem – dojít smí jen na „teď“. Když dojde dřív, dostane pět ran bičíkem a začínáte znovu. Cíl: aby došla přesně na povel.",
    "Pod stolem: Ona sedí na židli u stolu s rukama spoutanýma za opěradlem, ty jsi pod stolem a lížeš ji a prstíš. Cíl: zastavit tě může jen stop slovem.",
    "Trest nahoře, odměna dole: Horní polovinu jejího těla lehce plácej bičíkem, klín odměňuj vibrátorem. Střídej po 20 vteřinách. Cíl: dokud nedojde.|240",
    "Anál vestoje: Ona se opírá o zeď a ty jsi za ní. Hodně lubrikantu, začni jen špičkou a čekej. Cíl: ona řídí hloubku rukou na tvém boku.|180",
    "Hravý souboj: Minutu se ti snaží vyklouznout z postele a ty ji chytáš a držíš – hravě, bez násilí. Když ji chytíš, spoutej ji a vezmi si ji. Cíl: skončit v ní.",
    "Tři různé orgasmy: Doveď ji k orgasmu prsty, pak ji otoč a miluj zezadu, pak zase vibrátor. Cíl: tři různé orgasmy během patnácti minut.|900",
    "Spoutaná na gauči: Spoutej jí ruce za zády a posaď ji na gauč s jednou nohou přes područku a druhou přes opěradlo. Cíl: lízat ji, dokud nebude prosit o pauzu – a pak ještě 30 vteřin.",
    "Vedená bytem: Chyť ji za pouta a veď ji nahou do ložnice. Cestou ji zastav u zdi, u stolu a u dveří a pokaždé se s ní minutu miluj. Cíl: dojít do postele a tam ji dokončit.",
    "Horký zadeček: Dej jí třicet plácnutí dlaní na zadeček, střídavě na obě půlky, pak ji otoč a lízej. Cíl: orgasmus do tří minut.",
    "Sténání za plácnutí: Miluj ji tvrdě a za každé hlasité zasténání dostane plácnutí. Cíl: aby sténala tak, že přestaneš počítat.|180",
    "Anál se dvěma vibrátory: Mrdej ji do zadečku s hodně lubrikantu, jeden vibrátor si drží na klitorisu a druhý jí vsuneš do kundičky. Cíl: tempo podle ní.|240",
    "Houpačka moci: Každou minutu si prohoďte, kdo velí a kdo poslouchá. Příkazy musí být sexuální a splnitelné hned. Cíl: šest minut a tři výměny.|360",
    "Natažená přes stůl: Ona leží na břiše na jídelním stole s rukama spoutanýma a nataženýma před sebe, ty stojíš za ní. Cíl: tvrdé tempo a každých dvacet přírazů rána bičíkem.|180",
    "Kolik jich zvládne: Najdi s vibrátorem místo, kde dojde nejrychleji. Doveď ji k orgasmu, dej jí 30 vteřin pauzu a znovu. Cíl: kolik orgasmů zvládne za deset minut?|600",
    "Tvrdá lžička: Spoutej jí ruce za zády, lehni si za ni na bok, jednou rukou ji drž za bok a druhou jí hlaď klitoris. Cíl: tři minuty tvrdých přírazů bez zpomalení.|180",
    "Rána a prst: Přehni ji přes koleno a po každé ráně bičíkem do ní na chvíli vsuň prst. Cíl: patnáct ran a pak ji prsty dovést k orgasmu.",
    "Nohy spoutané nahoře: Spoutej jí kotníky, zvedni si její nohy na rameno a miluj se s ní. Cíl: těsné a hluboké přírazy – a ptát se, jestli to není moc.|180",
    "Její fantazie: Nech ji říct jednu hardcore fantazii, kterou jste nezkusili, a pak ji přesně tak mrdej. Cíl: splnit ji celou ještě dneska.",
    "Spoutaná na tvé tváři: Lehni si na záda, spoutej jí ruce za zády a nech ji sednout si ti na obličej. Cíl: držet ji za boky a lízat, dokud nedojde a nesesune se.",
    "Silný vibrátor: Zapni vibrátor na nejvyšší stupeň, přitlač jí ho na klitoris a drž ho tam, i když se kroutí. Druhou rukou jí drž zápěstí. Cíl: rychlý a silný orgasmus – stop slovo platí.",
    "Anální jezdkyně: Lehni si na záda a ona si tě s hodně lubrikantu pomalu zavede do zadečku, ty jí hladíš klitoris vibrátorem. Cíl: hloubku i tempo řídí jen ona.|240",
    "Písmeno bičíkem: Nakresli jí lehkými ranami bičíku na zadeček písmeno, třeba první písmeno svého jména. Cíl: když uhodne, dostane orál, když ne, kreslíš znovu.",
    "Deset minut dominance: Deset minut rozhoduješ o všem – poloze, tempu, kdy smí dojít a kam se má dívat. Ona odpovídá jen „ano“. Cíl: dát jí nejsilnější orgasmus večera.|600",
    "Péče po hře: Po nejtvrdším úkolu ji odpoutej, promasíruj jí zápěstí a zadeček, přikryj ji dekou a dej jí napít. Pak ji jemně hlaď prsty, dokud znovu nedojde. Cíl: vystřídat tvrdost něhou.",
    "Finále: Zkombinuj pouta, bičík, oba vibrátory a anál s hodně lubrikantu. Cíl: deset minut bez chvilky nudy, tempo podle ní a na konci společný orgasmus.|600",
  ],

  // Úkoly pro ženu – pro potěšení muže
  female: [
    "Spoutaný a poslepu: Spoutej mu ruce k čelu postele, zavaž mu oči, kuř mu a přikládej mu vibrátor na varlata. Cíl: nepřestat, dokud se neudělá.|300|pouta_postel!",
    "Deset ran pro něj: Předkloň ho přes opěradlo a dej mu deset ran bičíkem, každou o kousek silněji. On počítá. Cíl: teprve po desáté si na něj sednout.|240|predklon!",
    "Prostata a ústa: Prstem s lubrikantem mu masíruj prostatu pohybem „pojď sem“, zatímco mu kouříš. Cíl: tři minuty a tempo určuje jen on.|180|oral_on_vleze",
    "Anál a jeho ruka: Nabídni mu anál s velkým množstvím lubrikantu a jeho ruku si dej na klitoris. Cíl: hloubku i tempo řídíš jen ty.|240|zezadu!",
    "Po orgasmu ještě chvíli: Jezdi na něm a po jeho orgasmu nepřestávej hned, jen zpomal. Cíl: pokračovat, dokud sám neřekne dost.|300|ona_nahore",
    "Spoutaný na kraji postele: Nasaď mu pouta za zády, posaď ho na kraj postele a jezdi na něm tvrdě. Cíl: tři minuty a na stop ho hned odemknout.|180|klin_celem",
    "Dvojitá stimulace pro něj: Jeden vibrátor mu přilož na varlata, druhý na hráz a přitom mu kuř. Cíl: tři minuty a ani jedno nepřerušit.|180|oral_on_vleze",
    "Jen ano nebo stop: Přikaž mu lehnout si a nehýbat se a hoň mu. Smí říct jen „ano“, nebo stop slovo. Cíl: čtyři minuty a na to druhé hned přestat.|240|vedle_on_lezi",
    "Odpírání pro něj: Kouři mu až těsně k vrcholu a pak pokaždé přestaň. Cíl: třikrát ho zastavit a počtvrté ho nechat dojít.|300|oral_on_vleze",
    "Pírko, nebo rána: Spoutej ho, zavaž mu oči a střídej pírko a bičík po celém těle. Cíl: dvacet doteků a ať ani jednou neuhodne, co přijde.|180|pouta_postel!",
    "Poruč mu to sama: Chyť ho za vlasy, přitáhni si ho k sobě a poruč mu, ať tě vezme zezadu. Cíl: dvě minuty tvrdého stálého tempa.|120|predklon",
    "Anál a vibrátor: Nabídni mu anál a sama si přitom drž vibrátor na klitorisu. Cíl: hodně lubrikantu a zrychlit smí až na tvoje slovo.|180|zezadu!",
    "Ty řídíš obojí: Vsuň si vibrátor do kundičky a jeho nech s hodně lubrikantu vniknout do zadečku. Cíl: tempo i hloubku určuješ jen ty.|180|zezadu!",
    "Spoutaný až do konce: Spoutej ho k posteli a honi mu, dokud se neudělá. Cíl: pak pokračovat ještě půl minuty úplně jemně.|300|pouta_postel!",
    "Rána a jazyk: Dej mu pět ran bičíkem na vnitřní stranu stehen a po každé to místo olízni. Cíl: síla pokaždé stejná, ani jedna tvrdší.|180|oral_on_vleze",
    "Jeho ruce za hlavou: Poruč mu, ať klečí s rukama za hlavou, a kuř mu. Cíl: tři minuty – jakmile ruce sundá, přestáváš.|180|klek_ruce_hlava!",
    "Nohy na jeho ramenou: Lehni si na záda, nohy mu dej na ramena a řekni mu, ať přiráží rychle a silně. Cíl: dvě minuty a hlídat si, jestli to není moc.|120|nohy_ramena",
    "Vibrátor mezi vámi: Spoutej ho, polož ho na záda a jezdi na něm s vibrátorem přitisknutým mezi vámi. Cíl: tři minuty a na stop ho odemknout.|180|ona_nahore",
    "Dokud nepoprosí on: Zakaž mu dojít a pak mu kuř. Cíl: nepolevit, dokud tě nahlas nepoprosí o svolení – a pak mu ho dát.|300|oral_on_vleze",
    "Ruka za sebe: Jezdi na něm a přitom si sáhni za sebe a namazaným prstem mu masíruj hráz. Cíl: dvě minuty a ani jednou nezpomalit.|120|ona_nahore",
    "Spoutaný na židli: Spoutej ho, zavaž mu oči, posaď ho na židli a střídej ústa a vibrátor. Cíl: nepřestat, dokud se na židli nezačne kroutit.|180|zidle_celem",
    "Rytmus jeho zadku: Plácej ho dlaní po zadku přesně v tempu, jakým chceš, aby přirážel. Cíl: dvacet plácnutí a ať se do nich trefí.|90|misionar",
    "Nech ho sedět na gauči se spoutanýma rukama za zády. Klekni si nad něj a jezdi na něm.|180",
    "Hoň mu rychle a intenzivně s lubrikantem, zatímco mu olizuješ bradavky. Nepřestávej, dokud se neudělá.",
    "Předkloň ho přes kraj postele, dej mu bičíkem 3 rány, pak ho 3× olízni, pak 3 rány. Opakuj.|180",
    "Lehněte si do lžičky, ty za ním. Prstem s lubrikantem mu masíruj prostatu a druhou rukou mu hoň. Tempo i hloubku určuje jen on.|180",
    "Spoutej mu ruce za zády, klekni si před něj a kouři mu, zatímco stojí opřený o zeď.|120",
    "Vibrátorem mu zvenku dráždi zadek, zatímco na něm jezdíš.|180",
    "Přikaž mu, ať si lehne na záda a drží se čela postele. Jezdi na něm tvrdě – nesmí se pustit.|120",
    "Zavaž mu oči a přivaž mu ruce k nohám postele (pouty nebo šátkem). Pak mu kouři, dokud se neudělá.",
    "Sedni si na kuchyňskou linku a poruč mu, ať tě tvrdě a rychle ojede. Drž ho přitom za zátylek a dvě minuty ho nepouštěj.|120",
    "Vsuň mu vibrátor do zadku (jen takový, který je na to bezpečný – s rozšířenou základnou) a jezdi na něm. Jinak použij prst.|180",
    "Rány na jeho povel: Nasaď mu pouta, polož ho na břicho a dávej mu bičíkem rány přes zadek a stehna. Cíl: nepřestat, dokud sám neřekne dost.|180|na_brise!",
    "Až na povel: Jezdi na něm a on smí dojít jen na tvoje slovo. Odpočítej nahlas od deseti k nule. Cíl: trefit se přesně do nuly.|300|ona_nahore",
    "Jazykem vzadu, rukou vepředu: Olizuj mu zadek a přitom mu honi. Cíl: dvě minuty a ani jedno nepřerušit.|120|na_brise!",
    "Spoutej mu obě ruce nad hlavou a jen ho pomalu líbej po celém těle. Pak na něm ale jezdi tvrdě.|240",
    "Nech ho stát spoutaného uprostřed obýváku se zavázanýma očima. Obcházej ho a dotýkej se ho bičíkem, rukama a vibrátorem.|180",
    "Opři se o stěnu ve sprše a poruč mu, ať tě zezadu tvrdě mrdá celé dvě minuty bez jediného zpomalení.|120",
    "Zapni oba vibrátory na nejvyšší stupeň, jeden mu přilož na varlata, druhý na hráz a přitom mu kouři.|120",
    "Vybírá on: Klekni si, předkloň se a roztáhni si hýždě rukama. Cíl: nechat výběr na něm – a připravit hodně lubrikantu.|240|zezadu!",
    "Přehni ho přes koleno. Plácej ho dlaní po zadku a mezi ranami mu hoň.|90",
    "Posaď ho na židli a spoutej mu ruce za opěradlem. Klekni si a kouři mu, dokud nebude prosit o pauzu.",
    "Chyť ho za zápěstí, přitiskni ho k posteli a jezdi na něm rychle a hluboko.|120",
    "Anál na kraji postele: lehni si na břicho na kraj postele, on stojí, hodně lubrikantu. Cíl: tempo i hloubku určuješ jen ty.|180",
    "Poruč mu, ať se ti dívá do očí a nesmí je zavřít, zatímco mu honíš až do konce.",
    "Spoutej ho a přikaž mu, ať přesně řekne, jestli mu máš honit, kouřit, nebo se na něj nasadit. Dokud to neřekne konkrétně, nedostane nic.",
    "Lehni si na jídelní stůl, poruč mu, ať ti spoutá ruce nad hlavou a vestoje tě tvrdě mrdá. Cíl: tři minuty a ruce ti nesmí rozvázat.|180",
    "Plácni ho bičíkem přes bradavky jen velmi jemně – a hned je olízni. Pětkrát.",
    "Spoutej ho a hoň mu i po orgasmu – jemně, dokud to snese (stop slovo platí).",
    "Jezdi na něm a každých 20 vteřin mu dej plácnutí na stehno. On počítá.|180",
    "Spoutej mu ruce za zády, lehni si na záda a přitáhni si ho na sebe. Nohama ho řiď, jak rychle a hluboko smí.|120",
    "Kouři mu a zároveň mu prstem s lubrikantem masíruj prostatu. Nesmí se pohnout a hloubku určuje jen on.|180",
    "Klekni si na posteli a poruč mu, ať tě tvrdě mrdá zezadu a drží tě u toho za vlasy. Ne bolestivě a na stop tě hned pustí.|120",
    "Prstem s lubrikantem mu pomalu dráždi zadek a zároveň mu přikládej vibrátor na varlata.|180",
    "Rozkaž mu, ať si lehne na podlahu v obýváku s rukama nad hlavou. Obkroč ho a vezmi si ho.|180",
    "Nasaď mu pouta, zavaž mu oči, polož ho na gauč a jezdi na něm ve čtyřech různých polohách. Netuší, co přijde.|240",
    "Jezdi na něm tak tvrdě a rychle, jak to jen jde, a pak se úplně zastav a pomalu ho polib. Opakuj.|180",
    "Nech ho, ať si vybere počet ran bičíkem (1–15). Dej mu je a po poslední ho odměň orálem.",
    "Klekni si, vsuň si vibrátor do kundičky a nabídni mu anál zezadu. Pomalu, s hodně lubrikantu a tempo i hloubku určuješ ty.|180",
    "Oba vibrátory přilož z obou stran na jeho penis a hoň mu jimi, dokud se neudělá.",
    "Postav ho spoutaného před zrcadlo, přitiskni se k němu zezadu a hoň mu až do konce. Musí se u toho dívat.",
    "Poruč mu, ať nahlas popisuje, co cítí, zatímco na něm tvrdě jezdíš. Když přestane mluvit, zpomal.|180",
    "Spoutej ho v koupelně (ruce před tělem), posaď ho na okraj vany a kouři mu pod sprchou, dokud se neudělá.",
    "Jezdi na něm a pokaždé, když přestane přirážet zespodu, plácni ho bičíkem přes stehno.|120",
    "Kouři mu i po orgasmu dál – velmi jemně, dokud tě neodtáhne.",
    "Předkloň se přes kuchyňskou linku, vystrč na něj zadeček a poruč mu, ať tě tvrdě mrdá a drží tě za ramena. Cíl: dvě minuty.|120",
    "Přivaž mu zápěstí k nohám postele pouty nebo šátky, obkroč mu obličej a nech se lízat. Pak se posuň níž a sedni si na něj.|180",
    "Jezdi na něm a zároveň mu vsuň vibrátor do zadku (s rozšířenou základnou) nebo tam dej prst s lubrikantem.|180",
    "Zakaž mu dotknout se sebe i tebe. Pak ho aspoň 5 minut dráždi, ale nenech ho dojít.|300",
    "Spoutej ho k posteli, zavaž mu oči a nech vibrátor na jeho varlatech na nízký stupeň. Pak se na minutu potichu odtáhni (zůstaň v pokoji), ať neví, kde jsi – a pak pokračuj.|60",
    "Poruč mu, ať tě miluje rychle. Když zpomalí, dostane ránu bičíkem.|120",
    "Opři se o zeď v chodbě a poruč mu, ať tě vezme tvrdě zezadu. Jeho ruce si drž na bocích.|120",
    "Sedni si na pračku v plném odstřeďování a nech se od něj tvrdě a rychle ojet. Cíl: dvě minuty, než odstřeďování skončí.|120",
    "Plácni ho po zadku třikrát bičíkem, třikrát dlaní a nakonec ho třikrát polib.",
    "Nasaď mu pouta s rukama před tělem a kouři mu, zatímco ti jeho spoutané ruce drží hlavu.|180",
    "Nabídni mu anál v misionáři: podlož si boky polštářem, hodně lubrikantu a dívej se mu do očí. Tempo i hloubku určuješ jen ty.|180",
    "Klekni si na gauč, vsuň si vibrátor do kundičky a nech ho, ať tě s hodně lubrikantu pomalu mrdá do zadečku. Tempo určuješ ty.|180",
    "Hoň mu a kouři zároveň, dokud se neudělá. Pak ho olízni dočista.",
    "Spoutej mu ruce za zády a nech ho ležet na zádech. Sedni si na něj a jezdi pomalu a hluboko.|180",
    "Zakaž mu mluvit, dokud se neudělá. Za každé slovo dostane ránu bičíkem.",
    "Přikládej mu vibrátor střídavě na varlata a na zadek, zatímco na něm jezdíš.|180",
    "Zavaž mu oči, spoutej ho a vsuň mu prst do pusy. Ať ho saje, zatímco na něm jezdíš.|120",
    "Dvacet a pak na něj: Dej mu dvacet rychlých lehkých plácnutí bičíkem, on počítá nahlas. Cíl: teprve po dvacátém si na něj sednout.|180|ona_nahore",
    "Lehni si na kraj jídelního stolu a zatímco tě miluje, přikládej mu oba vibrátory na bradavky.|180",
    "Opři se o parapet okna se zataženými závěsy a poruč mu, ať tě miluje zezadu a ruce přitom drží za zády. Přirážej mu proti.|120",
    "Nech ho ležet se spoutanýma rukama na zádech. Olizuj ho, hoň mu, jezdi na něm – rozmazluj ho, dokud neřekne dost.",
    "Rozkaž mu, ať si sám drží vibrátor na varlatech – pokud ho sundá, přestaneš. Pak na něm tvrdě jezdi.|180",
    "Nabídni mu anál vestoje u kuchyňské linky: hodně lubrikantu a pomalý začátek. Tempo i hloubku určuješ celou dobu jen ty.|180",
    "Jen pírko a vibrace: Spoutej ho a doveď ho k orgasmu výhradně pírkem a vibrátorem. Cíl: nepoužít ani ústa, ani ruce.|300|pouta_postel!",
    "Plácni ho bičíkem na zadek vždy, když zasténá. Pak na něm jezdi tak, aby sténal pořád.|120",
    "Kouři mu, jeden prst mu s lubrikantem vsuň do zadku a druhou rukou mu masíruj varlata.|90",
    "Nech ho, ať si vybere: rány bičíkem, nebo vibrátor na varlata, zatímco na něm jezdíš. Může si vybrat i obojí.|180",
    "Klekni si na koberec a prohni záda. Poruč mu, ať tě drží za oba boky a tvrdě tě zezadu mrdá. Cíl: tři minuty bez zpomalení.|180",
    "Musí to vyslovit on: Spoutej ho a nech ho nahlas říct, jestli mu máš kouřit, nebo honit. Cíl: nedat mu nic, dokud to neřekne celou větou.|300|klek_pouta!",
    "Nabídni mu anál na boku s hodně lubrikantu – ty ležíš, on za tebou. Vibrátor si přikládej na klitoris a tempo určuješ ty.|180",
    "Jezdi na něm a jednou rukou mu zakrývej pusu, aby tlumil sténání (nos nech volný).|90",
    "Lehni si na podlahu v kuchyni a poruč mu, ať tě v misionáři tvrdě mrdá. Rychle, hluboko a celé dvě minuty bez přestávky.|120",
    "Zavaž mu oči a přikaž mu, ať si lehne na postel na záda. Nech ho minutu čekat a pak ho dráždi bičíkem a vibrátorem.|60",
    "Vsuň si vibrátor a sedni si na něj tak, abyste ho oba cítili.|180",
    "Odpírání: spoutej ho a pokaždé, když se blíží orgasmu, dej mu lehkou ránu bičíkem a přestaň. Až po pátém pokusu ho nech dojít.",
    "Spoutej ho k čelu postele a jezdi na něm tvrdě zády k němu, ať vidí všechno.|120",
    "Lízej mu zadek a varlata střídavě, zatímco mu honíš.|120",
    "Nabídni mu zadeček a nech ho pomalu vniknout, ale tempo a hloubku určuješ ty.|180",
    "Na gauči se přehni přes područku a poruč mu, ať tě tvrdě vezme zezadu. Pak mu dej ránu bičíkem a zase zpomalte.|180",
    "Vezmi ho do sprchy, spoutej mu ruce před tělem, vystrč na něj zadeček a nech ho, ať tě miluje. Pozor na uklouznutí.|120",
    "Přilož mu vibrátory na varlata a hráz a nech ho, ať je sevře stehny. Pak mu olizuj penis a rukama mu drž zápěstí.|180",
    "Rozkaž mu, ať ti řekne tu nejdivočejší věc, kterou by s tebou chtěl, a pak se na něj nasaď přesně tak. Splň mu to ještě dneska.",
    "Jezdi na něm tvrdě a on smí dojít, jen když si o to řekne tvým jménem.|180",
    "Spoutej mu ruce, zavaž mu oči a dej mu na výběr: tvrdá jízda, nebo 5 minut orálu. Pak udělej to druhé taky.",
    "Lehni si na kraj postele, roztáhni nohy a poruč mu, ať si tě vezme tvrdě vestoje.|120",
    "Nabídni mu pomalý anál s hodně lubrikantu a po každém přírazu mu řekni, jak úžasný je. Tempo i hloubku určuješ ty.|180",
    "Rychle a pak pomalu: Doveď ho rukou k orgasmu co nejrychleji. Cíl: ten druhý mu dopřát co nejpomaleji – ať trvá aspoň pět minut.|300|vedle_on_lezi",
    "Spoutaný podle sebe: Dej mu pouta a nech ho rozhodnout, kam mu připneš ruce. Cíl: pak ho potěšit jen pusou, dokud se neudělá.|300|oral_on_vleze",

    // Karty s cílem
    "Výslech pro něj: Spoutej mu ruce za zády a posaď ho na židli. Za upřímnou odpověď minuta kouření, za vytáčku rána bičíkem. Cíl: prozradit aspoň tři fantazie.|300|zidle_celem",
    "Dva orgasmy: Spoutej ho k posteli. Cíl: dva orgasmy za večer – první rukou, druhý jízdou na něm – a mezi nimi ho nepouštěj z pout.",
    "Prostata na rozehřátí: Namasíruj mu hráz olejem, pak prstem s lubrikantem kruž kolem a nakonec jeden prst pomalu dovnitř, ohnutý k břichu. Cíl: nepokračovat, dokud sám neřekne, že chce víc.|300|vedle_on_lezi",
    "Král na deset minut: On leží a rozkazuje a ty plníš každý jeho sexuální příkaz. Cíl: splnit všechno, dokud se neudělá.|600",
    "Abeceda bičíkem: On je na všech čtyřech. Dej mu 26 lehkých ran a u každé řekne další písmeno abecedy. Když se splete, začíná od A. Cíl: dojít k Z – pak ho odměň pusou.",
    "Bez rukou a pusy: Spoutej mu ruce nad hlavou. Jeden vibrátor mu přilož na varlata, druhý na hráz a ať je sevře stehny. Ty ho jen líbáš. Cíl: dovést ho k orgasmu bez tvých rukou a pusy.",
    "Anál v zrcadle: Lehněte si na bok čelem k zrcadlu, on za tebou, hodně lubrikantu a pomalu. Cíl: tempo i hloubku určuješ jen ty.|300|lzicka",
    "Odpočet pro něj: Hoň mu rukou a on smí dojít až po odpočítání od 30 do 0 nahlas. Když dojde dřív, dostane pět ran bičíkem. Cíl: aby se udělal přesně na nule.",
    "Stisknutá stehna: Lehni si na břicho s nohama u sebe a spoutej si kotníky. Nech ho, ať tě miluje zezadu. Cíl: tisknout stehna, aby to bylo co nejtěsnější, dokud se neudělá.|240",
    "Nehybný u zdi: Spoutej mu ruce za zády a postav ho ke zdi. Zatímco mu kouříš, nesmí se pohnout – za každý pohyb rána bičíkem. Cíl: aby vydržel dvě minuty.|120",
    "Dvojitý průnik: Vsuň si vibrátor do vagíny a nech ho vniknout do zadečku – nebo naopak, s rozšířenou základnou. Cíl: hodně lubrikantu a zrychlit smí až na tvoje slovo.|240|lzicka",
    "Tvrdě a s plácnutím: Opři se přes opěradlo gauče a přikaž mu, ať tě chytí za boky a přiráží tvrdě. Každých 30 vteřin tě plácne. Cíl: tři minuty bez zpomalení.|180",
    "Po orgasmu dál: Po jeho orgasmu ho nepouštěj – velmi jemně pokračuj rukou nebo pusou a drž mu ruce. Cíl: vydržet 30 vteřin jeho citlivosti – stop slovo platí.|30",
    "Prostata u postele: On klečí na zemi, hrudníkem na posteli, ruce spoutané. Prstem s lubrikantem mu masíruj prostatu a zespodu mu hoň. Cíl: hloubku určuje jen on.|180",
    "Bolest a slast pro něj: Přehni ho přes koleno a plácej ho bičíkem. Po každé ráně řekne číslo od 1 do 10. Cíl: držet se mezi 5 a 7, pak ho otočit a kouřit mu.",
    "Nikdy neví, co přijde: Spoutej ho a zavaž mu oči. Každých 20 vteřin něco jiného – rána bičíkem, pírko, vibrátor, pusa, tvůj klín. Cíl: pět minut překvapení.|300",
    "Prosím: Jezdi na něm a zastav se. Pokračuj jen tehdy, když ti přesně řekne, co chce, a začne slovy „prosím, udělej mi…“. Cíl: aby to řekl aspoň pětkrát.",
    "Anál na stole: Lehni si na kraj stolu s nohama nahoře, on stojí. Hodně lubrikantu a pomalý začátek. Cíl: tempo i hloubku určuješ rukou na jeho břiše jen ty.|240|nohy_ramena",
    "Připoutaný k židli: Posaď ho na židli s rukama spoutanýma za opěradlem, sedni si na něj obkročmo a jezdi. Cíl: on se nesmí hýbat, ty rozhoduješ o všem, dokud se neudělá.",
    "Trojitá péče: Přilož mu vibrátor na koule, prstem s lubrikantem mu masíruj prostatu a kouři mu. Cíl: udržet všechno najednou a hloubku určuje on.",
    "Za vlasy: Chyť ho pevně, ale ne bolestivě za vlasy, přitáhni si jeho pusu ke krku a tvrdě na něm jezdi. Cíl: šeptat mu do ucha, jak je dokonalý.|180",
    "Rány a hlazení: Předkloň ho přes linku. Tři rány bičíkem na zadek, pak ho třikrát pevně pohlaď zezadu mezi nohama, pak znovu rány. Cíl: deset kol – pak ho otoč a dokonči pusou.",
    "Rozepjatý: Spoutej mu zápěstí k nohám postele nebo nad hlavou a roztáhni mu nohy. Cíl: kouřit mu k orgasmu, zatímco se nemůže bránit.",
    "Prst při jízdě: Jezdi na něm a sáhni si za sebe – namazaný prst mu vsuň do zadku. Cíl: jezdit tak, aby se prst hýbal s tebou, dokud se neudělá.|180",
    "Pět přerušení pro něj: Hoň mu k orgasmu a pokaždé, když řekne „už budu“, přestaň. Když vydrží pět přerušení bez prošení, dostane orgasmus, jaký si řekne. Cíl: dotáhnout hru do konce.",
    "Klečí s rukama za hlavou: Ať klečí nahý na koberci s rukama za hlavou. Obcházej ho s bičíkem a dotýkej se ho. Cíl: pak si před něj lehni a přikaž mu, ať si tě vezme – ruce smí sundat až na tvůj povel.|240",
    "Prostata s vibrátorem: Prstem s lubrikantem mu masíruj prostatu a druhou rukou mu hoň, vibrátor na hrázi ať si drží sám. Cíl: hloubku určuje jen on.",
    "Tvrdá jízda a polibek: Jezdi na něm dvaceti tvrdými pohyby, pak se na 10 vteřin zastav a polib ho. Cíl: deset kol – v posledním nepřestávej.|300",
    "Jeho spoutané ruce na tobě: Spoutej mu ruce před tělem a sedni si na něj tak, aby měl ruce na tvém klíně. Jezdi na něm a přikaž mu, ať tě hladí. Cíl: dojít oba – ty první.|240",
    "Sprcha a spoutaný: Ve sprše mu spoutej ruce před tělem, zvedni mu je nad hlavu a drž je. Klekni si na ručník a kouři mu. Cíl: dvě minuty – a pozor na uklouznutí.|120",
    "Fáze na „ano“: Spoutej ho, zavaž mu oči a polož ho na záda. Nejdřív mu kouři, pak mu prstem s lubrikantem masíruj prostatu. Cíl: hloubku určuje jen on.",
    "Povel pro něj s trestem: Hoň mu a smí dojít jen na „teď“. Když dojde dřív, dostane pět ran bičíkem. Cíl: aby se udělal přesně na povel.",
    "Pod stolem pro něj: On sedí na židli u stolu s rukama spoutanýma za opěradlem, ty jsi pod stolem a kouříš mu. Cíl: zastavit tě může jen stop slovem.",
    "Trest a odměna: Jeho hruď a bradavky lehce plácej bičíkem, penis odměňuj pusou. Střídej po 20 vteřinách. Cíl: dokud se neudělá.|240",
    "Anál vestoje: Opři se o zeď a nabídni mu zadeček. Použijte hodně lubrikantu a ať začne jen špičkou. Cíl: ty řídíš hloubku rukou na jeho boku.|180",
    "Přetahovaná: Minutu se ho snaž povalit na postel, on se hravě brání. Když ho povalíš, spoutej ho a nasaď se na něj. Cíl: skončit s ním v sobě.",
    "Tři vrcholy: Spoutej ho a během patnácti minut ho třikrát doveď těsně k vrcholu – rukou, pusou a jízdou. Cíl: nechat ho dojít až napotřetí.|900",
    "Spoutaný na gauči: Spoutej mu ruce za zády, posaď ho na gauč a roztáhni mu nohy. Cíl: kouřit mu, dokud nebude prosit o pauzu – a pak ještě 30 vteřin.",
    "Vedený do ložnice: Chyť ho za pouta a veď ho nahého bytem. Zastav se u zdi, u stolu a u dveří a pokaždé mu minutu kouři nebo hoň. Cíl: dojít do postele a tam ho dokončit.",
    "Horký zadek: Dej mu třicet plácnutí dlaní na zadek, pak ho otoč a pomalu mu olizuj penis. Cíl: orgasmus do tří minut.",
    "Sténání za trest: Jezdi na něm tvrdě a za každé hlasité zasténání dostane plácnutí. Cíl: aby sténal tak, že přestaneš počítat.|180",
    "Plná pro něj: Nech ho s hodně lubrikantu vniknout análně zezadu, jeden vibrátor si drž na klitorisu a druhý si vsuň do kundičky. Cíl: tempo určuješ ty.|240",
    "Výměna velení: Každou minutu si prohoďte, kdo velí a kdo poslouchá. Příkazy musí být sexuální a splnitelné hned. Cíl: šest minut – kdo dá odvážnější příkaz, dojde jako první.|360",
    "Opřený o stůl: Předkloň ho přes jídelní stůl s rukama spoutanýma a nataženýma. Zezadu mu hoň a po každých dvaceti pohybech ho plácni bičíkem přes zadek. Cíl: aby se udělal opřený o stůl.|180",
    "Druhé kolo: Doveď ho k orgasmu co nejrychleji, nech ho chvíli vydechnout a pak začni znovu pusou. Cíl: druhý orgasmus do dvaceti minut.",
    "Tvrdá lžička pro něj: Spoutej mu ruce za zády, lehni si před něj zády k němu a nech ho, ať tě miluje zezadu. Tlač se proti němu tvrdě. Cíl: tři minuty – tvrdost určuješ ty.|180",
    "Rána a pohlazení: Přehni ho přes koleno a po každé ráně bičíkem ho jednou pomalu pohlaď zespodu mezi nohama. Cíl: patnáct ran a pak ho rukou dovést k orgasmu.",
    "Spoutané kotníky nahoře: Lehni si na záda, spoutej si kotníky, zvedni nohy na jeho rameno a nech se tvrdě mrdat. Cíl: řekni mu, kdyby to bylo moc.|180",
    "Jeho fantazie: Nech ho říct jednu hardcore fantazii, kterou jste nezkoušeli, a pak se na něj přesně tak nasaď. Cíl: splnit ji celou.",
    "Spoutaný pod tebou: Spoutej mu ruce nad hlavou a sedni si mu na obličej. Cíl: nechat se lízat, dokud nedojdeš, pak se posunout níž a jezdit na něm.",
    "Rychle a silně: Hoň mu tvrdě a rychle s lubrikantem a druhou rukou mu drž zápěstí. Cíl: rychlý silný orgasmus – stop slovo platí.",
    "Anální jízda: Sedni si na něj a s hodně lubrikantu si ho pomalu zaveď do zadečku, vibrátor si drž na klitorisu. Cíl: hloubku i tempo řídíš jen ty.|240",
    "Písmeno na jeho zadku: Nakresli mu lehkými ranami bičíku na zadek písmeno. Cíl: když uhodne, odměna pusou, když ne, kreslíš znovu.",
    "Deset minut vlády: Deset minut rozhoduješ o všem – poloha, tempo, kdy smí dojít, kam se dívá. On říká jen „ano“. Cíl: dát mu nejsilnější orgasmus večera.|600",
    "Péče po všem: Po nejtvrdším úkolu ho odpoutej, promasíruj mu zápěstí a zadek, přikryj ho a dej mu napít. Pak ho pomalu hlaď, dokud se mu znovu nepostaví. Cíl: vystřídat tvrdost něhou.",
    "Velké finále: Zkombinuj pouta, bičík, oba vibrátory, prostatu a svůj klín. Cíl: deset minut bez chvilky nudy a na konci společný orgasmus.|600",
  ],
});
