// Kategorie 5 – Hardcore (dávka d)
// Témata: odpírání orgasmu, vynucené orgasmy, přestimulace, výdrž a výměna moci.
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 5,

  male: [
    "Doveď ji na hranu pětkrát za sebou a pokaždé přestaň. Napošesté ji nech dojít.|300|pouta_postel",
    "Deset hran: Dnes se dostane na hranu desetkrát, než jí to dovolíš. Ona počítá nahlas. Cíl: dojít do deseti.|300|pouta_postel",
    "Zakaž jí dojít po celou dobu této karty, ať děláš cokoli.|300|pouta_postel",
    "Nech ji prosit o dovolení celou větou a pak jí ho odepři.|300|klek_pouta",
    "Dráždi ji a pokaždé, když řekne, že už to přijde, přestaneš.|300|deprivace",
    "Řekni jí, že dneska dojde jen jednou. Ať si dobře rozmyslí kdy.|300|misionar",
    "Doveď ji na hranu a nech ji tam ležet celou minutu bez dotyku.|300|pouta_postel",
    "Po žádosti: Musí tě požádat třikrát, pokaždé jinými slovy. Teprve potřetí to dostane. Cíl: tři různé prosby.|300|klek_pouta",
    "Nech ji na hraně tak dlouho, dokud se jí netřesou nohy.|300|pouta_postel",
    "Střídej pět vteřin naplno a dvacet vteřin nic.|300|vedle_ona_lezi",
    "Dráždi ji vibrátorem a vždycky ho odtáhni těsně před koncem.|300|pouta_postel",
    "Doveď ji na hranu ústy, pak rukou, pak vibrátorem. Pokaždé přestaň.|300|oral_klek",
    "Tři cesty na hranu: Jazykem, prsty a vibrátorem. Po každé úplné zastavení. Cíl: tři různá zastavení.|300|oral_klek",
    "Nech ji dojít a hned pokračuj dál, i když se bude bránit. Jen jemně.|300|pouta_postel",
    "Po jejím orgasmu ještě půl minuty nepřestávej.|300|oral_klek",
    "Přestimulace: Po prvním vrcholu pokračuj, dokud neřekne stop slovo nebo dost. Cíl: vydržet oba.|300|pouta_postel",
    "Doveď ji ke dvěma orgasmům za sebou bez přestávky.|300|pouta_postel",
    "Doveď ji ke třem orgasmům, každý jinak.|300|pouta_postel",
    "Nech ji dojít třikrát: rukou, ústy a vibrátorem.|300|pouta_postel",
    "Vynucená série: Dneska nesmí přestat, dokud nedojde třikrát. Mezi tím jen zpomalíš. Cíl: tři za sebou.|300|pouta_postel",
    "Spoutej ji a nech ji dojít tolikrát, kolikrát to zvládne.|300|pouta_postel",
    "Po orgasmu jí přilož vibrátor a počítej do dvaceti.|300|pouta_postel",
    "Po orgasmu ji ještě chvíli lízej, dokud tě neodstrčí.|300|oral_klek",
    "Dej jí minutu na to, aby se udělala. Když to nestihne, nebude nic.|60|vedle_ona_lezi",
    "Minuta a dost: Máš přesně šedesát vteřin. Pokud to nestihneš, karta je splněná bez konce. Cíl: stihnout to.|60|oral_klek",
    "Řekni jí, že nesmí dojít dřív než za pět minut.|300|misionar",
    "Řekni jí, že nesmí dojít později než za dvě minuty.|120|oral_klek",
    "Výdrž na čas: Ona se snaží vydržet co nejdéle a ty děláš všechno pro opak. Cíl: rozhodnout to do tří minut.|180|vedle_ona_lezi",
    "Nech ji vybrat: teď rychle, nebo za deset minut pořádně.|300|misionar",
    "Dej jí dvě minuty, kdy smí prosit. Pak už ne.|300|klek_pouta",
    "Nech ji počítat nahlas, kolik vteřin ještě vydrží.|300|pouta_postel",
    "Střídej ji a sebe: minutu ona, minutu ty. Kdo dřív, ten prohrál.|300|p69",
    "Souboj o výdrž: Oba zároveň a kdo první dojde, splní druhému přání. Cíl: vydržet déle.|300|p69",
    "Po každé minutě se prohodíte v tom, kdo poroučí.|300|kontrola_vsede",
    "První polovinu rozhoduješ ty, druhou ona. Beze slov.|300|kontrola_vsede",
    "Nech ji převzít kontrolu uprostřed úkolu, i když se ti nechce.|300|ona_nahore",
    "Výměna moci: Domluvte si signál, po kterém si okamžitě vyměníte role. Použijte ho třikrát. Cíl: tři výměny.|300|kontrola_vsede",
    "Nech ji rozhodnout, jestli bude dneska poroučet, nebo poslouchat.|300|klek_pouta",
    "Dej jí právo tě kdykoli zastavit. A ať ho použije.|300|pouta_postel",
    "Řekni jí, že dneska všechno rozhoduje ona, a dodrž to.|300|ona_nahore",
    "Dráždi ji vibrátorem tak dlouho, dokud neztratí přehled o čase.|300|deprivace",
    "Zavaž jí oči a nech ji nevědět, kdy přijde konec.|300|deprivace",
    "Slepé odpírání: Se zavázanýma očima ji drž na hraně tak dlouho, jak vydržíš ty. Cíl: pět minut.|300|deprivace",
    "Dráždi ji a vždycky, když se zhluboka nadechne, přestaneš.|300|pouta_postel",
    "Nech ji na hraně a mezitím jí šeptej, co uděláš, až jí to dovolíš.|300|pouta_postel",
    "Doveď ji na hranu a pak ji nech ležet a jen se dívej.|300|pouta_postel",
    "Řekni jí, že dovolení dostane, až ti řekne tři sprosté věty.|300|klek_pouta",
    "Cena za dovolení: Za každé svolení musí něco splnit. Tři úkoly, tři svolení. Cíl: projít všechny tři.|300|klek_pouta",
    "Nech ji dojít a hned ji vezmi zezadu, než se stihne vzpamatovat.|300|zezadu",
    "Po jejím orgasmu pokračuj v milování, ale úplně pomalu.|300|misionar",
    "Nech ji dojít v jedné poloze a hned ji převrať do jiné.|300|zezadu",
    "Doveď ji na hranu ve třech různých polohách.|300|zezadu",
    "Nech ji dojít a pak jí dej dvě minuty klidu. Pak zase.|300|pouta_postel",
    "Přestávka mezi vlnami: Dvě minuty naplno, dvě minuty úplný klid, a znovu. Cíl: tři vlny.|300|vedle_ona_lezi",
    "Dráždi ji tak dlouho, až ti sama řekne, že už nemůže.|300|pouta_postel",
    "Řekni jí, že když se udělá bez dovolení, dostane deset ran.|300|predklon",
    "Nech ji vybrat mezi jedním dlouhým a třemi krátkými.|300|vedle_ona_lezi",
    "Dráždi ji, ale pokaždé jinak, ať si nezvykne.|300|vedle_ona_lezi",
    "Nikdy dvakrát stejně: Každých třicet vteřin změň způsob. Ani jednou se neopakuj. Cíl: deset různých.|300|vedle_ona_lezi",
    "Dej jí vibrátor a řekni, že ho smí použít, až ti to dovolíš.|300|pouta_postel",
    "Nech ji držet vibrátor u sebe, ale zapnout ho smí až na povel.|300|pouta_postel",
    "Dráždi ji a nech ji říkat čísla od jedné do desíti podle toho, jak blízko je.|300|pouta_postel",
    "Na desítce stop: Jakmile řekne devět, okamžitě přestaneš. Pětkrát. Cíl: nikdy nenechat desítku.|300|pouta_postel",
    "Nech ji dojít a hned pokračuj, ale jen prsty.|300|vedle_ona_lezi",
    "Doveď ji na hranu a pak ji nech, ať se dodělá sama.|300|vedle_ona_lezi",
    "Nech ji dojít, aniž by ses jí dotkl. Jen slovy.|300",
    "Jen hlasem: Doveď ji tam jen tím, co říkáš. Ani jeden dotek. Cíl: dokázat to.|300",
    "Řekni jí, že když vydrží deset minut, splníš jí jakékoli přání.|300|pouta_postel",
    "Nech ji dojít v poloze, kterou nikdy nezkusila.|300|drep",
    "Doveď ji na hranu a pak ji polib a nech to být.|300|pouta_postel",
    "Nech ji dojít a pak ji drž, dokud se nezklidní.|300|lzicka",
    "Konec s péčí: Po poslední vlně ji zabal do deky a chvíli jen drž. Cíl: nevynechat to.|180|lzicka",
    "Dráždi ji pomalu tak dlouho, až ztratí trpělivost.|300|vedle_ona_lezi",
    "Nech ji na hraně, dokud ti to sama nezakáže.|300|pouta_postel",
    "Řekni jí, kolikrát dneska dojde, a to číslo dodrž.|300|pouta_postel",
    "Nech ji dojít, zatímco jí držíš ruce nad hlavou.|300|kontrola_vsede",
    "Dráždi ji a pokaždé, když se pohne, začínáš od začátku.|300|pouta_postel",
    "Bez pohybu: Ona nesmí pohnout ani prstem. Každý pohyb vrací počítadlo na nulu. Cíl: dojít tak do konce.|300|pouta_postel",
    "Nech ji dojít třikrát a po každém se jí zeptej, jestli chce další.|300|pouta_postel",
    "Doveď ji na hranu a nech ji rozhodnout, jestli chce pokračovat.|300|pouta_postel",
    "Dráždi ji tak dlouho, dokud nezapomene, kde je.|300|deprivace",
    "Nech ji dojít, ale až po tom, co se ti podívá do očí a řekne to nahlas.|300|kontrola_vsede",
    "Poslední svolení: Ona čeká na jediné slovo od tebe. Neřekni ho dřív než na konci. Cíl: načasovat to přesně.|300|pouta_postel",
    "Nech ji dojít a hned potom ji jen tiše obejmi.|180|lzicka",
  ],

  female: [
    "Doveď ho na hranu pětkrát za sebou a pokaždé přestaň. Napošesté ho nech dojít.|300|pouta_postel",
    "Deset hran: Dneska se dostane na hranu desetkrát, než mu to dovolíš. On počítá nahlas. Cíl: dojít do deseti.|300|pouta_postel",
    "Zakaž mu se udělat po celou dobu této karty, ať děláš cokoli.|300|pouta_postel",
    "Nech ho prosit o dovolení celou větou a pak mu ho odepři.|300|klek_pouta",
    "Dráždi ho a pokaždé, když řekne, že už to přijde, přestaneš.|300|deprivace",
    "Řekni mu, že dneska dojde jen jednou. Ať si dobře rozmyslí kdy.|300|ona_nahore",
    "Doveď ho na hranu a nech ho tam ležet celou minutu bez dotyku.|300|pouta_postel",
    "Třikrát a jinak: Požádat tě musí třikrát a pokaždé jinými slovy, jinak nedostane nic. Cíl: tři různé prosby.|300|klek_pouta",
    "Nech ho na hraně tak dlouho, dokud se mu netřesou nohy.|300|pouta_postel",
    "Pět vteřin naplno a pak dvacet vteřin absolutní klid. Pořád dokola.|300|vedle_on_lezi",
    "Dráždi ho vibrátorem a vždycky ho odtáhni těsně před koncem.|300|pouta_postel",
    "Doveď ho na hranu ústy, pak rukou, pak vibrátorem. Pokaždé přestaň.|300|oral_on_vleze",
    "Tři cesty na hranu: Jazykem, rukou a vibrátorem. Po každé úplné zastavení. Cíl: tři různá zastavení.|300|oral_on_vleze",
    "Nech ho dojít a hned pokračuj dál, i když se bude bránit. Jen jemně.|300|pouta_postel",
    "Po jeho vyvrcholení ještě půl minuty nepřestávej.|300|oral_on_vleze",
    "Přestimulace: Po prvním konci pokračuj, dokud neřekne stop slovo nebo dost. Cíl: vydržet oba.|300|pouta_postel",
    "Doveď ho na hranu a nech ho tam, dokud neztratí řeč.|300|pouta_postel",
    "Nech ho dojít a pak se ho ještě chvíli dotýkej, i když to bude na hraně snesitelnosti.|300|pouta_postel",
    "Doveď ho dvakrát na hranu a teprve potřetí ho nech.|300|pouta_postel",
    "Vynucený konec: Dneska nesmí přestat, dokud mu to nedovolíš, a to bude až po deseti minutách. Cíl: vydržet oba.|300|pouta_postel",
    "Spoutej ho a doveď ho na konec bez toho, aby se mohl hýbat.|300|pouta_postel",
    "Po jeho konci mu přilož vibrátor a počítej do dvaceti.|300|pouta_postel",
    "Po jeho konci mu ještě chvíli kouři, dokud tě neodstrčí.|300|oral_on_vleze",
    "Dej mu minutu na to, aby se udělal. Když to nestihne, nebude nic.|60|vedle_on_lezi",
    "Šedesát vteřin: Tolik času máš, a když to nestihneš, karta končí bez odměny. Cíl: stihnout to.|60|oral_on_vleze",
    "Řekni mu, že se nesmí udělat dřív než za pět minut.|300|ona_nahore",
    "Řekni mu, že se nesmí udělat později než za dvě minuty.|120|oral_on_vleze",
    "Výdrž na čas: On se snaží vydržet co nejdéle a ty děláš všechno pro opak. Cíl: rozhodnout to do tří minut.|180|vedle_on_lezi",
    "Nech ho vybrat: teď rychle, nebo za deset minut pořádně.|300|ona_nahore",
    "Dej mu dvě minuty, kdy smí prosit. Pak už ne.|300|klek_pouta",
    "Nech ho počítat nahlas, kolik vteřin ještě vydrží.|300|pouta_postel",
    "Střídejte se: minutu on, minutu ty. Kdo dřív, ten prohrál.|300|p69",
    "Kdo dřív prohrál: Užívejte si zároveň a ten, kdo dojde první, plní přání toho druhého. Cíl: vydržet déle.|300|p69",
    "Každou minutu si vyměňte, kdo z vás dvou rozkazuje.|300|kontrola_vsede",
    "První polovinu rozhoduješ ty, druhou on. Beze slov.|300|kontrola_vsede",
    "Nech ho převzít kontrolu uprostřed úkolu, i když se ti nechce.|300|zezadu",
    "Signál k výměně: Dohodněte se na znamení, po kterém si hned prohodíte role, a použijte ho třikrát. Cíl: tři výměny.|300|kontrola_vsede",
    "Nech ho rozhodnout, jestli bude dneska poroučet, nebo poslouchat.|300|klek_pouta",
    "Dej mu právo tě kdykoli zastavit. A ať ho použije.|300|pouta_postel",
    "Řekni mu, že dneska všechno rozhoduje on, a dodrž to.|300|zezadu",
    "Dráždi ho vibrátorem tak dlouho, dokud neztratí přehled o čase.|300|deprivace",
    "Zavaž mu oči a nech ho nevědět, kdy přijde konec.|300|deprivace",
    "Slepé odpírání: Se zavázanýma očima ho drž na hraně tak dlouho, jak vydržíš ty. Cíl: pět minut.|300|deprivace",
    "Dráždi ho a vždycky, když se zhluboka nadechne, přestaneš.|300|pouta_postel",
    "Nech ho na hraně a mezitím mu šeptej, co uděláš, až mu to dovolíš.|300|pouta_postel",
    "Doveď ho na hranu a pak ho nech ležet a jen se dívej.|300|pouta_postel",
    "Řekni mu, že dovolení dostane, až ti řekne tři sprosté věty.|300|klek_pouta",
    "Něco za něco: Každé svolení si musí vykoupit splněným úkolem. Tři a tři. Cíl: projít všechny tři.|300|klek_pouta",
    "Nech ho dojít a hned si na něj sedni, než se stihne vzpamatovat.|300|ona_nahore",
    "Po jeho konci pokračuj v milování, ale úplně pomalu.|300|ona_nahore",
    "Nech ho dojít v jedné poloze a hned ho převrať do jiné.|300|zezadu",
    "Doveď ho na hranu ve třech různých polohách.|300|zezadu",
    "Nech ho dojít a pak mu dej dvě minuty klidu. Pak zase.|300|pouta_postel",
    "Vlna a klid: Dvě minuty naplno, dvě minuty naprostý klid, a zase od začátku. Cíl: tři vlny.|300|vedle_on_lezi",
    "Dráždi ho tak dlouho, až ti sám řekne, že už nemůže.|300|pouta_postel",
    "Řekni mu, že když se udělá bez dovolení, dostane deset ran.|300|predklon",
    "Nech ho vybrat mezi jedním dlouhým a třemi krátkými koly.|300|vedle_on_lezi",
    "Dráždi ho, ale pokaždé jinak, ať si nezvykne.|300|vedle_on_lezi",
    "Pokaždé jinak: Po třiceti vteřinách vždycky změň způsob a nic neopakuj. Cíl: deset různých.|300|vedle_on_lezi",
    "Dej mu vibrátor a řekni, že ho smí použít, až mu to dovolíš.|300|pouta_postel",
    "Nech ho držet vibrátor u sebe, ale zapnout ho smí až na povel.|300|pouta_postel",
    "Dráždi ho a nech ho říkat čísla od jedné do desíti podle toho, jak blízko je.|300|pouta_postel",
    "Devítka je konec: Jakmile vysloví devítku, okamžitě zastavíš. Pětkrát za sebou. Cíl: nikdy nedojít na desítku.|300|pouta_postel",
    "Nech ho dojít a hned pokračuj, ale jen rukou.|300|vedle_on_lezi",
    "Doveď ho na hranu a pak ho nech, ať se dodělá sám.|300|vedle_on_lezi",
    "Nech ho dojít, aniž by ses ho dotkla. Jen slovy.|300",
    "Jen hlasem: Doveď ho tam jen tím, co říkáš. Ani jeden dotek. Cíl: dokázat to.|300",
    "Řekni mu, že když vydrží deset minut, splníš mu jakékoli přání.|300|pouta_postel",
    "Nech ho dojít v poloze, kterou nikdy nezkusil.|300|drep",
    "Doveď ho na hranu a pak ho polib a nech to být.|300|pouta_postel",
    "Nech ho dojít a pak ho drž, dokud se nezklidní.|300|lzicka",
    "Konec s péčí: Po poslední vlně ho zabal do deky a chvíli jen drž. Cíl: nevynechat to.|180|lzicka",
    "Dráždi ho pomalu tak dlouho, až ztratí trpělivost.|300|vedle_on_lezi",
    "Nech ho na hraně, dokud ti to sám nezakáže.|300|pouta_postel",
    "Řekni mu, kolikrát dneska dojde, a to číslo dodrž.|300|pouta_postel",
    "Nech ho dojít, zatímco mu držíš ruce nad hlavou.|300|kontrola_vsede",
    "Dráždi ho a pokaždé, když se pohne, začínáš od začátku.|300|pouta_postel",
    "Bez pohybu: On nesmí pohnout ani prstem. Každý pohyb vrací počítadlo na nulu. Cíl: dojít tak do konce.|300|pouta_postel",
    "Nech ho dojít a pak se ho zeptej, jestli chce ještě.|300|pouta_postel",
    "Doveď ho na hranu a nech ho rozhodnout, jestli chce pokračovat.|300|pouta_postel",
    "Dráždi ho tak dlouho, dokud nezapomene, kde je.|300|deprivace",
    "Nech ho dojít, ale až po tom, co se ti podívá do očí a řekne to nahlas.|300|kontrola_vsede",
    "Poslední svolení: On čeká na jediné slovo od tebe. Neřekni ho dřív než na konci. Cíl: načasovat to přesně.|300|pouta_postel",
    "Nech ho dojít a hned potom ho jen tiše obejmi.|180|lzicka",
  ],
});
