// Kategorie 5 – Hardcore (dávka c)
// Témata: bičík a plácání s počítáním, tah za vlasy, ruka na krku, tresty a rituály.
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 5,

  male: [
    "Deset a poděkování: Dej jí deset ran bičíkem přes zadeček, ona počítá nahlas a po každé řekne děkuju. Cíl: nevynechat ani jedno.|240|predklon",
    "Počítání naslepo: Zavaž jí oči a dávej jí rány bičíkem v nepravidelných rozestupech. Ona počítá. Cíl: deset bez ztráty počtu.|300|predklon",
    "Rána a polibek na stejné místo: Střídej ránu bičíkem a polibek přesně na to samé místo. Cíl: pět dvojic a ani jednou se netrefit vedle.|240|predklon",
    "Pět ran na stehna: Dej jí pět ran přes vnitřní stranu stehen – slabě, ale jistě. Cíl: síla pokaždé stejná, ani jedna tvrdší.|180|nohy_ramena",
    "Stupňování: Plácej ji dlaní po zadečku a postupně přidávej na síle. Cíl: nepřestat, dokud sama neřekne dost – a pak hned přestat.|240|zezadu",
    "Chyba v počítání: Nech ji počítat od jedné do dvaceti a plácni ji za každou chybu. Cíl: dojít k dvacítce s nejvýš třemi ranami.|300|predklon",
    "Deset a deset: Deset ran dlaní, pak deset bičíkem. Mezi tím minuta hlazení. Cíl: projít obojí.|300|predklon",
    "Tři rány a hlazení: Dej jí tři rány bičíkem a pak to místo dlouho hlaď dlaní. Cíl: hlazení musí trvat déle než rány.|180|na_brise",
    "O jednu navíc: Nech ji vybrat si počet ran a pak přidej ještě jednu za drzost. Cíl: dodržet její číslo do jedné – a tu poslední ohlásit.|240|predklon",
    "Rána po deseti: Miluj ji zezadu a po každých deseti přírazech ji plácni. Cíl: padesát přírazů, pět ran.|300|zezadu",
    "Rány shora vkleče: Nech ji klečet a dávej jí rány na zadeček shora. Cíl: deset ran a po každé se zeptat, jestli chce další.|240|klek_pouta",
    "Ruka nebo bičík: Ona si vybere, ale nesmí vidět, co držíš. Cíl: překvapit ji aspoň dvakrát.|300|predklon",
    "Pět lehkých na prsa: Dej jí pět ran přes prsa tak lehce, jak to jen jde. Cíl: ani jedna nesmí být silnější než ta první.|180|pouta_postel",
    "Patnáct s dotazem: Předkloň ji přes opěradlo a dej jí patnáct ran, po každé se zeptej, jestli chce další. Cíl: dojít k patnácté s jejím souhlasem.|300|predklon",
    "Otevřené oči stojí ránu: Poruč jí, ať klečí se zavřenýma očima, a plácni ji pokaždé, když je otevře. Cíl: čtyři minuty a nejvýš tři rány.|240|klek_ruce_hlava",
    "Drží se a nepouští: Nech ji držet se čela postele a plácej ji zezadu. Cíl: čtyři minuty – jakmile se pustí, přestáváš.|240|pouta_postel",
    "Odhalený krk: Vem ji za vlasy, stáhni jí hlavu dozadu a líbej ji na odhalený krk. Cíl: deset polibků a hlavu jí mezitím nepustit.|180|zezadu_vzpr",
    "Za vlasy a zezadu: Drž ji za vlasy stažené do pěsti, zatímco ji miluješ zezadu. Nikdy netahej silou. Cíl: udržet tah po celou dobu.|300|zezadu",
    "Otoč ji k sobě: Vem ji za vlasy a otoč jí hlavu k sobě, ať se ti dívá do očí. Cíl: čtyři minuty a nenechat ji uhnout.|240|zezadu",
    "Vkleče bez pohybu: Drž ji za vlasy a poruč jí, ať klečí úplně bez pohybu. Cíl: čtyři minuty a nejvýš dva pohyby.|240|oral_ona_klek",
    "Jen váha ruky: Polož jí ruku na krk a nech ji tam ležet – žádný tlak, jen váha. Cíl: kdykoli řekne stop, ruku hned sundat.|240|misionar",
    "Ruka na krku: Položíš jí dlaň na krk a ona ti nahlas řekne, jestli to chce silněji. Ty poslechneš. Cíl: zeptat se dřív, než přidáš.|300|kontrola_vsede!",
    "Přitisknutá k posteli: Drž ji za zápěstí a přitiskni ji k posteli celou svou vahou. Cíl: čtyři minuty a průběžně se ptát, jestli to není moc.|240|kontrola_vsede!",
    "Otevři pusu: Drž ji pod bradou a poruč jí, ať otevře pusu. Cíl: tři minuty a nesmí ji zavřít bez dovolení.|180|oral_ona_klek",
    "Vedená po kolenou: Vem ji jemně za vlasy a veď ji po kolenou přes postel. Cíl: dovést ji přesně tam, kam chceš, beze slova.|240|zezadu",
    "Ruka mezi lopatkami: Přitiskni ji čelem k posteli a drž ji tam rukou mezi lopatkami. Cíl: čtyři minuty a na stop ruku hned sundat.|240|na_brise",
    "Trest za pohyb: Za každý pohyb navíc dostane jednu ránu. Ona se má nehýbat. Cíl: aspoň pět trestů.|300|pouta_postel",
    "Slovo stojí ránu: Zakaž jí mluvit a za každé slovo bez dovolení jí dej ránu. Cíl: pět minut a nejvýš tři rány.|300|predklon",
    "Úkol a trest: Zadej jí konkrétní úkol a za nesplnění následuje deset ran. Cíl: úkol musí být splnitelný a ty ho musíš vymáhat přesně.|300|klek_pouta",
    "Sama si řekne: Nech ji, ať si sama nahlas řekne, kolik ran si zaslouží. Cíl: dát jí přesně tolik, ani o jednu víc.|240|klek_pouta",
    "Počítání pozpátku: Nech ji počítat nahlas pozpátku od dvaceti a za každou chybu dostane ránu. Cíl: dojít k nule.|300|predklon",
    "Odměna a trest: Za každou splněnou věc polibek, za každou nesplněnou rána. Cíl: aspoň pět a pět.|300|predklon",
    "Hádej, kolik ještě: Dej jí tři rány a nech ji hádat, kolik jich ještě přijde. Cíl: když uhodne, přestaneš – když ne, přidáš dvě.|240|predklon",
    "Až se sama nabídne: Plácej ji dlaní stejnou silou. Cíl: nepřestat, dokud sama nezvedne zadeček proti tvojí ruce.|240|na_brise",
    "Jemně přes stehna: Nech ji klečet a dej jí bičíkem přes stehna, hodně jemně. Cíl: deset ran a ani jedna silnější než ta první.|240|klek_pouta",
    "Dej jí rány přes zadeček a po každé jí tam přiložíš led.|300|predklon",
    "Led a rána: Dej jí ránu bičíkem a hned po ní přilož kostku ledu na to samé místo. Cíl: pět takových dvojic a co největší kontrast.|300|predklon",
    "Dej jí bičíkem přes záda, ale jen velmi lehce a nikdy přes páteř.|240|masaz_zada",
    "Plácej ji dlaní a zároveň ji dráždi druhou rukou.|300|na_brise",
    "Nech ji ležet a plácej ji, dokud tě sama nepoprosí o víc.|240|na_brise",
    "Poruč jí, ať ti poděkuje po každé ráně, a když zapomene, začínáte znovu.|300|predklon",
    "Dej jí pět ran a pak ji nech dojít jen rukou.|300|predklon",
    "Rituál před trestem: Musí si sama kleknout, poprosit a teprve pak začneš. Cíl: nechat ji projít celý rituál.|300|klek_pouta",
    "Nech ji, ať si sama vybere, čím ji budeš plácat.|240|predklon",
    "Dej jí rány přes zadeček přes kalhotky a teprve pak je stáhni.|300|predklon",
    "Plácni ji vždycky, když se nadechne příliš nahlas.|300|zezadu",
    "Drž ji za vlasy a poruč jí, ať se na sebe dívá do zrcadla.|240|zezadu",
    "Za vlasy k sobě: Vem ji za vlasy a přitáhni si ji na sebe při každém pohybu. Cíl: dvacet přitažení a pokaždé se zeptat, jestli je to dobré.|240|ona_nahore",
    "Vlasy a ruka: Miluj ji zezadu, jednou rukou jí drž vlasy a druhou ruku za zády. Cíl: pět minut a na stop ji hned pustit.|300|zezadu",
    "Dvě ruce, dvě věci: Jednou rukou ji drž za vlasy, druhou ji dráždi. Cíl: nepustit ani jedno.|300|zezadu",
    "Polož jí ruku na krk, když je nejblíž vrcholu.|240|misionar",
    "Drž ji za bradu a nedovol jí uhnout pohledem.|240|kontrola_vsede!",
    "Přitiskni ji ke zdi a drž ji tam jednou rukou.|240|zed",
    "Drž ji za ruce za zády a poruč jí, ať se předkloní.|240|predklon",
    "Poruč jí, ať si klekne a čeká s hlavou skloněnou.|180|klek_pouta",
    "Klid a čekání: Klečí se skloněnou hlavou tři minuty a ty nic neděláš. Cíl: nechat ji v tom.|180|klek_pouta",
    "Dej jí deset ran a po každé se jí zeptej na stupnici od jedné do desíti.|300|predklon",
    "Plácej ji, ale pokaždé jinam. Nikdy dvakrát na stejné místo.|240|na_brise",
    "Dej jí rány tak, aby po každé musela nahlas říct další.|300|predklon",
    "Nech ji vybrat mezi pěti silnými a dvaceti slabými ranami.|240|predklon",
    "Odpočítávání trestu: Řekni jí, kolik ran ji čeká, a odpočítávej je nahlas. Cíl: dojít na nulu bez zastavení.|300|predklon",
    "Dej jí rány, dokud nebude prosit, a pak ještě dvě.|300|predklon",
    "Plácni ji a hned ji vezmi zezadu, ať nemá čas se nadechnout.|300|zezadu",
    "Drž ji za vlasy a mluv na ni tvrdě, ale nikdy zle.|240|zezadu",
    "Poruč jí, ať tě požádá o každou další ránu zvlášť.|300|predklon",
    "Nech ji ležet na břiše a plácej ji jen konečky prstů.|240|na_brise",
    "Jemně a tvrdě: Střídej velmi jemné plácnutí a pořádnou ránu bez varování. Cíl: ať nikdy neví, co přijde.|300|predklon",
    "Rána a dlouhý polibek: Dávej jí rány bičíkem a mezi každými dvěma ji dlouze polib. Cíl: deset ran a deset polibků.|300|predklon",
    "Plácej ji, když sedí na tobě, a řiď tím tempo.|300|ona_nahore",
    "Pevné sevření boků: Drž ji zezadu za boky tak pevně, jak jí je příjemné. Cíl: čtyři minuty a ani jednou nepovolit sevření.|240|zezadu",
    "Zakousni se jí do ramene přesně ve chvíli, kdy je těsně před vrcholem.|240|lzicka",
    "Poruč jí, ať si sama stáhne kalhotky a předkloní se.|240|predklon",
    "Beze slov a s bičíkem: Celý trest proběhne beze slov, jen s gesty. Cíl: dorozumět se bez mluvení.|300|predklon",
    "Dej jí ránu pokaždé, když se pokusí sáhnout si.|300|pouta_postel",
    "Plácej ji, dokud nezačne počítat sama od sebe.|240|predklon",
    "Nech ji klečet s rukama za hlavou a dávej jí rány přes stehna.|240|klek_ruce_hlava",
    "Ruce na zdi: Poruč jí, ať drží obě ruce na zdi a nesundá je. Cíl: čtyři minuty – jakmile je sundá, začínáte znovu.|240|zed",
    "Dej jí rány a pak ji nech ležet a dívat se na tebe.|240|predklon",
    "Doveď ji za vlasy: Vem ji jemně za vlasy a doveď ji ke kraji postele. Cíl: cestou neříct ani slovo a posadit ji přesně tam, kam chceš.|180|kraj_postele",
    "Konec rituálu: Po posledním trestu ji obejmi a řekni jí, jak dobře to zvládla. Cíl: nikdy nevynechat.|180|pouta_postel",
    "Poslední rána: Dej jí poslední ránu bičíkem a hned poté ji dlouze polib. Cíl: polibek musí trvat aspoň půl minuty.|180|predklon",
    "Jemný konec: Plácni ji naposledy hodně jemně a pak ji jen hlaď. Cíl: dvě minuty hlazení a ani jedna další rána.|120|na_brise",
    "Na konec jí namasíruj místa, kam dopadly rány.|180|masaz_zada",
  ],

  female: [
    "Deset s poděkováním: Dej mu deset ran bičíkem přes zadek, on počítá nahlas a po každé řekne děkuju. Cíl: nevynechat ani jedno.|240|predklon!",
    "Počítání naslepo: Zavaž mu oči a dávej mu rány bičíkem v nepravidelných rozestupech. On počítá. Cíl: deset bez ztráty počtu.|300|predklon!",
    "Rána a hned polibek: Po každé ráně bičíkem to samé místo hned polib. Cíl: pět dvojic a ani jednou se netrefit vedle.|240|predklon!",
    "Pět na jeho stehna: Dej mu pět ran přes vnitřní stranu stehen – slabě, ale jistě. Cíl: síla pokaždé stejná, ani jedna tvrdší.|180|oral_on_vleze",
    "Přidávej na síle: Plácej ho dlaní po zadku a postupně přidávej na síle. Cíl: nepřestat, dokud sám neřekne dost – a pak hned přestat.|240|zezadu!",
    "Chyba stojí ránu: Nech ho počítat od jedné do dvaceti a plácni ho za každou chybu. Cíl: dojít k dvacítce s nejvýš třemi ranami.|300|predklon!",
    "Dlaň a bičík: Nejdřív deset ran dlaní, minuta hlazení a pak deset bičíkem. Cíl: projít obojí.|300|predklon!",
    "Tři rány a dlouhé hlazení: Dej mu tři rány bičíkem a pak to místo dlouho hlaď dlaní. Cíl: hlazení musí trvat déle než rány.|180|na_brise!",
    "Jedna navíc za drzost: Nech ho vybrat si počet ran a pak přidej ještě jednu. Cíl: dodržet jeho číslo do jedné – a tu poslední ohlásit.|240|predklon!",
    "Rána po každých deseti: Jezdi na něm a po každých deseti pohybech ho plácni. Cíl: padesát pohybů, pět ran.|300|ona_nahore",
    "Shora vkleče: Nech ho klečet a dávej mu rány na zadek shora. Cíl: deset ran a po každé se zeptat, jestli chce další.|240|klek_pouta!",
    "Ruka nebo bičík: On si vybere, ale nesmí vidět, co držíš. Cíl: překvapit ho aspoň dvakrát.|300|predklon!",
    "Pět lehkých na hrudník: Dej mu pět ran přes hrudník tak lehce, jak to jen jde. Cíl: ani jedna nesmí být silnější než ta první.|180|pouta_postel!",
    "Patnáct s otázkou: Předkloň ho přes opěradlo a dej mu patnáct ran, po každé se zeptej, jestli chce další. Cíl: dojít k patnácté s jeho souhlasem.|300|predklon!",
    "Oči zavřené, jinak rána: Poruč mu, ať klečí se zavřenýma očima, a plácni ho pokaždé, když je otevře. Cíl: čtyři minuty a nejvýš tři rány.|240|klek_ruce_hlava!",
    "Drží se a nepouští on: Nech ho držet se čela postele a plácej ho zezadu. Cíl: čtyři minuty – jakmile se pustí, přestáváš.|240|pouta_postel!",
    "Zakloněná hlava: Vem ho za vlasy, stáhni mu hlavu dozadu a líbej ho na odhalený krk. Cíl: deset polibků a hlavu mu nepustit.|180|zezadu_vzpr!",
    "Za vlasy a zezadu: Drž ho za vlasy stažené do pěsti, zatímco je v tobě zezadu. Nikdy netahej silou. Cíl: udržet tah po celou dobu.|300|zezadu!",
    "Otoč ho k sobě: Vem ho za vlasy a otoč mu hlavu k sobě, ať se ti dívá do očí. Cíl: čtyři minuty a nenechat ho uhnout.|240|zezadu!",
    "Klečí bez hnutí: Drž ho za vlasy a poruč mu, ať klečí úplně bez pohybu. Cíl: čtyři minuty a nejvýš dva pohyby.|240|oral_ona_klek",
    "Jen váha dlaně: Polož mu ruku na krk a nech ji tam ležet – žádný tlak, jen váha. Cíl: kdykoli řekne stop, ruku hned sundat.|240|kontrola_vsede",
    "Ruka na krku: Položíš mu dlaň na krk a on ti nahlas řekne, jestli to chce silněji. Ty poslechneš. Cíl: zeptat se dřív, než přidáš.|300|kontrola_vsede",
    "Přitisknutý k posteli: Drž mu zápěstí a přitiskni ho k posteli celou svou vahou. Cíl: čtyři minuty a průběžně se ptát, jestli to není moc.|240|kontrola_vsede",
    "Otevři pusu jemu: Drž ho pod bradou a poruč mu, ať otevře pusu. Cíl: tři minuty a nesmí ji zavřít bez dovolení.|180|oral_ona_klek",
    "Vedený po kolenou: Vem ho jemně za vlasy a veď ho po kolenou přes postel. Cíl: dovést ho přesně tam, kam chceš, beze slova.|240|zezadu!",
    "Mezi jeho lopatkami: Přitiskni ho čelem k posteli a drž ho tam rukou mezi lopatkami. Cíl: čtyři minuty a na stop ruku hned sundat.|240|na_brise!",
    "Trest za pohyb: Za každý pohyb navíc dostane jednu ránu. On se má nehýbat. Cíl: aspoň pět trestů.|300|pouta_postel!",
    "Jeho slovo stojí ránu: Zakaž mu mluvit a za každé slovo bez dovolení mu dej ránu. Cíl: pět minut a nejvýš tři rány.|300|predklon!",
    "Úkol a jeho trest: Zadej mu konkrétní úkol a za nesplnění následuje deset ran. Cíl: úkol musí být splnitelný a ty ho musíš vymáhat přesně.|300|klek_pouta!",
    "Řekne si sám: Nech ho, ať si sám nahlas řekne, kolik ran si zaslouží. Cíl: dát mu přesně tolik, ani o jednu víc.|240|klek_pouta!",
    "Pozpátku od dvaceti: Nech ho počítat nahlas pozpátku od dvaceti a za každou chybu dostane ránu. Cíl: dojít k nule.|300|predklon!",
    "Polibek nebo rána: Co splní, to je polibek, co nesplní, to je rána. Cíl: aspoň pět a pět.|300|predklon!",
    "Dej mu tři rány a pak ho nech hádat, kolik jich ještě bude.|240|predklon!",
    "Plácej ho tak dlouho, dokud nezvedne zadek sám.|240|na_brise!",
    "Nech ho klečet a dej mu bičíkem přes stehna. Jemně.|240|klek_pouta!",
    "Dej mu rány přes zadek a po každé mu tam přiložíš led.|300|predklon!",
    "Rána a mráz: Po každé ráně přilož na to místo kostku ledu. Pětkrát. Cíl: co největší kontrast.|300|predklon!",
    "Dej mu bičíkem přes záda, ale jen velmi lehce a nikdy přes páteř.|240|masaz_zada!",
    "Plácej ho dlaní a zároveň ho dráždi druhou rukou.|300|na_brise!",
    "Nech ho ležet a plácej ho, dokud tě sám nepoprosí o víc.|240|na_brise!",
    "Poruč mu, ať ti poděkuje po každé ráně, a když zapomene, začínáte znovu.|300|predklon!",
    "Dej mu pět ran a pak ho nech dojít jen rukou.|300|predklon!",
    "Rituál před trestem: Musí si sám kleknout, poprosit a teprve pak začneš. Cíl: nechat ho projít celý rituál.|300|klek_pouta!",
    "Nech ho, ať si sám vybere, čím ho budeš plácat.|240|predklon!",
    "Dej mu rány přes zadek přes trenýrky a teprve pak mu je stáhni.|300|predklon!",
    "Plácni ho vždycky, když se nadechne příliš nahlas.|300|ona_nahore",
    "Drž ho za vlasy a poruč mu, ať se na sebe dívá do zrcadla.|240|zezadu!",
    "Za vlasy k sobě jeho: Vem ho za vlasy a přitáhni si ho k sobě při každém pohybu. Cíl: dvacet přitažení a pokaždé se zeptat, jestli je to dobré.|240|kontrola_vsede",
    "Vlasy a jeho ruka: Drž ho jednou rukou za vlasy a druhou mu drž ruku za zády. Cíl: pět minut a na stop ho hned pustit.|300|zezadu!",
    "Dvě ruce, dvě věci: Jednou rukou ho drž za vlasy, druhou ho dráždi. Cíl: nepustit ani jedno.|300|zezadu!",
    "Ruka na krku v pravou chvíli: Polož mu ruku na krk přesně ve chvíli, kdy je nejblíž konci. Cíl: trefit se aspoň dvakrát a na stop ruku sundat.|240|kontrola_vsede",
    "Drž ho za bradu a nedovol mu uhnout pohledem.|240|kontrola_vsede",
    "Přitiskni ho ke zdi a drž ho tam jednou rukou.|240|zed",
    "Drž mu ruce za zády a poruč mu, ať se předkloní.|240|predklon!",
    "Poruč mu, ať si klekne a čeká se skloněnou hlavou.|180|klek_pouta!",
    "Klid a čekání: Klečí se skloněnou hlavou tři minuty a ty nic neděláš. Cíl: nechat ho v tom.|180|klek_pouta!",
    "Dej mu deset ran a po každé se ho zeptej na stupnici od jedné do desíti.|300|predklon!",
    "Plácej ho, ale pokaždé jinam. Nikdy dvakrát na stejné místo.|240|na_brise!",
    "Dej mu rány tak, aby po každé musel nahlas říct další.|300|predklon!",
    "Nech ho vybrat mezi pěti silnými a dvaceti slabými ranami.|240|predklon!",
    "Odpočítávání trestu: Řekni mu, kolik ran ho čeká, a odpočítávej je nahlas. Cíl: dojít na nulu bez zastavení.|300|predklon!",
    "Dej mu rány, dokud nebude prosit, a pak ještě dvě.|300|predklon!",
    "Plácni ho a hned si na něj sedni, ať nemá čas se nadechnout.|300|ona_nahore",
    "Drž ho za vlasy a mluv na něj tvrdě, ale nikdy zle.|240|zezadu!",
    "Poruč mu, ať tě požádá o každou další ránu zvlášť.|300|predklon",
    "Nech ho ležet na břiše a plácej ho jen konečky prstů.|240|na_brise!",
    "Bez varování: Jednou plácneš skoro neznatelně, podruhé naplno, a nikdy dopředu neřekneš které. Cíl: ať to nikdy neuhodne.|300|predklon!",
    "Rána a polibek pro něj: Dávej mu rány bičíkem a mezi každými dvěma ho dlouze polib. Cíl: deset ran a deset polibků.|300|predklon!",
    "Plácej ho, když je v tobě zezadu, a řiď tím tempo.|300|zezadu!",
    "Pevně za boky: Drž ho za boky tak pevně, jak je mu příjemné, a jezdi na něm. Cíl: čtyři minuty a ani jednou nepovolit sevření.|240|ona_nahore",
    "Zakousni se mu do ramene přesně ve chvíli, kdy je těsně před koncem.|240|lzicka",
    "Poruč mu, ať si sám stáhne trenýrky a předkloní se.|240|predklon!",
    "Jen gesta: Celý trest zvládněte bez jediného slova, domluvíte se rukama. Cíl: dorozumět se bez mluvení.|300|predklon!",
    "Dej mu ránu pokaždé, když se pokusí sáhnout si.|300|pouta_postel!",
    "Plácej ho, dokud nezačne počítat sám od sebe.|240|predklon!",
    "Nech ho klečet s rukama za hlavou a dávej mu rány přes stehna.|240|klek_ruce_hlava!",
    "Jeho ruce na zdi: Poruč mu, ať drží obě ruce na zdi a nesundá je. Cíl: čtyři minuty – jakmile je sundá, začínáte znovu.|240|zed",
    "Dej mu rány a pak ho nech ležet a dívat se na tebe.|240|predklon",
    "Doveď ho za vlasy: Vem ho jemně za vlasy a doveď ho ke kraji postele. Cíl: cestou neříct ani slovo a posadit ho přesně tam, kam chceš.|180|kraj_postele!",
    "Konec rituálu: Po posledním trestu ho obejmi a řekni mu, jak dobře to zvládl. Cíl: nikdy nevynechat.|180|pouta_postel!",
    "Poslední rána pro něj: Dej mu poslední ránu bičíkem a hned poté ho dlouze polib. Cíl: polibek musí trvat aspoň půl minuty.|180|predklon!",
    "Jemná tečka: Plácni ho naposledy hodně jemně a pak ho jen hlaď. Cíl: dvě minuty hlazení a ani jedna další rána.|120|na_brise!",
    "Na konec mu namasíruj místa, kam dopadly rány.|180|masaz_zada!",
  ],
});
