// Kategorie 5 – Hardcore (dávka e)
// Témata: trojkombinace stimulací, postupná anální hra, prostata, dva vibrátory, led.
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 5,

  male: [
    "Trojkombinace: Vibrátor v zadečku, dva prsty uvnitř a jazyk na klitorisu. Všechno naráz, dokud se neudělá. Cíl: nepřerušit ani jedno.|300|oral_klek",
    "Trojitá kombinace: Vsuň jí s lubrikantem vibrátor do zadečku, prsty ji prsti a zároveň ji lízej. Cíl: nepřestat, dokud nedojde, a hloubku určuje jen ona.|300|oral_klek",
    "Tři místa naráz: Jeden vibrátor jí s lubrikantem vsuň do zadečku, druhý drž na klitorisu a dráždi jí bradavky. Cíl: hloubku určuje jen ona.|300|pouta_postel",
    "Tři body naráz: Prst v zadečku, prsty vpředu a rty na klitorisu. Nikdy neuber ani jedno. Cíl: dovést ji tam všemi třemi.|300|oral_klek",
    "Palec a jazyk: Namaž jí zadeček lubrikantem, vsuň palec a zároveň ji lízej. Cíl: pět minut a hloubku palce určuje jen ona.|300|oral_klek",
    "Prsty, palec, jazyk: Prsti ji vpředu, palec měj s lubrikantem vzadu a jazykem krouži na klitorisu. Cíl: pět minut a všechno ve stejném rytmu.|300|oral_klek",
    "Dva vibrátory a jazyk: Jeden vibrátor jí vsuň dopředu, druhý přilož na klitoris a lízej jí bradavky. Cíl: pět minut a ani jeden neodložit.|300|vedle_ona_lezi",
    "Všechno najednou: Miluj se s ní, drž jí vibrátor na klitorisu a namazaný prst měj v zadečku. Cíl: pět minut a tempo určuje ona.|300|misionar",
    "Plná trojka při sexu: Jsi v ní, vibrátor na klitorisu a namazaný prst v zadečku. Cíl: udržet všechno tři minuty.|300|misionar",
    "Obě ruce dopředu: Miluj ji zezadu a zároveň jí oběma rukama sahej dopředu – jednou na klitoris, druhou na prsa. Cíl: pět minut bez pauzy.|300|zezadu",
    "Dvojitý průnik: Vibrátor v zadečku a ty v ní, s hodně lubrikantu. Hloubku řídí ona. Cíl: jít tak pomalu, jak řekne.|300|lzicka",
    "Vibrátor vzadu na boku: Vsuň jí s lubrikantem vibrátor do zadečku a mrdej ji na boku. Cíl: pět minut a stupeň nezvyšovat bez jejího slova.|300|lzicka",
    "Ty vzadu, vibrátor vpředu: Vsuň jí vibrátor dopředu a sám pomalu vnikej do zadečku. Cíl: hodně lubrikantu a začít až na její výslovné ano.|300|lzicka",
    "Anál pomalu: Hodně lubrikantu, začni jen špičkou a čekej, až se uvolní. Hloubku řídí ona. Cíl: nikam nespěchat.|300|zezadu",
    "Zatím jen kolem: Namaž jí zadeček lubrikantem a krouži prstem kolem. Cíl: dovnitř nejít ani jednou, dokud si o to sama neřekne.|300|na_brise",
    "Prst bez pohybu: Vsuň jí prst s lubrikantem do zadečku a nech ho tam úplně nehybně. Cíl: pět minut a nepohnout jím, dokud si neřekne.|300|na_brise",
    "Prst po prstu: Vsuň jí s lubrikantem nejdřív jeden prst a teprve po minutě druhý. Cíl: přidat další až tehdy, když si o něj sama řekne.|300|na_brise",
    "Jen kousek: Namaž kolík lubrikantem a vsuň ho jen kousek. Cíl: hlouběji jít vždycky až na její slovo.|300|na_brise",
    "Krok za krokem: Nanes hodně lubrikantu, vsuň nejdřív prst, pak menší kolík, pak víc. Cíl: postoupit dál vždycky až na její slovo, nikdy dřív.|300|na_brise",
    "Vzadu vibrace, vpředu ruka: Vsuň jí s lubrikantem vibrátor do zadečku a rukou ji dráždi vpředu. Cíl: obojí ve stejném rytmu a stupeň určuje jen ona.|300|lzicka",
    "Na břiše a pomalu: Nech ji ležet na břiše a s velkým množstvím lubrikantu ji pomalu prsti v zadečku. Cíl: tempo řídí výhradně ona.|300|na_brise",
    "Anál v lžičce: Na boku, hodně lubrikantu a ona si sama drží vibrátor vpředu. Cíl: nechat ji řídit tempo.|300|lzicka",
    "Hloubku určuje ona: Nech ji klečet a s hodně lubrikantem ji pomalu ber zezadu. Cíl: pět minut a nepřidat ani centimetr bez jejího slova.|300|zezadu",
    "Řídí si to sama: Nech ji sednout si na tebe a celý anál si řídit od začátku do konce. Cíl: hodně lubrikantu a ty se nehýbeš vůbec.|300|ona_nahore_zady",
    "Zepředu i zezadu na boku: Nech ji ležet na boku a dráždi ji zepředu i zezadu naráz. Cíl: pět minut a obě ruce ve stejném tempu.|300|dvojita_bok",
    "Vibrace a jazyk až do konce: Vsuň jí s lubrikantem vibrátor do zadečku a lízej jí kundičku. Cíl: nepřestat, dokud nedojde, a stupeň vibrací určuje jen ona.|300|oral_klek",
    "Vibrátor a jazyk: Vibrátor v zadečku, tvůj jazyk na klitorisu a nic jiného. Cíl: dovést ji tam tímhle.|300|oral_klek",
    "Vpředu si to řídí sama: Nech ji, ať si vibrátor vpředu drží sama, a ty se staráš o všechno ostatní. Cíl: pět minut a na vibrátor nesáhnout.|300|na_brise",
    "Jeden dovnitř, druhý ven: Vezmi dva vibrátory – jeden jí vsuň dovnitř, druhý přilož na klitoris. Cíl: pět minut a stupeň zvyšovat jen na její slovo.|300|pouta_postel",
    "Dva vibrátory: Jeden na bradavkách, druhý mezi nohama. Střídej, který má vyšší stupeň. Cíl: nikdy oba naplno.|300|pouta_postel",
    "Dokud neřekne dost: Přilož jí oba vibrátory naráz a nepolevuj. Cíl: nepřestat, dokud sama neřekne dost.|300|pouta_postel",
    "Dva naráz na spoutané: Spoutej ji a použij oba vibrátory zároveň – jeden dovnitř, druhý na klitoris. Cíl: pět minut a na stop ji hned odemknout.|300|pouta_postel",
    "Jeden v ní, druhý putuje: Jeden vibrátor nech v ní a druhým jí přejížděj po celém těle. Cíl: deset různých míst a ani jedno dvakrát.|300|pouta_postel",
    "Druhý si řídí ona: Přilož jí vibrátor na klitoris a druhý jí dej do ruky, ať si vybere kam. Cíl: pět minut a do její volby nemluvit.|300|vedle_ona_lezi",
    "Střídavá dvojka: Dva vibrátory, ale vždycky běží jen jeden. Střídej je po deseti vteřinách. Cíl: ať nikdy neví který.|300|deprivace",
    "Led a vibrace poslepu: Spoutej ji, zavaž jí oči a použij led a vibrátor zároveň. Cíl: pět minut a ať nikdy neuhodne, co kde bude.|300|pouta_postel",
    "Led a pouta: Je spoutaná a ty jí střídáš kostku ledu a horký dech po celém těle. Cíl: deset střídání.|300|pouta_postel",
    "Led po zádech, vibrace vpředu: Přejížděj jí kostkou ledu po zádech, zatímco si vepředu drží vibrátor. Cíl: pět cest ledem a ani jednou ho nesundat.|300|pouta_postel",
    "Led mezi kozy: Vlož jí kostku ledu mezi kozy a nech ji, ať ji tam udrží. Cíl: nepřestat ji dráždit, dokud led neroztaje.|300|pouta_postel",
    "Led a vibrace po deseti: Střídej kostku ledu a vibrátor na klitorisu přesně po deseti vteřinách. Cíl: patnáct střídání a čas nesplést.|300|vedle_ona_lezi",
    "Led po stehnech: Spoutej ji a přejížděj jí kostkou ledu po vnitřní straně stehen. Cíl: deset cest a ani jednou nesjet výš.|300|pouta_postel",
    "S kroužkem co nejdéle: Nasaď si erekční kroužek a mrdej ji tak dlouho, jak to jen půjde. Cíl: vydržet aspoň pět minut.|300|misionar",
    "Kroužek a výdrž: S kroužkem musíš vydržet, dokud nedojde ona. Cíl: nedojít dřív.|300|ona_nahore",
    "S kroužkem ji vezmi zezadu a zároveň jí drž vibrátor vpředu.|300|zezadu",
    "S kroužkem se nech od ní osedlat a nehýbej se vůbec.|300|ona_nahore",
    "Konec určuje ona: Nasaď si erekční kroužek a nech ji rozhodnout, kdy skončíte. Cíl: nepožádat o konec ani jednou.|300|ona_nahore",
    "Spoutej ji, nasaď si kroužek a nespěchej vůbec nikam.|300|pouta_postel",
    "Vibrátor vzadu v misionáři: Vsuň jí s lubrikantem vibrátor do zadečku a mrdej ji v misionáři. Cíl: pět minut a stupeň nezvyšovat bez jejího slova.|300|misionar",
    "Dvojí plnost: Vibrátor vzadu a ty vpředu, oba velmi pomalu. Cíl: nikdy nezrychlit.|300|misionar",
    "Vezmi ji zezadu a zároveň jí drž vibrátor na klitorisu.|300|zezadu",
    "Nech ji sedět na tobě a přitom jí dráždi zadeček prstem.|300|ona_nahore",
    "Ať si sedne na tebe zády a ty jí sahej dopředu i dozadu.|300|ona_nahore_zady",
    "Miluj se s ní a zároveň jí drž ruku na krku a druhou na klitorisu.|300|misionar",
    "Vezmi ji zezadu, drž ji za vlasy a zároveň jí sahej dopředu.|300|zezadu",
    "Tři ruce, dvě těla: Jedna ruka na vlasech, druhá vpředu a ty v ní zezadu. Cíl: nepustit ani jedno.|300|zezadu",
    "Nech ji ležet na břiše, vsuň jí vibrátor a plácej ji dlaní.|300|na_brise",
    "Spoutej ji, vsuň jí vibrátor a nech ji dojít bez jediného doteku navíc.|300|pouta_postel",
    "Přilož jí vibrátor a zároveň jí lízej bradavky a prsti ji.|300|vedle_ona_lezi",
    "Vsuň jí dva prsty, palcem dráždi klitoris a druhou rukou zezadu.|300|vedle_ona_lezi",
    "Všechno najednou: Prsty vpředu, palec vzadu, jazyk na klitorisu a druhá ruka na prsou. Cíl: udržet všechny čtyři.|300|oral_klek",
    "Prsti jí kundičku zepředu a zezadu zároveň, každou rukou jinak.|300|vedle_ona_lezi",
    "Lízej ji a zároveň jí strkej prst do zadečku a druhý dopředu.|300|oral_klek",
    "Nech ji klečet a dráždi ji jazykem zezadu, zatímco ji prstíš vpředu.|300|zezadu",
    "Jazyk vepředu, prst vzadu: Nech ji sednout si ti na obličej a namazaným prstem ji prsti zezadu. Cíl: pět minut a hloubku určuje jen ona.|300|oral_ona_nad_nim",
    "Nech ji ležet na boku a dráždi ji zepředu, zezadu a líbej ji na krk.|300|dvojita_bok",
    "Vsuň jí vibrátor zezadu a nech ji, ať si vpředu pomáhá sama.|300|na_brise",
    "Ona řídí všechno: Ona říká, kam máš sáhnout, kdy lízat a kdy mrdat, a ty jen plníš. Cíl: pět minut a neudělat nic sám od sebe.|300|na_brise",
    "Nech ji vybrat, kolik pomůcek dneska použiješ. Maximálně tři.|300|pouta_postel",
    "Vsuň jí s hodně lubrikantu kolík a pak ji mrdej úplně normálně. Hloubku kolíku určuje jen ona.|300|misionar",
    "S kolíkem v zadečku a hodně lubrikantu ji mrdej zezadu hodně pomalu. Tempo určuje jen ona.|300|zezadu",
    "Nasaď jí s hodně lubrikantu kolík, ať ho nosí celou dobu této karty, a dělej jinak všechno obvyklé. Kdy ho vyndá, určuje ona.|300|misionar",
    "Kolík a čekání: Vsuň jí s hodně lubrikantu kolík a pak se jí pět minut nedotkni. Cíl: vydržet pět minut a hloubku určuje jen ona.|300|pouta_postel",
    "Vsuň jí s hodně lubrikantu kolík a zároveň jí přilož vibrátor na klitoris. Hloubku kolíku určuje jen ona.|300|pouta_postel",
    "Prsti jí kundičku zezadu jedním prstem, zatímco jí ústy pracuješ vpředu.|300|oral_klek",
    "Nech ji ležet s polštářem pod boky a dráždi ji všemi třemi způsoby.|300|misionar_polstar",
    "Spoutej ji a použij prst, vibrátor i jazyk za sebou.|300|pouta_postel",
    "Postupná stavba: Nejdřív jen jazyk, pak přidej prst, pak vibrátor. Nikdy nic neuber. Cíl: skončit se vším naráz.|300|oral_klek",
    "Doveď ji na hranu trojkombinací a pak úplně přestaň.|300|oral_klek",
    "Trojkombinací ji doveď ke dvěma orgasmům za sebou.|300|oral_klek",
    "Jedna po druhé: Dráždi ji postupně všemi pomůckami, co doma máte, vždycky jednou minutu. Cíl: nevynechat ani jednu.|300|pouta_postel",
    "Vynechá jednu věc: Nech ji rozhodnout, jestli dneska vynecháte pouta, vibrátor, nebo lízání. Cíl: zbylé dvě věci dotáhnout do konce.|300|pouta_postel",
    "Bez pomůcek: Stejná trojkombinace, ale jen rukama a ústy. Žádné hračky. Cíl: dokázat, že to jde.|300|oral_klek",
    "Dráždi ji zezadu jazykem, zatímco jí vpředu drží vibrátor ona sama.|300|na_brise",
    "Vsuň jí vibrátor a při tom ji spoutanou lízej.|300|pouta_postel",
    "Všechno najednou: Nech ji ležet a zároveň ji lízej, prsti a dráždi vibrátorem. Cíl: pět minut a nepřerušit ani jedno.|300|vedle_ona_lezi",
    "Použij led, vibrátor a jazyk během jedné minuty.|300|oral_klek",
    "Nech ji dojít trojkombinací a pak jí všechno pomalu vyndej.|300|oral_klek",
    "Konec a péče: Přestaň ji dráždit, všechno opatrně vyndej, umyj si ruce, přines jí vodu a lehni si k ní. Cíl: nevynechat žádný krok.|180|lzicka",
    "Klidný konec: Obejmi ji zezadu na lžičku a nech ji vydechnout. Cíl: dvě minuty ticha a ani jeden z vás nic nechce.|120|lzicka",
  ],

  female: [
    "Trojkombinace: Vibrátor v zadku, ruka na kmeni a ústa na špičce. Všechno naráz, dokud se neudělá. Cíl: nepřerušit ani jedno.|300|oral_on_vleze",
    "Trojitá kombinace pro tebe: Nabídni mu anál s hodně lubrikantu, sama si drž vibrátor vpředu a nech se líbat na krk. Cíl: hloubku určuješ jen ty.|300|lzicka",
    "Tři místa u tebe: Jeden vibrátor si drž na klitorisu, druhý v kundičce a nabídni mu anál s hodně lubrikantu. Cíl: tempo určuješ jen ty.|300|zezadu!",
    "Tři body naráz: Prst v zadku, ruka na kmeni a rty na špičce. Nikdy neuber ani jedno. Cíl: dovést ho tam všemi třemi.|300|oral_on_vleze",
    "Anál a jeho ústa: Nech si namazat zadeček lubrikantem, nabídni mu anál a pak ať tě dolízá. Cíl: pět minut a hloubku určuješ jen ty.|300|na_brise!",
    "Anál, ruka, jazyk: Nabídni mu anál s hodně lubrikantu, sama si hlaď klitoris a nech si líbat záda. Cíl: hloubku určuješ jen ty.|300|na_brise!",
    "Anál a prst: Nabídni mu anál s hodně lubrikantu a zepředu si vsuň dva prsty. Cíl: najít, kde se to potká, a hloubku určuješ jen ty.|300|zezadu!",
    "Anál a jeho dlaň: Nabídni mu anál s hodně lubrikantu a nech si zepředu hladit klitoris dlaní. Cíl: pět minut a tempo řídíš jen ty.|300|lzicka",
    "Jen z análu: Nabídni mu anál s hodně lubrikantu a nesmí se tě dotknout nikde jinde. Cíl: hloubku určuješ jen ty a nepřestat, dokud nedojdeš.|300|zezadu!",
    "Kroužek a pět kol: Nasaď mu erekční kroužek a pětkrát ho kuř až na hranu a zastav se. Cíl: dojít smí až na pátém kole.|300|oral_on_vleze",
    "Kroužek a čekání: Kroužek nasazený, ty ho honíš a on se nesmí udělat, dokud mu to nedovolíš. Cíl: tři minuty na hraně.|300|oral_on_vleze",
    "Nahoře a prst na hrázi: Sedni si na něj a zároveň mu prstem dráždi hráz. Cíl: pět minut a obojí ve stejném tempu.|300|ona_nahore",
    "Dvojitý průnik: Vibrátor v jeho zadku, zatímco na něm sedíš. Hloubku řídí on. Cíl: jít tak pomalu, jak řekne.|300|ona_nahore",
    "Po orgasmu nepřestávej: Na lžičce mu hoň dál i potom, co se udělá. Cíl: nepřestat, dokud neřekne dost nebo stop slovo.|300|lzicka",
    "Anál pomalu: Hodně lubrikantu, začni jen špičkou prstu a čekej, až se uvolní. Hloubku řídí on. Cíl: nikam nespěchat.|300|na_brise!",
    "Deset kol na hranu: Kuř mu a pokaždé, když je těsně před koncem, přestaň. Cíl: deset kol a teprve pak ho nechat dojít.|300|oral_on_vleze",
    "Nehybná ruka: Vezmi ho do ruky a nehýbej se, dokud se sám nezačne pohybovat. Cíl: pět minut a udělat se smí, jen když řekneš ano.|300|vedle_on_lezi",
    "Postupně po prstech: Vsuň mu s lubrikantem nejdřív jeden prst a teprve po minutě druhý. Cíl: přidat další až tehdy, když si o něj sám řekne.|300|na_brise!",
    "Jen kousek a dost: Vezmi ho do pusy jen na kousek a po deseti vteřinách přestaň. Cíl: deset takových kol, než ho pustíš dál.|300|oral_on_vleze",
    "Krok za krokem pro něj: Nanes hodně lubrikantu, vsuň nejdřív prst, pak menší kolík, pak víc. Cíl: postoupit dál vždycky až na jeho slovo, nikdy dřív.|300|na_brise!",
    "Vibrace a dlaň na hraně: Drž mu vibrátor na hrázi a dlaní ho honi, ale zastav se vždycky těsně před koncem. Cíl: pět zastavení.|300|vedle_on_lezi",
    "Na břiše a pomalu jemu: Nech ho ležet na břiše a s velkým množstvím lubrikantu ho pomalu prsti. Cíl: tempo řídí výhradně on.|300|na_brise!",
    "Anál v lžičce: Na boku, hodně lubrikantu a on si sám drží ruku vpředu. Cíl: nechat ho řídit tempo.|300|lzicka",
    "Hloubku určuje on: Nech ho klečet a s hodně lubrikantem mu pomalu vsouvej kolík. Cíl: pět minut a nepřidat ani centimetr bez jeho slova.|300|zezadu!",
    "Řídí si to sám: Nech ho nasadit se na tebe a celé tempo přírazů si řídit sám. Cíl: pět minut, při kterých se ty vůbec nehýbeš.|300|kontrola_vsede",
    "Z obou stran na boku: Nech ho ležet na boku a dráždi ho zepředu i zezadu naráz. Cíl: pět minut a obě ruce ve stejném tempu.|300|dvojita_bok!",
    "Dva za sebou: Kuř mu až do konce a pak pokračuj, dokud se neudělá podruhé. Cíl: dva orgasmy s pauzou nejvýš deset vteřin.|300|oral_on_vleze",
    "Vibrátor a jazyk: Vibrátor v zadku, tvoje ústa nahoře a nic jiného. Cíl: dovést ho tam tímhle.|300|oral_on_vleze",
    "Drží si to sám: Nech ho, ať si vibrátor drží sám, a ty se staráš o všechno ostatní. Cíl: pět minut a na vibrátor nesáhnout.|300|na_brise!",
    "Dva na dvě místa: Vezmi dva vibrátory – jeden přilož na koule, druhý na hráz. Cíl: pět minut a stupeň zvyšovat jen na jeho slovo.|300|pouta_postel!",
    "Dvojice hraček: Jednu přilož na bradavky, druhou mezi nohy a pořád přehazuj, která jede silněji. Cíl: nikdy obě naplno.|300|pouta_postel!",
    "Dokud neřekne dost on: Přilož mu oba vibrátory naráz a nepolevuj. Cíl: nepřestat, dokud sám neřekne dost.|300|pouta_postel!",
    "Dva na spoutaného: Spoutej ho a použij oba vibrátory zároveň – jeden na koule, druhý na hráz. Cíl: pět minut a na stop ho hned odemknout.|300|pouta_postel!",
    "Jeden v něm, druhý putuje: Jeden vibrátor nech v něm a druhým mu přejížděj po celém těle. Cíl: deset různých míst a ani jedno dvakrát.|300|pouta_postel!",
    "Přilož mu vibrátor na hráz a druhý mu dej do ruky, ať si sám vybere kam.|300|vedle_on_lezi",
    "Jen jedna běží: Dráždi ho dvěma vibrátory, ale zapnutý je vždycky jen jeden a po deseti vteřinách je prohodíš. Cíl: deset výměn a ať nepozná který.|300|deprivace!",
    "Spoutej ho, zavaž mu oči a použij led a vibrátor zároveň.|300|pouta_postel!",
    "Led a pouta: Je spoutaný a ty mu střídáš kostku ledu a horký dech po celém těle. Cíl: deset střídání.|300|pouta_postel!",
    "Přejeď mu ledem po zádech, zatímco mu drží vibrátor vepředu.|300|pouta_postel!",
    "Polož mu kostku ledu na hrudník a nech ho, ať ji tam udrží.|300|pouta_postel!",
    "Led a ústa po deseti: Střídej kostku ledu a ústa přesně po deseti vteřinách. Cíl: patnáct střídání a čas ani jednou nesplést.|300|oral_on_vleze",
    "Spoutej ho a přejížděj mu ledem po vnitřní straně stehen.|300|pouta_postel!",
    "Nasaď mu erekční kroužek a sedni si na něj tak dlouho, jak to jen půjde.|300|ona_nahore",
    "Kroužek a výdrž: S kroužkem musí vydržet, dokud nedojdeš ty. Cíl: ať nedojde dřív.|300|ona_nahore",
    "S kroužkem ho nech kleknout si za tebe a zároveň si drž vibrátor vpředu.|300|zezadu",
    "S kroužkem si na něj sedni a nenech ho hnout se ani jednou.|300|kontrola_vsede",
    "Nasaď mu kroužek a rozhodni sama, kdy skončíte.|300|ona_nahore",
    "Spoutej ho, nasaď mu kroužek a nespěchej vůbec nikam.|300|pouta_postel!",
    "Nahoře a na povel: Jezdi na něm a on se nesmí udělat dřív, než mu to dovolíš. Cíl: pět minut a povolit mu to až na konci.|300|ona_nahore",
    "Dvojí plnost: Vibrátor vzadu a ty na něm, oba velmi pomalu. Cíl: nikdy nezrychlit.|300|ona_nahore",
    "Nech ho klečet za tebou a zároveň mu sahej dozadu mezi nohy.|300|zezadu!",
    "Sedni si na něj a přitom mu dráždi hráz prstem.|300|ona_nahore",
    "Zády a ruka dozadu: Sedni si na něj zády a namazaným prstem mu sahej dozadu. Cíl: pět minut a hloubku určuje jen on.|300|ona_nahore_zady",
    "Sedni si na něj, drž mu ruku na krku a druhou mu dráždi bradavky.|300|kontrola_vsede",
    "Nech ho klečet, drž ho za vlasy a zároveň mu sahej dopředu.|300|zezadu!",
    "Tři ruce, dvě těla: Jedna ruka na vlasech, druhá vpředu a on v tobě zezadu. Cíl: nepustit ani jedno.|300|zezadu!",
    "Rána za každý zvuk: Nech ho ležet na břiše a plácej ho dlaní po prdeli pokaždé, když se ozve. Cíl: deset plácnutí a ani jedno bez důvodu.|300|na_brise!",
    "Pět minut po prosbě: Spoutej ho a hoň mu tak dlouho, až začne prosit, a pak ho ještě pět minut nenech dojít. Cíl: vydržet těch pět minut.|300|pouta_postel!",
    "Přilož mu vibrátor a zároveň mu olizuj bradavky a hlaď ho.|300|vedle_on_lezi",
    "Drž ho rukou, palcem dráždi špičku a druhou rukou mu sahej dozadu.|300|vedle_on_lezi",
    "Všechno najednou: Ruka na kmeni, prst vzadu, ústa na špičce a druhá ruka na bradavkách. Cíl: udržet všechny čtyři.|300|oral_on_vleze",
    "Dvě ruce, dvě tempa: Honi mu každou rukou jinak a pokaždé, když zrychlí dech, obě zastav. Cíl: deset zastavení za pět minut.|300|vedle_on_lezi",
    "Zastav při napětí: Kuř mu a druhou rukou mu hlaď koule, ale zastav se pokaždé, když se napne. Cíl: pět zastavení, než ho necháš dojít.|300|oral_on_vleze",
    "Nech ho klečet a dráždi ho jazykem zezadu, zatímco ho držíš rukou vpředu.|300|zezadu!",
    "Sedni si mu na obličej a zároveň mu sahej rukou dozadu.|300|oral_ona_nad_nim",
    "Nech ho ležet na boku a dráždi ho zepředu, zezadu a líbej ho na krk.|300|dvojita_bok!",
    "Tempo určuješ ty: Nech ho, ať si honí sám, a ty mu nahlas určuj tempo. Cíl: pět změn tempa a udělat se smí až na tvoje slovo.|300|vedle_on_lezi",
    "On řídí všechno: On říká, kam máš sáhnout, kdy kouřit a kdy se na něj nasadit, a ty jen plníš. Cíl: pět minut a nic sama od sebe.|300|na_brise!",
    "Nech ho vybrat, kolik pomůcek dneska použiješ. Maximálně tři.|300|pouta_postel!",
    "Tři kola a dost: Nasaď se na něj a jezdi, dokud není těsně před koncem, pak se zvedni. Cíl: tři taková kola, než ho necháš dojít.|300|ona_nahore",
    "S kolíkem a pomalu: S kolíkem a hodně lubrikantu v zadku se na něj nasazuj co nejpomaleji. Cíl: hloubku určuješ jen ty.|300|ona_nahore",
    "Oznam mu, že se dneska udělá jen jednou, a ať si sám rozmyslí kdy. Kuř mu a čekej na jeho slovo.|300|oral_on_vleze",
    "Pět minut na hraně: Doveď ho rukou až na hranu a tam ho drž celých pět minut. Cíl: nenechat ho dojít ani jednou.|300|pouta_postel!",
    "Kroužek a přestimulace: Nasaď mu erekční kroužek a po orgasmu mu hoň dál. Cíl: nepřestat, dokud neřekne stop slovo nebo dost.|300|pouta_postel!",
    "Ústy a rukou střídavě: Minutu mu kuř, minutu mu hoň a u každého přechodu zastav na deset vteřin. Cíl: šest minut a ani jednou ho nenechat dojít.|300|oral_on_vleze",
    "Nech ho ležet s polštářem pod boky a dráždi ho všemi třemi způsoby.|300|misionar_polstar",
    "Spoutej ho a použij prst, vibrátor i jazyk za sebou.|300|pouta_postel!",
    "Postupná stavba: Nejdřív jen jazyk, pak přidej ruku, pak vibrátor. Nikdy nic neuber. Cíl: skončit se vším naráz.|300|oral_on_vleze",
    "Doveď ho na hranu trojkombinací a pak úplně přestaň.|300|oral_on_vleze",
    "Trojkombinace do konce: Kuř mu, rukou mu hoň a druhou mu hlaď koule, dokud se neudělá. Cíl: pak ještě půl minuty nepřestat.|300|oral_on_vleze",
    "Jedna po druhé: Dráždi ho postupně všemi pomůckami, co doma máte, vždycky jednou minutu. Cíl: nevynechat ani jednu.|300|pouta_postel!",
    "Vynechá jednu věc: Nech ho rozhodnout, jestli dneska vynecháte pouta, vibrátor, nebo kouření. Cíl: zbylé dvě věci dotáhnout do konce.|300|pouta_postel!",
    "Jen ty: Stejná trojkombinace, ale bez jediné hračky – vystačíš si rukama a ústy. Cíl: dokázat, že to jde.|300|oral_on_vleze",
    "Dráždi ho zezadu jazykem, zatímco si vpředu pomáhá sám.|300|na_brise!",
    "Spoutanému a na povel: Spoutej ho a kuř mu, ale udělat se smí až ve chvíli, kterou řekneš předem. Cíl: trefit ji na vteřinu.|300|pouta_postel!",
    "Všechno najednou: Nech ho ležet a zároveň mu kuř, hoň a dráždi mu koule. Cíl: pět minut a nepřerušit ani jedno.|300|vedle_on_lezi",
    "Během jediné minuty musí přijít na řadu led, vibrátor i tvůj jazyk.|300|oral_on_vleze",
    "Nech ho dojít trojkombinací a pak mu všechno pomalu vyndej.|300|oral_on_vleze",
    "Konec a péče: Přestaň ho dráždit, všechno opatrně vyndej, umyj si ruce, přines mu vodu a lehni si k němu. Cíl: nevynechat žádný krok.|180|lzicka",
    "Klidná tečka: Obejmi ho zezadu na lžičku a nech ho vydechnout. Cíl: dvě minuty ticha a ani jeden z vás nic nechce.|120|lzicka",
  ],
});
