// Kategorie 5 – Hardcore
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 5,
  name: "Hardcore",
  description: "Pouta, bičík, anál, dva vibrátory a úplná kontrola. Stop slovo platí vždycky.",

  // Úkoly pro muže – pro potěšení ženy
  male: [
    "Spoutej jí ruce pouty k čelu postele, zavaž jí oči a přikládej jí oba vibrátory – jeden na klitoris, druhý na bradavky. Nepřestávej, dokud nedojde.",
    "Předkloň ji přes opěradlo gauče a dej jí bičíkem 10 ran přes zadeček, postupně silněji. Ona počítá nahlas. Pak ji zezadu tvrdě miluj.",
    "Pomalu jí s lubrikantem vsuň prst do zadečku a zároveň ji lízej. Tempo zvyšuj jen podle toho, jak reaguje.|180",
    "Anál: použij hodně lubrikantu, začni jen špičkou a počkej, až se uvolní. Hloubku řídí ona, ty jí přitom hladíš klitoris.|240",
    "Miluj se s ní v misionáři a zároveň jí drž vibrátor na klitorisu. Nepřestávej ani po jejím orgasmu – dokud neřekne dost.",
    "Nasaď jí pouta za zády, klekni si za ni na posteli a tvrdě ji miluj zezadu. Drž ji přitom za pouta.|180",
    "Dvojitá stimulace: jeden vibrátor jí vsuň, druhý přilož na klitoris a jazykem jí přitom olizuj bradavky.|180",
    "Rozkaž jí, ať si lehne na kuchyňský stůl a nehne se. Dělej s ní, co chceš, a ona smí mluvit jen „ano“ nebo stop slovo.|240",
    "Odpírání orgasmu: dráždi ji vibrátorem až těsně k vrcholu a pak přestaň. Třikrát. Počtvrté ji nech dojít.",
    "Spoutej ji, zavaž jí oči a střídej pírko a bičík po celém těle. Ať nikdy neví, co přijde.|180",
    "Vezmi ji za vlasy (pevně, ale ne bolestivě), předkloň ji přes kuchyňskou linku a tvrdě ji miluj zezadu.|120",
    "Anál s vibrátorem: s hodně lubrikantu do ní pomalu vnikni análně, ona si přitom drží vibrátor na klitorisu.|180",
    "Dvojitý průnik: vsuň do ní vibrátor a sám do ní pomalu vnikni análně (jen pokud je vibrátor bezpečný a je jí to příjemné).|180",
    "Vynucené orgasmy: spoutej ji k posteli a vibrátorem ji doveď ke dvěma orgasmům za sebou.",
    "Dej jí 5 ran bičíkem na vnitřní stranu stehen a po každé ráně to místo olízni.",
    "Poruč jí, ať klečí na posteli s rukama za hlavou. Miluj ji zezadu a ona nesmí sundat ruce, jinak začínáte znovu.|180",
    "Tvrdý sex na gauči: ona leží na zádech s nohama na tvých ramenou, ty přirážíš rychle a silně.|120",
    "Spoutej ji pouty, polož ji na břicho, podlož jí boky polštářem a vsuň pod ni vibrátor. Pak ji miluj zezadu.|180",
    "Zakaž jí dojít. Pak ji lízej a prstěj tak dlouho, dokud to nevydrží. Až poprosí, dovol jí to.",
    "Zatímco ji miluješ zezadu, vsuň jí namazaný palec do zadečku.|120",
    "Dej jí pouta, zavaž jí oči a posaď ji na židli. Lízej ji a vibrátorem ji dráždi, dokud se na židli nezačne kroutit.|180",
    "Plácej ji dlaní po zadečku, zatímco na tobě jezdí – tak, aby to cítila, ale chtěla víc.|90",
    "Nech ji klečet na zemi opřenou o gauč s rukama spoutanýma před sebou. Miluj ji zezadu a jednou rukou ji drž za boky.|180",
    "Prstěj ji dvěma prsty rychle a intenzivně proti bodu G, dokud nedojde. Může přitom i stříkat, tak podlož ručník.",
    "Předkloň ji přes kraj postele, dej jí bičíkem 3 rány, pak 3 přírazy, pak 3 rány. Opakuj.|180",
    "Anál ve lžičce: ležíte na boku, ty za ní. S hodně lubrikantu do ní pomalu vnikni, ona tě navádí rukou.|180",
    "Spoutej jí ruce za zády, klekni si před ni a lízej ji, zatímco stojí opřená o zeď.|120",
    "Vibrátorem jí zvenku dráždi zadeček, zatímco ji miluješ v misionáři.|180",
    "Přikaž jí, ať si sama drží nohy u prsou, a tvrdě ji miluj. Nesmí je pustit.|120",
    "Zavaž jí oči a přivaž jí ruce k nohám postele (pouty nebo šátkem). Pak ji lízej, dokud nedojde dvakrát.",
    "Miluj se s ní na kuchyňské lince tvrdě a rychle, jednou rukou ji drž za zátylek.|120",
    "Vsuň jí vibrátor do zadečku (jen takový, který je na to bezpečný – s rozšířenou základnou) a miluj se s ní klasicky. Jinak použij prst.|180",
    "Nasaď jí pouta a polož ji na břicho. Bičíkem jí dej rány přes zadeček a stehna – ona řekne, kdy přestat.",
    "Ovládej její orgasmus: miluj ji a ona smí dojít jen na tvůj povel „teď“. Počítej odzadu od deseti.",
    "Lízej jí zadeček (anilingus) a zároveň jí vibrátorem dráždi klitoris.|120",
    "Spoutej jí obě ruce nad hlavou a jen ji pomalu líbej po celém těle. Pak ji ale vezmi tvrdě.|240",
    "Nech ji stát spoutanou uprostřed obýváku se zavázanýma očima. Obcházej ji a dotýkej se jí bičíkem, rukama a vibrátorem.|180",
    "Ve sprše se ona opře o stěnu a ty ji tvrdě miluj zezadu, drž ji přitom za boky.|120",
    "Zapni oba vibrátory na nejvyšší stupeň: jeden jí vsuň, druhý přilož na klitoris. Drž jí přitom ruce, ať si je nemůže sundat.|120",
    "Poruč jí, ať si klekne na postel, předkloní se a roztáhne si hýždě rukama. Lízej ji a pak si vyber, kam do ní vnikneš.",
    "Přehni ji přes koleno. Plácej ji dlaní po zadečku a mezi ranami ji hlaď mezi nohama.|90",
    "Posaď ji na židli a spoutej jí ruce za opěradlem. Klekni si a lízej ji, dokud nebude prosit o pauzu.",
    "Miluj ji v misionáři a drž jí přitom zápěstí přitisknutá k posteli. Rychle a hluboko.|120",
    "Anál na kraji postele: ona leží na břiše, ty stojíš. Použij hodně lubrikantu, začni pomalu a pak zrychluj podle ní.|180",
    "Poruč jí, ať se ti dívá do očí a nesmí je zavřít, zatímco ji vibrátorem dovádíš k orgasmu.",
    "Spoutej ji a přikaž jí, ať ti řekne, co přesně chce. Pokud to neřekne dost konkrétně, nedostane to.",
    "Polož ji na jídelní stůl, spoutej jí ruce nad hlavou a miluj ji vestoje. Jednou rukou jí přitom drž vibrátor na klitorisu.|180",
    "Plácni ji bičíkem přes bradavky jen velmi jemně – a hned je olízni. Pětkrát.",
    "Zkus s ní „vynucený“ orgasmus vibrátorem – drž jí ho na klitorisu, i když se kroutí, dokud nedojde (stop slovo platí).",
    "Miluj ji v jakékoli poloze a každých 20 vteřin jí dej plácnutí na zadeček. Ona počítá.|180",
    "Spoutej jí ruce za zády a posaď si ji na sebe. Drž ji za boky a tvrdě přirážej zespodu.|120",
    "Vsuň do ní vibrátor a nech ho tam. Pak jí lízej klitoris. Nesmí se pohnout.|180",
    "Tvrdý sex zezadu na posteli – jednou rukou ji drž za vlasy, druhou jí hlaď klitoris.|120",
    "Prstem s lubrikantem jí pomalu dráždi zadeček a zároveň do ní zasouvej vibrátor.|180",
    "Rozkaž jí, ať si lehne na podlahu v obýváku s roztaženýma nohama a rukama nad hlavou. Klekni si mezi její nohy a vezmi si ji.|180",
    "Nasaď jí pouta, zavaž jí oči, polož ji na gauč a vystřídejte 4 různé polohy. Ona netuší, co přijde.|240",
    "Miluj ji tak tvrdě a rychle, jak to jen jde, a pak se úplně zastav a pomalu ji polib. Opakuj.|180",
    "Nech ji, ať si vybere počet ran bičíkem (1–15). Dej jí je a po poslední ji odměň orálem.",
    "Ona klečí a má v sobě vibrátor, ty do ní zezadu pomalu vnikni análně. Použij hodně lubrikantu.|180",
    "Oba vibrátory přilož na klitoris zároveň z obou stran a nepovol, dokud nedojde.",
    "Postav ji spoutanou před zrcadlo, přitiskni se k ní zezadu a vibrátorem ji doveď k orgasmu. Musí se u toho dívat.",
    "Poruč jí, ať nahlas popisuje, co cítí, zatímco ji tvrdě miluješ. Když přestane mluvit, zpomal.|180",
    "Spoutej ji v koupelně (ruce před tělem), posaď ji na okraj vany a proudem ze sprchy jí miř na klitoris, dokud nedojde.",
    "Zatímco na tobě jezdí zády k tobě, plácej ji bičíkem po zadečku.|120",
    "Lízej ji po orgasmu dál – jemně, ale nepřestávej, dokud nepřijde další.",
    "Přikaž jí, ať se předkloní přes kuchyňskou linku a vystrčí na tebe zadeček, pak ji tvrdě miluj a drž ji za ramena.|120",
    "Přivaž jí zápěstí ke kotníkům (pouty nebo šátky), ať je rozevřená, a lízej ji.|180",
    "Miluj ji v misionáři a zároveň jí vsuň vibrátor do zadečku (s rozšířenou základnou) nebo tam dej prst s lubrikantem.|180",
    "Zakaž jí dotknout se sebe i tebe. Pak ji aspoň 5 minut dráždi, ale nenech ji dojít.|300",
    "Spoutej ji k posteli, zavaž jí oči a nech vibrátor na jejím klitorisu na nízký stupeň. Pak se na minutu potichu odtáhni (zůstaň v pokoji), ať neví, kde jsi – a pak pokračuj.|60",
    "Poruč jí, ať si na tebe sedne a jezdí rychle. Když zpomalí, dostane ránu bičíkem.|120",
    "Tvrdý sex vestoje v chodbě: ona se opírá o zeď, ty ji miluješ zezadu a držíš jí ruce na zdi.|120",
    "Vezmi si ji na pračce v plném odstřeďování – tvrdě a rychle.|120",
    "Plácni ji po zadečku třikrát bičíkem, třikrát dlaní a nakonec ho třikrát polib.",
    "Nasaď jí pouta s rukama před tělem a nech ji, ať tě navádí rukama tam, kde tě chce.|180",
    "Anál v misionáři: podlož jí boky polštářem, hodně lubrikantu, dívej se jí do očí a hlaď jí klitoris.|180",
    "Ona klečí spoutaná na gauči. Vsuň do ní vibrátor a miluj ji zezadu análně (pokud chce), nebo klasicky s vibrátorem na klitorisu.|180",
    "Prstěj ji a lízej zároveň, dokud nebude mít orgasmus. Pak ji hned miluj tvrdě.",
    "Spoutej jí ruce za zády a nech ji ležet na břiše na posteli. Lehni si na ni celou vahou (opatrně) a miluj ji zezadu pomalu a hluboko.|180",
    "Zakaž jí mluvit, dokud nedojde. Za každé slovo dostane ránu bičíkem.",
    "Přikládej jí vibrátor střídavě na klitoris a na zadeček, zatímco ji miluješ.|180",
    "Zavaž jí oči, spoutej ji a vsuň jí prst do pusy. Ať ho saje, zatímco ji miluješ.|120",
    "Dej jí 20 rychlých lehkých plácnutí bičíkem po celém zadečku a stehnech. Pak do ní vnikni.",
    "Miluj ji na kraji jídelního stolu a přitom jí oběma vibrátory hlaď bradavky.|180",
    "Drž jí zápěstí za zády jako v poutech a tvrdě ji miluj zezadu u okna se zataženými závěsy.|120",
    "Nech ji ležet se spoutanýma rukama na zádech. Olizuj ji, prstěj ji, miluj ji – prostě ji rozmazluj, dokud neřekne dost.",
    "Rozkaž jí, ať si sama drží vibrátor na klitorisu, a pokud ho sundá, přestaneš. Pak ji tvrdě miluj.|180",
    "Anál vestoje u kuchyňské linky: hodně lubrikantu, začni pomalu a pak pokračuj tak, jak je jí to příjemné.|180",
    "Spoutej ji a doveď ji k orgasmu jen pírkem a vibrátorem. Jazyk ani prsty nesmíš použít.",
    "Plácni ji bičíkem na zadeček vždy, když zasténá. Pak ji miluj tak, aby sténala pořád.|120",
    "Vsuň jí dva prsty do vagíny a palec s lubrikantem do zadečku a jemně je k sobě přitlač.|90",
    "Miluj ji zezadu na posteli a nech ji, ať si vybere: rány bičíkem, nebo vibrátor na klitoris. Může si vybrat i obojí.|180",
    "Poruč jí, ať si klekne na koberec a prohne záda. Miluj ji zezadu a drž ji za oba boky.|180",
    "Spoutej ji pouty a nech ji, ať ti řekne, jak moc chce, abys jí dal orgasmus. Pak jí dej dva.",
    "Anál na boku: ona leží na boku, ty za ní. Vibrátor jí přikládej zepředu na klitoris.|180",
    "Miluj ji a jednou rukou jí zakrývej pusu, aby tlumila sténání (nos nech volný).|90",
    "Tvrdý sex v misionáři na podlaze v kuchyni. Rychle, hluboko, bez přestávky.|120",
    "Zavaž jí oči a přikaž jí, ať si klekne na postel na všechny čtyři. Pak ji nech minutu čekat a pak ji dráždi bičíkem a vibrátorem.|60",
    "Nech v ní vibrátor a posaď si ji na sebe tak, abyste vibrace cítili oba.|180",
    "Odpírání: spoutej ji a pokaždé, když se blíží orgasmu, dej jí lehkou ránu bičíkem a přestaň. Až po pátém pokusu ji nech dojít.",
    "Spoutej ji k čelu postele a miluj ji tvrdě v misionáři s jejíma nohama na svých ramenou.|120",
    "Lízej jí zadeček a vagínu střídavě, a vibrátorem jí přitom dráždi klitoris.|120",
    "Poruč jí, ať si tě sama pomalu zavede do zadečku, a nech ji, ať si tempo určí sama. Ty jí přitom hlaď klitoris.|180",
    "Na gauči ji ohni přes područku a miluj ji zezadu tvrdě. Pak jí dej ránu bičíkem a zase zpomal.|180",
    "Vezmi ji do sprchy, spoutej jí ruce a miluj ji tam zezadu. Pozor na uklouznutí.|120",
    "Jeden vibrátor jí vsuň, druhý ať si sevře stehny na klitorisu. Jazykem jí olizuj bradavky a rukama jí drž zápěstí.|180",
    "Rozkaž jí, ať ti řekne tu nejdivočejší věc, kterou by s tebou chtěla. Když to jde, udělej jí to hned.",
    "Tvrdě ji miluj a ona smí dojít, jen když si o to řekne tvým jménem.|180",
    "Spoutej jí ruce, zavaž jí oči a dej jí na výběr: tvrdý sex, nebo 5 minut vibrátoru. Pak udělej to druhé taky.",
    "Stáhni ji za nohy ke kraji postele, roztáhni jí nohy a vezmi si ji tvrdě vestoje.|120",
    "Pomalý anál: po každém přírazu jí řekni, jak je skvělá.|180",
    "Dráždi ji vibrátorem tak, aby dosáhla orgasmu co nejrychleji. Hned potom ji k dalšímu doveď co nejpomaleji.",
    "Dej jí pouta a nech ji, ať sama rozhodne, kam ti má připnout ruce – a pak ji potěš jen pusou.",

    // Karty s cílem
    "Výslech: Spoutej jí ruce za zády a posaď ji na židli. Ptej se na její nejtajnější fantazie – za každou upřímnou odpověď dostane minutu vibrátoru na klitoris, za vytáčku ránu bičíkem na stehno. Cíl: aby ti prozradila aspoň tři.",
    "Orgasmový žebříček: Spoutej ji k posteli. Cíl: tři orgasmy – první vibrátorem, druhý jazykem, třetí při sexu – a mezi nimi jí nedej víc než minutu pauzy.",
    "Anální rozehřátí: Ona leží na břiše s polštářem pod boky a vibrátorem pod klínem. Namasíruj jí zadeček olejem, pak prstem s lubrikantem kruž kolem zadečku a nakonec pomalu jeden prst dovnitř. Cíl: aby sama řekla, že chce víc.|300",
    "Královna na deset minut: Ona leží a rozkazuje, ty plníš každý její sexuální příkaz přesně a bez odmlouvání. Cíl: splnit všechno, dokud nedojde.|600",
    "Bičík podle abecedy: Ona je na všech čtyřech. Dej jí 26 lehkých ran bičíkem a u každé řekne další písmeno abecedy. Když se splete, začínáš od A. Cíl: dojít k Z – a pak ji odměnit orálem.",
    "Bez tvých rukou: Spoutej jí ruce nad hlavou. Jeden vibrátor jí vsuň, druhý ať si sevře stehny na klitorisu. Ty ji jen líbáš. Cíl: orgasmus bez jediného dotyku tvých rukou.",
    "Anál v zrcadle: Ležíte na boku čelem k zrcadlu, ty za ní. S velkým množstvím lubrikantu do ní pomalu vnikni análně, ona si drží vibrátor na klitorisu. Cíl: dívat se na sebe v zrcadle, dokud nedojde.|300",
    "Odpočet: Dráždi ji vibrátorem a ona smí dojít až po odpočítání od 30 do 0 nahlas. Když dojde dřív, dostane pět ran bičíkem. Cíl: aby došla přesně na nule.",
    "Spoutané kotníky: Spoutej jí kotníky pouty a polož ji na břicho. Miluj ji zezadu mezi stisknutými stehny. Cíl: nepřestat, dokud nedojde.|240",
    "Nehybná u zdi: Spoutej jí ruce za zády a postav ji ke zdi. Zatímco ji prstíš a lížeš, nesmí se pohnout – za každý pohyb rána bičíkem. Cíl: aby vydržela dvě minuty.|120",
    "Dvojitý průnik: Vsuň jí vibrátor do vagíny a sám do ní pomalu vnikni análně s hodně lubrikantu (nebo naopak – vibrátor do zadečku jen s rozšířenou základnou). Cíl: pomalu, dokud sama nechce rychleji.|240",
    "Tvrdě přes gauč: Předkloň ji přes opěradlo gauče, chyť ji za boky a přirážej tvrdě a rychle. Každých 30 vteřin jí dej plácnutí. Cíl: tři minuty bez zpomalení.|180",
    "Nepovolit: Po jejím prvním orgasmu vibrátorem nech vibrátor dál na klitorisu na nejnižším stupni a drž jí ruce. Cíl: druhý orgasmus bez pauzy – stop slovo platí.",
    "Na kolenou u postele: Ona klečí na zemi, hrudníkem leží na posteli a ruce má spoutané před sebou. Ty ji miluješ zezadu – análně, nebo klasicky, podle ní. Cíl: pevně ji držet za boky a udržet tvrdé stálé tempo.|180",
    "Stupnice bolesti a slasti: Přehni ji přes koleno. Plácej ji bičíkem a ona po každé ráně řekne číslo od 1 do 10. Cíl: držet se mezi 5 a 7 a pak ji prsty dovést k orgasmu, dokud má zadeček ještě horký.",
    "Nikdy neví: Spoutej ji a zavaž jí oči. Každých 20 vteřin něco jiného – rána bičíkem, pírko, vibrátor, jazyk, příraz. Cíl: pět minut, kdy nikdy neví, co přijde.|300",
    "Řekni prosím: Miluj ji a přestaň. Pokračuj jen tehdy, když ti přesně řekne, co chce, a začne slovy „prosím, udělej mi…“. Cíl: aby to řekla aspoň pětkrát.",
    "Anál na stole: Ona leží na zádech na kraji jídelního stolu s nohama nahoře a ručníkem pod boky, ty stojíš. Hodně lubrikantu a pomalý začátek. Cíl: ona si hladí klitoris a řídí tvoje tempo rukou na tvém břiše.|240",
    "Židle s vibrátorem: Posaď ji na židli s rukama spoutanýma za opěradlem a vibrátorem na sedáku pod jejím klínem. Ty jí saješ bradavky. Cíl: aby se o vibrátor otírala, dokud nedojde.",
    "Tři najednou: Jeden vibrátor jí vsuň, druhý přilož zvenku na zadeček a jazykem jí lízej klitoris. Cíl: udržet všechny tři najednou, dokud nedojde.",
    "Pevný stisk: Chyť ji zezadu za vlasy u kořínků – pevně, ne bolestivě – a druhou rukou za bok. Miluj ji tvrdě na kolenou na posteli. Cíl: zaklonit jí hlavu a šeptat jí do ucha, jak je dokonalá.|180",
    "Rány a přírazy: Ona je předkloněná přes linku. Tři rány bičíkem, tři hluboké přírazy, znovu tři rány. Cíl: deset kol a pak pokračovat bez počítání, dokud nedojde.",
    "Rozevřená: Spoutej jí zápěstí ke kotníkům – levou ruku k levému, pravou k pravému – ať leží na zádech rozevřená. Cíl: vylízat ji k orgasmu, zatímco se nemůže bránit.",
    "Prst při přírazech: Při sexu v misionáři jí vsuň namazaný prst do zadečku a nech ho tam. Cíl: přirážet tak, aby se prst hýbal s tebou, dokud nedojde.|180",
    "Pět přerušení: Dráždi ji k orgasmu a pokaždé, když řekne „už budu“, přestaň. Když vydrží pět přerušení bez prošení, dostane orgasmus, jaký si sama řekne. Cíl: dotáhnout hru do konce.",
    "Ruce za hlavou: Ať si klekne nahá na koberec s rukama za hlavou a nohama od sebe. Obcházej ji s bičíkem a dotýkej se jí jím. Cíl: pak si klekni za ni a vezmi si ji, aniž by sundala ruce.|240",
    "Plná: Jeden vibrátor jí vsuň do vagíny, druhý – bezpečný, s rozšířenou základnou – do zadečku (jinak použij prst). K tomu jí lízej klitoris. Cíl: orgasmus, jaký ještě nezažila.",
    "Tvrdě a polibek: Udělej dvacet tvrdých rychlých přírazů, pak se na 10 vteřin úplně zastav a polib ji. Cíl: deset kol – v posledním nepřestávej.|300",
    "Spoutané ruce mezi nohama: Nasaď jí pouta tak, aby měla ruce před tělem mezi nohama, a přikaž jí, ať se hladí, zatímco ji miluješ zezadu. Cíl: musí se k orgasmu dovést sama, ty jen přirážíš.|240",
    "Pouta ve sprše: Ve sprše jí spoutej ruce před tělem, zvedni jí je nad hlavu a drž je. Miluj ji zezadu. Cíl: pomalé tvrdé přírazy dvě minuty – a pozor na uklouznutí.|120",
    "Krok za krokem: Spoutej ji, zavaž jí oči a polož ji na břicho s polštářem pod boky. Nejdřív ji lízej, pak prstěj, pak pomalu anál. Cíl: před každou další fází musí říct „ano“.",
    "Povel s trestem: Dráždi ji vibrátorem – dojít smí jen na „teď“. Když dojde dřív, dostane pět ran bičíkem a začínáte znovu. Cíl: aby došla přesně na povel.",
    "Pod stolem: Ona sedí na židli u stolu s rukama spoutanýma za opěradlem, ty jsi pod stolem a lížeš ji a prstíš. Cíl: zastavit tě může jen stop slovem.",
    "Trest nahoře, odměna dole: Horní polovinu jejího těla lehce plácej bičíkem, klín odměňuj vibrátorem. Střídej po 20 vteřinách. Cíl: dokud nedojde.|240",
    "Anál vestoje: Ona se opírá o zeď a ty jsi za ní. Hodně lubrikantu, začni jen špičkou a čekej. Cíl: ona řídí hloubku rukou na tvém boku.|180",
    "Hravý souboj: Minutu se ti snaží vyklouznout z postele a ty ji chytáš a držíš – hravě, bez násilí. Když ji chytíš, spoutej ji a vezmi si ji. Cíl: skončit v ní.",
    "Tři různé orgasmy: Doveď ji k orgasmu prsty, pak ji otoč a miluj zezadu, pak zase vibrátor. Cíl: tři různé orgasmy během patnácti minut.|900",
    "Spoutaná na gauči: Spoutej jí ruce za zády a posaď ji na gauč s jednou nohou přes područku a druhou přes opěradlo. Cíl: lízat ji, dokud nebude prosit o pauzu – a pak ještě 30 vteřin.",
    "Vedená bytem: Chyť ji za pouta a veď ji nahou do ložnice. Cestou ji zastav u zdi, u stolu a u dveří a pokaždé se s ní minutu miluj. Cíl: dojít do postele a tam ji dokončit.",
    "Horký zadeček: Dej jí třicet plácnutí dlaní na zadeček, střídavě na obě půlky, pak ji otoč a lízej. Cíl: orgasmus do tří minut.",
    "Sténání za plácnutí: Miluj ji tvrdě a za každé hlasité zasténání dostane plácnutí. Cíl: aby sténala tak, že přestaneš počítat.|180",
    "Anál se dvěma vibrátory: Miluj ji análně zezadu, ona si drží jeden vibrátor na klitorisu a druhý jí vsuneš do vagíny. Cíl: pomalu, dokud necítí plnost, pak tempo podle ní.|240",
    "Houpačka moci: Každou minutu si prohoďte, kdo velí a kdo poslouchá. Příkazy musí být sexuální a splnitelné hned. Cíl: šest minut a tři výměny.|360",
    "Natažená přes stůl: Ona leží na břiše na jídelním stole s rukama spoutanýma a nataženýma před sebe, ty stojíš za ní. Cíl: tvrdé tempo a každých dvacet přírazů rána bičíkem.|180",
    "Kolik jich zvládne: Najdi s vibrátorem místo, kde dojde nejrychleji. Doveď ji k orgasmu, dej jí 30 vteřin pauzu a znovu. Cíl: kolik orgasmů zvládne za deset minut?|600",
    "Tvrdá lžička: Spoutej jí ruce za zády, lehni si za ni na bok, jednou rukou ji drž za bok a druhou jí hlaď klitoris. Cíl: tři minuty tvrdých přírazů bez zpomalení.|180",
    "Rána a prst: Přehni ji přes koleno a po každé ráně bičíkem do ní na chvíli vsuň prst. Cíl: patnáct ran a pak ji prsty dovést k orgasmu.",
    "Nohy spoutané nahoře: Spoutej jí kotníky, zvedni si její nohy na rameno a miluj se s ní. Cíl: těsné a hluboké přírazy – a ptát se, jestli to není moc.|180",
    "Její fantazie: Nech ji říct jednu hardcore fantazii, kterou jste ještě nezkusili a dá se udělat hned. Cíl: splnit ji.",
    "Spoutaná na tvé tváři: Lehni si na záda, spoutej jí ruce za zády a nech ji sednout si ti na obličej. Cíl: držet ji za boky a lízat, dokud nedojde a nesesune se.",
    "Silný vibrátor: Zapni vibrátor na nejvyšší stupeň, přitlač jí ho na klitoris a drž ho tam, i když se kroutí. Druhou rukou jí drž zápěstí. Cíl: rychlý a silný orgasmus – stop slovo platí.",
    "Anální jezdkyně: Lehni si na záda, ona si na tebe sedne a pomalu si tě zavede do zadečku, ty jí hladíš klitoris vibrátorem. Cíl: ona má úplnou kontrolu nad hloubkou i tempem.|240",
    "Písmeno bičíkem: Nakresli jí lehkými ranami bičíku na zadeček písmeno, třeba první písmeno svého jména. Cíl: když uhodne, dostane orál, když ne, kreslíš znovu.",
    "Deset minut dominance: Deset minut rozhoduješ o všem – poloze, tempu, kdy smí dojít a kam se má dívat. Ona odpovídá jen „ano“. Cíl: dát jí nejsilnější orgasmus večera.|600",
    "Péče po hře: Po nejtvrdším úkolu ji odpoutej, promasíruj jí zápěstí a zadeček, přikryj ji dekou a dej jí napít. Pak ji jemně hlaď prsty, dokud znovu nedojde. Cíl: vystřídat tvrdost něhou.",
    "Finále: Zkombinuj pouta, bičík, oba vibrátory a anál nebo vagínu podle její chuti. Cíl: deset minut bez chvilky nudy a na konci společný orgasmus.|600",
  ],

  // Úkoly pro ženu – pro potěšení muže
  female: [
    "Spoutej mu ruce pouty k čelu postele, zavaž mu oči a kouři mu, zatímco mu vibrátor přikládáš na varlata. Nepřestávej, dokud se neudělá.",
    "Předkloň ho přes opěradlo gauče a dej mu bičíkem 10 ran přes zadek, postupně silněji. On počítá nahlas. Pak si na něj sedni.",
    "Namaž si prst lubrikantem, pomalu mu ho zasuň do zadku a pohybem „pojď sem“ směrem k břichu mu masíruj prostatu, zatímco mu kouříš.|180",
    "Nabídni mu anál: použijte hodně lubrikantu, hloubku i tempo řídíš ty a jeho ruku si dej na klitoris.|240",
    "Jezdi na něm a po jeho orgasmu nepřestávej hned – zpomal, ale pokračuj, dokud neřekne dost.",
    "Nasaď mu pouta za zády, posaď ho na kraj postele a jezdi na něm tvrdě a rychle.|180",
    "Dvojitá stimulace: jeden vibrátor mu přilož na varlata, druhý na hráz a přitom mu kouři.|180",
    "Rozkaž mu, ať si lehne na kuchyňský stůl a nehne se. Dělej s ním, co chceš, a on smí mluvit jen „ano“ nebo stop slovo.|240",
    "Odpírání orgasmu: kouři mu až těsně k vrcholu a pak přestaň. Třikrát. Počtvrté ho nech dojít.",
    "Spoutej ho, zavaž mu oči a střídej pírko a bičík po celém těle. Ať nikdy neví, co přijde.|180",
    "Chyť ho za vlasy, přitáhni si ho k sobě a poruč mu, ať tě tvrdě vezme zezadu na kuchyňské lince.|120",
    "Nabídni mu anál, zatímco si sama držíš vibrátor na klitorisu. Pomalu a hodně lubrikantu.|180",
    "Dvojitý průnik: vsuň si vibrátor do vagíny a jeho nech vniknout do zadečku – nebo naopak. Ty řídíš, co a jak.|180",
    "Vynucený orgasmus: spoutej ho k posteli a hoň mu, dokud se neudělá. Pak pokračuj ještě chvíli jemně.",
    "Dej mu 5 ran bičíkem na vnitřní stranu stehen a po každé ráně to místo olízni.",
    "Poruč mu, ať klečí na posteli s rukama za hlavou. Klekni si před něj a kouři mu – nesmí sundat ruce, jinak přestaneš.|180",
    "Tvrdý sex na gauči: lehni si na záda, nohy mu dej na ramena a řekni mu, ať přiráží rychle a silně.|120",
    "Spoutej ho pouty, polož ho na záda a jezdi na něm s vibrátorem přitisknutým mezi vámi.|180",
    "Zakaž mu dojít. Pak mu kouři tak dlouho, dokud to nevydrží. Až poprosí, dovol mu to.",
    "Zatímco na něm jezdíš, sáhni si za sebe a namazaným prstem mu masíruj hráz a zadek.|120",
    "Dej mu pouta, zavaž mu oči a posaď ho na židli. Kouři mu a vibrátorem mu dráždi varlata, dokud se na židli nezačne kroutit.|180",
    "Plácej ho dlaní po zadku, zatímco je v tobě – do rytmu, jaký chceš.|90",
    "Nech ho sedět na gauči se spoutanýma rukama za zády. Klekni si nad něj a jezdi na něm.|180",
    "Hoň mu rychle a intenzivně s lubrikantem, zatímco mu olizuješ bradavky. Nepřestávej, dokud se neudělá.",
    "Předkloň ho přes kraj postele, dej mu bičíkem 3 rány, pak ho 3× olízni, pak 3 rány. Opakuj.|180",
    "Lehněte si do lžičky, ty za ním. Prstem mu masíruj prostatu a druhou rukou mu hoň.|180",
    "Spoutej mu ruce za zády, klekni si před něj a kouři mu, zatímco stojí opřený o zeď.|120",
    "Vibrátorem mu zvenku dráždi zadek, zatímco na něm jezdíš.|180",
    "Přikaž mu, ať si lehne na záda a drží se čela postele. Jezdi na něm tvrdě – nesmí se pustit.|120",
    "Zavaž mu oči a přivaž mu ruce k nohám postele (pouty nebo šátkem). Pak mu kouři, dokud se neudělá.",
    "Sedni si na kuchyňskou linku a poruč mu, ať tě tvrdě a rychle vezme. Drž ho přitom za zátylek.|120",
    "Vsuň mu vibrátor do zadku (jen takový, který je na to bezpečný – s rozšířenou základnou) a jezdi na něm. Jinak použij prst.|180",
    "Nasaď mu pouta a polož ho na břicho. Bičíkem mu dej rány přes zadek a stehna – on řekne, kdy přestat.",
    "Ovládej jeho orgasmus: jezdi na něm a on smí dojít jen na tvůj povel „teď“. Počítej odzadu od deseti.",
    "Lízej mu zadek (anilingus) a přitom mu hoň.|120",
    "Spoutej mu obě ruce nad hlavou a jen ho pomalu líbej po celém těle. Pak na něm ale jezdi tvrdě.|240",
    "Nech ho stát spoutaného uprostřed obýváku se zavázanýma očima. Obcházej ho a dotýkej se ho bičíkem, rukama a vibrátorem.|180",
    "Opři se o stěnu ve sprše a poruč mu, ať tě tvrdě vezme zezadu.|120",
    "Zapni oba vibrátory na nejvyšší stupeň, jeden mu přilož na varlata, druhý na hráz a přitom mu kouři.|120",
    "Klekni si na postel, předkloň se a roztáhni si hýždě rukama. Nech ho, ať si vybere, kam do tebe vnikne.",
    "Přehni ho přes koleno. Plácej ho dlaní po zadku a mezi ranami mu hoň.|90",
    "Posaď ho na židli a spoutej mu ruce za opěradlem. Klekni si a kouři mu, dokud nebude prosit o pauzu.",
    "Chyť ho za zápěstí, přitiskni ho k posteli a jezdi na něm rychle a hluboko.|120",
    "Anál na kraji postele: lehni si na břicho na kraj postele, on stojí. Použijte hodně lubrikantu a ty mu říkej, jak rychle smí.|180",
    "Poruč mu, ať se ti dívá do očí a nesmí je zavřít, zatímco mu honíš až do konce.",
    "Spoutej ho a přikaž mu, ať ti řekne, co přesně chce. Pokud to neřekne dost konkrétně, nedostane to.",
    "Lehni si na jídelní stůl, poruč mu, ať ti spoutá ruce nad hlavou a vezme si tě vestoje.|180",
    "Plácni ho bičíkem přes bradavky jen velmi jemně – a hned je olízni. Pětkrát.",
    "Spoutej ho a hoň mu i po orgasmu – jemně, dokud to snese (stop slovo platí).",
    "Jezdi na něm a každých 20 vteřin mu dej plácnutí na stehno. On počítá.|180",
    "Spoutej mu ruce za zády, lehni si na záda a přitáhni si ho na sebe. Nohama ho řiď, jak rychle a hluboko smí.|120",
    "Kouři mu a zároveň mu masíruj prostatu prstem. Nesmí se pohnout.|180",
    "Klekni si na posteli a poruč mu, ať tě tvrdě vezme zezadu a chytí tě za vlasy (ne bolestivě).|120",
    "Prstem s lubrikantem mu pomalu dráždi zadek a zároveň mu přikládej vibrátor na varlata.|180",
    "Rozkaž mu, ať si lehne na podlahu v obýváku s rukama nad hlavou. Obkroč ho a vezmi si ho.|180",
    "Nasaď mu pouta, zavaž mu oči, polož ho na gauč a vystřídejte 4 různé polohy. Netuší, co přijde.|240",
    "Jezdi na něm tak tvrdě a rychle, jak to jen jde, a pak se úplně zastav a pomalu ho polib. Opakuj.|180",
    "Nech ho, ať si vybere počet ran bičíkem (1–15). Dej mu je a po poslední ho odměň orálem.",
    "Klekni si, vsuň si vibrátor a nabídni mu anál zezadu. Pomalu a s hodně lubrikantu.|180",
    "Oba vibrátory přilož z obou stran na jeho penis a hoň mu jimi, dokud se neudělá.",
    "Postav ho spoutaného před zrcadlo, přitiskni se k němu zezadu a hoň mu až do konce. Musí se u toho dívat.",
    "Poruč mu, ať nahlas popisuje, co cítí, zatímco na něm tvrdě jezdíš. Když přestane mluvit, zpomal.|180",
    "Spoutej ho v koupelně (ruce před tělem), posaď ho na okraj vany a kouři mu pod sprchou, dokud se neudělá.",
    "Jezdi na něm a pokaždé, když přestane přirážet zespodu, plácni ho bičíkem přes stehno.|120",
    "Kouři mu i po orgasmu dál – velmi jemně, dokud tě neodtáhne.",
    "Předkloň se přes kuchyňskou linku, vystrč na něj zadeček a poruč mu, ať tě tvrdě vezme a drží tě za ramena.|120",
    "Přivaž mu zápěstí k nohám postele pouty nebo šátky, obkroč mu obličej a nech se lízat. Pak se posuň níž a sedni si na něj.|180",
    "Jezdi na něm a zároveň mu vsuň vibrátor do zadku (s rozšířenou základnou) nebo tam dej prst s lubrikantem.|180",
    "Zakaž mu dotknout se sebe i tebe. Pak ho aspoň 5 minut dráždi, ale nenech ho dojít.|300",
    "Spoutej ho k posteli, zavaž mu oči a nech vibrátor na jeho varlatech na nízký stupeň. Pak se na minutu potichu odtáhni (zůstaň v pokoji), ať neví, kde jsi – a pak pokračuj.|60",
    "Poruč mu, ať tě miluje rychle. Když zpomalí, dostane ránu bičíkem.|120",
    "Opři se o zeď v chodbě a poruč mu, ať tě vezme tvrdě zezadu. Jeho ruce si drž na bocích.|120",
    "Sedni si na pračku v plném odstřeďování a nech se od něj tvrdě a rychle vzít.|120",
    "Plácni ho po zadku třikrát bičíkem, třikrát dlaní a nakonec ho třikrát polib.",
    "Nasaď mu pouta s rukama před tělem a kouři mu, zatímco ti jeho spoutané ruce drží hlavu.|180",
    "Nabídni mu anál v misionáři: podlož si boky polštářem, hodně lubrikantu, dívej se mu do očí.|180",
    "Klekni si na gauč, vsuň si vibrátor a nech ho, ať tě miluje zezadu – análně (pokud chceš), nebo klasicky.|180",
    "Hoň mu a kouři zároveň, dokud se neudělá. Pak ho olízni dočista.",
    "Spoutej mu ruce za zády a nech ho ležet na zádech. Sedni si na něj a jezdi pomalu a hluboko.|180",
    "Zakaž mu mluvit, dokud se neudělá. Za každé slovo dostane ránu bičíkem.",
    "Přikládej mu vibrátor střídavě na varlata a na zadek, zatímco na něm jezdíš.|180",
    "Zavaž mu oči, spoutej ho a vsuň mu prst do pusy. Ať ho saje, zatímco na něm jezdíš.|120",
    "Dej mu 20 rychlých lehkých plácnutí bičíkem po celém zadku a stehnech. Pak si na něj sedni.",
    "Lehni si na kraj jídelního stolu a zatímco tě miluje, přikládej mu oba vibrátory na bradavky.|180",
    "Opři se o parapet okna se zataženými závěsy a poruč mu, ať tě miluje zezadu a ruce přitom drží za zády. Přirážej mu proti.|120",
    "Nech ho ležet se spoutanýma rukama na zádech. Olizuj ho, hoň mu, jezdi na něm – rozmazluj ho, dokud neřekne dost.",
    "Rozkaž mu, ať si sám drží vibrátor na varlatech – pokud ho sundá, přestaneš. Pak na něm tvrdě jezdi.|180",
    "Nabídni mu anál vestoje u kuchyňské linky: hodně lubrikantu, pomalý začátek a pak tempo, jaké je ti příjemné.|180",
    "Spoutej ho a doveď ho k orgasmu jen pírkem a vibrátorem. Pusu ani ruce nesmíš použít.",
    "Plácni ho bičíkem na zadek vždy, když zasténá. Pak na něm jezdi tak, aby sténal pořád.|120",
    "Kouři mu, jeden prst mu s lubrikantem vsuň do zadku a druhou rukou mu masíruj varlata.|90",
    "Nech ho, ať si vybere: rány bičíkem, nebo vibrátor na varlata, zatímco na něm jezdíš. Může si vybrat i obojí.|180",
    "Klekni si na koberec a prohni záda. Poruč mu, ať tě drží za oba boky a vezme si tě zezadu.|180",
    "Spoutej ho pouty a nech ho, ať ti řekne, jak moc chce, aby ses mu postarala o orgasmus. Pak mu ho dej.",
    "Nabídni mu anál na boku – ty ležíš, on za tebou. Vibrátor si přikládej zepředu na klitoris.|180",
    "Jezdi na něm a jednou rukou mu zakrývej pusu, aby tlumil sténání (nos nech volný).|90",
    "Lehni si na podlahu v kuchyni a poruč mu, ať tě tvrdě vezme v misionáři. Rychle, hluboko, bez přestávky.|120",
    "Zavaž mu oči a přikaž mu, ať si lehne na postel na záda. Nech ho minutu čekat a pak ho dráždi bičíkem a vibrátorem.|60",
    "Vsuň si vibrátor a sedni si na něj tak, abyste ho oba cítili.|180",
    "Odpírání: spoutej ho a pokaždé, když se blíží orgasmu, dej mu lehkou ránu bičíkem a přestaň. Až po pátém pokusu ho nech dojít.",
    "Spoutej ho k čelu postele a jezdi na něm tvrdě zády k němu, ať vidí všechno.|120",
    "Lízej mu zadek a varlata střídavě, zatímco mu honíš.|120",
    "Nabídni mu zadeček a nech ho pomalu vniknout, ale tempo a hloubku určuješ ty.|180",
    "Na gauči se přehni přes područku a poruč mu, ať tě tvrdě vezme zezadu. Pak mu dej ránu bičíkem a zase zpomalte.|180",
    "Vezmi ho do sprchy, spoutej mu ruce před tělem, vystrč na něj zadeček a nech ho, ať tě miluje. Pozor na uklouznutí.|120",
    "Přilož mu vibrátory na varlata a hráz a nech ho, ať je sevře stehny. Pak mu olizuj penis a rukama mu drž zápěstí.|180",
    "Rozkaž mu, ať ti řekne tu nejdivočejší věc, kterou by s tebou chtěl. Když to jde, udělej mu to hned.",
    "Jezdi na něm tvrdě a on smí dojít, jen když si o to řekne tvým jménem.|180",
    "Spoutej mu ruce, zavaž mu oči a dej mu na výběr: tvrdá jízda, nebo 5 minut orálu. Pak udělej to druhé taky.",
    "Lehni si na kraj postele, roztáhni nohy a poruč mu, ať si tě vezme tvrdě vestoje.|120",
    "Nabídni mu pomalý anál a po každém jeho přírazu mu řekni, jak úžasný je.|180",
    "Nejdřív ho rukou doveď k orgasmu co nejrychleji. Ten další mu dopřej co nejpomaleji.",
    "Dej mu pouta a nech ho, ať sám rozhodne, kam mu máš připnout ruce – a pak ho potěš jen pusou.",

    // Karty s cílem
    "Výslech pro něj: Spoutej mu ruce za zády a posaď ho na židli. Ptej se na jeho nejtajnější fantazie – za upřímnou odpověď dostane minutu kouření, za vytáčku ránu bičíkem na stehno. Cíl: aby prozradil aspoň tři.",
    "Dva orgasmy: Spoutej ho k posteli. Cíl: dva orgasmy za večer – první rukou, druhý jízdou na něm – a mezi nimi ho nepouštěj z pout.",
    "Prostata na rozehřátí: On leží na zádech s polštářem pod boky. Namasíruj mu hráz olejem, pak prstem s lubrikantem kruž kolem zadku a nakonec jeden prst pomalu dovnitř, ohnutý k břichu. Druhou rukou ho hlaď po penisu. Cíl: aby sám řekl, že chce víc.|300",
    "Král na deset minut: On leží a rozkazuje a ty plníš každý jeho sexuální příkaz. Cíl: splnit všechno, dokud se neudělá.|600",
    "Abeceda bičíkem: On je na všech čtyřech. Dej mu 26 lehkých ran a u každé řekne další písmeno abecedy. Když se splete, začíná od A. Cíl: dojít k Z – pak ho odměň pusou.",
    "Bez rukou a pusy: Spoutej mu ruce nad hlavou. Jeden vibrátor mu přilož na varlata, druhý na hráz a ať je sevře stehny. Ty ho jen líbáš. Cíl: dovést ho k orgasmu bez tvých rukou a pusy.",
    "Anál pro něj v zrcadle: Lehněte si na bok čelem k zrcadlu, on za tebou. Nech ho, ať do tebe s velkým množstvím lubrikantu pomalu vnikne análně, a sama si drž vibrátor na klitorisu. Cíl: dívat se mu v zrcadle do očí, dokud se neudělá.|300",
    "Odpočet pro něj: Hoň mu rukou a on smí dojít až po odpočítání od 30 do 0 nahlas. Když dojde dřív, dostane pět ran bičíkem. Cíl: aby se udělal přesně na nule.",
    "Stisknutá stehna: Lehni si na břicho s nohama u sebe a spoutej si kotníky. Nech ho, ať tě miluje zezadu. Cíl: tisknout stehna, aby to bylo co nejtěsnější, dokud se neudělá.|240",
    "Nehybný u zdi: Spoutej mu ruce za zády a postav ho ke zdi. Zatímco mu kouříš, nesmí se pohnout – za každý pohyb rána bičíkem. Cíl: aby vydržel dvě minuty.|120",
    "Dvojitý průnik pro tebe: Vsuň si vibrátor do vagíny a nech ho vniknout do zadečku (nebo naopak – vibrátor do zadečku jen s rozšířenou základnou). Cíl: pomalu s lubrikantem – ty řekneš, kdy smí zrychlit.|240",
    "Tvrdě a s plácnutím: Opři se přes opěradlo gauče a přikaž mu, ať tě chytí za boky a přiráží tvrdě. Každých 30 vteřin tě plácne. Cíl: tři minuty bez zpomalení.|180",
    "Po orgasmu dál: Po jeho orgasmu ho nepouštěj – velmi jemně pokračuj rukou nebo pusou a drž mu ruce. Cíl: vydržet 30 vteřin jeho citlivosti – stop slovo platí.|30",
    "Prostata u postele: On klečí na zemi, hrudníkem leží na posteli a ruce má spoutané před sebou. Zezadu mu masíruj prostatu prstem a zespodu mu hoň. Cíl: udržet oba pohyby ve stejném rytmu.|180",
    "Bolest a slast pro něj: Přehni ho přes koleno a plácej ho bičíkem. Po každé ráně řekne číslo od 1 do 10. Cíl: držet se mezi 5 a 7, pak ho otočit a kouřit mu.",
    "Nikdy neví, co přijde: Spoutej ho a zavaž mu oči. Každých 20 vteřin něco jiného – rána bičíkem, pírko, vibrátor, pusa, tvůj klín. Cíl: pět minut překvapení.|300",
    "Prosím: Jezdi na něm a zastav se. Pokračuj jen tehdy, když ti přesně řekne, co chce, a začne slovy „prosím, udělej mi…“. Cíl: aby to řekl aspoň pětkrát.",
    "Anál na stole pro něj: Lehni si na záda na kraj jídelního stolu s ručníkem pod boky a nohama nahoře, on stojí. Hodně lubrikantu, pomalu. Cíl: rukou na jeho břiše řídit tempo, druhou si hladit klitoris.|240",
    "Připoutaný k židli: Posaď ho na židli s rukama spoutanýma za opěradlem, sedni si na něj obkročmo a jezdi. Cíl: on se nesmí hýbat, ty rozhoduješ o všem, dokud se neudělá.",
    "Trojitá péče: Přilož mu vibrátor na varlata, prstem mu masíruj prostatu a pusou mu kouři. Cíl: udržet všechny tři najednou, dokud se neudělá.",
    "Za vlasy: Chyť ho pevně, ale ne bolestivě za vlasy, přitáhni si jeho pusu ke krku a tvrdě na něm jezdi. Cíl: šeptat mu do ucha, jak je dokonalý.|180",
    "Rány a hlazení: Předkloň ho přes linku. Tři rány bičíkem na zadek, pak ho třikrát pevně pohlaď zezadu mezi nohama, pak znovu rány. Cíl: deset kol – pak ho otoč a dokonči pusou.",
    "Rozepjatý: Spoutej mu zápěstí k nohám postele nebo nad hlavou a roztáhni mu nohy. Cíl: kouřit mu k orgasmu, zatímco se nemůže bránit.",
    "Prst při jízdě: Jezdi na něm a sáhni si za sebe – namazaný prst mu vsuň do zadku. Cíl: jezdit tak, aby se prst hýbal s tebou, dokud se neudělá.|180",
    "Pět přerušení pro něj: Hoň mu k orgasmu a pokaždé, když řekne „už budu“, přestaň. Když vydrží pět přerušení bez prošení, dostane orgasmus, jaký si řekne. Cíl: dotáhnout hru do konce.",
    "Klečí s rukama za hlavou: Ať klečí nahý na koberci s rukama za hlavou. Obcházej ho s bičíkem a dotýkej se ho. Cíl: pak si před něj lehni a přikaž mu, ať si tě vezme – ruce smí sundat až na tvůj povel.|240",
    "Prostata s vibrátorem: Prstem mu masíruj prostatu a druhou rukou mu hoň. Vibrátor na hrázi ať si drží sám. Cíl: orgasmus, jaký ještě nezažil.",
    "Tvrdá jízda a polibek: Jezdi na něm dvaceti tvrdými pohyby, pak se na 10 vteřin zastav a polib ho. Cíl: deset kol – v posledním nepřestávej.|300",
    "Jeho spoutané ruce na tobě: Spoutej mu ruce před tělem a sedni si na něj tak, aby měl ruce na tvém klíně. Jezdi na něm a přikaž mu, ať tě hladí. Cíl: dojít oba – ty první.|240",
    "Sprcha a spoutaný: Ve sprše mu spoutej ruce před tělem, zvedni mu je nad hlavu a drž je. Klekni si na ručník a kouři mu. Cíl: dvě minuty – a pozor na uklouznutí.|120",
    "Fáze na „ano“: Spoutej ho, zavaž mu oči a polož ho na záda. Nejdřív mu kouři, pak mu masíruj prostatu a pak si na něj sedni. Cíl: před každou další fází musí říct „ano“.",
    "Povel pro něj s trestem: Hoň mu a smí dojít jen na „teď“. Když dojde dřív, dostane pět ran bičíkem. Cíl: aby se udělal přesně na povel.",
    "Pod stolem pro něj: On sedí na židli u stolu s rukama spoutanýma za opěradlem, ty jsi pod stolem a kouříš mu. Cíl: zastavit tě může jen stop slovem.",
    "Trest a odměna: Jeho hruď a bradavky lehce plácej bičíkem, penis odměňuj pusou. Střídej po 20 vteřinách. Cíl: dokud se neudělá.|240",
    "Anál vestoje: Opři se o zeď a nabídni mu zadeček. Použijte hodně lubrikantu a ať začne jen špičkou. Cíl: ty řídíš hloubku rukou na jeho boku.|180",
    "Přetahovaná: Minutu se ho snaž povalit na postel, on se hravě brání. Když ho povalíš, spoutej ho a sedni si na něj. Cíl: skončit s ním v sobě.",
    "Tři vrcholy: Spoutej ho a během patnácti minut ho třikrát doveď těsně k vrcholu – rukou, pusou a jízdou. Cíl: nechat ho dojít až napotřetí.|900",
    "Spoutaný na gauči: Spoutej mu ruce za zády, posaď ho na gauč a roztáhni mu nohy. Cíl: kouřit mu, dokud nebude prosit o pauzu – a pak ještě 30 vteřin.",
    "Vedený do ložnice: Chyť ho za pouta a veď ho nahého bytem. Zastav se u zdi, u stolu a u dveří a pokaždé mu minutu kouři nebo hoň. Cíl: dojít do postele a tam ho dokončit.",
    "Horký zadek: Dej mu třicet plácnutí dlaní na zadek, pak ho otoč a pomalu mu olizuj penis. Cíl: orgasmus do tří minut.",
    "Sténání za trest: Jezdi na něm tvrdě a za každé hlasité zasténání dostane plácnutí. Cíl: aby sténal tak, že přestaneš počítat.|180",
    "Plná pro něj: Nech ho, ať do tebe vnikne análně zezadu, jeden vibrátor si drž na klitorisu a druhý si vsuň do vagíny. Cíl: pomalu, dokud necítíš plnost – pak mu řekni, ať zrychlí.|240",
    "Výměna velení: Každou minutu si prohoďte, kdo velí a kdo poslouchá. Příkazy musí být sexuální a splnitelné hned. Cíl: šest minut – kdo dá odvážnější příkaz, dojde jako první.|360",
    "Opřený o stůl: Předkloň ho přes jídelní stůl s rukama spoutanýma a nataženýma. Zezadu mu hoň a po každých dvaceti pohybech ho plácni bičíkem přes zadek. Cíl: aby se udělal opřený o stůl.|180",
    "Druhé kolo: Doveď ho k orgasmu co nejrychleji, nech ho chvíli vydechnout a pak začni znovu pusou. Cíl: druhý orgasmus do dvaceti minut.",
    "Tvrdá lžička pro něj: Spoutej mu ruce za zády, lehni si před něj zády k němu a nech ho, ať tě miluje zezadu. Tlač se proti němu tvrdě. Cíl: tři minuty – tvrdost určuješ ty.|180",
    "Rána a pohlazení: Přehni ho přes koleno a po každé ráně bičíkem ho jednou pomalu pohlaď zespodu mezi nohama. Cíl: patnáct ran a pak ho rukou dovést k orgasmu.",
    "Spoutané kotníky nahoře: Lehni si na záda, spoutej si kotníky a zvedni nohy na jeho rameno. Cíl: těsné a hluboké – řekni mu, kdyby to bylo moc.|180",
    "Jeho fantazie: Nech ho říct jednu hardcore fantazii, kterou jste nezkoušeli a dá se udělat hned. Cíl: splnit ji.",
    "Spoutaný pod tebou: Spoutej mu ruce nad hlavou a sedni si mu na obličej. Cíl: nechat se lízat, dokud nedojdeš, pak se posunout níž a jezdit na něm.",
    "Rychle a silně: Hoň mu tvrdě a rychle s lubrikantem a druhou rukou mu drž zápěstí. Cíl: rychlý silný orgasmus – stop slovo platí.",
    "Anální jízda: Sedni si na něj a pomalu si ho zaveď do zadečku. Vibrátor si drž na klitorisu. Cíl: máš úplnou kontrolu nad hloubkou i tempem.|240",
    "Písmeno na jeho zadku: Nakresli mu lehkými ranami bičíku na zadek písmeno. Cíl: když uhodne, odměna pusou, když ne, kreslíš znovu.",
    "Deset minut vlády: Deset minut rozhoduješ o všem – poloha, tempo, kdy smí dojít, kam se dívá. On říká jen „ano“. Cíl: dát mu nejsilnější orgasmus večera.|600",
    "Péče po všem: Po nejtvrdším úkolu ho odpoutej, promasíruj mu zápěstí a zadek, přikryj ho a dej mu napít. Pak ho pomalu hlaď, dokud se mu znovu nepostaví. Cíl: vystřídat tvrdost něhou.",
    "Velké finále: Zkombinuj pouta, bičík, oba vibrátory, prostatu a svůj klín. Cíl: deset minut bez chvilky nudy a na konci společný orgasmus.|600",
  ],
});
