// Kategorie 5 – Hardcore (dávka b)
// Témata: pouta a svázání, úplná deprivace, kontrolní pozice, rozkazy a poslušnost.
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 5,

  male: [
    "Jen stop slovo: Spoutej jí ruce k čelu postele a mrdej ji, jak chceš. Cíl: pět minut, při kterých smí říct jediné slovo – a to je stop.|300|pouta_postel",
    "Svázaná a anál: Sváž jí zápěstí kravatou nad hlavou, uzel volně, a vnikni do ní análně s hodně lubrikantu. Cíl: tempo i hloubku určuje jen ona.|300|pouta_postel",
    "Rozepnutá a svázaná: Spoutej ji, zavaž oči, nasaď sluchátka a pak ji doveď na hranu a nech ji tam. Cíl: pět minut na hraně bez jediného orgasmu.|300|pouta_postel",
    "Klečí, dokud nedovolíš: Spoutej jí ruce za zády a s hodně lubrikantu do ní zezadu vnikni análně. Cíl: tempo i hloubku určuje jen ona.|300|klek_pouta",
    "Svázaná vkleče: Sváž jí ruce kravatou za zády a mrdej ji zezadu, když klečí. Cíl: pět minut a na stop ji hned rozvázat.|300|zezadu",
    "Hádej čím: Spoutej ji, zavaž jí oči a střídej ruce, pírko, led a vibrátor. Cíl: desetkrát ji dovést na hranu a ani jednou ji nenechat dojít.|300|pouta_postel",
    "Každá ruka jinam: Přivaž jí každou ruku k jinému rohu postele a lízej ji až na hranu a zpátky. Cíl: pět kol a na stop ji hned rozvázat.|300|pouta_postel",
    "Kotníky svázané, kolena od sebe: Sváž jí kotníky, roztahuj jí kolena a mrdej ji do kundičky. Cíl: pět minut a kolena nepustit ani jednou.|300|nohy_ramena",
    "Pouta a příkaz: Spoutej ji, prsti ji a zakaž jí dojít. Když se udělá bez dovolení, končíte. Cíl: pět minut a ona to nesmí porušit.|300|pouta_postel",
    "Minuta a pak anál: Spoutej ji, nech ji minutu čekat a pak do ní vnikni análně s hodně lubrikantu. Cíl: tempo i hloubku určuje jen ona.|300|pouta_postel",
    "Ruce u jejích stehen: Sváž jí ruce volně ke stehnům a dráždi ji vibrátorem až na hranu a zpátky. Cíl: pět kol a na stop ji hned uvolnit.|300|pouta_postel",
    "Nevidí, neslyší: Zavaž jí oči, nasaď jí sluchátka a pak do ní vnikni análně s hodně lubrikantu. Cíl: tempo i hloubku určuje jen ona.|300|deprivace",
    "Úplná tma: Zavázané oči, sluchátka, spoutané ruce a vibrátor na klitorisu. Cíl: třikrát ji dovést na hranu a teprve počtvrté ji nechat dojít.|300|deprivace",
    "Led a vibrace: Zavaž jí oči a střídej kostku ledu a vibrátor, ale vždycky přestaň těsně před koncem. Cíl: pět zastavení a pak ji nechat dojít.|300|deprivace",
    "Ruka, nebo pomůcka: Zavaž jí oči a dráždi ji střídavě rukou a vibrátorem. Cíl: dovést ji na hranu pětkrát a nenechat ji přes ni ani jednou.|300|deprivace",
    "Čekání poslepu: Zavaž jí oči, dráždi ji a přestaň vždycky, když zrychlí dech. Cíl: deset zastavení, než ji necháš dojít.|300|deprivace",
    "Ruce za hlavou vkleče: Poruč jí klečet s rukama za hlavou a vnikni do ní análně s hodně lubrikantu. Cíl: hloubku i tempo určuje jen ona.|300|klek_ruce_hlava",
    "Klek a povel: Klečí s rukama za hlavou a ty ji dráždíš, ale udělat se smí, až když dovolíš. Cíl: pět minut a povolit jí to až na konci.|300|klek_ruce_hlava",
    "Vkleče a bez rukou: Poruč jí, ať klečí s rukama za hlavou, a mrdej ji zezadu. Cíl: pět minut a ruce se nesmí hnout.|300|zezadu_vzpr",
    "Čeká na tvoje slovo: Doveď ji rukou až těsně před konec a tam ji nech čekat. Cíl: čtyři minuty na hraně, než jí dovolíš dojít.|240|klek_pouta",
    "Nehne se ani o kousek: Poruč jí předklonit se přes opěradlo a vnikni do ní análně s hodně lubrikantu. Cíl: tempo i hloubku určuje jen ona.|300|predklon",
    "Tři povolená slova: Dráždi ji a smí říct jen „ano“, „ještě“, nebo stop slovo. Udělat se smí, až když řekneš. Cíl: ani jedno slovo navíc.|300|klek_pouta",
    "Tři rozkazy: Dáš jí tři rozkazy za sebou a mezi nimi ji pokaždé dovedeš na hranu. Cíl: žádné zaváhání a žádný orgasmus navíc.|300|klek_pouta",
    "Celou větou: Ať si sama celou větou řekne, jestli ji máš prstit, lízat, nebo mrdat. Cíl: nedat jí nic, dokud to nevysloví.|300|klek_ruce_hlava",
    "Za pohyb trest: Oznam jí, že se nesmí hnout, ať děláš cokoli. Za každý pohyb rána bičíkem. Cíl: pět minut a nejvýš tři tresty.|300|pouta_postel",
    "Nesmí zavřít oči: Dráždi ji a poruč jí dívat se na tebe. Jakmile zavře oči, přestáváš na deset vteřin. Cíl: pět minut a nenechat ji dojít.|300|kontrola_vsede!",
    "Nevysmekne se: Drž jí obě ruce nad hlavou a mrdej ji. Cíl: pět minut a ani jednou se nesmí vysmeknout.|300|kontrola_vsede!",
    "Určuješ všechno ty: Vnikni do ní análně s hodně lubrikantu a drž jí zápěstí. Cíl: hloubku i tempo určuje jen ona, do zbytku ti nemluví.|300|kontrola_vsede!",
    "Plná kontrola: Drž jí ruce nad hlavou, mrdej ji vsedě a ona nesmí ani jednou převzít vedení. Cíl: pět minut a nepustit ji.|300|kontrola_vsede!",
    "Připomeneš jen pohledem: Nech ji ležet s rukama nad hlavou, dráždi ji a přestaň, kdykoli je blízko. Cíl: pět zastavení bez jediného slova.|300|pouta_postel",
    "Dlouhé pauzy: Spoutej ji a mezi doteky dělej co nejdelší pauzy. Cíl: deset doteků, po každém dvacet vteřin nic, a dojít smí až po desátém.|300|pouta_postel",
    "Svázaná mezi tvýma nohama: Sváž jí ruce a nech ji klečet mezi tvýma nohama. Cíl: pět minut ústy a ty se nesmíš udělat dřív.|300|oral_ona_klek",
    "Dívá se, jak se svlékáš: Spoutej ji, posaď na židli a svlékej se před ní. Pak do ní vnikni análně s hodně lubrikantu. Cíl: tempo určuje ona.|300|zidle_celem",
    "Ruce u kotníků na boku: Sváž jí ruce volně ke kotníkům a na boku ji mrdej zezadu. Cíl: pět minut a na stop ji hned rozvázat.|300|dvojita_bok",
    "Klečící a spoutaná: Ruce za zády, klečí před tebou a ty stojíš. Minutu nedělej nic, pak ať ti kouří. Cíl: nechat ji čekat celou minutu.|300|klek_pouta",
    "Kolik ještě vydržíš: Spoutej ji, dráždi ji a každou minutu se zeptej, kolik toho ještě vydrží. Cíl: dotáhnout to přesně k číslu, které řekne naposled.|300|pouta_postel",
    "Vybere si, dostane jiné: Sváž jí ruce a nech ji vybrat, jestli ji budeš lízat, prstit, nebo mrdat. Cíl: udělat jinou z těch tří – a dobře.|300|pouta_postel",
    "Počítá tvoje přírazy: Poruč jí, ať nahlas počítá každý tvůj příraz. Cíl: dojít k padesáti – jakmile se splete, začínáte od nuly.|300|zezadu",
    "Jen kývnutí: Spoutanou ji lízej a zakaž jí mluvit – smí jen kývnout nebo zavrtět hlavou. Cíl: pět minut a domluvit se jen otázkami.|300|pouta_postel",
    "Zaváže si je sama: Poruč jí, ať si sama zaváže oči a čeká, a pak ji beze slova prsti. Cíl: nechat ji čekat celou minutu, než se jí dotkneš.|240|deprivace",
    "Rituál: Klečíc před tebou ti musí nahlas říct, že ti chce kouřit. Teprve pak smí. Cíl: nechat ji to celé vyslovit.|300|oral_ona_klek",
    "Spoutej ji a pak jí velmi pomalu svlékej zbytek oblečení.|300|pouta_postel",
    "Deset koleček, deset plácnutí: Sváž jí ruce, nech ji stát uprostřed pokoje a obcházej ji, přitom ji pokaždé plácni po prdeli. Cíl: deset koleček a deset plácnutí.|240|klek_pouta",
    "Klečí a kouří: Spoutej jí ruce za zády, nech ji kleknout před tebe a ať ti kouří. Cíl: pět minut a ruce jí nerozvázat.|300|oral_ona_klek",
    "Ruce nad hlavou u zdi: Sváž jí ruce kravatou nad hlavu ke zdi a mrdej ji vestoje. Cíl: pět minut a na stop ji hned rozvázat.|300|zed",
    "Sluchátka a jazyk: Spoutej ji, nasaď jí sluchátka, ať tě neslyší, a pak ji beze slova lízej. Cíl: pět minut a ani jednou ji nevarovat.|300|deprivace",
    "Ticho a čekání: Spoutaná se zavázanýma očima čeká tři minuty úplně sama. Cíl: nepromluvit ani jednou.|180|deprivace",
    "Šeptem do ucha: Spoutej ji, prsti jí kundičku a celou dobu jí šeptej do ucha, co s ní uděláš dál. Cíl: pět minut a ani jednou se neodmlčet.|300|pouta_postel",
    "Polohu vybere ona: Sváž jí ruce kravatou, nech ji vybrat polohu a v té ji mrdej. Cíl: pět minut a polohu ani jednou nezměnit.|300|pouta_postel",
    "Spoutej ji a doveď ji k vrcholu jen vibrátorem.|300|pouta_postel",
    "Třikrát za sebou: Spoutej ji a střídej jazyk, prsty a vibrátor. Cíl: tři orgasmy za sebou a mezi nimi žádná pauza delší než minuta.|300|pouta_postel",
    "Sváž jí ruce, zavaž oči a střídej pírko a bičík.|300|pouta_postel",
    "Sedíš na ní: Spoutej ji, sedni si na ni, drž ji za boky a mrdej ji vsedě. Cíl: pět minut, při kterých se ani jednou nepohne sama.|300|kontrola_vsede!",
    "Pouta a pomalost: Je spoutaná a ty do ní přirážíš tak pomalu, jak to jde. Cíl: pět minut a ani jednou nezrychlit.|300|pouta_postel",
    "Svázaná na boku: Sváž jí ruce kravatou před tělem a mrdej ji na boku. Cíl: pět minut a na stop ji hned rozvázat.|300|dvojita_bok",
    "O každou věc zvlášť: Spoutej ji a ať si o každou další věc poprosí zvlášť – o prst, o jazyk, o tebe. Cíl: tři prosby a každou splnit hned.|300|pouta_postel",
    "Poruč jí, ať se otočí a nedívá se, co chystáš.|240|zezadu",
    "Řekni jí, ať nesmí dojít bez tvého svolení. A dlouho ho nedávej.|300|pouta_postel",
    "Poruč jí, ať si klekne, a ty jí jen hlaď vlasy. Nic víc.|240|oral_ona_klek",
    "Rozkaz a odměna: Za každý bezchybně splněný rozkaz dostane jednu věc, kterou má ráda. Cíl: tři odměny.|300|klek_pouta",
    "Sváž jí ruce a přitom jí drž bradu, ať se ti dívá do očí.|300|kontrola_vsede!",
    "Spoutaná na břiše: Spoutej ji, nech ji ležet na břiše a pak ji tvrdě mrdej zezadu. Cíl: pět minut a ruce jí nerozvázat.|300|na_brise",
    "Hlava dole: Sváž jí ruce, nech ji klečet na všech čtyřech s hlavou dole a mrdej ji zezadu. Cíl: pět minut a hlavu nezvednout.|300|zezadu",
    "Rozhoduje jen o tempu: Spoutej ji, lízej ji a nech ji rozhodnout jen o jedné věci – o tempu. Cíl: pět minut a do ničeho jiného jí nedat mluvit.|300|pouta_postel",
    "Poslouchá na slovo: Poruč jí, ať tě poslouchá na slovo, postav ji na všechny čtyři a mrdej ji zezadu. Cíl: tři rozkazy a ani jedno zaváhání.|300|zezadu",
    "Přesně tak: Popiš jí přesně, jak má ležet, a oprav každou odchylku. Cíl: ať to sedí na centimetr.|300|pouta_postel",
    "Minuta čekání: Spoutej ji a nech ji celou minutu čekat, než ji začneš lízat. Cíl: minuta čekání a pak tři minuty bez přestávky.|240|pouta_postel",
    "Sváž jí ruce nad hlavou a olizuj jí kundičku tak dlouho, dokud neprosí.|300|pouta_postel",
    "Spoutej ji a pak ji polib, jako by se nic nedělo.|240|pouta_postel",
    "Volná ruka: Sváž jí jednu ruku, druhou nech volnou a ať se tou volnou hladí, zatímco ji mrdáš. Cíl: pět minut a ruku nesmí zastavit.|300|pouta_postel",
    "Dneska rozhoduješ ty: Poruč jí kleknout si, řekni jí, že dneska rozhoduješ ty, a ať ti kouří. Cíl: pět minut a nesmí se zvednout.|300|klek_pouta",
    "Jediné slovo: Domluvte si jedno slovo, po kterém okamžitě přestaneš. Pak jdi až na hranu. Cíl: nikdy to slovo neslyšet.|300|pouta_postel",
    "Spoutej ji a mezi tím jí přejížděj ledem po celém těle.|300|pouta_postel",
    "Zády ke zdi: Sváž jí ruce, postav ji ke zdi zády a mrdej ji vestoje zezadu. Cíl: čtyři minuty a ani jednou ji neotočit.|240|zed",
    "Spoutej ji a nech ji ležet nahou, zatímco se jen díváš.|240|pouta_postel",
    "Poruč jí, ať ti řekne nahlas tři věci, které dneska udělá.|240|klek_pouta",
    "Sváž jí ruce a doveď ji na hranu pětkrát za sebou.|300|pouta_postel",
    "Říká, co cítí: Spoutej ji, prsti ji a nech ji celou dobu nahlas říkat, co cítí. Cíl: pět minut a ani jednou se neodmlčí.|300|pouta_postel",
    "Poslední rozkaz: Ukaž jí beze slova, ať si klekne a kouří ti. Cíl: čtyři minuty a nemuset nic vysvětlovat.|240|klek_pouta",
    "Sváž jí ruce a pak jí sundej pouta, ale ona se pořád nesmí hýbat.|300|pouta_postel",
    "Spoutej ji a pak ji obejmi. Kontrast, který funguje.|180|pouta_postel",
    "Na konec jí rozvaž ruce a promasíruj jí zápěstí.|120|pouta_postel",
  ],

  female: [
    "Jediné povolené slovo: Spoutej mu ruce k čelu postele a hoň mu péro až na hranu a zpátky. Cíl: pět kol a udělat se smí až na pátém.|300|pouta_postel!",
    "Prozkoumat celého: Sváž mu zápěstí kravatou nad hlavou a pomalu ho prozkoumej celého, ale přestaň vždycky, když se napne. Cíl: pět zastavení.|300|pouta_postel!",
    "Rozepnutý a svázaný: Spoutej ho, zavaž oči, nasaď sluchátka a pak ho doveď rukou na hranu a nech ho tam. Cíl: pět minut na hraně.|300|pouta_postel!",
    "Klečí, dokud nedovolíš: Spoutej mu ruce za zády, nech ho klečet a hoň mu. Cíl: nedovolit mu vstát dřív než po pěti minutách.|300|klek_pouta!",
    "Svázaný vkleče: Sváž mu ruce za zády, hoň mu a pokaždé, když je blízko, pusť ho. Cíl: pět zastavení a na stop ho hned rozvázat.|300|zezadu!",
    "Hádej, co to je: Spoutej ho, zavaž mu oči a střídej ruce, pírko, led a vibrátor. Cíl: desetkrát ho dovést na hranu a ani jednou ho nepustit dál.|300|pouta_postel!",
    "Ruce do rohů: Přivaž mu každou ruku k jinému rohu postele a kuř mu až na hranu a zpátky. Cíl: pět kol a na stop ho hned rozvázat.|300|pouta_postel!",
    "Kotníky u sebe: Sváž mu kotníky, roztahuj mu kolena a kuř mu, ale zastav se pokaždé, když se napne. Cíl: pět zastavení a kolena nepustit.|300|oral_on_vleze",
    "Pouta a příkaz: Spoutej ho, hoň mu a zakaž mu se udělat. Když to poruší, končíte. Cíl: pět minut a on to nesmí porušit.|300|pouta_postel!",
    "Minuta v poutech: Spoutej ho, nech ho minutu čekat a pak mu hoň až na hranu. Cíl: tři taková kola, než ho necháš dojít.|300|pouta_postel!",
    "Ruce u jeho stehen: Sváž mu ruce volně ke stehnům a dráždi ho vibrátorem až na hranu a zpátky. Cíl: pět kol a na stop ho hned uvolnit.|300|pouta_postel!",
    "Ani nevidí, ani neslyší: Zavaž mu oči, nasaď sluchátka a jezdi na něm, ale nesmí se udělat, dokud nedovolíš. Cíl: pět minut.|300|deprivace!",
    "Úplná tma: Zavázané oči, sluchátka, spoutané ruce a tvoje ústa na jeho péru. Cíl: třikrát ho dovést na hranu a teprve počtvrté ho nechat dojít.|300|deprivace!",
    "Mráz a vibrace: Zavaž mu oči a střídej kostku ledu a vibrátor, ale vždycky přestaň těsně před koncem. Cíl: pět zastavení a pak ho nechat dojít.|300|deprivace!",
    "Ruka, nebo věc: Zavaž mu oči a dráždi ho střídavě rukou a vibrátorem. Cíl: dovést ho na hranu pětkrát a nenechat ho přes ni ani jednou.|300|deprivace!",
    "Ať si počká: Zavaž mu oči, hoň mu a přestaň vždycky, když zrychlí dech. Cíl: deset zastavení, než ho necháš dojít.|300|deprivace!",
    "Na kolenou s rukama za hlavou: Poruč mu klečet s rukama za hlavou a kuř mu, ale udělat se smí, až když dovolíš. Cíl: pět minut.|300|klek_ruce_hlava!",
    "Klek a jeho povel: Klečí s rukama za hlavou, ty ho honíš a on se nesmí udělat bez tvého slova. Cíl: pět minut a povolit až na konci.|300|klek_ruce_hlava!",
    "Vkleče a bez rukou: Poruč mu klečet s rukama za hlavou a hoň mu zezadu až na hranu. Cíl: pět kol a ruce se nesmí hnout.|300|zezadu_vzpr!",
    "Čeká na tvoje svolení: Nech ho klečet a čekat, ty se zatím jen díváš. Cíl: čtyři minuty ticha, než mu dovolíš vstát.|240|klek_pouta!",
    "Ani se nehne: Poruč mu předklonit se přes opěradlo a hoň mu, ale zastav se pokaždé, když se pohne. Cíl: nejvýš dva pohyby za pět minut.|300|predklon!",
    "Tři slova pro něj: Kuř mu a smí říct jen „ano“, „ještě“, nebo stop slovo. Udělat se smí, až když řekneš. Cíl: ani jedno slovo navíc.|300|klek_pouta!",
    "Tři rozkazy pro něj: Dáš mu tři rozkazy za sebou a mezi nimi ho pokaždé dovedeš na hranu. Cíl: žádné zaváhání a žádný orgasmus navíc.|300|klek_pouta!",
    "Musí to říct celou větou: Ať sám celou větou řekne, jestli mu máš honit, nebo kouřit. Cíl: nedat mu nic, dokud to nevysloví.|300|klek_ruce_hlava",
    "Pohyb stojí trest: Oznam mu, že se nesmí hnout, ať děláš cokoli. Za každý pohyb rána bičíkem. Cíl: pět minut a nejvýš tři tresty.|300|pouta_postel!",
    "Oči na tobě: Hoň mu a poruč mu dívat se na tebe. Jakmile zavře oči, přestáváš na deset vteřin. Cíl: pět minut a nenechat ho dojít.|300|kontrola_vsede",
    "Drž ho nad hlavou: Drž mu obě ruce nad hlavou a nasaď se na něj. Cíl: pět minut a ani jednou se nesmí vysmeknout.|300|kontrola_vsede",
    "Určuješ všechno sama: Nasaď se na něj, drž mu zápěstí a zvedni se vždycky, když je blízko. Cíl: tři taková kola, než ho necháš dojít.|300|kontrola_vsede",
    "Plná kontrola: Držíš mu ruce nad hlavou, jezdíš na něm a on nesmí ani jednou převzít vedení. Cíl: pět minut a nepustit ho.|300|kontrola_vsede",
    "Připomínka pohledem: Nech ho ležet s rukama nad hlavou, hoň mu a přestaň, kdykoli je blízko. Cíl: pět zastavení bez jediného slova.|300|pouta_postel!",
    "Pauzy mezi doteky: Spoutej ho a mezi doteky dělej co nejdelší pauzy. Cíl: deset doteků, po každém dvacet vteřin nic, a dojít smí až po desátém.|300|pouta_postel!",
    "Svázaný před tebou: Sváž mu ruce a nech ho kleknout si před tebe. Cíl: pět minut a musí si vystačit jen ústy.|300|oral_ona_klek",
    "Dívá se na svlékání: Spoutej ho, posaď ho na židli a pomalu se před ním svlékej. Cíl: nesáhnout na něj, dokud nejsi úplně nahá.|300|zidle_celem",
    "Jeho ruce u kotníků: Sváž mu ruce volně ke kotníkům, nech ho ležet na boku a hoň mu péro. Cíl: pět minut a na stop ho hned rozvázat.|300|dvojita_bok!",
    "Klečící a spoutaný: Ruce za zády, klečí před tebou a ty stojíš. Minutu nedělej nic, pak mu hoň. Cíl: nechat ho čekat celou minutu.|300|klek_pouta",
    "Kolik ještě vydrží: Spoutej ho, dráždi ho a každou minutu se zeptej, kolik toho ještě vydrží. Cíl: dotáhnout to přesně k číslu, které řekne naposled.|300|pouta_postel!",
    "Vybere si, dostane něco jiného: Sváž mu ruce a nech ho vybrat, jestli mu budeš kouřit, honit, nebo se na něj nasadíš. Cíl: udělat jinou z těch tří.|300|pouta_postel!",
    "Počítá tvoje pohyby: Poruč mu, ať nahlas počítá každý tvůj pohyb. Cíl: dojít k padesáti – jakmile se splete, začínáte od nuly.|300|ona_nahore",
    "Jen kývne: Spoutanému mu kuř a zakaž mu mluvit – smí jen kývnout nebo zavrtět hlavou. Cíl: pět minut a domluvit se jen otázkami.|300|pouta_postel!",
    "Zaváže si je sám: Poruč mu, ať si sám zaváže oči a čeká na posteli, a pak mu beze slova hoň. Cíl: nechat ho čekat celou minutu, než se ho dotkneš.|240|deprivace!",
    "Rituál: Klekni si před něj a nahlas mu řekni, že mu chceš kouřit. Teprve pak začni. Cíl: nechat to celé vyslovit a pak nepřestat.|300|oral_ona_klek",
    "Spoutej ho a pak mu velmi pomalu svlékej zbytek oblečení.|300|pouta_postel!",
    "Deset koleček, deset doteků: Sváž mu ruce, nech ho stát uprostřed pokoje a obcházej ho, přitom mu pokaždé sáhni na péro. Cíl: deset koleček a deset doteků.|240|klek_pouta!",
    "Klečí spoutaný: Spoutej mu ruce za zády, nech ho klečet před sebou a hoň mu. Cíl: pět minut a ruce mu nerozvázat.|300|oral_ona_klek",
    "Jeho ruce nad hlavou: Sváž mu ruce kravatou nad hlavu ke zdi a hoň mu péro vestoje. Cíl: pět minut a na stop ho hned rozvázat.|300|zed",
    "Sluchátka a ústa: Spoutej ho, nasaď mu sluchátka, ať tě neslyší, a pak mu beze slova kuř. Cíl: pět minut a ani jednou ho nevarovat.|300|deprivace!",
    "Ticho a čekání: Spoutaný se zavázanýma očima čeká tři minuty úplně sám. Cíl: nepromluvit ani jednou.|180|deprivace!",
    "Šeptem do jeho ucha: Spoutej ho, hoň mu a celou dobu mu šeptej do ucha, co s ním uděláš dál. Cíl: pět minut a ani jednou se neodmlčet.|300|pouta_postel!",
    "Polohu vybere on: Sváž mu ruce kravatou, nech ho vybrat polohu a v té se na něj nasaď. Cíl: pět minut a polohu ani jednou nezměnit.|300|pouta_postel!",
    "Jen rukou až do konce: Spoutej ho a doveď ho na konec výhradně rukou. Cíl: nepoužít ústa ani nic jiného.|300|pouta_postel!",
    "Spoutej ho a nech ho dojít, pak pokračuj ještě chvíli.|300|pouta_postel!",
    "Sváž mu ruce, zavaž oči a střídej pírko a bičík.|300|pouta_postel!",
    "Sedíš na něm: Spoutej ho, nasaď se na něj a drž ho za ramena. Cíl: pět minut, při kterých se ani jednou nepohne sám.|300|kontrola_vsede",
    "Pouta a pomalost: Je spoutaný a ty na něm jezdíš tak pomalu, jak to jde. Cíl: pět minut a ani jednou nezrychlit.|300|pouta_postel!",
    "Svázaný na boku: Sváž mu ruce kravatou před tělem a mrdej se s ním na boku. Cíl: pět minut a na stop ho hned rozvázat.|300|dvojita_bok!",
    "O každou věc zvlášť pro něj: Spoutej ho a ať si o každou další věc poprosí zvlášť – o ruku, o ústa, o tebe. Cíl: tři prosby a každou splnit hned.|300|pouta_postel!",
    "Poruč mu, ať se otočí a nedívá se, co chystáš.|240|zezadu!",
    "Bez tvého svolení ne: Hoň mu péro a řekni mu, že se nesmí udělat bez tvého svolení. A dlouho ho nedávej. Cíl: třikrát ho dovést až na hranu.|300|pouta_postel!",
    "Jen vlasy a nic víc: Poruč mu, ať si klekne, a kuř mu, přitom mu jen prohrábni vlasy. Nic víc. Cíl: čtyři minuty a nesáhnout na nic jiného.|240|oral_ona_klek",
    "Rozkaz a odměna: Za každý bezchybně splněný rozkaz dostane jednu věc, kterou má rád. Cíl: tři odměny.|300|klek_pouta!",
    "Sváž mu ruce a přitom mu drž bradu, ať se ti dívá do očí.|300|kontrola_vsede",
    "Spoutaný na břiše: Spoutej ho, nech ho ležet na břiše a hlaď mu záda a prdel, dokud nezačne prosit. Cíl: pět minut a ani jednou nezastavit.|300|na_brise!",
    "Hlava dole u něj: Sváž mu ruce, nech ho klečet na všech čtyřech s hlavou dole a hoň mu péro zezadu. Cíl: pět minut a hlavu nesmí zvednout.|300|zezadu!",
    "Rozhoduje jen o tempu on: Spoutej ho, kuř mu a nech ho rozhodnout jen o jedné věci – o tempu. Cíl: pět minut a do ničeho jiného mu nedat mluvit.|300|pouta_postel!",
    "Poslouchá tě na slovo: Poruč mu, ať tě poslouchá na slovo, nasaď se na něj a buď hodně konkrétní. Cíl: tři rozkazy a ani jedno zaváhání.|300|ona_nahore",
    "Přesně tak: Popiš mu přesně, jak má ležet, a oprav každou odchylku. Cíl: ať to sedí na centimetr.|300|pouta_postel!",
    "Minuta čekání pro něj: Spoutej ho a nech ho celou minutu čekat, než mu začneš kouřit. Cíl: minuta čekání a pak tři minuty bez přestávky.|240|pouta_postel!",
    "Sváž mu ruce nad hlavou a kouři mu tak dlouho, dokud neprosí.|300|pouta_postel!",
    "Spoutej ho a pak ho polib, jako by se nic nedělo.|240|pouta_postel!",
    "Volná ruka pro něj: Sváž mu jednu ruku, druhou nech volnou a ať si s ní honí, zatímco ho olizuješ. Cíl: pět minut a ruku nesmí zastavit.|300|pouta_postel!",
    "Dneska rozhoduješ ty s ním: Poruč mu kleknout si, řekni mu, že dneska rozhoduješ ty, a pak mu hoň. Cíl: pět minut a nesmí se zvednout.|300|klek_pouta!",
    "Jedno slovo a konec: Dohodněte se na slově, po kterém všechno okamžitě skončí, a pak jdi až na hranu. Cíl: nikdy ho neslyšet.|300|pouta_postel!",
    "Spoutej ho a mezi tím mu přejížděj ledem po celém těle.|300|pouta_postel!",
    "Zády ke zdi ve stoje: Sváž mu ruce, postav ho ke zdi zády a zezadu mu hoň. Cíl: čtyři minuty a ani jednou ho neotočit.|240|zed",
    "Spoutej ho a nech ho ležet nahého, zatímco se jen díváš.|240|pouta_postel!",
    "Poruč mu, ať ti řekne nahlas tři věci, které dneska udělá.|240|klek_pouta!",
    "Sváž mu ruce a doveď ho na hranu pětkrát za sebou.|300|pouta_postel!",
    "Říká, co cítí on: Spoutej ho, hoň mu péro a nech ho celou dobu nahlas říkat, co cítí. Cíl: pět minut a ani jednou se neodmlčí.|300|pouta_postel!",
    "Poslední rozkaz: Ukaž mu beze slova, ať si klekne, a pak mu hoň. Cíl: čtyři minuty a nemuset nic vysvětlovat.|240|klek_pouta!",
    "Sváž mu ruce a pak mu sundej pouta, ale on se pořád nesmí hýbat.|300|pouta_postel!",
    "Spoutej ho a pak ho obejmi. Kontrast, který funguje.|180|pouta_postel!",
    "Na konec mu rozvaž ruce a promasíruj mu zápěstí.|120|pouta_postel!",
  ],
});
