// Kategorie 5 – Hardcore (dávka c)
// Témata: bičík a plácání s počítáním, tah za vlasy, ruka na krku, tresty a rituály.
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 5,

  male: [
    "Dej jí deset ran bičíkem přes zadeček. Ona počítá nahlas a po každé řekne děkuju.|240|predklon",
    "Počítání naslepo: Zavaž jí oči a dávej jí rány bičíkem v nepravidelných rozestupech. Ona počítá. Cíl: deset bez ztráty počtu.|300|predklon",
    "Střídej ránu bičíkem a polibek na stejné místo. Pětkrát.|240|predklon",
    "Dej jí pět ran přes vnitřní stranu stehen. Slabě, ale jistě.|180|nohy_ramena",
    "Plácej ji dlaní po zadečku a postupně přidávej na síle. Ona řekne, kdy dost.|240|zezadu",
    "Plácni ji vždycky, když udělá chybu v počítání. A počítá od jedné do dvaceti.|300|predklon",
    "Deset a deset: Deset ran dlaní, pak deset bičíkem. Mezi tím minuta hlazení. Cíl: projít obojí.|300|predklon",
    "Dej jí bičíkem tři rány a pak to místo dlouho hlaď.|180|na_brise",
    "Nech ji vybrat počet ran. Pak přidej jednu navíc za drzost.|240|predklon",
    "Plácej ji, zatímco do ní vnikáš zezadu. Vždycky po deseti pohybech.|300|zezadu",
    "Nech ji klečet a dávej jí rány na zadeček shora.|240|klek_pouta",
    "Ruka nebo bičík: Ona si vybere, ale nesmí vidět, co držíš. Cíl: překvapit ji aspoň dvakrát.|300|predklon",
    "Dej jí pět ran přes prsa. Tak lehce, jak to jen jde.|180|pouta_postel",
    "Předkloň ji přes opěradlo a dej jí patnáct ran. Po každé se zeptej, jestli chce další.|300|predklon",
    "Plácni ji pokaždé, když otevře oči.|240|klek_ruce_hlava",
    "Nech ji držet se čela postele a plácej ji zezadu.|240|pouta_postel",
    "Vem ji za vlasy, stáhni jí hlavu dozadu a líbej ji na krk.|180|zezadu_vzpr",
    "Za vlasy a zezadu: Drž ji za vlasy stažené do pěsti, zatímco ji miluješ zezadu. Nikdy netahej silou. Cíl: udržet tah po celou dobu.|300|zezadu",
    "Vem ji za vlasy a otoč jí hlavu k sobě, ať se ti dívá do očí.|240|zezadu",
    "Drž ji za vlasy a poruč jí, ať klečí bez pohybu.|240|oral_ona_klek",
    "Polož jí ruku na krk a jen ji tam nech. Žádný tlak, jen váha.|240|misionar",
    "Ruka na krku: Položíš jí dlaň na krk a ona ti nahlas řekne, jestli to chce silněji. Ty poslechneš. Cíl: zeptat se dřív, než přidáš.|300|kontrola_vsede!",
    "Drž ji za zápěstí a přitiskni ji k posteli celou vahou.|240|kontrola_vsede!",
    "Drž ji pod bradou a poruč jí, ať otevře pusu.|180|oral_ona_klek",
    "Vem ji za vlasy a veď ji po kolenou přes postel.|240|zezadu",
    "Přitiskni ji čelem k posteli a drž ji tam rukou mezi lopatkami.|240|na_brise",
    "Trest za pohyb: Za každý pohyb navíc dostane jednu ránu. Ona se má nehýbat. Cíl: aspoň pět trestů.|300|pouta_postel",
    "Za každé slovo bez dovolení jedna rána. Ona nesmí mluvit.|300|predklon",
    "Dej jí úkol a za nesplnění následuje deset ran.|300|klek_pouta",
    "Nech ji, ať si sama řekne, kolik si zaslouží.|240|klek_pouta",
    "Nech ji počítat pozpátku od dvaceti. Za chybu je rána.|300|predklon",
    "Odměna a trest: Za každou splněnou věc polibek, za každou nesplněnou rána. Cíl: aspoň pět a pět.|300|predklon",
    "Dej jí tři rány a pak ji nech hádat, kolik jich ještě bude.|240|predklon",
    "Plácej ji tak dlouho, dokud nezvedne zadeček sama.|240|na_brise",
    "Nech ji klečet a dej jí bičíkem přes stehna. Jemně.|240|klek_pouta",
    "Dej jí rány přes zadeček a po každé jí tam přiložíš led.|300|predklon",
    "Led a rána: Rána bičíkem a hned po ní kostka ledu na to samé místo. Pětkrát. Cíl: co největší kontrast.|300|predklon",
    "Dej jí bičíkem přes záda, ale jen velmi lehce a nikdy přes páteř.|240|masaz_zada",
    "Plácej ji dlaní a zároveň ji dráždi druhou rukou.|300|na_brise",
    "Nech ji ležet a plácej ji, dokud tě sama nepoprosí o víc.|240|na_brise",
    "Poruč jí, ať ti poděkuje po každé ráně, a když zapomene, začínáte znovu.|300|predklon",
    "Dej jí pět ran a pak ji nech dojít jen rukou.|300|predklon",
    "Rituál před trestem: Musí si sama kleknout, poprosit a teprve pak začneš. Cíl: nechat ji projít celý rituál.|300|klek_pouta",
    "Nech ji, ať si sama vybere, čím ji budeš plácat.|240|predklon",
    "Dej jí rány přes zadeček přes kalhotky a teprve pak je stáhni.|300|predklon",
    "Plácni ji vždycky, když se nadechne příliš nahlas.|300|zezadu",
    "Drž ji za vlasy a poruč jí, ať se na sebe dívá do zrcadla.|240|zezadu",
    "Vem ji za vlasy a přitáhni si ji na sebe.|240|ona_nahore",
    "Drž ji za vlasy a zároveň jí drž ruku za zády.|300|zezadu",
    "Dvě ruce, dvě věci: Jednou rukou ji drž za vlasy, druhou ji dráždi. Cíl: nepustit ani jedno.|300|zezadu",
    "Polož jí ruku na krk, když je nejblíž vrcholu.|240|misionar",
    "Drž ji za bradu a nedovol jí uhnout pohledem.|240|kontrola_vsede!",
    "Přitiskni ji ke zdi a drž ji tam jednou rukou.|240|zed",
    "Drž ji za ruce za zády a poruč jí, ať se předkloní.|240|predklon",
    "Poruč jí, ať si klekne a čeká s hlavou skloněnou.|180|klek_pouta",
    "Klid a čekání: Klečí se skloněnou hlavou tři minuty a ty nic neděláš. Cíl: nechat ji v tom.|180|klek_pouta",
    "Dej jí deset ran a po každé se jí zeptej na stupnici od jedné do desíti.|300|predklon",
    "Plácej ji, ale pokaždé jinam. Nikdy dvakrát na stejné místo.|240|na_brise",
    "Dej jí rány tak, aby po každé musela nahlas říct další.|300|predklon",
    "Nech ji vybrat mezi pěti silnými a dvaceti slabými ranami.|240|predklon",
    "Odpočítávání trestu: Řekni jí, kolik ran ji čeká, a odpočítávej je nahlas. Cíl: dojít na nulu bez zastavení.|300|predklon",
    "Dej jí rány, dokud nebude prosit, a pak ještě dvě.|300|predklon",
    "Plácni ji a hned ji vezmi zezadu, ať nemá čas se nadechnout.|300|zezadu",
    "Drž ji za vlasy a mluv na ni tvrdě, ale nikdy zle.|240|zezadu",
    "Poruč jí, ať tě požádá o každou další ránu zvlášť.|300|predklon",
    "Nech ji ležet na břiše a plácej ji jen konečky prstů.|240|na_brise",
    "Jemně a tvrdě: Střídej velmi jemné plácnutí a pořádnou ránu bez varování. Cíl: ať nikdy neví, co přijde.|300|predklon",
    "Dej jí rány a mezi nimi ji dlouze líbej.|300|predklon",
    "Plácej ji, když sedí na tobě, a řiď tím tempo.|300|ona_nahore",
    "Drž ji za boky tak pevně, že tam zůstanou otisky prstů.|240|zezadu",
    "Zakousni se jí do ramene přesně ve chvíli, kdy je těsně před vrcholem.|240|lzicka",
    "Poruč jí, ať si sama stáhne kalhotky a předkloní se.|240|predklon",
    "Beze slov a s bičíkem: Celý trest proběhne beze slov, jen s gesty. Cíl: dorozumět se bez mluvení.|300|predklon",
    "Dej jí ránu pokaždé, když se pokusí sáhnout si.|300|pouta_postel",
    "Plácej ji, dokud nezačne počítat sama od sebe.|240|predklon",
    "Nech ji klečet s rukama za hlavou a dávej jí rány přes stehna.|240|klek_ruce_hlava",
    "Poruč jí, ať drží ruce na zdi a nesundá je.|240|zed",
    "Dej jí rány a pak ji nech ležet a dívat se na tebe.|240|predklon",
    "Vem ji za vlasy a doveď ji ke kraji postele.|180|kraj_postele",
    "Konec rituálu: Po posledním trestu ji obejmi a řekni jí, jak dobře to zvládla. Cíl: nikdy nevynechat.|180|pouta_postel",
    "Dej jí poslední ránu a hned poté ji polib.|180|predklon",
    "Plácni ji naposledy, hodně jemně, a skonči.|120|na_brise",
    "Na konec jí namasíruj místa, kam dopadly rány.|180|masaz_zada",
  ],

  female: [
    "Dej mu deset ran bičíkem přes zadek. On počítá nahlas a po každé řekne děkuju.|240|predklon!",
    "Počítání naslepo: Zavaž mu oči a dávej mu rány bičíkem v nepravidelných rozestupech. On počítá. Cíl: deset bez ztráty počtu.|300|predklon!",
    "Po každé ráně bičíkem to samé místo hned polib. Pětkrát za sebou.|240|predklon!",
    "Dej mu pět ran přes vnitřní stranu stehen. Slabě, ale jistě.|180|oral_on_vleze",
    "Plácej ho dlaní po zadku a postupně přidávej na síle. On řekne, kdy dost.|240|zezadu!",
    "Plácni ho vždycky, když udělá chybu v počítání. A počítá od jedné do dvaceti.|300|predklon!",
    "Dlaň a bičík: Nejdřív deset ran dlaní, minuta hlazení a pak deset bičíkem. Cíl: projít obojí.|300|predklon!",
    "Dej mu bičíkem tři rány a pak to místo dlouho hlaď.|180|na_brise!",
    "Nech ho vybrat počet ran. Pak přidej jednu navíc za drzost.|240|predklon!",
    "Plácej ho, zatímco na něm sedíš. Vždycky po deseti pohybech.|300|ona_nahore",
    "Nech ho klečet a dávej mu rány na zadek shora.|240|klek_pouta!",
    "Ruka nebo bičík: On si vybere, ale nesmí vidět, co držíš. Cíl: překvapit ho aspoň dvakrát.|300|predklon!",
    "Dej mu pět ran přes hrudník. Tak lehce, jak to jen jde.|180|pouta_postel!",
    "Předkloň ho přes opěradlo a dej mu patnáct ran. Po každé se zeptej, jestli chce další.|300|predklon!",
    "Plácni ho pokaždé, když otevře oči.|240|klek_ruce_hlava!",
    "Nech ho držet se čela postele a plácej ho zezadu.|240|pouta_postel!",
    "Vem ho za vlasy, stáhni mu hlavu dozadu a líbej ho na krk.|180|zezadu_vzpr!",
    "Za vlasy a zezadu: Drž ho za vlasy stažené do pěsti, zatímco je v tobě zezadu. Nikdy netahej silou. Cíl: udržet tah po celou dobu.|300|zezadu!",
    "Vem ho za vlasy a otoč mu hlavu k sobě, ať se ti dívá do očí.|240|zezadu!",
    "Drž ho za vlasy a poruč mu, ať klečí bez pohybu.|240|oral_ona_klek",
    "Polož mu ruku na krk a jen ji tam nech. Žádný tlak, jen váha.|240|kontrola_vsede",
    "Ruka na krku: Položíš mu dlaň na krk a on ti nahlas řekne, jestli to chce silněji. Ty poslechneš. Cíl: zeptat se dřív, než přidáš.|300|kontrola_vsede",
    "Drž mu zápěstí a přitiskni ho k posteli celou vahou.|240|kontrola_vsede",
    "Drž ho pod bradou a poruč mu, ať otevře pusu.|180|oral_ona_klek",
    "Vem ho za vlasy a veď ho po kolenou přes postel.|240|zezadu!",
    "Přitiskni ho čelem k posteli a drž ho tam rukou mezi lopatkami.|240|na_brise!",
    "Trest za pohyb: Za každý pohyb navíc dostane jednu ránu. On se má nehýbat. Cíl: aspoň pět trestů.|300|pouta_postel!",
    "Za každé slovo bez dovolení jedna rána. On nesmí mluvit.|300|predklon!",
    "Dej mu úkol a za nesplnění následuje deset ran.|300|klek_pouta!",
    "Nech ho, ať si sám řekne, kolik si zaslouží.|240|klek_pouta!",
    "Nech ho počítat pozpátku od dvaceti. Za chybu je rána.|300|predklon!",
    "Polibek nebo rána: Co splní, to je polibek, co nesplní, to je rána. Cíl: aspoň pět a pět.|300|predklon!",
    "Dej mu tři rány a pak ho nech hádat, kolik jich ještě bude.|240|predklon!",
    "Plácej ho tak dlouho, dokud nezvedne zadek sám.|240|na_brise!",
    "Nech ho klečet a dej mu bičíkem přes stehna. Jemně.|240|klek_pouta!",
    "Dej mu rány přes zadek a po každé mu tam přiložíš led.|300|predklon!",
    "Rána a mráz: Po každé ráně přilož na to místo kostku ledu. Pětkrát. Cíl: co největší kontrast.|300|predklon!",
    "Dej mu bičíkem přes záda, ale jen velmi lehce a nikdy přes páteř.|240|masaz_zada!",
    "Plácej ho dlaní a zároveň ho dráždi druhou rukou.|300|na_brise!",
    "Nech ho ležet a plácej ho, dokud tě sám nepoprosí o víc.|240|na_brise!",
    "Poruč mu, ať ti poděkuje po každé ráně, a když zapomene, začínáte znovu.|300|predklon!",
    "Dej mu pět ran a pak ho nech dojít jen rukou.|300|predklon!",
    "Rituál před trestem: Musí si sám kleknout, poprosit a teprve pak začneš. Cíl: nechat ho projít celý rituál.|300|klek_pouta!",
    "Nech ho, ať si sám vybere, čím ho budeš plácat.|240|predklon!",
    "Dej mu rány přes zadek přes trenýrky a teprve pak mu je stáhni.|300|predklon!",
    "Plácni ho vždycky, když se nadechne příliš nahlas.|300|ona_nahore",
    "Drž ho za vlasy a poruč mu, ať se na sebe dívá do zrcadla.|240|zezadu!",
    "Vem ho za vlasy a přitáhni si ho k sobě.|240|kontrola_vsede",
    "Drž ho za vlasy a zároveň mu drž ruku za zády.|300|zezadu!",
    "Dvě ruce, dvě věci: Jednou rukou ho drž za vlasy, druhou ho dráždi. Cíl: nepustit ani jedno.|300|zezadu!",
    "Polož mu ruku na krk, když je nejblíž konci.|240|kontrola_vsede",
    "Drž ho za bradu a nedovol mu uhnout pohledem.|240|kontrola_vsede",
    "Přitiskni ho ke zdi a drž ho tam jednou rukou.|240|zed",
    "Drž mu ruce za zády a poruč mu, ať se předkloní.|240|predklon!",
    "Poruč mu, ať si klekne a čeká se skloněnou hlavou.|180|klek_pouta!",
    "Klid a čekání: Klečí se skloněnou hlavou tři minuty a ty nic neděláš. Cíl: nechat ho v tom.|180|klek_pouta!",
    "Dej mu deset ran a po každé se ho zeptej na stupnici od jedné do desíti.|300|predklon!",
    "Plácej ho, ale pokaždé jinam. Nikdy dvakrát na stejné místo.|240|na_brise!",
    "Dej mu rány tak, aby po každé musel nahlas říct další.|300|predklon!",
    "Nech ho vybrat mezi pěti silnými a dvaceti slabými ranami.|240|predklon!",
    "Odpočítávání trestu: Řekni mu, kolik ran ho čeká, a odpočítávej je nahlas. Cíl: dojít na nulu bez zastavení.|300|predklon!",
    "Dej mu rány, dokud nebude prosit, a pak ještě dvě.|300|predklon!",
    "Plácni ho a hned si na něj sedni, ať nemá čas se nadechnout.|300|ona_nahore",
    "Drž ho za vlasy a mluv na něj tvrdě, ale nikdy zle.|240|zezadu!",
    "Poruč mu, ať tě požádá o každou další ránu zvlášť.|300|predklon",
    "Nech ho ležet na břiše a plácej ho jen konečky prstů.|240|na_brise!",
    "Bez varování: Jednou plácneš skoro neznatelně, podruhé naplno, a nikdy dopředu neřekneš které. Cíl: ať to nikdy neuhodne.|300|predklon!",
    "Dej mu rány a mezi nimi ho dlouze líbej.|300|predklon!",
    "Plácej ho, když je v tobě zezadu, a řiď tím tempo.|300|zezadu!",
    "Drž ho za boky tak pevně, že tam zůstanou otisky prstů.|240|ona_nahore",
    "Zakousni se mu do ramene přesně ve chvíli, kdy je těsně před koncem.|240|lzicka",
    "Poruč mu, ať si sám stáhne trenýrky a předkloní se.|240|predklon!",
    "Jen gesta: Celý trest zvládněte bez jediného slova, domluvíte se rukama. Cíl: dorozumět se bez mluvení.|300|predklon!",
    "Dej mu ránu pokaždé, když se pokusí sáhnout si.|300|pouta_postel!",
    "Plácej ho, dokud nezačne počítat sám od sebe.|240|predklon!",
    "Nech ho klečet s rukama za hlavou a dávej mu rány přes stehna.|240|klek_ruce_hlava!",
    "Poruč mu, ať drží ruce na zdi a nesundá je.|240|zed",
    "Dej mu rány a pak ho nech ležet a dívat se na tebe.|240|predklon",
    "Vem ho za vlasy a doveď ho ke kraji postele.|180|kraj_postele!",
    "Konec rituálu: Po posledním trestu ho obejmi a řekni mu, jak dobře to zvládl. Cíl: nikdy nevynechat.|180|pouta_postel!",
    "Dej mu poslední ránu a hned poté ho polib.|180|predklon!",
    "Plácni ho naposledy, hodně jemně, a skonči.|120|na_brise!",
    "Na konec mu namasíruj místa, kam dopadly rány.|180|masaz_zada!",
  ],
});
