// Kategorie 5 – Hardcore (dávka b)
// Témata: pouta a svázání, úplná deprivace, kontrolní pozice, rozkazy a poslušnost.
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 5,

  male: [
    "Jen stop slovo: Spoutej jí ruce k čelu postele a dělej s ní, co chceš. Cíl: pět minut, při kterých smí říct jediné slovo – a to je stop.|300|pouta_postel",
    "Prozkoumat celou: Sváž jí zápěstí kravatou nad hlavou, uzel volně, a pomalu ji prozkoumej celou. Cíl: nevynechat ani jedno místo.|300|pouta_postel",
    "Rozepnutá a svázaná: Spoutej jí ruce k čelu postele, zavaž oči a nasaď sluchátka. Pět minut jen čeká. Cíl: nedotknout se jí dřív.|300|pouta_postel",
    "Klečí, dokud nedovolíš: Spoutej jí ruce za zády a nech ji klečet. Cíl: nedovolit jí vstát dřív než po pěti minutách.|300|klek_pouta",
    "Svázaná vkleče: Sváž jí ruce kravatou za zády a miluj ji zezadu, když klečí. Cíl: pět minut a na stop ji hned rozvázat.|300|zezadu",
    "Hádej čím: Spoutej ji, zavaž jí oči a střídej ruce, pírko, led a vibrátor. Cíl: deset doteků a ať uhodne aspoň šest.|300|pouta_postel",
    "Každá ruka jinam: Přivaž jí každou ruku k jinému rohu postele, uzly volně. Cíl: pět minut a kdykoli řekne stop, hned ji rozvázat.|300|pouta_postel",
    "Kotníky svázané, kolena od sebe: Sváž jí kotníky k sobě a pak jí rukama roztahuj kolena. Cíl: pět minut a nepustit je ani jednou.|300|nohy_ramena",
    "Pouta a příkaz: Spoutej jí ruce a dej jí jediné pravidlo – nesmí prosit. Když poprosí, přestaneš na minutu. Cíl: ať poprosí.|300|pouta_postel",
    "Minuta čekání ve poutech: Spoutej ji a pak ji nech celou minutu jen tak ležet. Cíl: nedotknout se jí dřív, ať říká cokoli.|300|pouta_postel",
    "Ruce u jejích stehen: Sváž jí ruce volně ke stehnům a dráždi ji vibrátorem. Cíl: pět minut a kdykoli řekne stop, hned ji uvolnit.|300|pouta_postel",
    "Nevidí, neslyší: Zavaž jí oči, nasaď jí sluchátka a pak ji miluj. Cíl: pět minut a domluvit se výhradně doteky.|300|deprivace",
    "Úplná tma: Zavázané oči, sluchátka a spoutané ruce. Ona neví nic. Cíl: pět minut úplné nejistoty.|300|deprivace",
    "Led a vibrace: Zavaž jí oči a přikládej jí střídavě kostku ledu a vibrátor. Cíl: dvacet střídání a ať ani jednou neuhodne, co přijde.|300|deprivace",
    "Ruka, nebo pomůcka: Zavaž jí oči a nech ji hádat, jestli se jí dotýkáš rukou, nebo pomůckou. Cíl: deset pokusů a splést ji aspoň čtyřikrát.|300|deprivace",
    "Čekání poslepu: Zavaž jí oči a nech ji ležet v tichu. Cíl: nedotknout se jí, dokud sama nezačne prosit.|300|deprivace",
    "Ruce za hlavou vkleče: Poruč jí, ať si klekne a dá ruce za hlavu, a pak se jí věnuj. Cíl: pět minut – jakmile ruce sundá, začínáte znovu.|300|klek_ruce_hlava",
    "Klek a povel: Klečí s rukama za hlavou a ty ji obcházíš. Když ruce sundá, začíná znovu. Cíl: vydržet bez pohybu.|300|klek_ruce_hlava",
    "Vkleče a bez rukou: Poruč jí, ať klečí s rukama za hlavou, a miluj ji zezadu. Cíl: pět minut a ruce se nesmí hnout.|300|zezadu_vzpr",
    "Čeká na tvoje slovo: Nech ji klečet a čekat, ty se zatím jen díváš. Cíl: čtyři minuty ticha, než jí dovolíš vstát.|240|klek_pouta",
    "Nehne se ani o kousek: Poruč jí, ať se předkloní přes opěradlo a nehne se, ať děláš cokoli. Cíl: pět minut a nejvýš dva pohyby.|300|predklon",
    "Tři povolená slova: Oznam jí, že smí říct jen „ano“, „pane“, nebo stop slovo. Cíl: pět minut a ani jedno slovo navíc.|300|klek_pouta",
    "Tři rozkazy: Dáš jí tři rozkazy za sebou a každý musí splnit do tří vteřin. Cíl: žádné zaváhání.|300|klek_pouta",
    "Celou větou: Poruč jí, ať tě sama poprosí o to, co chce – a musí to říct celou větou. Cíl: nedat jí nic, dokud to nevysloví.|300|klek_ruce_hlava",
    "Za pohyb trest: Oznam jí, že se nesmí hnout, ať děláš cokoli. Za každý pohyb rána bičíkem. Cíl: pět minut a nejvýš tři tresty.|300|pouta_postel",
    "Nesmí zavřít oči: Poruč jí, ať se na tebe celou dobu dívá. Cíl: pět minut – jakmile zavře oči, přestáváš na deset vteřin.|300|kontrola_vsede!",
    "Nevysmekne se: Drž jí obě ruce nad hlavou a miluj se s ní. Cíl: pět minut a ani jednou se nesmí vysmeknout.|300|kontrola_vsede!",
    "Určuješ všechno ty: Sedni si na ni, drž jí zápěstí a veď tempo i polohu úplně sám. Cíl: pět minut a nenechat si do ničeho mluvit.|300|kontrola_vsede!",
    "Plná kontrola: Držíš jí ruce nad hlavou a ona nesmí ani jednou převzít vedení. Cíl: vydržet to celou dobu.|300|kontrola_vsede!",
    "Připomeneš jen pohledem: Nech ji ležet s rukama nad hlavou a když je sundá, připomeň jí to jen pohledem. Cíl: pět minut bez jediného slova.|300|pouta_postel",
    "Dlouhé pauzy: Spoutej ji a mezi jednotlivými doteky dělej co nejdelší pauzy. Cíl: deset doteků a mezi nimi vždy aspoň dvacet vteřin nic.|300|pouta_postel",
    "Svázaná mezi tvýma nohama: Sváž jí ruce a nech ji kleknout si mezi tvoje nohy. Cíl: pět minut a musí si vystačit jen ústy.|300|oral_ona_klek",
    "Dívá se, jak se svlékáš: Spoutej ji, posaď ji na židli a pomalu se před ní svlékej. Cíl: nesáhnout na ni, dokud nejsi úplně nahý.|300|zidle_celem",
    "Ruce u kotníků na boku: Sváž jí ruce volně ke kotníkům a nech ji ležet na boku. Cíl: pět minut a na stop ji hned rozvázat.|300|dvojita_bok",
    "Klečící a spoutaná: Ruce za zády, klečí na podlaze, ty stojíš. Nic nedělej minutu. Cíl: nechat ji čekat.|300|klek_pouta",
    "Kolik ještě vydržíš: Spoutej ji, dráždi ji a každou minutu se zeptej, kolik toho ještě vydrží. Cíl: dotáhnout to přesně k číslu, které řekne naposled.|300|pouta_postel",
    "Vybere si, dostane jiné: Sváž jí ruce a nech ji vybrat, co s ní uděláš. Cíl: udělat něco úplně jiného – a udělat to dobře.|300|pouta_postel",
    "Počítá tvoje přírazy: Poruč jí, ať nahlas počítá každý tvůj příraz. Cíl: dojít k padesáti – jakmile se splete, začínáte od nuly.|300|zezadu",
    "Jen kývnutí: Zakaž jí mluvit – smí jen kývnout nebo zavrtět hlavou. Cíl: pět minut a všechno se domluvit otázkami.|300|pouta_postel",
    "Zaváže si je sama: Poruč jí, ať si sama zaváže oči a čeká na posteli. Cíl: nechat ji čekat celou minutu, než se jí dotkneš.|240|deprivace",
    "Rituál: Ona ti musí říct nahlas, co dneska chce, klečíc před tebou. Teprve pak to dostane. Cíl: nechat ji to vyslovit.|300|oral_ona_klek",
    "Spoutej ji a pak jí velmi pomalu svlékej zbytek oblečení.|300|pouta_postel",
    "Sváž jí ruce a nech ji stát uprostřed pokoje, zatímco ji obcházíš.|240|klek_pouta",
    "Spoutej jí ruce za zády a nech ji na kolenou před tebou.|300|oral_ona_klek",
    "Ruce nad hlavou u zdi: Sváž jí ruce kravatou a zvedni je nad hlavu ke zdi. Cíl: pět minut a na stop ji hned rozvázat.|300|zed",
    "Spoutej ji a nasaď jí sluchátka. Ať tě neslyší přicházet.|300|deprivace",
    "Ticho a čekání: Spoutaná se zavázanýma očima čeká tři minuty úplně sama. Cíl: nepromluvit ani jednou.|180|deprivace",
    "Spoutej ji a přitom jí celou dobu něco šeptej do ucha.|300|pouta_postel",
    "Sváž jí ruce kravatou a nech ji, ať si sama vybere polohu.|300|pouta_postel",
    "Spoutej ji a doveď ji k vrcholu jen vibrátorem.|300|pouta_postel",
    "Třikrát za sebou: Spoutej ji a střídej jazyk, prsty a vibrátor. Cíl: tři orgasmy za sebou a mezi nimi žádná pauza delší než minuta.|300|pouta_postel",
    "Sváž jí ruce, zavaž oči a střídej pírko a bičík.|300|pouta_postel",
    "Spoutej ji a pak si na ni sedni a drž ji za boky.|300|kontrola_vsede!",
    "Pouta a pomalost: Je spoutaná a ty se hýbeš tak pomalu, jak to jde. Cíl: nezrychlit ani jednou.|300|pouta_postel",
    "Svázaná na boku: Sváž jí ruce kravatou před tělem a miluj se s ní na boku. Cíl: pět minut a na stop ji hned rozvázat.|300|dvojita_bok",
    "Spoutej ji a nech ji prosit o každou další věc zvlášť.|300|pouta_postel",
    "Poruč jí, ať se otočí a nedívá se, co chystáš.|240|zezadu",
    "Řekni jí, ať nesmí dojít bez tvého svolení. A dlouho ho nedávej.|300|pouta_postel",
    "Poruč jí, ať si klekne, a ty jí jen hlaď vlasy. Nic víc.|240|oral_ona_klek",
    "Rozkaz a odměna: Za každý bezchybně splněný rozkaz dostane jednu věc, kterou má ráda. Cíl: tři odměny.|300|klek_pouta",
    "Sváž jí ruce a přitom jí drž bradu, ať se ti dívá do očí.|300|kontrola_vsede!",
    "Spoutej ji a nech ji ležet na břiše. Pak ji vezmi zezadu.|300|na_brise",
    "Sváž jí ruce a nech ji klečet na všech čtyřech s hlavou dole.|300|zezadu",
    "Spoutej ji a nech ji rozhodnout jen o jedné jediné věci.|300|pouta_postel",
    "Poruč jí, ať tě poslouchá na slovo, a pak buď hodně konkrétní.|300|zezadu",
    "Přesně tak: Popiš jí přesně, jak má ležet, a oprav každou odchylku. Cíl: ať to sedí na centimetr.|300|pouta_postel",
    "Spoutej ji a nech ji čekat, zatímco si dáváš na čas.|240|pouta_postel",
    "Sváž jí ruce nad hlavou a olizuj ji tak dlouho, dokud neprosí.|300|pouta_postel",
    "Spoutej ji a pak ji polib, jako by se nic nedělo.|240|pouta_postel",
    "Sváž jí jednu ruku a druhou nech volnou. Ať si vybere, co s ní.|300|pouta_postel",
    "Poruč jí, ať klečí, a řekni jí, že dneska rozhoduješ ty.|300|klek_pouta",
    "Jediné slovo: Domluvte si jedno slovo, po kterém okamžitě přestaneš. Pak jdi až na hranu. Cíl: nikdy to slovo neslyšet.|300|pouta_postel",
    "Spoutej ji a mezi tím jí přejížděj ledem po celém těle.|300|pouta_postel",
    "Sváž jí ruce a nech ji stát u zdi zády k tobě.|240|zed",
    "Spoutej ji a nech ji ležet nahou, zatímco se jen díváš.|240|pouta_postel",
    "Poruč jí, ať ti řekne nahlas tři věci, které dneska udělá.|240|klek_pouta",
    "Sváž jí ruce a doveď ji na hranu pětkrát za sebou.|300|pouta_postel",
    "Spoutej ji a nech ji celou dobu mluvit, co cítí.|300|pouta_postel",
    "Poslední rozkaz: Dej jí jeden poslední rozkaz a nech ji ho splnit beze slov. Cíl: nemuset nic vysvětlovat.|240|klek_pouta",
    "Sváž jí ruce a pak jí sundej pouta, ale ona se pořád nesmí hýbat.|300|pouta_postel",
    "Spoutej ji a pak ji obejmi. Kontrast, který funguje.|180|pouta_postel",
    "Na konec jí rozvaž ruce a promasíruj jí zápěstí.|120|pouta_postel",
  ],

  female: [
    "Jediné povolené slovo: Spoutej mu ruce k čelu postele a dělej s ním, co chceš. Cíl: pět minut, při kterých smí říct jediné slovo – a to je stop.|300|pouta_postel!",
    "Prozkoumat celého: Sváž mu zápěstí kravatou nad hlavou, uzel volně, a pomalu ho prozkoumej celého. Cíl: nevynechat ani jedno místo.|300|pouta_postel!",
    "Rozepnutý a svázaný: Spoutej mu ruce k čelu postele, zavaž oči a nasaď sluchátka. Pět minut jen čeká. Cíl: nedotknout se ho dřív.|300|pouta_postel!",
    "Klečí, dokud nedovolíš: Spoutej mu ruce za zády a nech ho klečet. Cíl: nedovolit mu vstát dřív než po pěti minutách.|300|klek_pouta!",
    "Svázaný vkleče: Sváž mu ruce za zády a nech ho klečet, zatímco ho olizuješ zezadu. Cíl: pět minut a na stop ho hned rozvázat.|300|zezadu!",
    "Hádej, co to je: Spoutej ho, zavaž mu oči a střídej ruce, pírko, led a vibrátor. Cíl: deset doteků a ať uhodne aspoň šest.|300|pouta_postel!",
    "Ruce do rohů: Přivaž mu každou ruku k jinému rohu postele, uzly volně. Cíl: pět minut a kdykoli řekne stop, hned ho rozvázat.|300|pouta_postel!",
    "Kotníky u sebe: Sváž mu kotníky k sobě a pak mu rukama roztahuj kolena. Cíl: pět minut a nepustit je ani jednou.|300|oral_on_vleze",
    "Pouta a příkaz: Spoutej mu ruce a dej mu jediné pravidlo – nesmí prosit. Když poprosí, přestaneš na minutu. Cíl: ať poprosí.|300|pouta_postel!",
    "Minuta v poutech: Spoutej ho a pak ho nech celou minutu jen tak ležet. Cíl: nedotknout se ho dřív, ať říká cokoli.|300|pouta_postel!",
    "Ruce u jeho stehen: Sváž mu ruce volně ke stehnům a dráždi ho vibrátorem. Cíl: pět minut a kdykoli řekne stop, hned ho uvolnit.|300|pouta_postel!",
    "Ani nevidí, ani neslyší: Zavaž mu oči, nasaď mu sluchátka a pak si na něj sedni. Cíl: pět minut a domluvit se výhradně doteky.|300|deprivace!",
    "Úplná tma: Zavázané oči, sluchátka a spoutané ruce. On neví nic. Cíl: pět minut úplné nejistoty.|300|deprivace!",
    "Mráz a vibrace: Zavaž mu oči a přikládej mu střídavě kostku ledu a vibrátor. Cíl: dvacet střídání a ať ani jednou neuhodne, co přijde.|300|deprivace!",
    "Ruka, nebo věc: Zavaž mu oči a nech ho hádat, jestli se ho dotýkáš rukou, nebo pomůckou. Cíl: deset pokusů a splést ho aspoň čtyřikrát.|300|deprivace!",
    "Ať si počká: Zavaž mu oči a nech ho ležet v tichu. Cíl: nedotknout se ho, dokud sám nezačne prosit.|300|deprivace!",
    "Na kolenou s rukama za hlavou: Poruč mu, ať si klekne a dá ruce za hlavu, a pak se mu věnuj. Cíl: pět minut – jakmile ruce sundá, začínáte znovu.|300|klek_ruce_hlava!",
    "Klek a povel: Klečí s rukama za hlavou a ty ho obcházíš. Když ruce sundá, začíná znovu. Cíl: vydržet bez pohybu.|300|klek_ruce_hlava!",
    "Vkleče a bez rukou: Poruč mu, ať klečí s rukama za hlavou, a olizuj ho zezadu. Cíl: pět minut a ruce se nesmí hnout.|300|zezadu_vzpr!",
    "Čeká na tvoje svolení: Nech ho klečet a čekat, ty se zatím jen díváš. Cíl: čtyři minuty ticha, než mu dovolíš vstát.|240|klek_pouta!",
    "Ani se nehne: Poruč mu, ať se předkloní přes opěradlo a nehne se, ať děláš cokoli. Cíl: pět minut a nejvýš dva pohyby.|300|predklon!",
    "Tři slova pro něj: Oznam mu, že smí říct jen „ano“, „paní“, nebo stop slovo. Cíl: pět minut a ani jedno slovo navíc.|300|klek_pouta!",
    "Tři rozkazy: Dáš mu tři rozkazy za sebou a každý musí splnit do tří vteřin. Cíl: žádné zaváhání.|300|klek_pouta!",
    "Musí to říct celou větou: Poruč mu, ať tě sám poprosí o to, co chce – a musí to říct celou větou. Cíl: nedat mu nic, dokud to nevysloví.|300|klek_ruce_hlava",
    "Pohyb stojí trest: Oznam mu, že se nesmí hnout, ať děláš cokoli. Za každý pohyb rána bičíkem. Cíl: pět minut a nejvýš tři tresty.|300|pouta_postel!",
    "Oči na tobě: Poruč mu, ať se na tebe celou dobu dívá. Cíl: pět minut – jakmile zavře oči, přestáváš na deset vteřin.|300|kontrola_vsede",
    "Drž ho nad hlavou: Drž mu obě ruce nad hlavou a sedni si na něj. Cíl: pět minut a ani jednou se nesmí vysmeknout.|300|kontrola_vsede",
    "Určuješ všechno sama: Sedni si na něj, drž mu zápěstí a veď tempo i polohu úplně sama. Cíl: pět minut a nenechat si do ničeho mluvit.|300|kontrola_vsede",
    "Plná kontrola: Držíš mu ruce nad hlavou a on nesmí ani jednou převzít vedení. Cíl: vydržet to celou dobu.|300|kontrola_vsede",
    "Připomínka pohledem: Nech ho ležet s rukama nad hlavou a když je sundá, připomeň mu to jen pohledem. Cíl: pět minut bez jediného slova.|300|pouta_postel!",
    "Pauzy mezi doteky: Spoutej ho a mezi jednotlivými doteky dělej co nejdelší pauzy. Cíl: deset doteků a mezi nimi vždy aspoň dvacet vteřin nic.|300|pouta_postel!",
    "Svázaný před tebou: Sváž mu ruce a nech ho kleknout si před tebe. Cíl: pět minut a musí si vystačit jen ústy.|300|oral_ona_klek",
    "Dívá se na svlékání: Spoutej ho, posaď ho na židli a pomalu se před ním svlékej. Cíl: nesáhnout na něj, dokud nejsi úplně nahá.|300|zidle_celem",
    "Jeho ruce u kotníků: Sváž mu ruce volně ke kotníkům a nech ho ležet na boku. Cíl: pět minut a na stop ho hned rozvázat.|300|dvojita_bok!",
    "Klečící a spoutaný: Ruce za zády, klečí na podlaze, ty stojíš. Nic nedělej minutu. Cíl: nechat ho čekat.|300|klek_pouta",
    "Kolik ještě vydrží: Spoutej ho, dráždi ho a každou minutu se zeptej, kolik toho ještě vydrží. Cíl: dotáhnout to přesně k číslu, které řekne naposled.|300|pouta_postel!",
    "Vybere si, dostane něco jiného: Sváž mu ruce a nech ho vybrat, co s ním uděláš. Cíl: udělat něco úplně jiného – a udělat to dobře.|300|pouta_postel!",
    "Počítá tvoje pohyby: Poruč mu, ať nahlas počítá každý tvůj pohyb. Cíl: dojít k padesáti – jakmile se splete, začínáte od nuly.|300|ona_nahore",
    "Jen kývne: Zakaž mu mluvit – smí jen kývnout nebo zavrtět hlavou. Cíl: pět minut a všechno se domluvit otázkami.|300|pouta_postel!",
    "Poruč mu, ať si sám zaváže oči a čeká na posteli.|240|deprivace!",
    "Rituál: On ti musí říct nahlas, co dneska chce, klečíc před tebou. Teprve pak to dostane. Cíl: nechat ho to vyslovit.|300|oral_ona_klek",
    "Spoutej ho a pak mu velmi pomalu svlékej zbytek oblečení.|300|pouta_postel!",
    "Sváž mu ruce a nech ho stát uprostřed pokoje, zatímco ho obcházíš.|240|klek_pouta!",
    "Spoutej mu ruce za zády a nech ho na kolenou před sebou.|300|oral_ona_klek",
    "Jeho ruce nad hlavou: Sváž mu ruce kravatou a zvedni je nad hlavu ke zdi. Cíl: pět minut a na stop ho hned rozvázat.|300|zed",
    "Spoutej ho a nasaď mu sluchátka. Ať tě neslyší přicházet.|300|deprivace!",
    "Ticho a čekání: Spoutaný se zavázanýma očima čeká tři minuty úplně sám. Cíl: nepromluvit ani jednou.|180|deprivace!",
    "Spoutej ho a přitom mu celou dobu něco šeptej do ucha.|300|pouta_postel!",
    "Sváž mu ruce kravatou a nech ho, ať si sám vybere polohu.|300|pouta_postel!",
    "Jen rukou až do konce: Spoutej ho a doveď ho na konec výhradně rukou. Cíl: nepoužít ústa ani nic jiného.|300|pouta_postel!",
    "Spoutej ho a nech ho dojít, pak pokračuj ještě chvíli.|300|pouta_postel!",
    "Sváž mu ruce, zavaž oči a střídej pírko a bičík.|300|pouta_postel!",
    "Spoutej ho a pak si na něj sedni a drž ho za ramena.|300|kontrola_vsede",
    "Pouta a pomalost: Je spoutaný a ty se hýbeš tak pomalu, jak to jde. Cíl: nezrychlit ani jednou.|300|pouta_postel!",
    "Svázaný na boku: Sváž mu ruce kravatou před tělem a miluj se s ním na boku. Cíl: pět minut a na stop ho hned rozvázat.|300|dvojita_bok!",
    "Spoutej ho a nech ho prosit o každou další věc zvlášť.|300|pouta_postel!",
    "Poruč mu, ať se otočí a nedívá se, co chystáš.|240|zezadu!",
    "Řekni mu, že se nesmí udělat bez tvého svolení. A dlouho ho nedávej.|300|pouta_postel!",
    "Poruč mu, ať si klekne, a ty mu jen prohrábni vlasy. Nic víc.|240|oral_ona_klek",
    "Rozkaz a odměna: Za každý bezchybně splněný rozkaz dostane jednu věc, kterou má rád. Cíl: tři odměny.|300|klek_pouta!",
    "Sváž mu ruce a přitom mu drž bradu, ať se ti dívá do očí.|300|kontrola_vsede",
    "Spoutej ho a nech ho ležet na břiše. Pak si sedni na něj.|300|na_brise!",
    "Sváž mu ruce a nech ho klečet na všech čtyřech s hlavou dole.|300|zezadu!",
    "Spoutej ho a nech ho rozhodnout jen o jedné jediné věci.|300|pouta_postel!",
    "Poruč mu, ať tě poslouchá na slovo, a pak buď hodně konkrétní.|300|ona_nahore",
    "Přesně tak: Popiš mu přesně, jak má ležet, a oprav každou odchylku. Cíl: ať to sedí na centimetr.|300|pouta_postel!",
    "Spoutej ho a nech ho čekat, zatímco si dáváš na čas.|240|pouta_postel!",
    "Sváž mu ruce nad hlavou a kouři mu tak dlouho, dokud neprosí.|300|pouta_postel!",
    "Spoutej ho a pak ho polib, jako by se nic nedělo.|240|pouta_postel!",
    "Sváž mu jednu ruku a druhou nech volnou. Ať si vybere, co s ní.|300|pouta_postel!",
    "Poruč mu, ať klečí, a řekni mu, že dneska rozhoduješ ty.|300|klek_pouta!",
    "Jedno slovo a konec: Dohodněte se na slově, po kterém všechno okamžitě skončí, a pak jdi až na hranu. Cíl: nikdy ho neslyšet.|300|pouta_postel!",
    "Spoutej ho a mezi tím mu přejížděj ledem po celém těle.|300|pouta_postel!",
    "Sváž mu ruce a nech ho stát u zdi zády k tobě.|240|zed",
    "Spoutej ho a nech ho ležet nahého, zatímco se jen díváš.|240|pouta_postel!",
    "Poruč mu, ať ti řekne nahlas tři věci, které dneska udělá.|240|klek_pouta!",
    "Sváž mu ruce a doveď ho na hranu pětkrát za sebou.|300|pouta_postel!",
    "Spoutej ho a nech ho celou dobu mluvit, co cítí.|300|pouta_postel!",
    "Poslední rozkaz: Dej mu jeden poslední rozkaz a nech ho splnit beze slov. Cíl: nemuset nic vysvětlovat.|240|klek_pouta!",
    "Sváž mu ruce a pak mu sundej pouta, ale on se pořád nesmí hýbat.|300|pouta_postel!",
    "Spoutej ho a pak ho obejmi. Kontrast, který funguje.|180|pouta_postel!",
    "Na konec mu rozvaž ruce a promasíruj mu zápěstí.|120|pouta_postel!",
  ],
});
