// Kategorie 5 – Hardcore (dávka d)
// Témata: odpírání orgasmu, vynucené orgasmy, přestimulace, výdrž a výměna moci.
window.CATEGORIES = window.CATEGORIES || [];
CATEGORIES.push({
  id: 5,

  male: [
    "Pětkrát na hranu: Doveď ji na hranu pětkrát za sebou a pokaždé přestaň. Cíl: teprve napošesté ji nechat dojít.|300|pouta_postel",
    "Deset hran: Dnes se dostane na hranu desetkrát, než jí to dovolíš. Ona počítá nahlas. Cíl: dojít do deseti.|300|pouta_postel",
    "Zákaz na celou kartu: Zakaž jí dojít po celou dobu téhle karty, ať děláš cokoli. Cíl: pět minut a ani jednou nepolevit.|300|pouta_postel",
    "Prosba bez výsledku: Nech ji prosit o dovolení celou větou a pak jí ho odepři. Cíl: tři prosby a všechny odmítnout.|300|klek_pouta",
    "Přizná se a přestáváš: Dráždi ji a pokaždé, když řekne, že už to přijde, přestaneš. Cíl: čtyři takové pauzy za pět minut.|300|deprivace",
    "Jen jednou za večer: Oznam jí, že dneska dojde jen jednou, a ať si rozmyslí kdy. Cíl: nechat rozhodnutí úplně na ní a dodržet ho.|300|misionar",
    "Minuta bez doteku: Doveď ji na hranu a pak ji nech celou minutu ležet bez jediného doteku. Cíl: vydržet, ať prosí, jak chce.|300|pouta_postel",
    "Po žádosti: Musí tě požádat třikrát, pokaždé jinými slovy. Teprve potřetí to dostane. Cíl: tři různé prosby.|300|klek_pouta",
    "Až se jí třesou nohy: Drž ji na hraně a nepusť ji dál. Cíl: nepřestat, dokud se jí nezačnou třást nohy.|300|pouta_postel",
    "Pět a dvacet: Prsti jí kundičku pět vteřin naplno a pak dvacet vteřin nic. Cíl: deset kol a ani jednou čas nesplést.|300|vedle_ona_lezi",
    "Odtáhnout těsně před: Dráždi ji vibrátorem a vždycky ho odtáhni těsně před koncem. Cíl: pět takových zastavení.|300|pouta_postel",
    "Tři nástroje, tři hrany: Doveď ji na hranu ústy, pak rukou, pak vibrátorem a pokaždé přestaň. Cíl: teprve počtvrté ji nechat dojít.|300|oral_klek",
    "Tři cesty na hranu: Jazykem, prsty a vibrátorem. Po každé úplné zastavení. Cíl: tři různá zastavení.|300|oral_klek",
    "Pokračovat po konci: Nech ji dojít a hned jemně pokračuj dál. Cíl: půl minuty přestimulace – a na stop hned přestat.|300|pouta_postel",
    "Půl minuty navíc: Po jejím orgasmu nepřestávej ještě celých třicet vteřin. Cíl: vydržet do konce, pokud neřekne stop.|300|oral_klek",
    "Přestimulace: Po prvním vrcholu ji lízej dál, dokud neřekne stop slovo nebo dost. Cíl: vydržet oba.|300|pouta_postel",
    "Dva bez pauzy: Doveď ji ke dvěma orgasmům za sebou. Cíl: mezi nimi nesmí být pauza delší než deset vteřin.|300|pouta_postel",
    "Tři různé konce: Doveď ji ke třem orgasmům a každý jiným způsobem – rukou, ústy a vibrátorem. Cíl: žádný způsob dvakrát.|300|pouta_postel",
    "Třikrát a pokaždé jinak: Nech ji dojít třikrát – jednou rukou, jednou ústy a jednou vibrátorem. Cíl: pořadí si vybere ona.|300|pouta_postel",
    "Vynucená série: Dneska nesmí přestat, dokud nedojde třikrát. Mezi tím jen zpomalíš. Cíl: tři za sebou.|300|pouta_postel",
    "Kolik jich zvládne: Spoutej ji a nech ji dojít tolikrát, kolikrát to zvládne. Cíl: počítat je nahlas a přestat až na její stop.|300|pouta_postel",
    "Dvacet po orgasmu: Hned po orgasmu jí přilož vibrátor a počítej nahlas do dvaceti. Cíl: dojít k dvacítce, pokud neřekne stop.|300|pouta_postel",
    "Dokud tě neodstrčí: Po orgasmu ji lízej dál, hodně jemně. Cíl: nepřestat, dokud tě sama neodstrčí.|300|oral_klek",
    "Minuta a dost: Dej jí minutu na to, aby se udělala, a pomáhej jí, jak umíš. Cíl: když to nestihne, dneska už nic nebude.|60|vedle_ona_lezi",
    "Minuta a dost: Máš přesně šedesát vteřin. Pokud to nestihneš, karta je splněná bez konce. Cíl: stihnout to.|60|oral_klek",
    "Nejdřív za pět minut: Oznam jí, že nesmí dojít dřív než za pět minut, a dělej všechno pro to, aby to nestihla. Cíl: dodržet čas na vteřinu.|300|misionar",
    "Nejpozději za dvě minuty: Oznam jí, že musí dojít do dvou minut, a nasaď tomu odpovídající tempo. Cíl: stihnout to.|120|oral_klek",
    "Výdrž na čas: Ona se snaží vydržet co nejdéle a ty ji prsti a dráždi vibrátorem pro opak. Cíl: rozhodnout to do tří minut.|180|vedle_ona_lezi",
    "Rychle, nebo pořádně: Nech ji vybrat, jestli ji máš mrdat rychle teď, nebo pořádně deset minut. Cíl: dodržet její volbu do puntíku.|300|misionar",
    "Dvě minuty na prosby: Nech ji spoutanou klečet a kouřit ti, dvě minuty smí mezitím prosit. Cíl: potom už každé slovo ignorovat.|300|klek_pouta",
    "Odpočítává si výdrž: Lízej ji a nech ji nahlas říkat, kolik vteřin ještě vydrží. Cíl: pokaždé, když číslo řekne, o pět vteřin ho přidat.|300|pouta_postel",
    "Minutu ona, minutu ty: V devětašedesátce se po minutě střídejte, kdo koho lízá. Cíl: kdo se první udělá, plní ještě jeden úkol navíc.|300|p69",
    "Souboj o výdrž: Oba zároveň a kdo první dojde, splní druhému přání. Cíl: vydržet déle.|300|p69",
    "Výměna po minutě: Mrdejte se vsedě a po každé minutě si prohoďte, kdo z vás poroučí. Cíl: pět výměn a ani jednou se nepřerušit.|300|kontrola_vsede!",
    "Půl na půl beze slov: První polovinu rozhoduješ ty, druhou ona – a ani jeden z vás nesmí promluvit. Cíl: předat vedení jen pohledem.|300|kontrola_vsede!",
    "Předání uprostřed: První polovinu přirážej ty zespodu a v půlce nech jezdit ji. Cíl: nevzít si vedení zpátky, ať se ti chce, jak chce.|300|ona_nahore",
    "Výměna moci: Domluvte si signál, po kterém si okamžitě vyměníte role. Použijte ho třikrát. Cíl: tři výměny.|300|kontrola_vsede!",
    "Její volba role: Nech ji rozhodnout, jestli dneska poroučí, nebo klečí a kouří ti. Cíl: držet se její volby až do konce úrovně.|300|klek_pouta",
    "Právo zastavit: Lízej jí kundičku a dej jí právo tě kdykoli zastavit, ať ho použije. Cíl: aspoň třikrát tě zastaví a ty hned poslechneš.|300|pouta_postel",
    "Dneska velí ona: Nech ji nasadit se na tebe a rozhodovat dneska o všem. Cíl: pět minut a ani jednou jí do toho nemluvit.|300|ona_nahore",
    "Ztratit přehled o čase: Zavaž jí oči a dráždi ji vibrátorem v nepravidelných intervalech. Cíl: nepřestat, dokud netipne čas vedle o dvě minuty.|300|deprivace",
    "Neví, kdy konec: Zavaž jí oči, dráždi ji vibrátorem a nikdy jí neprozraď, kolik zbývá. Cíl: pět minut a ani jednou jí neodpovědět.|300|deprivace",
    "Slepé odpírání: Se zavázanýma očima ji drž na hraně tak dlouho, jak vydržíš ty. Cíl: pět minut.|300|deprivace",
    "Dráždi ji a vždycky, když se zhluboka nadechne, přestaneš.|300|pouta_postel",
    "Nech ji na hraně a mezitím jí šeptej, co uděláš, až jí to dovolíš.|300|pouta_postel",
    "Doveď ji na hranu a pak ji nech ležet a jen se dívej.|300|pouta_postel",
    "Řekni jí, že dovolení dostane, až ti řekne tři sprosté věty.|300|klek_pouta",
    "Cena za dovolení: Za každé svolení musí něco splnit. Tři úkoly, tři svolení. Cíl: projít všechny tři.|300|klek_pouta",
    "Nech ji dojít a hned ji vezmi zezadu, než se stihne vzpamatovat.|300|zezadu",
    "Po jejím orgasmu pokračuj v milování, ale úplně pomalu.|300|misionar",
    "Nech ji dojít v jedné poloze a hned ji převrať do jiné.|300|zezadu",
    "Tři polohy, tři hrany: Doveď ji na hranu ve třech různých polohách a pokaždé přestaň. Cíl: teprve ve čtvrté ji nechat dojít.|300|zezadu",
    "Nech ji dojít a pak jí dej dvě minuty klidu. Pak zase.|300|pouta_postel",
    "Přestávka mezi vlnami: Dvě minuty naplno, dvě minuty úplný klid, a znovu. Cíl: tři vlny.|300|vedle_ona_lezi",
    "Dráždi ji tak dlouho, až ti sama řekne, že už nemůže.|300|pouta_postel",
    "Řekni jí, že když se udělá bez dovolení, dostane deset ran.|300|predklon",
    "Jedno dlouhé, nebo tři krátká: Nech ji vybrat mezi jedním dlouhým lízáním a třemi krátkými koly s vibrátorem. Cíl: dodržet její volbu.|300|vedle_ona_lezi",
    "Dráždi ji, ale pokaždé jinak, ať si nezvykne.|300|vedle_ona_lezi",
    "Nikdy dvakrát stejně: Každých třicet vteřin změň, čím ji dráždíš – prst, jazyk, vibrátor, dlaň. Cíl: deset různých způsobů bez opakování.|300|vedle_ona_lezi",
    "Dej jí vibrátor a řekni, že ho smí použít, až ti to dovolíš.|300|pouta_postel",
    "Nech ji držet vibrátor u sebe, ale zapnout ho smí až na povel.|300|pouta_postel",
    "Dráždi ji a nech ji říkat čísla od jedné do desíti podle toho, jak blízko je.|300|pouta_postel",
    "Na desítce stop: Lízej ji a jakmile řekne devět, okamžitě přestaneš. Cíl: pět takových kol a nikdy ji nenechat dojít na desítku.|300|pouta_postel",
    "Nech ji dojít a hned pokračuj, ale jen prsty.|300|vedle_ona_lezi",
    "Doveď ji na hranu a pak ji nech, ať se dodělá sama.|300|vedle_ona_lezi",
    "Nech ji dojít, aniž by ses jí dotkl. Jen slovy.|300",
    "Jen hlasem: Doveď ji tam jen tím, co říkáš. Ani jeden dotek. Cíl: dokázat to.|300",
    "Deset minut za přání: Spoutej ji, prsti jí kundičku a řekni jí, že když vydrží deset minut, splníš jí jakékoli přání. Cíl: nepolevit ani na chvíli.|300|pouta_postel",
    "Nová poloha do konce: Vyberte spolu polohu, kterou jste nikdy nezkusili, a v ní ji mrdej až do konce. Cíl: nezměnit ji, ani když bude nezvyklá.|300|drep",
    "Doveď ji na hranu a pak ji polib a nech to být.|300|pouta_postel",
    "Nech ji dojít a pak ji drž, dokud se nezklidní.|300|lzicka",
    "Konec s péčí: Po poslední vlně ji přestaň dráždit, zabal do deky a chvíli jen drž. Cíl: tři minuty a nevynechat to.|180|lzicka",
    "Dráždi ji pomalu tak dlouho, až ztratí trpělivost.|300|vedle_ona_lezi",
    "Dokud to nezakáže: Drž ji na hraně a nepouštěj ji dál. Cíl: nepřestat, dokud ti to sama nezakáže nahlas.|300|pouta_postel",
    "Řekni jí, kolikrát dneska dojde, a to číslo dodrž.|300|pouta_postel",
    "Nech ji dojít, zatímco jí držíš ruce nad hlavou.|300|kontrola_vsede!",
    "Dráždi ji a pokaždé, když se pohne, začínáš od začátku.|300|pouta_postel",
    "Bez pohybu: Ona nesmí pohnout ani prstem. Každý pohyb vrací počítadlo na nulu. Cíl: dojít tak do konce.|300|pouta_postel",
    "Nech ji dojít třikrát a po každém se jí zeptej, jestli chce další.|300|pouta_postel",
    "Doveď ji na hranu a nech ji rozhodnout, jestli chce pokračovat.|300|pouta_postel",
    "Dráždi ji tak dlouho, dokud nezapomene, kde je.|300|deprivace",
    "Nech ji dojít, ale až po tom, co se ti podívá do očí a řekne to nahlas.|300|kontrola_vsede!",
    "Poslední svolení: Prsti ji a ona čeká na jediné slovo od tebe – neřekni ho dřív než na konci. Cíl: načasovat to přesně.|300|pouta_postel",
    "Nech ji dojít a hned potom ji jen tiše obejmi.|180|lzicka",
  ],

  female: [
    "Pět hran za sebou: Doveď ho na hranu pětkrát za sebou a pokaždé přestaň. Cíl: teprve napošesté ho nechat dojít.|300|pouta_postel!",
    "Deset hran: Dneska se dostane na hranu desetkrát, než mu to dovolíš. On počítá nahlas. Cíl: dojít do deseti.|300|pouta_postel!",
    "Zákaz na celou kartu pro něj: Zakaž mu se udělat po celou dobu téhle karty, ať děláš cokoli. Cíl: pět minut a ani jednou nepolevit.|300|pouta_postel!",
    "Prosba nadarmo: Nech ho prosit o dovolení celou větou a pak mu ho odepři. Cíl: tři prosby a všechny odmítnout.|300|klek_pouta!",
    "Přizná se a je konec: Dráždi ho a pokaždé, když řekne, že už to přijde, přestaneš. Cíl: čtyři takové pauzy za pět minut.|300|deprivace!",
    "Jen jeden konec: Oznam mu, že dneska dojde jen jednou, a ať si rozmyslí kdy. Cíl: nechat rozhodnutí na něm a dodržet ho.|300|ona_nahore",
    "Minuta bez jediného doteku: Doveď ho na hranu a pak ho nech celou minutu ležet bez doteku. Cíl: vydržet, ať prosí, jak chce.|300|pouta_postel!",
    "Třikrát a jinak: Požádat tě musí třikrát a pokaždé jinými slovy, jinak nedostane nic. Cíl: tři různé prosby.|300|klek_pouta",
    "Až se mu třesou nohy: Drž ho na hraně a nepusť ho dál. Cíl: nepřestat, dokud se mu nezačnou třást nohy.|300|pouta_postel!",
    "Pět naplno, dvacet nic: Hoň mu péro pět vteřin naplno a pak dvacet vteřin nic. Cíl: deset kol a ani jednou čas nesplést.|300|vedle_on_lezi",
    "Vibrátor pryč včas: Dráždi ho vibrátorem a vždycky ho odtáhni těsně před koncem. Cíl: pět takových zastavení.|300|pouta_postel!",
    "Tři způsoby, tři hrany: Doveď ho na hranu ústy, pak rukou, pak vibrátorem a pokaždé přestaň. Cíl: teprve počtvrté ho nechat dojít.|300|oral_on_vleze",
    "Tři cesty na hranu: Jazykem, rukou a vibrátorem. Po každé úplné zastavení. Cíl: tři různá zastavení.|300|oral_on_vleze",
    "Po konci ještě chvíli: Nech ho dojít a hned jemně pokračuj dál. Cíl: půl minuty přestimulace – a na stop hned přestat.|300|pouta_postel!",
    "Třicet vteřin navíc: Po jeho vyvrcholení nepřestávej ještě celých třicet vteřin. Cíl: vydržet do konce, pokud neřekne stop.|300|oral_on_vleze",
    "Přestimulace: Po prvním konci mu hoň dál, dokud neřekne stop slovo nebo dost. Cíl: vydržet oba.|300|pouta_postel!",
    "Až ztratí řeč: Doveď ho na hranu a drž ho tam. Cíl: nepřestat, dokud nedokáže souvisle mluvit.|300|pouta_postel!",
    "Na hraně snesitelnosti: Nech ho dojít a pak se ho ještě chvíli jemně dotýkej. Cíl: dvacet vteřin – a na stop hned přestat.|300|pouta_postel!",
    "Dvakrát a potřetí ano: Doveď ho dvakrát na hranu a pokaždé přestaň. Cíl: teprve potřetí ho nechat dojít.|300|pouta_postel!",
    "Vynucený konec: Kuř mu a hoň mu a on se nesmí udělat, dokud mu to po deseti minutách nedovolíš. Cíl: vydržet oba.|300|pouta_postel!",
    "Bez jediného pohybu: Spoutej ho a doveď ho na konec, aniž by se mohl hýbat. Cíl: pět minut a na stop ho hned odemknout.|300|pouta_postel!",
    "Dvacet po jeho konci: Hned po jeho konci mu přilož vibrátor a počítej nahlas do dvaceti. Cíl: dojít k dvacítce, pokud neřekne stop.|300|pouta_postel!",
    "Dokud tě neodstrčí on: Po jeho konci mu kuř dál, hodně jemně. Cíl: nepřestat, dokud tě sám neodstrčí.|300|oral_on_vleze",
    "Minuta pro něj: Dej mu minutu na to, aby se udělal, a pomáhej mu, jak umíš. Cíl: když to nestihne, dneska už nic nebude.|60|vedle_on_lezi",
    "Šedesát vteřin: Tolik času máš, a když to nestihneš, karta končí bez odměny. Cíl: stihnout to.|60|oral_on_vleze",
    "Dřív než za pět minut ne: Jezdi na něm a oznam mu, že se nesmí udělat dřív než za pět minut. Dělej všechno pro to, aby to nestihl.|300|ona_nahore",
    "Do dvou minut: Kuř mu péro tak, aby se udělal do dvou minut, a nasaď tomu odpovídající tempo. Cíl: stihnout to.|120|oral_on_vleze",
    "Výdrž na čas: On se snaží vydržet co nejdéle a ty mu honíš a kouříš pro opak. Cíl: rozhodnout to do tří minut.|180|vedle_on_lezi",
    "Rychle, nebo za deset minut: Nech ho vybrat, jestli na něm máš jezdit rychle teď, nebo pořádně deset minut. Cíl: dodržet jeho volbu.|300|ona_nahore",
    "Okno na prosby: Nech ho spoutaného klečet a hoň mu, dvě minuty smí mezitím prosit. Cíl: potom už každé slovo ignorovat.|300|klek_pouta!",
    "Počítá si výdrž: Kuř mu péro a nech ho nahlas říkat, kolik vteřin ještě vydrží. Cíl: pokaždé, když číslo řekne, o pět vteřin ho přidat.|300|pouta_postel!",
    "Minutu on, minutu ty: V devětašedesátce se po minutě střídejte, kdo koho olizuje. Cíl: kdo se první udělá, plní ještě jeden úkol navíc.|300|p69",
    "Kdo dřív prohrál: Užívejte si zároveň a ten, kdo dojde první, plní přání toho druhého. Cíl: vydržet déle.|300|p69",
    "Rozkazy po minutě: Mrdejte se vsedě a po každé minutě si vyměňte, kdo z vás rozkazuje. Cíl: pět výměn a ani jednou se nepřerušit.|300|kontrola_vsede",
    "Půlka pro každého: První polovinu rozhoduješ ty, druhou on – a ani jeden z vás nesmí promluvit. Cíl: předat vedení jen pohledem.|300|kontrola_vsede",
    "Převezme to on: Veď to první polovinu a přesně v půlce nech kontrolu převzít jeho. Cíl: nevzít si ji zpátky, ať se ti chce, jak chce.|300|zezadu!",
    "Signál k výměně: Dohodněte se na znamení, po kterém si hned prohodíte role, a použijte ho třikrát. Cíl: tři výměny.|300|kontrola_vsede",
    "Jeho volba role: Nech ho rozhodnout, jestli dneska poroučí, nebo klečí spoutaný a ty mu honíš. Cíl: držet se jeho volby do konce úrovně.|300|klek_pouta!",
    "Smí tě zastavit: Kuř mu a dej mu právo tě kdykoli zastavit, ať ho použije. Cíl: aspoň třikrát tě zastaví a ty hned poslechneš.|300|pouta_postel",
    "Dneska velí on: Nech ho vniknout do tebe zezadu a rozhodovat dneska o všem. Cíl: pět minut a ani jednou mu do toho nemluvit.|300|zezadu!",
    "Dráždi ho vibrátorem tak dlouho, dokud neztratí přehled o čase.|300|deprivace!",
    "Neví, kdy konec: Zavaž mu oči, hoň mu péro a nikdy mu neprozraď, kolik zbývá. Cíl: pět minut a ani jednou mu neodpovědět.|300|deprivace!",
    "Slepé odpírání: Se zavázanýma očima ho drž na hraně tak dlouho, jak vydržíš ty. Cíl: pět minut.|300|deprivace!",
    "Dráždi ho a vždycky, když se zhluboka nadechne, přestaneš.|300|pouta_postel!",
    "Nech ho na hraně a mezitím mu šeptej, co uděláš, až mu to dovolíš.|300|pouta_postel!",
    "Doveď ho na hranu a pak ho nech ležet a jen se dívej.|300|pouta_postel!",
    "Řekni mu, že dovolení dostane, až ti řekne tři sprosté věty.|300|klek_pouta!",
    "Něco za něco: Každé svolení si musí vykoupit splněným úkolem. Tři a tři. Cíl: projít všechny tři.|300|klek_pouta!",
    "Nech ho dojít a hned si na něj sedni, než se stihne vzpamatovat.|300|ona_nahore",
    "Po jeho konci pokračuj v milování, ale úplně pomalu.|300|ona_nahore",
    "Nech ho dojít v jedné poloze a hned ho převrať do jiné.|300|zezadu!",
    "Tři polohy a tři hrany: Doveď ho na hranu ve třech různých polohách a pokaždé přestaň. Cíl: teprve ve čtvrté ho nechat dojít.|300|zezadu!",
    "Nech ho dojít a pak mu dej dvě minuty klidu. Pak zase.|300|pouta_postel!",
    "Vlna a klid: Dvě minuty naplno, dvě minuty naprostý klid, a zase od začátku. Cíl: tři vlny.|300|vedle_on_lezi",
    "Dráždi ho tak dlouho, až ti sám řekne, že už nemůže.|300|pouta_postel!",
    "Řekni mu, že když se udělá bez dovolení, dostane deset ran.|300|predklon!",
    "Jedno dlouhé, nebo tři krátká: Nech ho vybrat mezi jedním dlouhým kouřením a třemi krátkými koly rukou. Cíl: dodržet jeho volbu.|300|vedle_on_lezi",
    "Dráždi ho, ale pokaždé jinak, ať si nezvykne.|300|vedle_on_lezi",
    "Pokaždé jinak: Každých třicet vteřin změň, čím ho dráždíš – ruka, ústa, jazyk, vibrátor. Cíl: deset různých způsobů bez opakování.|300|vedle_on_lezi",
    "Dej mu vibrátor a řekni, že ho smí použít, až mu to dovolíš.|300|pouta_postel!",
    "Nech ho držet vibrátor u sebe, ale zapnout ho smí až na povel.|300|pouta_postel!",
    "Dráždi ho a nech ho říkat čísla od jedné do desíti podle toho, jak blízko je.|300|pouta_postel!",
    "Devítka je konec: Jakmile vysloví devítku, okamžitě zastavíš. Pětkrát za sebou. Cíl: nikdy nedojít na desítku.|300|pouta_postel!",
    "Nech ho dojít a hned pokračuj, ale jen rukou.|300|vedle_on_lezi",
    "Doveď ho na hranu a pak ho nech, ať se dodělá sám.|300|vedle_on_lezi",
    "Nech ho dojít, aniž by ses ho dotkla. Jen slovy.|300",
    "Jen hlasem: Doveď ho tam jen tím, co říkáš. Ani jeden dotek. Cíl: dokázat to.|300",
    "Deset minut za přání: Spoutej ho, hoň mu a řekni mu, že když vydrží deset minut, splníš mu jakékoli přání. Cíl: nepolevit ani na chvíli.|300|pouta_postel!",
    "Nová poloha do konce: Vyberte spolu polohu, kterou jste nikdy nezkusili, a v ní na něm jezdi až do konce. Cíl: nezměnit ji, ani když bude nezvyklá.|300|drep",
    "Doveď ho na hranu a pak ho polib a nech to být.|300|pouta_postel!",
    "Nech ho dojít a pak ho drž, dokud se nezklidní.|300|lzicka",
    "Konec s péčí: Po poslední vlně ho přestaň dráždit, zabal do deky a chvíli jen drž. Cíl: tři minuty a nevynechat to.|180|lzicka",
    "Dráždi ho pomalu tak dlouho, až ztratí trpělivost.|300|vedle_on_lezi",
    "Dokud nezakáže on: Drž ho na hraně a nepouštěj ho dál. Cíl: nepřestat, dokud ti to sám nezakáže nahlas.|300|pouta_postel!",
    "Řekni mu, kolikrát dneska dojde, a to číslo dodrž.|300|pouta_postel!",
    "Nech ho dojít, zatímco mu držíš ruce nad hlavou.|300|kontrola_vsede",
    "Dráždi ho a pokaždé, když se pohne, začínáš od začátku.|300|pouta_postel!",
    "Bez pohybu: On nesmí pohnout ani prstem. Každý pohyb vrací počítadlo na nulu. Cíl: dojít tak do konce.|300|pouta_postel!",
    "Nech ho dojít a pak se ho zeptej, jestli chce ještě.|300|pouta_postel!",
    "Doveď ho na hranu a nech ho rozhodnout, jestli chce pokračovat.|300|pouta_postel!",
    "Dráždi ho tak dlouho, dokud nezapomene, kde je.|300|deprivace!",
    "Nech ho dojít, ale až po tom, co se ti podívá do očí a řekne to nahlas.|300|kontrola_vsede",
    "Poslední svolení: Hoň mu péro a on čeká na jediné slovo od tebe – neřekni ho dřív než na konci. Cíl: načasovat to přesně.|300|pouta_postel",
    "Nech ho dojít a hned potom ho jen tiše obejmi.|180|lzicka",
  ],
});
